### ISSUE TITLE
Enhancement: Safe restore

### ISSUE THREAD

**Issue by slopp** [rstudio/renv#10]
Perhaps this could be outsourced to remotes or the `pak` package, but I think it'd be really nice if the restore was atomic; either the environment/snapshot gets restored completely or nothing changes.

One of packrat's most frustrating attributes was semi-restored environments

**Comment by kevinushey** [comment]
Implemented today with https://github.com/rstudio/renv/commit/3dda6e101fe266d6bf3a84240dae1764acf10be4. Now, if `restore()` fails for some reason, the library will not be mutated.

Still need to think about if and how we should make this configurable.

**Comment by kevinushey** [comment]
I don't think we need to make this configurable -- it makes more sense to have these operations be atomic, and even when they do fail the "good" packages still get installed into the cache (so their installation is still quick in the future).

**Comment by krlmlr** [comment]
Are restores still atomic? I remember seeing a partial restore recently when installation of one package failed.

**Comment by kevinushey** [comment]
Restores should still be atomic by default -- I just tested locally and this seems to still be the case.

```
> renv::restore(rebuild = TRUE)
The following package(s) will be updated:

# CRAN ===============================
- digest   [* -> 0.6.27]

# GitHub =============================
- broken   [* -> kevinushey/broken]

Do you want to proceed? [y/N]: y
Retrieving 'https://api.github.com/repos/kevinushey/broken/tarball/c6961b81754549e71e7fcd0ade3391771cc52e82' ...
        OK [file is up to date]
* Querying repositories for available binary packages ... Done!
Retrieving 'https://cran.rstudio.com/bin/macosx/contrib/4.0/digest_0.6.27.tgz' ...
        OK [file is up to date]
Installing digest [0.6.27] ...
        OK [installed binary]
Installing broken [0.1.0] ...
        FAILED
Error installing package 'broken':
==================================

* installing *source* package ‘broken’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
No man pages found in package  ‘broken’
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘broken’:
 .onLoad failed in loadNamespace() for 'broken', details:
  call: fun(libname, pkgname)
  error: oh no!
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/kevinushey/scratch/blooper/renv/staging/1/broken’
Error: install of package 'broken' failed
Traceback (most recent calls last):
14: renv::restore(rebuild = TRUE)
13: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
12: renv_install(records, library)
11: renv_install_staged(records, library)
10: renv_install_default(records, library)
 9: handler(package, renv_install_impl(record))
 8: renv_install_impl(record)
 7: withCallingHandlers(renv_install_package_local(record), error = function(e) {
        vwritef("\tFAILED")
        writef(e$output)
    })
 6: renv_install_package_local(record)
 5: renv_install_package_local_impl(package, path, library)
 4: r_cmd_install(package, path, library)
 3: r_exec(package, args, "install")
 2: r_exec_error(package, output, label)
 1: stop(error)
> list.files(.libPaths()[1])
[1] "renv"
> library(digest)
Error in library(digest) : there is no package called 'digest'
```

**Comment by krlmlr** [comment]
The log says that digest has been updated?

**Comment by krlmlr** [comment]
Oh, I see -- the `library()`  call fails.

**Comment by kevinushey** [comment]
Right -- it was successfully installed into an intermediate staging library, but we failed to install `broken` we don't copy over the packages from that staging library to the final library.

**Comment by krlmlr** [comment]
I saw the non-atomic restore with the following conditions:

- upgrading all packages to a more recent RSPM snapshot on one machine, snapshot, Git push, Git pull on other machine, restore
- option `renv.config.auto.snapshot` set to `TRUE`

**Comment by kevinushey** [comment]
I realize it's probably challenging, but is there any chance you would be able to share a reproducible example?

**Comment by krlmlr** [comment]
We're moving away from auto.snapshot, will keep an eye open if this occurs with manual snapshots.
