### ISSUE TITLE
Allow PAT environment variable to be specified for git2r repos

### ISSUE THREAD

**Issue by mstr3336** [rstudio/renv#100]
Hi, 
The project I develop for is hosted on a GitHub Enterprise server, and unfortunately, as a result, installing packages from git requires git2r, and for the user to supply credentials.
For a feature enhancement, I was wondering if in the lockfile, for git2r repos that may not be public-read, if a field that specifies the env variable holding a user's Personal Access Token might be supplied?
Really, that probably just looks like a few lines of code and maybe an extra parameter to a git2r call, and if that sounds like something you'd be happy with integrating, I can implement it (I'd find it really handy since I presently ignore the enterprise packages and then have my own hacky script that's responsible for maintaining them).
Let me know what you think :)

**Comment by mstr3336** [comment]
I implemented this in #101

**Comment by kevinushey** [comment]
It looks like there are a few ways to accomplish this:

1. Specify e.g. a `GIT_USER` and `GIT_PASSWORD`, and use those to set up a repository URL (e.g. `https://<user>@github.com/repo/user`), and then set `GIT_ASKPASS` to just echo `GIT_PASSWORD` for authentication.

2. For certain hosts (e.g. GitHub) it looks like we can just use a PAT directly, e.g. `https://<token>:x-oauth-basic@github.com/repo/user`.

We'll have to be careful that whatever scheme is chosen we don't accidentally leak the token (e.g. it looks like cloning with a URL like that can save the token in `.git/config`, which is suboptimal)

**Comment by mstr3336** [comment]
as per [my comment](https://github.com/rstudio/renv/pull/101#issuecomment-509844830)

> I like the sound of the
> ```r 
> options(renv.auth.git.MyPackage = function(record){})` 
> ```

Which could be called in .Rprofile, or in an auth script that .Rprofile could source  before sourcing `renv/activate.R`

> We'll have to be careful that whatever scheme is chosen we don't accidentally leak the token (e.g. it looks like cloning with a URL like that can save the token in `.git/config`, which is suboptimal)

I did want to check in re. this: 
When renv installs from git, how much cleanup does it do? Is the repository it clones deleted afterwards? 
If so, as long as the token is saved to the repos local config, how important is it that the token isn't saved before being deleted?

**Comment by kevinushey** [comment]
> When renv installs from git, how much cleanup does it do? Is the repository it clones deleted afterwards?

It is indeed deleted afterwards. We actually just fetch the branch of interest and build from that:

https://github.com/rstudio/renv/blob/708491c941550b0e9f5d1847234e47295d47f6e4/R/retrieve.R#L192-L198

I guess your point is that we don't have to worry about the token being saved, then -- and you're probably right :-)

**Comment by kevinushey** [comment]
I believe you should be able to accomplish what you need now with something like:

```
options(renv.auth.<package> = list(GIT_PAT = "<pat>"))
```

replacing, of course, `<package>` with your package name and `<pat>` with the associated token.

**Comment by mstr3336** [comment]
Yay! :) Thank you, Kevin.

Just re. your security concerns - I'd like to ask about the final mechanism of auth - Do we wind up sending a https payload with the username/pass encoded in the url? 

ie. `https://<username>:<password>`@url.git` ? 

Is that right? 
Or is the mechanism you described essentially to not encode the password in that url, but to to echo it using your `GIT_ASKPASS` mechanism when the git protocol requests it? 

Or somehow both? 

Also- I can't see how what you've described using options is implemented, however, I suspect that that might rest on some mechanism of renv scoping env vars on a per-package basis, maybe? 
I'm going to upgrade and give your mechanism a try- I might also run it by with a packet sniffer to check that passwords aren't being sent in the clear (I know it was my idea but I'm now feeling a little concerned about encoding a password in a url - for the use case of PATs (At least within my org) it's less critical, at least for my project, but I could see it being a security liability for the average user who may not be aware of the mechanics) 

Thank you!

**Comment by kevinushey** [comment]
> Just re. your security concerns - I'd like to ask about the final mechanism of auth - Do we wind up sending a https payload with the username/pass encoded in the url?

I just realized that the GIT_ASKPASS script can be used to provide both the username + password, so we no longer try to munge the URL (so there's no risk of credentials being seen in the URL; e.g. if someone were to inspect the process tree with `ps aux`). The same script provides the username and password as read from `GIT_USER` / `GIT_USERNAME` and `GIT_PASS` / `GIT_PASSWORD`.

> Also- I can't see how what you've described using options is implemented, however, I suspect that that might rest on some mechanism of renv scoping env vars on a per-package basis, maybe?

I've just updated `renv` on master now to make sure this is properly handled as well.
