### ISSUE TITLE
Same package installed from different repos leads to spurious lockfile changes

### ISSUE THREAD

**Issue by zkamvar** [rstudio/renv#1001]
## Problem

I often end up with diffs that look like this where the only thing that changes is the repository and some metadata: 

```diff
diff --git a/renv/profiles/lesson-requirements/renv.lock b/renv/profiles/lesson-requirements/renv.lock
index 1d33a23..83d704c 100644
--- a/renv/profiles/lesson-requirements/renv.lock
+++ b/renv/profiles/lesson-requirements/renv.lock
@@ -132,7 +132,7 @@
       "Package": "knitr",
       "Version": "1.39",
       "Source": "Repository",
-      "Repository": "CRAN",
+      "Repository": "RSPM",
       "Hash": "029ab7c4badd3cf8af69016b2ba27493",
       "Requirements": [
         "evaluate",
@@ -162,7 +162,7 @@
       "Package": "renv",
       "Version": "0.15.4",
       "Source": "Repository",
-      "Repository": "CRAN",
+      "Repository": "RSPM",
       "Hash": "c1078316e1d4f70275fc1ea60c0bc431",
       "Requirements": []
     },
@@ -178,7 +178,7 @@
       "Package": "rmarkdown",
       "Version": "2.14",
       "Source": "Repository",
-      "Repository": "CRAN",
+      "Repository": "RSPM",
       "Hash": "31b60a882fabfabf6785b8599ffeb8ba",
       "Requirements": [
         "bslib",
@@ -211,10 +211,7 @@
       "Package": "stringi",
       "Version": "1.7.6",
       "Source": "Repository",
-      "Repository": "https://carpentries.r-universe.dev",
-      "RemoteUrl": "https://github.com/gagolews/stringi",
-      "RemoteRef": "v1.7.6",
-      "RemoteSha": "1a1b5115884cd68650915bb1a8ad893ee4d3f4c6",
+      "Repository": "CRAN",
       "Hash": "bba431031d30789535745a9627ac9271",
       "Requirements": []
     },

```

This occurs if I change machines or work with collaborators and I'm wondering if there is a way to add an option that would prevent the modification of a lockfile entry if the hash of the package is identical? 

## Background

Somewhat related to #785, but I'm in a situation where we are trying to distribute projects that can be worked on without the user needing to know anything about {renv} or how it works. 

To achieve this, we have a function that uses a named project and runs a [`hydrate(); restore(); snapshot()` workflow](https://carpentries.github.io/sandpaper/articles/building-with-renv.html#motivation).

Here's an example of our problem: [this diff generated from a github action shows several packages where the only field changed is "Repository" from "CRAN" -> "RSPM"](https://github.com/carpentries/sandpaper-docs/commit/2edbea7d0843be6e839b7adb2953a693984cc6f6#diff-6e829793be5e3c69a05e6cd6cfdbb06dc108a8bfde1d1a36e9209b78d1850099).

A [subsequent commit two months later changed the "Repository" back from "RSPM" -> "CRAN"](https://github.com/carpentries/sandpaper-docs/commit/3f3c7bff6a14958c70922989c65c32b175376f91).

I believe that I could find a workaround for this by checking and modifying the lockfile post-snap, but I'm wondering if the solution could exist in {renv}.

**Comment by kevinushey** [comment]
I think there's a couple possible solutions here:

1. Stop encoding the "Repository" field into the lockfile entry, to avoid spurious diffs of this form. The downside here is we'd lose the "preferred" repository behavior when attempting to restore a package that's available from multiple repositories.

2. If the lockfile entries only differ in their `Repository` field, then just leave it alone. It looks like we already try to do this here: https://github.com/rstudio/renv/blob/81fecb07fcc78cabb61b5309875e59484727b090/R/lockfile-write.R#L27-L37

**Comment by zkamvar** [comment]
The second option is definitely the preferred one!

**Comment by kevinushey** [comment]
I believe this may already be resolved in the development version of `renv`? If not, let's fix if straightforward; otherwise punt for a future release.

**Comment by hadley** [comment]
Given that there isn't a reprex, and you think it's fixed, I think it's ok to close.
