### ISSUE TITLE
Remote parsing for git URLs fails with number in URL

### ISSUE THREAD

**Issue by arcresu** [rstudio/renv#1004]
`renv_remotes_parse_git` works on URLs like this one:

``` r
renv:::renv_remotes_parse_git("git@github.com:rstudio/renv")
#> $spec
#> [1] "git@github.com:rstudio/renv"
#> 
#> (etc...)
```

but as soon as there's a number in the username part of the URL it chokes:

``` r
renv:::renv_remotes_parse_git("git@github.com:rstudio1/renv")
#> Error: 'git@github.com:rstudio1/renv' is not a valid remote
```

This is stopping me from cloning a repository on an enterprise installation of GitHub where my username has a number in it.

Numbers are tolerated fine in the repo part (e.g. `git@github.com:rstudio/renv1` is fine) and indeed those parts of the regex are different patterns:

https://github.com/rstudio/renv/blob/35af08a635dde1d225cfe1a1c36cf61067d87ee3/R/remotes.R#L150-L165

I'm not sure if there's a general rule for what characters are allowed to appear in the username part, but at least the character range should be expanded from `"[/:]([-\\.a-zA-Z]+)"` to `"[/:]([-\\.a-zA-Z0-9]+)"` to reflect what's possible on GHE.

**Comment by kevinushey** [comment]
Thanks for the bug report! This should now be resolved in the development version of `renv`.
