### ISSUE TITLE
renv is attempting to write to R site-library folder

### ISSUE THREAD

**Issue by chprasad** [rstudio/renv#1005]
I'm trying to build a docker image for running a shiny app, with all my dependencies pre-installed via `renv::restore()` from a `renv.lock` file. 

Docker build fails complaining that renv is unable to write to `/usr/local/lib/R/site-library`. My understanding is that `renv` should only be writing to project folder and never to system folders. Is that understanding incorrect?

Here is the error trace.

```
Installing phangorn [2.8.1] ...
	OK [installed binary]
Copying phangorn [2.8.1] into the cache ...
	OK [copied to cache in 15 milliseconds]
Installing immunarch [0.6.8] ...
	OK [built from source]
Copying immunarch [0.6.8] into the cache ...
	OK [copied to cache in 11 milliseconds]
cp -pPR '/tmp/RtmpHFagIC/renv-staging64269080/abind/' '/usr/local/lib/R/site-library/.renv-copy-62e6e470d'
================================================================================

cp: cannot create directory '/usr/local/lib/R/site-library/.renv-copy-62e6e470d': Permission denied
Error: could not copy / move file '/tmp/RtmpHFagIC/renv-staging64269080/abind' to '/usr/local/lib/R/site-library/abind'
move: cannot rename file '/tmp/RtmpHFagIC/renv-staging64269080/abind' to '/usr/local/lib/R/site-library/abind', reason 'Permission denied'
copy: error copying directory [error code 1]
In addition: Warning message:
In dir.create(rownames(info), recursive = TRUE) :
  cannot create dir '/usr/local/lib/R/site-library/.renv', reason 'Permission denied'
Traceback (most recent calls last):
10: renv::restore()
 9: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
 8: renv_install_impl(records)
 7: renv_install_staged(records)
 6: enumerate(targets, renv_file_move, overwrite = TRUE)
 5: lapply(idx, callback)
 4: FUN(X[[i]], ...)
 3: f(n[[i]], x[[i]], ...)
 2: stopf(text, source, target)
 1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
The command '/bin/sh -c cd /srv/shiny-server/app/ && Rscript -e 'renv::restore()'' returned a non-zero code: 1
```

Here is my Dockerfile.  
```
FROM rocker/shiny-verse:4.2.0

ENV RENV_VERSION 0.15.4-32
RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv@${RENV_VERSION}')"

RUN apt-get update && apt-get install -y libproj-dev python-is-python3 libglpk40 libgeos-c1v5
RUN rm -fr /srv/shiny-server/* && mkdir -p /srv/shiny-server/app/renv && chown -R shiny:shiny /srv/shiny-server/app

USER shiny
ENV RETICULATE_PYTHON /usr/bin/python
COPY renv.lock /srv/shiny-server/app/renv.lock
RUN cd /srv/shiny-server/app/ && Rscript -e 'renv::restore()'
```

**Comment by chprasad** [comment]
Activating renv before calling `renv::restore` fixed the problem.

```
COPY renv.lock /srv/shiny-server/app/
COPY activate.R settings.dcf /srv/shiny-server/app/renv/
COPY .Rprofile /home/shiny/
RUN cd /srv/shiny-server/app/ && Rscript -e 'renv::restore()'
```

If activation is mandatory, it should be documented in  the "Using renv with Docker" article.

**Comment by kevinushey** [comment]
It's not mandatory, but you do need to make sure the Docker container has been configured to use a writable library path. The easiest way to make that happen is (probably) to copy the activate script, so that the project library is automatically used by new R sessions in the Docker container.

I'll think about clarifying this further in the documentation.

**Comment by kevinushey** [comment]
What are the actual `.libPaths()` set to in that session?

**Comment by pat-s** [comment]
```r
> .libPaths()
[1] "/home/patrick/R/x86_64-pc-linux-gnu-library/4.1" "/opt/R/4.1.3/lib/R/library" 
```

I forgot to mention: this is outside of an {renv} project, i.e. I am calling `renv::hydrate()` to install project dependencies and aiming to make use of a shared renv cache.

**Comment by kevinushey** [comment]
Weird... I don't know what to make of that.

Are you able to try stepping through `renv::hydrate()` to see if / where the library path is being changed? E.g.

```
debug(renv::hydrate)
renv::hydrate()
```

**Comment by pat-s** [comment]
Jup, here are my findings:

callstack: `hydrate` -> `renv_hydrate_resolve_missing` -> `renv_install_impl` -> `renv_install_staged` -> `libpaths` -> `renv_libpaths_all()`

- `renv_libpaths_all()` reports only `"/opt/R/4.1.3/lib/R/library"`
- In `renv_install_staged()`, `.libPaths()` only reports the system lib
- In `renv_install_impl()`, `.libPaths()`  only reports the system lib
- `renv_scope_libpaths(libpaths)` in `renv_hydrate_resolve_missing()` (https://github.com/rstudio/renv/blob/main/R/hydrate.R#L279) removes the user lib from `.libPaths()` and only returns the system lib

**Comment by kevinushey** [comment]
But where does the change happen? `renv_libpaths_all()` just calls `.libPaths()`, so somewhere in that callstack it's getting changed.

You could also try something like:

```
trace(.libPaths, quote({
  if (!missing(new)) {
    writeLines(paste("[!] Updating libpaths:", new))
    print(rlang::trace_back())
  }
}), print = FALSE)
```

to see if you can find out where (and why) the library paths are changing.

**Comment by pat-s** [comment]
It's happening in https://github.com/rstudio/renv/blob/main/R/scope.R#L52. After that call, `.libPaths()` consists only of the system lib.

**Comment by kevinushey** [comment]
Thanks -- I think I see what the issue is. I'll take a look.

**Comment by kevinushey** [comment]
That said, this seems like an off-label usage of `renv::hydrate()` -- it's intended for use with project libraries, rather than user libraries.

**Comment by kevinushey** [comment]
I made a change in https://github.com/rstudio/renv/commit/4453f0778a87890d7f1f3af1115c0754a80a2537 that I think should help fix this issue -- are you able to give the development version of `renv` a spin?

**Comment by pat-s** [comment]
Thanks, Kevin! Works now as expected with 0.16.0-5 🥳

**Comment by kevinushey** [comment]
Awesome, glad to hear it!
