### ISSUE TITLE
Cache symlinks not being created

### ISSUE THREAD

**Issue by dfeinzeig** [rstudio/renv#1007]
Inside an ubuntu based docker container I'm installing R and using renv to manage global packages. I want to install packages from my renv.lock to `renv:::renv_libpaths_system()`. I want to use the cache to speed up build times and I want to use symlinks to the cache.

Here's what I'm doing:

- install R
- `mkdir /renv_cache` and copy cache from host into `/renv_cache`
- `ENV RENV_PATHS_CACHE /renv_cache`
- `R -e "renv::init(bare=TRUE, force=TRUE); options(renv.config.cache.symlinks = TRUE); renv::restore(prompt=FALSE, library=renv:::renv_libpaths_system(), lockfile='<path to lockfile>')"`

Here's what is happening:
- packages are being installed to `/opt/R/4.1.2/lib/R/library/` (expected and desired!)
- packages are being COPIED, not symlinked (not expected)

I'm not sure why the symlinks are not being created. Any suggestions?

**Comment by kevinushey** [comment]
This is where `renv` decides whether a package should be copied vs. symlinked into the target library path:

https://github.com/rstudio/renv/blob/3e6518f153e83ed647e9725514ebde6e16cc298b/R/cache.R#L572-L579

You might need to also set `options(renv.cache.linkable = TRUE)` to allow symlinks to be created even when not using a project library.

There should probably be an easier way to override this in general.

**Comment by dfeinzeig** [comment]
That was the missing piece. Thank you!
