### ISSUE TITLE
Enhancement: Add System Requirements to Lockfile

### ISSUE THREAD

**Issue by rfineman** [rstudio/renv#1010]
As a potential enhancement, thoughts on adding the system requirements / prerequisites for install to the lockfile? I figure the user can specify the os via the config function and at point of install, renv could either get the information from the DESCRIPTION file if provided or use the RSPM API.

Here's how a resulting lockfile might look:
```
{
	"R": {
		"Version": "4.2.0",
		"Repositories": [
			{
				"Name": "CRAN",
				"URL": "https://packagemanager.rstudio.com/all/latest"
			}
		]
	},
	"Packages": {
		"chromote": {
			"Package": "chromote",
			"Version": "0.1.0",
			"Source": "Repository",
			"Repository": "CRAN",
			"Hash": "785cfc65cd435cc7f7b0cef04e4cf77c",
			"Requirements": [
				"R6",
				"curl",
				"fastmap",
				"jsonlite",
				"later",
				"magrittr",
				"processx",
				"promises",
				"rlang",
				"websocket"
			],
			"SystemRequirements": [
				"ubuntu-20.04": {
					"apt-get install -y libcurl4-openssl-dev"
					"apt-get install -y libssl-dev"
					"apt-get install -y make"
					"[ $(which google-chrome) ] || apt-get install -y gnupg curl"
					"[ $(which google-chrome) ] || curl -fsSL -o /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
					"[ $(which google-chrome) ] || DEBIAN_FRONTEND='noninteractive' apt-get install -y /tmp/google-chrome.deb"
					"rm -f /tmp/google-chrome.deb"
				}
			]
		}
	}
}
```

**Comment by aalexandersson** [comment]
Disclaimer: I am just a regular user.

According to the [renv homepage](https://rstudio.github.io/renv/articles/renv.html), the planned future work for system requirements is with [sysreqsdb](https://github.com/r-hub/sysreqsdb). However sysreqsdb does not work yet on Windows. How might a lockfile with system requirements look for Windows?

**Comment by millerh1** [comment]
Could you use the RSPM API for this, similar to [`{{getsysreqs}}`](https://github.com/mdneuzerling/getsysreqs)?

**Comment by hadley** [comment]
This is currently out of scope for renv, but is something we may consider for the future.
