### ISSUE TITLE
Session crashes after loading certain packages in renv

### ISSUE THREAD

**Issue by csadagents** [rstudio/renv#1011]
Dear developers,
I have a little problem with my renv environments since my update to R 4.2.0 yesterday:
when I load the packages "xlsx" or "mailR" in an environment, the R session crashes. If I load the packages outside an environment, everything works fine. All other packages I use also work in my environments.

R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
renv: 0.15.4
RStudio: 2022.02.2 Build 485

best regards

**Comment by kevinushey** [comment]
Can you share the result of `renv::diagnostics()`? Also, does reinstalling those packages make any difference?

Do you see the same crash if you use R outside of RStudio (e.g. via RGui or R in a terminal)?
