### ISSUE TITLE
project restart slow when using the cellar

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#1014]
When I first started using `renv`, restarting my R Session was pretty snappy, like a non-renv-based R Project. I found that once I started using the cellar and adding more and more in-house tarballs to it, each restart was rather slow. I did some profiling (using RStudio's built-in profiler tools) and it seems that each time renv is activated (each restart), renv crawls through the cellar, untars each package, then extracts the package version/description. It seems to me this untar process is what is causing the significant slow-down. I have quite a few packages in my cellar, and some are over 100MB. Is there something that can be done here to avoid so many untar calls? Thanks for any input!

**Comment by kevinushey** [comment]
Thanks for the bug report! It looks like the issue here occurs because `renv` is trying to read the DESCRIPTION file from each package in the cellar, as part of building its "available packages" database.

I'll check and see if this requirement can be relaxed.

**Comment by kevinushey** [comment]
I've made some changes in the development version of `renv` that should alleviate this issue -- can you give it a shot and let me know how it works for you?

**Comment by hutch3232** [comment]
This is great, thank you! It is feeling much more responsive when I restart my R session. Haven't gotten to do thorough testing or benchmarking, but initial reaction is that it's a nice improvement. Thanks for addressing so quickly!

**Comment by McClellandLegge** [comment]
Thanks so much! Using `v0.15.5-7` resolved for us as well -- `renv::load` was taking ~130s and now under 2s.
