### ISSUE TITLE
0.15.3+ bug - Installs incorrect package when multiple packages in a github repo

### ISSUE THREAD

**Issue by tinoater** [rstudio/renv#1016]
I can't easily add a reprex as I discovered the issue on our private github repo.

We have a github repo with multiple R packages, each in it's own folder, like:

```
repo
└───package_a
    └────  R
           | code.R
           | ...
    │   DESCRIPTION
    |   NAMESPACE
    │
└───package_b
    └────  R
           | code.R
           | ...
    │   DESCRIPTION
    |   NAMESPACE
...
```

Before renv 0.15.3 I could run:

`renv::install('github_repo/r_package_name')`

to install a package from the repo. Since 0.15.3 `renv:::renv_install_package_unpack` unpacks the tarball, sees all the DESCRIPTION files for each package and then this line:
`descpath <- descpaths[n == min(n)]`
seems to take the DESCRIPTION with the shortest filepath. This means that when I ask for any package it actually selects the package with the shortest name. (This then leads to errors further in the installation).

`renv_install_package_unpack` knows which `package` it's looking for, could it pick the relevant `descpath` in the case there are many?

**Comment by kevinushey** [comment]
Do things work if you use an explicit sub-directory invocation, e.g.

```
renv::install("user/repo:package_b")
```

**Comment by kevinushey** [comment]
I've pushed a candidate fix that's now available in the development version of `renv`, if you're able to test.

**Comment by tinoater** [comment]
Thank you for the quick reply.

On 0.15.5 the `renv::install('user/repo:package_b')` syntax has the same issue.

On the development version of renv both syntax work, so this looks fixed to me!
