### ISSUE TITLE
Add a package manually

### ISSUE THREAD

**Issue by sgvignali** [rstudio/renv#1018]
Hi

first of all thank you for developing this package. I was wondering if there is a way to add manually a package.
I would like to add a package, including its dependencies, that is among the suggested ones. I am aware that you can do it by modifying the `settings.dcf` file, but this will add all the suggested packages and not only the one I need.

Is there a way to do that?

Thank you
Sergio

**Comment by sgvignali** [comment]
Thank you @kevinushey for the prompt response. Yes, I meant adding a package to the lockfile together with its required packages.

While `renv::record()` adds the desired package to the lockfile, it does not add its dependencies.
Moreover, if you call again `renv::snapshot()`, the package addedd with  `renv::record()` is removed.

This is an example with `data.table`. Assuming a newly create RStudio project:
```
renv::init()
renv::install("data.table")
```
Then in an R script:
```
# Create a comppressed csv file
tmp <- tempdir()
file <- file.path(tmp, "iris.csv.gz")

iris |> write.csv(
  file = gzfile(file),
  row.names = FALSE
)

# Read file
df <- data.table::fread(input = file)

```
This will fail because `data.table` requires `R.utils` to read compressed file, which is listed as suggested package: 

`renv::install("R.utils")` which works fine.

`renv::snapshot()` will add `data.table` but not `R.utils`. So, I could use `renv::record("R.utils)` to include it to the lockfile.
The last command includes `R.utils` but not `R.methodsS3 and R.oo` which are its requirements.

Moreover, if now I install `ggplot2` `renv::install("ggplot2")`, include the following in the R script:
```
library(ggplot2)
df |> ggplot(mapping = aes(x = Species, y = Sepal.Length, fill = Species)) +
  geom_boxplot()
```
and run again `renv::snapshot()`, `ggplo2` with all its dependencies will be included but `R.utils` will be removed.

Is there a better way to do this? I could modify the `settings.dcf` to install all the suggested packages, but this would apply to all installed packages, and in this case, for example, I would like to include only "R.utils" with its dependencies to the lockfile.

I hope it is clearer now.

**Comment by kevinushey** [comment]
If that's the case, I think the simplest fix is to just add a file called `deps.R` and include `library(R.utils)`, or consider using "explicit" snapshots and annotate the packages you require in a project DESCRIPTION file. See https://rstudio.github.io/renv/reference/snapshot.html#snapshot-type for more details.

**Comment by sgvignali** [comment]
This is what I was looking for, thank you @kevinushey! I actually see now that this is described on the **Get started** page...
