### ISSUE TITLE
Installation fails with error in userlibs[[1]]

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#1020]
I'm seeing the following strange errors when installing packages from renv on my local mac M1. This is from a global R session, outside of renv, with renv 0b6a5a4a93105fd05c5f3c0d540c050debc4a9ca:

```
> options(renv.config.pak.enabled = FALSE)
> renv::install("renv")
Retrieving 'https://cloud.r-project.org/bin/macosx/big-sur-arm64/contrib/4.1/renv_0.15.5.tgz' ...
	OK [file is up to date]
Installing renv [0.15.5] ...
	FAILED
Error installing package 'renv':
================================

Error in userlibs[[1]] : subscript out of bounds
Calls: local -> eval.parent -> eval -> eval -> eval -> eval
Execution halted
Error: install of package 'renv' failed [error code 1]
Backtrace:
     ▆
  1. └─renv::install("renv")
  2.   └─renv:::renv_install_impl(records) at renv/R/install.R:214:2
  3.     └─renv:::renv_install_staged(records) at renv/R/install.R:237:2
  4.       └─renv:::renv_install_default(records) at renv/R/install.R:257:2
  5.         ├─renv handler(package, renv_install_package(record)) at renv/R/install.R:351:4
  6.         └─renv:::renv_install_package(record) at renv/R/install.R:351:4
  7.           ├─base::withCallingHandlers(...) at renv/R/install.R:383:2
  8.           └─renv:::renv_install_package_impl(record) at renv/R/install.R:383:2
  9.             └─renv:::r_cmd_install(package, path) at renv/R/install.R:588:2
 10.               └─renv:::r_exec_error(package, output, "install", status) at renv/R/r.R:207:4
```

This happens consistently across renv versions, for all packages I try to install, and for all renv projects (or global execution). It works for R 4.2 and R 4.1 (x86_64) on my system, doesn't work for R 4.1 (arm64), even after reinstall, so it's very likely that some part of the (system? user?) library is borked. It is strange though that the same error happens on a colleague's machine. I haven't found `userlibs` in any of renv or R sources.

I installed R with rig: https://github.com/r-lib/rig/.

CC @TSchiefer.

**Comment by kevinushey** [comment]
Looks like that code is coming from rig:

https://github.com/r-lib/rig/blob/4330f34b3e132ccfde1808e7c9acd63a4f8805bd/src/library.rs#L377-L396

I assume that means `R_LIBS_USER` is unset or empty for some reason here?

**Comment by krlmlr** [comment]
Thanks for the super-fast reply. I'll file a rig issue.

**Comment by krlmlr** [comment]
On the other hand, is this the right thing to do for `r_exec()` ? Should we mimic what {callr} is doing here?

**Comment by krlmlr** [comment]
Confirming that patching my system `Rprofile` fixes things, see https://github.com/r-lib/rig/pull/81.

My system `Rprofile` files for the other versions have the same code, yet the problem doesn't appear there (yet).

**Comment by kevinushey** [comment]
I've also made this change in renv: https://github.com/rstudio/renv/commit/4e00953f254d40cceeb4cfaebcb13ee139cd0340

Are there any other relevant changes I should consider?

**Comment by krlmlr** [comment]
Thanks, I don't know. @gaborcsardi: what do you think?

**Comment by gaborcsardi** [comment]
Ooops, I missed this, sorry. I don't think there is anything to do here.
