### ISSUE TITLE
Renv fails to restore Github packages

### ISSUE THREAD

**Issue by bobbywang000** [rstudio/renv#1023]
We've been using renv to install some public packages from Github in our CI pipeline. This has worked in the past, but recently we've failed with the following error:

```
Retrieving 'https://api.github.com/repos/CamaraLab/AdjacencyScore/tarball/88a2285aa6fa1c15f3e9ca1db752c86b78d0dd2f' ...
Error: failed to retrieve 'https://api.github.com/repos/CamaraLab/AdjacencyScore/tarball/88a2285aa6fa1c15f3e9ca1db752c86b78d0dd2f' [cannot open URL 'https://api.github.com/repos/CamaraLab/AdjacencyScore/tarball/88a2285aa6fa1c15f3e9ca1db752c86b78d0dd2f']
In addition: Warning message:
In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
  cannot open URL 'https://api.github.com/repos/CamaraLab/AdjacencyScore/tarball/88a2285aa6fa1c15f3e9ca1db752c86b78d0dd2f': HTTP status was '401 Unauthorized'
Traceback (most recent calls last):
8: renv::restore()
7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
6: retrieve(packages)
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_github(record)
2: renv_retrieve_package(record, url, path)
1: stop(status)
```

AdjacencyScore is a public repo, and we have no trouble accessing the problematic URL either via wget or directly in the browser.

Interestingly enough, even if we pull packages from the cache, we will get the following failure:

```
$ Rscript -e "renv::restore()"
...
Installing STvEA [0.2.0] ...
	OK [copied cache]
...
Installing AdjacencyScore [0.1.0] ...
	OK [copied cache]
...
Warning messages:
1: In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
  cannot open URL 'https://api.github.com/repos/CamaraLab/AdjacencyScore': HTTP status was '401 Unauthorized'
2: failed to resolve remote 'CamaraLab/AdjacencyScore' declared by package 'STvEA'; skipping 

$ Rscript -e "renv::install('devtools')"

Error in vapply(x, f, ..., FUN.VALUE = character(1)) : 
  values must be length 1,
 but FUN(X[[3]]) result is length 0
Calls: <Anonymous> ... renv_install_remotes_update -> renv_description_remotes -> map_chr -> vapply
In addition: Warning messages:
1: In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
  cannot open URL 'https://api.github.com/repos/CamaraLab/STvEA': HTTP status was '401 Unauthorized'
2: failed to resolve remote 'github::CamaraLab/STvEA' from project DESCRIPTION file; skipping 
Traceback (most recent calls last):
5: renv::install("devtools")
4: renv_install_remotes_update(records, project)
3: renv_description_remotes(descpath)
2: map_chr(parsed, `[[`, "Package")
1: vapply(x, f, ..., FUN.VALUE = character(1))
Execution halted
```

I've confirmed that this error exists on both `0.15.4` and `0.15.5`.

There are two points of confusion:

1. Why is github package installation failing with a 401, when the URL can be properly accessed via a browser or wget?
2. Why does renv try to access Github when the packages already exist in the cache and successfully installed?

**Comment by kevinushey** [comment]
That's very odd to me, especially since I can access both of those links from my browser without issue:

https://api.github.com/repos/CamaraLab/STvEA
https://api.github.com/repos/CamaraLab/AdjacencyScore/tarball/88a2285aa6fa1c15f3e9ca1db752c86b78d0dd2f

And indeed, this works for me:

```
> renv:::renv_remotes_resolve("github::CamaraLab/STvEA")
$Package
[1] "STvEA"

$Version
[1] "0.2.0"

$Source
[1] "GitHub"

$RemoteType
[1] "github"

$RemoteHost
[1] "api.github.com"

$RemoteUsername
[1] "CamaraLab"

$RemoteRepo
[1] "STvEA"

$RemoteRef
[1] "master"

$RemoteSha
[1] "e9fbba57177e72989684d4cbfcf7920c460b96ec"
```

So presumedly there's something going on with GitHub, or the machine trying to communicate with GitHub? (Normally I would guess an issue with the `GITHUB_PAT` being used; maybe that token was revoked or something similar?)

Presumedly, `renv::install()` is failing because it's trying to see if any updates for the `STvEA` package are available at the same time, and that update check is failing. The fact that `renv` is checking whether this package is up-to-date seems like a bug since it wouldn't be part of the `devtools` dependency chain, though.

**Comment by alex-odysseus** [comment]
Kevin, getting something similar on renv 0.15.4 @kevinushey 

```
Retrieving 'https://api.github.com/repos/OHDSI/CirceR/tarball/v1.1.1' ...
Error: failed to retrieve 'https://api.github.com/repos/OHDSI/CirceR/tarball/v1.1.1' [error code 22]
In addition: Warning message:
curl: (22) The requested URL returned error: 401  
Traceback (most recent calls last):
8: renv::restore()
7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
6: retrieve(packages)
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_github(record)
2: renv_retrieve_package(record, url, path)
1: stop(status)
Execution halted

```

In renv.lock this element is specified in the following way

```
"CirceR" : {
			"Package" : "CirceR",
			"Version" : "1.1.1",
			"Source" : "GitHub",
			"RemoteType" : "github",
			"RemoteHost" : "api.github.com",
			"RemoteRepo" : "CirceR",
			"RemoteUsername" : "OHDSI",
			"RemoteRef" : "v1.1.1"
		}
```

Is the Personal Access Token (PAT) mandatory to have for this scenario when the repository is public? Where to place it then?

**Comment by kevinushey** [comment]
Please see: https://rstudio.github.io/renv/articles/renv.html#authentication

The 401 error means Unauthorized, so for whatever reason GitHub is refusing access to the repository even though it's public. My best guess is that it's caused by an existing `GITHUB_PAT` that GitHub is denying access to, but I do not know.

**Comment by bobbywang000** [comment]
Yup, indeed - the `GITHUB_PAT` was expired and swapping it out fixed the issue!

A suggestion though: is it possible for renv to install public repos using a regular git clone instead of a github API call? It's a bit surprising that you need a valid Github PAT to access a public repo in renv, but not in your browser/anywhere else.

**Comment by kevinushey** [comment]
That is indeed possible; for example, to install `renv` using `git`:

```
renv::install("git::git@github.com:rstudio/renv.git")
```

Or, using `https`,

```
renv::install("git::https://github.com/rstudio/renv")
```

**Comment by bobbywang000** [comment]
Got it, thank you! I'll close this issue as resolved then.
