### ISSUE TITLE
json parse fail - more debug assistance (suggestion)

### ISSUE THREAD

**Issue by slodge** [rstudio/renv#1027]
While moving from R4.1 to R4.2 (on windows) we've been doing a lot of renv.lock file editing - just updating packages like curl which seem to need newer package versions to build on RTools42

While doing this we've had some finger trouble which has led to invalid JSON - to messages like:

``` 
> renv::status()
Error in seq_len(length(splat) - 1) : 
  argument must be coercible to non-negative integer
```

One way to find the json errors seems to be:

```
> jsonlite::validate(readr::read_file("renv.lock"))
[1] FALSE
attr(,"offset")
[1] 30949
attr(,"err")
[1] "parse error: after key and value, inside map, I expect ',' or '}'\n          \"Repository\": \"CRAN\"        \"Requirements\": []      },      \n                     (right here) ------^\n"
```

Obviously this only applies to people editing the renv.lock files manually (but we all do that, right?)

Would it help to build that error reporting into renv somehow - e.g. some sort of `renv:::validate_lock_file()` ?

(Cross linking to #130 where I also saw this message reported)

**Comment by wtimmerman-fitp** [comment]
Seconding this request! Someone on our team recently ran into this issue as well (after I goofed on manually editing a lockfile to remove a troublesome package), and the unclear message threw them off for a bit.
