### ISSUE TITLE
`record` drops requirements from lockfile

### ISSUE THREAD

**Issue by vandenman** [rstudio/renv#1035]
Calling `record(<package>)` empties the Requirements fields of a lock file

reproducible example:
``` r
library(renv) # inside a fresh project
#> 
#> Attaching package: 'renv'
#> The following objects are masked from 'package:stats':
#> 
#>     embed, update
#> The following objects are masked from 'package:utils':
#> 
#>     history, upgrade
#> The following objects are masked from 'package:base':
#> 
#>     autoload, load, remove
install("cli")
#> Installing cli [3.3.0] ...
#>  OK [linked cache]
snapshot()
#> * Lockfile written to '~/deleteMe/renv.lock'.
lockfile <- renv:::renv_lockfile_read(renv::paths$lockfile())
lockfile$Packages$cli$Requirements
#> [[1]]
#> [1] "glue"

record("glue")
#> * Updated 1 record in "~/deleteMe/renv.lock".
lockfile <- renv:::renv_lockfile_read(renv::paths$lockfile())
lockfile$Packages$cli$Requirements
#> list()
```

<sup>Created on 2022-06-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I figured this is probably not intended. It happens here
https://github.com/rstudio/renv/blob/f9cc3e0ec2f4eb0c1a729fa41f794c71c92f96e5/R/lockfile-write.R#L55-L72

In the example, `vals <- keep(record, keys)` returns an empty list.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I think this is already resolved in the development version of `renv`. I see:

```
> record("glue")
* Updated 1 record in "~/scratch/example/renv.lock".
> lockfile <- renv:::renv_lockfile_read(renv::paths$lockfile())
> lockfile$Packages$cli$Requirements
[[1]]
[1] "glue"
```

See also: https://github.com/rstudio/renv/issues/974

**Comment by vandenman** [comment]
You're right, it's already solved on the main branch. Sorry for the noise!

**Comment by kevinushey** [comment]
No worries! I appreciate your taking the time to report a bug, especially with a reproducible example. I'll try to get the fix up on CRAN soon.
