### ISSUE TITLE
Keep profiles in sync?

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#1039]
Scenario: I have a development and a deployment profile. In development I have devtools and other toys, the deployment profile is lean, but should be a subset of the development profile with exactly the same versions. (A variant of #624?)

What's the best way to keep both `renv.lock` in sync? Are you planning to support cascading profiles?

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for renv: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
