### ISSUE TITLE
Github pages - code snippet not visible

### ISSUE THREAD

**Issue by PaulinCharliquart** [rstudio/renv#1040]
hi,

Code snippets are empty in [documentation ](https://rstudio.github.io/renv/reference/install.html#bioconductor):

![image](https://user-images.githubusercontent.com/64043642/176897866-230cc691-a2c2-4e89-acc2-64855cd195e8.png)

kind regards,
Paulin

**Comment by kevinushey** [comment]
Thank you for the heads up; I'll take a look!

**Comment by mkoohafkan** [comment]
Seems to be in a few places, see also
- https://rstudio.github.io/renv/reference/dependencies.html
- https://rstudio.github.io/renv/reference/config.html#copy-methods
- https://rstudio.github.io/renv/reference/consent.html#details

Note that the "copy code" buttons work correctly.  I notice the code blocks render with significant padding, I wonder if that's what is causing the issue with single-line code blocks.
