### ISSUE TITLE
Is Changing Package Source To BioConductor based on "BiocViews" entry in DESCRIPTION valid behaviour?

### ISSUE THREAD

**Issue by mstr3336** [rstudio/renv#105]
As in [snapshot.R:renv_snapshot_description_source()](https://github.com/rstudio/renv/blob/master/R/snapshot.R#L397-L398)

When I original developed my package, with the following description:

```
biocViews:
Imports: 
    dplyr,
    forcats,
    stringr,
    magrittr,
    R6,
    glue,
    BiocManager,
    IRanges,
    readr,
    tibble,
    S4Vectors,
    lubridate,
    logging (>= 0.9-107),
    rlang,
    purrr,
    data.table,
    tidyr,
    here,
    pathlibr
RoxygenNote: 6.1.1
Suggests: 
    testthat,
    lintr,
    covr,
    knitr,
    rmarkdown,
    pkgdown
VignetteBuilder: knitr
Roxygen: list(markdown = TRUE)
Remotes: 
    mstr3336/portrpaths,
    mstr3336/timevis,
    mstr3336/contextractr
```

I included `BiocViews` as a workaround for allowing `devools::install_deps` to handle bioconductor packages.

I'm not sure if BiocViews implies that this package is hosted on BioConductor

**Comment by kevinushey** [comment]
This is where we attempt to infer a package's source from its DESCRIPTION file:

https://github.com/rstudio/renv/blob/master/R/snapshot.R#L395-L410

AFAIK all packages on Bioconductor set biocViews, so by doing this yourself with a non-bioconductor package you're "lying" to `renv` a bit.

**Comment by mstr3336** [comment]
> This is where we attempt to infer a package's source from its DESCRIPTION file:
> 
> https://github.com/rstudio/renv/blob/master/R/snapshot.R#L395-L410
> 
> AFAIK all packages on Bioconductor set biocViews, so by doing this yourself with a non-bioconductor package you're "lying" to `renv` a bit.

I saw where the behaviour was documented - My problem was that (To the best of my knowledge) to allow `devtools::install_deps()` to find BioC hosted packages, I needed to set the field (Perhaps this workaround is no longer needed, or this is a hacky fix to the problem).

I also noticed that as per [The behaviour that handles the "Repository" field](https://github.com/rstudio/renv/blob/master/R/snapshot.R#L400-L402) , renv will infer that a package is hosted on CRAN regardless of the value of the "Repository" field - (In my case it was actually set to localCRAN - Another attempt at a workaround for some dependency issues)

In my case, I could just remove those fields (I'll wait and see if the biocViews thing comes back for me but maybe that workaround is no longer needed), but that mightn't be true for all users.

I wonder if a more accurate behaviour for handling "Repository" might be to check if it's set, and if so, use the value it's set to, or if it's null / matches "cran" closely enough to then use CRAN?

**Comment by kevinushey** [comment]
Just to be clear, what problem are you having exactly? Are you just having this issue with `devtools::install_deps()` or are you seeing something `renv`-specific?

> I also noticed that as per The behaviour that handles the "Repository" field , renv will infer that a package is hosted on CRAN regardless of the value of the "Repository" field - (In my case it was actually set to localCRAN - Another attempt at a workaround for some dependency issues)

Right now, `renv` assumes that all "CRAN" packages come from one of the active CRAN mirrors, regardless of what repository is actually declared. (We saw in Packrat that users mostly wanted us to assume a package was available on CRAN, even if the Repository field didn't exist or the field name didn't match up with something in the active repositories).

Presumedly, if your localCRAN repository was in the active set of R repositories (ie: as reported by `getOption("repos")`) then everything should work. If it doesn't, a reproducible example would be useful.
