### ISSUE TITLE
Issues using renv in docker image with a volume mount

### ISSUE THREAD

**Issue by ramnathv** [rstudio/renv#1050]
@kevinushey I am running RStudio Server in a docker image with a volume mount. When I log in to RStudio, `.libPaths()` links to two libaries, a `/usr/local/lib/R/site-library` which holds the custom packages installed during the docker build and a `usr/local/lib/R/library` which holds the base+recommended packages that ship with R. In order to have access to the custom packages as well, I initialize `renv` in my project directory using:

```r
renv::init(settings = list(external.libraries = "/usr/local/lib/R/site-library"))
```

After initialization, when I try to load packages that are compiled (e.g. `rappdirs`, `yaml` etc), I run into the following error, which I believe is because of the cache being in a volume mount with `noexec` permissions.

```
Error: package or namespace load failed for ‘rappdirs’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/ramnath/.cache/R/renv/cache/v5/R-4.2/x86_64-pc-linux-gnu/rappdirs/0.3.3/5e3c5dc0b071b21fa128676560dbe94d/rappdirs/libs/rappdirs.so':
  /home/ramnath/.cache/R/renv/cache/v5/R-4.2/x86_64-pc-linux-gnu/rappdirs/0.3.3/5e3c5dc0b071b21fa128676560dbe94d/rappdirs/libs/rappdirs.so: failed to map segment from shared object
```

If I remove the offending packages from the cache folder, they load correctly, as they now load from the external library.

My question is what is considered best-practice in handling such a situation. Is there a way I can tell `renv` NOT to copy some packages to the cache? I searched around for mounting a volume with exec permissions, but could not find a reasonable approach to do that. I would love to get some pointers on how to approach this. Thanks in advance.

**Comment by kevinushey** [comment]
> Is there a way I can tell renv NOT to copy some packages to the cache?

Not on that granularity -- the cache is either "on" or "off" for a project. In theory we could add an extension here:

https://github.com/rstudio/renv/blob/d52a54437db159e98c79d59e9100e9c7fedcdc17/R/records.R#L37-L52

To disable the cache wholesale, you could use the `use.cache = FALSE` setting; see https://rstudio.github.io/renv/reference/settings.html for some more details.

**Comment by ramnathv** [comment]
@kevinushey On further investigation, I realized that I have to nuke compiled packages from the renv project library due to the aforementioned error. Once I do that they are loaded from the site-library. I realize that the issue is because I volume mount my home directory in a docker image, and as a result the project library is on a disk with `noexec` permissions. Is it possible to volume mount with `exec` permissions in docker? If not, is there any other workaround here, since it seems to be a big blocker using `renv` in docker settings, unless one sets up a shared cache.

**Comment by kevinushey** [comment]
I'm not sure to be honest. The advice I've been able to find online seems roughly:

- Prefer using bind mounts if you need the mount to be `exec`,
- Maybe it's possible to pass an argument through `--volume-opt`?

Perhaps worth an ask on StackOverflow or some other Docker-specific forum?
