### ISSUE TITLE
how to create a project-related DESCRIPTION file to use explicit snapshot?

### ISSUE THREAD

**Issue by ChristelSwift** [rstudio/renv#1054]
I would like to limit the list of packages that will end up in `renv.lock` to what i'm using in one of the files in my project.

According to the `renv` vignette (https://cran.r-project.org/web/packages/renv/vignettes/renv.html) it looks like i could use an explicit snapshot approach:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/24437540/181499348-00a2113b-51be-4310-b197-024d71829d2a.png">

Unfortunately the link provided in the documentation (https://r-pkgs.org/description.html) no longer works and i can't find any example of how to do this in practice.  

I've tried to create a DESCRIPTION file for my project using `usethis::use_description()` and editing it manually so it looks like this:  

```
Type: project
Title: my_project
Description: data refresh pipeline for my app
Imports: 
    tidyverse,
    duckdb,
    RJDBC,
    aws.s3,
    aws.ec2metadata,
    httr,
    jsonlite,
    stringr
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
```

Unfortunately i get this error when trying to set the snapshot to "explicit":

```
> renv::settings$snapshot.type("explicit")
28 Jul 2022 11:53:14 [rsession-jovyan] ERROR system error 71 (Protocol error) [description=Package field not found in /home/jovyan/my_project/DESCRIPTION]; OCCURRED AT: rstudio::core::Error rstudio::core::r_util::RPackageInfo::read(const rstudio::core::FilePath&) /home/ubuntu/rstudio/src/cpp/core/r_util/RPackageInfo.cpp:85; LOGGED FROM: bool rstudio::core::r_util::isPackageDirectory(const rstudio::core::FilePath&) /home/ubuntu/rstudio/src/cpp/core/r_util/RPackageInfo.cpp:121
```

Any idea what i'm doing wrong?  is there a tutorial showing how to do this in practice?

**Comment by kevinushey** [comment]
You're right, it looks like the documentation has moved to https://r-pkgs.org/Metadata.html. I'll need to update that link.

The error you're seeing is coming from RStudio rather than `renv`, though -- it seems to be expecting (perhaps erroneously) that your DESCRIPTION file should have a Package field. RStudio should only check that field if the Type field is Package (or missing). Otherwise, your DESCRIPTION file looks correct to me.

**Comment by ChristelSwift** [comment]
thanks Kevin.  So is this an RStudio bug?  should i log it as an issue in a different Git?  will it prevent my explicit snapshot to work as expected?

**Comment by kevinushey** [comment]
I think this should be filed as an RStudio issue; I'll move it there. It shouldn't affect the functionality of `renv`. Thanks!

**Comment by kevinushey** [comment]
Could you also confirm what version of RStudio you have installed?

**Comment by ChristelSwift** [comment]
it's RStudio version 1.1.419

```
─ Session info ─────────────────────────────────
 setting  value
 version  R version 3.6.1 (2019-07-05)
 os       Ubuntu 18.04.3 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2022-07-29
 rstudio  1.1.419 (server)
 pandoc   2.18 @ /opt/conda/bin/pandoc

**Comment by kevinushey** [comment]
I believe that would explain it -- that's quite an old version of RStudio; this seems like an issue that should already be resolved in the latest release.
