### ISSUE TITLE
.Rprofile code: only load _activate.R_ if it exists?

### ISSUE THREAD

**Issue by yogat3ch** [rstudio/renv#1056]
Hi @kevinushey & `renv` devs,
We're using `renv` throughout our apps & projects at Virga Labs, thank you all for the essential package!
I've just encountered an issue during shiny app deployment where the `renv` folder is often not included in the deployment image to reduce image size, but the _.Rprofile_ is. The line that `renv` automatically adds `source("renv/activate.R")` will cause the app to fail. 
What about adding the following to _.Rprofile_ to prevent this issue?
```r
if (file.exists("renv/activate.R"))
  source("renv/activate.R")
```

Curious to hear your thoughts!
Thanks!

**Comment by aronatkins** [comment]
Are you deploying to RStudio Connect? Could you share what version of Connect is in use? As of the RStudio Connect 1.8.6.3 release, the `.Rprofile` files should be rewritten to avoid running the `source("renv/activate.R")` line of code.

**Comment by yogat3ch** [comment]
Hi @aronatkins,
Thanks for the reply!
I'm deploying to AWS EC2 instances via docker and/or `shinyapps.io`

**Comment by hadley** [comment]
Should be fixed in rsconnect
