### ISSUE TITLE
changing renv/ location within project

### ISSUE THREAD

**Issue by kkmann** [rstudio/renv#1057]
Hi,

I was not able to figure out how to configure renv to put all confi files in a subfolder og my project. I would like to store renv/... in as subfolder "stuff" where all other infrastructure and config things are collected.  I tried to solve this via project specific .Renviron file

```
RENV_PATHS_PREFIX="stuff"
RENV_PATHS_LOCKFILE="./stuff/renv.lock"
```

the lock file is moved correctly, but renv still reates a renv folder at the project root directory (the library path is `.../my-project/renv/library/.infrastructure/R-4.1/x86_64-w64-mingw32`)

Is this even possible? If not, why not?

Thanks!

**Comment by kevinushey** [comment]
I think you want RENV_PATHS_RENV instead of RENV_PATHS_PREFIX?

**Comment by kkmann** [comment]
thanks. interesting, didn't see that in the docs https://rstudio.github.io/renv/reference/paths.html

somehow snapshot() is then getting confused, haven't figured it out yet. Would be great if there was a documentation on "how do I move all renv infrastructure out of sight (i.e. ins 'stuff')" :)

**Comment by kevinushey** [comment]
> thanks. interesting, didn't see that in the docs https://rstudio.github.io/renv/reference/paths.html

Thanks for catching that; it looks like I neglected to document it.

> somehow snapshot() is then getting confused, haven't figured it out yet. Would be great if there was a documentation on "how do I move all renv infrastructure out of sight (i.e. ins 'stuff')" :)

I'll have to think about this more... the main challenge with moving the `renv` folder is that the auto-loader in the project `.Rprofile` usually expects to find the activate script at `renv/activate.R`, so changing `RENV_PATHS_RENV` on its own in an existing project might not be sufficient.

If you were willing to live without the `renv` auto-loader (that is, you were willing to call `renv::load()` manually) that might make things a bit easier.

**Comment by kkmann** [comment]
Hm, I don't think this is a huge problem. The ppl who would want to do this kind of customization can probably be expected to fiddle with the .Rprofile manually. Would just be helpful to have the steps documented since fiddling with the renv infrastructure can get a bit scary quickly ;) If I understand you correctly, all it takes are a few additions to .Rprofile (is it really just modifying the path to activate.R?)

**Comment by kevinushey** [comment]
> If I understand you correctly, all it takes are a few additions to .Rprofile (is it really just modifying the path to activate.R?)

That should (hopefully) be all you need.
