### ISSUE TITLE
Feature Request: function that tests if renv project is loaded

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#1058]
Use-case:

When opening an .Rproj that uses renv, a message is printed like:
```r
* Project '/path/to/project/' loaded. [renv 0.15.5]
```
I can manually inspect the console output for that message, but it would be nice to add a line to my code that tests that it was successfully loaded. This would be particularly useful for cases where I'm running scripts in batch mode. Then my scripts could include something like:
```r
stopifnot(renv_is_loaded)
```
This came up because I noticed that I was running scripts in batch mode from the wrong directory, so renv was not being sourced properly.

**Comment by kevinushey** [comment]
One thing you can check -- after the project has been activated, the project path will be stored in `getOption("renv.project.path")`. If that option is `NULL`, then you can conclude `renv` has not yet been activated.

**Comment by kevinushey** [comment]
We now have a proper exported function for this: you can use `renv::project()` to get the path to the currently-loaded project, if any. If that returns `NULL`, then no project is currently loaded.

We should consider linking to `project` from the `load` documentation, to close this out? Or maybe somewhere in the introduction vignette?

**Comment by hadley** [comment]
It's a relatively rare need and it's listed in the reference index, so that should be adequate in my opinion.
