### ISSUE TITLE
renv library doesn't work well when sharing RStudio cloud projects

### ISSUE THREAD

**Issue by eliocamp** [rstudio/renv#1059]
Using renv to manage the package library in RStudio Cloud, the status of the library is broken when sharing the project. My guess is that it has to do with the global package cache, which is only valid in the original user account. 

In any case, the user experience is that if I want to share a project that uses renv in Rtudio Cloud, the recipient has to run `renv::repair()`, which can be confusing and take a long time. Compared with the experience of not using renv, in which required packages are come installed with the project, it's much worse, particularly for teaching and short workshops. 

I don't know if this is something that could be improved from the renv side or the Rstudio cloud side. Perhaps there's a workaround? Perhaps setting the cache path inside the project?

**Comment by kevinushey** [comment]
Thanks for the bug report! I agree that using a project-local cache is probably the best solution here, since otherwise the cache would be ephemeral (or tied only to one user's account).

I believe you should be able to accomplish this by creating a file called `.Renviron` in the project root directory, and including the line

```
RENV_PATHS_CACHE = renv/cache
```

in that file.

**Comment by kevinushey** [comment]
It might be worth asking a question on https://community.rstudio.com/c/rstudio-cloud/14, just to get some extra visibility from the RStudio Cloud team.

**Comment by eliocamp** [comment]
Thanks! 
`RENV_PATHS_CACHE = renv/cache` should work, although I'm not sure if it will be compatible with the size limit of RSC projects. I'd need to test it to be sure. 

I've opened a thread on the rstudio community: https://community.rstudio.com/t/renv-library-doesnt-work-well-when-sharing-rstudio-cloud-projects/143733

**Comment by eliocamp** [comment]
This has been solved from the [RStudio Cloud side](https://community.rstudio.com/t/renv-library-doesnt-work-well-when-sharing-rstudio-cloud-projects/143733/6).
