### ISSUE TITLE
Renv restore failed to find binary or source for all packages

### ISSUE THREAD

**Issue by robinzng** [rstudio/renv#1063]
Hi, I've been getting the following error when I run renv::restore for a project: 

Warning: failed to find binary for 'mgcv 1.8-39' in package repositories
Warning: failed to find source for 'mgcv 1.8-39' in package repositories
Error: failed to retrieve package 'mgcv@1.8-39'

This has happened for 3 different packages so far. I just downloaded the archived files from the CRAN website for the previous packages to see if that would resolve things, but it looks like renv is just going down the list of packages and failing for each one. The file_download_method is already set to wininet, and the repository is cran.rstudio.com. I read through the FAQs and other reported issues, but they don't seem to address what I'm seeing here. Any idea what I can do? 
Thanks,
Robin

**Comment by kevinushey** [comment]
Can you confirm the output of `getOption("repos")`?

You can also try debugging in `renv_retrieve_repos_archive` to see why `renv` is failing to find the package. (Is it using the wrong URL? Something else?)

You could also try setting:

```
options(renv.download.trace = TRUE)
```

to see what web requests `renv` is trying to make here as well.

**Comment by englander** [comment]
I was having the same problem (on a Windows machine), but when I ran   

Sys.setenv(RENV_DOWNLOAD_METHOD = "wininet")

then renv::restore() downloaded all packages correctly.

**Comment by nick-youngblut** [comment]
I'm running into this problem for my CI testing on `ubuntu-latest` (20.04.5):

```
Retrieving 'https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/Archive/ggplot2/ggplot2_3.4.0.tar.gz' ...
Warning: Warning: failed to find source for 'ggplot2 3.4.0' in package repositories
Warning: Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/Archive/ggplot2/ggplot2_3.4.0.tar.gz' [error code 22]
Error: Error: failed to retrieve package 'ggplot2@3.4.0'
```

**Comment by kevinushey** [comment]
You need to add CRAN as a fallback repository; a new version of ggplot2 was just released to CRAN but RSPM hasn't synchronized those changes yet.

**Comment by nick-youngblut** [comment]
@kevinushey do you know how to add CRAN as a fallback repository for https://github.com/r-lib/actions/tree/v2/setup-renv?

**Comment by kevinushey** [comment]
```
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```

You need to install the build-time requisites for `curl` as indicated there. Sorry, but I'm not familiar with the GitHub actions infrastructure, but my understanding is that the `sysreqs` package has some tooling for this: https://github.com/r-hub/sysreqs

**Comment by nick-youngblut** [comment]
Thanks @kevinushey! I modified my GitHub actions yaml file based on the renv yaml: https://github.com/rstudio/renv/blob/main/.github/workflows/R-CMD-check.yaml
