### ISSUE TITLE
Renv fails when package name differs from repo name

### ISSUE THREAD

**Issue by tomshafer** [rstudio/renv#1064]
Unlike [remotes](https://remotes.r-lib.org/reference/parse-git-repo.html), renv fails when trying to install a GitHub-hosted package using the `pkgname=user/repo` syntax:

``` r
renv::install("testpkg=tomshafer/example-r-package")
#> Warning: curl: (22) The requested URL returned error: 404
#> Error: failed to resolve remote 'testpkg=tomshafer/example-r-package' -- failed to retrieve 'https://api.github.com/repos/testpkg=tomshafer/example-r-package' [error code 22]
```

Cf. remotes:

``` r
remotes::install_github("testpkg=tomshafer/example-r-package")
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo tomshafer/example-r-package@HEAD
#> Running `R CMD build`...
#> * checking for file ‘/private/var/folders/jc/97flnncx6rl3rq_xv_31xwd1d808dq/T/Rtmp5OUxaR/remotese8255bf3c58b/tomshafer-example-r-package-1ad1d48/DESCRIPTION’ ... OK
#> * preparing ‘testpkg’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> * building ‘testpkg_1.0.0.tar.gz’
#> Installing package into '/Users/tom.shafer/Work/CSC/renv reprex/reprex/renv/library/R-4.2/x86_64-apple-darwin17.0'
#> (as 'lib' is unspecified)
```
<sup>Created on 2022-08-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The problem compounds when using renv for package development. When my development package Imports a GitHub-hosted package like above via `Remotes:`, renv cannot install _any_ packages. Presumably it looks at my local `DESCRIPTION` each time it tries to do an installation and I receive similar errors -- even though testpkg isn't involved in my install request in any way.

**Comment by kevinushey** [comment]
Where is that remotes format documented? I don't see it in https://cran.r-project.org/web/packages/remotes/vignettes/dependencies.html.

**Comment by tomshafer** [comment]
It's not well-documented but it's super useful. Grep for 'igraph' here: https://remotes.r-lib.org/reference/parse-git-repo.html
