### ISSUE TITLE
`renv/activate.R` has old `renv` version rather than `renv` version matching renv.lock of the project

### ISSUE THREAD

**Issue by nicholas-masel** [rstudio/renv#1066]
The reprex below creates a lock file w/renv 15.5, then installs renv 14.0 and uses renv 14.0 to create a new project, copy the renv.lock with 15.5 into it this project and initialize and restore the new project.  The activate.R ends up with `version <- 14.0` instead of `version <- 15.5` which gives us this warning when opening the new project.

```r
* Project '~/1_renv_question/use_renv_lock' loaded. [renv 0.15.5]
Warning message:
renv 0.15.5 was loaded from project library, but this project is configured to use renv 0.14.0.
Use `renv::record("renv@0.15.5")` to record renv 0.15.5 in the lockfile.
Use `renv::restore(packages = "renv")` to install renv 0.14.0 into the project library. 
```

Should `renv::restore()` update `renv/activate.R`?  Or am I using a hammer when I should be using a screwdriver to programmatically setup a project using an existing, restricted `renv.lock` file, meaning it cannot be updated w/`renv::snapshot()` as suggested [here](https://stackoverflow.com/questions/63897210/renv-0-12-0-was-loaded-from-project-library-but-renv-0-11-0-is-recorded-in-lock)?

**reprex:**

```r
# create a lock file using latest renv
options(repos = "https://packagemanager.rstudio.com/cran/latest")
install.packages("renv")
install.packages("rstudioapi")

# create project
rstudioapi::initializeProject("~/1_renv_question/renv15")

# initialize the project
renv::init(project = "~/1_renv_question/renv15")

# install renv 14.0
options(repos = "https://packagemanager.rstudio.com/cran/2022-01-04")
install.packages("renv")
install.packages("rstudioapi")

rstudioapi::restartSession()

# create project
rstudioapi::initializeProject("~/1_renv_question/use_renv_lock")

# add the renv.lock
file.copy("~/1_renv_question/renv15/renv.lock", "~/1_renv_question/use_renv_lock/renv.lock")

# initialize the project
renv::init(project = "~/1_renv_question/use_renv_lock", bare = TRUE, restart = FALSE)

# restore project
renv::restore(project = "~/1_renv_question/use_renv_lock", prompt = FALSE)

rstudioapi::openProject("~/1_renv_question/use_renv_lock/use_renv_lock.Rproj")
```

**Comment by kevinushey** [comment]
> Should renv::restore() update renv/activate.R?

I think it should -- thanks for catching that.
