### ISSUE TITLE
Consider masking Git provider environment variables from package install subprocesses

### ISSUE THREAD

**Issue by toph-allen** [rstudio/renv#1068]
R packages can execute code at install time. This code can access the local environment, and may not be trusted.

We [just implemented a feature in Packrat](https://github.com/rstudio/packrat/pull/682) to mask sensitive environment variables (e.g. Git service provider credentials like `GITHUB_PAT`) from package install subprocesses. Masked variables are unset before the subprocess is called and restored afterwards. This might be a good idea to do in `renv` as well.

In Packrat, the approach we decided to take was to enable masking by default for a set variables known to be used for Git provider secrets. This masking can be disabled with an option, and another option allows users to add other variables to the list of items to mask.

**Comment by hadley** [comment]
Do you mind pointing me to the motivation for this change?

**Comment by hadley** [comment]
Since it's been a couple of weeks and we haven't anything more, I'm going to close this issue.
