### ISSUE TITLE
Notify about changing R version?

### ISSUE THREAD

**Issue by MatthieuStigler** [rstudio/renv#1069]
I notice that the change in R version in the lockfile is done silently, without any notification? It seems it would be an important information for the user?

In my case, while I had an opening message such as _Project requested R version '4.1.2' but '4.2.1' is currently being used_, running `renv::snapshot()`seems to have updated the R version to 4.1.2, yet without notifying anything?

Here was for example the message I got, which is a bit confusing since it seems to be exhaustive (i.e. informing on all changes), while maybe the biggest change is not notified?

```
> renv::snapshot()
The following package(s) have unsatisfied dependencies:

	'lobstr' requires 'cpp11 (>= 0.4.2)', but version '0.3.1' will be snapshotted

Consider updating the required dependencies as appropriate.

Do you want to proceed? [y/N]: y
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- lobstr   [* -> 1.1.2]

Do you want to proceed? [y/N]:
```

**Comment by kevinushey** [comment]
Thanks for catching that -- we should definitely be pointing that out as well.
