### ISSUE TITLE
installing renv hangs on github actions

### ISSUE THREAD

**Issue by gui-salome** [rstudio/renv#1071]
I have a simple workflow that just installs R (via `r-lib/actions/setup-r@v2`), and then installs and restores packages with `renv` (using `r-lib/actions/setup-renv@v2`), nothing else. When the job ran, I noticed it hanged right after installing `renv` (after 10 minutes I cancelled):
<img width="1323" alt="Screen Shot 2022-09-02 at 11 37 28 AM" src="https://user-images.githubusercontent.com/68299186/188187292-6cbaae9f-2d79-4c25-83e6-6fb2d7b75881.png">

I modified the workflow so that after installing R, I just install renv (with `install.packages("renv")`) and not even attempt to do anything else. However, the process still hangs after installing `renv`:
<img width="1315" alt="Screen Shot 2022-09-02 at 12 02 36 PM" src="https://user-images.githubusercontent.com/68299186/188193854-0c6215e3-d9fe-42fa-b943-f30a887b522f.png">

This is the workflow:
<img width="366" alt="Screen Shot 2022-09-02 at 12 03 47 PM" src="https://user-images.githubusercontent.com/68299186/188194058-e76cecc9-b995-4712-8254-b05768b6923d.png">

This is my first time facing this problem, so apologies if this it not the right place to post about it.
Let me know what other information I can provide.

**Comment by hadley** [comment]
This is presumably now fixed; let me know if not.
