### ISSUE TITLE
How to handle two different version of R in one project?

### ISSUE THREAD

**Issue by chuyaowang** [rstudio/renv#1072]
Hi, I have recently encountered an issue when using renv to manage my project. When I set up the project I only had R 4.2 installed, and the `project/renv/library` directory only had the 4.2 version, just as usual. Then I went and installed my packages under the library for R 4.2. So far so good.

Now all of a sudden another R 3.6 shows up in the same folder (`project/renv/library`), and I don't know what to do with it. If I open the project in R studio, the 4.2 version is loaded, but if I run R in the command line, the 3.6 version is loaded, which is really inconvenient and deviating from my intention to keep the environment reproducible.

I believe the 3.6 version is installed by conda because the full directory to the installed libraries is `/project/renv/library/R-3.6/x86_64-conda_cos6-linux-gn`, and I do have two conda environments on my system. I created the second environment to install a python library (MACS2) that is used by one of my R package. Perhaps R 3.6 is installed in the process? But why can't conda detect I already have R 4.2 installed? Is it because R 4.2 is managed by another conda environment? But again, I can load the second environment containing MACS2 in commandline, and my package in R-4.2 can use it normally, which make it even more confusing. So maybe conda isn't managing R version after all?

So my question is if it is safe (and how) to remove R 3.6 from my project. I also want to know how to prevent this from happening again in the future. Should I set up a new conda environment for every new r project?

**Comment by kevinushey** [comment]
If you don't plan on using R 3.6 in that project, you can safely remove the library path associated with that version of R. In renv projects, different versions of R get different library paths, so they are effectively isolated from each other.

In general, it's safe to use the same `renv` project with different versions of R; they'll just make use of different library paths (but note that they will use the same lockfile `renv.lock`).

I can't answer the questions regarding conda, however.
