### ISSUE TITLE
`renv::snapshot` with `options(repos = "myrepourl")` - the wrong repository is being installed

### ISSUE THREAD

**Issue by avraam-inside** [rstudio/renv#1073]
![image](https://user-images.githubusercontent.com/52919010/188898812-0ce7ecf7-a6a7-4f49-8fea-630a428123dd.png)

I use a STRICTLY specific link: `__linux__/centos8`, but renv cuts this link.

Why is this being done?

**Comment by kevinushey** [comment]
By default, `renv` encodes the source RSPM URL in the lockfile, and transforms it dynamically into the correct binary URL based on the platform that `renv::restore()` is being called on. In your example, if you wanted to restore that lockfile on a separate platform (something that's not `centos8`), restore would fail as you would end up retrieving incompatible binaries.

If you want to disable this `renv` behavior, you can set the environment variable:

```
RENV_CONFIG_RSPM_ENABLED = FALSE
```

in your project `.Renviron`, or somewhere more global. See https://rstudio.github.io/renv/reference/config.html#renv-config-rspm-enabled for more details.

**Comment by avraam-inside** [comment]
Thanks for the clarification!
