### ISSUE TITLE
can not install packages with renv "Failed to find an renv installation: the project will not be loaded."

### ISSUE THREAD

**Issue by perezja** [rstudio/renv#1077]
Trying to install a package with `BiocManager::install` which hangs at "testing if installed package can be loaded from final location".  `renv` then tries to reinstall itself in a loop and the installation of the desired package and deps ultimately fail. I simply can't move forward with any of my work.

This is the diagnostics output:
Diagnostics Report [renv 0.15.5]
================================

# Session Info =======================
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 11 (bullseye)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
 [1] igraph_1.3.4        rstudioapi_0.13     knitr_1.39         
 [4] magrittr_2.0.3      tidyselect_1.1.2    R6_2.5.1           
 [7] rlang_1.0.4         fastmap_1.1.0       fansi_1.0.3        
[10] dplyr_1.0.9         tools_4.0.4         xfun_0.32          
[13] utf8_1.2.2          DBI_1.1.3           cli_3.3.0          
[16] htmltools_0.5.3     assertthat_0.2.1    yaml_2.3.5         
[19] digest_0.6.29       tibble_3.1.8        lifecycle_1.0.1    
[22] purrr_0.3.4         BiocManager_1.30.18 vctrs_0.4.1        
[25] glue_1.6.2          evaluate_0.16       rmarkdown_2.16     
[28] compiler_4.0.4      pillar_1.8.0        generics_0.1.3     
[31] renv_0.15.5         pkgconfig_2.0.3    

# Project ============================
Project path: "~/R"

# Status =============================
The following package(s) are installed but not recorded in the lockfile:
                                    _
  jquerylib                           [0.1.4]
  fs                                  [1.5.2]
  tinytex                             [0.41]
  TxDb.Hsapiens.UCSC.hg19.knownGene   [3.2.2]
  bslib                               [0.4.0]
  rmarkdown                           [2.16]
  sass                                [0.4.2]

Use `renv::snapshot()` to add these packages to your lockfile.

The following package(s) are used in the project, but are not installed:

	clusterProfiler

Consider installing these packages, and then using `renv::snapshot()`
to record these packages in the lockfile.

# Packages ===========================
                                     Library       Source  Lockfile       Source Path Dependency
AnnotationDbi                         1.52.0 Bioconductor    1.52.0 Bioconductor  [1]     direct
AnnotationFilter                      1.14.0 Bioconductor    1.14.0 Bioconductor  [1]   indirect
BH                                  1.78.0-0         CRAN  1.78.0-0         CRAN  [1]   indirect
BSgenome                              1.58.0 Bioconductor    1.58.0 Bioconductor  [1]   indirect
Biobase                               2.50.0 Bioconductor    2.50.0 Bioconductor  [1]   indirect
BiocFileCache                         1.14.0 Bioconductor    1.14.0 Bioconductor  [1]   indirect
BiocGenerics                          0.36.1 Bioconductor    0.36.1 Bioconductor  [1]   indirect
BiocManager                          1.30.18         CRAN   1.30.18         CRAN  [1]   indirect
BiocParallel                          1.24.1 Bioconductor    1.24.1 Bioconductor  [1]   indirect
BiocVersion                           3.12.0 Bioconductor    3.12.0 Bioconductor  [1]       <NA>
Biostrings                            2.58.0 Bioconductor    2.58.0 Bioconductor  [1]   indirect
DBI                                    1.1.3         CRAN     1.1.3         CRAN  [1]   indirect
DDRTree                                0.1.5         CRAN     0.1.5         CRAN  [1]   indirect
DelayedArray                          0.16.3 Bioconductor    0.16.3 Bioconductor  [1]   indirect
FNN                                  1.1.3.1         CRAN   1.1.3.1         CRAN  [1]   indirect
Formula                                1.2-4         CRAN     1.2-4         CRAN  [1]   indirect
GenomeInfoDb                          1.26.7 Bioconductor    1.26.7 Bioconductor  [1]   indirect
GenomeInfoDbData                       1.2.4 Bioconductor     1.2.4 Bioconductor  [1]   indirect
GenomicAlignments                     1.26.0 Bioconductor    1.26.0 Bioconductor  [1]   indirect
GenomicFeatures                       1.42.3 Bioconductor    1.42.3 Bioconductor  [1]   indirect
GenomicRanges                         1.42.0 Bioconductor    1.42.0 Bioconductor  [1]     direct
Gviz                                  1.34.1 Bioconductor    1.34.1 Bioconductor  [1]     direct
HSMMSingleCell                        1.10.0 Bioconductor    1.10.0 Bioconductor  [1]   indirect
Hmisc                                  4.7-1         CRAN     4.7-1         CRAN  [1]   indirect
IRanges                               2.24.1 Bioconductor    2.24.1 Bioconductor  [1]     direct
KernSmooth                           2.23-18         CRAN      <NA>         <NA>  [2]       <NA>
MASS                                7.3-58.1         CRAN  7.3-58.1         CRAN  [1]   indirect
Matrix                                 1.4-1         CRAN     1.4-1         CRAN  [1]     direct
MatrixExtra                           0.1.12         CRAN      <NA>         <NA>  [1]       <NA>
MatrixGenerics                         1.2.1 Bioconductor     1.2.1 Bioconductor  [1]   indirect
ProtGenerics                          1.22.0 Bioconductor    1.22.0 Bioconductor  [1]   indirect
R6                                     2.5.1         CRAN     2.5.1         CRAN  [1]     direct
RANN                                   2.6.1         CRAN     2.6.1         CRAN  [1]   indirect
RBGL                                  1.66.0 Bioconductor    1.66.0 Bioconductor  [1]   indirect
RColorBrewer                           1.1-3         CRAN     1.1-3         CRAN  [1]   indirect
RCurl                               1.98-1.8         CRAN  1.98-1.8         CRAN  [1]   indirect
RSQLite                               2.2.16         CRAN    2.2.16         CRAN  [1]   indirect
RUnit                                 0.4.32         CRAN    0.4.32         CRAN  [1]   indirect
Rcpp                                   1.0.9         CRAN     1.0.9         CRAN  [1]   indirect
RcppEigen                          0.3.3.9.2         CRAN 0.3.3.9.2         CRAN  [1]   indirect
RhpcBLASctl                       0.21-247.1         CRAN      <NA>         <NA>  [1]       <NA>
Rhtslib                               1.22.0 Bioconductor    1.22.0 Bioconductor  [1]   indirect
Rsamtools                              2.6.0 Bioconductor     2.6.0 Bioconductor  [1]   indirect
Rtsne                                   0.16         CRAN      0.16         CRAN  [1]   indirect
S4Vectors                             0.28.1 Bioconductor    0.28.1 Bioconductor  [1]     direct
SummarizedExperiment                  1.20.0 Bioconductor    1.20.0 Bioconductor  [1]   indirect
TxDb.Hsapiens.UCSC.hg19.knownGene      3.2.2 Bioconductor      <NA>         <NA>  [1]     direct
VGAM                                   1.1-7         CRAN     1.1-7         CRAN  [1]     direct
VariantAnnotation                     1.36.0 Bioconductor    1.36.0 Bioconductor  [1]   indirect
XML                                3.99-0.10         CRAN 3.99-0.10         CRAN  [1]   indirect
XVector                               0.30.0 Bioconductor    0.30.0 Bioconductor  [1]   indirect
ape                                    5.6-2         CRAN      <NA>         <NA>  [1]       <NA>
argparse                               2.1.6         CRAN     2.1.6         CRAN  [1]     direct
askpass                                  1.1         CRAN       1.1         CRAN  [1]   indirect
assertthat                             0.2.1         CRAN     0.2.1         CRAN  [1]     direct
backports                              1.4.1         CRAN     1.4.1         CRAN  [1]   indirect
base64enc                              0.1-3         CRAN     0.1-3         CRAN  [1]   indirect
biocViews                             1.58.1 Bioconductor    1.58.1 Bioconductor  [1]   indirect
biomaRt                               2.46.3 Bioconductor    2.46.3 Bioconductor  [1]   indirect
biovizBase                            1.38.0 Bioconductor    1.38.0 Bioconductor  [1]   indirect
bit                                    4.0.4         CRAN     4.0.4         CRAN  [1]   indirect
bit64                                  4.0.5         CRAN     4.0.5         CRAN  [1]   indirect
bitops                                 1.0-7         CRAN     1.0-7         CRAN  [1]   indirect
blob                                   1.2.3         CRAN     1.2.3         CRAN  [1]   indirect
boot                                  1.3-27         CRAN      <NA>         <NA>  [2]       <NA>
bslib                                  0.4.0         CRAN      <NA>         <NA>  [1]   indirect
cachem                                 1.0.6         CRAN     1.0.6         CRAN  [1]   indirect
checkmate                              2.1.0         CRAN     2.1.0         CRAN  [1]     direct
cicero                                 1.8.1 Bioconductor     1.8.1 Bioconductor  [1]     direct
class                                 7.3-18         CRAN      <NA>         <NA>  [2]       <NA>
cli                                    3.3.0         CRAN     3.3.0         CRAN  [1]   indirect
cluster                                2.1.4         CRAN     2.1.4         CRAN  [1]   indirect
clusterProfiler                         <NA>         <NA>      <NA>         <NA> <NA>     direct
coda                                  0.19-4         CRAN      <NA>         <NA>  [1]       <NA>
codetools                             0.2-18         CRAN      <NA>         <NA>  [2]       <NA>
colorspace                             2.0-3         CRAN     2.0-3         CRAN  [1]   indirect
combinat                               0.0-8         CRAN     0.0-8         CRAN  [1]   indirect
compiler                                <NA>         <NA>      <NA>         <NA>  [2]   indirect
cpp11                                  0.4.2         CRAN     0.4.2         CRAN  [1]   indirect
crayon                                 1.5.1         CRAN     1.5.1         CRAN  [1]   indirect
curl                                   4.3.2         CRAN     4.3.2         CRAN  [1]   indirect
data.table                            1.14.2         CRAN    1.14.2         CRAN  [1]     direct
dbplyr                                 2.2.1         CRAN     2.2.1         CRAN  [1]   indirect
deldir                                 1.0-6         CRAN     1.0-6         CRAN  [1]   indirect
densityClust                           0.3.2         CRAN     0.3.2         CRAN  [1]   indirect
dichromat                            2.0-0.1         CRAN   2.0-0.1         CRAN  [1]   indirect
digest                                0.6.29         CRAN    0.6.29         CRAN  [1]   indirect
dlstats                                0.1.5         CRAN      <NA>         <NA>  [1]       <NA>
docopt                                 0.7.1         CRAN     0.7.1         CRAN  [1]   indirect
dplyr                                  1.0.9         CRAN     1.0.9         CRAN  [1]     direct
ellipsis                               0.3.2         CRAN     0.3.2         CRAN  [1]   indirect
ensembldb                             2.14.1 Bioconductor    2.14.1 Bioconductor  [1]   indirect
evaluate                                0.16         CRAN      0.16         CRAN  [1]   indirect
fansi                                  1.0.3         CRAN     1.0.3         CRAN  [1]   indirect
farver                                 2.1.1         CRAN     2.1.1         CRAN  [1]   indirect
fastICA                                1.2-3         CRAN     1.2-3         CRAN  [1]   indirect
fastmap                                1.1.0         CRAN     1.1.0         CRAN  [1]   indirect
findpython                             1.0.7         CRAN     1.0.7         CRAN  [1]   indirect
float                                  0.3-0         CRAN      <NA>         <NA>  [1]       <NA>
foreign                               0.8-81         CRAN    0.8-81         CRAN  [2]   indirect
formatR                                 1.12         CRAN      1.12         CRAN  [1]   indirect
fs                                     1.5.2         CRAN      <NA>         <NA>  [1]   indirect
futile.logger                          1.4.3         CRAN     1.4.3         CRAN  [1]   indirect
futile.options                         1.0.1         CRAN     1.0.1         CRAN  [1]   indirect
generics                               0.1.3         CRAN     0.1.3         CRAN  [1]   indirect
ggfortify                             0.4.14         CRAN      <NA>         <NA>  [1]       <NA>
ggplot2                                3.3.6         CRAN     3.3.6         CRAN  [1]   indirect
ggrepel                                0.9.1         CRAN     0.9.1         CRAN  [1]   indirect
glasso                                  1.11         CRAN      1.11         CRAN  [1]   indirect
glue                                   1.6.2         CRAN     1.6.2         CRAN  [1]   indirect
grDevices                               <NA>         <NA>      <NA>         <NA>  [2]   indirect
graph                                 1.68.0 Bioconductor    1.68.0 Bioconductor  [1]   indirect
graphics                                <NA>         <NA>      <NA>         <NA>  [2]   indirect
grid                                    <NA>         <NA>      <NA>         <NA>  [2]     direct
gridExtra                                2.3         CRAN       2.3         CRAN  [1]   indirect
gtable                                 0.3.0         CRAN     0.3.0         CRAN  [1]   indirect
highr                                    0.9         CRAN       0.9         CRAN  [1]   indirect
hms                                    1.1.1         CRAN     1.1.1         CRAN  [1]   indirect
htmlTable                              2.4.1         CRAN     2.4.1         CRAN  [1]   indirect
htmltools                              0.5.3         CRAN     0.5.3         CRAN  [1]   indirect
htmlwidgets                            1.5.4         CRAN     1.5.4         CRAN  [1]   indirect
httr                                   1.4.4         CRAN     1.4.4         CRAN  [1]   indirect
igraph                                 1.3.4         CRAN     1.3.4         CRAN  [1]     direct
inspect                                0.1-2      unknown      <NA>         <NA>  [1]       <NA>
interp                                 1.1-3         CRAN     1.1-3         CRAN  [1]   indirect
irlba                                  2.3.5         CRAN     2.3.5         CRAN  [1]   indirect
isoband                                0.2.5         CRAN     0.2.5         CRAN  [1]   indirect
jpeg                                   0.1-9         CRAN     0.1-9         CRAN  [1]   indirect
jquerylib                              0.1.4         CRAN      <NA>         <NA>  [1]   indirect
jsonlite                               1.8.0         CRAN     1.8.0         CRAN  [1]   indirect
knitr                                   1.39         CRAN      1.39         CRAN  [1]     direct
labeling                               0.4.2         CRAN     0.4.2         CRAN  [1]   indirect
lambda.r                               1.2.4         CRAN     1.2.4         CRAN  [1]   indirect
lattice                              0.20-45         CRAN   0.20-45         CRAN  [1]   indirect
latticeExtra                          0.6-30         CRAN    0.6-30         CRAN  [1]   indirect
lazyeval                               0.2.2         CRAN     0.2.2         CRAN  [1]   indirect
lifecycle                              1.0.1         CRAN     1.0.1         CRAN  [1]   indirect
limma                                 3.46.0 Bioconductor    3.46.0 Bioconductor  [1]   indirect
logger                                 0.2.2         CRAN     0.2.2         CRAN  [1]     direct
magrittr                               2.0.3         CRAN     2.0.3         CRAN  [1]   indirect
markdown                                 1.1         CRAN      <NA>         <NA>  [1]       <NA>
matrixStats                           0.62.0         CRAN    0.62.0         CRAN  [1]   indirect
memoise                                2.0.1         CRAN     2.0.1         CRAN  [1]   indirect
memuse                                 4.2-1         CRAN      <NA>         <NA>  [1]       <NA>
methods                                 <NA>         <NA>      <NA>         <NA>  [2]     direct
mgcv                                  1.8-40         CRAN    1.8-40         CRAN  [1]   indirect
mime                                    0.12         CRAN      0.12         CRAN  [1]   indirect
monocle                               2.18.0 Bioconductor    2.18.0 Bioconductor  [1]     direct
munsell                                0.5.0         CRAN     0.5.0         CRAN  [1]   indirect
network                               1.17.2         CRAN      <NA>         <NA>  [1]       <NA>
nlme                                 3.1-159         CRAN   3.1-159         CRAN  [1]   indirect
nnet                                  7.3-15         CRAN    7.3-15         CRAN  [2]   indirect
openssl                                2.0.2         CRAN     2.0.2         CRAN  [1]   indirect
org.Hs.eg.db                          3.12.0 Bioconductor    3.12.0 Bioconductor  [1]     direct
parallel                                <NA>         <NA>      <NA>         <NA>  [2]   indirect
permute                                0.9-7         CRAN      <NA>         <NA>  [1]       <NA>
pheatmap                              1.0.12         CRAN    1.0.12         CRAN  [1]   indirect
pillar                                 1.8.0         CRAN     1.8.0         CRAN  [1]   indirect
pinfsc50                               1.2.0         CRAN      <NA>         <NA>  [1]       <NA>
pkgconfig                              2.0.3         CRAN     2.0.3         CRAN  [1]   indirect
plogr                                  0.2.0         CRAN     0.2.0         CRAN  [1]   indirect
plyr                                   1.8.7         CRAN     1.8.7         CRAN  [1]   indirect
png                                    0.1-7         CRAN     0.1-7         CRAN  [1]   indirect
prettyunits                            1.1.1         CRAN     1.1.1         CRAN  [1]   indirect
progress                               1.2.2         CRAN     1.2.2         CRAN  [1]   indirect
proxy                                 0.4-27         CRAN    0.4-27         CRAN  [1]   indirect
 [ reached 'max' / getOption("max.print") -- omitted 41 rows ]

[1]: /home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu
[2]: /usr/lib/R/library                                   

# ABI ================================
* No ABI conflicts were detected in the set of installed packages.

# User Profile =======================
[no user profile detected]

# Settings ===========================
List of 10
 $ bioconductor.version     : chr(0) 
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ r.version                : chr(0) 
 $ snapshot.type            : chr "implicit"
 $ use.cache                : logi TRUE
 $ vcs.ignore.cellar        : logi TRUE
 $ vcs.ignore.library       : logi TRUE
 $ vcs.ignore.local         : logi TRUE

# Options ============================
List of 9
 $ defaultPackages                     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method                : chr "libcurl"
 $ download.file.extra                 : NULL
 $ install.packages.compile.from.source: NULL
 $ pkgType                             : chr "source"
 $ repos                               : Named chr "https://cloud.r-project.org"
  ..- attr(*, "names")= chr "CRAN"
 $ renv.consent                        : logi TRUE
 $ renv.project.path                   : chr "/home/debian/R"
 $ renv.verbose                        : logi TRUE

# Environment Variables ==============
HOME                        = /home/debian
LANG                        = en_US.UTF-8
MAKE                        = make
R_LIBS                      = <NA>
R_LIBS_SITE                 = /usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library
R_LIBS_USER                 = /home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu:/usr/lib/R/library
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = /usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library
RENV_DEFAULT_R_LIBS_USER    = ~/R/x86_64-pc-linux-gnu-library/4.0
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = /home/debian/R

# PATH ===============================
- /sbin
- /usr/sbin
- /bin
- /usr/bin
- /usr/lib/rstudio-server/bin/quarto/bin
- /usr/lib/rstudio-server/bin/postback

# Cache ==============================
There are a total of 35 package(s) installed in the renv cache.
Cache path: "~/.cache/R/renv/cache/v5/R-4.0/x86_64-pc-linux-gnu"

This is the parent directory of my `renv` project folder

```
root@dc0aaef10db5:/home/debian# ls -a
.  ..  .bash_history  .cache  .config  .git  .gitignore  .local  Dockerfile  Makefile  R  README.txt  make_env  py
```

The project folder itself:

```
root@dc0aaef10db5:/home/debian/R# ls -a
.  ..  .Rhistory  .Rprofile  R.Rproj  projects  renv  renv.lock  x86_64-pc-linux-gnu-library
```

```
root@dc0aaef10db5:/home/debian/R# cat .Rprofile 
source("renv/activate.R")
```

Part of the log output:

```
* installing *source* package ‘tweenr’ ...
** package ‘tweenr’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-XqSJAD/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c along.cpp -o along.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-XqSJAD/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c at.cpp -o at.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-XqSJAD/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c cpp11.cpp -o cpp11.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-XqSJAD/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c easing.c -o easing.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-XqSJAD/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c element.cpp -o element.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-XqSJAD/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c element_at.cpp -o element_at.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-XqSJAD/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fill.cpp -o fill.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-XqSJAD/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c state.cpp -o state.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-z,relro -o tweenr.so along.o at.o cpp11.o easing.o element.o element_at.o fill.o state.o -L/usr/lib/R/lib -lR
installing to /home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/00LOCK-tweenr/00new/tweenr/libs
** R
** byte-compile and prepare package for lazy loading
# Bootstrapping renv 0.15.5 --------------------------------------------------
* Downloading renv 0.15.5 ... OK (downloaded source)
* Installing renv 0.15.5 ... Done!
Error installing renv:
======================
* installing *source* package ‘renv’ ...
** package ‘renv’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’
* removing ‘/home/debian/.cache/R/renv/library/tweenr-8a42f03e/R-4.0/x86_64-pc-linux-gnu/renv’
Warning messages:
1: In system2(r, args, stdout = TRUE, stderr = TRUE) :
  running command ''/usr/lib/R/bin/R' --vanilla CMD INSTALL --no-multiarch -l '/home/debian/.cache/R/renv/library/tweenr-8a42f03e/R-4.0/x86_64-pc-linux-gnu' '/tmp/Rtmp1MsKlY/renv_0.15.5.tar.gz' 2>&1' had status 1
2: Failed to find an renv installation: the project will not be loaded.
Use `renv::activate()` to re-initialize the project. 
** help
*** installing help indices
*** copying figures
** building package indices
# Bootstrapping renv 0.15.5 --------------------------------------------------
* Downloading renv 0.15.5 ... OK (downloaded source)
* Installing renv 0.15.5 ... Done!
Error installing renv:
======================
* installing *source* package ‘renv’ ...
** package ‘renv’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’
* removing ‘/home/debian/.cache/R/renv/library/tweenr-8a42f03e/R-4.0/x86_64-pc-linux-gnu/renv’
Warning messages:
1: In system2(r, args, stdout = TRUE, stderr = TRUE) :
  running command ''/usr/lib/R/bin/R' --vanilla CMD INSTALL --no-multiarch -l '/home/debian/.cache/R/renv/library/tweenr-8a42f03e/R-4.0/x86_64-pc-linux-gnu' '/tmp/RtmpKqXjn4/renv_0.15.5.tar.gz' 2>&1' had status 1
2: Failed to find an renv installation: the project will not be loaded.
Use `renv::activate()` to re-initialize the project. 
** testing if installed package can be loaded from temporary location
# Bootstrapping renv 0.15.5 --------------------------------------------------
* Downloading renv 0.15.5 ... OK (downloaded source)
* Installing renv 0.15.5 ... Done!
Error installing renv:
======================
* installing *source* package ‘renv’ ...
** package ‘renv’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’
* removing ‘/home/debian/.cache/R/renv/library/tweenr-8a42f03e/R-4.0/x86_64-pc-linux-gnu/renv’
Warning messages:
1: In system2(r, args, stdout = TRUE, stderr = TRUE) :
  running command ''/usr/lib/R/bin/R' --vanilla CMD INSTALL --no-multiarch -l '/home/debian/.cache/R/renv/library/tweenr-8a42f03e/R-4.0/x86_64-pc-linux-gnu' '/tmp/RtmpywlCt0/renv_0.15.5.tar.gz' 2>&1' had status 1
2: Failed to find an renv installation: the project will not be loaded.
Use `renv::activate()` to re-initialize the project. 
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
# Bootstrapping renv 0.15.5 --------------------------------------------------
* Downloading renv 0.15.5 ... OK (downloaded source)
* Installing renv 0.15.5 ... Done!
* Successfully installed and loaded renv 0.15.5.
Error: couldn't resolve renv project associated with path "/tmp/RtmphiWGQM/R.INSTALL49214b9081c0/tweenr"
Traceback (most recent calls last):
15: source("/home/debian/R/renv/activate.R")
14: withVisible(eval(ei, envir))
13: eval(ei, envir)
12: eval(ei, envir)
11: local(...)
10: eval.parent(substitute(eval(quote(expr), envir)))
 9: eval(expr, p)
 8: eval(expr, p)
 7: eval(quote(...), new.env())
 6: eval(quote(...), new.env())
 5: renv::load()
 4: project %||% renv_project_find(project)
 3: renv_project_find(project)
 2: stopf(fmt, renv_path_pretty(project))
 1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
ERROR: loading failed
* removing ‘/home/debian/R/renv/library/R-4.0/x86_64-pc-linux-gnu/tweenr’
* installing *source* package ‘polyclip’ ...
** package ‘polyclip’ successfully unpacked and MD5 sums checked
** using staged installation
# Bootstrapping renv 0.15.5 --------------------------------------------------
* Downloading renv 0.15.5 ... OK (downloaded source)
* Installing renv 0.15.5 ... Done!
Error installing renv:
======================
* installing *source* package 'renv' ...
** package 'renv' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
ERROR: hard-coded installation path: please report to the package maintainer and use '--no-staged-install'
* removing '/home/debian/.cache/R/renv/library/polyclip-c7df0764/R-4.0/x86_64-pc-linux-gnu/renv'
Warning messages:
1: In system2(r, args, stdout = TRUE, stderr = TRUE) :
  running command ''/usr/lib/R/bin/R' --vanilla CMD INSTALL --no-multiarch -l '/home/debian/.cache/R/renv/library/polyclip-c7df0764/R-4.0/x86_64-pc-linux-gnu' '/tmp/RtmpsVg315/renv_0.15.5.tar.gz' 2>&1' had status 1
2: Failed to find an renv installation: the project will not be loaded.
Use `renv::activate()` to re-initialize the project. 
...
Warning messages:
1: In install.packages(...) :
  installation of package ‘tweenr’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘polyclip’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘RcppArmadillo’ had non-zero exit status
4: In install.packages(...) :
  installation of package ‘fastmatch’ had non-zero exit status
5: In install.packages(...) :
  installation of package ‘tidygraph’ had non-zero exit status
6: In install.packages(...) :
  installation of package ‘ggfun’ had non-zero exit status
7: In install.packages(...) :
  installation of package ‘DO.db’ had non-zero exit status
8: In install.packages(...) :
  installation of package ‘cowplot’ had non-zero exit status
9: In install.packages(...) :
  installation of package ‘shadowtext’ had non-zero exit status
10: In install.packages(...) :
  installation of package ‘yulab.utils’ had non-zero exit status
```

**Comment by kevinushey** [comment]
If you need an escape hatch, you can use `renv::deactivate()` to temporarily disable `renv`. I'm going to see if I can reproduce the error you're describing locally.

**Comment by kevinushey** [comment]
It seems to work for me with a relatively "vanilla" `renv` project. Is it possible that your user profile, or site profile, contains a call to `source("renv/activate.R")`? That could lead `renv` to try and bootstrap itself even when installing a package, which would be undesired.

**Comment by kevinushey** [comment]
I don't have a good idea as to what's going on, but as a workaround you could use:

```
Sys.setenv(RENV_CONFIG_AUTOLOADER_ENABLED = FALSE)
```

to disable the `renv` autoloader when installing packages, so that `renv` doesn't try to bootstrap itself when packages are installed.
