### ISSUE TITLE
Inconsistent sources when snapshotting after installing new package

### ISSUE THREAD

**Issue by seasick** [rstudio/renv#1078]
When installing packages and snapshotting them I've encountered that renv would updates its lock file inconsistently.

For example, `R.utils` was updated from v2.11.0 to v2.12.0 while installing a new package. In `renv.lock` the package received a multitude of new properties (i.e. `RemoteRepos`, `RemoteSha` and others), but also the `Source` property was changed from `"Repository"` to `"CRAN"`.

Strangely the `R6` package, which was not updated, also received changes. The `Source` property was changed from `"CRAN"` to `"Reposiotry"` and a lot of properties were removed.

![image](https://user-images.githubusercontent.com/1318997/190095055-300e9d28-561f-4467-81ac-8bcfe666cfe3.png)

I'm not sure if this is a bug or I just have a poor understanding of how dependencies work with Renv.

**Comment by seasick** [comment]
Thank you @kevinushey for the explanation. 

For me personally it is now no longer an issue, but maybe a short hint in the documentation could help avoiding confusion for others.

**Comment by kevinushey** [comment]
Thanks; I added a vignette note in https://github.com/rstudio/renv/commit/b1364b90bb6fe5883df4b4f7445ba1a72d355409.
