### ISSUE TITLE
Does `equip()` give sufficient tools to install packages like nlopt?

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#108]
@kevinushey - As previously flagged to you I've been developing my own equip function of sorts for our corporate R package. I've been testing this fairly consistently for a good few months now on a windows server build machine to strong success coupled with packrat.

Worth linking this to you as there are some cpp libraries that I required to download that I don't think your equip function does. You can find the function [here](https://github.com/dfe-analytical-services/dfeR/blob/feature/rtools_pkgs/R/setup.R). I've been testing mine vs yours and if memory serves me right packages such as RCurl don't compile with equip. 

Another important thing to point out is that I've had to add the following (the RWINLIB bit) to the front of my local_libs within the last month:

```
LOCAL_LIBS = -L"$(RWINLIB)/lib$(R_ARCH)" -L"$(LOCAL_SOFT)/lib$(R_ARCH)" -L"$(LOCAL_SOFT)/lib"'

```

From what I can tell the [rwinlib](https://github.com/rwinlib) system dependencies that are downloaded by a number of packages have change structure in anticipation for the new rtools and this has caused older versions of some packages to not compile e.g. rgdal 1.3-6. This points it back to the right place and I don't think has any negative effects as will only point to something valid if such packages are downloaded. 

Leave it to you if you think any of this should make it into equip.

Cheers,

Adam

**Comment by adamrobinson361** [comment]
@kevinushey - is this something you would consider implementing before the CRAN release of renv? 

Conscious that it may put off a lot of windows users if they are immediately met with compilation errors. I think with my proposal 90% of these are addressed. 

Regards,

Adam

**Comment by adamrobinson361** [comment]
I can look into making a windows docker container and illustrating some tests if that helps?

**Comment by kevinushey** [comment]
Perhaps I can borrow from the list of packages you're using in https://github.com/dfe-analytical-services/dfeR/blob/feature/rtools_pkgs/R/setup.R -- would that be fair?

**Comment by adamrobinson361** [comment]
Feel free to - I’ve found this combination works well for the majority but am by no means an expert in it

**Comment by adamrobinson361** [comment]
Hi @kevinushey - not had much time to explore the docker testing. Is this something you could move forward with without?

**Comment by kevinushey** [comment]
Thanks! I think we can move forward without the Docker container.

Right now, the following packages are installed for Windows:

https://github.com/rstudio/renv/blob/52556ba4d8784cad933b0d8aaa6d0bbd057e7315/R/extsoft.R#L7-L8

I should extend that to `glpk`, `nlopt` and `GTK` as well.

**Comment by adamrobinson361** [comment]
Sounds perfect - my function has the changes to makevars required for reference. Note the local libs change mentioned above too which should be a more general requirement.

Cheers,

Adam

**Comment by adamrobinson361** [comment]
@kevinushey - anything I can do to support this being implemented. Would be great to retire my other function.

Cheers,

Adam

**Comment by hadley** [comment]
Is this still relevant?

**Comment by kevinushey** [comment]
We should see if packages like `nloptr` can be installed from sources easily with Rtools42 (or Rtools43)
