### ISSUE TITLE
Disable the second repo in renv

### ISSUE THREAD

**Issue by avraam-inside** [rstudio/renv#1080]
The `renv` uses two repo to host r-packages.
Example: 
![image](https://user-images.githubusercontent.com/52919010/190145937-b1f4af66-b0d8-4e70-81cc-3e23f490998a.png)

This creates a huge mass of problems! In some projects on different platforms, packages are installed in different repositories (directly in the `renv`-folder and in a second repo), and a package from the second repo can be written to `renv.lock`. I disabled the second repo in `.libPaths`, but the package continues to be called, although it is not in the `renv`-folder of the project. It's not clear what's going on at all.

It will be as comfortable and transparent as possible if `renv` works with only ONE repository, and not with two or more.

Request: tell me the most correct way to disable the second (and other) repository in renv, except for the first one, which leads to the `renv`-folder of the project

**Comment by kevinushey** [comment]
You probably want to enable the `renv` sandbox:

https://rstudio.github.io/renv/reference/config.html#renv-config-sandbox-enabled

This can be enabled with something like:

```
RENV_CONFIG_SANDBOX_ENABLED = TRUE
```

in your `.Renviron` file.

When enabled, `renv` will ensure that only 'base' packages (that is, packages distributed with R itself and required as part of the installation) are available in the system library path.

We don't enable this by default because the mechanism used to sandbox the system library can run into issues on systems that over-aggressively clean items in the temporary directory (where `renv` tries to create its symlinks). I'm hoping to find a better solution that allows us to enable the sandbox by default.

**Comment by avraam-inside** [comment]
Sorry, but `RENV_CONFIG_SANDBOX_ENABLED` doesn't solve the current problem.

I tried to illustrate it more clearly: 

![image](https://user-images.githubusercontent.com/52919010/190273653-ac551184-ae94-479a-909b-bc3a056838c7.png)

**Comment by kevinushey** [comment]
In the case of MASS (and other packages I see there), this is a so-called "recommended" package that's distributed with the builds of R on Windows + macOS, and because it's available "by default" in an R installation `renv` includes those in the sandboxed system library.

Note that this is a fairly hard requirement; `renv` requires a system library to be on the PATH (so you'll always see the first library path, the project library, and the final library path, the "system" library.)

The output of `renv::diagnostics()` might be helpful in understanding why the MASS package is entering the lockfile.

**Comment by avraam-inside** [comment]
1) I am using **Linux (Ubuntu)**. In this context, it is desirable not to mention other operating systems. If it is manage to fix the problem and there - ok, if not - also ok. Interesting fix in Linux.
2) Why is it necessary to use the "system" (second) repository in Linux Ubuntu? The second repository interferes with collecting statistics + makes it unclear how `renv` works, where packages are stored.
3) Expected behavior: do `renv::init` -> there is ONLY one repository (`renv/library/...`). There are NO other repositories of the second/third/"system"/etc. -> in the `renv/library/...` folder there will be 2 packages: `renv` and `base`. And both packages will be in `renv.lock`.

Could you tell me what do I need to do to make renv only work with one repository, please?

P.S.: because I did not ask for MASS to be installed + it is not in the renv/library directory - which means that the package should not be in the project in any form at all.

**Comment by avraam-inside** [comment]
Speaking of collecting statistics, here I am working with the commercial R Studio platform, where I wanted to collect complete statistics on packages, but NOT ALL got there (although I installed compiler explicitly with the version prescribed via `renv::install`!).

![image](https://user-images.githubusercontent.com/52919010/190685377-21109d7b-6209-4c09-8bf1-d32dab8d32bf.png)

Unlike the previous example, the package was not included in the statistics here.

The problem is that if there was ONE REPOSITORY, without an incomprehensible second one, the question would not have arisen at all. This is the most correct way to solve the problem - only one repository for all project packages in GENERAL (including base).

**Comment by kevinushey** [comment]
Did you already read the Getting Started guide at https://rstudio.github.io/renv/articles/renv.html?

> Speaking of collecting statistics, here I am working with the commercial R Studio platform

If you are an RStudio professional customer, I would recommend opening a ticket with the professional support team.

> Why is it necessary to use the "system" (second) repository in Linux Ubuntu? The second repository interferes with collecting statistics + makes it unclear how renv works, where packages are stored.

This is part of how R works internally. It uses separate library paths for different R packages. Packages distributed with R are installed into the system library, and packages installed by users are (typically) installed into a user library. Administrators can, of course, install packages into the system library if desired, but it's generally best to consider the system library "frozen" and instead install such packages into (for example) the R site libraries.

> older there will be 2 packages: renv and base

This is not possible. R depends on all so-called "base" packages and expects those to always be available. Those packages can be seen with `installed.packages(priority = "base")`. For example:

```
> rownames(installed.packages(priority = "base"))
 [1] "base"      "compiler"  "datasets"  "graphics"  "grDevices" "grid"
 [7] "methods"   "parallel"  "splines"   "stats"     "stats4"    "tcltk"
[13] "tools"     "utils"
```

> Could you tell me what do I need to do to make renv only work with one repository, please?

For reference, these are called library paths, not repositories. Repositories (e.g. CRAN) are used to host R packages, and is where packages are retrieved when e.g. `install.packages()` is called.

Packages do not enter the `renv.lock` lockfile immediately after package installation; they only do after `renv::snapshot()` is called, and only if that package is eligible for entry in the lockfile. See https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile for more details.

> The problem is that if there was ONE REPOSITORY, without an incomprehensible second one, the question would not have arisen at all. This is the most correct way to solve the problem - only one repository for all project packages in GENERAL (including base).

If you _really_ want this, then don't use `renv` -- instead, use an administrator account and run:

```
.libPaths(.Library)
```

in your R session, to ensure only the system library is used for package installation. Again, though, it seems unlikely that this is what you actually require (but I don't know all the specifics of how you're using R in your environment).

**Comment by avraam-inside** [comment]
> Did you already read the Getting Started guide at https://rstudio.github.io/renv/articles/renv.html?

Of course I read it. But I don't see there any information about the second "system"library path.

> If you are an RStudio professional customer, I would recommend opening a ticket with the professional support team.

So that they redirect me to the contributors of renv, who described the logic of filling renv.lock in the code?)

> Packages distributed with R are installed into the system library, and packages installed by users are (typically) installed into a > user library. 
> 
> older there will be 2 packages: renv and base
> 
> This is not possible. R depends on all so-called "base" packages and expects those to always be available. Those packages > can be seen with installed.packages(priority = "base")

Surely this is possible. If it is possible to change the path for storing system packages from one to another, then it is also possible to specify the renv folder as the location point for system packages. As a last resort, you can request improvements from the R Team (if there really are specific problem points, which is not a fact).

But if you have no desire to improve this moment, I am powerless here.

It all sounds sad.

Thanks for the relatively detailed answer!

PS: Apparently, I will be using crutches. Now I'll dig in the direction of setting up get Option("defaultPackages") so that only base swings to the system library, for example.
https://rstudio.github.io/r-manuals/r-admin/Add-on-packages.html
