### ISSUE TITLE
install() docs: include info/examples on installing from private repos 

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/renv#1082]
It would be helpful if the [`install()` docs](https://rstudio.github.io/renv/reference/install.html) included info on installing from private repos (e.g., linking to https://rstudio.github.io/renv/articles/renv.html#authentication).

**Comment by kevinushey** [comment]
Done in https://github.com/rstudio/renv/commit/e74a4a9f66441376fd9f67eb80a0be1e3f2052c0; thanks!
