### ISSUE TITLE
renv::use not working as expected when passing in a lockfile and setting a library path

### ISSUE THREAD

**Issue by kmkramer23** [rstudio/renv#1083]
I am having a problem getting renv::use() to work correctly when attempting to supply an renv lock file and setting the library path in the call.  

Example:  renv::use(lockfile = "/home/kkrame02/mylockfile/renv.lock",
                               library  = "/home/kkrame02/test/library",
                               isolate  = TRUE,
                               verbose  = TRUE,
                               )

When I call the function the first time and check out the .libPaths() it points toward the project /home/kkrame02/mytest/library/R-4.0/x86_64-pc-linux-gnu location.  When I run the same renv:use call a second time and check the .libPaths() location it points toward the library location specified above and all subsequent runs will now point towards the library path set above.  

It appears the first time I run the code it goes to activate the project and modifies the libpath to the library folder within the projects renv folder, but after the project is activated all future calls to renv::use() by-pass that section of code and retain my library path set above.  Is this working as intended?

**Comment by kevinushey** [comment]
Thanks -- this seems like a genuine bug; however, I wasn't able to reproduce locally. Can you provide any more details?

You might also want to try and see whether you can reproduce with the development version of `renv`.

**Comment by kmkramer23** [comment]
Thanks for the quick response.  I was using version 0.14 of renv which calls restore() inside the use() function without setting the prompt parameter.  It appears this was changed in a later version to call restore() with prompt equal to FALSE so activate does not run anymore when calling renv::use().  Is this correct that activate will no longer be called within renv::use()?

Now, when I test using the latest version with the isolate parameter set to TRUE, it does not isolate just the packages in my lock file.  When I do .libPaths(), the first path is /home/kkrame02/test/library, which currently is empty, and the second path points toward all the system library packages from "/opt/R/4.0.5/lib/R/library". Is /home/kkrame02/test/library empty because all the packages in my lock file match what is in the system library?  Should isolate = TRUE only show the packages from my lock file?

**Comment by kevinushey** [comment]
> Now, when I test using the latest version with the isolate parameter set to TRUE, it does not isolate just the packages in my lock file. When I do .libPaths(), the first path is /home/kkrame02/test/library, which currently is empty, and the second path points toward all the system library packages from "/opt/R/4.0.5/lib/R/library". Is /home/kkrame02/test/library empty because all the packages in my lock file match what is in the system library? Should isolate = TRUE only show the packages from my lock file?

That sounds plausible, but a reproducible example would help me know for sure.

**Comment by kmkramer23** [comment]
I grabbed the most recent version 0.16 of renv and tested the isolate parameter again in renv::use().  I was hoping it would sandbox the system library when isolate was set to TRUE but it did not.  I ended up calling renv_sandbox_activate to force the sandboxing of the system library, which in turn forces my renv::use library to be built containing all the items in my lock file.  Should sandboxing be built into renv::use when isolate is true or is it already?  The example below was based on the example from https://rstudio.github.io/renv/articles/use.html only using a lockfile.  [renv.lock](https://github.com/rstudio/renv/files/9719173/renv.txt)

renv:::renv_sandbox_activate()
renv::use(lockfile = "/home/kkrame02/mylockfile/renv.lock",
               library = "/home/kkrame02/test/library",
               isolate = TRUE,
               verbose = TRUE,
)
digest::digest(list(answer = 42))

My other question concerning renv::use is the case when running in RStudio and "show diagnostics for R" is turned on.  RStudio scans the code and loads any packages it finds in the script via a namespace.  Does this mean that when the code above is sourced it first loads digest from the version in the current user or system library and by the time renv::use sets up the environment its to late because digest has already been loaded so its not going to use the version from the lock file?

**Comment by kevinushey** [comment]
> I grabbed the most recent version 0.16 of renv and tested the isolate parameter again in renv::use(). I was hoping it would sandbox the system library when isolate was set to TRUE but it did not.

This is different from what the `isolate` argument does. With renv 0.16.0, you should now see the renv sandbox enabled by default; that is, the system library should be sandboxed so only base + recommended packages are visible.

If you're not seeing that, then you most likely have something like `RENV_CONFIG_SANDBOX_ENABLED = FALSE` somewhere -- but `renv::diagnostics()` would probably help.

> My other question concerning renv::use is the case when running in RStudio and "show diagnostics for R" is turned on. RStudio scans the code and loads any packages it finds in the script via a namespace. Does this mean that when the code above is sourced it first loads digest from the version in the current user or system library and by the time renv::use sets up the environment its to late because digest has already been loaded so its not going to use the version from the lock file?

The version of the package currently visible on the library paths will be used. For this reason, we generally recommend using `renv::use()` in scripts that you run separately (e.g. as RStudio jobs) and rely on the regular `renv` project infrastructure for code you want to run interactively.

**Comment by kmkramer23** [comment]
If I just run the code below from a new session of r within a script file without anything set including the RENV_CONFIG_SANDBOX_ENABLED it does not sandbox the system library.  

renv::use(lockfile = "/home/kkrame02/mylockfile/renv.lock",
    library = "/home/kkrame02/test/library",
    isolate = TRUE,
    verbose = TRUE,
)

The only way I can get it to sandbox the system library using renv::use running on linux-ubuntu-bionic is to call the function renv:::renv_sandbox_activate() before calling renv::use().
