### ISSUE TITLE
renv::install()  to skip already installed packages

### ISSUE THREAD

**Issue by pedrobtz** [rstudio/renv#1085]
Is there a way to run `renv::install()` on a project that uses DESCRIPTION file to keep packages dependencies, and `renv::install()` will ignore already installed packages and only install if required?

With version `0.15.5` it always installs packages if a newer version is available.

**Comment by kevinushey** [comment]
I think `renv::hydrate(update = FALSE)` should get you close -- does this do what you need?

**Comment by pedrobtz** [comment]
There are two "problems" with `renv::hydrate(update=FALSE)`:

1. First, even if `sources = .libPaths()` it copies all dependencies to `.libPaths()[1]`, which is not desirable;

2. Second, `deps <- renv_hydrate_dependencies(...)` list all recursive dependencies (including "Suggests" of packages) of the project. It is unclear if it looks at DESCRIPTION file or not.

**Comment by kevinushey** [comment]
The other option that I think would work would be explicitly declaring the package versions you want in the `DESCRIPTION` file, e.g.

```
Imports:
    dplyr (== 1.0.9)
```

That's still perhaps not ideal, though. I'll have to think about this more.

**Comment by pedrobtz** [comment]
The desire behaviour would be equivalent to:
```
ls_pkgs <- renv:::renv_dependencies_discover("DESCRIPTION", errors = NULL, progress = F)

lapply(ls_pkgs$Package, function(x){
  if(!require(x, character.only = T, quietly = T))
    install.packages(x)
})
```

**Comment by hadley** [comment]
This appears to be how `install()` does behavour — if you call it twice, the second time will do nothing because all the packages are already installed.
