### ISSUE TITLE
renv::install() not impacted by `renv.config.repos.override` option

### ISSUE THREAD

**Issue by thebioengineer** [rstudio/renv#1086]
The option "renv.config.repos.override" is used to set whether renv::restore uses the lock files repo settings or the R sessions repos options. I would think having renv::install() follow this option would make sense as well, or the ability to set them.

**Comment by hadley** [comment]
Is there a reason you don't want to update the repos in the snapshot file? (i.e. with `options(repos = ...)` then `renv::snapshot()`)

**Comment by hadley** [comment]
Since it's been a couple of weeks and we haven't anything more, I'm going to close this issue.
