### ISSUE TITLE
Add `dependencies` argument to `renv::install()` so that Suggests deps can be ignored

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/renv#1087]
With `renv::settings$snapshot.type("explicit")`, `renv::install()` will install all package dependencies from the `DESCRIPTION` file, although the snapshot will only include the package listed in `renv::settings$package.dependency.fields()`, typically `Imports, Depends, LinkingTo`.

It would be helpful to have a `dependencies` argument in `renv::install()` that could be used to ignore or include `Suggests` dependencies. The default behavior of installing everything in the `DESCRIPTION` is great, but I've been running into circumstances where I only want to use `renv::install()` to install the package dependencies that are included in the snapshot.

**Comment by nikolas-burkoff** [comment]
Yes, I'd find this really helpful as well 👍

**Comment by GitHunter0** [comment]
Yes, this is important. It would also be great to be able to have install everything but excluding "Suggests" when creating the snapshot.

**Comment by kevinushey** [comment]
I've made a change supporting this workflow here:

https://github.com/rstudio/renv/commit/e39906fdc5763ef50dbbc6b88ff156f721e6f444

You should now be able to run something like

```
renv::install(dependencies = "most")
```

to install package dependencies including suggests. Other field names like `Config/Needs/dev` should be supported as well.
