### ISSUE TITLE
Can I change the path for my Conda environment.yml file when I run `renv::snapshot()`

### ISSUE THREAD

**Issue by lucygarner** [rstudio/renv#1089]
Hi,

When I run `renv::snapshot()`, it generates a `environment.yml` file in the directory containing `.Rproj`. Is there a way to change the name of the file and the directory that it is saved to?

Best wishes,
Lucy

**Comment by kevinushey** [comment]
It's not currently possible, but it would be straightforward for us to support:

https://github.com/rstudio/renv/blob/13bee3e31ab41a8ab20a98f13c7662c0192fb2c4/R/python-conda.R#L32

What path were you hoping to use? Is this something you want to configure on a project-specific basis, or globally?

**Comment by lucygarner** [comment]
Thank you. Yes, I saw that it was hard coded. I would like to configure the path on a project-specific basis.

**Comment by kevinushey** [comment]
Thanks -- I've made a change in the development version of `renv` that allows this to be controlled via the `RENV_PATHS_CONDA_EXPORT` environment variable.

**Comment by lucygarner** [comment]
Great, thank you!
