### ISSUE TITLE
Unclear how to merge separate cache locations

### ISSUE THREAD

**Issue by wtimmerman-fitp** [rstudio/renv#1092]
This is a question, possibly a feature request. 

**Problem**: I have been using renv for a while now, and I somehow have separate renv caches at two locations on my machine. Both caches include packages from R 3.6, 4.0, and 4.1, which seems rather space inefficient. I didn't set two different cache locations manually, so I assume it's the result of renv updates over the past years.

![renv caches](https://user-images.githubusercontent.com/61324620/195134130-f16ea7fd-76bd-4c4d-9e03-a8b95586b7a2.PNG)

The two paths are those described in the [renv paths docs](https://rstudio.github.io/renv/reference/paths.html) [NOTE: edited to reflect comment below]:

* ~New~ Old default cache location: ```%LOCALAPPDATA%/renv```
* ~Old~ New default cache location ~(though somehow my new 4.2 caches are showing up here)~: ```%LOCALAPPDATA%/R/cache/R/renv```

I have no renviron modifications related to renv other than ```RENV_CONFIG_SANDBOX_ENABLED=FALSE```, these are the relevant parts of Sys.getenv():
```
RENV_CONFIG_SANDBOX_ENABLED                FALSE
RENV_DEFAULT_R_ENVIRON                     <NA>
RENV_DEFAULT_R_ENVIRON_USER                <NA>
RENV_DEFAULT_R_LIBS                        <NA>
RENV_DEFAULT_R_LIBS_SITE                   C:/PROGRA~1/R/R-4.2.1/site-library
RENV_DEFAULT_R_LIBS_USER                   C:\Users\myname\AppData\Local/R/win-library/4.2
RENV_DEFAULT_R_PROFILE                     <NA>
RENV_DEFAULT_R_PROFILE_USER                <NA>
RENV_PROJECT                               C:/Users/myname/Documents/etcetc
```

**Desired outcome**: all projects refer to a package cache in one place with no duplication elsewhere.

**Question**: Is there a suggested way to merge the two caches without breaking references in all my projects? Do i just modify the RENV_PATHS_ROOT environmental variable and merge the caches myself? If i do that, do i need to manually combine the 'projects' file that's in each cache? 

If there's no way to do this programmatically, a function in renv might be nice; probably a bit out of my wheelhouse to do it in a safe way for renv but am willing to offer myself up as a tester!

**Comment by kevinushey** [comment]
Thanks for the bug report! I think I need to clarify the documentation here, since the second set of paths is the new default:

```
> renv::paths$cache()
[1] "C:\\Users\\kevin\\AppData\\Local/R/cache/R/renv/cache/v5/R-4.2/x86_64-w64-mingw32"
> packageVersion("renv")
[1] ‘0.16.0’
> getRversion()
[1] ‘4.2.1’
```

There's probably a way to merge the two caches using robocopy (or rsync on Unix). I haven't tested but something like this might do what you need:

```
robocopy /path/to/old/renv/cache /path/to/new/renv/cache /E
```

**Comment by kevinushey** [comment]
Handling this programmatically is a little bit difficult, because (in theory) some `renv` projects might refer to one version of the cache, and other `renv` projects might refer to another version of the cache. `renv::restore()` should still be smart enough to find the package entries in the "new" cache location but because of this providing some programmatic support for this will require some extra thought.

**Comment by wtimmerman-fitp** [comment]
@kevinushey : should I only copy renv/cache, or the entire renv folder with mran, binary, extsoft, source, etc.? I did the latter and that seemed fine, but thought I'd confirm.

In any case, if someone stumbles upon this thread, this worked well for me:
1. Copy entire renv folder to new location with robocopy
```robocopy /path/to/old/renv /path/to/new/renv /E```
2. Open an older project that uses the old cache location, and upgrade renv with renv::upgrade()
3. Restore using renv::restore()

That seemed to produce the desired effect where the 'old' package files used by these old repos/projects were relinked from the cache without needing to fully reinstall. Nice! 

A few tips for others who might stumble upon this issue:

- I happened to leave RStudio open with a project pointed at the earlier renv cache location while i ran robocopy--this lead to some hiccups in the copying process where certain files were in use, but once I closed out, it resolved okay and the skipped items were eventually copied over. Took about an hour for 10 GB. There didn't seem to be any conflict between packages that might have already existed at the new renv cache location, though I admittedly didn't check closely.
- As is probably obvious, don't forget to upgrade renv first. On the first project/repo I tried I didn't do this and renv version 0.13.2 just created the previous cache location, also didn't restore cleanly. A few older repos when opened in RStudio would bootstrap renv and create a new renv folder at the old location, but not very surprising, not a big deal. After doing renv::upgrade() the restore would happen from the new location.

**Comment by kevinushey** [comment]
Glad to hear everything seems to have gone smoothly!

You should only need the cache folder -- the other pieces are optional, but might be used if you needed to re-install packages from sources / binaries directly (rather than reusing the cached version). If those files aren't available, then `renv` will just try to retrieve them from the appropriate remote source (e.g. CRAN for packages installed from CRAN)

**Comment by wtimmerman-fitp** [comment]
Yes, thank you for all the help and work on the package!
