### ISSUE TITLE
renv::load() duplicating paths in the PATH environment variable

### ISSUE THREAD

**Issue by lucygarner** [rstudio/renv#1095]
Hi,

`renv::load()` appears to be duplicating some of the paths in the `PATH` environment variable.

In my R project, I run the following prior to loading `renv`.
`renv:::renv_envvar_get("PATH")`

> [1] "/Users/lucy/Library/r-miniconda/condabin:/Users/lucy/Documents/2022/devel/10x/R/.conda_env/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/lucy/Applications/quarto/bin:/usr/texbin:/Applications/RStudio.app/Contents/MacOS"

Then I run `renv::load()` and `renv:::renv_envvar_get("PATH")`.

> [1] "/Users/lucy/Library/r-miniconda/condabin:/Users/lucy/Documents/2022/devel/10x/R/.conda_env/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/X11/bin:/Library/TeX/texbin:/Users/lucy/Library/r-miniconda/condabin:/Users/lucy/Documents/2022/devel/10x/R/.conda_env/bin:/Users/lucy/Applications/quarto/bin:/usr/texbin:/Applications/RStudio.app/Contents/MacOS"

I have `RENV_AUTOLOADER_ENABLED = FALSE` in my `.Renviron`.

Best wishes,
Lucy

**Comment by kevinushey** [comment]
IIUC these are the two path entries getting duplicated:

```
/Users/lucy/Library/r-miniconda/condabin
/Users/lucy/Documents/2022/devel/10x/R/.conda_env/bin
```

Do you know where these path entries are originally being set?

The output of the following might be helpful:

```
trace(Sys.setenv, quote({
  dots <- list(...)
  if ("PATH" %in% names(dots)) {
    print(rlang::trace_back())
  }
}), print = FALSE)
renv::load()
```

**Comment by lucygarner** [comment]
Yes correct.

```
trace(Sys.setenv, quote({
  dots <- list(...)
  if ("PATH" %in% names(dots)) {
    print(rlang::trace_back())
  }
}), print = FALSE)
```

> Tracing function "Sys.setenv" in package "base"
> [1] "Sys.setenv"

Is that what you wanted me to run?

**Comment by kevinushey** [comment]
Please also run renv::load() after running that code.

**Comment by lucygarner** [comment]
I had to run `renv::load()` prior to `trace` since otherwise I get an error that there is no package called `rlang`.

So I ran:
```
renv::load()
trace(Sys.setenv, quote({
    dots <- list(...)
    if ("PATH" %in% names(dots)) {
        print(rlang::trace_back())
    }
}), print = FALSE)
renv::load()
```

And got the following:
```
    ▆
 1. └─renv::load()
 2.   └─renv:::renv_load_path(project)
 3.     └─base::Sys.setenv(PATH = paste(mix, collapse = .Platform$path.sep))
    ▆
 1. └─renv::load()
 2.   └─renv:::renv_load_python(project, lockfile$Python)
 3.     └─renv:::renv_envvar_prepend("PATH", bindir)
 4.       └─renv:::renv_envvar_modify(envvar, value, TRUE)
 5.         ├─base::do.call(Sys.setenv, as.list(new))
 6.         └─base (local) `<fnctnWtT>`(PATH = "/Users/lucy/Documents/2022/devel/10x/R/.conda_env/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/X11/bin:/Library/TeX/texbin:/Users/lucy/Library/r-miniconda/condabin:/Users/lucy/Documents/2022/devel/10x/R/.conda_env/bin:/Users/lucy/Applications/quarto/bin:/usr/texbin:/Applications/RStudio.app/Contents/MacOS")
    ▆
 1. └─renv::load()
 2.   └─renv:::renv_load_python(project, lockfile$Python)
 3.     └─renv:::renv_envvar_prepend("PATH", dirname(conda))
 4.       └─renv:::renv_envvar_modify(envvar, value, TRUE)
 5.         ├─base::do.call(Sys.setenv, as.list(new))
 6.         └─base (local) `<fnctnWtT>`(PATH = "/Users/lucy/Library/r-miniconda/condabin:/Users/lucy/Documents/2022/devel/10x/R/.conda_env/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/X11/bin:/Library/TeX/texbin:/Users/lucy/Library/r-miniconda/condabin:/Users/lucy/Documents/2022/devel/10x/R/.conda_env/bin:/Users/lucy/Applications/quarto/bin:/usr/texbin:/Applications/RStudio.app/Contents/MacOS")
```

**Comment by kevinushey** [comment]
Thanks! I believe this will be fixed via https://github.com/rstudio/renv/commit/97f66204826e7da4844ad295cfad331705cf5c82.

**Comment by lucygarner** [comment]
Great thanks.

**Comment by kevinushey** [comment]
Thanks -- I'll have to take another look and see if I can figure out why...

**Comment by hadley** [comment]
I'm still seeing this too:

``` r
Sys.setenv("PATH" = "/opt/homebrew/bin/:/bin")
renv::scaffold()
#> * renv infrastructure has been generated for project "/private/tmp/RtmpQVJX13/reprex-13dda40d69662-odd-tuna".
strsplit(Sys.getenv("PATH")[[1]], ":")
#> [[1]]
#> [1] "/opt/homebrew/bin/" "/bin"
renv::load()
strsplit(Sys.getenv("PATH")[[1]], ":")
#> [[1]]
#> [1] "/opt/homebrew/bin/" "/opt/homebrew/bin/" "/bin"
```

<sup>Created on 2023-05-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
