### ISSUE TITLE
Add feature to flag if rendered documents do not correspond to current lockfile

### ISSUE THREAD

**Issue by eliocamp** [rstudio/renv#1099]
When managing a project that creates documents with RMarkdown/quarto someone can render a document and then update packages and change the lockfile. This will lead to a project in an "invalid state" in which the code used a different environment that the one stated in the lockfile. Or someone could updated  packages, run the code and forget to update the lockfile, again leading to a mismatch. 

Currently, there's no way that I know of to tell if a project is in one of these situations. 

I imagine that this could be controlled by versioning the lockfile, perhaps just with hashes, and attaching the current version to the rendered document somehow. Perhaps as a colophon inside the document or, with hidden, machine-readable metadata embedded in the file, or using a specific file for the job. 
Then, one could compare the current lockfile hash with the document lockfile hash to see if the project is valid or not. 

EDIT: Although this wouldn't work in the situation of the lockfile being out of sync with the project library. 

Is this in scope for renv?

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding, but there's two ways that `renv` will inform you of this situation.

- You can explicitly call `renv::status()` to check whether the lockfile + library are in sync,
- You can let `renv` inform you on startup, e.g.

```
* Project '~/scratch/example' loaded. [renv 0.16.0]
* The project library is out of sync with the lockfile.
* Use `renv::restore()` to install packages recorded in the lockfile.
```

If you want to embed an `renv` lockfile directly into a document, you can use `renv::embed` -- see the documentation for more details.

**Comment by eliocamp** [comment]
`renv::status()` checks if the current lockfile and library are in sync, but it doesn't tell you anything about the status of the library when a specific version of a document was rendered. 

I'm thinking of this case:

1. The author updates packages
3. they render the document. 
4. they commit everything and push it to their repo.

Now the status of the remote repository is not valid (the document was not rendered with the published lockfile!) but from outside it's impossible to tell. If I download the repo I might not get the same results (or the code might not even run) and I would be very puzzled about why. 

Another similar situation would be if 

1. The author renders the document
2. they update packages and update the lockfile
3. they commit everything and push it into their repo. 

Again, the external user cannot tell that the repo is not "valid" (in this case, not even the author can actually tell that anything is wrong). Maybe you could get to the issue by carefully examining the commit history and realising that the lockfile was changed after the last rendered version of the document. 

A simple diagnosis would be a function that added the current library status (that is, a lockfile representing the library in its current state, not the lockfile, which could be outdated) to the document. Maybe as embeded metadata or a hash or something like that. Then, another function that extracted that information and compared it with the current library and/or lockfile. 

With this, an external user could easily tell at least if a rendered document was rendered with the current lockfile/library or a different one.

**Comment by kevinushey** [comment]
Thanks! I understand better what you mean now.

> A simple diagnosis would be a function that added the current library status (that is, a lockfile representing the library in its current state, not the lockfile, which could be outdated) to the document. Maybe as embeded metadata or a hash or something like that. 

You can embed the current library state (as a lockfile) with:

`````
```{r}
renv::snapshot(reprex = TRUE)
```
`````

The argument name `reprex` here is because this was initially developed to support the [reprex](https://github.com/tidyverse/reprex) package.

This doesn't directly solve your issue, though, since it's not easy to see at a glance if the lockfile is different from whatever is current in the repository.

> Then, another function that extracted that information and compared it with the current library and/or lockfile.

The main challenge is figuring out when, or how, we should compare the rendered document with the lockfile. What would the API in `renv` for this look like? Would we just scan for rendered documents (`.html`? `.pdf`?) and see which of those included embedded data about the lockfile, and warn if they didn't match a project lockfile? Or does the user have to explicitly call some `renv` function here? If we perform the scanning, when would that happen -- as part of `renv::status()`, or something else?

**Comment by eliocamp** [comment]
> This doesn't directly solve your issue, though, since it's not easy to see at a glance if the lockfile is different from whatever is current in the repository.

Yeah, nor whether the lockfile embedded in the document was up-to-date at the time. 

> The main challenge is figuring out when, or how, we should compare the rendered document with the lockfile

I'd say that running it automatically might not be feasible since I don't see how renv could know which documents to check. Also, in a repository there might be lots of documents that are not the main report (thinking, for example, about a paper with some supplemental documents that created as part of preliminary exploration). So a function that needs to be run by the user might be better. In any case, if this feature is deemed relevant, the first step would be to add the function and then with time it can be automated or not. 

Something a bit more challenging, I think, might be how to entice people to embed their library status. It would be ideal to embed it by default, but I don't know how that would be possible. Overload `rmarkdown::render`?

**Comment by hadley** [comment]
Given the many ways folks might want the output from `renv::snapshot(reprex = TRUE)` to be included, I think the best thing we can do to is to encourage folks who want this to do it themselves.
