### ISSUE TITLE
create lockfile for entire cache

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#1100]
Right now I find the `lockfile` argument of `renv::restore` to be very useful. I can migrate _a project_ from one cache location (or system) to another, or a new version of R for instance, simply by restoring the project's lockfile. In my renv setup, many R users are sharing the same renv cache. That means if there is a migration (or new R version) everyone needs to do their own restore in order to capture all installed packages (and rebuild them).

I think it would be nice if there was a way to create a lockfile of all packages in a cache, perhaps limited to a specific version of R. I could then restore the cache so all packages exist again. This would be particularly useful in environments where write permissions are limited for users and admins want to perform the cache migration.

**Comment by kevinushey** [comment]
The main challenge for this is that, by default, an `renv` lockfile can only have one entry per package, whereas a cache may have multiple different versions of a particular package installed.

There's also some potential ambiguity in migrating an existing cache, as `renv` doesn't keep track of a package's build-time dependencies -- e.g. if a package depends on Matrix, we don't know what version of Matrix was available when that package was installed. (Usually this shouldn't matter, but unfortunately sometimes it does.)

All that said, you could build something that approximates this using some `renv` internals, where you construct something like a lockfile (that is, a list of package records):

```
# get a list of package records
cache <- renv::paths$cache()
descpaths <- list.files(cache, pattern = "DESCRIPTION", recursive = TRUE, full.names = TRUE)
records <- lapply(descpaths, renv:::renv_snapshot_description)

# save and restore that 'records' object, e.g. using saveRDS and readRDS
# on another machine, install the requisite packages in that lockfile one-by-one?
```

Is it possible that this (or some form of this) would be enough for your use case?
