### ISSUE TITLE
Missing OS_type since `renv` 0.16.0

### ISSUE THREAD

**Issue by eastclintw00d** [rstudio/renv#1102]
Since updating to `renv` 0.16.0 I have trouble making snaptshots in some projects. I receive the following message: 

```
> renv::snapshot()
Error: lexical error: invalid char in json text.
          : "0.16.0",       "OS_type": NA,       "NeedsCompilation": "
                     (right here) ------^
```

I have seen it unter windows as well as under linux. Any idea what went wrong?

**Comment by eastclintw00d** [comment]
Re-initializing the project solved the issue for me but shouldn't the update work properly?

**Comment by kevinushey** [comment]
Thanks for the bug report! I think this is a bug with the `renv` JSON serializer; we're writing an `NA` value which `jsonlite` correctly rejects. I will take a look.
