### ISSUE TITLE
Unexpected behavior cellar and github

### ISSUE THREAD

**Issue by Klesel** [rstudio/renv#1106]
I have observed a behavior that might be an issue (at least from my perspective).

I use a package cellar as suggested in the vignette (https://rstudio.github.io/renv/articles/cellar.html). In short, I created a new folder  renv/cellar and stored a package.

Since this package is rather small, I would like to push it on github which is why I removed this path in the .gitignore file (renv/.gitignore).

However, everytime I activate the library (i.e., renv::activate()) the .gitignore will be updated and the cellar will be excluded. 

I would expect that removing the cellar from .gitignore will not change when using renv in a project.

**Comment by kevinushey** [comment]
Try:

```
renv::settings$vcs.ignore.cellar(FALSE)
```

**Comment by Klesel** [comment]
That works perfectly. Thanks!
