### ISSUE TITLE
Is there a JSON schema for the renv.lock format?

### ISSUE THREAD

**Issue by cicdguy** [rstudio/renv#1107]
Hi there, is there a JSON schema that one can use for validation of renv.lock files or for integrations?

**Comment by kevinushey** [comment]
There isn't, but I could put one together if it would be useful.

**Comment by hadley** [comment]
The structure is pretty simple and stable, so while we're not planning to generate a JSON schema ourselves, it should be pretty simple for someone else to mock one up.
