### ISSUE TITLE
renv::init() WARNING: One or more problems were discovered while enumerating dependencies.

### ISSUE THREAD

**Issue by ENIAC-6** [rstudio/renv#1112]
I am trying to use renv::init() for the first time but receive the following warning:

`renv::init()`
WARNING: One or more problems were discovered while enumerating dependencies.

D:/Test/lidR/Scripts/lidR_Tutorial.R

ERROR 1: '\U' used without hex digits in character string starting "'D:\U"

Please see `?renv::dependencies` for more information.
Do you want to proceed? [y/N]: N

I'm not sure why I'm still getting the error for "'D:\U" as I moved my project from a directory starting with D:\US to D:\Test. If I say y and proceed, will that cause issues later down the line with snapshot() and restore()?

`sessionInfo()`
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1    renv_0.16.0

**Comment by kevinushey** [comment]
The issue is most likely that your script, D:/Test/lidR/Scripts/lidR_Tutorial.R, contains a line of code like:

```
"D:\US"
```

But in R strings, backslashes need to be escaped, and so you need to write "D:\\US" instead. (Or, use forward slashes and forego the need to escape anything.)

**Comment by kevinushey** [comment]
This is documented in `?renv::init` -- the intention is that it'll set up an `renv` project with everything ready to go, so that an existing "working" project will continue to work after you've initialized it.

> Thank you for your renv: Project Environments for R | RStudio (2020) video! https://www.youtube.com/watch?v=yjlEbIDevOs

Thanks; I'm glad you found it useful!
