### ISSUE TITLE
`renv_file_find()` and Docker

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#1115]
This isn't really a bug report, nor much of a feature request, either, just a note about how an renv feature (which is nice!) doesn't play so nicely with some standard ways of using Docker.

I found myself in an odd position recently of wanting to use `renv::autoload()` to load a project renv library from a (possibly deeply-nested) project subdirectory starting-point. In development on my localhost R environment, this worked fine. When I migrated to running from within a Docker image, suddenly the auto-load behavior stopped working.

It turns out I was copying/mounting the project (root) into the `/app` directory within the Docker container (which is somewhat standard: i.e. having the 'project' or 'application' mounted at a top-level directory). The auto-loading gave up before reaching the `/app` directory, however, because of [this math](https://github.com/rstudio/renv/blob/a921af3b9980a6cba82ebc3404c42f2a43e759fc/R/files.R#L482):
```R
  # compute number of slashes (avoid searching beyond home directory)
  slashes <- gregexpr("/", path, fixed = TRUE)[[1L]]
  n <- length(slashes) - 2L
```
Obviously on local development environments this makes sense, but when developing (or running) inside a Docker image, one _probably_ wants to go up to at least only one-level below `/`, since the application code ("project", here) would typically be mounted somewhere like `/app` or even `/root`.

Not sure what to do about this, other than make a note (this issue) for possible future reference; or possibly some optional switch to enable searching a bit farther up (with all the associated 'here-be-dragons' caveats that come from exploring that far up in the directory structure :-) ).

**Comment by kevinushey** [comment]
Thanks for the bug report! I agree we could relax this in the Docker scenario -- we could probably check whether `/.dockerenv` exists, and allow lookup to the root directory in that case. (Or check if the user is `root`?)

**Comment by kevinushey** [comment]
Should be fixed via https://github.com/rstudio/renv/commit/66f339c71915ef4641e66f530051bc118a96cf96 -- let me know if you encounter any issues!

**Comment by kevinushey** [comment]
Is there a more appropriate way for us to infer whether we're running within Docker (or some other type of container)?

**Comment by Kjir** [comment]
Hey,
sorry for the long overdue response: it is essentially not possible to reliably determine whether you are in a container or not. I've seen some techniques proposed for this-or-that container technology, but none that works in all of them. So for example you might be able to tell that you're running in Docker, but not that you're in Kubernetes or OpenShift and so on.

I see that in the meantime the check has changed, but I just wanted to include this note in case someone re-reads this issue.

And for the curious the current check looks for the string `docker` in `/proc/1/cgroup`, but in Kubernetes:

```bash
$ cat /proc/1/cgroup | grep docker
```
You won't find the `docker` string.

I assume it is ok to have an imperfect check, just so long there is awareness that it doesn't catch all cases of code running in a container.
