### ISSUE TITLE
Multiple lock files

### ISSUE THREAD

**Issue by rahultoora** [rstudio/renv#1118]
Is it possible to have two lock files. I am dealing with multi OS (Windows and Linux) and would like to have a lock file for each OS and only restore one depending on my OS

Something like:

if (Sys.info()[["sysname"]] == "Linux")
  options(renv.lockfile = 'linux_renv.lock')

if (Sys.info()[["sysname"]] == "Windows")
  options(renv.lockfile = 'windows_renv.lock')

Reason:

Currently my Linux binaries come from RSPM in particular  "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest" and Windows binaries come from CRAN in particular: CRAN = "https://cran.rstudio.com/".

If I create a project from a Windows OS my lock file will look something like:

{
  "R": {
    "Version": "4.1.2",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Packages": {
    "R6": {
      "Package": "R6",
      "Version": "2.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "470851b6d5d0ac559e9d01bb352b4021",
      "Requirements": []
    },...

then if I want to restore it from a Linux OS I need to add something like this to my .Rprofile:

if (Sys.info()[["sysname"]] == "Linux")
  options(renv.config.repos.override = "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest")

source("renv/activate.R")

however this does not allow me to lock down the dependencies.

**Comment by kevinushey** [comment]
You might consider using separate `renv` profiles for this case: see https://rstudio.github.io/renv/articles/profiles.html for more details.

Alternatively, you can use the `RENV_PATHS_LOCKFILE` environment variable to set the path to the `renv.lock` lockfile. See the documentation in https://rstudio.github.io/renv/reference/paths.html for more details.

**Comment by rahultoora** [comment]
Thanks for the quick response!
