### ISSUE TITLE
renv::install pushes devtools and roxygen2 into dependencies, when they are not under DESCRIPTION/Suggests

### ISSUE THREAD

**Issue by pedrobtz** [rstudio/renv#1119]
I am trying to find a way to use `renv` in gitlab ci/cd pipeline to install dependencies (under DESCRIPTION) of a R package before running R CMD CHECK. I excluded using package `pak` for now, because there are issues with download methods and certificates under company CRAN proxies.

When doing `renv::install(type = "explicit")` the packages `devtools` and `roxygen2` are pushes into the list of dependencies, when they are not even part of Suggests. The package `devtools` brings its 93 dependencies + some system requirements.

Doing `renv::settings$ignored.packages("devtools", persist = FALSE)` does not work because the ignore is applied before `devtools` inclusion.

https://github.com/rstudio/renv/blob/d1545be475e6cd949598fe5ee62a5b1a9919457e/R/project.R#L115-L116

Another place where `devtools` is pushes into the list of dependencies can be disabled by changing the RStudio settings.
https://github.com/rstudio/renv/blob/a921af3b9980a6cba82ebc3404c42f2a43e759fc/R/dependencies.R#L878

questions: Is there a way to install only the `explicit` dependencies of an R package?

**Comment by pedrobtz** [comment]
One solution seems to be

```r
deps <- renv:::renv_dependencies_discover_description(path = "DESCRIPTION")$Package
renv::install(packages = deps)
```
Although, this doesn't take into consideration version requirements.

**Comment by kevinushey** [comment]
Thanks for the bug report! I made a change in https://github.com/rstudio/renv/commit/64257251f8e5ee3044f9a65c8100ac3e4a78f78b that I hope will resolve this particular issue.

**Comment by pedrobtz** [comment]
many thanks
