### ISSUE TITLE
Inferring used packages from {pacman}

### ISSUE THREAD

**Issue by kstierhoff** [rstudio/renv#1121]
As I understand it, {renv} scans R scripts for `library()` and `require()` to determine packages used. Does it also scan calls to functions from the {pacman} package, e.g., `pacman::p_load("ggplot2")`? If not, would that be possible to add as a feature? Thanks!

**Comment by kevinushey** [comment]
`renv` does also support `pacman::p_load()` usages.

**Comment by kstierhoff** [comment]
Thanks for the confirmation, apologies if I missed that in the documentation. I'm just starting to use `renv` so haven't learned all it's behaviors yet.

**Comment by kevinushey** [comment]
> apologies if I missed that in the documentation.

That's a good point actually; we don't document what types of package usages are currently discovered by `renv`. I should add something to `?dependencies`.

For reference: https://github.com/rstudio/renv/blob/main/R/dependencies.R#L909-L923
