### ISSUE TITLE
failed to find binary for StanHeaders

### ISSUE THREAD

**Issue by wzbillings** [rstudio/renv#1122]
I'm using the development version of `rstan` and `StanHeaders` in a `renv` project, but when I try to do `renv::restore()` I get the following message:
```
Warning: failed to find binary for 'StanHeaders 2.26.13' in package repositories
Warning: failed to find source for 'StanHeaders 2.26.13' in package repositories
Error: failed to retrieve package 'StanHeaders@2.26.13'
```
`getOption("repos")` produces the following:
```
                             CRAN                              stan 
    "https://cloud.r-project.org" "https://mc-stan.org/r-packages/" 
```

and my `renv.lock` entry for StanHeaders reads:
```
    "StanHeaders": {
      "Package": "StanHeaders",
      "Version": "2.26.13",
      "Source": "Repository",
      "Repository": "stan",
      "Hash": "f54ef22dec1b0710070e2d9bd3fc0174",
      "Requirements": [
        "RcppEigen",
        "RcppParallel"
      ]
    },
```

This is the correct version and if I run `install.packages("StanHeaders", repos = "https://mc-stan.org/r-packages/")`, it installs correctly. (I subsequently deleted the installed package from the local file.)

Can someone please help me figure out why I can't just `renv::restore()` and have this work? I'm happy to provide any other useful information.

Edit: wanted to clarify that the URL is not the issue -- this is consistent with the instructions for installing the development version of packages [here](https://mc-stan.org/r-packages/) (and it installs correctly outside of `renv::restore()`).

Edit 2: double checked that `renv::install("StanHeaders", repos = "https://mc-stan.org/r-packages/")` works. It does, so the error seems to be with `renv::restore()` specifically.

**Comment by petrbouchal** [comment]
Just came across a similar situation with `{bslib}` - `renv` seems to be trying to get the binary from https://packagemanager.rstudio.com while CRAN only holds the source and Package Manager only holds the binary of the previous version.

```r
Retrieving 'https://packagemanager.rstudio.com/all/__linux__/jammy/latest/src/contrib/Archive/bslib/bslib_0.4.2.tar.gz' ...
Warning: Warning: failed to find source for 'bslib 0.4.2' in package repositories
Warning: Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/__linux__/jammy/latest/src/contrib/Archive/bslib/bslib_0.4.2.tar.gz' [error code 22]
Error: Error: failed to retrieve package 'bslib@0.4.2'
```

The solution is to install the version for which CRAN has the binary (`install.packages("bslib", type = "binary")`), and so does Package Manager.

Still, this is unexpected since packages are retrieved from somewhere other than `renv.lock` states and the discrepancy causes an error.

**Comment by petrbouchal** [comment]
Though my issue in the comment may be different, see #1103

**Comment by wzbillings** [comment]
potentially related: https://github.com/rstudio/renv/issues/671, although I did explicitly update the repos option in my `.Rprofile`. Guess I should try the suggested edit to the lockfile.

**Comment by wzbillings** [comment]
Changing the lockfile entry to
```
    "StanHeaders": {
      "Package": "StanHeaders",
      "Version": "2.26.13",
      "Source": "Repository",
      "Repositories": [
        {
          "Name": "CRAN",
          "URL": "https://cloud.r-project.org"
        },
        {
          "Name": "stan",
          "URL": "https://mc-stan.org/r-packages/"
        }
      ],
      "Hash": "f54ef22dec1b0710070e2d9bd3fc0174",
      "Requirements": [
        "RcppEigen",
        "RcppParallel"
      ]
    },
```
similar to what was suggested, didn't work. Still get the same error.

**Comment by wzbillings** [comment]
Can confirm that this seems to solve my issue.
