### ISSUE TITLE
Cannot install foreign-0.8-81 binary on Windows

### ISSUE THREAD

**Issue by PromyLOPh** [rstudio/renv#1123]
The following (synthetic) renv.lock tries to install the package `foreign` from source on R 4.2. This fails, because there is no compiler on this machine:

```
{"R": {"Version": "4.2.2"}, "Packages": {"foreign": {"Package": "foreign", "Version": "0.8-81", "Source": "Repository", "Repository": "CRAN"}}}
```

I do see a snapshot of the binary for Windows at https://cran.microsoft.com/snapshot/2021-08-19/bin/windows/contrib/4.2/foreign_0.8-81.zip though. Switching to R 4.1.3 `renv::restore()` correctly downloads the binary zip from MRAN.

Looking through renv’s source code I see the package database must be generated in [renv_mran_database_sync_all](https://github.com/rstudio/renv/blob/main/R/mran.R#L296). There is no entry for R 4.2 though, which could explain why the binary is not found.

**Comment by kevinushey** [comment]
I've updated the MRAN database, and now entries for (newer) versions of foreign should be available. Sorry for the trouble!

That said, note that Microsoft intends to discontinue its support for the MRAN service:

https://aka.ms/mran-retirement

so unfortunately you won't be able to rely on this for much longer. I'm hoping that RSPM will be a suitable alternative when that time comes: https://packagemanager.rstudio.com/client/#/

**Comment by PromyLOPh** [comment]
It looks like it works with R 4.2.2 and foreign 0.8-82:

```
The following package(s) will be updated:

# CRAN ===============================
- foreign   [0.8-83 -> 0.8-82]

Do you want to proceed? [y/N]: y
Retrieving 'https://mran.microsoft.com/snapshot/2022-09-29/bin/windows/contrib/4.2/foreign_0.8-82.zip' ...
	OK [downloaded 271.2 Kb in 1.8 secs]
Installing foreign [0.8-82] ...
	OK [installed binary]
Moving foreign [0.8-82] into the cache ...
	OK [moved to cache in 6.3 milliseconds]
```

But not 0.8-81:

```
# CRAN ===============================
- foreign   [0.8-83 -> 0.8-81]

Do you want to proceed? [y/N]: y
Warning: failed to find binary for 'foreign 0.8-81' in package repositories
Warning: failed to find source for 'foreign 0.8-81' in package repositories
Error: failed to retrieve package 'foreign@0.8-81'
```

Regarding the (unfortunate) retirement of MRAN: Will RSPM mirror all binaries currently available on MRAN and will renv fetch sources/binaries from RSPM in the future?

**Comment by kevinushey** [comment]
> Regarding the (unfortunate) retirement of MRAN: Will RSPM mirror all binaries currently available on MRAN and will renv fetch sources/binaries from RSPM in the future?

There's nothing set in stone yet, but we're having conversations with the MRAN team to see what we can do going forward.
