### ISSUE TITLE
renv ignores some packages in Rmd 

### ISSUE THREAD

**Issue by aghaynes** [rstudio/renv#1125]
I have a package which defines a PDF report template (conceptually similar to `pagedown`). I refer to the package in the header output option and one chunk. `renv` does not want to include it in the lockfile though when doing a snapshot...

Any ideas?

e.g.

`````
---
knit: 
  bookdown::render_book:
    output_dir: ""
output: 
  package::report_pdf
title: true
etc
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# create CLO file required by the Latex template
package::use_reportclo(...)
```
`````

**Comment by kevinushey** [comment]
Using the document you shared as an example:

`````
> renv::dependencies("test.Rmd")
Finding R package dependencies ... Done!
                         Source   Package Require Version   Dev
1 /Users/kevin/scratch/test.Rmd rmarkdown                 FALSE
2 /Users/kevin/scratch/test.Rmd  bookdown                 FALSE
3 /Users/kevin/scratch/test.Rmd   package                 FALSE
4 /Users/kevin/scratch/test.Rmd     knitr                 FALSE
5 /Users/kevin/scratch/test.Rmd   package                 FALSE
`````

it seems to work. Can you provide any more information / a fully reproducible example?

**Comment by hadley** [comment]
I'm closing this issue because there hasn't been any further discussion since December. @aghaynes please feel free to ping us if you're still having problems.
