### ISSUE TITLE
Issue warning when installing a package into a place that isn't `RENV_PATHS_CACHE`

### ISSUE THREAD

**Issue by eheinzen** [rstudio/renv#1126]
We have the `RENV_PATHS_CACHE` environment variable set.  Some of the packages installed to that directory by another user didn't have group write, which led to two problems:

1. When I went to install a new version of a package with `renv::install()`, it installed it to my Rproj directory without telling me it didn't install to `RENV_PATHS_CACHE`.
2. When I tried to install an existing package version in the cache, it re-downloaded and reinstalled to my Rproj directory (instead of, e.g., symlinking).  We were confused why renv kept installing packages that should've been in the cache until we realized that it was a permissions problem. 

Could `renv::install()` issue a warning when it's not able to install the package to `RENV_PATHS_CACHE`, and inform us where it's going instead?

I'm happy to be wrong on this, too--I know people don't like it when output gets too verbose...

cc @btbroderick

**Comment by kevinushey** [comment]
What version of `renv` are you using? In theory the situation should be a bit improved here, e.g. from NEWS.md:

```
* The R option `renv.cache.callback` can now be set, to run a user-defined
  callback after a package has been copied into the cache. This can be useful
  if you'd like to take some action on the cached package's contents after
  the package has been moved into the cache.

* (Unix only) The `RENV_CACHE_MODE` environment variable can now be used to
  change the access permissions of packages copied into the cache. When set,
  after a package is copied into the cache, `renv` will use `chmod -Rf` to try
  and change the permissions of the cache entry to the requested permissions.
  
* (Unix only) The `RENV_CACHE_USER` environment variable can now be used to
  change the ownership of folders copied into the cache. When set, after a
  package is copied into the cache, `renv` will use `chown -Rf` to try and
  change the ownership of that cache entry to the requested user account.
```

> Some of the packages installed to that directory by another user didn't have group write, which led to two problems:

I wonder if this is something that `renv` could / should fix up when copying packages into the cache.

**Comment by eheinzen** [comment]
``` `renv.cache.callback` ``` is a cool feature that I hadn't seen.  That would fix the underlying issue of the perms (in our case we found out we'd also need a `chgrp`, which we can do in the callback at the same time; otherwise I think ``` `RENV_CACHE_MODE` ```  would do the trick, too).

However, I tried to use it for the reason I opened the issue (that is: I just want it to tell me when the copy to the cache fails and when it sticks it locally instead) and it didn't work.  I tried this:
```
options(renv.cache.callback = function(path) {
  print(path)
  if(!startsWith(path, Sys.getenv("RENV_PATHS_CACHE"))) {
    warning("The package got copied to a location that isn't `RENV_PATHS_CACHE`")
  }
})
```
But it looks like the callback isn't called when the cache isn't writable.

**Comment by kevinushey** [comment]
For extra context, the workflow is usually something like the following:

1. First, `renv` installs the package directly into the active library;
2. If installation succeeds, and if `renv` is configured to do so, `renv` will then copy the package into the cache, and then replace the version in the library with a symlink (or another copy of the package if configured to do so).

This should normally be happening here:

https://github.com/rstudio/renv/blob/c59cae1c54648cb61f07daf4a7aa9df0a46d163b/R/cache.R#L183-L189

which is itself called from `renv_cache_synchronize()`, e.g.

https://github.com/rstudio/renv/blob/c59cae1c54648cb61f07daf4a7aa9df0a46d163b/R/install.R#L396-L398

Are you seeing `renv_cache_synchronize()` being called? Are you able to use the R debugger to step through and learn a bit more?

**Comment by hadley** [comment]
@eheinzen are you still interested in following up on this issue?

**Comment by eheinzen** [comment]
Jeez, sorry for the delay, guys.  I'll follow up in the morning and see if I can make a reprex.

**Comment by eheinzen** [comment]
My issue looks something like this: https://github.com/eheinzen/renv_1126/blob/master/reprex.R. I'm hoping that's close enough to a reprex for you to see what's happening.

Basically, in `.Renviron`, I set `RENV_PATHS_CACHE=directory_with_perms_500`.  I created that directory with mode 500 so that it's not writable.  I try to install the `glue` package.  `renv` installs directly to `renv/library/...` instead of `directory_with_perms_500` without telling me.  This could become a problem on a shared Linux ecosystem where everyone is trying to link packages to the cache, but `renv` is (silently) putting them all in the respective project directories instead, thereby keeping multiple copies of the package around.

To answer your question, `renv` never gets to the lines you referenced in `renv_cache_synchronize_impl()`, but exits on this line:
 https://github.com/rstudio/renv/blob/c59cae1c54648cb61f07daf4a7aa9df0a46d163b/R/cache.R#L170-L171
I guess my suggestion is then to give an option for a warning or message when it exits here.  `renv.cache.callback` doesn't work because we exit the function before getting to the callback evaluation.

**Comment by kevinushey** [comment]
Thanks for following up! My main concern is that the warnings could be annoying of the cache was intentionally made read-only (which it seems to be, in your case?)

Other than a potential warning, is there some other behavior you were hoping to get from `renv` in this scenario?

**Comment by kevinushey** [comment]
Thanks! I'll close this for now; please feel free to file another issue if you bump into any other problems.
