### ISSUE TITLE
renv should store its own SHA1 ref in renv.lock

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/renv#113]
When renv is installed from github at a latest master ref that is not a tag/release, it does not know how to restore itself on a clean machine with no renv installation.

E.g. with 

```
[renv]
Version=0.5.0-112
```

I get 

> Failed to find installation of renv -- attempting to bootstrap...
> '* Downloading renv 0.5.0-112 ... Error in utils::download.file(url, destfile = destfile, mode = "wb", quiet = TRUE) : 
>   cannot open URL 'https://api.github.com/repos/rstudio/renv/tarball/0.5.0-112'
> In addition: Warning message:
> In utils::download.file(url, destfile = destfile, mode = "wb", quiet = TRUE) :
>   cannot open URL 'https://api.github.com/repos/rstudio/renv/tarball/0.5.0-112': HTTP status was '404 Not Found'
> Warning message:
> Failed to find an renv installation: the project will not be loaded.
> Use `renv::activate()` to re-initialize the project. 
> 

where https://api.github.com/repos/rstudio/renv/tarball/0.5.0-112 really does not exist. Reinitiatising is not optimal as that would mean losing information about package versions. Installing the exact ref aa364e3d42419c77ba4e8244b0194e4856b58428 resolved the issue.

**Comment by kevinushey** [comment]
The problem here is that the `activate.R` script needs to know the SHA, before the change to the file has actually been committed to the repository. But setting the SHA would change the SHA of the commit. So (unless there's a clever way of doing this that I'm not thinking of) there isn't really a way to encode the SHA directly.

Instead, we should use something (a GitHub action?) to ensure newly-pushed commits to GitHub get auto-tagged.

**Comment by petrbouchal** [comment]
Thanks. I may have expressed myself poorly and this may be simpler than I made it seem. The SHA I was referring to was that of the renv github repo (rstudio/renv) when renv itself is installed from github, as is still the only way. That is not stored in renv.lock, unlike for entries for other packages installed from github. As a result, a restore on a clean machine installs renv from the github repo at its current master status. This may create a mismatch between the version of renv used for creating renv.lock and the version of renv used for restoring from this renv.lock - even if the version number is the same. The only way to recover from the error was to track down the correct git ref from which renv was installed and install it manually. 

Am I making sense? Or am I misunderstanding the intended usage/behaviour when restoring a renv-enabled project on a clean machine? 

The scenario giving rise to this issue may disappear once renv is on CRAN, but for now it creates a tricky situation for the user.

**Comment by kevinushey** [comment]
> The SHA I was referring to was that of the renv github repo (rstudio/renv) when renv itself is installed from github, as is still the only way. That is not stored in renv.lock, unlike for entries for other packages installed from github.

Ahh, that definitely makes sense. As a matter of fact, we now include `renv` as a regular package record in the lockfile, and that will include all the relevant Remote fields. E.g. I see:

```
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.7.0-107",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "rstudio",
      "RemoteRepo": "renv",
      "RemoteSubdir": null,
      "RemoteRef": "0.7.0-107",
      "RemoteSha": "2fe326156043b6ec5a303c9273e93c01856aa63e"
    }
  }
```

Although it looks like we're including the tag used for install rather than the actual commit -- I'll fix that soon.

**Comment by petrbouchal** [comment]
Thanks - that has been resolved in the meantime, then.
