### ISSUE TITLE
Question: MRAN alternatives? 

### ISSUE THREAD

**Issue by zkamvar** [rstudio/renv#1130]
Since [MRAN will stop archiving at the end of the month and shut down in July](https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161), I'm wondering if there is a full replacement for MRAN that {renv} will use. The [posit package manager supports Linux and Windows binaries](https://packagemanager.posit.co/__docs__/admin/getting-started/user-guide/#distribution), but MacOS binaries are missing from that setup.

**Comment by kevinushey** [comment]
Thanks for the question! On the RStudio side, we're actively discussing what steps we can take to fill this gap. No answers yet, but we're working on it.

**Comment by hadley** [comment]
I know that this is on the PPM roadmap, and we'll announce it on the blog when we have more to share publicly.
