### ISSUE TITLE
Working with monorepos

### ISSUE THREAD

**Issue by rahultoora** [rstudio/renv#1131]
Currently I am in the process of configuring renv for a monorepo that contains different R applications defined in their own sub-directories in my repo. I would like to setup renv in each directory and not at the root of the project. Is there any guidance on going about this? 

I know we can configure multiple lockfiles in a repo: https://rstudio.github.io/renv/articles/profiles.html
but dont think that is what I exactly need. I assume I need to manually create .Rprofiles in each sub-directory and then somehow configure renv in each sub-directory? if so, how is the latter achieved?

**Comment by rahultoora** [comment]
Have just seen this: https://github.com/rstudio/renv/issues/472
so will give this a try first

**Comment by rahultoora** [comment]
Closing as above solved

**Comment by kevinushey** [comment]
Great, I'm glad to hear it!

For my own information, would you be willing to share what you changed to handle this?
