### ISSUE TITLE
[Feature Request] allow user-configured remotes strategy

### ISSUE THREAD

**Issue by dgkf** [rstudio/renv#1133]
# Motivation

`renv` currently attempts to fetch all remotes when installing packages, which introduces a behaviors that might not always be desirable: 

   - this deviates from `base::install.packages` default behavior opaquely
   - this can add unexpected packages to the local cache for soft dependencies (even when they aren't specified to be installed)
   - this will throw warnings when remotes are not accessible

The last point is particularly annoying in a private enterprise context where permissions might be required to access optional remotes.

To give a concrete example, within the context of an industry setting this is posing some hurdles. Our analysts see warnings when remotes can't be found (due to requiring authenticated access to the remote). This happens even in situations where the remote is for a dependency that does not need to be installed as specified by [`package.dependency.fields`](https://rstudio.github.io/renv/reference/settings.html#:~:text=package.dependency.fields), or when the dependency can already be satisfied by a version from a repository in `options("repos")`.

For a real-world enterprise `renv.lock` file, with a large corpus of private dependencies, this can be a barrage of warnings that can be alarming to anyone not savvy to the intricacies of remote dependency management.

# Feature Request

Introduce options for configuring when remotes should be considered. To propose some behaviors, perhaps this could be either:

- `"always"`: Remotes are always pulled, even if a non-remote source for the package is available. The remote is used if the downloaded package is the latest known version of the package. (current behavior)
- `"needed"`: Remotes are pulled only if a dependency cannot be satisfied by other sources.
- `"never"`: Never pull remotes

Ideally this option would be able to be provided to user-facing functions (`renv::install`, `renv::restore`, etc) as a parameter, or using project-level [`settings`](https://rstudio.github.io/renv/reference/settings.html), or via [`config`](https://rstudio.github.io/renv/reference/config.html) options/envvars.

---

The `"always"` behavior can be further improved following this feature request to `remotes` to allow declarative package names in remote definitions, which would allow for more selective downloading of `remotes` based on desired dependency types. (https://github.com/r-lib/remotes/issues/741), but even without those changes this option would be helpful in cases where the publicly available version satisfies all version requirements and the remote isn't `"needed"`.

**Comment by dgkf** [comment]
Just to close this request out. Following a discussion in the `remotes` issue, it sounds like this functionality is being deferred to the `pak` backend. `pak` is still lacking some compatibility that would make it actionable in my particular usecase, but it sounds like any required functionality is planned and would be the preferred place for managing this particular request.

**Comment by kevinushey** [comment]
I can take a look. To echo your request (to make sure I understand), you'd like to allow users to control whether `renv` tries to read + use the `Remotes:` fields discovered in any installed package `DESCRIPTION` file. Is that correct?

**Comment by dgkf** [comment]
That's right - the crux is about choosing when/how Remotes are used. I _think_ this might be covered by `pak` when `renv.config.pak.enabled` is set to `TRUE`, but I need to continue doing some testing before I can say for sure. 

Specifically, at my place of work we have quite a few teams that develop in-house packages and use (possibly private) Remotes during development. When deployed, we don't need users to grab those remotes and any version available on an internal repo that satisfies the dependency would be preferred to the latest version from the remote. 

Before you invest too much time in this, let me investigate the `pak` behavior. It might be sufficient for us and then this might be easily resolved by just having my administrators configure an environment variable. Nevertheless, I could see this being a helpful feature to minimize github API warnings.

**Comment by dgkf** [comment]
Just tested again using `renv.config.pak.enabled` and the remotes-related warnings seem to be avoided when `pak` is used as the backend. Let me follow up with some of our users to see if this resolves things for them just to make sure I'm not accidentally affecting behaviors with some other configuration on my end. 

For this exact need, I think this might suffice. I still think it's a valuable feature, but perhaps it makes more sense for configuration of Remotes handling to live in the package-fetching backends (`remotes`/`pak`) rather than in `renv`.
