### ISSUE TITLE
Packages copied on network drive

### ISSUE THREAD

**Issue by adayim** [rstudio/renv#1134]
Hi there,

Thank you so much for the package. 

I am working on Windows 10 computer, all our work stored on a mapped network drive. We are now keeping a copy of all the packages used by the project under the study folder, but we wish to use `renv` to save storage by having a global cache. We don't need to keep a separate package library for every project. But while we were trying out the package, we noticed that all the packages are installed under the global cache and also copied to the project folder every time we run `renv::init()`. Looking at directory folders via `dir` with `cmd`, all folders are directories not a junction point. 

Root folder settings as:
`RENV_PATHS_ROOT = "V:/cctu/src/renv"`
Setting `RENV_CONFIG_CACHE_SYMLINKS = TRUE` not seems to solve this issue.
 
Projects and global path are live on the same network drive. The filesystem is NTFS. I tried it on my own laptop, everything seems to work perfectly fine. 

I saw the answer [here](https://community.rstudio.com/t/using-renv-on-network-drive-all-packages-are-copied-both-in-project-library-and-cache/83265/4) says that the junction point does not support network drive. I was wondering if this is the case, `renv` doesn't support mapped network drive? If it is not the case, is there any work around on this? And can I ask does `renv` use `mklink` on windows to create a junction point?

**Comment by slodge** [comment]
I don't know if this will help.. I hope it at least doesn't do the reverse!

I did some digging a year ago into robocopy and junction points and renv - see inside https://github.com/rstudio/renv/issues/870 

@kevinushey was very helpful... and it turned out that we did somehow have problems where our files were being cached and installed on different drives... 

`renv::diagnostics()` was a very useful tool in seeing where everything was happening

(I still feel guilty about misdiagnosing our problem last year ... which is partly why I'm answering here now... still hoping to earn redemption one day!)

**Comment by adayim** [comment]
@slodge Thanks for your response. The package works perfectly fine on my laptop with local drive, it does create a junction point. But it fails on the network drive. I am not an expert on this, but I thought the junction points are created with `mklink`.  I can't find any `mklink` command in the package source code. My understanding is that the `robocopy` is for copying or moving files, not for creating a junction point.  

I tried `mklink` myself and this is what I got.
```cmd
V:\STATISTICS\cctu-cran>mklink /J win V:\STATISTICS\cctu-cran\bin\windows\contrib
Local NTFS volumes are required to complete the operation.
```
The `V` drive here is mapped from `\\server\groups$\somefolder`. If this was caused by system settings, I can ask admin to help us solve this issue. Not sure if this is the limitation of the Windows DFS.

This is my `.Renviron` settings:
```
RENV_PATHS_ROOT="V:/STATISTICS/cctu-cran/renv"
RENV_PATHS_CELLAR="V:/STATISTICS/NON STUDY FOLDER/Software/R/R Code Library"
RENV_CONFIG_CACHE_SYMLINKS = TRUE
```

Here is the dump from `renv::diagnostics()`
```r
Diagnostics Report [renv 0.16.0]
================================

# Session Info =======================
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0    renv_0.16.0   

# Project ============================
Project path: "V:/STATISTICS/STUDY FOLDER/Studyproject/Test"

# Status =============================
* The project is already synchronized with the lockfile.

# Packages ===========================
           Library Source Lockfile Source Path Dependency
KernSmooth 2.23-20   CRAN     <NA>   <NA>  [2]       <NA>
MASS        7.3-54   CRAN     <NA>   <NA>  [2]       <NA>
Matrix       1.3-3   CRAN     <NA>   <NA>  [2]       <NA>
boot        1.3-28   CRAN     <NA>   <NA>  [2]       <NA>
class       7.3-19   CRAN     <NA>   <NA>  [2]       <NA>
cluster      2.1.2   CRAN     <NA>   <NA>  [2]       <NA>
codetools   0.2-18   CRAN     <NA>   <NA>  [2]       <NA>
data.table  1.14.6   CRAN   1.14.6   CRAN  [1]     direct
foreign     0.8-81   CRAN     <NA>   <NA>  [2]       <NA>
grDevices     <NA>   <NA>     <NA>   <NA>  [2]   indirect
graphics      <NA>   <NA>     <NA>   <NA>  [2]   indirect
lattice    0.20-44   CRAN     <NA>   <NA>  [2]       <NA>
methods       <NA>   <NA>     <NA>   <NA>  [2]   indirect
mgcv        1.8-35   CRAN     <NA>   <NA>  [2]       <NA>
nlme       3.1-152   CRAN     <NA>   <NA>  [2]       <NA>
nnet        7.3-16   CRAN     <NA>   <NA>  [2]       <NA>
renv        0.16.0   CRAN   0.16.0   CRAN  [1]     direct
rpart       4.1-15   CRAN     <NA>   <NA>  [2]       <NA>
spatial     7.3-14   CRAN     <NA>   <NA>  [2]       <NA>
stats         <NA>   <NA>     <NA>   <NA>  [2]   indirect
survival    3.2-11   CRAN     <NA>   <NA>  [2]       <NA>
utils         <NA>   <NA>     <NA>   <NA>  [2]   indirect

[1]: V:/STATISTICS/STUDY FOLDER/Studyproject/Test/renv/library/R-4.1/x86_64-w64-mingw32
[2]: C:/Users/usera/AppData/Local/Temp/Rtmp2hxIS3/renv-system-library                                   

# ABI ================================
* ABI conflict checks are not yet implemented on Windows.

# User Profile =======================
[1] Source  Package Require Version Dev    
<0 rows> (or 0-length row.names)

# Settings ===========================
List of 10
 $ bioconductor.version     : chr(0) 
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ r.version                : chr(0) 
 $ snapshot.type            : chr "implicit"
 $ use.cache                : logi TRUE
 $ vcs.ignore.cellar        : logi TRUE
 $ vcs.ignore.library       : logi TRUE
 $ vcs.ignore.local         : logi TRUE

# Options ============================
List of 9
 $ defaultPackages                     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method                : chr "wininet"
 $ download.file.extra                 : NULL
 $ install.packages.compile.from.source: chr "interactive"
 $ pkgType                             : chr "both"
 $ repos                               : Named chr "https://cran.rstudio.com"
  ..- attr(*, "names")= chr "CRAN"
 $ renv.consent                        : logi TRUE
 $ renv.project.path                   : chr "V:/STATISTICS/STUDY FOLDER/Studyproject/Test"
 $ renv.verbose                        : logi TRUE

# Environment Variables ==============
HOME                        = //me-filer1/home$/usera/My Documents
LANG                        = <NA>
MAKE                        = <NA>
R_LIBS                      = <NA>
R_LIBS_SITE                 = <NA>
R_LIBS_USER                 = V:/STATISTICS/STUDY FOLDER/Studyproject/Test/renv/library/R-4.1/x86_64-w64-mingw32;C:/Users/usera/AppData/Local/Temp/Rtmp2hxIS3/renv-system-library
RENV_CONFIG_CACHE_SYMLINKS  = TRUE
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = <NA>
RENV_DEFAULT_R_LIBS_USER    = C:\Users\usera\Documents\R\win-library
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PATHS_CACHE            = V:/STATISTICS/cctu-cran/renv/cache/dev;V:/STATISTICS/cctu-cran/renv/cache/prod
RENV_PATHS_CELLAR           = V:/STATISTICS/NON STUDY FOLDER/Software/R/R Code Library
RENV_PATHS_ROOT             = V:/STATISTICS/cctu-cran/renv
RENV_PROJECT                = V:/STATISTICS/STUDY FOLDER/Studyproject/Test

# PATH ===============================
- C:\rtools40\usr\bin
- C:/Program Files/R/R-4.1.0/bin/x64
- C:\WINDOWS\system32
- C:\WINDOWS
- C:\WINDOWS\System32\Wbem
- C:\WINDOWS\System32\WindowsPowerShell\v1.0\
- C:\WINDOWS\System32\OpenSSH\
- C:\Program Files\SASHome\Secure\ccme4
- C:\Program Files\SASHome\x86\Secure\ccme4
- C:\Program Files\dotnet\
- C:\Program Files\Git\cmd
- C:\Users\usera\AppData\Local\activestate\cache\bin
- C:\Users\usera\AppData\Local\ActiveState\StateTool\release\bin
- C:\Users\usera\AppData\Local\Microsoft\WindowsApps
- C:\Program Files\R\R-4.1.0\bin
- C:\Users\usera\AppData\Local\Programs\Microsoft VS Code\bin
- C:\Users\usera\AppData\Local\Programs\MiKTeX\miktex\bin\x64\
- C:\Users\usera\AppData\Local\Pandoc"

# Cache ==============================
There are a total of 1 package(s) installed in the renv cache.
Cache path: "V:/STATISTICS/cctu-cran/renv/cache/dev/v5/R-4.1/x86_64-w64-mingw32"
Cache path: "V:/STATISTICS/cctu-cran/renv/cache/prod/v5/R-4.1/x86_64-w64-mingw32"
```

**Comment by slodge** [comment]
On Windows, I think the link is done using `Sys.Junction` rather then `mklink`:

https://github.com/rstudio/renv/blob/8d5015741717b6cfb8e4ea88b4e57f497cd78420/R/files.R#L245

e.g. https://github.com/SurajGupta/r-source/blob/master/src/library/base/R/windows/junctions.R (not sure that's the original source)

**Comment by adayim** [comment]
Thank you @slodge, you are right. I checked the `Sys.Junction` manual, it uses `mklink /J`. I am guessing this may not be possible on a network drive after all? Bit frustrated.

**Comment by kevinushey** [comment]
As far as I can see, `Sys.junction()` doesn't work with network / UNC paths. For example:

```
# this works
dir.create("C:/a")
Sys.junction("C:/a", "C:/b") 

# this doesn't
dir.create("//localhost/c$/c")
Sys.junction("//localhost/c$/c", "//localhost/c$/d")
```

And running `mklink /J` gives some more context:

```
> shell("mklink /J \\\\localhost\\c$\\c \\\\localhost\\c$\\d")
Local NTFS volumes are required to complete the operation.
```

**Comment by adayim** [comment]
Sorry for taking so long to get back to this. We have applied a new network drive with the symbolic links turned on. But it's not working for us either. Some say that junction point will not work on remote-to-remote, but symbolic link works. 
https://superuser.com/questions/1017653/creating-symbolic-links-on-networked-drive

But it's not working for us, maybe it's related to the drive settings. We got the following error if run `mklink /D` with admin right
```bash
The device does not support symbolic links.
```

It seems like this require admin rights. Or maybe this is the problem related to our network drive settings. Have no idea.

Overall, this is a dead end for us now. We have given up.😢😢
Thank you both for helping this though.

**Comment by kevinushey** [comment]
@adayim Sorry that we weren't able to find a way forward here. 😞

**Comment by adayim** [comment]
> @adayim Sorry that we weren't able to find a way forward here. 😞

No problem. I think the system IT department use does not support Windows NTFS symbolic link as well. I am going to close this issue. Thank you @kevinushey and @slodge so much.
