### ISSUE TITLE
install packages already in system library, user library, or cache instead of from repository

### ISSUE THREAD

**Issue by tedmoorman** [rstudio/renv#1137]
I'm encountering errors when trying to install packages from repository. In this case, the packages are newer versions.

Is it possible to change the default behavior of renv such that it installs packages already in the system library, user library, or the cache?

**Comment by kevinushey** [comment]
This is part of what `renv::hydrate()` does; however, if a package is not available in one of those locations then `renv` will attempt to install that package from CRAN. Will that still be sufficient for your use case?

If so, you can try to run `renv::hydrate(packages = <...>)` or similar. See `?renv::hydrate` for more details.

**Comment by tedmoorman** [comment]
I tried this and it just shows the user library and system library instead of the project library. Is that expected?

I tried to `renv::hydrate()` from a renv.lock file. 

Also, the system I'm using is offline/air-gapped. And so, I won't be able to install from CRAN.

**Comment by kevinushey** [comment]
Sorry, can you please clarify?

> I tried to renv::hydrate() from a renv.lock file.

This doesn't quite make sense to me -- `renv::hydrate()` copies packages from the user / system libraries into the project library; it doesn't try to use the lockfile?

> Also, the system I'm using is offline/air-gapped. And so, I won't be able to install from CRAN.

If that's the case, you probably want a variant of `renv::hydrate()` which avoids falling back to CRAN. (Alternatively, it's worth considering if you could set up your own CRAN-like package repository which is accessible within your air-gapped environment -- but I understand that might not be feasible in your scenario)

In any case, it would be helpful to know exactly what commands you're trying to run, and what errors (or undesired behaviors) you are seeing.

**Comment by tedmoorman** [comment]
It looks like `renv::hydrate()` is working for me. I mistakenly thought it used the lockfile rather than looking at the project code files. Thank you for your help!

**Comment by kevinushey** [comment]
Awesome, I'm glad to hear it!

**Comment by tedmoorman** [comment]
Just for the reference of others, whenever a new package is needed, use `renv::hydrate(packages = "<package_name_here>")`. For example, to include the readxl package, you would use `renv::hydrate(packages = "readxl")`.
