### ISSUE TITLE
[Feature Request] `renv::install()` supports extra dependencies like `remotes::install_deps(dependencies = "config/needs/dev")`

### ISSUE THREAD

**Issue by eitsupi** [rstudio/renv#1138]
Sometimes we want to list packages for package development in fields like `Config/Needs/dev`.
It would be great if `renv::install()` supported package installation from these fields.
https://github.com/r-lib/pkgdepends/blob/0228b05b3a94c9abe0d947f800a2d8f55289aff8/DESCRIPTION#L58-L68

**Comment by kevinushey** [comment]
To confirm, would the proposed syntax be something like `renv::install(..., dependencies = "Config/Needs/dev")`?

**Comment by eitsupi** [comment]
Thanks for your response.

> To confirm, would the proposed syntax be something like `renv::install(..., dependencies = "Config/Needs/dev")`?

My thought was like `renv::install(dependencies = "Config/Needs/dev")`, but I am beginning to feel that using `renv::install()` here may cause confusion since `remotes` and `pak` have dedicated functions to install dependencies only......
e.g. `pak::local_install_deps(dependencies = c("all", "Config/Needs/dev", "Config/Needs/website"))`

Here's what I actually use.
https://github.com/eitsupi/prqlr/blob/a4779c5ec296bf89650259305ec7601b351cedf6/Taskfile.yml#L13-L19

**Comment by kevinushey** [comment]
`renv` now supports the `dependencies` field. The ultimate goal is still for `renv` to defer package installation to `pak` entirely though.

**Comment by eitsupi** [comment]
Thanks for the update! That seems working very nice!

However, in my case below, an error seems to occur. Perhaps another issue?

https://github.com/eitsupi/prqlr/blob/c7ef1c277cc7c4d9894d8f8665a232c43855d96e/DESCRIPTION

```r
> renv::install(
              dependencies = c("Imports", "Depends", "LinkingTo", "Config/Needs/website"),
              repos = c(getOption("repos"))
            )
Error: package 'r' is not available
Traceback (most recent calls last):
13: renv::install(
              dependencies = c("Imports", "Depends", "LinkingTo", "Config/Needs/website"),
              repos = c(getOption("repos"))
            ) at #2
12: retrieve(names(remotes))
11: handler(package, renv_retrieve_impl(package))
10: renv_retrieve_impl(package)
 9: renv_retrieve_successful(record, path, install = FALSE)
 8: retrieve(package)
 7: handler(package, renv_retrieve_impl(package))
 6: renv_retrieve_impl(package)
 5: records[[package]] %||% renv_retrieve_missing_record(package)
 4: renv_retrieve_missing_record(package)
 3: renv_available_packages_latest(package)
 2: stopf("package '%s' is not available", package)
 1: stop(sprintf(fmt, ...), call. = call.)
```

**Comment by kevinushey** [comment]
Thanks -- it looks like this is a problem in `renv` parsing the remotes declared in the DBI package. I'll take a look.

**Comment by kevinushey** [comment]
This should now hopefully work as expected in the development version of `renv`.

**Comment by eitsupi** [comment]
> This should now hopefully work as expected in the development version of `renv`.

It works, thanks again!
