### ISSUE TITLE
package deps not installed when using remotes::install_github()

### ISSUE THREAD

**Issue by rpodcast** [rstudio/renv#114]
This is loosely related to #77 with respect to the system's R library being a part of `.libPaths()` inside an `renv` project (maybe) but I've encountered this perplexing issue illustrated by this workflow:

* I want to install an updated version of a package (for example Shiny) in my renv project.
* An (earlier) version of the package already exists in the system R library.
* renv::snapshot()` shows that a few dependencies of Shiny are not installed.

Interestingly, this does not seem to happen when I am installing packages from CRAN.  This is becoming a bit of a problem because I have to then manually install the package dependencies one-by-one in the renv project to get rid of that message.  Hope this makes sense, but I have the workflow below:

### Initialize renv in project

```r
renv::init()
```

### Install remotes package

```r
install.packages("remotes")
```

### Install updated version of Shiny from GitHub

* Within the default R system library, shiny `1.3.2` is already installed

```r
remotes::install_github("rstudio/shiny")
```

```
> remotes::install_github("rstudio/shiny")
Downloading GitHub repo rstudio/shiny@master
These packages have more recent versions available.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: mime   (0.6    -> 0.7   ) [CRAN]
5: digest (0.6.19 -> 0.6.20) [CRAN]
6: rlang  (0.3.4  -> 0.4.0 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
```

Packages install ...

```
fastmap (NA     -> 91321f1ae...) [GitHub]
mime    (0.6    -> 0.7         ) [CRAN]
digest  (0.6.19 -> 0.6.20      ) [CRAN]
rlang   (0.3.4  -> 0.4.0       ) [CRAN]
```

### Try snapshot

```r
renv::snapshot()
```

```
> renv::snapshot()
The following required packages are not installed:

	crayon       [required by shiny]
	htmltools    [required by shiny]
	httpuv       [required by shiny]
	jsonlite     [required by shiny]
	later        [required by shiny]
	promises     [required by shiny]
	R6           [required by shiny]
	sourcetools  [required by shiny]
	xtable       [required by shiny]

Consider re-installing these packages before snapshotting the lockfile.

Do you want to proceed? [y/N]: 
```

Why didn't the above packages get installed?

**Comment by kevinushey** [comment]
What is the output of:

```
find.package("sourcetools")
```

in that project? Note that `snapshot()` currently only looks at the state of your project's private library, and so if those packages were installed into the system library they would be missed. (perhaps this is misguided and we should use all libraries on the library paths).

You could try running:

```
renv::install("rstudio/shiny")
```

to install Shiny + its dependencies -- this should ensure all sub-dependencies get installed into the private library, as well.

Perhaps worth saying that we've also enabled sandboxing in the latest version of renv on master, so that even if you do have R packages installed in the system library they will not be made available by default, so that situations like this will be less common.

**Comment by rpodcast** [comment]
> What is the output of:
> 
> ```
> find.package("sourcetools")
> ```

It simply returned the default system's path to `sourcetools`.

> You could try running:
> 
> ```
> renv::install("rstudio/shiny")
> ```
> 
> to install Shiny + its dependencies -- this should ensure all sub-dependencies get installed into the private library, as well.

I was completely unaware that this also worked for packages stored in GitHub or other source control repos!  Yes running that function grabbed the missing dependencies and snapshot was done automatically.  I think it would be helpful to throw in an example of this in the `renv::install` function docs, in case others encounter this same issue.  Perhaps it's packrat "muscle memory" that I would always use `install.packages()` and `remotes::install_github` to get everything set up.

**Comment by kevinushey** [comment]
Good idea! I'll do that :-)

**Comment by kevinushey** [comment]
I've made two changes here:

1. When `renv::snapshot()` is called, we use all active library paths when writing the lockfile.
2. I've updated the documentation for `renv::install()` to note that it understands GitHub remotes (+ some other tips)
