### ISSUE TITLE
Unable to load library rJava on M1 apple processor

### ISSUE THREAD

**Issue by luismieryteran** [rstudio/renv#1144]
Hello,

Running library(rJava) in Rstudio (Version 2022.12.0+353 2022.12.0+353) gives this error:

Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(jvm, FALSE)
  error: unable to load shared object '/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server/libjvm.dylib':
  dlopen(/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server/libjvm.dylib, 0x000A): tried: '/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server/libjvm.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server/libjvm.dylib' (no such file), '/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server/libjvm.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

I am working with R version:

R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.0

Runnig 'sudo R CMD javareconf' in a terminal gives:

Java interpreter : /usr/bin/java
Java version     : 19.0.2
Java home path   : /Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/include/darwin  -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c conftest.c -o conftest.o
clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: ignoring file /Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server/libjvm.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

JAVA_HOME        : /Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.

so there appear to be clashes between the arm64 and x86_64 architectures. Any help is greatly appreciated.

**Comment by kevinushey** [comment]
How did you install your OpenJDK installation? Can you confirm what the output of:

```
file /Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server/libjvm.dylib
```

is, from a Terminal?

For reference, on my machine with a different JDK version:

```
$ file /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/server/libjvm.dylib
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib/server/libjvm.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

I suspect that you installed an x86 version of the JDK, and are trying to use that with arm64 R. You'll likely need to reinstall an arm64 version of the JDK.

**Comment by luismieryteran** [comment]
@kevinushey, thanks for your reply. Running what you suggested in a terminal gives:

/Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home/lib/server/libjvm.dylib: Mach-O 64-bit dynamically linked shared library x86_64

so it definitely looks like you nailed down the issue. To install, I did 'brew install --cask temurin'

**Comment by kevinushey** [comment]
Interesting; I would've figured that Homebrew here would've picked an arm64 installation.

For what it's worth, binaries are also available here:

https://adoptium.net/temurin/releases/

and you should be able to explicitly select an arm64 (well, aarch64) binary.

**Comment by luismieryteran** [comment]
Thanks, @kevinushey. I installed the pkg for jdk-17.0.6+10 with aarch64 and that seems to have solved the issue. Cheers!

**Comment by kevinushey** [comment]
Great, I'm glad to hear it!
