### ISSUE TITLE
[Feature Request] Support for `librarian` package loading

### ISSUE THREAD

**Issue by H-Mateus** [rstudio/renv#1145]
It'd be super handy if `renv::dependencies` could parse `librarian::shelf`

I'm not a fan of having loads of `library` calls across scripts in a project, so I've got in the habit of using [`librarian`](https://github.com/DesiQuintans/librarian) like so:

```
# list packages needed
pkg <- c("dplyr", "readr", "stringr")
# install/load
librarian::shelf(pkg)
# clean up
rm(pkg)
```

I'm not particularly wedded to `librarian`, so if there's another way of easily installing/loading a list of packages that `renv` can parse, I'm happy to switch to whatever that might be!

**Comment by H-Mateus** [comment]
On the off chance it's handy to someone else, my current workaround is to just generate a file of library calls for `renv` to parse like so:

```
# list packages needed
pkg <- c("dplyr", "readr", "stringr")
# install/load
librarian::shelf(pkg)

# generate library calls for renv
library_calls <- paste0("library(", pkg, ")")
readr::write_lines(library_calls, here::here("scripts/library_calls_for_renv.R"))

# clean up
rm(pkg, library_calls)
```

Which is a pretty easy solution to be fair 😅

**Comment by hadley** [comment]
Your workaround looks good to me. Unfortunately I think it's out of scope for renv to support every possible means of loading an R package.
