### ISSUE TITLE
This project is configured to use Bioconductor '3.12', which is not compatible with R '4.0.5'.

### ISSUE THREAD

**Issue by zhuxr11** [rstudio/renv#1148]
Hi, when loading an R project in terminal, I sometimes (but not always) see this message possibly prompting from `renv` package: "This project is configured to use Bioconductor '3.12', which is not compatible with R '4.0.5'. Use 'renv::init(bioconductor = TRUE)' to re-initialize this project with the latest Bioconductor release."

From [Bioconductor site](https://www.bioconductor.org/about/release-announcements/#release-versions), it says version 3.12 works with R 4.0, so I think it is natural that R '4.0.5' comes with Bioconductor 3.12, which is the version automatically determined when installing `BiocManager` package.

It is totally OK that I ignore this warning, but I would still like to find out why renv thinks Bioconductor 3.12 is not compatible with R 4.0.5.

**Comment by zhuxr11** [comment]
I saw this message came together with failing to connect to `https://bioconductor.org/config.yaml`. In case of failed connection, could `renv` skip checking bioconductor version instead of warning incompatibility?

```
Warning messages:
1: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': status was 'SSL connect error'
2: In file(con, "r") :
  cannot open URL 'http://bioconductor.org/config.yaml': HTTP status was '502 Bad Gateway'
3: This project is configured to use Bioconductor '3.12', which is not compatible with R '4.0.5'.
Use 'renv::init(bioconductor = TRUE)' to re-initialize this project with the latest Bioconductor release. 
```

**Comment by kevinushey** [comment]
Thanks for the report! This should be improved with https://github.com/rstudio/renv/commit/aa9e49f728ac18dae7a4bf7eccddd0ded56e3d3d -- please let me know if you're able to test and confirm.
