### ISSUE TITLE
renv inside Docker container - could not find function "renv_snapshot_auto_update"

### ISSUE THREAD

**Issue by achamess** [rstudio/renv#1151]
I have a Docker container running based on a rocker image
I'm using renv to install packages.
I'm running rstudio server through the Docker.

I keep getting this error:
```
Error in renv_snapshot_auto_update(project = project) :
could not find function "renv_snapshot_auto_update"
```

and it keeps on looping infinitely until I force out of the the R session somehow.

**Comment by achamess** [comment]
I also get this message at startup

Warning message:
`target file '/home/rstudio/analysis/renv/sandbox/R-4.2/x86_64-pc-linux-gnu/25ebdc09/boot' already exists `

Not sure if it's related

**Comment by kevinushey** [comment]
Thanks for the bug report -- unfortunately, without more information (or a reproducible example) it's unlikely that I will be able to help.

**Comment by achamess** [comment]
Happy to provide more info. I don't think I can provide a reproducible example since it's not in response to any code or command. It just happens when I leave the Rstudio server running for some time, and then I return to it. I then try to run some code block (and one, not the same one each time) and then I get this message and infinte loop. 

I wish I could say more, but I'm not sure exactly what I'm looking for. Is there anything more I could provide to ascertain the issue? lock file? sessionInfo?

**Comment by kevinushey** [comment]
> It just happens when I leave the Rstudio server running for some time, and then I return to it.

This is helpful; thanks! This could imply that perhaps the issue occurs when the R session is suspended and then later restored. I'll see if I can reproduce in a similar context.

The output of `renv::diagnostics()` might also be helpful -- mostly I'm curious what version of R, what OS, and so on.

**Comment by kevinushey** [comment]
I've made some changes in the development version of `renv` which may help:

https://github.com/rstudio/renv/commit/094c01d726d3c6ceaf770de71fafa7b2eafe5ae9

**Comment by achamess** [comment]
No longer having the issue FYI. Thanks!

**Comment by salim-b** [comment]
I get the `could not find function "renv_snapshot_auto_update"` when trying to upgrade from renv 0.16.0 to 0.17.0 in a project configured to use explicit snapshots:

```
> renv::upgrade()
A new version of the renv package will be installed:

# CRAN ===============================
- renv   [repo: RSPM -> CRAN; ver: 0.16.0 -> 0.17.0]

This project will use the newly-installed version of renv.

Do you want to proceed? [y/N]: y
Retrieving 'https://packagemanager.rstudio.com/cran/__linux__/jammy/latest/src/contrib/renv_0.17.0.tar.gz' ...
	OK [file is up to date]
Installing renv [0.17.0] ...
	OK [installed binary]
Moving renv [0.17.0] into the cache ...
	OK [moved to cache in 6.7 milliseconds]
Warning messages:
1: In get(method, envir = envir) : internal error -3 in R_decompress1
2: In get(method, envir = envir) : internal error -3 in R_decompress1
Error in renv_snapshot_auto_update(project = project) : 
  could not find function "renv_snapshot_auto_update"
In addition: Warning message:
In get(method, envir = envir) : internal error -3 in R_decompress1
Error in get(method, envir = envir) : 
  lazy-load database '/home/salim/REDACTED/renv/library/R-4.2/x86_64-pc-linux-gnu/renv/R/renv.rdb' is corrupt
In addition: Warning message:
In get(method, envir = envir) : internal error -3 in R_decompress1
```

**Comment by kevinushey** [comment]
Does the error go away after restarting the R session?

**Comment by salim-b** [comment]
> Does the error go away after restarting the R session?

Yes. I just tried upgrading from renv 0.16.0 to 0.17.0 with another project that is also configured to use `snapshot.type: explicit`. The initial error message seems different though, probably because renv 0.17.0 was already in the package cache this time:

```
> renv::upgrade()
A new version of the renv package will be installed:

# CRAN ===============================
- renv   [0.16.0 -> 0.17.0]

This project will use the newly-installed version of renv.

Do you want to proceed? [y/N]: y
Installing renv [0.17.0] ...
	OK [linked cache]
Warning message:
In eval(handler$expr, handler$envir) : internal error -3 in R_decompress1
Error in cb(expr, value, succeeded, visible) : 
  lazy-load database '/home/salim/REDACTED/renv/library/R-4.2/x86_64-pc-linux-gnu/renv/R/renv.rdb' is corrupt
In addition: Warning message:
In cb(expr, value, succeeded, visible) : internal error -3 in R_decompress1

Restarting R session...

* Project '~/REDACTED/R' loaded. [renv 0.17.0]
* The project is currently out-of-sync.
* Use `renv::status()` for more details.
```

(The "out-of-sync" statement is misleading, cf. https://github.com/rstudio/renv/issues/1159.)

**Comment by kevinushey** [comment]
If you can share a reproducible example for how you got that `renv` lockfile entry, that would be helpful -- I definitely recognize it could be challenging to figure out what's going on, though.

**Comment by kevinushey** [comment]
Do you also see the same thing if you run `renv::upgrade(reload = TRUE)`? (In case explicitly setting that seems to help here)

**Comment by salim-b** [comment]
> Do you also see the same thing if you run `renv::upgrade(reload = TRUE)`? (In case explicitly setting that seems to help here)

Yes, now with the initial `could not find function "renv_snapshot_auto_update"` again (appears again regardless of `reload`):

```
> renv::upgrade(reload = TRUE)
A new version of the renv package will be installed:

# CRAN ===============================
- renv   [repo: RSPM -> CRAN; ver: 0.16.0 -> 0.17.0]

This project will use the newly-installed version of renv.

Do you want to proceed? [y/N]: y
Installing renv [0.17.0] ...
	OK [linked cache]
Warning messages:
1: In get(method, envir = envir) : internal error -3 in R_decompress1
2: In format(renv_error_simplify(call)) :
  internal error -3 in R_decompress1
3: In get(method, envir = envir) : internal error -3 in R_decompress1
Error in renv_snapshot_auto_update(project = project) : 
  could not find function "renv_snapshot_auto_update"
In addition: Warning message:
In get(method, envir = envir) : internal error -3 in R_decompress1
Error in get(method, envir = envir) : 
  lazy-load database '/home/salim/REDACTED/renv/library/R-4.2/x86_64-pc-linux-gnu/renv/R/renv.rdb' is corrupt
In addition: Warning message:
In get(method, envir = envir) : internal error -3 in R_decompress1
```

> If you can share a reproducible example for how you got that `renv` lockfile entry, that would be helpful -- I definitely recognize it could be challenging to figure out what's going on, though.

The project is public, so you can simply clone the repo (just stay in the `master` branch), bootstrap and then upgrade renv: 🙂

```
git clone https://gitlab.com/zdaarau/websites/digipartindex.ch.git
cd digipartindex.ch/R/
Rscript -e 'print("hello world")'   # bootstrap renv by running `.Rprofile`
git status                          # ensure there are no changes yet
Rscript -e 'renv::upgrade()'
git diff renv.lock                  # now you should see the diff from above
```

**Comment by kevinushey** [comment]
Thanks; I'll take a look!

**Comment by kevinushey** [comment]
I believe the issue you describe with the strange lockfile entry should now be resolved. The 'lazy-load database warning' issue is more challenging as (to my understanding) that's a long-standing issue with R, but I also tried making some changes that may alleviate that.

**Comment by hutch3232** [comment]
Hi @kevinushey, I thought I could chime in with another report that should be reproducible (it occurred in both a linux docker environment with RStudio Server and also in RStudio for Windows desktop).

<details><summary>Session Info</summary>
<p>

```r
sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2 
```

</p>
</details> 

I started with `renv` 0.16.0 in a mostly empty R project. I did not even have `renv.lock`:
```r
renv::status()
* This project has not yet been snapshotted -- 'renv.lock' does not exist.
The following package(s) are installed but not recorded in the lockfile:
       _
  renv   [0.16.0]

Use `renv::snapshot()` to add these packages to your lockfile.
```

Upgrading gives the "scary" warnings:
```r
renv::upgrade()
A new version of the renv package will be installed:

# CRAN ===============================
- renv   [0.16.0 -> 0.17.3]

This project will use the newly-installed version of renv.

Do you want to proceed? [y/N]: y
Retrieving 'https://cloud.r-project.org/src/contrib/renv_0.17.3.tar.gz' ...
	OK [downloaded 1 Mb in 0.3 secs]
Installing renv [0.17.3] ...
	OK [built from source]
Moving renv [0.17.3] into the cache ...
	OK [moved to cache in 24 milliseconds]
Warning messages:
1: In runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
2: In runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
Error in runHook(".onLoad", env, package.lib, package) : 
  lazy-load database 'C:/Users/hutch3232/Documents/R/test_renv/renv/library/R-4.2/x86_64-w64-mingw32/renv/R/renv.rdb' is corrupt
In addition: Warning message:
In runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
```

Simply restarting my R session and it fixes those warnings, so really not a big deal except it might cause concern for some.

As for the lock file, that does initially look kind of strange:
```
{
  "R": {
    "Version": "4.2.2",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.17.3",
      "OS_type": NA,
      "NeedsCompilation": "no",
      "Repository": "CRAN",
      "Path": NA,
      "Source": "Repository",
      "Requirements": []
    }
  }
}
```
However, that's also easily resolved by simply running `renv::snapshot()`:
```
{
  "R": {
    "Version": "4.2.2",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.17.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "4543b8cd233ae25c6aba8548be9e747e"
    }
  }
}
```

As a final test I tried to "upgrade" from 0.17.3 back to 0.16.0 and tried to do so using `reload=TRUE` and found that it did not actually restart my R session which is what I was expecting. It left an object in my global environment: `_renv_restore_state`.

```r
renv::upgrade(version = "0.16.0", reload = TRUE)
A new version of the renv package will be installed:

# GitHub =============================
- renv   [0.17.3 -> rstudio/renv@0.16.0]

This project will use the newly-installed version of renv.

Do you want to proceed? [y/N]: y
Retrieving 'https://api.github.com/repos/rstudio/renv/tarball/0e3aab27a928eb261819a3fc45a3ee2b4ba902a5' ...
	OK [downloaded 480.3 Kb in 0.9 seconds]
Installing renv [0.16.0] ...
	OK [built from source in 39 seconds]
Moving renv [0.16.0] into the cache ...
	OK [moved to cache in 13 milliseconds]
Warning messages:
1: In runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
2: In get(method, envir = home) : internal error -3 in R_decompress1
3: In get(method, envir = home) : internal error -3 in R_decompress1
4: In get(method, envir = home) : internal error -3 in R_decompress1
5: In runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
Error in runHook(".onLoad", env, package.lib, package) : 
  lazy-load database 'C:/Users/hutch3232/Documents/R/test_renv/renv/library/R-4.2/x86_64-w64-mingw32/renv/R/renv.rdb' is corrupt
In addition: Warning messages:
1: In get(method, envir = home) : internal error -3 in R_decompress1
2: In get(method, envir = home) : internal error -3 in R_decompress1
3: In get(method, envir = home) : internal error -3 in R_decompress1
4: In runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
```

**Comment by kevinushey** [comment]
For reference, the associated R bug report is here: https://bugs.r-project.org/show_bug.cgi?id=16644

That said, I believe the issue may be resolved in the latest `renv` releases, insofar that updating from renv 0.17.2 to any newer release shouldn't produce this error.
