### ISSUE TITLE
.Rprofile's `options()` vs .Renviron's `RENV_CONFIG_*`

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#1152]
I have a large project and after recently upgrading that project's {renv} to v0.16.0 I suddenly found myself with slow R startup times again, presumably because of {renv}'s various checks.
My `.Rprofile` file in that project contains both of these settings:
```r
options("renv.config.synchronized.check" = FALSE)
options("renv.config.updates.check" = FALSE)
```
In that R session, I double-checked to make sure those were set (e.g. via `options("renv.config.synchronized.check")`) and indeed they were there.

To test whether or not those values being _used_, I commented-out those two options in the `.Rprofile` file and created an `.Renviron` file with the equivalents. Important to note that there was previously no `.Renviron` file, and the base environment from which R was called has no `RENV_*` variables.
```r
RENV_CONFIG_SYNCHRONIZED_CHECK=FALSE
RENV_CONFIG_UPDATES_CHECK=FALSE
```
Upon restarting R, voila, quick startup and immediate prompt.

This leads me to believe that somehow the `.Rprofile` options were not being respected by {renv} upon startup.
Has the behavior of these changed somehow in the past few releases?

Has a 'verbose' mode for {renv} been considered, where we can see the various code-scanning, library-scanning, and lockfile-reading steps?

Also, the documentation for the `renv.config.synchronized.check` option suggests that the lockfile is compared to the library, but not necessarily the source code.
When `status()` is run, however, _source_ is inspected, too, and it's unclear to me if there's a way to just check the library-vs-lockfile without also scanning code.

**Comment by kevinushey** [comment]
Just to confirm, in your `.Rprofile` -- are those options are being set before the call to `source("renv/activate.R")`? I'm not able to reproduce in some simple local tests, so I might need some more information.

> Has a 'verbose' mode for {renv} been considered, where we can see the various code-scanning, library-scanning, and lockfile-reading steps?

It has, but we haven't carved out time to implement it yet.

It might be helpful if you could include an R profile -- you could put this in your profile `.Rprofile`:

```
Rprof("startup.Rprof")
# other .Rprofile code
Rprof(NULL)
```

Then, call `summaryRprof("startup.Rprof")` and share those results.

**Comment by kevinushey** [comment]
Sorry -- based on the sequence of events in how RStudio starts up projects using `renv` (assuming you're in RStudio) you might want to instead only include `utils::Rprof("startup.Rprof")` in the `.Rprofile`, and then later run:

```
utils::Rprof(NULL)
utils::summaryRprof("startup.Rprof")
```

after the long-running action has concluded.

**Comment by mmuurr** [comment]
> are those options are being set before the call to source("renv/activate.R")

oohhhhh of course they have to _precede_ `activate.R`; I'm a simpleton, forgive me.

(May still be worth reminding people in the Introduction doc or the "config" man page to make sure those settings precede the activation script :-) ).
