### ISSUE TITLE
renv.config.synchronized.check ... what does it do?

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#1153]
In earlier versions of {renv}, my recollection is that if `renv.config.synchronized.check` was enabled, upon project startup (i.e. R startup within that project), if the lockfile and library were out-of-sync, we'd receive the customary "may be out of sync" warning.
After upgrading to 0.16.0, however, I found long scan times (#1152) and then expected warnings (because I happened to know my library and lockfile are not synchronized) but received none.

To test this behavior:
1. I created a brand new empty project and ran `renv::init()`. The lockfile thus included on the R and {renv} versions.
2. Restart R to properly activate the {renv} project.
3. I then created a R file and added the single `library(Matrix)` line, and within the R session ran `renv::install("Matrix")`. Importantly **do not** `renv::snapshot()` and ensure that `renv.config.auto.snapshot` is ` FALSE`. Double-check the `renv.lock` file to ensure that indeed {Matrix} is not included. Inspect the project's `renv/library/{R-version}/{arch}/` directory to ensure that {Matrix} is installed. At this point the library and the lockfile are out-of-sync.
4. Quit and restart R with `renv.config.synchronized.check` set to TRUE in the project's `.Rprofile`.
5. No warning :-| 

I also replaced the `.Rprofile` version with the corresponding `RENV_CONFIG_SYCHRONIZED_CHECK=TRUE` `.Renviron` setting, still no warning.

When checking if {renv} does actually believe the library and lockfile are out-of-sync explicitly via `renv::status()`, I get the familiar:
```
The following package(s) are installed but not recorded in the lockfile:
          _
  Matrix    [1.5-3]
  lattice   [0.20-45]

Use `renv::snapshot()` to add these packages to your lockfile.
```

I'm quite confused as to what `renv.config.synchronized.check` actually does these days, is the above scenario expected?
If it doesn't present us with the expected warning, the startup cost (of scanning) seems expensive -- and it's even unclear how exactly to control that scanning (#1152).

Apart from a few small sources** of confusion, I love love love using {renv} :-)

** pun intended

**Comment by kevinushey** [comment]
Thanks! This seems like a bug / regression in `renv`; let me see if I can narrow it down.

**Comment by kevinushey** [comment]
Okay, I think I understand. Newer versions of `renv` are trying to do a slightly more light-weight dependency check, in that we basically just try to check if there's a package mentioned in the lockfile that doesn't appear in the project library, but not vice-versa.

This means that the case where a package is installed, but not recorded in the lockfile, will be missed by the 'synchronized' check. I'll see if this is really still necessary.

**Comment by kevinushey** [comment]
This should now be much better / faster in the development version of `renv`.

```
> system.time(renv:::renv_project_synchronized_check())
* The project is currently out-of-sync.
* Use `renv::status()` for more details.
   user  system elapsed
  0.247   0.022   0.269
```

Hopefully in similar projects, you'll see the synchronization check finishing in at most a couple of seconds.
