### ISSUE TITLE
Question: installing renv in a offline environment

### ISSUE THREAD

**Issue by nettoyoussef** [rstudio/renv#116]
I was pondering to use `renv` in a offline environment, but usually one would need other tools to install a package from github, such as devtools (e.g. `source_pkg()`), which in turn requires a long list of dependencies.

At the moment, is there a workaround? Or until `renv` enters CRAN it is better to use packrat?

Thanks in advance!

**Comment by kevinushey** [comment]
Can you elaborate a bit more? If `renv` (or Packrat even) need to retrieve packages from remote sources, they'll require internet connectivity to do so.

What are you trying to do exactly?

**Comment by nettoyoussef** [comment]
>Can you elaborate a bit more? If renv (or Packrat even) need to retrieve packages from remote sources, they'll require internet connectivity to do so.

Yes, sure. But using `packrat` one can save a local repo and install packages from source.
I understand that `renv` can do the same. 

My problem is installing `renv` in the first place. While I can install packrat directly from a tar ball, from what I understand to install renv I need to first download the master from github as a zip and then to the following:

```R
library(devtools)
source <- devtools:::source_pkg("path/to/renv.zip")
install(source)
```
But since `devtools` has other dependencies, such as `roxygen2`, I would have to install them first (and check if they have other dependencies), then install `devtools`, and finally, `renv`.

My question was if there were another way to install `renv` while it is not available at CRAN.

**Comment by kevinushey** [comment]
Something like the following should work:

```
setwd(tempdir())
url <- "https://github.com/rstudio/renv/archive/master.zip"
download.file(url, destfile = "renv.zip")
unzip("renv.zip")

system("R CMD build renv-master")
renv <- list.files(pattern = "^renv_")
install.packages(renv, repos = NULL, type = "source")
```

In other words, you don't need devtools to install packages from source -- you can just use the regular base R facilities to build and install from package sources / tarballs.

I'm hoping renv will be going to CRAN very soon so fortunately this will be moot at that point.

**Comment by nettoyoussef** [comment]
Whoa, that was fast!

Thanks Kevin!

**Comment by kevinushey** [comment]
Glad to hear it! Please let me know if you have any other questions or run into any roadblocks using renv.
