### ISSUE TITLE
stop 'fixing' my .gitignore :-)

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#1165]
Is there an option to prevent various {renv} functions from re-editing my `.gitignore` files?
The specific example here is as follows:
1. I have a `cellar/` (symlink to `local/` for backwards compatibility with some of my own tooling) under my `renv/` directory in a project. I.e. these directories exist:
    ```
    <project>/renv/local/
    <project>/renv/cellar/
    ```
2. In `<project>/renv/.gitignore` there are the standard entries:
    ```
    lock/
    sandbox/
    library/
    python/
    staging/
    ```
3. In this project, I choose to store my {renv} cellar _with_ the repo. Thus I've specifically removed `cellar/` and `local/` from {renv}'s standard `.gitignore` file. (I've also tried just commenting them, but {renv} is clever and undoes my comments in the next step :-)
4. At some point during the development lifecycle, {renv} (well, I assume it's {renv}) keeps **adding** the `cellar/` and `local/` entries back into my `.gitignore` file :-|  ... this means prior to each git add/commit cycle I need to edit that file, run my git commands, and then at some point in the future {renv} reverts my changes (to `.gitignore`). (Else my package tarballs which I want to commit to the repo don't get added.)

Is there any way to tell {renv} that I'm 100% okay with the current state of my `.gitignore` file and that it should (ironically?) _ignore_ it? Perhaps a config/option that changes the silent editing behavior to warnings?

**Comment by kevinushey** [comment]
There is a project setting that controls this; e.g. you should be able to use:

```
renv::settings$vcs.ignore.cellar(FALSE)
```

This will stop `renv` from trying to place `cellar/` in the `.gitignore`.

For a more general "stop touching my `.gitignore`", `renv` doesn't have that yet -- would that be useful?

**Comment by mmuurr** [comment]
Hm, my current `.Rprofile` looks like so:
```
options("renv.config.synchronized.check" = FALSE)
options("renv.config.updates.check" = FALSE)
options("renv.vcs.ignore.local" = FALSE)
options("renv.vcs.ignore.cellar" = FALSE)
source("renv/activate.R")
```
... but once I {renv}-activate the project, I get both of the `local/` and `cellar/` lines added-back to my `.gitignore`.

This is with {renv} v0.17.0, and I've validated this behavior with a brand new project via the following steps:
1. In a new/clean directory, start R and init {renv} with `renv::init()`. Quit R.
2. Edit `renv/.gitignore` by removing the `local/` and `cellar/` entries.
3. Edit `.Rprofile` by adding `options("renv.vcs.ignore.local" = FALSE)` and `options("renv.vcs.ignore.cellar" = FALSE)` **above** the `source("renv/activate.R")` line.
4. Start R. (Observe that {renv} is running.) Quit R.
5. Inspect `renv/.gitignore` ... the two lines have returned from the dead! 🧟

**Comment by mmuurr** [comment]
Wait -- I've also just realized the default `settings.dcf` file has both `vcs.ignore.cellar` and `vcs.ignore.local` set to `TRUE`. I assume this is the conflict source, and `settings.dcf` is overriding my profile's preferences.

I'll admit that I've never quite understood the inclusion of the `settings.dcf` (as earlier {packrat} and {renv} versions didn't have this, correct?), since the R-centric mechanism seems to be with `.Rprofile` -- and even the {renv} docs here suggest using `.Rprofile` (or equivalent).

**Comment by kevinushey** [comment]
The general idea is that "config"-level options are associated with a user, and "settings"-level options are associated with a project. In general, options that might need to be persistent, or need to be visible to other users / collaborators in a project, need to be stored with the project (and so become part of `settings.dcf`).

**Comment by mmuurr** [comment]
Yeah that makes sense; I do have some additional questions/thoughts about this, but I'll stew on them some more and perhaps open a separate Issue later for your feedback :-)

---

Re: the `.gitignore` issue, the only other suggestion might be to (in response to your question), yes, add a setting that enables/disables auto-modifying `.gitignore` files (with the default being enabled, as it is now), since for some projects those files are carefully crafted by the developer.

And/or a switch for increased verbosity by {renv}, letting the developer know what's happening (_especially_ when {renv} is modifying existing files).

**Comment by kevinushey** [comment]
This is now possible the development version of `renv` -- please see https://github.com/rstudio/renv/commit/1cfa13daf01229ab6c2c9adb426be0d3ba916097. Thanks!
