### ISSUE TITLE
.onLoad from user built package failing within renv

### ISSUE THREAD

**Issue by dbrandt2012** [rstudio/renv#1167]
I'm trying to implement renv in projects that primarily use a custom built private package ("syhelpr") to perform a variety of tasks. The package loads perfectly fine without any renv in the project environment but fails when renv is included. Additionally, the warnings in restore() seem to occur with any renv function I run:

```
> renv::restore()
* The library is already synchronized with the lockfile.
Warning messages:
1: In value[[3L]](cond) : restarting interrupted promise evaluation
2: In value[[3L]](cond) : restarting interrupted promise evaluation
> library(syhelpr)
Loading required package: foreach
Error: package or namespace load failed for ‘syhelpr’:
 .onLoad failed in loadNamespace() for 'syhelpr', details:
  call: loadNamespace(x)
  error: there is no package called ‘reticulate’
```

This is the code causing the failure within the syhelpr package
```
sy_init <- function() {
  library(pacman)
  pacman::p_load(
    devtools,
    here,
    odbc,
    tictoc,
    lubridate,
    fuzzyjoin,
    kableExtra,
    knitr,
    htmltools,
    tidyverse,
    dbplyr
  )
}

# python's 'uuid' module we want to use in our package
uuid <- NULL

#' Config File
#'
#' Loads common packages, configurations, db connections,
#'
#'
.onLoad <- function(libname, pkgname){
  sy_init()
  # delay load uuid module (will only be loaded when accessed via $)
  uuid <<- reticulate::import("uuid", delay_load = TRUE)
}
```

Further, I've tried `renv::install('reticulate')` and the same error occurs, even when I specify my repositories in the user .Rprofile and the project .Rprofile (not sure if this is redunant)
```
local({
  r <- getOption("repos")
  r["CRAN"] <- "https://cloud.r-project.org" 
  r["syapse"] <- "https://private/repository/path"
  options(repos = r)
})
```

I've read through the following issue but can't make the connection as I'm relatively new to R package development:
#https://github.com/r-lib/pillar/issues/252

**Comment by kevinushey** [comment]
What version of `renv` are you using? A new release of `renv` 0.17.1 was just pushed to CRAN, and it might resolve the issue you're seeing.

**Comment by dbrandt2012** [comment]
I was using `renv` 0.17.0. After updating to 0.17.1, I'm allowed to install packages as needed and the `Warning messages:
1: In value[[3L]](cond) : restarting interrupted promise evaluation` is gone.

I'm still getting 
```
Error: package or namespace load failed for ‘syhelpr’:
 .onLoad failed in loadNamespace() for 'syhelpr', details:
  call: loadNamespace(x)
  error: there is no package called ‘reticulate’
```
but I think that's in issue with out custom package dependencies.

I'll close once I can update those and confirm.

**Comment by kevinushey** [comment]
@dbrandt2012: thanks; let me know what you learn.

**Comment by hadley** [comment]
`sy_init()` doesn't look like correct package code to my eye; you should be declaring required packages in `DESCRIPTION`.

**Comment by dbrandt2012** [comment]
@kevinushey @hadley apologies, I forgot to circle back here. I removed `sy_init()` and cleaned up the `DESCRIPTION` for the package and all works perfectly!
