### ISSUE TITLE
renv 0.17.1 changed package hash

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#1168]
I upgraded to 0.17.1 this morning and when I took a snapshot, it changed the hash for the vast majority of my packages. The new hash didn't align with the package path in my cache. This was pretty unexpected. 

I tried it in two separate R environments (OS, R, RStudio and renv versions [0.16.0->0.17.1, 0.17.0->0.17.1]) and it occurred with both. 

One package example was BH. It didn't happen to R6, but it did to Rcpp and many others.

**Comment by kevinushey** [comment]
Thanks for the bug report; this was an unintentional change. I'll fix this ASAP and get a patch onto CRAN.

This shouldn't effect the integrity of the cache, but you may have some duplicate cache entries. I'll put together a tool for cleaning those up soon after.

**Comment by kevinushey** [comment]
I have a fix in https://github.com/rstudio/renv/commit/fad080814a9b9b747bb3ae462038739f3b2a0dfb; I'll do some testing to confirm all looks well on my end but please let me know if you can confirm as well.

**Comment by hutch3232** [comment]
Just tested on my end by backing up my renv.lock, upgrading to that new version, taking a new `renv:: snapshot()`, and then running it through `diff`. The only change was related to the renv package itself, as expected.

Thanks for fixing so quickly!

**Comment by kevinushey** [comment]
renv 0.17.2 is on its way to CRAN; hopefully to be accepted soon. Sorry for the rocky round of releases in 0.17.

**Comment by kevinushey** [comment]
renv 0.17.2 is now on CRAN!
