### ISSUE TITLE
Migration from Packrat to Renv

### ISSUE THREAD

**Issue by ckiefer** [rstudio/renv#117]
Dear All

Any ideas about this is highly appreciated. Packages in the project-specific packrat folder are not copied to the renv cache directory, hence, no symlinks are created from the "former" packrat project library files to the "new" renv cache files.

Pre-conditions:

- My private renv cache in  `~/.local/share/` is empty.
- .libsPaths() as printed in the R session:
```
> .libPaths()
[1] "/home/ckiefer/R/x86_64-pc-linux-gnu-library/3.5"
[2] "/opt/R/R3.5/library"
```

Steps to reproduce:

1. Install renv in project folder (the folder with the packrat project to be migrated): 
```
> remotes::install_github("rstudio/renv")
Installing package into ‘/home/ckiefer/R/x86_64-pc-linux-gnu-library/3.5’
DONE (renv)
```

2. Check renv status
```
> renv::status()
* This project has not yet been initialized.
```

3. Migration from Packrat to renv:
```
> renv::migrate()
* Migrating library from Packrat to renv ... [230/230] Done!
* Moving packages into the renv cache ... Done!
* The renv cache is already synchronized with the Packrat cache.
* The renv support infrastructure has been written.
* Project '~/RProjects/Renv_Test' has been migrated from Packrat to renv.
* Consider deleting the project 'packrat' folder if it is no longer needed.
```

4. Renv cache is empty (i.e., no files copied to ~/.local/share/renv/cache). Hence, no symlinks are created to cache files:
```
[user@host Renv_Test]$ ls ~/.local/share/renv/
bootstrap
```

Best, Chris

**Comment by kevinushey** [comment]
Just to check -- the project should still be functional after `renv::migrate()`, right? `renv` copies the Packrat library folder to the `renv` library folder, but does not move those packages into the global cache. (Most likely, we should)

**Comment by kevinushey** [comment]
Hmm, I'm wrong -- the installed packages _should_ be migrated to the renv cache, and we explicitly test for that in our examples:

https://github.com/rstudio/renv/blob/ba81b0f982452d44c24bc5af766f0feaca09b14c/R/migrate.R#L116-L123

Can you provide a reproducible example, or any other information?

**Comment by kevinushey** [comment]
Closing due to lack of response -- please feel free to re-open if you can provide more information.
