### ISSUE TITLE
issue with non-writable available package index

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#1171]
**Main issue:**

`renv::install("pkgname")` hangs indefinitely on `renv` >= 0.17.0 due to my non-standard setup. 

**Details:**

I have a large `renv` cache being used by many people. It's defined using the `RENV_PATHS_ROOT` environmental variable. That location is read-only* (for most users). For `renv` prior to 0.17.0 that would result in successful installs (simply a symlink) if the package existed in the cache and an error if it did not (because it can't write there).

Now, however, it seems to hang due to `renv:::available_packages`. 

I found that if I run `options(renv.index.enabled=FALSE)` the old behavior is restored. 

I'm wondering if there could be a solution where the index will automatically be used if it can succeed (maybe just a `file.access` test or something for write-ability) and disabled otherwise? Essentially to avoid having to specify this option in every project.

I realize this is probably a very uncommon setup so understand if this isn't worth it.

\* The reason my setup is like this is because we have the `renv` cache mounted to Docker environments and for technical reasons the mounts need to be read-only. There is a separate process (where the cache is writable) to add new packages.

Thanks for the awesome package!

**Comment by kevinushey** [comment]
Thanks for the bug report! I want `renv` to work out-of-the-box in cases like yours as well so I'd like to consider if there's a better way for `renv` to handle this.

As a workaround, you could place the available packages index in a shared location, with something like:

```
RENV_PATHS_INDEX = <path/to/shared/writable/location>
```

And that could be added to your R installation's `etc/Rprofile.site` so it would be active for all R installations.

**Comment by kevinushey** [comment]
Perhaps the index could be placed in a location like this by default:

```
<renvRoot>/shared/<index>
```

And system administrators could allow that directory to be considered readable + writable by all users by default if desired?

**Comment by hutch3232** [comment]
Thanks for these ideas! I tested the option of setting `RENV_PATHS_INDEX` to my `/.../R proj/renv/index`, where `index` is a new folder, and that worked well. I like this approach because it's presumably always going to be writeable. I'm guessing it's not the default because then others aren't getting to refer to it (even in cases where `RENV_PATHS_ROOT` is writeable. Setting the `etc/Rprofile.site` is a good idea too and might work for me.

**Comment by hutch3232** [comment]
I haven't had a chance yet to test your fix yet https://github.com/rstudio/renv/commit/998c0438b8482492626aba843847a49af845a4a9 but I was also looking at my `renv` setup in a different environment where it is shared between many users and is also writeable (due to using `RENV_CACHE_MODE`) and I noticed the cached available packages .rds files are accumulating. I think the intent was to remove the old one when creating a new one, but in my case since someone else wrote the .rds file, I'm unable to remove it.

 

https://github.com/rstudio/renv/blob/e24dfb3728e9efdf01e42074a109c7b90d23b5c1/R/index.R#L187

 

I wonder if the `RENV_CACHE_MODE` could be used to set the mode of the created .rds in a way similar to the tarballs under `source/` and the packages under `cache/`.

**Comment by kevinushey** [comment]
I think these commits should help:

https://github.com/rstudio/renv/commit/9abe0db495b2d32e545fa2a3607b37744c022f8e
https://github.com/rstudio/renv/commit/1178600059a2f0beb3f9fe4ffb70d7130b144986

Let me know if those make a difference.

**Comment by hutch3232** [comment]
Finally had a chance to test out these commits. Thank you for making these changes! It seems like this will work well and I like the approach taken.

**Comment by kevinushey** [comment]
Great to hear -- thank you!
