### ISSUE TITLE
autodetect packages loaded with lapply

### ISSUE THREAD

**Issue by geneh0** [rstudio/renv#1172]
Is it possible to have `renv` be able to detect dependencies when they're loaded via a list and `lapply`, instead of the traditional `library`? 

```
libraries <-
  c("dplyr",
    "highcharter",
    "knitr",
    "lubridate",
    "purrr",
    "scales",
    "stringr",
    "survival",
    "tidyr")

invisible(lapply(libraries, library, character.only = TRUE))
```

**Comment by hadley** [comment]
It's extremely difficult to perform this sort of analysis 100% correctly using only static analysis, so I'd recommend to use individual `library()` calls for each package.
