### ISSUE TITLE
Get Gitlab host from Global Variable

### ISSUE THREAD

**Issue by grimmjulian** [rstudio/renv#1174]
Hello,

I tried setting up Renv to use a private Gitlab server following [this stackoverflow post](https://stackoverflow.com/questions/62772833/use-renv-for-private-gitlab-package) and [this issue](https://github.com/rstudio/renv/issues/476).

```
options(renv.config.gitlab.host = "https://gitlab.mycompany.de")
Sys.setenv(GITLAB_PAT = "...")
```

After reading the documentation I found, that I can use Environment Variables in .Renviron instead of options.
However, the GITLAB_PAT key works, but the GITLAB_HOST option does not seem to work as it still tries to connect to `https://gitlab.com` , even though the options work. 
Does anybody else have this issue?

**Comment by kevinushey** [comment]
It should work if you set `RENV_CONFIG_GITLAB_HOST` -- see https://rstudio.github.io/renv/reference/config.html#details for more details.

**Comment by grimmjulian** [comment]
Thanks for the Correction! For some reason I read it so that I need to set `GITLAB_HOST` instead of `RENV_CONFIG_GITLAB_HOST`.
