### ISSUE TITLE
Dealing with MRAN retirement

### ISSUE THREAD

**Issue by arnauddeblic** [rstudio/renv#1179]
Dear @kevinushey,
As you know, MRAN server will be shut down on July 1, 2023. Do you already know how this will affect `renv` package?
I assume that you will use Posit Public Repository Manager snapshots, but I would enjoy to have more details, so that I can start to think about the impacts in my company (firewall configuration, Nexus configuration, etc.). Typically, will you use the same kind of database to store the relevant snapshot date? And so on..
Please feel free to tell me if another way would be more appropriate than "issues" to ask such questions!
Kind regards
Arnaud

**Comment by kevinushey** [comment]
Thanks! I think this is an appropriate venue for such questions.

Indeed, the goal is to use the public Posit package manager instance for binaries going forward.

The MRAN database used by `renv` might no longer be necessary, as we'll be able to download binaries directly from the "current" snapshot by asking for the package in the archive. But that will take some more time to evaluate. If that's not possible, then I think we'll be able to build and maintain a similar database file for the Posit package manager.
