### ISSUE TITLE
use() as an alias for library()

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#118]
But allowing for a remote spec. So, for example:

```
renv::use("r-lib/rlang")
```

would likely just mean `library(rlang)`, but static analysis tools could use the original form to ascertain where the package could / should be retrieved.

**Comment by MilesMcBain** [comment]
This is a great idea. I often do something like this in my projects:

`library(ragg) #thomasp85/ragg`

for things that are Github only.

**Comment by kevinushey** [comment]
This has now been implemented; both with `renv::use()` + `renv::embed()` to generate a call to `renv::use()` that basically embeds an `renv` lockfile within an R / R Markdown document.

A vignette or some other "advertisement" of these functions would probably be useful.
