### ISSUE TITLE
Error when renv_available_packages_latest called during install

### ISSUE THREAD

**Issue by jeetinder72** [rstudio/renv#1180]
I have a package called dbstan which I install from "covidestim/dbstan". 

I can install this package ok within renv but when I try to install all my other packages, I see (using traceback) that an error is hit when renv_available_packages_latest is called on the above package (the package is not available error, as well as it not being available on MRAN). 

I can't seem to get past this error - any ideas how I could?

**Comment by kevinushey** [comment]
Can you please share a reproducible example, or the code you're running and the output you're seeing?

**Comment by jeetinder72** [comment]
I was able to reproduce the issue based on the attached test project. I just have one R script in the project called test. You can reproduce the error by running renv::install().
[renv_test.zip](https://github.com/rstudio/renv/files/11072286/renv_test.zip)

**Comment by jeetinder72** [comment]
the below are the contents of the test script. So importing this into a project and then running renv::install() should reproduce the error. The key part in terms of reproducing the error is just the installing of the dbstan package.

install.packages("covidestim/dbstan")

library(dbstan)
library(dplyr)
library(lubridate)
library(ggplot2)
library(MASS)
library(datasets)

data(iris)

summary(iris)

iris %>% group_by(Sepal.Length)

ggplot(iris) + geom_bar(aes(x = Sepal.Length))

id <- stanfit_insert(fit1, conn, insert_samples = T)

**Comment by kevinushey** [comment]
Here's the error I saw:

```
Installing dbstan [0.0.0.9000] ...
	FAILED
Error installing package 'dbstan':
==================================

Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package 'dbstan' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'dbplyr'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'dbstan'
* removing 'C:/Users/kevin/Downloads/renv_test/renv/staging/1/dbstan'
```

It seems like the package depends on `dbplyr` without properly specifying that in the DESCRIPTION file. You can manually install `dbplyr` first, e.g. with

```
install.packages("dbplyr")
```

Also note your code has other issues; e.g. `stanfit_insert` references a variable `conn` that doesn't exist, and apparently uses a parameter `insert_samples` which should probably be called `include_samples`.

**Comment by jeetinder72** [comment]
yes, the last part was just so that it was using a function from the dbstan package - it would be quite involved to actually create those inputs.

I will try installing dbplyr first and see if that helps.

**Comment by jeetinder72** [comment]
so if I first install dplyr and then  renv::install("covidestim/dbstan"), I still get the same error below when running renv:install():

> renv::install()
Error: package 'dbstan' is not available
In addition: Warning messages:
1: package 'dbstan' is not available 
2: package 'dbstan' is not available from MRAN 

dbstan actually installs fine when I run the above renv::install("covidestim/dbstan") command.

This is the output of traceback():

> traceback()
7: stop(sprintf(fmt, ...), call. = call.)
6: stopf("package '%s' is not available", package)
5: renv_available_packages_latest(package)
4: renv_retrieve_impl(package)
3: handler(package, renv_retrieve_impl(package))
2: retrieve(names(remotes))
1: renv::install()

**Comment by kevinushey** [comment]
Right, because `renv::install()` (when invoked without arguments) is not able to infer that `dbstan` is a package that should be installed from https://github.com/covidestim/dbstan, and not from CRAN like all the other packages referenced.

If you need to communicate information like this, you need to use a project `DESCRIPTION` file with a `Remotes:` field. For example:

```
Depends: dbstan
Remotes: covidestim/dbstan
```

**Comment by jeetinder72** [comment]
ah ok, that was not something I was aware of this. That sounds like it should solve it, appreciate your time.

**Comment by jeetinder72** [comment]
ok, so I have now created a DESCRIPTION file in my project containing the above but I still get the same error when running renv::install(). Am I missing a step (PS I restarted my R session)?

**Comment by jeetinder72** [comment]
There was one package left to install which I was able to by including the name of the package inside renv::install(). 

I don't fully understand why renv::install() doesn't work without doing this though. If I still had multiple packages left to install for example, would I have to do them manually?

**Comment by kevinushey** [comment]
Thanks; I hope you find the package useful!
