### ISSUE TITLE
No package names in renv::diagnostics()

### ISSUE THREAD

**Issue by csadagents** [rstudio/renv#1182]
Hi @ all,
since the update to version 0.17.2, after running renv:diagnostics(), no package names are listed in the #packages section of the output. Instead of the names there is a running index from 1 to n. It would be great if you could fix this. Thanks and keep up the good work <3

R version 4.2.3 (2023-03-15)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: AlmaLinux 8.7 (Stone Smilodon)
renv version: renv_0.17.2

**Comment by kevinushey** [comment]
Thanks for the bug report -- I'll take a look.

**Comment by kevinushey** [comment]
Should be fixed up now; thanks for reporting! Hopefully we'll be able to prepare a patch release for CRAN soon.

**Comment by csadagents** [comment]
> Should be fixed up now; thanks for reporting! Hopefully we'll be able to prepare a patch release for CRAN soon.

Thanks a lot!
