### ISSUE TITLE
snapshot due to pre-flight validation failure

### ISSUE THREAD

**Issue by sclewis23** [rstudio/renv#1183]
I'm able to use 0.17.1 and make a snapshot but if I install that latest version 0.17.2 it gives me the following error:
'Do you want to proceed? [y/N]: y
Error in renv::snapshot() :
aborting snapshot due to pre-flight validation failure
'
Should I use force ?

**Comment by sclewis23** [comment]
I used force, it updated the lock file, but when I run the snapshot again it fails unless I use force.

**Comment by kevinushey** [comment]
Thanks for the bug report. Are you able to share a reproducible example? Is renv showing any information regarding the pre-flight validation failure?

**Comment by sclewis23** [comment]
``` r
renv::snapshot(prompt = FALSE)
#> Error in renv::snapshot(prompt = FALSE): aborting snapshot due to pre-flight validation failure
```

<sup>Created on 2023-03-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I don't see anything else? What else can I provide?

**Comment by sclewis23** [comment]
Do you think it could be related to the hash being update with renv 0.17.0 ?

**Comment by kevinushey** [comment]
Can you try the following?

```
options(renv.verbose = TRUE)
options(warn = 1)
trace(renv:::renv_snapshot_validate, exit = quote(print(ok)))
renv::snapshot(prompt = FALSE)
```

What output do you see in that case?

You can also try using the R debugger yourself, stepping through `renv_snapshot_validate`:

```
debug(renv:::renv_snapshot_validate)
renv::snapshot()
```

and step through to see where validation appears to be failing.

**Comment by sclewis23** [comment]
`options(renv.verbose = TRUE)
options(warn = 1)
trace(renv:::renv_snapshot_validate, exit = quote(print(ok)))
#> Tracing function "renv_snapshot_validate" in package "renv
#> (not-exported)"
#> [1] "renv_snapshot_validate"
renv::snapshot(prompt = FALSE)
#> Tracing renv_snapshot_validate(project, new, libpaths) on exit 
#> [1] FALSE  TRUE FALSE  TRUE
#> Error in renv::snapshot(prompt = FALSE): aborting snapshot due to pre-flight validation failure`

**Comment by kevinushey** [comment]
Okay, I do not know why you're not seeing any output related to why snapshot validation is failing. Are you running renv in some special environment, or just locally on your machine? The validation errors suggest something is wrong with either your Bioconductor dependencies, or the versions of packages installed are not compatible.

**Comment by sclewis23** [comment]
It is on our RStudio Workbench Server, I have been using this project (I have a project for 4.1.2, 4.0.0, and 3.6.3) as one place to update our shared cache.
We do have some dependency issues within some package from different releases but it hasn't caused an issue before.
The following Bioconductor packages appear to be from a separate Bioconductor release:

	synergyfinder   [installed 2.4.16 != latest 2.2.4]
	MatrixGenerics  [installed 1.2.1  != latest 1.0.2]
	fgsea           [installed 1.16.0 != latest 1.14.0]
	ggtree          [installed 2.4.2  != latest 2.2.4]
	rhdf5filters    [installed 1.2.1  != latest 1.0.1]
	org.Hs.eg.db    [installed 3.12.0 != latest 3.11.4]
	EnhancedVolcano [installed 1.8.0  != latest 1.6.0]
	impute          [installed 1.64.0 != latest 1.62.0]
	BiocGenerics    [installed 0.36.1 != latest 0.34.0]
	Biobase         [installed 2.50.0 != latest 2.48.0]
	GO.db           [installed 3.12.1 != latest 3.11.4]
	Rhdf5lib        [installed 1.12.1 != latest 1.10.1]
	rhdf5           [installed 2.34.0 != latest 2.32.4]

**Comment by kevinushey** [comment]
Sorry, but are you saying that you _were_ seeing these messages before, but you didn't include them when you opened the issue? What is the entire output you're seeing? It really feels like you're not accurately describing everything you're trying to do, and the output you're seeing, which makes it difficult for me to provide feedback.

If you want to ignore the messages, just set `options(renv.config.snapshot.validate = FALSE)`.

**Comment by sclewis23** [comment]
Sorry, about the miss understanding....yes I have been getting these messages about bioconductor (for version of renv previously) may not be able to restored.
The issue now is the snapshot fails...did a change in renv change about if the validate failed?
I didn't have any issue until I upgraded my renv version to 0.17.2.

**Comment by hadley** [comment]
I'd recommend starting by following renv's advice to update the needed dependencies. If that doesn't help, please file a new issue with a reprex that allows us to reproduce your problem from a fresh project.
