### ISSUE TITLE
issue with setting library on `renv::restore` on update to 0.17.2

### ISSUE THREAD

**Issue by jamieRowen-mediacom** [rstudio/renv#1190]
Restoring from a lockfile to a specific library path under 0.17.0 worked perfectly. On using 0.17.2 this now fails with the following error

```
#17 6.456   unused argument (library = "/opt/R/3.4.4/lib64/R/library")
#17 6.456 Calls: <Anonymous> ... %in% -> renv_packages_base -> %||% -> installed_packages
```

Having a look at the diff between the 0.17.0 and 0.17.2 tags I believe the issue arises [here](https://github.com/cran/renv/compare/0.17.0...0.17.2#diff-eab3f37d71e88037a65cece28c25b2ca15224c7b7a669fc5c393b3a290462edcR7) where the parameter of the function is instead `lib.loc`

[Linked](https://github.com/cran/renv/compare/0.17.0...0.17.2#diff-8e77d3fb6a6c3afce5d20722587ca366b7c8d9303fd9fd9b1c3ad596eb75c515R2) diff view the definition of `installed_packages`

**Comment by kevinushey** [comment]
Thanks -- this has been fixed in the development version; I'm hoping to get an upgrade on CRAN soon.

**Comment by jamieRowen-mediacom** [comment]
Great, thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
