### ISSUE TITLE
[Feature request] Populate project cellar from renv.lock file for offline execution

### ISSUE THREAD

**Issue by egillax** [rstudio/renv#1192]
I have an airgapped (offline) server where I often need to run analyses. It would be nice if I could somehow populate a project's cellar with package sources from the renv.lock file so I could restore the env easily in the offline environment.

**Comment by kevinushey** [comment]
You could also use `renv::isolate()` to copy the packages from cache directly into the project library. Would that be a suitable alternative?

**Comment by kevinushey** [comment]
Thanks for clarifying. There isn't anything directly available in `renv`, but it shouldn't be too arduous to implement. It seems like a reasonable request to me.

**Comment by hadley** [comment]
We now think this is probably out of scope for renv given the working and competing prioirities. One way you could work around this limitation would be to use [miniCRAN][https://andrie.github.io/miniCRAN/] or similar to create your on CRAN mirror on the air grapped machine.
