### ISSUE TITLE
[Feature Request] Override repositories in lock file

### ISSUE THREAD

**Issue by malcolmbarrett** [rstudio/renv#1193]
`renv.config.repos.override` allows me to override the repo used in `restore()`. Often I want the opposite of this, too: being able to override the repo written by `snapshot()`

Because we use RSPM on our server but CRAN locally, often I need to undue those changes when snapshotting.

**Comment by kevinushey** [comment]
`snapshot()` just uses whatever you have in `getOption("repos")`, so you could just set that before calling `snapshot()`. Or, I can add a parameter to `renv::snapshot()` to make it a bit more direct.

**Comment by malcolmbarrett** [comment]
I did try `snapshot(repos = list(RSPM = the_url_to_it))` but all it still changed all the package-level repo names to CRAN

**Comment by kevinushey** [comment]
> changed all the package-level repo names to CRAN

Sorry, do you mean that you want a way to control what repository name is included in each package record? As opposed to the set of repositories that get encoded into the top-level of the lockfile?

**Comment by malcolmbarrett** [comment]
Right

**Comment by malcolmbarrett** [comment]
(And using `repos` does indeed change the top-level info, that's just not what I'm looking to control)

**Comment by hadley** [comment]
If you mean the `Repository` field, then that's something that is provided by the source repo, and not something that I think renv should mess with. (Although it certainly might record the information in another way).

**Comment by malcolmbarrett** [comment]
(Picking a random entry in our lock file), if I `snapshot()` locally often it will change the entry to 

```
...
    "brio": {
      "Package": "brio",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "976cf154dfb043c012d87cddd8bca363",
      "Requirements": []
    },
...
```
But I want to keep it as RSPM for our deployed version

```
...
    "brio": {
      "Package": "brio",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "RSPM",
      "Hash": "976cf154dfb043c012d87cddd8bca363",
      "Requirements": []
    },
...
```

Again, I see this as sort of the opposite of `renv.config.repos.override` for the same reason as this option's documentation:

> Primarily useful for deployment / continuous integration, where you might want to enforce the usage of some set of repositories [...]

**Comment by hadley** [comment]
And the problem with having `Repository: CRAN` is that you don't get binaries when you deploy to connect? If that's the case, we should globally configure our connect server to use RSPM for CRAN packages.

**Comment by malcolmbarrett** [comment]
Right, although in this case, it's mainly on CI. If interfering with the repository field is problematic, maybe I'm thinking of this problem backward. Maybe we should have CRAN be our default and force `renv.config.repos.override` in the CI pipeline.

**Comment by kevinushey** [comment]
For what it's worth, by default, `renv` tries the repositories declared in `getOption("repos")` one-by-one (in order) when attempting to install packages with `Source: "Repository"`. The "Repository" field is mainly a "preferred" repository; that is, if there is a named repository matching that repository, we'll try that repository first when retrieving that package.

To wit, if the only active repository at `restore()` time is an RSPM repository, then that's the only repository that would be used, even for packages with `Repository: CRAN` or some other alternate repository.

**Comment by hadley** [comment]
It sounds like there are adequate workarounds for this case for now, so I'm going to close this issue. We'll continue to think about the more general problem, which I think is closely related to #1052.

**Comment by malcolmbarrett** [comment]
Yes I think that issue is close enough, thanks!
