### ISSUE TITLE
Feature Request: Renv update with bitbucket

### ISSUE THREAD

**Issue by CorneeldH** [rstudio/renv#1194]
We have our own (semi-)private packags in bitbucket. renv::install works, but renv::update not yet (while we are updating our own packages quite often. Is there a roadmap or timeline for adding support for bitbucket in renv::update? Or R-universe for that matter

Currently we are just using renv::install for these packages.

Thanks!

**Comment by kevinushey** [comment]
There isn't a timeline yet, but it shouldn't be too hard to add support here -- we'd just need to detect and support Bitbucket here.

https://github.com/rstudio/renv/blob/a1e9b24e261cbccb9d733d1797674489eb29a231/R/update.R#L146-L154
