### ISSUE TITLE
renv doesn't support full Bioconductor remote spec

### ISSUE THREAD

**Issue by arcresu** [rstudio/renv#1195]
The [remotes documentation](https://remotes.r-lib.org/articles/dependencies.html#other-sources) gives these examples for Bioconductor specs:

```
# Bioconductor
Remotes: bioc::3.3/SummarizedExperiment#117513, bioc::release/Biobase
```

however renv 0.17.3 doesn't properly handle either of these.

`"bioc::3.3/SummarizedExperiment#117513"`:
<details><pre>
renv:::renv_remotes_parse("bioc::3.3/SummarizedExperiment#117513")
#> $spec
#> [1] "bioc::3.3/SummarizedExperiment#117513"
#> 
#> $package
#> NULL
#> 
#> $type
#> [1] "bioc"
#> 
#> $host
#> NULL
#> 
#> $user
#> [1] "3.3"
#> 
#> $repo
#> [1] "SummarizedExperiment"
#> 
#> $subdir
#> NULL
#> 
#> $pull
#> [1] "117513"
#> 
#> $ref
#> NULL
</pre></details>

`"bioc::release/Biobase"`:
<details><pre>
renv:::renv_remotes_parse("bioc::release/Biobase")
#> $spec
#> [1] "bioc::release/Biobase"
#> 
#> $package
#> NULL
#> 
#> $type
#> [1] "bioc"
#> 
#> $host
#> NULL
#> 
#> $user
#> [1] "release"
#> 
#> $repo
#> [1] "Biobase"
#> 
#> $subdir
#> NULL
#> 
#> $pull
#> NULL
#> 
#> $ref
#> NULL
</pre></details>

`"bioc::Biobase"` (works as intended):
<details><pre>
renv:::renv_remotes_parse("bioc::Biobase")
#> $spec
#> [1] "bioc::Biobase"
#> 
#> $repository
#> [1] "bioc"
#> 
#> $package
#> [1] "Biobase"
#> 
#> $version
#> NULL
#> 
#> $type
#> [1] "repository"
</pre></details>

I found this when installing a package that uses one of these Bioconductor specs [in its DESCRIPTION](https://github.com/thackl/gggenomes/blob/06195f7137f572b6fdc5f6a57745de7cfb10d2b5/DESCRIPTION#L21) resulted in an obscure error. I think the underlying cause is the package name not being properly extracted from the spec:
```r
> renv::install("thackl/gggenomes@fd0ada41")
Retrieving 'https://api.github.com/repos/thackl/gggenomes/tarball/fd0ada41012c031651cce11fdb06f35d5a7c6f7b' ...
	OK [downloaded 48 Mb in 23 seconds]
Error in record$Package : object of type 'closure' is not subsettable
Traceback (most recent calls last):
16: renv::install("thackl/gggenomes@fd0ada41")
15: retrieve(names(remotes))
14: handler(package, renv_retrieve_impl(package))
13: renv_retrieve_impl(package)
12: renv_retrieve_github(record)
11: renv_retrieve_package(record, url, path)
10: renv_retrieve_successful(record, path)
 9: renv_retrieve_handle_remotes(record, subdir = subdir)
 8: renv_retrieve_handle_remotes_impl(remote)
 7: dynamic(key = list(remote = remote), value = renv_retrieve_handle_remotes_impl_one(remote))
 6: `_renv_dynamic_objects`[[id]] %??% {
        dlog("dynamic", "memoizing dynamic value for '%s'", id)
        value
    }
 5: renv_retrieve_handle_remotes_impl_one(remote)
 4: warningf(fmt, remote, record$Package)
 3: warning(sprintf(fmt, ...), call. = call., immediate. = immediate.)
 2: sprintf(fmt, ...)
 1: base::sprintf(fmt, ...)
```

**Comment by kevinushey** [comment]
I've made a change in `renv` to support the (simpler) version of such remotes. Please let me know if that works in your case.

**Comment by arcresu** [comment]
Thanks for this! I can confirm that the package in question now installs for me.

I notice that `renv_remotes_parse()` still gives the same incorrect output since the fix is applied afterwards. I know that's an internal helper function, but it's been useful for debugging renv's parsing in the past, so it would be nice if it were accurate. Anyway the core problem is solved, so thanks again.

**Comment by kevinushey** [comment]
One thing I recently learned is that the remotes syntax here is mostly used to install packages from the Bioconductor git repository, hosted at https://git.bioconductor.org/. We could probably take advantage of that when trying to install Bioconductor packages from git-like remote specifications.

**Comment by hadley** [comment]
Closing, since it looks like the motivating problem has been resolved.
