### ISSUE TITLE
Confusing prompt from `snapshot()`

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#1198]
Here's a (redacted) exchange received with {renv} v0.17.3 when running `snapshot()`:
```r
> renv::snapshot()
The following required packages are not installed:

        some, redacted, in_development,
        packages

Packages must first be installed before `renv` can snapshot them.
Consider installing these packages using `renv::install()`.
Use `renv::dependencies()` to see where this package is used in your project.

Do you want to proceed? [y/N]: 
```
It's not clear what "proceed" means here. `status()` gives effectively the same message but without the prompt to "proceed".

When I select `y`, `snapshot()` reports that `The lockfile is already up to date`, but it can be a bit unsettling to select `y` to verify (to oneself) that last fact.

**Comment by kevinushey** [comment]
The idea here is that calling `renv::snapshot()` will create a lockfile which doesn't contain those packages. However, because it appears that your project does depend on / use those packages, the lockfile may not capture the required state of your project.

Would it help if we explicitly said "Do you want to create a lockfile without these packages? [y/N]"

**Comment by mmuurr** [comment]
I guess the confusing part is that I already have a lockfile (in that above example). It's not clear to what "proceed" will do here: {renv} is implying it'll do _something_, but what? In the end, it did nothing, because there was a lockfile and all was okay.

So in response to your question, yes, I think {renv} telling the user what it is about to do is probably helpful.

I can stew on this some more and get back to you, too. (I certainly use {renv} enough that it's always top-of-mind for me :-)

**Comment by mmuurr** [comment]
Ah, I've worked out a larger example that I think helps explain my confusion. In the example below, which just extendes the example above, I've taken a fresh dependency on {fortunes}, made a snapshot, then removed that dependency, now am running `snapshot()` again to remove {fortunes} from the lockfile:
```
> renv::snapshot()
The following required packages are not installed:

	my, redacted, packages

Packages must first be installed before `renv` can snapshot them.
Consider installing these packages using `renv::install()`.
Use `renv::dependencies()` to see where this package is used in your project.

Do you want to proceed? [y/N]: y
NOTE: Dependency discovery took 11 seconds during snapshot.
Consider using .renvignore to ignore files -- see `?dependencies` for more information.
Use `renv::settings$snapshot.type("all")` to disable dependency discovery during snapshot.
The following package(s) will be updated in the lockfile:

# Repository =========================
- fortunes   [1.5-4 -> *]

Do you want to proceed? [y/N]: y
* Lockfile written to '~/github.com/gorisio/nonessentialtrivia/renv.lock'.
*
```
I see now that I'm given _two_ "Do you want to proceed?" prompts, but as a long-time user of {renv}, that first prompt looked (to me) like it was about to update the lockfile (without telling me what was about to be updated). In fact it's the second prompt that I was expecting all along.

So, yeah, I think it's still a bit confusing, but (perhaps counterintuitively) _more_ confusing to those already familiar with {renv}, as I think(?) seeing both prompts is somewhat new(ish) behavior for this flow.

**Comment by hadley** [comment]
I wonder if this is another place where spelling out the options might be useful:

```
The following packages are needed but not installed:
* some
* redacted
* in_development
* packages

What do you want to do?
1. Install the packages, then snapshot
2. Snapshot, just using the currently installed packages
3. Cancel
```

**Comment by kevinushey** [comment]
That sounds like a good idea to me as well.
