### ISSUE TITLE
Several GitHub packages are able to be installed explicitly, but something is consistently corrupt

### ISSUE THREAD

**Issue by ryandward** [rstudio/renv#1199]
```
> renv::install("drcData=DoseResponse/drcData")
Installing drcData [1.1-3] ...
	OK [linked cache in 0.11 milliseconds]
* Installed 1 package in 9.2 milliseconds.
> renv::install()
Error: package 'drcData' is not available
```

Do you have any suggestions? 
Using Linux and renv version 0.17.3

**Comment by kevinushey** [comment]
How is `drcData` declared and used in the project? Does your project have a DESCRIPTION file with the field:

```
Remotes: drcData=DoseResponse/drcData
```

**Comment by hadley** [comment]
Your code works for me in a fresh project:

```
[main] >  renv::install("drcData=DoseResponse/drcData")
Retrieving 'https://api.github.com/repos/DoseResponse/drcData/tarball/09f9da308aeea62322b0a7b67946435a87c36589' ...
	OK [downloaded 148.4 Kb in 1 second]
Installing drcData [1.1-3] ...
	OK [built from source in 1.1 seconds]
Copying drcData [1.1-3] into the cache ...
	OK [copied to cache in 18 milliseconds]
* Installed 1 package in 2.2 seconds.
[main] >  renv::install()
* There are no packages to install.
```

So as @kevinushey suggests it's likely to be something specific your project and we'll need more details.

**Comment by ryandward** [comment]
Thanks for looking into this. I figured as much — the project is years old now, but I just started using renv the day I commented here. Could it be incompatible packages? What kind info can I provide to help figure it out?

**Comment by hadley** [comment]
Before we dig into that further does using `renv::install("DoseResponse/drcData")` make any difference? You only need to use `=` if the package name doesn't match the repo name.

If that doesn't make any difference, we'd need some way to reproduce what you're seeing to have a chance at fixing it. Given a problem like yours, you could start by making a copy of your project, and then gradually remove files until the problem no longer appears. However, it's possible that the problem is caused by some conflict in the combination of package versions that you've installed over time and it'll be very difficult to reproduce.

Can you include a copy of your `DESCRIPTION` file, if you're using one?

**Comment by ryandward** [comment]
Yeah, this also produced the same error:

``` R
> renv::install("DoseResponse/drcData")
Installing drcData [1.1-3] ...
	OK [linked cache in 0.26 milliseconds]
* Installed 1 package in 38 milliseconds.
> renv::install()
Error: package 'drcData' is not available
```

I think you're right. I don't think this is necessarily a renv problem. I just modified the forked version of drc to abolish references to drcData. 

We can probably just pretend this never happened. If you're curious:

### Changes I made in this edition https://github.com/ryandward/drc: 
- NAMESPACE file: Removed the line import(drcData) to prevent importing functions and objects from the drcData package.
- DESCRIPTION file: Removed the drcData from the Depends: field to eliminate the package dependency.
- README.md and README.Rmd: Removed the instructions related to installing the drcData package.
- .travis.yml: Removed the line - DoseResponse/drcData to avoid referencing the drcData package in Travis CI configuration.
- docs/index.html: Removed the instructions related to installing the drcData package.

**Comment by kevinushey** [comment]
I guess my question here really is: why do you expect `renv::install()`, when invoked without arguments, to successfully install the `drcData` package? (How should `renv` know that `drcData` should be installed from that remote repository?)

**Comment by ryandward** [comment]
https://github.com/rstudio/renv/issues/1199#issuecomment-1521758554

Maybe this isn't how `install` intended to be used and I should use `restore` instead? But the strange issue for me is that it works in a clean project. 

Here's the same operations on a totally new project:
```R
> renv::install("drcData=DoseResponse/drcData")
Installing drcData [1.1-3] ...
	OK [linked cache in 0.56 milliseconds]
* Installed 1 package in 17 milliseconds.
> renv::install()
* There are no packages to install.
```

I can `snapshot`, `restore`, `install`, whatever without arguments, and the new pristine project seems to work just fine. It gives the impression that there's something muddy about my bigger/older project, and initially wanted to understand where the incongruences are coming from.
