### ISSUE TITLE
Can't find packages installed from alternate repositories

### ISSUE THREAD

**Issue by karawoo** [rstudio/renv#120]
I have a project that uses packages I've installed from a repository that my workplace maintains (http://ran.synapse.org). When I initialize renv, it warns me that these packages were installed from an unknown source:

``` r
## Install package
install.packages('synapser', repos = 'http://ran.synapse.org')
#> 
#> The downloaded binary packages are in
#>  /var/folders/m5/b4h1d7k16dxcvp3px2x8kvy00000gp/T//RtmpIPRycN/downloaded_packages

## Create project
library("fs")
dir_create("my_project")
setwd("my_project")
file_create("test.R")
writeLines(
  "library('synapser')",
  "test.R"
)

## Set up renv
renv::init()
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> The following package(s) were installed from an unknown source:
#> 
#>  pack, PythonEmbedInR, synapser
#> 
#> renv may be unable to restore these packages in the future.
#> Consider re-installing these packages from a known source (e.g. CRAN).
#> 
#> * Lockfile written to '/private/var/folders/m5/b4h1d7k16dxcvp3px2x8kvy00000gp/T/RtmpxUWSzf/reprex30021e64ba59/my_project/renv.lock'.
```

<sup>Created on 2019-07-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As suspected [on twitter](https://twitter.com/kevin_ushey/status/1156315177400164352), the description for this package is missing a Repository field:

``` r
packageDescription("synapser")
#> Package: synapser
#> Type: Package
#> Title: R language bindings for Synapse API
#> Version: 0.6.61
#> Date: 2019-07-19
#> Authors@R: c( person("Bruce", "Hoff", role = c("aut", "cre"),
#>        email = "bruce.hoff@sagebase.org"), person("Kimyen",
#>        "Ladia", role = c("aut"), email =
#>        "kimyen.ladia@sagebase.org"), person("Sage Bionetworks",
#>        role = c("cph")) )
#> Maintainer: Bruce Hoff <bruce.hoff@sageabse.org>
#> BugReports: https://github.com/Sage-Bionetworks/synapser/issues
#> Description: Provides R language bindings for Synapse RESTful web
#>        services.
#> License: Apache License 2.0
#> Imports: PythonEmbedInR(>= 0.3.25), utils, methods
#> Depends: R(>= 3.3)
#> Suggests: testthat, knitr, rmarkdown
#> URL: https://www.synapse.org
#> VignetteBuilder: knitr
#> SystemRequirements: libssl-dev, libcurl-dev, zlib-dev
#> Additional_repositories: http://ran.synapse.org
#> RoxygenNote: 6.0.1
#> NeedsCompilation: no
#> Packaged: 2019-07-20 00:42:28 UTC; administrator
#> Author: Bruce Hoff [aut, cre], Kimyen Ladia [aut], Sage
#>        Bionetworks [cph]
#> Built: R 3.6.0; ; 2019-07-20 00:43:03 UTC; unix
#> 
#> -- File: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/synapser/Meta/package.rds
```

It would be great if there were a way for me to provide renv with the missing info about the source of this package. Or, is there some change to the synapser package's DESCRIPTION file that would solve this issue?

**Comment by kevinushey** [comment]
One way to work around this on your end would be to include a Repository field; e.g.

```
Repository: synapse
```

`renv` would then infer that the package could be installed from a CRAN-like repository -- that is, one of the repositories currently specified in `getOption("repos")`. You'd have to make sure your extra CRAN repository was set explicitly as part of the `repos` option for this to work, though.

Another option: for packages installed by [pak](https://github.com/r-lib/pak), a number of extra fields are appended to the DESCRIPTION file:

```
options(repos = c(getOption("repos"), SAGE = "http://ran.synapse.org"))
pak::pkg_install("synapser")
```

which then gives:

```
> packageDescription("synapser")
Package: synapser
Type: Package
Title: R language bindings for Synapse API
Version: 0.6.61
Date: 2019-07-19
Authors@R: c( person("Bruce", "Hoff", role = c("aut", "cre"), email = "bruce.hoff@sagebase.org"), person("Kimyen", "Ladia", role = c("aut"), email =
                  "kimyen.ladia@sagebase.org"), person("Sage Bionetworks", role = c("cph")) )
Maintainer: Bruce Hoff <bruce.hoff@sageabse.org>
BugReports: https://github.com/Sage-Bionetworks/synapser/issues
Description: Provides R language bindings for Synapse RESTful web services.
License: Apache License 2.0
Imports: PythonEmbedInR(>= 0.3.25), utils, methods
Depends: R(>= 3.3)
Suggests: testthat, knitr, rmarkdown
URL: https://www.synapse.org
VignetteBuilder: knitr
SystemRequirements: libssl-dev, libcurl-dev, zlib-dev
Additional_repositories: http://ran.synapse.org
RoxygenNote: 6.0.1
NeedsCompilation: no
Packaged: 2019-07-20 00:42:28 UTC; administrator
Author: Bruce Hoff [aut, cre], Kimyen Ladia [aut], Sage Bionetworks [cph]
Built: R 3.6.0; ; 2019-07-20 00:43:03 UTC; unix
RemoteType: standard
RemoteRef: synapser
RemoteRepos: http://ran.synapse.org
RemotePkgType: macos
RemoteSha: 0.6.61

-- File: /Users/kevinushey/Library/R/3.6/library/synapser/Meta/package.rds 
```

and so `renv` could use the `Remote*` fields to infer the package source. (note: I don't think we currently do this, though)

Finally, we could implement something in `renv` that could allow the user to explicitly declare package sources, for the cases where `renv` is unable to infer directly from the DESCRIPTION file. Perhaps something like an R file called `remotes.R`, with fields like:

```
list(
    synapser = list(
        Source = "CRAN"
    ),

    # other packages
)
```

What are your thoughts on these approaches / an alternative?

**Comment by karawoo** [comment]
Thanks @kevinushey! These approaches seem viable, particularly options 2 and 3. Option 1 would be an option for this case as well, though I think it only works when you have the ability to influence the package's DESCRIPTION (which is fine here, since the author sits down the hall from me, but wouldn't always be the case). Just so I'm sure I understand: if we do option 1, does the repo name in `getOption("repos")` need to match whatever is in the `Repository: ` field of the DESCRIPTION? e.g. `Repository: synapse` would need `options(repos = c(getOption("repos"), synapse = "http://ran.synapse.org"))`

**Comment by kevinushey** [comment]
> Just so I'm sure I understand: if we do option 1, does the repo name in getOption("repos") need to match whatever is in the Repository: field of the DESCRIPTION? e.g. Repository: synapse would need options(repos = c(getOption("repos"), synapse = "http://ran.synapse.org"))

It does not -- we took that approach in Packrat and it caused a fair amount of misery :-) Rather, as long as one of the active repositories provides the package, `renv` will be able to find it.

I also just made a change in `renv` to be a bit more opportunistic. If we can't figure out a package's source from the DESCRIPTION file, but that package is available from one of the active repositories, then we'll assume we should retrieve it from those repositories.

**Comment by slopp** [comment]
FWIW we set that field in RSPM - how are you hosting the CRAN-like repo? It would be nice to outsource that work to the repo and not necessarily rely on pak or add complexity - I like Kevin's opportunistic approach though

**Comment by kevinushey** [comment]
I think this should be better handled now. For example:

```
> # set repos
> options(repos = c(CRAN = "https://cran.rstudio.com", SAGE = "http://ran.synapse.org"))
> 
> # initialize and load
> renv::init()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
* Lockfile written to '/private/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T/RtmpdnxOtV/example-1405f67e3cfba/renv.lock'.
> renv::load()
* Project '/private/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T/RtmpdnxOtV/example-1405f67e3cfba' loaded. [renv 0.6.0-27]
> 
> # try installing a package
> renv::install("synapser")
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
Retrieving 'http://ran.synapse.org/bin/macosx/el-capitan/contrib/3.6/synapser_0.6.61.tgz' ...
	OK [downloaded 35 Mb in 22.4 secs]
Retrieving 'http://ran.synapse.org/bin/macosx/el-capitan/contrib/3.6/PythonEmbedInR_0.3.37.tgz' ...
	OK [downloaded 42.4 Mb in 29.4 secs]
Retrieving 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/R6_2.4.0.tgz' ...
	OK [downloaded 55.9 Kb in 0.5 secs]
Retrieving 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/rjson_0.2.20.tgz' ...
	OK [downloaded 187.9 Kb in 0.4 secs]
Retrieving 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/pack_0.1-1.tgz' ...
	OK [downloaded 26.2 Kb in 0.2 secs]
Installing R6 [2.4.0] from CRAN ...
	OK (installed binary)
Installing rjson [0.2.20] from CRAN ...
	OK (installed binary)
Installing pack [0.1-1] from CRAN ...
	OK (installed binary)
Installing PythonEmbedInR [0.3.37] from CRAN ...
	OK (installed binary)
Installing synapser [0.6.61] from CRAN ...
	OK (installed binary)
* Lockfile written to '/private/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T/RtmpdnxOtV/example-1405f67e3cfba/renv.lock'.
> writeLines(readLines("renv.lock"))
{
  "renv": {
    "Version": "0.6.0-27"
  },
  "R": {
    "Version": "3.6.1",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      },
      {
        "Name": "SAGE",
        "URL": "http://ran.synapse.org"
      }
    ]
  },
  "Packages": {
    "pack": {
      "Package": "pack",
      "Version": "0.1-1",
      "Source": "CRAN",
      "RemoteType": "standard",
      "RemoteRef": "pack",
      "RemoteRepos": "https://cran.rstudio.com",
      "RemoteSha": "0.1-1",
      "Hash": "297fdfd63080b703a77be9fa81a4d4ca"
    },
    "PythonEmbedInR": {
      "Package": "PythonEmbedInR",
      "Version": "0.3.37",
      "Source": "CRAN",
      "RemoteType": "standard",
      "RemoteRef": "PythonEmbedInR",
      "RemoteRepos": "http://ran.synapse.org",
      "RemoteSha": "0.3.37",
      "Hash": "1c9851afda5c6300be59a1d99fc694dc"
    },
    "R6": {
      "Package": "R6",
      "Version": "2.4.0",
      "Source": "CRAN",
      "RemoteType": "standard",
      "RemoteRef": "R6",
      "RemoteRepos": "https://cran.rstudio.com",
      "RemoteSha": "2.4.0",
      "Hash": "92b50d943a7c76c67918c1e1beb68627"
    },
    "rjson": {
      "Package": "rjson",
      "Version": "0.2.20",
      "Source": "CRAN",
      "RemoteType": "standard",
      "RemoteRef": "rjson",
      "RemoteRepos": "https://cran.rstudio.com",
      "RemoteSha": "0.2.20",
      "Hash": "d3349736ec0f60d05591c316b926382e"
    },
    "synapser": {
      "Package": "synapser",
      "Version": "0.6.61",
      "Source": "CRAN",
      "RemoteType": "standard",
      "RemoteRef": "synapser",
      "RemoteRepos": "http://ran.synapse.org",
      "RemoteSha": "0.6.61",
      "Hash": "637a14039d0e4e4698fe509c0a0b0e78"
    }
  }
}
```

**Comment by slopp** [comment]
@kevinushey what happens in the case where renv is tracking packages that are already installed - I assume it does the same "snapshot time" analysis of the current repos?

I believe that is what we do in reconnect to create the manifest file which has almost this same format cc @aronatkins

**Comment by kevinushey** [comment]
> @kevinushey what happens in the case where renv is tracking packages that are already installed - I assume it does the same "snapshot time" analysis of the current repos?

Sorry, what do you mean exactly?

**Comment by slopp** [comment]
Like if you do:

```
install.packages(...)
renv::init()
```

**Comment by kevinushey** [comment]
`renv` tries to figure out a package's source based on the DESCRIPTION file, as per here:

https://github.com/rstudio/renv/blob/425328c38617e258c922b2b1b0ca2d5c3b371a3c/R/snapshot.R#L396-L418

That gets encoded into the lockfile, and then gets used later for e.g. `renv::restore()`. The main tweak is that, if we cannot determine a package's source only from the DESCRIPTION file, but the package's name happens to match one in the active CRAN repositories, then we'll assume the package should be retrieved from CRAN.

**Comment by karawoo** [comment]
Thanks for this addition @kevinushey!

@slopp to your earlier question, I don't know that much about how the repo is hosted (it's managed by a different part of the organization) but I can find out if you have specific questions, or perhaps @kimyen can chime in.

**Comment by kevinushey** [comment]
@karawoo, do you think the solution in https://github.com/rstudio/renv/commit/1401430074643b5b371cc111e7127c9937b1dc1a (assume a package can be retrieved from CRAN if it does exist there) is sufficient for your use case?

**Comment by karawoo** [comment]
Yeah, that's great! I think this issue can be closed unless you are still interested in pursuing any of the other options as well. But yeah, for my use case I think it's resolved.
