### ISSUE TITLE
renv::install from GitHub does not install vignettes

### ISSUE THREAD

**Issue by MarekGierlinski** [rstudio/renv#1201]
When I install a package from GitHub:

```
renv::install("bartongroup/fenr")
```

the package vignette is not available:

```
> vignette("fenr")
Warning message:
vignette ‘fenr’ not found 
```

When I install the same package outside `renv` environment using `remotes::install_github("bartongroup/fenr", build_vignettes = TRUE)`, the vignette is present. 

`renv::install` does not have explicit `build_vignettes` argument, and running it with `build_vignettes = TRUE` does not change anything and does not produce an error (though the docs says "If any arguments are matched to ..., renv will signal an error.").

Is it a bug? Is it a feature? Am I doing something wrong?

**Comment by kevinushey** [comment]
By default, `renv` installs packages from the sources directly, without building the package via `R CMD build`. You can use something like:

```
options(renv.config.install.build = TRUE)
renv::install("bartongroup/fenr")
```

With this set, `renv` will call `R CMD build` before installing the package. Note that you may need to manually install the 'Suggests' package (e.g. BiocStyle) before installing the package, as we don't install 'Suggests' packages by default.

**Comment by MarekGierlinski** [comment]
Thank you for your answer, this is exactly what I was looking for!

What is the reason for not fully building packages by `renv`? Speed?

**Comment by kevinushey** [comment]
The main reason is that vignettes often depend on the "Suggests" package dependencies being installed as well, and so if `renv` were to choose to build vignettes for all packages, we'd potentially end up installing a _lot_ more packages.

It's unfortunate as R doesn't really let a package author declare which packages are required when building vignettes (AFAIK).

**Comment by hadley** [comment]
Out of scope for renv given the challenges, but we should document it and how to work around it (e.g. use r-universe)
