### ISSUE TITLE
Proper way to integrate custom packages with renv

### ISSUE THREAD

**Issue by jpanfil** [rstudio/renv#1204]
I'm looking for guidance on using `renv` where some packages are from CRAN, and other packages are custom ones I have written. At the moment, these custom packages are just saved in a folder, for example, C:\R Custom Packages\my_package_0.0.0.9000.tar.gz. My custom packages are work-specific, so they will never end up on CRAN or a public repo.

When using `renv::restore()`, I get output like

```
The following package(s) were installed from an unknown source:
                _
  my_package [0.0.0.9000]

renv may be unable to restore these packages in the future.
Consider reinstalling these packages from a known source (e.g. CRAN).

Do you want to proceed? [y/N]: y
The following package(s) will be updated:

# CRAN ===============================
- Matrix          [1.5-1 -> 1.5-3]
- nlme            [3.1-160 -> 3.1-161]
[snip]

# (Unknown Source) ===================
- my_package [* -> 0.0.0.9000]

Do you want to proceed? [y/N]: y
* Querying repositories for available source packages ... Done!
Warning: failed to find source for 'my_package 0.0.0.9000' in package repositories
Error: failed to retrieve package 'my_package@0.0.0.9000'
```
My current strategy is to just install `my_package` myself via `install.packages(r"[C:\R Custom Packages\my_package_0.0.0.9000.tar.gz]", repos = NULL)`

After installing my custom packages myself, I can then run `renv::restore()` successfully.

**My question**
Is this the recommended best practice for this situation? Or is there a better way to do this?

Thanks so much

**Comment by jpanfil** [comment]
After another hour looking through your documentation (dense but quite good), I believe I have found the solution: the Package Cellar, described [here](https://rstudio.github.io/renv/reference/paths.html#package-cellar).

I'll leave the issue open for a little longer just in case an admin comes in with a correction. Otherwise, I'll close out later today.

**Comment by hadley** [comment]
Yup, the package cellar looks like the right solution for your problem 😄
