### ISSUE TITLE
`renv_settings_migrate()` only called from exported function `renv::load()`

### ISSUE THREAD

**Issue by cstepper** [rstudio/renv#1206]
In our case, we heavily rely on `renv` for dependency management in package 
development and CI/CD with Gitlab
(more or less following the suggestions in https://rstudio.github.io/renv/articles/ci.html).

Up to `renv` v0.16.0 our process was to create/update the `renv/settings.dcf` 
especially for keeping the `snapshot.type = "explicit"` and for handling the list of ignored packages (e.g. those just needed for package development like pkgbuild, rcmdcheck, etc.)

Each time before we pushed new changes to Gitlab, we called `renv::snapshot()` to update the `renv.lock` file (taking into account the `renv/settings.dcf`).

With the move to `renv/settings.json`, our settings (in the dcf file) 
are not used any longer, and the automatic migration (as stated in the release 
notes) only works within `renv::load()`, which we don't use.

Would it be possible to add the automatic conversion (or a hint for it) to 
the functions `status()` and `snapshot()`, or maybe export `renv_settings_migrate`?

Thanks, Christoph

**Comment by hadley** [comment]
Are you always running CI/CD with the latest version of CRAN packages? (I think that's what you're describing but I'm not sure). If so, you might be better off using one of the [r-lib actions](https://github.com/r-lib/actions/tree/v2-branch/examples#quickstart-ci-workflow) that use pak to always install the latest version.
