### ISSUE TITLE
investigate occasional test warnings

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1208]
See:

```
⠴ |         6 | Restore                                                                     tar: Error opening archive: Failed to open '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/RtmpJNlrLX/renv-test-1332d4ca6f073/file:///var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//RtmpJNlrLX/renv-test-repos-1332d55b41c33/src/contrib/bread_1.0.0.tar.gz'
⠧ |         8 | Restore                                                                     tar: Error opening archive: Failed to open '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/RtmpJNlrLX/renv-test-1332d4ca6f073/file:///var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//RtmpJNlrLX/renv-test-repos-1332d55b41c33/src/contrib/bread_1.0.0.tar.gz'
```

Not exactly sure how this malformed URL is being formed.

**Comment by kevinushey** [comment]
> /private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/RtmpJNlrLX/renv-test-1332d4ca6f073/file:///var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//RtmpJNlrLX/renv-test-repos-1332d55b41c33/src/contrib/bread_1.0.0.tar.gz

**Comment by hadley** [comment]
I just ran all the restore tests 50 times in a row and didn't see it 😬

**Comment by hadley** [comment]
If I delete the first half of the tests before `test-restore.R` the problem goes away. If I delete the seocnd half of the tests before `test-restore.R` the problem also goes away. 😭

**Comment by hadley** [comment]
I'm giving up on this — there enough of a stochastic component that my efforts to systematically eliminate tests that aren't causing the problem don't work.

**Comment by kevinushey** [comment]
Maybe we can add some kind of error / warning handler on the `tar` invocation when tests are running, and have that dump the R frames to see where that weird path is coming from? I'll try and explore that.

Of course, it's also possible that this issue will completely vanish when we move to testthat 3E!

**Comment by hadley** [comment]
I haven't seen this for a while, so I think it got fixed somewhere in all the test refactoring.
