### ISSUE TITLE
Change the default behavior to `RENV_PATHS_PREFIX_AUTO=TRUE`

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#1211]
By default, `renv` creates caches that are used (in an incompatible fashion) across differing linux OSes

By setting `RENV_PATHS_PREFIX_AUTO=TRUE`, this can be remedied for different linux operating systems. We should do this by default so that starting projects on different operating systems "just works" on `renv` (modulo package rebuilding).

There may be ways to mitigate a one-time breakage with existing project options, one-time symlinks, etc.

**Comment by kevinushey** [comment]
This would be worth including in a 1.0.0 release, since it'd be a potentially breaking change.

**Comment by kevinushey** [comment]
Punted due to time constraints + danger in making such a breaking change here.

**Comment by kevinushey** [comment]
@HenrikBengtsson that is an excellent idea -- I'll do that!

**Comment by kevinushey** [comment]
This has been implemented. Thanks again for the suggestion @HenrikBengtsson!
