### ISSUE TITLE
update support for Rtools43

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1214]

**Comment by hadley** [comment]
Done in 7ece0ee741370c2737d3d13fb90ae6b8c0ebb83b

**Comment by slodge** [comment]
Is there more to do in the file?

https://github.com/rstudio/renv/blob/029c4457c0c2846eafd9a1da8bf3f95daf49fe45/R/rtools.R#LL54C1-L58C35

and
https://github.com/rstudio/renv/blob/029c4457c0c2846eafd9a1da8bf3f95daf49fe45/R/rtools.R#LL78C1-L78C33

And
https://github.com/rstudio/renv/blob/029c4457c0c2846eafd9a1da8bf3f95daf49fe45/R/rtools.R#LL117C1-L122C39

(I did try to take a look at this issue - maybe in a generic way to support future r4.x - but I got distracted back to the day job)

**Comment by kevinushey** [comment]
Oops, I think you're right. We should consolidate some of that disparate information into a single location so we don't have to hunt down every place we need to update these things.
