### ISSUE TITLE
Better repository recovery for BioC packages

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#1215]
Need a better fallback if `repos` does not include the Bioc repos. Worth exploring the `git_branch` field as discussed in https://github.com/Bioconductor/BiocManager/issues/164

**Comment by kevinushey** [comment]
Can you elaborate a bit more? `renv` tries to be "smart" about adding the Bioconductor repositories when required, e.g. in a call to `renv::install("bioc::Biobase")`.

**Comment by hadley** [comment]
Hmmmm, I can't seem to recreate the problem, so I think this must be some artefact of how was installing packages and setting up a test case for rsconnect.
