### ISSUE TITLE
Snapshot shouldn't prompt to activate

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#1218]
Because using it without activation is a reasonable workflow, if you just want to capture the package dependencies you currently have installed.

**Comment by kevinushey** [comment]
We prompt to activate in a variety of places, e.g.

```
$ rg renv_activate_prompt
R/snapshot.R
138:    renv_activate_prompt("snapshot", library, prompt, project)

R/hydrate.R
84:  renv_activate_prompt("hydrate", library, prompt, project)

R/clean.R
81:  renv_activate_prompt("clean", NULL, prompt, project)

R/restore.R
78:  renv_activate_prompt("restore", library, prompt, project)
```

Do you think the usages in other scenarios are reasonable?

**Comment by hadley** [comment]
I think it makes sense to prompt when you’re creating a project library, so at least hydrate and restore seem reasonable to me.
