### ISSUE TITLE
Cannot find reason why a missing package is sought

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/renv#122]
Hey, apparently my code somehow depends on `mixOmics`. 

`packrat::init` fails with 
> Error: failed to retrieve package 'mixOmics' (missing record)

However, I cannot find the dependency that requires mixOmics using packrat. Installing it by hand with `BiocManager` also doesn't help.

It would be great if `packrat::init` could finish with a warning about missing dependencies and allow me to fix them instead of breaking hard at every missing package.

**Comment by kevinushey** [comment]
If you use the latest version of `renv`, this will become a warning rather than an error:

```
$ echo "library(mixOmics)" > deps.R && R --vanilla --slave -e 'renv::init()'
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
* Resolving missing dependencies  ...
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
The following package(s) were not installed successfully:

        [mixOmics]: package 'mixOmics' is not available on CRAN

You may need to manually download and install these packages.

* Lockfile written to '~/scratch/test/renv.lock'.
* renv activated -- please restart the R session.
```

Then you can install `mixOmics` as required (or skip it if it really is not required).

**Comment by rubenarslan** [comment]
Sorry, I upgraded to the latest `renv` before writing this (because I saw the messages saying this had become more robust). Apparently, I confused myself with the libraries into which I installed it, because I now see I was still on 0.4 somehow. I'll use `renv::upgrade` in the future.

This

> 	mixOmics       [required by RVAideMemoire]

is extremely helpful. Thanks!
