### ISSUE TITLE
Expose API to read lockfile

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#1220]
> I wonder if I should expose something like renv::lockfile$read() so you can read an renv lockfile and let renv handle parsing of the Repositories field

— https://github.com/rstudio/rsconnect/pull/791/files#r1183033156

**Comment by kevinushey** [comment]
Should we just export functions `lockfile_read()` and `lockfile_write()`?

**Comment by hadley** [comment]
Yeah, that's what I was thinking.

**Comment by kevinushey** [comment]
Closed by https://github.com/rstudio/renv/commit/85f32bdad3f5966c7df3ae8a268ca124bcc2b658.
