### ISSUE TITLE
renv::restore() issue with private github repos

### ISSUE THREAD

**Issue by niklasvm** [rstudio/renv#123]
Hi there

I have successfully installed a package from a company's private github repo using `remotes::install_github` and setting the `GITHUB_PAT` environment variable. I have also run `renv::snapshot()` to create the lock file successfully.

I am now having an issue running `renv::restore()` whereby I get a warning of the form:

```{r}
* Operation aborted.
Warning messages:
1: In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
  cannot open URL 'https://api.github.com/repos/{company_name}/{package_name}/tarball/{RemoteSha}': HTTP status was '404 Not Found'
```
I have masked the company name, package name and remote sha in the output above. The package fails to install. The 404 error from github suggests that authentication is not happening. I can confirm that I have set GITHUB_PAT as an environment variable. I never encountered this issue previously when using packrat.

One observation is I see that the function `github_pat()` is not exported from the `remotes` package. I am not sure if this could be causing the issue.

Please can you assist?

**Comment by kevinushey** [comment]
Thanks for the bug report! It looks like this was a bug in the `renv` downloader that was recently introduced; it should be fixed with https://github.com/rstudio/renv/commit/d205a7f13c2a813f0735fc3457e3e667ea2aa75b.

Can you try upgrading renv with `renv::upgrade()`, and let me know if things work as expected then?

**Comment by niklasvm** [comment]
It worked! Thank you so much @kevinushey . I am finding `renv` to be very useful! For more efficient than `packrat`

**Comment by kevinushey** [comment]
I am very glad to hear that :-) Please let us know if you bump into any other issues or have other feedback!
