### ISSUE TITLE
renv can't install ropensci/tabulizer package from github remote

### ISSUE THREAD

**Issue by anesta95** [rstudio/renv#1230]
I am getting the same `Error in record$Package : object of type 'closure' is not subsettable` error found in #1195 when I run `renv::restore()` in a [github action](https://github.com/anesta95/nyc_shelter_count/actions/runs/4857095102/jobs/8657274409) for my R project. Based on the context of the closed issue it seems like renv can't install the [tabulizer](https://github.com/ropensci/tabulizer) package correctly from the github remote.

This is the output with the same `renv:::renv_remotes_parse()` function referenced in the closed issue:

<details>

```
> renv:::renv_remotes_parse("github::ropensci/tabulizer")
$spec
[1] "github::ropensci/tabulizer"

$package
NULL

$type
[1] "github"

$host
NULL

$user
[1] "ropensci"

$repo
[1] "tabulizer"

$subdir
NULL

$pull
NULL

$ref
NULL

> renv:::renv_remotes_parse("github::ropensci/tabulizerjars")
$spec
[1] "github::ropensci/tabulizerjars"

$package
NULL

$type
[1] "github"

$host
NULL

$user
[1] "ropensci"

$repo
[1] "tabulizerjars"

$subdir
NULL

$pull
NULL

$ref
NULL
```

</details>

**Comment by hadley** [comment]
Can you please provide a small reproducible example that illustrates the error?

**Comment by kevinushey** [comment]
FWIW installing from that remote directly seems to work okay:

```
> renv::install("github::ropensci/tabulizer")
Retrieving 'https://api.github.com/repos/ropensci/tabulizer/tarball/08e3d763b7bb2becfe5fc95f800b3767ea704439' ...
        OK [downloaded 122.6 Kb in 0.65 seconds]
Retrieving 'https://api.github.com/repos/ropensci/tabulizerjars/tarball/d1924e01db15b75251e4eb8f558e6e1a81e1c270' ...
        OK [downloaded 10.4 Mb in 1.2 seconds]
Installing rJava [1.0-6] ...
        OK [copied cache in 77 milliseconds]
Installing tabulizerjars [1.0.1] ...
        OK [built from source in 1.6 seconds]
Copying tabulizerjars [1.0.1] into the cache ...
        OK [copied to cache in 41 milliseconds]
Installing tabulizer [0.2.3] ...
        OK [built from source in 1.7 seconds]
Copying tabulizer [0.2.3] into the cache ...
        OK [copied to cache in 23 milliseconds]
* Installed 3 packages in 10 seconds.
```

I was also unable to reproduce via cloning the repository at https://github.com/anesta95/nyc_shelter_count and restoring from the included lockfile.

**Comment by anesta95** [comment]
@hadley Unfortunately it's really only a problem occurring in the GitHub Action, not on my – or any other – local machine so I don't really know how to reproduce it. @kevinushey thank you for trying, my guess at this point is it's not a renv error but rather some issue with my install in the GH action and renv not getting the package from the correct remote so I'll close the issue. Thank you both for looking I really appreciate it.

**Comment by kevinushey** [comment]
Thanks for following up -- I've definitely seen this issue sporadically locally, so if we can figure out a reproducible example to examine locally we'll try to take another look.

**Comment by yogat3ch** [comment]
@anesta95 Did you happen to discover what the issue was here?
I'm encountering the same issue when attempting to `renv::restore` while building a docker image

**Comment by yogat3ch** [comment]
@anesta95 Nevermind, I think I got it figured it out - this is what happens when the docker image is unable to access the Github API it seems. Including the GITHUB_PAT in the _.Renviron_ in the local directory, and copying that .Renviron to the docker image with `COPY .Renviron .Renviron` appears to have resolved it for me.
