### ISSUE TITLE
`renv` Cache Size + Deleting `source`s in Cache Safely

### ISSUE THREAD

**Issue by mrkaye97** [rstudio/renv#1237]
Hey Kevin!

We've been following [the approach laid out in this issue](https://github.com/rstudio/renv/issues/826) for slimming down our Docker images by deleting clones of the Git repos for already-installed packages by using `rm -rf /.local/share/renv` to get rid of often multiple GB of files.

I'm working on upgrading off of `v0.13.2` and it appears that at least as of `v0.15.0` (and maybe higher), this approach doesn't work anymore. 

Nowadays, after running that `rm ...`, the _next_ (read: not the current run, but the run of our CI _after_ trying to restore the cache the first time) fails with an error that looks like the following:

```r
The following package(s) will be updated:

# GitHub =============================
- renvtest   [* -> collegevine/renv-test:renvtest]

Error in file(con, "rb") : cannot open the connection
Calls: <Anonymous> ... renv_dcf_read -> %||% -> renv_dcf_read_impl -> readBin -> file
In addition: Warning message:
In file(con, "rb") :
  cannot open file '/root/.cache/R/renv/cache/v5/R-4.1/x86_64-pc-linux-gnu/renvtest/0.0.0.9000/4add73f37c9efdc342b8496a1e42ec2f/renvtest/renvtest/DESCRIPTION': No such file or directory
Traceback (most recent calls last):
14: renv::restore()
13: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
12: retrieve(packages)
11: handler(package, renv_retrieve_impl(package))
10: renv_retrieve_impl(package)
 9: renv_retrieve_successful(record, path)
 8: renv_description_read(path, subdir = subdir)
 7: filebacked(scope = "DESCRIPTION", path = path, callback = renv_description_read_impl, 
        subdir = subdir, ...)
 6: callback(path, ...)
 5: renv_dcf_read(path, ...)
 4: text %||% renv_dcf_read_impl(file, ...)
 3: renv_dcf_read_impl(file, ...)
 2: readBin(con = file, what = "raw", n = renv_file_size(file))
 1: file(con, "rb")
```

Note than in this example, `renvtest` is a minimal (no deps) package living in a private repo, which I'm installing with `renv::install("collegevine/renv-test:renvtest")` after setting my `GITHUB_PAT` environment variable.

I'm going to upload a tarball to this issue with a stable repro. To run it, you'll need to:

1. Open the `repro` project.
2. Edit the `library(renvtest)` line in `test.R` to load whatever package from a private library you choose. You can also make a private repo from the `renvtest` package in the tarball, and then open the `repro` R project in the tarball and use `renv::install("kevinushey/renv-test:renvtest")` (assuming your repo is called `renv-test` like mine is.
3. Overwrite my lockfile in `repro` with `renv::snapshot()`
4. Run `docker build --build-arg GITHUB_PAT=<< your Github PAT >> -t foo .` to build the image.
5. Run `docker run foo` to run the image, which will run the `repro.sh` to give you the same error as I'm seeing.
6. If you're curious, you can edit the Dockerfile and the lockfile to use `renv 0.13.2` and then run the build + run again, and you'll see that the package correctly restores with that version.

So on to the question: Now that I seemingly can't safely just nuke that directory, what's the best way to keep our Docker images slim after many, many CI runs that cache lots of incremental updates to many internal libraries? I'd really love to be able to avoid saving the large files, and would even more love to not need to manually cache evict often.

One note: This is actually a potentially breaking issue in production for us (and presumably others). The issue is that if our Docker images get too big, they'll build in our CI just fine, but Heroku's container boot process scales (probably sub-linearly, but unsure) with the size of the image being booted. And Heroku has a boot timeout. Which means that it's possible that if we have an image that contains an API that's supposed to be run on Heroku, that API could fail to boot seemingly at random once the image size hit some threshold, as a result of the cache getting bigger and bigger over time.

Here's the tarball with the repro that I used! I'll leave some comments in the code with pointers for what to edit.

[renv-test.zip](https://github.com/rstudio/renv/files/11427062/renv-test.zip)

Thanks a bunch!! And thanks so much for all of your work on `renv` too -- it's a really awesome package :)

**Comment by kevinushey** [comment]
Thanks for the bug report! One question before I dive in further: does `renv::restore(rebuild = TRUE)` fail in the same way?

**Comment by mrkaye97** [comment]
> Thanks for the bug report! One question before I dive in further: does `renv::restore(rebuild = TRUE)` fail in the same way?

Great question! I tried adding `rebuild = TRUE` to the last `renv::restore()` call in `repro.sh`, and it restored successfully (it went back and pulled the package from GH again). So it looks like that "fixes" the issue in some sense.

Do you think that's a reasonable workaround? It's not ideal, but it's not the worst thing in the world -- I can use that as a patch fix if there's nothing else.

Thanks again!

**Comment by kevinushey** [comment]
> Do you think that's a reasonable workaround? It's not ideal, but it's not the worst thing in the world -- I can use that as a patch fix if there's nothing else.

Definitely the right workaround -- `rebuild = TRUE` basically means "bypass the `renv` cache when retrieving the package", so it's the right tool in situations like these.

That said, I'd prefer if this error didn't occur in either case so I'll see if I can figure out what's going on.

**Comment by kevinushey** [comment]
The path included here:

```
  cannot open file '/root/.cache/R/renv/cache/v5/R-4.1/x86_64-pc-linux-gnu/renvtest/0.0.0.9000/4add73f37c9efdc342b8496a1e42ec2f/renvtest/renvtest/DESCRIPTION': No such file or directory
```

makes me think this is an issue with `renv`'s handling of sub-directories. In particular, note that the name `renvtest` is duplicated in the path.

**Comment by mrkaye97** [comment]
Awesome, thanks! It's not the sexiest workaround in the world, since those installs take a while. But it'll work fine as a holdover :+1:

> The path included here:
> 
> > cannot open file '/root/.cache/R/renv/cache/v5/R-4.1/x86_64-pc-linux-gnu/renvtest/0.0.0.9000/4add73f37c9efdc342b8496a1e42ec2f/renvtest/renvtest/DESCRIPTION': No such file or directory
> 
> makes me think this is an issue with `renv`'s handling of sub-directories. In particular, note that the name `renvtest` is duplicated in the path.

This makes sense to me. I didn't notice the duplication in the path. 

Let me know what you find out or if you want any more help debugging / coming up with repros! I'll be curious to know what was changed to cause this issue. I can probably also share the test repo I made with you if that'd be helpful!

If it's related to subdirs, do you think this would also happen for non-private packages? It'd make the repro simpler

**Comment by mrkaye97** [comment]
Ah actually, it definitely is subdir-related. Here's what I see in our CI:

```
  cannot open file '/root/.local/share/renv/cache/v5/R-4.1/x86_64-pc-linux-gnu/schoolrecommendr/6.1.1/066c42b1a1e1aba31b03e522229222e4/schoolrecommendr/analytics/school_recs/schoolrecommendr/DESCRIPTION': No such file or directory
```

It's looking for a package called `schoolrecommendr` living at `collegevine/app:analytics/school_recs/schoolrecommendr` and for some reason it seems like it's trying to find it at `{package-name}/path/to/DESCRIPTION` so I think this is totally the issue.

**Comment by kevinushey** [comment]
Can you also confirm what version of `renv` you're using?

**Comment by mrkaye97** [comment]
I'm testing this and getting the failure on 0.15.0, and have been on 0.13.2 (which works). The reason to upgrade is because I need the "relative file paths to local packages in the lockfile" feature that was introduced in 15 AFAICT

**Comment by kevinushey** [comment]
Are you able to use the latest CRAN release (0.17.3)?

**Comment by mrkaye97** [comment]
> Are you able to use the latest CRAN release (0.17.3)?

Looks like I can't repro on `0.17.3`, so magically it was fixed between 15 and 17? I'll try just updating our prod build to the CRAN release -- was trying to avoid that since it's a bigger version change, but maybe worthwhile.

Any idea what the issue was?

**Comment by mrkaye97** [comment]
Ah, although there does appear to be a separate issue. `renv` isn't picking up my cache now in our CI. did anything else change about cache location or similar? I can poke around into this one more -- I think it's unrelated to this issue

**Comment by mrkaye97** [comment]
Aha! Found it in the docs. https://rstudio.github.io/renv/reference/paths.html#details

Problem solved. Thanks again for the patience and for working with me on this one :) 

Closing
