### ISSUE TITLE
Feature Request: Add `renv.lock` to Rbuildignore when a package project

### ISSUE THREAD

**Issue by uribo** [rstudio/renv#125]
Thank you for developing a nice package.
I started using renv in my R package project. At that time, there was a point worried about.

Since `renv.lock` exists in the top directory, the notation of "NOTE" is made in the process of` devtools::check()`.

```
checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘renv.lock’
```

If run `renv::init()` in a package development project, the `renv/` directory will be the target of `.Rbuildignore`.

https://github.com/rstudio/renv/blob/19a23ad9cab707b507515bdc96064826546bde8a/R/infrastructure.R#L23-L31
 
I suggest that add `renv.lock` to ignore. (If `requirements.txt` exists, it does the same.)

**Comment by kevinushey** [comment]
Thank you! You're absolutely right and I've made that change.
