### ISSUE TITLE
Problem with `dynamic()` when vendoring renv

### ISSUE THREAD

**Issue by juliasilge** [rstudio/renv#1253]
The [vetiver package vendors renv](https://github.com/rstudio/vetiver-r/blob/main/inst/vendor/renv.R) and some recent change has caused a problem for how this works.

Locally in vetiver, I updated the vendored renv with `renv:::vendor()`, then built the package. Now I see a problem like this:

``` r
library(vetiver)
vetiver:::renv$snapshot(
    lockfile = NULL,
    packages = c("janeaustenr", "glue"),
    prompt = FALSE,
    force = TRUE
)
#> Error: internal error: dynamic() received unexpected call 'renv_snapshot_libpaths(libpaths = libpaths, project = project)'
```

<sup>Created on 2023-05-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I can share a full traceback, if that's helpful, but [this looks like the change that is causing the problem](https://github.com/rstudio/renv/commit/f3ed64bac3e1ace61d5e81a306e42080c6085cc8#diff-5d849f3782ddfdd6b0053b841b4be729f4fdaa33c9262caf6757aa185e5f5658). What happens if I turn `renv.dynamic.enabled` off? The code in `renv:::dynamic()` is a bit opaque to me.

The same function works fine when I use it directly, of course:

``` r
renv::snapshot(
    lockfile = NULL,
    packages = c("janeaustenr", "glue"),
    prompt = FALSE,
    force = TRUE
)
#> $R
#> $R$Version
#> [1] "4.2.2"
#> 
#> $R$Repositories
#> $R$Repositories$CRAN
#> [1] "https://cran.rstudio.com/"
#> 
#> 
#> 
#> $Packages
#> $Packages$glue
#> $Packages$glue$Package
#> [1] "glue"
#> 
#> $Packages$glue$Version
#> [1] "1.6.2"
#> 
#> $Packages$glue$Source
#> [1] "Repository"
#> 
#> $Packages$glue$Repository
#> [1] "CRAN"
#> 
#> $Packages$glue$Requirements
#> [1] "R"       "methods"
#> 
#> $Packages$glue$Hash
#> [1] "4f2596dfb05dac67b9dc558e5c6fba2e"
#> 
#> 
#> $Packages$janeaustenr
#> $Packages$janeaustenr$Package
#> [1] "janeaustenr"
#> 
#> $Packages$janeaustenr$Version
#> [1] "1.0.0"
#> 
#> $Packages$janeaustenr$Source
#> [1] "Repository"
#> 
#> $Packages$janeaustenr$Repository
#> [1] "CRAN"
#> 
#> $Packages$janeaustenr$Requirements
#> [1] "R"
#> 
#> $Packages$janeaustenr$Hash
#> [1] "26f391e42073877818f2d4f0470dca24"
#> 
#> 
#> 
#> attr(,"class")
#> [1] "renv_lockfile"
```

<sup>Created on 2023-05-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kevinushey** [comment]
The goal of `dynamic()` is to basically memoize calls to certain expensive functions within a particular scope, so that repeated calls to `available_packages()` (for example) only pay the cost of reading available packages once.

I'll take a look; however, you should be able to safely disable this with the aforementioned option if necessary. Sorry for the trouble!

**Comment by hadley** [comment]
I just tried this now and couldn't reproduce it, so we've probably fixed it in dev.

**Comment by juliasilge** [comment]
I believe this is still a problem, unfortunately. I just tried to vendor again and remove the option in rstudio/vetiver-r#218 and I still see the same problem. You can see this [in CI here](https://github.com/rstudio/vetiver-r/actions/runs/5212697956/jobs/9406660084?pr=218). To see locally, you'll need to install via `devtools::install_github("rstudio/vetiver-r@vendor-renv-again")` and then you can see something like:

``` r
library(vetiver)
vetiver:::renv$snapshot(
    lockfile = NULL,
    packages = c("janeaustenr", "glue"),
    prompt = FALSE,
    force = TRUE
)
#> Error: internal error: dynamic() received unexpected call 'renv_snapshot_libpaths(libpaths = libpaths, project = project)'
```

<sup>Created on 2023-06-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by juliasilge** [comment]
Ah yep, thank you! I have a new problem now with how I am using an internal function, but I'll open a new issue.
