### ISSUE TITLE
`init()` should append to `.Rprofile`

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#1255]
Using renv-0.17.3 (CRAN).

Given an `.Rprofile`

```r
parentDir <- dirname(getwd())
cacheDir <- file.path(parentDir, "cache")
Sys.setenv(RENV_PATHS_CACHE = cacheDir)
```

This file is modified to:

```r
source("renv/activate.R")
parentDir <- dirname(getwd())
cacheDir <- file.path(parentDir, "cache")
Sys.setenv(RENV_PATHS_CACHE = cacheDir)
```

To workaround this, I'm doing something like the following:

```r
renv::init(
  bare = TRUE,
  settings = list(
  ),
  repos = c(CRAN = "https://packagemanager.posit.co/cran/latest")
)

# Make sure we are using our isolated cache.
writeLines(
  c(
    "parentDir <- dirname(getwd())",
    "cacheDir <- file.path(parentDir, \"cache\")",
    "Sys.setenv(RENV_PATHS_CACHE = cacheDir)",
    "Sys.setenv(RENV_RSPM_ENABLED = 'false')",
    "source(\"renv/activate.R\")"
  ),
  ".Rprofile"
)
```

**Comment by aronatkins** [comment]
I encountered this while trying to create an example for https://github.com/rstudio/renv/issues/884#issuecomment-1545949051; not sure if it happens in real environments.

**Comment by hadley** [comment]
It sounds like decision to prepend was carefully thought through, and we're currently doing the best we can, so I'm going to close this issue.

**Comment by aronatkins** [comment]
👍 -- Agree that both prepend and append are occasionally the better choice. OK with closing and having this issue as a record of the choice.
