### ISSUE TITLE
improve handling of orphaned locks in available packages index

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1261]
`renv` uses a helper `index()` function for the available packages index, basically allowing the retrieved copy of available packages to be shared across time and across processes. This helps avoid some painful slowness when retrieving available packages is slow, especially in a session that is restarted often.

A simple reproducible example:

```
local({
  renv:::renv_scope_lock("test")
  tools:::pskill(Sys.getpid(), 9L)
})
```

You'll end up with an orphaned lock which cannot be recovered. The best option I can think of (currently) would be to spawn a separate watchdog process that waits until the R session exits, and then deletes the lockfile if it exists and was owned by that process.

Then, each process could generate a unique key (UUID?) on startup, use that key when taking ownership of a lock, and also let the watchdog know about that key so that if the watchdog sees the process exits, it could check if the lock exists with that key and remove it if so.

**Comment by kevinushey** [comment]
Should also provide an internal API like `renv:::renv_index_reset()` to just clear out the index and / or clear out locks so users can easily recover.

**Comment by kevinushey** [comment]
For the watchdog process, we could consider using `serverSocket()` / `socketAccept()` and associated tools.

**Comment by hadley** [comment]
I made this reprex:

```R
unlink("test123", recursive = TRUE)
file.exists("test123")

proc <- callr::r_bg(function() {
  local({
    renv:::renv_scope_lock("test123")
    Sys.sleep(10)
  })
})

tools:::pskill(proc$get_pid(), 9L)
file.exists("test123")
```

Which appears to be fixed by this change:

```R
renv_scope_lock <- function(path = NULL, envir = parent.frame()) {
  renv_lock_acquire(path)
  reg.finalizer(envir, function(e) renv_lock_release(path), onexit = TRUE)
}
```

That relies on the GC so would happen stochastically, if that's a problem. I thought you might be able to fix that with something like this:

```R
renv_scope_lock <- function(path = NULL, envir = parent.frame()) {
  renv_lock_acquire(path)
  reg.finalizer(envir, function(e) renv_lock_release(path), onexit = TRUE)
  defer(envir = envir, {
    renv_lock_release(path)
    reg.finalizer(envir, NULL)
  })
}
```

But it seems like you can't remove a finalizer:

``` r
e <- new.env()
reg.finalizer(e, function(e) print("Hi!"))
#> NULL
reg.finalizer(e, function(e) {})
#> NULL
rm(e)
. <- gc()
#> [1] "Hi!"
```

If immediately running on function exit is important, we could instead make a queue and attach a single finalizer to some renv environment. Let me know if that makes sense and I can do a PR.

**Comment by kevinushey** [comment]
Are you sure your reprex works? E.g. I see:

```
> unlink("test123", recursive = TRUE)
> file.exists("test123")
[1] FALSE
> 
> proc <- callr::r_bg(function() {
+   local({
+     renv:::renv_scope_lock("test123")
+     Sys.sleep(10)
+   })
+ })
> 
> Sys.sleep(1)
> file.exists("test123")
[1] TRUE
> tools:::pskill(proc$get_pid(), 9L)
> file.exists("test123")
[1] TRUE
```

I think you're killing the process before it even gets a chance to acquire the lock. If we want to be robust against abruptly-terminated processes, I think we need to use a separate watchdog process that monitors locks owned by any R process using renv.

**Comment by hadley** [comment]
Oh that's totally possible 😞
