### ISSUE TITLE
Cannot install from the cellar with pak

### ISSUE THREAD

**Issue by lgaborini** [rstudio/renv#1268]
Hello, I'm using a {drat} repository as a {renv} cellar. Since it mirrors CRAN's structure, it works fine with {renv}.
E.g. it contains a package `rITAtools_0.1.9.tar.gz`.

It installs fine when `RENV_CONFIG_PAK_ENABLED` is FALSE (also without specifying the version):

``` r
renv::install("rITAtools@0.1.9")
#> * Package rITAtools [0.1.9] will be installed from the cellar.
#> Installing rITAtools [0.1.9] ...
#>  OK [built from source in 11 seconds]
#> Moving rITAtools [0.1.9] into the cache ...
#>  OK [moved to cache in 17 milliseconds]
#> * Installed 1 package in 12 seconds.
```

However, when {pak} is enabled, the cellar is not considered:
``` r
renv::install("rITAtools@0.1.9")
#> ℹ Loading metadata database✔ Loading metadata database ... done
#> Error: ! error in pak subprocess
#> Caused by error: 
#> ! Could not solve package dependencies:
#> * rITAtools@0.1.9: Can't find package called rITAtools@0.1.9.
```

Is it by design? Thanks!

I'm on Windows, using {renv} 0.17.3, {pak} 0.5.1.

**Comment by kevinushey** [comment]
Thanks for the bug report! This is not by design; I'll have to think about how we can hook up `pak` installation to the cellar.

**Comment by hadley** [comment]
Want to include this into the pak metaissue? https://github.com/rstudio/renv/issues/1210
