### ISSUE TITLE
renv with pak install issues 

### ISSUE THREAD

**Issue by robincrlee** [rstudio/renv#127]
I'm using renv with pak. 

In one project initialized with renv, after running pak::pkg_install('tidyr'), I saw this error message. 
> ℹ Checking for package metadata updates
> ✖ Metadata download failed                                                        
> Error in any && ask : invalid 'x' type in 'x && y'
But install.packages() would work. 

However, in another project also initialized with renv, pak::pkg_install('tidyr') works. 

I checked the sessionInfo() in both projects and can't see anything different. 

I'm not sure whether I should report this issue to renv or pak repo. 

How would you all suggest debugging this difference?

**Comment by kevinushey** [comment]
Thanks for the bug report! Let me see if I can learn more about what's going on.

**Comment by kevinushey** [comment]
Very odd. It looks like this is a bug in `pak` that occurs when:

1. The repository URL has a trailing slash; and
2. The `repos` option is encoded as an R list, rather than a character vector.

I'll work around this on the `renv` side and file a bug on the `pak` side. Thanks!

**Comment by kevinushey** [comment]
I believe this should be worked around on the `renv` side; I've filed a companion issue for `pak` here: https://github.com/r-lib/pak/issues/150. Please re-open if you're still seeing issues. Thanks!

**Comment by robincrlee** [comment]
thanks for the speedy response :)
