### ISSUE TITLE
Export `renv:::unload()`?

### ISSUE THREAD

**Issue by milanmlft** [rstudio/renv#1285]
For some applications, we might want to use `renv::load()` to explicitly load a renv environment/profile. It would be nice to also have access to the inverse operation `renv::unload()`.
`renv::deactivate()` works but can be a bit too invasive, as it also restarts the R session along with some other side effects.

IMO, having `renv::unload()` would be useful e.g. in testing to temporarily load a renv environment, allowing something like

```r
project <- "project-path"
withr::defer(renv::unload(project))
renv::load(project)
...
```

Thank you for considering this!

**Comment by hadley** [comment]
While it seems like `unload()` might be useful for testing, in practice, I don't think will be, just because loading and unloading R packages in the same environment is fraught with difficult. Instead you might want to explore using `callr` or similar to run your tests in a separate R session.
