### ISSUE TITLE
Sort also alphabetically the packages to update

### ISSUE THREAD

**Issue by llrs** [rstudio/renv#1289]
When updating the snapshot packages are not sorted at least those in CRAN, **DE**optimR before  **ca**Tools:

```r
renv::snapshot(update = TRUE)
## The following package(s) will be updated in the lockfile:
## 
## # Bioconductor =======================
## - SC3          [* -> 1.26.2]
## 
## # CRAN ===============================
## - DEoptimR     [* -> 1.0-12]
## - KernSmooth   [* -> 2.23-20]
## - ROCR         [* -> 1.0-11]
## - WriteXLS     [* -> 6.4.0]
## - caTools      [* -> 1.18.2]
## - class        [* -> 7.3-20]
## - doParallel   [* -> 1.0.17]
## - doRNG        [* -> 1.8.6]
## - foreach      [* -> 1.5.2]
## - gplots       [* -> 3.1.3]
## - gtools       [* -> 3.9.4]
## - iterators    [* -> 1.0.14]
## - mvtnorm      [* -> 1.1-3]
## - patchwork    [* -> 1.1.2]
## - rngtools     [* -> 1.5.2]
## - robustbase   [* -> 0.95-1]
## 
## # RSPM ===============================
## - e1071        [* -> 1.7-13]
## - pcaPP        [* -> 2.0-3]
## - proxy        [* -> 0.4-27]
## - rrcov        [* -> 1.7-2]
## 
## Do you want to proceed? [y/N]: y
```

The output of `renv::status()` is sorted. I think it would be nice to be a bit more consistent and sort the packages by repository. This would make checking which packages are added slightly easier.

I couldn't find if this was requested earlier, apologies if this decision was already made.
I'm using renv 0.17.3.

**Comment by kevinushey** [comment]
I think the confusion here arises because we're sorting using the C locale, which places uppercase letters before lowercase letters:

https://github.com/rstudio/renv/blob/feec5cd2c4753c88c4758c5656cba9148e8e0ef6/R/pretty.R#L97-L98

Compare e.g.

```
> withr::with_collate("C", sort(c("a", "A", "b", "B")))
[1] "A" "B" "a" "b"
> withr::with_collate("en_US.UTF-8", sort(c("a", "A", "b", "B")))
[1] "a" "A" "b" "B"
```

Perhaps we don't want to use the C locale for sorting here?

**Comment by hadley** [comment]
Probably it makes sense to use the native locale, since that's probably how the user expects things to be sorted?

**Comment by kevinushey** [comment]
Right -- I think we can just drop the `renv_scope_locale()` call.

**Comment by kevinushey** [comment]
Fixed by https://github.com/rstudio/renv/commit/94d7acae1404a9b643b44a0b48d4b79fb07d2698.
