### ISSUE TITLE
hydrate corrupts user's library paths

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#131]
I can't actually reprex this properly because the bug causes `reprex` to error.... 😎 

The two `.libPaths()` calls in the snippet below return different values, since `hydrate` permanently removes all library paths except system and adds the paths supplied in `library`:

 ```r
## check .libPaths()
.libPaths()
# [1] "C:/Users/msmcbain/libs/R" "c:/R/R-3.6.0/library"    

library(renv)
lib_path <- tempdir()
hydrate("remotes", library = lib_path)

## check .libPaths()
.libPaths()
# [1] "C:/Users/msmcbain/AppData/Local/Temp/RtmpOoGhKo"
# [2] "c:/R/R-3.6.0/library"                           

##clean_up
unlink(lib_path, recursive = TRUE)
```

The context of this is trying to use `renv` from outside the context of the project local environment as discussed in #121

**Comment by kevinushey** [comment]
Thanks! This should be fixed up on master now.
