### ISSUE TITLE
Should default `.Rprofile` check that `renv/activate.R` exists?

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#1319]
If you accidentally delete `renv/activate.R` but not `.Rprofile`, you get an uninformative error when re-starting the project. Would be worthwhile to have some error checking code?

**Comment by kevinushey** [comment]
Do you have any proposals? Part of the goal here was to keep the code we insert into the `.Rprofile` as minimal as possible.

**Comment by hadley** [comment]
I was thinking like a simple `withCallingHandlers()` wrapper:

```R
withCallingHandlers(
  source("renv/activate.R"),
  error = function(err) {
    stop(
      "Failed to activate renv from .Rprofile.\n",
      "Do you need to re-run renv::activate()?", 
      conditionMessage(err)
    )
  }
)
```

But I can also imagine that using more than one line massively increases the costs of managing the `.Rprofile`, and I have no idea if this is actually a common problem. So I'd also be happy if you wanted to close this issue.

**Comment by kevinushey** [comment]
> I can also imagine that using more than one line massively increases the costs of managing the .Rprofile

That's my main concern. The error produced, while opaque, is at least easily searchable so users can usually recover if they find themselves here. Let's close this for now unless we find a number of users are stubbing their toes on this.
