### ISSUE TITLE
external.libraries

### ISSUE THREAD

**Issue by robertdj** [rstudio/renv#132]
I have a question regarding `external.libraries` in renv settings.

I think that a package like `remotes` could be needed for installing packages, but that it doesn't need to be included in the renv dependencies. 
I can include my default library

    renv::settings$external.libraries(Sys.getenv("R_LIBS_USER"))

But this writes the *value* of `Sys.getenv("R_LIBS_USER")`. If I share my project with others that may not have the same location this will not work. Is it possible to have `renv` read and evaluate the R code `Sys.getenv("R_LIBS_USER")`? Like <https://github.com/rstudio/config> allows `!expr`

I am unsure if my reasoning/use of `external.libraries` is flawed, but please correct me if this is the case :-)

**Comment by kevinushey** [comment]
I'll have to think about this. Having this as a project option is weird for exactly the reason you state: it's really more of a user-level preference. Yet, at the same time, you might want to associate this preference only with this project, and not with all of your projects.

**Comment by hadley** [comment]
Overarching problem now tracked in #624
