### ISSUE TITLE
Why aren't packages installed with pak synchronized to renv cache?

### ISSUE THREAD

**Issue by Fuco1** [rstudio/renv#1331]
I don't know all the internals but by going through the code, calling the following seems to take the `pak` installed packages (that is, `renv::install` with `renv.config.pak.enabled` set to `TRUE`) and move them to the `renv` cache.

```R
records <- renv:::renv_snapshot_libpaths(libpaths = renv:::renv_libpaths_resolve(NULL), project = renv:::renv_project_resolve(NULL))
purrr::map(records, \(x) renv:::renv_cache_synchronize(x, linkable = TRUE))
```

Wouldn't it make sense to move the installed packages to the renv cache?

**Comment by hadley** [comment]
Part of #1210
