### ISSUE TITLE
BiocVersion recorded in lockfile but not used in this project

### ISSUE THREAD

**Issue by lucygarner** [rstudio/renv#1356]
Hi,

I am getting the message that BiocVersion "recorded in the lockfile, but do not appear to be used in this project". 
"Use `renv::snapshot()` if you'd like to remove these packages from the lockfile."

![image](https://github.com/rstudio/renv/assets/22564745/119bf94b-0b0b-4abe-a623-754d60129a65)

However, when I run `renv::snapshot()`, it says "The lockfile is already up to date". Is this something specific about the BiocVersion package?

Best wishes,
Lucy

`sessionInfo()`

```
R version 4.3.0 (2023-04-21)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.0      BiocManager_1.30.20 tools_4.3.0         rstudioapi_0.14    
[5] yaml_2.3.7          renv_0.17.3   
```

**Comment by hadley** [comment]
Can you provide at least a rough reprex of your current package state?

**Comment by kevinushey** [comment]
I think we need to pick up BiocVersion as an "implicit" dependency of projects using Bioconductor, because no packages will explicitly depend on it but users can install a specific version of the BiocVersion package to implicitly depend on a specific Bioconductor release. At least, that's my understanding based on https://bioconductor.org/packages/release/bioc/html/BiocVersion.html.

**Comment by kevinushey** [comment]
BiocManager is a similar type of dependency here.

**Comment by lucygarner** [comment]
> Can you provide at least a rough reprex of your current package state?

What would be the most useful thing to have? A copy of the `renv.lock` file?

**Comment by lucygarner** [comment]
> I think we need to pick up BiocVersion as an "implicit" dependency of projects using Bioconductor, because no packages will explicitly depend on it but users can install a specific version of the BiocVersion package to implicitly depend on a specific Bioconductor release. At least, that's my understanding based on https://bioconductor.org/packages/release/bioc/html/BiocVersion.html.

Just to say that `BiocVersion` was installed as a dependency of another package, rather than me explicitly installing it.

**Comment by kevinushey** [comment]
For reference:

```
> tools::package_dependencies("BiocVersion", reverse = TRUE)
$BiocVersion
[1] "AnnotationHub" "pkgndep"      
```

But, at least from the lockfile, it doesn't look like your project depends on AnnotationHub?

**Comment by hadley** [comment]
I can't reproduce the problem with this reprex script:

```R
renv::init()

renv::install("bioc::scuttle")
writeLines("library(scuttle)", "dep-1.R")
renv::snapshot()

renv::install("bioc::clusterProfiler")
writeLines("library(clusterProfiler)", "dep-2.R")
renv::snapshot()

renv:::renv_restart_request(".")
renv::snapshot()
```

I switch to using `renv::install()` since there are SO many packages to install and the cache makes a big difference.

**Comment by hadley** [comment]
Oh because your reprex doesn't include `status()` which is the actual source of the problem.

**Comment by hadley** [comment]
Ok, here's a reprex that shows the problem — it appears to be caused by taking and then removing a BioC dependency:

```R
renv::init()

renv::install("bioc::BiocGenerics", prompt = FALSE)
writeLines("library(BiocGenerics)", "deps.R")
renv::snapshot(prompt = FALSE)

unlink("deps.R")
renv::snapshot(prompt = FALSE)
renv::status()
```

**Comment by hadley** [comment]
And that arises because of this special case:

https://github.com/rstudio/renv/blob/e1953d0468cfe38a72fed2c9d255d59f4179192d/R/status.R#L186-L189

It feels like that logic should involve `packages` (what's used), not just `library` (what's installed).

**Comment by lucygarner** [comment]
> Oh because your reprex doesn't include `status()` which is the actual source of the problem.

Interesting. I didn't have to run `status()` for the message to show up.
