### ISSUE TITLE
use clearer message when prompting use to restart after install

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1371]
E.g. I saw:

```
> renv::install("rstudio/renv")
Retrieving 'https://api.github.com/repos/rstudio/renv/tarball/a02b1b28dc1b1752b005ec8fdca1426c5ba4b956' ...
	OK [downloaded 497 Kb in 0.91 seconds]
Installing renv [0.17.3-76] ...
	OK [built from source in 4.7 seconds]
Copying renv [0.17.3-76] into the cache ...
	OK [copied to cache in 37 milliseconds]
Installed 1 package into library at path "~/Library/R/arm64/4.3/library".
The following package(s) have been updated:

	renv [installed version 0.17.3-76 != loaded version 0.17.3.76]

Consider restarting the R session and loading the newly-installed packages.
```

Perhaps we should just do the regular record diff printout here?

https://github.com/rstudio/renv/blob/a02b1b28dc1b1752b005ec8fdca1426c5ba4b956/R/install.R#L666-L711

Note that the main intention here is to let the user know they installed a package that was already loaded and so should (probably) restart the R session.

**Comment by kevinushey** [comment]
That, and use the same style of diff output as we use when prompting the user to restore, e.g.

```
- renv [0.17.3-76; sha: abc123 -> sha: def456]
```

which I think just comes from https://github.com/rstudio/renv/blob/a02b1b28dc1b1752b005ec8fdca1426c5ba4b956/R/records.R#L141?

**Comment by hadley** [comment]
We probably won't need to show the version numbers after #587, since you'll get them in the initial prompt.

**Comment by kevinushey** [comment]
Good point!
