### ISSUE TITLE
renv::restore() gives error in vapply

### ISSUE THREAD

**Issue by dgodderis** [rstudio/renv#138]
Hi,
When building a docker image I get the following result using `renv::restore()`. I am working on R3.5.1, using renv 0.6.0-73. On a Windows PC the `renv::restore()` seems to restore just fine, only when I try to build it it gives below error (docker image is built on rocker/tidyverse:3.5.1).

`RUN R -e 'local({r <- getOption("repos");r["CRAN"] <- "https://mran.microsoft.com/snapshot/2019-08-08/" ;options(repos=r);}); Sys.setenv(TAR = "internal"); renv::activate(); renv::restore()'`
...
`Retrieving 'https://mran.microsoft.com/snapshot/2019-08-08/src/contrib/stringi_1.4.3.tar.gz' ...
        OK [downloaded 7 Mb in 6.4 secs]`
`Retrieving 'https://mran.microsoft.com/snapshot/2019-08-08/src/contrib/tidyr_0.8.3.tar.gz' ...
        OK [downloaded 374.9 Kb in 2.1 secs]`
`Retrieving 'https://mran.microsoft.com/snapshot/2019-08-08/src/contrib/bsplus_0.1.1.tar.gz' ...
        OK [downloaded 30.5 Kb in 1.2 secs]`
`Retrieving 'https://mran.microsoft.com/snapshot/2019-08-08/src/contrib/callr_3.3.1.tar.gz' ...
        OK [downloaded 92.1 Kb in 1.3 secs]`
`Retrieving 'https://mran.microsoft.com/snapshot/2019-08-08/src/contrib/processx_3.4.1.tar.gz' ...
        OK [downloaded 120.5 Kb in 1.5 secs]`
`Retrieving 'https://mran.microsoft.com/snapshot/2019-08-08/src/contrib/ps_1.3.0.tar.gz' ...
        OK [downloaded 255.7 Kb in 1.7 secs]`
`Error in vapply(x, `[[`, ..., FUN.VALUE = character(1)) :`
  `values must be length 1,`
 `but FUN(X[[42]]) result is length 0`
`Calls: <Anonymous> ... renv_retrieve_successful -> renv_retrieve -> extract_chr -> vapply`
`Traceback (most recent calls first):`
`29: renv::restore()`
`28: renv_restore_run_actions(project, diff, current, lockfile)`
`27: renv_retrieve(packages)`
`26: handler(package, renv_retrieve_impl(package))`
`25: renv_retrieve_impl(package)`
`24: renv_retrieve_cran(record)`
`23: method(record)`
`22: renv_retrieve_cran_impl(record, "source")`
`21: renv_retrieve_package(record, url, path)`
`20: renv_retrieve_successful(record, path)`
`19: renv_retrieve(package)`
`18: handler(package, renv_retrieve_impl(package))`
`17: renv_retrieve_impl(package)`
`16: renv_retrieve_cran(record)`
`15: method(record)`
`14: renv_retrieve_cran_impl(record, "source")`
`13: renv_retrieve_package(record, url, path)`
`12: renv_retrieve_successful(record, path)`
`11: renv_retrieve(package)`
`10: handler(package, renv_retrieve_impl(package))`
 `9: renv_retrieve_impl(package)`
 `8: renv_retrieve_cran(record)`
 `7: method(record)`
 `6: renv_retrieve_cran_impl(record, "source")`
 `5: renv_retrieve_package(record, url, path)`
 `4: renv_retrieve_successful(record, path)`
 `3: renv_retrieve(package)`
 `2: extract_chr(data, "Package")`
 `1: vapply(x, `[[`, ..., FUN.VALUE = character(1))`
`Execution halted`
`The command '/bin/sh -c R -e 'local({r <- getOption("repos");r["CRAN"] <- "https://mran.microsoft.com/snapshot/2019-08-08/" ;options(repos=r);}); Sys.setenv(TAR = "internal"); renv::activate(); renv::restore()'' returned a non-zero code: 1`

Thanks for all help provided!

**Comment by kevinushey** [comment]
Can you provide the lockfile you're using / the Dockerfile?

**Comment by dgodderis** [comment]
Hi Kevin,
Thanks for being able to respond this quickly! 
[renvlock_Dockerfile.zip](https://github.com/rstudio/renv/files/3495694/renvlock_Dockerfile.zip)

**Comment by kevinushey** [comment]
Strange -- I was able to restore without issue on both my macOS + Windows machines.

Are you able to reproduce with the latest version of `renv`?

**Comment by dgodderis** [comment]
> Strange -- I was able to restore without issue on both my macOS + Windows machines.
> 
> Are you able to reproduce with the latest version of `renv`?

Thanks for the help Kevin, using the latest release `renv 0.6.0-103` I was able to build & launch without any issues! Cheers!

**Comment by kevinushey** [comment]
Glad to hear it! Thanks for taking the time to test.
