### ISSUE TITLE
tweak display of installation log

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1386]
```
> renv::install()
Downloading 24 package(s) and their dependencies
Done

* There are no packages to install.
```

The output makes it look like 24 packages _need_ to be downloaded, but really it's just we inferred the project depends on 24 packages, which will need to be downloaded and installed. (Some of which might already be downloaded and cached.)

Also, by convention, progress headers should usually end with an ellipsis, e.g. something like:

```
* Updating 24 package(s) and their dependencies ... Done!
* There are no packages to install.
```

I also noticed that we're now getting prompted _after_ download; is that expected?

```
> renv::install()
Downloading 24 package(s) and their dependencies
Retrieving 'https://cloud.r-project.org/bin/macosx/big-sur-arm64/contrib/4.3/devtools_2.4.5.tgz' ...
        OK [downloaded 420.8 Kb in 0.12 seconds]
Done

The following package(s) will be installed:

- devtools [2.4.5]

Packages will be installed into "~/Library/R/arm64/4.3/library"

Do you want to proceed? [Y/n]: y
```

**Comment by hadley** [comment]
Ok, I'll take a look. 

I think the install message has to come after download otherwise you don't get any information about the transitive deps.

**Comment by kevinushey** [comment]
> I think the install message has to come after download otherwise you don't get any information about the transitive deps.

I wonder if this is part of the reason why I chose not to prompt in `install()`? Really, we should have a proper solver that figures all this out without needing to download packages, though. (in other words, "use pak")

Maybe this is a reason to prompt in `restore()` but not in `install()`?

**Comment by hadley** [comment]
I still think it's better to prompt, even if it's a bit later than ideal.

**Comment by hadley** [comment]
I don't see how to use the `...` style here since we might have a bunch of bullets in between, e.g.

```
Downloading 24 package(s) and their dependencies
Retrieving 'https://cloud.r-project.org/bin/macosx/big-sur-arm64/contrib/4.3/devtools_2.4.5.tgz' ...
        OK [downloaded 420.8 Kb in 0.12 seconds]
Done
```

Because dependencies have to be downloaded recursively, I don't see any way to make this really polished, but I think we can make a few hacks like eliminating the count, and 

I think we should eliminate the number (since might either be too low if there are dependencies or too high if packages are cached). I don't know if renv uses this style elsewhere, but we could use `---` to break up the downloading/installing steps. Maybe something like this:

```
> renv::install()
-- Retrieving package metadata ---------------------------------------------------------------------
Retrieving 'https://cloud.r-project.org/bin/macosx/big-sur-arm64/contrib/4.3/devtools_2.4.5.tgz' ...
        OK [downloaded 420.8 Kb in 0.12 seconds]

--- Installing packages to ~/Library/R/arm64/4.3/library ----------------------------------------------
The following package(s) will be installed:

- devtools [2.4.5]

Do you want to proceed? [Y/n]: y
```

What do you think?

As part of this work, I could also work on making the individual lines take up less space, like:

```
-- Retrieving package metadata ---------------------------------------------------------------------
Downloading `r-lib/devtools` from GitHub OK [421 Kb in 2 s]
Downloading `r-lib/testthat` from GitHub OK [123 Kb]
```

**Comment by kevinushey** [comment]
`renv` has a `header()` function as well:

```
> renv:::header("blah")
[1] "# blah ==============================="
```

so we should use that to be consistent. (I'm also happy with tweaking the display to just use `--` delimiters)
