### ISSUE TITLE
New renv not detected

### ISSUE THREAD

**Issue by robertdj** [rstudio/renv#139]
I have weird problem when I am changing things in the `renv` source: I install the package ("Install & Restart" in RStudio) and the changes are registered in the "normal" R instances, but not in the projects that use `renv`.  Not even after restarting/removing the `renv` completely and installing again.

I know this is a vague question, but I am clueless about how to fix this.

**Comment by kevinushey** [comment]
You can use `renv::upgrade()` to upgrade the version of `renv` used. (`renv` lives in its own special library separate from the project library so a special command is needed to upgrade it)
