### ISSUE TITLE
snapshot(exclude = "myPackage") failure

### ISSUE THREAD

**Issue by russHyde** [rstudio/renv#1396]
The 'exclude' parameter in renv::snapshot() doesn't exclude a local package.

I'm writing a shiny app as a package ("golemDeploy", built with {golem}) and am having some problems using snapshot.

There is a top-level `./app.R` file, that is required to start the app after deployment on a Connect server.
It looks like this:

```
pkgload::load_all(export_all = FALSE,helpers = FALSE,attach_testthat = FALSE)
options( "golem.app.prod" = TRUE)
golemDeploy::run_app()
```

Now, I don't want {golemDeploy} to be included in the renv.lock for this project. So I'm using `renv::snapshot(exclude = "golemDeploy")`. But snapshot fails in two different ways here:

When `golemDeploy` is not installed locally, snapshot fails because that package isn't installed (which seems odd since I've asked for that package to be excluded)

```r
> renv::snapshot(exclude = "golemDeploy")
The following required packages are not installed:

	golemDeploy

Packages must first be installed before `renv` can snapshot them.
Consider installing these packages using `renv::install()`.
Use `renv::dependencies()` to see where this package is used in your project.
```

When golemDeploy is installed locally, snapshot states that it will be updating that package in the renv.lock even though I've asked for it to be excluded. (Proceeding here means that an renv.lock is written, but golemDeploy is not included in the renv.lock, contrary to what the message implies)

```r
> # when golemDeploy is installed locally:
> renv::snapshot(exclude = "golemDeploy")
The following package(s) will be updated in the lockfile:

# (Unknown Source) ===================
- golemDeploy   [0.0.0.9000 -> *]

Do you want to proceed? [y/N]:
```

(Admittedly, I can just remove the `golemDeploy::` prefix from the app.R file, but it seems like there is a bug with 'exclude' in renv::snapshot() here)

**Comment by kevinushey** [comment]
Thanks for the bug report; this should be better handled in the development version of `renv`. Can you install it with:

```
renv::install("rstudio/renv")
```

and let us know if the issue seems fixed on your end?

**Comment by russHyde** [comment]
Thanks.
Now, when the package is installed, renv::snapshot outputs the following:

```r
> renv::snapshot(exclude = "golemDeploy")
The following package(s) were installed from an unknown source:

- golemDeploy [0.1.0]

renv may be unable to restore these packages in the future.
Consider reinstalling these packages from a known source (e.g. CRAN).

Do you want to proceed? [Y/n]:
```

It does seem a little strange that a warning about the origin of an excluded package is shown. But it's more clear than when it used to suggest that the excluded package would be added to the lockfile
