### ISSUE TITLE
Changes to `renv.pretty.print.emitter`

### ISSUE THREAD

**Issue by juliasilge** [rstudio/renv#1413]
The vetiver package vendors all of renv, and I recently updated to the dev version of renv as outlined in #1253. I have this function that is used to report to users how their current packages are different from their model's packages (for a specific subset of packages relevant to making predictions):

```r
renv_report_actions <- function(current, model) {
    withr::local_options(
        list(renv.pretty.print.emitter = function(text, ...) {cli::cli_inform(text)})
    )
    diff <- renv$renv_lockfile_diff_packages(current, model)

    if (renv$empty(diff))
        return(invisible(NULL))

    lhs <- renv$renv_records(current)
    rhs <- renv$renv_records(model)
    renv$renv_pretty_print_records_pair(
        lhs[names(lhs) %in% names(diff)],
        rhs[names(rhs) %in% names(diff)],
        "The following package(s) do not match your model:",
        "Consider installing the same versions that your model was trained with."
    )

}
```

Everything in here works up to using `renv_pretty_print_records_pair()` (`diff`, `lhs`, and `rhs` are all correct) but then nothing is printed or returned.

The new version of renv doesn't have `renv.pretty.print.emitter` anymore and I am struggling with how to get similar output to what I had before, or actually any output at all now from `renv_pretty_print_records_pair()`. What would be an approach that gets me something similar to what I am doing currently?

**Comment by kevinushey** [comment]
Thank you! Sorry for the trouble in the interim.
