### ISSUE TITLE
vendor: documentation indicates public availability

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#1417]
The documentation for `vendor` indicates that it is exported.

https://github.com/rstudio/renv/blob/355778db046739bf907f4f9af0706c2f0dd42b08/R/vendor.R#L6

It is not.

```r
renv::vendor()
#> Error: 'vendor' is not an exported object from 'namespace:renv'
```

**Comment by hadley** [comment]
@kevinushey do you think it's worth exporting, or should I tweak the docs?

**Comment by kevinushey** [comment]
Let's tweak the docs; I don't want to promise the public at large that they can vendor `renv` since really there's a large number of caveats around what is safe to do.
