### ISSUE TITLE
Question on using pak and renv

### ISSUE THREAD

**Issue by robincrlee** [rstudio/renv#142]
I have installed pak globally since I think that's a package I'll be using across different projects. 

Since the pak library would be installed in a private library, when I initialize a project with renv, the packages in renv/library do not include pak. 

Is this behavior expected? If so, how would you suggest using pak and renv together?
Should I install pak in every project with renv separately?

**Comment by kevinushey** [comment]
I would in general recommend installing `pak` into the project library, e.g. with `renv::install("pak")` -- it's the safest way forward, and will ensure `pak` will be reused from the `renv` cache.

However, if you'd prefer, you can tell `renv` to use the user library. Using the latest version of `renv`, set the R option e.g. in your `~/.Rprofile`:

```
options(renv.config.user.library = TRUE)
```

and the user library will be included on the library paths for new R sessions launched in `renv` projects, so you can access and use those packages. Alternatively, you could use:

```
options(renv.config.external.libraries = c("/path/to/lib"))
```

to point to a library path containing `pak`.

Note that there are some caveats with this workflow; please see the documentation in `?config` for some more details.

**Comment by kevinushey** [comment]
I think `renv` provides the necessary configuration hooks here to get things working here -- please feel free to re-open or file another issue if something is unclear, or if you run into any problems.

**Comment by Andrei-WongE** [comment]
For clarification. Following config, is use `renv::init()` and then write an `.Renviron` file using the following lines:

```
renv_file <- ".Renviron"
 lines <- c(
   "# Project environment variables",
  "RENV_CONFIG_PAK_ENABLED = 'TRUE'",
)
 writeLines(lines, renv_file)
```
I could also use:

`options(renv.config.pak.enabled = TRUE)`

Are both options equivalent, beyond being project vs global options?

**Comment by kevinushey** [comment]
Yes, they are indeed equivalent.
