### ISSUE TITLE
Renv and reticulate compatibility

### ISSUE THREAD

**Issue by DavorJ** [rstudio/renv#1428]
```
> renv::use_python(type = 'conda')
+ "[conda_root]/x64/condabin/conda.bat" "create" "--yes" "--prefix" "[project_root]/renv/python/condaenvs/renv-python" "python=3.7" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... done
[...]
* Activated Python 3.7.12 [conda; ./renv/python/condaenvs/renv-python]
* Project '[project_root]' loaded. [renv 0.17.3]
> reticulate::py_config()
python:         [python_root]/x64/python.exe
libpython:     [python_root]/x64/python39.dll
pythonhome:     [python_root]/x64
version:        3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON
```

A few questions for default `renv` use:
1) Why use `[project_root]/renv/python/condaenvs/renv-python` as default? New versions of `renv` place everything in `%LOCALAPPDATA%` or [path overrides](https://rstudio.github.io/renv/reference/paths.html).
2) Why 3.7 by default and only overridable by `RENV_CONDA_PYTHON_VERSION`??
2) It is stated that "Activated Python 3.7.12", but when you look what `reticulate` is using, it is the system python version. I have never set `RETICULATE_PYTHON`: `renv` does it on startup! I have only set `RENV_PYTHON`.
4) If I don't set `RENV_PYTHON` then it should mean that I want `renv` to ignore python. But still, `renv` sets `RETICULATE_MINICONDA_PYTHON_ENVPATH`. Why, and why this specific environment variable among a plethora of others?
https://github.com/rstudio/renv/blob/3eb85a762ab2bbdd9aae6e0a4d6be17f9ddd42e4/R/load.R#L507-L509
 

Using `reticulate_1.20` and `renv_0.17.3`.

**Comment by kevinushey** [comment]
I think you might be better served by managing your Conda / Python installation yourself rather than doing so in renv.
