### ISSUE TITLE
renv ignores packages loaded by `pacman::p_load`

### ISSUE THREAD

**Issue by okiyuki99** [rstudio/renv#143]
Hi. I often use `pacman::p_load(AAA, BBB, ...)` to install and load packages at the same time on my project.
However, I saw that renv ignores packages loaded by `pacman::p_load`.

```R
> packageVersion("renv")
[1] ‘0.6.0.98’
```

I changed the method loading `kableExtra` package from `library` to `pacman::p_load` in a test.R.

```
library(pacman)
pacman::p_load(kableExtra)
<snip>
```

Then, I did `renv::snapshot()`.

```R
> renv::snapshot()
The following package(s) will be removed from the lockfile:
             _        
  kableExtra   [1.1.0]
  rvest        [0.3.4]
  selectr      [0.4-1]
  webshot      [0.5.1]
```

renv will remove the package from original locakfile.
I think this is because methods in dependencies.R don't treat `pacman`.
https://github.com/rstudio/renv/blob/master/R/dependencies.R#L488-L494.

Is it correct ?

**Comment by kevinushey** [comment]
That's right. I'll add support for `pacman` packages today.

**Comment by kevinushey** [comment]
Should be properly handled now.

Note that you can also set:

```
renv::settings$snapshot.type("simple")
```

to tell `renv` to capture all package dependencies in your library, regardless of whether `renv` is able to infer whether you're actively using it in your project or not.

**Comment by kevinushey** [comment]
Closing this as implemented -- please feel free to re-open or open a new issue if there's an alternate `pacman` syntax that we should support. Thanks!
