### ISSUE TITLE
Question: sharing projects with different rlang versions

### ISSUE THREAD

**Issue by alxfranco** [rstudio/renv#144]
I tried sharing a project that makes use of 'rlang' 0.4.0, however, when I successfully restored the project (using renv::restore()) in a machine that already had 'rlang' 0.3.4 installed, the scripts couldn't run and I got the following error: 

>Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): namespace ‘rlang’ 0.3.4 is already loaded, but >= 0.4.0 is required

What I think is happening is that when a new R session starts it loads a handful of packages including "testthat" and "usethis" which import 'rlang' from the local library. So even though the correct version was installed in the private project library, it was not being used during the start of the R session.

Also it prevents from reloading from the private library because it's being imported:

>Error in unloadNamespace(package) : namespace ‘rlang’ is imported by ‘usethis’, ‘pkgload’, ‘testthat’ so cannot be unloaded

To get past this I had to update 'rlang' before opening the renv project, which seems to defeat the purpose. I hope this is useful, but please let me know if I've just done something stupid.

**Comment by kevinushey** [comment]
Where are these packages being loaded? Do you have a `.Rprofile` or something similar that attempts to load these packages?

**Comment by alxfranco** [comment]
Hi, thank you for your reply. 

You are right! It turns out that the person I was trying to share my project with had an `.Rprofile` (and forgot about it) which was loading 'usethis', 'testthat', and a few other things automatically. 

I wonder if this is something that could be checked automatically when restoring or would that be too intrusive? At least it would be good to make a note of this in a checklist for troubleshooting.

**Comment by kevinushey** [comment]
I've made a couple tweaks here that should help avoid this sort of issue:

1. `renv` now loads the project library paths before running the user profile, which should ensure that any user-requested packages would be loaded from the private library (if available).

2. Loading of the user profile can also be suppressed; e.g. by placing:

```
RENV_CONFIG_USER_PROFILE = FALSE
```

in a user `~/.Renviron` file.

Hopefully this will be sufficient and can avoid issues of this form in the future -- please let me know if you run into any other problems!

**Comment by alxfranco** [comment]
Thank you!
