### ISSUE TITLE
migrate not working if no library

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#148]
I am getting the following error when cloning a fresh copy of this public project: https://github.com/dfe-analytical-services/schools-workforce-benchmarking

and then running `r renv::migrate("schools-workforce-benchmarking")`

```
renv::migrate("schools-workforce-benchmarking")
* Migrating library from Packrat to renv ... Error: failed to create directory at path ''
In addition: Warning message:
In dir.create(rownames(info), recursive = TRUE) :
  cannot create dir '', reason 'No such file or directory'
Traceback (most recent calls first):
7: renv::migrate("schools-workforce-benchmarking")
6: renv_migrate_packrat(project)
5: renv_migrate_packrat_library(project)
4: ensure_parent_directory(targets)
3: ensure_directory(unique(dirname(path)))
2: stopf("failed to create directory at path '%s'", rownames(info))
1: stop(sprintf(fmt, ...), call. = call.)
```

I've tried this on a couple of projects with same result. Is it the case that this is failing as there is no packrat lib directory? Can a migration occur without this?

**Comment by kevinushey** [comment]
Thanks for the bug report -- let me see if I can figure out what's going on.

**Comment by kevinushey** [comment]
Should be working now! Let me know if you run into any other issues.
