### ISSUE TITLE
Should init() infer, or prompt, what the default snapshot type should be?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1485]
If a user calls `renv::init()` on a project containing a DESCRIPTION file, should we:

- Assume they want to use "explicit" snapshots in the project, and set that project setting for them?
- Or, prompt them to do so?
- Or, do nothing?

**Comment by hadley** [comment]
I like the idea of prompting, or at least messaging something like:

```
* You project has a `DESCRIPTION` but renv will capture all dependenices
* Use `settings$snapshot.type("explict")` to only capture dependencies defined in the `DESCRIPTION`
```

**Comment by kevinushey** [comment]
Do we want different behavior for R packages versus "regular" projects that have a DESCRIPTION file?
