### ISSUE TITLE
Install package from renv-managed R-package project to user library

### ISSUE THREAD

**Issue by lschneiderbauer** [rstudio/renv#1489]
Hi,

I tried to find some information about the following in your documentation, especially https://rstudio.github.io/renv/articles/packages.html, however I cannot find what I am looking for:

I work on an R-package which is managed by renv and therefore has it's own project library.
For testing purposes of the package itself I would like to install it into the user library (not! the renv-library), so other scripts / packages on my computer can load the package and I can perform some testing.
However, when I try to install the package from within the project, it will only install the package into the renv-managed project-library itself which is not easily accessible by other projects. (concretely I press Ctrl + Shift + B to trigger Rcmd.exe INSTALL)
How can I achieve installing the package into the user library?

Thanks a lot for your help!

**Comment by kevinushey** [comment]
One potential workaround, I think, would be to change the library paths before install; e.g. something like

```
oldLibPaths <- .libPaths(c("~/path/to/user/library", .libPaths()))
```

and then reset the library paths after, e.g.

```
.libPaths(oldLibPaths)
```

**Comment by hadley** [comment]
The other option would be to run something like `devtools::install("~/path/to/your/project")` outside of the renv managed project.

**Comment by lschneiderbauer** [comment]
Thanks for your suggestions.

`devtools::install("~/path/to/your/project")` for some reason took 37 minutes finish.
So I will go with the first suggestion (at least in spirit, it seems `oldLibPaths` does not really contain the old lib paths, but the ones that get correctly registered with that call), that only takes a couple of seconds as usual.
