### ISSUE TITLE
table in help page does not render correctly in pkgdown website

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#149]
Currently, the table in roxygen help page does not render correctly and it makes it difficult to read. 

In pkgdown, we got this: 
![image](https://user-images.githubusercontent.com/6791940/63125409-e1cbfb80-bfad-11e9-9dd3-f7c842226d6f.png)

In help page we got the correct table
![image](https://user-images.githubusercontent.com/6791940/63125440-f27c7180-bfad-11e9-98b1-148e63473245.png)

It was an issue in pkgdown but it has been [fixed](https://pkgdown.r-lib.org/dev/news/index.html#improvements-to-rd-translation) in last dev version. 

pkgdown website for `renv` should use development version of pkgdown I guess with a `install_github` here
https://github.com/rstudio/renv/blob/999ea9a7bc65d89695a8f94f17b717e8651dfeec/.travis.yml#L13

**Comment by cderv** [comment]
I can confirm that using last dev version of pkgdown renders correctly the tables in the website

**Comment by kevinushey** [comment]
Thanks for spotting that! Should be fixed up now at https://rstudio.github.io/renv/reference/config.html.

**Comment by cderv** [comment]
👍 That is much easier to read now ! 😊
