### ISSUE TITLE
Why does settings.dcf have "packrat" as type?

### ISSUE THREAD

**Issue by cportner** [rstudio/renv#1498]
I just updated to `renv` 0.17.3, and all of a sudden, I kept getting the following error after `renv::status()`:

```
Error: internal error: unhandled snapshot type 'packrat' in eval(expr, envir = environment(dot))
```

The problem disappeared after I set the snapshot type using: `renv::settings$snapshot.type("implicit")`. However, it looks like `settings.dcf` contains a reference to `packrat`:

```
external.libraries:
ignored.packages:
package.dependency.fields: Imports, Depends, LinkingTo
snapshot.type: packrat
use.cache: TRUE
vcs.ignore.library: TRUE
```

Is the `settings.dcf` a leftover from prior iterations of `renv`, given that writing to the setting changes `settings.json`?

**Comment by hadley** [comment]
What version of renv did you update from? Did you previously migrate this project from packrat?

**Comment by cportner** [comment]
I upgraded from 0.17.2. The project did, indeed, start out with packrat but I moved to renv 0.9.3 on Feb 20, 2020 and I have not previously had this problem with renv. I use RStudio and RStudio project if that makes any difference.

**Comment by kevinushey** [comment]
Yes, `settings.dcf` is a leftover from older versions of `renv` -- you can safely remove it.

**Comment by kevinushey** [comment]
It looks like the development version of `renv` will handle this: https://github.com/rstudio/renv/blob/bfb5356541694c987232ae7ceedac992efbdbdca/R/snapshot.R#L987

**Comment by dchiu911** [comment]
Does the dev version mean upgrading from a very old version of `renv`, the `settings.json` will not have "packrat" as the "snapshot.type" field anymore?
