### ISSUE TITLE
Error in if (startswith(loaded, version)) { : argument is of length zero

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1511]
This can happen if the activate script has a recorded RemoteSha, but the currently-installed version of `renv` lacks it.

**Comment by kevinushey** [comment]
If you re-run `renv::activate()` in the affected project, does the issue go away?

**Comment by kevinushey** [comment]
I guess this can happen if `renv` is updated to 1.0.0 without the activate script being updated. :-/

**Comment by LDalby** [comment]
I just ran into the same issue as @dchiu911, but I was able to fix it via `renv::activate()` as suggested by @kevinushey 
I was upgrading a project from renv version 0.16.0 to 1.0.0

**Comment by kevinushey** [comment]
I think this should be fixed via https://github.com/rstudio/renv/pull/1576, so at least we won't see this issue in future `renv` releases.
