### ISSUE TITLE
GitHub record for package 'rmarkdown' has no recorded 'RemoteSha' 

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#152]
@kevinushey - following on from #148 I'm trying to restore the project that I linked there with renv::restore(). This has got through most of the packages but is giving me the above error for an rmarkdown version from GitHub.

renv.lock as follows for markdown:

```
    "rmarkdown": {
      "Package": "rmarkdown",
      "Source": "github",
      "Version": "1.6.0.9003",
      "Requires": "base64enc, caTools, evaluate, htmltools, jsonlite, knitr,\nrprojroot, stringr, yaml",
      "GithubRepo": "rmarkdown",
      "GithubUsername": "rstudio",
      "GithubRef": "master",
      "GithubSha1": "fb3a614e49115858b655d1354f4f33cad66e385b"
    },
```

Any ideas? I can provide full renv.lock if required.

**Comment by adamrobinson361** [comment]
Following on from this if I do install.packages("markdown") after the restore has failed to try and update the version in the lock to non GitHub it rewrites the whole lock file to be just rmarkdown and its dependencies. Is this expected behaviour?

**Comment by kevinushey** [comment]
The first issue is likely because of the 'old' record format used by Packrat for GitHub packages. I'll see if that can be fixed up.

The second is expected behavior -- after calling installing a new package, `renv` will perform an automatic snapshot for you, thereby capturing the current state of your project library (which would then only contain `rmarkdown`). You can disable automatic snapshots with:

```
options(renv.config.auto.snapshot = FALSE)
```

if so desired.

**Comment by adamrobinson361** [comment]
Thanks that makes sense - would there be a way to say upgrade a package in the lock before restoring? Say for instance if you had a package that you couldn't get to compile from source and you wanted to update to the latest version?

**Comment by kevinushey** [comment]
> Thanks that makes sense - would there be a way to say upgrade a package in the lock before restoring?

The simplest way to do this right now, I think, would be to just manually modify the lockfile (e.g. with your favorite text editor) and then call `renv::restore()` after.

**Comment by adamrobinson361** [comment]
Confirmed that restore now works with new commit. Exactly my approach on the upgrade so will stick to that for now.

Thanks!

Adam
