### ISSUE TITLE
`renv_retrieve_git_impl` and Windows don't play well together

### ISSUE THREAD

**Issue by lschneiderbauer** [rstudio/renv#1521]
Hi,

when using renv on Windows with a package dependency on gitlab, I encounter the following error when trying to restore a particular commit:
```r
renv::restore()
#> Cloning '****' ...
#> error: remote origin already exists.
#> Error: error cloning '****' from '*****.git' [status code 3]
```

I suspect that error message comes up because
1) renv creates a temporary folder (where the cloned repository is supposed to be placed)
2) a "cd" command is used to change the working directory to that folder
3) it is assumed that "cd" actually always changes the directory correctly
4) `git init` and friends are called.

In my case, the project folder and the temporary folder happen to live on two different "drives"[1] on my Windows machine. Windows seems to have this unexpected behavior, that if the argument to "cd" is a path in another "drive", the working directory is not changed unless a separate "<D>:" command is used to explicitly change the "working drive".
I think that in my case that leads to the working drive not to change at all, and `renv` effectively tries to execute `git init` in the actual project folder, including setting the remote origin, which in this case already exists and is set. This leads to the error above.

A possible fix would be to add the "/d" argument to "cd" on Windows, which should change the working directory regardless of the active drive.

[1] because I lack a better name: By "drive" I mean the Windows "root directories" which typically are named by capital letters, like "C:", etc.

**Comment by kevinushey** [comment]
I just pushed a potential fix in https://github.com/rstudio/renv/commit/ab98d23549dcc8eee2097e0abb8e663665579a0e, which obviates the need to call `cd` first -- can you let me know if that helps?

**Comment by kevinushey** [comment]
I'm closing this as fixed; please let me know if you have any further trouble. Thanks!
