### ISSUE TITLE
Unable to install some packages within project now MRAN retired

### ISSUE THREAD

**Issue by samuelrneal** [rstudio/renv#1523]
I notice today that I am no longer able to install packages within my .Rproj with the following error:

```
install.packages("qqplotr")
Retrieving 'https://mran.microsoft.com/snapshot/2022-06-07/bin/macosx/big-sur-arm64/contrib/4.1/qqplotr_0.0.5.tgz' ...
	ERROR [curl: (22) The requested URL returned error: 403]
```

It seems all packages are being installed from MRAN, which was retired on 1st July 2023 ([link](https://tinyurl.com/y74zuked)).

Is there a solution or update I can use?

Here's my session and system info:
```
# session
R version 4.1.3 (2022-03-10)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6.5

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.3  tools_4.1.3     rstudioapi_0.13 yaml_2.3.5      renv_0.17.3  

# system
sysname 
"Darwin" 
release 
"21.6.0" 
version 
"Darwin Kernel Version 21.6.0: Thu Mar  9 20:10:19 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T8101" 
nodename 
"XXX" 
machine 
"arm64" 
login 
"root" 
user 
"XXX" 
effective_user 
"XXX" 
```

**Comment by kevinushey** [comment]
Is installing the development version of `renv` an option? You can do so with:

```
renv::install("rstudio/renv")
```

Otherwise, you can disable MRAN and use PPM instead, e.g. put the following in your project `.Renviron`:

```
RENV_CONFIG_MRAN_ENABLED = FALSE
```

and then use something like `options(repos = c(CRAN = "https://packagemanager.posit.co/cran/latest"))` to use [PPM](https://packagemanager.posit.co/client/#/repos/2/overview).

**Comment by samuelrneal** [comment]
I can install `renv` development version, but the second solution worked using PPM. Thanks.
