### ISSUE TITLE
renv::dependencies(... quiet=TRUE) errs; no NEWS

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#1524]
``` r
renv::dependencies(path=getwd(),root=getwd(),quiet=TRUE)
#> Error in renv_dependencies_impl(path = path, root = root, progress = progress, : unused argument (quiet = TRUE)
```

The removal of this option is not mentioned in NEWS.

Called from packrat: https://github.com/rstudio/packrat/blob/main/R/dependencies.R#L182

**Comment by kevinushey** [comment]
Thanks -- we thought this might've been used only internally but if Packrat is depending on this we can revert.
