### ISSUE TITLE
renv install GitHub package

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#153]
Sorry to keep bombarding with issues - I've just begun testing renv on a number of projects ahead of the anticipated move over to it. 

I've found a problem with renv::install in that when I install our corporate r package on github it is not recorded in the lock file even though it says lock file updated. 

To reproduce the error you should be able to just run the following in an renv project:

`r renv::install("dfe-analytical-services/dfeR")`

I wonder if the problem is that we don't define releases as we are still early days in our package? We've not had any problems using the package with packrat though.

**Comment by adamrobinson361** [comment]
In fact having now referenced the library in my code this does work - maybe I misunderstood as I thought any install automatically updates lock?

**Comment by kevinushey** [comment]
What error did you see when you tried to install?

**Comment by adamrobinson361** [comment]
No error - the package installed but I expected it to appear in the lock file post install which it did not. This was the case when the package name dfeR was not referenced in my code.

When referenced and I re ran the install it then updated the lock file. 

I assumed that installing a package regardless of if it was referenced in your code that it would update the lock file. Is that not the intention?

**Comment by kevinushey** [comment]
The default snapshot mode ("packrat") only captures packages currently used in your project, as detected by `renv::dependencies()`. See the documentation in `?settings` for more information -- let me know if anything is unclear.

**Comment by adamrobinson361** [comment]
With method 1 if with no reference to dfeR if I then add the reference and snapshot it works as expected. 

I think the confusion comes from what a snapshot post install does. If you are installing a package for the first time the snapshot is redundant as I understand it as you won't have referenced it in your code yet. If it is an existing package and you are updating then it will snapshot the updated version.

**Comment by adamrobinson361** [comment]
Thats much clearer from the settings page - thanks for flagging

**Comment by adamrobinson361** [comment]
Just to confirm my understanding based on the settings page. With the default setting of packrat style snapshot does any updating of the lock file happen for new or updated packages installed with rent::install?

It seems to show * Lockfile written to 'project-name/renv.lock'. either way but I'm not convinced it does anything under the default?

**Comment by kevinushey** [comment]
The lockfile is indeed regenerated, but if you've installed a package that isn't currently used in the project, then that package won't enter the lockfile.

That is, the auto snapshot doesn't add the installed package to the lockfile; it just generates a brand new lockfile (as calling `renv::snapshot()` would).

I'm not entirely certain whether this is the right choice yet, though -- but it is ultimately consistent. The main challenge is that users might install things like development dependencies into their project library, but not want them to actually enter the lockfile.

**Comment by kevinushey** [comment]
I feel like this is going to be a common point of confusion so I may want to document it in something like an FAQ.

**Comment by adamrobinson361** [comment]
Understood - so to conclude when you run an install, if it is an existing package being updated the the lock file will be updated. If it is a new package it will need to be added to be referenced in code and snapshotted. 

My general feeling is that there should be no snapshot post install as I think the user would want to check for updated packages that they are happy that the upgrade still works with their code. When the user is happy then I'd think they should then snapshot. If not I think they'd want a mechanism where they can revert back to the previous version. Not sure if that's already possible?

**Comment by kevinushey** [comment]
I've heard the exact opposite from a number of users :-) That is, it's too easy to forget to call snapshot, so automatic snapshots are helpful. If you're using git, it's easy to roll back to an old lockfile with `renv::history()` and `renv::revert()`.

Ultimately though, this is why these things can be configured with user config / project settings. See `auto.snapshot` in `?config` for more information -- you probably want

```
options(renv.config.auto.snapshot = FALSE)
```

**Comment by adamrobinson361** [comment]
Thats interesting - guess it's the weigh up between convenience and having development packages not entering your lock file unintentionally.

Very useful - thanks for all your help
