### ISSUE TITLE
Updating pkgdown site for latest release?

### ISSUE THREAD

**Issue by llrs** [rstudio/renv#1535]
Congrats on the new release!
I think it will be easier to use and update projects with it. I found the message more informative and helpful.

The [default webpage](https://rstudio.github.io/renv/news/index.html) of renv doesn't show up (yet) the recent release 1.0.0.
One needs to use the [dev version]( https://rstudio.github.io/renv/dev/news/index.html) to see the changelog with all the changes.

**Comment by kevinushey** [comment]
Thanks for catching that! We (well, @hadley) has rebuilt and pushed the website up, and it should now be visible.
