### ISSUE TITLE
[renv@1.0.0]: prompted for action after project activation in RStudio

### ISSUE THREAD

**Issue by Gilquin** [rstudio/renv#1536]
After activating a project within RStudio and executing a single line in the console, `renv` always prompts the following:
```r
What do you want to do?

1: Snapshot, just using the currently installed packages.
2: Install the packages, then snapshot.
3: Cancel, and resolve the situation on your own.
 
Selection: 
```
This doesn't occur when the project is activated within an R session launched from the terminal.

```bash
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS
RStudio: 2023.06.0+421
```

**Comment by kevinushey** [comment]
It looks like this happens when an automatic snapshot is triggered when a package recorded in the lockfile isn't currently installed. As a workaround, you can disable automatic snapshots:

```
RENV_CONFIG_AUTO_SNAPSHOT = FALSE
```

in your `~/.Renviron`.
