### ISSUE TITLE
renv::restore() runs automatically without prompting user

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1543]
To reproduce, from the terminal:

```
cd $(mktemp -d)
R -e 'renv::init()'
R -e 'renv::record("rlang")'
```

Then, try starting R. You'll see something like:

```
$ R

R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

- Project '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.oksvrpRh' loaded. [renv 1.0.0.9000]
- None of the packages recorded in the lockfile are installed.
- Using `renv::restore()` to restore the project library.
The following package(s) will be updated:

# Repository -----------------------------------------------------------------
- rlang   [* -> 1.1.1]

# Installing packages --------------------------------------------------------

- Installing rlang ...                          OK [linked from cache]
```

However, the code seems to indicate that we'd normally prompt the user here:

https://github.com/rstudio/renv/blob/63d8881e0947a544651cce394d2fc297650e34dd/R/load.R#L823-L828

Most likely this is the culprit:

https://github.com/rstudio/renv/blob/63d8881e0947a544651cce394d2fc297650e34dd/R/utils.R#L124-L128

but maybe we can just remove this code now?

**Comment by kevinushey** [comment]
I also think we should probably use `menu()` here instead.

**Comment by hadley** [comment]
The code was added in https://github.com/rstudio/renv/pull/1473/files

Just to be sure I understand your reasoning — since the autoloaded called as a top-level task after the `.Rprofile` has run and interactivity has returned to the user, it should be safe to disregard `renv.autoloader.running` in `proceed()`?

**Comment by kevinushey** [comment]
Right, that's my understanding.

**Comment by hadley** [comment]
Oooh that doesn't work because it's only the bootstrapping that happens in the hook, not the loading.
