### ISSUE TITLE
[renv 1.0.0] restore(prompt = FALSE) does not respect prompt parameter in profile with default snapshot settings

### ISSUE THREAD

**Issue by zkamvar** [rstudio/renv#1544]
I've found an issue with our [hydrate -> restore -> snapshot workflow](https://carpentries.github.io/sandpaper/articles/building-with-renv.html) where `renv::restore(prompt = FALSE)` will fail in a profile if it's run non-interactively (see https://github.com/carpentries/sandpaper/issues/490), but I've also found that it will still prompt if it's run interactively. 

I've created [a minimum working example](https://github.com/zkamvar/sandpaper-issue-490#readme) (less complex, but derived from the WE for #1177) that demonstrates this workflow and shows that, while new packages are provisioned for the restore step, it never moves on to the snapshot step, so new packages are not recorded in the lockfile: 

<details><summary>Non-interactive results</summary>

Excerpt from [the output of the MWE](https://github.com/zkamvar/sandpaper-issue-490/blob/e6dc4bc4eaa0c03fbed5f7358b49f5ed215a1e01/out.txt):

```
The following packages are used in this project, but not available locally:

- reprex

renv will attempt to download and install these packages.

- Hydrated 0 packages in 0.028 milliseconds.
- Resolving missing dependencies ... 
# Installing packages --------------------------------------------------------

- Installing ps ...                             OK [linked from cache in 0.00038s]
- Installing processx ...                       OK [linked from cache in 0.00027s]
- Installing callr ...                          OK [linked from cache in 0.00027s]
- Installing clipr ...                          OK [linked from cache in 0.00025s]
- Installing rstudioapi ...                     OK [linked from cache in 0.00027s]
- Installing withr ...                          OK [linked from cache in 0.00025s]
- Installing reprex ...                         OK [linked from cache in 0.00032s]

The following required packages are not installed:

- boot
- class
- cluster
- codetools
- foreign
- KernSmooth
- lattice
- MASS
- Matrix
- mgcv
- nlme
- nnet
- rpart
- spatial
- survival

Packages must first be installed before renv can snapshot them.
Use `renv::dependencies()` to see where this package is used in your project.

Not interactive. Will:
Snapshot, just using the currently installed packages.
- Operation canceled.
```

</details> 

In addition, when I run this interactively, I find the prompt appearing:

```r
r$> renv::restore(library = renv_lib, lockfile = renv_lock, prompt = FALSE)
The following required packages are not installed:

- boot
- class
- cluster
- codetools
- foreign
- KernSmooth
- lattice
- MASS
- Matrix
- mgcv
- nlme
- nnet
- rpart
- spatial
- survival

Packages must first be installed before renv can snapshot them.
Use `renv::dependencies()` to see where this package is used in your project.

What do you want to do?

1: Snapshot, just using the currently installed packages.
2: Install the packages, then snapshot.
3: Cancel, and resolve the situation on your own.

Selection:
```

**Comment by kevinushey** [comment]
For context, are the packages in that list installed into the system or site library?

**Comment by zkamvar** [comment]
On my machine they are in both, but these are not packages that are recorded in the lockfile, which is a {knitr}-based lockfile with the {reprex} package added in for discovery. 

For further context, the [GitHub Actions Run](https://github.com/zkamvar/sandpaper-docs/actions/runs/5525965721/jobs/10080142355#step:6:143) that alerted me to this issue also [shows these packages causing an error](https://github.com/zkamvar/sandpaper-docs/actions/runs/5525965721/jobs/10080142355#step:6:318), but none of them are used in the project.

**Comment by zkamvar** [comment]
I used the {flow} package to trace the issue to this part of restore and I think its the _snapshot_ part, but I'm confused as to why it would snapshot on restore. 

https://github.com/rstudio/renv/blob/b71485a6b956cc4e488cc9f6fd3a1ab7f02830d7/R/restore.R#L101C20-L125

I get a feeling that this is somewhat related to this news item:

> If renv::snapshot() finds missing packages, a new prompt allows you to
> install them before continuing (#1198).

**Comment by kevinushey** [comment]
> but I'm confused as to why it would snapshot on restore.

This is mainly done so we can report the diff / actions that `renv::restore()` will perform; that is, it's a way to compare the lockfile state with the current library state, so we can tell the user what's going to happen when packages are installed.
