### ISSUE TITLE
Install local source package without internet

### ISSUE THREAD

**Issue by rmflight** [rstudio/renv#1549]
renv v 0.17.3
R version 4.3.0
Note: project and package have Bioconductor dependencies.

When installing a local source package, without internet, I expect `renv` to just verify that dependencies are fulfilled, and go ahead and install from source.

Instead it just seems to hang for several minutes and not do anything at all beyond the message:

> Package ... will be installed from the cellar

Waiting, waiting, eventually I kill the R process.

**Comment by kevinushey** [comment]
I wasn't able to reproduce. I tried installing `rlang` from sources like follows:

```
> renv::install("~/r/pkg/rlang")
The following package(s) will be installed:

- rlang [1.1.1.9000]

These packages will be installed into "/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.2vxXGc22/renv/library/R-4.3/aarch64-apple-darwin20".

Do you want to proceed? [Y/n]: y

# Installing packages --------------------------------------------------------

- Installing rlang ...                          OK [built from source and cached in 6.3s]

Successfully installed 1 package in 6.3 seconds.
```

I used the macOS network link conditioner to simulate 100% packet loss, so that any attempts to access the internet would fail.

Can you please provide a reproducible example, or share the project wherein you're seeing this issue?

**Comment by rmflight** [comment]
Huh. I can't get it to reproduce on anything **except** my actual package, [visualizationQualityControl](https://github.com/MoseleyBioinformaticsLab/visualizationQualityControl). I've tried adding things to a local clone of `rlang`'s DESCRIPTION to force the same issue, but I can't get it to do it, which seems odd.

Things I tried:

* initializing as a bioconductor project (bioconductor = TRUE)
* adding `biocViews:` to the DESCRIPTION to make it seem like a bioconductor based package
* Adding a requirement on a bioconductor package, `ComplexHeatmap`, which I installed first via `renv`.

Nothing triggers the same behavior, nor the message about using the `cellar`, unless I try to install `visualizationQualityControl`.

Really oddly, although I get a message about using the `renv cellar`, the directory returned by `renv:::renv_paths_cellar()` does not exist.

Maybe I'll try upgrading my version of `renv` and see if that fixes everything.

**Comment by zkamvar** [comment]
FWIW, I had a similar problem, but it's fixed for me with the new version of {renv}. Before the new version of {renv}, I was unable to run offline tests with {sandpaper}](https://github.com/carpentries/sandpaper/blob/4b2a219522a30132e33fb05aea2bf37bcb9a7f32/R/utils-renv.R#L130-L133) because `renv::init()` was attempting to fetch the available package database from CRAN.

**Comment by kevinushey** [comment]
> Really oddly, although I get a message about using the renv cellar, the directory returned by renv:::renv_paths_cellar() does not exist.

You might also check `renv:::renv_cellar_roots(getwd())`, since `renv` also consults local directories here:

```
> renv:::renv_cellar_roots(getwd())
[1] "/Users/kevin/r/pkg/renv/renv/cellar"
[2] "/Users/kevin/r/pkg/renv/renv/local"
[3] "/Users/kevin/Library/Caches/org.R-project.R/R/renv/cellar"
[4] "/Users/kevin/Library/Caches/org.R-project.R/R/renv/local"
```

**Comment by kevinushey** [comment]
@rmflight were you able to figure out what the underlying issue was, or did the latest release resolve your issue?

**Comment by rmflight** [comment]
@kevinushey , sorry, I should have commented when I closed. Latest release is chattier, and pointed to other things that are possibly going on. There are perhaps some issues with that package that I wasn't aware due to GH based install going fine, but local having a bunch of other cruft that causes weird issues.

My local copy actually has a lot of other stuff that I haven't been good about keeping in directories that are ignored during building, and I think that, plus something about the GH remote were causing `renv` to error out. The latest release gives lots more feedback on things going on under the hood during installation, so thankful for that!

**Comment by kevinushey** [comment]
Got it -- glad to hear!
