### ISSUE TITLE
Funcky project structure: a follow up

### ISSUE THREAD

**Issue by adomingues** [rstudio/renv#155]
This is a follow up to the discussion we were having [here](https://community.rstudio.com/t/packrat-bundles-with-different-r-versions-suggestions-and-alternatives/32988), but since the thread got closed I decided to continue here.

The basic issue I was having can be summed up as:

- How to make `renv` work in a situation where src, analysis and the renv itself exists in diverse locations?

Tested solution using tips from  @cderv and @kevinushey :

- Place the renv infrastructure in PRJ_SCRIPTS, for the  purposes of version control- this is where .git lives
- Initialize the project in PRJ_SCRIPTS without attempting dependency discovery and installation – that is, we manually install the packages your project requires – with `renv::init(bare = TRUE)`
- Find / install libraries manually with `renv::dependencies()` and renv::hydrate() function, which will also attempt to save time by copying packages from your user library (rather than re-installing from CRAN) as appropriate. Code used:

```R
pkg_src <- c("./", "../prj_data")
pkgs <- do.call(rbind, lapply(pkg_src, renv::dependencies))$Package
renv::hydrate(pkgs)
```

- Restore project in the analysis folder with `renv::load(project = "../prj_scripts")`. In a final setting this line needs to be present in the `.Rprofile` inside the analysis folder.

While on the analysis folder I installed some packages to see:
1. where the source would end up
2. if they would be registered in the lockfile

the answer is that they are stored in the PRJ_SCRIPTS, as expected / desired, and registered in that folder's lockfile:
>  Lockfile written to '/projects/sandbox/prj_scripts/renv.lock'

In the end this looks less complicated that I initially though. Let me know if I am missing something or something else you would like me to test.

**Comment by kevinushey** [comment]
This sounds like exactly the workflow I would promote for your use case. Thanks for testing!

I don't have any other substantial comments so I'll close this -- please let me know if you bump into any surprises.
