### ISSUE TITLE
Problems with renv::restore() in Mac M2

### ISSUE THREAD

**Issue by DaviYokogawa** [rstudio/renv#1551]
I have an old project running with other people, all other maintainers of these project use Windows or Linux, and only me are using  MacBook.

This project uses R 4.1.1, renv 0.16.0

I use R Switch on my machine and I try to use R 4.1.1 arm version and R 4.1.1 x86_64 and both keep having problems.

When I try to run renv::restore in the project this crash in the installation of MASS and another package to

Follow the renv::diagnostics()
![Screenshot 2023-07-13 at 11 56 41](https://github.com/rstudio/renv/assets/52435393/33949b4e-e01c-4355-866b-0451b5d119f8)

Follow the errors from renv::restore()
![Screenshot 2023-07-13 at 11 58 18](https://github.com/rstudio/renv/assets/52435393/d049832c-171d-452c-b369-ef248469ec17)
![Screenshot 2023-07-13 at 11 58 31](https://github.com/rstudio/renv/assets/52435393/91b8f859-b5a9-4bd4-91d0-ac61c1995208)

I don't know how to deal with this problem

**Comment by kevinushey** [comment]
Unfortunately, MRAN has now shut down. https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161

You'll need to update to the latest release of `renv`; we now use [PPM](https://packagemanager.posit.co/client/#/) for older package binaries.

Alternatively, set:

```
RENV_CONFIG_MRAN_ENABLED = FALSE
```

in your `~/.Renviron` to disable MRAN now.
