### ISSUE TITLE
Renv failing to resolve remote repo

### ISSUE THREAD

**Issue by lakikowolfe** [rstudio/renv#1552]
I'm using `renv` to manage my shiny app dependancies and GitHub actions to deploy to `shinyapps.io`. I set this workflow up using 0.17.3 and was having no problems for months. Since updating to 1.0.0 my [deployment script has started erroring](https://github.com/Sage-Bionetworks/data_flow_HTAN/actions/runs/5525892994/jobs/10097691535). It looks like it is unable to download and install the package [`dcamodules`](https://github.com/Sage-Bionetworks/dcamodules).

I am having trouble figuring out why it can't resolve the `dcamodules` URL. Do you have any thoughts? Thank you in advance!

**Comment by kevinushey** [comment]
It seems to work for me locally, e.g.

```
> renv::install("Sage-Bionetworks/dcamodules")
# Downloading packages -------------------------------------------------------

- Downloading dcamodules from GitHub ...        OK [148 Kb in 0.46s]
- Downloading shinydashboard from CRAN ...      OK [318.9 Kb in 0.42s]
- Downloading colourpicker from CRAN ...        OK [1.2 Mb in 0.66s]
- Downloading shinyjs from CRAN ...             OK [1 Mb in 0.55s]
- Downloading sagethemes from GitHub ...        OK [1.1 Mb in 0.46s]
- Downloading extrafont from CRAN ...           OK [53.6 Kb in 0.16s]
- Downloading extrafontdb from CRAN ...         OK [7 Kb in 0.14s]
- Downloading Rttf2pt1 from CRAN ...            OK [101.2 Kb in 0.35s]
- Downloading patchwork from CRAN ...           OK [3.1 Mb in 0.27s]
- Downloading waiter from CRAN ...              OK [452.1 Kb in 0.17s]

The following package(s) will be installed:

- colourpicker   [1.2.0]
- dcamodules     [Sage-Bionetworks/dcamodules@main]
- extrafont      [0.19]
- extrafontdb    [1.0]
- patchwork      [1.1.2]
- Rttf2pt1       [1.3.12]
- sagethemes     [Sage-Bionetworks/sagethemes@main]
- shinydashboard [0.7.2]
- shinyjs        [2.1.0]
- waiter         [0.2.5]

These packages will be installed into "~/Library/R/arm64/4.3/library".

Do you want to proceed? [Y/n]: y

# Installing packages --------------------------------------------------------

- Installing shinydashboard ...                 OK [installed binary and cached in 0.57s]
- Installing shinyjs ...                        OK [installed binary and cached in 0.72s]
- Installing colourpicker ...                   OK [installed binary and cached in 0.44s]
- Installing extrafontdb ...                    OK [installed binary and cached in 0.39s]
- Installing Rttf2pt1 ...                       OK [installed binary and cached in 0.38s]
- Installing extrafont ...                      OK [installed binary and cached in 0.4s]
- Installing patchwork ...                      OK [installed binary and cached in 0.58s]
- Installing sagethemes ...                     OK [built from source and cached in 1.1s]
- Installing waiter ...                         OK [installed binary and cached in 0.44s]
- Installing dcamodules ...                     OK [built from source and cached in 1.8s]

Successfully installed 10 packages in 7.4 seconds.
```

It'd odd, as the URL reported in the GitHub Action error also appears to be accessible to me in the browser, e.g. https://api.github.com/repos/Sage-Bionetworks/dcamodules/contents/DESCRIPTION?ref=1e14dcfbdaa2913eeeacc12acaac1c8264bac1f7 gives me the expected contents.

**Comment by kevinushey** [comment]
I tried adding a specific test with that remote in https://github.com/rstudio/renv/pull/1553/commits/dd9da0bb9467f23d2dc35921c8471215fc880ba2, and it seems to work okay.

I feel like the issue might lie either on the GitHub side, or perhaps something in the `setup-renv` action itself.

**Comment by lakikowolfe** [comment]
Hm yeah it works for me locally too. Thanks for taking a look!

**Comment by kevinushey** [comment]
If the issue is still occurring on your side, it might be worth filing an issue at https://github.com/r-lib/actions/issues.

**Comment by lakikowolfe** [comment]
Thats a good idea. I'll ask over there!
