### ISSUE TITLE
Add option to configure a proxy server within renv::config?

### ISSUE THREAD

**Issue by KRRLP-PL** [rstudio/renv#1554]
Hi,

in our organization we need to set a `https_proxy` in order to install/retrieve packages for a project using renv.

With `renv.config.autoloader.enabled`, however, restoring a project fails when the user is prompted during the first initialization run (typically after the git clone) with:

```
- None of the packages recorded in the lockfile are installed.
- Using `renv::restore()` to restore the project library.
Do you want to proceed? [Y/n]: Y
```
There is not even an error or a warning because the installation process seems to become stuck because of the missing proxy configuration.

So what the user typically has to do instead is 

- ignoring the initial `Do you want to proceed? [Y/n]: n`
- then setting `Sys.setenv(https_proxy = our_proxy)` 
- again run `renv::restore()` which, then, works just fine.

Could it be useful to store the proxy information somewhere in the renv configuration?

Thanks
Philipp

**Comment by kevinushey** [comment]
Is placing `https_proxy` within your project's `.Renviron` file an option? (Or, perhaps within the R installation's `Renviron.site` -- see `?Startup` in R for more details.)

**Comment by KRRLP-PL** [comment]
Thanks @kevinushey! I wasn't aware of `.Renvifon files`. Also nice that they can be created at the project level.

**Comment by captcoma** [comment]
@kevinushey 

Thank you for your advice. 

I added the https_prox to the global `.Renviron` and to the project's `.Renviron`
However, I cannot install new packages.

If I do not use renv, I can easily install new packages. 

I also tried `renv::refresh()`

```
- Querying repositories for available binary packages ... Done!
renv was unable to query available packages from the following repositories:
- # https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.2 --------
error downloading 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.2/PACKAGES.rds' [curl: (22) The requested URL returned error: 407]
error downloading 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.2/PACKAGES.gz' [curl: (22) The requested URL returned error: 407]
error downloading 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.2/PACKAGES' [curl: (22) The requested URL returned error: 407]
```

**Comment by kevinushey** [comment]
The 407 error is for "Proxy authentication required" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407) so presumedly something else needs to be set up to get the proxy functional.

Alternatively, if package installation works outside of an `renv` project, then you could also try:

```
options(renv.download.override = utils::download.file)
```

so that the built-in R downloader is used instead of `curl`. See the information in https://rstudio.github.io/renv/articles/package-install.html#downloads for more details.

**Comment by captcoma** [comment]
Thank you. 
I had similar issues.

I finally found the issue in my case. 
I realized that renv seems to change the repos. Which seems to affect `utils::download.file` too. (stopped working after renv was installed). Unfortunately my employer blocks all repos except rstudio.com, `https` is also blocked.

In my case following helped:
`options(repos="http://cran.rstudio.com/")`

**Comment by kevinushey** [comment]
Ah, that would explain it too. The most recent release of `renv` defaults to using [PPM](https://packagemanager.posit.co/client/#/), so you may want to revert to using the default CRAN repositories if necessary.

See also https://rstudio.github.io/renv/reference/config.html#renv-config-ppm-default if you'd like to stop using PPM by default in new `renv` projects as well.
