### ISSUE TITLE
Provide option for profiling renv startup

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#1557]
On occasion, R can be slow to start up due to work that `renv` is doing. It would be helpful if we could define something like:

```
RENV_STARTUP_DIAGNOSTICS = TRUE
```

and use `Rprof()` to provide a summary on what `renv` was doing while the project `.Rprofile` was sourced.

**Comment by black-snow** [comment]
Would be nice. I receive
> Warning message:
renv took longer than expected (20 seconds) to activate the sandbox.

with 1.0.0 constantly and it's unclear why :)
