### ISSUE TITLE
installed-from-source warning for non-project package

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#1559]
Using renv-1.0.0 from CRAN and an installation from source of rsconnect into the default R library:

``` r
td <- tempfile()
dir.create(td)
fn <- file.path(td, "index.Rmd")
writeLines(c("hello, markdown"), fn)
renv:::renv_snapshot_preflight_check_sources(td, .libPaths()[[1L]])
#> The following package(s) were installed from sources, but may be available from the following remotes:
#> 
#> - rsconnect  [rstudio/rsconnect]
#> 
#> Would you like to use these remote sources for these packages?
#> See 'snapshot.inference' in ?renv::config for more details.
#> Otherwise, these packages will be recorded with an unknown source.
#> [1] TRUE
```

<sup>Created on 2023-07-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by aronatkins** [comment]
This does not happen when rsconnect is installed from GitHub using remotes; it only happens when the package is installed from source. All from-source packages are reported as having problems, even when they are unrelated to the project.

**Comment by aronatkins** [comment]
When renv and rsconnect are both installed from source (to show this is not a problem only with rsconnect):

``` r
td <- tempfile()
dir.create(td)
fn <- file.path(td, "index.Rmd")
writeLines(c("hello, markdown"), fn)
renv:::renv_snapshot_preflight_check_sources(td, .libPaths()[[1L]])
#> The following package(s) were installed from sources, but may be available from the following remotes:
#> 
#> - renv       [rstudio/renv]
#> - rsconnect  [rstudio/rsconnect]
#> 
#> Would you like to use these remote sources for these packages?
#> See 'snapshot.inference' in ?renv::config for more details.
#> Otherwise, these packages will be recorded with an unknown source.
#> [1] TRUE
```

<sup>Created on 2023-07-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by aronatkins** [comment]
Note: The formatting of this message has changed in the latest version of renv; it is much more compact:

``` r
td <- tempfile()
dir.create(td)
fn <- file.path(td, "index.Rmd")
writeLines(c("hello, markdown"), fn)
renv:::renv_snapshot_preflight_check_sources(td, .libPaths()[[1L]])
#> The following package(s) were installed from sources, but may be available from the following remotes:
#> - renv       [rstudio/renv]
#> - rsconnect  [rstudio/rsconnect]
#> Would you like to use these remote sources for these packages?
#> See 'snapshot.inference' in ?renv::config for more details.
#> Otherwise, these packages will be recorded with an unknown source.
#> [1] TRUE
```

<sup>Created on 2023-07-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kevinushey** [comment]
I think this is the expected behavior? @hadley, what do you think? Or should this only be triggered via a top-level `snapshot()` call?

**Comment by kevinushey** [comment]
Or is the concern here that the check is being performed on packages which aren't actually inferred as project dependencies?

**Comment by aronatkins** [comment]
The concern is that both @hadley and I had all our installed-from-source packages reported as in need of adjustment even when none of those packages contributed to the target (project) directory.

The `renv_snapshot_preflight_check_sources` reprex was me attempting to construct a narrow test case without fully initializing a project.

We saw this happening when testing renv-1.0.0 with rsconnect against arbitrary pieces of content. In my case, I was deploying a trivial R Markdown document with no other package dependencies. My reprex is fairly close to that situation.

**Comment by aronatkins** [comment]
FYI: The rsconnect package (in my case) was installed using the RStudio "Install" button in the "Build" pane. Regular package development workflow.

**Comment by hadley** [comment]
I think the warning about renv is expected (since we have dev renv installed from source and it's captured in the snapshot), but unexpected for rsconnect.
