### ISSUE TITLE
renv_migrate_packrat_cache bad packages?

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#156]
@kevinushey  - I've been trialling out renv on our works build pipeline. To do this I've simply added in a migrate step that checks if a project is packrat, if so migrates it to renv and then restores.

I'm having some problems due to the automatic migration of the packrat cache to renv (might be an idea to make this optional if its not already?). 

Basically I have some bad packages in the packrat cache - by that I mean the folders are there but they seem to be empty when I look in them (I cant explain why). Am I right that you call this a bad hash?

Is there any way to alter the renv_migrate_packrat_cache function so that it checks that what its bringing across is good?

The following is the error I am getting. Note it was a fresh named renv cache before the build set off.

```
Error: target file 'C:/Agents/renv/v4/R-3.4/x86_64-w64-mingw32/bindrcpp/0.2.2/8366d79c45a3eaf4a7a223600aa0c87a/bindrcpp' already exists
Traceback (most recent calls first):
15: source(Sys.getenv("BUILD_ANALYSIS_R_SCRIPT"), local = TRUE)
14: withVisible(eval(ei, envir))
13: eval(ei, envir)
12: eval(ei, envir)
11: renv::migrate()
10: renv_migrate_packrat(project)
9: renv_migrate_packrat_cache(project)
8: enumerate(targets, copy)
7: lapply(idx, function(i) f(n[[i]], x[[i]], ...))
6: FUN(X[[i]], ...)
5: f(n[[i]], x[[i]], ...)
4: f(...)
3: renv_file_preface(source, target, overwrite)
2: stopf("target file '%s' already exists", target)
1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
```

**Comment by kevinushey** [comment]
That's surprising to me as I'd expect cache copying to only occur if the file doesn't exist:

https://github.com/rstudio/renv/blob/2d9ded95e4c7184befbac13c8b61cf8f7bbca6f8/R/migrate.R#L194-L201

I'll add a couple safety checks to see if that helps.

**Comment by adamrobinson361** [comment]
I will see if I can diagnose a bit more what it was copying from the packrat cache when in tomorrow. 

Just to confirm my understanding:

1. As part of the migrate project function the entire packrat cache is attempted to be copied into the renv cache regardless of the project uses the package it is putting into the renv cache?

2. How are empty package folders in packrat cache dealt with? Is this picked up in the read descriptions part which would return null?

3. Are these packages physically moved out of the packrat cache such that the packrat cache is emptied? I.e. is it all or nothing?

**Comment by kevinushey** [comment]
> As part of the migrate project function the entire packrat cache is attempted to be copied into the renv cache regardless of the project uses the package it is putting into the renv cache?

That's correct.

> How are empty package folders in packrat cache dealt with? Is this picked up in the read descriptions part which would return null?

That should be an error:

```
> renv:::renv_description_read("/no/such/file")
Error: file '/no/such/file' does not exist.
```

So the error you're seeing seems potentially unrelated to your having empty folders in the Packrat cache (?)

> Are these packages physically moved out of the packrat cache such that the packrat cache is emptied? I.e. is it all or nothing when making jump to renv?

No, they are only copied (the Packrat cache remains intact). The onus is on the user to remove the Packrat cache if they're absolutely sure it's no longer required.

**Comment by adamrobinson361** [comment]
Perfect - point 3 should mean I should be able to empty renv cache and reproduce error tomorrow. 

I’d agree based on what you’ve outlined it’s unlikely related to empty folders.

**Comment by adamrobinson361** [comment]
@kevinushey - your changes have resolved my issue and the migrate and restore pipeline is now working as intended. Thanks for your help!

**Comment by kevinushey** [comment]
Awesome! I'm glad to hear it :-)
