### ISSUE TITLE
installing from github for version 1.0.0 doesn't work (cannot open URL 'https://api.github.com/repos/rstudio/renv/tarball/1.0.0')

### ISSUE THREAD

**Issue by jachuR** [rstudio/renv#1560]
In the [vignette](https://rstudio.github.io/renv/articles/docker.html) about using renv with docker, it is suggested to install from GitHub but for version 1.0.0 it doesn't work (for version 0.17.0 it works).

`> remotes::install_github('rstudio/renv@1.0.0')`
`Downloading GitHub repo rstudio/renv@1.0.0
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/rstudio/renv/tarball/1.0.0'`
  
 remotes::install_github('rstudio/renv') - works fine and install 1.0.0 version.
 
 Am I doing something wrong?

**Comment by jachuR** [comment]
I found out what was wrong. The correct one is remotes::install_github('rstudio/renv@v1.0.0'). The [vignette](https://rstudio.github.io/renv/articles/docker.html) should be updated.

**Comment by kevinushey** [comment]
Thanks for catching that! I've updated the vignette.
