### ISSUE TITLE
renv 1.0.0 - restore builds everything from source

### ISSUE THREAD

**Issue by black-snow** [rstudio/renv#1568]
I upgraded to `1.0.0` and now `renv::restore` takes forever. Apparently it builds everything from source:
![grafik](https://github.com/rstudio/renv/assets/579733/b618ad82-c415-4c11-ae29-f9e332154e75)

I wonder why this is happening.  
As a side question - how would I enable P3M for an existing project? The default is a mirror for CRAN that keeps prebuilt packages? So, it's "safe" to use it? (As in "should yield the same result as targeting CRAN")

P.S.: I was missing some upgrade instruction on the release page / the blog post. I might have missed something - [this](https://github.com/haganjam/FW_invert_biomass_allometry/commit/406739b5750fa5184674c697d46469b43ddc2144) is what happened ;)

**Comment by kevinushey** [comment]
Are you running on macOS? The latest release of `renv` switched to using PPM by default, but I think we were too hasty -- it looks like PPM doesn't provide binaries on arm64 macOS yet.

You could try changing the repositories back to CRAN with e.g.

```
options(repos = c(CRAN = "https://cloud.r-project.org"))
renv::snapshot()
```

Then restart the R session and try to install again.

**Comment by kevinushey** [comment]
Yep, that's right.

**Comment by kevinushey** [comment]
I wonder if the problem here is that the action failed to restore the `renv` package cache?

<img width="1512" alt="Screenshot 2023-07-19 at 2 20 47 PM" src="https://github.com/rstudio/renv/assets/1976582/82990ec8-6a4c-4fdc-ac05-1d898965c91c">

**Comment by black-snow** [comment]
I'll try to drop the old stuff and go with https://rstudio.github.io/renv/articles/ci.html#using-r-libactionssetup-renv

**Comment by Kjir** [comment]
Using RSPM could improve your install time when cache is unavailable: https://packagemanager.posit.co/cran/latest

As to why it rebuilds it, did you upgrade the R version recently? Or if it's just the github actions that you linked, I don't see a successful build that would have saved the cache in the first place, and with the cache being empty `renv` just has to install everything from scratch

**Comment by black-snow** [comment]
One pipeline got through. I'll see if it's faster now.

@Kjir thanks. I think it originally used rspm but that failed rather often (for something wasn't available there yet, while it was on CRAN already). Is there a way to use rspm but fall back to vanilla CRAN?  
(I'm still fairly new to the R ecosystem)

**Comment by Kjir** [comment]
Curious that you mention that problem, I had it too with the new release of openssl, but it was another CRAN mirror that claimed to have the newer version in its metadata, but the package archive was not actually available for that version yet.

To fall back, it should be enough to configure more than one repo:

`options(repos = c(RSPM="https://packagemanager.posit.co/cran/latest", CRAN="https://cran.r-project.org"))`

**Comment by black-snow** [comment]
@Kjir would I past this into `.Rprofile` just before `source()`?

**Comment by Kjir** [comment]
Yes, that would work

------- Original Message -------
