### ISSUE TITLE
renv::restore() should have to option to repair broken symlinks

### ISSUE THREAD

**Issue by Kjir** [rstudio/renv#1570]
Sometimes `renv::restore()` fails on my pipelines with the following message:

```
$ Rscript -e "renv::restore()"
Warning message:
renv took longer than expected (20 seconds) to activate the sandbox.
The sandbox can be disabled by setting:
    RENV_CONFIG_SANDBOX_ENABLED = FALSE
within an appropriate start-up .Renviron file.
See `?renv::config` for more details. 
The following package(s) have broken symlinks into the cache:
- Matrix
- mgcv
Use `renv::repair()` to try and reinstall these packages.
The following required packages are not installed:
- Matrix
- mgcv
Packages must first be installed before renv can snapshot them.
Use `renv::dependencies()` to see where this package is used in your project.
Not interactive. Will:
Snapshot, just using the currently installed packages.
- Operation canceled.
Execution halted
```

While this might be fine when working interactively, it does not work in a Pipeline: the only option for me is to delete the workers cache and rebuild it completely.

I think `renv` should automatically repair broken symlinks. Unless there is some other reason I'm not seeing, I don't think users should be particularly interested in actively knowing that this has happened.

Like the change made to autosnapshotting (which is great), `renv::restore()` should automatically try to repair, unless explicitly disabled. A log message informing that this is happening should be enough to hint at a potential problem.

At the very least, there should be a way to auto-repair, precisely for this scenario of renv running in a pipeline or in some other non-interactive way.

**Comment by kevinushey** [comment]
> I think renv should automatically repair broken symlinks. Unless there is some other reason I'm not seeing, I don't think users should be particularly interested in actively knowing that this has happened.

I guess my concern is that we don't know why the symlinks are broken -- for example, is it because the cache directory is not accessible, or has it changed? Or maybe something else?

I'd like to know why this issue is occurring in your environment before deciding to automatically call `renv::repair()`. (I think you could also add that as a step in your pipeline if it was really necessary.)

**Comment by Kjir** [comment]
The reason this happens is that my pipeline happens to have 2 workers coming from different environments. Through the Gitlab cache/artifacts, the library and sandbox get preserved, but the global renv cache  doesn't. So the symlinks point to something that doesn't exist.

I should probably modify the pipeline or runners to avoid this situation, but I also think renv should be able to detect the missing packages from the cache and reinstall them to fix the links

**Comment by kevinushey** [comment]
Ah, I think I might have misunderstood -- you're absolutely right that if you're running `renv::restore()` and you have broken symlinks, `renv` should just fix those for you. Sorry for the confusion on my end.

For posterity, do you also see this with the current development version of renv?
