### ISSUE TITLE
Source: CRAN imputed by default?

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#158]
In my lockfile, I see `Source: "CRAN"`, and this should not be coming anywhere in my system, so must be originating in `renv`. I expected `renv` to honor what was either (1) in my environment or (2) what was in the package description.

renv.lock
```
{
  "renv": {
    "Version": "0.6.0-120"
  },
  "R": {
    "Version": "3.5.3",
    "Repositories": [
      {
        "Name": "RSPM_PROD",
        "URL": "https://demo.rstudiopm.com/cran/latest"
      },
      {
        "Name": "RSPM_DEV",
        "URL": "https://demo.rstudiopm.com/internal/latest"
      }
    ]
  },
  "Packages": {
    "digest": {
      "Package": "digest",
      "Version": "0.6.20",
      "Source": "CRAN",
      "Hash": "ee526dc5fbf649c15ce452a474543a4c"
    },
    "sass": {
      "Package": "sass",
      "Version": "0.1.2.1",
      "Source": "CRAN",
      "Hash": "ff156f075792053be129b9c60373461e"
    }
  }
}
```

package DESCRIPTION:
```
Type: Package
Package: sass
Version: 0.1.2.1
Title: Syntactically Awesome Style Sheets ('Sass')
...
Repository: RSPM
```

options("repos")
```
options("repos")
$repos
                                   RSPM_PROD                                     RSPM_DEV 
    "https://demo.rstudiopm.com/cran/latest" "https://demo.rstudiopm.com/internal/latest" 

```

**Comment by kevinushey** [comment]
`Source: CRAN` means "looks like it came from a CRAN-like repository". Packages from RSPM set the `Repository` field in the DESCRIPTION file, which `renv` treats as a signal that a package came from a CRAN-like repository -- which, ultimately, RSPM is.

If you use `renv::install()` (or `pak::pkg_install()`) then we could also tag the DESCRIPTION file with the repository that was actually used when the package was installed, though.

**Comment by kevinushey** [comment]
The lockfile format has been modified slightly to make this clearer:

```
    "mime": {
      "Package": "mime",
      "Version": "0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "908d95ccbfd1dd274073ef07a7c93934"
    },
```

And so packages from RSPM would be tagged as from RSPM (as opposed to a CRAN mirror).
