### ISSUE TITLE
`renv::auto_load` does not work anymore

### ISSUE THREAD

**Issue by jd4ds** [rstudio/renv#1580]
Hey,
I think with this commit (https://github.com/rstudio/renv/commit/314009b6ab456a413af03cb360239923139e57e3#diff-43c4528da3e8c329bb7bce6306f225c0b66b8e8c2fdc8d5f5f2560df86542707) a logic error has been inadvertently introduced into the autoload function, which causes the trigger for autoload to work the other way around.
If `RENV_AUTOLOAD_ENABLED=TRUE` or not set, the autoload operation is aborted instead of being performed.
This is currently causing a problem in our build pipelines and on Posit Workbench that all projects are running against the standard R library and are no longer initializing with locked packages or tracking changes.
I would be very grateful for a quick fix.
Thanks and best regards!

**Comment by kevinushey** [comment]
Thank you for the bug report! You're right about the error; we'll get this fixed up soon.
