### ISSUE TITLE
`init()` needs `load = FALSE`

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#1583]
So you can set up renv in another directory. I'm thinking particularly of the rsconnect tests where I want this.

Unless there's some other way of doing this that I'm missing?

**Comment by kevinushey** [comment]
That seems reasonable to me. Would that basically just control whether this code is run? https://github.com/rstudio/renv/blob/ae783a9879162eb60a28aff9886eef6e72ea33bd/R/init.R#L148-L149

**Comment by kevinushey** [comment]
Might also need some tweaks around things like https://github.com/rstudio/renv/blob/ae783a9879162eb60a28aff9886eef6e72ea33bd/R/init.R#L89-L91.

**Comment by kevinushey** [comment]
Actually, this reminds me of `renv::scaffold()`, which is basically "init without loading". Does that do what you need here?

**Comment by hadley** [comment]
That's useful but I still need to do a few steps by hand:

``` r
path <- tempfile()
dir.create(path)

writeLines("library(MASS); library(foreign)", file.path(path, "deps.R"))
renv::scaffold(path)
#> - Lockfile written to "/private/tmp/RtmpEA53xn/file149ae7dbe29e1/renv.lock".
#> - renv infrastructure has been generated for project "/private/tmp/RtmpEA53xn/file149ae7dbe29e1".
renv::snapshot(path)
#> The following package(s) will be updated in the lockfile:
#> 
#> # CRAN -----------------------------------------------------------------------
#> - foreign   [* -> 0.8-84]
#> - MASS      [* -> 7.3-60]
#> 
#> - Lockfile written to "/private/tmp/RtmpEA53xn/file149ae7dbe29e1/renv.lock".
renv::hydrate(project = path, prompt = FALSE, library = renv:::renv_paths_library(project = path))
#> The following packages were discovered:
#> 
#> # ~/Library/R/arm64/4.2/library ----------------------------------------------
#> - foreign   0.8-84
#> - MASS      7.3-60
#> 
#> They will be linked into the project library.
#> 
#> - Linking packages into the project library ... Done!
#> - Hydrated 2 packages in 75 milliseconds.
```

<sup>Created on 2023-07-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

(the hydrate call will get simpler if I can figure out #1586)
