### ISSUE TITLE
Cran Package deletion and exclude source defaults

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#161]
@kevinushey - thanks for your help on the other queries this week. Managed to now get renv up for testing on our build pipeline which has 40+ packrat projects that i'm looking to test and see if a migrate and restore works as intended. Hopefully will provide some useful insights.

Having just passed a number of projects through this I've come up with an error around not being able to download packages from cran. This is not network related and is specific to tidytext which a previous version cannot be downloaded. 

I've tracked this down to this GitHub issue which highlights that older versions were removed from cran (+archive): https://github.com/juliasilge/tidytext/issues/142

Error as follows:

```
Error: failed to retrieve package 'tidytext' from CRAN
In addition: Warning message:
In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
  cannot open URL 'https://cran.microsoft.com/src/contrib/Archive/tidytext/tidytext_0.1.6.tar.gz': HTTP status was '404 Not Found'
Traceback (most recent calls first):
```

I thought i'd flag this in terms of the thought about the default for excluding package sources. I was under the impression cran packages were not removed but seems like that's not the case. Will potentially find more when other projects have been through the pipeline.

I wonder what an elegant fix to this would be? 

1. Should the migrate function have the option bring across the sources to renv folder (or/and straight to cache)
2. Should there be a way to tell renv to store the sources of certain packages (i'm thinking GitHub packages are most likely to disappear).
3. Does this affect your view on the default being no sources?
4. Maybe the solution is to provide a secondary cran mirror for these cases where you know the source does exist (if its very uncommon). I'm thinking mran snapshots but not sure if I read they are discontinuing that.

**Comment by adamrobinson361** [comment]
As discussed in a previous issuethe fix may be to manually edit the lock file and update the version but with dependencies potentially changing I wonder if there is a more elegant solution.

**Comment by kevinushey** [comment]
> Should the migrate function have the option bring across the sources to renv folder (or/and straight to cache)

This is a good idea, especially since `renv` already does have its own notion of a package tarball cache. See `RENV_PATHS_SOURCE` in `?paths`.

> Should there be a way to tell renv to store the sources of certain packages (i'm thinking GitHub packages are most likely to disappear).

I think this is reasonable. `renv` actually does already store package sources that get downloaded, but only for packages that get installed from sources explicitly. It might be useful to provide some API for downloading and storing local package sources, but I'll have to think about what such an API would look like.

> Does this affect your view on the default being no sources?

I don't think so. Always downloading and storing package sources by default is too frustrating / annoying, especially for new projects -- as an example, nobody wants to re-download the `tidyverse` package + its dependencies every time a new project is started.

> Maybe the solution is to provide a secondary cran mirror for these cases where you know the source does exist (if its very uncommon). I'm thinking mran snapshots but not sure if I read they are discontinuing that.

Would be interesting to know what RSPM does in these cases -- cc: @slopp.

---

You could _probably_ solve this by placing the required package sources into the `RENV_PATHS_SOURCE` folder; e.g. within a folder like:

```
renv::paths$root("source/cran/tidytext")
```

If the require package tarball is present there, `renv` will use it instead of trying to download + reinstall the package. See also the **Local Sources** mechanism (also documented in `?paths`) for another path forward.

**Comment by kevinushey** [comment]
And I've now just pushed a commit that should help with migration of Packrat sources to renv -- let me know if it works for you.

**Comment by adamrobinson361** [comment]
Thanks for the explanation and change.

To confirm migrate now will check if there is a src directory and if so migrate the folder to renv. If not then nothing will occur.

Does this in turn make any changes to the src settings for the renv project? I.e. after restore if I install another package within renv will it be automatically added to the src folder?

Re the external package repos that sounds like a quick fix and likely this src folder tweak will also fix my immediate problem.

On the wider problem of packages disappearing I think something more simple to upgrade a single package post restore might make sense if it can’t be found. Otherwise I think a lot of users would begin to struggle to get out of the state. Maybe at a minimum a message saying internet connection? or package not available on CRAN mirror would be useful?

**Comment by kevinushey** [comment]
> To confirm migrate now will check if there is a src directory and if so migrate the folder to renv. If not then nothing will occur.

That's correct.

> Does this in turn make any changes to the src settings for the renv project? I.e. after restore if I install another package within renv will it be automatically added to the src folder?

This doesn't change any other existing behavior in `renv`.

> On the wider problem of packages disappearing I think something more simple to upgrade a single package pre restore might make sense if it can’t be found. Otherwise I think a lot of users would begin to struggle to get out of the state. Maybe at a minimum a message saying internet connection? or package not available on CRAN mirror would be useful?

The particular issue you've bumped into should be exceedingly rare, but I think the output generated is at least enough for users to have a toehold -- `renv` was not able to install this version of this package, so either (1) one needs to figure out an alternate way to provide that package to `renv`, or (2) the associated package record + version needs to be updated.

It would be worth thinking about making completely-offline installs possible but in practice we've seen that users typically have either internet access to access to an internal CRAN-like repository providing all necessary packages.

**Comment by kevinushey** [comment]
I've opened a separate issue to track how to handle offline-only workflows. I think this issue can be closed; feel free to re-open or file a new issue if you run into trouble.
