### ISSUE TITLE
`renv::status()` not usable on uninitialized projects

### ISSUE THREAD

**Issue by cstepper** [rstudio/renv#1612]
Hi,
we use `renv` for dependency management in our package setup (for CI/CD purposes, i.e. `restoring` within docker containers).

Our setup is: 
- using only dependencies as declared in DESCRIPTION file
- defining renv settings
  `renv::settings$snapshot.type(value = "explicit")` --> writing a `renv/settings.json`
- creating a snapshot (with type "explicit" as defined in settings.json file)
  `renv::snapshot()`

(see [test package](https://github.com/cstepper/renvtestr))

Each time we add new functions etc. we used to use `renv::status()` to check if our lockfile is up to date (comparing against the currently set libraries, e.g. default `.libPaths()`). 
If not, we took a new snapshot to update the lockfile.

With the new version of `renv`, this does not work any longer, as `renv::status()` is exiting without comparing the lockfile with the library; it exits before checking as `renv_status_check_initialized` returns `FALSE` 

(due to the missing projlib object: 
https://github.com/rstudio/renv/blob/ba90043f58c2d8f6ee807512da1287fd750dd887/R/status.R#L122
)

``` r
# check status of renv.lock against currently set libraries 
# (for checking if all packages are up to date)
(lb = .libPaths())
#> [1] "/home/christoph/R/x86_64-pc-linux-gnu-library/4.3"
#> [2] "/usr/local/lib/R/site-library"                    
#> [3] "/usr/lib/R/site-library"                          
#> [4] "/usr/lib/R/library"

st = renv::status(library = lb)
#> This project does not appear to be using renv.
#> Use renv::init() to initialize the project.

str(st)
#> List of 3
#>  $ library     :List of 1
#>   ..$ Packages: Named list()
#>  $ lockfile    :List of 1
#>   ..$ Packages: Named list()
#>  $ synchronized: logi FALSE
```

<sup>Created on 2023-07-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Is this on purpose? Do we need to initialize the package in all cases, even if we just want to use `renv` in the described setup?
Any workarounds?

Thanks for consideration.

**Comment by kevinushey** [comment]
If I understand correctly, `status()` needs to pass along `library` into `renv_status_check_initialized()`, to support cases where `renv` is being used without explicitly activating / using a project library.

**Comment by hadley** [comment]
I think I see a way forward on this. I'll finish it off on Monday.

**Comment by kevinushey** [comment]
> I do not understand your source code to 100%, but may it be that we need the renv_libpaths_resolve() part before entering the renv_status_check_initialized() function?

The intention here, I think, is to confirm that (for a project using `renv` explicitly) that it does indeed have a project library + a lockfile. So we end up with a slightly different state of affairs; whether or not a project is "initialized" depends on whether the project library exists, but comparing the library + lockfile state just uses the current library paths.

In the end, the hard part is figuring out how to reconcile the behavior of `renv::status()` for initialized versus uninitialized projects.

**Comment by cstepper** [comment]
Thanks @kevinushey! That makes sense to me. I changed my code now to use `renv::status(lockfile = "renv.lock")` whereever I called this function.
