### ISSUE TITLE
`renv::use()` does not respect the sandbox parameter

### ISSUE THREAD

**Issue by MichalLauer** [rstudio/renv#1622]
When a `{renv}` project is activated using `renv::use(...)`, the sandbox parameter is not used.

``` r
renv::use(lockfile = "renv.lock", sandbox = F)
#> - The library is already synchronized with the lockfile.
renv::config$sandbox.enabled()
#> [1] TRUE
```

<sup>Created on 2023-08-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

What I would expect is this behavior:

``` r
renv::use(lockfile = "renv.lock", sandbox = F)
#> - The library is already synchronized with the lockfile.
options(renv.config.sandbox.enabled = F) # this part should be done automatically because I set the parameter to FALSE
renv::config$sandbox.enabled()
#> [1] FALSE
```

<sup>Created on 2023-08-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Here is my session info:

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.3.0 (2023-04-21 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 11 x64 (build 22621)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=Czech_Czechia.utf8  LC_CTYPE=Czech_Czechia.utf8   
#> [3] LC_MONETARY=Czech_Czechia.utf8 LC_NUMERIC=C                  
#> [5] LC_TIME=Czech_Czechia.utf8    
#> 
#> time zone: Europe/Prague
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.32     fastmap_1.1.1     xfun_0.39         glue_1.6.2       
#>  [5] knitr_1.43        htmltools_0.5.5   rmarkdown_2.23    lifecycle_1.0.3  
#>  [9] cli_3.6.1         reprex_2.0.2      renv_1.0.0        withr_2.5.0      
#> [13] compiler_4.3.0    rstudioapi_0.15.0 tools_4.3.0       evaluate_0.21    
#> [17] yaml_2.3.7        rlang_1.1.1       fs_1.6.2
```

</details>

Is this a bug, or am I missing something? Thanks!

**Comment by kevinushey** [comment]
We don't change the option, but you should see the library paths differ in each case, as reported by `.libPaths()`.

**Comment by MichalLauer** [comment]
Oh, so It's not used to enable/disable sandbox; it's used to denote whether it should be used. Thanks! I will manually modify the appropriate config settings.

**Comment by kevinushey** [comment]
Right -- the intention is to allow users to do something like:

```
renv::use("r-lib/rlang", sandbox = FALSE)
```

to use the development version of `rlang`, but still allow whatever other R packages that might currently be installed, to also be used.

**Comment by MichalLauer** [comment]
Got it, thank you very much :)
