### ISSUE TITLE
Errors using `renv` with RMarkdown

### ISSUE THREAD

**Issue by meghanmshea** [rstudio/renv#1623]
I have an RMarkdown file in an R Project that reproduces all of the analyses for a manuscript. Originally, I had a section in the RMarkdown file where required packages were installed (if needed) and loaded, but I am trying to switch over to `renv` for package management. I used `renv::init()` to set up my project to use `renv`, installed and loaded all the packages I needed using my normal script for doing so, and used `renv::snapshot()` to update my lockfile. 

Then, I was imagining I could just use `renv::restore()` in place of my original package loading section in my RMarkdown file. 

While I am able to run individual chunks from the RMarkdown file in the console successfully, and I also seem to be able to render the RMarkdown file from the console successfully, when I try to Knit to HTML using the RStudio IDE, which is typically how I knit, I now get an error from my first chunk of code that suggests `renv::restore()` is not successfully allowing RMarkdown to access the packages:

```
Error in `ggplot()`:
! could not find function "ggplot"
Execution halted
```

Any idea why this is happening and how to fix it? My ideal is that anyone can load the GitHub repo with this R Project, and immediately knit the RMarkdown file to HTML (ideally using the button, rather than code, to make it easy for new R users) without any problems, without having to do anything extra. This was the case when the RMarkdown file installed/loaded packages correctly, so I'm hoping to make it the case using `renv` too, for maximum reproducibility!

**Comment by meghanmshea** [comment]
Update to say that this seems like it might be the same issue experienced in #194

**Comment by kevinushey** [comment]
Thank you for the bug report! Could you share a reproducible example, just so I can confirm exactly what behaviour you're seeing? (Is there any chance you could share the project / R Markdown file you're using on GitHub?)

**Comment by meghanmshea** [comment]
I'm relatively new to GitHub, so apologies if this is not the proper way to do this -- but GitHub repo where I'm attempting to implement `renv` and having issues with the RMarkdown file is here: https://github.com/meghanmshea/intertidal-eDNA/tree/working-branch-3

**Comment by kevinushey** [comment]
Thank you! I took a look, and I think the issue is that you're no longer calling `library()` for the packages you want to use. Calling `renv::restore()` will install the packages recorded in the lockfile, but you'll still need to use e.g. `library(ggplot2)` to load the `ggplot2` package where you're using it.

**Comment by meghanmshea** [comment]
Thank you so much for checking, and sorry for misunderstanding (I thought `renv::restore()` encompassed both `install.package()` and `library()`).
