### ISSUE TITLE
renv 1.0 not working as expected - source('.Rprofile') working but renv::activate() does not. EMR boostrap and Rocker

### ISSUE THREAD

**Issue by ssefick** [rstudio/renv#1627]
Context:

Both in an emr boostrap and
Inside a rocker container with host cache mounted.

renv 1.0

renv::activate() reports to restart

but source('.Rprofile') activates the project.

Please let me know any information you might need.

Thanks!

**Comment by kevinushey** [comment]
Can you elaborate on what exactly you're trying to do?

**Comment by ssefick** [comment]
This is my fault. In 0.6 renv::activate() activated the environment. In 1.0
renv::load() works like renv::activate() used to work.

Please close this issue.

Stephen Sefick

**Comment by kevinushey** [comment]
Thanks!
