### ISSUE TITLE
Feature request: `dependencies()` to scan `NAMESPACE` files

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#1637]
At present, `dependencies()` will perform a static analysis of R files. I find this very useful during development as a mechanism to help build the Imports section of a package's DESCRIPTION file; e.g.:
```r
package_imports <- renv::dependencies("R/")$Package
purrr::walk(package_imports, usethis::use_package, type = "Imports", min_version = TRUE)
```
The only problem is the static analysis skips the NAMESPACE file, which itself is based on roxygen2 tags, and includes some imports. For example, I might have the tag `#' @importFrom foo bar`, yielding the NAMESPACE entry:
```
importFrom(foo, bar)
```
It'd be useful if `dependencies()` also read the NAMESPACE file to identify additional packages.

FWIW, there's a base `parseNamespaceFile()` function, which can be run (here from within the nascent package's root) like so:
```r
parseNamespaceFile("packagename", "..")
```
One would still need to know how to deal with the various outputs -- each type corresponding to each unique NAMESPACE directive, but fortunately new NAMESPACE directives don't come around too often :-)

**Comment by AshesITR** [comment]
This feature would also be useful to manually specify dependencies that renv doesn't discover.
Currently, we use a no-use R script with `library(pkg)` calls to force renv to discover some dependencies.

**Comment by mmuurr** [comment]
Amazing; thanks!
