### ISSUE TITLE
Unable to install packages inside renv-tracked project - need to reset "repos" option?

### ISSUE THREAD

**Issue by DCEW** [rstudio/renv#1644]
This is a similar problem to some posted here before, but none of the stated fixes work for me.  In a brand new renv-initiated project, `install.packages("here")` leads to `"Error: package 'here' is not available"`.  

Outside of projects, the getOption("repos") call returns "https://cran.rstudio.com/", but inside an renv project it returns "https://packagemanager.posit.co/cran/latest".  I can't access that second URL in a browser, but I can obviously access cran.rstudio.com.  Not sure how to change the repo within the project.  

I've tried:
Adding `Sys.setenv("RENV_CONFIG_REPOS_OVERRIDE" = "https://cran.rstudio.com/")`, but getOption("repos") doesn't change even after a restart.

For info:
`> renv::diagnostics()
Diagnostics Report [renv 1.0.0]
===============================

# Session Info ---------------------------------------------------------------
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8 
[2] LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.1    tools_4.3.1       rstudioapi_0.15.0 renv_1.0.0       

# Project --------------------------------------------------------------------
Project path: "C:/Users/.../Documents/project"

# Status ---------------------------------------------------------------------
The following package(s) are missing their DESCRIPTION files:

- viridis [C:/Users/.../Documents/project/renv/library/R-4.3/x86_64-w64-mingw32/viridis]

These may be left over from a prior, failed installation attempt.
Consider removing or reinstalling these packages.

The following package(s) are in an inconsistent state:

 package       installed recorded used
 askpass       y         n        y   
 backports     y         n        y   
 base64enc     y         n        y   
 bit           y         n        y   
 bit64         y         n        y   
 blob          y         n        y   
 broom         y         n        y   
 bslib         y         n        y   
 cachem        y         n        y   
 callr         y         n        y   
 cellranger    y         n        y   
 cli           y         n        y   
 clipr         y         n        y   
 colorspace    y         n        y   
 conflicted    y         n        y   
 cpp11         y         n        y   
 crayon        y         n        y   
 curl          y         n        y   
 data.table    y         n        y   
 DBI           y         n        y   
 dbplyr        y         n        y   
 digest        y         n        y   
 dplyr         y         n        y   
 dtplyr        y         n        y   
 ellipsis      y         n        y   
 evaluate      y         n        y   
 fansi         y         n        y   
 farver        y         n        y   
 fastmap       y         n        y   
 fontawesome   y         n        y   
 forcats       y         n        y   
 fs            y         n        y   
 gargle        y         n        y   
 generics      y         n        y   
 ggplot2       y         n        y   
 glue          y         n        y   
 googledrive   y         n        y   
 googlesheets4 y         n        y   
 gtable        y         n        y   
 haven         y         n        y   
 highr         y         n        y   
 hms           y         n        y   
 htmltools     y         n        y   
 httpuv        y         n        y   
 httr          y         n        y   
 ids           y         n        y   
 isoband       y         n        y   
 jquerylib     y         n        y   
 jsonlite      y         n        y   
 knitr         y         n        y   
 labeling      y         n        y   
 later         y         n        y   
 lattice       y         n        y   
 lifecycle     y         n        y   
 lubridate     y         n        y   
 magrittr      y         n        y   
 MASS          y         n        y   
 Matrix        y         n        y   
 memoise       y         n        y   
 mgcv          y         n        y   
 mime          y         n        y   
 modelr        y         n        y   
 monochromeR   n         n        y   
 munsell       y         n        y   
 NHSRtheme     y         n        y   
 nlme          y         n        y   
 openssl       y         n        y   
 pillar        y         n        y   
 pkgconfig     y         n        y   
 prettyunits   y         n        y   
 processx      y         n        y   
 progress      y         n        y   
 promises      y         n        y   
 ps            y         n        y   
 purrr         y         n        y   
 R6            y         n        y   
 ragg          y         n        y   
 rappdirs      y         n        y   
 RColorBrewer  y         n        y   
 Rcpp          y         n        y   
 readr         y         n        y   
 readxl        y         n        y   
 rematch       y         n        y   
 rematch2      y         n        y   
 reprex        y         n        y   
 rlang         y         n        y   
 rmarkdown     y         n        y   
 rstudioapi    y         n        y   
 rvest         y         n        y   
 sass          y         n        y   
 scales        y         n        y   
 selectr       y         n        y   
 servr         y         n        y   
 sf            n         n        y   
 stringi       y         n        y   
 stringr       y         n        y   
 sys           y         n        y   
 systemfonts   y         n        y   
 textshaping   y         n        y   
 tibble        y         n        y   
 tidyr         y         n        y   
 tidyselect    y         n        y   
 tidyverse     y         n        y   
 timechange    y         n        y   
 tinytex       y         n        y   
 tzdb          y         n        y   
 utf8          y         n        y   
 uuid          y         n        y   
 vctrs         y         n        y   
 viridis       n         n        y   
 viridisLite   y         n        y   
 vroom         y         n        y   
 withr         y         n        y   
 xaringan      y         n        y   
 xfun          y         n        y   
 xml2          y         n        y   
 yaml          y         n        y   

See ?renv::status() for advice on resolving these issues.

# Packages -------------------------------------------------------------------
Traceback (most recent calls last):
4: renv::diagnostics()
3: tryCatch(reporter(project), error = renv_error_handler)
2: tryCatchList(expr, classes, parentenv, handlers)
1: tryCatchOne(expr, names, parentenv, handlers[[1L]])

# ABI ------------------------------------------------------------------------
- ABI conflict checks are not yet implemented on Windows.

# User Profile ---------------------------------------------------------------
[1] Source  Package Require Version Dev    
<0 rows> (or 0-length row.names)

# Settings -------------------------------------------------------------------
List of 13
 $ bioconductor.version     : NULL
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ ppm.enabled              : NULL
 $ ppm.ignored.urls         : chr(0) 
 $ r.version                : NULL
 $ snapshot.type            : chr "implicit"
 $ use.cache                : logi TRUE
 $ vcs.ignore.cellar        : logi TRUE
 $ vcs.ignore.library       : logi TRUE
 $ vcs.ignore.local         : logi TRUE
 $ vcs.manage.ignores       : logi TRUE

# Options --------------------------------------------------------------------
List of 8
 $ defaultPackages                     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method                : NULL
 $ download.file.extra                 : NULL
 $ install.packages.compile.from.source: chr "interactive"
 $ pkgType                             : chr "both"
 $ repos                               : Named chr "https://packagemanager.posit.co/cran/latest"
  ..- attr(*, "names")= chr "CRAN"
 $ renv.consent                        : logi TRUE
 $ renv.verbose                        : logi TRUE

# Environment Variables ------------------------------------------------------
HOME                        = C:/Users/.../OneDrive - NHS/Documents
LANG                        = <NA>
MAKE                        = <NA>
R_LIBS                      = <NA>
R_LIBS_SITE                 = C:/PROGRA~1/R/R-43~1.1/site-library
R_LIBS_USER                 = C:/Users/.../Documents/project/renv/library/R-4.3/x86_64-w64-mingw32;C:/Users/clwe3/AppData/Local/R/cache/R/renv/sandbox/R-4.3/x86_64-w64-mingw32/e9e85620
RENV_CONFIG_REPOS_OVERRIDE  = https://cran.rstudio.com/
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = C:/PROGRA~1/R/R-43~1.1/site-library
RENV_DEFAULT_R_LIBS_USER    = C:\Users\clwe3\AppData\Local/R/win-library/4.3
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = C:/Users/.../Documents/project

# PATH -----------------------------------------------------------------------
- c:\rtools43\x86_64-w64-mingw32.static.posix\bin
- c:\rtools43\usr\bin
- C:\Program Files\R\R-4.3.1\bin\x64
- C:\Program Files (x86)\Common Files\Oracle\Java\javapath
- C:\Windows\system32
- C:\Windows
- C:\Windows\System32\Wbem
- C:\Windows\System32\WindowsPowerShell\v1.0\
- C:\Windows\System32\OpenSSH\
- C:\Program Files\Git\cmd
- C:\Users\clwe3\AppData\Local\Programs\Quarto\bin
- C:\Users\clwe3\AppData\Local\Microsoft\WindowsApps
- C:\Users\clwe3\AppData\Roaming\TinyTeX\bin\windows
- C:\Users\clwe3\AppData\Local\Programs\Quarto\bin
- C:\Program Files\RStudio\resources\app\bin\postback

# Cache ----------------------------------------------------------------------
There are a total of 225 packages installed in the renv cache.
Cache path: "C:/Users/.../AppData/Local/R/cache/R/renv/cache/v5/R-4.3/x86_64-w64-mingw32"`

Any help greatly appreciated, along with explanation of why this is happening!!

**Comment by kevinushey** [comment]
Is it possible that PPM was briefly unavailable?

You can reset the repositories using e.g.

```
options(repos = c(CRAN = "https://cran.rstudio.com"))
renv::snapshot()
```

**Comment by DCEW** [comment]
That seems to have worked!! So simple, thanks @kevinushey !!

**Comment by kevinushey** [comment]
Great, I'm glad to hear it!
