### ISSUE TITLE
large directories in tempdir cause error with NULL root

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#1658]
``` r
t <- tempfile()
dir.create(t)
for (each in seq_len(1001)) { writeLines(character(0), file.path(t, paste0(each, ".txt")))}
renv::dependencies(t)
#> Error in dirname(root): a character vector argument expected
```

<sup>Created on 2023-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This happens because `renv:::renv_dependencies_root()` returns `NULL` when provided the temporary directory as its `path`.

https://github.com/rstudio/renv/blob/ac7126d7b2856a39012d6079689861b18c07c5b7/R/dependencies.R#L218-L219

This is the underlying issue causing https://github.com/rstudio/rsconnect/issues/968

**Comment by aronatkins** [comment]
Workaround is to set `renv.config.dependencies.limit`.

```r
options(renv.config.dependencies.limit = 10000)
```

Bypassing the "large directory" handling lets `renv::dependencies()` complete.

**Comment by kevinushey** [comment]
I think it ultimately comes down to this:

```
> renv:::renv_dependencies_root(t)
NULL
```

So, I think that setting `root` is the right solution here.
