### ISSUE TITLE
Different library paths between R project and R package

### ISSUE THREAD

**Issue by ntyndall** [rstudio/renv#1660]
Hi there,

Thanks for all the work on this project! renv has really saved me with lots of multiple projects I have been working on these past few years. I have been working off of a particular version 0.13.2. I have had to recently upgrade to 1.0.2 for other reasons, and I am getting some strange behaviour (possibly intended). I am on a windows machine.

When I create a project (**abc**) and initialise with renv my default library location is as follows; which is what I am used to seeing in 0.13.2
![image](https://github.com/rstudio/renv/assets/25510323/362d79ad-5f7f-494b-9fa6-f0f36ed03183)

However, when I create an R package (**def**) and initialise with renv, my default library location is different... 
![image](https://github.com/rstudio/renv/assets/25510323/836ec609-826c-48a9-a7f6-837c2933610e)

In 0.13.2 this wasn't the behaviour as I have maybe 15 different packages and I kind of depend the library directory to be in the packages root location, i.e. **def/renv/library**. I'm kind of out of ideas at this stage, are there some environment variables I can maybe tweak to get this to build into my packages root **renv/library** location.

I have tried various different ways, the checkboxes on the Rstudio gui, and also just using `renv::init()` etc but it's just looking a little strange. When I install packages, I am then not able to `renv::snapshot()` these into the `renv.lock` file either, even running `renv::status()` looks okay as well..

I should note that if it's relevant; my user name has a dot between my two names that I have blacked out in the image above. e.g. **john.smith**

**Comment by kevinushey** [comment]
This change was intentional, with rationale described here:

https://github.com/rstudio/renv/blob/ac7126d7b2856a39012d6079689861b18c07c5b7/NEWS.md?plain=1#L635-L639

See also the online documentation here: https://rstudio.github.io/renv/articles/packages.html. In particular, you should be able to set:

```
RENV_PATHS_LIBRARY = renv/library
```

in your project `.Renviron` to ensure the project library is always stored in that location.

**Comment by emountier** [comment]
I've just come here with similar extreme gratitude and a similar problem 😊

 @kevinushey the behaviour you've described below (and the workaround) used to be explained in vignettes/packages.Rmd but looks like that whole section was deleted in commit #794d8b. Am I missing it somewhere else in the docs ? 
> 
> See also the online documentation here: https://rstudio.github.io/renv/articles/packages.html. In particular, you should be able to set:
> 
> ```
> RENV_PATHS_LIBRARY = renv/library
> ```
> 
> in your project `.Renviron` to ensure the project library is always stored in that location.

**Comment by kevinushey** [comment]
@emountier -- thanks for catching that! I think this was unintentional; I've added that documentation back in https://github.com/rstudio/renv/commit/70ba9e232386d8154f56da343c103cab57c1b07f.

**Comment by kevinushey** [comment]
@ntyndall, now that this is probably documented again, I believe this issue can be closed -- please feel free to re-open if you're still having trouble or have any other questions.

**Comment by ntyndall** [comment]
I don't know how I missed these comments - my github account is linked to an old email address - but that worked perfectly! Really saved me from a lot of headaches, and thank you so much again!

**Comment by emountier** [comment]
@kevinushey should the the restored "Library paths" section be showing up in the [rendered site](https://rstudio.github.io/renv/articles/packages.html) now? It isn't for me (have cleared browser cache etc)

**Comment by kevinushey** [comment]
It's available on the development version of the documentation at https://rstudio.github.io/renv/dev/articles/packages.html; the main site will be updated alongside the next `renv` release (hopefully soon).

**Comment by ntyndall** [comment]
@kevinushey sorry to be a pain on this ticket. I was testing out some stuff in terms of our set up. I am upgrading to try and fix a load of problems we are having lately, so I am using renv 1.0.3 now; and this functionality did work correctly when using renv 1.0.2, but I noticed that setting the RENV_PATHS_LIBRARY to something like renv/test does set up the skeleton and installs renv in there, but .libPaths() remains unchanged

![image](https://github.com/rstudio/renv/assets/25510323/abef3f95-627e-4ec6-9f80-f76bc9b41496)

In a way, this isn't a big problem for me, but just a heads up that this variable doesn't seem to be doing what is intended from what I can see!

Thanks!
