### ISSUE TITLE
Installed dependencies not kept if main installation fails

### ISSUE THREAD

**Issue by kinto-b** [rstudio/renv#1661]
Unfortunately I can't provide a reprex, but every now and then I will come across a package that I can't install together with its dependencies. So for instance, just now I tried to install `geojsonio`. I was missing a bunch of deps, so I had to install them too. I got:

```
# Installing packages --------------------------------------------------------
- Installing urltools ...                       OK [installed binary and cached in 1.9s]
- Installing httpcode ...                       OK [installed binary and cached in 1.7s]
...
- Installing sf ...                             OK [installed binary and cached in 17s]
- Installing V8 ...                             OK [installed binary and cached in 3.3s]
- Installing geojsonio ...                      FAILED
```

with the issue being that `...geojsonio.rdb' is corrupt`. 

Often, if I install each dependency individually, and then try installing the main package again, it will work. Since I've just installed all the deps, I should just be able to run `renv::install('geojsonio')` to do that. But, alas, I get:

```
# Installing packages --------------------------------------------------------
- Installing urltools ...                       OK [linked from cache in 1.5s]
- Installing httpcode ...                       OK [linked from cache in 1.0s]
...
- Installing s2 ...                             OK [linked from cache in 1.9s]
- Installing units ...                          OK [linked from cache in 1.7s]
- Installing sf ...                             OK [linked from cache in 19s]
- Installing V8 ...                             OK [linked from cache in 2.0s]
- Installing geojsonio ...                      FAILED
```

It seems like if one of the installations fails, all are rewound? 

It's easy enough to run

```r
renv::install(tools::package_dependencies("geojsonio")[[1]])
```

but I think it would be preferable if the installed deps just stuck around despite the failure.

**Comment by kevinushey** [comment]
This is controlled via the following option:

https://rstudio.github.io/renv/reference/config.html#renv-config-install-transactional

You can disable that if you'd like to have the previously-installed packages remain in the project library even if a later package installation fails.

**Comment by kinto-b** [comment]
Ah, stellar! Thanks very much!
