### ISSUE TITLE
Bioconductor installation issue for R 3.6.0

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#167]
https://community.rstudio.com/t/rstudio-connect-packrat-chokes-on-bioconductor-packages/36706

This community thread discusses changes to R 3.6.0, for which:

Bioconductor packages need to be installed using BiocManager::install().

Similar issue within packrat: https://github.com/rstudio/packrat/issues/573

**Comment by kevinushey** [comment]
This should already be handled in `renv`:

https://github.com/rstudio/renv/blob/729e33e3bbcfd549947f22b95db5b8ef0f62b8ef/R/bioconductor.R#L34-L47

Please file a reprex if you see that's not the case.
