### ISSUE TITLE
renv installing from cran.rstudio url not locating echarts4r 0.4.5

### ISSUE THREAD

**Issue by Patrikios** [rstudio/renv#1673]
restoring `echarts4r `package from` renv.lock`, renv cannot locate the following link:

`Downloading echarts4r from CRAN ...             ERROR [cannot open URL 'https://cran.rstudio.com/src/contrib/Archive/echarts4r/echarts4r_0.4.5.tar.gz': HTTP status was '404 Not Found']`

**Comment by kevinushey** [comment]
Can you please provide a reproducible example / share the lockfile you were using when you encountered this error? I'm guessing this was a transient error and has now already resolved?

**Comment by Patrikios** [comment]
The problem at hand is persistent, non-transcient.
That means, the renv entry as can be seen under, an excerpt from the lock file, shows the 'signature' which then on restore calls the URL` https://cran.rstudio.com/src/contrib/Archive/echarts4r/echarts4r_0.4.5.tar.gz`. An this URL is dead, there is nothing there. Hence my question, why does renv not ping the canonical CRAN URL `https://cran.r-project.org/src/contrib/echarts4r_0.4.5.tar.gz` (which works) on failure from the rstudio mirror? I would guess, as I installed from CRAN, that will be the primary mirror and additionaly some failover option would make sense to me.
Thnx for your time reviewing this!

```
...  
  "echarts4r": {
      "Package": "echarts4r",
      "Version": "0.4.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "broom",
        "corrplot",
        "countrycode",
        "dplyr",
        "htmltools",
        "htmlwidgets",
        "jsonlite",
        "purrr",
        "rstudioapi",
        "scales",
        "shiny"
      ],
      "Hash": "4247fd6acd3bdb4a481479f469956d2f"
    },
...
```

**Comment by Patrikios** [comment]
Was transcient.
I was using on the other server R version 4.0.5 whereas the echarts4r explicitely needs at least 4.1.0.
Upgrading to lock version of R solved the issue.
Thnx for your time!
