### ISSUE TITLE
Explicit mode and suggested packages

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/renv#1677]
`renv::init()` installs packages in `Suggests`. Which is the right thing to do, probably.

But these packages are not added to `renv.lock`, and if the project/package is copied to a new user/location, they are not restored.

Should they be added to the lock file? Should they be restored?

Is there a way to install them manually?

**Comment by kevinushey** [comment]
We decided to treat packages in Suggests as development dependencies, so that `renv::install()` would install those packages but they wouldn't be tracked in the lockfile. You're not the first person to find this confusing though.

cc: @hadley

**Comment by gaborcsardi** [comment]
I think that's ok. Is there a way to install the suggested packages as well? Are you saying that `renv::install()` will install them?

**Comment by kevinushey** [comment]
> Are you saying that renv::install() will install them?

I thought that was the case, but apparently it's not... that feels like a bug to me? The behavior should ideally match what `pak::pak()` does.

**Comment by hadley** [comment]
I think we should add an explicit `dev = TRUE` argument to `install()` (and possibly `dev = FALSE` to `snapshot()`) to make it crystal clear what's supposed to happen.

**Comment by kevinushey** [comment]
Maybe I did something wrong; it looks like `renv::install()` is working as expected?

```
cd "$(mktemp -d)"
cat <<- EOF > DESCRIPTION
Type: Package
Imports: rlang
Suggests: packrat
EOF

R -e 'renv::init()'
R -e 'renv::install()'
```

And I see during installation:

```
$ R -e 'renv::install()'
- Project '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.1sAE9PGI' loaded. [renv 1.0
.2.9000]
> renv::install()
# Downloading packages -------------------------------------------------------
- Downloading packrat from CRAN ...             OK [file is up to date]
Successfully downloaded 1 package in 1.2 seconds.

The following package(s) will be installed:
- packrat [0.9.2]
- rlang   [1.1.1]
These packages will be installed into "~/Library/Caches/org.R-project.R/R/renv/library/tmp.1sAE9PGI
-d7cfbd42/R-4.3/aarch64-apple-darwin20".

# Installing packages --------------------------------------------------------
- Installing rlang ...                          OK [linked from cache]
- Installing packrat ...                        OK [installed binary and cached in 0.55s]
Successfully installed 2 packages in 0.6 seconds.
```
