### ISSUE TITLE
Global Package Cache on Databricks -- Persistence + Change

### ISSUE THREAD

**Issue by kmishra9** [rstudio/renv#1679]
Hey there,

Was going through the process of [setting up renv to work with R in Databricks](https://docs.databricks.com/en/sparkr/renv.html#id3) via Notebooks + RStudio Server and the lack of an automated `.Rprofile` sourcing mechanism in the context of Databricks Notebooks and the ephemeral compute makes the global cache very important and a little confusing to set and change the path (to a non ephemeral DBFS path).

When I install packages from `renv` I get the following:
`These packages will be installed into "/local_disk0/.ephemeral_nfs/envs/rEnv-6e7151e7-3792-4219-ae69-7dec6aaa5672".`
This is _fine_, I assume -- a local ephemeral copy of the packages, symlinked to the global cache. Am slightly confused that none of the paths at `renv::paths$*` (i.e. library, sandbox, etc.) give me this path but it's fine.

I also understand we can _access_ and set our `renv` global cache path with these commands: 
```
>  renv::paths$cache()
"/Workspace/Repos/kunal.mishra@interwellhealth.com/data-predictive-analytics/v5/R-4.2/x86_64-pc-linux-gnu"

> Sys.setenv(RENV_PATHS_CACHE = here::here()) # here::here() = /Workspace/Repos/kunal.mishra@interwellhealth.com/data-predictive-analytics

> # Change not reflected:
>  renv::paths$cache()
"/Workspace/Repos/kunal.mishra@interwellhealth.com/data-predictive-analytics/v5/R-4.2/x86_64-pc-linux-gnu"
```
But when an R session is already running, is there a way to set the cache path? Or even alter the path to which our project's library is saved? Right now, the global package cache is persisting on the DBFS (good), but I wonder if that's the default behavior or something that occurred because I did a `setwd(here::here())` at some point earlier and the cache ended up in that working directory due to that. 

If there's not a way, a possible addition here could be a function for refreshing or setting the cache path that works _with_ the environment variable (like `sparkler::spark_home_set()`) that refreshes the output of `renv::paths$cache()` as well.

**Comment by kevinushey** [comment]
> This is fine, I assume -- a local ephemeral copy of the packages, symlinked to the global cache. Am slightly confused that none of the paths at renv::paths$* (i.e. library, sandbox, etc.) give me this path but it's fine.

You should be able to see this in `.libPaths()` as the first entry.

Regarding the code you shared:

```
> Sys.setenv(RENV_PATHS_CACHE = here::here()) # here::here() = /Workspace/Repos/kunal.mishra@interwellhealth.com/data-predictive-analytics

> # Change not reflected:
>  renv::paths$cache()
"/Workspace/Repos/kunal.mishra@interwellhealth.com/data-predictive-analytics/v5/R-4.2/x86_64-pc-linux-gnu"
```

The output looks correct to me -- am I misunderstanding something? Note that `renv` will always append a platform-specific prefix to the cache path, just in case you'd like to have a single cache path that's used by multiple different machines / architectures.

**Comment by kmishra9** [comment]
Gotcha -- the prefix in this case would then be `v5/R-4.2/x86_64-pc-linux-gnu`, correct? I think that part was throwing me. 

I was also able to confirm updating `RENV_PATHS_CACHE` was immediately reflected in a different output when calling `renv::paths$cache()` too, so that's great -- I must've done something differently the first time to have not seen that update properly. 

And finally, yes the local library path where packages are symlinked from the cache was in `.libPaths()` as the first entry. 

Think this was all just some confusion on my end -- thought I needed to _do_ something specific to enable the global cache to persist, based on [a thread](https://github.com/facebook/prophet/issues/1857) I had come upon, but I think it's actually working by default fairly sensibly once I start things with a `setwd(here::here())` to mimic an RStudio project.
