### ISSUE TITLE
Package installation with `renv::restore()` is broken

### ISSUE THREAD

**Issue by sebffischer** [rstudio/renv#1688]
Hey, thanks for your work on the renv package!

I have noticed  that calling `renv::restore()` can install packages incorrectly.
This is with R 4.3.1 and  renv 1.0.0
I have created an example repository with a workflow that illustrates this behavior [here](https://github.com/sebffischer/zzz/actions/runs/6173720354/job/16756711475).

This workflow essentially runs:

```r
library(mlr3)
LearnerClassifRpart$new()$train
```
twice, once after installing mlr3 using `renv::restore()` and once using `install.packages("mlr3")` and the output is different.
(The code in the workflow is `lrn("classif.rpart")$train`, which is equivalent to the above `LearnerClassifRpart$new()$train`).

In the relevant package (https://github.com/mlr-org/mlr3) for which the installation via renv fails, we have some "magic" in the `./R/zzz.R` file, which "leanifies" R6 classes (see: https://github.com/mlr-org/mlr3misc/blob/main/R/leanify.R and https://github.com/mlr-org/mlr3/blob/dfa917ea8afd074b632547242cd853005b4e2a76/R/zzz.R#L96)
This walks over all R6 classes and puts the class methods as functions into the `mlr3` namespace and then replaces the method in the class with a call to the function from the namespace.

E.g. the public `$train` method from the `Learner` R6 class (from which `LearnerClassifRpart` inherits) is put into the mlr3 namespace as 
```r
.__Learner__train = function(self, private, super, task, row_ids) {
      task = assert_task(as_task(task))
      assert_learnable(task, self)
      row_ids = assert_row_ids(row_ids, null.ok = TRUE)
      ... (the actual content of the function)
}
```

The method in the R6 class is then replaced with a call to the above function:

``` r
library(mlr3)
lrn("regr.rpart")$train
#> function (task, row_ids = NULL) 
#> .__Learner__train(self = self, private = private, super = super, 
#>     task = task, row_ids = row_ids)
#> <environment: 0x55a424ab3230>
```

When installing packages using `renv::restore()` this leanification is not applied and the output of `lrn("classif.rpart")$train` is not as expected, but what should be the content of `.__Learner__train`.

```r
function(task, row_ids = NULL) {
      task = assert_task(as_task(task))
      assert_learnable(task, self)
      row_ids = assert_row_ids(row_ids, null.ok = TRUE)
      ... (the actual content of the function)
    }
```

If this is not an issue with renv but a dependency, please let me know and I will transfer the issue.

**Comment by sebffischer** [comment]
I also get the warning:

```
Warning in read.dcf(file.path(p, "DESCRIPTION"), c("Package", "Version")) :
  cannot open compressed file '/home/runner/work/zzz/zzz/renv/library/R-4.3/x86_64-pc-linux-gnu/renv/DESCRIPTION', probable reason 'No such file or directory'
```

after calling `renv::restore()` (see the logs from the workflow run above).

**Comment by kevinushey** [comment]
I just tried restoring from your example (using the development version of `renv`) and I see:

```
> LearnerClassifRpart$new()$train
function (task, row_ids = NULL)
.__Learner__train(self = self, private = private, super = super,
    task = task, row_ids = row_ids)
```

Is that the correct output?

Either way, I'd strongly recommend using the latest release of `renv` rather than 1.0.0.

**Comment by kevinushey** [comment]
It also seems very unlikely to me that `renv` could be the culprit here, since `renv` is just running `R CMD INSTALL` underneath the hood and so the behavior should be identical either way.

**Comment by sebffischer** [comment]
Thank you for your response, it seems the `--with-keep.source` is the culprit in `R CMD INSTALL --with-keep.source path/to/mlr3`. Thanks for pointing out that you just call this function and sorry for bothering!

**Comment by kevinushey** [comment]
Thanks for reporting back! If that's the case, I wonder if the problem here is that the source references on the functions aren't being updated after you mutate their definitions?

**Comment by sebffischer** [comment]
Yes that seems to be at least related to the problem, I have not understood it fully yet.

The whole point of the "leanification" is to circumvent objects being gigantic after writing + reading from disk and when installing mlr3 with --with-keep.source = TRUE our solution stops working.

Consider the code below, where the size of the written object depends on the number of packages that are loaded before: 

``` r
library(mlr3)
library(mlr3verse)
library(data.table)

task = tsk("iris")
learner = lrn("classif.rpart")

learner$fallback = lrn("classif.featureless")

learner$train(task)

pth = tempfile(fileext = ".rds")

saveRDS(learner$state, pth)

x = readRDS(pth)

pryr::object_size(x)
#> 19.78 MB
```

<sup>Created on 2023-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sebffischer** [comment]
Still I have a question (because I don't understand why our GH actions workflow **used** to work): Did you change something in renv that added the `--with-keep.source` to the installation?

**Comment by kevinushey** [comment]
Yes, that was a relatively recent change: https://github.com/rstudio/renv/commit/19830de675350e8b555a7765752e6390856c30a4
