### ISSUE TITLE
Recognize linux binaries vs. build from source

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#169]
Related to https://github.com/rstudio/packrat/issues/572

It seems that `renv` has the same behavior that it expects that `.tar.gz` means source vs. binary.

```
Installing tinytex [0.15] from CRAN ...
	OK (built from source)
Installing rmarkdown [1.15] from CRAN ...
	OK (built from source)
Installing reprex [0.3.0] from CRAN ...
	OK (built from source)
Retrieving 'https://cluster.rstudiopm.com/cran/__linux__/xenial/latest/src/contrib/rvest_0.3.4.tar.gz' ...
	OK [downloaded 890 Kb in 4.4 secs]
Installing selectr [0.4-1] ...
	OK (linked cache)
Installing rvest [0.3.4] from CRAN ...
	OK (built from source)
```

Also, am I seeing some multi-threadedness here? Surprising to me that `rvest` was downloaded before `selectr` was installed.

**Comment by kevinushey** [comment]
Are you using the latest version of `renv`? This should already be fixed.

What `renv` command did you invoke to produce that output? (is this an install or restore?)

**Comment by colearendt** [comment]
This was install. I thought I was updated, but I think I was on a super old version 😬 Sorry about that!
