### ISSUE TITLE
renv::clean either does not listen or sends bad messages

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#170]
```
renv::clean()
* Enumerating packages used by renv projects ... Done!
The following packages are installed in the cache but no longer used:

	renv 0.6.0-141 [Hash: 9fc911db6b6aeb188e7b3edccebb1319]

These packages will be removed.

Do you want to proceed? [y/N]: N
* The project has been cleaned.
```

Also, why did `renv::clean` detect itself?

**Comment by kevinushey** [comment]
Two things going on here:

1. `renv` itself gets installed into a special separate directory, and is explicitly filtered so it's not detected as a project dependency. If you install `renv` into a project library, then it will be seen as an "installed but not used" package (unless, of course, you _do_ explicitly use it with e.g. `library(renv)` somewhere)

2. Multiple clean actions are run during clean; the message "* The project has been cleaned." gets emitted if any of the cleaning actions ran successfully. I'll have to think about how to better report this.

**Comment by kevinushey** [comment]
I think the situation here should be better now -- please re-open if you're still seeing some oddness.

**Comment by Kodiologist** [comment]
```
Do you want to proceed? [y/N]: N
* The project has been cleaned.
```

This still happens as of `renv` 0.17.3, and it freaked me out until I realized that `renv` hadn't actually done anything. I think the right thing to do is probably to remove the [unconditional message](https://github.com/rstudio/renv/blob/aa3df0efb8a9ed2542aa757bd9991f75f2388dc5/R/clean.R#L96) "The project has been cleaned." If completion messages are desired, they should probably be implemented per action, and only print when the action actually runs.

**Comment by Kodiologist** [comment]
Cool, thanks.
