### ISSUE TITLE
Empty binary on CRAN causes "In max(n) : no non-missing arguments to max; returning -Inf" 

### ISSUE THREAD

**Issue by slodge-work** [rstudio/renv#1706]
What I'm seeing is frequent but occasional messages saying:

> Warning message:
> In max(n) : no non-missing arguments to max; returning -Inf

I see these reported occasionally after the renv activation during an R session start, and after operations like `renv::restore()`:

![image](https://github.com/rstudio/renv/assets/141234056/48119108-17ae-4596-a91c-985c20afdf2d)

Using `options(warn=2)` I managed to track this down to renv_available_packages_success being passed an empty `db` parameter:

![image](https://github.com/rstudio/renv/assets/141234056/aa9dbf11-fa8f-4f37-b82b-9f7996794579)

Looking down the stack this is because our CRAN server for our local packages doesn't cache any binaries - so it returns an empty string for PACKAGES for https://cran.OurCo.app/cran/bin/windows/contrib/4.3

We can change this behaviour in our CRAN server - it can return 404 instead I guess.. although then I suspect we will see warnings about the file being missing... Or maybe we could add a dummy `zzzUnicorn` binary entry...

But I thought I'd also check with renv whether this is a situation you want to handle without this warning (or with a more specific message/warning)

**Comment by kevinushey** [comment]
Thanks for the bug report; this seems like something we should be able to handle more gracefully.
