### ISSUE TITLE
renv::run() returns error in defer() function in all versions after 0.17.3

### ISSUE THREAD

**Issue by YannisChourdakis** [rstudio/renv#1707]
When running renv::run() in both 1.0.0 and 1.0.3 version I get the error below, I would greatly appreciate any thoughts or help on this.

```
Error in defer(unlink("D:\\Users\\<username>\\AppData\\Local\\Temp\\RtmpY9w5CO\\renv-job-b88396d210b.R")) : 
  could not find function "defer"
Calls: .rs.sourceWithProgress ... local -> eval.parent -> eval -> eval -> eval -> eval
Execution halted
```

**Comment by kevinushey** [comment]
Thanks for the bug report; we'll try to take a look for the next release.

**Comment by f-hafner** [comment]
I still have this issue in a special case: After installing `Hmisc` in an `renv` environment, I cannot use run scripts anymore with `renv::run()`.

OS: ubuntu 20
R: 4.3.2

To reproduce, start with script `myscript.R`:
```R
print("hello world")
```

Open the R console where the script is stored. Then
```R
install.packages("renv")
library(renv)
renv::init()
renv::run("myscript.R")
```

This should work fine.

Now, adopt `myscript.R`:
```R
print("hello world")
library(Hmisc)
```

Then, back in the R console, do 
```R
renv::snapshot() # press 2, and press Y
renv::run("myscript.R") # fails
```
When run from the ubuntu terminal, the same works without problems.

**Comment by klmr** [comment]
I’m still experiencing this issue in v1.0.7.

It’s 100% reproducible in interactive mode but doesn’t fail in non-interactive mode. In particular, the error occurs when loading a project via `renv::load()` from inside another ‘renv’ project. Here’s my simplified project outline:

```
client-package
├── DESCRIPTION
├── NAMESPACE
├── R
├── dev
│   └── deploy-server
├── man
├── renv
├── renv.lock
├── server
│   ├── renv
│   ├── renv.lock
│   └── rsconnect
└── tests…
```

`deploy-server` is a script that deploys the `server` subdirectory as a Plumber API to Posit Connect. Its simplified code looks as follows:

```r
#!/usr/bin/env Rscript

dir = commandArgs(trailingOnly = TRUE)[1L]
app_id = commandArgs(trailingOnly = TRUE)[2L]

# We need to explicitly add the library of the R environment of the app we are deploying. If we don’t do this, ‘rsconnect’ won’t find the dependencies declared in the R environment of the server project. Conversely, we need to make sure that ‘rsconnect’ can still find its dependencies; so we append the *current* R environment library path.
old_lib = .libPaths()[1L]
renv::load(dir)
renv::restore()
.libPaths(c(.libPaths(), old_lib))
rsconnect::deployApp(dir, appId = app_id, account = 'default', server = 'default')
```

Here, `renv::load(dir)` fails. Interestingly, calling it *again* afterwards succeeds.

The error message is:

> ```
> Error in defer(setwd(owd), scope = scope) : 
>   could not find function "defer"
> Traceback (most recent calls last):
> 3: renv::load(dir)
> 2: if (switch)
>      return(renv_load_switch(project)) at load.R#98
> 1: renv_scope_wd(project) at load.R#701
> ```

Running `get('defer', asNamespace('renv'))` *does* show the definition of `defer` in the namespace `renv`, so I have no idea why it isn’t found by `renv_scope_wd()`.

**Comment by kevinushey** [comment]
I wonder if https://github.com/rstudio/renv/commit/5125714cf11bc20345c2051483ebd237dad5e62c is enough to resolve the issue -- that is, avoid using `renv` functions directly after unloading?

Or is this a sort of fool's errand?

**Comment by klmr** [comment]
No, that *should* work. Unfortunately I cannot test it now since I’m on holidays and the project with the reported issue is on my work computer. I’ll check it next week!

An alternative solution (which is not necessarily better, just mentioning it for completeness), and which I’m currently using as a workaround, is to force all namespace names before unloading ‘renv’ (e.g. via `mget(ls(envir = topenv()), envir = topenv())`).

**Comment by klmr** [comment]
Okay, I’ve finally tried it, and that change seems to work well. 💯
