### ISSUE TITLE
markdown package not discovered when there's an .Rmd file

### ISSUE THREAD

**Issue by eliocamp** [rstudio/renv#1708]
I've noticed that renv seems to discover knitr and its dependencies if the project has an .Rmd file. However, it fails to record the markdown package as a necessary dependency. 

1. Create a new project with an R Markdown document (say, paper.Rmd)
2. run `renv::init()` .
3. Reopen the project (see #1709). 
4. Click the knit button.

I get "Rendering R Markdown documents requires an updated version of the markdown package". With the option of installing it.

**Comment by ttimbers** [comment]
Yes! I and my colleagues at UBC MDS have this exact issue today!

**Comment by ttimbers** [comment]
This issue persists even if I have a `DESCRIPTION` file like so to try to capture `rmarkdown` explicitly as a dependency:

```
Type: project
Description: worksheet1
Depends:
    rmarkdown (>= 2.25)

```

and I can see I have it in the lockfile:

```
"rmarkdown": {
      "Package": "rmarkdown",
      "Version": "2.25",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R",
        "bslib",
        "evaluate",
        "fontawesome",
        "htmltools",
        "jquerylib",
        "jsonlite",
        "knitr",
        "methods",
        "stringr",
        "tinytex",
        "tools",
        "utils",
        "xfun",
        "yaml"
      ]
```

**Comment by eliocamp** [comment]
> This issue persists even if I have a `DESCRIPTION` file like the one shown below to try to capture `rmarkdown` explicitly as a dependency:

Note that the dependency in question is the markdown package, not the rmarkdown package (yes, the names are very confusing 😖)

**Comment by ttimbers** [comment]
Right!!! Also, this seems to actually be an IDE issue, as running `rmarkdown::render()` from R not in RStudio (in R launched in the terminal for example) doesn't have this error...

**Comment by ttimbers** [comment]
I think this is the underlying issue? 

https://github.com/rstudio/rstudio/issues/9861

Thanks to @chendaniely for help diagnosing this!

**Comment by eliocamp** [comment]
> I think this is the underlying issue?
> 
> [rstudio/rstudio#9861](https://github.com/rstudio/rstudio/issues/9861)
> 
> Thanks to @chendaniely for help diagnosing this!

Ah, excellent. I'll close this issue, then.

**Comment by ttimbers** [comment]
A fix is to include a `DESCRIPTION` file with:

```
Type: project
Description: project_title
Depends:
    markdown (>= 1.9.0)

```

and then run `renv::install()` and then `renv::snapshot()`

Then the knit button issue is not there when you share the environment and it is restored.

**Comment by eliocamp** [comment]
Just for posterity and anyone reaching this issue after searching for the error, if your project doesn't use a DESCRIPTION file, you can create a `_dependencies.R` file with `library(markdown)` to make renv add markdown as a dependency ([as per renv documentation](https://rstudio.github.io/renv/reference/dependencies.html#missing-dependencies))

**Comment by chendaniely** [comment]
@eliocamp : you should... :+1: that issue :wink:
Glad we all fixed the root cause!
