### ISSUE TITLE
question on renv 0.12.5 using default user library as local package source

### ISSUE THREAD

**Issue by brianrepko** [rstudio/renv#1730]
I have a situation where two users are trying to both do a renv::restore(clean=TRUE) having wiped out their renv cache and doing this in a fresh git clone. For one user, their renv::restore works and all the lines say "OK [built from source]" but for the other user, they have occasional lines of "OK [copied local binary]" and end up with weird Rcpp linking issues.

Details are lme4@1.1-25 which has a copied local binary of minqa@1.2.4 and ends up with the error of 

function 'Rcpp_precious_remove' not provided by package 'Rcpp'

which it is not in Rcpp@1.0.5

Literally everything _SEEMS_ the same for these two users - except however their DEFAULT library which would be under ~/R/x86_64-pc-linux-gnu-library/3.6/

I'm wondering if potentially (based on the comments on https://github.com/rstudio/renv/issues/636) if potentially renv is finding a compatible (meaning package+version) if minqa there for one user and not the other and for one it copies it over and for the other it builds from source.

That is, does renv 0.12.5 make use of the default user library?

**Comment by brianrepko** [comment]
Duplicated - default 3.6 library has Rcpp 1.0.11 and minqa 1.2.4 and renv.lock has Rcpp 1.0.5 and minqa 1.2.4

**Comment by brianrepko** [comment]
I see that the next release has the `install.shortcuts = FALSE` configuration option so probably nothing to fix here other than making it clear how the cache gets populated by default and options around that.

**Comment by kevinushey** [comment]
Yep, I think you found it -- `renv` tries to re-use packages installed in the default library paths if possible during `init()`; this can be disabled if appropriate via `options(renv.config.install.shortcuts = FALSE)`.

**Comment by brianrepko** [comment]
Thanks @kevinushey - we tested on 0.12.5 (which doesn't have that config option yet) by moving the default library out of the way and it worked. When we upgrade (soon!) then we will set this option in the project's .Rprofile for everyone.
