### ISSUE TITLE
Installation paths not writeable in sandbox dir

### ISSUE THREAD

**Issue by rdavison** [rstudio/renv#1734]
Hi everyone,

I am a professional developer, but a beginner to R, and I am confused about an error/warning message that I'm seeing when installing a package through `renv` in `RStudio`.

Essentially what I have done so far is:

1. Create a new project
2. Checked the button to create the project using renv
3. Ran the following code in the console to install a Bioconductor package:

```R
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("OmnipathR")
```

It seems the package installed correctly because I was able to run
```R
library(OmnipathR)
```

However, the logs at the end of the installation mention a local cache directory not being writeable.

```R
* installing *source* package ‘OmnipathR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (OmnipathR)

The downloaded source packages are in
	‘/tmp/RtmpHebTEz/downloaded_packages’
Installation paths not writeable, unable to update packages
  path: /home/richard/.cache/R/renv/sandbox/R-4.3/x86_64-pc-linux-gnu/9a444a72
  packages:
    boot, foreign, lattice, Matrix, nlme, rpart, spatial, survival
```

Why should it be the case that this cache directory be not writeable?

**Comment by kevinushey** [comment]
That is the sandbox; it contains "base" and "recommended" R packages which should not be updated. This seems more like a bug in BiocManager to me; it should not be trying to update packages in the default library paths. (If it wants to update packages, it should install new versions of those into the user library path instead.)
