### ISSUE TITLE
[BUG] `renv::restore()` fails under v1.0.3 but is successful using v0.17.3

### ISSUE THREAD

**Issue by campbead** [rstudio/renv#1741]
I am running `renv::restore()` as part of the following `docker_build` command:

`docker build -f Dockerfile_base --progress=plain -t golem.test.project_base .`

where `Dockerfile_base` is:

```
FROM rocker/verse:4.2.2
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock renv.lock
RUN R -e 'renv::restore()'
```
this results in the following error:

<img width="691" alt="278238375-e91d6bc8-d5e0-403f-b634-39e212c01812" src="https://github.com/rstudio/renv/assets/2994053/2edc33bb-8236-476a-9ec7-7436fec623f6">

I have attempted fix by changing `Dockerfile_base` to force an install of renv version 0.17.3 to:
```
FROM rocker/verse:4.2.2
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_version("renv", version = "0.17.3")'
COPY renv.lock renv.lock
RUN R -e 'renv::restore()'
```
which results in a successful build when using the `docker build` command.

I believe this might relate to [this bug](https://github.com/r-lib/pkgdepends/issues/330) and is affecting [golem package](https://github.com/ThinkR-open/dockerfiler/issues/66) upstream.

I have attached my `renv.lock` file as [renv.lock.txt](https://github.com/rstudio/renv/files/13183016/renv.lock.txt) so that i can upload it here.

Thank you for any help.  Please let me know if any addition information is needed.

**Comment by kevinushey** [comment]
Thanks for the bug report, and sorry for the delay. It seems like this issue may be resolved with pak 0.7.0; I'm no longer able to reproduce. Are you still seeing this issue?

**Comment by campbead** [comment]
I can confirm that I no longer see the issue.  I will close the ticket now.

-Adam

**Comment by kevinushey** [comment]
Awesome news; thanks for confirming!
