### ISSUE TITLE
renv shims and deactivate

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#175]
@kevinushey - I've noticed that when you deactivate renv in a project that the install.packages is still the renv version. 

Is this intentional? I would think renv would basically be off and you'd be in your regular r state after deactivating.

Regards,

Adam

**Comment by kevinushey** [comment]
Good point; I think you're right that we should only have the shims active when a project is active.

**Comment by kevinushey** [comment]
Implemented with https://github.com/rstudio/renv/commit/6106c19c4780e2108ac37488d8dd093435afe219.
