### ISSUE TITLE
"Do you want to proceed" prompt for installing BiocManager after activation doesn't render properly in Rstudio

### ISSUE THREAD

**Issue by dvg-p4** [rstudio/renv#1754]
## Steps to reproduce
1. Create a directory, e.g. `renv_bioc_reprex`
2. Create the following files in that directory:
   `renv_bioc_reprex/script.R`:
   ```
   x <- data.frame(x=1:5,
                   y=factor(letters[1:5], levels=letters[1:8]),
                row.names=letters[1:5])
   y <- data.frame(z=3:7,
                   y=factor(letters[3:7], levels=letters[1:8]),
                   row.names=letters[3:7])
   BiocGenerics::combine(x,y)  
   ```
   `renv.lock`:
   ```
   {
     "R": {
       "Version": "4.2.2",
       "Repositories": [
         {
           "Name": "CRAN",
           "URL": "https://packagemanager.posit.co/cran/latest"
         }
       ]
     },
     "Bioconductor": {
       "Version": "3.16"
     },
     "Packages": {
       "BiocGenerics": {
         "Package": "BiocGenerics",
         "Version": "0.44.0",
         "Source": "Bioconductor",
         "Requirements": [
           "R",
           "graphics",
           "methods",
           "stats",
           "utils"
         ],
         "Hash": "0de19224c2cd94f48fbc0d0bc663ce3b"
       },
       "BiocManager": {
         "Package": "BiocManager",
         "Version": "1.30.19",
         "Source": "Repository",
         "Repository": "CRAN",
         "Requirements": [
           "utils"
         ],
         "Hash": "726b3bc83ff8e0c35c7efdb74a462b0d"
       },
       "BiocVersion": {
         "Package": "BiocVersion",
         "Version": "3.16.0",
         "Source": "Bioconductor",
         "Requirements": [
           "R"
         ],
         "Hash": "44c5824508b9a10e52dbb505c34fa880"
       },
       "renv": {
         "Package": "renv",
         "Version": "1.0.3",
         "Source": "Repository",
         "Repository": "CRAN",
         "Requirements": [
           "utils"
         ],
         "Hash": "41b847654f567341725473431dd0d5ab"
       }
     }
   }
   ```
   (this was generated by simply running `renv::init()`, but the bug happens when activating, not init-ing)
3. Create and open an Rstudio project in that directory (if in a setup affected by https://github.com/rstudio/rstudio/issues/13922)
4. In Rstudio, run `renv::activate()`
5. See expected messages that BiocManager will be installed, followed by what looks like the standard command prompt.
6. Attempt to run any R command--it turns out that a "Y" or "N" is expected, but the prompt for such only appears *after* trying to run a command. (See screenshots below.) 

### System details
- MacOS Sonoma 14.0 (23A344)
- RStudio Desktop 2023.09.1+494
- renv 1.0.3
- R 4.2.3 or 4.3.1

<img width="777" alt="image" src="https://github.com/rstudio/renv/assets/106110177/f2dfede4-f125-49a7-a7f2-a1845193ddf9">
<img width="776" alt="image" src="https://github.com/rstudio/renv/assets/106110177/8a1c281a-1f18-42db-84fb-ac8d87c14dd6">

### System details
- Linux CentOS 7
- RStudio Server 2022.12.0 build 353
- renv 1.0.3
- R 4.2.2

![renv-bug-1](https://github.com/rstudio/renv/assets/106110177/c3264d57-7c8c-4682-bdce-a86bd1ede7c2)
![renv-bug-2](https://github.com/rstudio/renv/assets/106110177/94c8a2a8-b343-4048-a518-6f1baf8de0bb)

**Comment by kevinushey** [comment]
Can you also please confirm what version of `renv` you're using? Do you have a standalone reproducible example?

**Comment by dvg-p4** [comment]
Busy day today, sorry--will check back later this week and see if I can get a reprex for you.

**Comment by dvg-p4** [comment]
Hmm, seems this only reproduces in RStudio--the prompt comes up correctly on the command line. Unfortunately the version of RStudio Server on our server is about a year old (2022.12.0), so I don't know if this will still be present in a later version. Also, in trying to reproduce locally on my macbook, I ran into a different RStudio bug--it isn't sourcing the local .Rprofile so `renv::activate()` isn't working at all.

**Comment by dvg-p4** [comment]
Ah, can repro locally if I make a project in that directory! Alright, this should be enough for you to work with--I'll edit the reprex into the top-level.

**Comment by dvg-p4** [comment]
There you go @kevinushey

**Comment by kevinushey** [comment]
Awesome, thank you! I've now reproduced the issue locally as well -- I'll take a look.

**Comment by kevinushey** [comment]
Should be fixed via https://github.com/rstudio/renv/commit/e2708dffc9b053aa2b265c4da57d454ba50631b7; thanks again for reporting!
