### ISSUE TITLE
transfer lock.file in another computer to recreate renv

### ISSUE THREAD

**Issue by yamihn** [rstudio/renv#1757]
I'm sorry, once I've created renv in my project and I captured libraries in my lock.file, how can I transfer it into a new computer restoring the installed libraries? I'm losing some points?

**Comment by kevinushey** [comment]
This is discussed in https://rstudio.github.io/renv/articles/renv.html#collaboration -- does that documentation have what you need?

**Comment by yamihn** [comment]
I found this part of description that I Need, but It Is still not clear to me. i have to send only the lock.file to the other machine in a specific folder and start a new project? This Is Just what I Need the lock.file? And so, I Will Need Just to run renv::init() and renv::restore() to download the libraries that I Need?
I would be grateful if you provide me a small example.
Thank you


```
One of the reasons to use renv is to make it easier to share your code in such a way that everyone gets exactly the same package versions as you. As above, you’ll start by calling [renv::init()](https://rstudio.github.io/renv/reference/init.html). You’ll then need to commit renv.lock, .Rprofile, renv/settings.json and renv/activate.R to version control, ensuring that others can recreate your project environment. If you’re using git, this is particularly simple because renv will create a .gitignore for you, and you can just commit all suggested files3.

Now when one of your collaborators opens this project, renv will automatically bootstrap itself, downloading and installing the appropriate version of renv. It will also ask them if they want to download and install all the packages it needs by running [renv::restore()](https://rstudio.github.io/renv/reference/restore.html).



```

**Comment by ishwarvh** [comment]
Replace the new renv.lock file in the new renv with the one that has all the package information (i.e. old renc.lock file)

Then restore the old lockfile in the new renv using:
```
renv::restore(lockfile="renv.lock")
```

**Comment by yamihn** [comment]
thank you!
