### ISSUE TITLE
renv_update_find_github() warning message recommends a deprecated usethis function

### ISSUE THREAD

**Issue by remlapmot** [rstudio/renv#1763]
I notice that a warning message in `renv_update_find_github()` in `R/update.R` recommends a deprecated function in the usethis package (I think it was deprecated in version 2.0.0 of usethis, the current version is 2.2.2).

https://github.com/rstudio/renv/blob/62695b4cae0eb73e774ab9e0ad2ede0d899157db/R/update.R#L81

I believe that `usethis::create_github_token()` is the up-to-date function.

**Comment by kevinushey** [comment]
Thanks! Fixed on main now.

**Comment by remlapmot** [comment]
Thanks
