### ISSUE TITLE
Add mc-stan as known source?

### ISSUE THREAD

**Issue by emstruong** [rstudio/renv#1765]
Hi,

When running 

```r
# From https://mc-stan.org/cmdstanr/articles/cmdstanr.html
install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

I get the following from `renv` in my R-Studio Project 

```
The following package(s) were installed from an unknown source:

- cmdstanr [0.6.1]

renv may be unable to restore these packages in the future.
Consider reinstalling these packages from a known source (e.g. CRAN).


See ?renv::status() for advice on resolving these issues.
```

Is it possible to add `mc-stan` as a known source?

**Comment by kevinushey** [comment]
The simplest solution would be to ensure the `repos` option is set globally, e.g.

```
options(repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
install.packages("cmdstanr")
renv::snapshot()
```

It might be helpful if `renv` encoded the repository source for downloaded packages, though -- conforming with what `pak` does.

**Comment by kevinushey** [comment]
This has now been implemented in the development version of `renv`. If you install a package within an `renv` project using the above code, you'll later get a lockfile entry like the following:

```
    "cmdstanr": {
      "Package": "cmdstanr",
      "Version": "0.6.1",
      "Source": "Repository",
      "Repository": "https://mc-stan.org/r-packages",
      "Requirements": [ <...> ],
      "Hash": "56a08cc593fc5ddc263342209e5d1e14"
    },
```

Note that this repository URL is generated from the package's DESCRIPTION file; `renv` now inserts these fields upon install:

```
RemoteType: standard
RemotePkgRef: cmdstanr
RemoteRef: cmdstanr
RemoteRepos: https://mc-stan.org/r-packages
RemoteReposName: https://mc-stan.org/r-packages/
RemotePkgPlatform: source
RemoteSha: 0.6.1
```

which also matches the behavior of `pak`.
