### ISSUE TITLE
renv absolute and relative paths

### ISSUE THREAD

**Issue by andzandz11** [rstudio/renv#1775]
I foolishly set the project path inside of a project using relative paths and nothing happened. 
I would have expected an error because that lockfile does not exist, no?

```

R version 4.3.0 (2023-04-21 ucrt) -- "Already Tomorrow"
[...]
- Project 'C:/R/refdat/resources/renv_windows' loaded. [renv 1.0.3]

> renv::snapshot(project="./resources/renv_windows")
- The lockfile is already up to date.
```

**Comment by kevinushey** [comment]
Presumedly, the issue you're seeing here is because that `resources/renv_windows` sub-directory does in fact exist? I see an error if I try a similar example, e.g.

```
>   snapshot(project = "./oops")
Error in normalizePath(path, winslash, mustWork) : 
  path[1]="/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/RtmpIEHOOi/renv-test-59cf381dd369/./oops": No such file or directory
```
