### ISSUE TITLE
Cannot compile C++ in R

### ISSUE THREAD

**Issue by KimmDD** [rstudio/renv#1777]
Hi, I used the Mac Air with an Apple M2 Chip, and I used Ventura 13.5.1  for macOS right now. I face the issue when R studio tries to compile the C++ file, and the error is below:
https://gist.github.com/KimmDD/9dd25cb6b273d0b576995bf3008d7e49
Can anyone help me with this?

**Comment by kevinushey** [comment]
Given this output:

```
using C compiler: ‘Apple clang version 12.0.0 (clang-1200.0.32.2)’
using SDK: ‘MacOSX10.15.sdk’
```

my best guess is that you need to update or reinstall command line tools. The simplest way to do this would be to do something like:

```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```
