### ISSUE TITLE
system2 warning when calling renv 1.0.2 load on emr

### ISSUE THREAD

**Issue by ssefick** [rstudio/renv#1778]
Good morning,

I am unable to provide a reprex.

R 4.3.1 and renv 1.0.2 on AWS emr 6.4.0.

When calling renv:load I am getting a warring at the R interpreter of a system2 error. There is no command passed along except for what looks like a default call to system2.

This does have a python venv recorded in the lock file that is being pushed pulled from ec-2 to emr (work around for difficulties related to old python on emr).

2 things highlight my possible misunderstandings.

1. The warning does nothing at an interactive session, but throws an error that halts execution when run as a batch script (Rscript).

2. Is renv trying to call a subshell to a command that doesn't exist?

Thanks for any help correcting my understanding of renv etc.

**Comment by kevinushey** [comment]
Can you try calling something like:

```
trace(system2, quote({
  print(utils::ls.str())
  print(rlang::trace_back())
}))
renv::load()
```

and let us know what you see?
