### ISSUE TITLE
Convert old lockfile format to json

### ISSUE THREAD

**Issue by jaredlander** [rstudio/renv#178]
I've been experimenting with `{renv}` since about version 0.4. The lockfile was written in a config file format like so.

```
[renv]
Version=0.7.0-24

[R]
Version=3.6.1
Repositories=
	CRAN=https://cran.rstudio.com/

[R/Package/BH]
Package=BH
Version=1.69.0-1
Source=CRAN
Hash=0fde015f5153e51df44981da0767f522
```

I noticed when using newer versions of `{renv}` starting from scratch, it uses json.

```json
{
  "renv": {
    "Version": "0.7.0-21"
  },
  "R": {
    "Version": "3.6.1",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Packages": {
    "AmesHousing": {
      "Package": "AmesHousing",
      "Version": "0.0.3",
      "Source": "CRAN",
      "Hash": "6e3d492f96fc477234bdbc5e1338b3c4"
    },
    "BH": {
      "Package": "BH",
      "Version": "1.69.0-1",
      "Source": "CRAN",
      "Hash": "0fde015f5153e51df44981da0767f522"
    }
}
}
```

The json lockfile is easier (for me) to parse from the command line, plus it seems to be the new default, so I want everything to be consistent. I tried looking at some of the non-exposed functions but didn't find a safe-seeming way to change formats. Is there a quick way to convert the old lockfiles to the new json format?

**Comment by kevinushey** [comment]
I think the simplest way right now would be to upgrade renv in the project (call `renv::upgrade()`), and then use:

```
lockfile <- renv:::renv_lockfile_read("renv.lock")
renv:::renv_lockfile_write(lockfile, "renv.lock")
```

The lockfile reader should understand how to read the old formats if needed, and re-writing the lockfile will force it to be written using the new JSON format.

**Comment by kevinushey** [comment]
The lockfile should also get automatically updated if you call `renv::snapshot()` with a newer version of renv (assuming that the lockfile has indeed changed)

**Comment by jaredlander** [comment]
I had a feeling it would as easy as `renv:::renv_lockfile_read()` and `renv:::renv_lockfile_write()` but wasn't sure about the functions.

And it turns out creating a snapshot works as you say. I previously tried creating a new snapshot without changing the lockfile and nothing happened, but after making a package change `renv::snapshot()` does indeed update the file to json.

Thanks!
