### ISSUE TITLE
`renv` does not respect enterprise or user repository configuration

### ISSUE THREAD

**Issue by guslipkin** [rstudio/renv#1782]
## Description

Depending on how `renv` is started in a project, it overrides the repository configuration in different ways by modifying the named `CRAN` repository and/or removing all other configured repositories. This happens in both an enterprise environment where a `repos.conf` or `rsession.conf` file is used as well as a local environment where the Package Management settings pane in RStudio is used. The problem appears in all tested versions of R on a variety of operating systems. Only renv 1.0.3 was tested. Below is documentation of the problem across two different enterprise environments. While testing, it was determined that using `renv` inside of a `reprex::reprex()` call did not reproduce these results.

### Checking Default Repositories

```{bash}
cat /etc/rstudio/rsession.conf
#> # R Session Configuration File
#> # repository
#> r-cran-repos=https://rspm.example.com/prod-cran/__linux__/jammy/latest/
```

```{r}
options("repos")
#> $repos
#>                                       CRAN 
#> "https://rspm.example.com/prod-cran/latest/" 
#>                                     Example 
#>  "https://rspm.example.com/prod-cran/latest" 
#> attr(,"RStudio")
#> [1] TRUE
```

### Checking R Version

```{r}
R.version
#>                _                           
#> platform       x86_64-pc-linux-gnu         
#> arch           x86_64                      
#> os             linux-gnu                   
#> system         x86_64, linux-gnu           
#> status                                     
#> major          4                           
#> minor          2.3                         
#> year           2023                        
#> month          03                          
#> day            15                          
#> svn rev        83980                       
#> language       R                           
#> version.string R version 4.2.3 (2023-03-15)
#> nickname       Shortstop Beagle
```

### Checking `renv` Global Install

```{r}
packageVersion("renv")
#> [1] '1.0.3'
```

#### No `renv`

```{r}
renv::status()
#> This project does not appear to be using renv.
#> Use `renv::init()` to initialize the project.
options('repos')
#> $repos
#>                                       CRAN 
#> "https://rspm.example.com/prod-cran/latest/" 
#>                                     Example 
#>  "https://rspm.example.com/prod-cran/latest" 
#> attr(,"RStudio")
#> [1] TRUE
```

#### `renv` Through Project Checkbox

```{r}
renv::status()
#> No issues found -- the project is in a consistent state.
options('repos')
#> $repos
#>                                                          CRAN 
#> "https://packagemanager.posit.co/cran/__linux__/jammy/latest" 
#>                                                        Example 
#>     "https://rspm.example.com/prod-cran/__linux__/jammy/latest" 
```

#### `renv::activate()`

```{r}
renv::activate()
#> Restarting R session...
#> - Project '~/renv-test/renv-activate-snapshot' loaded. [renv 1.0.3]
#> - The project is out-of-sync -- use `renv::status()` for details.
options('repos')
#> $repos
#>                          CRAN 
#> "https://cloud.r-project.org" 
```

#### `renv::init()`

```{r}
renv::init()
#> The following package(s) will be updated in the lockfile:
#> # RSPM -----------------------------------------------------------------------
#> - renv   [* -> 1.0.3]
#> The version of R recorded in the lockfile will be updated:
#> - R      [* -> 4.2.3]
#> - Lockfile written to "~/renv-test/renv-init/renv.lock".
#> Restarting R session...
#> - Project '~/renv-test/renv-init' loaded. [renv 1.0.3]
options('repos')
#> $repos
#>                                                          CRAN 
#> "https://packagemanager.posit.co/cran/__linux__/jammy/latest" 
#>                                                        Example 
#>     "https://rspm.example.com/prod-cran/__linux__/jammy/latest" 
```

#### `renv::activate()`, `renv::snapshot()`, `renv::init()` and Discard/Reinitialize

`renv::snapshot()` does not change the repositories, but is necessary to reproduce further steps.

```{r}
renv::activate()
#> Restarting R session...
#> - Project '~/renv-test/renv-activate-snapshot-init' loaded. [renv 1.0.3]
#> - The project is out-of-sync -- use `renv::status()` for details.
renv::snapshot()
#> The following package(s) will be updated in the lockfile:
#> # RSPM -----------------------------------------------------------------------
#> - renv   [* -> 1.0.3]
#> The version of R recorded in the lockfile will be updated:
#> - R      [* -> 4.2.3]
#> - Lockfile written to "~/renv-test/renv-activate-snapshot-init/renv.lock".
renv::init()
#> This project already has a lockfile. What would you like to do? 
#> 1: Restore the project from the lockfile.
#> 2: Discard the lockfile and re-initialize the project.
#> 3: Activate the project without snapshotting or installing any packages.
#> 4: Abort project initialization.
#> Selection: 2
#> - Lockfile written to "~/renv-test/renv-activate-snapshot-init/renv.lock".
#> Restarting R session...
#> - Project '~/renv-test/renv-activate-snapshot-init' loaded. [renv 1.0.3]
options('repos')
#> $repos
#>                                                          CRAN 
#> "https://packagemanager.posit.co/cran/__linux__/jammy/latest" 
```

#### `renv::init()`, `renv::init()` and Discard/Reinitialize

```{r}
renv::init()
#> The following package(s) will be updated in the lockfile:
#> # RSPM -----------------------------------------------------------------------
#> - renv   [* -> 1.0.3]
#> The version of R recorded in the lockfile will be updated:
#> - R      [* -> 4.2.3]
#> - Lockfile written to "~/renv-test/renv-init-init/renv.lock".
#> Restarting R session...
#> - Project '~/renv-test/renv-init-init' loaded. [renv 1.0.3]
renv::init()
#> This project already has a lockfile. What would you like to do? 
#> 1: Restore the project from the lockfile.
#> 2: Discard the lockfile and re-initialize the project.
#> 3: Activate the project without snapshotting or installing any packages.
#> 4: Abort project initialization.
#> Selection: 2
#> - The lockfile is already up to date.
#> Restarting R session...
#> - Project '~/renv-test/renv-init-init' loaded. [renv 1.0.3]
options('repos')
#> $repos
#>                                                          CRAN 
#> "https://packagemanager.posit.co/cran/__linux__/jammy/latest" 
#>                                                        Example 
#>     "https://rspm.example.com/prod-cran/__linux__/jammy/latest" 
```

### Checking Default Repositories

```{r}
options("repos")
#> $repos
#>                                      CRAN 
#>               "https://cran.rstudio.com/" 
#>                                    Example 
#> "https://rspm.example.com/prod-cran/latest" 
#> attr(,"RStudio")
#> [1] TRUE
```

### Checking R Version

```{r}
R.version
#>                _                           
#> platform       x86_64-apple-darwin20       
#> arch           x86_64                      
#> os             darwin20                    
#> system         x86_64, darwin20            
#> status                                     
#> major          4                           
#> minor          3.2                         
#> year           2023                        
#> month          10                          
#> day            31                          
#> svn rev        85441                       
#> language       R                           
#> version.string R version 4.3.2 (2023-10-31)
#> nickname       Eye Holes
```

### Checking `renv` Global Install

```{r}
packageVersion("renv")
#> [1] '1.0.3'
```

#### No `renv`

```{r}
renv::status()
#> This project does not appear to be using renv.
#> Use `renv::init()` to initialize the project.
options('repos')
#> $repos
#>                                      CRAN 
#>               "https://cran.rstudio.com/" 
#>                                    Example 
#> "https://rspm.example.com/prod-cran/latest" 
#> attr(,"RStudio")
#> [1] TRUE
```

#### `renv` Through Project Checkbox

```{r}
renv::status()
#> No issues found -- the project is in a consistent state.
options('repos')
#> $repos
#>                                          CRAN 
#> "https://packagemanager.posit.co/cran/latest" 
#>                                        Example 
#>     "https://rspm.example.com/prod-cran/latest" 
```

#### `renv::activate()`

```{r}
renv::activate()
#> Restarting R session...
#> - Project '~/Documents/renv-test/renv-activate' loaded. [renv 1.0.3]
#> - The project is out-of-sync -- use `renv::status()` for details.
options('repos')
#> $repos
#>                          CRAN 
#> "https://cloud.r-project.org" 
```

#### `renv::init()`

```{r}
renv::init()
#> The following package(s) will be updated in the lockfile:
#> # CRAN ------------------------------------------------------------
#> - renv   [* -> 1.0.3]
#> The version of R recorded in the lockfile will be updated:
#> - R      [* -> 4.3.2]
#> - Lockfile written to "~/Documents/renv-test/renv-init/renv.lock".
#> Restarting R session...
#> - Project '~/Documents/renv-test/renv-init' loaded. [renv 1.0.3]
options('repos')
#> $repos
#>                                          CRAN 
#> "https://packagemanager.posit.co/cran/latest" 
#>                                        Example 
#>     "https://rspm.example.com/prod-cran/latest" 
```

#### `renv::activate()`, `renv::snapshot()`, `renv::init()` and Discard/Reinitialize

`renv::snapshot()` does not change the repositories, but is necessary to reproduce further steps.

```{r}
renv::activate()
#> Restarting R session...
#> - Project '~/Documents/renv-test/renv-activate-snapshot-init' loaded. [renv 1.0.3]
#> - The project is out-of-sync -- use `renv::status()` for details.
renv::snapshot()
#> The following package(s) will be updated in the lockfile:
#> # CRAN -----------------------------------------------------------------------
#> - renv   [* -> 1.0.3]
#> The version of R recorded in the lockfile will be updated:
#> - R      [* -> 4.3.2]
#> - Lockfile written to "~/Documents/renv-test/renv-activate-snapshot-init/renv.lock".
renv::init()
#> This project already has a lockfile. What would you like to do? 
#> 1: Restore the project from the lockfile.
#> 2: Discard the lockfile and re-initialize the project.
#> 3: Activate the project without snapshotting or installing any packages.
#> 4: Abort project initialization.
#> Selection: 2
#> - Lockfile written to "~/Documents/renv-test/renv-activate-snapshot-init/renv.lock".
#> Restarting R session...
#> - Project '~/Documents/renv-test/renv-activate-snapshot-init' loaded. [renv 1.0.3]
options('repos')
#> $repos
#>                                          CRAN 
#> "https://packagemanager.posit.co/cran/latest" 
```

#### `renv::init()`, `renv::init()` and Discard/Reinitialize

```{r}
renv::init()
#> The following package(s) will be updated in the lockfile:
#> # CRAN -----------------------------------------------------------------------
#> - renv   [* -> 1.0.3]
#> The version of R recorded in the lockfile will be updated:
#> - R      [* -> 4.3.2]
#> - Lockfile written to "~/Documents/renv-test/renv-init-init/renv.lock".
#> Restarting R session...
#> - Project '~/Documents/renv-test/renv-init-init' loaded. [renv 1.0.3]
renv::init()
#> This project already has a lockfile. What would you like to do? 
#> 1: Restore the project from the lockfile.
#> 2: Discard the lockfile and re-initialize the project.
#> 3: Activate the project without snapshotting or installing any packages.
#> 4: Abort project initialization.
#> Selection: 2
#> - The lockfile is already up to date.
#> Restarting R session...
#> - Project '~/Documents/renv-test/renv-init-init' loaded. [renv 1.0.3]
options('repos')
#> $repos
#>                                          CRAN 
#> "https://packagemanager.posit.co/cran/latest" 
#>                                        Example 
#>     "https://rspm.example.com/prod-cran/latest" 
```

**Comment by kevinushey** [comment]
I think there's two different things happening here:

1. renv is replacing the binary-specific repository URL with the base source repository URL;
2. renv is sometimes replacing the default CRAN URL with the Posit mirror.

For (1), I believe this setting is related: https://rstudio.github.io/renv/reference/settings.html#ppm-enabled

The intention here is that the lockfile should normally store a platform-agnostic repository URL, which can then later be transformed into an appropriate binary URL as appropriate for the current platform being used. If you'd prefer to disable this repository URL transformation, you can change that setting to FALSE for the project.

For (2), I am less certain, but that's most likely happening in RStudio as opposed to `renv`, since the only thing `renv` should be doing here is transforming `@CRAN@` repository URLs into the default cloud repository URL, e.g. https://github.com/rstudio/renv/blob/de3af61f7e1d69f0f8320ec7251a7340e740f233/R/repos.R#L7-L9.

Note that `renv` will also read and apply the repositories set in the project lockfile on load, so if those repositories will take precedence over any other repository configuration in your R / RStudio installation.

**Comment by guslipkin** [comment]
You've given me a bit to think about.

For the first case, I don't see changing the binary-specific URL to the base URL as an issue as ultimately they resolve to the same Package Manager URL.

The second case I'm a bit confused about the intended behavior. Does `renv` always override the `@CRAN@` repository URL? What options does that leave enterprise users who have an internal Package Manager setup as their default CRAN repository?

In addition, the behavior seems inconsistent depending on how `renv` is used to create the lock file. For example, let's say I have a Package Manager at `rspm.example.com` and set that as my default CRAN repository in `repos.conf`. I then initialize a new project through the Workbench GUI and check the box to use `renv`, my default CRAN repository is replaced with `packagemanager.posit.co`. Alternatively, if I start the new project then call `renv::activate()`, my default CRAN repository then becomes `cloud.r-project.org` as you suggest. As demonstrated in my initial report, activating `renv` in different ways seems to result in a variety of different effects on not only the default CRAN repository, but also any other additional configured repositories, including removing them entirely.

**Comment by kevinushey** [comment]
> The second case I'm a bit confused about the intended behavior. Does renv always override the @CRAN@ repository URL? What options does that leave enterprise users who have an internal Package Manager setup as their default CRAN repository?

Just to clarify, `@CRAN@` is a placeholder used by R for the `repos` option when no repository has been set; e.g.

```
$ R --vanilla -s -e 'getOption("repos")'
    CRAN
"@CRAN@"
```

so I just mean that `renv` only ever tries to automatically replace that placeholder; if the `repos` option has already been set via some other mechanism, `renv` shouldn't touch it. If `renv` is changing an explicitly-set repository beyond just transforming source <-> binary PPM URLs, that's certainly a bug.

> I then initialize a new project through the Workbench GUI and check the box to use renv, my default CRAN repository is replaced with packagemanager.posit.co.

I wonder if that's happening here:

https://github.com/rstudio/renv/blob/de3af61f7e1d69f0f8320ec7251a7340e740f233/R/init.R#L309-L330

Just to explain the code intention, if the user calls `renv::init()` but appears to be using the "default" repositories, we opt the user into using the public Posit Package Manager instance instead. This is done by checking for an "RStudio" attribute on the reposiotry, which would happen if RStudio has set the repository itself (as opposed to, say, a `.Rprofile`). Given what you're describing, we are being too aggressive here.

**Comment by guslipkin** [comment]
Thank you for the clarification on `@CRAN@`. I've never seen the default before.

Based on my initial findings, I'm not sure that's the only place the repositories are being effected. It looks like `renv::activate()` leads to slightly different behavior. I'm more than happy to give more details as needed.

**Comment by kevinushey** [comment]
I believe

**Comment by kevinushey** [comment]
I believe the issues related to `renv::init()` should now be resolved. Can you confirm if this also resolves the issues you had seen with `renv::activate()`?

**Comment by kevinushey** [comment]
Sorry, but just because there's a lot going on in the original post, can you emphasize the issues that you're still seeing?

In particular, it would be helpful to see:

- The output of `getOption("repos")`,
- The output of `str(renv:::renv_lockfile_read("renv.lock")$R)`

Note that `renv` should be setting the R repositories on startup, if there are repositories recorded in the lockfile. This should take precedence over any specific configuration set for the R session / RStudio itself.

In addition, can you confirm if the correct repositories are set after restarting the R session?

**Comment by guslipkin** [comment]
Each of the sets in the original report were mostly to illustrate the variety of circumstances under which I could reproduce the error. For simplicity, I just reproduced it using `renv::activate()` and `renv::snapshot()` for initialization in a brand new project. It looks like `renv::init()` is working as expected.

```
packageVersion('renv')
#> [1] '1.0.3.9000'
getOption('repos')
#>  CRAN 
#> "https://rspm.example.com/prod-cran/latest" 
renv::activate()
#> Restarting R session...
#> - Project '~/renv-test/renv-activate2' loaded. [renv 1.0.3.9000; sha: 6b13e12]
#> - The project is out-of-sync -- use `renv::status()` for details.
renv::snapshot()
getOption('repos')
#> CRAN
#> 'https://cloud.r-project.org'
str(renv:::renv_lockfile_read('renv.lock')$R)
#> List of 2
#> $ Version     : chr "4.3.0"
#> $ Repositories:List of 1
#>   ..$ CRAN: chr "https://cloud.r-project.org"
```

**Comment by kevinushey** [comment]
Thanks again -- I'll try to get this as part of a CRAN release in the coming weeks, as I'd like to get a new release of `renv` out in time for the upcoming R 4.4.0 release.
