### ISSUE TITLE
Please Help...Quitting from lines 3-66 

### ISSUE THREAD

**Issue by annwashburn** [rstudio/renv#1786]
67% [unnamed-chunk-1]

processing file: U2_Hwk5_RCode_AndreaWashburn.spin.Rmd

Quitting from lines 3-66 [unnamed-chunk-1] (U2_Hwk5_RCode_AndreaWashburn.spin.Rmd)
                                                                                                            
Error in `contrib.url()`:
! trying to use CRAN without setting a mirror
Backtrace:
 1. utils::install.packages("tidyverse")
 2. utils::contrib.url(repos, "source")
Execution halted

**Comment by kevinushey** [comment]
This doesn't seem to be an `renv`-related issue, but without a reproducible example we cannot know or help more.
