### ISSUE TITLE
renv fails when HTTPUserAgent is improperly set

### ISSUE THREAD

**Issue by arcresu** [rstudio/renv#1787]
I encountered this issue when using the rstudio binary builds of R on Debian unstable, which is not an officially supported platform. As such this is a bit niche and might not be worth addressing.

The result is the equivalent of running `options(HTTPUserAgent = character(0))` (see rstudio/r-builds#196 for background).

In this case, every attempt to run `install()` with renv 1.0.3 fails with:

``` r
options(HTTPUserAgent = character(0))
renv::install("tidyverse")
#> Error in if (!grepl("renv", agent)) {: argument is of length zero
```

<sup>Created on 2024-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is because of this internal function:
https://github.com/rstudio/renv/blob/de3af61f7e1d69f0f8320ec7251a7340e740f233/R/http.R#L2-L5

The fix could be to set `agent` to NULL if it is equal to `character(0)`. However, feel free to close this since it's probably not a likely scenario that others will run into unless they are using the rstudio R binaries on Debian testing or unstable.

**Comment by kevinushey** [comment]
In the places where the user agent is used internally, R seems to expect it to be either NULL or a length one character vector, e.g.

https://github.com/wch/r-source/blob/e13caf6d43653e2b3fbc513bbaf6fdd6ee93b455/src/library/utils/R/readhttp.R#L39-L48

We could make `renv` robust against this, but I think this needs to be changed upstream.
