### ISSUE TITLE
Custom CRAN mirror 

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#179]
@kevinushey - i seem to have started getting some errors on my build pipeline related to CRAN connectivity.

The machine only has CRAN.microsoft.com access whitelisted and I set it with options repos as normal. 

Not sure if some of your recent CRAN commits are overriding this. If so how can I specifically set a CRAN mirror for an renv session?

Cheers,

Adam

**Comment by kevinushey** [comment]
I don't think anything has changed here. You might need to confirm that the R repositories are set as you expect -- what does `getOption("repos")` report in your R session? What repositories are set in your lockfile?

**Comment by kevinushey** [comment]
FWIW the default CRAN repository used before was `cran.rstudio.com`; this has been switched to `cloud.r-project.org` by request of CRAN. However, all the other 'regular' repository machinery should work as normal; that is, setting `options(repos = <...>)` is the way to set the active R repositories.

**Comment by adamrobinson361** [comment]
This was down to CRAN.microsoft.com being down. Apologies!

Adam

**Comment by adamrobinson361** [comment]
Hi Kevin, 

Sorry to re-open this but i'm not sure my issue was solved. My pipeline was mostly taking packrat projects, converting the repo for that and then converting to renv. This route brought the updated repo across. For renv projects with a default repo my pipeline doesn't seem to be working.

Below is an extract of the code we use. Do you think this should work in downloading packages from the set CRAN via renv?

``` r

# If packrat project then convert
if (file.exists("packrat/packrat.lock")) {

	print("")
	print("Converting packrat project to renv")
	print("")

	packrat::repos_set("CRAN" = "https://cran.microsoft.com/")

	packrat::set_lockfile_metadata(repos = c("CRAN" = "https://cran.microsoft.com/"))

	renv::migrate()

}

print("")
print("Restoring renv environment")
print("")

# Restore environment
options(repos = c(CRAN = "https://cran.microsoft.com/")) 
renv::activate()
renv::upgrade()
print(getOption("repos"))
renv::restore()

# Stage 3 - Run run script ------------------------------------------------
print("")
print("Running run.R")
print("")

source('run.R')
```

**Comment by kevinushey** [comment]
It should work, but it would help if you could provide some extra diagnostics. What does `renv.lock` look like after calling `renv::migrate()`?

Note that you can also explicitly provide the required repositories during restore; e.g.

```
renv::restore(repos = c(CRAN = "https://cran.microsoft.com"))
```

and that will override any other repositories set.

It would also be helpful to know what error you're seeing exactly.

**Comment by adamrobinson361** [comment]
Ah sorry I wasn’t clear in my previous post.

The packrat project -> renv migrate -> renv route does work. The resultant lock file in renv will have the repo I set.

It is when the user already has renv set up so it just does the activate, upgrade restore step. I would’ve expected that setting the cran repo before this would mean that the restore step would use that repo. Instead it uses the one listed in the renv.lock.

What you outline below will be a solution for me but I’m just wondering if this is expected behaviour. For packrat I think it would then restore using the set repo

**Comment by kevinushey** [comment]
> It is when the user already has renv set up so it just does the activate, upgrade restore step. I would’ve expected that setting the cran repo before this would mean that the restore step would use that repo. Instead it uses the one listed in the renv.lock.

This is the expected behavior -- the repositories encoded in the lockfile override those in the current session. (This is necessary to support e.g. restoring from a lockfile when `renv` itself is not already active.)

I don't think I've documented this explicitly, though -- I'll make that change.

**Comment by adamrobinson361** [comment]
And is there a way to easily edit the cran in the lock file similar to packrat or is the recommended workflow for restoring on a machine with specific cran mirror access to do as you said above?

**Comment by kevinushey** [comment]
No, not yet at least. I would recommend using the workflow I described above.

**Comment by adamrobinson361** [comment]
Perfect - thanks v much
