### ISSUE TITLE
Undefined `catch` function in `activate.R`

### ISSUE THREAD

**Issue by bentilley** [rstudio/renv#1791]
# Description

Hello 👋 . I've noticed a strange error when trying to bootstrap renv from a custom repo.

When renv attempts to bootstap itself during start up, it first does some checks to determine which repo it should use. I have a custom repo defined in `renv.lock`, and the default CRAN URL doesn't work on our company network. In `activate.R` the `renv_json_read` function references a `catch` function which doesn't seem to be defined at this point. It looks like this function comes from `R/utils.R`, but at this point during the bootstrap, that isn't available.

Consequently, the bootstrap process fails. I'm able to workaround by setting `renv.repos.cran`, so that the code path never touches the undefined `catch`, but it seems like this is a bug that prevents bootstrapping against a non-standard repo defined in the lock file (if you don't have access to CRAN!).

I guess the fix could be to just use a standard `tryCatch` in `activate.R` instead 🤷 ... Actually, I just tried replacing it with `tryCatch(..., error = identity)`, and now it's complaining that the `read` function is also undefined (another one from `R/utils.R`). Would it be sufficient to copy the definition to `activate.R`?

**Comment by kevinushey** [comment]
Thanks for catching that! The `json-read.R` script should be standalone, so the usages of `catch()` and `read()` there were unintentional. I've updated that now.

**Comment by kevinushey** [comment]
Also added some tests in https://github.com/rstudio/renv/commit/95b28e4c091d5357427766eea564e8856a068c17; should be good to go now!
