### ISSUE TITLE
link to vignette is missing

### ISSUE THREAD

**Issue by nickreich** [rstudio/renv#1793]
Noting that the link to the actual remotes vignette is missing on this line: 
https://github.com/rstudio/renv/blob/6507f92f0eb646479747fd7ee8ad3ee9ea602ab0/vignettes/packages.Rmd#L64

The link should be: https://remotes.r-lib.org/articles/dependencies.html

**Comment by kevinushey** [comment]
Thanks! Should be fixed on main via https://github.com/rstudio/renv/commit/ae73cfcde5b9799f807634e14f780516f1193088.
