### ISSUE TITLE
Cannot `R CMD build` renv-based package having vignettes

### ISSUE THREAD

**Issue by krystian8207** [rstudio/renv#1798]
Hi. Thank you for your hard work on this incredibly useful package!

I've been trying to run `R CMD build <pkg>` command on a package having some vignettes within.
Every time the command fails on the vignette building step with the following error (R@4.3.1 - but for lower version it's the same, renv@1.0.3):

```
$ R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘checkpkg’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
# Bootstrapping renv 1.0.3 ---------------------------------------------------
- Downloading renv ... OK
- Installing renv  ... OK

- None of the packages recorded in the lockfile are currently installed.
ERROR: dependency ‘magrittr’ is not available for package ‘checkpkg’
* removing ‘/tmp/RtmpNCKMdZ/Rinst99e0500257ef/checkpkg’
      -----------------------------------
ERROR: package installation failed
```

The missing `magrittr package`:
- is included in Imports section of DESCRIPTION file,
- is installed and added via `renv::snapshot` to renv.lock file.

After short investigation I found the reason is `hash` added to the project library which is based on its path.
Because of that:
1. The original project library is `<lib-path>/project-<hash1>/R-4.3/x86_64-pc-linux-gnu`
2. When `R CMD build <project>` is run, the project is copied to `/tmp/<tmp-path>`.
3. Further commands are run from within `/tmp/<tmp-path>`. Because of different project path this line https://github.com/rstudio/renv/blob/main/inst/resources/activate.R#L766 will compute different hash, so the project library becomes `<lib-path>/project-<hash2>/R-4.3/x86_64-pc-linux-gnu` where none of the dependencies is installed.

We can easily overcome the issue by setting up `RENV_PATHS_LIBRARY_ROOT_ASIS=TRUE` (see: https://github.com/rstudio/renv/blob/main/inst/resources/activate.R#L761) in order to stop adding the hash to the library, but I guess this is not expected setup.

Could you please take a look at the issue? Thank you.

**Comment by kevinushey** [comment]
Thanks for the bug report! Do you also see this issue with the development version of renv? You can install it with:

```
renv::upgrade(version = "main")
```

The solution in the development version of `renv` avoids the need to activate library paths again with R CMD build, and instead re-uses any existing library paths passed in from the parent session when building vignettes.

**Comment by krystian8207** [comment]
@kevinushey 

Unfortunately the issue is still showing up:

```
➜  checkpkg git:(master) ✗ R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘checkpkg’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
# Bootstrapping renv 1.0.5.9000 [sha: f30f828] -------------------------------
- Downloading renv ... OK
- Installing renv  ... OK

- None of the packages recorded in the lockfile are currently installed.
Warning message:
ERROR: dependency ‘magrittr’ is not available for package ‘checkpkg’
* removing ‘/tmp/RtmpA7zLVy/Rinst8343c99e0de7/checkpkg’
      -----------------------------------
ERROR: package installation failed
```

**Comment by kevinushey** [comment]
Thanks for confirming -- I'll see if there's something we can do to improve the situation here.

**Comment by kevinushey** [comment]
I believe this is now fixed in the development version of `renv`. Can you please try:

```
renv::install("rstudio/renv")
renv::activate()  # ensure renv autoloader is regenerated
```

and let me know if the issue appears to be resolved for you?

**Comment by krystian8207** [comment]
@kevinushey I confirm, it works fine now.
Thank you!

**Comment by kevinushey** [comment]
Awesome, thanks for reporting back!
