### ISSUE TITLE
API for copying packages from cache into project

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#18]
The motivation for this: for a project that is "finished", one might want to collect the R packages the project depends on and ensure they're installed directly in the project library (rather than linked from the cache). This is primarily just to make sure the project library could outlive the cache, or (perhaps) be more easily transplanted to another system.

This is in the same vein as `packrat::bundle()`.

**Comment by rpodcast** [comment]
Another situation (somewhat related) is when the user bootstraps a project with `renv` and the cache is used, but later on decides to disable use of the cache with `renv::settings$use.cache(FALSE)`. I would hope that immediately after disabling the cache, the packages from the cache would either be automatically copied or the user would get a prompt to begin the copying process.

**Comment by kevinushey** [comment]
@rpodcast I implemented that behavior with https://github.com/rstudio/renv/commit/98dcfad97a38bd0b993c5e1c4770ca9bcd58bbcc -- now, toggling the `use.cache` setting will copy packages to / from the cache as appropriate.

**Comment by rpodcast** [comment]
Excellent!  I just did a quick test and packages were immediately copied to the project dir after running `env::settings$use.cache(FALSE)`.  I'm really digging how snappy and fast `renv` runs even in this early stage.

**Comment by mstr3336** [comment]
Just speaking to this - I have packages that I am only able to install via `install_git`, which doesn't have a shim for renv. 

This results in a private library install, which I'm happy enough with, but my problem is that I can't call `renv::settings$use.cache(FALSE)`, without it throwing me the error "Error: source file '~/.local/share/renv/R-3.5/cache/v2/<PKGNAME>/0.1.6.9001/<long_hash>/<PKGNAME>' does not exist"

**Comment by mstr3336** [comment]
is the fix to instruct Renv to ignore my private packages?

**Comment by slopp** [comment]
@mstr3336  slightly tangential, but do you have your package available in a CRAN-like repository as well? Or do you plan to? (e.g. miniCRAN, drat, RStudio Package Manager, etc)

**Comment by kevinushey** [comment]
@mstr3336 Can you be a bit more explicit on what you were trying to do, and what failed? A reproducible example would be helpful.

**Comment by kevinushey** [comment]
It's worth saying that you should be able to install packages from Git using `remotes::install_git("<url>")`, and `renv` should understand how to snapshot + restore such packages.

**Comment by mstr3336** [comment]
> @mstr3336 slightly tangential, but do you have your package available in a CRAN-like repository as well? Or do you plan to? (e.g. miniCRAN, drat, RStudio Package Manager, etc)

I don't intend to in the near future, personally I'd be more than okay with publishing it but my boss doesn't want to. 



> @mstr3336 Can you be a bit more explicit on what you were trying to do, and what failed? A reproducible example would be helpful.

I suppose I could make a reprex with a minimal package skeleton, though making a reprex that captures my work's enterprise server setup is a little less feasible.

The main thing I was trying to do was disable the cache on my work's HPC for portability, because the R project in installed to a folder shared across my team and I didn't want to deal with configuring the cache path to be within the share.

This looked like 

```
install_git("<url>", credentials = "access_token")
# Installs to 'projectroot/renv/library' , 
# rather than to '~/.local/share/renv/R-3.5/cache/v2//0.1.6.9001/<long_hash>/'

renv::settings$use.cache(FALSE)
# "Error: source file '~/.local/share/renv/R-3.5/cache/v2//0.1.6.9001/<long_hash>/' does not exist"
```

> It's worth saying that you should be able to install packages from Git using `remotes::install_git("<url>")`, and `renv` should understand how to snapshot + restore such packages.

`renv` is actually very good at handling my snapshots/restores, though! (A lot less pain than `packrat` )

**Comment by kevinushey** [comment]
While the primary request here is solved with `renv::settings$use.cache(FALSE)`, I think we may also want a more direct API (e.g. `renv::isolate()` or something like that).
