### ISSUE TITLE
User library path issues

### ISSUE THREAD

**Issue by mik3y64** [rstudio/renv#180]
Hi, `renv` is a great dependency package and I am loving it more and more. Thank you. One issue though is with the user libraries. 

As an example, there are certain packages such as `usethis`, `devtools`, `git2r`, and personal "rstudio addin" packages that we're using during development but need not to be included in the renv.lock file. Loading `renv` project, particularly, running the `source("renv/activate.R")` in project-specific .Rprofile on startup overwrites all lib paths.

I am stucked at this...how do I append user-specific library on startup and what are the best practices? (well of course it's the users' responsibilities to avoid snapshot them into the renv.lock file accidentally) without bloating the very important project-specific .Rprofile because it does not make sense to write user-specific library into the project folder since it's shared project. I tried appending the library, say, `.libPaths(c(.libPaths(), 'path/to/my/lib'))` on Rprofile.site but it doesn't work as `renv` somehow overwrite the path because Rprofile.site is run before project-specific .Rprofile. This project-specific .Rprofile also makes the user home directory's .Rprofile redundant.

**Comment by kevinushey** [comment]
There are a couple solutions:

1. Use "packrat"-style snapshots, whereby `renv` only includes the packages you're actually using in the project, in the lockfile. This is the default, but you might want to double check with:

```r
# check current type
renv::settings$snapshot.type()

# use packrat-style snapshots
renv::settings$snapshot.type("packrat")
```

In that case, you can still install 'development' dependencies into the project library, but they normally won't enter the lockfile.

2. Add your user library path using renv's config mechanism; e.g.

```r
options(renv.config.external.libraries = "/path/to/user/lib")
```

But note that then packages in this library may enter the lockfile. I believe you should be able to set that in any appropriate `.Rprofile` but let me know if that doesn't work.

If neither of these handles your workflow well, let me know and I'll see what else we can consider. FWIW, I generally consider installing things into the project library the best approach, as development dependencies can have deep recursive dependencies and you want to be careful they don't conflict with your project's actual dependencies.

**Comment by kevinushey** [comment]
I'm going to close this, but please re-open if the above doesn't quite fit what you need.

**Comment by slhck** [comment]
I have a similar issue. Perhaps you can help. I would like to install the `languageserver` globally on my system and not have it be part of each renv project-specific setup.

How could I accomplish this?

I am using https://github.com/jozefhajnala/languageserversetup to get a global separate library just containing the languageserver package.

I saw that I could set `external.libraries` for renv, but it does not handle environment variables or placeholders like `$HOME`, so I cannot make this portable across different systems with different versions of R.

Should I set an additional library lookup path in the `.Rprofile` file and load the package from there?

**Comment by kevinushey** [comment]
> Should I set an additional library lookup path in the .Rprofile file and load the package from there?

That's probably the simplest way forward. You could also file a separate feature request for `external.libraries`, describing what you were hoping for.

One thing to be aware of is that `languageserver` has a large number of package dependencies, so you might need to be careful to ensure that the packages (+ their versions) used in your project are compatible with the version used by `languageserver`, assuming `languageserver` needs to be loaded in the same R session.
