### ISSUE TITLE
Recreate an entire R library regardless of project

### ISSUE THREAD

**Issue by royfrancis** [rstudio/renv#1801]
I want to recreate an entire R library from one system on to another. This has nothing to do with any specific project.

If I run `renv::snapshot()` in an empty directory, it only captures R and renv. So, I created a dummy R script file with all the packages in the library.

```r
pkgs <- installed.packages()[,"Package"]
write.table(data.frame(x=paste0("library(",pkgs,")")),,col.names=F,row.names=F,quote=F)
```

which just lists all the packages like this:

```
library(parallel)
library(rpart)
library(spatial)
library(splines)
library(stats)
library(stats4)
library(survival)
...
```

And ran `renv::init()`. It gives an error:

```
Error in renv_snapshot_validate_report(valid, prompt, force) : 
  aborting snapshot due to pre-flight validation failure
Traceback (most recent calls last):
4: renv::init()
3: snapshot(library = libpaths, repos = repos, prompt = FALSE, project = project)
2: renv_snapshot_validate_report(valid, prompt, force)
1: stop("aborting snapshot due to pre-flight validation failure")
```

Then I realized maybe I don't need to initialize because I don't plan to actually work in this folder. So, I just ran `renv::snapshot()`. And that seems to have worked.

I was wondering if there is a better way to do this? Also, is this `renv::settings$snapshot.type("all")` relevant here?

`R 4.3.2` `renv 1.0.3`

**Comment by kevinushey** [comment]
> I was wondering if there is a better way to do this? Also, is this renv::settings$snapshot.type("all") relevant here?

Yes, you likely want that in this scenario -- https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile also discusses this a bit.

The most explicit way of accomplishing this would be:

```
renv::snapshot(library = .libPaths(), type = "all")
```
