### ISSUE TITLE
Are there plans for Posit Connect to support advanced renv features?

### ISSUE THREAD

**Issue by dvg-p4** [rstudio/renv#1804]
IIUC, Connect currently uses packrat under the hood, which can handle the basic features of renv but not some of the newer ones, e.g. packages from Github (or other custom repos), and renv profiles.

**Comment by dvg-p4** [comment]
I guess this isn't an issue with `renv` per se, but I figured this would be as good a place as any to ask since it's all under the rstudio/Posit umbrella and Connect doesn't have a github repo.

**Comment by kevinushey** [comment]
I'm not aware of anything planned currently -- are there any specific features you're hoping to see supported?

**Comment by dvg-p4** [comment]
We've had a lot of issues and cryptic errors trying to deploy apps that depend on GitHub-sourced packages, I'd say that's the main one.

**Comment by kevinushey** [comment]
Are you able to share some examples of these errors (either here or on https://github.com/rstudio/rsconnect/issues)? I think installation of packages on GitHub should normally be supported.

**Comment by dvg-p4** [comment]
Oh I didn't realize that existed--yeah that'd be a more appropriate place for this ticket. Let me download the latest versions of everything, go through the process again, and I'll open a more specific ticket there if I'm still having issues.
