### ISSUE TITLE
Using renv without project library or global cache

### ISSUE THREAD

**Issue by royfrancis** [rstudio/renv#1810]
I am using renv inside a docker container. I use one container for one project, so the standard R library in that container is for that project only and I don't need project level isolation. I do not want renv package library in my working directory.

How can I force renv to only use the system library and not use a project directory? When installing packages, it must be installed directly into system library. I also don't need any cache.

`renv 1.0.3`

**Comment by alketh** [comment]
Hey there, I have a very similar problem. We use 

```
renv::restore(clean = FALSE, prompt = FALSE)
```

during docker build to restore the libs using a renv.lock file. Packages are also copied into the cache

```
#9 7.741 Installing renv [1.0.3] ...
#9 17.85 	OK [built from source in 10 seconds]
#9 17.85 Copying renv [1.0.3] into the cache ...
```

I noticed that this can result in additional layers. I would like to suppress the use of a cache during docker build.

**Comment by kevinushey** [comment]
You can disable the cache with e.g.

```
options(renv.config.cache.enabled = FALSE)
```

Does that suffice?
