### ISSUE TITLE
Dependency not checked when filenames only differ in their extension

### ISSUE THREAD

**Issue by alexpbell** [rstudio/renv#1812]
Hi Kevin,

With two similarly named files in a project, say filename.Rmd and filename.R, renv::dependencies() (and hence renv::status()) appears to fail to notice the file with the ".R" extension. Contributing factors may have been that the filename.R used to be called something else, and at some point the code in filename.R had an error in it. So the full sequence of steps to get into trouble and then recover in my case was:

1. install and renv sync various packages successfully into filename.Rmd and somethingelse.R.
2. rename somethingelse.R to filename.R and then add package B to filename.R and leave filename.R with a code error
3. renv::status() reports that package A (used in filename.R) is installed and recorded but not used, and says nothing about package B (used in filename.R, installed, and not recorded).  
4. guess this might be a filename clash issue and rename filename.R to filename2.R
5. renv now reports code error in filename2.R and still reports renv status as above
6. fix code error in filename2.R. renv::status now reports everything as expected: package A is not mentioned (because it is installed, recorded and used), and package B is installed, used and not recorded. renv::snapshot and all is well.

I have not reproduced this behaviour without the contributing factors, but could do so if that would help.

Kind regards,
Alex

**Comment by kevinushey** [comment]
Thanks for the bug report -- unfortunately, I wasn't able to reproduce the issue you described. Any chance you'd be able to dig in a bit further and prepare a fully reproducible example?
