### ISSUE TITLE
renv parses `from(x)` into attach library 

### ISSUE THREAD

**Issue by mangost** [rstudio/renv#1815]
In the following code
```{r}
#' Replace some values with others, in a data frame
#' @param df A data frame
#' @param from A function that returns a logical vector,
#'   which is applied on each column to select elements to replace
#' @param to A vector, values to replace with (recycled if necessary)
#' @return A data frame
filter_and_replace_df <- function(df, from = is.na, to = 0) {
  return(
    df |>
      lapply(\(x) replace(x, from(x), to)) |>
      as.data.frame() |>
      setRowNames(rownames(df))
  )
}
```

` renv::dependencies()` reported package "x".

If I changed the argument name `from` -> `filter`, ` renv::dependencies()`  did not report package "x".

The minimal example is 
```{r}
from <- c
x <- 1
from(x)
```

I guess `from` is not a builtin or reserved name in R, is it?
```{r}
?from
# No documentation for ‘from’ in specified packages and libraries:
# you could try ‘??from’
```

**Comment by kevinushey** [comment]
Thanks for the bug report -- I think this is because `renv` is erroneously inferring that this is supposed to be a usage of the form `import::from()`, for the CRAN package [import](https://cran.r-project.org/web/packages/import/index.html).

I'll see if we can't improve the situation here.
