### ISSUE TITLE
some packages fail to maintain installed updates

### ISSUE THREAD

**Issue by jkylearmstrong** [rstudio/renv#1817]
Cross posting this issue I posted on RStudio as I think it might be `renv` related:

System details
RStudio Edition : Desktop
RStudio Version : 2023.12.1 Build 402
OS Version      :  Windows Version 22H2 (OS Build 22621.3007)
R Version       :  R version 4.3.2 (2023-10-31 ucrt)
Steps to reproduce the problem
when in RStudio if I attempt to update the following packages:

![image](https://github.com/rstudio/renv/assets/29757798/39b4013b-b62b-42a6-92cf-3358f9e77039)

with

```
install.packages(c("cluster", "foreign", "lattice", "MASS", "Matrix", "mgcv", "nlme", "rpart"))
```

and then after restarting R and checking the "update" in RStudio the packages will still appear out of date.

Unsure if the issue is related to `renv` within the project environment or a general problem, but it exists on 2 different windows PCs that I am currently working with.

See the conversation at https://github.com/rstudio/rstudio/issues/14235

**Comment by kevinushey** [comment]
Thanks! I followed up on the RStudio repository; I suspect the issue here will actually need to be resolved on the RStudio side.
