### ISSUE TITLE
Artifactory Authentication in Lock File

### ISSUE THREAD

**Issue by thefabnab** [rstudio/renv#1819]
I'm having an issue following the standard artifactory [CRAN instance setup instructions](https://jfrog.com/help/r/jfrog-artifactory-documentation/resolve-cran-packages-using-the-ui) which embed a username and password into the repository URL, like so:

```
local({ 
        r <- list("internal-cran" = "https://USERNAME:PASSWORD@internal-cran.io/artifactory/repository"
        )
        options(repos = r)
})
```

and having those credentials embedded in the url [showing up in the Repositories field](https://rstudio.github.io/renv/reference/lockfiles.html#details) of the renv.lock file:

```
{
  "R": {
    "Version": "3.6.1",
    "Repositories": [
      {
        "Name": "internal-cran",
        "URL": "https://USERNAME:PASSWORD@internal-cran.io/artifactory/repository"
      }
    ]
  },
  "Packages": {
...
```

If I'm doing package development I'd rather not these credentials be included in the commit history of the repository.

**Comment by kevinushey** [comment]
`renv` could strip the credentials from the repository URL, but how would you ensure those credentials are set later when that lockfile is used elsewhere?

Is there a way for you to set these authentication credentials without encoding them directly in the repository URL?

**Comment by thefabnab** [comment]
I figured out a fix that'll communicate here for others.

I found [this post](https://www.dahl-jacobsen.dk/data/2020/12/04/access-cran-on-jfrog/) from Robert Jacobsen where in it he describes how to use the JFROG_PAT (Personal Authentication Token) with bearer authentication to install packages:

```
install.packages("<package>", headers = c("Authorization" = paste("Bearer", Sys.getenv('JFROG_PAT'))))
```

I logged onto artifactory and generated a PAT and set it as an environment variable (`JFROG_PAT`) within my `.Renviron` file and followed the renv instructions for [using custom headers](https://rstudio.github.io/renv/articles/package-install.html#custom-headers) modifying the `.Rprofile` file in the root of my repository as follows:

```
source("renv/activate.R")
local({
options(renv.download.headers = function(url) {
  if (grepl("internal-cran.io", url))
    return(headers=c("Authorization" = paste("Bearer",Sys.getenv("JFROG_PAT"))))
})
```

Finally I modified the lockfile to look as follows:

```
{
  "R": {
    "Version": "3.6.1",
    "Repositories": [
      {
        "Name": "internal-cran",
        "URL": "https://internal-cran.io/artifactory/repository"
      }
    ]
  },
  "Packages": {
...
```
To test that these changes are working I ran `renv::refresh()` and `renv::rebuild()` to make sure that it could pull all the packages for the project it needed from the repository. Then to really make sure it was working I used `renv::install()` to install one of the packages I know to be served from our internal repository.

Seems like everything is working now on my end. How does this resolution sound to you @kevinushey? The only thing I'll have to do is encourage our internal users to generate their own PATs/Embed one into our CI/CD and it would seem all my needs are met.

**Comment by kevinushey** [comment]
That looks correct to me, and that's the intended way of using the authentication tooling in `renv`.

It does come with the implicit requirement that you (or anyone else) later attempting to call `renv::restore()` with that lockfile has the appropriate authentication credentials set up on their machine; that is, they have `options(renv.download.headers)` set in the same way as you have. But if you're only ever working in, or sharing, the whole project, then that should be the right solution.

The other downside is that other tooling for downloading / installing packages from that repository (e.g. `install.packages()`; `pak::pkg_install()`) won't work, as the authentication tooling is `renv`-specific ... but perhaps that's fine?

**Comment by thefabnab** [comment]
Thanks for the positive feedback Kevin. I'm rather happy with the way renv is working and more happy that I'm using it correctly in this regard.

Since the project is self contained within a VCS repository I'll just be communicating to folks developing on the package that they'll need a token to build their R environments to develop.

WRT package installations I'm just going to keep the artifactory setup (`USERNAME:PASSWORD`) as is so `install.packages` pulls from the repos object with the user and password embedded in the URL and renv using the header specified. As far as I can tell as long as I don't "remake" the lock file from scratch the URL will remain the same.

I think that'll be splitting the difference, allowing folks to keep their current environment configured in a convenient fashion, and allow our CI/CD to operate using renv.
