### ISSUE TITLE
Error installing custom package from github enterprise

### ISSUE THREAD

**Issue by eli-ob1** [rstudio/renv#1821]
Hi,
I have been trying to install a custom package from github enterprise, i have been reading other issues to try and solve and followed the suggestions. This is what i have so far:

In my .Renviron file I set:
GIT_USER = '<username>'
GIT_PAT = '<pat>'
GIT_PASS = '<pat>' (since the above line didn't work)

I then tried running:
renv::install("https://github.tools.digital.companyname.com/group/package.git")

I also set as an option based on renv documentation:

options(renv.auth = function(package, record) {
  if (package == "packagename")
    return(list(GIT_PAT = Sys.getenv("GIT_PAT ")))
})

The error:
remote: Password authentication is not available for Git operations.
remote: You must use a personal access token.
remote: See https://github.tools.digital.companyname.com/settings/tokens
fatal: unable to access 'https://github.tools.digital.companyname.com/group/packagename.git/': The requested URL returned error: 403
Error: failed to resolve remote 'https://github.tools.digital.companyname.com/group/packagename.git' -- error cloning 'packagename' from 'https://github.tools.digital.companyname.com/group/packagename.git' [status code 128]

**Comment by kevinushey** [comment]
Is https://github.com/rstudio/renv/issues/1751 potentially relevant? In particular, what I saw was that the PAT had to be used as the username, and the password either left blank, or set as `x-oauth-basic`.

**Comment by eli-ob1** [comment]
> Is #1751 potentially relevant? In particular, what I saw was that the PAT had to be used as the username, and the password either left blank, or set as `x-oauth-basic`.

Thanks! This worked, sorry I must have missed that suggestion

**Comment by kevinushey** [comment]
Glad to hear it! I'll reopen this issue as a reminder to myself to update the documentation so this is easier to find.
