### ISSUE TITLE
https protocol pre-pended twice during restore

### ISSUE THREAD

**Issue by wjhopper** [rstudio/renv#183]
After cloning a project that uses renv, an `renv` installation was helpfully "bootstrapped" for me upon opening the project. When attempting to restore the rest of the project library using `renv::restore()`, it reported a mismatch between the version of renv just installed and the version recorded in the project lockfile. 

When attempting to resolve this mismatch by retrieving and installing the source package corresponding to the version in the lockfile, the https:// protocol information is pre-pended twice, as seen below:

```r
> renv::restore()
The following package(s) will be installed:
       _                       
  renv   [0.7.0-17 -> 0.7.0-17]

Do you want to proceed? [y/N]: y
Retrieving 'https://https://api.github.com/repos/rstudio/renv/tarball/83666b023c9d3ece269303820cf86d34c2a248ae' ...
curl: (6) Could not resolve host: https
curl: (6) Could not resolve host: https
```

It appears the offending line is line 159 of retreive.R :
https://github.com/rstudio/renv/blob/b73c18e59ec10ea5168cc1b4087d8d5f63a7a230/R/retrieve.R#L155-L160

The URL template includes the https:// prefix, but https:// is already part of the RemoteHost field in the package record, which then breaks the URL.

**Comment by kevinushey** [comment]
Thanks for the bug report! To the best of my knowledge, `https://` shouldn't normally be included as part of the RemoteHost field. Can you provide any more information as to how you got into that state?

**Comment by kevinushey** [comment]
This should be fixed up on master, but I'd still be curious to know if there's a way for me to reproduce this issue and see where the extra `https` is coming from. Let me know if all looks well on your side with the latest `renv`.

**Comment by wjhopper** [comment]
The project was migrated from packrat to renv via the migrate function, and
did have to be interupted at least once (Windows search indexing and
Windows Defender were churning through the BH libraries and such), so
perhaps that has something to do with it?

**Comment by wjhopper** [comment]
Oh also the specific renv lockfile is here:
https://github.com/wjhopper/SvDPRec/blob/master/renv.lock

Sorry I can't be more specific about how that https snuck in there.

**Comment by kevinushey** [comment]
Thanks! No worries; I appreciate your following up. You should be able to run `renv::upgrade()` in your project to upgrade to the latest version of `renv`.
