### ISSUE TITLE
Ignore comparing package version number at R start

### ISSUE THREAD

**Issue by elgabbas** [rstudio/renv#1830]
Hello,
Is it possible to hide/ignore that the project is out of sync? I receive the following message at the start of R.
```
The project is out-of-sync -- use `renv::status()` for details.
```
This is okay. However, when working in parallel at an HPC, the message is repeated on the screen; e.g.:
```
.NCores <- 50
c1 <- snow::makeSOCKcluster(.NCores)
future::plan(cluster, workers = c1, gc = TRUE)
# here the message appears 50 times, for each core
```

Is it possible to ignore this warning using something like `options()`? 

Alternatively is it possible to disable comparing between versions of installed packages and their versions on the lock file at R startup altogether (this may make R start faster especially if there are many packages installed in the project)? 

Thanks

**Comment by kevinushey** [comment]
You can use:

```
RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE
```

in your project `.Renviron` -- please see https://rstudio.github.io/renv/reference/config.html#renv-config-synchronized-check for the documentation.

**Comment by elgabbas** [comment]
Thanks @kevinushey .. This worked for me.
