### ISSUE TITLE
generate lockfile (or list of records) from active repos, given list of packages

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#184]
This would provide a way for projects to switch from one repository to another in a more natural way. The lockfile could be generated based on the packages available and reported from the active repositories, and then those could be used in e.g. `renv::restore()` to install specifically those packages.

**Comment by kevinushey** [comment]
This can basically be done with:

```
packages <- c("dplyr")
lapply(packages, renv:::renv_available_packages_latest)
```

Note that there are some concerns about whether (for macOS + Windows) binary or source packages should be selected. `renv_available_packages_latest` tries to pick a binary if it detects the user does not have the necessary build tools installed, or has otherwise opted out of compiling packages from sources.

**Comment by hadley** [comment]
This is `checkout()` again.
