### ISSUE TITLE
Add param `lock` to `update()`

### ISSUE THREAD

**Issue by salim-b** [rstudio/renv#1849]
I wondered whether the [recently introduced param `lock` in `install()`](https://github.com/rstudio/renv/commit/41a4d4dbea1297a2f45ae1327321c8a043ffeb6a) could also be added to `update()`, allowing the `renv.lock` lockfile to be updated automatically after successful update of the requested packages. It would be be a convenient feature for users of renv's `"explicit"` [snapshot type](https://rstudio.github.io/renv/reference/snapshot.html#snapshot-types).

**Comment by kevinushey** [comment]
This was an easy lift, given that `renv::update()` calls `renv::install()` in the end -- I've just added this.
