### ISSUE TITLE
Is there a way to remove a package from project library as well as the cache library?

### ISSUE THREAD

**Issue by yuanqingye** [rstudio/renv#1858]
Hi

I notice if I installed a new package in a renv activated project, say `install.packages("tictoc")`
Then it is in project library as well as in cache library(`renv::paths$cache()` will give the absolute path).
If I remove the package, I think it just remove the one in the project library and it was just a link, the one in cache library is still there.

So if I am 100% sure currently I want to remove it also from cache library, is there a formal way to do so?
Manually to do it is fine for just one, but if more than one, the work becomes formidable.

**Comment by kevinushey** [comment]
You can use, for example, `renv::purge("tictoc")` see `?renv::purge` for more details.

**Comment by yuanqingye** [comment]
> You can use, for example, `renv::purge("tictoc")` -- please see `?renv::purge` for more details.
OK,I got it, thank you very much.
