### ISSUE TITLE
Package install errors in new renv project not in user home directory on system drive  (Ubuntu 22.04 LTS) 

### ISSUE THREAD

**Issue by lyndbacon** [rstudio/renv#1866]
Hello.  I've been using renv for a few projects that I have located in my user directory on the system drive of an Ubuntu workstation. I recently tried to create new projects that use renv on a second drive in the same workstation that I have full read/write access to.   I get installation failure messages when I try to install new packages in renv projects on this second drive.  Using identical projects installed under my user account on the system drive, I can install the same packages without error.   

Following is an example of the install errors I get.  It was produced by trying to install the "MASS" package.  The project is on  /media/sdb2, a partition on my second drive.  The product home directory is renv_sdb2_testing, which is where the project .Rprofile, etc., are.  

`> renv::install('MASS')
## Downloading packages -------------------------------------------------------
- Downloading MASS from CRAN ...                OK [548.4 Kb in 0.51s]
Successfully downloaded 1 package in 0.61 seconds.

The following package(s) will be installed:
- MASS [7.3-60.0.1]
These packages will be installed into "/media/sdb2/renv_sdb2_testing/renv/library/R-4.3/x86_64-pc-linux-gnu".

Do you want to proceed? [Y/n]: Y

## Installing packages --------------------------------------------------------
- Installing MASS ...                           FAILED
Error: Error installing package 'MASS':
================================

* installing *source* package ‘MASS’ ...
** package ‘MASS’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c MASS.c -o MASS.o
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c lqs.c -o lqs.o
gcc -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o MASS.so MASS.o lqs.o -L/usr/lib/R/lib -lR
installing to /media/sdb2/renv_sdb2_testing/renv/staging/1/00LOCK-MASS/00new/MASS/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘MASS’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/media/sdb2/renv_sdb2_testing/renv/staging/1/00LOCK-MASS/00new/MASS/libs/MASS.so':
  /media/sdb2/renv_sdb2_testing/renv/staging/1/00LOCK-MASS/00new/MASS/libs/MASS.so: failed to map segment from shared object
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/media/sdb2/renv_sdb2_testing/renv/staging/1/MASS’
install of package 'MASS' failed [error code 1]
Traceback (most recent calls last):
12: renv::install("MASS")
11: renv_install_impl(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_package(record))
 7: renv_install_package(record)
 6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 5: renv_install_package_impl(record)
 4: r_cmd_install(package, path)
 3: r_exec_error(package, output, "install", status)
 2: abort(all)
 1: stop(fallback)
> 
`
The above looks a little like a permission error of some sort, but the project directory and subdirs are owned by me and are read/write accessible.  An issue related to the lock file location, or...?  

As an experiment I tried relocating the cache to /media/sdb2 by creating a directory there, and by setting the path for it in a project-level .Renviron file.  I got the same installation error messages, and the renv diagnostics for the project (below) still indicates a cache in my user home directory on the system drive.  I get the same result with a user-level .Renviron file.  Maybe the root path for global state storage  needs to be changed?  It doesn't seem like it should need to be, based on the renv doc.  I've tried removing all renv components I could locate, and then uninstalling it and reinstalling it.

Here's the diagnostic info for the project that generates errors like the above:

`
> renv::diagnostics()
Diagnostics Report [renv 1.0.5]
===============================

## Session Info ---------------------------------------------------------------
R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Denver
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.3 tools_4.3.3    renv_1.0.5    

## Project --------------------------------------------------------------------
Project path: "/media/sdb2/renv_sdb2_testing"

## Status ---------------------------------------------------------------------
No issues found -- the project is in a consistent state.

## Packages -------------------------------------------------------------------
              Library Source Lockfile Source Path Dependency
KernSmooth    2.23-22   CRAN     <NA>   <NA>  [2]       <NA>
MASS       7.3-60.0.1   CRAN     <NA>   <NA>  [2]       <NA>
Matrix          1.6-5   CRAN     <NA>   <NA>  [2]       <NA>
boot           1.3-30   CRAN     <NA>   <NA>  [2]       <NA>
class          7.3-22   CRAN     <NA>   <NA>  [2]       <NA>
cluster         2.1.6   CRAN     <NA>   <NA>  [2]       <NA>
codetools      0.2-19   CRAN     <NA>   <NA>  [2]       <NA>
foreign        0.8-86   CRAN     <NA>   <NA>  [2]       <NA>
lattice        0.22-6   CRAN     <NA>   <NA>  [2]       <NA>
mgcv            1.9-1   CRAN     <NA>   <NA>  [2]       <NA>
nlme          3.1-163   CRAN     <NA>   <NA>  [2]       <NA>
nnet           7.3-19   CRAN     <NA>   <NA>  [2]       <NA>
renv            1.0.5   CRAN    1.0.5   CRAN  [1]     direct
rpart          4.1.23   CRAN     <NA>   <NA>  [2]       <NA>
spatial        7.3-17   CRAN     <NA>   <NA>  [2]       <NA>
survival        3.5-8   CRAN     <NA>   <NA>  [2]       <NA>
utils            <NA>   <NA>     <NA>   <NA>  [2]   indirect

[1]: /media/sdb2/renv_sdb2_testing/renv/library/R-4.3/x86_64-pc-linux-gnu
[2]: /home/lynd/.cache/R/renv/sandbox/R-4.3/x86_64-pc-linux-gnu/9a444a72 

## ABI ------------------------------------------------------------------------
- No ABI problems were detected in the set of installed packages.

## User Profile ---------------------------------------------------------------
[1] Source  Package Require Version Dev    
<0 rows> (or 0-length row.names)

## Settings -------------------------------------------------------------------
List of 13
 $ bioconductor.version     : NULL
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ ppm.enabled              : NULL
 $ ppm.ignored.urls         : chr(0) 
 $ r.version                : NULL
 $ snapshot.type            : chr "implicit"
 $ use.cache                : logi TRUE
 $ vcs.ignore.cellar        : logi TRUE
 $ vcs.ignore.library       : logi TRUE
 $ vcs.ignore.local         : logi TRUE
 $ vcs.manage.ignores       : logi TRUE

## Options --------------------------------------------------------------------
List of 8
 $ defaultPackages                     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method                : NULL
 $ download.file.extra                 : NULL
 $ install.packages.compile.from.source: NULL
 $ pkgType                             : chr "source"
 $ repos                               : Named chr "https://cloud.r-project.org"
  ..- attr(*, "names")= chr "CRAN"
 $ renv.consent                        : logi TRUE
 $ renv.verbose                        : logi TRUE

## Environment Variables ------------------------------------------------------
HOME                        = /home/lynd
LANG                        = en_US.UTF-8
MAKE                        = make
R_LIBS                      = <NA>
R_LIBS_SITE                 = /usr/local/lib/R/site-library/:/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library
R_LIBS_USER                 = /media/sdb2/renv_sdb2_testing/renv/library/R-4.3/x86_64-pc-linux-gnu
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = /usr/local/lib/R/site-library/:/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library
RENV_DEFAULT_R_LIBS_USER    = /home/lynd/R/x86_64-pc-linux-gnu-library/4.3
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = /media/sdb2/renv_sdb2_testing

## PATH -----------------------------------------------------------------------
- /home/lynd/.modular/pkg/packages.modular.com_max/bin
- /home/lynd/.modular/pkg/packages.modular.com_mojo/bin
- /home/lynd/anaconda3/condabin
- /usr/local/cuda-11.8/bin
- /home/lynd/.cargo/bin
- /home/lynd/bin
- /usr/local/sbin
- /usr/local/bin
- /usr/sbin
- /usr/bin
- /sbin
- /bin
- /usr/games
- /usr/local/games
- /snap/bin
- /usr/local/go/bin
- /home/lynd/go/bin
- /home/lynd/julia-1.10.0/bin/julia
- /home/lynd/julia-1.9.4/bin
- /home/lynd/racket/bin
- /home/lynd/.local/bin

## Cache ----------------------------------------------------------------------
There are a total of 0 packages installed in the renv cache.
Cache path: "~/.cache/R/renv/cache/v5/R-4.3/x86_64-pc-linux-gnu"

> 
`
Maybe 

Any thoughts or suggestions will be greatly appreciated!  I suspect I must be missing something that's really obvious, maybe in terms of some necessary renv customization.  Hm...

Lynd

**Comment by kevinushey** [comment]
IIRC, this kind of error:

> /media/sdb2/renv_sdb2_testing/renv/staging/1/00LOCK-MASS/00new/MASS/libs/MASS.so: failed to map segment from shared object

can occur if a directory is mounted as `noexec`. Can you share the output of:

```
mount
```

or check if that drive (`sdb2`?) is mounted as `noexec`?

As far as workarounds, you could force those projects to use an alternate library path; see https://rstudio.github.io/renv/reference/paths.html#customising-individual-paths for more details.

**Comment by lyndbacon** [comment]
@kevinushey , and All, an update.  "failed to map segment" errors do pop up when trying to execute code from a partition with the noexec flag set.   I removed the noexec flag from the sdb2 partition and remounted it, but still got the same errors.  Maybe I needed to remove the other security flags for when this partition is mounted.

However, I don't get this error on a partition with the noexec flag set that is a master boot partition, as this one is:

```
lynd@zdog:/media/nvme$ mount | grep nvme
/dev/nvme0n1p1 on /media/nvme type ext4 (rw,nosuid,nodev,noexec,relatime,user,uhelper=udisks)
```
For example,

```
Project '/media/nvme/renv_testing' loaded. [renv 1.0.5]
> renv::install('fs')
The following package(s) will be installed:
- fs [1.6.3]
These packages will be installed into "/media/nvme/renv_testing/renv/library/R-4.3/x86_64-pc-linux-gnu".

Do you want to proceed? [Y/n]: Y

# Installing packages --------------------------------------------------------
- Installing fs ...                             OK [linked from cache]
Successfully installed 1 package in 32 milliseconds.
```
The one partition on nvme is a master boot partition, and the noexec flag is set for it, as indicated above. 

In the directory of this project on nvme, /media/nvme/renv_testing, I have an .Renviron file that contains:

Sys.setenv(RENV_PATHS_CACHE='/media/nvme/renv/cache')

In R, however, I find that the cache path is the default:

```
> renv::paths$cache()
[1] "/home/lynd/.cache/R/renv/cache/v5/R-4.3/x86_64-pc-linux-gnu"
```
I found that assigning a new RENV_PATH_ROOT value in .Renviron also didn't have any affect.  All the referenced directories were created before starting R.

I suspect I must be defining custom paths incorrectly.

**Comment by lyndbacon** [comment]
Sorry about the "false close."   Fat thumbed.

**Comment by lyndbacon** [comment]
I've updated to a new version of renv, 1.0.7.  I am still unable to install packages in an renv project on a non-system drive, i.e., to a drive that does not have an MBR/boot partition.  I'm now running R version 4.4.0 (2024-04-24) -- "Puppy Cup"

As an example, trying to install 'backports':

```
installing to /media/sdb2/mlr3ext/renv/staging/1/00LOCK-backports/00new/backports/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘backports’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/media/sdb2/mlr3ext/renv/staging/1/00LOCK-backports/00new/backports/libs/backports.so':
  /media/sdb2/mlr3ext/renv/staging/1/00LOCK-backports/00new/backports/libs/backports.so: failed to map segment from shared object
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/media/sdb2/mlr3ext/renv/staging/1/backports’
install of package 'backports' failed [error code 1]
```

**Comment by kevinushey** [comment]
Just to rule out something that `renv` might be doing, do you see the same issue if you try to install packages with e.g.

```
dir.create("/media/sdb2/mlr3ext/lib", recursive = TRUE)
utils::install.packages("backports", lib = "/media/sdb2/mlr3ext/lib")
```

Or, perhaps:

```
dir.create("/media/sdb2/mlr3ext/renv/library", recursive = TRUE)
utils::install.packages("backports", lib = "/media/sdb2/mlr3ext/renv/library")
```

That is, can you install R and use R packages with "base" R, without `renv` in the mix?

**Comment by lyndbacon** [comment]
Hi.   Thanks.  No, neither of the above worked.  Both threw the same kind of failure error.  For the latter,

```
> dir.create("/media/sdb2/mlr3ext/renv/library", recursive=TRUE)
> utils::install.packages("backports", lib="/media/sdb2/mlr3ext/renv/library")
trying URL 'https://cloud.r-project.org/src/contrib/backports_1.4.1.tar.gz'
Content type 'application/x-gzip' length 26201 bytes (25 KB)
==================================================
downloaded 25 KB

* installing *source* package ‘backports’ ...
** package ‘backports’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-H8urij/r-base-4.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dotsElt.c -o dotsElt.o
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-H8urij/r-base-4.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dotsLength.c -o dotsLength.o
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-H8urij/r-base-4.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dotsNames.c -o dotsNames.o
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-H8urij/r-base-4.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c init.c -o init.o
gcc -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o backports.so dotsElt.o dotsLength.o dotsNames.o init.o -L/usr/lib/R/lib -lR
installing to /media/sdb2/mlr3ext/renv/library/00LOCK-backports/00new/backports/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘backports’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/media/sdb2/mlr3ext/renv/library/00LOCK-backports/00new/backports/libs/backports.so':
  /media/sdb2/mlr3ext/renv/library/00LOCK-backports/00new/backports/libs/backports.so: failed to map segment from shared object
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/media/sdb2/mlr3ext/renv/library/backports’

The downloaded source packages are in
	‘/tmp/RtmppGHiQ7/downloaded_packages’
Warning message:
In utils::install.packages("backports", lib = "/media/sdb2/mlr3ext/renv/library") :
  installation of package ‘backports’ had non-zero exit status

```
I did check to verify that noexec is not set on mount for this partition, or for the other partition on this device.

**Comment by kevinushey** [comment]
Can you check what permissions are set on the library file after installation? You could do something like:

```
library <- "/media/sdb2/mlr3ext/renv/library"
.libPaths(c(library, .libPaths()))
utils::install.packages("backports", INSTALL_opts = "--no-test-load")
libs <- system.file("libs", package = "backports")
system(paste("ls -la", libs))
```

What output do you get? Does the `.so` file have executable permissions set?

Either way, this unfortunately seems like an issue outside of `renv`'s purview -- something on your system is configured in such a way that `.so` files cannot be loaded on this filesystem. A `noexec` mount is the most common culprit, but it's possible something else is preventing this as well.

It's also possible that your system logs (SELinux? Something else?) could be reporting when these attempts to load the library are happening, and why they're being denied.

**Comment by lyndbacon** [comment]
Thanks!  Following is the output from the code you provided.  As you can see,  the .so file has executable permission.

```
> libs <- system.file("libs", package="backports")
> libs
[1] "/media/sdb2/mlr3ext/renv/library/backports/libs"
> system(paste("ls -la", libs))
total 32
drwxr-xr-x 2 lynd hadoop  4096 Apr 26 18:20 .
drwxr-xr-x 7 lynd hadoop  4096 Apr 26 18:20 ..
-rwxr-xr-x 1 lynd hadoop 24248 Apr 26 18:20 backports.so
> system(paste("namei -l", libs))
f: /media/sdb2/mlr3ext/renv/library/backports/libs
drwxr-xr-x root root   /
drwxr-xr-x lynd hadoop media
drwxr-xr-x lynd hadoop sdb2
drwxr-xr-x lynd hadoop mlr3ext
drwxr-xr-x lynd hadoop renv
drwxr-xr-x lynd hadoop library
drwxr-xr-x lynd hadoop backports
drwxr-xr-x lynd hadoop libs
> library(backports)
Error: package or namespace load failed for ‘backports’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/media/sdb2/mlr3ext/renv/library/backports/libs/backports.so':
  /media/sdb2/mlr3ext/renv/library/backports/libs/backports.so: failed to map segment from shared object

```
I observed previously that I could successfully renv::install()  packages on an attached drive that happens to have a master boot record on it.  I think I'll investigate that further, and will also look into whether my logs provide any clues.  I'll post any status updates.

Thanks again, @kevinushey !

**Comment by lyndbacon** [comment]
Found the problem.  "User error" on my part, or a blind spot.  While reviewing some mount doc I realized that the order that I had the partition mount options in was overriding my exec option to default to noexec.   Mount options are processed from left to right.  Putting exec at the end of my mount options list cured the problem.

@kevinushey  thanks for your patience with this.

**Comment by lyndbacon** [comment]
Thanks again!

**Comment by kevinushey** [comment]
Great news; I'm glad to hear you were able to get to the bottom of this! At the very least, this issue log will likely be helpful to somebody else administrating R installations in the future at well.
