### ISSUE TITLE
library path is inside cache and not the project

### ISSUE THREAD

**Issue by shumza-nali** [rstudio/renv#1868]
Hi @kevinushey,

When I call renv inside a golem Shiny App, it creates an renv folder inside the project with .gitignore, activate.R, settings.json. There is no library inside with all my packages. With `.libPaths()` I found out it is saving this directory to:

'/home/myUser/.cache/R/renv/library/myAppName/...'. 

I would expect `.libPaths()` to change to my project directory once I initiate renv `renv::init()`.

When I call renv outside a golem shiny App it works as intended. I wonder what behaviour of renv or interaction between golem and renv is causing this?

**Comment by shumza-nali** [comment]
https://github.com/rstudio/renv/issues/384#issuecomment-611785515

Found the answer here. I had to specify my RENV_PATHS_LIBRARY in project .Renviron. 

I wonder why I had to do this in the first place? Why was this not the default and the .cache directory was?

**Comment by kevinushey** [comment]
The rationale is described here: https://rstudio.github.io/renv/articles/packages.html#library-paths
