### ISSUE TITLE
`renv::install` fails to install from GitHub when using `curl` 8.7.1

### ISSUE THREAD

**Issue by jabenninghoff** [rstudio/renv#1869]
`renv::install` fails to install from GitHub when using `curl` 8.7.1 on macOS.

To reproduce, create a new project in RStudio on macOS in a new directory, selecting "Use renv with this project" and install the latest version of `curl` using `brew install curl`.

Running:

```r
Sys.setenv(PATH = paste0("/opt/homebrew/opt/curl/bin:", Sys.getenv("PATH")))
renv::install("eddelbuettel/digest")
```

Will fail with an error:

```
Error: failed to resolve remote 'eddelbuettel/digest' -- error downloading 'https://api.github.com/repos/eddelbuettel/digest/contents/DESCRIPTION?ref=ebd25a4bd18f3c5ee786a463cb01d629162cc8f1' [error code 26]
```

A trace shows the call is failing on `renv_remotes_resolve_github_description`. Setting `options(renv.download.trace = TRUE)` fails to provide any additional information.

```
> traceback()
15: stop(simpleError(message = message, call = e$call))
14: h(simpleError(msg, call))
13: .handleSimpleError(function (e) 
    {
        fmt <- "failed to resolve remote '%s'"
        prefix <- sprintf(fmt, spec)
        message <- paste(prefix, e$message, sep = " -- ")
        stop(simpleError(message = message, call = e$call))
    }, "error downloading 'https://api.github.com/repos/eddelbuettel/digest/contents/DESCRIPTION?ref=ebd25a4bd18f3c5ee786a463cb01d629162cc8f1' [error code 26]", 
        base::quote(NULL))
12: stop(sprintf(fmt, ...), call. = call.)
11: stopf("error downloading '%s' [%s]", url, msg, call. = FALSE)
10: renv_download_error(url, "error code %i", status)
9: download(url, destfile = destfile, type = "github", quiet = TRUE, 
       headers = headers)
8: renv_remotes_resolve_github_description(url, host, user, repo, 
       subdir, sha)
7: renv_remotes_resolve_github(remote)
6: renv_remotes_resolve_impl(spec, latest)
5: withCallingHandlers(renv_remotes_resolve_impl(spec, latest), 
       error = error)
4: FUN(X[[i]], ...)
3: lapply(x, f, ...)
2: map(packages, renv_remotes_resolve)
1: renv::install("eddelbuettel/digest")
```

Notes:

- The `PATH` command is for `arm64` macs, the `curl` path will be different for `x86_64`.
- I discovered this issue when GitHub Actions started failing after the release of [macOS-12/20240329.1](https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240329.1), which updates curl from 8.6.0 to 8.7.1
- This will cause any GitHub Action that runs `renv::install` to fail, although `renv::restore` still works
- On the Windows runner, which uses `curl` 8.4.0, `renv::install` succeeds
- See https://github.com/jabenninghoff/jbplot/pull/49 for more detail

**Comment by jabenninghoff** [comment]
As a workaround for GitHub Actions, you can call `Sys.setenv(RENV_DOWNLOAD_METHOD = "libcurl")` before `renv::install()`, as shown in https://github.com/jabenninghoff/rtraining/pull/98 (works on current Windows and macOS runners).

**Comment by kevinushey** [comment]
Thanks for the bug report. I believe this should be resolved by https://github.com/rstudio/renv/commit/565abf4155c6e491563eda784c36482e974ca2f5 -- any chance you could take a look?

**Comment by jabenninghoff** [comment]
Thanks! Installing from the latest commit (https://github.com/rstudio/renv/commit/7f423f98f18e1a69a1fa3ebec0dfffb7db1ba1ce) does resolve the issue, running:

```r
renv::install("rstudio/renv")
# (restart R)
Sys.setenv(PATH = paste0("/opt/home brew/opt/curl/bin:", Sys.getenv("PATH")))
renv::install("eddelbuettel/digest")
```

is successful.
