### ISSUE TITLE
Support for restoring from a snapshot object

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/renv#187]
I think some tools and workflows (say `pins`) would benefit from enabling the following:

```
lirbary(renv)
snapshot() %>% restore()
```

However, currently `restore()` expects a lock file while `snapshot()` generates a lock file and returns a snapshop object.

The fix could be to make `snapshot()` return the path to the lock file, or for `restore()` to support the snapshot object produced by `snapshot()`.

**Comment by kevinushey** [comment]
You can use `restore(lockfile = <...>)` to restore from a lockfile explicitly (as an R object, or path to a lockfile). Is that sufficient?

**Comment by kevinushey** [comment]
I think this should be sufficient:

```
lockfile <- renv::snapshot(...)
renv::restore(lockfile = lockfile)
```

Ultimately this is all possible; just perhaps now with a pipe-able API.
