### ISSUE TITLE
could not find function "heredoc" in renv 1.0.6 activate script

### ISSUE THREAD

**Issue by pascal-sauer** [rstudio/renv#1874]
I believe there is a critical bug in renv 1.0.6. When writing the corresponding renv/activate.R script it contains
```
    fmt <- heredoc("
      renv %1$s was loaded from project library, but this project is configured to use renv %2$s.
      - Use `renv::record(\"%3$s\")` to record renv %1$s in the lockfile.
      - Use `renv::restore(packages = \"renv\")` to install renv %2$s into the project library.
    ")
```
in lines 842+. This fails with an error when the R session starts and the renv version installed is not 1.0.6, because heredoc is not found (it is an unexported function of renv, renv:::heredoc works).

```
Error in heredoc("\n      renv %1$s was loaded from project library, but this project is configured to use renv %2$s.\n      - Use `renv::record(\"%3$s\")` to record renv %1$s in the lockfile.\n      - Use `renv::restore(packages = \"renv\")` to install renv %2$s into the project library.\n    ") : 
  could not find function "heredoc"
```

**Comment by kevinushey** [comment]
Thanks for the bug report -- I was able to reproduce; I'll get this fixed up ASAP.

**Comment by kevinushey** [comment]
Thanks again for reporting -- this should now be resolving with the latest release of renv 1.0.7 on CRAN.
