### ISSUE TITLE
Notes on renv + CI (specifically, travis) ... and bookdown

### ISSUE THREAD

**Issue by jennybc** [rstudio/renv#188]
Notes on my experience wiring renv into the STAT 545 reboot based in https://github.com/rstudio-education/stat545.

I think this could be used to expand the new [short vignette re: CI/CD](https://rstudio.github.io/renv/articles/ci.html). I'm envisioning some some high-level guidance about what to cache (or not) and why, then examples of concrete config files / snippets for important providers. I am also only doing this for a bookdown site right now, so I didn't explore the variant for an R package. Another major point that needs coverage -- maybe it's own vignette? -- is the interaction between renv and `DESCRIPTION`.

---

Here's the current `.travis.yml`:

https://github.com/rstudio-education/stat545/blob/master/.travis.yml

Below I comment on certain features and will inline bits that exist / don't exist as of https://github.com/rstudio-education/stat545/commit/f1feb7f06a2bb2fb3c0379bbc72909e04e0b3f3f. Obviously the file can and probably will continue to evolve.

---

What to put in the CI's cache?

``` yaml
language: r
cache:
  directories:
  - _bookdown_files
  - $HOME/.npm
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
```

Notice the **absence** of the usual `packages: true` here. If the renv-using project is structured properly / in the default way, the usual R package library will not be used. I decided it was best to not cache it, because this will make any use of it more visible and painful and will encourage scrutiny.

`$HOME/.local/share/renv` is [renv's global package cache](https://rstudio.github.io/renv/articles/renv.html#cache). This is the default location for Linux.

`$TRAVIS_BUILD_DIR/renv/library` is the project-specific private library. @jimhester has suggested that I **not** cache this and I think I agree? I almost deleted this line, but it's still there because I want to discuss. If we don't cache this, then every build will rebuild the private library, from the global package cache, triggered by `renv::restore()`. This is fast (~30s for this project) because it's just recreating symlinks. However, I feel like the log will be more informative if we **do** cache the private library, because it makes _changes_ to the library more visible. If we are constantly rebuilding the whole thing, you can't see change. Thoughts?

`_bookdown_files` and `$HOME/.npm` relate to bookdown and Netlify's cli, respectively.

---

Where to install packages from?

I also wanted to get Linux binaries from RSPM. That's what `RENV_CONFIG_REPOS_OVERRIDE` is about here:

```
env:
  global:
    - NETLIFY_SITE_ID=6b6a38b6-7523-4555-965a-fa5cdc9f7157
    # NETLIFY_AUTH_TOKEN set in travis settings
    - RENV_CONFIG_REPOS_OVERRIDE=https://demo.rstudiopm.com/all/__linux__/xenial/latest
```

This setting only appeared in renv v0.7.0-50 and that's a direct result of the stat545 experiment. The usual mechanisms of setting the CRAN repository don't work because renv generally consults the repository indicated in the lock file for this.

Using binaries makes a big difference: if we install from CRAN, it takes 35-40 mins to build & deploy. Using Linux binaries from RSPM brings this down to 13 mins for the first build and to ~6 mins for subsequent builds (that's the benefit of the travis-caching the renv global package cache).

---

Prepare the private library.

``` yams
before_install:
  - export COMMIT_MSG=$(echo "$TRAVIS_COMMIT_MESSAGE" | head -n1)
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${COMMIT_MSG:0:50}"
  - Rscript -e "renv::restore()"
```

The `renv::restore()` line is the one that makes sure the private project library is ready to go. We do this in `before_install`, so it precedes the step where the base r-travis script installs the dependencies discovered from `DESCRIPTION`. I think we expect the `install` step to always be a no-op here (right?). Because you shouldn't be discovering the need to install or upgrade anything based on `DESCRIPTION` that wasn't already embodied in the lock file.

The `export` commands are just preparing some decent messages for the Netlify log.

**Comment by jennybc** [comment]
FYI @topepo 👆

**Comment by kevinushey** [comment]
> $TRAVIS_BUILD_DIR/renv/library is the project-specific private library. @jimhester has suggested that I not cache this and I think I agree? I almost deleted this line, but it's still there because I want to discuss. If we don't cache this, then every build will rebuild the private library, from the global package cache, triggered by renv::restore(). This is fast (~30s for this project) because it's just recreating symlinks. However, I feel like the log will be more informative if we do cache the private library, because it makes changes to the library more visible. If we are constantly rebuilding the whole thing, you can't see change. Thoughts?

I would agree that caching the project library is worthwhile just for the diffs. Is there a reason why caching this might be dangerous? It's indeed normally just a directory full of symlinks so should be safe to cache.

Although this isn't true right now, it's possible that we may want to exclude some packages from `renv`'s cache for some reason, and in such a case one could end up with a mixture of cached and uncached packages in the project library. Caching the project library would ensure those uncached packages could still be saved.

> Using binaries makes a big difference: if we install from CRAN, it takes 35-40 mins to build & deploy. Using Linux binaries from RSPM brings this down to 13 mins for the first build and to ~6 mins for subsequent builds (that's the benefit of the travis-caching the renv global package cache).

I'll confer with @slopp as to whether we would want to advertise using the demo RSPM server in this way, just to be sure we're ready for that public level of promotion / consumption.

> I think we expect the install step to always be a no-op here (right?). Because you shouldn't be discovering the need to install or upgrade anything based on DESCRIPTION that wasn't already embodied in the lock file.

_In theory_, the DESCRIPTION and `renv.lock` could be out of sync, and in such a case the Travis installer might want to re-install packages whose inferred remote did not match that as provided by `renv` (I think). In practice, that shouldn't happen?

**Comment by jennybc** [comment]
I've already seen this happen:

The standard r-travis `install` step, which consults `DESCRIPTION`, has installed a new version of curl into my project, which apparently just incremented from 4.0 to 4.1.

Now travis is building the project with a more recent version of curl from what I’m using locally.
That fact is pretty subtle (I just happen to be reading my travis logs closely right now).

My desired reaction is to upgrade curl in the local project-specific library. It's currently not clear how to make this info flow back to me locally.

But the simplest answer is that, if you're living the renv lifestyle, you also can't let this happen. I.e. you should override the standard `install` step. So this is another consideration for CI if you're trying to ensure that all collaborators and the CI are truly using the same versions.

**Comment by kevinushey** [comment]
I think this is better handled now -- in particular, we advertise doing the following in the [vignette](https://rstudio.github.io/renv/articles/ci.html):

```
cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - Rscript -e "renv::restore()"
  
script:
  - Rscript -e '<your-build-action>'
```

In addition, you can also now pass repositories directly to `renv::restore()` to override the repositories declared in the lockfile, which may be more ergonomic than using an environment variable.

**Comment by ValeriVoev** [comment]
I have followed the advice by @kevinushey above, but I get the following error in Travis:

R session information
1453$ Rscript -e 'sessionInfo()'
1454R version 3.6.2 (2017-01-27)
1455Platform: x86_64-pc-linux-gnu (64-bit)
1456Running under: Ubuntu 16.04.6 LTS
1457
1458Matrix products: default
1459BLAS:   /home/travis/R-bin/lib/R/lib/libRblas.so
1460LAPACK: /home/travis/R-bin/lib/R/lib/libRlapack.so
1461
1462locale:
1463 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
1464 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
1465 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
1466 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
1467 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
1468[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
1469
1470attached base packages:
1471[1] stats     graphics  grDevices utils     datasets  methods   base     
1472
1473loaded via a namespace (and not attached):
1474[1] compiler_3.6.2
14750.17s$ Rscript -e "renv::restore()"
1476Error in loadNamespace(name) : there is no package called ‘renv’
1477Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
1478Execution halted
1479The command "Rscript -e "renv::restore()"" failed and exited with 1 during .

Any help with why this happens would be much appreciated. Thanks

**Comment by kevinushey** [comment]
I believe you need to install `renv` first. This isn't reflected in the CI vignette, so I'll update that.

**Comment by ValeriVoev** [comment]
I managed to make it work in the end with this small addition:
```
install:
  - Rscript -e 'if (system.file(package="renv") == "") install.packages("renv")'
  - Rscript -e "renv::restore()"
```
Thanks
