### ISSUE TITLE
Can't install package from source

### ISSUE THREAD

**Issue by eblchen** [rstudio/renv#1880]
I want to create a renv project with a downgraded version of Seurat and SeuratObject but when I try to install the package from source it outputs the following error.

`> install.packages("Seurat_4.0.5.tar.gz", repos = NULL, type = "source")
Error: failed to resolve remote 'Seurat_4.0.5.tar.gz' -- failed to parse remote spec 'Seurat_4.0.5.tar.gz'`

[Seurat_4.0.5.tar.gz](https://github.com/rstudio/renv/files/15025432/Seurat_4.0.5.tar.gz)

**Comment by kevinushey** [comment]
Try:

```
utils::install.packages("Seurat_4.0.5.tar.gz", repos = NULL, type = "source")
```
