### ISSUE TITLE
renv doesnt use vendored GLPK from igraph

### ISSUE THREAD

**Issue by AmelZulji** [rstudio/renv#1881]
Hello there,

On this system:
```
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
```

During `renv::install("igraph")` i get following error: 

```
# Installing packages --------------------------------------------------------
- Installing igraph ...                         FAILED
/gpfs/bwfor/software/common/math/R/4.3.3-mkl-2022.2-gnu-12.1/lib64/R/bin/R --vanilla -s -f '/gpfs/bwfor/scratch/hd_ut239_o05i14/RtmpLa30XJ/renv-install-252de6f08a42b.R'
================================================================================

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/gpfs/bwfor/home/hd/hd_hd/hd_ut239/test_renv/renv/staging/1/igraph/libs/igraph.so':
  libglpk.so.40: cannot open shared object file: No such file or directory
Calls: loadNamespace -> library.dynam -> dyn.load
Execution halted

Error: error testing if 'igraph' can be loaded [error code 1]
Traceback (most recent calls last):
13: renv::install("igraph")
12: renv_install_impl(records)
11: renv_install_staged(records)
10: renv_install_default(records)
 9: handler(package, renv_install_package(record))
 8: renv_install_package(record)
 7: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 6: renv_install_package_impl(record)
 5: withCallingHandlers(if (isbin) renv_install_test(package), error = function(err) unlink(installpath, 
        recursive = TRUE))
 4: renv_install_test(package)
 3: renv_system_exec(command = R(), args = c("--vanilla", "-s", "-f", 
        renv_shell_path(script)), action = sprintf("testing if '%s' can be loaded", 
        package))
 2: abort(sprintf("error %s [error code %i]", action, status), body = renv_system_exec_details(command, 
        args, output))
 1: stop(fallback)
```

I understand it has to do with missing libglpk. However, `utils::install.packages("igraph") ` is able to install (it shows that it is using vendored GLPK). Is it possible to do it with `renv` as well? 

I have no root, and installing libglpk might not be possible ... 

Thank you and regards,
Amel

**Comment by kevinushey** [comment]
Can you please share the output of:

```
renv::install("igraph", verbose = TRUE, rebuild = TRUE)
```

The installation log is unfortunately not displayed by default if a failure occurs when loading a package (I should change that).

**Comment by kevinushey** [comment]
Actually... I wonder if the issue here is that you're installing a package binary (e.g. from Posit Package Manager), but that binary isn't compatible with your RHEL system?

**Comment by szhorvat** [comment]
> - common/devel/miniconda/3-py39-23.10.0/bin
> - common/devel/miniconda/3-py39-23.10.0/condabin

igraph maintainer here. We strongly recommend to disable any conda environments before compiling igraph. See https://r.igraph.org/articles/installation-troubleshooting.html

Typically what happens is that the build system picks up libraries from within the conda environment. Then when you either update packages in that environment, or disable it, the libraries are no longer found. Anaconda themselves recommend not to have conda's bin directory in the path by default.

**Comment by AmelZulji** [comment]
Hi @szhorvat 

I can confirm that:

1. there was no active conda environment during installation
2. Installation was attempted from R terminal not IDE

My feeling is that `LD_LIBRARY_PATH` is problematic here (i.e. R doesnt properly inherit it when launched)...

**Comment by szhorvat** [comment]
> there was no active conda environment during installation

To be more specific, can you also confirm that conda's `bin` directory was not in your path?

This should not be in your path:

> * common/devel/miniconda/3-py39-23.10.0/bin

This is fine (and necessary for conda to work):



> * common/devel/miniconda/3-py39-23.10.0/condabin

**Comment by szhorvat** [comment]
> My feeling is that `LD_LIBRARY_PATH` is problematic here (i.e. R doesnt properly inherit it when launched)...

That is possible.

**Comment by AmelZulji** [comment]
> To be more specific, can you also confirm that conda's bin directory was not in your path?

yes, I can confirm that as well.

**Comment by kevinushey** [comment]
In case renv is trying to install a binary, you could also try this following:

```
renv::settings$ppm.enabled(FALSE)
renv::install("igraph", type = "source", rebuild = TRUE)
```

**Comment by AmelZulji** [comment]
Thank you for for checking this, @kevinushey and @szhorvat, 
I can confirm that this is related to internal R issue. Namely R is available as module and when it is loaded for some reason `LD_LIBRARY_PATH`. Setting proper `LD_LIBRARY_PATH` in `.Renviron` solved the issue.
