### ISSUE TITLE
Github build-deploy script not working since last week despite no changes - error installing jsonlite

### ISSUE THREAD

**Issue by jzadra** [rstudio/renv#1886]
I have a github build-deploy app that runs nightly.  It ran successfully up until 5 nights ago when it started failing during the "Install R packaged with renv" step.  Specifically, when it tries to install the `jsonlite` package.  Absolutely nothing was changed by me.

<details>
   <summary>Error details</summary>
Installing htmltools [0.5.4] ...
	OK [built from source]
Moving htmltools [0.5.4] into the cache ...
	OK [moved to cache in 7.1 milliseconds]
Installing jsonlite [1.8.4] ...
	FAILED
Error: Error: install of package 'jsonlite' failed [error code 1]
Error installing package 'jsonlite':
====================================

* installing *source* package ‘jsonlite’ ...
** package ‘jsonlite’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
Traceback (most recent calls last):
12: renv::restore()
11: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
10: renv_install_impl(records)
 9: renv_install_staged(records)
 8: renv_install_default(records)
 7: handler(package, renv_install_package(record))
 6: renv_install_package(record)
 5: withCallingHandlers(renv_install_package_impl(record), error = function(e) {
        vwritef("\tFAILED")
        writef(e$output)
    })
 4: renv_install_package_impl(record)
 3: r_cmd_install(package, path)
 2: r_exec_error(package, output, "install", status)
 1: stop(error)
using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c base64.c -o base64.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c collapse_array.c -o collapse_array.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c collapse_object.c -o collapse_object.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c collapse_pretty.c -o collapse_pretty.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c escape_chars.c -o escape_chars.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c integer64_to_na.c -o integer64_to_na.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c is_datelist.c -o is_datelist.o
Execution halted
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c is_recordlist.c -o is_recordlist.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c is_scalarlist.c -o is_scalarlist.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c modp_numtoa.c -o modp_numtoa.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c null_to_na.c -o null_to_na.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c num_to_char.c -o num_to_char.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c parse.c -o parse.o
parse.c: In function ‘R_parse’:
parse.c:38:32: warning: format not a string literal and no format arguments [-Wformat-security]
   38 |       Rf_errorcall(R_NilValue, errbuf);
      |                                ^~~~~~
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c prettify.c -o prettify.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c push_parser.c -o push_parser.o
push_parser.c: In function ‘R_parse_connection’:
push_parser.c:71:14: warning: format not a string literal and no format arguments [-Wformat-security]
   71 |     Rf_error(errbuf);
      |              ^~~~~~
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c r-base64.c -o r-base64.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c register.c -o register.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c row_collapse.c -o row_collapse.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c transpose_list.c -o transpose_list.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c validate.c -o validate.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c yajl/yajl.c -o yajl/yajl.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c yajl/yajl_alloc.c -o yajl/yajl_alloc.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c yajl/yajl_buf.c -o yajl/yajl_buf.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c yajl/yajl_encode.c -o yajl/yajl_encode.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c yajl/yajl_gen.c -o yajl/yajl_gen.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c yajl/yajl_lex.c -o yajl/yajl_lex.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c yajl/yajl_parser.c -o yajl/yajl_parser.o
gcc -I"/opt/R/4.4.0/lib/R/include" -DNDEBUG -Iyajl/api  -I/usr/local/include   -fvisibility=hidden  -fpic  -g -O2  -c yajl/yajl_tree.c -o yajl/yajl_tree.o
ar rcs yajl/libstatyajl.a yajl/yajl.o yajl/yajl_alloc.o yajl/yajl_buf.o yajl/yajl_encode.o yajl/yajl_gen.o yajl/yajl_lex.o yajl/yajl_parser.o yajl/yajl_tree.o
gcc -shared -L/opt/R/4.4.0/lib/R/lib -L/usr/local/lib -o jsonlite.so base64.o collapse_array.o collapse_object.o collapse_pretty.o escape_chars.o integer64_to_na.o is_datelist.o is_recordlist.o is_scalarlist.o modp_numtoa.o null_to_na.o num_to_char.o parse.o prettify.o push_parser.o r-base64.o register.o row_collapse.o transpose_list.o validate.o -Lyajl -lstatyajl -L/opt/R/4.4.0/lib/R/lib -lR
installing to /home/runner/work/beta/beta/renv/staging/1/00LOCK-jsonlite/00new/jsonlite/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) : 
  invalid non-character version specification 'x' (type: double)
Error: Error: unable to load R code in package ‘jsonlite’
Execution halted
ERROR: lazy loading failed for package ‘jsonlite’
* removing ‘/home/runner/work/beta/beta/renv/staging/1/jsonlite’
Error: Process completed with exit code 1.

</details>

I have compared that with my last success run.  The package version of `jsonlite` is the same in both cases (1.8.4).  However, in the successful run, it appears to be installing from cache:
```
Installing jsonlite [1.8.4] ...
	OK [linked cache]
```

Whereas in the failed one, it is downloading:

```
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/jsonlite/jsonlite_1.8.4.tar.gz' ...
	OK [downloaded 1 Mb in 0.1 secs]
```
And then following that is the installation error reported in the details above.   I will note that in the failling one, it appears to be downloading ALL of the packages (whereas before they were all from cache), however it gets through many many successful installs before failing when it gets to `jsonlite`

<details><summary>Here is the header of the log under "Install R packages with renv"</summary>

Run r-lib/actions/setup-renv@v2-branch
  with:
    cache-version: 1
    bypass-cache: false
    working-directory: .
  env:
    BUNDLE_EXT: linux-amd64.deb
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
Run echo "RENV_PATHS_ROOT=/home/runner/work/_temp/renv" >> $GITHUB_ENV
  echo "RENV_PATHS_ROOT=/home/runner/work/_temp/renv" >> $GITHUB_ENV
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    BUNDLE_EXT: linux-amd64.deb
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
Run if (!requireNamespace("renv", quietly=TRUE)) install.packages("renv")
  if (!requireNamespace("renv", quietly=TRUE)) install.packages("renv")
  renv::activate(profile = )
  shell: /usr/local/bin/Rscript {0}
  env:
    BUNDLE_EXT: linux-amd64.deb
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    RENV_PATHS_ROOT: /home/runner/work/_temp/renv
# Bootstrapping renv 0.16.0 --------------------------------------------------
* Downloading renv 0.16.0 ... OK
* Installing renv 0.16.0 ... Done!
* Successfully installed and loaded renv 0.16.0.
ℹ Using R 4.4.0 (lockfile was generated with R 4.2.1)
ℹ Using R 4.4.0 (lockfile was generated with R 4.2.1)
Run cat("os-version=", sessionInfo()$running, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
  cat("os-version=", sessionInfo()$running, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
  cat("r-version=", R.Version()$version.string, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
  shell: /usr/local/bin/Rscript {0}
  env:
    BUNDLE_EXT: linux-amd64.deb
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    RENV_PATHS_ROOT: /home/runner/work/_temp/renv
ℹ Using R 4.4.0 (lockfile was generated with R 4.2.1)
Run actions/cache@v4
  with:
    path: /home/runner/work/_temp/renv
    key: Ubuntu 22.04.4 LTS-R version 4.4.0 (2024-04-24)-1-212791556cc816d2a8dea2a773a849ddb276efee6c8eaec4ced6e37939b73a7e
    restore-keys: Ubuntu 22.04.4 LTS-R version 4.4.0 (2024-04-24)-1-
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
    save-always: false
  env:
    BUNDLE_EXT: linux-amd64.deb
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    RENV_PATHS_ROOT: /home/runner/work/_temp/renv
Cache not found for input keys: Ubuntu 22.04.4 LTS-R version 4.4.0 (2024-04-24)-1-212791556cc816d2a8dea2a773a849ddb276efee6c8eaec4ced6e37939b73a7e, Ubuntu 22.04.4 LTS-R version 4.4.0 (2024-04-24)-1-
Run renv::restore()
  renv::restore()
  shell: /usr/local/bin/Rscript {0}
  env:
    BUNDLE_EXT: linux-amd64.deb
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    RENV_PATHS_ROOT: /home/runner/work/_temp/renv
ℹ Using R 4.4.0 (lockfile was generated with R 4.2.1)
The following package(s) will be updated:
....
</details>

Please let me know if there is anything more I can provide.

**Comment by kevinushey** [comment]
> ℹ Using R 4.4.0 (lockfile was generated with R 4.2.1)

Normally, if you upgrade the version of R used, you should also update the versions of packages used in your lockfile. In this case, it looks like the issue here is that jsonlite 1.8.4 cannot be installed with R 4.4.0; most likely the issue here is resolved by updating to the latest release of jsonlite.

**Comment by jzadra** [comment]
I didn't upgrade anything.  I haven't touched it since it was working last.

**Comment by kevinushey** [comment]
Sure, but I'm guessing your automation tries to install and use the latest-available version of R, rather than explicitly install and use a specific version of R?

**Comment by kevinushey** [comment]
I suspect this comment will be useful: https://github.com/rstudio/renv/issues/1887#issuecomment-2083951600

That is, you can tell the setup-r step to use the version of R encoded in the lockfile via something like:

```
- uses: r-lib/actions/setup-r@v2
    with:
      r-version: renv
```

**Comment by jzadra** [comment]
That did it.  Thank you for educating me!

**Comment by kevinushey** [comment]
Glad I was able to help; sorry for the trouble in the interim!
