### ISSUE TITLE
Inconsistent renv.lock entries

### ISSUE THREAD

**Issue by robertdj** [rstudio/renv#190]
On My Machine &trade; I get entries like this:

```
    "BH": {
      "Package": "BH",
      "Version": "1.69.0-1",
      "Source": "CRAN",
      "RemoteType": "standard",
      "RemoteRef": "BH",
      "RemoteRepos": "https://mran.microsoft.com/snapshot/2019-07-04",
      "RemoteSha": "1.69.0-1",
      "Hash": "0fde015f5153e51df44981da0767f522"
    }
```

On other machines (where `renv` has been installed in the same way on the same R version) the entry for the same packages looks like this:

```
    "BH": {
      "Package": "BH",
      "Version": "1.69.0-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0fde015f5153e51df44981da0767f522"
    }
```

If I restore an environment and then install the packages again, My Machine updates the entries. 

The problem is in particular for packages hosted on an internal CRAN. 
I have followed the advice in <https://github.com/rstudio/renv/issues/120> and the `Repositories` entry in `renv.lock` contains multiple CRANs.

Is there a way to ensure consistency?

**Comment by kevinushey** [comment]
What is the output of:

```
writeLines(readLines(system.file("DESCRIPTION", package = "BH")))
```

on each machine? (Note that some of the formatting here has changed in the most recent updates to `renv` as well so you might want to make sure you're using the same `renv` version on both machines)

**Comment by robertdj** [comment]
Thanks for your quick response! Let me get back to you on Monday with the responses when I have access to both machines.

**Comment by robertdj** [comment]
Over the weekend one of the problematic computers started adding all the `Remote*` fields :thinking:

Which format is the current/expected future?

**Comment by kevinushey** [comment]
Note that if you're install packages using [pak](https://cran.r-project.org/web/packages/pak/index.html), then some extra remote fields are expected. E.g. if I install `rlang` using `pak`:

```
RemoteType: standard
RemoteRef: rlang
RemoteRepos: https://cran.rstudio.com/
RemotePkgType: macos
RemoteSha: 0.4.0
```

In your particular example, I see the same fields except `RemotePkgType` is missing, and I think that's symptomatic of a package that was installed with an earlier buggy version of `renv`. The simplest fix would be to reinstall the package; e.g.

```
renv::install("BH", rebuild = TRUE)
```

should work.

**Comment by robertdj** [comment]
Just to be sure I understand you correctly: Is the current expected format to have the `Remote*` fields or is it to **not** have the `Remote*` fields?

**Comment by kevinushey** [comment]
Both are valid -- it depends on what was used to install the package.

1. If you use `renv` or plain old `utils::install.packages()`, I would expect no remote fields.
2. If you use `pak`, I would expect remote fields as above.

In either case, `renv` should be able to successfully restore the package. In the future, the extra fields passed along by `pak` may be used to allow stricter package restoration (e.g. the package _must_ be installed from the declared repository, as opposed to any of the repositories denoted in the lockfile)

**Comment by robertdj** [comment]
That's odd. I have only used `install.packages` and I get the `Remote*` fields.

**Comment by kevinushey** [comment]
`renv` inserts a shim that re-routes calls to `install.packages()` to `renv::install()`, so that's the most likely explanation there. (This lets you take advantage of `renv`'s package caching even for "default" installation methods)

**Comment by robertdj** [comment]
That makes sense -- thanks!
