### ISSUE TITLE
Did renv v 1.0.5 use posit manager as default repos for installing and updating packages?

### ISSUE THREAD

**Issue by yuanqingye** [rstudio/renv#1904]
When I start a brand new project and using renv to manage the package.

I noticed the downloaded repos is automatically set to repos manager and the renv.lock file also has this setting. So I guess renv by default use posit manager as repos.

However, I noticed all the tutorials (like https://rstudio.github.io/renv/articles/renv.html) seems take cran repos as default.

So Did I make the guess right, or it was because my personal setting I am not awared of changes my repos setting.

**Comment by kevinushey** [comment]
This was a change made in renv 1.0.0:

https://github.com/rstudio/renv/blob/5d0d52c395e569f7f24df4288d949cef95efca4e/NEWS.md?plain=1#L272-L276

So I think that confirms what you're seeing -- if you haven't already explicitly set your R repositories, then `renv` will default to using https://packagemanager.posit.co/cran/latest, unless you opt out via the indicated configuration options.
