### ISSUE TITLE
Place the renv project library not in the project directory

### ISSUE THREAD

**Issue by harrismcgehee** [rstudio/renv#1905]
In the context of project development (c.f. https://rstudio.github.io/renv/articles/packages.html#library-paths), there is a default to move the `renv/library` into the `RENV_PATHS_LIBRARY_ROOT` else `tools::R_user_dir("renv", "cache")`.

It seems like this is all dependent on finding a Project Type of "package" in a `DESCRIPTION` file.
https://github.com/rstudio/renv/blob/5d0d52c395e569f7f24df4288d949cef95efca4e/R/bootstrap.R#L717

Can this be enabled via another envvar or project setting?

**Comment by kevinushey** [comment]
Can you elaborate a bit further? You should be able to set e.g. `RENV_PATHS_LIBRARY` in your project `.Renviron` file if you want to alter the library path for this project (or similarly, `RENV_PATHS_LIBRARY_ROOT`).

**Comment by harrismcgehee** [comment]
Thank you!

I like the behavior of the "Project Type of "package" in a `DESCRIPTION` file" because I will not be able to know which users are going to also use the project, so I won't be able to hard-code the path into the .Renviron for everyone.

Could I instead put `Sys.setenv(RENV_PATHS_LIBRARY_ROOT = tools::R_user_dir("renv", "cache"))` before the `source("renv/activate.R")`?

**Comment by kevinushey** [comment]
Thanks; I think I understand now -- you'd like to use the `renv` cache folder by default for library paths, even for non-package projects.

> Could I instead put Sys.setenv(RENV_PATHS_LIBRARY_ROOT = file.path(tools::R_user_dir("renv", "cache"), "library")) before the source("renv/activate.R") in the project .Rprofile?

This would be a way forward. You could also place this in your R installation's `etc/Rprofile.site`, if you want this to be the default behavior for any of your R sessions.
