### ISSUE TITLE
Dependency discovery can't handle complex `eval` chunk options

### ISSUE THREAD

**Issue by multimeric** [rstudio/renv#1906]
Let's say you have the following nonsensical chunk:

`````rmd
```{r}
#| eval = c(1, 2)
x <- LETTERS
x <- letters
x <- stringi::stri_rand_lipsum()
```
`````

If you save it as "foo.rmd" and run `rmarkdown::render("foo.rmd")` you will note that it works correctly, demonstrating that this uses valid syntax.

However, if you run `renv::dependencies()`:
```
Finding R package dependencies ... Done!
[1] Source  Package Require Version Dev
<0 rows> (or 0-length row.names)
Warning message:
In if (value %in% c("TRUE", "True", "true", "T", "1")) TRUE else if (value %in%  :
  the condition has length > 1
```

Specifically this happens because when we reach the following line, `value` is a vector of `c(1, 2)`, and so the `if` gets a length-2 argument: 
https://github.com/rstudio/renv/blob/568e8cc0a7344b7dc54c5a928c153937af61a999/R/truthy.R#L20

**Comment by kevinushey** [comment]
Thanks -- should now be resolved in the development version of `renv`.
