### ISSUE TITLE
Different versions using source("renv/activate.R") vs renv::load()

### ISSUE THREAD

**Issue by elgabbas** [rstudio/renv#1909]
Hello,

I am using renv in an HPC. I noticed that I am getting different versions of renv loaded if I add `source("renv/activate.R")` or `renv::load()` in the `.Rprofile` file.

```
source("renv/activate.R")
# - Project '******' loaded. [renv 1.0.7]

renv::load()
# - Project '******' loaded. [renv 1.0.3]
```
I tried using `renv::upgrade` to update renv but it took a long time to start (until I quit it) and did not show any results.
The installed version of renv `packageVersion("renv")` is 1.0.3. Using `renv::update("renv")` or `update.packages("renv")` does not show any updates.

I am using R version 4.3.2.

Thanks.

**Comment by kevinushey** [comment]
This is probably expected? The activate script makes sure to use the version of `renv` installed in the project library. If you just use `renv::load()`, then the version of `renv` being loaded is likely the one from your default library paths, which most likely has an older version of `renv` installed.

> Using renv::update("renv") or update.packages("renv") does not show any updates.

That seems odd to me, given that the latest version of `renv` on CRAN is 1.0.7. What package repositories are you using?

**Comment by elgabbas** [comment]
Thanks @kevinushey. Now I get it. 
I expected that renv always uses the installed version within the renv folder. Without explicitly sourcing the `renv/activate.R` file, R/renv loads the default library version which is maintained by the HPC administration.
