### ISSUE TITLE
renv_retrieve_incompatible() error - record argument is causes error

### ISSUE THREAD

**Issue by erssec** [rstudio/renv#1911]
Hi. 

I get a 'Error in record$Version : $ operator is invalid for atomic vectors' error when restoring an renv environment. This is the traceback

`13. renv_retrieve_incompatible(remote, record)
12. renv_retrieve_successful_recurse_impl_check(remote)
11. renv_retrieve_successful_recurse_impl(remote)
10. renv_retrieve_successful_recurse(deps)
9.(function() {
    repos <- if (is.null(desc$biocViews)) 
        getOption("repos")
    else renv_bioconductor_repos() ...
8. renv_retrieve_successful(record, path)
7. renv_retrieve_package(record, url, path)
6. renv_retrieve_github(record)
5. renv_retrieve_impl(package)
4. handler(package, renv_retrieve_impl(package))
3. retrieve(packages)
2. renv_restore_run_actions(project, diff, current, lockfile, rebuild) at <tmp>#70
1. renv::restore(clean = TRUE)`

How can this error be solved?

**Comment by kevinushey** [comment]
Can you please share your lockfile?

**Comment by erssec** [comment]
Apologies, I should have included that from the beginning. This is the renv.lock file. I am using renv 1.0.7 and R 4.3.1.
[renv.lock.txt](https://github.com/rstudio/renv/files/15444823/renv.lock.txt)

**Comment by kevinushey** [comment]
Thanks! I wasn't able to reproduce locally, unfortunately. I wonder if you could try again with:

```
trace(renv:::renv_retrieve_incompatible, quote(print(utils::ls.str())))
renv::restore()
```

and let me know what output you see?

**Comment by erssec** [comment]
Thank you @kevinushey. This is the last few lines before running into the error:

```
Tracing renv_retrieve_incompatible(remote, record) on entry 
package :  chr "dplyr"
record : List of 7
 $ Package     : chr "dplyr"
 $ Version     : chr "1.1.2"
 $ Source      : chr "Repository"
 $ Repository  : chr "CRAN"
 $ Requirements: chr [1:14] "R" "R6" "cli" "generics" ...
 $ Hash        : chr "dea6970ff715ca541c387de363ff405e"
 $ Path        : chr "/home/rstudio/.cache/R/renv/source/repository/dplyr/dplyr_1.1.2.tar.gz"
Tracing renv_retrieve_incompatible(remote, record) on entry 
package :  chr "sf"
record : List of 7
 $ Package     : chr "sf"
 $ Version     : chr "1.0-14"
 $ Source      : chr "Repository"
 $ Repository  : chr "CRAN"
 $ Requirements: chr [1:14] "DBI" "R" "Rcpp" "classInt" ...
 $ Hash        : chr "e2111252a76984ca50bf8d6314348681"
 $ Path        : chr "/home/rstudio/.cache/R/renv/source/repository/sf/sf_1.0-14.tar.gz"
Tracing renv_retrieve_incompatible(remote, record) on entry 
package :  chr "Matrix"
record :  logi NA
Error in record$Version : $ operator is invalid for atomic vectors
```

I am running all of this in a docker container bioconductor/bioconductor_docker:3.18-R-4.3.1. 

Only installing Matrix using restore(package= c('Matrix')) works flawless.

**Comment by kevinushey** [comment]
Thanks -- I've pushed a potential fix in https://github.com/rstudio/renv/commit/78082339350e03463e978dc7aa1a9d6a0cfad061; would you be able to test with the development version of `renv`?

**Comment by erssec** [comment]
Thank you @kevinushey . This fix works for me.

**Comment by kevinushey** [comment]
Great! Thanks for taking the time to confirm.
