### ISSUE TITLE
renv::restore() terra installation fails

### ISSUE THREAD

**Issue by marcelglueck** [rstudio/renv#1913]
Dear Kevin,

some time ago, I encountered an [issue](https://github.com/rstudio/renv/issues/1809) with restoring a reproducible environment that was successfully troubleshot by you. 

Now, unfortunately, I stumbled upon another issue in restoring a reproducible environment. This time with renv 1.0.3 and terra 1.7-18. Interestingly, this issue did not pop up in earlier restoring processes with the same renv and terra versions, but I encountered it the first time today. 

Here the prompts generated in trying to restore the reproducible environment:

```R
- Installing terra ...                          FAILED
Error: Error installing package 'terra':
=================================

* installing *source* package 'terra' ...
** package 'terra' successfully unpacked and MD5 sums checked
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
rm -f terra.dll RcppExports.o RcppFunctions.o RcppModule.o arith.o crs.o distRaster.o distance.o extract.o file_utils.o focal.o gcp.o gdal_algs.o gdal_multidimensional.o gdalio.o geodesic.o geos_methods.o geosphere.o math_utils.o mediancut.o memory.o movingWindow.o ncdf.o ram.o raster_methods.o raster_stats.o rasterize.o read.o read_gdal.o read_ogr.o sample.o sort.o spatBase.o spatDataframe.o spatFactor.o spatRaster.o spatRasterMultiple.o spatSources.o spatTime.o spatVector.o spatVector2.o string_utils.o vecmath.o vecmathse.o vector_methods.o write.o write_gdal.o write_ogr.o
mkdir -p ../inst
"C:/PROGRA~1/R/R-41~1.1/bin/x64/Rscript.exe" --vanilla "../tools/winlibs.R" 3.4.1
Warning message:
In unzip("lib.zip", exdir = "../windows") :
  error 1 in extracting from zip file
cp -r "../windows/gdal3-3.4.1/share/gdal" ../inst/
cp: cannot stat '../windows/gdal3-3.4.1/share/gdal': No such file or directory
make: *** [Makevars.win:28: winlibs] Error 1
ERROR: compilation failed for package 'terra'
* removing 'C:/Users/Zoologie/Desktop/BEpipeR_test/renv/staging/1/terra'
install of package 'terra' failed [error code 1]
```

The important entries from the lockfile are:

```R
"R": {
    "Version": "4.1.1",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
}

<shortened>

"terra": {
  "Package": "terra",
  "Version": "1.7-18",
  "Source": "Repository",
  "Repository": "CRAN",
  "Requirements": [
    "R",
    "Rcpp",
    "methods"
  ],
  "Hash": "5db3d690ad42a1828d3bf9e063c98587"
},
```

Is this an issue that might be resolved by updating renv to the newest release?

Thanks for your help!

**UPDATE**
I searched the internet and found [this issue](https://github.com/rstudio/renv/issues/1832#issuecomment-2076049132). However, in my opinion, the solution suggested does not really solve my issue, because my lock file already points to the correct repository (see above). Please correct me, if I am mistaken.

**Comment by kevinushey** [comment]
Based on this error:

```
"C:/PROGRA~1/R/R-41~1.1/bin/x64/Rscript.exe" --vanilla "../tools/winlibs.R" 3.4.1
Warning message:
In unzip("lib.zip", exdir = "../windows") :
  error 1 in extracting from zip file
```

I would guess that something went wrong either when downloading or unpacking the underlying library that the terra configure script wants. It uses code like:

```
# Download gdal-3.* from rwinlib
VERSION <- commandArgs(TRUE)
testfile <- sprintf("../windows/gdal3-%s/include/gdal-%s/gdal.h", VERSION, VERSION)
if(!file.exists(testfile)){
	download.file(sprintf("https://github.com/rwinlib/gdal3/archive/v%s.zip", VERSION), "lib.zip", quiet = TRUE)
	dir.create("../windows", showWarnings = FALSE)
	unzip("lib.zip", exdir = "../windows")
	unlink("lib.zip")
}
```

So perhaps the download is quietly failing? I'm not sure if this is still an issue with the latest release of terra, though -- is updating an option?

**Comment by marcelglueck** [comment]
Thanks for your fast reply and for digging deeper into the underlying code. 

In February this year, installing the exact same version of terra through renv 1.0.3 did work. Since then, the version of terra requested and encoded in the lock file did not change. Also, https://github.com/rwinlib/gdal3/archive/v%s.zip should correctly be expanded to https://github.com/rwinlib/gdal3/archive/v3.4.1.zip, which is available. 

The suggestion of a quietly failing download is a good one. While downloading the packages through renv, my internet connection was not the best. On Friday, I will try again and let you know.

**Comment by kevinushey** [comment]
Let me know how it goes. Unfortunately, the use of `download.file(..., quiet = TRUE)` implies that we won't get any feedback if the download did indeed fail, so this is mostly speculation. For what it's worth, I was able to install that version of terra locally, so I suspect it could indeed have been related to intermittent internet connectivity.

**Comment by marcelglueck** [comment]
Today, I successfully restored the reproducible environment while being connected to the internet through a LAN cable. Hence, it seems that a quietly failed download caused this issue. Thanks for pointing me in the right direction!

**Comment by kevinushey** [comment]
Great news; thanks for confirming!
