### ISSUE TITLE
Error with 0.7.0-87 on renv::restore()

### ISSUE THREAD

**Issue by austingrosel** [rstudio/renv#193]
I've been seeing an error with `renv 0.7.0-87` when trying to restore the packages on a new machine. 

I have a project that loads a few libraries and builds a data frame. I am using `R 3.6.0` and the command in the terminal that I use is `Rscript Restart.R`.

The error that shows is:
```
Error in vapply(x, f, ..., FUN.VALUE = character(1)) : 
  values must be length 1,
 but FUN(X[[2]]) result is length 0
Calls: <Anonymous> ... renv_pretty_print_records_impl -> lapply -> FUN -> map_chr -> vapply
Traceback (most recent calls first):
8: renv::restore()
7: renv_restore_report_actions(diff, current, lockfile)
6: renv_pretty_print_records_pair(lhs[names(lhs) %in% names(actions)], 
       rhs[names(rhs) %in% names(actions)], "The following package(s) will be updated:")
5: renv_pretty_print_records_impl(old, new)
4: lapply(sort(unique(groups)), function(group) ...)
3: FUN(X[[i]], ...)
2: map_chr(nms, function(nm) {
       renv_record_format_pair(lhs[[nm]], rhs[[nm]])
   })
1: vapply(x, f, ..., FUN.VALUE = character(1))
```

The following zip file has the `renv.lock` file, the `renv/activate.R` file and the `Restart.R` file.
[RenvFiles.zip](https://github.com/rstudio/renv/files/3636186/RenvFiles.zip)

According to this post (#138), I reverted my `renv/activate.R` file to activate version `0.6.0-103` and in `Restart.R`, switched the `remotes::install_github("rstudio/renv")` to `remotes::install_github("rstudio/renv@0.6.0-103")`. This worked! 

So `0.6.0-103` seems to be working, but `0.7.0-87` seems to be breaking.

I'm new to `renv` so it's very possible I'm doing something wrong with the new package version, but I'm curious if this is just a new bug.

**Comment by kevinushey** [comment]
I believe this is a new bug -- it looks like I introduced a bug in the formatting code (which @jimhester kindly just contributed a PR to fix). Hopefully fixed in the latest build.

**Comment by austingrosel** [comment]
Thanks for the quick response! I will use 0.6.0 in the meantime.
