### ISSUE TITLE
Rstudio's knit button does not use project's renv

### ISSUE THREAD

**Issue by josiekre** [rstudio/renv#194]
Knitting each chunk by hand sends code to the console in Rstudio. This code executes with the project's `renv`. However, hitting the `knit` button seems to be using the local computer's environment. How do I make sure the `knit` button uses the project's `renv` if it exists?

**Comment by kevinushey** [comment]
This looks like a bug in `renv`. I'll see if I can figure out what's going on.

**Comment by kevinushey** [comment]
I believe this should be fixed in the latest version of `renv` on master. Please feel free to re-open if you're still seeing trouble after upgrading. Thanks!

**Comment by josiekre** [comment]
I upgraded to v0.7.0-108 and still see this issue. i.e. I see `renv.lock` updated to "0.7.0-108" but a call to a library *not* installed in its `/renv` still works.

**Comment by subramv** [comment]
Having a similar issue with v0.12. `Knit` button + buttons in Build pane (e.g. `Clean and Rebuild` and `Install and Restart`) seem to check the default library for dependencies and attempt to install the package into that default library, as opposed to using and installing to the `renv` library. Calling `rmarkdown::render()`, `devtools::build`, or `devtools::install` in the console use the `renv` library as expected. 

1. Is there a way to set the RStudio buttons to use the `renv` library path? `Use renv with this project` is checked under Configure Build Tools -> Environments. 
2. On a similar note, what is the recommended method for installing local packages to the global cache for future use? Is it to build a source and then install within a separate project? 

Thanks!
