### ISSUE TITLE
headers not considered in function `renv_bootstrap_download_cran_latest_find` when retrieving package database

### ISSUE THREAD

**Issue by siri16100** [rstudio/renv#1942]
Hi @kevinushey  as mentioned in #1084  I use `renv` together with artifactory and have problems when bootstrapping. I debugged into `renv\activate.R` and found the potential problem in function `renv_bootstrap_download_cran_latest_find`. The function tries to retrieve the package database:
```
utils::available.packages(type = type, repos = repos),
````
this is (e.g. when using artifactory) not possible, as no headers are provided in function `available.packages`. Experimentally, I changed the line into:
```
utils::available.packages(type = type, repos = repos, headers = renv_bootstrap_download_custom_headers(repos))
```
and all worked fine. 

Maybe you have the chance to look into this?

**Comment by kevinushey** [comment]
Thanks! Should be fixed up via https://github.com/rstudio/renv/commit/0f0ad9dc8e355bc9970be6a86d28fce702fe29a6.

**Comment by bruceskarin** [comment]
Greetings, We're having some issues around this as well, thanks for fixing it! Any chance you can get it out in a release? We  unfortunately can't install dev versions.

**Comment by kevinushey** [comment]
Thanks for the nudge -- I can look into preparing a release soon.

**Comment by siri16100** [comment]
Hi @kevinushey  I just had the chance to test this but still having trouble to get this running. Problem imho is function `renv_bootstrap_download_cran_latest_find` which calls `renv_bootstrap_download_custom_headers(url)` but function argument url has not jet been set. It worked for me by change the order of execution 
```r
 renv_bootstrap_download_cran_latest <- function(version) {
    
    baseurl <- utils::contrib.url(repos = repos, type = type)
    ext <- if (identical(type, "source"))
      ".tar.gz"
    else if (Sys.info()[["sysname"]] == "Windows")
      ".zip"
    else
      ".tgz"
    name <- sprintf("renv_%s%s", version, ext)
    url <- paste(baseurl, name, sep = "/")
    
    spec <- renv_bootstrap_download_cran_latest_find(version)
    type  <- spec$type
    repos <- spec$repos
    
    destfile <- file.path(tempdir(), name)
    status <- tryCatch(
      renv_bootstrap_download_impl(url, destfile),
      condition = identity
    )
    
    if (inherits(status, "condition"))
      return(FALSE)
    
    # report success and return
    destfile
    
  }
```

**Comment by kevinushey** [comment]
Thanks -- I think https://github.com/rstudio/renv/commit/5725cdee36c6d0b8c32fef4f0bd4b4e1da9e73e2 should also fix the issue; I chose to pass the repository URL when retrieving custom headers in this case.

**Comment by siri16100** [comment]
@kevinushey  thanks for fixing this, as far as I was able to test den dev version it does work now. Any chance you can get it out in a release?

**Comment by kevinushey** [comment]
Thanks for testing! I'll try to get a patch release out soon.
