### ISSUE TITLE
Allow for "Github only" packages in DESCRIPTION when calling `install()`

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#195]
Calling `renv::install()` on a package with a DESCRIPTION file listing a "pure" Github package (i.e. in one of IMPORTS || SUGGESTS) AND under REMOTES but not on CRAN fails with 

`Error: failed to parse remote 'renv' -- package 'renv' is not available on CRAN`

This only applies to packages which are not on CRAN at all - otherwise `renv` correctly uses the GH version from the ones listed under REMOTES.

Reprex: 
- Add `renv` to SUGGESTS and `rstudio/renv` to REMOTES and call `renv::install()`

**Comment by kevinushey** [comment]
Thanks! I've reproduced this and will take a look.
