### ISSUE TITLE
renv does not include remote libraries in lock file

### ISSUE THREAD

**Issue by matt-jay** [rstudio/renv#1962]
I am using a DESCRIPTION file for my R project to define required libraries that I want to manage with `renv`.

My `DESCRIPTION` file looks like this:

```
Type: project
Description: Analysis project
Imports:
    clipr,
    docstring,
    dplyr,
    echarts4r,
    fs,
    janitor,
    lubridate,
    plyr,
    purrr,
    readxl,
    remotes,
    reshape2,
    rlang,
    stringdist
    stringr,
    tidyr,
    tidyverse,
    writexl
Remotes: gitlab::hrbrmstr/pluralize
```

The library defined in the `Remotes` section is not included in the lock file, however, when I run `renv::snapshot()`. `renv::dependencies()` yields all libraries in the `Imports` section, but ignores the entry in the `Remotes` section. Can anyone explain why this happens?

**Comment by remlapmot** [comment]
For a package, the remote packages need to be listed in either the Imports or Suggests field as well as in the Remotes field.

So try adding `pluralize` to your Imports list (and keep it in Remotes as you have it).
