### ISSUE TITLE
separate download step from install step in `renv::restore`?

### ISSUE THREAD

**Issue by natlownes** [rstudio/renv#1965]
Hi

I was wondering if it's possible to separate the download step from the install step? The use case is I'm trying to create an image of a large and fussy R project. It would be cool to cache the result of "downloading 40% of the R packages ever created in the course of human history" step before trying to build them

Thanks for all you do

**Comment by kevinushey** [comment]
Thanks! I've implemented this in the development version of `renv`; you should now be able to use something like:

```
renv::retrieve()
renv::restore()
```

and the `renv::restore()` step will use the packages downloaded in the first `retrieve()` step.

**Comment by natlownes** [comment]
wow thank you so much this is incredible. if I run into any issues I'll open a PR. really appreciate this
