### ISSUE TITLE
RENV_PATHS_RENV interaction with DESCRIPTION file

### ISSUE THREAD

**Issue by simmonsja** [rstudio/renv#1978]
Hi, 
While making use of the `RENV_PATHS_RENV` environment variable to specify a custom location for the project's renv folder, I came across an unexpected interaction with the DESCRIPTION file. When renv detects from DESCRIPTION that the type is a package it changes the renv folder to a path relative to `%LOCALAPPDATA%/R/cache/R/renv`, instead of using the specified `RENV_PATHS_RENV` path.

Reading through the source I was able to manually set "Type: unknown" in DESCRIPTION to force the correct path. I don't know enough about the expected behaviour to know what a package type implies (and the treatment in `renv::renv_bootstrap_project_type()`). So not sure if anything needs to be changed or maybe it is just an extra line in the documentation to note the behaviour?

Min working example:

```r
print(renv::paths$library())
# create a folder called my_env
dir.create("my_env")
# create an .Renviron file
envfile <- file(".Renviron")
writeLines(
    c("RENV_PATHS_RENV = 'my_env'"),
    envfile
)
close(envfile)
readRenviron(".Renviron")
# check again - now it uses the RENV_PATHS_RENV path
print(renv::paths$library())

# now add a description file
usethis::use_description()
# check again - path has changed
print(renv::paths$library())

# modify the description file
unlink("./DESCRIPTION")
usethis::use_description(fields=list(Type="unknown"))
# check again - fixed the path
print(renv::paths$library())
```

```r
Diagnostics Report [renv 1.0.7]
===============================

# Session Info ---------------------------------------------------------------
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)
```

**Comment by kevinushey** [comment]
`renv` normally treats the existence of a `DESCRIPTION` file as a hint that the project is an R package, and so uses alternate library paths in this scenario. The rationale is described in https://rstudio.github.io/renv/articles/packages.html#library-paths.

If you want to avoid this behavior; that is, you want to use a DESCRIPTION file but your project is not an R package, then setting `Type: project` or something similar is indeed the right solution.

**Comment by simmonsja** [comment]
Ah I see! Okay makes sense reading that link - I was focussed on the paths.R docs. Will close this out and hopefully useful to others if they're similarly trying to use RENV_PATHS_RENV.
Thanks Kevin
