### ISSUE TITLE
Docker build using MRAN when it shouldn't

### ISSUE THREAD

**Issue by jbixon13** [rstudio/renv#199]
Hi, thank you for your contribution and an awesome tool.

 I'm able to locally `init()` and `restore()` without issue, but when using `restore()` in a docker build I get an error indicating a 404 error when trying to reach the MRAN repository for a package (BH). I find this strange since the renv.lock file specifies a CRAN repository for all packages. 

I see a similar problem was faced here: https://github.com/rstudio/renv/issues/43 with a workaround of using `chooseCRANmirror()`. This does not solve my problem and the same error persists. Any guidance is appreciated. 

Additional info:
OS: Windows 10 
Example from renv.lock: 
  "Packages": {
    "BH": {
      "Package": "BH",
      "Version": "1.69.0-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "88e64b38758666b85d283617231bb766"
    },

**Comment by kevinushey** [comment]
`renv` will use the repositories as recorded in the Repositories field. Can you post the whole lockfile?

For example, with a lockfile containing only `renv`:

```
{
  "R": {
    "Version": "3.6.1",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.7.0-108",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "rstudio",
      "RemoteRepo": "renv",
      "RemoteRef": "master",
      "RemoteSha": "0e8cc1bb57d24e57611813731c291a11d5bbcf01",
      "Hash": "9d3bf756b6f5629f6134a7fe0e5a0a34"
    }
  }
}
```

I suspect your Repositories field contains MRAN. If that's not the case, then the usage of MRAN must be getting enforced from some place outside of `renv`.

**Comment by jbixon13** [comment]
Here's my lockfile: https://github.com/jbixon13/shinyhero/blob/master/renv.lock 
* I see no mention of MRAN in the lockfile

Here's my Dockerfile: https://github.com/jbixon13/shinyhero/blob/master/Dockerfile

Here's my error on docker build:
![image](https://user-images.githubusercontent.com/32110237/65737392-5ebdbb00-e0ac-11e9-9b83-4d0ebb3dabde.png)

**Comment by kevinushey** [comment]
It looks like there's two things going on:

1. The Docker image you're using uses a MRAN snapshot as the default CRAN mirror. This is documented at https://hub.docker.com/r/rocker/r-ver.

2. You don't copy the `.Rprofile` to the Docker build, so `renv` does not get automatically activated. This means the project doesn't get loaded, and the repositories set in the lockfile don't get used.

Right now, `renv` sets the repositories when a project is loaded, as opposed to when `renv::restore()` is called. Perhaps that behavior should be changed.

**Comment by kevinushey** [comment]
I've just made a change to `renv` master that should ensure `renv::restore()` works as you expect now. Let me know if you're still having any trouble.

**Comment by jbixon13** [comment]
Thank you! I'm playing around with my dockerfile at the moment, still a little wonky of a process to me even if I've used Linux before. I'll pull down the update and see if that resolves. Thanks for the quick responses!

**Comment by jbixon13** [comment]
Progress has been made on one hand: I updated my dockerfile to properly run renv through .Rprofile. Now when I run `renv::restore` the command returns with `"The library is already synchronized with the lockfile."` Maybe I am misunderstanding if this is an expected behavior but this shouldn't be accurate because there are no packages loaded to the Docker image. 

![image](https://user-images.githubusercontent.com/32110237/65744569-be28c480-e0c6-11e9-8304-373371926d3d.png)

When I try adding `renv::rebuild()` after, I get similar errors to my original setup (cannot access MRAN)

![image](https://user-images.githubusercontent.com/32110237/65744706-24ade280-e0c7-11e9-8eff-2b8b7f39c561.png)

**Comment by kevinushey** [comment]
I think the problem is that your Dockerfile now only copies the Shiny application files itself, not the `renv` lockfile. Here:

https://github.com/jbixon13/shinyhero/blob/master/Dockerfile#L19-L23

When you set `WORKDIR`, that also affects the paths used by `COPY`. To make that concrete, if I try running `find .` in your Dockerfile, I see:

```
Step 8/10 : RUN find .
 ---> Running in 4f2106747b10
.
./global.R
./ui.R
./server.R
```

**Comment by jbixon13** [comment]
Thinking about it further, it would actually make sense to output that the library is up to date if the renv/library folder is copied to the docker image. 

That would then still not explain why when I try running `shiny:runApp()` shiny is not installed. Unless it has to do with where library is loaded/where R expects packages to be? Not familiar enough with this in a Docker context.

**Comment by jbixon13** [comment]
That makes sense, I had thought that was setting the directory at the higher level since they're named the same thing. I think if I push that down to just before I run `runApp()` that should resolve, unless that working directory is needed for anything `renv`-related. Thanks again
