### ISSUE TITLE
Mention the support for .ipynb files in renv::dependencies

### ISSUE THREAD

**Issue by modosist** [rstudio/renv#1995]
I believe that support for extracting libraries from ipynb files should be mentioned in the documentation (especially the `path` argument in the `renv::dependencies` function). It is a feature, after all. :) If I were to consider adopting renv for our company based solely on the documentation, I might reject the package, as we use Jupyter extensively (for both Python and R projects), which would be a shame.

By the way, thank you for an amazing package—it is really useful for tracking project dependencies.

**Comment by kevinushey** [comment]
Thanks for the kind words and the documentation nudge! I added a blurb to the documentation in https://github.com/rstudio/renv/commit/5961a60616157815766af052bfe6b9c2dd49e112.
