### ISSUE TITLE
`renv::dependencies()` has become slow in release 1.0.8

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [rstudio/renv#1999]
With 1.0.8, `renv::dependencies()` takes 15-20 seconds to run. On the same project with 1.0.7, it used to be 2-3 seconds.

**Comment by kevinushey** [comment]
Thanks for the bug report; I was able to reproduce. I'll take a look.

**Comment by kevinushey** [comment]
I've made a number of optimizations to the implementation of `renv::dependencies()` in https://github.com/rstudio/renv/commit/16c05d5484f7d1936cb22f0de944f9e80c6d02e0; any chance you could give it a download and let me know how things look? You can use e.g. `renv::install("rstudio/renv")` to install the development version of `renv` for testing.

**Comment by HenningLorenzen-ext-bayer** [comment]
> I've made a number of optimizations to the implementation of `renv::dependencies()` in [16c05d5](https://github.com/rstudio/renv/commit/16c05d5484f7d1936cb22f0de944f9e80c6d02e0); any chance you could give it a download and let me know how things look? You can use e.g. `renv::install("rstudio/renv")` to install the development version of `renv` for testing.

Great work! The optimized version not only beats v1.0.9 but also v1.0.7. 💪 

| | Setup 1 | Setup 2 |
|-|-----|----|
| 1.0.7 | 2.8s | 4.6s |
| 1.0.9 | 7.5s | 23.4s |
| 16c05d5 | 1.9s | 3.0s |

**Comment by kevinushey** [comment]
Awesome news :-) Thanks for reporting back!
