### ISSUE TITLE
Package not added to lockfile

### ISSUE THREAD

**Issue by maximecharriere** [rstudio/renv#2001]
I have a project with already a renv.lock file. The devtools and openxlsx2 package are not in it, but are used in the R script `./scripts/main.R`.  
I did `renv.install("devtools")`.  
I did `renv::dependencies()` that shows that devtools and openxlsx2 are used: 

| ID | Source | Package | Require Version | Dev |
| ---|---|---|---|---|
| 31 | C:/.../scripts/main.R |devtools | | FALSE |
| 32 | C:/.../scripts/main.R |openxlsx2| | FALSE |  

however, when I do `renv::snapshot()`, devtools and openxlsx2 is not added to the lockfile.  

Any idea ?

Edit: 
It seams that all package used in files in `./R/<filename>.R` are added, but not for the scripts in `./scripts/<filename>.R`.

**Comment by kevinushey** [comment]
Any chance you can share a standalone reproducible example?

**Comment by maximecharriere** [comment]
I found, when creating my standalone reproducible example, that RStudio set the renv setting `snapshot.type` to `explicit`. Changing it to `implicit` solved my issue.  

As devtools and openxlsx2 are not directly used by my package, but by independent scripts, they were not listed in a DESCRIPTION file. Therefore, `renv::dependencies()` was listing devtools and openxlsx2, but renv::snapshot() was not adding them.
