### ISSUE TITLE
reduce the size of the renv cache

### ISSUE THREAD

**Issue by pedriniedoardo** [rstudio/renv#2004]
Hello,
I am working on a machine where the home folder has a cap on the space I can use.
I have noticed that removing the content of the `binary` and `source` folders in `~/.cache/R/renv` could free a considerable amount of space.
Is it safe to remove the files in those folders?

Also, what would be the recommendation for working with `renv` in a situation like mine (home with a capped space)? Is it possible to migrate the current `~/.cache/` folder to another location while some projects are still active/linked (not breaking everything)?

Otherwise, I am considering isolating (`renv::isolate`) each project (which is not in home) and then pruning the oldest packages to save some space, but, again, I would like not to break anything.
Would you happen to have any suggestions or recommendations?

**Comment by kevinushey** [comment]
>  I have noticed that removing the content of the binary and source folders in ~/.cache/R/renv could free a considerable amount of space. Is it safe to remove the files in those folders?

Those can be safely removed. They're mainly used if you need to reinstall older source / binary packages, but often they're not needed if you already have cached installations available.

> Also, what would be the recommendation for working with renv in a situation like mine (home with a capped space)? Is it possible to migrate the current ~/.cache/ folder to another location while some projects are still active/linked (not breaking everything)?

See the documentation in https://rstudio.github.io/renv/reference/paths.html -- you can customize the paths that `renv` uses for almost all of the data it stores or uses. In this case, you would probably want to set `RENV_PATHS_CACHE` in an appropriate R startup file.
