### ISSUE TITLE
Infer dependency on `lintr`

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#2005]
Not sure how widely valuable this would be, but I was thinking it'd be nice if `renv` could infer a dependency on `lintr` when it encounters a `.lintr` file in a project.

For now, I might just put 
```R
if (FALSE) library(lintr)
```

in my `.Rprofile`

**Comment by kevinushey** [comment]
Seems reasonable, but I suspect you'd normally want it picked up as a development dependency, not a "regular" dependency? Do you want the version to be tracked and used in the lockfile?

**Comment by hutch3232** [comment]
Awesome! Yeah that makes sense to me that it should be picked up as a development dependency in this case where's it's implicitly found. 

> Do you want the version to be tracked and used in the lockfile?

I don't have much of an opinion. I guess whatever is consistent with other dev packages like `devtools` and `testthat`. In this case, would it be installed if I run `renv::restore()` or would I need to do something else to get dev pkgs too? (I don't have a DESCRIPTION file).

**Comment by kevinushey** [comment]
> In this case, would it be installed if I run renv::restore() or would I need to do something else to get dev pkgs too? (I don't have a DESCRIPTION file).

In this scenario, a plain:

```
renv::install()
```

would install `lintr`, and any other development dependencies detected in the project, but it would not normally become part of the lockfile unless it were explicitly used in the project. The rationale here being, you likely don't need to track the version of `lintr` used specifically, since it's not a "runtime" dependency of the project.

**Comment by hutch3232** [comment]
That sounds great, thank you! I did have a thought related to this. `renv::settings$ignored.packages()` allows explicitly ignoring packages. What if there was a companion like `extra.packages` or something so that in "implicit" tracking packages you could still throw in a few you want to include. That could have been an approach for handling `lintr`.

Another example is the optional dependency of `R.utils` in `data.table` to be able to read `.gz` files. Currently I just fake it with:
`if (FALSE) library(R.utils)` but it would be nice to somehow include it with a generic/general approach.

If this approach was taken, I think it would be good if `renv::dependencies()` reported that it was finding it via this setting.

**Comment by kevinushey** [comment]
In this scenario, I lean towards using "explicit" snapshots, and manually enumerating your project's dependencies in the DESCRIPTION file.

> Another example is the optional dependency of R.utils in data.table to be able to read .gz files.

Perhaps `renv` could infer this, if it sees something like `data.table::fread("file.gz")`? I do wonder why `data.table` cannot just use a plain `gzcon()` in this scenario, though.

**Comment by kevinushey** [comment]
>  if (FALSE) library(R.utils) but it would be nice to somehow include it with a generic/general approach.

The other approach here is having a file called `_dependencies.R`, or something similar, and just collecting your `library()` calls here.

**Comment by hutch3232** [comment]
Regarding `data.table` and `gzcon` - I couldn't say for sure, but perhaps because they're supporting several different compression types in one block of code?
https://github.com/Rdatatable/data.table/blob/03c647f9a44710aad834c0718e0b34e8c5341bf1/R/fread.R#L112-L124

**Comment by kevinushey** [comment]
Looks like this was implemented in https://github.com/rstudio/renv/commit/755c2d92198066680a8fbf01594e942397628e4d. Let me know if that seems sufficient.

**Comment by hutch3232** [comment]
That looks awesome, thanks so much!
