### ISSUE TITLE
renv 1.0.11 creates object in global environment

### ISSUE THREAD

**Issue by kthayashi** [rstudio/renv#2017]
I just upgraded from renv 1.0.7 to 1.0.11 and am finding that `source("renv/activate.R")` in the .Rprofile creates an object named `object` of type `call` in the global environment. In a fresh project, the value of `object` is `source("renv/activate.R")`, but if I have some other R scripts in the project the value is the last call in one of those scripts. I can confirm that clearing the global environment with `rm(list = ls())` and manually running `source("renv/activate.R")` creates this object again. Could this be a bug in one of the recent updates of renv?

**Comment by kevinushey** [comment]
Thanks; this is most likely an issue with some of the native extensions introduced in the most recent release of `renv`. Can you try setting the environment variable

```
RENV_EXT_ENABLED = FALSE
```

in your project `.Renviron` and let me know if the issue persists?

**Comment by kthayashi** [comment]
Thank you, and apologies for not getting back to you about this earlier. In case this might still be helpful - setting `RENV_EXT_ENABLED = FALSE` does indeed seem to resolve the issue for me.
