### ISSUE TITLE
Mac silicon ARM64 with Docker and GitHub Actions - install.packages('renv") failure

### ISSUE THREAD

**Issue by rressler** [rstudio/renv#2019]
I am trying to resolve an error about whether GitHub Actions is pulling an AMR64 version of renv.

I am working on a Mac silicon (ARM64) with Sequoia 15.0.1 (24A348) OS. I built a docker container for a shiny app with an image FROM rocker/r-ver:latest and installed and used renv to install packages. The container runs correctly on my local machine. I have also manually pushed it to AWS and it runs fine there on ECS.

However, when I try to use a GitHub action file with my dockerfile to build and push to AWS, it fails on the dockerfile action RUN R -e "install.packages('renv', repos = 'https://cloud.r-project.org/', verbose = TRUE)"

GitHub Actions uses ...
name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: 123456789012.dkr.ecr.us-east-1.amazonaws.com/shiny/my_app:latest
          build-args: |
             R_BASE_IMAGE=rocker/r-ver:latest

The result is 

#12 1.592 > install.packages('renv', repos = 'https://cloud.r-project.org/', verbose = TRUE)
#12 1.616 Installing package into ‘/usr/local/lib/R/site-library’
#12 1.616 (as ‘lib’ is unspecified)
#12 1.620 system (cmd0): /usr/local/lib/R/bin/R CMD INSTALL
#12 4.711 trying URL 'https://cloud.r-project.org/src/contrib/renv_1.0.11.tar.gz'
#12 5.198 Content type 'application/x-gzip' length 1220458 bytes (1.2 MB)
#12 5.199 ==================================================
#12 5.200 downloaded 1.2 MB
#12 5.200 
#12 5.209 foundpkgs: renv, /tmp/RtmpAob3wU/downloaded_packages/renv_1.0.11.tar.gz
#12 5.215 files: /tmp/RtmpAob3wU/downloaded_packages/renv_1.0.11.tar.gz
**#12 5.435 Error while loading /usr/local/lib/R/bin/INSTALL: Exec format error**
#12 5.441 
#12 5.442 The downloaded source packages are in
#12 5.442 	‘/tmp/RtmpAob3wU/downloaded_packages’
#12 5.443 Warning message:
#12 5.445 In install.packages("renv", repos = "https://cloud.r-project.org/",  :
#12 5.446   installation of package ‘renv’ had non-zero exit status

The renv binary says it is ARM64 compatible. I have also tried compiling from source but it does not make a difference.  

Rocker says rocker/r-ver:latest supports ARM64. 

Open to any suggestions to resolve this error where renv installs fine locally but there is an issue with the GitHub Actions creating an ARM64 environment.

Thanks,
Richard

**Comment by rressler** [comment]
Turns out the issue is with the GotHub Action machine is a AMD machine so it defaults to its OS for creating the build even if the ARM64 environment is specified. Needed to add 

- name: Set up QEMU # Emulator necessary for creating ARM64 containers on GitHub Action runners that are X86
        uses: docker/setup-qemu-action@v1

to the .yml file to use Qemu. It now loads the renv fine. The downside is that the emulator complies every package from source which took 2 hours to build for the 57 packages.

I also built a custom builder with the following but that may not be necessary now that the emulator is working.

 - name: Enable BuildKit and Create Multi-Arch Builder # create custom builder for ARM64
        run: |
          docker buildx create --name mybuilder  --use --platform linux/arm64
          docker buildx inspect --bootstrap

**Comment by remlapmot** [comment]
An idea for you, I believe that if you set your GHA runner to `macos-latest` or `macos-14` you will be given an M1 machine - which is ARM

<https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories>

So then installing Docker on that will by default request `linux/arm64` images.
