### ISSUE TITLE
installation of xfun fails to copy xfun.dll silently to a network drive

### ISSUE THREAD

**Issue by fernandoroa** [rstudio/renv#2020]
In Windows, `library(xfun)` fails after an installation (`renv::install`) without errors, because of lack of `xfun.dll`
when using a folder from a network path mapped to a letter drive. VSCode R extension requires the use of a the letter instead of the network path.

I can see the expected file(s) in the cache folder:
```
...\\xfun\\libs\\x64
```
`symbols.rds  xfun.dll*`

But `xfun.dll` is missing from the local renv folder (in drive mapped to a letter).

As a workaround I can `cp` the file from cache folder to local folder, when renv folder is not locked / in use.

- Is unexpected that `symbols.rds` is copied and the other file not.
- It is unexpected that an error is not raised during installation for the failed copy

Another workaround could be

> You may also want to set RENV_PATHS_CACHE so that the global package cache can be stored on the same volume as the projects you normally work on. This is especially important when working projects stored on a networked filesystem. [link](https://rstudio.github.io/renv/articles/package-install.html#:~:text=In%20some%20cases%2C%20renv%20will,cache%20into%20the%20project%20library.)

- same for package `glue`

**Comment by fernandoroa** [comment]
Maybe it is that one file gets copied for default, while the other is supposed to be a symlink?, but maybe the system is not allowed to make symlinks, or symlinking fails because it involves a network path. I think an error should be raised when symlinking or copies fail, or when in general the system is not symlink capable and system will try to do so (or give warning).

**Comment by kevinushey** [comment]
For what it's worth, on Windows, `renv` by default uses `robocopy` to copy directories -- perhaps we're not catching errors appropriately when one or more files fail to copy.

This can be changed, if you want to test -- try setting

```
options(renv.config.copy.method = "r")
```

See https://rstudio.github.io/renv/reference/config.html#copy-methods for more details.
