### ISSUE TITLE
Slow opening of renv projects with ipynb files - problem in default JSON reader?

### ISSUE THREAD

**Issue by modosist** [rstudio/renv#2021]
Hello,

I found out that starting R interpreter in folder with renv project with ipynb files + their generated cell outputs, the dependency discovery may take quite a long time. Here is an example (I  cannot share my real data on which the problem occurs, as they are confidential)

```r
# slow.ipynb
library(tidyverse)
library(gt)
library(gtsummary)
library(IRdisplay)

theme_gtsummary_compact()

num_groups <- 4
num_vars <- 100
num_obs_per_group <- 30
num_obs <- num_groups * num_obs_per_group
set.seed(1)
dat <- data.frame(
    group=rep(1:num_groups, each=num_obs_per_group*num_vars),
    variable=rep(1:num_vars, times=num_obs)
  ) %>%
  mutate(group=paste0("group ", group)) %>%
  mutate(value=runif(n())) %>%
  mutate(value=case_when(
    value<=0.3 ~ "less 0.3",
    value<=0.6 ~ "between 0.3 and 0.6",
    T ~ "larger 0.6"
  )) %>%
  mutate(value=factor(value)) %>%
  mutate(variable=paste0("variable ", variable)) %>%
  mutate(obs=rep(1:num_obs, each=num_vars)) %>%
  pivot_wider(id_cols = c(obs, group), values_from = value, names_from = variable)
dat %>%
  tbl_summary(by="group") %>%
  add_overall() %>%
  as_gt() %>%
  as_raw_html() %>%
  display_html()
```

I'm running it on Macbook Pro with M1, R 4.4.1, renv 1.0.7. Opening R interpreter within this project with the generated gtsummary table tooks roughly 20s (the same goes for starting the Jupyter R kernel).

Digging into renv code, I think I found the problematic place. When renv performs the startup dependency discovery, it checks whether `jsonlite` library is loaded. If yes, it will use it to read the ipynb file (which is just a JSON file); otherwise, it uses the default renv-specific JSON reader. And it turns out that the default JSON reader might be slower when there are large outputs, as with the code above. I did some small benchmark to compare the jsonlite and default reader

```r
library(tidyverse)
library(bench)
library(renv)
library(knitr)
res <- mark(
  renv:::renv_json_read_jsonlite("slow.ipynb"),
  renv:::renv_json_read_default("slow.ipynb")
)

res %>% as.data.frame() %>% select(expression, total_time, n_gc, mem_alloc) %>% kable(format="markdown")
```

|expression                                        | total_time| n_gc| mem_alloc|
|:-------------------------------------------------|----------:|----:|---------:|
|renv:::renv_json_read_jsonlite("slow.ipynb") |    504.3ms|    0|    1.49MB|
|renv:::renv_json_read_default("slow.ipynb")  |      19.9s|    9|    1.62GB|

Just to be sure, I tried a small hack by adding `library(jsonlite)` as a first line in project `.Rprofile` (generated by renv) so that this library is loaded. This solved the running time issue as the R interpreter started immediately.

 I'm not sure whether there is a bug in the default JSON reader that causes the slowdown. If not, then perhaps renv should depend on jsonlite or atleast have some option that allows the user to enforce it?

**Comment by modosist** [comment]
BTW: just to be sure, right now I tried the sample code with the newer renv 1.0.11 . Unfortunately, the problem persists.

**Comment by kevinushey** [comment]
Can you share an example document so I can try and see if I could improve the speed in this scenario?

**Comment by modosist** [comment]
Sure!

 [ipynb_renv_slow_start.zip](https://github.com/user-attachments/files/17506780/ipynb_renv_slow_start.zip)

**Comment by kevinushey** [comment]
Thanks! The issue here comes down to the performance of `renv`'s built-in JSON reader, and that should now be much improved in the development version.

## renv 1.0.11

```
> path <- "~/Downloads/ipynb_renv_slow_start/slow_renv.ipynb"
> system.time(renv:::renv_json_read_default(path))
   user  system elapsed 
 14.850   0.201  15.069 
```

## renv 1.0.11.9000

```
> path <- "~/Downloads/ipynb_renv_slow_start/slow_renv.ipynb"
> system.time(renv:::renv_json_read_default(path))
   user  system elapsed 
  0.182   0.004   0.186 
```

**Comment by modosist** [comment]
Amazing! I tried the development version and indeed it is much, much faster. Thank you!

**Comment by kevinushey** [comment]
Awesome, thanks!
