### ISSUE TITLE
detect quarto script rendering dependencies

### ISSUE THREAD

**Issue by edavidaja** [rstudio/renv#2023]
Given a [script](https://quarto.org/docs/computations/render-scripts.html#knitr) with yaml frontmatter such as:

```
#' ---
#' title: a script
#' ---

```

we should identify `knitr` and `rmarkdown` as dependencies.

**Comment by kevinushey** [comment]
Thanks! Implemented in https://github.com/rstudio/renv/commit/7ec0ad86693ef2afc4ba61b4acd2b68bb0acd748.
