### ISSUE TITLE
Restoring a renv envroment on Posit Workbench fails when trying to add igraph

### ISSUE THREAD

**Issue by novica** [rstudio/renv#2028]
I have a renv.lock file that I am sharing with another user. We are both on Posit Workbench (RStudio Pro) running R 4.4.1 

`renv::restore()` fails with:

```
/opt/R/4.4.1/lib/R/bin/R --vanilla -s -f '/tmp/RtmpDxvx2N/renv-install-19f8b34df76300.R'
================================================================================

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '..../renv/staging/1/igraph/libs/igraph.so](.../renv/staging/1/igraph/libs/igraph.so)':
  libglpk.so.40: cannot open shared object file: No such file or directory
Calls: loadNamespace -> library.dynam -> dyn.load
Execution halted

Error: error testing if 'igraph' can be loaded [error code 1]
```

install.packages("igraph") works for me and the other user in a non-renv session.  The error at the other user persists after the package is installed with `install.packages()`.

**Comment by kevinushey** [comment]
Can you please share the full installation log?

Is the `libglpk-dev` package installed on their machine? You can run `sudo apt install libglpk-dev` to check, assuming a Debian / Ubuntu machine.

**Comment by novica** [comment]
I can do that tomorrow. No access to the server from home :) 

However, that is the same for us both. We are using Posit Workbench, so the system is the same. We are just two users on a CentOS based server.

**Comment by kevinushey** [comment]
Strange... is it possible that a binary package is being installed in one scenario, and a source package in the other? And that prebuilt binary is incompatible with your CentOS system?

In any case, it might be useful to see:

```
remove.packages("igraph")
options(renv.config.install.verbose = TRUE)
renv::restore()
```

on each machine, to compare the output.

**Comment by novica** [comment]
> is it possible that a binary package is being installed in one scenario, and a source package in the other? 

Yes this is correct. `renv` fetches stuff from posit package manger, and `install.packages` from CRAN. 

Thanks for your help!
