### ISSUE TITLE
Error when trying init(): object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by hkaspersen** [rstudio/renv#2029]
Hello!
I am trying to make `renv` work on an existing project, but no matter what I do I always get the error `Error in FUN(X[[i]], ...) : object of type 'closure' is not subsettable` when using `renv::init()`.

I have a description file in my project, but I want `renv` to use all the files in the project (implicit mode). However I do get the same error with both methods.

I have installed the newest version of `renv` (1.0.11), on R version 4.3.0. 

Any idea what this may be?

**Comment by kevinushey** [comment]
Any chance you can share the project? Is it available on GitHub?

**Comment by hkaspersen** [comment]
Sorry the project is private and I cannot make it public unfortunately. 
Is there any specific information I could provide that will help?

**Comment by hkaspersen** [comment]
FYI I also upgraded R to the newest version and reinstalled renv, but I still get the same error every time

**Comment by hkaspersen** [comment]
I actually managed to get it to work by using the `bare = TRUE` parameter!

**Comment by kevinushey** [comment]
If you're able to distill this into a reproducible example that you can share, that would help greatly.
