### ISSUE TITLE
Regression:  `.libPaths` is being updated when suspended session is restored

### ISSUE THREAD

**Issue by Mosk915** [rstudio/renv#2036]
This is a regression of issue #936 that I opened a couple of years ago.  I'll reinclude the issue here for convenience with a few updates.

I'm using Posit Workbench, and have an renv-enabled project that uses version `1.011` of `renv`.  When the project is first opened, `.libPaths` looks like this:

```r
> .libPaths()
[1] "/home/comzm/renv_test/renv/library/R-4.3/x86_64-pc-linux-gnu"
[2] "/opt/R/4.3.3/lib/R/library"   
```

I should note that I have an `.Renviron` file that sets `RENV_CONFIG_SANDBOX_ENABLED=FALSE` in order to retain the behavior of older versions of `renv` where the system library is used directly rather than using a location in the cache that is symlinked to the system library.

After awhile of inactivity, the R session will enter a suspended state (it can also be forcibly suspended from the home screen to avoid having to wait).  Then when the session is resumed, `.libPaths` looks like this:

```r
> .libPaths()
[1] "/home/comzm/renv_test/renv/library/R-4.3/x86_64-pc-linux-gnu"
[2] "/opt/R/4.3.3/lib/R/library"                                  
[3] "/rlibrary/4.3"    
```

The third path is our site library that we set in `Rprofile.site` for use with non-renv-enabled projects.  It shouldn't be part of `.libPaths` in renv-enabled projects.

Restarting R correctly removes the third path from `.libPaths`.

I can see that when first opening the project or after restarting R, `.Library.site` is correctly set to `NULL`, and running `renv::project()` gives me the path to the project: `"/home/comzm/renv_test"`.  But when resuming a suspended session, `Library.site` is set to `"/rlibrary/4.3"` and running `renv::project()` returns `NULL`.

The fix the last time was to set the `renv.project.path` option in `renv_load_finish` and then check for it in `.onLoad`.  It seems since version `1.0.0` that option is no longer being set, but it is still used in the check, so the project path is just `NULL`.  It seems either that option still needs to be set, or some other way is needed to get the project path.  Perhaps using the `RENV_PROJECT` environment variable could be used instead?

**Comment by kevinushey** [comment]
I'm not able to reproduce locally. First, I modified my R installation's `etc/Rprofile.site` to use:

```
.libPaths(c("/tmp", .libPaths()))
```

to try setting up a library path. (This gets respected in non-`renv` sessions.) Then, I created a new RStudio project, and used `renv::init()` to initialize it. I see:

```
> .libPaths()
[1] "/home/kevin/scratch/test/renv/library/R-4.3/aarch64-unknown-linux-gnu"     
[2] "/home/kevin/.cache/R/renv/sandbox/R-4.3/aarch64-unknown-linux-gnu/9a444a72"
```
and that same set of library paths is still used, even after suspend + resume.

As a workaround, can you try something like:

```
if (!file.exists("renv")) {
  .libPaths("/rlibrary/4.3")
}
```

in your `etc/Rprofile.site`, and see if that makes a difference?

**Comment by Mosk915** [comment]
I think you're missing the `.Renviron` file in the project that sets `RENV_CONFIG_SANDBOX_ENABLED=FALSE`.  I have this set to reproduce the old behavior of `renv` where it uses the system library directly rather than a symlinked location within the cache.

**Comment by kevinushey** [comment]
Hmm... it seems like this is occurring because the `renv.project.path` option isn't being set? `renv` is looking for that as a hint that RStudio is restoring a suspended session, and uses that to re-activate the sandbox in that scenario. I'll need to look into this a bit further, but I think this might require some changes on the RStudio side.

**Comment by Mosk915** [comment]
Right, the `renv.project.path` option isn't being set anymore.  The [fix](https://github.com/rstudio/renv/commit/5808e3fd6225fb76a7ad306da6228ab7f9b5683c) you made when I opened the original issue was to set it at the beginning of `renv_load_finish` and then check for it in `.onLoad`.  But it looks like it's no longer being set anymore as of version `1.0.0`.  I was wondering if instead you could use the `RENV_PROJECT` environment variable in `.onLoad` instead since that does persist after a suspend + resume.

**Comment by kevinushey** [comment]
I think the simplest thing here is to just make sure we're setting the option when we set the other project variables.

**Comment by Mosk915** [comment]
It's working now in the development version.  Thanks!
