### ISSUE TITLE
`future` and `.libPaths()`

### ISSUE THREAD

**Issue by schloerke** [rstudio/renv#204]
Ran into an interesting bug with the `future` package and `.libPaths()` and was pointed your way to double check you have the case covered with `renv`.

--------------------------------

Issue:  https://github.com/HenrikBengtsson/future/issues/219

`future` Bug Repro:

1. Make a custom lib path to use a package in that libpath. 
2. `future` PSOCK cluster is used.
3. In a future call, try to use package in custom libpath.
* Error: Fails to find package as custom libpath is not passed through.

--------------------

Work around:

* Set `R_LIBS` to the custom libpath

I can see in the code `R_LIBS` is being set here: https://github.com/rstudio/renv/blob/24ed969635376879ca16655d2d6a289eaa0e676b/R/R.R#L12 . 

Didn't know if there were other situations where this might be useful, but I thought I'd pass along the odd situation.  (Feel free to close if this is already covered.)

cc @jcheng5

**Comment by kevinushey** [comment]
`renv` does set the environment variables in `R_LIBS_USER`; e.g.

https://github.com/rstudio/renv/blob/master/R/load.R#L178-L183

So I _think_ this should be handled (but I will properly test that).

**Comment by kevinushey** [comment]
Looks like this works as expected. In particular, the new R processes launched read the project `.Rprofile`, and so get the same project initialization stuff run that any regular R process would.

```
> library(future)
> cl <- makeClusterPSOCK(2)
> plan(cluster, workers = cl)
> f <- future(.libPaths())
> value(f)
[1] "/Users/kevinushey/scratch/futurenv/renv/library/R-3.6/x86_64-apple-darwin15.6.0"        
[2] "/private/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T/Rtmpu4TXue/renv-system-library"
```

**Comment by jcheng5** [comment]
Thanks to both of you for confirming!
