### ISSUE TITLE
Misleading messages if cache is not writable

### ISSUE THREAD

**Issue by gowerc** [rstudio/renv#2041]
We recently noticed that if the renv cache is readable but not writable renv fails to cache the package (understandable) however it still reports to the user that successfully cache the package which we found to be very confusing / misleading (took us a while to work out why our package wasn't be restored quickly) 😄 

Steps to reproduce:

```
mkdir cachedir
chmod 555 cachedir
export RENV_PATHS_CACHE=$(pwd)/cachedir
Rscript --no-environ -e "renv::init()"
Rscript --no-environ -e "renv::install('htmlTable')"


- Installing rmarkdown ...                      OK [installed binary and cached in 4.9s]
- Installing htmlwidgets ...                    OK [installed binary and cached in 1.6s]
- Installing rstudioapi ...                     OK [installed binary and cached in 1.2s]
- Installing htmlTable ...                      OK [installed binary and cached in 2.3s]
```

Despite the message being printed if you then check the cachedir you'll see it is empty still.

**Comment by kevinushey** [comment]
Many thanks for the bug report and reproducible example! This should be fixed up with https://github.com/rstudio/renv/commit/3ab8c653c9e60fbfadc274699ffcb357379bbb1e.
