### ISSUE TITLE
Skip package installation in `renv::use()` if packages already installed.

### ISSUE THREAD

**Issue by noamross** [rstudio/renv#2044]
I have been starting to use `renv::use()` for utility scripts so they self-install dependencies, like so

```r
#!/usr/bin/env Rscript

script_version = "0.2.0"
script_lib =  tools::R_user_dir(paste0("myScript_", script_version), "data")
if (!dir.exists(script_lib)) dir.create(script_lib)

if (!requireNamespace("renv", quietly = TRUE)) {
    install.packages("renv")
}

options(repos = c(rOpenSci = "https://ropensci.r-universe.dev", getOption("repos")))

renv::use(
  "docopt@0.7.0",
  "rnaturalearthhires",
  verbose = TRUE,
  sandbox = FALSE,
  library = script_lib
)

library(docopt)
library(rnaturalearthhires)

sessionInfo()
```

The idea is that the script has a self-contained library and is portable across machines without interfering with the user library (analagous to `uv tool run`).  However, I note that `renv::use()` always installs the packages, even if they are already in the library. This is fast when using the `renv` package cache, but still adds startup overhead. Would it be possible for `use()` to skip installation if the correct package version exists in the library directory already?

**Comment by kevinushey** [comment]
Thanks for the feature request -- I can take a look.

**Comment by kevinushey** [comment]
Thanks! I've implemented something in https://github.com/rstudio/renv/commit/1093f0fae12f043b11e0896eaf877286cebed3f0; can you let me know if that seems sufficient?

**Comment by noamross** [comment]
Looks like it! Network calls are avoided, and the total time of `renv::use()` was consistently cut down from ~0.016s to ~0.008s. Thanks.
