### ISSUE TITLE
Error upon opening R "ERROR r error 4 (error readRDS(nsinfoFilePath): unknown input format

### ISSUE THREAD

**Issue by CoralKiwis** [rstudio/renv#2045]
Hello lovely people, can someone help me? Randomly Rstudio didnt open, instead showing this error message. Yesterday was working just fine and i already try to unistall and reinstall multiple times.

I wish i could send more info to locate the problem, but i really dont know. This is my first time using R :(

![Image](https://github.com/user-attachments/assets/04591a75-7899-496c-aeeb-c756c0375c85)

**Comment by kevinushey** [comment]
My best guess is that one of your installed packages was unexpectedly corrupted -- you might need to uninstall or reinstall one or more of your installed R packages.
