### ISSUE TITLE
renv overwrites .libPaths() defined in user .Rprofile

### ISSUE THREAD

**Issue by venpopov** [rstudio/renv#2046]
`renv` has presented a problem for Visual Studio Code users because using R in VSCode requires several packages. These packages are unrelated to the actual project code, but are necessary for VSCode to work well with R.

There exists [this](https://github.com/REditorSupport/vscode-R/wiki/Working-with-renv-enabled-projects) tutorial to solve this problem. However, [this solution hasn't worked for a while.](https://github.com/REditorSupport/vscode-R/issues/1478).

I tried to create a custom solution by adapting the Wiki tutorial linked above as follows:

1. Add the following line to your user `.Rprofile` file (can launch it via `usethis::edit_r_profile()`)

```r
.libPaths(c(.libPaths(), "PATH/TO/CUSTOM/RENV/LIBRARY"))
```

where the path is the same as that recommended in the Wiki above

2. Add the following in your user `.Renviron` file:

```
RENV_CONFIG_USER_PROFILE=TRUE
```

This setting forces RENV to load not only the project .Rprofile file, but also your global user `.Rprofile`

Unfortunately, this also doesn't work. While `renv` now lets R to load the user `.Rprofile` file, it rewrites the .libPaths() *after* it has already loaded the user file. 

This might explain why the official solution stopped working. Has there been any recent changes to the order in which renv loads the user .Rprofile and sets library paths?

**Comment by tianranchunzhen** [comment]
Sorry for interruption, but is there a better solution available at the moment? 👀
