### ISSUE TITLE
allow to exclude some R files and directories

### ISSUE THREAD

**Issue by FeelLiao** [rstudio/renv#2049]
In my project, I use both a older version  and the last version of ggplot2.  I use  `library(ggplot2,lib.loc = "rp_ggplot2")` command for the older version. But when I run `renv::init()`, It will capture all the file in the project and then cause a dependency error. Is there some solution?

**Comment by hutch3232** [comment]
I didn't quite follow the question, but if you want to ignore files/folders I'd suggest using `.renvignore` file, documented here:

https://rstudio.github.io/renv/reference/dependencies.html#ignoring-files

(I'm not associated with this repo besides being an avid user of `renv`)

**Comment by FeelLiao** [comment]
> I didn't quite follow the question, but if you want to ignore files/folders I'd suggest using `.renvignore` file, documented here:
> 
> https://rstudio.github.io/renv/reference/dependencies.html#ignoring-files
> 
> (I'm not associated with this repo besides being an avid user of `renv`)

That works for me, thank you!
