### ISSUE TITLE
Not Reproducing R Universe Packages?

### ISSUE THREAD

**Issue by emstruong** [rstudio/renv#2050]
Hello,

I've been using `renv` to install what I think is the same set of packages across multiple different systems. Something I noticed is that for some reason, it seems like packages from R-Universe may keep the same version number despite their hashes changing, so I'm confused about whether this is a problem for reproducibility or not?

I've attached my [old_renv.lock.txt](https://github.com/user-attachments/files/18001006/old_renv.lock.txt) and the [current version](https://github.com/user-attachments/files/18001007/New_renv.lock.txt) here.

It seems like the hash for cmdstanr and posterior have changed, even though the remotesha are the same and the version numbers are... identical? Is this because these packages require compilation, thus differences in compilation settings between machines will create differences in the hash? (I don't have an understanding of what's being hashed, I'm just guessing).

Thanks

**Comment by kevinushey** [comment]
The hash field is used only for caching; that is, if an installed version of `cmdstanr` with a matching hash is available in the cache, that copy will be used. Otherwise, the package will be downloaded and installed using the declared remote information.

The hash field in question is computed based on the package's DESCRIPTION file -- more specifically, on a normalized subset of fields within the DESCRIPTION file. If the hash changed, that most likely implies something may have changed in how the DESCRIPTION file was built / generated.

Unfortunately, that doesn't answer the question as to _why_ the hash changed; the only hypothesis I can provide is that the package DESCRIPTION changed in some way. (Maybe it depends on how the package was installed; e.g. if it was installed by `pak` versus `remotes` or something else?)

**Comment by emstruong** [comment]
I don't think I changed whether pak or remotes was being used to install the package...

If it helps, I noticed that although [this page](https://stan-dev.r-universe.dev/cmdstanr)  states that cmdstanr version 0.8.1 was from hash[02259ef7aa](https://github.com/stan-dev/cmdstanr/commit/02259ef7aa2a8b1c8de2fa3fc42a9feafd789288) and that was the last update.

Right now, [this page](https://stan-dev.r-universe.dev/builds) states that cmdstanr was built... 4 hours ago? 

I don't know much about r-universe, but do you think this is relevant?

**Comment by kevinushey** [comment]
It's possible, but unfortunately it's all just speculation. The hash I'm seeing right now is:

```
> url <- "https://stan-dev.r-universe.dev/src/contrib/cmdstanr_0.8.1.tar.gz"
> download.file(url, destfile = basename(url))
trying URL 'https://stan-dev.r-universe.dev/src/contrib/cmdstanr_0.8.1.tar.gz'
Content type 'application/gzip' length 863161 bytes (842 KB)
==================================================
downloaded 842 KB

> renv:::renv_hash_description(file.path(getwd(), basename(url)))
[1] "e3409949f3437c53affcf4447c9aaace"
```

**Comment by emstruong** [comment]
> It's possible, but unfortunately it's all just speculation. The hash I'm seeing right now is:
> 
> ```
> > url <- "https://stan-dev.r-universe.dev/src/contrib/cmdstanr_0.8.1.tar.gz"
> > download.file(url, destfile = basename(url))
> trying URL 'https://stan-dev.r-universe.dev/src/contrib/cmdstanr_0.8.1.tar.gz'
> Content type 'application/gzip' length 863161 bytes (842 KB)
> ==================================================
> downloaded 842 KB
> 
> > renv:::renv_hash_description(file.path(getwd(), basename(url)))
> [1] "e3409949f3437c53affcf4447c9aaace"
> ```

...Hold-on, isn't this a completely different hash from either of my two files, or am I not understanding something?

**Comment by kevinushey** [comment]
I don't think so; the hash matches what you have in `old_renv.lock` for cmdstanr.

I also note that the new lockfile contains an entry

```
      "RemoteType": "repository",
```

which the old lockfile does not -- that could be the reason why the hash has changed in the lockfiles. Do you recall how the `cmdstanr` package was installed?

**Comment by emstruong** [comment]
Not really... But I'd be surprised if I did anything other than `renv::restore()`

**Comment by kevinushey** [comment]
I unfortunately do not. :-/ If the issue arises again, or if you can figure out a way to reproduce the issue more readily, I could try to dive in some more.
