### ISSUE TITLE
interaction with gitignore everything without an extension

### ISSUE THREAD

**Issue by luispfonseca** [rstudio/renv#2052]
I do not know if this is a bug or user error. I have a project using [RStan](https://mc-stan.org/users/interfaces/rstan). RStan compiles model code to a binary file without an extension in the name. I don't want this binary file to be committed to git, so I followed a suggestion described [here](https://discourse.mc-stan.org/t/using-gitignore-to-ignore-stan-models-with-git/31745) and I have the following block in my `.gitignore`.

```gitignore
# ignore *everything*
*
!/**/
# and then this 'unignores' anything with an extension
!*.*
# now, the rest of your gitignore should appear after the above
# on windows Stan executables end in .exe
*.exe
# Ignore temporary files created as part of compilation.
*.hpp
*.o
```

The issue is that `renv` does not detect any R files in subfolders if I have this in my `.gitignore`, and thus detects no packages used. This issue does not affect `.R` files in the root folder of the project; only in subfolders. Is this expected behaviour? I suspect this is not a great use of gitignore, but I'm unsure how to reconcile the two goals here.

Thanks for all the work in the package!

**Comment by kevinushey** [comment]
I'm surprised that Stan doesn't give a unique extension to the compiled model files, or something like that... Either way, any divergence between how git and renv interprets the `.gitignore` file should be considered a bug in renv, so this seems worth fixing.

Regardless, the simplest solution in your case might be to include a `.renvignore` file, which might include simpler ignore rules. Please see https://rstudio.github.io/renv/reference/dependencies.html#ignoring-files for more details.

**Comment by kevinushey** [comment]
This should now be fixed up via https://github.com/rstudio/renv/commit/9274c79dd12aa5044512e1868de4594f1206458a -- if you're able to test, please let me know if that resolves the problem for you. Thanks for reporting!

**Comment by luispfonseca** [comment]
Seems to work now, thanks a lot for the quick fix!
