### ISSUE TITLE
utils::packageVersion("....") not picked up by renv

### ISSUE THREAD

**Issue by edward-burn** [rstudio/renv#2053]
I'm sure this is very much an edge case, but I used renv in a project with a line of code `utils::packageVersion("duckdb")` - although duckdb was not in my renv lock file this line of code worked for me as I had duckdb installed on my computer, but this broke for the person I shared the code with because they did not have the package installed locally. 

I wonder if there is a way to pick this up, so that in this case duckdb would have been added to the renv lock file?

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.2.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
utils::packageVersion("duckdb")
#> [1] '1.0.0'
renv::dependencies()$Package 
#> Finding R package dependencies ... Done!
#>  [1] "dplyr"     "renv"      "utils"     "dplyr"     "renv"      "utils"    
#>  [7] "rmarkdown" "dplyr"     "renv"      "utils"     "utils"
```

<sup>Created on 2024-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kevinushey** [comment]
Is this the only way that `duckdb` was used in the project? Or is it used / loaded in other ways?

**Comment by edward-burn** [comment]
No this was the only line of code using it in the whole project, which must be very much an edge case (I suppose a bit similar to https://github.com/rstudio/renv/issues/2047)

**Comment by kevinushey** [comment]
In this scenario, I'd recommend just adding an appropriate `library()` call, or using "explicit" snapshots and enumerating your project dependencies in the project DESCRIPTION file.
