### ISSUE TITLE
remember `configure.args` when updating packages

### ISSUE THREAD

**Issue by elgabbas** [rstudio/renv#2054]
Hello,

Is it possible to store in the `renv` settings the `configure.args` used to install the packages?
For example, I installed the following packages with specific `configure.args `:
```
Sys.setenv(LIBARROW_BINARY = TRUE)
install.packages('arrow', type = "source", configure.args = "--enable-zstd")
remotes::install_cran("qs2", type = "source", configure.args = "--with-TBB --with-simd=AVX2", force = TRUE)
R CMD INSTALL Rmpi_0.7-2.1.tar.gz --configure-args="--with-Rmpi-type=MPICH2" --no-test-load
```
However, when using `renv::update()`, these pacakges will be installed without these flags. Is it possible to store these flags; e.g. in the `renv.lock` file? 

Thanks

**Comment by kevinushey** [comment]
My main worry with this approach is that the configure arguments used might be different for different platforms (or even different versions of the same operating system). For that reason, we generally recommend setting options appropriately where you need to update / install, e.g.

```
options(configure.args.arrow = "--enable-zstd")
```

See also: https://rstudio.github.io/renv/articles/package-install.html#configure-flags

**Comment by elgabbas** [comment]
Thanks @kevinushey. This is clear.
