### ISSUE TITLE
option to disable warning on missing dependencies when snapshotting?

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#206]
I've been experimenting with using snapshots of `type = "custom"`, where I supply a function in `renv.snapshot.filter` that only returns my project's direct dependencies, ignoring recursive dependencies.

This seems like a nice way to capture the versions of my direct dependencies in a minimal lockfile. Currently this process results in a large screen of recursive dependencies that I should `Consider re-installing these packages before snapshotting the lockfile.`. This occurs even with `force = TRUE`.

It would be nice to have the option to disable the messages relating to recursive dependencies not included in the snapshot. Or it might make sense not to warn when `renv.snapshot.filter` is in use since this implies advanced usage.

**Comment by kevinushey** [comment]
Are you sure this is a good idea? The intention is that the lockfile captures a consistent library state, including both top-level dependencies as well as recursive dependencies. What if you try to restore this project in the future, and the wrong version(s) of your recursive dependencies are picked up?

**Comment by MilesMcBain** [comment]
Outside the right context it would be a bad idea. 

In this context I am trying to allow someone who sits at the next desk to me to easily clone a repo today and have it work. I'm still not sure if this is a good idea but it seemed worth trying.

**Comment by kevinushey** [comment]
But things _should_ work fine if you use one of the default snapshot options and then restore from that. What problem are you trying to solve, exactly, through the use of a custom snapshot filter?

**Comment by kevinushey** [comment]
Closing this for now -- feel free to re-open if you can provide more context.
