### ISSUE TITLE
Trouble with StanHeaders on R-Universe?

### ISSUE THREAD

**Issue by emstruong** [rstudio/renv#2061]
My renv is simply unable to install StanHeaders 2.35.0.9000 for some reason... Any clues if this is an issue with R-Universe, or...? Personally, I can't find 2.35.0.9000 myself with their new update, so I wonder if it's an issue with R-Universe? [renv.lock.txt](https://github.com/user-attachments/files/18143373/renv.lock.txt)

**Comment by kevinushey** [comment]
Can you please include the code you are running, and the entirety of the output + errors you're seeing?

**Comment by emstruong** [comment]
> Can you please include the code you are running, and the entirety of the output + errors you're seeing?

Hi,

Unfortunately, I'm not in that context anymore--so I don't have the code anymore. So I'll close the issue. I can tell you that the pak and r-universe issue seems to be replicable, however. https://github.com/rstudio/renv/issues/2060

**Comment by kevinushey** [comment]
For reference, this came down to older versions of r-universe not including a `RemoteSubdir:` entry in the package DESCRIPTION file; this has since been fixed on the r-universe side and so `renv` should be able to successfully restore such packages in the future.

**Comment by emstruong** [comment]
That's good... So everything should be okay with the latest CRAN release of renv, right?

**Comment by kevinushey** [comment]
Yes, I believe so -- feel free to re-open with more details if you're still having trouble.
