### ISSUE TITLE
Should `renv::install()` auto-install roxygen?

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#207]
When doing

```r
init(bare = TRUE)
install()
```

in a pkg root, `renv` does not install/link `roxygen2` if it is not explicitly listed under Imports and friends.
Should _renv_ auto-detect roxygen if the "Roxygen" keyword is set in DESCRIPTION?

**Comment by kevinushey** [comment]
This seems like a good idea, but shouldn't you include `roxygen2` in your `Suggests:` anyhow?
