### ISSUE TITLE
snapshot() should work even without project library

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#21]
i.e. it should capture the dependency information from the system library, filtered by `dependencies()`

**Comment by kevinushey** [comment]
My original intention was for `snapshot()` to capture the state of a library, and nothing more (no filtering based on inferred dependencies). The only special thing `renv` does right now is it will warn if you attempt to snapshot a library with a broken dependency tree (e.g. pkg A depends on pkg B but that package is not installed).

You can snapshot an arbitrary library with e.g.

```
renv::snapshot(library = "/path/to/library")
```

We could filter the set of records post-hoc based on dependencies but I don't think it should be automatic; e.g. I think the user should have to write something like (for example):

```
deps <- renv::dependencies()
renv::snapshot(
  library = "/path/to/library",
  filter = deps$Packages
)
```

What do you think?

**Comment by hadley** [comment]
I think being able to `snapshot()` before `init()` is a gateway drug to reproducibility, and I think it's worth putting some extra effort to make `snapshot()` work without a project library.  (You could also imagine that this is what rsconnect would do)

**Comment by slopp** [comment]
What would be different between doing that and just calling init? What is the downside of snapshot in a new environment prompting for init?

**Comment by kevinushey** [comment]
IIUC the intention is to support the case when someone doesn't actually want to use a private library, but still wants to capture the state of their user / system library at some point in time. (sort of an on-ramp to reproducibility without fully buying into the `renv` paradigm?)

**Comment by slopp** [comment]
Ah, ok, that makes sense.  I think the filtering makes sense then, you'd want to capture only the relevant parts of the library instead of the whole thing
