### ISSUE TITLE
`reticulate` no longer able to find the Python binary

### ISSUE THREAD

**Issue by jeroenjanssens** [rstudio/renv#215]
When using `renv` in combination with `reticulate`, the latter is no longer able to find the Python binary. I suspect this is because `renv` sets the environment variable "RETICULATE_PYTHON_ENV" to an empty string. The current workaround I employ is to first unset that variable:

```r
Sys.unsetenv("RETICULATE_PYTHON_ENV")
library(reticulate)
use_virtualenv("../venv", required = TRUE)
```

PS. I filed this issue as requested by @kevinushey (see https://twitter.com/kevin_ushey/status/1183869321992269824).

PPS. This package is amazing. Thank you.

**Comment by kevinushey** [comment]
Thanks for the bug report! I've adjusted how `renv` and `reticulate` coordinate in order to choose an appropriate Python virtual environment, and I believe this should be better handled now. Please feel free to re-open or follow up if you're still having trouble.

**Comment by jeroenjanssens** [comment]
I just updated `renv` and I'm happy to confirm that the above-mentioned workaround is no longer needed. Thank you!
