### ISSUE TITLE
option to add full library to git 

### ISSUE THREAD

**Issue by rpodcast** [rstudio/renv#217]
I will preface this with saying this is an esoteric request, but very much informed by my day-to-day with legacy enterprise processes!  

Currently renv automatically creates `renv/.gitignore` with the `library` directory added so that it's ignored by Git.  For 99% of the time I fully support that 😄 .  However for some of my app deployments, I need to actually add the full package library to the Git repo for the project.  So my first attempt is to simply edit the `renv/.gitignore` and remove `library/` rmyself.  However if I close the project and resume again, renv automatically adds that line back.  Would there be a way for a user to opt-out of this automatic behavior, as crazy as it may sound?

**Comment by kevinushey** [comment]
Thanks! I've implemented this now with a project-specific setting -- you should now be able to run:

```
renv::settings$vcs.ignore.library(FALSE)
```

to instruct `renv` to allow the project to be included with version control. You may need to modify the `.gitignore` file to remove the `library/` entry once more, but `renv` should stop adding it back in afterwards.

**Comment by gtm19** [comment]
Can I jump on this and just ask for a pithy explanation as to why the `library/` subdirectory is ignored by default? Is this just to lighten the project during development, with the idea that you would remove it from the `.gitignore` file before release?

**Comment by kevinushey** [comment]
Mainly because it's often quite large, and tracking it in `git` would quickly bloat the repository size -- especially if you were sharing that repository with many collaborators, on different systems / OSes who also had their own libraries to update and change.
