### ISSUE TITLE
Vignette about python is not accessible in menu for articles in website

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#218]
Is this on purpose ? 

The vignette exists but is not listed for pkgdown publication in the navbar menu

https://github.com/rstudio/renv/blob/e8857e7d46ea4c2188169d908481808a4a3e4563/_pkgdown.yml#L63-L67

It would be useful to be able to have menu to point to it: 
https://rstudio.github.io/renv/articles/python.html

**Comment by cderv** [comment]
This may be on purpose as vignette still mentioned `renv::settings$python` and not the new `renv::use_python` 🤔

**Comment by kevinushey** [comment]
Right, I haven't updated the vignette yet to be inline with how `use_python()` has evolved :)

**Comment by cderv** [comment]
Ok. that is why. ☺️ I was puzzled by the existing vignette not being feature... 🙄  
You can close this issue then... sorry to have step in.

**Comment by kevinushey** [comment]
No, I appreciate it! I'll leave this issue as a marker indicating that the vignette is out-of-date.

**Comment by cderv** [comment]
Glad to know. 
As a small return of experience, I find `use_python` from renv really interesting, with the virtual env project inside RStudio project. Also the fact renv load by default the virtual env (via `RETICULATE_PYTHON`) is very cool to use with reticulate python. `
I am still not sure how it should interact with reticulate and what should be the best pratices (letrenv create the virtualenv or let reticulate do it or create it in terminal with python directly) and I look forward to the new vignette!
