### ISSUE TITLE
Can't install local package when dependency is from an alternate repository

### ISSUE THREAD

**Issue by karawoo** [rstudio/renv#221]
This may be the same fundamental issue as #120. I am developing a package, and using renv within the repo. One of my dependencies comes from an alternate repository. With renv activated, I cannot run `devtools::install()` locally; if I deactivate renv, `devtools::install()` works. 

```r
# Create test package and add synapser as an Import
usethis::create_package("test")
write(
  "Imports:\n    devtools,\n    synapser\nAdditional_repositories: http://ran.synapse.org",
  "DESCRIPTION",
  append = TRUE
)
renv::init()

# < restart R here; renv will be activated >

devtools::install() # Fails
#> Error in if (type == "both") type <- "source" else if (type == "binary") type <- .Platform$pkgType :
#>   argument is of length zero

renv::deactivate()

# < restart R here >

devtools::install() # Succeeds
```

**Comment by kevinushey** [comment]
This sounds similar to https://github.com/r-lib/remotes/issues/291. Unfortunately, I'm not able to reproduce.

Can you confirm whether you have the latest versions of devtools + remotes installed? If so, can you try running your example again with:

```r
options(error = renv:::renv_error_handler)
devtools::install() # Fails
```

so we can get a stack trace?

**Comment by karawoo** [comment]
Thanks for the quick response @kevinushey! Yes I'm on dev versions of remotes and devtools. Here's the traceback and package version info:

```r
devtools::install() # Fails
#> Error in if (type == "both") type <- "source" else if (type == "binary") type <- .Platform$pkgType : 
#>   argument is of length zero
#> Traceback (most recent calls first):
#> 17: devtools::install()
#> 16: remotes::install_deps(pkg$path, build = build, build_opts = build_opts, 
#>         INSTALL_opts = opts, dependencies = dependencies, quiet = quiet, 
#>         force = force, upgrade = upgrade, ...)
#> 15: dev_package_deps(pkgdir, repos = repos, dependencies = dependencies, 
#>         type = type)
#> 14: combine_deps(package_deps(deps, repos = repos, type = type), 
#>         remote_deps(pkg))
#> 13: nrow(cran_deps)
#> 12: package_deps(deps, repos = repos, type = type)
#> 11: vapply(remote, function(x) remote_sha(x), character(1))
#> 10: FUN(X[[i]], ...)
#>  9: remote_sha(x)
#>  8: remote_sha.cran_remote(x)
#>  7: available_packages(remote$repos, remote$pkg_type)
#>  6: available_packages_set(repos, type, suppressWarnings(utils::available.packages(utils::contrib.url(repos, 
#>         type), type = type)))
#>  5: suppressWarnings(utils::available.packages(utils::contrib.url(repos, 
#>         type), type = type))
#>  4: withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
#>  3: utils::available.packages(utils::contrib.url(repos, type), type = type)
#>  2: utils::contrib.url(repos, type)
#>  1: resolvePkgType(type)
packageVersion("remotes")
#> [1] ‘2.1.0.9000’
packageVersion("devtools")
#> [1] ‘2.2.1.9000’
packageVersion("renv")
#> [1] ‘0.7.1.24’
```

**Comment by kevinushey** [comment]
For some reason, the wrong package type appears to be getting tagged on the remote. Can you confirm what:

```
getOption("pkgType")
```

reports for you?

You could also try:

```
debug(remotes:::dev_package_deps)
```

to see if you can figure out what is going on within and where `pkgType` is getting lost.

**Comment by karawoo** [comment]
From within the project, with renv activated, `getOption("pkgType")` returns `"both"`. Debugging when `remotes:::dev_package_deps()`, `type` is `"both"` there too.

I moved down and debugged `remotes:::package_deps()` and here it gets a little more interesting:
- The `type` that's passed to `package_deps()` is still `"both"`
- [This line](https://github.com/r-lib/remotes/blob/a85cef56222d3239841c951cdb5c7bb4962a9efa/R/deps.R#L72) seems to cause the problem, so before it runs I did some exploration of the `remote` object created [shortly before](https://github.com/r-lib/remotes/blob/a85cef56222d3239841c951cdb5c7bb4962a9efa/R/deps.R#L69). Specifically I looked for which elements a) are considered CRAN remotes (because the traceback specifically shows the `remote_sha.cran_remote` method) and b) have a null `pkg_type` within the list object:
```r
cran_remotes_null_type <- vapply(remote, function(x) {
  inherits(x, "cran_remote") & is.null(x$pkg_type)
}, logical(1))
# Subset
remote[cran_remotes_null_type]
#> [[1]]
#> $name
#> [1] "synapser"
#> 
#> $repos
#> [1] "http://ran.synapse.org"
#> 
#> $pkg_type
#> NULL
#> 
#> $sha
#> [1] "0.6.61"
#> 
#> attr(,"class")
#> [1] "cran_remote" "remote"     
#> 
#> [[2]]
#> $name
#> [1] "PythonEmbedInR"
#> 
#> $repos
#> [1] "http://ran.synapse.org"
#> 
#> $pkg_type
#> NULL
#> 
#> $sha
#> [1] "0.3.37"
#> 
#> attr(,"class")
#> [1] "cran_remote" "remote"     
#> 
#> [[3]]
#> $name
#> [1] "pack"
#> 
#> $repos
#> [1] "https://cran.rstudio.com"
#> 
#> $pkg_type
#> NULL
#> 
#> $sha
#> [1] "0.1-1"
#> 
#> attr(,"class")
#> [1] "cran_remote" "remote"     
```

**Comment by kevinushey** [comment]
What is the output of:

```
writeLines(readLines(system.file("DESCRIPTION", package = "synapser")))
```

I wonder if there are some extra DESCRIPTION fields tagged that are confusing remotes in some way?

**Comment by karawoo** [comment]
```
Package: synapser
Type: Package
Title: R language bindings for Synapse API
Version: 0.6.61
Date: 2019-07-19
Authors.R: c( person("Bruce", "Hoff", role = c("aut", "cre"), email =
    "bruce.hoff@sagebase.org"), person("Kimyen", "Ladia", role = c("aut"),
    email = "kimyen.ladia@sagebase.org"), person("Sage Bionetworks", role =
    c("cph")) )
Maintainer: Bruce Hoff <bruce.hoff@sageabse.org>
BugReports: https://github.com/Sage-Bionetworks/synapser/issues
Description: Provides R language bindings for Synapse RESTful web services.
License: Apache License 2.0
Imports: PythonEmbedInR(>= 0.3.25), utils, methods
Depends: R(>= 3.3)
Suggests: testthat, knitr, rmarkdown
URL: https://www.synapse.org
VignetteBuilder: knitr
SystemRequirements: libssl-dev, libcurl-dev, zlib-dev
Additional_repositories: http://ran.synapse.org
RoxygenNote: 6.0.1
NeedsCompilation: no
Packaged: 2019-07-20 00:42:28 UTC; administrator
Author: Bruce Hoff [aut, cre],
 Kimyen Ladia [aut],
 Sage Bionetworks [cph]
Built: R 3.6.0; ; 2019-07-20 00:43:03 UTC; unix
RemoteType: standard
RemoteRef: synapser
RemoteRepos: http://ran.synapse.org
RemoteSha: 0.6.61
```

**Comment by kevinushey** [comment]
```
RemoteType: standard
RemoteRef: synapser
RemoteRepos: http://ran.synapse.org
RemoteSha: 0.6.61
```

I think the problem here is that the installed package has `RemoteType: standard` but `RemotePkgType` is not declared. You try adding e.g.

```
RemotePkgType: binary
```

to see if that helps make a difference. Alternatively, reinstalling the offending packages should help as well.

**Comment by kevinushey** [comment]
I've made a pull request for remotes that should help resolve this issue: https://github.com/r-lib/remotes/pull/450

**Comment by karawoo** [comment]
Unfortunately none of these help. I tried reinstalling all 3 packages caught above (synapser, PythonEmbedInR, and pack) with both `install.packages()` and `renv::install()`; neither fixes the issue. Editing the description with the following does not help either:

```r
write(
  "RemotePkgType: binary",
  system.file("DESCRIPTION", package = "synapser"),
  append = TRUE
)
```

**Comment by kevinushey** [comment]
That's surprising to me :-/ To the best of my knowledge, that's where the `pkg_type` field should be coming from.

If you install `remotes` from this branch, do you have any better luck?

```
renv::install("kevinushey/remotes@feature/pkgtype-resilience")
# restart R
devtools::install()
```

**Comment by karawoo** [comment]
YES installing from your branch works 🎉

**Comment by karawoo** [comment]
Closing this as it's working now with the updates to remotes, thanks!
