### ISSUE TITLE
V3 vs V4 cache

### ISSUE THREAD

**Issue by johanneswaage** [rstudio/renv#223]
Hi,
Related to disk space usage concerns in a production environment, I'm curious to the difference between v3 and v4 in the renv cache dir? If users are on the newest version of renv, can v3 be deleted safely?
Thanks

**Comment by kevinushey** [comment]
The v3 cache was used by older versions of `renv`; if you're using the newer versions of `renv` consistently you can delete the old cache.

**Comment by kevinushey** [comment]
Closing this issue for now -- feel free to re-open or file a new issue if you have any further questions.
