### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#224]
Just sharing thoughts following new experience with `renv`

Currently, `renv` is not on CRAN and I am testing it in our offline servers by installing it manually (no access to GITHUB).

From the current documentation of `renv::upgrade`

> By default, this function will attempt to install the latest version of renv as available on the active R package repositories. If you'd instead like to try out a development version of renv, you can explicitly request a different version of renv and that version of the package will be downloaded and installed from GitHub. Use version = "master" to install the latest development version of renv, as from the renv project's GitHub page. 

I was under the impression that if not find on CRAN (which is currently the case), `renv` would say FALSE or "already up to date" if I ask to `upgrade`. However, that is not the default behavior I observed, and indeed it is not the default behavior in the code.  

`renv::upgrade` will look into my internal CRAN mirror, not find it, **then** look for a version Github, and at last R will hang until timeout as it can't access the web. 

I think the documentation could be improved to say what is the default behavior. 

I also open the issue if someone look for this during development phase.
Because once a first version will be one CRAN, this would not be an issue I guess. Unless for outdated or curated cran mirror where `renv` would not be available and `upgrade` would still try to look on github even if not asked to. 

This type of issue falls under "offline mode" category for renv - best scenario would be an option to deactivate all features requiring internet access. But like with remotes or pak, this is not always easy and this helps only a few of us who are still on offline environment 🤷‍♂

**Comment by kevinushey** [comment]
My expectation was that users wouldn't want to call `renv::upgrade()` unless they did indeed have access to a CRAN mirror with `renv`, or internet access with access to GitHub.

**Comment by cderv** [comment]
I agree with you. This is not an issue per se. 
I stumble upon it because I forgot to configure in option repo the special cran like repository with renv inside. I wanted to upgrade renv for a project but only the cran  without renv was configured in ˋrepos` option. 
I first did not understood why it hanged. (No error or something else). And The documentation did not helped. I understood when I read the code.

Feel free to close. I just wanted to share this as potential doc improvement but it should be a lot clearer after first cran release.

**Comment by kevinushey** [comment]
Now that `renv` is on CRAN, I think it's okay to leave this as-is :-)
