### ISSUE TITLE
restore() chooses the wrong directory for Rtools?

### ISSUE THREAD

**Issue by julieinsan** [rstudio/renv#225]
When I run `renv::restore()` the MASS package fails to install because the wrong directory is being used to find gcc.  But, when I run `devtools::find_rtools(debug = T)` devtools finds the right Rtools directory.  I have tried creating a .Renviron for the Project as well as editing the global .Renviron file. 

![renv issue](https://user-images.githubusercontent.com/6402308/67526443-c7379200-f682-11e9-8084-13ba6708aee5.PNG)

**Comment by kevinushey** [comment]
Thanks for the bug report! `renv` does not yet have any sophisticated scanning for Rtools.

As a workaround, you can try setting the environment variable:

```
Sys.setenv(RENV_PATHS_RTOOLS = "C:/Users/<username>/Rtools")
```

Does that make a difference?

**Comment by julieinsan** [comment]
That did the trick!  Thanks!

**Comment by kevinushey** [comment]
Great! I'm going to re-open this issue just as a reminder to myself to see if we can improve our own Rtools detection.

**Comment by kevinushey** [comment]
This has now been implemented.
