### ISSUE TITLE
How to `install_github` as link cache?

### ISSUE THREAD

**Issue by mik3y64** [rstudio/renv#226]
For CRAN packages, `renv::install` install packages as linked cache and automatically populate the `renv.lock` file without any issues.

For github packages, I successfully installed github package (private repo) and run `renv::snapshot` to populate `renv.lock` file. 

```
remotes::install_github('...')

renv::snapshot()
# Lockfile written to path/to/lib

sessionInfo()
# R version 3.6.1 (2019-07-05)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 18362)
# ...
```

However, doing so doesn't install the packages as linked cached like CRAN packages. How do I `install_github` as link cache? 

Thank you.

**Comment by adisarid** [comment]
Sorry for reiterating this closed issue, however - it doesn't work for me.
I.e., trying to install from a private repo `renv::install("***/***")`  yields an error:

```
Error: failed to resolve remote '***/***' -- failed to retrieve 'https://api.github.com/repos/***/***' [error code 22]
In addition: Warning message:
curl: (22) The requested URL returned error: 404  
```

Prior to that I followed the vignette trying to set the GitHub authentication key (i.e., `GITHUB_PAT`) which is to my understanding the equivalent of `remotes::install_github`'s auth_token argument, and `renv::install` doesn't work.

```
options(renv.auth.*** = list(GITHUB_PAT = "******"))
```

For now, I'm restricted to installing via `remotes::install_github("***/***", auth_token="*****")` and then using it to install my private-repo package. But it does not enter the cache so every project it's the same story all over again without the benefit of having a global cache for the package.

Sorry for not providing a rigorous reprex, but the package and the PAT are private... I'm hoping that maybe I'm doing something wrong which will be obvious with this broad description...

Any ideas?
@kevinushey

**Comment by kevinushey** [comment]
I'm not sure. I have a private repository, and this demonstrates that it works for me:

## Failing example

```
> options(renv.auth.private = list(GITHUB_PAT = "oops"))
> renv::install("kevinushey/private", rebuild = TRUE)
Retrieving 'https://api.github.com/repos/kevinushey/private/tarball/ee1a6dfd29dde94f79b320a826e8d1da0f33a971' ...
Warning: curl: (22) The requested URL returned error: 401 Unauthorized
Warning: curl: (22) The requested URL returned error: 401 Unauthorized
Error: failed to retrieve 'https://api.github.com/repos/kevinushey/private/tarball/ee1a6dfd29dde94f79b320a826e8d1da0f33a971' [error code 22]
Traceback (most recent calls last):
7: renv::install("kevinushey/private", rebuild = TRUE)
6: records <- retrieve(names(remotes)) at install.R#192
5: for (package in packages)
     handler(package, renv_retrieve_impl(package)) at retrieve.R#33
4: for (package in packages)
     handler(package, renv_retrieve_impl(package)) at retrieve.R#33
3: switch(source,
          bioconductor = renv_retrieve_bioconductor(record),
          bitbucket    = renv_retrieve_bitbucket(record),
          git          = renv_retrieve_git(record),
          github       = renv_retrieve_github(record),
          gitlab       = renv_retrieve_gitlab(record),
          repository   = renv_retrieve_repos(record),
          url          = renv_retrieve_url(record),
          renv_retrieve_unknown_source(record)
   ) at retrieve.R#149
2: renv_retrieve_package(record, url, path) at retrieve.R#248
1: if (inherits(status, "error"))
     stop(status) at retrieve.R#731
```

## Succeeding example

```
> options(renv.auth.private = list(GITHUB_PAT = Sys.getenv("GITHUB_PAT")))
> renv::install("kevinushey/private", rebuild = TRUE)
Retrieving 'https://api.github.com/repos/kevinushey/private/tarball/ee1a6dfd29dde94f79b320a826e8d1da0f33a971' ...
	OK [downloaded 603 bytes in 0.7 secs]
Installing private [0.0.0.9000] ...
	OK [built from source]
Copying private [0.0.0.9000] into the cache ...
	OK [copied to cache in 22 milliseconds]
```

The fact that you're seeing a 404 instead of a 401 error makes me think there's something else going on. Does your PAT have the required API permissions?

**Comment by adisarid** [comment]
I don't know how to explain the 404 versus the 401.
Now it works - I think that I might have had a typo in this code `options(renv.auth.*** = list(GITHUB_PAT = "******"))` and copying-and-pasting your code and re-writing might have fixed it.

I was wondering if adding an argument of `auth_token` to `renv::install` will help.
It will be more consistent with `remotes::install_github` which has this argument, and will make things straightforward for those who are used to this argument.

Thoughts?

**Comment by kevinushey** [comment]
We prefer to specify this via an option in `renv` to make this easier to pass to, for example, `renv::restore()`. This way, you can configure multiple different PATs on a per-package basis.

**Comment by adisarid** [comment]
Hi,
Thanks - I understand this preference.

I also found what was my problem. It wasn't a typo.

Trying this doesn't work `options(renv.auth.*** = list(GITHUB_PAT = "******"))`
(I was trying to set the PAT explicitly without using env variables).

You first have to use `Sys.setenv(GITHUB_PAT = "*****")`
Only then you can either use the PAT explicitly or use `Sys.getenv` like in your example. Both will work after you set the env variable.

I'm not sure why though. Is that intentional?

**Comment by kevinushey** [comment]
That is not intentional. I'll try to see what's going on.

**Comment by kevinushey** [comment]
Thanks -- I was able to reproduce the issue, and I believe it should be resolved on master now. Sorry for the trouble!

**Comment by adisarid** [comment]
Thanks!
