### ISSUE TITLE
renv::restore with a lockfile gives error

### ISSUE THREAD

**Issue by nettoyoussef** [rstudio/renv#227]
# Summary
- Renv version: renv_0.8.2
- Command used: renv:restore(lockfile = 'path/to/lockfile')
- The lockfile was generated using a migration from packrat (renv::migrate())
- renv restore returns an error:  Error: $ operator is invalid for atomic vectors

# Verbose
I am using `renv::restore` to  restore a project that was originally maintained with packrat. After using renv::migrate to adapt the lockfile, I tried to restore the project with renv but I was unable to do so.

The following error occurred when i tried the command:

```R
library(renv)
renv::restore(lockfile = 'path/to/lockfile')
# Error: $ operator is invalid for atomic vectors
```
However, when using `renv::restore()` using no arguments whatsoever, the installation ran fine.
I think maybe a recent change in the format of the arguments may be causing this issue.

A copy of the renv lockfile used is given below.

[renv.lock.txt](https://github.com/rstudio/renv/files/3779263/renv.lock.txt)

**Comment by kevinushey** [comment]
Thanks for the bug report + reproducible example! This should now be fixed on master.

**Comment by nettoyoussef** [comment]
Hi Kevin, 

Thanks for the fast response. I tested it and it is working fine.
