### ISSUE TITLE
`renv::load("dir_with_renv")` does not reload `renv` version specified in "dir_with_renv/renv.lock"

### ISSUE THREAD

**Issue by brshallo** [rstudio/renv#229]
> ...To point a project to another projects environment locally, I add the line to the ".Rprofile" : `renv::load("dir_with_renv")` ...

_Originally posted by @brshallo in https://github.com/rstudio/renv/issues/1#issuecomment-525054106_

One issue with above is that calling `renv::load("dir_with_renv")` loads the `renv` version on the general computer library rather than that specified in the private project's lock file (i.e. in "dir_with_renv/renv.lock").  Under the assumption the lock file is the single source of truth, #47 , would it make sense to have `renv::load()` reload `renv` to the version consistent with the lock file?  

(Or, if I want to accomplish this, what would be the most appropriate way?)

**Comment by kevinushey** [comment]
In theory, the current way would be to set the working directory and source the project `.Rprofile`; e.g.

```
owd <- setwd("dir_with_renv")
source(".Rprofile")
setwd(owd)
```

But I agree it would be nice to have `renv::load()` automatically do the right thing here, assuming it's not too messy to implement.

**Comment by brshallo** [comment]
Thanks, (in the project inheriting the environment) replaced `renv::load("dir_with_renv")` in the project .Rprofile with the code above and worked perfectly.

**Comment by kevinushey** [comment]
I've now implemented this on master -- if you have a chance, please give it a spin and let me know if things work as expected. Thanks!

**Comment by brshallo** [comment]
Thanks, tested out -- works perfectly.
