### ISSUE TITLE
iron down semantics of init() in different contexts

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#23]
hadley [9:37 AM]
1. No lockfile + no package library ->  discover package dependencies, install them, reload
2. Lockfile + no package library -> restore the project from the lockfile, reload
3. Anything else - ask whether you want 1 or 2

**Comment by kevinushey** [comment]
In interactive sessions, we now ask the user what action they want to take when we detect one of these cases.

```
> renv::init()
This project has already been initialized. What would you like to do? 

1: Discover and install R package dependencies.
2: Restore project from lockfile.
3: Activate the project without installing or snapshotting any packages.
```

@hadley what do you think?

**Comment by hadley** [comment]
I’d swap 1 and 2. It’s likely the wording will need tweaking, but I think that will need to wait for real users to see what confuses them.

**Comment by kevinushey** [comment]
Tweaked a bit:

```
> renv::init()
This project has already been initialized. What would you like to do? 

1: Restore the project from the lockfile.
2: Re-initialize the project, discovering and installing R package dependencies as required.
3: Activate the project without installing or snapshotting any packages.
```

Let me know what you think.

**Comment by hadley** [comment]
Maybe the initial text could be more descriptive? How about: This project has a lockfile, but no library. 

Oh then that suggests: 
1. Create a project library from the lockfile
2. Create a new lockfile from your system library 
3. Create an empty project library (???)

**Comment by slopp** [comment]
I actually think Kevin's current messaging addresses a different scenario than the original two outlined by Hadley, which is: lockfile + project library (e.g. what happens if you call `init` twice in a row).

Hadley, your other scenario (lockfile, no library) would then present different options?
