### ISSUE TITLE
Official position on using renv in package development?

### ISSUE THREAD

**Issue by cjvanlissa** [rstudio/renv#230]
Dear authors, thank you for the excellent work on renv, and congratulations on the recent CRAN release! I was wondering whether you would recomment using `renv` in package development, and if so, what the recommended workflow is? `packrat` had some hangups in this situation (https://github.com/rstudio/packrat/issues/31). Thank you sincerely, Caspar

**Comment by kevinushey** [comment]
Package development using renv is something we explicitly seek to support, and should work as expected with the current CRAN release.

That said, I'm sure there are still some rough edges to be ironed out so please feel free to file an issue if you find any!

**Comment by cjvanlissa** [comment]
So, one unusual thing I come accross is that it appears that, when renv is installed on a system, I can no longer Install and Restart packages that do **not** use `renv`. They remain locked to the previous version. When I do initialize `renv` within that project, I can Install and Restart them as usual (although I suspect the version number must be incremented). Is it intended behavior that, once you install renv, every project **must** use renv?

**Comment by kevinushey** [comment]
No, this is not the expected behavior. My best guess is that you may have accidentally initialized renv in your home directory, or otherwise modified your ~/.Rprofile so that the renv autoloader is run.

Aside from that, the error you're seeing is a bug in callr.

**Comment by cjvanlissa** [comment]
Yes, I believe that explanation is correct. Thank you!
