### ISSUE TITLE
[Package development] should the package in development be a dependency ? 

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#231]
Currently, using `renv` on a projet for package development
```r
> renv::init()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... [81/81] Done!
* Resolving missing dependencies  ... 
The following package(s) were not installed successfully:

	[poker.utils]: package 'poker.utils' is not available

You may need to manually download and install these packages.

The following package(s) will be updated in the lockfile:
# <truncated> here on GH
```

here `poker.utils` is the name of my package in development, and the dependency is found because I have a `library(poker.utils)` in vignettes. 

I wonder if, for package development, the dependency found with the name of the current package in dev (in DESCRIPTION) should be ignored by default. 

What do you think ?

**Comment by kevinushey** [comment]
Agree 100%! I'll try to fix this.

**Comment by kevinushey** [comment]
This should be fixed up on master -- please feel free to file an issue or re-open if you're still having issues. Thanks again for reporting!
