### ISSUE TITLE
Dependency versions from DESCRIPTION not installed and locked 

### ISSUE THREAD

**Issue by joemirizio** [rstudio/renv#233]
When using `renv` with a `DESCRIPTION` file, specified versions are not installed and locked in the lockfile.

### Expected behavior
Specifying `glue (== 1.2.0)` should install and lock `glue` version 1.2.0.

### Actual behavior
The latest version (1.3.1) is installed and locked.

### Steps to reproduce
Create a `DESCRIPTION` file with the following contents:
```
Package: renvtest
Imports:
  glue (== 1.2.0)
```

Run `renv::init()` and `glue-1.3.1` will be installed, but `renv::dependencies()` shows `glue-1.2.0` was required.
```r
> renv::init()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- glue   [* -> 1.3.1]

* Lockfile written to '/private/tmp/renvtest/renv.lock'.
* Project '/private/tmp/renvtest' loaded. [renv 0.8.2-14]
* renv activated -- please restart the R session.
> renv::dependencies()
Finding R package dependencies ... Done!
                             Source Package Require Version
1 /private/tmp/renvtest/DESCRIPTION    glue      ==   1.2.0
2   /private/tmp/renvtest/renv.lock    renv
> packageVersion('renv')
[1] ‘0.8.2.14’
```

**Comment by kevinushey** [comment]
Thanks! This is now implemented on master.

Note that you can also use `renv::install("glue@1.2.0")` to explicitly install a specific version of a package.

**Comment by joemirizio** [comment]
Wow, that was so fast! Thanks 😄

**Comment by cnolanminich** [comment]
Hi @kevinushey, it seems like {renv} is still not respecting package versions from `DESCRIPTION` files. I tried @joemirizio's example after running: `remotes::install_github("rstudio/renv")`

When I run `packageVersion("renv")` I get
> [1] ‘0.8.2.17’

but then I run renv::init() and glue-1.3.1 is installed, but renv::dependencies() shows glue-1.2.0 was required.
```r
> renv::init()
* "C:/Users/minichc/AppData/Local/renv" has been created.
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- glue   [* -> 1.3.1]

* Lockfile written to 'C:/users/minichc/code/R/renv-test/renv.lock'.
```

```r
> renv::dependencies()
Finding R package dependencies ... Done!
                                         Source Package Require Version
1 C:/Users/minichc/code/R/renv-test/DESCRIPTION    glue      ==   1.2.0
2   C:/Users/minichc/code/R/renv-test/renv.lock    renv                
```

**Comment by kevinushey** [comment]
Right, the fix was implemented only for `renv::install()` -- `renv::init()` has not yet been updated.

**Comment by kevinushey** [comment]
I'll have to think a bit about how to best handle this.

There is a bit of tension here in that, normally, `renv::init()` simply "forks" the current state of your R install, and then isolates that for use in your project. In effect, your R library state is taken as the source of truth; the versions of the R packages you have installed get copied / linked into a project library.

In this case, we want to override that and provide package versions directly in the DESCRIPTION file, and tell `renv` to use that instead. In other words, the DESCRIPTION is now the source of truth, rather than the R library.

For now, you should be able to do:

```
renv::init(bare = TRUE)
renv::install()
```

**Comment by krzyslom** [comment]
I just stumbled upon a similar issue.

I'm running `rocker/verse:4.0.0-ubuntu18.04` image with `renv 0.10.0.58`.
I start a new package project from the RStudio GUI in ~. With opened project I add the following code to the `DESCRIPTION` file
```
Imports:
    checkmate (== 1.8.0)
```
I run `renv::init(bare = TRUE)`, disable the cache, and run `renv::install("~/<my_pkg>")`.
The result is that the latest available version of the `checkmate` package (2.0.0) is downloaded and installed. `renv` ignores the version provided in the Imports section.

I also put conflicting versions in Imports and Remotes by mistake.
```
Imports:
    checkmate (== 1.8.0)
Remotes:
    mllg/checkmate@v1.7.4
```
This results in an attempt to install local package from `options("repos")`.
```
> renv::install("~/<my_pkg>")
Retrieving 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest/src/contrib/Archive/<my_pkg>/<my_pkg>_0.1.0.tar.gz' ...
Error: failed to retrieve package '<my_pkg>'
In addition: Warning messages:
1: curl: (22) The requested URL returned error: 404  
2: curl: (22) The requested URL returned error: 404  
```
I guess that having version described both in Remotes and in Imports is redundant, not to mention conflicting ones. However, this behavior implies that suddenly the version from the Imports section is not ignored after all.

Digging deeper I realized that the inner function `renv:::renv_retrieve_impl` assigns the following values to the `retrieved` variable
L110 - `<simpleError: GitHub record for package 'checkmate' has no recorded 'RemoteSha' / 'RemoteRef'>`
L120 - `<simpleError: <my_pkg> [0.1.0] is not available locally>`
Then it falls back to the switch and executes `renv:::renv_retrieve_unknown_source(record)` which results in mentioned error.

It took me a substantial amount of time to realize what is really happening. I can see that there is `# TODO: handle more explicit dependency requirements` in the source code, although I believe that a more informative error message would be much appreciated.

Like having non-existent reference to the remote source
```
Remotes:
    mllg/checkmate@v9.9.9
```
results in the following message
```
Warning messages:
1: curl: (22) The requested URL returned error: 422 Unprocessable Entity 
2: curl: (22) The requested URL returned error: 422 Unprocessable Entity 
3: failed to parse remote 'mllg/checkmate@v9.9.9' declared by package 'zzz'; skipping
```

**Comment by kevinushey** [comment]
The initial fix made was fairly narrow -- if you call `renv::install()` with no arguments, then `renv` will install packages as declared in the `DESCRIPTION` file. Those version requests don't get propagated or honored in other contexts yet, though.

**Comment by hadley** [comment]
I think it has since become clear the right solution here is:

```R
renv::init(bare = TRUE)
renv::install()
```
