### ISSUE TITLE
During installation, it attempts to render Rmds

### ISSUE THREAD

**Issue by labriola** [rstudio/renv#234]
In the course of doing an install or a migration from Packrat (same problem occurred in Packrat when used from within R Studio) R markdown files are apparently invoked. If you watch the processes, pandoc is invoked and you can briefly see rendering of the Rmd appear in source folders.

This seems to cause some form of infinite loop where it also hits the same git end points thousands of times in the course of an installation

**Comment by kevinushey** [comment]
`renv` does not attempt to render R Markdown documents -- it must be Packrat doing this.

A reproducible example would be helpful.

**Comment by labriola** [comment]
That's fair. I will come up with an example for you. Its tricky cause you need to setup packrat, then try to do the migrate to reproduce. Hang tight on this and I appreciate the follow up

**Comment by labriola** [comment]
I am going to close this issue here and I will reopen an issue at packrat with a reproduction case as it's better tracked there. I can confirm it happens both in the migrate from packrat but also in a packrat restore when in RStudio only.

**Comment by cderv** [comment]
FWIW packrat will in some case render the Rmd file to determine dependencies in Rmarkdown file
See https://github.com/rstudio/packrat/blob/505f12aa4ef884cc7021719f4f0e4b69a0b93354/R/dependencies.R#L611-617

**Comment by labriola** [comment]
Understood and thanks. It seems to get caught in a loop of rendering the same file again and again. I suspect (but have not confirmed) that somehow RStudio is noticing a change in the project files and either restarting or beginning some type of process that interferes. Just need to find more hours to debug. Many thanks.
