### ISSUE TITLE
Module Dependencies

### ISSUE THREAD

**Issue by labriola** [rstudio/renv#235]
This is a future-looking feature request. At the moment, dependencies expressed in patterns such as modules (https://cran.r-project.org/web/packages/modules/vignettes/modulesInR.html) are incorrectly identified. The consequences is that, unless one set snapshot type to simple, dependencies only used in these types of modules do not end up in the lock file (I am assuming during the dependency discovery phase it believes it's not needed).

Realize this is complex and renv::settings$snapshot.type("simple") is an easy workaround. Thanks

**Comment by kevinushey** [comment]
Is there a common pattern in the way modules are used that `renv` could crawl for dependencies?

**Comment by kevinushey** [comment]
IIUC we could try to crawl for `import()` calls within `module({})` definitions.

**Comment by labriola** [comment]
That's what I was thinking. Let me see if I can prototype it up in a PR. I don't know your code base particularly well yet so no concerns if the effort is for information only

**Comment by kevinushey** [comment]
For reference, we "register" a number of different methods for collecting dependencies from R scripts here:

https://github.com/rstudio/renv/blob/b434756f96cb1d0a701318a6d069955f532c93ef/R/dependencies.R#L537-L544

And this is a good example of how we parse packages from `xfun::pkg_attach()`:

https://github.com/rstudio/renv/blob/b434756f96cb1d0a701318a6d069955f532c93ef/R/dependencies.R#L572-L600

So a PR could add a similar method in this file.

**Comment by labriola** [comment]
Perfect. I appreciate the info, let's see what I can get working

**Comment by kevinushey** [comment]
Also worth saying up front -- if you put together a pull request, we do require a [Contributor License Agreement](https://www.rstudio.com/wp-content/uploads/2014/06/RStudioIndividualContributorAgreement.pdf) before we can accept pull requests on RStudio repositories. Would you be willing to fill one out, and send it to the e-mail indicated in the form? (Please also reference this PR in your e-mail.)

**Comment by labriola** [comment]
Understood and willing

**Comment by kevinushey** [comment]
Implemented via #238. Thanks!
