### ISSUE TITLE
permission denied error with renv::install

### ISSUE THREAD

**Issue by kubasmolik** [rstudio/renv#239]
On Ubuntu 18.04 I'm unable to install packages after initialising a project library. I got the message `* Project '~/kaggle/porto_seguro' loaded. [renv 0.8.3]`  so I assume renv was initialised properly, but when I called `renv::install(packages = "dplyr")` I got following error:
`* installing *source* package ‘assertthat’ ...
** package ‘assertthat’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
mv: cannot move '/home/kuba/kaggle/porto_seguro/renv/staging/1/00LOCK-assertthat/00new/assertthat' to '/home/kuba/kaggle/porto_seguro/renv/staging/1/assertthat': Permission denied
ERROR:   moving to final location failed`
**Any ideas what caused this issue and how can it be handled?**

My `sessionInfo()` output:
`R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    renv_0.8.3 `

**Comment by kevinushey** [comment]
The error seems to indicate that you lack write permissions into your project's library, which is surprising.

Can you confirm that you have read / write permissions in this project folder + its subdirectories?

**Comment by kubasmolik** [comment]
Permissions to project folder:
`drwxrwxrwx 1 kuba kuba 512 Nov 11 19:14 porto_seguro`

And to it's content:
`drwxrwxrwx 1 kuba kuba  512 Nov 11 15:19 data`
`-rw-r--r-- 1 kuba kuba 3029 Nov 11 19:14 log.txt`
`-rwxrwxrwx 1 kuba kuba  205 Nov 11 18:41 porto_seguro.Rproj`
`drwxrwxrwx 1 kuba kuba  512 Nov 11 15:18 r`
`drwxrwxrwx 1 kuba kuba  512 Nov 11 17:37 renv`

**Comment by kevinushey** [comment]
And the subdirectories?

**Comment by kubasmolik** [comment]
`kuba@Kuba:~/kaggle/porto_seguro/renv$ ls -l`
`-rwxrwxrwx 1 kuba kuba 5460 Nov 11 17:35 activate.R`
`drwxrwxrwx 1 kuba kuba  512 Nov 11 18:43 library`
`-rwxrwxrwx 1 kuba kuba  102 Nov 11 17:35 settings.dcf`
`drwxrwxrwx 1 kuba kuba  512 Nov 11 19:14 staging`

**Comment by kevinushey** [comment]
Okay, I don't have any great ideas. You may need to investigate further yourself.

To the best of my knowledge, nobody else is affected by this issue so it may be something local to your environment.

**Comment by kevinushey** [comment]
See also:

https://stackoverflow.com/questions/56241007/non-zero-exit-status-r-3-6-0-biobase

Are you running on Ubuntu through WSL?

**Comment by kubasmolik** [comment]
Yes, I was running Ubuntu on WSL. Setting `Sys.setenv(R_INSTALL_STAGED = FALSE)` solved the problem. 
Thanks fout your help :)

**Comment by kevinushey** [comment]
Phew! Very glad to hear it :-)
