### ISSUE TITLE
Suggests packages in CI/CD

### ISSUE THREAD

**Issue by matthijsvanderloos** [rstudio/renv#240]
I am trying to use `renv` for an internal package that I am developing, but I am running into two issues when building the package through our CI/CD pipeline.

The first issue concerns dependencies that are in the `Suggests` field in the `DESCRIPTION` of the package.

In my local development environment I have ran the following commands:
```R
renv::init(bare = true)
renv::install()
```
This correctly sets up my development environment by also installing any suggested dependencies.

During build time the following commands are executed (as suggested [here](https://rstudio.github.io/renv/articles/ci.html)):
```
Rscript -e "renv::restore()"
R CMD build
R CMD check
```
but this results in the following error:

```
* checking package dependencies ... ERROR
Packages suggested but not available:
  'data.table', 'devtools', 'DBI', 'odbc', 'roxygen2'
```
which makes sense, because suggested dependencies are not in `renv.lock`. What is the suggested workflow here? Should I run `renv::install()` in the build script? 

~~Regarding the second issue: my build script compiles windows binaries of the package for several versions of R, but the lockfile is linked to a specific version of R. Do you have suggestions to handle this situation?~~

EDIT: ok, I now see that using a different R version only results in a warning...

**Comment by kevinushey** [comment]
Thanks for the bug report! This is indeed a bug in `renv`.

For context, there's a convention for non-package projects to declare required dependencies in a DESCRIPTION file. Under that scheme, packages mentioned in the `Suggests` field are normally not required during runtime, but instead are required during development.

That is not true for package projects -- normally, I believe, one wants `Suggests` to be installed.

Using `renv::install()` would indeed be an appropriate workaround, but I'll see about getting this fixed so `renv::restore()` works without issue as well.

**Comment by matthijsvanderloos** [comment]
Thanks for the confirmation and your explanation! Is the convention for non-package projects to use a DESCRIPTION file documented anywhere? 

For now, I am skipping any checks that require suggested dependencies by setting the `_R_CHECK_FORCE_SUGGESTS_` environment variable to `false`.

I did, however, discover another issue while migrating to `renv`. When I don't explicitly list `devtools` and/or `roxygen2` as suggested dependencies, running `renv::install()` returns an error:

```R
> renv::install()
Error in spec[spec$Require == "==", ] : incorrect number of dimensions
 ```

**Comment by kevinushey** [comment]
> Thanks for the confirmation and your explanation! Is the convention for non-package projects to use a DESCRIPTION file documented anywhere?

Good question -- I'm not sure yet, but I think there is a push (at least in the tidyverse) to adopt that as a sort of best-practice for declaring dependencies in data science projects.

> I did, however, discover another issue while migrating to renv. When I don't explicitly list devtools and/or roxygen2 as suggested dependencies, running renv::install() returns an error:

Let me see if I can reproduce.

**Comment by kevinushey** [comment]
I'm not able to reproduce your second error. Can you provide some more specific reproduction steps?

**Comment by kevinushey** [comment]
The issue you noted with `renv::install()` should now be fixed up on master. Sorry for the trouble!

**Comment by matthijsvanderloos** [comment]
Great, thanks! The `renv::install()` call is working now indeed.
