### ISSUE TITLE
Working in a shared renv in two machines

### ISSUE THREAD

**Issue by adomingues** [rstudio/renv#241]
The way our work is set-up is that sometimes we work on a project on a server (for compute-heavy tasks), others in the locally mounted project folder (quick plotting etc). In effect we access the same `renv` from two different locations. Both OSs are unix-based (LInux on the server side, and OSX or linux on client side). 

My expectation was that, assuming that the R version is the same on the server and client, we could load `renv `on either and carry on with the work having the same version of all libraries. So as a test I created an `renv` locally, did some work on it, and then logged into the server. There the renv was recognize by the R session, however there was warning:

```R
 Project '/lustre/projects/bioinfo/domingue/scripts/motifs' loaded. [renv 0.8.3]
Warning message:
The following package(s) are missing entries in the cache:

        acepack, annotate, AnnotationDbi, AnnotationFilter, ape,
        argparser, backports, bamsignals, base64enc, beachmat,
        beeswarm, bezier, BH, bibtex, Biobase, BiocGenerics,
        BiocManager, BiocNeighbors, BiocParallel, BiocSingular,
        biomaRt, Biostrings, biovizBase, bit, bit64, bitops, blob,
        BSgenome, callr, caTools, checkmate, cluster,
        clusterProfiler, codetools, colorspace, corescf, covr,
        cowplot, crosstalk, cummeRbund, curl, data.table, DBI,
        DelayedArray, DelayedMatrixStats, DESeq2, devtools,
        dichromat, digest, DO.db, docopt, DOSE, dplyr, dqrng, DT,
        ellipsis, enrichplot, ensembldb, europepmc, fansi, farver,
        fastcluster, fastmap, fastmatch, fdrtool, fgsea,
        fitdistrplus, FNN, forcats, foreach, foreign, formatR,
        Formula, futile.logger, futile.options, future,
        future.apply, gbRd, gdata, genefilter, geneplotter,
        GenomeInfoDb, GenomeInfoDbData, GenomicAlignments,
        GenomicFeatures, GenomicRanges, GGally, ggbeeswarm,
        ggforce, g [... truncated]
```

After a quick search, it seems that the libraries are missing because the packages are symlinked in `renv`, which is expected.

The question is how circumvent this issue? Is it even possible to use `renv` in this situation?  Would something like `renv::isolate()` or callling `renv::restore()` in the server be a solution?

**Comment by kevinushey** [comment]
Do your two machines have a shared filesystem somewhere? If so, you can instruct `renv` to use that filesystem for its package cache, with something like:

```
RENV_PATHS_CACHE = /shared/storage/renv/cache
```

See `?paths` for more details.

If not, then I think `renv::isolate()` + `renv::restore()` is the most appropriate solution.

**Comment by kevinushey** [comment]
I think my response answers your question -- please feel free to re-open or file a new issue if you have any other questions.

**Comment by adomingues** [comment]
@kevinushey apologies for not replying. I am testing option 2 and thinking about the implementation details of option 1, and therefore didn't want to reply before having some hard facts on either. But yes, the machines do share a (mounted) filesystem.
