### ISSUE TITLE
R CMD build significantly slower

### ISSUE THREAD

**Issue by matthijsvanderloos** [rstudio/renv#245]
When I build a package that makes use of  `renv`, it takes much longer to build the package than without `renv`, even though the `renv` folder is in `.Rbuildignore`:

```
v  checking for file 'C:\pkg/DESCRIPTION' (810ms)
-  preparing 'pkg': (1m 22s)
v  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (35.3s)
-  checking for empty or unneeded directories
-  building 'pkg_1.0.0.tar.gz'
```

When I temporarily move the `renv` folder out of the root package folder, package build is much faster:
```
v  checking for file 'C:\pkg/DESCRIPTION' (763ms)
-  preparing 'pkg': (5.2s)
v  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (3.6s)
-  checking for empty or unneeded directories
-  building 'pkg_1.0.0.tar.gz'
```

This is probably due to `R CMD build` copying all directories/files first and then removing any that are in `.Rbuildignore`, as explained [here](https://community.rstudio.com/t/r-cmd-check-preparing-package/27151).

Do you have any suggestions how to speed up package building when using `renv`?

**Comment by kevinushey** [comment]
You are indeed correct -- unfortunately, R filters files using `.Rbuildignore` _after_ copying them to the build directory. I'll have to think about whether there's a clean solution to this...

**Comment by kevinushey** [comment]
Here's where `R CMD build` (ie, `tools:::.build_package()`) copies the package sources to a build directory:

```
https://github.com/wch/r-source/blob/18aa82c79745d99f3da3375e8585321654064f7d/src/library/tools/R/build.R#L990-L1004
```

Unfortunately, this doesn't give `renv` a lot of opportunities to try and hide the `renv/library` folder during build.

I think the best solution would be to use an out-of-source library directory. This can be done by setting the `RENV_PATHS_LIBRARY` environment variable; e.g. in a project `.Renviron`:

```
RENV_PATHS_LIBRARY=/path/to/library
```

I might need to think about whether this becomes a default behavior in `renv` or not.

**Comment by kevinushey** [comment]
See also this R feature request: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17549

**Comment by matthijsvanderloos** [comment]
Thanks again for the clarification! For now, I'll use an out-of-source library directory to speed up building.

I did notice, however, that after setting `RENV_PATHS_LIBRARY` to `~/.renv/<pkg>/library` and running `renv::restore()`, packages are not cached anymore but installed directly into the out-of-source library directory. I don't think this is to be expected?

**Comment by kevinushey** [comment]
You are correct, that is not expected! I suspect I know what's going on. We have some code that tries to avoid using symlinks unless we know we're copying to a project library, but I suspect that check is failing.

I will take a look today.

**Comment by kevinushey** [comment]
A potential workaround would be to use:

```
Sys.setenv(RENV_PATHS_LIBRARY = path.expand("~/.renv/<pkg>/library"))
```

That is, I suspect the bug here occurs if the library path is not equivalent to its "normalized" form. Is that true in your case?

Regardless, I think this is worth fixing.

**Comment by matthijsvanderloos** [comment]
Just upgraded to version `0.8.3-25` and the cache is now being used even when the library path is non-normalized. Thanks again!

**Comment by kevinushey** [comment]
Very glad to hear it! I think everything in this issue should be resolved now; please feel free to re-open or file a new issue if that is not the case.
