### ISSUE TITLE
renv::init() fails on "no space left on device"

### ISSUE THREAD

**Issue by leungi** [rstudio/renv#246]
Destination drive has plenty (7+ TB), yet `renv::init()` is unable to copy files over.

```r
> renv::init()
This project already has a lockfile. What would you like to do? 

1: Restore the project from the lockfile.
2: Discard the lockfile and re-initialize the project.
3: Activate the project without snapshotting or installing any packages.

Selection: 2
Error in file.copy(source, tempdir, recursive = TRUE) : 
  problem copying C:\Users\Public\Data\R\R-3.5.1\library\renv\html\modify.html to P:\project\stooip\renv\library\R-3.5\x86_64-w64-mingw32\renv-copy-12e8c7c9f7b9d\renv\html\modify.html: No space left on device
```

**Comment by kevinushey** [comment]
Is `P:/` mapped to a network filesystem, or something similar? Can you provide any other information?

**Comment by leungi** [comment]
Thanks for prompt response; apologies for lack of info.

Indeed, `P:/` is a mapped network drive.

**Comment by kevinushey** [comment]
Is the error reproducible? Do you alway see the exact same error, or do you see slight differences (e.g. it fails on a different file)?

**Comment by leungi** [comment]
Apologies for delayed response.

`renv` previously got stuck on 16/107 packages, and when I reran and it went pass that mark, I let it run over weekend, and it completed 🙌.

I suspect network drive issue.

On a side note; it took almost half a day for `renv::init()` to complete for 107 packages; is that duration reasonable?

```r
> renv::init()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... [107/107] Done!
NOTE: Dependency discovery took 20 seconds during snapshot.
Consider using .renvignore to ignore files -- see `?dependencies` for more information.
Use `renv::settings$snapshot.type("simple")` to disable dependency discovery during snapshot.
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- BH                [* -> 1.69.0-1]
- DBI               [* -> 1.0.0]
- MASS              [* -> 7.3-51.4]
- Matrix            [* -> 1.2-17]
- R6                [* -> 2.4.0]
- RColorBrewer      [* -> 1.1-2]
- askpass           [* -> 1.1]
- assertthat        [* -> 0.2.1]
- backports         [* -> 1.1.5]
- base64enc         [* -> 0.1-3]
- broom             [* -> 0.5.2]
- callr             [* -> 3.3.0]
- cellranger        [* -> 1.1.0]
- cli               [* -> 1.1.0]
- clipr             [* -> 0.6.0]
- colorspace        [* -> 1.4-1]
- crayon            [* -> 1.3.4]
- crosstalk         [* -> 1.0.0]
- curl              [* -> 4.2]
- dbplyr            [* -> 1.4.0]
- digest            [* -> 0.6.21]
- dplyr             [* -> 0.8.3]
- ellipsis          [* -> 0.3.0]
- evaluate          [* -> 0.14]
- fansi             [* -> 0.4.0]
- forcats           [* -> 0.4.0]
- fs                [* -> 1.3.1]
- generics          [* -> 0.0.2]
- ggplot2           [* -> 3.2.1]
- glue              [* -> 1.3.1]
- gridExtra         [* -> 2.3]
- gtable            [* -> 0.3.0]
- haven             [* -> 2.1.0]
- highr             [* -> 0.8]
- hms               [* -> 0.4.2]
- htmltools         [* -> 0.4.0]
- htmlwidgets       [* -> 1.5.1]
- httpuv            [* -> 1.5.2]
- httr              [* -> 1.4.1]
- jsonlite          [* -> 1.6]
- labeling          [* -> 0.3]
- lattice           [* -> 0.20-38]
- lazyeval          [* -> 0.2.2]
- lifecycle         [* -> 0.1.0]
- lubridate         [* -> 1.7.4]
- magrittr          [* -> 1.5]
- markdown          [* -> 1.1]
- mgcv              [* -> 1.8-28]
- mime              [* -> 0.7]
- modelr            [* -> 0.1.4]
- munsell           [* -> 0.5.0]
- nlme              [* -> 3.1-140]
- openssl           [* -> 1.4.1]
- pillar            [* -> 1.4.2]
- pkgconfig         [* -> 2.0.3]
- plogr             [* -> 0.2.0]
- plyr              [* -> 1.8.4]
- png               [* -> 0.1-7]
- prettyunits       [* -> 1.0.2]
- processx          [* -> 3.4.1]
- ps                [* -> 1.3.0]
- purrr             [* -> 0.3.2]
- raster            [* -> 2.9-5]
- readr             [* -> 1.3.1]
- readxl            [* -> 1.3.1]
- rematch           [* -> 1.0.1]
- reprex            [* -> 0.2.1]
- reshape2          [* -> 1.4.3]
- rgdal             [* -> 1.4-4]
- rlang             [* -> 0.4.1]
- rmarkdown         [* -> 1.15]
- rvest             [* -> 0.3.3]
- scales            [* -> 1.0.0]
- selectr           [* -> 0.4-1]
- shiny             [* -> 1.3.2]
- shinyFiles        [* -> 0.7.3]
- shinyWidgets      [* -> 0.4.8]
- shinycssloaders   [* -> 0.2.0]
- sourcetools       [* -> 0.1.7]
- sp                [* -> 1.3-1]
- stringi           [* -> 1.4.3]
- stringr           [* -> 1.4.0]
- sys               [* -> 3.3]
- tibble            [* -> 2.1.3]
- tidyr             [* -> 1.0.0]
- tidyselect        [* -> 0.2.5]
- tidyverse         [* -> 1.2.1]
- tinytex           [* -> 0.16]
- utf8              [* -> 1.1.4]
- viridis           [* -> 0.5.1]
- viridisLite       [* -> 0.3.0]
- whisker           [* -> 0.4]
- xfun              [* -> 0.9]
- xml2              [* -> 1.2.2]
- xtable            [* -> 1.8-4]
- yaml              [* -> 2.2.0]
- zeallot           [* -> 0.1.0]

# GitHub =============================
- Rcpp              [* -> RcppCore/Rcpp]
- knitr             [* -> yihui/knitr]
- later             [* -> r-lib/later]
- leaflet           [* -> rstudio/leaflet]
- progress          [* -> r-lib/progress]
- promises          [* -> rstudio/promises]
- reticulate        [* -> rstudio/reticulate]
- rstudioapi        [* -> rstudio/rstudioapi]
- vctrs             [* -> DavisVaughan/vctrs@c-exports]
- withr             [* -> r-lib/withr]

* Lockfile written to 'P:/project/stooip/renv.lock'.

Restarting R session...

* Project 'P:/project/stooip' loaded. [renv 0.8.3-16]
```

**Comment by kevinushey** [comment]
> On a side note; it took almost half a day for renv::init() to complete for 107 packages; is that duration reasonable?

That's longer than I would expect, but I could see that happening if your project and the `renv` global cache lived on different disk drives.

You may want to set the `RENV_PATHS_CACHE` environment variable to somewhere on your `P:/` drive. For example, you could put in your project `.Renviron`:

```
RENV_PATHS_CACHE = "P:/path/to/cache"
```

since the cache by default uses your system drive (normally `C:/`).

**Comment by kevinushey** [comment]
FWIW, the most recent versions of `renv` will use `robocopy` for directory copies, which should (in theory) be more performant + reliable than the base R file copying tools. You may have better luck with the latest version of `renv` as well.

**Comment by kevinushey** [comment]
I've now also added a comment in the intro vignette detailing this recommendation:

https://github.com/rstudio/renv/commit/47cc0f5ef7fc68d870f21df0bc5b84edac7314a6

With that, I think this issue is a little bit better documented + understood now. Please feel free to re-open or file a new issue if you find you're still having trouble. Thanks!

**Comment by leungi** [comment]
> > On a side note; it took almost half a day for renv::init() to complete for 107 packages; is that duration reasonable?
> 
> That's longer than I would expect, but I could see that happening if your project and the `renv` global cache lived on different disk drives.
> 
> You may want to set the `RENV_PATHS_CACHE` environment variable to somewhere on your `P:/` drive. For example, you could put in your project `.Renviron`:
> 
> ```
> RENV_PATHS_CACHE = "P:/path/to/cache"
> ```
> 
> since the cache by default uses your system drive (normally `C:/`).

Thanks for the tip; will do!

**Comment by leungi** [comment]
> FWIW, the most recent versions of `renv` will use `robocopy` for directory copies, which should (in theory) be more performant + reliable than the base R file copying tools. You may have better luck with the latest version of `renv` as well.

@kevinushey: update on this.

- Install latest from Github
- Set `RENV_PATHS_CACHE` to same network drive where projects are
- success on first `renv::init()` run 👍
- run completed under  1.5 hour 😎
