### ISSUE TITLE
renv::restore tries to download unknown source (i.e. local) package from CRAN

### ISSUE THREAD

**Issue by kendonB** [rstudio/renv#249]
I have an renv with a user package. After snapshotting on my Ubuntu machine I tried to restore on my Windows virtualbox and got this:

```
> renv::restore()
The following package(s) were installed from an unknown source:
             _
  degreedays   [0.1]

renv will install the latest version(s) from your R package repositories instead.

Do you want to proceed? [y/N]: y
The following package(s) will be updated:

# CRAN ===============================
- RcppParallel   [* -> 4.4.4]

# (Unknown Source) ===================
- degreedays     [* -> 0.1]

Do you want to proceed? [y/N]: y
* Querying repositories for available binary packages ... Done!
Retrieving 'https://cloud.r-project.org/bin/windows/contrib/3.6/RcppParallel_4.4.4.zip' ...
	OK [file is up to date]
* Querying repositories for available source packages ... Done!
Retrieving 'https://cloud.r-project.org/src/contrib/Archive/degreedays/degreedays_0.1.tar.gz' ...
Error: failed to retrieve package 'degreedays'
In addition: Warning messages:
1: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 Not Found
2: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 Not Found
```
Ubuntu 18.04
RStudio 1.2.5001
R 3.6.1

then:
Win 10 VB Guest
RStudio 1.2.522
R 3.6.1

The two machines are sharing the renv folder (i.e. it is mounted on the Windows virtual machine)

**Comment by kevinushey** [comment]
This is the expected behavior: `renv` cannot restore packages do not record an external source. It will try to assume CRAN in some cases as a fallback (since some users might intentionally want to restore packages from a CRAN-like repository serving that package) but in general you need to ensure packages are installed from a known source.

Alternatively, see https://rstudio.github.io/renv/articles/local-sources.html for some other ways to handle this.

**Comment by kendonB** [comment]
Thanks for this @kevinushey. Is there a more useful error / warning message that could be printed? Perhaps you could even link to that vignette in the error message?
