### ISSUE TITLE
install() and friends should remind you to snapshot()

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#25]
I think a reminder message after the function completes would be adequate. Something like: "don't forget to snapshot when you're confident the packages work"

**Comment by jjallaire** [comment]
One tension we have here is whether the package is constantly chirping at you or whether it mostly leaves you alone. The early versions of packrat had all kinds of console messages (e.g. after installs) and people found that annoying and even sometimes confusing. 

That said, I find the workflow of e.g. `npm` where you do `npm install --save foo` as kind of your default way to install packages to be excellent (you never "forget" to snapshot if you do this). I wonder if renv should have it's own install function that proxies to install.packages and does this snapshot automatically?

**Comment by hadley** [comment]
I was talking about this with @kevinushey: the problem with `install()` auto-snapshotting is that what happens if you can't get your code to update to the new version of the package, and you want to rollback to the previous snapshot? Can we now assume that renv uses are also use git, so if that happens they can `git revert`? I think that would be a powerful simplifying assumption.

**Comment by jjallaire** [comment]
Interesting, it hadn't occurred to me that `npm install --save` pretty much assumes that you are using version control. I don't know if this is a safe assumption in our case, so maybe the original idea (reminder) is the best way to split the difference.

**Comment by hadley** [comment]
Another approach would be to assume git, and then later back pedal if that assumption is wrong. Do we really expect people to be deploying to production or researching reproducibly without git?

**Comment by kevinushey** [comment]
I think something like this would be best handled in the IDE (as opposed to by `renv` directly) with some minimal UI explaining when the lockfile + project library are out of sync. Something less aggressive than what we had explored with Packrat but enough to signal to the user.

Right now I'm thinking of something in the Console pane's header e.g. a small icon that highlights or similar when things are out of sync. The icon could live next to the broom icon we display for cleaning console output.

**Comment by kevinushey** [comment]
renv now automatically snapshots by default after an `renv::install()`.
