### ISSUE TITLE
Allow for non tarred/zipped folders in RENV_PATHS_LOCAL?

### ISSUE THREAD

**Issue by kendonB** [rstudio/renv#250]
Currently, it looks like the only way to use a local source is to first install to a zip or tar. Would be good to also be able to just try to install like `install.packages("${RENV_PATHS_LOCAL}/<package>")`?

**Comment by kevinushey** [comment]
But the package version / sha needs to be tagged on the archive name; e.g.

```
<package>_<version>.tar.gz
```

You _could_ put the package folder there with that format, but at that point you might as well just create an archive anyhow.

(Recall that `renv` tries to restore the exact version of the package recorded in the lockfile as well)

**Comment by kendonB** [comment]
Actually I'm going to disagree with my past self that this is a good idea. I was thinking it would sacrifice a bit of reproducibility for the sake of convenience bit that's probably a bad idea. 

While we're here, do you have/know of a vignette for how to build a user package, calculate the checksum, and tar/zip?

**Comment by kevinushey** [comment]
I think the regular R tools are appropriate here; e.g.

```
# build a source package
R CMD build --md5 package

# build a binary package
R CMD INSTALL --build package
```

It is perhaps a bit surprising that one builds a binary package through `R CMD INSTALL`, but it makes sense in the context that a binary is just an archive of an already-installed package.

**Comment by kevinushey** [comment]
And I suppose the canonical documentation is in R-exts:

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Building-package-tarballs
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Building-binary-packages

**Comment by kevinushey** [comment]
Ultimately, I think it's best not to take any action here -- if you disagree, feel free to re-open. Thanks!
