### ISSUE TITLE
renv::restore() on a networked drive

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#251]
Hi,  I've been using renv and it's been incredibly useful..thank you!

Everything works as I expect when I `restore()` a project's libraries if the R project is saved to my local drive (in my case, my C: drive on Windows 10). But if I move the same project to a networked drive, `restore()` no longer works.  I don't get any errors, and it appears as though everything has worked properly.  Is there anything special I need to configure to get this working on a networked drive?

These are the results I get when I try to restore (and this code works if I move the project folder to my C: drive).  After I restore, the `renv/library` folder is populated with a survival folder, but the folder is empty.
```r
* Project 'G:/TEST/oyoyoyoyoyoyo' loaded. [renv 0.8.3]
> renv::restore()
The following package(s) will be updated:

# CRAN ===============================
- survival   [3.1-7 -> 2.44-1.1]

Do you want to proceed? [y/N]: y
Installing survival [2.44-1.1] ...
> renv::status()
The following package(s) are missing their DESCRIPTION files:

	survival

Consider removing or re-installing these packages.
Library: "G:/TEST/oyoyoyoyoyoyo/renv/library/R-3.6/x86_64-w64-mingw32"

The following package(s) are out of sync:

   Package   Lockfile Version   Library Version
  survival           2.44-1.1             3.1-7

Use `renv::snapshot()` to save the state of your library to the lockfile.
Use `renv::restore()` to restore your library from the state of the lockfile.
```

Thank you for taking a look!

**Comment by kevinushey** [comment]
Can you try again using the development version of `renv`, and let me know if things work better?

You can use `renv::upgrade(version = "master")` to install the latest development version.

**Comment by ddsjoberg** [comment]
Thank you so much for the response.  The same issue is occurring using the dev version.  After running `restore()`, the survival folder is created in the `renv/library` folder, but the folder is empty (i.e. the older version of survival was not successfully restored).

```r
> renv::upgrade(version = "master")
A new version of the renv package will be installed:

# GitHub =============================
- renv   [0.8.3 -> rstudio/renv]

This project will use the newly-installed version of renv.

Do you want to proceed? [y/N]: y
Retrieving 'https://api.github.com/repos/rstudio/renv/tarball/bed65ffbe873aad0c055f51d81912bfdeeebba81' ...
	OK [downloaded 186.2 Kb in 0.4 secs]
Installing renv [0.8.3-25] ...
	OK [built from source]

Restarting R session...

* Project 'G:/TEST/oyoyoyoyoyoyo' loaded. [renv 0.8.3-25]
> renv::restore()
The following package(s) will be updated:

# CRAN ===============================
- survival   [3.1-7 -> 2.44-1.1]

Do you want to proceed? [y/N]: y
Installing survival [2.44-1.1] ...
> renv::status()
The following package(s) are missing their DESCRIPTION files:

	survival [G:/TEST/oyoyoyoyoyoyo/renv/library/R-3.6/x86_64-w64-mingw32/survival]

These may be left over from a prior, failed installation attempt.
Consider removing or re-installing these packages.

The following package(s) are out of sync:

   Package   Lockfile Version   Library Version
  survival           2.44-1.1             3.1-7

Use `renv::snapshot()` to save the state of your library to the lockfile.
Use `renv::restore()` to restore your library from the state of the lockfile.

> 
```

**Comment by kevinushey** [comment]
Thanks for reporting back! Let me see if I can prepare a similar environment locally and reproduce the issue.

**Comment by kevinushey** [comment]
The other thing I would recommend trying: normally, the `renv` package cache is stored on the default system drive (typically `C:/`); in your case, you might instead want to keep it on the networked drive `G:/`.

To that end, you could try writing the following to a project `.Renviron`:

```
RENV_PATHS_CACHE = "G:/path/to/renv/cache"
```

where that path is some existing directory within `G:/` that could be used for the `renv` cache.

**Comment by kevinushey** [comment]
I have a candidate fix in master now -- can you try updating once more with `renv::upgrade(version = "master")` and let me know if you have better luck (or, at least, get an error message on failure)?

**Comment by ddsjoberg** [comment]
Wow!  That is great!  The update you pushed fixed the issue!  :hibiscus: With the update, `restore()` works properly if the cache is on the C drive or the networked G drive. :fireworks: :fireworks: :fireworks:

**Comment by kevinushey** [comment]
Fantastic :-) Thank you for the bug report; I'm glad to we were able to find a fix!
