### ISSUE TITLE
RStudio package pane list shows all system packages

### ISSUE THREAD

**Issue by rpodcast** [rstudio/renv#26]
I'm so happy to see `renv` out in the open now!  I'm just getting started and I noticed that after I run `renv::init()` within a newly created RStudio project that the packages pane still lists all of the available R packages in the global R library.  I'm hoping that in a future update that the IDE will only show the packages in the `renv` custom library, like how `packrat` currently operates in the IDE?

**Comment by kevinushey** [comment]
Can you elaborate on what you're seeing? In RStudio I see the packages reported as part of the "Packrat Library".

![Screen Shot 2019-03-20 at 2 02 43 PM](https://user-images.githubusercontent.com/1976582/54718904-d963b780-4b18-11e9-8806-acdab273b486.png)

**Comment by rpodcast** [comment]
I did some more testing and it seems to only happen on an older version of RStudio server (in this case version `1.1.453` running on a RHEL 7 server).  On my mac and ubuntu laptops (each running the preview release of RStudio) the packages show up just like your screenshot above.  Even with `packrat` I would occasionally have the same issue in the packages pane.  I'll close and re-open if I see anything odd occur with the preview RStudio release.
