### ISSUE TITLE
Documentation improvement on local source package

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#262]
While trying to configure all renv paths for a RStudio server cluster, I stumble upon soemthing not clear in the documentation about where local source packages should be

### In the vignette 

https://rstudio.github.io/renv/articles/local-sources.html
Only `RENV_PATHS_LOCAL` is mentioned and, if unset, it is a folder parent of  `RENV_PATHS_ROOT` 

### In the paths help page 

https://rstudio.github.io/renv/reference/paths.html#local-sources

It says that local source can be put into the project folder

```
<project>/renv/local/<package>_<version>.<ext>
<project>/renv/local/<package>/<package>_<version>.<ext>
```

it seems to be here in the code
https://github.com/rstudio/renv/blob/cfbbf9e9868f1a22a4d6748785ac15382b2feb59/R/retrieve.R#L280

FWIW, I think this should be added to the local source vignettes.

**Comment by kevinushey** [comment]
Thanks -- I'll make that change.
