### ISSUE TITLE
permit automatic upgrade of some packages?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#263]
From https://community.rstudio.com/t/error-message-installing-nlme-with-restore-command/45246.

---

In some cases, `renv::restore()` may fail on Windows or macOS because:

1. One of the packages recorded in the lockfile is no longer current; hence
2. That package must be installed from archive sources, but
3. The user's machine does not have the necessary tools to build the package.

We should consider accommodating such cases by instead choosing to download the latest available binary.

**Comment by hadley** [comment]
Another instance of #1188
