### ISSUE TITLE
add a use_renv_ignore to help maintain `.renvignore` file ?

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#267]
This is an idea I share as feature request 

I find this functions in usethis really useful to help maintain `*ignore` files from R

* [`use_git_ignore`](https://usethis.r-lib.org/reference/use_git_ignore.html) for `.gitignore`
* [`use_build_ignore`](https://usethis.r-lib.org/reference/use_build_ignore.html)  for `.Rbuildignore`

How about `renv::use_renv_ignore`  that would add something to `.renvignore` and create it if not yet existing ?

I understand if this is too high level for renv. Editing directly the file is easy too but I guess usethis package has made me lazy 😉

**Comment by kevinushey** [comment]
Sorry, but I think it's more appropriate that users edit these files with a text editor.

**Comment by cderv** [comment]
yep it is completely understandable. Thank you for considering anyway.
