### ISSUE TITLE
Add check for updated dependency versions to renv install.packages shim

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#268]
Much like `remotes` offers to upgrade packages for you when installing packages that depend on them, perhaps `renv` could offer something similar in its `install.packages()` shim? 

Otherwise, these types of errors are annoying, because you must go through them one-by-one:
```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.4.0 is being loaded, but >= 0.4.1 is required
```

**Comment by kevinushey** [comment]
A reproducible example would be helpful.

**Comment by colearendt** [comment]
Yeah 😓 Definitely should have made a reprex first. Sorry! I am having trouble reproducing this. I will close for now until / unless I can figure out how to reproduce!
