### ISSUE TITLE
Enhancement: Show progress for copying packages to cache

### ISSUE THREAD

**Issue by rpodcast** [rstudio/renv#27]
Minor comment but when I initialized `renv` in a Shiny app project directory (in this case a very [simple example](https://rstudio.github.io/shinydashboard/get_started.html) with `shinydashboard`) it took a bit of time for the packages to be copied to the cache.  It would be nice to have an optional flag to show a progress bar in this step.

**Comment by kevinushey** [comment]
Good idea! (hopefully only that first `init()` will be slow and future calls will be nice and fast however)
