### ISSUE TITLE
shouldn't renv narrow to project packages when snapshot type is `packrat`?

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#271]
If I add `library(blabla)` to my project files `renv::status` does not detect it. The other way around, when I install a package which is not loaded by the project, `renv:status` will report it and `renv::snapshot()` will shove it into the `renv.lock`. 

It looks to me that, when snapshot type is packrat, renv should differentiate between used and unused packages in the library, and snapshot only the used ones. What do you think?

The motivation behind this is somewhat similar to what has been discussed in #121. I want to share with collaborators only the state of the relevant packages, not all the mambo-jumbo that I play with while experimenting and learning locally. 

I know there is `settings::ignored.packages`, but we are after is more like `used.packages`. Is there a way to achieve this currently?

**Comment by vspinu** [comment]
To be more specific, I am talking about `project` in a loose sense. It's not an R package, there is no DESCRIPTION in the root, only .Rproj file.

**Comment by cderv** [comment]
I observed the opposite. It took me time to see that `renv` will by default only lock the package that are indeed dependencies of my code and not lock every package I have available in my project, unless I specifiy to swith to `simple` snapshot type.

Are you observing the opposite ? What is the value of `renv::settings$snapshot.type()` for your project ? 

I build a reprex to show how it works for me.

``` r
dir.create(tmp_dir <- tempfile())
# init a renv project
renv::init(tmp_dir, restart = FALSE)
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> * Lockfile written to 'C:/Users/DERVIE~1/AppData/Local/Temp/Rtmpcv0J1t/file42c01c506c82/renv.lock'.
# add a script with dependency
xfun::write_utf8("library(ps)", file.path(tmp_dir, "dummy.R"))
renv::dependencies(path = tmp_dir)
#> Finding R package dependencies ... Done!
#>                                                                          Source
#> 1   C:/Users/dervieuxchr/AppData/Local/Temp/Rtmpcv0J1t/file42c01c506c82/dummy.R
#> 2 C:/Users/dervieuxchr/AppData/Local/Temp/Rtmpcv0J1t/file42c01c506c82/renv.lock
#>   Package Require Version   Dev
#> 1      ps                 FALSE
#> 2    renv                 FALSE
# it is found to snapshot
renv::status(project = tmp_dir)
#> The following package(s) are installed but not recorded in the lockfile:
#>        _
#>   ps     [1.3.0]
#>   renv   [0.8.3-46]
#> 
#> Use `renv::snapshot()` to add these packages to your lockfile.
renv::snapshot(tmp_dir, confirm = FALSE)
#> The following package(s) will be updated in the lockfile:
#> 
#> # CRAN ===============================
#> - ps     [* -> 1.3.0]
#> - renv   [* -> 0.8.3-46]
#> 
#> * Lockfile written to 'C:/Users/DERVIE~1/AppData/Local/Temp/Rtmpcv0J1t/file42c01c506c82/renv.lock'.
# install a package
renv::install("glue", project = tmp_dir)
#> Retrieving 'http://cran.rte-france.com/bin/windows/contrib/3.6/glue_1.3.1.zip' ...
#>  OK [file is up to date]
#> Installing glue [1.3.1] ...
#>  OK (linked cache)
# not found to put in the lockefile
renv::status(project = tmp_dir)
#> * The project is already synchronized with the lockfile.
# even if it is correcly installed
find.package("glue")
#> [1] "C:/Users/dervieuxchr/AppData/Local/Temp/Rtmpcv0J1t/file42c01c506c82/renv/library/R-3.6/x86_64-w64-mingw32/glue"
# using simple snapshot type will look into the library to see what to snapshot
renv::settings$snapshot.type("simple", project = tmp_dir)
renv::status(project = tmp_dir, library = .libPaths()[1])
#> The following package(s) are installed but not recorded in the lockfile:
#>        _
#>   glue   [1.3.1]
#> 
#> Use `renv::snapshot()` to add these packages to your lockfile.
#> 
#> The following package(s) are recorded in the lockfile but not installed:
#>      _
#>   ps   [1.3.0]
#> 
#> Use `renv::restore()` to install these packages.
unlink(tmp_dir)
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kevinushey** [comment]
Can you also report the output of `renv::dependencies()`? Is it possible `renv` is not discovering your usages of a particular package for some reason?

**Comment by kevinushey** [comment]
> I know there is settings::ignored.packages, but we are after is more like used.packages. Is there a way to achieve this currently?

I'd also be curious if you have an alternate proposal for how `renv` could select which packages enter the lockfile. Note that package versions + sources are inferred based on what packages are currently installed in the active library paths; I'm not sure if you also want to explicitly declare versions + sources as well.

**Comment by vspinu** [comment]
@kevinushey 
> renv::dependencies()

I do see the `blabla` package there, but not when I run `renv::status`. Cannot you reproduce the same when you add `library(blabla)` in your project files?

> I'd also be curious if you have an alternate proposal for how renv could select which packages enter the lockfile. 

The way I understand how `renv` is supposed to work right now is that if DESCRIPTION file is present renv snapshots only those packages that are in the description, otherwise `renv` calls `renv::dependencies` to sniff for all usage of `library`, `require`, `::` etc. and restricts to those packages only. 

I think this is a reasonable behavior. Especially that there is `.renvignore` that blacklists files that should not be parsed. My problem is that this "capsule" doesn't quite work as expected. 

This is what I observe with packrat style snapshots:

- `renv::snapshot` - adds files that are not listed in the package
- `renv::status` and `renv::update` don't pick up new entrants into `renv::dependencies` list
- `renv::status` shows packages not in the `renv::dependencies` list
- `renv::snapshot` snapshots packages that are not part of the `renv::dependenies` list

@cderv I will put together a reprex illustrating these  issues in a minute

**Comment by vspinu** [comment]
I couldn't run the reprex as it throws `Error: callr subprocess failed: there is no package called 'reprex'` in the middle, but here is the direct paste:

```R

> dir.create(tmp_dir <- tempfile())
> renv::init(tmp_dir, restart = FALSE)
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
* Lockfile written to '/tmp/RtmphP1vpy/file2a47779e3bd0/renv.lock'.
* Project '/tmp/RtmphP1vpy/file2a47779e3bd0' loaded. [renv 0.8.3-46]
> xfun::write_utf8("library(ps)", file.path(tmp_dir, "dummy.R"))
> renv::dependencies(path = tmp_dir)
Finding R package dependencies ... Done!
                                      Source Package Require Version   Dev
1   /tmp/RtmphP1vpy/file2a47779e3bd0/dummy.R      ps                 FALSE
2 /tmp/RtmphP1vpy/file2a47779e3bd0/renv.lock    renv                 FALSE
> renv::status(project = tmp_dir)
The following package(s) are installed but not recorded in the lockfile:
       _
  renv   [rstudio/renv@0.8.3-46]

Use `renv::snapshot()` to add these packages to your lockfile.

> renv::snapshot(tmp_dir, confirm = FALSE)
The following package(s) will be updated in the lockfile:

# GitHub =============================
- renv   [* -> rstudio/renv@0.8.3-46]

* Lockfile written to '/tmp/RtmphP1vpy/file2a47779e3bd0/renv.lock'.
> renv::status(project = tmp_dir)
* The project is already synchronized with the lockfile.
> renv::install("glue", project = tmp_dir)
Retrieving 'https://cloud.r-project.org/src/contrib/glue_1.3.1.tar.gz' ...
	OK [file is up to date]
Installing glue [1.3.1] ...
	OK (linked cache)
> renv::status(project = tmp_dir)
* The project is already synchronized with the lockfile.
> find.package("glue")
[1] "/home/vspinu/.local/share/renv/cache/v4/R-3.6/x86_64-pc-linux-gnu/glue/1.3.1/e8436e647719b7c9d01409767cd88cc8/glue"
> renv::settings$snapshot.type("simple", project = tmp_dir)
> renv::status(project = tmp_dir, library = .libPaths()[1])
The following package(s) are installed but not recorded in the lockfile:
       _
  glue   [1.3.1]

Use `renv::snapshot()` to add these packages to your lockfile.

> unlink(tmp_dir)
> 
```

So, for me `ps` is not shown in the status nor it is snapshoted. 

But I do see that snapshot would ignore packages outside of `renv::dependencies`. So I am retracting my 3rd claim from my previous post. That part works as expected.

**Comment by kevinushey** [comment]
Currently, the goal of `renv::status()` is to tell you what would happen if you were to call `snapshot()`, versus what would happen if you were to call `restore()`. I believe then what you're seeing is the expected behavior.

It sounds like you're looking for something separate -- what packages are referenced / used in my project, but not actually installed in the project library? (Such packages will not be snapshotted.)

**Comment by cderv** [comment]
Thank you for the reprex. I understand now the difference in behavior. 

If package is found as dependencies but not installed yet, it won't be found in `status()` and won't enter lockfile.

The hint was 
> The following package(s) are installed but not recorded in the lockfile

If I remove `ps` package from my user library (`Sys.getenv("R_LIBS_USER")`), I can reproduce using your example. `ps` is not reported in `renv::status`

**Comment by cderv** [comment]
I think i was expecting the same behavior as in packrat where status would tell you that a package is referenced in the code but not present in the library and it gives the advice to install it. 

```r
> dir.create(tmp_dir <- tempfile())
> # init a renv project
> packrat::init(tmp_dir, restart = FALSE)
Initializing packrat project in directory:
- "C:/Users/dervieuxchr/AppData/Local/Temp/RtmpWyXeT6/file2d7459bb54d4"
Packrat mode off. Resetting library paths to:
- "D:/Users/dervieuxchr/Documents/Portable/R/R-3.6.1/library"

Adding these packages to packrat:
            _      
    packrat   0.5.0

Fetching sources for packrat (0.5.0) ... OK (CRAN current)
Snapshot written to "C:/Users/dervieuxchr/AppData/Local/Temp/RtmpWyXeT6/file2d7459bb54d4/packrat/packrat.lock"
Installing packrat (0.5.0) ... 
	OK (downloaded binary)
Initialization complete!
Packrat mode on. Using library in directory:
- "C:/Users/dervieuxchr/AppData/Local/Temp/RtmpWyXeT6/file2d7459bb54d4/packrat/lib"
> # add a script with dependency
> writeLines("library(ps)", file.path(tmp_dir, "dummy.R"))
> # is ps installed ? 
> find.package("ps", quiet = TRUE)
character(0)
> packrat::status(tmp_dir)

The following packages are referenced in your code, but are not present
in your library nor in packrat:

    ps

You will need to install these packages manually, then use
packrat::snapshot() to record these packages in packrat.
> # not found
> unlink(tmp_dir)
```

I understand this behavior has changed in `renv`. is it on purpose ? Was it linked to the fact that packrat downloaded the source bundle in the project too ?

**Comment by kevinushey** [comment]
> I understand this behavior has changed in renv. is it on purpose ? Was it linked to the fact that packrat downloaded the source bundle in the project too ?

No, it was just not yet implemented. :-) Should be good to go now, as reporting this information is indeed worthwhile.
