### ISSUE TITLE
Make `renv::status` output available to programs

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#276]
Currently `renv::status` prints a lot but outputs very little. I think the common way to design the reporter is in the `print` method - let `renv::status` do all the work but printer do the reporting. 

Particularly, concerning #255 I don't see how to grab the packages listed for purge and re-install them in bulk.

**Comment by kevinushey** [comment]
I'm going to punt on this because it's not entirely clear to me what the result of `renv::status()` should be. I'd rather have it give prescriptions for actions that can be taken to resolve any problematic states.
