### ISSUE TITLE
Provide loading utility similar to `pacman::p_load`

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#278]
Would be nice if renv cold provide a way to attach a list of packages, (and install+attach if packages are missing). It should load all project specific packages at once when called with no arguments.

My team is currently using `pacman::p_load` a lot, and that's the only function we use from that package. Would be great if we could get rid of that dependency. To my mind such an utility is a natural complement to the existing trio `renv::install`, `renv::remove`, `renv::update`.

As a concrete workflow, if my packages are already declared in DESCRIPTION then I could do `renv::load_packages` and load all of them in the order they are specified in that file. 

Not sure about the name though. The current `renv::load` is a too-nice-of-a-name reserved for an semi-internal function. So maybe (if you agree with the proposal) the current `renv::load` could be renamed into `load_project` and the name could be used for this new feature.

**Comment by arthur-albuquerque** [comment]
Has this been implemented?

**Comment by kevinushey** [comment]
This has been implemented with `renv::use()` -- please see https://rstudio.github.io/renv/articles/use.html for more details.
