### ISSUE TITLE
Should the lockfile live in renv/ ?

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#28]
Then all renv related files would be in the same directory.

**Comment by slopp** [comment]
I prefer having the lock file at the top-level directory. In packrat the lock file was an implementation detail that was stored in the packrat folder. In renv, we want users to be aware of the lock file, the role it plays, and clearly associate the file with their code, since both belong in Git (whereas nothing else in the renv folder needs to live in Git).

**Comment by hadley** [comment]
I don't think that's true — at least the `activate.R` needs to be in git, and the current `.gitignore` structure suggests there are other files in `renv/` that should also be checked in.

**Comment by slopp** [comment]
@kevinushey  will have to weigh in then, I was under the impression the lock file was self-sufficient (and appears to be in my testing)

My main point was that burying the lock file was listed as a "packrat mistake" in the renv design document

**Comment by rpodcast** [comment]
I'd like to throw in my support to keep the `renv` lock file in the top-level directory.  While I consider myself a "power" packrat user, it was always a struggle to get many of my colleagues working with me on a packrat-enabled project to understand the current state of package versions and overall dependency structure.  Having the lock file front and center in the project directory will make this more transparent, especially for newer users.

**Comment by kevinushey** [comment]
The lockfile is the only really vital piece if you want to rebuild a library. `renv/activate.R` is just infrastructure for ensuring that new R sessions load the `renv` library by default; it's not absolutely required (although I think normally one can and should commit it to Git)

**Comment by hadley** [comment]
Having the lockfile in the project dir also better supports the `snapshot()`-before-`init()` workflow.
