### ISSUE TITLE
renv::restore() only creates base Python install from renv.lock without add-on libraries i n environment.yml

### ISSUE THREAD

**Issue by leungi** [rstudio/renv#281]
Two issues, as outlined below.

Below are steps taken to attempt to create a reproducible R and Python environments with `renv`:

1. in an RStudio project, call `renv::init()`
2. call `renv::use_python()`, pointing to existing Python interpreter in conda virtual environment
3. confirmed correct Python.exe used with `reticulate::py_config()` 
4. __Issue 1__:  `renv::init()` correctly captures R environment, but doesn't capture all the supplementary Python libraries in the conda virtual environment
5. manually installed missing Python libraries into new virtual environment created by `renv::use_python()`
6. call `renv::snapshot()` to capture R and Python environments via `renv.lock` and `environment.yml`
7. on a separate machine, git cloned repository containing `renv.lock` and `environment.yml`, and call `renv::restore()`
8. __Issue 2__: full R environment reproduced, but only base Python environment is restored; is user expected to manually run `conda env create -f environment.yml` on the restored  Python environment to install missing libraries from base Python?

**Comment by kevinushey** [comment]
> Issue 1: renv::init() correctly captures R environment, but doesn't capture all the supplementary Python libraries in the conda virtual environment

I _think_ the issue here is that `renv` actually creates its own conda environment, using the same Python interpreter that you've requested from `renv::use_python()`. By default, that new environment does not have the same packages as the requested Python environment, by default, and so need to be installed manually.

Can you confirm the output of `py_config()` in your project?

> Issue 2: full R environment reproduced, but only base Python environment is restored; is user expected to manually run conda env create -f environment.yml on the restored Python environment to install missing libraries from base Python?

No, `renv` should do that for you on `restore()`. See:

https://github.com/rstudio/renv/blob/4b32dc89bb8f53cb1a93199ab8815038760b29fc/R/python-conda.R#L49-L71

For what it's worth, this works as expected in my tests but for some reason Conda doesn't seem to write anything to stdout when the requested packages are installed.

**Comment by leungi** [comment]
Noted for _Issue 1_; this is what I figure based on the outcome from running `renv::use_python()` the first time. I was wishfully hoping it'd do a complete Python environment copy, but without should've known better given there's no `environment.yml` to begin with 😅.

For _Issue 2_, what you noted above is what I had expected; below is console output.

__Console output__
```r
* Project 'P:/project/Fun/r-tensorflow' loaded. [renv 0.8.3-43]
> renv::use_python()
* Activated Python 3.6.9 :: Anaconda, Inc. [conda; P:/project/Fun/r-tensorflow/renv/python/condaenvs/renv-python]
* Project 'P:/project/Fun/r-tensorflow' loaded. [renv 0.8.3-43]
> reticulate::py_config()
python:         P:/project/Fun/r-tensorflow/renv/python/condaenvs/renv-python/python.exe
libpython:      P:/project/Fun/r-tensorflow/renv/python/condaenvs/renv-python/python36.dll
pythonhome:     P:\project\Fun\r-tensorflow\renv\python\condaenvs\renv-python
version:        3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON
> list.files()
[1] "environment.yml"    "r-tensorflow.Rproj" "renv"               "renv.lock"          "rmd"                   
> devtools::session_info()
- Session info ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Chicago             
 date     2019-12-04                  

- Packages --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version     date       lib source                             
 assertthat    0.2.1       2019-03-21 [2] CRAN (R 3.5.3)                     
 backports     1.1.5       2019-10-02 [2] CRAN (R 3.5.3)                     
 callr         3.3.0       2019-07-04 [2] CRAN (R 3.5.1)                     
 cli           1.1.0       2019-03-19 [2] CRAN (R 3.5.3)                     
 crayon        1.3.4       2017-09-16 [2] CRAN (R 3.5.3)                     
 desc          1.2.0       2018-05-01 [2] CRAN (R 3.5.1)                     
 devtools      2.2.1       2019-09-24 [2] CRAN (R 3.5.3)                     
 digest        0.6.23      2019-11-23 [2] CRAN (R 3.5.1)                     
 ellipsis      0.3.0       2019-09-20 [2] CRAN (R 3.5.3)                     
 fs            1.3.1       2019-05-06 [2] CRAN (R 3.5.3)                     
 glue          1.3.1       2019-03-12 [2] CRAN (R 3.5.3)                     
 jsonlite      1.6         2018-12-07 [2] CRAN (R 3.5.1)                     
 magrittr      1.5         2014-11-22 [2] CRAN (R 3.5.1)                     
 memoise       1.1.0       2017-04-21 [2] CRAN (R 3.5.1)                     
 packrat       0.5.0       2018-11-14 [2] CRAN (R 3.5.3)                     
 pkgbuild      1.0.3       2019-03-20 [2] CRAN (R 3.5.3)                     
 pkgload       1.0.2       2018-10-29 [2] CRAN (R 3.5.1)                     
 prettyunits   1.0.2       2015-07-13 [2] CRAN (R 3.5.1)                     
 processx      3.4.1       2019-07-18 [2] CRAN (R 3.5.3)                     
 ps            1.3.0       2018-12-21 [2] CRAN (R 3.5.1)                     
 R6            2.4.1       2019-11-12 [2] CRAN (R 3.5.3)                     
 Rcpp          1.0.3       2019-11-08 [2] CRAN (R 3.5.3)                     
 remotes       2.1.0       2019-06-24 [2] CRAN (R 3.5.3)                     
 renv          0.8.3-43    2019-11-22 [1] Github (rstudio/renv@8330c00)      
 reticulate    1.13.0-9000 2019-09-29 [2] Github (rstudio/reticulate@6b94066)
 rlang         0.4.2       2019-11-23 [2] CRAN (R 3.5.1)                     
 rprojroot     1.3-2       2018-01-03 [2] CRAN (R 3.5.1)                     
 rstudioapi    0.10        2019-03-19 [2] CRAN (R 3.5.3)                     
 sessioninfo   1.1.1       2018-11-05 [2] CRAN (R 3.5.1)                     
 testthat      2.1.1       2019-04-23 [2] CRAN (R 3.5.3)                     
 usethis       1.5.1       2019-07-04 [2] CRAN (R 3.5.1)                     
 withr         2.1.2.9000  2019-10-14 [2] Github (r-lib/withr@07bfc68)       

[1] P:/project/Fun/r-tensorflow/renv/library/R-3.5/x86_64-w64-mingw32
[2] C:/Users/Public/Data/R/R-3.5.1/library
```

**Comment by kevinushey** [comment]
Sorry, but can you confirm that the required Python packages indeed are _not_ restored following an `renv::restore()`? Is `reticulate` able to load those packages following a restore?

**Comment by kevinushey** [comment]
I'm just surprised because in my case, the restore _did_ work (`reticulate` could find the required Python packages) but their installation simply was not reported in the Conda console output, for some strange reason.

**Comment by leungi** [comment]
I did `renv::restore()` a second time and it works! As you noted, during the Python install, console only ouputs certain library installs, not all; however, given it's taking a long time, it must be installing all the libraries as per `environment.yml`

FWIW, below is a screenshot of the first `renv::restore()` attempt where some libraries are missing.

![renv_restore_issue](https://user-images.githubusercontent.com/30273868/70253885-b2eab880-1749-11ea-8d60-7a030d5e497a.gif)
