### ISSUE TITLE
Url fetcher: Allow platform dependent binary urls

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#282]
Follow up on #272 

If a package is a compiled binary and is installed through `devtools::install_url` on linux machine `renv:restore` will fail on Mac and Windows. See for example the [catboost binaries](https://github.com/catboost/catboost/releases). 

I think one simple solution would be to allow for multiple `"RemoteUrl"` fields, one for each platform. What do you think?

**Comment by kevinushey** [comment]
The underlying issue is that `renv` relies on information encoded in the `DESCRIPTION` file to determine the package source, and when `RemoteUrl` points to a binary there's ultimately no chance of it working on other platforms.

As far as I can tell, fixing this requires some user intervention or hard-coding of the correct URLs for such packages "somewhere".

The general mechanism for overriding a record in `renv` is with e.g.

```
options(renv.records.catboost = list(Package = "catboost", Version = "<...>", Source = "url", RemoteUrl = "<...>"))
```

Not sure if there's a cleaner approach that could solve this more generally.

**Comment by vspinu** [comment]
Yes, manual intervention would be ok, but would be nice if it could be done by editing renv.lock itself. Otherwise pkg information is spread in various places. 

If `renv` could treat different binaries of the same package as different packages then maybe it would be possible to have multiple entries in the renv.lock for the same package. Then I could install it in linux and snapshot my version. A colaborator can install on Mac and snapshot etc. On `renv::restore` renv should then be able to figure the right binary automatically. 

Even if one would need to add manually a conditional entry (`platform`) to the renv.lock entry it would be easy enough.

Alternatively this could be a good use for multiple profiles (#253). One could have the base (default) profile and conditional profiles which would overwrite parts of the default profile depending on the platform or other conditions.

**Comment by kevinushey** [comment]
Alternatively, you could set up a CRAN-like repository that serves the `catboost` package with sources + binaries in the expected places. Then `renv` could just use that repository like any other repository.

This seems like a lot of engineering to handle a single package with a unique distribution pattern.

**Comment by vspinu** [comment]
Sounds reasonable. They are actually working on moving it to CRAN atm and there is already a way to install it with `install_github` which will bring the correct dll automatically. I still have to give it a try. 

The env variable that you have suggested is a dissent workaround anyhow. Thanks!
