### ISSUE TITLE
renv::status spurious "not installed packages" v4/v5 cache issue?

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#283]
Seems like `renv:status` doesn't recognize v5 cache. I have only two packages in v5 cache: `bit` and `bit64` all other packages are in v4 cache directory. 

I am getting this:

```R
> renv::status()
The following package(s) are recorded in the lockfile but not installed:
        _
  bit     [1.1-14]
  bit64   [0.9-7]

Use `renv::restore()` to install these packages.

> renv::restore()
* The library is already synchronized with the lockfile.
```

Nothing seem to help with the `status` mis-reporting (re-install, deletion of v5 cache folder and re-install).

**Comment by kevinushey** [comment]
This should be, in theory, separate from the cache altogether. `renv::status()` says that these packages are referenced in your lockfile, but for some reason `renv::restore()` disagrees (and seems to believe the packages are already installed).

What's odd is that in theory these two operations should be drawing from the same sources of information -- e.g. `renv::status()` really just calls `renv::snapshot()` and compares that to the current lockfile.

Can you share the output of `renv::diagnostics()` in this project? Are you able to load those packages in this project?

**Comment by vspinu** [comment]
This is just mis-reporting. I don't have `library(bit64)` in my project path, but it used to be before. When I add it back the problem disappeared. 

 So now    `renv_snapshot_filter_packrat` filters it out from the list of packages in `renv` local library. As a result `renv_lockfile_diff_packages` [here](https://github.com/rstudio/renv/blob/4f5f7e83fab8947b0ea2139372ba1385e766ddb4/R/status.R#L165) returns the following diff state:

```
List of 2
 $ bit  : chr "remove"
 $ bit64: chr "remove"
```

Which is then wrongly interpreted by the subsequent code that packages are not installed.

**Comment by kevinushey** [comment]
I understand the issue now -- the problem is that we don't properly distinguish between packages which are:

1. No longer being snapshotted because they're not used in the project, versus
2. No longer being snapshotted simply because they are not installed.

I think `renv::status()` needs to better report the combinations of these three states.

**Comment by vspinu** [comment]
Thanks!
