### ISSUE TITLE
question about version of installed packages

### ISSUE THREAD

**Issue by nbbn** [rstudio/renv#288]
Hi,
I guess I'm doing something wrong with renv, but I tried to install package in specific version and I get another version, can you please check it?
I described it in detail here:
https://community.rstudio.com/t/renv-installs-inproper-version-of-package/46333

Thanks,
Jakub

**Comment by kevinushey** [comment]
Thanks; I've responded on the community page.

**Comment by nbbn** [comment]
Thanks, let's continue this discussion on community page. It is still not clear for me how to do it :)
