### ISSUE TITLE
get renv::update to update local packages

### ISSUE THREAD

**Issue by kendonB** [rstudio/renv#289]
```r
library(tidyverse)
library(mypackage)
list.files(renv:::renv_paths_local()) %>% 
     str_subset("mypackage_0.1.1")
#> [1] "mypackage_0.1.1.tar.gz"
devtools::session_info() %>%
     .$packages %>% 
     filter(package == "mypackage") %>% 
     select(package, ondiskversion)
#>   package ondiskversion
#> mypackage         0.1.0
renv::update()
#> * Checking for updated packages ... Done!
#>   * All packages are up-to-date.
```

**Comment by kevinushey** [comment]
I can try to implement this, but I _really_ believe you should consider an alternate solution -- e.g. a local on-disk CRAN repository, or something else.

I view the locals mechanism as a last-resort mechanism for packages that cannot be installed from another source, not an ad-hoc local CRAN repository.

**Comment by kendonB** [comment]
Is there a vignette for this? https://rstudio.github.io/renv/articles/local-sources.html does not mention a local CRAN-like repo

**Comment by kevinushey** [comment]
You could use `drat` + a local repository: http://dirk.eddelbuettel.com/code/drat.html

**Comment by smingerson** [comment]
This seems similar to #284. I commented about not wanting to set up a CRAN-like repo. How does renv parse `options(repos)`? If I provide `repos = c(CRAN = "https://cran.rstudio.com", MYCRANLIKE = "path/to/cranlike")`, will renv check both for updated packages? My initial assumption was I would have to set up a CRAN-like repository and copy all packages from CRAN that are relevant into the CRAN-like on a regular basis. Perhaps that is mistaken, based upon http://eddelbuettel.github.io/drat/DratFAQ.html

**Comment by kevinushey** [comment]
> If I provide repos = c(CRAN = "https://cran.rstudio.com", MYCRANLIKE = "path/to/cranlike"), will renv check both for updated packages?

Yes, it will find the latest available package provided by any of the package repositories currently declared within `getOption("repos")`. So you could be able to add your own CRAN-like repository, containing only the add-on packages you're developing -- no need to try and make your own local CRAN mirror.

**Comment by smingerson** [comment]
Great, thank you for all the hard work on this package and your responsiveness @kevinushey, it is really appreciated. I have that all set up now and it is working like a charm.

**Comment by kevinushey** [comment]
Awesome! I'm very glad to hear it.
