### ISSUE TITLE
packages missing from the lockfile

### ISSUE THREAD

**Issue by aghaynes** [rstudio/renv#290]
I'm trying to implement renv for a project which uses relatively old packages (only a couple of years), including 2 which are deprecated (ReporteRs and it's associated ReporteRsjars), and version of R (3.4.2). I had to install both of those packages as if I were installing them from a local file...
``` 
install.packages("https://cran.r-project.org/src/contrib/Archive/ReporteRsjars/ReporteRsjars_0.0.4.tar.gz", repos = NULL)
install.packages("https://cran.r-project.org/src/contrib/Archive/ReporteRs/ReporteRs_0.8.10.tar.gz", repos = NULL)
``` 
Neither of those packages appear in the lockfile or the renv library though. 
Is there any way to add them?

**Comment by kevinushey** [comment]
Please see: https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile

I suspect the issue is that these packages are indeed being successfully installed into the project library, but `renv` is not detecting that you're using these packages in your project.

**Comment by kevinushey** [comment]
I think the issue here should be understood now -- feel free to re-open if you're still having trouble.

**Comment by aghaynes** [comment]
Thanks Kevin... I'll dig a bit further with the dependencies function to see whats happening then...

**Comment by aghaynes** [comment]
FWIW, I found the culprit...
```
for(i in c("haven", "ReporteRs")){
  if(!i %in% row.names(installed.packages())){
    install.packages(i, repos = "http://stat.ethz.ch/CRAN/")
  }
  library(i, character.only = TRUE)
}
```
Using renv negates the requirement to use such a technique though...

**Comment by kevinushey** [comment]
Right, this is unfortunately one of the forms that `renv`'s static analysis is unable to detect. Using a plain old:

```
library(haven)
library(ReporteRs)
```

should help fix things up.

**Comment by aghaynes** [comment]
exactly, that did the trick. Thanks for your input Kevin :)
