### ISSUE TITLE
`purge()` only accepts a single package

### ISSUE THREAD

**Issue by smingerson** [rstudio/renv#292]
This seems intentional, as the documentation says "A single package to be removed from the cache." I think that makes sense given that it is destructive. 

I have 94 (ish, some of them are listed twice with different hashes) packages renv is recommending to purge and reinstall. What is the recommended way of doing this, using `lapply()`, deleting my project library and using `renv::restore()`? 

As a side note, `renv::status()` says "This function is normally called for its side effects." Should there be a way to extract the list of problematic packages? I understand the tension between providing useful information and making it clear that it is not meant for programmatic use. I'm getting the list of packages using. I can move this second piece to another issue if you would prefer.

```r
pkg_status <- capture.output(renv::renv_status())
purges <- regmatches(pkg_status, regexpr("(?<=\\t)[A-z.0-9]+", pkg_status, perl = TRUE))
```
```r
# example
viridisLite  0.3.0      [Hash: 9cdc281be942ca5c7ed232951f7cd001 != 1f264fa42320c4f44b1689d89101e823]
viridisLite  0.3.0      [Hash: ce4f6271baa94776db692f1cb2055bee != 1f264fa42320c4f44b1689d89101e823]
```

**Comment by kevinushey** [comment]
FWIW, right now I would recommend upgrading to `renv 0.9.0` and using `renv::rehash()` to fix up hashes for the latest version of `renv`.

The older versions of `renv` had an issue where using different versions of R within the same project could cause multiple versions of a package to become hashed within the same cache.

**Comment by smingerson** [comment]
I did as you suggested, things are looking a lot better now. I'm closing this because the issue was a large number of packages with mismatched hashes, which `renv::rehash()` solves.
