### ISSUE TITLE
document that xcode command line tools are required?

### ISSUE THREAD

**Issue by Aariq** [rstudio/renv#296]
When I run `renv::restore()` or `renv::install()` I get the following error:

```
Installing renv [0.8.3] ...
	FAILED
Error in writeLines(contents, con = path) : 
  can only write character objects
In addition: Warning messages:
1: In system2(R(), args, stdout = TRUE, stderr = TRUE) :
  running command ''/Library/Frameworks/R.framework/Resources/bin/R' CMD config CC 2>&1' had status 69
2: In if (eval(cond, envir = environment(dot))) return(eval(expr, envir = environment(dot))) :
  the condition has length > 1 and only the first element will be used
3: In if (eval(cond, envir = environment(dot))) return(eval(expr, envir = environment(dot))) :
  the condition has length > 1 and only the first element will be used
```

I eventually figured out that this is solved by installing Xcode and command line tools, but that wasn't obvious from the error message. I don't see anything in the documentation saying that xcode is required on macOS.

**Comment by kevinushey** [comment]
What is the output of:

```
R CMD config CC
```

on your machine? Do you have a compiler toolchain set up on your machine?

**Comment by kevinushey** [comment]
FWIW the requirement that a compiler toolchain be available is documented here:

https://rstudio.github.io/renv/articles/renv.html#installation-from-source

**Comment by kevinushey** [comment]
And finally, note that the exit code 69 likely implies that you have not yet agreed to the Xcode license.

**Comment by Aariq** [comment]
Ah, thanks.  I see it in the documentation now.  You're correct that I hadn't agreed to the Xcode license on this machine.  I've fixed it now, so It would be difficult to reproduce this error to give you more details.  I guess I was just surprised that it seemed to effect every package installation, not just ones that needed to be installed from source.  But I could be wrong, as I didn't test exhaustively.

**Comment by kevinushey** [comment]
Note to self: we check for the Xcode license in RStudio here:

https://github.com/rstudio/rstudio/blob/0ae52a9831ce9c11bdcf9228c2dd5878ae20dfc0/src/cpp/session/SessionModuleContext.cpp#L2631-L2646

We could do a similar check in `renv` to be helpful as well.
