### ISSUE TITLE
Possible conflict with devtools::check()

### ISSUE THREAD

**Issue by copernican** [rstudio/renv#297]
I'm having an issue getting `devtools::check()` to work with `renv` for package development. These are the steps I've used to reproduce the issue:

1. In RStudio, create a new package Project named `foo`.
2. `renv::activate()`
3. `renv::install("devtools")`
4. `devtools::check()`

This throws the error

```r
> devtools::check()
── Building ─────────────────────────────────────────────────────────────────────────────────────────────────────────── foo ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   Error in file(filename, "r", encoding = encoding) : 
     cannot open the connection
   Calls: source -> file
   In addition: Warning message:
   In file(filename, "r", encoding = encoding) :
     cannot open file 'renv/activate.R': No such file or directory
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
```

It appears this may be related to the `path` argument to `pkgbuild::build()`, which is eventually called by `devtools::check()`. In particular, if the package is at `~/foo`, then I can use `setwd()` to set the working directory to one level above the package (`~`), then `devtools::check("foo")` succeeds.

I have `renv` 0.9.2 and `devtools` 2.2.1.

**Comment by kevinushey** [comment]
The problem here is with the way `callr` tries to load the project `.Rprofile`.

Full story, IIUC:

1. The project profile contains `source("renv/activate.R")`.
2. The R process used to check the package uses the R tempdir as the working directory.
3. `R_PROFILE_USER` is set to point at (a mutated version of) the project profile.
4. The call within the profile to `source("renv/activate.R")` fails as the working directory is no longer the project root (the package root).

cc: @gaborcsardi; what do you think the best remedy for this is?

**Comment by gaborcsardi** [comment]
So maybe if the wd is not the same (any more), then it just should not try to load the project `.Rprofile`?

**Comment by kevinushey** [comment]
I think that's the right approach.

At least in the context of using `renv` + `devtools` together, I think the main thing required is that the same library paths are used when `R CMD check` is run (or `devtools::test()`). Since the library paths are already set through loading the process, and those library paths are passed along to the child R process, things should work as expected.

**Comment by gaborcsardi** [comment]
OK, I'll try to do that then: https://github.com/r-lib/callr/issues/139

An alternative would be to load the profile using an absolute path, and then it can be loaded, but I agree with you that the other solution seems better.

**Comment by lnyman1** [comment]
+1.  I have tracked down the same issue I was seeing to this package.  The same issue happens when calling devtools::check() with packrat.

**Comment by condour** [comment]
(Just to note, for anyone coming here, that downgrading callr from 3.4.0 to 3.3.0 fixes this, if you need a solution before callr gets fixed)

**Comment by kevinushey** [comment]
The easiest way to downgrade using `renv` would be just:

```
renv::install("callr@3.3.0")
```

**Comment by mlell** [comment]
This bug also makes it impossible to build or install local packages inside an renv-controlled environment. 

```r
renv::init()
install.packages("devtools")
dir.create("utils")
devtools::create("utils/test", rstudio = FALSE, open = FALSE)

remotes::install_local("utils/test") # fails
devtools::build("utils/test")        # fails
##   Error in file(filename, "r", encoding = encoding) : 
##     cannot open the connection
##   Calls: source -> file
##   In addition: Warning message:
##     In file(filename, "r", encoding = encoding) :
##     cannot open file 'renv/activate.R': No such file or directory
##   Execution halted
## Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
##                       System command error
```

**Comment by kevinushey** [comment]
Closing this as this is an issue in `callr` rather than `renv`, and unfortunately there isn't much `renv` can do to work around this (beyond providing tools for installing an older version of `callr`, as documented above)

**Comment by mlell** [comment]
[Fixed in callr](https://github.com/r-lib/callr/issues/139#issuecomment-578067620)
