### ISSUE TITLE
Option to force renv/.gitignore (and other ignore-file) construction?

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#300]
I use a project structure where the R 'project' (i.e. directory) itself sits in a subdirectory within a parent git repository. So, for example, the repo itself might be called `top-level`, and it'll contain its own `.gitignore`. Then within, `top-level`, there'll be R projects (`app1`, `app2`, etc), and from there each has its own `renv` structure. This results in a directory structure a bit like so:
```
/top-level/.git/*
/top-level/.gitignore
/top-level/app1/main.R
/top-level/app1/renv.lock
/top-level/app1/renv/*
/top-level/app2/main.R
/top-level/app2/renv.lock
/top-level/app2/renv/*
```
When initializing `renv` from within any of the `app`s, no `.gitignore` file is created and placed in the `renv` directory.
After poking-around a bit it appears the `.gitignore` file will only be created _if_ a non-empty `.gitignore` is found in the same directory in which the `renv` directory itself will live.
I can probably create some dummy indicators to 'simulate' each `app` as being its own git repo, but perhaps it'd be easier to have an option where we can _force_ ignore-file construction regardless of the detected directory structure?

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be better handled on master now.
