### ISSUE TITLE
Can I renv::init a project from another folder?

### ISSUE THREAD

**Issue by maelle** [rstudio/renv#303]
I'm trying to add support for renv in the [starters package](https://github.com/lockedata/starters) where we initiate projects (folder creation, basic infrastructure) from another folder/project. I might be missing something but at the moment when I am suprised that the following code changes `.libPaths()`.

```r
cwd <- getwd()
renv::status(cwd)
.libPaths()
tmp <- fs::file_temp()
fs::dir_create(tmp)
renv::init(tmp, restart = FALSE)
setwd(cwd)
renv::status(cwd)
.libPaths()
```

I can't run reprex() on the code above. The first call to `.libPaths` returns

```
[1] "/home/maelle/R/x86_64-pc-linux-gnu-library/3.6"
[2] "/usr/local/lib/R/site-library"                 
[3] "/usr/lib/R/site-library"                       
[4] "/usr/lib/R/library"  
```

The second returns

```
[1] "/tmp/RtmpQXYWzD/file2b0c46213454/renv/library/R-3.6/x86_64-pc-linux-gnu"
[2] "/tmp/RtmpQXYWzD/renv-system-library"   
```

Can I get the initial results without restarting R?

**Comment by maelle** [comment]
It seems related to #131

**Comment by kevinushey** [comment]
This is the expected behavior -- `renv::init()` will also load the project you've just initialized immediately, so that it's ready to be used. This implies modifying the session's library paths.

Unfortunately, there isn't currently an exported function to only write out the `renv` project infrastructure without loading the project. The closest would be the unexported function:

```
renv:::renv_infrastructure_write()
```

**Comment by kevinushey** [comment]
While a bit awkward, you could in theory call `renv::init()` in a separate R session as well -- e.g. the moral equivalent of:

```
system2("R", c("-e", shQuote("renv::init()")))
```

**Comment by maelle** [comment]
thank you! is exporting such a function planned or not all?

**Comment by kevinushey** [comment]
I think this issue provides good motivation for me to implement such a function. :-)

**Comment by maelle** [comment]
Hehe, cool, then I'll wait instead of using the workaround.

**Comment by kevinushey** [comment]
I've now implemented `renv::scaffold()` for generating project infrastructure for a particular project. Thanks!

**Comment by maelle** [comment]
Thank _you_!
