### ISSUE TITLE
System library package now show when Project is using renv

### ISSUE THREAD

**Issue by sclewis23** [rstudio/renv#304]
We have rJava installed as system library, but when we create a new project rJava is not available.
If we start an R session (no project), then rJava is available.
This is the only extra library installed as a system library.
Is there any way to have it show all packages in system library?

renv project:
.libPaths()
#> [1] "/usrfiles/shared-projects/clinicalInformatics/DEMO_4/renv/library/R-3.6/x86_64-pc-linux-gnu"
#> [2] "/tmp/RtmpEdfM0k/renv-system-library"                                                        
#> [3] "/tmp/Rtmpn18BGH/renv-system-library"

subset.data.frame(as.data.frame(installed.packages()[, c(1:4)]), 
    Package == "rJava")
#> [1] Package  LibPath  Version  Priority
#> <0 rows> (or 0-length row.names)

new r session:
.libPaths()
#> [1] "/home/shannon.lewis@beigenecorp.net/R/x86_64-pc-linux-gnu-library/3.6"
#> [2] "/opt/R/R_3.6.1/lib64/R/library"

subset.data.frame(as.data.frame(installed.packages()[, c(1:4)]), 
    Package == "rJava")
#>       Package                        LibPath Version Priority
#> rJava   rJava /opt/R/R_3.6.1/lib64/R/library  0.9-10     <NA>

Thanks,
Shannon

**Comment by kevinushey** [comment]
By default, `renv` sandboxes the system library so that only packages distributed with base R are made available. You can disable this behavior with:

```
RENV_CONFIG_SANDBOX_ENABLED = FALSE
```

See `?renv::config` for more details.
