### ISSUE TITLE
Support authentication for private CRAN-like repositories

### ISSUE THREAD

**Issue by wligtenberg** [rstudio/renv#307]
I would like to use renv with an internal repository that requires authentication.
I can already install package from the repo using install.packages:

```install.packages("pkgName", repos = "https://repo.url", headers = c("Authorization" = Sys.getenv("AUTH_HEADER")))```

I would really appreciate it, if I could specify the authentication header somewhere, like the GITHUB_PAT and that this would then be picked up when installing packages from that CRAN-like repository.

**Comment by kevinushey** [comment]
This sounds like a good idea to me as well; however, I won't have time to look at this until after the holidays.

**Comment by kevinushey** [comment]
I've added a mechanism for setting arbitrary HTTP headers during download to the development version of `renv`. You should be able to do something like:

```
options(renv.download.headers = function(url) {
  if (grepl("^https://repo.url", url))
    c(Authorization = Sys.getenv("AUTH_HEADER"))
})
```

Let me know if this works.

**Comment by MarcinKosinski** [comment]
This is so cool

**Comment by mhvelplund** [comment]
> I would like to use renv with an internal repository that requires authentication. I can already install package from the repo using install.packages:
> 
> `install.packages("pkgName", repos = "https://repo.url", headers = c("Authorization" = Sys.getenv("AUTH_HEADER")))`
> 
> I would really appreciate it, if I could specify the authentication header somewhere, like the GITHUB_PAT and that this would then be picked up when installing packages from that CRAN-like repository.

So ironically, I have the same issue as you, but as a non-R dev I was missing the work-around of adding header to the `install.packages` call. Thanks! :)
