### ISSUE TITLE
sudden errors in loading packages

### ISSUE THREAD

**Issue by majazaloznik** [rstudio/renv#309]
I'm getting the following error in a renv initialised project:

```
Error: package or namespace load failed for ‘RefManageR’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/home/mz/.local/share/renv/cache/v4/R-3.6/x86_64-pc-linux-
gnu/stringi/1.4.3/113506f116db9dd5bd1caf46884e0647/stringi/libs/stringi.so':
  libicui18n.so.64: cannot open shared object file: No such file or directory
```

Same thing happened with the strinr package in another renv project. 

The packages load no problem outside renv projects. I've tried removing and reinstalling them in the renv projects, but the same thing happpens. 

I have renv 0.9.2, sessionInfo is bellow

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.7.so
LAPACK: /usr/lib/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=sl_SI.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=sl_SI.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=sl_SI.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=sl_SI.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    renv_0.9.2  
```

**Comment by kevinushey** [comment]
```
  libicui18n.so.64: cannot open shared object file: No such file or directory
```

My best guess:

1. You installed `stringi`;
2. The version of `libicui18n.so` was upgraded on your system;
3. `stringi` retains a reference to the old version of libicu (`libicui18n.so.64`), but that no longer exists.

You'll likely need to reinstall the `stringi` package.

**Comment by majazaloznik** [comment]
Sorry I wasn't able to be systematic about what worked here and what didn't. I uninstalled and reinstalled a bunch of things, and reinitialised renv a few times as well, and not all seems fine. 

I only opened this here because throughout this I never had any problems with loading any packages in any non-initialised repos or projects. But there was a similar issue with every renv project I had, so I assumed it was connected somehow.

**Comment by grantmcdermott** [comment]
An old issue, but I run into this fairly frequently due to the fact that I'm using an optimised BLAS (OpenBLAS to be precise). The TL;DR version is that you need to re-install any linked packages after a BLAS upgrade, including those in an renv cache. More details [here](https://github.com/grantmcdermott/arch-tips#reinstall-r-packages-after-openblas-update).

On the plus, you _should_ be able to use [this script](https://gist.github.com/mllg/b9c75ded211df7df58942c5d647b9c43) to fix this issue automatically in any renv-based project.
