### ISSUE TITLE
Issue installing github packages

### ISSUE THREAD

**Issue by NathanSkene** [rstudio/renv#310]
Hi, I was setting up a new package. Had an error occuring during installation of a package (loomR) due to lack of an external dependency (needed to run 'sudo apt-get install libhdf5-dev'). Since then it's not been possible to try reinstalling that package. I get the following error

```
> devtools::install_github(repo = "hhoeflin/hdf5r")
Downloading GitHub repo hhoeflin/hdf5r@master
   Error in file(filename, "r", encoding = encoding) : 
     cannot open the connection
   Calls: source -> file
   In addition: Warning message:
   In file(filename, "r", encoding = encoding) :
     cannot open file 'renv/activate.R': No such file or directory
   Execution halted
Error: Failed to install 'hdf5r' from GitHub:
  System command error, exit status: 1, stdout + stderr:
E> Error in file(filename, "r", encoding = encoding) : 
E>   cannot open the connection
E> Calls: source -> file
E> In addition: Warning message:
E> In file(filename, "r", encoding = encoding) :
E>   cannot open file 'renv/activate.R': No such file or directory
E> Execution halted
```

**Comment by actuarialvoodoo** [comment]
I believe this is the same as #297, and related issue has been filed for r-lib/callr#139

**Comment by NathanSkene** [comment]
Just had the same error occur after another external dependency failure during installation of a package. This time it was installing monocle, which depends on sf, which has an external dependency on "sudo apt-get install libgdal-dev".

**Comment by actuarialvoodoo** [comment]
@NathanSkene the second situation appears different to me. Based on what you said, it sounds like the 2nd issue is a package failing due to an expected system library not being installed. If you have permissions to install libgdal-dev on your system, and run "sudo apt-get isntall libgdal-dev" then you should be able to install sf.

**Comment by NathanSkene** [comment]
Hi, sorry, wasn't clear enough. The issue is not that the install fails. It's that after the install fails, I get the renv error when I try to install it again (after fixing the external dependency issue). Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by actuarialvoodoo** [comment]
Are you also installing monocle from github or from bioconductor?

**Comment by kevinushey** [comment]
The error you're reporting is indeed an issue in callr. If you're bumping into a separate problem, please file a separate issue.

**Comment by kevinushey** [comment]
Since this is an issue with callr and not `renv`, I'm going to close this issue. Note that you can install an older version of the `callr` package with (e.g. for 3.3.0):

```
renv::install("callr@3.3.0")
```

if so required.
