### ISSUE TITLE
install/restore failing with drat repository

### ISSUE THREAD

**Issue by smingerson** [rstudio/renv#311]
I'm using renv 0.9.2

Based on the advice in #289, I've set up an internal package repository using drat. My repos are configured as

```
# repos
c(CRAN = "https://cran.rstudio.com", COMPANY = "file:///R:")
# R: is a network drive. It must be defined as such due to limitations in `install.packages()`
```

As I make changes to my package, I run `drat::insertPackage(devtools::build(), repodir = "R:/")` from the package's source directory to add to the drat repository. In a separate project which uses renv my package , I use `install.packages("mypkg", type = "source")` to update the package within the renv project. 

## Problem 1
Now, suppose I clone the project to another directory, and run `renv::restore(packages = "mypkg")`. After proceeding, I receive 
```
   * Querying repositories for available binary packages ... Done!
   * Querying repositories for available source packages ... Done!
     Retrieving 'https://cran.rstudio.com/src/contrib/Archive/mypkg/mypkg_0.1.4.tar.gz' ...
```
And, shortly after, 
```
Error: failed to retrieve package 'mypkg'
In addition: Warning messages:
1: In system2("curl", args$data(), stdout = TRUE, stderr = TRUE) :
  running command '"curl" --config "C:/Users/Sean.Ingerson/AppData/Local/Temp/Rtmp2BrLTO/renv-tempdir-4dacfa6a06/renv-download-config-4dace77400b"' had status 22
2: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 Not Found
3: In system2("curl", args$data(), stdout = TRUE, stderr = TRUE) :
  running command '"curl" --config "C:/Users/Sean.Ingerson/AppData/Local/Temp/Rtmp2BrLTO/renv-tempdir-4dacfa6a06/renv-download-config-4dac9d7eb6"' had status 22
4: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 Not Found
```

## Problem 2
This is despite the package description having "Repository: COMPANY" specified. I receive a "package not available" error if I try `renv::install("mypkg")`.

## Expected behavior

Based on our previous discussion, I was under the impression packages with a specified repository would be looked for there, if a matching repository was specified in `getOption("repos")`. Or perhaps that packages not in CRAN would be queried in other repositories. 

If you need more information or a reproducible example, I'm happy to provide one. I apologize if this should have been tacked onto another issue; I've looked at several and thought this was sufficiently different

**Comment by kevinushey** [comment]
Is `mypkg_0.1.4` current in your drat repository, or should it be found in the archive there?

Can you confirm that the package is found if you execute:

```R
renv:::renv_available_packages_entry("mypkg", type = "source")
```

Can you also check whether using a repository URL as:

```
file:R:/<...>
```

works; that is, without any slash? I wonder if `renv` is failing to handle this particular form for the repository URL.

**Comment by smingerson** [comment]
If mypkg has dependencies not in the same repository and not already installed, could that cause an issue? 

> Is mypkg_0.1.4 current in your drat repository, or should it be found in the archive there?

It is the current version. I tried installing a newer version so 0.1.4 is in the archive, and I have the same issue when 0.1.4 is in the archive. The rest of my response is with 0.1.4 as the current version in the drat repo.

> Can you confirm that the package is found if you execute:
`renv:::renv_available_packages_entry("mypkg", type = "source")`

With the company repo as `file://R:/`, I receive this object. Since this still works with `install.packages()`, I'll keep it as this.

```
structure(list(Package = "mypkg", Version = "0.1.4", Priority = NA_character_, 
    Depends = NA_character_, Imports = "BART, data.table, dplyr, drake, forcats, ggforce, ggplot2,\nmagrittr, magrittr, rlang, rpart, stringr, tibble, tidyr,\nxgboost", 
    LinkingTo = NA_character_, Suggests = "knitr, rmarkdown", 
    Enhances = NA_character_, License = NA_character_, License_is_FOSS = NA_character_, 
    License_restricts_use = NA_character_, OS_type = NA_character_, 
    Archs = NA_character_, MD5sum = "4e94f8d632274146a8db05967d25d557", 
    NeedsCompilation = "no", Repository = "file://R:/src/contrib", 
    Type = "source", Name = "COMPANY"), row.names = "miypkg", class = "data.frame")
```

With the the original repo `file:///R:/`, it failed with `Error: failed to find source for package mypkg in active repositories`. 
> Can you also check whether using a repository URL as:
`file:R:/<...>`
works; that is, without any slash? I wonder if renv is failing to handle this particular form for the repository URL.

I tried `file:R:/`, `R:/` and `file://R:/` for the repo specification. In all cases, renv is still trying to hit CRAN For the result. 

One thing that is strange is it seems renv correctly identifies it at one point (under any of the repo specifications beginning with `file`)

```
> renv::restore(packages = "mypkg")
The following package(s) will be updated:

# COMPANY =============================
- mypkg  [* -> 0.1.4]
```

If this is any help, the `renv.lock` entry looks like

```
    "mypkg": {
      "Package": "mypkg",
      "Version": "0.1.4",
      "Source": "Repository",
      "Repository": "COMPANY",
      "Hash": "b31bc42c43a7b6262af0538493a31048"
    },
```

**Comment by smingerson** [comment]
I was working in a project without renv today, and `utils::install.packages("dplyr")` fails with
```
Warning in install.packages :
  cannot open compressed file '//R:/src/contrib/PACKAGES', probable reason 'Invalid argument'
Error in install.packages : cannot open the connection
```
Switching my internal repo back to `file:///R:/` fixed the problem, so evidently the triple slash was there for a reason.

**Comment by kevinushey** [comment]
Got it. I think the bug here is in `renv`'s handling of file URIs on Windows, then. I'll try to take a look next week.

**Comment by kevinushey** [comment]
I've made some changes to the development version of reticulate that should ensure this is better handled. If you have a chance, can you try upgrading to the latest development version of `renv` and let me know if you have better luck?

**Comment by smingerson** [comment]
`renv::restore(packages = "mypkg")` is working as expected in the latest development version.  `renv::install("mypkg")` also works. Thank you for the speedy fix!

**Comment by kevinushey** [comment]
Fantastic! I'm very glad to hear it 🙂
