### ISSUE TITLE
RENV_PATHS_CACHE and libPath

### ISSUE THREAD

**Issue by umayrh** [rstudio/renv#313]
I'm trying to get Travis to cache all Renv-installed R packages by installing them all under a shared directory instead of per-project directory. I thought setting RENV_PATHS_CACHE would accomplish this but it's not in libPath and so R still install packages under project/renv. Is my understanding/usage of RENV_PATHS_CACHE incorrect? It it is, when is setting RENV_PATHS_CACHE useful? 
I've reviewed the docs but still confused by its behavior.

**Comment by umayrh** [comment]
RENV_PATHS_LIBRARY does what I needed so closing issue.

**Comment by kevinushey** [comment]
In case you haven't seen it, https://rstudio.github.io/renv/articles/ci.html#travis-ci should be helpful as well.
