### ISSUE TITLE
renv + RStudio Connect git-backed content

### ISSUE THREAD

**Issue by jd4ds** [rstudio/renv#314]
When deploying git-backed content to RStudio Connect which is managed with renv it seems redundant to additionally execute rsconnect::writeManifest() each time the renv configuration has changed.
Is there something I'm missing? Is there anyway around this? Or will RStudio Connect also be able discover packages through the renv.lock file in the near future?
Thanks!

**Comment by kevinushey** [comment]
Thanks for the feature request! We're planning on adding `renv` support to RStudio Connect in the future; it just hasn't happened yet.

**Comment by jd4ds** [comment]
One thing that I've noticed when deploying content managed by renv to RStudio Connect is that although it seems to work technically, the startup times for content are extremely slow, so I had to set the startup timeouts to twice the default startup timeouts.

**Comment by jd4ds** [comment]
The issue was probably fixed by https://docs.rstudio.com/connect/news/#rstudio-connect-1863.
