### ISSUE TITLE
restore of git repos using SSH fails auth on Windows

### ISSUE THREAD

**Issue by mstr3336** [rstudio/renv#316]
Whenever I try to call `renv::restore()` on windows systems, it seems to hit a wall on my private git repos, auth'd with private/public keys (no password). 

I don't have this problem on other platforms. 

I'm not sure if `renv` is actually to blame, or if I'm missing something about how to make sure the ssh agent is running, but I have noticed that with the ssh agent running in the background, git clones of these repos seem to work fine, while `restore` fails.

When I'm home and booted to windows I can provide more info on this, but in the mean-time I was wondering if anyone else has encountered this, and what they did to resolve it?

**Comment by kevinushey** [comment]
I think the problem here is that we haven't set up a `git` askpass helper for Windows:

https://github.com/rstudio/renv/blob/21fa2183fe0c617e99074b6deab4b1505a7412cf/R/retrieve.R#L247-L250

**Comment by mstr3336** [comment]
> (well, to be clear, we have, but I'm not certain if it works with shell scripts as opposed to plain Windows batch scripts)

Do you mean to say that you have defined a helper for windows, and that helper works for batch scripts, but might not work for shell scripts?

Also, when we say "shell scripts" are we talking about scripts that might be executed in a minGW shell?

**Comment by kevinushey** [comment]
> Do you mean to say that you have defined a helper for windows, and that helper works for batch scripts, but might not work for shell scripts?

The other way around -- it works for shell scripts (executed by e.g. `bash` or `sh`) but not for regular Windows batch scripts (executed by e.g. `cmd.exe`).

In the development version of `renv`, I've made sure that we don't try to use this script on Windows (and only ever use it if `GIT_USERNAME` and `GIT_PASSWORD` are both set), so that may alleviate the issue here -- let me know if it makes a difference.

**Comment by kevinushey** [comment]
I think this issue is now handled in the development version of `renv`. If you're still having trouble, please feel free to re-open or file a separate issue with some more detail. Thanks!

**Comment by matthewstrasiotto** [comment]
I re-explored this recently, as it became necessary to run my software on a corporate server that only has windows.

I finally resolved my problem - it was not `renv`'s problem, but rather some non-obvious windows-specific platform discrepencies - Basically `R` on windows sets the `$HOME` variable used by `base::system` processes to be something different from the `$HOME` variable used by shells, and this means the same config isn't used between a shell vs R-launched processed. 

Documented further at: https://github.com/rstudio/renv/issues/424#issuecomment-792724374
