### ISSUE TITLE
Doc improvement: sandbox is enabled by default on unix

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#317]
Trying to understand better the internal of renv to configure it best for users in our servers, I spend some times on the different libpaths and configurations. 

I find that the doc says `sandbox.enabled` is FALSE by default
https://rstudio.github.io/renv/reference/config.html

However, it seemed I was using sandbox. After looking where I would have changed something, I found that the default is TRUE on unix. 
https://github.com/rstudio/renv/blob/b7ac4322f4e4d10b5e1ff8210b8b8c75393203b6/R/sandbox.R#L2-L4

Maybe it could be documented ? 
And maybe this is not the only thing with a OS-related default.

**Comment by kevinushey** [comment]
Thanks for catching that -- this is a deficiency in the documentation.

While I'd like to enable this by default, my experience is that the sandboxing mechanism fails in some commonly-used Windows environments.
