### ISSUE TITLE
Loading Renviron manually looses expansion identifer for R_LIBS_*

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#318]
On our mutualized servers, we use `R_LIBS_SITE` to configure a site library. As we need to take care of multiple R versions, we use the expansion identifier as describe in `?.libPaths()`
Something like that in `~/Renviron` 
```
R_LIBS_SITE=/applis/R/site-library/%p/%V
```

It seems when using a `renv` project, the ` ~/.Renviron` file is manually imported in `renv_load_renviron` using `readRenviron`. Issue is this function does not do the identifier expansion as it is done when R load the environ file. 

Outside of renv project I get : 
```r
> Sys.getenv("R_LIBS_SITE")
[1] "/applis/R/site-library/x86_64-pc-linux-gnu/3.6.2"
```
but inside renv project
```r
> Sys.getenv("R_LIBS_SITE")
[1] "/applis/R/site-library/%p/%V"
```

This means the environment variable can't be read anymore. 

This could be a very special case but I think it is worth underlying this behavior. 
I did not find an R function that does the % identifier expansion. Not sure it is possible... 
You may already have encounter this and know how to solve this.

It is a bit annoying that renv behavior superseed this by overwriting the env variable. However, I can find some workaround by not using this environment variable anymore or by setting at the server level if possible as `Renviron.site` is correctly loaded by R, not read by renv.

I don't know if other R environment variables, other than `R_LIBS_*` have this feature and could be impacted. 

Anyway, `%` identifier can't be used in environ file that `renv` will load.

## Step to reproduce

1. create a project with renv
2. Have a `~/.Renviron` with `R_LIBS_SITE` set up
3. compare `Sys.getenv("R_LIBS_SITE")` when renv activated and when deactivated

**Comment by kevinushey** [comment]
Thanks! The base R function `.expand_R_libs_env_var()` is supposed to be used for this purpose; I think I need to make sure this is called on `R_LIBS_*` after calling `readRenviron()`.

FWIW R itself does this initialization in its base `.Rprofile`, as defined here:

https://github.com/wch/r-source/blob/7d071d16b90a78d6f707713fb50f6329cc820e8d/src/library/profile/Common.R#L58-L62

**Comment by cderv** [comment]
Thanks for the link ! I did not think this time on looking into r-source. This function will be useful to know. Another mystery solved! 😉 

Would be nice if `renv` does the same as `.Rprofile` indeed- it would help for servers management and be consistent with R behavior.
