### ISSUE TITLE
renv doesn't respect github sourced Bioconductor installs

### ISSUE THREAD

**Issue by alexvpickering** [rstudio/renv#319]
if I install a Bioconductor package development version from github, e.g.:
`renv::install('Bioconductor/BiocGenerics')`

Then `renv::snapshot()` complains about it being from a seperate Bioconductor release. If i manually edit the lockfile to Source: "Github", then `renv::restore()` works fine but calls to `renv::snapshot()` change Source back to "Bioconductor".

Ideally I should update to R 4.0.0 and work from there but it is a bit cumbersome until it is released. It would be really nice if `renv` could record that a particular bioconductor package was installed from github.

**Comment by kevinushey** [comment]
What version of renv are you using? There were some changes made in the development version of renv to help better handle this.

**Comment by alexvpickering** [comment]
0.9.2

I'll try dev and report back. Thank you

**Comment by alexvpickering** [comment]
Working very well in 0.9.2.20 thanks again!
