### ISSUE TITLE
Philosophically should renv itself use renv?

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#32]
I would argue no, because it's actually more important for a CRAN package to be compatible with current versions of packages. (Although in the short-term, I can certainly see the advantages of dog-fooding)

**Comment by kevinushey** [comment]
Right, it's mostly done for dog-fooding at this point. However, I've also needed it for [remotes](https://github.com/r-lib/remotes/pull/310) and [pkgdown](https://github.com/r-lib/pkgdown/pull/978).
