### ISSUE TITLE
Unable to install new packages with install.packages() after running renv::init()

### ISSUE THREAD

**Issue by grahamalytics** [rstudio/renv#320]
**Issue**
Began using renv today for managing project environments and package dependencies. After creating a new project folder and running `renv::init()`, I attempted to install packages into the new project however am unable to do so. 

Here is code below from my attempt to install the profvis package and related error and warnings:

`> install.packages('profvis')`
`Error: package 'profvis' is not available`
`In addition: Warning messages:`
`1: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib"`
`2: could not retrieve available packages for url "https://cran.rstudio.com/bin/windows/contrib/3.6"`

I've confirmed that I'm able to install the package in a new R session separate from the project. This issue is not unique to the profvis package as I have tried it on a few others with the same result

Also, I noticed when I went into RStudio-->Global Options-->Packages that I saw the following warning under the _Package Management_ header that said 

> CRAN Repositories modified outside package preferences

I'm not sure what this is referring to exactly.

**System specs**
Windows 10
RStudio v1.2.5033
R v3.6.2
renv v0.9.2

**renv.lock file**
`{
  "R": {
    "Version": "3.6.2",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.9.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5181d5f316c7a6589219866d640e004c"
    }
  }
}`

**Comment by cderv** [comment]
> could not retrieve available packages for url "https://cran.rstudio.com/src/contrib"

It seems you have some issue to connect to  https://cran.rstudio.com/ . Do you have internet connectivity ? A proxy to pass through maybe ? 

There are some useful information on how `renv` works for downloading packages 
https://rstudio.github.io/renv/articles/renv.html#downloads

One difference with `install.packages` is that `renv::install`  is using curl 
> By default, renv uses curl for file downloads when available

and also know, that by default `renv` use shims to get the full of the caching feature and it means that by default when you call `install.packages` inside a renv project, it will call `renv::install` 
See https://rstudio.github.io/renv/articles/renv.html#shims

Hope it helps identify what is going wrong

**Comment by grahamalytics** [comment]
Hi Christophe, thanks for your comment. Yes, indeed, I am behind a corporate firewall. I read-up on the renv shims but must have missed the part about renv::install using curl.

Do you have any insight into how I can get renv to work inside a firewall? I do not have any access or ability to change proxy settings. Are there any options I can change?

Also, do you have any insight into where that message "CRAN Repositories modified outside package preferences" is coming from within RStudio? I'm having a hard time tracking it down.

As for a un-ideal workaround, I assume I could download the packages in my user's R directory and then load them in a project via library() before calling renv::init() in order to still use the dependency tracking feature of renv. Does this sound reasonable to you?

**Comment by kevinushey** [comment]
If you upgrade to the development version of `renv`, you should be able to set the environment variable:

```
RENV_DOWNLOAD_FILE_METHOD=wininet
```

to use the `wininet` download method (which R on Windows normally does).

**Comment by grahamalytics** [comment]
Thanks @kevinushey I will look into giving that a try.

**Comment by cderv** [comment]
@grahamalytics 
> Do you have any insight into how I can get renv to work inside a firewall? I do not have any access or ability to change proxy settings. Are there any options I can change?

I am also on windows behind a corporate proxy and I use the environment variables `http_proxy`, `https_proxy` and no `proxy` to configure with my proxy setting. it is method 1 describe [here ](https://rstudio.github.io/renv/articles/renv.html#proxies)and it works. something like `http_proxy=http://user:pwd@proxy_url_or_ip:port` and `curl::ie_get_proxy_for_url()` would help you find the url or ip.

Changing renv download file method to wininet maybe easier though as it will use IE settings that should already be configured in your work computer. Nothing to do.

**Comment by kevinushey** [comment]
I think the issue here is well understood now, with workarounds documented as necessary. Thanks for the report!

**Comment by dpopadic** [comment]
Had the same issue as I was unable to install new packages from private repos after initialising renv. I'm working inside a firewall (on windows) and without having to change proxy settings or the curl download method this worked for me:

```
renv::deactivate()
utils::install.packages(pkgs = "my_pkg")
renv::activate()
renv::snapshot()
```

Note: I have a specific method for file-download in my project .Rpfrofile: `options(download.file.method = "libcurl")`

**Comment by armenic** [comment]
There is a nice conversation with a solution at https://community.rstudio.com/t/cant-install-packages-with-renv/96696

```
Can you also share the output of:

getOption("download.file.method")
renv:::renv_download_file_method()
I wonder if renv is selecting a different download method that for some reason does not work on your machine. If that's the case, then setting:

RENV_DOWNLOAD_FILE_METHOD = <method>
where <method> is the same as what's currently set for the download.file.method option should help. (That can be set in your project's .Renviron file.)
```
