### ISSUE TITLE
renv tests all fail for users with uid >32767 

### ISSUE THREAD

**Issue by swt30** [rstudio/renv#321]
This took me a while to understand but I think I have found what's going on now.

Steps to reproduce:
* Run the renv tests with a user whose uid is > 32767.
* All tests fail.

What's happening:
* R's internal `utils::tar` command produces a warning when used with uids > 32767 (https://stackoverflow.com/questions/30599326/warning-message-during-building-an-r-package-invalid-uid-value-replaced-by-that)
* renv uses `utils::tar` during test setup 
  https://github.com/rstudio/renv/blob/83fa169e6d49559a072e350267a427df1c8ac634/R/tests.R#L128
* renv sets options(warn = 2) during testing, converting warnings to an error
  https://github.com/rstudio/renv/blob/83fa169e6d49559a072e350267a427df1c8ac634/R/tests.R#L97
* According to the stackoverflow discussion above, the use of this internal tar command can be bypassed by providing a system tar in an environment variable like `R_BUILD_TAR`. This workaround can be used to avoid the warning when building/installing packages, and `utils::tar` itself also checks Sys.getenv("tar"). But renv calls `utils::tar` directly with the argument `tar = internal` and so overrides those choices.
* Therefore renv tests fail if your uid is too large.

I can think of two ways that we might be able to resolve this:
* Don't force the use of tar = "internal", allowing the use of the system tar instead of the internal R implementation.
* Don't convert warnings to errors.

Any other ideas?

**Comment by kevinushey** [comment]
Thanks for the bug report -- we no longer enforce use of the R internal tar during tests.
