### ISSUE TITLE
Found continuation line starting...

### ISSUE THREAD

**Issue by cjvanlissa** [rstudio/renv#322]
This issue is tripping me up with `renv`. It's a known issue for `packrat` and `devtools`, but I haven't found a working solution.

https://github.com/rstudio/packrat/issues/470
https://github.com/r-lib/devtools/issues/1900

**Comment by kevinushey** [comment]
It would help if you provided the whole error message you're seeing.

**Comment by kevinushey** [comment]
A reprex would also be greatly helpful.
