### ISSUE TITLE
renv bootstrapping with cache

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#323]
I am building a handful of test Docker images and scripts that use `renv` to prepare environments. I am adjusting or removing the `renv`-generated `.Rprofile` and `renv/activate.R` files to avoid private installs of `renv`. This issue is trying to determine how to best bootstrap `renv` in shared multi-project environments (such as a Docker image that may be used for multiple Shiny applications).

In my working directory, I have `cache` and `content` subdirectories. The `cache` directory starts empty. The `content` directory contains a simple R Markdown document and the `.Rprofile`, `renv.lock`, and `renv/activate.R` created by `renv` initialization and snapshotting.

Bootstrapping `renv` installs the package into the `renv/library/....` and does not take advantage of the cache. This means that each project that uses `renv` installs its own copy of the package.

In my case, I have a same-version of `renv` in the environment. The `renv/activate.R` does not see this copy of `renv` because it is not a loaded namespace. I am attempting to restore outside an active R session with:

```bash
export RENV_PATHS_CACHE=/cache
R -e 'renv::restore(repos = c(CRAN=Sys.getenv("R_REPOSITORY")))'
# Failed to find installation of renv -- attempting to bootstrap...
# * Installing renv 0.9.2 ... Done!
# Successfully installed and loaded renv 0.9.2.
```

This `renv` is in `renv/library` but not the cache. Everything besides `renv` is a symlink from `renv/library/...` into `/cache/...`.

```bash
ls -ld renv/library/R-3.6/x86_64-pc-linux-gnu/renv
drwxr-xr-x 13 USER USER 416 Jan 22 22:39 renv/library/R-3.6/x86_64-pc-linux-gnu/renv
ls -ld /cache/v5/R-3.6/x86_64-pc-linux-gnu/renv
ls: cannot access '/cache/v5/R-3.6/x86_64-pc-linux-gnu/renv': No such file or directory
```

The system-installed `renv` is used if the `.Rprofile` is changed to:

```r
library(renv)
source("renv/activate.R")
```

Alternatively, I can bypass `renv/activate.R` entirely if I ditch the `.Rprofile` and explicitly call `renv::load()`:

```bash
R --slave -e 'renv::load(); renv::restore(repos = c(CRAN=Sys.getenv("R_REPOSITORY")))'
```

What is the recommended way to bootstrap `renv` into environments? Should `renv/activate.R` attempt to load `renv` from the system library if the namespace is not already loaded? Should `renv` come from the cache (is this even possible with such a lightweight `renv/activate.R`)?

**Comment by kevinushey** [comment]
The main challenge in making this work automagically:

1. To form a path into the cache, the appropriate version of `renv` must be installed.
2. `renv` is not installed, so we cannot form that path without installing it.

The fix here would be to include the appropriate cache-finding code into the standalone `activate.R` script, so that `renv` could find itself in the cache and symlink that instead of requiring a brand new install.

**Comment by kevinushey** [comment]
Revisiting this with a fresh perspective, I think your second proposal is the right way forward. That is, you can avoid using the `renv` autoloader, and instead manage the load process yourself.
