### ISSUE TITLE
Windows Server: Error: failed to retrieve package

### ISSUE THREAD

**Issue by bjoerm** [rstudio/renv#326]
Hey guys,
Thanks a lot for your work.

We run R scripts on a remote Windows Server. We have experience working with packrat and that is working for us. However, for a new project we wanted to give renv a try.

We use git to collaborate on code. We have it set-up, so that my colleagues can pull the code, the renv.lock file and with that successfully run a renv::restore(). So everything runs like expected on their local machines. We all run R 3.6.1, latest renv version from cran (0.9.2) and use Windows 10 locally.

However, on the remote Windows Server, for the exact same code as for my colleagues, we run into errors.

    library(renv)    
    renv::activate()
    renv::restore(confirm = FALSE)

Leads to the console output:

    * Project 'D:/[my path...]' loaded. [renv 0.9.2]

    The following package(s) will be updated:

    # CRAN ===============================
    - BH           [* -> 1.72.0-3]
    - DBI          [* -> 1.1.0]
    - R6           [* -> 2.4.1]
    [...]
    - zeallot      [* -> 0.1.0]

    * Querying repositories for available binary packages ... Done!
    * Querying repositories for available source packages ... Done!
    Retrieving 'https://cran.rstudio.com/src/contrib/Archive/BH/BH_1.72.0-3.tar.gz' ...
    Error: failed to retrieve package 'BH'
    In addition: Warning messages:
    1: could not retrieve available packages for url "https://cran.rstudio.com/bin/windows/contrib/3.6" 
    2: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib" 
    3: In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
    InternetOpenUrl failed: 'The requested header was not found'

So it is (to me) a bit odd that it goes for `/src/contrib/Archive/...` and not just `/src/contrib/...

After reading other issues here and in the manual, I checked:

    renv:::renv_download_file_method()

    # Which returns:
    "libcurl"

Executing `capabilities("libcurl")` returns `libcurl TRUE`.

I was unable to run `renv::equip()` as that lead to:

    Error: download failed [cannot open URL 'https://s3.amazonaws.com/rstudio-buildtools/extsoft/local323.zip']
    In addition: Warning message:
    In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
    InternetOpenUrl failed: 'The requested header was not found'

Outside of this project and thus without renv, I can install (and have) the curl package in R. I can also just install any package on my own via install.packages() outside renv on that computer.

Here is the return from the diagnostics function as well as the renv.lock.
[renv diagnostics.txt](https://github.com/rstudio/renv/files/4129197/renv.diagnostics.txt)
[renv.lock](https://github.com/rstudio/renv/files/4129199/renv.lock.txt)

    > sessionInfo()
    R version 3.6.1 (2019-07-05)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows Server x64 (build 14393)

    Matrix products: default

    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] renv_0.9.2

    loaded via a namespace (and not attached):
    [1] compiler_3.6.1 tools_3.6.1    packrat_0.5.0 

Any idea of what is going wrong or any information I can provide?

Thank you very much!

**Comment by kevinushey** [comment]
The chief issue here is:

```
In addition: Warning messages:
1: could not retrieve available packages for url "https://cran.rstudio.com/bin/windows/contrib/3.6" 
2: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib" 
```

which implies that `renv` isn't able to query available packages in that environment, for some reason.

What is the output of

```R
getOption("download.file.method")
renv:::renv_available_packages(type = "source")
```

1. within an `renv` project; and
2. outside of an `renv` project?

https://github.com/rstudio/renv/issues/264 may also be relevant.

You can also try installing the development version of `renv`, using e.g.

```
renv::install("rstudio/renv")
```

and setting:

```
Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "wininet")
# or, try libcurl
```

to force `renv` to use a specific download method.

**Comment by bjoerm** [comment]
Hey @kevinushey,
Thanks for the awesomely swift and helpful response.


I tested your suggestions and here are the results:



    library(renv)

    Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "libcurl")

    renv::restore(
        # clean = TRUE
        # , 
        confirm = FALSE
    )

works and returns this output:

    The following package(s) will be updated:

    # CRAN ===============================
    - renv         [rstudio/renv -> 0.9.2]
    - BH           [* -> 1.72.0-3]
    - DBI          [* -> 1.1.0]
    - R6           [* -> 2.4.1]
    - Rcpp         [* -> 1.0.3]
    - assertthat   [* -> 0.2.1]
    [...]

    * Querying repositories for available binary packages ... Done!
    Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/renv_0.9.2.zip' ...
        OK [downloaded 801 Kb in 0.4 secs]
    Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/BH_1.72.0-3.zip' ...
        OK [downloaded 17.4 Mb in 0.6 secs]
    Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/DBI_1.1.0.zip' ...
        OK [downloaded 593 Kb in 0.3 secs]    
    [...]

    * Querying repositories for available source packages ... Done!
    Retrieving 'https://cran.rstudio.com/src/contrib/Archive/rlang/rlang_0.4.2.tar.gz' ...
        OK [downloaded 789 Kb in 0.5 secs]
    Retrieving 'https://cran.rstudio.com/src/contrib/Archive/vctrs/vctrs_0.2.1.tar.gz' ...
        OK [downloaded 0 bytes in 0.5 secs]
    Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/backports_1.1.5.zip' ...
        OK [downloaded 67 Kb in 0.2 secs]    
    [...]

    Installing renv [0.9.2] ...
        OK [installed binary]
    Installing BH [1.72.0-3] ...
        OK [installed binary]
    Installing DBI [1.1.0] ...
        OK [installed binary]
    Installing R6 [2.4.1] ...
        OK [installed binary]
    Installing Rcpp [1.0.3] ...
        OK [installed binary]


So thanks to your help, I am able to bypass the problems I had on that server.



*However, I found something that is odd. When I execute:*

    library(renv)

    # First try
    Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "wininet")
    renv:::renv_available_packages(type = "source")

    # Second try
    Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "libcurl")
    renv:::renv_available_packages(type = "source")

The first try block returns (as expected, as wininet seems to cause the trouble):

    * Querying repositories for available source packages ... Done!
    named list()
    Warning messages:
    1: package ‘renv’ was built under R version 3.6.2 
    2: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib" 

However, *executing the second try block afterwards (in the same R session) still leads to an output of only*

    named list()





At the same time executing only the second block without having run the first block in the same R session:

    library(renv)
    Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "libcurl")
    renv:::renv_available_packages(type = "source")

Leads to:

    * Querying repositories for available source packages ... Done!
    $CRAN
                                Package Version Priority
    A3                                 A3   1.0.0     <NA>
    aaSEA                           aaSEA   1.1.0     <NA>
    ABACUS                         ABACUS   1.0.0     <NA>
    abbyyR                         abbyyR   0.5.5     <NA>
    abc                               abc     2.1     <NA>
    abc.data                     abc.data     1.0     <NA>
    ABC.RAP                       ABC.RAP   0.9.0     <NA>
    abcADM                         abcADM     1.0     <NA>
    ABCanalysis               ABCanalysis   1.2.1     <NA>
    abcdeFBA                     abcdeFBA     0.4     <NA>
    ABCoptim                     ABCoptim  0.15.0     <NA>
    ABCp2                           ABCp2     1.2     <NA>
    [...]

and is thus working.


*To me it seems that the execution of renv:::renv_available_packages in the second block does not even try to get the renv_available_packages, after I set Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "libcurl").*



This was done with renv 0.9.2 from cran and not yet the Gitlab version. Will now experiment further and try running renv::equip() on that Windows Server (while using libcurl).

**Comment by bjoerm** [comment]
PS:

    Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "libcurl")
    renv::equip()

Worked, was able to download and install the additional packages/building tools (incl. curl).

Now on our Windows Server everything is working out of the box.

    library(renv)
    renv::restore(confirm = FALSE)

Thank you very much!

Shall I close the issue or do you want to investigate the `named list()` issue I mentioned above?

**Comment by kevinushey** [comment]
Great to hear!

Let's leave this issue open; I think that issue is worth fixing. (The underlying issue is that `renv` caches the output of available packages, but perhaps erroneously does that when the download fails.)

**Comment by Jfluss** [comment]
I have some very similar issues, but on a local machine (not server). The project and the main libraries are both on the same drive and the install works when you specify the library path but not without it.
Here are the .libPaths for a new project I just created, following init and snapshot with existing scripts. When trying to install a new package, I get 
```
> .libPaths()
[1] "C:/Users/Josh/R Projects/FR2900_R_Code/renv/library/R-3.6/x86_64-w64-mingw32"
[2] "C:/Users/Josh/R-3.6.0/library"                                               
> install.packages("rsample")
Error: package 'rsample' is not available
In addition: Warning messages:
1: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib" 
2: could not retrieve available packages for url "https://cran.rstudio.com/bin/windows/contrib/3.6" 
```
But after specifying the library, the package installs correctly. 
```
> install.packages("rsample", .libPaths()[1])
also installing the dependencies ‘listenv’, ‘future’, ‘globals’, ‘generics’, ‘furrr’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/listenv_0.8.0.zip'
Content type 'application/zip' length 106914 bytes (104 KB)
downloaded 104 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/future_1.16.0.zip'
Content type 'application/zip' length 685787 bytes (669 KB)
downloaded 669 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/globals_0.12.5.zip'
Content type 'application/zip' length 76713 bytes (74 KB)
downloaded 74 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/generics_0.0.2.zip'
Content type 'application/zip' length 65650 bytes (64 KB)
downloaded 64 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/furrr_0.1.0.zip'
Content type 'application/zip' length 110531 bytes (107 KB)
downloaded 107 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/rsample_0.0.5.zip'
Content type 'application/zip' length 374455 bytes (365 KB)
downloaded 365 KB

package ‘listenv’ successfully unpacked and MD5 sums checked
package ‘future’ successfully unpacked and MD5 sums checked
package ‘globals’ successfully unpacked and MD5 sums checked
package ‘generics’ successfully unpacked and MD5 sums checked
package ‘furrr’ successfully unpacked and MD5 sums checked
package ‘rsample’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Josh\AppData\Local\Temp\RtmpoFtqCm\downloaded_packages
```
capabilities("libcurl") also returns TRUE, like above, and even after installing it by specifying the .libPaths, attempting to install the package again still fails. Running the above code to try and set the system environment variable still generates ```named list()```, not the list of packages. This is also on version 0.9.2 from CRAN.

```
> capabilities("libcurl")
libcurl 
   TRUE 
> install.packages("rsample")
Error: package 'rsample' is not available
> Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "libcurl")
> renv:::renv_available_packages(type = "source")
named list()
```

Finally, I also restarted the R session to re-run that code and see what it would do, but I got a different result.

```
> Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "libcurl")
> renv:::renv_available_packages(type = "source")
* Querying repositories for available source packages ... Done!
named list()
Warning message:
could not retrieve available packages for url "https://cran.rstudio.com/src/contrib" 
```

I've also included the output of renv::diagnostics. 
[renv_diagnostics.txt](https://github.com/rstudio/renv/files/4150259/renv_diagnostics.txt)

Any other information I can provide?

**Comment by kevinushey** [comment]
I think the issue here is that the download file method that `renv` is using doesn't match what R itself is using, and R is correctly configured for downloads but `renv` isn't.

What is the output of:

```
getOption("download.file.method")
```

on your machine? Does setting `RENV_DOWNLOAD_FILE_METHOD` to match that output make a difference?

**Comment by Jfluss** [comment]
Unfortunately, that doesn't seem to resolve the issue either 
```
> getOption("download.file.method")
[1] "wininet"
> 
> Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "wininet")
> renv:::renv_available_packages(type = "source")
* Querying repositories for available source packages ... Done!
named list()
Warning message:
could not retrieve available packages for url "https://cran.rstudio.com/src/contrib" 
```

But when I run the same code outside of a project I get a NULL returned.

```
> getOption("download.fie.method")
NULL
```

Both of these were run in brand new R sessions.

Here is the session info for the R session outside of the project.

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    yaml_2.2.0   
```

**Comment by kevinushey** [comment]
I noticed you mistyped `download.file.method` here:

```
> getOption("download.fie.method")
NULL
```

Can you try once more with the spelling corrected?

> Also I don't know if this is helpful or related, but it looks like there is no site library available, and the libPath is not defaulting to the user library. Not sure how this happened but I wonder if this is part of the issue.

This is unrelated -- by default, R on Windows does not specify a site library, and `.Library` may or may not be specified as a so-called Windows "short path name". However, the version reported in `.libPaths()` will always be normalized, hence why they appear different.

One more thing we could try to learn about how the default R downloader is configured. Can you execute the following:

```
trace(download.file, exit = quote(print(ls.str())))
db <- available.packages(ignore_repo_cache = TRUE)
```

and let me know what is printed out? You should see something like:

```
> trace(download.file, exit = quote(print(ls.str())))
Tracing function "download.file" in package "utils"
[1] "download.file"
> db <- available.packages(ignore_repo_cache = TRUE)
Tracing download.file(url = paste0(repos, "/PACKAGES.rds"), destfile = dest,  .... on exit 
cacheOK :  logi FALSE
destfile :  chr "/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T//Rtmp5bgmgR/file3fd12f5515ae"
extra :  NULL
headers :  NULL
method :  chr "libcurl"
mode :  chr "wb"
nh :  NULL
quiet :  logi TRUE
status :  int 0
url :  chr "https://cran.rstudio.com/src/contrib/PACKAGES.rds"
```

**Comment by Jfluss** [comment]
> I noticed you mistyped ```download.file.method``` here:

Whoops, corrected above. It does return "wininet" like before.

And here is the output from the print you requested.

```
> trace(download.file, exit = quote(print(ls.str())))
Tracing function "download.file" in package "utils"
[1] "download.file"
> db <- available.packages(ignore_repo_cache = TRUE)
Tracing download.file(url = paste0(repos, "/PACKAGES.rds"), destfile = dest,  .... on exit 
cacheOK :  logi FALSE
destfile :  chr "C:\\Users\\Josh\\AppData\\Local\\Temp\\RtmpcXIoYd\\file7f787cc168e5"
extra :  NULL
headers :  NULL
method :  chr "wininet"
mode :  chr "wb"
nh :  NULL
quiet :  logi TRUE
status :  int 0
url :  chr "https://cran.rstudio.com/src/contrib/PACKAGES.rds"
```

**Comment by kevinushey** [comment]
This should now be fixed in the development version of `renv`. The issue here was that `renv` was making a call to `download.file()` like this:

```
> download.file(

+   url      = "https://cloud.r-project.org/src/base/THANKS",
+   destfile = tempfile(),
+   method   = "wininet",
+   headers  = character()
+ )
trying URL 'https://cloud.r-project.org/src/base/THANKS'
Error in download.file(url = "https://cloud.r-project.org/src/base/THANKS",  : 
  cannot open URL 'https://cloud.r-project.org/src/base/THANKS'
In addition: Warning message:
In download.file(url = "https://cloud.r-project.org/src/base/THANKS",  :
  InternetOpenUrl failed: 'The requested header was not found'
```

That is, setting `headers = character()` triggered this issue.

Can you try updating to the development version of `renv` and let me know if things appear fixed? You can use:

```
renv::upgrade(version = "master")
```

to upgrade `renv` for a particular project.

**Comment by Jfluss** [comment]
After updating renv from github using remotes and reinitializing renv on a toy project (renv::upgrade wouldn't work because of the header issue you described) the problem was resolved and I was able to both install and update packages within the project successfully

```
> renv::activate()
* Project 'C:/Users/B1JXF16/R Projects/FR2900_R_Code' loaded. [renv 0.9.2]
> renv::install("yardstick")
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/yardstick_0.0.5.zip' ...
	OK [downloaded 1.2 Mb in 0.5 secs]
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/pROC_1.16.1.zip' ...
	OK [downloaded 1.3 Mb in 0.5 secs]
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/plyr_1.8.5.zip' ...
	OK [downloaded 1.2 Mb in 0.5 secs]
Installing plyr [1.8.5] ...
	OK [installed binary]
Installing pROC [1.16.1] ...
	OK [installed binary]
Installing yardstick [0.0.5] ...
	OK [installed binary]
> install.packages("vctrs")
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/vctrs_0.2.2.zip' ...
	OK [downloaded 922 Kb in 0.3 secs]
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/rlang_0.4.4.zip' ...
	OK [downloaded 1.1 Mb in 0.2 secs]
Installing rlang [0.4.4] ...
	OK [installed binary]
Installing vctrs [0.2.2] ...
	OK [installed binary]
> renv::upgrade(version = "master")
* renv [0.9.2-43] is already installed and active for this project.
```

**Comment by kevinushey** [comment]
Great! I'm very glad to hear it; thanks for your perseverance in helping me get to the bottom of this issue. I'll plan to update `renv` on CRAN soon with this fix available.

**Comment by Jfluss** [comment]
Thank you for working with me to fix it! Look forward to seeing it on CRAN

**Comment by kevinushey** [comment]
renv 0.9.3 is now on CRAN and should have this fix. Thanks again for your help in narrowing this down!
