### ISSUE TITLE
Typo in warning message created by snapshot()

### ISSUE THREAD

**Issue by s-fleck** [rstudio/renv#327]
There is something wrong with this `sprintf()` statement:

```
  fmt <- "'%s' requires '%s', but version '%s' will be snapshotted"
  txt <- sprintf(fmt, format(package), format(requires), format(package), format(request))
```
The result is something like this:
`'tidyselect' requires 'vctrs (>= 0.2.99.9002)', but version 'tidyselect' will be snapshotted`

**Comment by kevinushey** [comment]
You are indeed correct -- thanks for catching that! Fixed on master now.
