### ISSUE TITLE
snapshot requires version number suffix for local packages

### ISSUE THREAD

**Issue by dchiu911** [rstudio/renv#328]
I often receive local package updates from colleagues of the form `<package>_<date>.tar.gz`. This causes problems in `snapshot()` as it is unable to detect the source but `install()` still works fine. I have set `RENV_PATHS_LOCAL=~/Documents/packages` in my project-specific `.Renviron`.

With date suffix:
```
> renv::install("~/Documents/packages/promiseOvca_2020-01-30.tar.gz")
Installing promiseOvca [0.10] ...
	OK [built from source]
> renv::snapshot()
The following package(s) were installed from an unknown source:

	promiseOvca

renv may be unable to restore these packages in the future.
Consider re-installing these packages from a known source (e.g. CRAN).

Do you want to proceed? [y/N]: y
The following package(s) will be updated in the lockfile:

# (Unknown Source) ===================
- promiseOvca   [0.8 -> 0.10]

* Lockfile written to '~/Documents/GitHub/ovarian_promise/renv.lock'.
```

With version number suffix:
```
> renv::install("~/Documents/packages/promiseOvca_0.10.tar.gz")
Installing promiseOvca [0.10] ...
	OK [built from source]
> renv::snapshot()
The following package(s) will be updated in the lockfile:

# Local ==============================
- promiseOvca   [0.8 -> 0.10]

Do you want to proceed? [y/N]: y
* Lockfile written to '~/Documents/GitHub/ovarian_promise/renv.lock'.
```

Should the syntax `<package>_<version>.tar.gz` be strictly enforced so we don't run into this kind of issue? Thanks!

**Comment by kevinushey** [comment]
This is the documented behavior for local sources:

https://rstudio.github.io/renv/articles/local-sources.html

But `renv::install()` is less picky, and will install from arbitrarily-formatted package sources.

I'm not sure if I should make any changes here; I think if you're placing packages into the `renv` local sources folder then you need to adhere to the prescribed format.

(Perhaps `renv::install()` could be extended to tag installed packages with the filepath on disk from which it was originally retrieved, which would be a separate way to handle this separately from local sources)

**Comment by kevinushey** [comment]
Note: `remotes` does this; e.g.

```
RemoteType: local
RemoteUrl: /Users/kevinushey/r/pkg/skeleton_1.0.1.tar.gz
```
