### ISSUE TITLE
Failed to install package from source in a project with renv (succeeded without renv)

### ISSUE THREAD

**Issue by ScaonE** [rstudio/renv#334]
Using renv 0.9.2 and R 3.3.2

**I tried the following installation from source :**
```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/assertthat/assertthat_0.2.0.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

**Within an renv initialized project, it resulted in :**

> Installing package into ‘C:/Statistiques/R&D/Toto/renv/library/R-3.3/x86_64-w64-mingw32’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.r-project.org/src/contrib/Archive/assertthat/assertthat_0.2.0.tar.gz'
> Content type 'application/x-gzip' length 11612 bytes (11 KB)
> downloaded 11 KB
> 
> Erreur : ERREUR : aucun package spécifié
> Le chemin d'accŠs sp‚cifi‚ est introuvable.
> Warning in install.packages :
>   running command '"C:/Users/FR_SCA~1/DOCUME~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Statistiques\R&D\Toto\renv\library\R-3.3\x86_64-w64-mingw32" "C:/Users/FR_SCA~1/AppData/Local/Temp/RtmpO0c8xH/downloaded_packages/assertthat_0.2.0.tar.gz"' had status 1
> Warning in install.packages :
>   installation of package ‘C:/Users/FR_SCA~1/AppData/Local/Temp/RtmpO0c8xH/downloaded_packages/assertthat_0.2.0.tar.gz’ had non-zero exit status

_(French OS, so some error/warning messages appear in French, sorry about that)_

**Within a project without renv, it resulted in :**

> trying URL 'https://cran.r-project.org/src/contrib/Archive/assertthat/assertthat_0.2.0.tar.gz'
> Content type 'application/x-gzip' length 11612 bytes (11 KB)
> downloaded 11 KB
> 
> * installing *source* package 'assertthat' ...
> ** package 'assertthat' correctement décompressé et sommes MD5 vérifiées
> ** R
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> *** arch - x64
> * DONE (assertthat)

**=>** It seems that the issue are the backslashes in "C:\Statistiques\R&D\Toto\renv\library\R-3.3\x86_64-w64-mingw32" (the path where my renv project-specific files are stored).
Any hints ?

Best regards

**Comment by kevinushey** [comment]
Thanks for the bug report. This is happening because your project name has a `&`, and those special characters are not handled correctly by R. You can reproduce the issue outside of `renv` with something like:

```
libpath <- "~/scratch/R&D/library"
dir.create(libpath, recursive = TRUE)
.libPaths(libpath)
install.packages("assertthat", type = "source")
```

For example, I see:

```
> install.packages("assertthat", type = "source")
Installing package into ‘C:/Users/kevinushey/scratch/R&D/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/assertthat_0.2.1.tar.gz'
Content type 'application/x-gzip' length 12742 bytes (12 KB)
downloaded 12 KB

Error: ERROR: no packages specified
The filename, directory name, or volume label syntax is incorrect.
Warning in install.packages :
  installation of package ‘assertthat’ had non-zero exit status
```
