### ISSUE TITLE
Fail to compile in renv project

### ISSUE THREAD

**Issue by ScaonE** [rstudio/renv#335]
Dear all,

Thanks for the solution to a previous [issue](https://github.com/rstudio/renv/issues/334), it did solve many but not all of my installations issues.

_Ps_ : Using renv 0.9.2 and R 3.3.2, Win 7, non-admin user.

I am still trying to install a bunch a packages with specific versions using the install from source method below :
```
packageurl <- "https://cran.r-project.org/src/contrib/flashClust_1.01-2.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

**Within an renv initialized project, it resulted in** :
> Installing package into ‘C:/Statistiques/RnD/EasyBioM/renv/library/R-3.3/x86_64-w64-mingw32’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.r-project.org/src/contrib/flashClust_1.01-2.tar.gz'
> Content type 'application/x-gzip' length 8367 bytes
> downloaded 8367 bytes
> 
> * installing *source* package 'flashClust' ...
> ** package 'flashClust' correctement décompressé et sommes MD5 vérifiées
> ** libs
> 
> *** arch - i386
> Warning: l'exécution de la commande 'make -f "C:/Users/FR_SCA~1/DOCUME~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/Users/FR_SCA~1/DOCUME~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB="flashClust.dll" SHLIB_LIBADD='$(FLIBS)' OBJECTS="hc.o hcass2.o"' renvoie un statut 127
> ERROR: compilation failed for package 'flashClust'
> * removing 'C:/Statistiques/RnD/EasyBioM/renv/library/R-3.3/x86_64-w64-mingw32/flashClust'
> Warning messages:
> 1: running command '"C:/Users/FR_SCA~1/DOCUME~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Statistiques\RnD\EasyBioM\renv\library\R-3.3\x86_64-w64-mingw32" "C:/Users/FR_SCA~1/AppData/Local/Temp/Rtmpw7xSxP/downloaded_packages/flashClust_1.01-2.tar.gz"' had status 1 
> 2: In utils::install.packages(packageurl, repos = NULL, type = "source") :
>   installation of package ‘C:/Users/FR_SCA~1/AppData/Local/Temp/Rtmpw7xSxP/downloaded_packages/flashClust_1.01-2.tar.gz’ had non-zero exit status

**Within a project without renv, it resulted in :** 
_Ps_ : this project is located in the same parent directory as the renv-project.
> trying URL 'https://cran.r-project.org/src/contrib/flashClust_1.01-2.tar.gz'
> Content type 'application/x-gzip' length 8367 bytes
> downloaded 8367 bytes
> 
> * installing *source* package 'flashClust' ...
> ** package 'flashClust' correctement décompressé et sommes MD5 vérifiées
> ** libs
> 
> *** arch - i386
> C:/RBuildTools/3.5/mingw_32/bin/gfortran      -O3  -mtune=core2 -c hc.f -o hc.o
> C:/RBuildTools/3.5/mingw_32/bin/gfortran      -O3  -mtune=core2 -c hcass2.f -o hcass2.o
> C:/RBuildTools/3.5/mingw_32/bin/gcc -shared -s -static-libgcc -o flashClust.dll tmp.def hc.o hcass2.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -lgfortran -lm -lquadmath -LC:/Users/FR_SCA~1/DOCUME~1/R/R-33~1.2/bin/i386 -lR
> installing to C:/Users/FR_SCAERW/Documents/R/R-3.3.2/library/flashClust/libs/i386
> 
> *** arch - x64
> C:/RBuildTools/3.5/mingw_64/bin/gfortran      -O2  -mtune=core2 -c hc.f -o hc.o
> C:/RBuildTools/3.5/mingw_64/bin/gfortran      -O2  -mtune=core2 -c hcass2.f -o hcass2.o
> C:/RBuildTools/3.5/mingw_64/bin/gcc -shared -s -static-libgcc -o flashClust.dll tmp.def hc.o hcass2.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -lgfortran -lm -lquadmath -LC:/Users/FR_SCA~1/DOCUME~1/R/R-33~1.2/bin/x64 -lR
> installing to C:/Users/FR_SCAERW/Documents/R/R-3.3.2/library/flashClust/libs/x64
> Warning in file.copy(files, dest, overwrite = TRUE) :
>   problème lors de la copie de .\flashClust.dll vers C:\Users\FR_SCAERW\Documents\R\R-3.3.2\library\flashClust\libs\x64\flashClust.dll: Permission denied
> ** R
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> *** arch - x64
> * DONE (flashClust)

Within the renv project, RBuildTools is not found ?
Any tips ?

_Nb_ : I tried to [set RENV_PATHS_RTOOLS](https://github.com/rstudio/renv/issues/225) to the path that seems to be used in the successful install above : 
`Sys.setenv(RENV_PATHS_RTOOLS = "C:/RBuildTools/3.5/mingw_32/bin")`
But it did not do the trick.

Best regards

**Comment by kevinushey** [comment]
Thanks for the bug report! Can you share the output of the following commands?

```
renv:::renv_paths_rtools()
renv:::renv_scope_rtools()
Sys.which("make.exe")
Sys.getenv("SYSTEMDRIVE")
Sys.getenv("BINPREF")
```

**Comment by ScaonE** [comment]
Still using renv 0.9.2, the above commands yielded : 

`renv:::renv_paths_rtools()`
> [1] "C:/RBuildTools/3.5"

`renv:::renv_scope_rtools()`

`Sys.which("make.exe")`
> make.exe 
> "C:\\RBUILD~1\\3.5\\bin\\make.exe" 

`Sys.getenv("SYSTEMDRIVE")`
> [1] "C:"

`Sys.getenv("BINPREF")`
> [1] "C:/RBuildTools/3.5/mingw_$(WIN)/bin/"

**Comment by kevinushey** [comment]
I think I know what might be going on here. Are you working within RStudio?

By default, RStudio injects a hook for `install.packages()` which will ensure that Rtools is placed on the PATH. When an `renv` project is active, on the other hand, it will install its own shim that bypasses the RStudio shim, and so this doesn't happen.

There are a couple ways to work around this for now:

1. Call `renv:::renv_scope_rtools()` to ensure Rtools is placed on the PATH;
2. Use `renv::install()` as opposed to `install.packages()`.

I'll try to fix this up in `renv` as well.

**Comment by ScaonE** [comment]
Yes, I am working with RStudio (Version 1.1.463). I failed to mention it previously given that we are @github.com/rstudio.

`renv:::renv_scope_rtools()` is doing the trick for me atm. Thanks for you input !
