### ISSUE TITLE
renv::restore() freezes when installing stringi

### ISSUE THREAD

**Issue by Ljupch0** [rstudio/renv#339]
When running renv::restore(), the whole process gets blocked on stringi. What can be the issue?

**Comment by kevinushey** [comment]
Are you sure it's frozen? stringi takes a long time to install, especially when compiling from sources. You may just have to wait.

**Comment by Ljupch0** [comment]
Yes you are right. Takes like 15 mins.

**Comment by kevinushey** [comment]
Once that copy of stringi has been cached, future restores on that machine should be much faster.
