### ISSUE TITLE
Generate citation list

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/renv#340]
Suppose I'm working on a paper and using renv in my project. I'd love to be able to do something like `renv::cite()` and pass an argument for whether I want plain or bibtex citation and get a list of citations of all packages I've used, along with the correct version numbers. I could copy and paste this, maybe directly include it in an R Markdown file in the project? I'm not sure, but the basic print to the console or write out to a file functionality would be very welcome at the first stage! It might even have the positive effect of people getting in the habit of citing packages.

**Comment by kevinushey** [comment]
For 'plain' citations, do we need to be concerned about citation format? If so, which format(s) should be supported?

Note to self: we could likely use pandoc to convert a `.bibtex` database as appropriate; e.g. https://tex.stackexchange.com/questions/171793/bibtex-to-html-markdown-etc-using-pandoc.

We might also want to encourage users to create a `.bib` file and use that, since that's supported natively by R Markdown: https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

But not all projects will use R Markdown, of course.

**Comment by mine-cetinkaya-rundel** [comment]
My naive thinking was the style used in text citation when you run `citation("package")`. 

If offering multiple formats, perhaps the ones Google Scholar offers is not a bad starting place?

<img width="507" alt="Screenshot 2020-02-14 at 15 13 18" src="https://user-images.githubusercontent.com/5965649/74543110-b74b0300-4f3c-11ea-9a3d-da5437698212.png">

This package seems relevant: https://docs.ropensci.org/RefManageR/

**Comment by aronatkins** [comment]
Does `renv` have a function to return its current set of managed dependencies? Should it do more than asking users to JSON-parse the `renv.lock` file?

@mine-cetinkaya-rundel This might help you get started; it produces the package `DESCRIPTION` for each package referenced in the `renv.lock`:

```r
renvLock <- jsonlite::read_json("renv.lock")
packageNames <- names(renvLock$Packages)
packageDescriptions <- lapply(packageNames, packageDescription)
names(packageDescriptions) <- packageNames
```

Are there existing patterns for converting `DESCRIPTION` into the various citation formats? Could that happen from within the Rmd/R code? If the conversion happens by another package called by user code, it becomes just another dependency tracked by `renv`.

**Comment by kevinushey** [comment]
R has a function `citation()` that can be used to generate a citation for a given package, either formatted as `bibtex` or it's own plain-text format. That function either auto-generates an appropriate citation, or uses the package's own CITATION file to form the citation.

My thought is that we could use the generated `bibtex` and then convert that using `pandoc` as appropriate for the user-requested citation format.

**Comment by mine-cetinkaya-rundel** [comment]
I was also envisioning that `cite()` would use the output from `citation()`. In some cases, however, the citation is a book/paper as opposed to the "package", and hence doesn't include package version. In those cases `cite()` somehow append that information somehow.

**Comment by the-Hull** [comment]
@mine-cetinkaya-rundel  I've made a little (experimental) package for just that reason:

https://the-hull.github.io/lib2bib/index.html

**Comment by mine-cetinkaya-rundel** [comment]
Nice @the-Hull! I'll give it a try.

**Comment by jcolomb** [comment]
One can create the .bib file with:
```
renvLock <- jsonlite::read_json("renv.lock")
sink("biblio.bib")
knitr::write_bib(names(renvLock$Packages))
sink()
```

you may want to also use something like
 `sapply(names(renvLock$Packages), function(x) print(citation(x), style = "Bibtex"))`

could be nice to have it part of the remv package to make it easier for normal users ?

**Comment by hadley** [comment]
This is pretty easy to do yourself:

```R
deps <- renv::dependencies()
pkgs <- setdiff(unique(deps$Package), "R")
lapply(pkgs, citation)
```

(or you can use @jcolomb's code if you want to cite every dependency too)

And it doesn't feel that closely aligned with the core purpose of renv, so I'm closing this issue.

**Comment by andyatsenversa** [comment]
if you want to generate a bib file, you can use `bibtex::write.bib`
```{r}
deps <- renv::dependencies()
pkgs <- setdiff(unique(deps$Package), "R")
bibtex::write.bib(entry = pkgs, file = "reference/references_libs.bib", append = FALSE)
```
