### ISSUE TITLE
generate lockfile from DESCRIPTION + (environment)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#341]
Something like:

```R
renv::resolve(packages, remotes, ..., project)
```

which would generate a lockfile `renv.lock`.

- `packages`: The packages to resolve. When `NULL`, draw the packages as declared in the project `DESCRIPTION` file (if any).
- `remotes`: Remote specifications, giving requirements around package versions.

When `packages` is NULL or empty, the dependency list is drawn from the project's DESCRIPTION file.

**Comment by pat-s** [comment]
I wanted to open an issue asking if `hydrate()` could gain the ability to look for a Remotes: field in DESC which lists packages which require dev versions. Seems this is already on the list 👍

**Comment by hadley** [comment]
This is now `checkout()` with explicit snapshot type.
