### ISSUE TITLE
Global .Rprofile which requires a package 

### ISSUE THREAD

**Issue by smingerson** [rstudio/renv#343]
I'm interested in settings `options(rlang::entrace)` in my global .Rprofile. For a project using renv, this will error if rlang isn't in the project library. That's the correct thing to do. 

Next, I install rlang in the project library. I restart R, my .Rprofile still has `options(error = rlang::entrace)`, yet `getOption("error")` returns `NULL`. The expected behavior is to return a call to `rlang::entrace`. 

The weird thing is that all my even though the error option isn't set, all my other options defined in .Rprofile are.

# How to reproduce

Create a new project. Run `renv::init()`. Set `RENV_CONFIG_USER_PROFILE=TRUE` in .Renviron. Add `options(error = rlang::entrace)` to global .Rprofile, along with another option, such as `options(digits = 10)`, to verify the .Rprofile is being run. 

Restart R, receive an error because rlang is not installed. Install rlang into the project, restart R. `getOption('error')` returns `NULL`.

If you run `renv::deactive()`, we'll get the expected return value of `getOption("error")`. 
# session info
Using the latest from Github, 57eb5398 (0.9.3-6)

**Comment by smingerson** [comment]
This isn't limited to `rlang::entrace`, the same thing happens setting `options(error = Sys.time)`

**Comment by kevinushey** [comment]
Thanks for the bug report! I can reproduce this behavior; I'll take a look.

**Comment by kevinushey** [comment]
Should be resolved in master now -- `renv` was erroneously setting and restoring its own error handler while trying to load the user profile. Thanks again for reporting! Please re-open if you're still having any trouble.
