### ISSUE TITLE
renv make building package painful: helper functions to improve and better documentation for workaround ?

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#345]
Following https://github.com/rstudio/renv/issues/230#issuecomment-549228089, I think this documented point is still really painful as user experience: 
https://rstudio.github.io/renv/articles/packages.html#r-cmd-build-and-the-project-library
> By default, when building a package tarball, R will copy all files within the package directory to a temporary build directory before building the package. Unfortunately, this also implies copying the renv library. When that library is large, this can dramatically increase the amount of time it takes to build your package.
This was already posted here also https://github.com/rstudio/renv/issues/245

To illustrate, I am working on a package for my company where without renv it takes **992ms** against more than **3min** as reported by `devtools::install()`

As a workaround to install a dev version, one can use `devtools::install(build = FALSE)` or `devtools::install(quick = TRUE)` that does not build. However, when this package will be build it will took some time. 

To follow the advice given in the documentation, do you think there could be room for some helpers functions and workflow to have a dev mode in renv in order to use a `~/.renv` folder for globally storing library for package developpement ? 

In Python, `virtualenvwrapper `does this by default. See [Location of Environments](https://virtualenvwrapper.readthedocs.io/en/latest/install.html#location-of-environments) with is `$HOME/.virtualenvs`. Then creating a new virtualenv for a project is done by `mkvirtualenv env1` and it will be created there by default. 

As development environment in R, I always found the [`devtools::dev_mode()`](https://devtools.r-lib.org/reference/dev_mode.html) interesting. Coupling this logic with `renv` project would be very nice for package development. 

Do you have any other feedback on using renv for package development  ?

I am thinking of helpers function to set up a dev mode use of renv, that would default to create a project library outside of the project in a global folder, using the package name in DESCRIPTION or a define renv project name that would be then store in renv files somewhere. 

I am willing to dig into this or prototype something if you this is useful or in your scope. 

What is your opinion on this ?

**Comment by kevinushey** [comment]
I agree this is worth solving in general. I even do something similar for `renv` itself here:

https://github.com/rstudio/renv/blob/77e387e607d47e7299c895c9786747bd6bc37ce0/.Renviron#L2

The main challenge is doing this in a CRAN-compliant way, as packages on CRAN should not write to the user's home directory without consent. So writing to `~/.renv` isn't something that `renv` should do by default.

We'd also want to make sure the mapping between a project and its library is stable, so projects would need to get some sort of unique, stable ID -- likely as some kind of file within the `renv` folder. Otherwise collisions could happen in a variety of ways.

**Comment by kevinushey** [comment]
I've now made a change to `renv` such that a unique project id is stored at `renv/project-id`. My intention is to use that when forming a unique library path "somewhere" that can be used when appropriate.

Questions are:

1. Where should that live by default? `~/.renv`? Somewhere in `renv::paths$root()`? As a sub-directory of the user library?

2. Should this be on by default, or opt-in? How should users opt-in?

It seems like the nicest way to enable this would be to have users set an environment variable, like:

```
RENV_PATHS_LIBRARY_ROOT = ~/.renv
```

and when that is set, `renv` forms library paths at `~/.renv/<id>/<platform>`. What do you think?

**Comment by cderv** [comment]
> Where should that live by default?

As a user, I think `~/.renv` is a good place. 
On windows, I already have some folders in `~` like from Python `.conda`, `.keras`, `.matplotlib`, from R 📦 `.TinyTex`, and from RStudio I think a `.R`. Having another one for `.renv` seems clear and fine to me. `devtools::dev_mode` defaults to `"~/R-dev"` and I always found this ok.  There are also other tools writing in `%USERPROFILE%` like `.vscode`, `.anaconda`, `.docker`, `.kube`, `.ssh` or `.yarn`. 
However, I understand that could not be the right place. If this is a folder that is not to be visited by the user maybe `renv::paths$root()` is enough and a good place to have all of renv stuff in the same place. I don't think going inside the R user library is a good thing to not mix up with R logic and configuration. 

> Should this be on by default, or opt-in? How should users opt-in?

As in my idea for this issue, I think this should be opt-in by the user. Having the renv project library inside the project seems clearer. I think it conflicts only during development and it closer for python user of virtualenv where venv are created locally. 
Now I see some advantages of having the project libraries centralized: 
* It does not conflict with R package development
* No risk to bundle the renv library in the deployment process, like in rsconnect deployment or when using Docker `COPY . /project` 
* Less potential conflicts with any future change in R that concerns the whole project dir.

About the way to opt_in, I think the easiest could be to set an option to activate centralized mode (like caching mechanism in a way). This would change the default `RENV_PATHS_LIBRARY_ROOT` from `file.path(project, "renv/library")` to `~/.renv` or `renv:::renv_paths_root()` and activate the use of the prefix with `id`. And if user wants to change the default globally, one could set `RENV_PATHS_LIBRARY_ROOT` globally with other renv paths configuration. 

Does it make sense ?

**Comment by kevinushey** [comment]
That makes sense to me. I'll also document this as part of the "package development with renv" vignette so that users know this is a way to go.

**Comment by kevinushey** [comment]
I've made this change and documented my recommendation here:

https://rstudio.github.io/renv/articles/packages.html#r-cmd-build-and-the-project-library

Let me know if this sounds sufficient, and feel free to re-open or file a new issue if you think I've missed anything.

**Comment by gorgitko** [comment]
Hello, I am still having issues with `devtools::build()` and `devtools::check()`:

```
> devtools::build()
✓  checking for file ‘/mnt/foibe3/Users/novotnyj/projects/bioinfocz/scdrake/DESCRIPTION’ ...
─  preparing ‘scdrake’: (504ms)
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
   # Bootstrapping renv 0.14.0 --------------------------------------------------
─  Downloading renv 0.14.0 ... OK (downloaded source)
─  Installing renv 0.14.0 ... Done!
─  Successfully installed and loaded renv 0.14.0.
   Warning message:
   could not load renv from project "/tmp/RtmpHU9ikB/Rbuild1214425acbeea/scdrake"; reloading previously-loaded renv 
─  installing *source* package ‘scdrake’ ...
   ** using staged installation
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
     there is no package called ‘drake’
   Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
   Execution halted
   ERROR: lazy loading failed for package ‘scdrake’
─  removing ‘/tmp/RtmpHU9ikB/Rinst121446c2ae561/scdrake’
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
E>   there is no package called ‘drake’
E> Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
E> Execution halted
E> ERROR: lazy loading failed for package ‘scdrake’
E> * removing ‘/tmp/RtmpHU9ikB/Rinst121446c2ae561/scdrake’
E>       -----------------------------------
E> ERROR: package installation failed
Type .Last.error.trace to see where the error occurred
```

I have followed the steps in <https://rstudio.github.io/renv/articles/packages.html#r-cmd-build-and-the-project-library>,
so this is how `.Rprofile` and `.Renviron` in the project directory look like:

`.Rprofile`:
```
source("renv/activate.R")
```

`.Renviron`:
```
RENV_PATHS_LIBRARY_ROOT="~/.renv/library"
```

Obviously, `renv` is working well in the project directory, but as you can see in the output from `devtools::build()`,
the `renv` library is not loaded in the package build temp directory:

```
   # Bootstrapping renv 0.14.0 --------------------------------------------------
─  Downloading renv 0.14.0 ... OK (downloaded source)
─  Installing renv 0.14.0 ... Done!
─  Successfully installed and loaded renv 0.14.0.
   Warning message:
   could not load renv from project "/tmp/RtmpHU9ikB/Rbuild1214425acbeea/scdrake"; reloading previously-loaded renv
```

It's like the `RENV_PATHS_LIBRARY_ROOT` is not used? I also get the same error when I use

```
devtools::check(env_vars = c(RENV_PATHS_LIBRARY_ROOT = "~/.renv/library", NOT_CRAN = "true"))
```

Thanks in advance for the help!

**Comment by gorgitko** [comment]
So, here is my dirty solution:

`.Rprofile` inside project's root:
```
if (Sys.getenv("R_BUILD_CHECK") != "TRUE") {
  source("renv/activate.R")
}
```

Now I can build or check the package with:

```
withr::with_envvar(
  c(R_BUILD_CHECK = "TRUE"),
  devtools::build()
)
```

This will prevent `renv` from activation during package building.

And at the same time, paths to `renv` libraries are still preserved in `R_LIBS_USER` environment variable,
which is inherited by child R process called by `devtools`:

```
> Sys.getenv("R_LIBS_USER")
[1] "/home/novotnyj/.renv/library/scdrake-bd9d9402/R-4.1/x86_64-pc-linux-gnu:/tmp/RtmpXKqaLL/renv-system-library"
```
