### ISSUE TITLE
Suggestion: Highlight renv::equip() in starter guides and documentation

### ISSUE THREAD

**Issue by Ljupch0** [rstudio/renv#346]
Hi Kevin, thanks for the great package.

I had several issues with compiling older package versions from source. The problem is exacerbated by the fact that once renv::restore() is stopped, the entire 30min+ package installation process begins anew.

As time progresses most people will be working with older package versions which CRAN will not keep as binaries. Could be useful to know about renv::equip() from the get go.

**Comment by kevinushey** [comment]
Was `renv::equip()` sufficient to get your system in a state where compilation would succeed?

Perhaps `renv` could warn or similar if it detects that packages will need to be compiled from sources, but the requisite libraries appear to not be available.

**Comment by Ljupch0** [comment]
In my case it was. Issuing such a warning before the process starts sounds great.

**Comment by kevinushey** [comment]
Good to hear! I'm going to keep this issue open as a reminder of myself to implement this (notify the user that they may want to call `renv::equip()` before restoring packages)

**Comment by hadley** [comment]
Related to #1264
