### ISSUE TITLE
troubleshooting renv::init()

### ISSUE THREAD

**Issue by adschwab1** [rstudio/renv#350]
New user to renv. I'm initializing a new project, and loading tidyverse, but when I run `renv::init()`, the lockfile is only showing renv. Further, when I run `renv::snapshot()` after loading a system library, the output shows 'The lockfile is already up to date'. Not sure if I'm missing something, but I cant seem to add anything to the lockfile or project library. Thank you for any assistance.

`renv::init()`
```
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- renv   [* -> 0.9.3]

```
`library(rpart)`
`renv::snapshot()`
```
* The lockfile is already up to date.

```

**Comment by kevinushey** [comment]
See https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile -- the most likely reason is because the package you're using isn't actually referenced in the source code of your project.

**Comment by adschwab1** [comment]
Got it! Thank you!
