### ISSUE TITLE
renv::scaffold does not include currently set repos?

### ISSUE THREAD

**Issue by matthijsvanderloos** [rstudio/renv#351]
Hi,

As part of an internal company package, I have included an[ RStudio project template](https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html) to easily create new projects according to our coding standards.

As part of creating a new project, I would also like to setup an `renv` project library and thought about using `renv::scaffold` for this. However, it seems that this function does not setup repositories (correctly):

From outside a project (I have set a secondary repository through the RStudio settings):

```R
> dput(getOption("repos"))
structure(c(CRAN = "https://cran.rstudio.com/", `cran-local` = "https://mycompany.com/cran-local/"
), RStudio = TRUE)
```

From within a newly-created project after using `renv::scaffold`:
```R
> dput(getOption("repos"))
c(CRAN = "https://cloud.r-project.org")
```

Do you have any suggestions, how I can ensure the repositories are set correctly?

**Comment by kevinushey** [comment]
In `renv`, the repositories are stored as part of the lockfile `renv.lock`. Unfortunately, `renv::scaffold()` doesn't write out any lockfile.

This seems like an oversight; I believe it should populate the project with a bare lockfile as well.

**Comment by kevinushey** [comment]
Thanks -- this has now been implemented as part of https://github.com/rstudio/renv/commit/6d6e79d2c67848ca172cd159bb9817baf3acc55d.

As an aside, if you're using the CRAN version of `renv`, you might be able to get by with:

```
renv::init(bare = TRUE)
```

This will also attempt to activate the associated project as well, which may not be what you want. A way around that would be to invoke that command in an R sub-process; e.g.

```
system("R -e 'renv::init(bare = TRUE)'")
```

**Comment by matthijsvanderloos** [comment]
> Thanks -- this has now been implemented as part of [6d6e79d](https://github.com/rstudio/renv/commit/6d6e79d2c67848ca172cd159bb9817baf3acc55d).
> 
Thank you!

> This will also attempt to activate the associated project as well, which may not be what you want. A way around that would be to invoke that command in an R sub-process; e.g.
> 
> ```
> system("R -e 'renv::init(bare = TRUE)'")
> ```

This is exactly what I tried as well, but this also does not set the repositories correctly? I.e., this results in:
```R
> getOption("repos")
                         CRAN 
"https://cloud.r-project.org" 
```
in the newly-created project.

**Comment by kevinushey** [comment]
The currently-set repositories are what enter the lockfile, so I guess the current repositories needs to be propagated to the sub-process (as otherwise the default is written out)

**Comment by matthijsvanderloos** [comment]
Ok, thanks! I will implement that.
