### ISSUE TITLE
Warn on missing dependencies / Auto-restore

### ISSUE THREAD

**Issue by holub008** [rstudio/renv#353]
Thank you for `renv`!

I created a [new project](https://github.com/holub008/robopico/tree/master/train) and deployed it on a clean machine with only base R installed. When I opened an R shell in the project root, it was great that the `renv` package auto-installed and the session started with correct library paths (as scripted in `renv/activate.R`). 

Given this, I was surprised that the project dependencies themselves weren't auto-installed. It took me a minute of digging around to realize this. Does an auto-hydrate feature play well with `renv`'s philosophy? If not, a warning or user directive may be valuable for first time users. e.g. "Missing dependencies detected! Run `renv::hydrate()` to install.", based on the outcome of `renv::status()`.

**Comment by kevinushey** [comment]
To be clear, `renv::hydrate()` is used to initialize a project, copying the same packages that are currently available in the default R libraries. For an existing project, it's more likely that you'd want to call `renv::restore()` to restore the packages as defined in the `renv.lock` lockfile.

We _could_ auto-restore, but I'd be worried that this could be annoying as `renv::restore()` may be slow if packages aren't already in the cache, and it could also be slow if many packages need to be installed (especially if they must be compiled from sources).

I agree that a compromise where we notify the user when the two are out-of-sync would be best.

**Comment by holub008** [comment]
Thanks for the clarification.

Agreed auto-restore could be slow, and moreover may be an unexpected action by `renv`, given the user's only action was starting a session.

I'll submit a PR for out of sync warning on session start, in case you're interested in adding.

**Comment by vspinu** [comment]
I think this should be a drop-in option. We use a Makefile driven workflow, so each time a team member clones a project we have to remember to first start the session and do `renv:restore()` manually before any other `make xyz`.

**Comment by vspinu** [comment]
To be more precise, I am talking about the auto-restore on bootstrap only, not for follow-up sessions.

**Comment by holub008** [comment]
@vspinu Maybe I don't understand your setup, but why couldn't `renv:restore` be part of an earlier make target?

To your point, though, I agree that having a user config for auto-restore would be nice. So far in my usage (primarily isolated experiments/analyses), I have never check out a fresh `renv` project and *not* wanted dependencies installed for me.

It's worth noting that various dependency management tools handle this differently. For example, pipenv does not auto-install on first run, but maven does (or at least has configs to).

**Comment by vspinu** [comment]
> Maybe I don't understand your setup, but why couldn't renv:restore be part of an earlier make target?

Because I don't want unconditional restore every time a session is restarted. If I understand the renv::restore logic correctly, if a users installed a package and didn't snapshot, it will get overwritten by automatic restore on next restart.

**Comment by slodge** [comment]
I think an option for auto-restore would be nice - just as an option to auto-snapshot is.

In our developer/user environments we already have auto-snapshot enabled - and I think we'd enable auto-restore similarly.

Possibly we'd even consider extending this to some sort of watcher system - something that watched when renv.lock changed (e.g. due to a git pull or branch checkout) and would auto-restore when that occurred.

**Comment by hadley** [comment]
I think renv could be more aggressive at recommending a `restore()` when you're bootstrapping a project (i.e. it has a lockfile, but no library). Currently you see something like this:

```
# Bootstrapping renv 0.17.3 --------------------------------------------------
* Downloading renv 0.17.3 ... OK (downloaded binary)
* Installing renv 0.17.3 ... Done!
* Successfully installed and loaded renv 0.17.3.
* Project '~/Desktop/renv-test' loaded. [renv 0.17.3]
* One or more packages recorded in the lockfile are not installed.
* Use `renv::status()` for more details.
```

At a minimum, this message should include advice to call `renv::restore()`, but I think it would make sense to prompt the user to restore (defaulting to yes).

**Comment by kevinushey** [comment]
We try to detect this here:

https://github.com/rstudio/renv/blob/40aa593527e828fe392df24f566427ba04d2961d/R/project.R#L289-L300

I suspect this is failing because we're also taking into account packages installed in the system library (e.g. MASS) which might be project dependencies but are technically available.

We could probably simplify this check, e.g. "warn if there's a lockfile with some recorded packages, but the project library contains either nothing or only `renv`".

**Comment by hadley** [comment]
It also feels like there's quite a lot of space spent giving the details of the renv install, which most people won't be that interested in:

```
# Bootstrapping renv 0.17.3 --------------------------------------------------
* Downloading renv 0.17.3 ... OK (downloaded binary)
* Installing renv 0.17.3 ... Done!
* Successfully installed and loaded renv 0.17.3.
```

And a confusing mix of `stderr` and `stdout`:

<img width="707" alt="Screenshot 2023-05-11 at 07 47 08" src="https://github.com/rstudio/renv/assets/4196/9aedc79a-73d1-41ba-b623-a0f6c2a59f3d">

**Comment by kevinushey** [comment]
We need to print some kind of progress information for the download + install since the session will be busy during that duration (otherwise the R session will just look "frozen")

**Comment by hadley** [comment]
@kevinushey yeah, but I think we could squeeze that onto one 1, instead of 4 😄

**Comment by kevinushey** [comment]
Here's the current display:

```
Bootstrapping renv 9b579e28c36e336cc25100ac42964ac57185420e:
* Downloading from GitHub ... OK
* Installing ... OK


* Project '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.PAcj5tug' loaded. [renv 9b579e28c36e336cc25100ac42964ac57185420e]
```

I think this could still be refined. Perhaps something like:

```
[!] renv is not available; an installation will be bootstrapped.
* Installing renv [rstudio/renv] ... OK
* Project '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.PAcj5tug' loaded. [renv abcd123]
```

Or, if we want to keep a header:

```
-- Bootstrapping renv [rstudio/renv] -------------------------------
* Installing renv ... OK (installed from GitHub)
* Project '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.PAcj5tug' loaded. [renv abcd123]
```

**Comment by hadley** [comment]
In the context of the motivating issue, I think it makes sense for the header to stay, so we can add a new header for auto-restore (since I think we now believe that's the right action if we detect the entire library is missing).

```
-- Bootstrapping renv [rstudio/renv] -------------------------------
* Installing renv ... OK (installed from GitHub)
* Project '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.PAcj5tug' loaded. [renv abcd123]

-- Restoring library ------------------------------------------------

# CRAN -----------------------------------------------------------------------
- lattice        [0.20-45 -> 0.21-8]
- MASS           [7.3-58.2 -> 7.3-60]
- Matrix         [1.5-3 -> 1.5-4.1]
- cli            [* -> 3.6.1]
- colorspace     [* -> 2.1-0]
- dplyr          [* -> 1.1.2]
...
```

Will need to figure out how to nest with the headers produced by `restore()`

**Comment by hadley** [comment]
Oooooh, that explains what I've been seeing on load. In that case, I definitely agree that we shouldn't auto-restore, but I do think we should give the user a prompt on load and/or maybe as a top-level task? I'd also like to think about the case where you `git pull` and get a new lockfile, where I think we should at least notify and maybe prompt (I'm just not sure what the experience of prompting from a top-level task will feel like).

**Comment by kevinushey** [comment]
> Oooooh, that explains what I've been seeing on load. In that case, I definitely agree that we shouldn't auto-restore, but I do think we should give the user a prompt on load and/or maybe as a top-level task? 

One thing we could consider is using something like:

```
setHook("rstudio.sessionInit", function(...) {
  # do some stuff
})
```

so that the relevant startup code is run only after RStudio has finished initialization. You can detect if you're running in RStudio in a .Rprofile with:

```
commandArgs()[[1]] == "RStudio"
```

**Comment by kevinushey** [comment]
I think this should now be better handled? It might be worth some manual testing both within and outside of RStudio to verify.
