### ISSUE TITLE
Allow 'source' to be specified for renv::restore()

### ISSUE THREAD

**Issue by combiz** [rstudio/renv#355]
For Docker images, it would be useful to generate separate layers for R packages from CRAN, Bioconductor, and github.  A `source` parameter for `renv::restore()` would be valuable for large builds (e.g. 300 packages) where a complete rebuild might otherwise be required from a single error (typically in a github package), e.g.

```
RUN R -e 'renv::restore(source = "CRAN")'
RUN R -e 'renv::restore(source = "Bioconductor")'
RUN R -e 'renv::restore(source = "GitHub")'
```

This would allow the relatively error-free packages to install first and be cached by Docker.  Any errors in the relatively more error-prone github packages then wouldn't require a complete rebuild and would accelerate troubleshooting.

**Comment by evasgit** [comment]
@combiz @kevinushey hi, it is an important feature!!! and... if an error happened, the all installed packages(from renv::restore) will be deleted.(renv 0.9.3-40)

**Comment by kevinushey** [comment]
This is intentional. By default, `renv::restore()` should either:

1. Fail, and leave your library in the state it was in pre-restore, or
2. Succeed, and now give you a library matching the requested restore.

This is called a 'staged install' in `renv` parlance, and can be configured if so desired:

https://github.com/rstudio/renv/blob/18d1169f04370d37021fce7dbc188bd256ecde22/R/config.R#L86-L93

If you prefer the 'fail forward' approach, disabling that option should help.

**Comment by kevinushey** [comment]
I ultimately don't think specifying `source` is a good idea (since packages can have cross-source dependencies) so this will not be implemented.

I'm open to alternate suggestions on how to make this go a bit more smoothly when errors occur.

**Comment by combiz** [comment]
Thanks for the info. re: staged install.  That's a useful feature.  For a Docker container, I conclude that a staged or non-staged `renv::restore()` fail will both result in a docker build fail and cause the `renv::restore()` layer to restart from scratch on the next build -- is that right?

If the idea of a series of partial restores using `source` doesn't fly, then as an alternative approach -- consistent with the aforementioned all or nothing philosophy of `renv::restore()` -- perhaps the order of packages restored could be adjusted to prioritize first building the more error-prone GitHub packages?  This would at least allow the 'restore' failure to occur early?

**Comment by kevinushey** [comment]
One solution would be to use the `packages` argument; e.g.

```
renv::restore(packages = c("my", "cran", "packages"))
renv::restore(packages = c("my", "github", "packages"))
renv::restore()  # make sure anything that was missed gets restored now
```

That is, you could use multiple `restore()` calls, each specifically requesting the installation of some subset of packages in the lockfile. Do you think that would help?

**Comment by combiz** [comment]
Yes!  Perfect.. as the `renv.lock` JSON itself can be (presumably) easily parsed in R to retrieve package names for each 'source', this would provide the needed functionality.  Thank you.
