### ISSUE TITLE
Python packages used via reticulate are returned as dependencies

### ISSUE THREAD

**Issue by jdblischak** [rstudio/renv#359]
## What I observed

When I run `dependencies()` on a project that imports Python packages with reticulate, the Python packages are returned.

## What I expected

I expected that `dependencies()` would only return R packages. And if it returned more than R packages, there would be a column distinguishing which packages belong to which language.

## Reproducible example

The example below reproduces the observed behavior. I ran it with the latest development version available on GitHub.

``` r
d <- tempfile()
dir.create(d)
f <- file.path(d, "script.R")
writeLines(c(
  "library(reticulate)",
  "pytime <- import(\"time\")",
  "pytime$time()"
  ), con = f)
packageVersion("renv")
#> [1] '0.9.3.43'
renv::dependencies(d)
#> Finding R package dependencies ... Done!
#>                                      Source    Package Require Version   Dev
#> 1 /tmp/RtmputHNtU/file260815a5233f/script.R reticulate                 FALSE
#> 2 /tmp/RtmputHNtU/file260815a5233f/script.R       time                 FALSE
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

<details>

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Ubuntu 18.04.4 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2020-03-03                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                       
#>  assertthat    0.2.1      2019-03-21 [3] CRAN (R 3.5.3)               
#>  cli           2.0.2      2020-02-28 [3] CRAN (R 3.6.3)               
#>  crayon        1.3.4      2017-09-16 [3] CRAN (R 3.5.0)               
#>  digest        0.6.25     2020-02-23 [3] CRAN (R 3.6.3)               
#>  evaluate      0.14       2019-05-28 [3] CRAN (R 3.6.0)               
#>  fansi         0.4.1      2020-01-08 [3] CRAN (R 3.6.2)               
#>  fs            1.3.1.9000 2020-01-08 [1] Github (r-lib/fs@2fb543e)    
#>  glue          1.3.1      2019-03-12 [3] CRAN (R 3.5.3)               
#>  highr         0.8        2019-03-20 [3] CRAN (R 3.5.3)               
#>  htmltools     0.4.0      2019-10-04 [3] CRAN (R 3.6.1)               
#>  knitr         1.28       2020-02-06 [3] CRAN (R 3.6.2)               
#>  magrittr      1.5        2014-11-22 [3] CRAN (R 3.5.0)               
#>  Rcpp          1.0.3      2019-11-08 [3] CRAN (R 3.6.1)               
#>  renv          0.9.3-43   2020-03-03 [1] Github (rstudio/renv@a9b26ad)
#>  reprex        0.3.0.9000 2019-07-19 [1] local                        
#>  rlang         0.4.4      2020-01-28 [3] CRAN (R 3.6.2)               
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.2)               
#>  sessioninfo   1.1.1      2018-11-05 [3] CRAN (R 3.5.1)               
#>  stringi       1.4.6      2020-02-17 [3] CRAN (R 3.6.2)               
#>  stringr       1.4.0      2019-02-10 [3] CRAN (R 3.5.2)               
#>  withr         2.1.2      2018-03-15 [3] CRAN (R 3.5.0)               
#>  xfun          0.11       2019-11-12 [3] CRAN (R 3.6.1)               
#>  yaml          2.2.1      2020-02-01 [3] CRAN (R 3.6.2)               
#> 
#> [1] /home/jdb-work/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

## Investigation

I think this behavior was introduced in renv version [0.9.0](https://github.com/rstudio/renv/blob/master/NEWS.md#renv-090) via PR #238 to support R modules (#235), which use `import()` to load R packages. To support this, I confirmed that Python packages are returned in version 0.9.0, but not in version 0.8.3.

For the the upcoming [Chicago R Collaborative](https://chircollab.github.io/), we are looking for open source R projects to work on. Would this issue be something a contributor could address?

**Comment by kevinushey** [comment]
You're exactly right. Doh!

> For the the upcoming Chicago R Collaborative, we are looking for open source R projects to work on. Would this issue be something a contributor could address?

I wanted to get this fixed ASAP since I expect a number of users working with `reticulate` + `renv` together so I've made the fix already on master. That said, I'd love to see some extra community contributions to `renv`; let me take a look and see if there's something similar that might be appropriate.

**Comment by kevinushey** [comment]
In particular, I'd like to learn a bit more about:

1. How R users are using `renv` (or wish they could use `renv`),
2. `renv` behaviors that are surprising or sub-optimal in some way,
3. Errors or traps that users fall into while using `renv` that are hard to recover from or hard to understand.

One of the biggest challenges for me in building `renv` is that I find different users often have very different expectations on what the right "default" behavior for `renv` should be. To that end, I've tried to choose what I believe are the "best" or at least "safest" defaults but I'm sure I've gotten some of these wrong.

**Comment by jdblischak** [comment]
@kevinushey Thanks for the quick fix!

Also, I've opened an Issue for the Collaborative to encourage more people to try renv with their projects: https://github.com/chircollab/chircollab20/issues/24
