### ISSUE TITLE
Can't install from local repo

### ISSUE THREAD

**Issue by birnbera** [rstudio/renv#360]
I'm trying to install a package from a local git repository into a new `renv` environment. The package works fine using `devtools` and in fact uses `renv` to manage its own development dependencies.

I'm trying to install the package into a new environment using `renv::install("~/path/to/package_repo")`. It starts installing all of the dependencies:

```
Retrieving 'https://cran.rstudio.com/src/contrib/dplyr_0.8.4.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/rlang_0.4.5.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/cli_2.0.2.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/vctrs_0.2.3.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/digest_0.6.25.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/tidyselect_1.0.0.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/plogr_0.2.0.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/tidyr_1.0.2.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/<MY_PACKAGE>/<MY_PACKAGE>.tar.gz' ...
Error: failed to retrieve package '<MY_PACKAGE>'
In addition: Warning messages:
1: In system2("curl", args$data(), stdout = TRUE, stderr = TRUE) :
  running command ''curl' --config '/private/var/folders/tz/plclckxj0bn73zrfbxk9km1m0000gp/T/Rtmp6fyTxF/renv-tempdir-b41c2ddaa8bb/renv-download-config-b41c533b7ae6' 2>&1' had status 22
2: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 Not Found
3: In system2("curl", args$data(), stdout = TRUE, stderr = TRUE) :
  running command ''curl' --config '/private/var/folders/tz/plclckxj0bn73zrfbxk9km1m0000gp/T/Rtmp6fyTxF/renv-tempdir-b41c2ddaa8bb/renv-download-config-b41c7c0d8ba7' 2>&1' had status 22
4: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 Not Found
```

I'm not sure why it's trying to get the package itself from CRAN. It's not listed as a dependency anywhere and it is the package I'm trying to install from a local repo, so it shouldn't need find it from CRAN.

I've had lots of issues in the past installing packages from sources besides CRAN (e.g. a remote bitbucket server, etc.). According to the docs, `renv` is using `remotes` under the hood, but as far as I can tell it's not passing things to `remotes` correctly as I am able to install with `remotes`, but not `renv`.

Any assistance would really help. Thanks!

**Comment by kevinushey** [comment]
What is your package called? Can you share its sources publicly?

Unfortunately, it's hard for me to say what's going on without a reproducible example.

**Comment by kevinushey** [comment]
Sorry, but without a reproducible example I cannot help further. Please feel free to re-open if you can provide more details.
