### ISSUE TITLE
renv losing system packages

### ISSUE THREAD

**Issue by smingerson** [rstudio/renv#361]
I don't have a reproducible example (yet), but I wanted to put this on your radar. It has happened to me a couple times now. It seems to happen when I'm browsing through documentation. I do something like `?grepl` and RStudio can't find the help file. It then vomits a bunch of warnings at me:

```
1: In read.dcf(file.path(p, "DESCRIPTION"), c("Package",  ... :
  cannot open compressed file 'C:/Users/Sean.Ingerson/AppData/Local/Temp/RtmpEnFhNF/renv-system-library/compiler/DESCRIPTION', probable reason 'No such file or directory'
# Several more warnings in the same vein
7: In find.package(if (is.null(package)) loadedNamespaces() else package,  ... :
  there is no package called ‘compiler’
# Several more warnings in the same vein
```

renv: 0.9.3 from CRAN
R: 3.6.3
RStudio: 1.3.880 
```
# packageDescription('stats')
# [1] NA
# Warning message:
# In packageDescription("stats") :
#  DESCRIPTION file of package 'stats' is missing or broken
```
```
.libPaths()
# [1] "S:/Projects/MyProject/renv/library/R-3.6/x86_64-w64-mingw32" "C:/Users/Sean.Ingerson/AppData/Local/Temp/RtmpEnFhNF/renv-system-library"
```
The system library given is empty. Restarting my R session fixes the problem.

**Comment by smingerson** [comment]
I don't think I do. The system library path exists, it is just empty. If I go up one level, that directory has files. I will try the setting and see if that fixes the problem.

**Comment by kevinushey** [comment]
`renv` now re-generates its system sandbox if it detects that it was deleted.
