### ISSUE TITLE
Renv and docker buildkit caching?

### ISSUE THREAD

**Issue by jameshowison** [rstudio/renv#362]
Longer thread here: https://community.rstudio.com/t/docker-buildkit-cache-package-build-and-install/46839/3

In short: is there an approach to using renv with docker that:
- makes the docker container self-contained (ie not dependent on mounting the renv library as a volume)
- works with the fairly new docker buildkit approach (buildx) (which, if I understand correctly creates a docker container for doing the builds, so a package cache can exist on the building container).

**Comment by kevinushey** [comment]
Does the Docker vignette help here?

https://rstudio.github.io/renv/articles/docker.html#creating-docker-images-with-renv

If I understand correctly, the solution here is to ensure `renv::restore()` is called in the Dockerfile, as that will ensure packages are installed directly into the image.

You can also disable the `renv` global cache by setting the environment variable:

```
RENV_CONFIG_USE_CACHE = FALSE
```

as documented in `?config`.

**Comment by jameshowison** [comment]
It does help, I haven't had a chance to hack on this.  I think the issue is that buildkit expects the cache to be on the special docker container/volume being used for building, but these instructions expect the cache to be on the host machine.

The end goal (and the way it works with apt-get and pypy) is to have a list of packages in a Dockerfile, then to cache the intermediate build results so that adding a single package to the line results in a docker build that is quick.  ie Docker notices that the line has changed and so goes to rebuild that layer. Without buildkit everything in that docker layer had to be rebuilt from scratch, which mean that people added line after line of new installs. But buildkit is able to do it quickly because it find the cache.

**Comment by kevinushey** [comment]
> It does help, I haven't had a chance to hack on this. I think the issue is that buildkit expects the cache to be on the special docker container/volume being used for building, but these instructions expect the cache to be on the host machine.

The vignette described both versions -- the first section describes building an image using `renv` with installed packages baked directly into the image, and the second describes the second version with an external mounted cache.

> The end goal (and the way it works with apt-get and pypy) is to have a list of packages in a Dockerfile, then to cache the intermediate build results so that adding a single package to the line results in a docker build that is quick. ie Docker notices that the line has changed and so goes to rebuild that layer. Without buildkit everything in that docker layer had to be rebuilt from scratch, which mean that people added line after line of new installs. But buildkit is able to do it quickly because it find the cache.

I think one challenge here is that `renv` normally installs packages in a single call, e.g. a plain old

```
renv::restore()
```

so if you want to have a separate line for each package in your Dockerfile that will require some more work.

**Comment by jameshowison** [comment]
No way to use the `install2.r` approach used by rocker in a way that could benefit from renv?

https://stackoverflow.com/questions/45289764/install-r-packages-using-docker-file

**Comment by shibahead** [comment]
Are these repositories a solution to this problem?

- Avoid rebuilding R packages adding a single package to a docker image
https://github.com/howisonlab/test_repo_buildx_renv

- renv-docker
https://github.com/robertdj/renv-docker
> My solution in this repository is to create two Docker images:
> The "install image": The first image consists only of the prerequisites for the projects. When running a container from this image it can install R packages in the format it needs inside the container and save them to {renv}'s cache on the host through a mount.
> The "final image": The second image copies the project along with dependencies from the host into the image.
