### ISSUE TITLE
better heuristics in RSPM detection?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#365]
Right now, `renv` attempts to automatically detect RSPM repository URLs, and transform source URLs to binary URLs on Linux as appropriate. However, I'm not sure if `renv` can do this automagically and always correctly.

The main challenge here is, given a repository URL, `renv` needs to try and determine if it refers to an RSPM repository. There are some heuristics:

- Does this have the format `<url>/<name>/<id>`? If so, we might be able to infer this is RSPM. Can we expect that all RSPM URLs will have this format? Do we need to worry about proxies that subvert this format in some way?

- Does that repository respond to the `<url>/__api__/status` endpoint? (Note: this also runs into issues with proxies subverting the format above)

Ultimately though, it seems like if we can't get this right all the time then users might need some way of telling `renv` that "yes, you should treat this like an RSPM repository".

@slopp, what are your thoughts?

**Comment by slopp** [comment]
sorry I missed this @kevinushey , I think we explored further through a related RSPM issue, right? I liked the idea of using the header

**Comment by kevinushey** [comment]
Indeed, that's where we landed. I'll plan on making use of that once it's part of the next RSPM release.

**Comment by hadley** [comment]
Judging by `renv_ppm_status_impl()`, we're now checking for a PPM with a API call.
