### ISSUE TITLE
Collaborating with renv: init() vs restore()

### ISSUE THREAD

**Issue by jl5000** [rstudio/renv#366]
Within the 'Collaborating with renv' article, it briefly mentions using either init() or restore() to automatically install all required packages. Please could the article clarify whether there is a difference in behaviour in this situation. For example, if calling init(), will renv regenerate the infrastructure? (This is precisely what I don't want since I've added to the project .Rprofile file and I don't want it overwritten by a re-initialisation).

**Comment by kevinushey** [comment]
`renv::init()` should prompt you and ask what behavior you want in that case (restore from lockfile versus re-initialize the project).

That said, this is indeed a common point of confusion and I'll try to further clarify this in the article.

**Comment by daniel-conn17** [comment]
I've been trying to develop a workflow for my lab group based on the article "Collaborating with renv."  In my early testing, I've been trying to start a project on one computer than duplicate it on a second computer.  When I transfer the renv.lock file to the second computer and run renv::init(), the required renv folders and files are created.  But, when try to run the source code in the project, I get errors about the packages not being found.  

For example:
"Error in library(randomForest) : 
  there is no package called ‘randomForest’."

Running renv::restore fixes the issue.  Is this a bug?  Or is renv::init followed by renv::restore what you intend users to type?

**Comment by kevinushey** [comment]
That should work. For example:

```
$ tail -n+1 *
==> renv.lock <==
{
  "R": {
    "Version": "4.0.0",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Packages": {
    "digest": {
      "Package": "digest",
      "Version": "0.6.25",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f697db7d92b7028c4b3436e9603fb636"
    },
    "renv": {
      "Package": "renv",
      "Version": "0.10.0",
      "Source": "Repository"
    }
  }
}

==> script.R <==
library(digest)
```

If I try to call `renv::init()` and then source the associated script, I see:

```
$ R

R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> renv::init()
* Restoring project ...
The following package(s) will be updated:

# CRAN ===============================
- digest   [* -> 0.6.25]

# Repository =========================
- renv     [* -> 0.10.0]

Installing digest [0.6.25] ...
        OK (linked cache)
Installing renv [0.10.0] ...
        OK (linked cache)
The following package(s) have been updated:

        renv [installed version 0.10.0 != loaded version 0.10.0-2]

Consider restarting the R session and loading the newly-installed packages.

* Project '~/scratch/za' loaded. [renv 0.10.0]
source("* renv activated -- please restart the R session.
> source("script.R")  # succeeds, quietly
```

**Comment by d-sci** [comment]
In recent experimentation with my team, I've found the following to be the best way to collaborate:

1. **One person** installs renv and runs `renv::init`, **once**
2. They make sure that `renv/activate.R` and `.Rprofile` (with the call to source the former) are checked into vcs
3. No one else has to do anything to set up infrastructure, including even installing `renv` in their normal library. Rely on the .Rprofile and the activate script.
4. After loading, everyone can run `renv::restore()` as often as they'd like

The alternative option we played with involved  _not_ checking in the Rprofile and having everyone call `renv::init`, but the main problem with this was that it means they had to have renv installed already, and they might have had different versions (you can't lock the version via renv until you've initialized renv!). Which means that everyone's call to `renv::init` could create a different `renv/activate.R` script and we lose some of the consistency.

Relying on the .Rprofile/activation script and then just running `renv::restore()` also seems to work for our CI / Dockerized environments. 

This collaboration method was gleaned primarily from the ["Infrastructure" section of the "Getting started" vignette](https://rstudio.github.io/renv/articles/renv.html#infrastructure), and I did find it somewhat confusingly out-of-sync with the ["collaborating" vignette](https://rstudio.github.io/renv/articles/collaborating.html), which repeatedly references calling `renv::init` on each machine.

**Comment by kevinushey** [comment]
Thanks @d-sci! I think I will update the collaborating vignette to encourage the style of collaboration that you've had success with.

**Comment by hadley** [comment]
Looks like this is what's shown in https://rstudio.github.io/renv/articles/collaborating.html
