### ISSUE TITLE
Renv is putting the system library in /tmp on linux

### ISSUE THREAD

**Issue by ColeWunderlich** [rstudio/renv#368]
When using renv on linux with `use.cache=F`,  the `renv-system-library` is being installed in the `tmp` directory ie. `/tmp/Rtmp*/renv-system-library`.

I am not sure if this is intended or is a potential issue.

A call to `.libPaths()` after loading the project yields the following 
```
[1] "/path/to/project/renv/library/R-3.6/x86_64-pc-linux-gnu"
[2] "/tmp/RtmpXCscJx/renv-system-library"    
```

**Comment by kevinushey** [comment]
This is expected. What you're seeing is the so-called `renv` sandbox, whereby system packages are linked into a 'safe' system library. This is independent of the global cache.

If you want to disable this behavior, you can set e.g.

```
RENV_CONFIG_SANDBOX_ENABLED = FALSE
```

See `?config` for more details.

**Comment by ColeWunderlich** [comment]
Ok, thanks!  Good to know.
