### ISSUE TITLE
hex logo?

### ISSUE THREAD

**Issue by ginolhac** [rstudio/renv#369]
Hello,

thanks for a fantastic package! it really solves the isolation env. Using Artem (renv gitlab-CI) and Noam(drake gitlab-CI) examples, I have a `drake` workflow with `renv` working in dind and gitlab-CI. Works perfectly, thanks again!

My only question: do you plan to have a hex logo for `renv`?

**Comment by kevinushey** [comment]
Yes! We are planning to put one together soon :-)

**Comment by ginolhac** [comment]
thanks a lot!
