### ISSUE TITLE
renv::init() have no permmison to create dir

### ISSUE THREAD

**Issue by sixvable** [rstudio/renv#370]
I create a new project using RStudio and then try to initialize with renv::init()
`> renv::init()`

Welcome to renv! It looks like this is your first time using renv.
This is a one-time message, briefly describing some of renv's functionality.
This package maintains a local cache of data on the filesystem at:
- "C:/Users/98611/AppData/Local/renv"
This path can be customized -- see the documentation in `?paths`.
renv will also write to files within the active project folder, including:
 - A folder 'renv' in the project directory, and
 - A lockfile called 'renv.lock' in the project directory.
In particular, projects using renv will normally use a private, per-project
R library, in which new packages will be installed. This project library is
isolated from other R libraries on your system.
In addition, renv will attempt to update files within your project, including:
- .gitignore
- .Rbuildignore
- .Rprofile
Please read the introduction vignette with `vignette("renv")` for more information.
You can also browse the package documentation online at http://rstudio.github.io/renv.
By providing consent, you will allow renv to write and update these files.
Do you want to proceed? [y/N]: y
* "C:/Users/98611/AppData/Local/renv" has been created.
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
The following package(s) will be updated in the lockfile:
CRAN ===============================
- renv   [* -> 0.9.3]
* Lockfile written to 'D:/test/renv.lock'.
**Warning message:
In dir.create(tempPath, recursive = TRUE) :
  cannot create dir 'D:\', reason 'Permission denied'**
Restarting R session...
[1] "English_United States.1252"
* Project 'D:/test' loaded. [renv 0.9.3]

**Comment by kevinushey** [comment]
What version of RStudio are you using?

**Comment by sixvable** [comment]
> What version of RStudio are you using?

RStudio desktop 1.2.5033,the lastest version

**Comment by kevinushey** [comment]
What is the output of `.Call("rs_profilesPath")` on your machine? It seems like this is an RStudio issue as opposed to an `renv` issue.

**Comment by kevinushey** [comment]
It also seems like `renv` initialized without issue, despite the warning.

**Comment by sixvable** [comment]
> What is the output of `.Call("rs_profilesPath")` on your machine? It seems like this is an RStudio issue as opposed to an `renv` issue.

I think you are right it is a RStudio issue. 
The output of `.Call("rs_profilesPath")` is the same error.
So if I init  within an existing project created by RStudio I get this error, but if I init with `renv::init(project="path/to/new/project")` it seems fine right now.
Thank you @kevinushey for helping me figure out.
