### ISSUE TITLE
Installing Bioconductor packages

### ISSUE THREAD

**Issue by llrs** [rstudio/renv#371]
I copied a project to one computer to another one (I didn't copy the `{renv}` cache). In this different computer I can't seem to install packages from Bioconductor well with `BiocManager::install("BH")`. The installation finish with the uninformative error:

```
ERROR: unable to create ‘projects/design_ngs/renv/library/R-3.6/x86_64-pc-linux-gnu/BH’
# ...
ERROR: unable to create ‘projects/design_ngs/renv/library/R-3.6/x86_64-pc-linux-gnu/GO.db’
```

As you can see it happens with both Bioconductor packages and packages that are on CRAN. It seems like it cannot install CRAN packages, because if I install the dependencies manually via `install.packages` then I can install the Bioconductor packages.

**Comment by kevinushey** [comment]
I guess the question is why that error is occurring:

> ERROR: unable to create ‘projects/design_ngs/renv/library/R-3.6/x86_64-pc-linux-gnu/BH’

Most likely it would imply some sort of permissions issue, but it's hard for me to know without more information.

**Comment by llrs** [comment]
What kind of information do you need (what should I look at) ? It has permissions to write to the /renv/* folders.

**Comment by kevinushey** [comment]
Are you able to create those directories "by hand"? What happens if you run:

```
dir.create("projects/design_ngs/renv/library/R-3.6/x86_64-pc-linux-gnu/BH", recursive = TRUE)
```

**Comment by llrs** [comment]
Yes, I am able to create a directory that way (I installed the BH package with just `install.packages` so instead I created another directory named BT).

**Comment by kevinushey** [comment]
Sorry, but without a reproducible example there is not much I can do.

**Comment by llrs** [comment]
I would provide a reproducible example if I could. But currently my only idea is giving you the whole project. Are you willing to accept and look into a project? 

Perhaps there is another way to make it reproducible. What do you think I need to provide a reproducible example my whole directory?
