### ISSUE TITLE
Use of renv without .Rprofile on startup

### ISSUE THREAD

**Issue by ColeWunderlich** [rstudio/renv#373]
I am using renv in a cluster environment and as a result want to find a way to have `renv` bootstrap itself without the use of a `.Rprofile` file since the initialization of R will not be occurring in the project directory nor will it always be by the same user.

So far my solution has been to call either `renv::activate("/path/to/renv/lib")` or `renv::load("/path/to/renv/lib")` at the beginning of the script that is using the `renv` library.  I worry though that doing this after R's normal startup process (where default packages are attached) might cause some issues with system versions of packages being loaded  during startup rather than the`renv` library version of those packages.

Is there a better way to do this, or does `renv` really need to be loaded via `.Rprofile` in order to function appropriately?

**Comment by kevinushey** [comment]
The job of the `renv` autoloader is basically to:

1. Ensure the correct version of `renv` is installed and loaded;
2. Call `renv::load()`.

If you can do (1) yourself, then you can just explicitly call `renv::load("path/to/project")`.

> I worry though that doing this after R's normal startup process (where default packages are attached) might cause some issues with system versions of packages being loaded during startup rather than therenv library version of those packages.

This is indeed the challenge with doing it yourself. If you want to go this route, the onus is on you to try and ensure that packages aren't loaded from separate library paths beforehand. That said, `renv` uses the system library paths as-is (or optionally with a sandbox which is basically just a "safe" system library path) so as long as you aren't explicitly loading certain packages from e.g. the user library you should be fine.

**Comment by kevinushey** [comment]
I believe this should answer your question adequately; feel free to re-open or file a new issue if you still have questions.
