### ISSUE TITLE
Can't install package from source, the 'cannot open file 'renv/activate.R': No such file or directory' error

### ISSUE THREAD

**Issue by sdcharle** [rstudio/renv#374]
Hello, I realize this is LIKE issue #310, #297 and #197 but none of the recommendations there worked.

I have a project, we are using renv_0.9.3, we want to use udpipe but I have to use a more recent version of the compiler for certain functionality to work.

I did this on a box yesterday and all was fine, doing it today, keep running into this. I try:

install.packages('udpipe', type = 'source')

Installing package into ‘/home/scharlesworth/serviceticketanalysis/renv/library/R-3.6/x86_64-redhat-linux-gnu’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/udpipe_0.8.3.tar.gz'
Content type 'application/x-gzip' length 4750855 bytes (4.5 MB)
==================================================
downloaded 4.5 MB

.
.
.
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory

**Comment by sdcharle** [comment]
Ugh, issue was an incorrect '~/.Rprofile' which when fixed works. There's a reason renv tells you not to run renv::init() in the home directory...

**Comment by Bio-data-tricks** [comment]
Hi, I have the same problem, how can I solve it? I have reinstalled python, anaconda several times, but I still have this problem... Thanks 
Nico

**Comment by lofung** [comment]
i never used the function ````renv::init()```` and there is always the same problem.
