### ISSUE TITLE
Autosnapshot cant be disabled

### ISSUE THREAD

**Issue by sixvable** [rstudio/renv#375]
I have tried all the way to disabled auto.snapshot but it doesn't work.
I tried tree ways:

set `options(renv.config.auto.snapshot = FALSE)` or `Sys.setenv(RENV_CONFIG_AUTO_SNAPSHOT = FALSE)` in an `renv::init()` project
switch to the project using RStudio ,set `options(renv.config.auto.snapshot = FALSE)` or `Sys.setenv(RENV_CONFIG_AUTO_SNAPSHOT = FALSE)` before activating `renv::activate()` environment
set `options(renv.config.auto.snapshot = FALSE)` or `Sys.setenv(RENV_CONFIG_AUTO_SNAPSHOT = FALSE)` into the project 's .Rprofile()

Even `renv::diagnostics()` shows the key of the auto.snapshot is FALES it still snapshot autmatically whether `install.packages()` or `renv::install()`

**Comment by kevinushey** [comment]
Sorry, but I'm not able to reproduce:

```
> options(renv.config.auto.snapshot = FALSE)
> install.packages("digest")
Installing digest [0.6.25] ...
	OK (linked cache)
> options(renv.config.auto.snapshot = TRUE)
> install.packages("digest")
Installing digest [0.6.25] ...
	OK (linked cache)
* Lockfile written to '~/scratch/renvshot/renv.lock'.
```

Can you provide any more information?

**Comment by sixvable** [comment]
I am not really sure if `renv::snapshot()` works.
```
>renv::init(project="path/to/myproject")
Project 'D:/check' loaded. [renv 0.9.3]
```
_initalize a new project_
```
> renv::diagnostics()
Diagnostics Report -- renv [0.9.3]
# Session Info =======================
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=English_United States.1252        

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    renv_0.9.3    

# Project ============================
Project path: "D:/check"

# Status =============================
* The project is already synchronized with the lockfile.
```
Lockfile ===========================
**There are 1 package(s) recorded in the lockfile.
       _
  renv   [0.9.3]**
_only one package **renv** writen in the lockfile._
```
# Library ============================
The are 1 package(s) installed in the project library.
Library path: "D:/check/renv/library/R-3.6/x86_64-w64-mingw32"

# Dependencies =======================
              Source Package Require Version   Dev
1 D:/check/renv.lock    renv                 FALSE

# User Profile =======================
[no user profile detected]

# Settings ===========================
List of 6
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ snapshot.type            : chr "packrat"
 $ use.cache                : logi TRUE
 $ vcs.ignore.library       : logi TRUE

# Options ============================
List of 2
 $ renv.consent: logi TRUE
 $ renv.verbose: logi TRUE

# Environment Variables ==============
HOME                        = C:\Users\98611\Documents
LANG                        = en
R_LIBS                      = <NA>
R_LIBS_SITE                 = <NA>
R_LIBS_USER                 = D:/check/renv/library/R-3.6/x86_64-w64-mingw32;C:/Users/98611/AppData/Local/Temp/RtmpSu8mpX/renv-system-library
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = <NA>
RENV_DEFAULT_R_LIBS_USER    = C:/Users/98611/Documents/R/win-library/3.6
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = D:/check

# PATH ===============================
- D:\R\R-3.6.3\bin\x64
- C:\RBuildTools\3.5\bin
- C:\Rtools\bin
- C:\WINDOWS\system32
- C:\WINDOWS
- C:\WINDOWS\System32\Wbem
- C:\WINDOWS\System32\WindowsPowerShell\v1.0\
- C:\WINDOWS\System32\OpenSSH\
- F:\SPSS\JRE\bin
- F:\MEGA\MEGA-X
- F:\Bitvise Tunnelier
- F:\Git\Git\cmd
- C:\Users\98611\AppData\Local\Microsoft\WindowsApps
- C:\Users\98611\AppData\Roaming\TinyTeX\bin\win32

# Cache ==============================
There are a total of 0 package(s) installed in the renv cache.
Cache path: "C:/Users/98611/AppData/Local/renv/cache/v5/R-3.6/x86_64-w64-mingw32"
```
```
> options(renv.config.auto.snapshot = TRUE)
```
_make sure packaged installed be snapshoted._
```
> install.packages("digest")
Retrieving 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/3.6/digest_0.6.25.zip' ...
	OK [downloaded 243.7 Kb in 0.7 secs]
Installing digest [0.6.25] ...
	OK [installed binary]
```
**Lockfile written to 'D:/check/renv.lock'.**
_console shows it seems that package **digest** are writen into lockfile_
```
> renv::diagnostics()
Diagnostics Report -- renv [0.9.3]
==================================

# Session Info =======================
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=English_United States.1252        

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    renv_0.9.3    

# Project ============================
Project path: "D:/check"

# Status =============================
* The project is already synchronized with the lockfile.
```
Lockfile ===========================
**There are 1 package(s) recorded in the lockfile.
       _
  renv   [0.9.3]**
_still only package **renv**_
```
```
# Library ============================
The are 2 package(s) installed in the project library.
Library path: "D:/check/renv/library/R-3.6/x86_64-w64-mingw32"

# Dependencies =======================
              Source Package Require Version   Dev
1 D:/check/renv.lock    renv                 FALSE

# User Profile =======================
[no user profile detected]

# Settings ===========================
List of 6
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ snapshot.type            : chr "packrat"
 $ use.cache                : logi TRUE
 $ vcs.ignore.library       : logi TRUE

# Options ============================
List of 3
 $ renv.consent             : logi TRUE
 $ renv.config.auto.snapshot: logi TRUE
 $ renv.verbose             : logi TRUE

# Environment Variables ==============
HOME                        = C:\Users\98611\Documents
LANG                        = en
R_LIBS                      = <NA>
R_LIBS_SITE                 = <NA>
R_LIBS_USER                 = D:/check/renv/library/R-3.6/x86_64-w64-mingw32;C:/Users/98611/AppData/Local/Temp/RtmpSu8mpX/renv-system-library
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = <NA>
RENV_DEFAULT_R_LIBS_USER    = C:/Users/98611/Documents/R/win-library/3.6
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = D:/check

# PATH ===============================
- D:\R\R-3.6.3\bin\x64
- C:\RBuildTools\3.5\bin
- C:\Rtools\bin
- C:\WINDOWS\system32
- C:\WINDOWS
- C:\WINDOWS\System32\Wbem
- C:\WINDOWS\System32\WindowsPowerShell\v1.0\
- C:\WINDOWS\System32\OpenSSH\
- F:\SPSS\JRE\bin
- F:\MEGA\MEGA-X
- F:\Bitvise Tunnelier
- F:\Git\Git\cmd
- C:\Users\98611\AppData\Local\Microsoft\WindowsApps
- C:\Users\98611\AppData\Roaming\TinyTeX\bin\win32

# Cache ==============================
There are a total of 1 package(s) installed in the renv cache.
Cache path: "C:/Users/98611/AppData/Local/renv/cache/v5/R-3.6/x86_64-w64-mingw32"
```

**Comment by kevinushey** [comment]
Please see: https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile

Only packages which appear to be used in the project will enter the lockfile.

**Comment by sixvable** [comment]
> Please see: https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile
> 
> Only packages which appear to be used in the project will enter the lockfile.

got it. seems like really different from **packrat**
Thank you @kevinushey ,sorry to bother you.

**Comment by kevinushey** [comment]
No worries, I appreciate your feedback -- it definitely takes time to become familiar with some of the nuances of `renv`.
