### ISSUE TITLE
Q: I run into a lot of compilation issues, possible to install binaries of packages off MRAN?

### ISSUE THREAD

**Issue by Ljupch0** [rstudio/renv#377]
Hi Kevin, appreciate the work.

As I run into compilation errors even with `renv::equip()` (damn you igraph), is there some setting I can set that will download the package versions as binaries from MRAN and install them without any compilation?

I see double benefits - no nasty compilation errors and a faster `renv::restore()`.

What do you think?

**Comment by kevinushey** [comment]
Unfortunately, there isn't anything built-in yet. I'm thinking of putting something together so that `renv` can download binaries from MRAN when available, but this will take some more time.

**Comment by kevinushey** [comment]
This is now available in the development version of `renv`. For example:

```
> renv::install("stringi@1.4.4")
Retrieving 'https://mran.microsoft.com/snapshot/2020-02-19/bin/windows/contrib/3.6/stringi_1.4.4.zip' ...
	OK [file is up to date]
Installing stringi [1.4.4] ...
	OK [installed binary]
* Copying 'stringi' into the cache ... Done!
```

Please upgrade `renv` in your project with:

```
renv::upgrade(version = "master")
```

and let me know if things appear to work for you. Thanks!

**Comment by Ljupch0** [comment]
Great! I solved my current problem with some hacking, but as soon as I take code to another machine I'll use this!

**Comment by swt30** [comment]
I'm excited about this! Looks like the URL https://rstudio-buildtools.s3.amazonaws.com/renv/mran/packages.rds might not be publicly accessible though (access denied). I'm guessing it holds an index of MRAN packages?

**Comment by kevinushey** [comment]
@swt30 doh; thanks for catching that! This should be fixed up now; let me know if things appear to be working on your end.

**Comment by swt30** [comment]
I've had success with this now, though I had to switch to a different version of R (turns out if you build R from source, it won't install binaries).

**Comment by kevinushey** [comment]
My understanding is you need to set the `PLATFORM_PKGTYPE` definition during compilation to tell your copy of R to point at the right binary type:

https://github.com/wch/r-source/blob/917fb7d87d74eaed52d3ac74408b72ee47832bd8/src/main/platform.c#L287-L294

**Comment by Ljupch0** [comment]
Worked like a charm! Took 15 minutes vs 45 mins previously. No errors. Great work Kevin.  For me this can be closed.

**Comment by kevinushey** [comment]
Great news :-) Thanks for following up!
