### ISSUE TITLE
The following package(s) have broken symlinks into the cache:

### ISSUE THREAD

**Issue by statnmap** [rstudio/renv#378]
As I played a lot with the cache, I got this message:

```
The following package(s) have broken symlinks into the cache:
...
Consider re-installing these packages.
```

I did not see a function to retrieve broken symlinks packages so that I can install them without having to write the list manually.

This requires the following lines of code. Could you add this possibility to re-install automatically if symlinks are broken ?

```r
pkgs <- list.files(.libPaths()[1], full.names = TRUE)
broken <- which(!file.exists(pkgs))
if (length(broken) > 0) {
  renv::install(basename(pkgs)[broken])
}
```

**Comment by kevinushey** [comment]
That code won't necessarily do the correct thing, though. That will install the latest versions of packages from CRAN; it's perhaps more likely that a user would want to reinstall based on the package versions currently recorded in the lockfile.

(In theory, we could parse out the package + version based on the symlink into the cache as well)

**Comment by statnmap** [comment]
True. That would be something more ilke this, although github versions would be detected:

```r
# Explore packages dirs
# pkgs <- list.files(.libPaths()[1], full.names = TRUE)
# reprex
pkgs <- c(
  "/home/rstudio/myproject/renv/library/R-3.6/x86_64-pc-linux-gnu/askpass",
  "/home/rstudio/myproject/renv/library/R-3.6/x86_64-pc-linux-gnu/covr",
  "/home/rstudio/myproject/renv/library/R-3.6/x86_64-pc-linux-gnu/rex"
)

# Find if broken
# broken <- which(!file.exists(pkgs))
# reprex
broken <- c(2, 3)

if (length(broken) > 0) {
  # Get symlinks
  # symlinks <- Sys.readlink(pkgs[broken])
  # reprex
  symlinks <- c(
    "/opt/renv_cache/v5/R-3.6/x86_64-pc-linux-gnu/covr/3.2.1/ad68cd0c9a25388ac1b84ccb764e7ed8/covr",
    "/opt/renv_cache/v5/R-3.6/x86_64-pc-linux-gnu/rex/1.1.2/6d3dbb5d528c8f726861018472bc668c/rex"
  )

  # Get versions from symlinks
  pkgnames <- basename(pkgs[broken])
  versions <- unlist(lapply(
    strsplit(symlinks, split = pkgnames, fixed = TRUE),
    function(x) strsplit(x[2], split = "/", fixed = TRUE)[[1]][2]
  ))
  # Install versions
  lapply(seq_along(pkgnames),
         function(i) remotes::install_version(pkgnames[i], version = versions[i])
  )
}

```

**Comment by tomasruizt** [comment]
Whats the status on this? Is there an `renv` function to reinstall broken packages?

**Comment by kevinushey** [comment]
Calling `renv::restore()` should be sufficient.

**Comment by statnmap** [comment]
I can tell that `renv::restore()` is not sufficient. This is because I have a specific infrastructure.  
Indeed, I use the same project with different OS on the same laptop.  
The problem arise when I open my project inside a Docker container like with {devindocker} to test for what could happen in the CI: https://github.com/ThinkR-open/devindocker , and then try to open it locally, out of the Docker. The link to the cache is not the same inside and outside the container.  
That would be the same with accessing the same project using dual boot Windows / Linux for instance I guess.  
`renv::restore()` does not have a `force` option to re-install everything, as far as I can see.  
I know this is a specific use case though.

**Comment by MikhaelManurung** [comment]
Hi, I am also having a problem with a broken symlink. After calling `renv::restore()`, I saw a list of packages that have broken symlinks, but I received no prompt to install those packages. Is there a straightforward way to do this?

**Comment by kevinushey** [comment]
The development version of `renv` now exports a function called `renv::repair()`, designed to try and "repair" the project library when it's in this case.

I'll also see about why `restore()` doesn't work as we expect here.

**Comment by kevinushey** [comment]
I wasn't able to reproduce the behavior described with `restore()` not working -- if you're still having trouble, please file a new issue with more details. Thanks!

**Comment by oslobowl** [comment]
Hi!
I'm getting this
```
The following package(s) have broken symlinks into the cache:`...
```

each time I start my project in my Docker container. Does there exist any discussion on how to fix this? Thanks a bunch, and thanks for a great package :)

**Comment by kevinushey** [comment]
@oslobowl; can you please file a separate issue with more details on how your Docker container is set up (e.g. what is your Dockerfile)? Have you already seen https://rstudio.github.io/renv/articles/docker.html?
