### ISSUE TITLE
renv::init() - operation aborted

### ISSUE THREAD

**Issue by ivan-paleo** [rstudio/renv#381]
Hi,

I'm new to renv so I might be missing something obvious.

I have created a new Rproject in RStudio with some .R and .Rmd files loading some packages  through library(). 
I then loaded renv through ```library(renv)``` and tried to initialize with ```renv::init()``` but I get a message "* Operation aborted." (I guess it is an error, but it is not explicit). In any case, the renv folder contains only settings.dcf.

Here is the output of renv::dependencies(), from which I have shortened the paths in "Source" for compactness:
structure(list(Source = c("Create_RC_SSFA.Rmd", "Create_RC_SSFA.Rmd", "Create_RC_SSFA.Rmd", "Create_RC_SSFA.Rmd", "Create_RC_SSFA.Rmd", "Create_RC_SSFA.Rmd", "Create_RC_SSFA.Rmd", "Create_RC_SSFA.Rmd", "Create_RC_SSFA.Rmd", "SSFA_1_Import.Rmd", "SSFA_1_Import.Rmd", "SSFA_1_Import.Rmd", "SSFA_1_Import.Rmd"), Package = c("rmarkdown", "knitr", "here", "rrtools", "usethis", "rrtools", "usethis", "rrtools", "rrtools", "rmarkdown", "knitr", "openxlsx", "R.utils"), Require = c("", "", "", "", "", "", "", "", "", "", "", "", ""), Version = c("", "", "", "", "", "", "", "", "", "", "", "", ""), Dev = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)), row.names = c(NA, 13L), class = "data.frame")

From what I understand, the necessary packages are recognized. But I don't know what "Require", "Version" and "Dev" refer to (I couldn't find it in the help).

Any pointer appreciated, thanks!
Ivan

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
Matrix products: default
locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] renv_0.9.3-66
loaded via a namespace (and not attached):
 [1] compiler_3.6.3  htmltools_0.4.0 tools_3.6.3     yaml_2.2.1     
 [5] Rcpp_1.0.4      rmarkdown_2.1   knitr_1.28      xfun_0.12      
 [9] digest_0.6.25   packrat_0.5.0   rlang_0.4.5     evaluate_0.14

**Comment by kevinushey** [comment]
Thanks for the bug report! This was a bug in the development version of `renv`; I've pushed a fix and things should be working as expected now.

**Comment by ivan-paleo** [comment]
It indeed now works correctly, thanks!
