### ISSUE TITLE
init()/snapshot() error

### ISSUE THREAD

**Issue by ivan-paleo** [rstudio/renv#382]
Hi,

init() works fine when I call it at the beginning of the project. Then I copy some scripts in my project directory.

The problem arises when I either call snapshot(), re-open the project, or try to init() not at the beginning but once I have all the scripts in the directory.

The error is:
Error in !deps$Dev : invalid argument type
In addition: Warning message:
In FUN(X[[i]], ...) : subscript out of bounds

When I re-open the project, I get a bit more details:
Error in !deps$Dev : invalid argument type
In addition: Warning message:
In FUN(X[[i]], ...) : subscript out of bounds
Traceback (most recent calls last):
34: source("renv/activate.R")
33: withVisible(eval(ei, envir))
32: eval(ei, envir)
31: eval(ei, envir)
30: local(...) at activate.R#2
29: eval.parent(substitute(eval(quote(expr), envir)))
28: eval(expr, p)
27: eval(expr, p)
26: eval(quote(...), new.env())
25: eval(quote(...), new.env())
24: return(renv::load()) at activate.R#100
23: renv_load_finish(project, lockfile)
22: renv_load_report_synchronized(project, lockfile)
21: renv_project_synchronized_check(project, lockfile)
20: quietly({
        libstate <- snapshot(project = project, library = library, 
            lockfile = NULL, force = TRUE)
        synchronized <- renv_status_check_synchronized(project = project, 
            lockfile = lockfile, library = library, libstate = libstate)
    })
19: withCallingHandlers(expr, warning = function(c) invokeRestart("muffleWarning"), 
        message = function(c) invokeRestart("muffleMessage"), packageStartupMessage = function(c) invokeRestart("muffleMessage"))
18: snapshot(project = project, library = library, lockfile = NULL, 
        force = TRUE)
17: renv_lockfile_create(project, library, type)
16: renv_snapshot_r_packages(library = library, project = project) %>% 
        renv_snapshot_filter(project = project, type = type) %>% 
        renv_snapshot_fixup()
15: eval(call, envir = parent.frame())
14: eval(call, envir = parent.frame())
13: renv_snapshot_fixup(renv_snapshot_r_packages(library = library, 
        project = project) %>% renv_snapshot_filter(project = project, 
        type = type))
12: renv_snapshot_fixup_renv(records)
11: renv_snapshot_r_packages(library = library, project = project) %>% 
        renv_snapshot_filter(project = project, type = type)
10: eval(call, envir = parent.frame())
 9: eval(call, envir = parent.frame())
 8: renv_snapshot_filter(renv_snapshot_r_packages(library = library, 
        project = project), project = project, type = type)
 7: renv_snapshot_filter_implicit(project, records)
 6: renv_snapshot_filter_impl(project, records, project)
 5: renv_snapshot_dependencies(source)
 4: withCallingHandlers(dependencies(source, progress = FALSE, errors = errors), 
        renv.dependencies.error = renv_dependencies_error_handler(message, 
            errors))
 3: dependencies(source, progress = FALSE, errors = errors)
 2: deps[!deps$Dev, ]
 1: `[.data.frame`(deps, !deps$Dev, )

I guess there is a problem with one (or several) of the package(s) I use, but is there a way to avoid it?

Thank you in advance.
Ivan

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
Matrix products: default
locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    
attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     
loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4      bookdown_0.18   here_0.1        digest_0.6.25  
 [5] rprojroot_1.3-2 bitops_1.0-6    backports_1.1.5 evaluate_0.14  
 [9] rlang_0.4.5     renv_0.9.3-68   curl_4.3        fs_1.3.2       
[13] rstudioapi_0.11 rmarkdown_2.1   tools_3.6.3     glue_1.3.2     
[17] RCurl_1.98-1.1  xfun_0.12       yaml_2.2.1      compiler_3.6.3 
[21] rrtools_0.1.0   htmltools_0.4.0 knitr_1.28      usethis_1.5.1

**Comment by kevinushey** [comment]
Any chance you can provide a reproducible example? I've seen this reported once before as well but haven't yet been able to reproduce.

**Comment by kevinushey** [comment]
If you can share the scripts that are causing the error you're seeing, that would be a big help.

**Comment by ivan-paleo** [comment]
Hi Kevin,

It took me some time to find out where the problem was, but I think I've tracked it down to the DESCRIPTION file.
I do a lot using the package [rrtools](https://github.com/benmarwick/rrtools).

Here is a reproducible example:
```
rrtools::use_compendium(getwd()) # Select "yes" or equivalent
renv::init() # Works fine

rrtools::add_dependencies_to_description()
# 4 warnings "In readLines(y) : incomplete final line found on
# C:/Users/calandra.RGZM/Documents/Work/GitHub/testRenv/renv/library/R-3.6/x86_64-w64-mingw32/mgcv/tests/gam.R
# .../missing.data.R
# .../getmunsellmap.R
# .../convert.R"

renv::snapshot()
# Error in !deps$Dev : invalid argument type
# In addition: Warning message:
#  In FUN(X[[i]], ...) : subscript out of bounds
```

If I do things the other way around:
```
rrtools::use_compendium(getwd()) # Select "yes" or equivalent
rrtools::add_dependencies_to_description() # No warning
                                                                     # List of "Imports" much shorter in DESCRIPTION
renv::init()
# The following package(s) were not installed successfully:
#	[subscript out of bounds]: package 'subscript out of bounds' is not available
# You may need to manually download and install these packages.
# Error in !deps$Dev : invalid argument type
# In addition: Warning message:
# In FUN(X[[i]], ...) : subscript out of bounds
```

So, as far as I can tell, there is something wrong with the DESCRIPTION file, but it's not just the dependencies.

That's where my skills end, but let me know if I can help you any further.
Best,
Ivan

**Comment by ivan-paleo** [comment]
And I forgot to mention that I have a script with the library() calls to the packages I need in the project directory.
Since I cannot share the script file, here is the code:
```
library(R.utils)
library(ggplot2)
library(doBy)
library(openxlsx)
library(knitr)
library(rmarkdown)
library(here)
library(usethis)
library(rrtools)
library(renv)
```

I have created a repository for this in case you would want to check it:
[](https://github.com/ivan-paleo/testRenv)

**Comment by kevinushey** [comment]
Thank you very much! I greatly appreciate your taking the time to put together a reproducible example. I'm now able to reproduce this locally and should be able to fix this soon.

**Comment by kevinushey** [comment]
This should now be fixed on master: https://github.com/rstudio/renv/commit/04733b8f44429a52e5b74f24133531de943c5b72

The underlying issue was the empty field in the `Imports:` section of the `DESCRIPTION` file:

https://github.com/ivan-paleo/testRenv/blob/13bb383ed3482a78f52fdda8e761319b491c194f/DESCRIPTION#L14

Notice the comma at the end of a line (effectively specifying an 'empty' field). Unfortunately, `renv` tripped up on this. Should be fixed now!

**Comment by ivan-paleo** [comment]
Thanks Kevin, it works perfectly now!
