### ISSUE TITLE
Document how to use renv with GitHub Actions in ci.Rmd

### ISSUE THREAD

**Issue by KevCaz** [rstudio/renv#386]
First of all, thanks a lot for your work on this!

Second, I am currently deploying a blog (using blogdown) with GitHub Actions and
as I was looking for a way to reduce time of the run dedicated to install R
packages, I stumbled into this issue [r-lib/actions#79](https://github.com/r-lib/actions/issues/79) and after checking what @DavisVaughan did, I was able to successfully use `renv` and now the build takes 8min instead of >40 (https://github.com/inSileco/inSileco.github.io/actions).

Here I would simply like to point out that there is currently no information about
this in the `ci.Rmd` vignette and that I wouldn't mind completing the vignette
with a section `GitHub Actions` if you think that this could be of interest.

**Comment by kevinushey** [comment]
Thanks! I've added this to the documentation now:

https://rstudio.github.io/renv/articles/ci.html#github-actions

Let me know if this captures everything that one might need to know.

**Comment by KevCaz** [comment]
Looks good, thanks! FYI, the link in "See also the example on GitHub actions" isn't working (I guess it should be https://github.com/actions/cache/blob/master/examples.md#r---renv).

**Comment by kevinushey** [comment]
Thanks! Should be fixed up now.
