### ISSUE TITLE
How to install binaries from local sources on Linux (RcppParallel_5.0.0.tgz not being detected)

### ISSUE THREAD

**Issue by mstr3336** [rstudio/renv#388]
Hi Kevin et al, 
I've been trying to install some packages whose dependency trees include RcppParallel on my work's HPC. 

# Overview

After hitting a tonne of compilation issues bc of TBB, it seemed like I'd have to somehow just remove the dependency.
Fortunately, it turns out that for the most recent evironment module version of R, `R/3.6.3`, the sysadmins have actually built TBB for us. 

I searched for my system's RcppParallel install, living here: `/usr/local/R/3.6.3/lib64/R/library/RcppParallel` , and I was able to copy it into `~/extlib`, and point `renv::settings$external_libraries()` at `~/extlib`. 

This appeared to have given me access to `RcppParallel` from within my projects, but I don't particularly relish the thought of having to maintain and document such a setup in order for the project to function portably.

When i try to `restore()` it looks like renv will still prefer a project local install for `RcppParallel` from CRAN, so I'd probably have to ignore the package or something. 

# Current Problem

I thought a more elegant solution might be to use tar this static copy of the library, and set up [Local Sources](https://rstudio.github.io/renv/articles/local-sources.html) in order to force R to install the local binary if working from the HPC, but in other environments use CRAN. 

So far this doesn't appear to be working, and renv seems to default to fetching a source tarball from cran.

# Reprex

## In R

```r
renv:::renv_paths_local()
#> [1] "/home/mstr3336/.local/share/renv/local"
renv::settings$external.libraries()
#> character(0)
```

## Bash

```bash
cd ~/.local/share/renv/local
ls
```
```
RcppParallel
```
```bash
 ls RcppParallel/
```
```
RcppParallel_5.0.0.tgz
```

## Attempting Restore

Retrieval:

```r
Retrieving 'https://cran.csiro.au/src/contrib/RcppParallel_5.0.0.tar.gz' ...
        OK [file is up to date]
```

Failed Installation:

```r
Installing RcppParallel [5.0.0] ...
        FAILED
Error installing package 'RcppParallel':
========================================

* installing *source* package ‘RcppParallel’ ...
** package ‘RcppParallel’ successfully unpacked and MD5 sums checked
** using staged installation
** preparing to cleanup package 'RcppParallel' ...
** finished cleanup for package 'RcppParallel'
** preparing to configure package 'RcppParallel' ...
*** executing 'R CMD config'
```

I've also tried placing this tgz in `renv:::r_paths_binary()`, which has not helped things.

```r
renv:::renv_paths_binary()
#> [1] "/home/mstr3336/.local/share/renv/binary/R-3.6/x86_64-pc-linux-gnu
```

```bash
cd ~/.local/share/renv/binary/R-3.6/x86_64-pc-linux-gnu
pwd
#> /home/mstr3336/.local/share/renv/binary/R-3.6/x86_64-pc-linux-gnu
ls
#> RcppParallel_5.0.0.tgz
```

I didn't really expect this to work but i figured it was worth a crack. 

What am I missing here?

**Comment by mstr3336** [comment]
As I was about to post this issue, I re-reviewed #169 , and decided to try renaming `RcppParallel_5.0.0.tgz` -> `RcppParallel_5.0.0.tar.gz` in `~/.local/share/renv/local/RcppParallel`, (That is- I changed the extension from .tgz to .tar.gz) and it is now recognized by renv! 

Mystery solved!
I'll leave this issue up because I think that some of the wording in [Local Sources](https://rstudio.github.io/renv/articles/local-sources.html) and [Path Customization](https://rstudio.github.io/renv/reference/paths.html) could be clarified, as the following:

> The main requirement is that your source path exists, and the path has an extension of either `.tar.gz`, (for source packages), `.tgz` (for macOS binaries) or `.zip` (for Windows binaries).

Doesn't really document the process for providing local linux binary sources.

**Comment by kevinushey** [comment]
Thanks! I've updated the vignette to make this more clear.
