### ISSUE TITLE
renv::init() broken in recent versions

### ISSUE THREAD

**Issue by tannerntannern** [rstudio/renv#391]
Last week I was trying out renv and it seemed to work fine.  This week I tried it again, but I'm getting this error when running `renv::init()`:

```
> renv::init()
Error in is.na(Sys.getenv("GITHUB_ACTION"), unset = NA) : 
  2 arguments passed to 'is.na' which requires 1
```

I have little experience with R, but this looks like a typo to me -- isn't the `unset = NA` supposed to be part of `Sys.getenv`, not `is.na`?

I've confirmed that the issue is present in `0.9.3-76`, but not in `0.9.3-71`.

**Comment by kevinushey** [comment]
Sorry about that! Should be fixed up on master now -- thanks for reporting.

**Comment by tannerntannern** [comment]
Impressive turnaround time!  `0.9.3-77` works.  Thanks!
