### ISSUE TITLE
renv::update() does not update Bioconductor packages

### ISSUE THREAD

**Issue by PeteHaitch** [rstudio/renv#392]
Could `renv::update()` support the updating of Bioconductor packages?
Currently, it seems to ignore them and so my workflow for updating + snapshotting ends up looking something like this:

```R
 # Update CRAN and GitHub packages
renv::update()
# Update Bioconductor packages
out_of_date <- BiocManager::valid()$out_of_date
renv::install(paste0("bioc::", rownames(out_of_date)))
renv::snapshot()
```

The attached [renv.lock.zip](https://github.com/rstudio/renv/files/4478637/renv.lock.zip) can hopefully help illustrate the problem; I've taken a shopshot with an out-date version of the **S4Vectors** Bioconductor package.

Thanks!

**Comment by kevinushey** [comment]
Thanks for the request! This has now been implemented on master; give it a spin and let me know how it works:

```
renv::upgrade(version = "master")
renv::update("S4Vectors")
```

**Comment by PeteHaitch** [comment]
Works like a charm on my test case!
Thank you very much for implementing this, Kevin.
