### ISSUE TITLE
load external package that is in global library

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#393]
Hi, 

this could relate to #132 but I believe it is an adjacent use case. 

## Context

We use RStudio Server Pro in our company where I configured some internal R packages to connect to our internal DB. Theses packages are only available inside these servers and can't be installed by the user. They are installed in a server-wide library with other strandard packages. That allow us to provide specific packages versions for new users. (following something similary to [shared baselines strategy](https://environments.rstudio.com/shared.html)). 

## Issue

The issue we encountered with our users is that they can't use renv with a project that is using one of these specific internal packages. It is unlucky because renv has proven to be useful for collaboration and deployment inside the company where these packages are always available. 

In packrat, there was an option called [`external.packages`](https://rstudio.github.io/packrat/commands.html#externalpackages) that allow to have a project external package loaded. I believe this is used also [in RStudio Connect: to have external packages for content](https://docs.rstudio.com/connect/admin/r/package-management/#external-package-installation)
I don't think there is such an option already in renv. Or Maybe I missed it...

## Current situation 

Currently the workaround is to use `external.librairies` [settings](https://rstudio.github.io/renv/reference/settings.html) but we get all the drawbacks described only to have access to one packages. In this situations the renv project get access to all the packages.

We could also isolate in a specific  library path to only provide access to those to renv. Seems a bit tedious to do r-admin stuff to solve this. 

Otherwise, I guess we could deploy our internal package directly into the global renv cache we set up on the servers so that they are available for other without any installation. Obviously this would work only if this global cache is used. And this would work only for packages that don't require specific access right. yes, we have also internal packages that are deployed in specific library path with linux access right. I guess for those, the `external.libraries` setting would work just fine. 

## Follow-up

What could be the best way to handle this in your opinion ? 
Is something like `external.packages` considered for renv ? 
Is there any other similar use case out there ? 

Thank you.

**Comment by kevinushey** [comment]
My biggest fear with `external.packages` is that it's then no longer clear where dependent packages should be loaded from.

For example, if a user wants to load `dplyr` from the user library, do they also want dependencies (e.g. `tibble`) loaded from the external library as well, or from the project library? What happens when these cross-library dependencies are incompatible or out-of-sync -- e.g. you have `tibble 1.0.0` in your project library, but `tibble 1.0.1` in your external library? I think it could be very easy for users to run into these sorts of issues.

Ultimately, because of this, `external.packages` feels dangerous, hence why I didn't port that over to `renv`. However, I think an alternate solution would be to relax some of the sandboxing requirements done by `renv`; for example:

1. Include both site and system libraries in the `.libPaths()`,
2. Don't sandbox the system library (so that R packages installed in the system library are visible to users)

That way, packages within the site libraries would still be available to users by default.

**Comment by FvD** [comment]
@kevinushey maybe a particular and reproducible use case is [nvim-r](https://github.com/jalvesaq/Nvim-R). I  expected to be able to do something like adding the following to my `.Rprofile`, a solution that [worked with packrat](https://github.com/jalvesaq/Nvim-R/issues/59#issuecomment-319590419).

     options(renv.settings.external.packages = "nvimcom")

I understand now that this has not been implemented yet. Here's one vote in favour of doing so!

As for the dangers you point out: To my mind it is one of those cases where with power comes responsibility. It should be used with care and most users will not even try it out. But for particular ones, including the case described by @cderv  it seems to me that it makes sense to have the option.

**Comment by kevinushey** [comment]
One question I have: why not just install `nvimcom` into the project library?

**Comment by katosh** [comment]
`nvimcom` comes with the vim plugin [Nvim-R](https://github.com/jalvesaq/Nvim-R) and has no isolated public source. It can be installed into the project library but this can make `renv::restore()` fail on other machines.

**Comment by kevinushey** [comment]
In that case, you could "ignore" that package so it doesn't enter the lockfile:

```
renv::settings$ignored.packages("nvimcom")
```

Then, you can still install `nvimcom` into the project library locally, but not worry about it entering the lockfile / being installed on future restore attempts.

**Comment by hadley** [comment]
Otherwise @kevinushey's experience with packrat is that external packages caused more problems than they solved, because it wasn't clear where to install dependencies. In the last 3 years, it's become easier to create your own repositories, so that's likely what we'd recommend today.
