### ISSUE TITLE
Error in writef(e$output) : could not find function "writef"

### ISSUE THREAD

**Issue by alandipert** [rstudio/renv#395]
System: renv version: 0.9.2-37 as (I think?) installed automatically by RStudio Server Pro 1.2.5019-6 with R 3.6.2

How I saw it:

1. clone https://github.com/CRI-iAtlas/shiny-iatlas at 6c9427b38d65af708e5f1f5434abc59eb375ecfc
1. Open in RStudio
1. In the RStudio console, run `renv::restore()`

Observed the following error:
```
Installing RPostgres [1.2.0] ...
	FAILED
Error in writef(e$output) : could not find function "writef"
```
I suspect the reasons RPostgres failed are particular to my system, so I'm not confident this is enough information to reproduce. Perhaps the failure could be reproduced by simulating an install failure somehow.

A quick grep of renv master pointed me at https://github.com/rstudio/renv/blob/c3d726851a8fa5d7c116536ebb27ce260ffb55c0/R/install.R#L239 which looks like it could be the source of the error.

Thanks in advance for looking into it 🙏

**Comment by kevinushey** [comment]
Can you update to the latest version of `renv`? This should already be fixed.

**Comment by kevinushey** [comment]
Note that the version of `renv` is set explicitly by the project, so that project needs to update the version of `renv` associated.

**Comment by alandipert** [comment]
Thanks 👍 

I resolved by running `renv::install("renv")`. Then I ran `renv::restore()` and saw the error message that was previously suppressed.

**Comment by kevinushey** [comment]
Great! Hopefully getting to the bottom of the package installation issue was not too arduous.
