### ISSUE TITLE
renv::restore Error: failed to retrieve package after recent update to that package

### ISSUE THREAD

**Issue by ercbk** [rstudio/renv#397]
This is similar to issue #209 .  My github actions [run](https://github.com/ercbk/Indiana-COVID-19-Tracker/blob/master/.github/workflows/noon-update.yaml) this morning [failed](https://pipelines.actions.githubusercontent.com/932YpfzaxGsn62tZpjWssZvRbJv0TKSQtYyqOv7xOr8b2MILvG/_apis/pipelines/1/runs/52/signedlogcontent/3?urlExpires=2020-04-20T16%3A03%3A59.2970862Z&urlSigningMethod=HMACV1&urlSignature=HEx2SCVvBwWEGhlSxfG9X2xazMr8IfeCa4%2FD46agbfY%3D) after `restore` couldn't find the tibble package in in the mtu CRAN Archive.   
```
Retrieving 'https://cran.mtu.edu/src/contrib/Archive/tibble/tibble_3.0.0.tar.gz' ...
2020-04-20T15:55:05.3247034Z ##[error]Error: failed to retrieve package 'tibble'
``` 
A more recent `tibble` package was released 7 hours earlier and I guess the previous version hadn't been moved to the Archive directory in that repo yet. My version was still in the primary [directory](https://cran.mtu.edu/src/contrib/) of that CRAN repo last time I checked  I haven't tried the fix the stated in issue #209 yet, but thought I'd create another issue (as you suggested in that other thread) with links to my workflow yaml and run log in case that helps. I'll try the fix later this afternoon.  

Update: Changing the download source, `renv::restore(repos = c(CRAN = "https://cloud.r-project.org"))` does still work. The mtu mirror still hasn't moved the older version to the archive after 11 hrs, so it's not something that fixes itself that quickly.

**Comment by kevinushey** [comment]
While this is indeed a problem, I'm not sure what `renv` could do to rectify the issue -- if I understand correctly, this implies there was a brief period of time where `tibble 3.0.0` was just not available on CRAN.

**Comment by ercbk** [comment]
1. tibble 3.0.0 was available but `restore()` decided to look for it in the Archive directory instead of the contrib directory it normally used. I assumed the trigger was because a new version was available, but I don't know. Is it not possible to check both directories, contrib and Archive?  
2. If one source doesn't have the version of the package, can it not check https://cloud.r-project.org before failing?  
I don't know how these things work. So, if neither of these solutions(?) is practical, then I think it'd be helpful to put the fix or the issue somewhere in the documentation. This is my first time using a sort of CI/CD type thing, but this seems it might be a common occurrence if it takes CRAN mirrors over 12 hours move package verions around. It wasn't that hard to find the fix, but I would've like to have known about it beforehand and not have my project break.

**Comment by ercbk** [comment]
Even with `renv::restore(repos = c(CRAN = "https://cloud.r-project.org"))`, the project failed to retrieve my `installr` package version today. Log shows it looked in the Archive directory again. So, to anyone else who has this problem, specifying the cloud.r-project repo isn't a guaranteed fix.

**Comment by kevinushey** [comment]
Any chance you can provide more information? The install log from `renv` would be helpful.

You could also check what:

```
options(repos = c(CRAN = "https://cloud.r-project.org"))
renv:::renv_available_packages_entry("installr")
```

reports for you.

**Comment by ercbk** [comment]
[Log](https://pipelines.actions.githubusercontent.com/932YpfzaxGsn62tZpjWssZvRbJv0TKSQtYyqOv7xOr8b2MILvG/_apis/pipelines/1/runs/199/signedlogcontent/3?urlExpires=2020-06-12T00%3A39%3A18.4078543Z&urlSigningMethod=HMACV1&urlSignature=BZiZd2kF7e6qhZ09CrmtWNwefmXRC8QtALb8UtUMWVA%3D) from earlier today. I uninstalled it and removed it from the lock file earlier, so my run would pass this evening. Not sure how that's going to affect what you're looking at below.

``` r
options(repos = c(CRAN = "https://cloud.r-project.org"))
renv:::renv_available_packages_entry("installr")
#> * Querying repositories for available source packages ... Done!
#>           Package Version Priority                       Depends Imports
#> installr installr  0.22.0     <NA> R (>= 2.14.0), stringr, utils    <NA>
#>          LinkingTo
#> installr      <NA>
#>                                                                                      Suggests
#> installr curl, XML, htmltab, devtools, rjson, data.table, plyr,\nggplot2, sp, tools, pkgbuild
#>          Enhances License License_is_FOSS License_restricts_use OS_type Archs
#> installr     <NA>   GPL-2            <NA>                  <NA> windows  <NA>
#>                                    MD5sum NeedsCompilation Path
#> installr 2ddc0fa5dcce7e4ca4a378f820e1ec49               no <NA>
#>                                       Repository   Type Name
#> installr https://cloud.r-project.org/src/contrib source CRAN
```

<sup>Created on 2020-06-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kevinushey** [comment]
Unfortunately the log appears to have expired -- I just see:

```
{"count":11,"value":"Uri expired"}
```

Regardless, it looks like `installr` is found without issue now at least, so it's hard to know what might've happened.

**Comment by ercbk** [comment]
Hmph. looks like those links expire. Didn't know they did that. Here's the log file link in my Dropbox, https://www.dropbox.com/s/7177nuf7drjg21x/9_copy%20dev%20environment%20to%20runner.txt?dl=0

**Comment by kevinushey** [comment]
Thinking about this a bit more -- I wonder if the issue here is simply that the `installr` package is not available on non-Windows platforms, but `renv` is still trying to install it?

If that's indeed the case, then this sounds like an issue that should be fixed in the development version of `renv`.

**Comment by ercbk** [comment]
Whoops on me trying to use installr on a linux machine. Maybe that it is the problem in this case I dunno, but it was trying to download that installr version from the Archive directory when it wasn't there just like last time.

**Comment by hadley** [comment]
I suspect this is another case of #1188
