### ISSUE TITLE
Can't install renv

### ISSUE THREAD

**Issue by BernardFournier** [rstudio/renv#398]
I want to install this package to install another package (adventr), but this warning comes up.

  There is a binary version available but the source version is later:
     binary source needs_compilation
renv  0.9.2  0.9.3             FALSE

**Comment by kevinushey** [comment]
Did the installation from sources not succeed?

**Comment by kevinushey** [comment]
Installation from sources should still succeed without issue, so I'm going to close this unless you can provide more detail.

**Comment by BernardFournier** [comment]
Perfect it worked

Bernard

________________________________
