### ISSUE TITLE
renv::init() call just hangs?

### ISSUE THREAD

**Issue by jameshowison** [rstudio/renv#399]
This is happening on a fresh Docker image.

```sh
docker run --rm -ti rocker/r-base
```

drops you into an R session

```r
install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))
remotes::install_github('rstudio/renv')
```
appear to work fine.  renv_0.9.3-85.tar.gz is installed.

```
renv::init()
```

Just hangs ... I've left it for quite some time, should there be any messages or status? I'm expecting something like

```
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
```

Hitting ^C shows:

```
^C
Traceback (most recent calls last):
392: renv::init()
391: renv_dependencies_scope(project, action = "init")
390: withCallingHandlers(dependencies(path, progress = FALSE, errors = errors, 
         dev = TRUE), renv.dependencies.error = renv_dependencies_error_handler(message, 
         errors))
389: dependencies(path, progress = FALSE, errors = errors, dev = TRUE)
388: delegate(renv_dependencies_impl)
387: eval(call, envir = parent.frame(2))
386: eval(call, envir = parent.frame(2))
385: <condition-handler>(...)
384: renv_dependencies_find(path, root)
383: lapply(path, renv_dependencies_find_impl, root = root)
382: FUN(X[[i]], ...)
381: renv_dependencies_find_dir(path, root)
380: lapply(children, renv_dependencies_find_impl, root = root)
379: FUN(X[[i]], ...)
378: renv_dependencies_find_dir(path, root)
```

And that repeats until

``` 
10: FUN(X[[i]], ...)
  9: renv_dependencies_find_dir(path, root)
  8: lapply(children, renv_dependencies_find_impl, root = root)
  7: FUN(X[[i]], ...)
  6: renv_dependencies_find_dir(path, root)
  5: lapply(children, renv_dependencies_find_impl, root = root)
  4: FUN(X[[i]], ...)
  3: renv_dependencies_find_dir(path, root)
  2: renv_renvignore_exec(path, root, path)
  1: renv_renvignore_pattern(path, root)
```

**Comment by jameshowison** [comment]
Hmmm, same issue with `renv::init(bare=T)` and `renv::dependencies()` called directory.  `renv::status` also hangs.  I wonder if this is something to do with rocker, I'll try it with other image paths.

**Comment by jameshowison** [comment]
Nope, same issue with the rstudio/r-base image.

```bash
docker run --rm -it rstudio/r-base:3.5-xenial
```

**Comment by kevinushey** [comment]
Based on the call stack, it sounds like `renv` is getting hung up crawling your Docker image (or files on its filesystem) for dependencies.

What files / folders exist in that project? To reproduce we'd probably need to know the exact project structure. (Maybe `renv` is tripping up on a recursive symlink?)

**Comment by jameshowison** [comment]
Right, probably that :)  Bringing up those images the R session working directory is `/` so indeed the crawl is probably large and there is probably a recursive symlink somewhere!

```r
getwd()
[1] "/"
```

The use case here is interacting with renv via Dockerfiles and particularly the Docker/buildx cachemounts (which work wonderfully for Python but don't work for R).  

I'm trying to prototype that here:  https://github.com/howisonlab/test_repo_buildx_renv

**Comment by kevinushey** [comment]
Wouldn't you normally want to set the working directory in the Dockerfile to some appropriate project directory?

**Comment by kevinushey** [comment]
I've made a change on master that should improve our handling of recursive symlinks. Can you give that a shot and let me know if things look better there?

**Comment by jameshowison** [comment]
I redid the install from github on the container, so I think it picked up the most recent changes (straight from master, right?)

```
remotes::install_github('rstudio/renv')
```

Same behavior, I'm afraid. But I don't really know how to debug these, I'm afraid. Is there anyway to print out the directories being looked at, so I can see where the hang is? I'm confused why renv::init(bare=TRUE) also seems to hang.  The stack trace shows:

```
> renv::init(bare=TRUE)
^C
Traceback (most recent calls last):
103: renv::init(bare = TRUE)
102: renv_dependencies_scope(project, action = "init")
101: withCallingHandlers(dependencies(path, progress = FALSE, errors = errors, 
         dev = TRUE), renv.dependencies.error = renv_dependencies_error_handler(message, 
         errors))
100: dependencies(path, progress = FALSE, errors = errors, dev = TRUE)
 99: delegate(renv_dependencies_impl)
 98: eval(call, envir = parent.frame(2))
 97: eval(call, envir = parent.frame(2))
 96: <condition-handler>(...)
 95: renv_dependencies_find(path, root)
```

I think you might be right about creating a project directory!

**Comment by jameshowison** [comment]
I added a project directory to the Dockerfile

```
COPY hello_world.r /app
```

Then in the script I used this:


```
setwd("/app")
Sys.setenv(RENV_PATHS_ROOT = '/buildx_caches/renv_cache')
install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))
remotes::install_github('rstudio/renv')
renv::consent(TRUE)
renv::init()
```

Which works. So, running renv::init() with `setwd("/")` still hangs, but starting in the `/app` directory works.

**Comment by mobiuscreek** [comment]
Thank you for the working snippet. For future reference this behaviour is now documented here: https://rstudio.github.io/renv/articles/docker.html
