### ISSUE TITLE
Enhancement: Check installed and pack.lock package version at session start

### ISSUE THREAD

**Issue by asodja** [rstudio/renv#40]
I was playing with renv a bit and I find it pleasant to use - specially I like that renv::install() automatically updates renv.lock, since one can easily forget to call snapshot.

One cool feature that could be added would be a check of installed package versions and versions in renv.lock when R session is started. So if versions for some package are different, then user would be asked to run renv::restore() (or there could be [y/N] prompt to call restore).

**Use case:**
For example there are multiple people working on the same project and then someone updates/downgrades some library and pushes changes to git. Then other guys might pull changes but they would not notice package changes and project would break for them. With this check everyone would know right away that some package version was changed and that they should update their local packages.

**Comment by kevinushey** [comment]
This is effectively what `renv::status()` does -- perhaps that's worth calling when the R session is started?

**Comment by jjallaire** [comment]
This might be getting back into the “I wish packrat would stop printing
messages” territory.

**Comment by asodja** [comment]
@kevinushey Basically renv::status() is what I had in mind, only additionally that there would be a prompt to choose what to do with it.

As @jjallaire pointed out, I see that this behaviour might be confusing to some users. Is it possible to get return result like renv::status prints (diff data.frame between installed and pack.lock package versions) to handle it by myself? 

In case that this is not useful to anyone else you can close this issue.

**Comment by kevinushey** [comment]
Having `renv::status()` return its output (invisibly) seems like a great idea.

**Comment by hadley** [comment]
`renv::status()` now does invisibly return (but needs to be documented, #807). Tracking auto-status/restore in #353.
