### ISSUE TITLE
Improve `.gitignore` handling

### ISSUE THREAD

**Issue by chriswasser** [rstudio/renv#403]
Hello everyone,

While trying to apply `renv` to some of my projects, I ran into an issue when invoking `renv::init()` in one of them. Surprisingly, the automatic dependency discovery implemented in `renv::dependencies()` did not work correctly. After deleting file after file to identify the cause of the problem and resolve the complications, I came across [this section](https://rstudio.github.io/renv/reference/dependencies.html#ignoring-files) in the `renv::dependencies` documentation dealing with automatically skipped scripts occurring in `.gitignore` files. As it seems, `renv` does not correctly process patterns for explicitly included files (marked by `!`), which are tracked by `git`.

Below is a shell script, which shows the difference between a failed dependency discovery and a correctly initialized project. To run the script only renv is required to be installed. I tested both the current `renv` release on CRAN and the up-to-date GitHub master branch - both resulting in the same result.

Workaround for now would be not to rely on `!` in `.gitignore`files though I doubt that this is intended behaviour.

Hope this helps for implementing a fix 😃 Love the package already 👍

Greetings

Christian

```sh
#!/usr/bin/env sh

# renv does not discover dependencies in script.R
mkdir renv-failing
cat > renv-failing/script.R <<EOF
library(tidyverse)
EOF
cat > renv-failing/.gitignore <<EOF
# also fails for *.R /* /*.R
*
!script.R
EOF
cd renv-failing
Rscript -e 'renv::init()'
cd ..

# renv correctly discovers all dependencies
mkdir renv-working
cat > renv-working/script.R <<EOF
library(tidyverse)
EOF
cd renv-working
Rscript -e 'renv::init()'
cd ..
```

**Comment by kevinushey** [comment]
Thanks for the bug report! I believe this should now be properly handled with the latest version of `renv` -- could you give it a try and let me know if all looks well?

```
renv::upgrade(version = "master")
```

**Comment by chriswasser** [comment]
The reproducer script from above still shows the same behaviour: In `renv-failing,` only `renv` appears in `renv.lock` while in `renv-working` all dependencies are captured correctly. I rechecked the version of `renv` after upgrading and it is the correct, up-to-date version:

```sh
    "renv": {
      "Package": "renv",
      "Version": "0.9.3-96",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "renv",
      "RemoteUsername": "rstudio",
      "RemoteRef": "master",
      "RemoteSha": "f21b15fe433f738a7f42368e62303f2a4c087fbd",
      "Hash": "a9203f0c51512b0f4fe3e8d0c6162659"
    }
```

Something is still not right 🤔

**Comment by kevinushey** [comment]
Sorry about that! There were a couple mistakes in my initial implementation; should now be properly fixed up on master.

**Comment by chriswasser** [comment]
Thanks, the specific case from above works correctly now 👍

As I tested a few different `.gitignore` patterns, I came across an interesting [repository](https://github.com/svent/gitignore-test "Github Repository gitignore-test"), which is designed for providing examples for testing tools like `renv` that deal with `.gitignore` files. I tested some of the cases though definitely not all of them as you need to rename the specific file under test to *.R and add some `library(...)` call to make it relevant for `renv`. One case which is ignored by `git` but wrongly processed by `renv` is a pattern like `\!script!.R` where the `!` is contained in the filename and therefore escaped in the `.gitignore`. Below again, a modified reproducer 😃 However, this case may be less relevant than the other bug as most people will not put a `!` at the start of their filename... Maybe something to look into for a 1.0.0 release of `renv` 👌

I am not sure if you want to leave this issue open for keeping track of `.gitignore` parsing errors in general or if you want to close it because the initial bug is fixed.

```sh
#!/usr/bin/env sh

# renv does not discover dependencies in script.R
mkdir renv-failing
cat > 'renv-failing/!script!.R' <<EOF
library(tidyverse)
EOF
cat > renv-failing/.gitignore <<EOF
\!script!.R
EOF
cd renv-failing
Rscript -e 'renv::init()'
cd ..

# renv correctly discovers all dependencies
mkdir renv-working
cd renv-working
Rscript -e 'renv::init()'
cd ..
```

**Comment by hutch3232** [comment]
hello @kevinushey! I am encountering a similar issue where dependencies are not detected when I use `!` in an attempt to include them.

My setup:

- renv
- .Rproj
- top
  - bottom
    - script.R
  - dont_match
    - script.R

then my `.gitignore` contains:
```
.Rproj.user
.Rhistory
.RData
.Ruserdata

top/*
!top/bottom
```

I was hoping that dependencies in `top/bottom` would be found, but those in `top/dont_match` would be excluded.

I believe the issue stems from `renv_renvignore_exec`, which will find `./top` to be excluded, so in the next pass, it won't look further down the directory tree, which would find it (if it looked) with the exact match from the regex which needs all of `./top/bottom`.

**Comment by kevinushey** [comment]
Thanks for the bug report! As a workaround, I think you could set the `.gitignore` rules in the `top/` folder directly, with:

```
*
!bottom
```

**Comment by tilley-charles** [comment]
We were running into a similar issue with the parsing of negation logic in a `.gitignore`, and were able to side-step the issue by creating a `.renvignore` for the exclusive use of `renv`, based on the description here:

https://github.com/rstudio/renv/blob/37f4e97e0cff7dfddfcef9d2de702f7c45e056fb/R/dependencies.R#L40-L48

**Comment by hadley** [comment]
@kevinushey thinks all the reported cases have already been fixed;  I'll double check and add a couple of tests.

**Comment by hadley** [comment]
Looks like all the cases in this issue are already covered by tests so it can be closed: https://github.com/rstudio/renv/blob/b4493f95b0d73a370ce3a5cac39cb07a73e7ee12/tests/testthat/test-renvignore.R#L146-L169
