### ISSUE TITLE
renv::install() modifies .Rprofile

### ISSUE THREAD

**Issue by twesleyb** [rstudio/renv#404]
I think that call's to `renv::install()` sometimes prepend the `.Rprofile` with `source("renv/activate.R")`. 

This can be really annoying if you try to launch R outside a directory containing `renv/activate.R` as it results in an error: 
> cannot open file 'renv/activate.R': No such file or directory

To accommodate this scenario, I have a global `.Rprofile` in which I wrote:
```
# Only try to activate a renv if it exists!
if (file.exists("renv/activate.R")) { source("renv/activate.R") } 
```
But when I install a package with `renv::install()` it messes everything up by adding source("renv/activate.R") at the top!

Can the default behavior of `renv::install` be changed so that it doesn't modify the .Rprofile? 
Alternatively, If I'm not doing things correct or could be doing them better please let me know.

**Comment by kevinushey** [comment]
Is there any chance you could provide a reproducible example? `renv::install()` shouldn't be modifying any existing `.Rprofile` files.

**Comment by twesleyb** [comment]
Hi Kevin, I tried my best to make a reproducible example. Here's what I did:

I create a directory in which I am going to do work.
```Bash
# Create a new project directory.
mkdir ~/test
cd ~/test
```

I use `conda` to manage non-R dependencies, so I'll initialize a new environment from a `yaml` file.
```Bash
# Initialize env
conda env create -f ~/test/test.yml
```

My simple yaml file looks like this:
```yaml
name: test
channels:
  - conda-forge
prefix: /home/twesleyb/anaconda3/envs/test
```

Let's activate the env and install `renv` from conda-forge.
```Bash
conda activate test

# Check which R we are using:
which R # /usr/bin/R

# Install renv
conda install -c conda-forge r-renv

# Check R again:
which R # /home/twesleyb/anaconda3/envs/test/bin/R
```

Now I'll create an `renv` to manage my R-dependencies:
```R
# Init renv.
renv::init()
```
`renv::init()` does its thing... 
> * renv activated -- please restart the R session.

Let's check the contents of my project directory.
```Bash
ls -a
```
> .Rprofile  renv  renv.lock  test.yml

`renv::init` created a `.Rprofile` -- like I believe It should have. However, I want to use my own in `~/.Rprofile`. I'll link it from my home directory.

```Bash
rm ~/test/.Rprofile
ln -sv ~/.Rprofile . # './.Rprofile' -> '/home/twesleyb/.Rprofile'
```
My `.Rprofile` looks like this:
```
# Rprofile - R configuration
# NOTE: Rprofiles are symlinked to $HOME/dotfiles/.Rprofile
# Load renv.
if (file.exists("renv/activate.R")) { source("renv/activate.R") }
```

Back to action, lets do some work in a sub-directory of my new project.
```
mkdir ~/test/subdir
cd ~/test/subdir
```
I create a script, it looks like this:
```My script
#!/usr/bin/env Rscript

# Activate renv
root <- dirname(getwd()) 
renv::activte(root)

# Hi
print("Hello world")
```
I run the script.
```Bash
chmod +x script.R
./script.R
```
It works. Now lets check the contents of my `.Rprofile` again, `cat ~/test/.Rprofile`:
```
source("renv/activate.R")
# Rprofile - R configuration
# NOTE: Rprofiles are symlinked to $HOME/dotfiles/.Rprofile
# Load renv.
if (file.exists("renv/activate.R")) { source("renv/activate.R") }
```

`source("renv/activate.R")` has been inserted at the top!
Now, when I launch R in a subdirectory which does not contain `renv/activate.R` I gen an error message:
```bash
cd ~/test/subdir
R
```
> Error in file(filename, "r", encoding = encoding) : 
>  cannot open the connection
>  In addition: Warning message:
>  In file(filename, "r", encoding = encoding) 
> cannot open file 'renv/activate.R': No such file or directory

Herein the problem lies.

**Comment by kevinushey** [comment]
Calling `renv::activate()` does modify the project `.Rprofile`, and that is its purpose:

```
     Use 'activate()' to write the infrastructure needed to ensure that
     newly-launched R projects will load the project's private library
     on launch, alongside any other project-specific state recorded for
     the project.
```

In other words, `renv::activate()` / `renv::deactivate()` are basically used for turning the auto-loader in the `.Rprofile` on and off.

Maybe you want to call `renv::load()` instead?

**Comment by twesleyb** [comment]
Thanks, that was the problem. 
My familiarity with `conda activate` probably caused the confusion.
Initially, I followed your [tutorial](https://rstudio.github.io/renv/articles/renv.html) to learn about `renv`. 
It doesn't mention `renv::load()`. If I were to suggest an improvement... Maybe it should?

Also, maybe `renv::activate()` could warn you if it modifies the `.Rprofile`? It already checks if the .Rprofile contains the _renv::activate()_ line, and doesn't add another if it exists. I think this behavior arises from the `infrastructure.R` script.

Also, the documentation of `load()` seems to imply its use is to follow `activate()`:
```
Examples:                                                                                                                                                                                                                                                        ## Not run:
# Load a project -- note that this is normally done automatically
# when the R session is started in an renv project after calling
# renv::activate()
# renv::load()
## End(Not run)
```

**Comment by kevinushey** [comment]
Normally though, things "just work" as long as you launch R with the working directory set to the project directory. Then, the autoloader (normally added by `renv::init()` or `renv::activate()`) will take care of calling `renv::load()` for you.

I think the recommended workflow is well documented in the vignette:

https://rstudio.github.io/renv/articles/renv.html

and the documentation for `?renv::load` makes it clear that you normally don't need to call it:

> Normally, this is done automatically on session startup by the infrastructure generated by activate() – users should not need to call this function directly.

I don't quite understand why you want to create a symlink from your project `.Rprofile` to the global `.Rprofile`. Just delete the project `.Rprofile` and then the global `.Rprofile` will be used -- but of course, then you'd have to manually call `renv::load()` to load an `renv` project.

**Comment by twesleyb** [comment]
Alright, I'm sticking to my idea here. I don't think calls to `renv::init()` should modify the `.Rprofile` without at least warning you it is going to do so. Of course `renv` warns you if the lock.file exists, but I would prefer that it also notify the user if it modifies the .Rprofile. Feel free to close if you disagree as there is no real error with renv.  And thanks again, using renv has really helped me manage my environments.

**Comment by kevinushey** [comment]
This is part of `renv::init()`'s documented behavior, though. The intention here is that if you launch R at the root of a project managed by `renv`, then that `renv` project should automatically be loaded. This is facilitated via the use of a project-local `.Rprofile`.

We could consider controlling this via an option / parameter to `renv::init()`, I suppose?
