### ISSUE TITLE
Different linux distros/versions are not distinguished in the cache

### ISSUE THREAD

**Issue by mstr3336** [rstudio/renv#407]
I am trying to migrate my project across to singularity containers on my work's HPC.

I am running R from a singuarity container.

When running singularity from our HPC, the host system's `/home` , and `/project` directories are mounted to the container.

My work's HPC is Centos 6.9, the container image is Ubuntu 16.04 (Newest version of Ubuntu that the HPC's kernel can run). 

In the past, to set the path to `renv::cache`, I would set the following in `~/.Renviron`: 

```
RENV_PATHS_CACHE=/project/STEMI/software/renv/cache
```

# The problem

My problem is this:

When I attempt to run some package (For example here's something that uses igraph), I run into errors like this:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :  unable to load shared object '/project/RDS-FHS-STEMI-RW/software/renv/cache/v5/R-3.6/x86_64-pc-linux-gnu/igraph/1.2.4.2/fffa635f747cd07ffc56bc13a23701e4/igraph/libs/igraph.so':
   libRlapack.so: cannot open shared object file: No such file or directory 
```

Digging into this, I perform the following from within both the host and container

```r
# HOST
renv:::renv_paths_cache()

#> [1] "/project/RDS-FHS-STEMI-RW/software/renv/cache/v5/R-3.6/x86_64-pc-linux-gnu"

La_library()

#> [1] "/usr/local/R/3.6.3/lib64/R/lib/libRlapack.so"
```

```r
# CONTAINER
renv:::renv_paths_cache()

#> [1] "/project/RDS-FHS-STEMI-RW/software/renv/cache/v5/R-3.6/x86_64-pc-linux-gnu"

La_library()
#> [1] "/usr/lib/lapack/liblapack.so.3.6.0" 
```

So what I'm seeing is that both container and host are looking at the same cache - I'd be okay with that, except that they also can't really distinguish whose system is whose, and packages built on the HPC host system are going to reference shared objects dependendant on the host systems environment. 

The following article explains how to achieve exactly the same setup I already have, but with Docker:
https://rstudio.github.io/renv/articles/docker.html#running-docker-containers-with-renv 

You state:

> Note that the platform and R version in use are appended to the requested cache directory. This ensures that a single directory can act a base of cached packages for multiple different platforms and R versions.

The thing is- Ubuntu 16.04 and Centos 6.9 (Legacy HPC Magic Edition) are VERY different platforms, and they should probably not share any cache whatsoever - 

That being said, I would like my container to leverage the cache, and I'd still like my host system to be able to do the same, if possible.

How can I trick, force, or politely ask renv to use a different cache when in my container?

**Comment by mstr3336** [comment]
I think I've got an answer to my question - More to do with singularity than renv. 

I'm adding defintion of RENV_PATHS_CACHE to my recipes %runscript

**Comment by kevinushey** [comment]
> The thing is- Ubuntu 16.04 and Centos 6.9 (Legacy HPC Magic Edition) are VERY different platforms, and they should probably not share any cache whatsoever -

You are absolutely correct. We should be appending the operating system's ID / version to this path as well.

You're indeed correct that the workaround here is to explicitly set `RENV_PATHS_CACHE` to point at a different directory for each OS, but I should fix this on the `renv` side to obviate this requirement.

**Comment by kevinushey** [comment]
I've just made a change in the development version of `renv` that should help here.

Now, it's possible to tell `renv` to prepend an arbitrary path component to the paths used for the library or cache by setting the `RENV_PATHS_PREFIX` environment variable. You could set this in (for example) your R installation's `Rprofile.site`; e.g.

```
RENV_PATHS_PREFIX = ubuntu-bionic
```

In a future version of `renv`, I'll see if we can make it possible to automatically construct and prepend OS-specific components to these paths, but wanted to avoid doing so immediately as to avoid any potential carnage in the next `renv` update on CRAN.

Let me know if that sounds reasonable.

**Comment by mstr3336** [comment]
I think that that sounds reasonable, though maybe it doesn't bring MUCH advantage over my previous solution (setting RENV_PATHS_CACHE vs SINGULARITYENV_RENV_PATHS_CACHE)

That being said, it's a big change that would break/require relinking a lot of people's caches, and in some instances I'm sure that it's not even true to say that a different distro/version even needs a different cache (it's likely that debian systems can usually share a cache, unless its some specialized setup like the HPC), so many users probably mightnt even want this feature.

Thank you for your consideration!

**Comment by mstr3336** [comment]
> I think that that sounds reasonable, though maybe it doesn't bring MUCH advantage over my previous solution (setting RENV_PATHS_CACHE vs SINGULARITYENV_RENV_PATHS_CACHE)

Actuallyon reflection, your solution is still cleaner and better, and I appreciate it, since it allows one to add this definition to their container's install, and avoid modifying the value of `renv_paths_cache`, instead modifying an optional value.

Thanks, Kevin! What you propose sounds excellent!

**Comment by kevinushey** [comment]
Great! I'm glad to hear it -- thanks for your feedback!
