### ISSUE TITLE
Sync package versions between lockfiles

### ISSUE THREAD

**Issue by smingerson** [rstudio/renv#409]
I have multiple projects which share a subset of packages. Between projects, I want those packages (and their dependencies) to have the same version present. Ideally, I would be able to pass a function a vector of project or lock file locations, and it would update (checking with the user first) the lockfiles to the latest version of each package.

**Comment by kevinushey** [comment]
I believe you could accomplish this with multiple calls to `restore()`; e.g.

```
renv::restore(lockfile = "/path/to/renv-base.lock")
renv::restore(lockfile = "/path/to/renv-project.lock")
```

Would this be enough for what you require?

**Comment by smingerson** [comment]
That'll work well. I should've thought about it more before filing an issue. Thank you!
