### ISSUE TITLE
Install of package from unknown source fails with renv 0.2.0-49 and later

### ISSUE THREAD

**Issue by asodja** [rstudio/renv#41]
When restoring package from unknown source with renv.verbose=TRUE there is error with following message:
Message: 
`Error in renv_verbose() && renv_pretty_print_records(unknown, "The following package(s) were installed from an unknown source:",  : 
  invalid 'y' type in 'x && y'`.

Bug was probably introduced with commit:
https://github.com/rstudio/renv/commit/327eabf61d1703ae074034d06c010674e6d5a0b5

In function _renv_restore_preflight_unknown_source_:
`renv_verbose() && renv_pretty_print(...)`
probably should be:
 `if (renv_verbose()) {
   renv_pretty_print(...)
  } 
`

There might be similar issue in function _renv_restore_preflight_permissions_.

**Comment by kevinushey** [comment]
Thanks! You're correct; I'll fix that.

**Comment by kevinushey** [comment]
Just fixed it up -- please try running `renv::upgrade()` to get the fixed-up copy of `renv` in your project.

**Comment by asodja** [comment]
Thanks, this fix works. Although for renv::upgrade() I get for renv 0.2.0-47 and later:

`> renv::upgrade()
Error in map[[json]] : subscript out of bounds
`
It works fine with 0.2.0-46.

**Comment by kevinushey** [comment]
Thanks -- I'll try to investigate.

**Comment by kevinushey** [comment]
Sorry for the trouble. This should be fixed on master again with https://github.com/rstudio/renv/commit/85ab7a752ba6f7396ac87205be86273e41f4b60f.

**Comment by asodja** [comment]
No problem. I appreciate great work you are doing. Renv works really great for me. 
 
Keep up the good work!

**Comment by kevinushey** [comment]
I'm very glad to hear it :-) Please let us know if you run into any issues!
