### ISSUE TITLE
Set options("repos") to include RSPM binaries

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#410]
Today, we take a _linux_ URL and strip off the binary URL bit for the lockfile, which makes the lockfile more portable across operating systems

However, I'm wondering whether when we read the lockfile into my runtime we could set my repos URL to `__linux__` , so that tools like `devtools::install_deps()` or other things that skip renv and just use the `options('repos')` will automatically use the binaries.

Minimal `renv.lock` file:
```
{
  "R": {
    "Version": "3.4.3",
    "Repositories": [
      {
        "Name": null,
        "URL": "https://packagemanager.rstudio.com/cran/latest"
      }
    ]
  },
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.9.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c1a367437d8a8a44bec4b9d4974cb20c"
    }
  }
}

```

- Create this `renv.lock`
- Then load the project and see that `options("repos")` does not include `__linux__/bionic` (if on a bionic system)
- Ideally, `options("repos")` would automatically infer the binary repository URL, if available

**Comment by kevinushey** [comment]
Thanks! I've made that change.
