### ISSUE TITLE
renv::restore fall-back to newer package version

### ISSUE THREAD

**Issue by mb706** [rstudio/renv#412]
I am using renv in an educational setting, where I give students R-exercises to solve, and I want to give them an R environment as close as possible to the "known good" environment on my computer. However, this leads to students sometimes having to install "old" package versions, and that can give them trouble on Windows: Apparently there are no binary packages of old versions available (and guiding them through installing Rtools is beyond my capacity).

Is there a way to have `renv::restore()` fall back to a the newest version of a package should installation of a package fail? Or is there a way to tell `renv` to just install the newest versions of all packages that are in `renv.lock`?

I could give them a script that does the `if (!require` thing and loops through the list of needed packages, but since I am already using `renv` to make sure this list of packages is enough to solve the exercise (i.e. by taking this list from `renv.lock`) it would be convenient if my students could also use `renv` to get to a good-if-not-perfect replication of my environment.

**Comment by kevinushey** [comment]
The development version of `renv` will use MRAN binaries, which should help alleviate some of this pain. I'm hoping to get a new release of `renv` on CRAN soon as well.

I agree it would be useful to give the user more control over what happens during `restore()`, though.

**Comment by mb706** [comment]
Some updates on how this is working out for me:
* renv 0.10 does seem to use binaries when installing older packages now, which is :+1:
* sometimes a very new package does not have binaries available for windows, or does not have binaries for all versions of R, in which case it would still be nice if renv could offer the possibility to fall back to the newest version *with* binaries available 
* `renv::restore()` seems to abort and revert everything, even if there is a problem with installing just one package. It would help if there were at least the possibility to react to an `renv::restore()` failure, e.g.:
    ```r
    renv::restore()
    #> Installing [thirty something packages without issue]
    #>     OK
    #> ...
    #> Installing XX [3.1] ...
    #>     FAILED
    install.packages("XX", type = "binary")
    #> ... [installing XX version 3.0] ...
    renv::restore(accept_partial_state = TRUE)
    #> Installing XX [3.1] ...
    #>     FAILED, BUT I WILL NOT MAKE YOU INSTALL EVERYTHING BY HAND JUST BECAUSE OF THIS
    ```
    i.e. to install the things that can be installed and not revert when an installation fails (maybe only revert if dependencies are not met, but accept different versions that are present in the library before)

**Comment by kevinushey** [comment]
> renv::restore() seems to abort and revert everything, even if there is a problem with installing just one package. It would help if there were at least the possibility to react to an renv::restore() failure, e.g.:

See `install.staged` in `?renv::config`. You probably want:

```
options(renv.config.install.staged = FALSE)
```

**Comment by kevinushey** [comment]
I should probably rename that to something like `install.transactional` or `restore.transactional`.

**Comment by kevinushey** [comment]
> sometimes a very new package does not have binaries available for windows, or does not have binaries for all versions of R, in which case it would still be nice if renv could offer the possibility to fall back to the newest version with binaries available

Are you seeing this with `renv::install()` or `renv::restore()`? With renv 0.10.0, `renv::install()` will install binaries by default, unless the newer source version does not require compilation.

**Comment by hutch3232** [comment]
I have a similar use-case but having some issues and stumbled across this issue.

I'm in a situation where I'm trying to establish a process where various projects can migrate their renv-based project to a new system as seemlessly as possible. This is a pretty big change (large R version upgrade, redhat -> ubuntu, different C++ compilers, etc.) so even though renv manages very effectively, I'm coming across installation issues when trying to `restore` an old lock file into the new compute environment.

After finding this page, I thought I could simply run the following and that it would skip over any errors and install as much as possible. Then at the end it could let me know what the problem packages are. Using `exclude` is one option, but that gets really tedious, especially when the problem packages are dependencies of other packages. It becomes trial and error..

Am I following the recommended practice here?

```r
options(renv.config.install.transactional = FALSE)
renv::restore(lockfile = "/path/to/old/lockfile")
```

Thanks!

**Comment by kevinushey** [comment]
That is indeed the recommended practice, although I recognize it's still not ideal (since you're still stuck fixing installation issues one-by-one as they occur).

The main difference with that example is, after the `restore()` fails, you should still see the previously-installed packages remain in the library, so they shouldn't need to be re-installed on subsequent `restore()` attempts.

**Comment by hadley** [comment]
I think the motivating issue here has mostly been resolved, and what hasn't been substantially overlaps with #1188
