### ISSUE TITLE
Running a shiny app from command prompt uses the default library path

### ISSUE THREAD

**Issue by Ljupch0** [rstudio/renv#414]
Hi Kevin, great work on renv. It's been extremely useful especially with the new MRAN first download.

I ran into an issue when using a desktop shortcut to a shiny app (made with shinyShortcut). Namely, it runs the following command `Rscript.exe -e "shiny::runApp('C:/path_to_shiny_app', launch.browser = TRUE)`. 

I noticed that when the app is launched like this, it uses the windows default path and not the renv project specific package library, and as such packages are missing.

Do I need to add something in the project itself or rather in this command? Thank you.

**Comment by kevinushey** [comment]
The library paths for a project are typically loaded by the `renv` auto-loader, which is part of the project `.Rprofile`. This typically implies you need to launch R from the project root; e.g.

```
cd path\to\project
Rscript.exe -e "shiny::runApp('path/to/app')"
```

**Comment by kevinushey** [comment]
The alternative is to explicitly call `renv::load("/path/to/project")` before running the application.

**Comment by augustohassel** [comment]
Hi! Just to add one case, I was a bit confused when I've tried to launch my Shiny App using renv. I didn't know how to change (if I should do it..) the shiny-server.conf file. 
This message saved me a lot a trouble. I've just added expliclitly the path at the start of my global.R file and then everything has worked fine.. Tks!

**Comment by drag05** [comment]
@augustohassel 
Hello Augusto, I am very interested in this subject relating to Shiny Server. The server I work on shows the Index file for all installed apps at start and I would like to have a more elegant start page, at least having friendly name links grouped by activity. 

I am thinking of creating a web page to connect to all the Shiny apps inside the server through icons or, as mentioned before, friendly name links. 

You mention of adding the path to the global.R: which global.R is this? Shiny app's global.R or another? Thank you!
