### ISSUE TITLE
init() on an initialized project: allow an option to "cancel"

### ISSUE THREAD

**Issue by daattali** [rstudio/renv#415]
When wanting to update your local library, it's not unreasonable to accidentally call `init()` instead of `restore()`

```
> renv::init()
This project already has a lockfile. What would you like to do? 

1: Restore the project from the lockfile.
2: Discard the lockfile and re-initialize the project.
3: Activate the project without snapshotting or installing any packages.
```

There should be an additional option "4: Cancel" to exit this

**Comment by kevinushey** [comment]
FWIW you can also cancel by sending an interrupt (with `Ctrl + C`)

**Comment by daattali** [comment]
That actually didn't work (at least on windows). I could only cancel with Escape. But this option isn't for me, it's for people who get to this message and freak out and don't know what to do.
