### ISSUE TITLE
If I delete my local cache (c:/users/d/appdata/local/renv) then strange things happen

### ISSUE THREAD

**Issue by daattali** [rstudio/renv#416]
I tried adding renv to an existing project (`renv::init()` on an existing project) and checked it into git. I wanted to try to mimic what would happen to a different person on a different machine, so I deleted my project locally, re-cloned from git (which means I didn't have the `renv/library/` anymore), deleted the local cache, and tried using renv. 

Things did not work well. I know we're not expected to delete that folder, but the problems I ran into seem like they shouldn't happen.

When I ran `renv::init()` it told me that this project already has a lock file and asked me what to do. So I thought "ok, maybe I need to use `restore()` instead of `init()`. So to make sure I get a fresh start, I again deleted the local cache and again deleted the project locally and again re-cloned from git.

Now I ran `renv::restore()`. I received the "Welcome to renv! It looks like this is your first time..." message, which makes sense since I deleted the cache. When I said "y" I want to proceed, I got a message 

```
The library is already synchronized with the lockfile.
```

Strange. I looked inside `renv/library/` and the only package in there was `renv`. So it did not work. After restarting my RStudio session and again running `renv::restore()`, now it actually attempted to install the packages locally.

Also, I kept running into this issue https://github.com/rstudio/rstudio/issues/6799

I know I'm doing things I shouldn't be doing 🙈

**Comment by kevinushey** [comment]
Can you please distill this to a reproducible example?

**Comment by daattali** [comment]
I normally would but I really don't have the bandwidth to do more testing so I'll just close it
