### ISSUE TITLE
Warning: closing unused connection

### ISSUE THREAD

**Issue by llrs** [rstudio/renv#418]
Hi, I am testing this on a repository and I got a warning. I know it is not reproducible but I cannot do anything and maybe you know about it or it helps you uncover some obscure bug. 

```r
In sys.parent() :
  closing unused connection 3 (/home/user/.local/share/renv/cache/v5/R-3.6/x86_64-pc-linux-gnu/slam/0.1-47/73c92e0f6f2a29786505152040c35825/slam/help/aliases.rds)
```

**Comment by kevinushey** [comment]
Thanks -- please let me know if you're able to get a reproducible example.

**Comment by hadley** [comment]
Closing because it's been almost 3 years 😄
