### ISSUE TITLE
Infinite recursion if .Rprofile is in $HOME

### ISSUE THREAD

**Issue by asodja** [rstudio/renv#42]
This might not be common use case to have project root in $HOME. But when running project in docker one might have it there.

The issue seems to be, that source('activate.R') is called recursively when one have project root in $HOME or in other words when .Rprofile is in $HOME (~/.Rprofile). 

The issue seems to be in 'activate.R' in lines:

`# source the user profile if any, respecting R_PROFILE_USER`
`profile <- Sys.getenv("R_PROFILE_USER", unset = "~/.Rprofile")`
`if (file.exists(profile)) source(profile)`

**Comment by kevinushey** [comment]
You could work around this by ensuring `R_PROFILE_USER` is set to either an empty string or a non-existent path.

I'll see if there's something smarter that `renv` can do here as well.

**Comment by kevinushey** [comment]
Can you let me know if https://github.com/rstudio/renv/commit/8e1a7aa305618a0486428b3de475f139322bd021 helps?

**Comment by asodja** [comment]
It works with renv 0.2.0-56, although it seems that activate.R is not updated when you do renv::upgrade(). So if I first install 0.2.0-55 and do renv::upgrade() activate.R is not updated. Is that expected behaviour?

**Comment by kevinushey** [comment]
I'm not able to reproduce this behavior. Can you provide any other details?

**Comment by asodja** [comment]
You are right, It works fine. Problem was, that I was testing with .Rprofile in $HOME with version without recursion fix. So when I ran upgrade there was stackoverflow due to infinite recursion and activate.R was not updated. I suspect that was the reason. 

I think you can close this issue.

**Comment by mstr3336** [comment]
I think I've noticed this problem also - If you try to 

```
source("hard/path/to/project_root/renv/activate.R")
```

but the actual working directory isn't that of the project (This situation is probably not too unusual in HPC batch submission processes), it doesn't appear to resolve renv according to the project root correctly, I've noticed, it seems to do some work in whatever `getwd()` returns (I saw a `~/renv` directory, basically)

I'm not sure if this is fixed by [8e1a7aa](https://github.com/rstudio/renv/commit/8e1a7aa305618a0486428b3de475f139322bd021), though.

**Comment by kevinushey** [comment]
@mstr3336 the activate script is not designed to be sourced that way -- the working directory needs to be the same as the project root when activate.R is sourced.

You should change the working directory to the project root first.

**Comment by mstr3336** [comment]
@kevinushey , that's what I wound up doing, and it worked fine for me :) I wasn't too sure if the behaviour was intentional, or something you'd consider a bug, or perhaps an informative error message might help address the problem. 
Cheers!
