### ISSUE TITLE
Following XDG_CACHE_HOME specification

### ISSUE THREAD

**Issue by birnbera** [rstudio/renv#420]
Currently, on Linux, `renv` uses the environment variable `XDG_DATA_HOME` for setting the `renv` global storage path. Unless the `RENV_PATHS_CACHE` environment variable is set, it seems that the default is to store the cache in the `$RENV_PATHS_ROOT/renv/cache`, which ultimately uses `$XDG_DATA_HOME/renv/cache` (if that variable is set).

For completeness and simplicity of configuration, it would be nice if you could use `$XDG_CACHE_HOME` to set the location of the cache directory when `RENV_PATHS_CACHE` is not set.

In any case, thanks for maintaining this great package! It's made analyses done in R much more reproducible 😄.

Here's the full [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for anyone who is interested.

**Comment by hadley** [comment]
It looks like this is already the case: 

https://github.com/rstudio/renv/blob/6c0e8be69ff683c0d2b7c62c371783663f293b5d/R/paths.R#L232-L236

`renv_paths_root_default_impl_v2()` now calls `tools::R_user_dir("renv", "cache")` which is documented to respect the `XDG_CACHE_HOME` env var.
