### ISSUE TITLE
Renv outputs to stdout instead of stderr

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#428]
I have noticed that recent renv 10.0 started printing to stdout instead of stderr. 

```
* Project '/opt/program' loaded. [renv 0.10.0]
```

I don't think this is ok. Output of the program is normally consumed by other tools, so renv messages get intermingled with the program output. `message` or `warning` should be used instead.

**Comment by vspinu** [comment]
Well, I see that `--slave` is respected internally, which I wasn't using which solves the issue, but still stderr could be logged otherwise.

**Comment by vspinu** [comment]
Some messages seem to be ignoring --slave option as well:

```
oot@931de2a9fd13:/opt/program# R --slave
* The project and lockfile are out of sync -- use `renv::status()` for more details.
```

In my case I know why it's out of sync, production system has fewer dirs and thus fewer libraries are detected.

**Comment by kevinushey** [comment]
This would also be avoided by turning off the synchronization check, via

```
options(renv.config.synchronized.check = FALSE)
```
