### ISSUE TITLE
allow package records with explicit source path

### ISSUE THREAD

**Issue by michaelhogersosis** [rstudio/renv#43]
It would be great if the renv.lock file can also accommodate a library that is installed either from a local .tar.gz file or via devtools::install_github(, auth_token = ...). I am not sure if this is easy to facilitate though. 

Great work on this library, incredibly useful!

**Comment by kevinushey** [comment]
How should a local tarball be handled? It's more challenging because we cannot automatically infer an appropriate source; that is, if we need to download and install the package in the future where should we go to download / retrieve it?

renv does understand how to restore packages from private GitHub repositories as long as the `GITHUB_PAT` token is set. Does that help accomplish what you need?

(we don't have a mechanism for associating different auth tokens with different packages, though -- is that what you require?)

**Comment by cderv** [comment]
> How should a local tarball be handled? It's more challenging because we cannot automatically infer an appropriate source; that is, if we need to download and install the package in the future where should we go to download / retrieve it?

does renv plan to facilitate the creation of a local ran like packrat ? Or support the source folder like packrat did ? 

For some internal packages not published on cran, we already use those feature to deploy and restore project. 

It was before RStudio Package Manager that I know should fill this gap for company, but sometimes it is not needed to publish a project package in a company repository only if the project uses. having the hability to provide a tar.gz somewhere renv expected to be could be useful. 

I have in mind something like a local per-project cranlike repo in folder that renv would expect to exist if a the lockfile says a package comes from a local source. This local repos would be to populated before restoring. Just Ideas. 
Does it make sense ?

**Comment by kevinushey** [comment]
`renv` does support local CRAN-like repositories; e.g. you should be able to specify a CRAN repository on-disk with a file format like:

```
options(repos = c(CRAN = "file:///my/cran/repo"))
```

We could also consider supporting 'ad-hoc' repositories as Packrat did, though.

**Comment by cderv** [comment]
Yep. And I was thinking about `repos_*` functions from packrat that help setting up a repo to use with packrat. But it may not be a set of functions that should live in renv afterall... 🤔 

I believe having tools to create some local cran to use with a tool like renv could be useful for supporting local tar.gz.

**Comment by kevinushey** [comment]
IMHO that sort of CRAN repository management should be done by a separate package; e.g. there is [cranlike](https://cran.r-project.org/web/packages/cranlike/index.html).

**Comment by cderv** [comment]
I agree. I tried cranlike and it currently only help on managing the PACKAGES files efficiently. There is no function to create a structured folder as repo, upload sources and binaries, archive and remove packages. I'll open ideas there to work with renv. we'll see. thanks.

**Comment by slopp** [comment]
It is worth noting that miniCRAN and RStudio Package Manager both offer viable alternatives here

**Comment by cderv** [comment]
In fact, there is also [craneur](https://github.com/ColinFay/craneur) and drat that have tools that could help.

I think building a local cran like repo, or using a cranlike server is a good solution to work with not on CRAN packages.

**Comment by michaelhogersosis** [comment]
@kevinushey the GITHUB_PAT environment variable is already very helpful, thank you.

**Comment by kevinushey** [comment]
`renv` will now support local tarballs (see `?paths` + `RENV_PATHS_LOCAL`); I'm going to leave this issue open as a reminder for me to add a vignette.

**Comment by kevinushey** [comment]
I've added a small vignette on this topic: https://rstudio.github.io/renv/articles/local-sources.html

Let me know if this works for you or if you have any other trouble.

**Comment by kurlare** [comment]
Hey @kevinushey, when I installed the package from a local file (not pointing to a specific repo), `renv.lock` listed that package source as CRAN.  Now when I go to install it in another location, `renv::restore` is looking for the package on CRAN, and so it fails.  I tried specifying `RENV_PATHS_LOCAL` to the folder with my local file, but it doesn't seem to be checking there.  Can you tell me what I'm doing wrong here?  Thanks, I appreciate your work here and with packrat.

**Comment by kevinushey** [comment]
@kurlare I'll take a look. For completeness, can you tell me how you're installing the R package?

I _think_ modifying the lockfile by hand so that the Source is 'local' instead of 'CRAN' would also work.

**Comment by michaelhogersosis** [comment]
@kurlare @kevinushey I seemed to have a similar issue where I was installing packages from the https://cloud.r-project.org/ mirror on Windows, but when installing it again via the renv.lock in a Docker container the source would -always- be set to mran.microsoft.com. I will come back on this with a more detailed description if it occurs again. I ended up fixing it with chooseCRANmirror().

**Comment by kevinushey** [comment]
`renv` doesn't track the actual CRAN mirror used when a package was installed (in fact, it's not possible in general for `renv` to know what repository was used when a package was installed) so whatever is reported by `getOption("repos")` is used during restore.

`renv` will save the current repositories into the lockfile and use that when performing a restore; are you seeing `mran.microsoft.com` in `renv.lock`?

**Comment by michaelhogersosis** [comment]
There was no mran.microsoft.com saved in renv.lock. The reason I mention this is because the mran.microsoft.com mirror seemed relatively outdated, hence a renv.lock with relatively new library versions would have trouble installing from an outdated mirror. For now I simply fixed this by consistently setting chooseCRANmirror() on my two different environments.

**Comment by kevinushey** [comment]
Do you set that repository somewhere else (e.g. in your `.Rprofile` or something similar)?

The repository selection must be coming from somewhere but `renv` doesn't explicitly request usage of MRAN.

**Comment by kurlare** [comment]
Sure, I am working on Mac and have a custom package called `hosta` at the following location:

`/Users/kurlare/RProjects/localCRAN/src/contrib/hosta_1.0.tar.gz`

Then I run

```
renv::init()

install.packages("/Users/kurlare/RProjects/localCRAN/src/contrib/hosta_1.0.tar.gz", repos = NULL, type = "source")

renv::snapshot()
```

The lockfile then looks like this:

```
[R/Package/hosta]
Package=hosta
Version=1.0
Source=CRAN
Hash=4ff6f91f39e814a159b4454d4ae82aa8
```

If I manually edit the lockfile to specify `Source=` as anything other than CRAN, running `renv::snapshot()` will force me to change it back to CRAN.  The only other option is to abort the snapshot.

**Comment by kevinushey** [comment]
The problem (I suspect) is that even though you're installing from a local tarball, that package is still from a CRAN-like repository, and even declares so in its DESCRIPTION file:

```
Repository: CRAN
```

`renv` uses that as a hint that a package was retrieved from CRAN, and so should be retrieved from CRAN in the future.

I'm not sure what the best solution here is. You could remove `Repository: CRAN` from your local install, or `renv` could learn to fall back to 'local' package sources during restore. Or, if possible, you could make that local CRAN-like repository available during later restores, and make sure its included as one of the active repositories.

**Comment by kurlare** [comment]
Interesting.  What about having an option to specify Source = /path/to/tar.gz in the lockfile?

**Comment by kevinushey** [comment]
You could also just set `Source=local` (so that the package is looked for in `RENV_PATHS_LOCAL`).

We could also consider something like:

```
Source=local
Path=/path/to/tar.gz
```

to allow for explicit paths to certain packages.
