### ISSUE TITLE
renv::init(bare = TRUE) to all child directories 

### ISSUE THREAD

**Issue by jhaseon** [rstudio/renv#431]
Hello, 

Great work with the package.

I am using R installed via conda, and been facing some issues with renv so I have been looking into using the feature:
>  `renv::init(bare = TRUE)`

However packages are only sent to the library if they are installed in the directory with renv. Is there an option to have all packages installed in adjacent directories be sent to the renv library?

## Project Strcture:
project 
├── renv
│   ├── library
│   └── staging
└── shiny
    └── www

### Ex 1: 
`$ project R -e "shiny::runApp()"`
> This gets installed in the renv library

### Ex 2:
`$ shiny R -e "shiny::runApp()"`
> This gets installed in the conda R library

**Comment by kevinushey** [comment]
`renv::init()` writes an autoloader to the project `.Rprofile`, and this is the mechanism used to ensure that `renv` is initialized for a project on load.

If you want `renv` to "load" a parent directory, you can do so by explicitly calling

```
renv::load("/path/to/project/root")
```

and you could also accomplish the same via `.Rprofile`s within each directory if needed.

**Comment by kevinushey** [comment]
Closing this since I think the above answers your question -- please feel free to re-open if you have more questions. You might also consider asking on the community forums, at https://community.rstudio.com/ using the tag `renv`.

**Comment by jhaseon** [comment]
I've tried your suggestions specifically putting an .Rprofile to each directory, but it just creates new renvs in each directory.

Essentially, I want to be able to use one renv in the project folder and have libraries downloaded in children folders be stored in the project folder renv. 

Is this something possible currently? Maybe I missed on some documentation located here.

**Comment by kevinushey** [comment]
You might also try something like:

```
owd <- setwd("/path/to/project/root")
source("renv/activate.R")
setwd(owd)
```

**Comment by jhaseon** [comment]
I did something like this in my .Rprofile in the child directory
`project_dir <- dirname(getwd())

renv_path <- file.path(project_dir)
print(renv_path)
renv::load(renv_path)`

I'm still new to R so I'll try your method as well.
