### ISSUE TITLE
Feature Request: Manage R Environments through terminal in a "conda" fashion

### ISSUE THREAD

**Issue by jtelleriar** [rstudio/renv#433]
Would it be possible to manage R Package Environments directly from terminal, in a "conda" fashion?

http://know.continuum.io/rs/387-XNW-688/images/conda-cheatsheet.pdf

http://www.jadejaber.com/documents/conda-cheatsheet.pdf

**Comment by kevinushey** [comment]
In theory, you could just invoke `renv` using e.g.

```
R -e "renv::init()"
```

Perhaps not as pretty as just writing `renv init`, but at least still doable.

**Comment by jtelleriar** [comment]
Implementing an argument parser on the terminal though Python is easy with `argparse` module:

https://docs.python.org/3/library/argparse.html

For R I ignore how could be done...

**Comment by jtelleriar** [comment]
Well conda also seems to have Python as a dependency indeed, as its core is pure Python:

https://github.com/conda/conda

**Comment by cderv** [comment]
@jtelleriar If you don't know it already I think you could be interested in the {jetpack} library
https://github.com/ankane/jetpack
There is a cli mode in the 📦 : https://github.com/ankane/jetpack#command-line

Currently it is based on packrat, but there is plan to switch to `renv` according to the issue containing the plan. 

Hope it helps.

**Comment by jtelleriar** [comment]
Thanks @cderv for letting me know about `jetpack` library, it looks promising, will definitely give it a try :)

However, it would still be beneficial for renv to have terminal access (Specially for productionazing ML models), the cli.R mode of your package could be a startpoint: 

https://github.com/ankane/jetpack/blob/master/R/cli.R

**Comment by cderv** [comment]
> the cli.R mode of your package could be a startpoint:

It is not my package. 😉  I just happen to know it exists and have a command line mode ☺️

**Comment by kevinushey** [comment]
I put together a dumb CLI tool for `renv`. It's distributed with the `renv` package, and is available at this location:

```
path <- if (Sys.info()[["sysname"]] == "Windows") "bin/renv.cmd" else "bin/renv"
renv <- system.file(path, package = "renv")
```

You can put this on the PATH if you want; e.g. by running something like:

```
system(paste("ln -nfs", renv, "/usr/local/bin/renv"))
```

All it really does is take a shell command and translate it into the equivalent `renv` function call, so that e.g.

```
renv init path/to/project
```

would just run the equivalent of `renv::init("path/to/project")`.

**Comment by jtelleriar** [comment]
Thank you!

Will test it during the following week and let you know.

If works as expected, we could even document it and create a Cheatsheet for
renv ;) Reproducibility is a serious topic.

By the way:
a) conda allows you to swap between different versions of R within the
terminal:
https://docs.anaconda.com/anaconda/user-guide/tasks/using-r-language/
b) And is Project Agnostic, that is, you can have a conda environment
shared through different projects.
c) You can swap between different active environments dynamically: conda
activate r-env (Example)

Thank you!

Best,
Juan

>

**Comment by hadley** [comment]
Now tracking in #1055
