### ISSUE TITLE
Feature Request: Use RStudio Package Manager or MRAN

### ISSUE THREAD

**Issue by jtelleriar** [rstudio/renv#434]
Could renv, for a given "frozen" package version, pick up the required binary packages from MRAN or RStudio Package Manager, without requiring source compilation?

https://packagemanager.rstudio.com/client/#/
https://mran.microsoft.com/timemachine

**Comment by kevinushey** [comment]
`renv` 0.10.0 already does this for Windows + macOS for MRAN binaries.

I'm thinking about making this change for Linux as well, but we also need to make sure missing system dependencies are properly handled. See also: https://github.com/rstudio/renv/issues/430

**Comment by jtelleriar** [comment]
Great thank you!
