### ISSUE TITLE
Unable to install non-default branch of package from GitLab

### ISSUE THREAD

**Issue by jistria** [rstudio/renv#436]
Installing packages from GitLab always returns the version on the default branch, regardless of whether you specify a different branch. 

I believe the problem is caused by this line:
https://github.com/rstudio/renv/blob/3c86e40c8e09f2e26fcfae3c953a60ac96c29aec/R/retrieve.R#L220

For packages from GitLab, `record$RemoteSha` is always `NULL`. 

Substituting `record$RemoteSha` with `record$RemoteRef` resolves the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- should be fixed up on master now.
