### ISSUE TITLE
modify throws an error

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#44]
currently I get an error after closing `usethis::file.edit()` window
```r
> utils::file.edit("renv.lock")
Error in editor(file = file, title = title) : 
  Error in parse(targetFile) : renv.lock:1:1: unexpected '['
1: [
    ^
You can attempt to correct the error using renv.lock = edit()
Call `rlang::last_error()` to see a backtrace
```
Got the same with file.edit
```r
> utils::file.edit("renv.lock")
Error in editor(file = file, title = title) : 
  Error in parse(targetFile) : renv.lock:1:1: unexpected '['
1: [
    ^
You can attempt to correct the error using renv.lock = edit()
Call `rlang::last_error()` to see a backtrace
```
don't know if it will stay or not (seems like it would have been removed after #15)...

**Comment by kevinushey** [comment]
`modify()` had a different purpose before: it now exists specifically for editing `renv.lock`. I'll see if I can figure out what's going on.

**Comment by kevinushey** [comment]
Looks like this is an RStudio bug (only on Windows). Filed here: https://github.com/rstudio/rstudio/issues/4588
