### ISSUE TITLE
Migrate changing versions

### ISSUE THREAD

**Issue by ankane** [rstudio/renv#440]
Hi, thanks for renv! I'm seeing an issue when trying to migrate from Packrat. Versions are different between lockfiles:

- [packrat.lock](https://gist.github.com/ankane/65a74a4874f7b5c9013bad99d2daed4f#file-packrat-lock)
- [renv.lock](https://gist.github.com/ankane/65a74a4874f7b5c9013bad99d2daed4f#file-renv-lock)

A few examples are:

- `withr` changes from `2.1.2` to `2.2.0`
- `pillar` changes from `1.4.3` to `1.4.4`
- `padr` changes from `0.5.0` to `0.5.2`

To reproduce, create `packrat/packrat.lock` in a new directory, open an R session, and run:

```r
renv::migrate(packrat="lockfile")
```

**Comment by kevinushey** [comment]
Sorry, not reproducible:

```
> setwd(tempdir())
> 
> url <- "https://gist.githubusercontent.com/ankane/65a74a4874f7b5c9013bad99d2daed4f/raw/8aa67d31e7dffe14fd59d7e083a037819389e545/packrat.lock"
> 
> dir.create("packrat")
Warning message:
In dir.create("packrat") : 'packrat' already exists
> download.file(url, destfile = "packrat/packrat.lock")
trying URL 'https://gist.githubusercontent.com/ankane/65a74a4874f7b5c9013bad99d2daed4f/raw/8aa67d31e7dffe14fd59d7e083a037819389e545/packrat.lock'
Content type 'text/plain; charset=utf-8' length 6252 bytes
==================================================
downloaded 6252 bytes

> renv::migrate(packrat = "lockfile")
* The renv cache is already synchronized with the Packrat cache.
* renv support infrastructure has been written.
* Project '/private/tmp/RtmpjO42jV' has been migrated from Packrat to renv.
* Consider deleting the project 'packrat' folder if it is no longer needed.
> 
> packrat.lock <- packrat:::readLockFilePackages("packrat/packrat.lock")
> packrat.lock$withr
$name
[1] "withr"

$source
[1] "CRAN"

$version
[1] "2.1.2"

$requires
[1] NA

$hash
[1] "d534108bcd5f34ec73e9eb523751ba20"

> 
> renv.lock <- renv:::renv_lockfile_read("renv.lock")
> renv.lock$Packages$withr
$Package
[1] "withr"

$Version
[1] "2.1.2"

$Source
[1] "CRAN"
```

**Comment by ankane** [comment]
Hey @kevinushey, thanks for the quick response. I deleted `renv:::renv_paths_root()` and it's working as expected now, and haven't been able to reproduce since. Will report back if I can get a reproducible example from a fresh cache in the future.
