### ISSUE TITLE
Feature request: suppressing warnings for renv::activate()

### ISSUE THREAD

**Issue by ocschwar** [rstudio/renv#441]
Could we have an argument to activate() to ignore when a renv lock file lists packages that the local project no longer needs as dependencies?

**Comment by kevinushey** [comment]
Can you explain which warning you are seeing?

**Comment by ocschwar** [comment]
`e$ R

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

* Project '~/r_oschwarz/REhedge' loaded. [renv 0.10.0]
* The project and lockfile are out of sync -- use `renv::status()` for more details.
Loading required package: stats
> renv::status()
The following package(s) are no longer used in this project:
                     _
  MatrixModels         [0.4-1]
  RANN                 [2.6.1]
  RJSONIO              [1.3-1.4]
  RcppEigen            [0.3.3.7.0]
  SparseM              [1.78]
`

The reason for this is that this project uses zzz.R to import another project, and those packages are in the renv package for that reason. (The reason for this is protection of intellectual property among our developers and contractors.)

So this warning will be put out every time we start an R kernel, unless it can be suppressed.

**Comment by kevinushey** [comment]
You can set this option:

```
options(renv.config.synchronized.check = FALSE)
```

Or, as an environment variable:

```
RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE
```

I plan on disabling this by default in the next release of `renv` as most users have found the message annoying rather than helpful.

**Comment by ocschwar** [comment]
Perfect. Thank you!
