### ISSUE TITLE
Temporarily disabling search for dependencies

### ISSUE THREAD

**Issue by statnmap** [rstudio/renv#444]
Can there be an option to temporarily disabling dependencies search at startup and while installing new packages? I am looking for an option that disables all {renv} tests at startup, but sets the link to the internal {renv} libraries.  
 
I am working with big projects with multiple files to search in. I would like to avoid {renv} to search for dependencies each time I add a new package and each time I open a new session with `system()`.  

Indeed, the main problem is while using {future}. Setting a `mulitprocess` plan takes forever to setup all separate processes. I would like to be able to add an option in the `.Rprofile` so that {renv} only sets up the internal `.libPaths` with the correct symlink to the cache and nothing else.

**Comment by kevinushey** [comment]
See in `?renv::config` the `synchronized.check` option. In particular, you should be able to set the environment variable:

```
RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE
```

to disable this check on startup.

**Comment by kevinushey** [comment]
(note that this will be disabled by default in the next version of `renv`, given the number of users encountering difficulties with this check at startup)

**Comment by statnmap** [comment]
That's perfect. I set it up in .Rprofile, just before activation and it's much quicker.  
`Sys.setenv(RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE)` 
It's good that it will disabled by default.  
Thanks.
