### ISSUE TITLE
Add `.Rprofile` to `.Rbuildignore` when working within an R package project

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#447]
Hello!

Love renv!  I just set it up for a package I maintain.  I noticed `renv::init()` knew it was an R package, and added `^renv$` and `^renv\.lock$` to `.Rbuildignore`, but did not add the newly created `.Rprofile` file.  Is this intended?  It seems the file should also be included in `.Rbuildignore`. 

Thank you!

**Comment by kevinushey** [comment]
`.Rprofile` should already automatically be excluded from the built package tarball. Are you not seeing that?

**Comment by ddsjoberg** [comment]
Ah, you are of course correct!  Sorry about that!
