### ISSUE TITLE
R failure when opening Rstudio project with renv

### ISSUE THREAD

**Issue by allenbaron** [rstudio/renv#448]
When attempt to start an Rstudio project that uses renv I get a fatal error in R and Rstudio crashes:
![image](https://user-images.githubusercontent.com/21225409/83679168-cb6e4b00-a593-11ea-8c65-e9de289f8942.png)

Here's my R setup:
- R installed at "C:\R\R-3.6.3"
- etc/Renviron.site containing `RENV_PATHS_ROOT=C:/R/renv`
- etc/Rprofile.stie specifies a site-library: `.Library.site <- file.path(chartr("\\", "/", R.home()), "site-library")`

My project is located on another external hard-drive (directly connected to the computer).

Some tests I've done, all without errors:
- Open Rstudio with different project on same hard-drive (not using renv)
- Open R-3.6.3 (no Rstudio), navigate to project directory, and run `source("renv/activate.R")'
- Comment out `source("renv/activate.R")' in .Rprofile in project directory, startup Rstudio project, run source("renv/activate.R")

**Comment by edwinschut** [comment]
I have the same error this morning.  I closed my project yesterday around 18:00 pm, and this morning when i resumed my work i was unable to open this project.  

R setup

- Renv 1.0  with R 3.6.3 and the latest Rstudio.  
- My cache path is on the same disk as the project files.
-  Besides CRAN i use a local cran.

**Comment by edwinschut** [comment]
It's working again.  Nu clue why, but here is my workaround: 

- Comment out `source("renv/activate.R")' in .Rprofile in project directory, startup Rstudio project, run source("renv/activate.R")
- Renv::update()
- Renv::snapshot()
- Restart R

**Comment by ercbk** [comment]
Just adding my experience. Upgraded to renv 0.10.0 with RStudio Version 1.2.5033 and R 3.6.2.  

With uncommented `source("renv/activate.R") in .Rprofile, my project load would hang. With it commented out, it still took minutes to load, but did load.  

Reverted back to renv 0.9.3, uncommented source("renv/activate.R") in .Rprofile and the project loaded immediately.

**Comment by kevinushey** [comment]
Please try executing:

```
cat(
  "RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE",
  file = "~/.Renviron",
  append = TRUE
)
```

to disable the startup synchronized check.

**Comment by allenbaron** [comment]
That worked for me. It starts fine now.

**Comment by kevinushey** [comment]
I think this should now be resolved with the latest releases of RStudio + `renv`, so I'm going to close this. Please feel free to re-open or file a new issue if you're still having trouble. Thanks!
