### ISSUE TITLE
Cache is not by default in ~/.renv/cache

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#45]
The doc says that 
https://github.com/rstudio/renv/blob/494ce53b8593a84eb2305ea7728008b097c8566b/vignettes/renv.Rmd#L145-L147

But it is not the case... It took me some digging to find it. 
by default we have
``` r
renv:::renv_paths_cache()
#> [1] "C:\\Users\\chris\\AppData\\Local/renv/R-3.5/cache/v2"
```
which is expected according to the code in [path.R](https://github.com/rstudio/renv/blob/master/R/paths.R)

I think the doc should be updated

**Comment by kevinushey** [comment]
Thanks! The cache was originally located there but I changed the location to use proper OS-specific paths. I'll update the documentation soon.
