### ISSUE TITLE
Setting RENV_PATHS_CACHE does not works

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#46]
Setting RENV_PATHS_ROOT seems to work
``` r
Sys.setenv(RENV_PATHS_ROOT="~/.renv")
renv:::renv_paths_cache()
#> [1] "~/.renv/R-3.5/cache/v2"
```

but only trying to change the cache does not
``` r
Sys.setenv(RENV_PATHS_CACHE="~/.renv/mycache")
renv:::renv_paths_cache()
#> [1] "C:\\Users\\chris\\AppData\\Local/renv/R-3.5/cache/v2"
```

I think there is something wrong here read here
https://github.com/rstudio/renv/blob/494ce53b8593a84eb2305ea7728008b097c8566b/R/paths.R#L67
is in fact
https://github.com/rstudio/renv/blob/494ce53b8593a84eb2305ea7728008b097c8566b/R/paths.R#L104
and `cacheroot` has the value `cache/v2` so the Env variable expected is `RENV_PATHS_CACHE/V2`

``` r
Sys.setenv(`RENV_PATHS_CACHE/V2`="~/.renv/mycache")
renv:::renv_paths_cache()
#> [1] "~/.renv/mycache"
```

I am not sure this is expected. Am I right ? 

If you want I can PR something and do other check like these.

**Comment by kevinushey** [comment]
Thanks! I appreciate the testing. I'll take a look at what's going on.

**Comment by kevinushey** [comment]
This should be fixed up on master now -- thanks for reporting!
