### ISSUE TITLE
Error on some OSs for GitHub Actions

### ISSUE THREAD

**Issue by CorradoLanera** [rstudio/renv#462]
I have followed [this](https://rstudio.github.io/renv/articles/ci.html#github-actions) to use Actions on `{renv}` enabled projects/packages starting from (a slight modification of) [this](https://github.com/r-lib/actions/blob/master/examples/check-full.yaml), ie running on develop branches too and excluding R-3.3 -- R-3.5 from being tested.

The error happened during the check stage. But issues come before (see [here](https://github.com/UBESP-DCTV/maparpav/runs/806448498?check_suite_focus=true#step:6:16)). Looking at that warning I tried to `renv::rebuild()` which seems to solve the initial warnings but not [the error](https://github.com/UBESP-DCTV/maparpav/runs/806531496?check_suite_focus=true#step:9:29) in the check stage. 

Note: R-CMD check action succeeded on Win OS; other [actions](https://github.com/UBESP-DCTV/maparpav/actions) (ie lintr, pkgdown, and test-coverage) succeeded as well (on macOS).

**Comment by kevinushey** [comment]
One part of the problem might be that you've committed your `renv` library to GitHub:

https://github.com/UBESP-DCTV/maparpav/tree/master/renv/library/R-4.0/x86_64-pc-linux-gnu

`renv` normally ensures this is excluded from your `.gitignore` so this library isn't published. Was putting that library on GitHub intentional?

**Comment by CorradoLanera** [comment]
mmm... no. So, as a standard procedure, have I to initialize the repo before to activate `renv`?
I'll do it now and then come back! Just a moment :-)

**Comment by CorradoLanera** [comment]
Yeah!!! It was that easy (plus restore the original order to first install the system dependencies and then the packages :-)).

Thank you!!!

Could be useful to include the `renv/.gitignore` in a non git project too? I think it shouldn't harm, but it could save from this issue if, in some future, the project will go under git control. What do you think?

**Comment by CorradoLanera** [comment]
That seem solve some issue but remain some system dependencies problem (but at this point I do not think it is a `{renv}` issue anymore, right?)

**Comment by kevinushey** [comment]
That sounds right to me -- if packages are failing to install or run because system dependencies are missing, that's ultimately outside of `renv`'s purview. (Hopefully it won't be some day in the future!)

**Comment by CorradoLanera** [comment]
Power! Thank you very much for your time and help :-)!

**Comment by CorradoLanera** [comment]
I have deleted all the actions, the `renv` folder, the `lock.file` and `.Rprofile`; committed and pushed. re initialized `renv` (with option `explicit`), re added actions; committed and pushed... and everything go smooth!! 🎉 https://github.com/UBESP-DCTV/maparpav/actions/runs/147942733

thank you again!

**Comment by kevinushey** [comment]
Fantastic! I'm glad to hear it :-)
