### ISSUE TITLE
Include on website instructions for uninstalling renv

### ISSUE THREAD

**Issue by enfascination** [rstudio/renv#463]
I'm using renv within a conda env to make a complex flow reproducible.  My first pass didn't work and I'm trying to get a clean slate with renv.  I have a guess about what I have to do, but explicit uninstall instructions would be a big help.

**Comment by kevinushey** [comment]
Thanks! I've provided some instructions here: https://rstudio.github.io/renv/articles/renv.html#uninstalling-renv

Let me know if that's sufficient.
