### ISSUE TITLE
renv not finding user library ?

### ISSUE THREAD

**Issue by ScaonE** [rstudio/renv#464]
Dear all,

Using either renv 0.10.0 or the latest dev version 0.10.0.66, it seems that renv doesn't find the right directory for my R 3.5.1 user library, see the pic below :

![new](https://user-images.githubusercontent.com/1412265/85871502-c84f2f00-b7ce-11ea-8051-716cfa0cf587.PNG)

Right dir should be = C:/Users/FR_SCAERW/Documents/R/R-3.5.1/library, but R_LIBS_USER is instead set to a weird AppData/Local/Temp/... directory.

According to this screenshot, my pre-existing system library contains ~30 packages, which is far from the actual number & would sadly make a lot of package re-installed (with the same version) if I use renv in this project.

If I switch back to renv 0.9.2, then the right directory is setup in the R_LIBS_USER env-var, and the pre-existing user library contains hundreds of packages, see screenshot below.

![old_version](https://user-images.githubusercontent.com/1412265/85871776-2da32000-b7cf-11ea-9a5a-d4c7328476c7.PNG)

Any tips ? (I definitely want to use 0.10.0)

Ps : I did check [issues](https://github.com/rstudio/renv/issues?q=is%3Aissue+R_LIBS_USER) mentioning R_LIBS_USER but failed to find something for my case

**Comment by kevinushey** [comment]
This seems like fallout from https://github.com/rstudio/renv/issues/334. Can you please share the output of:

```
getwd()
Encoding(getwd())
```

within your project?

Also, note that while the library path looks odd, it should still work. That folder is a junction back to the "real" library path, and installing packages into that junction should effectively install them into the "real" library path. Does `renv` still work properly beyond the UI issues you see in RStudio?

**Comment by ScaonE** [comment]
> Project 'C:/Statistiques/Test/renv_mcf' loaded. [renv 0.10.0-66]

`R.version`              

> platform       x86_64-w64-mingw32          
> arch           x86_64                      
> os             mingw32                     
> system         x86_64, mingw32             
> status                                     
> major          3                           
> minor          5.1                         
> year           2018                        
> month          07                          
> day            02                          
> svn rev        74947
> language       R                           
> version.string R version 3.5.1 (2018-07-02)
> nickname       Feather Spray               

`packageVersion("renv")`
> [1] ‘0.10.0.66’

`Sys.getenv()["R_LIBS_USER"]`
> R_LIBS_USER        C:/Statistiques/Test/renv_mcf/renv/library/R-3.5/x86_64-w64-mingw32;C:/Users/FR_SCAERW/AppData/Local/Temp/RtmpmAJsRU/renv-system-library

`getwd()`
> [1] "C:/Statistiques/Test/renv_mcf"

`Encoding(getwd())`
> [1] "unknown"

**Comment by ScaonE** [comment]
I fail to see the link with issue #334 , as this one was related to the presence of special characters in paths.
Here the paths are :
User library = C:/Users/FR_SCAERW/Documents/R/R-3.5.1
R Project = C:/Statistiques/Test/renv_mcf
Which char could cause issue in there ?

**Comment by kevinushey** [comment]
I think I'm misunderstanding what the issue you're seeing here is.

Normally, when using `renv`, the user library shouldn't be used -- you just have a project library, plus an (optionally) sandboxed system R library.

Is the problem here that `renv` is mutating `R_LIBS_USER` in an expected way?

**Comment by ScaonE** [comment]
Thing is, when my colleague tried to launch this renv_initialized project, the same "issue" occured (wrong user library path detected). Thus, the project initialization took quite long, given that almost all packages had to be installed "from scratch" (despite being for the most part already present in the R 3.5.1 user library with the right version). I thought this was something that renv tried to avoid.
Sorry I if may be using the wrong terminology for "user library".

**Comment by ScaonE** [comment]
And yes I was expecting that renv 0.10.1 would use the same R_LIBS_USER as renv 0.9.2, which is not the case in my limited testing.

**Comment by mdbrannock** [comment]
I'm having the same issue, though perhaps I don't understand what `renv` does. I recently migrated to a new computer and have had to re-clone all my existing projects. When I try to `restore()` from the lock file it reinstalls every package, including the default R packages that I always have in my system library with the same version as in the lock file.

My impression was that `renv` only reinstalls packages if you do not already have that version installed in your system library.

**Comment by mdbrannock** [comment]
I should point out that I'm on MacOS Catalina and using `renv` version `0.11.0`

**Comment by mdbrannock** [comment]
Update: After running `renv::snapshot()` everything is behaving how I expected. This is a still disconcerting, because it forced me to update all of my packages. In my case that wasn't a big deal, but it could be for others.

**Comment by kevinushey** [comment]
Every project using `renv` maintains its own private project library, independent of the user library. This does imply that `renv::restore()` will need to reinstall packages into that project library, even if those same packages are indeed installed currently within the user library. (By default, `renv` projects don't use or see the user library; see `user.library` in `?renv::config` if you'd like to change that.)

We could consider whether we could just re-use the packages existing in the user library during restore if they're compatible with what's requested, though. (This is effectively what `renv::init()` does, for what it's worth)

**Comment by mdbrannock** [comment]
Thanks, @kevinushey, that's helpful. I was confused about how the global cache works. Everything is working how it's supposed to (at least for me). Ultimately moving the project to a new computer didn't prove as easy as I hoped, but that was mostly due to having to install an old version of `Matrix`, which required pointing R to a Fortran compiler.
