### ISSUE TITLE
Weird error when knitting

### ISSUE THREAD

**Issue by ivan-paleo** [rstudio/renv#467]
I am trying to render an Rmd file to a GitHub document. This worked without any issue until now. I have changed only text.

When I try to render it with the "knit" button in RStudio, I get the following error:
Error in file.exists(children) : 
  file name conversion problem -- name too long?
Calls: source ... renv_dependencies_find_dir -> renv_dependencies_find_dir_children -> file.exists
Traceback (most recent calls last):
49: source("renv/activate.R")
48: withVisible(eval(ei, envir))
47: eval(ei, envir)
46: eval(ei, envir)
45: local(...)
44: eval.parent(substitute(eval(quote(expr), envir)))
43: eval(expr, p)
42: eval(expr, p)
41: eval(quote(...), new.env())
40: eval(quote(...), new.env())
39: renv_bootstrap_load(project, libpath, version)
38: renv::load(project)
37: renv_load_finish(project, lockfile)
36: renv_load_report_synchronized(project, lockfile)
35: renv_project_synchronized_check(project, lockfile)
34: quietly({
        libstate <- snapshot(project = project, library = library, 
            lockfile = NULL, force = TRUE)
        synchronized <- renv_status_check_synchronized(project = project, 
            lockfile = lockfile, library = library, libstate = libstate)
    })
33: withCallingHandlers(expr, warning = function(c) invokeRestart("muffleWarning"), 
        message = function(c) invokeRestart("muffleMessage"), packageStartupMessage = function(c) invokeRestart("muffleMessage"))
32: snapshot(project = project, library = library, lockfile = NULL, 
        force = TRUE)
31: renv_lockfile_create(project, library, type)
30: renv_snapshot_r_packages(library = library, project = project) %>% 
        renv_snapshot_filter(project = project, type = type) %>% 
        renv_snapshot_fixup()
29: eval(call, envir = parent.frame())
28: eval(call, envir = parent.frame())
27: renv_snapshot_fixup(renv_snapshot_r_packages(library = library, 
        project = project) %>% renv_snapshot_filter(project = project, 
        type = type))
26: renv_snapshot_fixup_renv(records)
25: renv_snapshot_r_packages(library = library, project = project) %>% 
        renv_snapshot_filter(project = project, type = type)
24: eval(call, envir = parent.frame())
23: eval(call, envir = parent.frame())
22: renv_snapshot_filter(renv_snapshot_r_packages(library = library, 
        project = project), project = project, type = type)
21: renv_snapshot_filter_implicit(project, records)
20: renv_snapshot_filter_impl(project, records, project)
19: renv_snapshot_dependencies(source)
18: withCallingHandlers(dependencies(source, progress = FALSE, errors = errors), 
        renv.dependencies.error = renv_dependencies_error_handler(message, 
            errors))
17: dependencies(source, progress = FALSE, errors = errors)
16: delegate(renv_dependencies_impl)
15: eval(call, envir = parent.frame(2))
14: eval(call, envir = parent.frame(2))
13: <condition-handler>(...)
12: renv_dependencies_find(path, root)
11: lapply(path, renv_dependencies_find_impl, root = root)
10: FUN(X[[i]], ...)
 9: renv_dependencies_find_dir(path, root)
 8: lapply(children, renv_dependencies_find_impl, root = root)
 7: FUN(X[[i]], ...)
 6: renv_dependencies_find_dir(path, root)
 5: lapply(children, renv_dependencies_find_impl, root = root)
 4: FUN(X[[i]], ...)
 3: renv_dependencies_find_dir(path, root)
 2: renv_dependencies_find_dir_children(path, root)
 1: file.exists(children)
Execution halted

There is no README.md in the directory and I do even not understand why renv is called. The README.Rmd also does not call any file.

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
Matrix products: default
locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    
attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     
loaded via a namespace (and not attached):
 [1] compiler_4.0.2  htmltools_0.4.0 tools_4.0.2     rstudioapi_0.11 yaml_2.2.1     
 [6] tinytex_0.23    crayon_1.3.4    Rcpp_1.0.4.6    rmarkdown_2.1   knitr_1.28     
[11] xfun_0.14       digest_0.6.25   rlang_0.4.6     renv_0.10.0     evaluate_0.14

> RStudio.Version()$version
[1] ‘1.3.959’

I attach the problematic Rmd file.
[README.zip](https://github.com/rstudio/renv/files/4856412/README.zip)

**Comment by kevinushey** [comment]
This should be fixed in the latest CRAN release of `renv` (0.11.0) -- can you try updating?

**Comment by ivan-paleo** [comment]
Updating renv solved the problem.
I should have tried that first, sorry for the noise...!

**Comment by kevinushey** [comment]
No worries! Glad to hear everything is working now.
