### ISSUE TITLE
Replace references to deprecated flag `--slave` with `-s` or `--no-echo`

### ISSUE THREAD

**Issue by scottmmjackson** [rstudio/renv#468]
https://github.com/rstudio/renv/blob/3cb0f1516d73b0b31596484a8cb54ee0e53282c8/R/session.R#L10

https://github.com/rstudio/renv/blob/9fbf93e7023679fc2f6ae7bdb74e6cee565b1702/tests/testthat/test-activate.R#L21

https://github.com/rstudio/renv/blob/4e91e2f7c039f631dbce8bc565c3286c1e979baa/R/repos.R#L32

https://github.com/rstudio/renv/blob/8216d005e5ce24f5254b03f95345041681c9c789/tests/testthat/test-profiles.R#L23

https://github.com/rstudio/renv/blob/31073ae174e828c0c6be31b66b7532216073df86/R/run.R#L92

https://github.com/rstudio/renv/blob/3e92b4fc2278bf969505c94bb68a266f1eb964ad/vignettes/docker.Rmd#L136

From R 4.0.1 forward, `--slave` is deprecated: https://cran.r-project.org/doc/manuals/r-release/NEWS.html

https://github.com/wch/r-source/commit/f1ff49e74593341c74c20de9517f31a22c8bcb04

`-s` is an undocumented alias for the flag formerly `--slave` now `--no-echo` and thus ensures backwards compatibility. Alternatively, going forward, we could trap for the R version to be called and choose `-s` or `--no-echo` as needed.

**Comment by kevinushey** [comment]
Thanks! I've updated these usages.
