### ISSUE TITLE
Should upgrade offer to snashot version change in lockfile ?

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#47]
I just upgraded my version of renv to test last commits
```r
> renv::upgrade()
A new version of the renv package will be installed:

	[0.2.0-59] -> [0.2.0-68]

This project will use the newly-installed version of renv.

Do you want to proceed? [y/N]: Y
Retrieving 'https://api.github.com/repos/rstudio/renv/tarball/18b32a57463100e49c16246a5ee5aece32dc9029' ...
	OK [downloaded 121.9 Kb in 1.5 secs]
Installing renv [0.2.0-68] from GitHub ...
	OK (built from source)

Restarting R session...

Using libraries at paths:
- C:/Users/chris/Documents/R/win-library/3.5
- C:/Program Files/R/R-3.5.3/library
* Project '~/DEV_R/#Blogging/cderv' loaded. [renv 0.2.0-68]
```
I believe this should upgrade my renv version for the project. It seems the 📦 is not a the project library but in the cache
```r
> find.package("renv")
[1] "C:/Users/chris/AppData/Local/renv/R-3.5/bootstrap/x86_64-w64-mingw32/3.5/renv/0.2.0-68/renv"
```
I understand it modifies the infrastucture of renv inside the project
https://github.com/rstudio/renv/blob/18b32a57463100e49c16246a5ee5aece32dc9029/R/infrastructure.R#L3-L10

However, the lock file is not updated unless I run 
```r
> renv::snapshot()
The following lockfile fields will be updated:

  [renv]
  Version: [0.2.0-59] => [0.2.0-68]
  
The lockfile will be written to '~/DEV_R/#Blogging/cderv/renv.lock'.
Do you want to proceed? [y/N]: y
* Lockfile written to '~/DEV_R/#Blogging/cderv/renv.lock'.
```

I would expect upgrade to update the lock file or at least ask user to do so. What do you think ? 

It does not seem my project can work with another version of renv even if the lockfile says so...

I modify the version to previous one (with `renv::modify()`)
```r
> readLines("renv.lock", n = 2)
[1] "[renv]"           "Version=0.2.0-59"
```
and restarted the session.

The renv version loaded is `[renv 0.2.0-68]`, not like the renv.lock, but determine according to activate. However, this says that everything is ok
```r
> renv::status()
* The project is already synchronized with the lockfile.
```
```r
> renv::restore()
* The project is already synchronized with the lockfile.
```
What do you think ?

**Comment by kevinushey** [comment]
The version of `renv` loaded with a project is specified in `renv/activate.R` as opposed to the lockfile. I'm now not sure if this distinction is helpful / useful though. The intention was for `renv` to still be able to initialize without a lockfile.

**Comment by cderv** [comment]
What the renv version of a lockfile means in the case if different ?

I did some more test from user perpective. 

After a `renv::upgrade()`, new version of `renv` is used. If I install a new paackage with `renv::install` a snapshot is run, and renv version will be updated in the lockfile. So at the end it will be updated at next snapshot after upgrade. But why not update directly after the upgrade though ?

Having the version loaded specified in activate seems ok in the purpose of initialization without lockfile.(don't see the use case though. I would have in mind => using renv = a lockfile...)
However, having a different version in lockfile than activate seems different. The version of renv in lockfile is useful to know which one to use if we want to restore a project with only the lockfile, as I think it is the only file required to restore a project.

**Comment by kevinushey** [comment]
I think you're right. It's much more clear if there is a single source of truth for the version of `renv` associated with a project, and that source of truth should be the lockfile. I'll make this change.

It does imply that if the user deletes their lockfile that we'll no longer be able to know what version of `renv` should be used to manage the project, but I think that's fine since we do create a lockfile when the project is initialized anyhow.

**Comment by cderv** [comment]
> It does imply that if the user deletes their lockfile that we'll no longer be able to know what version of renv should be used to manage the project, but I think that's fine since we do create a lockfile when the project is initialized anyhow.

I agree with that. The lockfile is the one and only reference for the project. If a lockfile is delete I find it ok to not be able to restore - the project is no more a renv project in this case.

**Comment by kevinushey** [comment]
This should be implemented now.
