### ISSUE TITLE
Option to change renv folder location

### ISSUE THREAD

**Issue by reifjulian** [rstudio/renv#472]
It would be nice to allow the user to specify the location of the /renv folder and the renv.lock file. For example, rather than having these items located in the root folder, I might instead want to locate them in a /libraries subfolder.

**Comment by kevinushey** [comment]
Can you expand on why you want to change the location of the `renv` folder? Where are you hoping to place it instead?

The main challenge here is the `renv` auto-loader, which is created as part of the project `.Rprofile`. This typically contains a line of the form:

```
source("renv/activate.R")
```

and the path in the auto-loader needs to be "stable"; e.g. it needs to be able to find the activate script without `renv` itself being available yet.

**Comment by reifjulian** [comment]
I generally use R as part of a larger project that does separate analyses in Stata. My Stata libraries are kept in a subfolder, `/scripts/libraries/stata`. These Stata libraries are crossplatform and small in size, and thus can easily be shared for reproducibility purposes. It is often awkward to do this with R, however, since many libraries such as `tidyverse` are gigantic and need separate installations for each OS. (Hence the appeal of `renv`!) Additional discussion is available in my [Stata coding guide](https://julianreif.com/guide/#libraries).

What I would like is the ability to store `renv.lock` and `renv/activate.R` in my subfolder `/scripts/libraries/`. I do not personally have any need for the autoloader, and I do not mind having to write a line of code that supplies the path by calling `source("[path]/renv/activate.R")` directly. Essentially, I would like to use this as a configuration command that sets up a user's system prior to reproducing an analysis.

**Comment by kevinushey** [comment]
Thanks for the clarification. We could do this, but I think there's a bunch of things that would have to be done. Here are the places where we make use of the `"renv"` path by default:

- https://github.com/rstudio/renv/blob/15b044de8087d8c5944d73cbe9c8b76ddf09e6f5/R/paths.R#L68-L72
- https://github.com/rstudio/renv/blob/15b044de8087d8c5944d73cbe9c8b76ddf09e6f5/R/bootstrap.R#L474
- https://github.com/rstudio/renv/blob/15b044de8087d8c5944d73cbe9c8b76ddf09e6f5/renv/activate.R#L607-L608 (+ others)
- https://github.com/rstudio/renv/blob/15b044de8087d8c5944d73cbe9c8b76ddf09e6f5/R/infrastructure.R#L73-L78
- https://github.com/rstudio/renv/blob/15b044de8087d8c5944d73cbe9c8b76ddf09e6f5/R/install.R#L282-L288

We'd likely want to add a configuration option `autoloader.enabled` and also an argument for e.g. `renv::init(autoloader = FALSE)`.

**Comment by reifjulian** [comment]
I gave it a quick try and ran into a few problems.

1. `renv::init` initially gave me an error, and told me I had to specify `force=TRUE`
2. The renv.lock file was not created in the directory I specified
3. `renv` modified my `.Rprofile`, but I would prefer not to have it do this.
4.  Calling `renv::snapshot()` freezes R

I confirmed that `renv` created the folder `/renv` in my local user folder, with contents `activate.R`, `library`, etc, as expected. It also successfully linked the installed library (`estimatr`, see below) to what had been previously installed.

Here is sample code
R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Platform: x86_64-apple-darwin17.0 (64-bit)

```R
# Project folder location
MyProject <- Sys.getenv(c("MyProject"))

# Install development version of renv
library(devtools)
install_github("rstudio/renv")

# Disable autoloader, set lockfile path
RENV_CONFIG_AUTOLOADER_ENABLED = FALSE
RENV_PATHS_LOCKFILE <- paste0(MyProject,'/scripts/libraries')

# Error: refusing to initialize project in home directory -- use renv::init(force = TRUE) to override
renv::init(bare = TRUE, force = TRUE)
renv::install("estimatr@0.30.4")

renv::snapshot()
```

**Comment by kevinushey** [comment]
```
# Disable autoloader, set lockfile path
RENV_CONFIG_AUTOLOADER_ENABLED = FALSE
RENV_PATHS_LOCKFILE <- paste0(MyProject,'/scripts/libraries')
```

These need to be set as environment variables. For example:

```

remotes::install_github("rstudio/renv")

project <- tempfile()
dir.create(project)
setwd(project)

# Disable autoloader, set lockfile path
Sys.setenv(
  RENV_CONFIG_AUTOLOADER_ENABLED = "FALSE",
  RENV_PATHS_LOCKFILE = file.path(project, "scripts/libraries/")
)

renv::init(bare = TRUE, restart = FALSE)
renv::install("estimatr@0.30.4")

renv::snapshot()
```

I see, at the end:

```
* Lockfile written to '/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//Rtmp7sirUH/file393ec1cc3e1/scripts/libraries/renv.lock'.
```

Note that if you want `renv.lock` to be placed within the requested directory, you should append a trailing slash. If you want to control the location of the project-local `renv` folder, you should set `RENV_PATHS_RENV`.

**Comment by kevinushey** [comment]
A more complete solution changing both the `renv` and `renv.lock` folders would look like:

```
Sys.setenv(
  RENV_CONFIG_AUTOLOADER_ENABLED = "FALSE",
  RENV_PATHS_RENV = file.path(project, "scripts/libraries/renv"),
  RENV_PATHS_LOCKFILE = file.path(project, "scripts/libraries/renv.lock")
)

renv::init(bare = TRUE, restart = FALSE)
renv::snapshot()
```

**Comment by jacob-lee** [comment]
We frequently are in a situation in which the same directory might be mounted as a SMB share on Mac, or it might be accessed via a number of different virtual Linux systems (a virtual machine with gui environment, or on a cluster). The binaries being compiled won't be cross-compatible. It seems like there should be a relatively simple way to (1) check the OS/server-name etc. and then (2) load the appropriate library folder (assuming that the same package versions are available across OS's).

Is there a vignette or documentation on how that might be achieved reliably and with little hassle? Which environment variables would have to be set? `RENV_PATHS_RENV`?

**Comment by kevinushey** [comment]
@jacob-lee can you elaborate? `renv` already included architecture-specific information in the library paths by default. For example, I see on macOS:

```
> .libPaths()
[1] "/Users/kevin/scratch/example/renv/library/macos/R-4.4/aarch64-apple-darwin20"
[2] "/Users/kevin/Library/Caches/org.R-project.R/R/renv/sandbox/macos/R-4.4/aarch64-apple-darwin20/f7156815"
```

and you should see similar OS-specific components for other platforms.

**Comment by Arthfael** [comment]
I am running into a similar issue and would appreciate knowing what the current solution is:
 - I typically run analysis in a temporary folder then deliver them in another location shared with users and/or archive them
 - I recently moved to renv for the very purpose of ensuring that I can reconstitute analyses as exactly as possible in the future
 - However if some of the information is not copied when I move the data to a new location, then this voids the whole purpose of using renv in the first place
 - I cannot use git for this purpose: most of my users have never written a single line of code nor can they be expected to use complicated IT solutions.
If I understand correctly (from [https://github.com/rstudio/renv/issues/1757]), one solution would be to create a new renv project in the destination location, replace its `renv.lock` with that of the original project then run `renv::restore(lockfile="renv.lock")`, is that correct?

**Comment by yopolarbear** [comment]
Thanks so much @kevinushey and the team for all the wonderful work! Following the instructions above, I have no problem with initializing renv with `/renv` placed in a subfolder. However, once I restart the R session, I cannot seem to get renv activated, not even manually. 

Assuming that I'm at my project root directory. I used the following code to initialize renv and checked that both renv and renv.lock are placed correctly under `/lib`. 
```
Sys.setenv(
  RENV_CONFIG_AUTOLOADER_ENABLED = "FALSE",
  RENV_PATHS_RENV = "lib/renv",
  RENV_PATHS_LOCKFILE = "lib/renv.lock"
)
renv::init(bare = TRUE, restart = FALSE)
renv::snapshot()
```
I also added
```
source("lib/renv/activate.R")
```
to the top of my `/.Rprofile` and added
```
RENV_CONFIG_AUTOLOADER_ENABLED=FALSE
RENV_PATHS_RENV=lib/renv
RENV_PATHS_LOCKFILE=lib/renv.lock
```
in my `/.Renviron`. 

However, upon restarting the R session, I got no message of renv activation. Running `renv::project()` returns `NULL`. Running `renv::snapshot()` tells me that no renv project is active. I tried to manually run `source("lib/renv/activate.R")` but nothing happens. Am I missing something? 

Thanks in advance!!!

**Comment by kevinushey** [comment]
If I understand correctly, I think you want to remove this part from your project's `.Renviron`:

```
RENV_CONFIG_AUTOLOADER_ENABLED = FALSE
```

If that's set, then the project auto-loader won't be run when new sessions are started.

**Comment by kevinushey** [comment]
Thanks -- I believe this should be fixed up via https://github.com/rstudio/renv/commit/bc72d5aa9bdb394b9c9d8e1323e45a4baaa4d3ba. Can you install the development version of `renv` and let me know if that helps?

**Comment by yopolarbear** [comment]
Thanks @kevinushey! Unfortunately it didn't work for me. I installed the dev version, started a new session in a subdirectory under my project, run `renv::autoload()`, and nothing happened. I tried setting `RENV_PATHS_RENV` and `RENV_PATHS_LOCKFILE` to the full paths to `renv` and `renv.lock` before calling `renv::autoload()`, but it didn't work either. Am I missing something?

**Comment by kevinushey** [comment]
Possibly not -- I'll try to investigate a bit more myself to see if I can learn more.
