### ISSUE TITLE
installation failure - missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by dshakey** [rstudio/renv#473]
> devtools::install_github("rstudio/renv")
Downloading GitHub repo rstudio/renv@master
Error in if (!file.info(path)$isdir) { :
  missing value where TRUE/FALSE needed

**Comment by kevinushey** [comment]
Seems like this is a bug in `devtools` rather than `renv`? You could also just use the version of `renv` available on CRAN, via `install.packages("renv")`.
