### ISSUE TITLE
Feature Request: Allow direct query of the package dependency graph

### ISSUE THREAD

**Issue by strazto** [rstudio/renv#474]
When `renv` discovers dependencies, it does so by searching the source code for implicit dependencies, and the description for implicit dependencies. 

If I have this correctly (Correct me if I'm wrong):

It then recursively searches through its dependencies, using their DESCRIPTIONs to build a graph (or tree) of all of its required dependencies.

When this traversal is done, it uses it for whatever purpose we've asked it to (initializing the project, cleaning out unused deps, reporting the status, whatever). 

I am wondering if we could have a user-side function that allows us to access this dependency graph, ideally in a format that may be consumed by existing network graph tools such as [visNetwork](https://github.com/datastorm-open/visNetwork), [igraph](http://igraph.org/r/) , or whatever other network graph tools exist. 

A few solutions appear to be floating around for graphing this, like miniCran, pkggraph, but a lot of them seem to be highly CRAN focussed, and limited in what they can actually do.

**Comment by mstr3336** [comment]
Having said this, I literally just found the following: https://github.com/datastorm-open/DependenciesGraphs

It's hard to tell exactly what this package does without testing it, as the docs are very light, but I'll try it out

**Comment by kevinushey** [comment]
This is effectively true, except that `renv` doesn't build a dependency graph. Here's a short summary of what we do for now:

1. `renv::dependencies()` looks for top-level dependencies in a project, based on what packages appear to be used in the project's R files;

2. `renv_package_dependencies()` can be used to infer the recursive dependencies of those packages; this is used during `init()` to find the recursive package dependencies used in a project, and also during `renv::snapshot()` to confirm that the library is in a consistent state (no missing dependencies);

3. During `renv::restore()`, while `renv` doesn't build a graph explicitly, it does install package dependencies recursively to ensure that the lowest-level packages are retrieved and installed first. This is done implicitly as part of https://github.com/rstudio/renv/blob/caf0b39c883168cdd5ebd55a547f6d8689ab8712/R/retrieve.R#L560-L563, and this also ensures that packages are later installed in the correct order.

**Comment by vspinu** [comment]
Just came to the repo to open the same request :) 

Would be really nice to have a way to identify which dependencies are brought to renv.lock by which required packages. The main use case for me is to lighten the renv to the bare-bones for aws docker and lambda layer. 

This is what I use right now:

```
lock <- renv:::lockfile("renv.lock")
packs <- names(lock$data()$Packages)
map_dfr(set_names(packs), ~ list(deps = paste(names(renv:::renv_package_dependencies(.)), collapse = ",")), .id = "package")

```

**Comment by mstr3336** [comment]
That dependency graph package i shared is a little rough but actually does do what we need @vspinu

**Comment by mstr3336** [comment]
For me, the use case is sometimes getting rid of packages that pull in c++ compilation that expects decently modern build environments

**Comment by hadley** [comment]
I think providing an API for introspecting the dependency graph is out of scope of renv; you should now be able to get much of what you need from pak and friends.
