### ISSUE TITLE
upgrade does not work with a version number

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#48]
The doc says 
> his implies that you can call (for example) renv::upgrade(remote = "0.1.0-75) to request the installation of that particular version of renv if so required.

But 
```r
> renv::upgrade(remote = "0.2.0-59")
Error in unclass(numeric_version(rhs))[[1]] : subscript out of bounds
Call `rlang::last_error()` to see a backtrace
```
This is because there is no version in records
https://github.com/rstudio/renv/blob/494ce53b8593a84eb2305ea7728008b097c8566b/R/upgrade.R#L30-L35
``` r
renv:::renv_remotes_parse("0.2.0-59")
#> $Package
#> [1] "0.2.0-59"
#> 
#> $Version
#> NULL
#> 
#> $Source
#> [1] "CRAN"
```

so `request` is NULL and `version_compare(current, request) == 0` throws the error

It is like Package and Version field are not correct. I would expect
```r
#> $Package
#> [1] "renv"
#> 
#> $Version
#> [1] "0.2.0-59"
#> 
#> $Source
#> [1] "Github"
```

Currently from the code, I don't think it is possible to install a specific renv version like documented. I understand that the call should be something like that `rstudio/renv@0.2.0-59` to be understand as a github remote
```r
 renv:::renv_remotes_parse("rstudio/renv@0.2.0-59")
```
But even like that it is not ok because 0.2.0-59 is a tag name and `renv_remotes_parse_github` only knows how to handle branch reference (`git/refs/heads/`)
* https://api.github.com/repos/rstudio/renv/git/refs/heads/0.2.0-59 does not exist
* https://api.github.com/repos/rstudio/renv/git/refs/tags/0.2.0-59 does exist

Github API makes a difference here between commit / branch and tag. You would need to test both or use another approach like download the tarball and read DESCRIPTION inside 
`https://api.github.com/repos/rstudio/renv/tarball/<any git ref>`

Currently, `renv::upgrade` only works to upgrade from master or branch but not from a version number.

**Comment by kevinushey** [comment]
This should be fixed now -- please re-open if you're still having trouble. (Note that I've changed the interface to instead be a plain version rather than a remote specification)

**Comment by cderv** [comment]
It is working fine and plain version is what I had in mind. 👍 

I try to run `renv::upgrade("0.3.0-2")` instead of `renv::upgrade(version = "0.3.0-2")`. 
Don't know if argument should be reverse (_version_ and _project_) - just a matter of getting used to I thing.. 🤔 

Thanks.
