### ISSUE TITLE
`renv::snapshot(lockfile = "...")` doesn't see the library path for dependencies

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#480]
I am trying to achieve a poor man's modularization of the lockfile (#253) by extracting a subset of a lock file:

```R
subsnapshot <- function(lockfile, packages = renv::dependencies(sources)$Package, sources) {
  lock <- renv:::lockfile()
  opts <- options(renv.snapshot.filter = function(.) packages)
  on.exit(options(opts))
  renv::snapshot(type = "custom", lockfile = lockfile)
}
subsnapshot("./renv2.lock", sources = "./predictor/init.R")
```

This almost works except that renv complains about libpaths the dependencies of the packages are not written

```
The following required packages are not installed:

	BH            [required by PoissonBinomial]
	dplyr         [required by rPref]
	generics      [required by lubridate]
	igraph        [required by rPref]
	lazyeval      [required by rPref]
	magrittr      [required by purrr, xgboost]
	Matrix        [required by xgboost]
	Rcpp          [required by lubridate, PoissonBinomial, rPref, and 1 other]
	RcppParallel  [required by rPref]
	rlang         [required by purrr]
	stringi       [required by xgboost]

Consider re-installing these packages before snapshotting the lockfile.
```

The .libPaths() shows me the current renv path with all those packages installed. 

I can circumvent this by explicitly adding `names(renv:::renv_package_dependencies(packages))` to the snapshoted packages for now, but still thought to report.

**Comment by kevinushey** [comment]
Does it help if you supply the project directory; e.g.

```
renv::snapshot(project = "/path/to/project", type = "custom", lockfile = lockfile)
```

Or are you already running within that working directory?

The other thing you could do is (probably as an R sub-process) run something like:

```
renv::activate("/path/to/project")
renv::snapshot(...)
```

just to make sure any project-specific context is made available for that session.

**Comment by vspinu** [comment]
I am within the same project, so neither of the above would help.

**Comment by kevinushey** [comment]
In the end, I think this is the right behavior: you're creating a lockfile that doesn't capture the full dependency tree, and so `renv` is warning you about that.

 The right resolution here, I think, is to resolve recursive dependencies via `renv:::renv_package_dependencies()`. This is basically what the "implicit" snapshot mode does, except it takes all files within the project as "sources".

It seems like ultimately what you want is an "implicit" snapshot, except dependencies should be inferred from some subset of project files. Is that correct?

**Comment by vspinu** [comment]
Precisely. This is why I have those `sources` argument. Basically #443. 

This is my working version atm:

```
renv_subsnapshot <- function(lockfile, packages = renv::dependencies(sources)$Package, sources) {
  lock <- renv:::lockfile()
  deps <- names(renv:::renv_package_dependencies(packages))
  opts <- options(renv.snapshot.filter = function(.) unique(c(packages, deps)))
  on.exit(options(opts))
  renv::snapshot(type = "custom", lockfile = lockfile)
}
```

**Comment by hadley** [comment]
Closing in favour of #443
