### ISSUE TITLE
hydrate uses cache, install doesn't

### ISSUE THREAD

**Issue by py9mrg** [rstudio/renv#481]
Not sure if this is by design and I'm missing something, or whether this is a bug, but it appears that `hydrate` uses the local cache whereas `install` doesn't.

To explain I'll describe how I noticed this. Normally I'll write a script/Rmarkdown etc first, and that will have a call such as `library(Rcpp)`. I then use `hydrate` to pull `Rcpp` into the project library before actually running the code, it all works perfectly and picks up the `Rcpp` that exists in the local `renv` cache.

However, if I try to use `install` first instead, then it completely ignores the cache and tries to download `Rcpp`. I only noticed this because of the downloading issue on Windows behind corporate proxy, so I got an error that the package is not available (and that the relevant urls aren't) rather than it just being downloaded instead. But if the package is already in my local cache, I don't believe it should even be trying to download the package - so that shouldn't be an issue unless I'm trying to install something completely new.

The problem is a nuisance at the moment (and I'm pretty sure I didn't have this before 0.11.0 - but I can't remember 100 %) is that I can't open a new notebook in a new project. When I do RStudio warns some packages are needed, then it tries to install them but fails. If I click don't install (so I could manually do them after) it just fails outright, so it's not like I can even open a new notebook and then tell `hydrate` to go do it instead. 

Ok so I can manually fudge a way to get `hydrate` to pull them in and/or fix the download/proxy issue, but I shouldn't really need to - I think - because these packages are all in the cache and it should pull the relevant ones in for the notebook. Like I said, I never noticed this problem before so it seems like the downloading/cache issues are both new to me.

Output from some commands that might help:

```
> renv:::renv_paths_cache()
[1] "C:/Users/XXX/AppData/Local/renv/cache/v5/R-4.0/x86_64-w64-mingw32"

> .Library
[1] "C:\\Users\\XXX\\AppData\\Local\\Temp\\RtmpULev1w/renv-system-library"

> .libPaths()
[1] "C:/ProjectName/renv/library/R-4.0/x86_64-w64-mingw32" "C:/Users/XXX/AppData/Local/Temp/RtmpULev1w/renv-system-library" 
```

Edit: I checked the `use.cache` option and it was `NULL`, so changed it and then re-initialised, but that didn't change anything:

```
> getOption("renv.settings.use.cache")
NULL
> options("renv.settings.use.cache" = TRUE)
```

Edit 2: I can get around this by removing `renv` from the project, opening a notebook, then re-introducing `renv`, then `hydrate` will pull (almost) everything required. Except it doesn't pull in `Rcpp` or `rprojroot` automatically so I have to make a temporary script with a `library` call for those.

Weirdly, if I remove that script and then use `clean` I get the following packages listed as unusused, first `translations` then:

```
backports, Rcpp, renv, rprojroot
```

So something really weird is going on as `renv` thinks it doesn't need itself, plus those other packages which are needed to use a notebook - it even pulled in `backports` when I hydrated after saving a notebook template! I'm sure this was never an issue with previous versions and (I think) I haven't done something really dumb recently - though I can't swear to it!

**Comment by kevinushey** [comment]
> Not sure if this is by design and I'm missing something, or whether this is a bug, but it appears that hydrate uses the local cache whereas install doesn't.

`renv::install()` should normally use the cache; e.g. I see (not inside an `renv` project):

```
> renv::install("digest")
Installing digest [0.6.25] ...
        OK (copied cache)
```

I'm curious why you're seeing the cache not being used here, unless you've explicitly disabled cache usage in the project you're working on (via for example `renv::settings$use.cache(FALSE)`). Can you share the output you see when you try to install a package in this way? What is the output of `renv::settings$use.cache()`?

> I then use hydrate to pull Rcpp into the project library before actually running the code, it all works perfectly and picks up the Rcpp that exists in the local renv cache.

`hydrate()` actually attempts to pull in packages from the user / system libraries, as opposed to the `renv` global cache. So I suspect what you're seeing is `renv` pulling Rcpp from your user library.

> Edit: I checked the use.cache option and it was NULL, so changed it and then re-initialised, but that didn't change anything:

The cache should be enabled by default (unless disabled in project settings), so this still seems consistent.

It does seem like you could call something like:

```
renv::hydrate(packages = "rmarkdown")
```

to pull in `rmarkdown` + its dependencies explicitly -- otherwise `renv::hydrate()` will "guess" based on the result of `renv::dependencies()`.

**Comment by py9mrg** [comment]
Thanks for coming back to me. So it's really weird, originally `renv::settings$use.cache()` was returning `NULL` but since I set it as per above it does now return `TRUE` but still I have the following error message:

```
> renv::settings$use.cache()
[1] TRUE
> renv::install('Rcpp')
Error: package 'Rcpp' is not available
In addition: Warning messages:
1: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib" 
2: could not retrieve available packages for url "https://cran.rstudio.com/bin/windows/contrib/4.0" 
```

Now if I go into my cache location as specified by `renv:::renv_paths_cache()` then I can see `Rcpp` there (and the same happens if I try other packages). I've also tried `purge` and that doesn't help, so it's not like it's that a package is corrupt.

I've also tried completely removing `renv` from my system, reinstalling, same thing. But I didn't get this strange warning:
```
> remove.packages("renv", lib="~/R/win-library/4.0")
Warning message:
In read.dcf(file.path(p, "DESCRIPTION"), c("Package", "Version")) :
  cannot open compressed file 'C:/Users/mgadsdo/Documents/R/win-library/4.0/renv/DESCRIPTION', probable reason 'No such file or directory'
```

Finally, I tried using a previous versions (0.10.0 and 0.9.3) as I never saw this issue before, but then I'd only used hydrate until now - same problem. But, when uninstalling I didn't get the warning message about the DESCRIPTION file. 

Finally, there is a slight difference in behaviour when using `install` within a project or in a normal R session. Everything above is within an RStudio project, but in a non-project session I get:

```
> renv::install("Rcpp")
The following folder(s) appear to be left-over temporary directories:

	file2be8702578ea

Consider removing these folders from your library.

Retrieving 'https://cran.ma.imperial.ac.uk/bin/windows/contrib/4.0/Rcpp_1.0.5.zip' ...
	OK [downloaded 3.1 Mb in 2 secs]
Installing Rcpp [1.0.5] ...
	OK (copied cache)
```

So the issue still seems to be there as it's resorting to downloading, but obviously I don't get the download error outside of a project. Plus I'm not sure what the warning about temp directories is about.

Anyway, now back on 0.11.0, same issue - it's really weird. It's not the end of the world as I can work around it a little using `hydrate`, but strange nevertheless. Maybe I have some weird setting somewhere I need to delete, but I never changed any default settings.

**Comment by kevinushey** [comment]
I think I have a better understanding now, given the error message.

When `renv::install("Rcpp")` is invoked, this is really a request for `renv` to install the latest version of `Rcpp` available from those package repositories. To figure that out, `renv` needs to actually request the list of available packages from those repositories. It looks like that fails in your case, as the repositories are not accessible. Since `renv` ultimately doesn't know what version of `Rcpp` you want to install, it cannot install it.

However, ultimately, it looks like that alternate CRAN mirror (`https://cran.ma.imperial.ac.uk`) is available. You could try setting that repository within your `renv` project; e.g.

```
options(repos = c(CRAN = "https://cran.ma.imperial.ac.uk"))
```

and then trying to install.

Regarding the warning you're seeing, I suspect that may be a bug external to `renv`. Are you using RStudio? It's possible RStudio is attempting to read the package DESCRIPTION file after it's removed.

Can you confirm what repositories are recorded in the project lockfile? That is, what is the output of:

```
# current repos
getOption("repos")

# repos in lockfile
lockfile <- renv:::renv_lockfile_read("renv.lock")
lockfile$R$Repositories
```

**Comment by py9mrg** [comment]
> However, ultimately, it looks like that alternate CRAN mirror (https://cran.ma.imperial.ac.uk) is available. You could try setting that repository within your renv project; e.g.

Ah ok, that makes sense as in a normal R session I'm setting the repose to that manually in my `.Rprofile`. Yeah I can do that in a project too to fix the renv download there.

The outputs you requested are as:

```
> # current repos
> getOption("repos")
                                CRAN                            CRANextra 
       "https://cloud.r-project.org" "http://www.stats.ox.ac.uk/pub/RWin" 
> 
> # repos in lockfile
> lockfile <- renv:::renv_lockfile_read("renv.lock")
> lockfile$R$Repositories
$CRAN
[1] "https://cloud.r-project.org"

$CRANextra
[1] "http://www.stats.ox.ac.uk/pub/RWin"
```

Interestingly, I set that CRANextra repos in my `.Rprofile` in my main working directory, but it's not in the `.Rprofile` of the project so, presumably it's picking it up from there.

Once I manually set the repos with `options(repos = c(CRAN = "https://cran.ma.imperial.ac.uk"))` and then tried to install, I got:
```
> renv::install('Rcpp')
Installing Rcpp [1.0.5] ...
	OK (linked cache)
The following package(s) have been updated:

	Rcpp [installed version 1.0.5 != loaded version 1.0.4.6]

Consider restarting the R session and loading the newly-installed packages.
```
So looks like you've cracked it as I'm fairly sure it didn't download it (no download pop up window), it paused for a little, presumably to do the checks you mentioned, and then seems to link to the existing one in the cache. I never realised `renv` was checking for the latest version against the repository, but now you said it it seems obvious - sorry! Had I been smarter I might have realised that and sorted the repos out first. Thanks for your help and (patient) explanations.

**Comment by kevinushey** [comment]
No worries; I'm glad I was able to help! There are a lot of subtleties and moving parts here that are definitely difficult to grok.
