### ISSUE TITLE
Using renv between dev and production environments?

### ISSUE THREAD

**Issue by JimShady** [rstudio/renv#482]
Hello,

After a little advice please on my workflow and how to use renv within it, as I have been having package version issues (and missing packages altogether).

- I develop locally on a Windows laptop in a R project folder. I have about 10 different scripts which do different things for the application I am building.
- I commit my changes to a git repo.
- Those changes are deployed from the git repository to a Unix server.
- The R scripts are than ran on the Unix server by cron-jobs.

How to use renv in this scenario to ensure that my project on the server has the same packages and versions available as I am using on my laptop development environment? What is the reccomended workflow?

I have so far done renv::init() in my local development project. It has set-up renv.
I've commited this to the git repo.
I've deployed this to the unix server.

I'm not really sure where to go from there...

Thanks in advance, Jim

**Comment by kevinushey** [comment]
The main things you need to do from here:

1. Make sure R processes are launched from the project directory, so that the `renv` autoloader can be run,
2. Run `renv::restore()` to make sure the project library is restored based on the lockfile `renv.lock`,
3. Run your script(s) as necessary.

If you're running jobs using a cron job, you probably want to invoke R with something like:

```
cd path/to/project && R -e 'renv::restore(); source("script.R")'
```

**Comment by JimShady** [comment]
Wow, quick reply, thanks @kevinushey  .

My cron-jobs actually run a .sh script which looks like this.

```
#!/bin/bash
cd /myproject/
/bin/Rscript script1.R
```

So I guess I need to change them to something like this?

```
#!/bin/bash
cd /myproject/
R -e 'renv::restore()'
/bin/Rscript script1.R
```

Look about right?

**Comment by kevinushey** [comment]
That sounds correct to me. Let me know if that works for you. I'd also recommend checking out the getting started vignette: https://rstudio.github.io/renv/articles/renv.html

**Comment by JimShady** [comment]
Thanks for your help. Thinking about it perhaps I can also have `R -e 'renv::restore()'` run as part of the deployment process which takes the code from my git repo and puts it onto the server. Then it would only be ran once, rather than every time I want to run a script. 

I did read the vignette, but having also read the packrat vignette this evening my brain was rather fried! 

Thanks again.

**Comment by JimShady** [comment]
Incase anyone is reading this later, I think I actually needed to add consent before the restore. Like this.

```
renv::consent(provided=TRUE)
renv::restore()
```

**Comment by kevinushey** [comment]
Thanks -- I should've mentioned that as well. Glad to hear things are working!
