### ISSUE TITLE
Slow load time

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#484]
Parsing a ~1200 lines `renv.lock` file takes >0.5 seconds, this is where most of the time is spent when opening an renv-enabled project. Have you considered caching the parsed `renv.lock` file in an uncompressed `.rds`?

``` r
path <- "~/.../renv.lock"
length(readLines(path))
#> [1] 1139
bench::mark(renv:::renv_json_read(path))
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 renv:::renv_json_read(path)    599ms    599ms      1.67    51.9MB     1.67
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kevinushey** [comment]
I haven't yet, just because this is the first time a performance issue there has been reported. :-)

Is the slowness here compounding or causing specific issues in a specific workflow? It would help me understand what the best resolution here is.

**Comment by krlmlr** [comment]
Dropped to 30 ms for my ~2500 lines file thanks to efforts in #664.
