### ISSUE TITLE
Add handling for repos that are non-responsive?

### ISSUE THREAD

**Issue by adamroyjones** [rstudio/renv#485]
I had a small issue today in which renv was attempting to go to a CRAN mirror that was non-responsive (https://cran.ma.imperial.ac.uk/), which caused renv to likewise become non-responsive.

Do you think that there should be some built-in handling for this kind of situation?

If you think so, then I'm happy to go off and work on the feature and raise a pull request in the not-so-distant future.

**Comment by kevinushey** [comment]
Yes, I think we could / should absolutely do better here. Right now, the behavior is governed by the `connect.timeout` and `connect.retry` configuration options:

https://github.com/rstudio/renv/blob/f7a8c873ec8bb7414be71a24b6589ea9e29781cc/inst/config.yml#L22-L34

We might want to decrease the defaults for some of these.

**Comment by adamroyjones** [comment]
Thanks for the pointer—I'll try and put something together over the next couple of weeks.

**Comment by adamroyjones** [comment]
(I've evidently not found the time to look at this... I'll close the issue.)
