### ISSUE TITLE
Never downgrade required R version?

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#486]
In a project with multiple collaborators with different R versions installed, the version recorded in `renv.lock` is reset with every `snapshot()`. Would you consider only ever upgrading the R version in the lock file, with a warning if the R version is lower?

**Comment by kevinushey** [comment]
Perhaps instead it would be worth having some way of "freezing" the R version used, so that it's only updated explicitly (rather than implicitly by whatever version of R happened to be used in that project at that time)?

**Comment by krlmlr** [comment]
Are you suggesting a project setting?

**Comment by kevinushey** [comment]
That's what I ended up going with -- see `renv::settings$r.version()`. When set, it basically overrides whatever the current version of R might be when lockfiles are written, basically "freezing" the version of R to the project-set version.

**Comment by krlmlr** [comment]
Awesome! I'll check it out and close this issue then.

**Comment by vspinu** [comment]
With renv 0.14.0 this option has no effect or me. I am setting `options(renv.settings.r.version = "4.1.1")` but `renv::snapshot()` on R4.0.0 still overwrites `renv.lock` to

```
{
  "R": {
    "Version": "4.0.0",
...
```

**Comment by vspinu** [comment]
Actually it woks if set in `renv/settings.dcf` (which in fact I prefer to .Rprofile + options configuration). 

But the docs of `renv::settigns` still recommend using `options`:

```
     You can change the default values of these settings for
     newly-created ‘renv’ projects by setting R options for
     ‘renv.settings’ or renv.settings.<name>. For example:

     options(renv.settings = list(snapshot.type = "all"))
     options(renv.settings.snapshot.type = "all")
```

**Comment by kevinushey** [comment]
Technically I believe this is working as documented: the options only affect the default value used in newly-created projects.

If I understand correctly, you're expecting the option to take precedence at runtime when the setting is read as well; is that correct?

**Comment by kevinushey** [comment]
There is a test for this behavior specifically:

https://github.com/rstudio/renv/blob/master/tests/testthat/test-settings.R#L22-L27

... but I'm not sure what the main motivation was.

**Comment by vspinu** [comment]
> the options only affect the default value used in newly-created projects.

Got it. Didn't notice this one. 

> you're expecting the option to take precedence at runtime when the setting is read as well

Precisely. To be frank I am quite confused by the totality of "configuration" options in renv. There are options starting with `renv.config`, then `renv.setting`, `renv::settings` list of functions, `env` variables, and `renv/settings.dcf`. It's pretty much a soup in my head, so I tend to stick to manually editing `renv/settings.dcf`.

**Comment by kevinushey** [comment]
The main idea is that "config" options are associated with a user and are generally based on their preferred `renv` workflow, whereas "settings" are associated with a project, and so need to be active for anyone working with that particular project. The distinction is sometimes blurry, though.

The `renv.settings` option is normally used to control the "default" project settings used in newly-initialized projects; `renv/settings.dcf` is still the canonical "source of truth" for project-specific settings.

**Comment by krlmlr** [comment]
This seems to work for me now.
