### ISSUE TITLE
Is there an option of warning-continue instead of error-exit on init failure?

### ISSUE THREAD

**Issue by OmaymaS** [rstudio/renv#487]
_I checked the previous issues but I didn't find a related one, please refer me to any relevant ones if exist._

I was wondering if there's any option with `init()`to set in order to make it possible to skip errors while installing packages specified in  `renv.lock`. What I am looking for is an option so that **whenever it fails to install a package, it should try the next one till the end and then provide a log of the failed attempts.** Is there any possibility? And what would be the cons of it?

Thanks

**Comment by kevinushey** [comment]
Just for clarity, you're calling `renv::init()` on a project that already contains a lockfile? (That is, what is happening in effect is an `renv::restore()` behind the scenes)

This isn't currently possible, but seems like it would be worth implementing.

As an aside, you could also use `renv::activate()` to activate `renv` for a project without explicitly restoring the project library.

**Comment by OmaymaS** [comment]
> Just for clarity, you're calling renv::init() on a project that already contains a lockfile? (That is, what is happening in effect is an renv::restore() behind the scenes)

What I wanted to do is to keep a lockfile in the Github repo, so others could clone the repo and install the same packages. Now I get that  I also commit `renv/activate.R` and let others use `renv::restore()`. But I assume they will probably get the same issue on any package installation failure.

**Comment by kevinushey** [comment]
Still though, won't that be an issue for other users down the line? If they're unable to install packages required by a particular project, then they're unlikely to be able to run scripts in that project. Or are these packages optional, or used only in separate circumstances?

**Comment by karawoo** [comment]
I have wished for this feature as well. I'll sometimes run into difficulties restoring from a lockfile (I think normally due to issues installing older versions of packages from source). If I need to work on part of the project that doesn't use all the dependencies it'd be nice to restore everything else, and leave dealing with the unsuccessful dependencies for later.

**Comment by kevinushey** [comment]
While this isn't a perfect fix, you should be able to do something like:

```
renv::restore(packages = c(...))
```

to restore a subset of packages from a lockfile (+ that package's dependencies). Note that `renv` will only notify you about the package you've requested (which I should try to fix eventually) but you will see all dependent packages restored. For example:

```
> renv::restore(packages = "rmarkdown")
The following package(s) will be updated:

# CRAN ===============================
- rmarkdown   [* -> 2.3]

Do you want to proceed? [y/N]: y
Installing evaluate [0.14] ...
        OK (linked cache)
Installing highr [0.8] ...
        OK (linked cache)
Installing xfun [0.16] ...
        OK (linked cache)
Installing mime [0.9] ...
        OK (linked cache)
Installing markdown [1.1] ...
        OK (linked cache)
Installing glue [1.4.1] ...
        OK (linked cache)
Installing magrittr [1.5] ...
        OK (linked cache)
Installing stringi [1.4.6] ...
        OK (linked cache)
Installing stringr [1.4.0] ...
        OK (linked cache)
Installing yaml [2.2.1] ...
        OK (linked cache)
Installing knitr [1.29] ...
        OK (linked cache)
Installing digest [0.6.25] ...
        OK (linked cache)
Installing base64enc [0.1-3] ...
        OK (linked cache)
Installing rlang [0.4.7] ...
        OK (linked cache)
Installing htmltools [0.5.0] ...
        OK (linked cache)
Installing jsonlite [1.7.0] ...
        OK (linked cache)
Installing tinytex [0.25] ...
        OK (linked cache)
Installing rmarkdown [2.3] ...
        OK (linked cache)
```

**Comment by karawoo** [comment]
Oh nice, I didn't know that
