### ISSUE TITLE
renv to manage common libraries?

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rstudio/renv#488]
Hi,

I'd like to know if it's possible to use renv to manage common libraries as in this article: https://support.rstudio.com/hc/en-us/articles/215733837-Managing-libraries-for-RStudio-Server

My goal is to have a reproducible common R env, even for dependencies.

I was thinking on creating a fake project with ```renv::settings$snapshot.type("all")```

Is this a good practice or is there a better one?

Thanks for any feedback.

**Comment by kevinushey** [comment]
Yes, this should work. My recommendation would be to create a "dummy" `renv` project is some location, and then use:

```
renv::load("/path/to/project")
```

to load that as the active project, even for alternate project directories. Then your various projects will make use of that same library path, and so on.

Alternatively, you can likely build something of your own on top of `renv::snapshot()`, `renv::restore()`, setting library paths on startup, and so on. It would help if you further described what exactly you want to achieve.

**Comment by sebastien-prudhomme** [comment]
My use case is to reproduce an actual R environment with some shared R libraries on an updated operating system (Centos6 to CentOS7).

I'm now using the R version packaged by RStudio and i'd like to install the same shared libraries with the same versions in default R system directory /opt/R/X.Y.Z/lib/R/library.

**Comment by kevinushey** [comment]
Thanks. I think you want to do something like the following:

```
# capture state of system library
renv::snapshot(library = .Library, type = "all", lockfile = "system-library.lock")
```

Then later, you can call:

```
# restore state from lockfile
renv::restore(library = .Library, lockfile = "system-library.lock")
```

This will install the same list of packages (and the exact same versions of those packages) into the system library in your new R environment.

**Comment by sebastien-prudhomme** [comment]
Will try that. Thanks for these precious advices!

**Comment by kevinushey** [comment]
Glad I could help! Please let me know if you run into any roadblocks or have any other trouble.

**Comment by sebastien-prudhomme** [comment]
@kevinushey everything is working fine.

I'm now trying to automate everything with Ansible.

I'm trying to launch "renv::restore" only if there is something to do but the "renv::status" as no "type" option to say that i want to take into account all packages in the library.

Should i create a new issue for this feature?

**Comment by kevinushey** [comment]
For what it's worth, `renv::restore()` should already be a no-op if your project library is up-to-date, so perhaps just calling that without first checking `renv::status()` should be fine. You'd just need to make sure the project's library paths have been initialized before calling `renv::restore()`.

Let me know if I'm misunderstanding something -- if so, please feel free to file a new issue.

**Comment by sebastien-prudhomme** [comment]
@kevinushey you're right, perfectionism :-)
