### ISSUE TITLE
Feature Request: Optionally check status of library on startup

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#489]
Thanks for your great work on this important package!

It would be helpful to optionally have the status of the project checked on start-up (similar to running `renv::status()`).

```r
# during initialization, optionally request the status to be checked on startup
renv::init(check_status_on_startup = TRUE)
```

When project is up to date on startup.
```r
* Project 'C:/Users/SjobergD/GitHub/Morrow-Negotiation-theory-and-unnecessary-breast-surgery' loaded. [renv 0.11.0]
* The project is already synchronized with the lockfile.
```

When project is **not** up to date on startup.
```r
* Project 'C:/Users/SjobergD/GitHub/Morrow-Negotiation-theory-and-unnecessary-breast-surgery' loaded. [renv 0.11.0]
* The project is not synchronized with the lockfile. Run `renv::status()` for details.
```

🕺

**Comment by kevinushey** [comment]
You can use the following configuration option to control that:

```
RENV_CONFIG_SYNCHRONIZED_CHECK = TRUE
```

This can be set in e.g. `~/.Renviron`. Please see `?renv::config` for more details.

**Comment by ddsjoberg** [comment]
fantastic, thank you so much, and apologies for not seeing that in the documentation!
