### ISSUE TITLE
Renv::install does not appear to handle Bioconductor Installation smoothly

### ISSUE THREAD

**Issue by ColeWunderlich** [rstudio/renv#495]
When attempting to install a Bioconductor package into a fresh `renv` the installation always fails, producing the following error:
```
> install.packages("dropletUtils")
Error: package 'dropletUtils' is not available
Traceback (most recent calls last):
8: install.packages("dropletUtils")
7: install(pkgs)
6: renv_retrieve(packages)
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_available_packages_latest(record$Package)
2: stopf("package '%s' is not available", package)
1: stop(sprintf(fmt, ...), call. = call.)
```
This appears to be because `renv::install()` does not automatically configure the package repositories as `biocLite` or `BiocManager::install()` do.

I haven't tried to rehydrate a `renv` containing a Bioconductor package yet, but I wonder if this would also run into similar problems.

I was able to work around this by first installing `BiocManager` and then running `options(repos = BiocManager::repositories())` as suggested in #81.

Is it reasonable to implement a solution where the repositories are configured automatically when a Bioconductor package install is attempted?  As a newer user of `renv`, when the documentation stated it supported installing from Bioconductor, I was confused when `renv::install()` failed and I had to search for a workarround.

**Comment by kevinushey** [comment]
This is expected, although perhaps isn't well-documented. You can install packages from Bioconductor explicitly with, for example:

```
renv::install("bioc::Biobase")
```

Note that `renv` requires either the `BiocManager` or `BiocInstaller` packages to be available in order for installation from Bioconductor to work, as `renv` depends on those packages to determine how Bioconductor can be accessed.

**Comment by kevinushey** [comment]
The documentation for `renv::install()` has been updated in the development version to make this more clear -- thanks for reporting!

**Comment by ColeWunderlich** [comment]
Hey Kevin,  sorry for such a delayed reply.  The new docs look good!

My only suggestion would be adding a similar note to either the [package sources](https://rstudio.github.io/renv/articles/renv.html#package-sources) or [inferring package sources](https://rstudio.github.io/renv/articles/renv.html#inferring-package-sources) sections on the Getting Started page.  As a newer user, I read the package sources section and thought it implied automagic handling of Bioconductor packages, which is where I got confused.
