### ISSUE TITLE
Feature request: method to check library vs lockfile, regardless of project

### ISSUE THREAD

**Issue by d-sci** [rstudio/renv#496]
My lockfile has packages I want even though they aren't obvious dependencies of my project. This means that if I turn on the `synchronized.check`, I'll always get:
```
* The project and lockfile are out of sync -- use `renv::status()` for more details.
```
even if the **library** and **lockfile** are in sync:
```
> renv::status()
The following package(s) are no longer used in this project:
                _
  KernSmooth      [2.23-17]
   . . . # but no actual mismatches

> renv::restore()
* The library is already synchronized with the lockfile.
```

That's fine in of itself. The option is now FALSE by default anyway. And maybe I should have used some non-default snapshot type that I haven't bothered to figure out. But what I would really like, and what seems useful anyway, is an option to check if the **library** and **lockfile** are in sync, ideally on load, but without attempting to actually restore. 

Basically:
- just activating `renv` (i.e., `source('renv/activate.R')`) won't run `renv::restore()` or otherwise guarantee that my project library is in line with the lockfile
- I don't necessarily want to force myself or my team to run `restore()` at load, e.g. by adding `renv::restore(prompt = FALSE)` to the `.Rprofile` right after `source(renv/activate.R)`
- But I do want to KNOW if I probably need to run `renv::restore()`, ideally via an automatic check at load

An option similar to `synchronized.check` could work, but even wrapping some of the checks that happen inside `renv::restore()` into its own exported function so that I can check myself would be helpful, e.g. I could manually make my .Rprofile something like:
```
source('renv/activate.R')
if (renv::needs_restore()) { # doesn't seem to be an easy way to do this yet
  message("Warning: the library is out of sync with the lockfile. You may need to run renv::restore()")
}
```

**Comment by kevinushey** [comment]
> My lockfile has packages I want even though they aren't obvious dependencies of my project.

One solution here would be to make a dependency on the package explicit, e.g. by placing `library(<package>)` in a file called `dependencies.R`. It's a bit of a kludge, but should work.

> `> renv::restore()`
> `* The library is already synchronized with the lockfile.`

By default, `renv::restore()` won't remove unused packages, so you'd need to use:

```
renv::restore(clean = TRUE)
```

if you did want the restore action to uninstall `KernSmooth` in this case.

---

That said, it's probably confusing that the synchronized check would warn in this case -- perhaps it should ignore unused packages? Now that I think of it, using the `ignored.packages` setting might work; e.g.

```
renv::settings$ignored.packages("KernSmooth")
```

Ultimately though, I think what you want is the same as the `synchronized.check` option, but perhaps with its behavior tweaked a bit. Do you think it's permissible to ignore unused packages when reporting if the library + lockfile are out-of-sync?

**Comment by d-sci** [comment]
Thanks for those suggestions. It looks like if I change my snapshot type setting to `all`, I don't get a warning via the `synchronized.check`, and I get a "clean" output from `renv::status()`. That's all consistent and sensible, so maybe no action required. (And if I want to keep the `implicit` snapshot type, I can use the `dependencies.R` trick).

More generally, though, I guess I was bringing up the point that there are **three** (3) things that renv could check:
1. The lockfile
2. The project library
3. The (inferred or actual) project dependencies

In theory that leads to 3 potential comparisons of interest, but for the most part there doesn't seem to be any way to decouple those. What I was originally asking for was a way to compare (1) and (2) ignoring (3). It seems the `synchronized.check` provides that, though _only if_ the snapshot type is `all`.

**Comment by kevinushey** [comment]
That's correct. I'm wondering if it might be appropriate to only compare (1) and (2) in the startup synchronized check, as attempting to infer project dependencies might be slow, and would inhibit project startup time. In general, comparing against (3) is less "interesting" in this case, I think.

**Comment by d-sci** [comment]
Agree with you on all points there.

**Comment by d-sci** [comment]
It might even mean that the default should go back to `TRUE` (since it will still be fast).

**Comment by kevinushey** [comment]
Precisely :-)

**Comment by kevinushey** [comment]
Thanks! I've now made this change on `master`. You should see a warning from `renv` if there are packages declared within the lockfile that don't match what's currently available for the associated `renv` project. For example:

```
* Project '~/scratch/test' loaded. [renv 0.11.0-13]
* The project may be out of sync -- use `renv::status()` for more details.
> renv::status()
The following package(s) are out of sync:

   Package   Lockfile Version   Library Version
    digest             0.6.25            0.6.24

Use `renv::snapshot()` to save the state of your library to the lockfile.
Use `renv::restore()` to restore your library from the lockfile.
```

Please let me know if you bump into any issues!
