### ISSUE TITLE
Add optional RProfile chaining in  renv_infrastructure_write_rprofile 

### ISSUE THREAD

**Issue by slodge** [rstudio/renv#499]
In our local environment we use Rprofile entries to provide several custom options - including setup of private CRAN urls.

As we experiment with using Renv we're hitting issues with the Renv Rprofile hiding the one in the user folder.

We'd quite like to have an option (setup in Rprofile or using an Renviron flag) to allow chaining to be added to Rprofile by default

If following this, we'd add to the code in https://github.com/rstudio/renv/blob/a1069187df857378d3a29b07c582cd4b6d2e57d5/R/infrastructure.R#L13 with some pseudo code like:

```
if (rprofile_chaining_option_set)  {
add  <- c(
  "source(\"~/.Rproflile\")"
  "source(\"renv/activate.R\")"
 )
}
```

Is this something the Renv team are interested in?

Alternatively, could we expose a hook of some kind to allow user to customise the Rprofile?

Happy to assist with PRs on this - but thought we'd start with an issue....

**Comment by kevinushey** [comment]
If I understand correctly, I believe there should already be an `renv` config option to control this -- you can try setting

```
RENV_CONFIG_USER_PROFILE = TRUE
```

in an appropriate `.Renviron` file (maybe your R installation's `Renviron.site`?)

`renv` will read that when loading an `renv` project, and use that to decide if the user profile should also be sourced on initialization. See `?renv::config` for more details.

**Comment by slodge** [comment]
Excellent.

Thanks. It's even documented as the last option on
https://rstudio.github.io/renv/reference/config.html

That's exactly what we need... So closing this. Thanks.

**Comment by slodge** [comment]
Closed. Thanks again and sorry for missing the functionality in the docs!
