### ISSUE TITLE
devtools::install_version shim needs special architecture option

### ISSUE THREAD

**Issue by slodge** [rstudio/renv#500]
We're trying to make `devtools::install_version` work correctly through renv

For example

`
> devtools::install_version("roxygen2","7.1.0")
...
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'roxygen2' in library.dynam(lib, package, package.lib):
 DLL 'rlang' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
`

This seems to fail because of single vs multiple architecture issues.

e.g. it can be made to work with:

`
devtools::install_version("roxygen2","7.1.0", INSTALL_opts = c("--no-multiarch"))
`

Is there some way we can get this to work within renv without the additional option?

**Comment by kevinushey** [comment]
You should be able to just use `renv::install()` here:

```
renv::install("roxygen2@7.1.0")
```

By default, `renv` sets `--no-multiarch` so this should in theory "just work".

**Comment by slodge** [comment]
Thanks. We'd spotted the renv::install option and it works.

Our challenge is that we've got a fair number of existing non-renv repos and a fair number of less technical users (as well as grumpy more technical users) - so we're trying to make the renv revolution seamless - trying to make it feel just like the existing workflow.

This isn't a pressing issue, however - as to be honest `install_version` isn't something we use a lot. We can probably work around this issue with internal documentation and user support - so should we close this as "won't change"?

**Comment by kevinushey** [comment]
Right -- I think ultimately this is something that cannot be fixed in `renv`; I believe `devtools` (or perhaps R itself) would need some mechanism for communicating default options for `INSTALL_opts`.

**Comment by slodge** [comment]
One option we've seen on this is we could use https://github.com/r-lib/devtools/commit/21f6b38819549a5c41fbc6b88fca7d1758612664 

I guess currently we'll set this option in our user's .RProfile file - although it might again be interesting to use some kind of hook in Renv .RProfile generation to add it to local Renv .RProfile files.

**Comment by kevinushey** [comment]
For what it's worth, the `renv` way of accomplishing this currently is via the `install.opts` option; e.g.

```
options(install.opts = list(roxygen2 = "--no-multiarch"))
```

This is documented in `?install` for the development version of `renv`, but not yet in the CRAN release.
