### ISSUE TITLE
install_version does not respect auto snapshot option

### ISSUE THREAD

**Issue by slodge** [rstudio/renv#501]
Possibly linked to #500

After installing using devtools::install_version it seems like the snapshot is *not* automatically taken

e.g. after auto snapshot set with:

```
options(renv.config.auto.snapshot = TRUE) 
# or 
Sys.setenv(RENV_CONFIG_AUTO_SNAPSHOT = TRUE)
```

then we use `devtools::install_version("roxygen2","7.1.0", INSTALL_opts = c("--no-multiarch"))` and still see:

```
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (roxygen2)
In R CMD INSTALL
> renv::status()
The following package(s) are out of sync:

   Package   Lockfile Version   Library Version
  roxygen2              7.1.1             7.1.0

Use `renv::snapshot()` to save the state of your library to the lockfile.
Use `renv::restore()` to restore your library from the lockfile.
```

**Comment by kevinushey** [comment]
Thanks! Right now, `renv` only triggers an automatic snapshot when one of its own installation APIs are called; it's not hooked up to other package installation functions. This is a fixable problem though and I'll see if there's something sensible I can do.

**Comment by kevinushey** [comment]
This should be fixed in the development version of `renv`. You can give it a try with:

```
renv::install("rstudio/renv")
```

If you're able, please give it a try and let me know if you bump into any issues!

**Comment by slodge** [comment]
I'm actually away from the home office for the next 5 days... But I'll get
a colleague to test it out.

Thanks!

**Comment by slodge** [comment]
A colleague has tested this - it works on his machine (y) Thanks!

**Comment by kevinushey** [comment]
Awesome! Glad to hear it -- thanks to your colleague for taking the time to test, and thanks for reporting back.
