### ISSUE TITLE
Separate libraries for different linux distributions

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#505]
There are some environments where the same directory might be shared by multiple linux operating systems (i.e. RSP with Launcher, where a session can be started on a Centos docker image or a Bionic docker image).

It would be nice if `renv` environments were more specific in their library storage than `x86_64-pc-linux-gnu-library`, which is universal across many of the linux operating systems. Instead, it should have directories that correspond to distribution / etc. 

Even if this is not the "default," it would be nice if this were behavior that were possible as an "opt in."

Perhaps related to #253

**Comment by kevinushey** [comment]
This is currently possible via the `RENV_PATHS_PREFIX` environment variable -- from the documentation in `?renv::paths`,

> If you need to share the same cache with multiple different Linux operating systems, you may want to set the RENV_PATHS_PREFIX environment variable to help disambiguate the paths used on Linux. For example, setting RENV_PATHS_PREFIX = "ubuntu-bionic" would instruct renv to construct a cache path like:
> 
> /mnt/shared/renv/cache/v2/ubuntu-bionic/R-3.5/x86_64-pc-linux-gnu
> 
> If this is required, it's strongly recommended that this environment variable is set in your R installation's Renviron.site file, typically located at file.path(R.home("etc"), "Renviron.site"), so that it can be active for any R sessions launched on that machine.

Eventually I'd like to make this (or something similar) the default, but for now at least this should be a workable escape hatch.

**Comment by hadley** [comment]
Now tracking in #1211.
