### ISSUE TITLE
`renv::update("renv")` gives invalid update instructions that result in cURL error 22 - Unprocessable entity

### ISSUE THREAD

**Issue by mlell** [rstudio/renv#506]
I was updating renv today. This resulted in 

* Instructions to record a non-existent renv version in the lockfile
* An cURL error 22 / HTTP error 422 (Unprocessable entity) instead of a more helpful error message.

I used `update` to update renv. That installed the latest commit on the master branch which is `5831de0b` at the time of this writing.

That commit bumped the version number to 0.11.0-21, but no tag named like that exists in the repository, yet. 

This lead to invalid post-install instructions. After installing the new renv version and restarting R, I get the instructions to record renv in the version `0.11.0-21` in the lockfile. But this tag does not exist yet, and calling that command gives the error

```
# Error: failed to parse remote 'rstudio/renv@0.11.0-21' -- download failed [error code 22]
```

**Proposals**:
1. `renv::update()` should download the latest version that has a version tag, instead of the master branch
2. When a non-existent version is requested via the `renv::update("PACKAGE@VERSION")` syntax, the "Error 22"/"Unprocessable Entity"-Warning should be replaced by something more related to the missing version. 

Code and output below:

```
renv::update("renv")
# * Checking for updated packages ... Done!
# The following package(s) will be updated:
# 
# # GitHub =============================
# - renv   [rstudio/renv: f85f2f7b -> 5831de0b]
# 
# Do you want to proceed? [y/N]: y
# Retrieving 'https://api.github.com/repos/rstudio/renv/tarball/5831de0bd139ce4f7cb41c08111a24a601e6d983' ...
# 	OK [downloaded 333.5 Kb in 0.9 secs]
# Installing renv [0.11.0-21] ...
# 	OK [built from source]
# The following package(s) have been updated:
# 
# 	renv [installed version 0.11.0-21 != loaded version 0.9.3-4]
# 
# Consider restarting the R session and loading the newly-installed packages.
# 
# Warning message:
# GITHUB_PAT is unset. Updates may fail due to GitHub's API rate limit.
# 
# To increase your GitHub API rate limit:
# - Use `usethis::browse_github_pat()` to create a Personal Access Token (PAT).
# - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`. 
```

I then cleared my RStudio environment and restarted my R session. I got the following message from renv:

```
# * Project '~/' loaded. [renv 0.11.0-21]
# Warning message:
# renv 0.11.0-21 was loaded from project library, but renv 0.9.3-4 is recorded in lockfile.
# Use `renv::record("rstudio/renv@0.11.0-21")` to record this version in the lockfile.
# Use `renv::restore(packages = "renv")` to install renv 0.9.3-4 into the project library. 
# * The project may be out of sync -- use `renv::status()` for more details.
```

(My project is called `~` because my RStudio runs inside a singularity container that maps my project directory onto the folder `/proj` which is also set as the home directory. So in my case running renv in the home directory is intended.)

Following the instructions by renv got me an error: 
```
renv::record("rstudio/renv@0.11.0-21")
# Error: failed to parse remote 'rstudio/renv@0.11.0-21' -- download failed [error code 22]
# In addition: Warning messages:
# 1: curl: (22) The requested URL returned error: 422 Unprocessable Entity 
# 2: curl: (22) The requested URL returned error: 422 Unprocessable Entity 
```

**Comment by kevinushey** [comment]
Thanks for the bug report, and sorry for the trouble. This should be fixed via https://github.com/rstudio/renv/commit/735e17f696e17873895891f4e0a84c578344e0f6 -- we now query the GitHub `tags` API to find the latest tag, and use that as the associated version when updating to the "latest" version of `renv`.

**Comment by kevinushey** [comment]
Closing as I believe this should be resolved -- please feel free to re-open or file a new issue if you're still having trouble.
