### ISSUE TITLE
Diagnose connectivity errors

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#508]
I had a series of weird errors that I now attribute to a proxy server between the target machine and RSPM/CRAN. Still need to confirm.

Would it make sense to add a verbosity option for downloads that explains which files are downloaded (and why)? Should `renv::diagnostics()` also check sanity of the package repositories?

**Comment by kevinushey** [comment]
This sounds reasonable to me. We could pass the `--verbose` flag to `curl` when it's invoked to start the download.

**Comment by krlmlr** [comment]
That, and a message and the R level for the case of alternative download methods?

**Comment by hadley** [comment]
You can now use `options(renv.download.trace = TRUE)` to get more info.

We'll make a note to document this near the auth section of the main vignette.
