### ISSUE TITLE
Feature request: snapshot a local document template package into the lockfile

### ISSUE THREAD

**Issue by aalexandersson** [rstudio/renv#509]
How can I snapshot a local document template package into the lockfile? I am using CRAN's `renv` 0.11.0 on Windows 10:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.2  htmltools_0.5.0 tools_4.0.2     yaml_2.2.1      tinytex_0.24   
 [6] rmarkdown_2.3   knitr_1.29      xfun_0.15       digest_0.6.25   renv_0.11.0    
[11] rlang_0.4.7     evaluate_0.14  
```

I created a local document template package by following Chester Imay's instructions [here](http://ismayc.github.io/ecots2k16/template_pkg/). The instructions worked fine except that you must also add a description line in template.yaml. There are complementary instructions from the `bookdown` manual [here](https://bookdown.org/yihui/rmarkdown/document-templates.html).

According to the `renv` [FAQ](https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile), you encourage feasible feature requests, This feature request seems highly feasible to me given the importance and ease of using a local document template package. 

I could not figure out to snapshot the source version of the package, therefore I built a binary package version with:
`devtools::build(pkg = "basictemplate", binary = TRUE)`

I installed the binary template package, which by default is named `basictemplate_0.0.0.9000.zip`, with:
`renv::install("V://Testing//renv//local//basictemplate_0.0.0.9000.zip", type="binary")`

I can only snapshot the package with:
`renv::settings$snapshot.type("all")`
and then from the renv.lock copy-paste the basictemplate portion:
```
      "basictemplate": {
      "Package": "basictemplate",
      "Version": "0.0.0.9000",
      "Source": "Local",
      "Hash": "4edabaa51dfcdfe93edb5db45309c490"
    },
```
into the another renv.lock file. As an aside, should the "hash" change when I update the skeleton.Rmd? 

But this manual method is convoluted. Can you please provide a simpler and more automated way to snapshot a local document template package? It does not matter to me if the template package is source or binary but it has to be a local package (unless there is an easy other "private" solution based on the Chester Imay example data). Perhaps a new feature is not required, perhaps better documentation is sufficient.

**Comment by aalexandersson** [comment]
Here is an attempt of an MWE of the issue:
```
# Anders Alexandersson 6-Aug-2020 "renv.r"
# Reproduce renv github issue #509

# 0. Prerequisites
# First create source document package as described at
#    http://ismayc.github.io/ecots2k16/template_pkg/ , mostly this:
# devtools::create("basictemplate")
# dir.create("basictemplate/inst/rmarkdown/templates/report/skeleton",
#     recursive = TRUE)
# devtools::install("basictemplate")
# Aside: Can we create the document package programmatically?
#        Why do we have to edit template.yaml manually etc.?

# Then create binary version:
# # devtools::build(pkg = "basictemplate", binary = TRUE) 

# Then do this:
setwd("V:/Testing/github_issue509")
if (!require(renv)) install.packages("renv")

# 1. Initalize a project
renv::init()

# 2. Restart R
# (RStudio -> Session -> Restart R)

# 3. Install and use binary template package
# (How to install from local sources? The article is not sufficiently clear.
#   https://rstudio.github.io/renv/articles/local-sources.html)

dir.create("./renv/local") # (if it does not exist)
file.copy("basictemplate_0.0.0.9000.zip", "V:/Testing/github_issue509/renv/local/")
renv::install("V://Testing/github_issue509//renv//local//basictemplate_0.0.0.9000.zip",
    type="binary")
# This is the output:
# Installing basictemplate [0.0.0.9000] ...
# OK [installed binary]

renv::status()  #
# * The project is already synchronized with the lockfile.
# But the lockfile only has renv, not the template package:
# {
#  "R": {
#    "Version": "4.0.2",
#    "Repositories": [
#      {
#        "Name": "CRAN",
#        "URL": "http://cran.rstudio.com"
#      }
#      ]
#  },
#  "Packages": {
#    "renv": {
#      "Package": "renv",
#      "Version": "0.11.0",
#      "Source": "Repository",
#      "Repository": "CRAN",
#      "Hash": "1c3ef87cbb81c23ac96797781ec7aecc"
#    }
#  }
#}

renv::settings$snapshot.type("all")
# The following package(s) are installed but not recorded in the lockfile:
#  _
# basictemplate   [0.0.0.9000]
# boot            [1.3-25]
# class           [7.3-17]
# cluster         [2.1.0]
# codetools       [0.2-16]
# foreign         [0.8-80]
# KernSmooth      [2.23-17]
# lattice         [0.20-41]
# MASS            [7.3-51.6]
# Matrix          [1.2-18]
# mgcv            [1.8-31]
# nlme            [3.1-148]
# nnet            [7.3-14]
# rpart           [4.1-15]
# spatial         [7.3-12]
# survival        [3.1-12]
#
# Use `renv::snapshot()` to add these packages to your lockfile.

renv::snapshot()
# The lockfile now includes the template but also 15 not wanted packages:
# The following package(s) will be updated in the lockfile:
#
# CRAN ===============================
# - KernSmooth      [* -> 2.23-17]
# - MASS            [* -> 7.3-51.6]
# - Matrix          [* -> 1.2-18]
# - boot            [* -> 1.3-25]
# - class           [* -> 7.3-17]
# - cluster         [* -> 2.1.0]
# - codetools       [* -> 0.2-16]
# - foreign         [* -> 0.8-80]
# - lattice         [* -> 0.20-41]
# - mgcv            [* -> 1.8-31]
# - nlme            [* -> 3.1-148]
# - nnet            [* -> 7.3-14]
# - rpart           [* -> 4.1-15]
# - spatial         [* -> 7.3-12]
# - survival        [* -> 3.1-12]

# Local ==============================
# - basictemplate   [* -> 0.0.0.9000]
# 
# Do you want to proceed? [y/N]: y
# * Lockfile written to 'V:/Testing/github_issue509/renv.lock'.

# Therefore, I manually copy-paste only the template portion from renv.lock:
#
#    "basictemplate": {
#     "Package": "basictemplate",
#     "Version": "0.0.0.9000",
#     "Source": "Local",
#     "Hash": "4edabaa51dfcdfe93edb5db45309c490"
# },
#
# into the original lockfile.
# It works, but there must be a more efficient way!

```

**Comment by kevinushey** [comment]
I feel like I might not be understanding your issue in its entirety, but https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile might apply here.

Basically, it looks like `renv` doesn't "see" that you are using the `basictemplate` package, so it infers that it should not be placed into `renv.lock`. If you add something like:

```
library(basictemplate)
```

to a file called `dependencies.R`, then things should "just work".

One thing that's not entirely clear to me: is `basictemplate` a sub-folder in the project, or is `basictemplate` the project itself?

Can you elaborate on where exactly the `basictemplate` package is referenced and / or used in your project?

**Comment by aalexandersson** [comment]
The `basictemplate` package has an R markdown file `skeleton.Rmd` which is my project. Basically, the Rmd file helps (or rather will help once I have improved the template) to easily knit a record linkage report using R.  

Great, your suggestion worked for my case. Thanks!! 

You suggested a similar file, `deps.R` in issue #66. That issue also mentioned an alternative solution using a DESCRIPTION file but how was not clear to me. Can you elaborate on how to possibly instead using a DESCRIPTION file? Will the DESCRIPTION file be of the file or of the project? I am interested in the possibility of not having to create this extra file `dependencies.R`. The file is obviously very easy to create but it is still an extra file which could possibly be avoided.

Currently, I do not have a DESCRIPTION file of the project in the project directory named "V:/Testing", but this is the DESCRIPTION file of the package `basictemplate` and in the sub-directory `renv\library\R-4.0\x86_64-w64-mingw32\basictemplate`:
```
Package: basictemplate
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person(given = "First",
           family = "Last",
           role = c("aut", "cre"),
           email = "first.last@example.com",
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: What the package does (one paragraph).
License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a
        license
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Author: First Last [aut, cre] (YOUR-ORCID-ID)
Maintainer: First Last <first.last@example.com>
Built: R 4.0.2; ; 2020-08-04 16:26:27 UTC; windows
```
