### ISSUE TITLE
implement method for getting dependencies from record

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#510]
E.g. `renv_record_dependencies()` would look at the record, try and figure out how to find the associated `DESCRIPTION` file for that package, and then resolve records for those dependencies.

This is currently done sort of implicitly via `retrieve`, but it'd be good to refactor some of this out if possible. (Would be needed for APIs that want to manipulate the lockfile directly without installing packages)

**Comment by ginolhac** [comment]
Hi,
something like `packrat:::recursivePackageDependencies()` would be great to have it ported in `renv`. Something I am using is
to find reverse dependencies in my `renv` projects. Since `renv::dependencies` is not recursive.

```
apply(purrr::set_names(unique(renv::dependencies()$Package)), function(x) packrat:::recursivePackageDependencies(x, lib.loc = .libPaths()[1]))
```
