### ISSUE TITLE
suggestion: mention that renv will not update lockfile unless installed package has explicit reference in repo

### ISSUE THREAD

**Issue by DanOvando** [rstudio/renv#512]
Ran into a thing that confused me for a bit this week. I had a missing package inside an `renv` project that I installed with `renv::install`, which worked fine (I now had access to the package). But, when I ran `renv::status()` it said that my project was up to date with the lockfile, even though the new package was installed inside the project library but was not listed in the lockfile. After some trial and error, I realized that `renv` only noticed that the new package was there and should be updated in the lockfile if it was explicitly referenced somewhere in the repo (e.g. `library(newpackage)` or `newpackage::function()`). 

That makes sense in that you wouldn't want a lockfile filled with packages that aren't referenced anywhere in a repository. But, this behavior did confuse me for a while since the [documentation](https://rstudio.github.io/renv/articles/renv.html#workflow) doesn't mention this behavior clearly, and just says that you should install / uninstall packages normally; I thought there was an error with `renv` so kept trying to reinstall it, reinstall the troublesome package etc, until I realized that I needed to install the package *and* reference it somewhere in the repository. 

If you agree with the need, I'm happy to submit a pull request to the documentation explaining this?

**Comment by kevinushey** [comment]
This is documented in a few places -- e.g. `?renv::snapshot`, and https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile.
