### ISSUE TITLE
renv prevents compilation of TMB models

### ISSUE THREAD

**Issue by DanOvando** [rstudio/renv#513]
Template Model Builder ([TMB](https://github.com/kaskr/adcomp)) does some rather complicated things to compile models. Running into a problem where TMB can't compile models inside an `renv` project

Assuming you're inside an `renv` project, the examples below illustrate the problem. When `renv` is deactivated, the TMB example compiles and runs correctly. Restarting R and activating `renv`, while TMB is in the lockfile and in the `renv` project, it no longer compiles. 

It seems as though it might have to do with the caching of the package creating a path to the TMB package that TMB can't follow (since that `renv/cache/...` path does not exist)

```
packageVersion("renv")
[1] ‘0.11.0.23’

renv::deactivate()

library(TMB)

TMB::runExample("simple", clean = TRUE)

# restart R
renv::activate()

library(TMB)

TMB::runExample("simple", clean = TRUE)

Cleanup:
Building example simple 
Note: Using Makevars in /Users/danovan/.R/Makevars 
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Users/danovan/Library/Application Support/renv/cache/v5/R-4.0/x86_64-apple-darwin17.0/TMB/1.7.18/1500330bbd3c378400d65a5010aa7ce5/TMB/include -I/Users/danovan/packages/ex/renv/library/R-4.0/x86_64-apple-darwin17.0/RcppEigen/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple   -I/usr/local/include   -fPIC  -Wall -g -O2  -c simple.cpp -o simple.o
clang: error: no such file or directory: 'Support/renv/cache/v5/R-4.0/x86_64-apple-darwin17.0/TMB/1.7.18/1500330bbd3c378400d65a5010aa7ce5/TMB/include'
make: *** [simple.o] Error 1
Error in compile(paste0(name, ".cpp"), ...) : Compilation failed
In addition: Warning messages:
1: In file.remove(dynlib(name)) :
  cannot remove file 'simple.so', reason 'No such file or directory'
2: In file.remove(paste0(name, ".o")) :
  cannot remove file 'simple.o', reason 'No such file or directory'
Timing stopped at: 0.033 0.017 0.056

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] TMB_1.7.18

loaded via a namespace (and not attached):
[1] compiler_4.0.2  Matrix_1.2-18   tools_4.0.2     grid_4.0.2      renv_0.11.0-23  lattice_0.20-41
```

**Comment by kevinushey** [comment]
> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Users/danovan/Library/Application Support/renv/cache/v5/R-4.0/x86_64-apple-darwin17.0/TMB/1.7.18/1500330bbd3c378400d65a5010aa7ce5/TMB/include -I/Users/danovan/packages/ex/renv/library/R-4.0/x86_64-apple-darwin17.0/RcppEigen/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple   -I/usr/local/include   -fPIC  -Wall -g -O2  -c simple.cpp -o simple.o
>
> clang: error: no such file or directory: 'Support/renv/cache/v5/R-4.0/x86_64-apple-darwin17.0/TMB/1.7.18/1500330bbd3c378400d65a5010aa7ce5/TMB/include'

Based on this output, the issue here is that the path to the TMP include directory is not being quoted.

I'd recommend filing a bug for the package author, indicating that the paths created here:

https://github.com/kaskr/adcomp/blob/ea5238611af919a67e60ba129a83a7abf1768d58/TMB/R/TMB.R#L1083-L1091

need to be quoted, to ensure spaces (and other special characters) are properly handled.
