### ISSUE TITLE
renv will "close" the current project

### ISSUE THREAD

**Issue by renejuan** [rstudio/renv#514]
Not sure this is intended but I noticed recently that if you are running `renv::init()` in a directory with another RStudio project that is not the current directory then your current RStudio project will be closed. Maybe this should be changed to at least provide the option of keeping your current project open.

**Comment by kevinushey** [comment]
This can be done with e.g. `renv::init(restart = FALSE)`. Still though, the new project is automatically activated after an `init()`; what exactly do you want to do?

**Comment by nielsaka** [comment]
I just tried out *renv* for the first time and ran `renv::init()` as suggested in the [vignette](https://rstudio.github.io/renv/articles/renv.html). The info printed to the console and the interactiveness is great. But then at the very end RStudio suddenly restarts and I can't even read the last info. I am not sure if I had another project open. 

This issue (close current proj and open new one) might be driving this. A question "Do you want to restart R and open the new project [y/N]" or similar would be nice.

Using renv version 0.12.2 from CRAN on R 4.0.2.

**Comment by hadley** [comment]
Looks like this has been fixed — when I run in a fresh package, I see the R session restart, but the RStudio project remains as is.
