### ISSUE TITLE
R packages not installed in renv folder in rocker/shiny Docker image

### ISSUE THREAD

**Issue by gontcharovd** [rstudio/renv#518]
Hello, 

I'm installing packages onto a rocker/shiny:3.6.3 Docker image.
After calling `renv::restore()` in my Docker file, the packages are installed in /usr/local/lib/R/site-library.
I expected the packages to be installed in a folder "renv" in the working directory /home/dashboard.

Is this intended behavior? Did I miss something?

Here is a minimal reproducible example:

Dockerfile:

```
FROM rocker/shiny:3.6.3
RUN R -e "install.packages('renv', version = '0.11.0')"
WORKDIR /home/dashboard 
COPY renv.lock .
RUN R -e "renv::restore()"
CMD tail -f /dev/null
```

renv.lock

```
{
  "R": {
    "Version": "3.6.3",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Packages": {
    "zoo": {
      "Package": "zoo",
      "Version": "1.8-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c2ea03282caa1f6972dc84fc5bf671cc"
    }
  }
}
```

The renv folder does not exist:

```
root@bce0be4d05b9:/home/dashboard# ls -a
.  ..  renv.lock
```

The package zoo is installed here:

```
root@bce0be4d05b9:/home/dashboard# ls /usr/local/lib/R/site-library/ | grep zoo
zoo
```

**Comment by gontcharovd** [comment]
I do get the renv folder if I add `RUN R -e "renv::init()"` right before RUN R -e "renv::restore()" in the Dockerfile.

**Comment by kevinushey** [comment]
I think this is expected -- `renv::restore()` just uses the "default" library paths, and if you haven't explicitly initialized a folder as an `renv` project, then `restore()` will target the default user library rather than the project library.

**Comment by gontcharovd** [comment]
I think you are right. The Docker container works flawlessly without `RUN R -e "renv::init()"` anyway. `renv` makes R package management a breeze, good stuff! I'll close the issue.
