### ISSUE TITLE
Add package license information to lockfile?

### ISSUE THREAD

**Issue by markusdumke** [rstudio/renv#523]
We are using renv to document the R package dependencies in our projects. The lockfile exactly provides what we need for this.

In software projects there is also the need of documenting the licenses of the packages used. So I was wondering if it might be possible to add the licenses of the packages in the lockfile? Like this:

```
"backports": {
      "Package": "backports",
      "Version": "1.1.8",
      "License": "GPL-2 | GPL-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3ef0eac19317fd03c0c854aed581d473"
    }
```

Currently we need to save a text file with package name and license in addition to the lockfile. This seems a bit like duplicated work (dependencies are now listed in two different places, which we have to keep in sync.)

Is this something you could imagine integrating into renv or out of scope?

**Comment by kevinushey** [comment]
Good idea!

One complication here is that many packages include a custom LICENSE file, giving additional details on how the package is licensed to its users. We might need to consider how to store those, as well.

**Comment by markusdumke** [comment]
Yes, I agree, there is the need to download the custom LICENSE files and store those maybe in a folder "Licenses" somewhere.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: licensing is hard to do 100% accurately.  Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
