### ISSUE TITLE
Workflow for restoring Bioconductor packages when updating to new R version

### ISSUE THREAD

**Issue by dchiu911** [rstudio/renv#524]
I've read #244 and #495 and don't think either answer my question directly. I'm trying to update one of my projects to use the newest version of R. Naturally, the first console messages I see are:
```
* The project and lockfile are out of sync -- use `renv::status()` for more details.
Warning message:
Project requested R version '3.5.3' but '4.0.2' is currently being used 
Error in loadNamespace(name) : there is no package called ‘rmarkdown’
Error in loadNamespace(name) : there is no package called ‘rmarkdown’
```
The Bioconductor version for R-3.5 is 3.8, whereas the version for R-4.0 is 3.11. What I expect `renv::restore()` to do automatically is detect that I'm using R 4.0.2 and have a prompt to modify the following part of the lock file so that it uses the repositories from `BiocManager::repositories()` (in this case under 3.11).
```
{
  "R": {
    "Version": "3.5.3",
    "Repositories": [
      {
        "Name": "BioCsoft",
        "URL": "https://bioconductor.org/packages/3.8/bioc"
      },
      {
        "Name": "BioCann",
        "URL": "https://bioconductor.org/packages/3.8/data/annotation"
      },
      {
        "Name": "BioCexp",
        "URL": "https://bioconductor.org/packages/3.8/data/experiment"
      },
      {
        "Name": "BioCworkflows",
        "URL": "https://bioconductor.org/packages/3.8/workflows"
      },
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Bioconductor": {
    "Version": "3.8"
  },
```
But it doesn't, and I get the following error:
```
Error: failed to determine Bioconductor repositories
In addition: Warning messages:
1: could not retrieve available packages for url "https://bioconductor.org/packages/3.8/data/annotation/bin/windows/contrib/4.0" 
2: could not retrieve available packages for url "https://bioconductor.org/packages/3.8/workflows/bin/windows/contrib/4.0" 
3: could not retrieve available packages for url "https://bioconductor.org/packages/3.8/data/experiment/bin/windows/contrib/4.0" 
4: could not retrieve available packages for url "https://bioconductor.org/packages/3.8/bioc/bin/windows/contrib/4.0" 
```
I know that the Bioconductor package versions depend on the Bioconductor version itself, but I was hoping there's a way to make this migration as smooth as possible and minimize the number of packages used in my `renv` that need to have an updated version. The Bioconductor packages will definitely change, and maybe some of the other ones depending on whether there are `Depends: R (>= 4.0)` fields, for example.

My current workflow:

1. Run `options(repos = BiocManager::repositories())`
2. Run `renv::install(vector_of_bioc_packages)` so that the release versions of the Bioconductor packages get installed
3. Manually `renv::restore(packages = package_name)` one by one until they are all restore. I can't just do `renv::restore()` since I'll get the error `Error: failed to determine Bioconductor repositories`, and I can't use `renv::snapshot()` to update the part of the lockfile that tells `renv` what version of bioconductor I'm using since it'll remove all the packages I have yet to restore.

Is there a better way to do this?

**Comment by kevinushey** [comment]
The problem here is that `renv::restore()` wants to install exactly the same packages (and their versions) as recorded in the lockfile, but (if I understand correctly) you really want a brand new lockfile for your new version of R + newer versions of the associated Bioconductor packages.

I think what you ultimately want to do is something like:

1. Read the current list of packages from Bioconductor recorded in the lockfile,
2. Install new versions of those packages,
3. Call `renv::snapshot()` to generate a new lockfile with those newly-installed packages.

Unfortunately, `renv` doesn't export any tools for reading the lockfile at the moment, but you could use some of the unexported functions for now. Something like:

```
# make sure we have latest version of BiocManager
renv::install("BiocManager")

# read lockfile records
lockfile <- renv:::renv_lockfile_read("renv.lock")
records <- lockfile$Packages

# keep only packages from Bioconductor
bioc <- Filter(function(record) {
  record$Source == "Bioconductor"
}, records)

pkgs <- names(bioc)

# install those packages
options(repos = BiocManager::repositories())
renv::install(pkgs)

# create a new snapshot
renv::snapshot()
```

should get you most of the way there. Does that make sense?

**Comment by dchiu911** [comment]
Thanks @kevinushey yes that is basically what I'm trying to do. I think adding the following steps between `renv::install(pkgs)` and `renv::snapshot()` prevents losing all the uninstalled CRAN packages from the lockfile.

Manually changing to the lockfile Bioconductor version:
```
  "Bioconductor": {
    "Version": "3.11"
  },
```
and using `renv::record()` on the new Bioconductor package versions:
```r
renv::record(
  list(
    AnnotationDbi = list(
      Package = "AnnotationDbi",
      Version = "1.50.3",
      Source = "Bioconductor"
    ),
    Biobase = list(
      Package = "Biobase",
      Version = "2.48.0",
      Source = "Bioconductor"
    ),
    BiocGenerics = list(
      Package = "BiocGenerics",
      Version = "0.34.0",
      Source = "Bioconductor"
    ),
    IRanges = list(
      Package = "IRanges",
      Version = "2.22.2",
      Source = "Bioconductor"
    ),
    S4Vectors = list(
      Package = "S4Vectors",
      Version = "0.26.1",
      Source = "Bioconductor"
    ),
    org.Hs.eg.db = list(
      Package = "org.Hs.eg.db",
      Version = "3.11.4",
      Source = "Bioconductor"
    )
  )
)
```
Finally, I can run `renv::snapshot()`

**Comment by kevinushey** [comment]
FWIW, the other way you can force the usage of a particular set of Bioconductor repositories is by setting:

```
options(renv.bioconductor.version = "3.11")
```

**Comment by kevinushey** [comment]
The development version of `renv` now recommends re-initializing the project, using:

```
renv::init(bioconductor = TRUE)
```

The intention here is that, if you're upgrading to a new version of Bioconductor, you're going to want brand-new versions of your project's packages anyhow -- in that case, the lockfile is no longer really relevant; you just want to build a brand new project library with whatever is newest on Bioconductor.
