### ISSUE TITLE
Use with devtools::install - leads to create directory pathing problem

### ISSUE THREAD

**Issue by slodge** [rstudio/renv#526]
I'm currently working on a project following a format similar to https://github.com/sol-eng/bike_predict which has a package project nested inside the project itself

Because some of this project internally uses `futures` one of my requirements is that I need to be able to install the package during development.

I can do this using `install.packages("path", repos = NULL, type="source")` but I'd also quite like to do it using the shorter form `devtools::install('pkg-sub-folder')`

When I try this I get a strange create directory pathing error (see trace below)

Just wondering if this is an easy fix (and whether it's worth addressing). This area where we have a package and some uses of that package together in a larger project - with both of them sharing a single renv environment - is one we're exploring more frequently at present - but I'm wondering if we're choosing the best pattern to do this (see also question on https://community.rstudio.com/t/is-it-possible-to-use-a-single-renv-across-multiple-projects/78340/3)

The trace below was created using RStudio - first by creating a brand new RPackage project, then by calling renv::init, then calling devtools::install()

```
> renv::init()
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- renv   [* -> 0.9.3]

* Lockfile written to 'C:/Source/Repos/Play/ExampleRPackageWithRenv/renv.lock'.

Restarting R session...

* Project 'C:/Source/Repos/Play/ExampleRPackageWithRenv' loaded. [renv 0.9.3]
> devtools::load_all()
Loading ExampleRPackageWithRenv
> devtools::install()
√  checking for file 'C:\Source\Repos\Play\ExampleRPackageWithRenv/DESCRIPTION' (785ms)
-  preparing 'ExampleRPackageWithRenv': (50.2s)
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts (22.3s)
-  checking for empty or unneeded directories
-  building 'ExampleRPackageWithRenv_0.1.0.tar.gz'
   
Running "C:/Source/R/R-40~1.2/bin/x64/Rcmd.exe" INSTALL "C:/source/rtemp\RtmpEtfdwv/ExampleRPackageWithRenv_0.1.0.tar.gz" --install-tests 
Error: failed to create directory at path 'C:/Source/renvR_PROFILE=C:/source/rtemp/RtmpEtfdwv/callr-spr-8b747e33104c'
In addition: Warning message:
In dir.create(rownames(info), recursive = TRUE) :
  cannot create dir 'C:\Source\renvR_PROFILE=C:\source', reason 'Invalid argument'
Traceback (most recent calls first):
20: source(".Rprofile", local = TRUE)
19: withVisible(eval(ei, envir))
18: eval(ei, envir)
17: eval(ei, envir)
16: source("renv/activate.R")
15: withVisible(eval(ei, envir))
14: eval(ei, envir)
13: eval(ei, envir)
12: local(...)
11: eval.parent(substitute(eval(quote(expr), envir)))
10: eval(expr, p)
 9: eval(expr, p)
 8: eval(quote(...), new.env())
 7: eval(quote(...), new.env())
 6: renv::load()
 5: renv_load_project(project)
 4: ensure_parent_directory(projects)
 3: ensure_directory(unique(dirname(path)))
 2: stopf("failed to create directory at path '%s'", rownames(info))
 1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occured
```

**Comment by kevinushey** [comment]
`renv 0.9.3` is a bit old at this point -- are you able to update to `renv 0.12.0`, the latest version on CRAN?

FWIW, given your example I wasn't able to reproduce the error on my Windows machine.

**Comment by slodge** [comment]
Thanks... and sorry for not being on the latest 👍 

I've tried R12 and I'm still seeing issues.

```
Restarting R session...

* Project 'C:/Source/Repos/Play/ExampleRPackageWithRenv' loaded. [renv 0.12.0]
Warning message:
renv 0.12.0 was loaded from project library, but renv 0.9.3 is recorded in lockfile.
Use `renv::record("renv@0.12.0")` to record this version in the lockfile.
Use `renv::restore(packages = "renv")` to install renv 0.9.3 into the project library. 
* The project may be out of sync -- use `renv::status()` for more details.
> renv::record("renv@0.12.0")
* Updated 1 record in "C:/Source/Repos/Play/ExampleRPackageWithRenv/renv.lock".
> devtools::install()
√  checking for file 'C:\Source\Repos\Play\ExampleRPackageWithRenv/DESCRIPTION' (1s)
-  preparing 'ExampleRPackageWithRenv': (1m 12.2s)
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts (30.6s)
-  checking for empty or unneeded directories
-  building 'ExampleRPackageWithRenv_0.1.0.tar.gz'
   
Running "C:/Source/R/R-40~1.2/bin/x64/Rcmd.exe" INSTALL "C:/source/rtemp\RtmpWeOWIp/ExampleRPackageWithRenv_0.1.0.tar.gz" --install-tests 
Error: failed to create directory at path 'C:/Source/renvR_PROFILE=C:/source/rtemp/RtmpWeOWIp/callr-spr-cb08c731245'
In addition: Warning message:
In dir.create(rownames(info), recursive = TRUE) :
  cannot create dir 'C:\Source\renvR_PROFILE=C:\source', reason 'Invalid argument'
Traceback (most recent calls last):
21: source(".Rprofile", local = TRUE)
20: withVisible(eval(ei, envir))
19: eval(ei, envir)
18: eval(ei, envir)
17: source("renv/activate.R")
16: withVisible(eval(ei, envir))
15: eval(ei, envir)
14: eval(ei, envir)
13: local(...)
12: eval.parent(substitute(eval(quote(expr), envir)))
11: eval(expr, p)
10: eval(expr, p)
 9: eval(quote(...), new.env())
 8: eval(quote(...), new.env())
 7: renv_bootstrap_load(project, libpath, version)
 6: renv::load(project)
 5: renv_load_project(project)
 4: ensure_parent_directory(projects)
 3: ensure_directory(unique(dirname(path)))
 2: stopf("failed to create directory at path '%s'", rownames(info))
 1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occured
```

Leave this with me - it feels like this must be something in my environment - will dig some more.

**Comment by kevinushey** [comment]
Thanks! If you can share the sources for your `ExampleRPackageWithRenv` package I can also try and take a look.

**Comment by kevinushey** [comment]
It could also be some kind of bug in `callr` -- you could see if updating that makes a difference.

**Comment by slodge** [comment]
Thanks for your patience

The problem went away and I've not been able to recreate it.

I think the issue must have been something to do with an entry in my user profile .RENVIRON file. Sadly that's changed and isn't source controlled - so I can't go back and reproduce it.

Looking back through the previous trace - especially around the line:

```
... path 'C:/Source/renvR_PROFILE=C:/source/rtemp/RtmpWeOWIp/callr-spr-cb0 ...
```

I can only guess that I somehow had a string that wasn't being picked up correctly from the RENVIRON - I do know my file contained both entries for RENV_CONFIG_USER_PROFILE=TRUE and RENV_PATHS_ROOT=C:/Source/renv.

What this was... was it Windows line ending thing? Was it something to do with my Home directory being a synced remote folder on the network share? was there some quote encoding user error (I know I have used quotes on the right-hand side of the environment setters in the past)?

Anyways... closing this now... thanks for your help above. Sorry I don't actually know what it was. Hope this helps someone in the future...
