### ISSUE TITLE
`renv::init()` fails with path detection

### ISSUE THREAD

**Issue by keita-makino** [rstudio/renv#527]
When I do `renv::init()` **outside RStudio** (in my case VSCode), the following error appears.

```r
> renv::activate()
* Project 'C:/Users/apricot/src/kemakino/research/covid-19-ldt' loaded. [renv 0.12.0]
> renv::init()
Error in normalizePath(path, winslash = winslash, mustWork = mustWork) : 
  file name conversion problem -- name too long?
Traceback (most recent calls last):
5: renv::init()
4: renv_init_validate_project(project, force)
3: renv_file_same(project, home)
2: renv_path_normalize(target, mustWork = FALSE)
1: normalizePath(path, winslash = winslash, mustWork = mustWork)
```

Everything else (e.g., `restore`, `snapshot`, and so on) works. Is this a bug or intended?

**Comment by kevinushey** [comment]
What is the output of:

```R
path.expand("~/")
normalizePath(path.expand("~/"))
```

It seems like R is having trouble normalizing that path, if I understand correctly. (Or, it could be the project path itself, but that seems less likely)

**Comment by keita-makino** [comment]
It gives

```r
path.expand("~/")
[1] "F:\\OneDrive\\Onenote\\?h?L?…?\201?“?g/"
> normalizePath(path.expand("~/"))
[1] "F:\\OneDrive\\Onenote\\?h?L?…?\201?“?g\\"
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="F:\OneDrive\Onenote\?h?L?…???“?g/": The system cannot find the file specified
> here::here()
[1] "C:/Users/apricot/src/kemakino/research/covid-19-ldt"
```

What's this path...? I don't understand at all, though the "F:\OneDrive\Onenote" exists.

**Comment by keita-makino** [comment]
I found that, somehow my path settings for the "Document" folder was wrong.

I fixed it in the registry and now it works, thank you!

**Comment by kevinushey** [comment]
Glad to hear you were able to figure out what was going on!

**Comment by xiaosongz** [comment]
> I found that, somehow my path settings for the "Document" folder was wrong.
> 
> I fixed it in the registry and now it works, thank you!

Same here, could you please let us know more detail about how to change the default path?
