### ISSUE TITLE
How to properly load the renv project from a Windows batch file?

### ISSUE THREAD

**Issue by gontcharovd** [rstudio/renv#532]
I have an R script that I want to run with a Windows batch file.
This file is located in a subfolder of the project_root (where renv/ renv.lock and .Rprofile are located).

This is how I got it to work:

```cmd
CALL "C:\Program Files\R\R-4.0.2\bin\Rscript.exe" -e "renv::load('c:/project_root'); source('c:/project_root/subfolder/script_name.R')"
```

However `renv::load()` is not supposed to be called directly according to the function documentation:

```
# load a project -- note that this is normally done automatically
# when the R session is started in an renv project after calling
# renv::activate()
```

Is the use of `renv::load()` justified in this case?
If not, what is the proper way to activate the renv project if I run my scripts exclusively through a batch.cmd file?

**Comment by kevinushey** [comment]
This should work. Basically, there are two ways to ensure an `renv` project is loaded:

1. Launch R from the project directory, and let the `renv` loader (in the `.Rprofile`) ensure that `renv` is loaded and used for a project;

2. Launch R from an arbitrary directory, but call `renv::load("/path/to/project")` to load the requested project.

Some users might opt for option (2) if they don't want to rely on the `renv` auto-loader in the project `.Rprofile` for whatever reason.

I'll try to clarify this in the documentation to make this more clear.

**Comment by kevinushey** [comment]
I've updated the documentation -- please let me know if everything looks clear and feel free to re-open if not!

**Comment by gontcharovd** [comment]
Yes, it's clear now. Thanks

**Comment by gontcharovd** [comment]
I had one question after all: for this workflow the renv package must be installed in the default library otherwise `renv::load()` can't be called to activate renv, right?

**Comment by kevinushey** [comment]
Indeed, that's correct. (This is one of the benefits of approach 1 -- the autoloader will automatically find and load `renv` as required, even downloading `renv` from CRAN if necessary.)

**Comment by mlamias** [comment]
Anyone know how to load `renv` using the 2. approach above but using `CMD BATCH` instead of `RScript.exe`?  I can't seem to get the syntax right.

Thanks.
