### ISSUE TITLE
`rebuild()`:  respect `repos =` setting?

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#534]
When invoking `renv::rebuild()` currently MRAN snapshot sources are used to re-install packages.

It would be great if `renv::rebuild()` could in some way also only honor the listed "Repositories" in `renv.lock` for non-GH packages rather than always using the MRAN snapshot.

**Comment by kevinushey** [comment]
You can disable MRAN integration with:

```
options(renv.config.mran.enabled = FALSE)
```

Is that sufficient for your case?

**Comment by pat-s** [comment]
Yes, now the RSPM snapshot is used. Thanks!

**Comment by kevinushey** [comment]
Great!

For context, `renv` tries to opportunistically use MRAN binaries if it sees that you're attempting to install or restore a package from CRAN that does not appear to have binary packages available. Setting `options(renv.config.mran.enabled = FALSE)` basically disables that check, but you then may instead need to install packages from the CRAN archive from sources.

(If you're using RSPM and have binaries enabled for your platform, that is likely not an issue though!)

**Comment by pat-s** [comment]
Thanks. 

Yes, the rationale is to strictly stay on the chosen snapshot. If binaries are avail (RStudio Server with RSPM) that's great - otherwise we install from source.
