### ISSUE TITLE
Can't snapshot my own project

### ISSUE THREAD

**Issue by karawoo** [rstudio/renv#538]
This may be an unusual use case, but I have a golem app where I need to snapshot my package itself in its own lockfile. Previously this wasn't a problem, but in trying to upgrade my renv and dependency versions, renv now wants to remove my package from the lockfile. Adding a `dependencies.R` file that loads my package doesn't help. `renv::dependencies()` does detect my package as a dependency, and I'm using implicit snapshots, but it still won't show up in the lockfile. I'm not sure the best way to provide a minimal reprex of this situation, but am happy to do so if you have ideas. Does renv intentionally prevent a package from snapshotting itself? 

I realize it's probably weird to have a project be its own dependency...in our case the package has an app.R file, and we deploy the app to our shiny server by cloning the repo -- but since some of the functions use CSS files accessed with `system.file()`, the package also needs to be installed on the system. Is there any way to snapshot the package, or would we need to create a separate project and treat the package as a more normal dependency from there?

**Comment by kevinushey** [comment]
> Does renv intentionally prevent a package from snapshotting itself?

That's exactly right -- `renv` does tries to explicitly exclude the project package itself if it appears to be an R package:

https://github.com/rstudio/renv/blob/ae1dd544adad04a09bd1309a55731233b598af7c/R/project.R#L148-L154

One potential workaround would be to set the `Type:` field in the DESCRIPTION file; e.g. something like:

```
Type: Golem Application
```

but this might break other package-relating tooling. We could also just consider allowing this behavior to be configured via an R option or something similar. Do you have any thoughts?

**Comment by karawoo** [comment]
Ok that makes sense, it is a pretty unusual thing we're doing 🙂 if you'd be willing to support it via an option that would be great. The other idea I had was allowing `dependencies.R` to supersede renv's internal decisions about what gets snapshotted.

**Comment by slodge** [comment]
I've come across the same restriction - in our case we have several
renvironments which are following a project structure a bit like
https://github.com/sol-eng/bike_predict with jobs, apps and reports that
all rely on a central package.

The option would be useful for us too :+1:

**Comment by kevinushey** [comment]
I've made a couple changes on master:

By default, we no longer ignore the project itself if we see the project is using golem -- that is, if `inst/golem-config.yml` exists.

In addition, the behavior can now also be controlled via the R option `renv.config.ignore.self`; e.g.

```
options(renv.config.ignore.self = FALSE)
```

**Comment by karawoo** [comment]
Thanks @kevinushey!
