### ISSUE TITLE
skip retrieval of packages already installed when appropriate

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#54]
ref: https://github.com/rstudio/renv/blob/dc18c0504ddf6ed261d1f945f1d7274817862803/R/install.R#L112

**Comment by michaelhogersosis** [comment]
Hi @kevinushey, we are in the process of adopting renv for our automated R Shiny builds that use Docker. renv really works like a charm to ensure all library dependencies used by both developers and our production environment (a Docker image for example) are aligned. 

Currently there is only one real downside and that is the build time when using a linux based docker image with renv to install all relevant libraries. 

There are two options currently I think. First option, we create a second docker image that serves as a base image containing all libraries by using renv, this image can then be used by another docker image and should keep build times fast.  Second option, we accept the long build times (> 1 hour as of now), as it decreases the Docker overhead for us, but it does complicate the feedback loop from our automated test suit. 

Perhaps you have experience with Docker and renv and I am curious whether you have a nice solution to keep build times fast. I personally develop on a Windows machine, perhaps there are settings available to speed up the installation of libraries on linux?

**Comment by kevinushey** [comment]
The solution here is to indeed set the `RENV_PATHS_CACHE` environment variable to point at a mounted directory. Pseudo-code for how I think this could be accomplished when running docker:

```
docker run \
    -e "RENV_PATHS_CACHE=/mnt/renv/cache" \
    -v /path/to/local/renv/cache:/mnt/renv/cache \
    < ... >
```
