### ISSUE TITLE
Error if missing package version

### ISSUE THREAD

**Issue by lazappi** [rstudio/renv#540]
Hi

I was getting the following error from most **renv** functions (`renv::status()`, `renv::snapshot()`...):

```
Error in if (eval(cond, envir = environment(dot))) return(eval(expr, envir = environment(dot))) : 
  argument is of length zero
```

Using `traceback()` and `debug()` I was able to track it down to the `renv:::renv_lockfile_diff_record()` function, particularly these lines: https://github.com/rstudio/renv/blob/5831de0bd139ce4f7cb41c08111a24a601e6d983/R/lockfile-diff.R#L50-L55

Eventually, I worked out that one of the entries in my `renv.lock` file was missing a version number:

```json
    "reticulate": {
      "Package": "reticulate",
      "Source": "Repository",
    },
```

This was causing the comparison between `before$Version` and `after$Version` to fail. The easy fix was to manually edit `renv.lock` to add the version.

I'm not sure how I managed to have an entry without a version but thought I should report the issue in case somebody else manages to do the same thing.

My suggestion would be to add a check somewhere and give a more informative error if there is no version. I would be happy to help with a PR for that but I'm not sure if it is best to do it in this function or somewhere upstream?

**Comment by kevinushey** [comment]
I'd be curious to know how you got into this state -- normally, lockfile entries should have a version.

**Comment by kevinushey** [comment]
Ah, I bet this was caused by calling `renv::record()` without a package version.

**Comment by lazappi** [comment]
I don't remember doing that but it's definitely possible 👍! Maybe another potential place for a check?

**Comment by harrismcgehee** [comment]
I had the same experience and I believe I got into the state by using `renv::record()` as speculated.

The `record`ed package is not referenced directly and is only a suggested package by another package that is in the lock file.

**Comment by kevinushey** [comment]
This should now be rectified in the development version of `renv` -- thanks for reporting!
