### ISSUE TITLE
Initializing renv causes RStudio to collapse with R 3.6.3

### ISSUE THREAD

**Issue by manumanul** [rstudio/renv#541]
I recently installed both R and RStudio on a new computer, and wanted to create an RProject. I used to use the package *renv* before and it worked pretty well so far.

However, when I tried to initialize the renv library it first created all the necessary folders within the Rproject, but then suddenly gives th following error:

```Fehler in data[[1]] . Indizierung ausserhalb der Grenzen```

Afterwards it says: *Fataler Fehler: unable to initialize the JIT*

![](https://i.stack.imgur.com/uqqBA.png)

And finally produces a fatal error and collapses.

I already un- and reinstalled both R and RStudio twice, but without success. It works with R 4.0.2, however since my collegues work with 3.6.3 I really want to stick to R 3.6.3 as well!

Any ideas?

```sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252   
[3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=German_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    yaml_2.2.1     tinytex_0.20   xfun_0.12          ```

**Comment by kevinushey** [comment]
Does the error reproduce outside of RStudio?

**Comment by manumanul** [comment]
Yes, it does. Same story when I work directly in R.

**Comment by kevinushey** [comment]
To resolve this, I think we'd need to figure out where this is coming from:

```
Fehler in data[[1]] . Indizierung ausserhalb der Grenzen
```

My best guess is that this is coming from something in the (user? project?) `.Rprofile` -- errors that occur when running the `.Rprofile` unfortunately can cause surprising issues when launching RStudio.

**Comment by kevinushey** [comment]
Unfortunately, without more information (or a reproducible example) there's not much we can do to help.
