### ISSUE TITLE
tutorial exercises trip up dependency detection

### ISSUE THREAD

**Issue by garrettgman** [rstudio/renv#542]
I'm using renv to manage a repository of learnr tutorials. The tutorials provide a lot of incomplete code for the students to complete, like this:

````
```{r unite-code-0, exercise = TRUE}
unite_test %>%
  unite(combined, left:right, ____ = " | ", ____ = FALSE)
```
````
This code raises errors when I run `renv::snapshot()`, like this
```
ERROR 1: <text>:148:31: unexpected input
147: unite_test %>%
148:   unite(combined, left:right, _
                                   ^
```
Which is a shame, because it is quite important to manage the package dependencies for the tutorial library. **I'd like `renv` to automatically detect dependencies without throwing errors for these chunks.**

The learnr based exercises systems that we use provide one path for accommodating this:

"Broken" code will only appear in chunks that:

1. have the chunk option `exercise = TRUE`, or
1. have a chunk label that ends in `-display`

These chunks could be treated as if they were not evaluated in the final document (`eval = FALSE`). They are usually accompanied by a solution chunk that contains the desired, working code.

**Comment by kevinushey** [comment]
Thanks! Should be fixed in the development version of `renv` now.

https://github.com/rstudio/renv/commit/7dd7c94769eef279f2348dd9ced79f5a01711d5e
