### ISSUE TITLE
`renv::status()`: option to ignore user library (when enabled)

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#545]
I have set `RENV_CONFIG_USER_LIBRARY = TRUE` and facing the problem that `renv::status()` reports (correctly) that some packages are out of sync.

This is due to different versions of these packages in the project and user library.
It would be great if `renv::status()` could ignore the user library for such checks.

**Comment by kevinushey** [comment]
Would you be able to share a reproducible example, just so I better can understand what's going on?

**Comment by pat-s** [comment]
I think I got confused and an `renv::restore()` helped and now everything works as expected. Sorry 🤯
