### ISSUE TITLE
Updating 1 package is deleting several others

### ISSUE THREAD

**Issue by kylegilde** [rstudio/renv#549]
Hi, I'm trying to update the parsnip package, but when I take a snapshot, it keeps trying to delete a bunch of other packages. Am I doing something wrong? 

Thank you

**Commands**
`
sessionInfo()

setwd("~/ds_machine_learning")

system("ls")

renv::hydrate()

renv::restore()

renv::update("parsnip")

renv::snapshot()

`
**Output**

R version 3.4.0 (2017-04-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_3.4.0      tools_3.4.0        
[4] rstudioapi_0.11     renv_0.10.0        
* Discovering package dependencies ... Done!
* Copying packages into the library ... Done!
The following package(s) will be updated:

CRAN ===============================
- parsnip   [0.1.3 -> 0.1.1]

Do you want to proceed? [y/N]: y

Installing parsnip [0.1.1] ...
	OK (copied cache)

Do you want to proceed? [y/N]: y

* Checking for updated packages ... Done!
The following package(s) will be updated:

CRAN ===============================
- parsnip   [0.1.1 -> 0.1.3]

Installing parsnip [0.1.3] ...
	OK (copied cache)
The following package(s) will be updated in the lockfile:

CRAN ===============================
- BH                 [1.72.0-3 -> *]
- Lahman             [7.0-1 -> *]
- OptimalCutpoints   [1.1-4 -> *]
- PRROC              [1.3.1 -> *]
- R.methodsS3        [1.7.1 -> *]
- R.oo               [1.23.0 -> *]
- R.utils            [2.9.2 -> *]
- ROCR               [1.0-7 -> *]
- ThresholdROC       [2.8.2 -> *]
- askpass            [1.1 -> *]
- bit                [1.1-14 -> *]
- bit64              [0.9-7 -> *]
- bitops             [1.0-6 -> *]
- blob               [1.2.0 -> *]
- brew               [1.0-6 -> *]
- caTools            [1.17.1 -> *]
- callr              [3.4.0 -> *]
- clipr              [0.7.0 -> *]
- curl               [4.3 -> *]
- desc               [1.2.0 -> *]
- forcats            [0.4.0 -> *]
- gdata              [2.17.0 -> *]
- gplots             [3.0.1.2 -> *]
- gtools             [3.5.0 -> *]
- hms                [0.5.2 -> *]
- httr               [1.4.1 -> *]
- kableExtra         [1.1.0 -> *]
- microbenchmark     [1.4-7 -> *]
- nycflights13       [1.0.1 -> *]
- openssl            [1.4.1 -> *]
- parsnip            [0.1.1 -> 0.1.3]
- pkgbuild           [1.0.6 -> *]
- pkgload            [1.0.2 -> *]
- praise             [1.0.0 -> *]
- processx           [3.4.1 -> *]
- ps                 [1.3.0 -> *]
- readr              [1.3.1 -> *]
- rprintf            [0.2.1 -> *]
- rprojroot          [1.3-2 -> *]
- rvest              [0.3.5 -> *]
- selectr            [0.4-2 -> *]
- sos                [2.0-0 -> *]
- sys                [3.3 -> *]
- testthat           [2.3.1 -> *]
- webshot            [0.5.2 -> *]
- xml2               [1.2.2 -> *]
- zeallot            [0.1.0 -> *]
- vip                [* -> 0.2.2]

Do you want to proceed? [y/N]: N

* Operation aborted.

**Comment by kevinushey** [comment]
This most likely implies that `renv` no longer sees these packages as "used" in your project. Does https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile answer your question?

**Comment by kylegilde** [comment]
I think it does. Thanks!

**Comment by kevinushey** [comment]
Glad to hear it!
