### ISSUE TITLE
Error retrieving packages on restore

### ISSUE THREAD

**Issue by brianperdomo** [rstudio/renv#551]
I am unable to restore my packages. I've been trying everything I could find on the internet, but haven't found someone else having this issue. I've tried this using both wininet and libcurl as my download method... same difference.

Any help would be greatly appreciated!

```
Retrieving 'https://cloud.r-project.org/src/contrib/Archive/backports/backports_1.1.4.tar.gz' ...
Error: failed to retrieve package 'backports'
In addition: Warning messages:
1: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate. 
2: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate. 
```

Session Info:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.2    assertthat_0.2.1  cli_2.0.2         tools_4.0.2       withr_2.2.0       glue_1.4.0        rstudioapi_0.11   crayon_1.3.4      fansi_0.4.1      
[10] renv_0.11.0       sessioninfo_1.1.1
```

**Comment by kevinushey** [comment]
Sorry, I'm not sure what's going on but it's most likely some kind of certificate / configuration issue on your machine.

**Comment by kevinushey** [comment]
See e.g.

https://stackoverflow.com/questions/45556189/git-the-revocation-function-was-unable-to-check-revocation-for-the-certificate

https://stackoverflow.com/questions/54938026/curl-unknown-error-0x80092012-the-revocation-function-was-unable-to-check-r

Sounds like the most likely issue here is that you're working in a corporate environment with a MITM proxy that's causing issues here.
