### ISSUE TITLE
Clarify isolate() usage

### ISSUE THREAD

**Issue by kdkavanagh** [rstudio/renv#555]
My understanding from the documentation for `isolate()` is that it should create a copy of the cache and install packages from that copy into the activated renv.  However, the source code for `isolate()` just seems to disable the cache (vs copying the cache), and running `restore()` after `isolate()` results in a otherwise-cached packages being install from CRAN.  

Curious if there was a regression somewhere which prevented the cache from getting copied, or if my interpretation of the docs is incorrect?

**Comment by kevinushey** [comment]
Can you provide a reproducible example? This seems to work as I would expect:

```
* Project '/private/tmp/renv-isolate' loaded. [renv 0.12.0]
> renv::isolate()
* Copying packages into the private library ... Done!
* The cache has been disabled for this project.
>
```

Note that the logic for handling this lives here:

https://github.com/rstudio/renv/blob/4a8bcb4605f085fbea5f29a76ad9a291ac2bd363/R/settings.R#L167

although I realize now that it's not enabled on Windows (the motivation for being disabled there seems incorrect?)

**Comment by kdkavanagh** [comment]
I think what I was missing is that the order of operations seems to be important - I'm activating a project by explicitly setting it's path vs starting R from within that project's directory.  As a result, I had the following set of calls.  Thought process behind this was "When I restore the library, I want to make sure that it's isolated/things are copied in instead of symlinked":

```
renv::activate()
renv::isolate()
renv::restore()
```

Since isolate has the side-effect of setting `use.cache = FALSE`, the call to `restore` obviously wouldnt check the cache.  

If I flip the order of operations such that I call `restore` _then_ `isolate`, things seem to work as expected.  

Somewhat related, would be helpful to have a way to override the project's settings.dcf at runtime, or provide `use.cache` as an argument to `restore` and eliminate any ambiguity.  Since `isolate` modifies the settings.dcf file, other processes activating the same project (but using differently library paths - HPC-style usecase) will not be able to use the cache.  In other words, is there a way to make the cache setting a property of the _library path_ rather than a property of the renv project?

**Comment by kdkavanagh** [comment]
Perhaps a way to say "Use the cache, but copy instead of symlink" during `restore` would be sufficient, effectively isolating w/o disabling the cache
