### ISSUE TITLE
Installation fails with 'main' as the default branch name on `renv::install()`

### ISSUE THREAD

**Issue by uribo** [rstudio/renv#557]
GitHub has announced that the default branch name of the repository will change from `master` to `main`.
https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/
This causes the installation of the new package repository to fail.

```r
renv::install("uribo/tororomecab")
#> Error: failed to parse remote 'uribo/tororomecab' -- download failed [error code 22]
#> In addition: Warning messages:
#> 1: curl: (22) The requested URL returned error: 422 Unprocessable Entity 
#> 2: curl: (22) The requested URL returned error: 422 Unprocessable Entity 
```

I was able to install it by specifying the branch as follows. 

```r
renv::install("uribo/tororomecab@main")
```

However, I feel that it would be better to support both master and main by default to prevent the same problem.

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be fixed in the latest development build of `renv` via https://github.com/rstudio/renv/commit/b570aa9cb49acf368bf7e8a821e65a75967d332f.
