### ISSUE TITLE
Provide some equivalent to npm package.json's postinstall scripts / add "scripts" field to lockfile

### ISSUE THREAD

**Issue by strazto** [rstudio/renv#558]
I'm interested in automating initialization of certain git hooks to enforce commit style on my repos. 

In javascript, a pattern for achieving this is to use the package.json's "scripts" field, with a postinstall script. See https://typicode.github.io/husky/#/ 

This would make sense for renv, if a project has conventions/toolings, it would be nice to have a way to bootstrap toolings, & to help enforce these.

**Comment by kevinushey** [comment]
`renv` does something somewhat similar: it uses the project `.Rprofile` to ensure Git hooks are active that bump the DESCRIPTION version on every commit to master.

https://github.com/rstudio/renv/blob/b570aa9cb49acf368bf7e8a821e65a75967d332f/.Rprofile#L2


`renv` also has the (currently undocumented) notion of an `renv/settings.R` file, which likely is sourced when a project is loaded.

Are either of these mechanisms suitable for what you need?

**Comment by matthewstrasiotto** [comment]
Renv/settings.R will probably be sufficient for running some shell script that bootstraps the hooks.

Thank you, Kevin
