### ISSUE TITLE
Provide a means to initalize a renv project without using the global package library

### ISSUE THREAD

**Issue by mlell** [rstudio/renv#560]
Using renv enables me to have a separate library for each of my projects, completely avoiding the use of any user or system library. In this light, it seems strange to me that in order to install renv, I need to use the global package library. We deploy R in containers in our institution and don't know what the users do besides that. For example, our users could have a user library for other projects and different versions of R, that does not distinguish between R versions from following some barely-understood blog tutorial. Or they could use different containers with the same R versions but different libcs (e.g. Alpine vs Debian...)

When I was explaining renv to my biologist users, it took them a good portion of thinking to learn about the package library, and to understand `init`, `snapshot`, and `restore`. I then have to go on to troubleshoot problems with mismatching R internals or missing user libraries (for example, on our system, `install.packages` tries to install packages to the folder `NA`...) just for the one-time-task of initializing an renv project. It is unnessecarily cumbersome to explain users that with renv they don't need to care about different libraries for different R versions coming in conflict, but in order to install it they need to know the state of their user or system library. 

It is almost there: renv already has the means to install itself as part of hydrating. So why not provide a script that installs the latest CRAN version of renv directly into a new package library?

Currently this can be achived by executing

```r
source("https://raw.githubusercontent.com/rstudio/renv/(COMMIT ON CRAN)/renv/activate.R"
```

However, this is a bit cumbersome and by replacing `(COMMIT ON CRAN)` with `master` users might get an unstable version. 

So why not create a script with an easy-to-remember link that points to the latest CRAN `renv/activate.R`, like for example `https://rstudio.github.io/renv/install.R`?

**Comment by kevinushey** [comment]
That seems reasonable to me.

**Comment by hadley** [comment]
If you don't want to use packages from the system library during init, you can run `renv::init(bare = TRUE)`. This still assumes that you have installed renv into the system library, which is the case for the vast majority of renv users. Currently, we have heard few requests for renv initialisation sans install, so we're not planning on working on it at this time, but we'll certainly keep an eye on the situation.
