### ISSUE TITLE
renv::snapshot working only with absolute file paths

### ISSUE THREAD

**Issue by vladimir-obucina** [rstudio/renv#562]
I've had problem with snapshotting my local library with R packages used in project. I have separate directory for all the libraries used in project, it's called "userLibrary", so when I type in command (my working dir is set to the project):

`renv::snapshot(getwd(), lockfile = "renv.lock", library = "userLibrary/", confirm = FALSE)`

I get an error (I've excluded all packages, just showing first few) saying: 

```
renv was unable to snapshot the following packages:

'anytime': renv_path_absolute(path) is not TRUE, 
'askpass': renv_path_absolute(path) is not TRUE, 
.......

```
But it works well if I try:

`renv::snapshot(getwd(), lockfile = "renv.lock", library = paste0(getwd(),"/userLibrary/"), confirm = FALSE)`

I think this needs to be solved, cause it's a bit confusing for some users, maybe they're used to package functions working with both absolute and relative paths.

**Comment by kevinushey** [comment]
Thanks for the bug report! Should now be fixed in the development version of `renv`.
