### ISSUE TITLE
renv and containers

### ISSUE THREAD

**Issue by kkmann** [rstudio/renv#563]
Hey,

I think I might have a problem that is not yet covered by https://rstudio.github.io/renv/articles/docker.html

I want to create a custom docker container (other stuff) and then install the packages specified in an renv.lock file during the build. 
I want to be able to use the container as non-root user as well for HPC portability, e.g., using singularity. 

My fist impression was to only modify RENV_PATHS_CACHE to some shared location in the container (/usr/share/renv) and 
the use `renv::restore(prompt = FALSE)`. 
This would install the cache in a location that can later be accessed by other users as well. I then run into problems with shared libraries not being found. 
I can circumvene that by setting the RENV_PATHS_ROOT to the current working directory (which is writable). renv complains about broken symlinks but restores the packages all-right from the cache. 

I guess, ideally I would want to use the information in renv.lock to install all packages on the system level is there any functionality in renv that could help me do that?
Alternatively, how do I safely restore an renv to the host project folder when the cache is inside of  a container?

edit: the julia package manager allows multiple 'depots', this allos me to append the depot that I have in the container to the user depot. Whatever is not found in the current users depot is then taken from the container.

**Comment by kevinushey** [comment]
I don't have any specific recommendations, but https://github.com/cole-brokamp/singr may be useful?

> I guess, ideally I would want to use the information in renv.lock to install all packages on the system level is there any functionality in renv that could help me do that?

You can use `renv::restore(library = renv:::renv_libpaths_system())` to explicitly force the restore to update packages in the system library rather than the project library.
