### ISSUE TITLE
RENV_PATHS_LIBRARY_ROOT leads to conflicts

### ISSUE THREAD

**Issue by klmr** [rstudio/renv#564]
I’m using `RENV_PATHS_LIBRARY_ROOT` to use ‘renv’ during package development, and this works quite well. However, I often have projects (most throw-away, some bigger) with identical names. This even happens during package development, because I occasionally check out multiple copies of a project when working on multiple branches simultaneously (Git purists might say this is bad practice, but it’s fairly common, and sometimes just practical).

Unfortunately this causes conflicts since the libraries in `RENV_PATHS_LIBRARY_ROOT` are identified only by a single folder name rather than by a complete path. That is, a library for a project `X` is located at the path `$RENV_PATHS_LIBRARY_ROOT/‹X›/%v/%p`.

I suggest changing this by replacing the `‹X›` by a slug of the whole path to `X`. Obviously this means that moving the project to a different location in the file system renders the library path stale (I don’t see that as a big problem).

As an example for slugging the paths, Vim uses `%` in place of `/` for undo and swap files (for reasons unknown to me, Vim doesn’t seem to escape `%` in the original path though, so `foo/bar` and `foo%bar` still conflict, despite this being trivially solvable).

**Comment by kevinushey** [comment]
This sounds reasonable to me. For reference, here's where we form the library path when `RENV_PATHS_LIBRARY_ROOT` is set:

https://github.com/rstudio/renv/blob/8a36e46ce872d65fbd59f7cb6bb44e5d7155d23a/R/bootstrap.R#L233-L235

The only other downside is that you end up with a potentially long / "ugly" path name. I wonder if we could also have a compromise where each project gets a unique "id" and these paths are formed as e.g.

```
<name>-<id>
```

That unique `id` could be stored within the project, e.g. at `renv/id` or something similar.

**Comment by klmr** [comment]
> The only other downside is that you end up with a potentially long / "ugly" path name.

I’m not sure that’s a problem, since these paths are not usually getting shown to users. But I’m totally fine with a compromise.

Besides using explicit IDs (requires more work for users, if I understand you correctly; though that’s not a deal-breaker!), an alternative would be to use hashes of the absolute paths. Something like Git’s truncated SHA-1 hashes could work: collisions should still be very unlikely (≪ 1%). E.g. the project located at `/Users/konrad/projects/example` would be `example-c9fa888`.
