### ISSUE TITLE
Setting `renv.lock` location globally?

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#567]
In a project with a monorepo setting the following structure exists:

```
$DRIVE (network drive)
  - renv/RENV_CACHE
  - renv/RENV_BINARY
  - renv/RENV_SOURCE
  - renv.lock
  - renv/activate.R
  
$LOCAL 
   - project1
   - project2
   - projectX
```

Idea: All projects should share the same `renv.lock` file by default which should live in `$DRIVE`.

The issue we are facing is that the `lockfile` argument in all {renv} functions points to the project directory and can not be set via an env var.

Hence, for every call to `renv::snapshot()` or `renv::restore()` from within a project, `lockfile` needs to be set explicitly, otherwise an `renv.lock` file will be created in the project directory.
This is not a longterm solution and currently we are working around the problem by redefining customized {renv} functions with hardcoded paths for `lockfile` pointing to `$DRIVE`.

(We are accounting for the location of `$DRIVE/renv/activate.R` in the global `.Rprofile`)

Would it be possible to define a global env var `RENV_PATHS_LOCKFILE` similar to the already existing `RENV_PATHS_*` ones?

**Comment by krlmlr** [comment]
Is this the `RENV_PROJECT` environment variable by any chance?

**Comment by kevinushey** [comment]
It sounds like you really just want:

```
renv::activate("$DRIVE")
```

in each project, so that each local project is using the same `renv` project on your external drive. (You could use `RENV_PATHS_LIBRARY` to make sure each project gets its own unique library path in that case as well)

**Comment by pat-s** [comment]
Thanks Kevin. We are still exploring what might be the best way. We will report back once we found a solution.

**Comment by pat-s** [comment]
We went with `renv::load()` and it works great so far. Thanks for the help!
