### ISSUE TITLE
Renv does not detect dependencies in .Rprofile

### ISSUE THREAD

**Issue by jaspervanm** [rstudio/renv#569]
When I initiate renv using `renv::init()`, or manually scan for dependencies with `renv::dependencies()`, any `library()` calls in `.Rprofile` are not picked up.
As soon as I save the `.Rprofile` file as a file with the `.R` extension, the dependencies are shown.

Is this expected behaviour? Shouldn't the dependencies in `.Rprofile` also be detected?  
I am used to loading a few libraries I use throughout my project in the `.Rprofile` file.

**Comment by kevinushey** [comment]
To be clear, are you talking about the project `.Rprofile` or the one located at `~/.Rprofile`?

**Comment by jaspervanm** [comment]
At least the project .Rprofile; I haven’t checked ~/.Rprofile because I do not use it.

**Comment by kevinushey** [comment]
Thanks! This is now fixed in the development version of `renv`.
