### ISSUE TITLE
error with renv on Binder

### ISSUE THREAD

**Issue by ivan-paleo** [rstudio/renv#575]
I have used the package [holepunch](https://github.com/karthik/holepunch) to create a Dockerfile (using the function `write_dockerfile()`) and a Binder badge (function `generate_badge()`).

When I try t launch Binder, I get an error (see screenshot).

![Binder_build-logs](https://user-images.githubusercontent.com/12525997/99772716-976bef80-2b0b-11eb-938e-f3f58fa528bc.PNG)

Any idea what could be the cause?

**Comment by kevinushey** [comment]
The problem here is that `renv` is not installed in the project library, and so `renv` is trying to install itself from the declared package repositories. Unfortunately, `renv 0.12.2` isn't actually available from the older MRAN snapshot you've set.

The fix here would be to ensure that `renv` is installed from CRAN as opposed to an older MRAN snapshot.

**Comment by ivan-paleo** [comment]
Thank you for the very quick answer?
How can I ensure that renv is installed from CRAN?

**Comment by kevinushey** [comment]
Unfortunately I'm not sure -- I presume that would need to be configured on the `holepunch` side somewhere.

Alternatively, `renv` could probably handle this by attempting to bootstrap itself from CRAN explicitly (and ignoring the repositories already set)

**Comment by ivan-paleo** [comment]
Good that I cross-referenced to holepunch :)

**Comment by ivan-paleo** [comment]
Thank you anyway!

**Comment by kevinushey** [comment]
I've made a change in `renv` that should help resolve this issue:

https://github.com/rstudio/renv/commit/32c1ff2c6e90a3202a931d5ea208b54a329781e5

Now, `renv` will always attempt to bootstrap itself from CRAN in addition to whatever the default repositories are. Hopefully you'll see the fix when the next version of `renv` is published to CRAN!

**Comment by ivan-paleo** [comment]
Thank you!

**Comment by ivan-paleo** [comment]
renv 0.12.3 is now on CRAN. Does that version solve the issue already? Thank you for the info!

**Comment by kevinushey** [comment]
Sorry, no, not yet -- it will be part of the next CRAN release.
