### ISSUE TITLE
renv occasionally fails to copy a package to the cache

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#577]
Observed the following on Windows with renv 0.12.2:

- installed a large number of packages via `renv::install()`, in batches of 10; sometimes dependent packages were installed too
- called `renv::snapshot()` after each batch
- removed `renv/library`
- restarted R
- called `renv::restore()`

The restore showed quite a few packages with the annotation "Copying ... into the cache". At the beginning I saw "Retrieving ..." for some packages too.

Does this ring a bell? I can try to whip up a reprex.

CC @pat-s.

**Comment by kevinushey** [comment]
A reprex would be greatly appreciated -- thanks!

**Comment by krlmlr** [comment]
One more thing: I did a second iteration of removing/restarting/restoring, in the second iteration no more "Retrieving ...", I suspect all packages will be installed from the cache.

Will get back with a reprex.

**Comment by krlmlr** [comment]
Can't reprex in Linux with 0.12.2 and the following code that closely mimics our setup on Windows:

```
withr::with_tempdir(clean = FALSE, {
  print(getwd())
  
  options(renv.settings.snapshot.type = "all")
  options(renv.config.cache.symlinks = FALSE)
  
  dir.create("renv-root")
  Sys.setenv(RENV_PATHS_ROOT = normalizePath("renv-root"))
  
  renv::init()
  renv::snapshot(prompt = FALSE)
  
  renv::install("here")
  renv::snapshot(prompt = FALSE)
  unlink("renv/library", recursive = TRUE)
  renv::restore(prompt = FALSE)
  unlink("renv/library", recursive = TRUE)
  renv::restore(prompt = FALSE)
})
```

It's a pity that reprex currently fails with renv...

**Comment by krlmlr** [comment]
My latest attempts don't reproduce on Linux, giving up. All packages show "copying to cache" on the first attempt. Will keep an eye open and test on Windows later.

```r
# Save to file, run with R -q -f file.R

dir <- "reprex"
unlink(dir, recursive = TRUE)
dir.create(dir)
setwd(dir)

dir.create("libs-user")
Sys.setenv(R_LIBS_USER = normalizePath("libs-user"))

.libPaths(normalizePath("libs-user"))

options(renv.config.cache.symlinks = FALSE)

dir.create("renv-root")
Sys.setenv(RENV_PATHS_ROOT = normalizePath("renv-root"))

install.packages("renv")

system('R -q -e "renv::init(); renv::snapshot(prompt = FALSE)"')

source("renv/activate.R")

options(renv.settings.snapshot.type = "all")

renv::install(c("abind", "acepack", "alphavantager"))
```

**Comment by krlmlr** [comment]
This issue still persists on Windows.

**Comment by kevinushey** [comment]
I'll try to take a look tomorrow.

**Comment by kevinushey** [comment]
I wasn't able to reproduce locally. :-/ I feel like an installation log might be helpful here. Best guess: it feels like there might be some `renv::install()` code paths that (unexpectedly) bypass the cache?

**Comment by krlmlr** [comment]
Do we have better logging now?

**Comment by hadley** [comment]
Is this still a problem?

**Comment by hadley** [comment]
Since it's been a couple of weeks and we haven't heard anything more, I'm going to close this issue.
