### ISSUE TITLE
<project-root>/renv/local requires full tar.gz path, not just package name ... is this expected?

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#578]
Hi, I'm trying to bundle some custom packages with a project, and I've following the instructions in the [_Installing from Local Sources_](https://rstudio.github.io/renv/articles/local-sources.html) article. My interpretation of the documentation suggests that for package `mypkg` placed in `./renv/local/` (relative to the project's root) one can install it using:
```R
renv::install("mypkg")
```
... and that, upon failing to locate `mypkg` on CRAN (and any other registered other remotes) search locally in the `./renv/local/` directory **OR** `${RENV_PATHS_LOCAL}` (the latter of which I'm trying to avoid for maximum portability with colleagues).

This doesn't appear to be the case, however, as I'm finding I need to specify the exact path to the tarball, as in:
```R
renv::install("./renv/local/mypkg_0.0.0.9000.tar.gz")
```
(Similarly `renv::install("./renv/local/mypkg")` doesn't work, either.)

Is this behavior expected? Or should `renv::install` use the fallback search path (or the environment variable) and standard 'packagename-only' semantics?

EDIT: `renv` v0.12.0

**Comment by kevinushey** [comment]
The problem, I think, is that `renv::install("mypkg")` doesn't declare a package version, and so `renv` doesn't attempt to scan local sources for the package. This would likely work if you requested package installation with e.g.

```
renv::install("mypkg@0.0.0.9000")
```

That said, it may be sensible for `renv` to take the latest-available version of that package within local sources, assuming that version is newer than what is available on CRAN.

**Comment by mmuurr** [comment]
Ah, I didn't realize the package _version_ was required in that syntax.

> That said, it may be sensible for renv to take the latest-available version of that package within local sources, assuming that version is newer than what is available on CRAN.

My vote is for that ^, and in my particular use case the package _isn't_ available on CRAN. (I'm 'bundling', for lack of a better word, a few custom packages with a project.)

But in case you want to keep the behavior where the package version needs to be explicitly specified, I created PR #581. (And if you decide to change the behavior, you can just ignore that PR.)

**Comment by kevinushey** [comment]
This should now work as expected in the latest release of `renv` -- `renv::install("mypkg")` will select the latest-available version from local sources if one is available.

**Comment by mmuurr** [comment]
`w00t`, thanks!
