### ISSUE TITLE
renv 'time' caches incorrect package list

### ISSUE THREAD

**Issue by matthijsvanderloos** [rstudio/renv#579]
I am behind a corporate proxy through which I need to access the internet. To use `renv`, I set the `HTTP_PROXY` and `HTTPS_PROXY` env variables and this allows me to install packages correctly:

``` r
Sys.setenv("HTTP_PROXY" = "<proxy_server>", "HTTPS_PROXY" = "<proxy_server>")
renv::install("data.table")
#> Retrieving 'https://cran.rstudio.com/bin/windows/contrib/4.0/data.table_1.13.2.zip' ...
#>  OK [downloaded 2.5 Mb in 1.3 secs]
#> Installing data.table [1.13.2] ...
#>  OK [installed binary]
```

The following situation is, however, unexpected:

1. Install a package before setting the proxy server (this fails as expected).
2. Set the proxy env variables.
3. Install the package again, which fails (unexpected).

``` r
renv::install("data.table")
#> Warning: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib"
#> Warning: could not retrieve available packages for url "https://cran.rstudio.com/bin/windows/contrib/4.0"
#> Error: package 'data.table' is not available
Sys.setenv("HTTP_PROXY" = "<proxy_server>", "HTTPS_PROXY" = "<proxy_server>")
renv::install("data.table")
#> Error: package 'data.table' is not available
```

After some debugging I found that `renv` seems to inadvertently cache the result from the first call to `renv::install()`. I am using R 4.0.2 and `renv` 0.12.3.

Edit:
I think the following code allows to reproduce the issue when not behind a proxy:

``` r
Sys.setenv("HTTP_PROXY" = "<proxy_server>", "HTTPS_PROXY" = "<proxy_server>")
renv::install("data.table", rebuild = TRUE)
#> Warning: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib"
#> Warning: could not retrieve available packages for url "https://cran.rstudio.com/bin/windows/contrib/4.0"
#> Error: package 'data.table' is not available
Sys.unsetenv(c("HTTP_PROXY", "HTTPS_PROXY"))
renv::install("data.table", rebuild = TRUE)
#> Error: package 'data.table' is not available
```

**Comment by kevinushey** [comment]
This is because `renv` caches the result of `available.packages()`, even in the case where it fails (e.g. if you haven't configured your proxy settings as expected).

You can try using `renv::refresh()` to explicitly refresh the set of available packages after re-configuring the proxy settings.

**Comment by matthijsvanderloos** [comment]
Thanks, calling `renv::refresh()` after configuring the proxy indeed enables installing packages. I guess caching the result of `available.packages()` even when it fails is by design?

**Comment by kevinushey** [comment]
It is, although I'm not confident it is the right design :-)

The goal was to avoid stalling when attempting to query (or re-query) a package repository that might be inaccessible. The downside of that is, of course, that we don't properly account for other system changes that could effect whether we need to re-query.

The simple fix here, I think, would be to invalidate the cache if we detect that the `http_proxy` or `https_proxy` environment variables are changed.

**Comment by kevinushey** [comment]
Fixed now via https://github.com/rstudio/renv/commit/09fc6e308385f8dc345a346f01886304fab3369c.
