### ISSUE TITLE
renv::upgrade() inconsistency

### ISSUE THREAD

**Issue by bastienchassagnol** [rstudio/renv#580]
For a package project, we have used renv to store our libraries.

However, when we wanted to upgrade renv version (using renv::upgrade, with versions going from 0.12.0 to 0.12.3), we coped with multiple inconsistencies:
 - snapshot was not correctly performed, with a number of packages not kept
- we had to rerun by hand R project to have this new version of renv installed
- R_LIB_USERS has changed its value adding strange suffix to package name where libraries were stored by default. As a result,
.libPaths() and the value of R_LIB_USERS were not always the same
- version indicated by packageVersion("renv") was still 0.12.0, while renv::diagnostics indicate 0.12.3 ...

**Comment by kevinushey** [comment]
>snapshot was not correctly performed, with a number of packages not kept

Can you please be more specific?

> we had to rerun by hand R project to have this new version of renv installed

I don't understand what you mean here.

> R_LIB_USERS has changed its value adding strange suffix to package name where libraries were stored by default. As a result, .libPaths() and the value of R_LIB_USERS were not always the same

Again, can you please be more specific? What values of `.libPaths()` and `R_LIBS_USER` are you seeing?

> version indicated by packageVersion("renv") was still 0.12.0, while renv::diagnostics indicate 0.12.3 ...

`packageVersion()` reports the version of the package currently loaded, so it's possible that `renv 0.12.0` was loaded, you upgraded to `renv 0.12.3`, but did not restart the R session after doing so.

**Comment by kevinushey** [comment]
Closing until more information can be provided. (A reproducible example, in particular, would be most helpful.)
