### ISSUE TITLE
Package development with renv and build-time \Sexpr in documentation

### ISSUE THREAD

**Issue by brianrepko** [rstudio/renv#582]
I'll try to put together a reproducible example but stubbled on this issue last week on some code I'm working on.
The package-level Rd file was making use of \packageTitle, \packageDESCRIPTION etc macros that are basically build-time \Sexpr in the processed Rd.

When doing an R CMD build (via various entry points) - the build process sees the build-time \Sexpr and tries to install the package in order to complete the help pages. This package installation fails when it cannot find the Import: packages.

The solution was to create the package level Rd with Roxygen which avoids these macros and uses knitr or Sweave to do much of what a build-time \Sexpr would do. So this is VERY low priority. But potentially worth looking into. I'm not sure how to do this however as it involves a change to the code in R.

**Comment by hadley** [comment]
I think this is only triggered if the `\Sexpr` is used in a topic title so this is very unusual, and given that you have a work around, I don't think it's worth fixing in renv.

**Comment by brianrepko** [comment]
There have been so many other changes with `{renv}` that I'm not even sure this is broken - like you say - `{scales}` would have had it.
