### ISSUE TITLE
Possible to define compilation staging folder outside of the project

### ISSUE THREAD

**Issue by KyleHaynes** [rstudio/renv#584]
Hi @kevinushey,

Thanks for such a great package - our team is getting a lot of use from it!

Would it be possible to allow renv users to compile packages outside of the current defined location: `*\renv\staging\.*`?

**Why?**
Our IT are starting to roll-out CarbonBlack (security software that limits what staff can install) and they've whitelisted certain locations where packages can be installed / compiled. 

`renv` works fine with symbolic links to these whitelisted library folder locations, however, when setting up (restoring) a renv project, for packages that require compilation, this compilation occurs within the `project\renv\staging\.*` folder which isn't allowed.

I believe it's as simple as allowing the `root` path to be manually declared in the following function (in `install.R`):

```R
renv_install_staged_library <- function(library) {

  project <- renv_project(default = NULL)

  root <- if (is.null(project))
    file.path(library[[1]], ".renv")
  else
    file.path(project, "renv/staging")

  renv_install_staged_library_impl(root)

}
```

**Comment by kevinushey** [comment]
Thanks! I've made this change in the development version of `renv` -- you can now customize the path to the staged library via the `RENV_PATHS_LIBRARY_STAGING` environment variable.

In the interim, you can also disable `renv`'s staged installs by setting the option:

```
options(renv.config.install.transactional = FALSE)
```

See `?renv::config` for more details.
