### ISSUE TITLE
renv::status throws warning for reused knitr chunks

### ISSUE THREAD

**Issue by solarchemist** [rstudio/renv#586]
I recently introduced a knitr chunk with [reused chunks](https://yihui.org/knitr/demo/reference/) in my Rnw document, and noted that `renv::status()` throws a warning (that looks like an error). Apparently, renv does not consider reused chunks valid R code ;-)

Example:
```{r}
<<'chunk1', eval=FALSE>>
a <- 1+1
@

<<'chunk2'>>=
<<chunk1>>
a+1
@ 
```

Run `renv::status()`:
```{r}
> renv::status()
WARNING: One or more problems were discovered while enumerating dependencies.

/solarchemist/thesis/300-text.Rnw
----------------------------------------------------------

ERROR 1: <text>:6:1: unexpected input
6: <<
   ^

Please see `?renv::dependencies` for more information.
Do you want to proceed? [y/N]: 
```

There are at least a couple of ways for the user to proceed, in spite of this error-looking warning (it's just a warning):

+ simply choose `y` to proceed at the prompt, or
+ [add `renv.ignore=TRUE` to the chunk options](https://github.com/rstudio/renv/issues/421#issuecomment-689007228) of the chunk containing the reused chunks.

`renv` v0.11.0 on R 3.6.2, Ubuntu 18.04.5.

**Comment by kevinushey** [comment]
Thank you for the bug report! This should now be resolved in the development version of `renv`.

In the interim, you are indeed correct that using `renv.ignore` is the correct workaround.

**Comment by kevinushey** [comment]
I've also now documented the use of `renv.ignore` in `?renv::dependencies` to make this more obvious in future versions of `renv`.
