### ISSUE TITLE
GitLab refs with slash not working

### ISSUE THREAD

**Issue by dagola** [rstudio/renv#590]
# Problem
Trying to specify a Remote on a GitLab server with a slash in the `ref`, e.g. `gitlab@host::user/repo/@feature/foo` fails during  `renv::restore()`.

# Reason
The `ref` is not encoded using `URLencode` as `id` is:
https://github.com/rstudio/renv/blob/7fdff02b7148f850ae65e0fdda130594373b64b7/R/remotes.R#L382-L385

# Proposal
Add `ref <- URLencode(ref, reserved = TRUE)`.

**Comment by kevinushey** [comment]
Thanks! Should be fixed up in the latest development version of `renv` -- please feel free to re-open if you're still having any trouble.
