### ISSUE TITLE
renv and multi-package projects

### ISSUE THREAD

**Issue by brianrepko** [rstudio/renv#591]
We are using renv for a product that is made up of multiple packages - call them A and B.
The issue we are facing is that A depends on B.
We deploy released versions "x.y.z" to a WORK repository.
We use local sources when building development versions "x.y.z.9000".

For our workflow, we tried setting up A with a renv setting of ignored.packages = B thinking that we would manually manage the dependent package version. However this doesn't work since A's environment needs B's dependent packages. So we can't ignore B because that ignores all of B's dependencies.

The only way that I can think to make this work is for the renv of A to depend on a Local B.
But then I always have to build the local B even if I'm only working on A.

Also when I install from local sources
```
renv::install('B@1.0.0.9000')
```
that works but then when I snapshot it - it thinks that the repository is WORK.
And renv::upgrade does not see local sources as a later version of the WORK versions.

I really don't want to have to do a deploy of B in order to use it for A changes.

I'm at a loss for how best to make this work and looking for ideas...

**Comment by kevinushey** [comment]
> For our workflow, we tried setting up A with a renv setting of ignored.packages = B thinking that we would manually manage the dependent package version. However this doesn't work since A's environment needs B's dependent packages.

Can you elaborate a bit more? You have full control over what packages + what versions are installed into the project library; this option ultimately just effects what enters the lockfile.

> that works but then when I snapshot it - it thinks that the repository is WORK.

This is sort a kludge that `renv` does where, if it sees that a package of that name is available on one of the active package repositories, then it assumes copies of those packages installed from sources are available from those package repositories:

https://github.com/rstudio/renv/blob/080234134766804fb1dbbd777dff77dffff4b2e6/R/snapshot.R#L665-L671

Would it be accurate to say that what you want is to:

- Work with a development copy of B locally (1.0.0.9000), but
- Always record a "released" copy of B in the lockfile (1.00)

or am I misunderstanding?

The other option would be to explicitly load `B` from a separate library path, e.g.

```
library(B, lib.loc = <...>)
```

or even append that library path to the project library path used by the project.

**Comment by brianrepko** [comment]
Hi @kevinushey and thank you for the quick response.

> Can you elaborate a bit more? (on use of ignored.packages)

In this specific case, A depends on B and B depends on arsenal. So arsenal is in the renv.lock file for B and for A. If I set A to ignore B, then I get a message that arsenal is no longer used in A and would I like to remove it from A's renv.lock file.

This is why I don't think I can use ignore.packages=B in the A project setup - that then ignores B's dependencies.

**Related to Local vs Repository...**

I realize that I forgot to mention that there are multiple developers on this product (code under source code control). **_And_** we share a renv.lock file for the use of the product (basically the library needed for all these packages together). So there is a product renv.lock (for usage), an A renv.lock (for dev) and a B renv.lock (for dev).

We've done some work related to how to best do package development with renv (versus a non-package project with renv) and understand how renv can be used to vary the versions of dependencies (or dependencies of dependencies) for testing the package under development. We are now extending that to a product that includes multiple packages which depend on each other.

I think what would work is if renv could see that there is a later version in local and that I could upgrade B when working on A and that that would be treated as Local (dependencies that are developed as part of the product are Local). Since those versions are all later than the Repository version it should always take those from Local.

And then for the renv.lock that builds the library (the product renv.lock), we would change that to x.y.z based on the WORK repository and the releases of A and B. And when we release A and B we update the source to move to the next development version. Trying to following versioning based on the r-pkgs book.

**Comment by brianrepko** [comment]
I should add that when I build B, I then copy it to the global cache's local area.

**Comment by kevinushey** [comment]
> In this specific case, A depends on B and B depends on arsenal. So arsenal is in the renv.lock file for B and for A. If I set A to ignore B, then I get a message that arsenal is no longer used in A and would I like to remove it from A's renv.lock file.

For what it's worth, the simplest workaround for this is to simply insert `library(arsenal)` into one of your project's scripts; e.g. into a file called `deps.R`. That is, take an explicit dependency on the package but not through `B`.

> I think what would work is if renv could see that there is a later version in local and that I could upgrade B when working on A and that that would be treated as Local (dependencies that are developed as part of the product are Local). Since those versions are all later than the Repository version it should always take those from Local.

Just to be sure I understand correctly; are you hoping that `renv::install("B")` would see that the latest-available version of that package is available via local sources, and so choose to install that? (Similarly with `renv::update()`?)

**Comment by brianrepko** [comment]
Hi @kevinushey - that is correct - the latest version can be installed regardless of Local or Repository. What do you think? Or make that configurable? RENV_CONFIG_LOCAL_AS_REPO?

**Comment by kevinushey** [comment]
I've made a change in the development version of `renv` that should help make sure this "just works". Now, `renv::install("B")` will install a copy from local sources, if a version located there is found and is newer than whatever is available from the active package repositories.

**Comment by brianrepko** [comment]
thanks @kevinushey I'll try to test this in the new year
