### ISSUE TITLE
renv issues warning when used with R-devel

### ISSUE THREAD

**Issue by chunyunma** [rstudio/renv#592]
I installed the R-devel version (4.1) today on a Mac (Big Sur). 
When I initiated a project with `renv::init()` and restarted R, 
I received a warning:

```
Warning message:
could not retrieve available packages for url 'https://cloud.r-project.org/bin/macosx/contrib/4.1'
```

This warning message would disappear once I deactivate renv. 
I don't understand why this warning message persists 
even when I set `options(pkgType = "source")`.
I also tried a bit trouble shooting.
For example, I tried 
`Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "libcurl")`, 
which did not make any difference. 

BTW, `renv` continues to work properly when I switch back to the stable R release (4.0)

**Comment by kevinushey** [comment]
What version of `renv` are you using, and where are you setting `options(pkgType = "source")`? I was able to reproduce something similar when using a development version of `renv`, but want to see if that's congruent with what you're seeing.

**Comment by chunyunma** [comment]
Thank you for the quick reply @kevinushey !

```
packageVersion("renv")
# [1] ‘0.12.3.8’
```

And `options(pkgType = "source")` is set in `.Rprofile` inside the project folder.

**Comment by kevinushey** [comment]
One possibility -- does the issue go away if you set:

```
RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE
```

in your project `.Renviron`?

**Comment by chunyunma** [comment]
Yes, it did!!!
Very interesting. 
Based on the documentation, this setting 

```
Check that the project library is synchronized with the lockfile on load? Defaults to TRUE
```

By setting it FALSE, do I need to check manually from time to time?

Thanks again for the help!

**Comment by kevinushey** [comment]
Great, I'm glad to hear it!

This is ultimately a bug in `renv` that should be resolved in the latest development versions -- if you update to the latest version of `renv`, you should see the issue gone regardless of whether you use `RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE` or not.

Thanks again for reporting and taking the time to test!
