### ISSUE TITLE
renv::upgrade() modifies renv path location

### ISSUE THREAD

**Issue by bastienchassagnol** [rstudio/renv#593]
I use that issue to give you more precisions. I am on R server using R.3.6 code, and for my package project, I use renv to store my libraries. Unfortunately, when I use function upgrade (here from renv to 0.12.0 to 0.12.3), this changes the library location.

Here's my session info before upgrade, when everything works well:
![renv_before_error](https://user-images.githubusercontent.com/23634475/101700331-26ba5200-3a7d-11eb-865f-f3d6e31fdc6d.PNG)

And this is after upgrade, where renv articially changes location of my renv library:
![renv_after_error](https://user-images.githubusercontent.com/23634475/101700365-3174e700-3a7d-11eb-8470-31b9f4b494fa.PNG)
![renv_after_error_diagnostics](https://user-images.githubusercontent.com/23634475/101700815-fde68c80-3a7d-11eb-8d37-21712ec9e1a7.PNG)

I hope this will help you better diagnose the issue. This is quite disturbing, as changing path location implies at each upgrade requires to reload and reinstall all packages used in renv previous version.

**Comment by kevinushey** [comment]
Sorry for the trouble! I think this is fallout from the changes described to fix this issue:

https://github.com/rstudio/renv/issues/564

With `renv 0.12.3`, when `RENV_PATHS_LIBRARY_ROOT` is set, `renv` will append a short hash based on the project's path when constructing the library path. The intention here is to avoid issues where one might be working with multiple projects with identical names, but in different locations.

Is this change in behavior acceptable for you, or would you prefer the prior behavior?

**Comment by kevinushey** [comment]
From NEWS: https://github.com/rstudio/renv/blob/080234134766804fb1dbbd777dff77dffff4b2e6/NEWS.md#L51-L52

**Comment by bastienchassagnol** [comment]
Thanks for the update, I have to test it with my team project now, to check if your last commit works well (we effectively want to share the same library for all users). I will come back later in the day to you to check if everything works well, and potentially close the channel

**Comment by bastienchassagnol** [comment]
Adding this variable: RENV_PATHS_LIBRARY_ROOT_ASIS, enables to clearly remove alias, thank you very much.

**Comment by kevinushey** [comment]
Glad to hear that works, and sorry for the trouble!
