### ISSUE TITLE
Local packages or distinct Biocmanager repositories

### ISSUE THREAD

**Issue by bastienchassagnol** [rstudio/renv#594]
This issue is more like a set of questions for best practices of renv in use in a package:

- for the snapshot, what is the best option to use with parameter type, "explicit"? Especially, when i call install.packages on my local source package archive, will it use packages stored in renv.lock, or in the DESCRIPTIOn file?
- what is the best way in snapshot to refer to local packages, especially in context of building a local package dependant of another local package?
- with Biocmanager, I may need versions of packages compiling with my code that were stored in older versions of Biocmanager (to take a clear example, i am using biocmanager version 1.30.10 but I need version of GEOquery package present in version 1.30.8 of Biocmanager. How can I install this specific version (do I have to download the tar file and compile it locally), and how do I register it using snapshot (cf below picture)
![geoquery_snapshot](https://user-images.githubusercontent.com/23634475/101702368-01c7de00-3a81-11eb-9a73-80eee64c1f90.PNG)

**Comment by kevinushey** [comment]
> for the snapshot, what is the best option to use with parameter type, "explicit"? Especially, when i call install.packages on my local source package archive, will it use packages stored in renv.lock, or in the DESCRIPTIOn file?

This is discussed a bit in the [FAQ](https://rstudio.github.io/renv/articles/faq.html), but ultimately it's your choice: which packages do you want `renv` to capture in the lockfile, and how should `renv` capture those packages?

Calling `install.packages()` will work just as it did before -- it installs the latest-available version of the requested package(s) from the active R package repositories. If you want to use the packages declared in the lockfile, then you want to use `renv::restore()`.

> what is the best way in snapshot to refer to local packages, especially in context of building a local package dependant of another local package?

If your package is local, you should be able to just install it and snapshot it. You should be able to follow the documentation in [local sources](https://rstudio.github.io/renv/articles/local-sources.html) to ensure such packages can be restored.

> with Biocmanager, I may need versions of packages compiling with my code that were stored in older versions of Biocmanager (to take a clear example, i am using biocmanager version 1.30.10 but I need version of GEOquery package present in version 1.30.8 of Biocmanager. How can I install this specific version (do I have to download the tar file and compile it locally), and how do I register it using snapshot (cf below picture)

The simplest way to resolve this right now is to store this package archive as a local source, but I'll see if this is a use case that `renv` could feasibly support.
