### ISSUE TITLE
RMarkdown issue - `Error in !deps$Dev : invalid argument type`

### ISSUE THREAD

**Issue by slodge** [rstudio/renv#598]
I'm seeing a similar error to #382 and #401 with 0.12.3 for some RMarkdown code

My error and warnings are:
```
Error in !deps$Dev : invalid argument type
In addition: Warning messages:
1: In grepl("-display$", label) :
  argument "label" is missing, with no default
2: In grepl("-display$", label) :
  argument "label" is missing, with no default
3: In grepl("-display$", label) :
  argument "label" is missing, with no default
```

After some digging it seems like this was caused by line ... https://github.com/rstudio/renv/blob/471bf7e78fa8a32882e55c33fc049e336d1535e4/R/dependencies.R#L598

which was hitting some of our RMarkdown which had sections starting like:
```
{r  , echo=FALSE, warning=FALSE, message=FALSE}
```

I have fixed these locally to:

```
{r  echo=FALSE, warning=FALSE, message=FALSE}
```

But thought we might also want to write make renv defend against this.

**Comment by kevinushey** [comment]
Thanks for the bug report + reproducible example! Should be fixed up now in the development version of `renv`.

**Comment by slodge** [comment]
Thanks! It's good to have a genuine issue, instead of my normal "failure to
read the manual" :+1:
