### ISSUE TITLE
renv::restore throws errors when attempting to install specific versions of core packages

### ISSUE THREAD

**Issue by krumsieklab** [rstudio/renv#603]
```
> renv::restore()

[... package list removed...]

Do you want to proceed? [y/N]: y
Retrieving 'https://api.github.com/repos/rstudio/renv/tarball/e996b619471ea5174322e1287f94fcc3cf026010' ...
    OK [file is up to date]
Retrieving 'https://mran.microsoft.com/src/contrib/boot_1.3-25.tar.gz' ...
    OK [file is up to date]
Retrieving 'https://mran.microsoft.com/src/contrib/lattice_0.20-41.tar.gz' ...
    OK [file is up to date]
The following error(s) occurred while retrieving 'MASS':

    - character(0)

Error: failed to retrieve package 'MASS'
```
The error occasionally happens with the `foreign` package as well. 

Update operations for those two packages reported by `renv::restore` are:
```
- MASS [7.3-51.5 -> 7.3-51.6] 
- foreign [0.8-75 -> 0.8-76]
```

**Reproducible example:**

- Original project was built in MacOS, but I'm not sure that that matters.
- I'm running the test in a docker image: `docker run -d -p 8787:8787 -e PASSWORD=yourpasswordhere rocker/rstudio:3.6.3`
- In Rstudio (http://localhost:8787/), get this test repository: `system("git clone https://github.com/krumsieklab/renv_testing")`
- Open the project, run `renv::restore()`

**Comment by kevinushey** [comment]
Thanks for the bug report! A workaround would be to make sure that the `curl` binary is installed on your Docker image, but I'll get this fixed up in `renv`.

**Comment by kevinushey** [comment]
Should now be fixed in the development version of `renv` -- please upgrade to the latest version and let me know if all looks well.

**Comment by krumsieklab** [comment]
Works like a charm now, thanks for the fix!
