### ISSUE TITLE
warn if curl is not available?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#605]
Since `renv` relies on `curl` for custom headers, etc.

It's available almost everywhere nowadays (especially since new versions of Windows come with curl) but some users (notably, in Linux containers) might have not installed `curl`.

**Comment by hadley** [comment]
Were you thinking on load?

**Comment by kevinushey** [comment]
It looks like I added a bunch of stuff in https://github.com/rstudio/renv/commit/998c0438b8482492626aba843847a49af845a4a9, so this can probably be closed.
