### ISSUE TITLE
renv::activate() error because it writes a file

### ISSUE THREAD

**Issue by guma44** [rstudio/renv#607]
I am creating Docker image from a project that provides `renv.lock`. So when I create docker image I call:
```docker
RUN R -e "renv::restore()"
```

Then I convert this image to Singularity and do:

```
 renv::activate()
```

With this I get the error:
```
renv/R/load.R
Line 220 in 47579d9
 writeLines(enc2utf8(projlist), projects, useBytes = TRUE) 
):
Error in file(con, "w") : cannot open the connection
Calls: <Anonymous> ... renv_activate_impl -> load -> renv_load_project -> writeLines -> file
In addition: Warning message:
In file(con, "w") :
  cannot open file '/opt/app-root/lib/python3.6/site-packages/pisces/R/renv/projects': Read-only file system
Traceback (most recent calls last):
6: renv::activate()
5: renv_activate_impl(project = project, version = NULL, restart = FALSE, 
       quiet = FALSE)
4: load(project, quiet = quiet)
3: renv_load_project(project)
2: writeLines(enc2utf8(projlist), projects, useBytes = TRUE)
1: file(con, "w")
Execution halted
```

As Singularity is read-only file system. I could solve this problem by adding `renv::activate()` to Docker image but I would rather expect that activating renv would not modify anything in the system. Not sure what a good solution would be for this issue as the project loading is (probably) essential (I am not an R expert). But maybe project file should be written with `restore` function.

**Comment by kevinushey** [comment]
As a workaround, I wonder if you mean to call `renv::load()` instead of `renv::activate()`? `renv::activate()` is used to turn on the `renv` autoloader, which implies mutating some files within the project directory. `renv::load()` is used to explicitly activate a project.

**Comment by kevinushey** [comment]
This should be resolved in the latest development version of `renv`. (Sorry; the fix didn't make its way into the most recent CRAN release.)

**Comment by guma44** [comment]
Thanks!
