### ISSUE TITLE
Minor concern with `configure.vars` documentation

### ISSUE THREAD

**Issue by tub78** [rstudio/renv#609]
When I include `options(configure.vars = c(PKG_A = "something"))` in my .Rprofile, as described in https://rstudio.github.io/renv/reference/install.html , I obtain the traceback listed below during `renv::restore()`.  Note that, in the example in the docs, the configure option is specified as character vector.

However, when `renv` attempts to retrieve the `configure.vars` corresponding to *a different* package, a "subscript out of bounds" error is thrown.  This error goes away if I provide a list instead; e.g. `options(configure.vars = list(PKG_A = "something"))`. 

HTH,
-Stuart (renv@0.12.3)

```r
Installing BH [1.72.0-3] ...
	FAILED
Error in value[[package]] : subscript out of bounds
Traceback (most recent calls last):
12: renv::restore()
11: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
10: renv_install(records, library)
 9: renv_install_staged(records, library)
 8: renv_install_default(records, library)
 7: handler(package, renv_install_impl(record))
 6: renv_install_impl(record)
 5: withCallingHandlers(renv_install_package_local(record), error = function(e) {
        vwritef("\tFAILED")
        writef(e$output)
    })
 4: renv_install_package_local(record)
 3: renv_install_package_local_impl(package, path, library)
 2: r_cmd_install(package, path, library)
 1: r_cmd_install_option(package, "configure.vars", TRUE)
```

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be fixed up in the development version of `renv` now. For now, your workaround is indeed correct -- use a named list rather than a named character vector.
