### ISSUE TITLE
Unexpected inclusion of MASS package from base system

### ISSUE THREAD

**Issue by tub78** [rstudio/renv#610]
After converting a project to `renv` and verifying that the project library and scripts are working as expected, I have the following result from `renv::status()` that I do not understand: - It says that the MASS package is installed but not recorded in the lockfile.  

The MASS package is not installed in my project library, but instead exists pre-configured as a base / system library in `/Library/Frameworks/R.framework/Resources/library/`.  To the best of my knowledge, none of the libraries depend on MASS in any way.

Is this expected?  Should I add the MASS package to the list of ignored packages in the project settings?

Thanks!

```r
> renv::status()
The following package(s) are installed but not recorded in the lockfile:
       _
  MASS   [7.3-51.4]

Use `renv::snapshot()` to add these packages to your lockfile.

> renv::paths$cache()
[1] "<RENV-HOME>/cache/v5/R-3.6/x86_64-apple-darwin15.6.0"
> renv::paths$library()
[1] "<PROJECT_FOLDER>/renv/library/R-3.6/x86_64-apple-darwin15.6.0"
> renv::paths$root()
[1] "<RENV-HOME>"
> .libPaths()
[1] "<PROJECT_FOLDER>/renv/library/R-3.6/x86_64-apple-darwin15.6.0"
[2] "/private/var/folders/s2/fw4yx0qx35nb3mrls_fkqtbh0000gr/T/RtmpESwbyM/renv-system-library"                                 


> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6.1/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    renv_0.12.3   
```

**Comment by kevinushey** [comment]
Any chance you can provide a reproducible example?

**Comment by tub78** [comment]
Ok, it took some time ... but here is a minimal example.  The final output log confirming the mis-inferred MASS package is below.  The file: "_pkgdown.yml" seems to be the culprit. 

Is this behavior normal?   Why would the YML file cause this?

Otherwise, really enjoying `renv` - Thanks!

```bash
  rm -rf kushy_example
  mkdir kushy_example
  cd kushy_example
  ARCHVER="$(R --slave --vanilla -e 'cat(file.path(paste("R", numeric_version(paste(R.version$major, R.version$minor, sep = "."))[1, 1:2], sep = "-"), R.version$platform))')"
  mkdir -p "renv/library/$ARCHVER"
  export R_LIBS="renv/library/$ARCHVER"
  echo "destination: docs" >| _pkgdown.yml
  R -e 'install.packages("renv", type = "binary", repos = "https://ftp.osuosl.org/pub/cran/")'
  R -e 'renv::init()'
  R -e 'renv::status()'
```

OUTPUT LOG: 

```r
--------------------- snip ----------------
> renv::status()
* This project has not yet been snapshotted -- 'renv.lock' does not exist.
The following package(s) are installed but not recorded in the lockfile:
       _
  MASS   [7.3-51.4]
  renv   [0.12.5]

Use `renv::snapshot()` to add these packages to your lockfile.
```

**Comment by kevinushey** [comment]
Thanks for the bug report -- unfortunately, even with that script I'm still not able to reproduce.

You could check the output of:

```
deps <- renv::dependencies()
pkgs <- sort(unique(deps$Package))
all <- unlist(tools::package_dependencies(pkgs, recursive = TRUE))
```

Presumedly, `MASS` is mentioned in that list?

Finally, the output of `renv::diagnostics()` may be useful as well.

**Comment by tub78** [comment]
Strange - I do not see MASS listed in the list of recursive dependencies.

Beyond tracing the issue to the `pkgdown` dependency, I am unable to explain the unexpected inclusion of the MASS package by `renv`.  Interestingly, in the results of `renv::diagnostics()`, MASS is characterized as an "<indirect>" library dependency, whereas the remaining system / core libraries say "<NA>".

Please see my gist showing the output in three scenarios of the diagnostic commands you provided:
1. directly after creating the `kushy_example` using the reproducible example script from above
2. after explicitly ignoring `_pkgdown.yml` via `.renvignore`
3. after explicitly forcing the `pkgdown` dependency with a `library(pkgdown)` statement

https://gist.github.com/tub78/80e0fdb9e12a7b31d3b92dacbaa975d6

For what it's worth, I found evidence that this issue may have occurred for others as well (see https://github.com/rstudio/renv/issues/507#issuecomment-675595631) which includes the following comment:

> # Edit renv.lock to include RSPM snapshot and remove bogus installation of MASS (!?!)

As a work-around, I am comfortable with the `.renvignore` solution for now.  

Thanks HTH
-S.
