### ISSUE TITLE
Cannot update packages since 0.12.4

### ISSUE THREAD

**Issue by razz-matazz** [rstudio/renv#611]
Since upgrading from 0.12.3 to 0.12.4 I cannot update any package anymore.

This is the message I get:
```
cannot open file 'C:/Users/(my_username)/AppData/Local/Temp/RtmpE7ZYHG/renv-staging-23342055054/httpuv': Die im Analysepunktpuffer vorhandenen Daten sind ungültig
```

Last sentence is german. Its translation is: ```The data in the reparse (or analysis) point buffer is invalid```

Returning to 0.12.3 everything is working again.

Maybe I am wrong, but didn't Renv staged to the current project folder before?

R-Version 4.0.2
Windows

**Comment by kevinushey** [comment]
That's correct. From the NEWS file:

> renv now uses the R temporary directory for staging, when performing transactional restores / installs. If you need to control the path used for staged installs, please set the RENV_PATHS_LIBRARY_STAGING environment variable.

This change was made because project folders are often backed up automagically via e.g. Dropbox or OneDrive, and having a staging folder in the project directory led to issues.

The alternate solution is to disable staged installs, as documented in `?renv::config`.

**Comment by kevinushey** [comment]
Were you able to successfully work around this via the `RENV_PATHS_LIBRARY_STAGING` environment variable?

**Comment by razz-matazz** [comment]
Thanks,
 
I have now sucessfully tried both options and will use RENV_PATHS_LIBRARY_STAGING.

**Comment by kevinushey** [comment]
Thanks; I'm glad to hear it! Sorry for the trouble but glad to hear things are working now.

**Comment by razz-matazz** [comment]
Hello,

I do not know if this is directly connected with this, but since then I sometimes cannot update or install. I get this stack trace:

```
Error 'sass' is not a legal package name
Error: install of package 'sass' failed
Traceback (most recent calls last):
13: install.packages("sass")
12: install(pkgs)
11: renv_install(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_impl(record))
 7: renv_install_impl(record)
 6: withCallingHandlers(renv_install_package_local(record), error = function(e) {
        vwritef("\tFAILED")
        writef(e$output)
    })
 5: renv_install_package_local(record)
 4: renv_install_package_local_impl(package, path)
 3: r_cmd_install(package, path)
 2: r_exec_error(package, output, "install")
 1: stop(error)
```

**Comment by kevinushey** [comment]
What version of R are you using?

**Comment by razz-matazz** [comment]
R> sessionInfo()
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] magrittr_2.0.1 IQS_0.1.0     

loaded via a namespace (and not attached):
 [1] zip_2.1.1           Rcpp_1.0.6          compiler_4.0.2     
 [4] pillar_1.4.7        BiocManager_1.30.10 R.methodsS3_1.8.1  
 [7] R.utils_2.10.1      tools_4.0.2         scriptName_1.0.1   
[10] lifecycle_0.2.0     tibble_3.0.5        pkgconfig_2.0.3    
[13] rlang_0.4.10        openxlsx_4.2.3      DBI_1.1.1          
[16] rstudioapi_0.13     parallel_4.0.2      xfun_0.20          
[19] rJava_0.9-13        dplyr_1.0.3         stringr_1.4.0      
[22] xlsxjars_0.6.1      generics_0.1.0      vctrs_0.3.6        
[25] rprojroot_2.0.2     tidyselect_1.1.0    glue_1.4.2         
[28] here_1.0.1          R6_2.5.0            pacman_0.5.1       
[31] purrr_0.3.4         logger_0.2.0        ellipsis_0.3.1     
[34] assertthat_0.2.1    renv_0.12.5         xlsx_0.6.5         
[37] tinytex_0.29        stringi_1.5.3       crayon_1.3.4       
[40] R.oo_1.24.0 
```

**Comment by kevinushey** [comment]
Do you also see this with the development version of `renv`? Can you share any other information about how you're using `renv`?

What you're reporting sounds like an R bug that should've been fixed since a while ago.

**Comment by razz-matazz** [comment]
I've now installed latest dev version of renv and it is still happening. 

We are using renv in our projects with a shared network drive (PATH.R.SOURCES.EXT):

Sys.setenv(RENV_PATHS_ROOT = PATH.R.SOURCES.EXT)
Sys.setenv(RENV_PATHS_CACHE = PATH.R.SOURCES.EXT)
Sys.setenv(RENV_PATHS_LIBRARY = PATH.R.SOURCES.EXT)
Sys.setenv(RENV_PATHS_LIBRARY_STAGING = paste0(PATH.R.SOURCES.EXT, "stage/"))

**Comment by kevinushey** [comment]
```
Sys.setenv(RENV_PATHS_ROOT = PATH.R.SOURCES.EXT)
Sys.setenv(RENV_PATHS_CACHE = PATH.R.SOURCES.EXT)
Sys.setenv(RENV_PATHS_LIBRARY = PATH.R.SOURCES.EXT)
Sys.setenv(RENV_PATHS_LIBRARY_STAGING = paste0(PATH.R.SOURCES.EXT, "stage/"))
```

If you're setting `RENV_PATHS_ROOT`, you don't need to set `RENV_PATHS_CACHE` or `RENV_PATHS_LIBRARY` -- the cache + library paths will be resolved to independent sub-folders of the root folder.

**Comment by kevinushey** [comment]
I'd also be curious to know if the issue persists if you disable staged installed; e.g. what happens if you run:

```
options(renv.config.install.staged = FALSE)
renv::install("httpuv")
```

**Comment by razz-matazz** [comment]
With ```options(renv.config.install.staged = FALSE)``` I don't run into those problems.

**Comment by kevinushey** [comment]
Thanks for reporting back. If that's the case, I'd recommend setting that as the default for your projects; the simplest way would be by setting:

```
RENV_CONFIG_INSTALL_STAGED = FALSE
```

in an appropriate `.Renviron` file. See `?Startup` in R for more details.
