### ISSUE TITLE
restore() ignores library argument?

### ISSUE THREAD

**Issue by glin** [rstudio/renv#612]
Hi, I've found that in renv 0.12.5, the `library` argument in `renv::restore()` works differently than it did in renv 0.12.3. Before, a `restore()` would've always restored packages into the `library` directory if specified. But now, renv seems to ignore the `library` directory in certain cases.

I'm not sure if this is a bug or if it's intended, but I didn't see anything in the changelog about it.

Here's a minimal example to demo this:

```r
# Create a minimal lockfile with just renv in the snapshot
proj_dir <- file.path(tempdir(), "project")
dir.create(proj_dir)
renv::snapshot(project = proj_dir, prompt = FALSE)

# Restore the lockfile into an empty package library
temp_lib <- file.path(tempdir(), "lib")
dir.create(temp_lib)
renv::restore(project = proj_dir, library = temp_lib, prompt = FALSE)

# The renv package should have been restored into the package library
library(renv, lib.loc = temp_lib)
```

In renv 0.12.3, this is what I get. The renv package is snapshotted and restored into the specified package library:
```r
> proj_dir <- file.path(tempdir(), "project")
> dir.create(proj_dir)
> renv::snapshot(project = proj_dir, prompt = FALSE)
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- renv   [* -> 0.12.3]

* Lockfile written to '/tmp/RtmpYMfHi0/project/renv.lock'.

> temp_lib <- file.path(tempdir(), "lib")
> dir.create(temp_lib)
> renv::restore(project = proj_dir, library = temp_lib, prompt = FALSE)
The following package(s) will be updated:

# CRAN ===============================
- renv   [* -> 0.12.3]

Installing renv [0.12.3] ...
	OK [copied local binary]
Copying renv [0.12.3] into the cache ...
	OK [copied 61 files in 0.01 seconds]
The dependency tree was repaired during package installation:
       _
  renv   [0.12.3]

Call `renv::snapshot()` to capture these dependencies in the lockfile.

> library(renv, lib.loc = temp_lib)
```

However in renv 0.12.5, the restore doesn't do anything. It's like the `library` argument was ignored, and my default libraries were used anyway:
```r
> proj_dir <- file.path(tempdir(), "project")
> dir.create(proj_dir)
> renv::snapshot(project = proj_dir, prompt = FALSE)
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- renv   [* -> 0.12.5]

* Lockfile written to '/tmp/RtmpSx9Osb/project/renv.lock'.

> temp_lib <- file.path(tempdir(), "lib")
> dir.create(temp_lib)
> renv::restore(project = proj_dir, library = temp_lib, prompt = FALSE)
* The library is already synchronized with the lockfile.

> library(renv, lib.loc = temp_lib)
Error in library(renv, lib.loc = temp_lib) : 
  there is no package called ‘renv’
```

**Comment by kevinushey** [comment]
Thanks for the bug report! This is unintentional, and is caused because `renv` is prepending the requested library path to the current library paths, rather than using that library path exclusively. I'll take a look.

**Comment by kevinushey** [comment]
Should be fixed by https://github.com/rstudio/renv/commit/92b1dda9354e10327d15695eea45c9dc81360fa3 -- thanks for reporting.

As a workaround, I believe something like the following should work without issue:

```
.libPaths(temp_lib)
renv::restore(project = proj_dir, prompt = FALSE)
```

in case you're not able to update to the development version.

**Comment by glin** [comment]
Can confirm it's fixed in the dev version, and I'll use that workaround for now. Thanks!

**Comment by kevinushey** [comment]
Awesome! Thanks again for the bug report and sorry for the trouble.
