### ISSUE TITLE
Avoid using junctions in the temporary directory

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#614]
On Windows, the base library is mirrored in the temporary directory using junctions ("sandbox" in the code), in `file.path(tempdir(), "renv-system-library")`. This creates a problem in the following situation:

- The user works in RStudio
- They reboot their machine while RStudio is open
- A service (configured or third-party) purges `%TEMP%\` and incorrectly deletes the contained junctions recursively before reboot.

After reboot, the user finds a base library full with empty directories where the base packages should be, yielding a non-usable R installation. (Sorry, no reprex :upside_down_face:.)

Can we generate the sandbox in a subdirectory of `./renv/` to work around this problem?

CC @pat-s.

**Comment by kevinushey** [comment]
> After reboot, the user finds a base library full with empty directories where the base packages should be, yielding a non-usable R installation.

😭 

One way forward would be to disable the sandbox entirely, via:

```
options(renv.config.sandbox.enabled = FALSE)
```

But I'll look at making the path configurable here as well.

**Comment by kevinushey** [comment]
I wonder if this is the root cause of some issues others have seen; e.g. https://github.com/rstudio/renv/issues/835?

**Comment by kevinushey** [comment]
The challenging part here is figuring out how to disambiguate the sandbox path between multiple different sessions; e.g. imagine that you have R 4.1.2 from Homebrew and R 4.1.2 from CRAN running at the same time in the project:

1. How should the sandbox path be created in each case?
2. How should the sandbox path be cleaned up?

We also want to make sure the symlinks / junction points live on the same drive as the R installation; for users working on a network drive, it's quite possible that their project sources live on a different drive than their R installation.

Putting everything into the R session's temporary directory makes it a lot easier to answer those questions.

**Comment by kevinushey** [comment]
I've decided to take the simple way out and disable the sandbox by default (https://github.com/rstudio/renv/commit/56bdb37c3bd5221ec7e4fd48e5998319bd6eab5c). It seems the potential downsides outweigh the benefits. We can revisit this in the future if we can think of a better + safer way to create + use + manage the sandbox.
