### ISSUE TITLE
FR: progress bar for `restore()`

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#620]
In some projects we recently faced the situation that `restore()` might take a while due to the amount of packages to be restored.

Even when using RSPM, this can take a while.

Currently the following output is shown in the console

```
	OK [downloaded 43.9 Kb in 1.2 secs]
Retrieving 'https://packagemanager.rstudio.com/cran/__linux__/bionic/301/src/contrib/brew_1.0-6.tar.gz' ...
```

with differences depending on the availability of the binary, availability in the cache and so on.

While this is great, I was wondering if there could be a user option to display a progress bar instead of this output.
With the current output, the user has no idea how long the restore might take and at which point the process is.
After some usage of {renv} and getting experiend in how it works, this progress bar might bring more value than the current download/install log.

Maybe an option `renv_settings_progress` which could be set to `"bar"` or `"text"` by the user.

When it comes to progressbar packages, you might know Henriks [progressr](https://github.com/HenrikBengtsson/progressr) package already.

**Comment by warnes** [comment]
Alternatively, simply adding "(X of Y)" to the "Installing" status message would help a lot.  I.e.:
```
Installing sp [1.6-0] (85 of 114) ...
        OK [built from source]
Moving sp [1.6-0] into the cache ...
        OK [moved to cache in 6.3 milliseconds]
Installing raster [3.6-14] (86 of 114) ...
```

**Comment by hadley** [comment]
I think unfortunately that this isn't possible because we don't know how many packages we are going to download, until we start downloading them. For example, when you do `renv::install("r-lib/dplyr")` we don't know how which packages need to be downloaded until we've downloaded and parsed dplyr's `DESCRIPTION`. (And if dplyr has a development dependency we need to wait until that `DESCRIPTION` is downloaded and parsed).

**Comment by kevinushey** [comment]
In addition, we're actively working on using `pak` by default for package installation, so eventually concerns of this form will be delegated to `pak`.
