### ISSUE TITLE
renv v0.12.4+ fails to create links on windows

### ISSUE THREAD

**Issue by aprilrathe** [rstudio/renv#621]
When I upgrade renv to v0.12.4 or v0.12.5, `renv::restore()`on Windows 10 stops creating links. Instead packages are copied into the project folder every time restore is run. I tried explicitly setting the configurations RENV_CONFIG_CACHE_SYMLINKS=TRUE and `renv::settings$use.cache(TRUE)`. The packages are still copied.

The output message to the console per package says
`Installing xlsx [0.6.5] ...
         OK [linked cache]
`
And all package message print out quickly, then the command line waits. If you look at the file system, files are being copied from the cache into the project folder. 

When I downgrade to 0.12.3 the links are created again. 

`renv::diagnostics()`
```
# Settings ===================
List of 7
$ external.libraries : chr(0)
$ ignored.packages : chr(0)
$ package.dependency.fields : chr [1:3] "Imports" "Depends" "LinkingTo"
$ r.version : chr(0)
$ snapshot.type  : chr "implicit"
$ use.cache   : logi TRUE
$ vcs.ignore.library  : logi TRUE

# Environment Variables =========
HOME  = H:
LANG   = <NA>
R_LIBS  = <NA>
R_LIBS_SITE = <NA>
R_LIBS_USER  = F:/projects/project1/renv/library/R-4.0/x86_64-w64-mingw32
R_CONFIG_CACHE_SYMLINKS   =  TRUE
RENV_DEFAULT_R_ENVIRON   = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS  = <NA>
RENV_DEFAULT_R_LIBS_SITE   = <NA>
RENV_DEFAULT_R_LIBS_USER = H:/R/win-library/4.0
RENV_DEFAULT_R_PROFILE = H:/Rprofile.site
RENV_DEFAULT_R_PROFILE_USER   = <NA>
RENV_PROJECT  = F:/projects/project1
```

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, I wasn't able to reproduce on my Windows VM. Some things worth testing:

Does disabling transactional installs help? What if you set `options(renv.config.install.transactional = FALSE)` prior to install?

Can you try running:

```
trace(renv:::renv_file_link, quote(print(ls.str())))
```

to see what the paths are when `renv` attempts to create the junctions?

I suspect this is related to https://github.com/rstudio/renv/issues/584.

**Comment by aprilrathe** [comment]
Hi Kevin. Thanks for the suggestion. Disabling transactions by setting `options(renv.config.install.transactional = FALSE)` prior to `renv::restore()` fixes the problem and the junctions are created. I repeated this several times with 0.12.5 (changing the setting) and was able to replicate both the issue and the fix.

**Comment by kevinushey** [comment]
Awesome -- thanks for verifying! I'll try to fix the underlying cause of the issue here so that links work without requiring this option set.

**Comment by kevinushey** [comment]
This should now hopefully be fixed in the development version of `renv`.
