### ISSUE TITLE
"deploying" an environment to a cluster

### ISSUE THREAD

**Issue by myoung3** [rstudio/renv#623]
Thanks for the excellent work on this package. 

I'm working with somewhat of a unique situation: I start a script on a server that involves data processing. This script is in a project that uses renv for package versioning. Later in that script, I send some files (that result from the data processing) to a cluster along with a signal to run some code on that cluster.  I'd like the package versions loaded on the cluster to be the same versions that the renv lockfile specifies. I'd prefer not to have the same git repo both on the local server and the remote cluster because that involves ensuring that the repos are always in sync.

So is there any way to "deploy" a lockfile to a new directory (such that that in that new directory a local library is created and all the specified package versions are installed/hopefully copied from a local library) without having to copy the entire project directory from the local server to the cluster? I guess I'm asking is: what is the cleanest way to initialize a new project (and install packages) from just an existing lockfile?

**Comment by hadley** [comment]
Call `renv::restore()`?
