### ISSUE TITLE
Improper MRAN Mac binary URL constructed

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#627]
I found myself in the state where `brew` changes forced a reinstall of `RcppRoll` 0.3.0 and building from source was failing (g++-9 issues).

In any case, I wanted to have `renv` reinstall from binary, so I ran the following, which generated an invalid URL (renv 0.12.5 / latest). As you can see, fixing the URL manually (removing the duplicated `.tgz`) was a fine workaround in this case

```
> renv::install("RcppRoll", type = "binary", rebuild = TRUE)
Retrieving 'https://mran.microsoft.com/snapshot/2020-04-24/bin/macosx/el-capitan/contrib/3.6/RcppRoll_0.3.0.tgz/RcppRoll_0.3.0.tgz' ...
* There are no packages to install.
Warning message:
curl: (22) The requested URL returned error: 404 Not Found 
> renv::install("https://mran.microsoft.com/snapshot/2020-04-24/bin/macosx/el-capitan/contrib/3.6/RcppRoll_0.3.0.tgz", type = "binary", rebuild = TRUE)
Installing RcppRoll [0.3.0] ...
	OK [installed binary]
```

**Comment by kevinushey** [comment]
What version of R?

**Comment by kevinushey** [comment]
Also not clear why we'd be using MRAN here given that there should be a current binary available on CRAN anyway...

**Comment by kevinushey** [comment]
Reproducible example:

```
options(repos = character())
renv::install("RcppRoll", type = "binary", rebuild = TRUE)
```

**Comment by colearendt** [comment]
Interesting! I'm surprised that repo was unset 😮 In any case, the version of R was 3.6

**Comment by colearendt** [comment]
Ahah! RSPM causes the issue, so probably keying off of `CRAN`. Would love to have this as a test case too!
```
options("repos" = c(RSPM = "https://packagemanager.rstudio.com/cran/latest"))
renv::install("RcppRoll", type = "binary", rebuild = TRUE)
```

**Comment by kevinushey** [comment]
Should be fixed now on master -- thanks for reporting!
