### ISSUE TITLE
Feature request: Multiple cache directories

### ISSUE THREAD

**Issue by vandenman** [rstudio/renv#628]
Would it be possible to support multiple cache directories?

For example, `Sys.setenv("RENV_PATHS_CACHE" = "~/.local/share/renv/cache1;~/.local/share/renv/cache2")`, could indicate that both `~/.local/share/renv/cache1` and `~/.local/share/renv/cache2` are directories where renv looks for cached packages. When adding a new package to the cache, renv would use the first writeable path.

My use case is the following: our software consists of multiple modules (basically R packages with a user interface). Each of these modules has its own dependencies, and we supply a default set of R packages through an installer. Right now, we are making these modules more modular so that we can update them independently. During an update, the package dependencies may change. To efficiently reuse available packages, I'd like to use renv with its excellent caching feature.
Now here's the problem. The R packages shipped by default end up in the installation folder of a user. We do not have write access there after installing (at least on macOS and on Linux with flatpak). In our own local folder (inside Appdata, ~/.local/share, etc.) we do have write access. My goal is to create a second cache directory in our local folder. That way, we can 1) efficiently reuse the R packages in the installation folder and 2) reuse R packages installed while updating modules.

The changes required to make this work are rather minimal, at least in the small example that I tested locally. I'd be more than happy to open a PR if you think this could be useful.

**Comment by kevinushey** [comment]
I'd be willing to review a PR but my gut instinct is that there's a fair amount of code internally in `renv` that assumes there is a single cache path and so getting this to work may be challenging. (but I'd be happy to be proven wrong!)

**Comment by kevinushey** [comment]
Also worth saying up-front: we require a [Contributor License Agreement](https://www.rstudio.com/wp-content/uploads/2014/06/RStudioIndividualContributorAgreement.pdf) before we can accept pull requests on RStudio repositories.
