### ISSUE TITLE
Error in renv::init() when there are accents in the path

### ISSUE THREAD

**Issue by DanChaltiel** [rstudio/renv#629]
I experience the exact same messages as https://github.com/rstudio/renv/issues/527.

However, I found out that in my case this was due to accents (mostly "é") in the path of my project.

I cannot give you a true reproducible example but I could reproduce this bug with this minimal procedure:

- In some test directory (without an accent in the path), create 2 plain old projects using `RStudio > File > New Project > New directory > New Project`
   - name one `without accent`
   - name the other `with accént`
- In both, activate renv using `Tools > Project Options > Environments > Use renv with this project`. This will run `renv::activate()` in the console without issue.
- In both, run renv::init() with choice `2`
   - No problem in the project `without accent`
   - Same error than #527 in the project `with accént`

I also tried with choice `1`, it throws several errors of connection and a warning but finally outputs a sucess message. 

Here is the full console log:

<details>
  <summary>console log</summary>
  
```r
renv::activate()
* Project 'F:/Nextcloud GR/Programmation/test renv/avéc accent' loaded. [renv 0.12.5]
> Sys.setenv(LANG = "en")
> 
> renv::init()
This project already has a private library. What would you like to do? 

1: Activate the project and use the existing library.
2: Re-initialize the project with a new library.
3: Abort project initialization.

Selection: 2
* Initializing project ...
Error in normalizePath(path, winslash = winslash, mustWork = mustWork) : 
  file name conversion problem -- name too long?
> renv::init()
This project already has a private library. What would you like to do? 

1: Activate the project and use the existing library.
2: Re-initialize the project with a new library.
3: Abort project initialization.

Selection: 1

Restarting R session...

Error in gzfile(file, "wb") : cannot open the connection
Error saving session (options): R code execution error
Error in file(file, "wb") : cannot open the connection
Error saving session (search_path): R code execution error
WARNING: Forcing suspend of process in spite of all session data not being fully saved.
# Bootstrapping renv 0.12.5 --------------------------------------------------
* Downloading renv 0.12.5 from CRAN ... OK
* Installing renv 0.12.5 ... Done!
* Successfully installed and loaded renv 0.12.5.
* Project 'F:/Nextcloud GR/Programmation/test renv/avéc accent' loaded. [renv 0.12.5]
> renv::init()
This project already has a private library. What would you like to do? 

1: Activate the project and use the existing library.
2: Re-initialize the project with a new library.
3: Abort project initialization.

Selection: 
Enter an item from the menu, or 0 to exit
Selection: 2
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- renv   [* -> 0.12.5]

* Lockfile written to 'F:/Nextcloud GR/Programmation/test renv/avéc accent/renv.lock'.

Restarting R session...

Error in gzfile(file, "wb") : impossible d'ouvrir la connexion
Error saving session (options): R code execution error
Error in file(file, "wb") : impossible d'ouvrir la connexion
Error saving session (search_path): R code execution error
WARNING: Forcing suspend of process in spite of all session data not being fully saved.
* Project 'F:/Nextcloud GR/Programmation/test renv/avéc accent' loaded. [renv 0.12.5]
```

</details>

**Comment by kevinushey** [comment]
Thanks for the bug report. This is unfortunately a bug in R -- for example:

```
> path <- file.path(tempdir(), "你好")
> file.create(path)
[1] TRUE
> 
> short <- utils::shortPathName(path)
> normalizePath(short)
[1] "C:\\tmp\\RtmpgjcFLp\\??"
```

and `renv` does something similar when normalizing paths... *sigh*

I'll see if we can work around this somehow.

**Comment by kevinushey** [comment]
I think this should now be better handled in the development version of `renv` -- could you try installing it with:

```
renv::install("rstudio/renv")
```

and let me know how things look?

**Comment by DanChaltiel** [comment]
Thanks for the quick fix!

Unfortunately, I ran the command, restarted RStudio, and redid what I've written above, the error remains the exact same.

`renv` version didn't change though, maybe I did it wrong.

Let me know if I should try again anytime or if you need more info.

<details>
  <summary>sessionInfo()</summary>
  
```r
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3    renv_0.12.5   
```
</details>

**Comment by kevinushey** [comment]
```
Error in gzfile(file, "wb") : impossible d'ouvrir la connexion
Error saving session (options): R code execution error
Error in file(file, "wb") : impossible d'ouvrir la connexion
Error saving session (search_path): R code execution error
WARNING: Forcing suspend of process in spite of all session data not being fully saved.
```

I _think_ this is RStudio-related and independent of `renv`...

**Comment by DanChaltiel** [comment]
With the version I installed 2 days ago, if I check "use renv with this project" when creating a new project with an accent in the path, `renv` will duplicate the path with the wrong charset. For instance, if I create a project in `C://foo/baré/rénv`, it will duplicate the project skeleton in `C://foo/barÃ©/rÃ©nv`.
I don't know if it is due to recent changes or if it is older.

However, after updating to github's last version, I get that `normalizePath` error again, and now even befor I get the chance to choose any option:

```r
> renv::init()
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
The following package(s) will be updated in the lockfile:

# GitHub =============================
- renv   [* -> rstudio/renv@HEAD]

* Lockfile written to 'F:/Nextcloud GR/Programmation/test rénv/tést check/renv.lock'.
Error in normalizePath(short, winslash, mustWork) : 
  problème de conversion de nom de fichier -- nom trop long ?
```

**Comment by kevinushey** [comment]
Thanks again for reporting back -- it looks like this is enough Windows oddity where this:

```
normalizePath(shortPathName(path))
```

can fail occasionally for 'latin1' encoded paths. Hopefully the development version of `renv` should handle this better...

**Comment by kevinushey** [comment]
I think this should be properly handled with `renv 0.14.0` -- please feel free to re-open if you're still having trouble.
