### ISSUE TITLE
Option to disable dependency search in `init()`

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#63]
I think the option to disable the scraping of dependencies in `packrat` is really useful and should make its way over to `renv::init()`.

For new projects, the point is moot. But when you have been working on something a little while, and are ready to make it transportable, I like the workflow of:

1. Init empty project-local library and restart R session
2. Manually install what I think my dependencies are into my project-local library
3. Run project and see what breaks
4. Fix broken things by either changing code or installing additional libraries
5. Snapshot

It's a nice opportunity to catch things that might have slipped through the net like stray usage of `::`. Nearly every time I've used the automated scraping I've picked up stuff by accident. I just now watched a colleague do the same thing playing around with `renv`, so I know it's not just me :).

To save the user some labor, you could have a function that returns a character vector of all the detected dependencies. They can then evaluate that and choose whether to install them all.

**Comment by mstr3336** [comment]
I think that that function exists @MilesMcBain , see [renv::dependencies()](https://rstudio.github.io/renv/reference/dependencies.html) . 

This returns a `data.frame` of all of the detected dependencies, with a little metadata re. these deps, and the user can pipe this like so (or follow whatever process they desire).

 ```
renv::dependencies() %>%
    dplyr::filter(! package %in% vector_of_ignored_pkgs) %>%
    dplyr::pull("package") %>%
    install.packages()
```

**Comment by mstr3336** [comment]
I guess what you're asking for is to be able to use that function i mentioned, but optionally from calling `renv::init()`, though.

**Comment by kevinushey** [comment]
You can also try using `renv::activate()` to activate an `renv` project without performing the other usual `init()` steps. This effectively just creates and activates the project, giving you an empty project library if the project has not yet been activated before. Is that sufficient in your case?

**Comment by MilesMcBain** [comment]
Yep that's great, thanks!
