### ISSUE TITLE
Problem with renv and data packages

### ISSUE THREAD

**Issue by birnbera** [rstudio/renv#631]
I'm running into some confusing issues trying to install data packages in an `renv` environment. In particular, I am trying to include `BSgenome.Hsapiens.UCSC.hg38` and `org.Hs.eg.db` in the environment. I am able to install them using `renv::install("bioc::BSgenome.Hsapiens.UCSC.hg38")`, but when I snapshot they aren't included in the lock file. I forced their inclusion using `renv::snapshot(packages=c("BSgenome.Hsapiens.UCSC.hg38", "org.Hs.eg.db"))`, but the records don't look normal, e.g.:
```json
"BSgenome.Hsapiens.UCSC.hg38": {
      "Package": "BSgenome.Hsapiens.UCSC.hg38",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "bioc"
}
```
As you can see, they are missing a hash and the repository isn't correct. Even correcting the lock file using the hashes from the cache and changing the Repository field to "Bioconductor" (matching the repository name at the top of the lock file), doesn't seem to help.

When starting up a session with the environment, `renv::status` complains that the packages are no longer used in the project and should be removed from the lock file.

This is only happening with these data packages, and I'm wondering if they have different semantics from normal packages that `renv` is unable to parse correctly.

Any suggestions?

**Comment by kevinushey** [comment]
I suspect this is because data packages are never explicitly used by other packages (that is, they aren't listed in `Imports` or `Depends` of other packages), and `renv` doesn't collect all `Suggests` dependencies.

To test, does adding:

```
library(BSgenome.Hsapiens.UCSC.hg38)
```

to a file (e.g. `deps.R`) cause it to show up in the lockfile?

**Comment by birnbera** [comment]
I actually do have it within a script but using something akin to:
```R
lib <- "BSgenome.Hsapiens.UCSC.hg38"
requireNamespace(lib)
``` 
I imagine this would be difficult for `renv` to parse as a dependency, though.

**Comment by kevinushey** [comment]
> I imagine this would be difficult for renv to parse as a dependency, though.

That's unfortunately correct. This is discussed a bit here: https://rstudio.github.io/renv/articles/faq.html

In situations like this (where the `renv` dependency discovery machinery cannot automagically figure out what your project needs) the simplest fix is to manually declare that dependency in the project.

**Comment by birnbera** [comment]
Am I able to use "explicit" snapshotting without a DESCRIPTION file? In other words, do no dependency discovery but just snapshot whatever is installed in the project library?

**Comment by kevinushey** [comment]
That's the version for type = "all"; that is, just snapshot whatever happens to be in the project library, without applying a filter based on what appears to be used in the project.
