### ISSUE TITLE
`renv::update()` issues

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#632]
Origin: https://github.com/rstudio/renv/issues/630#issuecomment-772828131

renv 0.12.5 (CRAN)

I missed to say that the initial reason to comment in the linked issue was that I had the exactly same error message as in the OP.
However, this does not necessarliy mean that I am seeing the same error.

I don't have a reproducible example to paste but I went through the stacktrace and found that one of the GitHub packages in `renv.lock` pointed to a owner/repo combination which does not exist anymore (the owner of the repo changed).

```r
1: renv::update()
 2: renv_update_find(selected)
 3: enumerate(grouped, function(source, records) {
    case(source == "B
 4: lapply(idx, callback)
 5: FUN(X[[i]], ...)
 6: f(n[[i]], x[[i]], ...)
 7: case(source == "Bioconductor" ~ renv_update_find_repos(records), sou
 8: eval(expr, envir = environment(dot))
 9: eval(expr, envir = environment(dot))
10: renv_update_find_github(records)
11: renv_parallel_exec(records, renv_update_find_github_impl)
12: lapply(data, callback)
13: FUN(X[[i]], ...)
14: renv_remotes_resolve_github_sha_ref(host, user, repo, ref)
15: renv_retrieve_origin(host)
```

After reinstalling this package, I faced more errors for GitHub packages which was pointing to the master branch but the repo changed the default branch to `main`. After having found all of these, I
faced a problem with `r-lib/crancache`. Here, the renv.lock entry actually seemed fine but it appaered in the traceback (frame number 14)

```
    "crancache": {
      "Package": "crancache",
      "Version": "0.0.0.9000",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteRepo": "crancache",
      "RemoteUsername": "r-lib",
      "RemoteRef": "master",
      "RemoteSha": "11e6bde59e05b76b8dcabb194f693592e31d93f3",
      "Hash": "0acb4226e555fd9ed40ec115b85c2c83"
    },
```

The new renv.lock entry also has the `RemoteHost` field. Could this be an issue with the old entry?

```
    "crancache": {
      "Package": "crancache",
      "Version": "0.0.0.9001",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "r-lib",
      "RemoteRepo": "crancache",
      "RemoteRef": "master",
      "RemoteSha": "7ea4e479bdf780adadd1bd421a5ca23e5f951697",
      "Hash": "4d052e39a8632b360df78452982162cc"
    },
```

The next package I checked also seemed fine with respect to branch and owner/repo but also missed the `RemoteHost` entry.

I haven't yet processed all packages. 
I'll try adding `"RemoteHost": "api.github.com"` to all entries tmrw and see if that helps.

**Comment by kevinushey** [comment]
Thanks for the extra information! I think you're correct that the issue here is caused by the missing `RemoteHost` field. I've pushed a fix to `renv` if you'd like to test again with the latest development version.

**Comment by pat-s** [comment]
Thanks Kevin! 🚀
