### ISSUE TITLE
How to prevent stealth copying from user library?

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#636]
Hi Kevin 👋 

We faced a strange scenario this morning while upgrading a RSP container from 18.04 to 20.04. During this process we realized that renv somehow copies binaries from the local user library even though all configs were set not to do this. Do we overlook something or is this a bug?

## Scenario

- `stringi` installed in user library (no renv) from binary on Ubuntu 18.04 (RSP) some days ago
- `RENV_PATHS_CACHE=/opt/renv/cache`
- `RENV_PATHS_BINARY=/opt/renv/binary`
- `RENV_PATHS_SOURCE=/opt/renv/source`

→ Upgrade RSP/OS to 20.04 (RSP running in a container with the home dirs mounted)

→ Delete renv/cache, renv/binary, renv/source to start fresh

→ `renv::init()` in project (new session)

→ `renv::install("stringi")`

Now instead of downloading a new binary, renv copies the local binary (console log says: `copied binary`) from the user library.

Then `library("stringi")` fails because it tries to link against `libicu60` (bionic) but the container has `libicu66` (focal).

## Questions

- Is there a way to prevent {renv} from copying from the user library? It would be great if we could restrict this to the paths set with `RENV_PATHS_*`. To make this clear, this does not relate to `renv.config.user.library` but where renv gets cached packages from.

  ```r
   .libPaths()
  [1] "/home/someuser/project/renv/library/R-4.0/x86_64-pc-linux-gnu"
  [2] "/tmp/Rtmpn3oKZp/renv-system-library"
   ```

- Because renv does not report where it copies the binary from it took us long to realize that renv did not copy it from RENV_PATHS_BINARY but from the users local library. Maybe a verbosity setting could help here to tell where it got the binary from?

- Installing `stringi` again into the user library and then letting renv pick it up solved the issue. This prooves the assumption that renv copied the pkg from the user library.

- renv states in the log "copied local binary". Where does this binary come from in this scenario? AFAIK there are only installed packages in the user library but not the downloaded binaries (binaries <-> installed packages). Only renv stores and caches the pkg binaries (?) but we deleted all binaries in `RENV_PATHS_BINARY` and `~/.local/share/renv`.

**Comment by kevinushey** [comment]
This is occurring here:

https://github.com/rstudio/renv/blob/f64494b1129db7dae81677a973d9f179e290f0f1/R/retrieve.R#L363-L369

Basically, we look at the user + site libraries, and if we see a compatible version of the requested package installed there, we copy from that location. Right now this behavior isn't configurable, but it probably should be.

**Comment by kevinushey** [comment]
https://github.com/rstudio/renv/commit/34d2ee3fa1473ac75875a651baa81fb652746382 should allow you to configure this behavior with:

```
options(renv.config.install.shortcuts = FALSE)
```

Let me know if that seems sufficient.

**Comment by pat-s** [comment]
Thanks Kevin!

cc @krlmlr @ThomasKnecht
