### ISSUE TITLE
should `renv_download_curl()` inherit local config from _curlrc/.curlrc?

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#64]
At my work we have an awful man in the middle proxy which decrypts all traffic by substituting the certificates on all secure connections. We work around this by disabling certificate verification for git and other services. 

We can do the same for `curl` using the `insecure` option in the `curlrc` but since `renv` does not read this config and in fact provides its own, all attempted package installations fail due to certificate errors with curl.

edit relevant function is: renv_download_curl, https://github.com/rstudio/renv/blob/master/R/download.R#L87

**Comment by kevinushey** [comment]
Thanks! This is definitely something we'll want to support.

The intention of invoking `curl` in this way was to help ensure things like credentials wouldn't be leaked on the command line (e.g. so they can't be seen in the output of tools like `lsof`) but I think that implies we need to do extra work here to support user-defined `curlrc`s as well.

**Comment by kevinushey** [comment]
I think this should be handled correctly now -- can you test and let me know if you bump into any issues?
