### ISSUE TITLE
renv::install fails to install archived versions from company internal CRAN-like repo since renv version 0.12.4

### ISSUE THREAD

**Issue by schrnstn** [rstudio/renv#641]
Dear renv developers,

thank you for this very versatile and helpful package. It is a game changer to our package handling in R projects.

# Summary

I am facing a bug when downloading and installing an old package version from our company internal CRAN-like repository. Everything worked as intended until renv `0.12.3`. However, I run into an error as soon as I upgrade to any renv version from `0.12.4` onwards, including the latest dev-version.

# Assumption on the origin of the bug

I hypothesise that auth via the `renv.download.headers` option is not considered correctly when installing archived versions from private repos with `renv::install`.

I suppose that the bug may have been introduced in the following change stemming from the changelog details for `0.12.4`: 
> renv::install(<pkg>) will now install the latest-available version of that package from local sources, if that package is available and newer than any package available on the active package repositories. (#591)

# Setup

- We have a company internal R package called `MY-PACKAGE` hosted on our company internal R package distribution server `https://company-repo-url` (the same problem arises with all of our packages)
- The latest version of `MY-PACKAGE` is `0.4.8`. I aim to install `0.4.6`, e.g. via `renv::install("MY-PACKAGE@0.4.6")` or during a call to `renv::restore()` when `0.4.6` is recorded in the lockfile and has not been cached yet.
- Auth via `renv.download.headers` option (as described in your [vignette](https://rstudio.github.io/renv/articles/renv.html#authentication-with-custom-headers-1))

# Working behaviour with `0.12.3`

```
r$> renv::install("MY-PACKAGE@0.4.6")
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz' ...
Retrieving 'https://company-repo-url/.../src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz' ...
        OK [downloaded 17 Kb in 5.6 secs]
Installing MY-PACKAGE [0.4.6] ...
        OK [built from source]
```

# Buggy behaviour with `0.12.4`

What does not work
1. `renv::install("MY-PACKAGE@0.4.6")`
2. `renv::restore()` when `0.4.6` is pinned in `renv.lock`

What works
3. `renv::install("MY-PACKAGE")`, i.e. installing the latest version
4. `renv::install("https://company-repo-url/.../src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz")`, i.e. providing the correct URL.
5. `renv::install("MY-PACKAGE@0.4.6")` from a local directory with the exact same folder structure as on the server.
6. `renv::install("data.table@1.11.8")`, i.e. installing an archived version of a publically available package

# Log output

Numbering refers to the overview in the previous section.

1. `renv::install("MY-PACKAGE@0.4.6")`

```
r$> renv::install("MY-PACKAGE@0.4.6")
The following error(s) occurred while retrieving 'MY-PACKAGE':

        - character(0)
        - character(0)

Error: failed to retrieve package 'MY-PACKAGE'
Traceback (most recent calls last):
7: renv::install("MY-PACKAGE@0.4.6")
6: renv_retrieve(names(remotes))
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)
```

2. `renv::restore()` when `0.4.6` is pinned in `renv.lock`

```
r$> renv::restore()
The following package(s) will be updated:

# COMPANY-REPO ============================
- MY-PACKAGE   [0.4.5 -> 0.4.6]

Do you want to proceed? [y/N]: y
The following error(s) occurred while retrieving 'MY-PACKAGE':

        - character(0)
        - character(0)

Error: failed to retrieve package 'MY-PACKAGE'
Traceback (most recent calls last):
8: renv::restore()
7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
6: renv_retrieve(packages)
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)
```

3. `renv::install("MY-PACKAGE")`, i.e. installing the latest version

```
r$> renv::install("MY-PACKAGE")
Retrieving 'https://company-repo-url/.../src/contrib/MY-PACKAGE_0.4.8.tar.gz' ...
        OK [downloaded 18.3 Kb in 6.5 secs]
Installing MY-PACKAGE [0.4.8]
```

4. `renv::install("https://company-repo-url/.../src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz")`, i.e. providing the correct URL

```
r$> renv::install("https://company-repo-url/.../src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz")
Installing MY-PACKAGE [0.4.6] ...
* installing to library 'C:/Users/USERNAME/AppData/Local/Temp/RtmpAd6P81/renv-staging-2a5456432c75'
* installing *source* package 'MY-PACKAGE' ..
```

5. `renv::install("MY-PACKAGE@0.4.6")` from a local directory with the exact same folder structure as on the server.

```
r$> renv::install("MY-PACKAGE@0.4.6")
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
Retrieving 'file:C:/Users/USERNAME/.../src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz' ...
        OK [downloaded 17 Kb in 0 secs]
Installing MY-PACKAGE [0.4.6] ...
```

6. `renv::install("data.table@1.11.8")`, i.e. installing an archived version of a publically available package from RStudio CRAN

```
r$> renv::install("data.table@1.11.8")
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/data.table/data.table_1.11.8.tar.gz' ...
        OK [downloaded 3.1 Mb in 1.1 secs]
Installing data.table [1.11.8] ...
* installing to library 'C:/Users/USERNAME/AppData/Local/Temp/RtmpAd6P81/renv-staging-2a541d2d251'
* installing *source* package 'data.table'
```

**Comment by kevinushey** [comment]
Thank you for the bug report! My first suspicion is that you are correct -- we're forgetting to pass headers when checking if a particular archive URL is available here.

https://github.com/rstudio/renv/commit/b1cf4d43c19e9aed423cf5dcc8a7a399d23b63da

Can you try installing the development version of `renv`, and see if the issue persists? You can use:

```
renv::install("rstudio/renv")
```

to install the development version in a project, and then restart the R session to ensure that version is loaded.

**Comment by schrnstn** [comment]
Dear Kevin, thank you for your fast reply. Using the dev-version, I still receive the warning from above. The empty error message is no longer present, as you intended in one of your recent commits.

```
r$> renv::install("MY-PACKAGE@0.4.6")
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
Error: failed to retrieve package 'MY-PACKAGE'
Traceback (most recent calls last):
7: renv::install("MY-PACKAGE@0.4.6")
6: renv_retrieve(names(remotes))
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)
```

Please feel free to give me further instructions such that we can understand the bug throroughly.

**Comment by kevinushey** [comment]
Thanks for reporting back so quickly. Let's try one more thing -- install the development version of `renv` with:

```
remotes::install_github("rstudio/renv")
```

Then, try to download once more with:

```
options(renv.download.trace = TRUE)
renv::install("<...>")
```

replacing the `install()` statement as appropriate. You should see the exact commands we're sending to `curl` (or whichever downloader is being used); e.g.

```
> renv::install("digest@0.6.25", rebuild = TRUE)
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/digest/digest_0.6.25.tar.gz' ...
# Downloading 'https://cran.rstudio.com/src/contrib/Archive/digest/digest_0.6.25.tar.gz' [curl]

## Request ===================================================================
location
fail
silent
show-error
head
include
user-agent = "renv (0.12.5-47); RStudio Desktop (1.4.1541); R (4.0.3 x86_64-apple-darwin17.0 x86_64 darwin17.0)"
url = "https://cran.rstudio.com/src/contrib/Archive/digest/digest_0.6.25.tar.gz"
output = "/private/tmp/RtmpTtumPW/renv-tempdir-44ab7c736487/renv-headers-44ab5e63652a"
connect-timeout = "20"
retry = "3"

## Output ====================================================================
[no output generated]

## Status ====================================================================
0

	OK [file is up to date]
Installing digest [0.6.25] ...
	OK [built from source]
Copying digest [0.6.25] into the cache ...
	OK [copied 40 files in 0.036 seconds]
```

**Comment by schrnstn** [comment]
Nice prints! This results in the following logs. The third request should have worked. However, it results in a 416 error.

```
r$> renv::install("MY-PACKAGE@0.4.6")
# Downloading 'https://cran.rstudio.com/src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz' [curl]

## Request ===================================================================
location
fail
silent
show-error
user-agent = "renv (0.12.5-48); R (4.0.3 x86_64-w64-mingw32 x86_64 mingw32)"
url = "https://cran.rstudio.com/src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz"
output = "C:/Users/USERNAME/AppData/Local/Temp/RtmpI1UcYW/renv-tempdir-514011e25e84/renv-download-51401db01c2e"
connect-timeout = "20"
retry = "3"

## Output ====================================================================
curl: (22) The requested URL returned error: 404 Not Found

## Status ====================================================================
22

# Downloading 'https://cran.rstudio.com/src/contrib/Archive/MY-PACKAGE/0.4.6/MY-PACKAGE_0.4.6.tar.gz' [curl]

## Request ===================================================================
location
fail
silent
show-error
user-agent = "renv (0.12.5-48); R (4.0.3 x86_64-w64-mingw32 x86_64 mingw32)"
url = "https://cran.rstudio.com/src/contrib/Archive/MY-PACKAGE/0.4.6/MY-PACKAGE_0.4.6.tar.gz"
output = "C:/Users/USERNAME/AppData/Local/Temp/RtmpI1UcYW/renv-tempdir-514011e25e84/renv-download-5140113e15de"
connect-timeout = "20"
retry = "3"

## Output ====================================================================
curl: (22) The requested URL returned error: 404 Not Found

## Status ====================================================================
22

# Downloading 'https://company-repo-url/.../src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz' [curl]

## Request ===================================================================
location
fail
silent
show-error
user-agent = "renv (0.12.5-48); R (4.0.3 x86_64-w64-mingw32 x86_64 mingw32)"
url = "https://company-repo-url/.../src/contrib/Archive/MY-PACKAGE/MY-PACKAGE_0.4.6.tar.gz"
output = "C:/Users/USERNAME/AppData/Local/Temp/RtmpI1UcYW/renv-tempdir-514011e25e84/renv-download-5140193f1701"
connect-timeout = "20"
retry = "3"
header = "<removed - header is correct>"

## Output ====================================================================
curl: (22) The requested URL returned error: 416 Requested Range Not Satisfiable

## Status ====================================================================
22

# Downloading 'https://company-repo-url/.../src/contrib/Archive/MY-PACKAGE/0.4.6/MY-PACKAGE_0.4.6.tar.gz' [curl]

## Request ===================================================================
location
fail
silent
show-error
user-agent = "renv (0.12.5-48); R (4.0.3 x86_64-w64-mingw32 x86_64 mingw32)"
url = "https://company-repo-url/.../src/contrib/Archive/MY-PACKAGE/0.4.6/MY-PACKAGE_0.4.6.tar.gz"
output = "C:/Users/USERNAME/AppData/Local/Temp/RtmpI1UcYW/renv-tempdir-514011e25e84/renv-download-514047e97e73"
connect-timeout = "20"
retry = "3"
header = "<removed - header is correct>"

## Output ====================================================================
curl: (22) The requested URL returned error: 404 NOT FOUND

## Status ====================================================================
22

Error: failed to retrieve package 'MY-PACKAGE'
Traceback (most recent calls last):
7: renv::install("MY-PACKAGE@0.4.6")
6: renv_retrieve(names(remotes))
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)

```

**Comment by kevinushey** [comment]
Thanks! That makes it clear this portion is failing:

https://github.com/rstudio/renv/blob/abd4974cfa61e49fadc86bceea7fcbe26d67a7e9/R/download.R#L758-L760

The goal here is to use `curl` to probe the requested URL to see if it's available, and setting `-r 0-0` basically asks the server to only provide the first byte of the file (making it cheap). Unfortunately that operation isn't supported here.

The solution here is probably to request headers for that URL instead of requesting a specific range, since that's more likely to be supported for that URL.

**Comment by kevinushey** [comment]
I'm now 99% sure this should be resolved in the development version of `renv` now -- can you give it one more test?

**Comment by schrnstn** [comment]
Great work! Works like a charm.
Your fast response and fix time really makes us trust in renv being a great choice for our R package management setup.

Thanks a lot!

**Comment by schrnstn** [comment]
@kevinushey When are you planning to release a `0.12.6` on CRAN containing these changes?

I am running into a follow up problem. I think bootstrapping `0.12.5-51` from GitHub with the logic in `renv/activate.R` file works differently then `renv::install("rstudio/renv@0.12.5-51")`.

I may file an issue with a reprex if this persists after the CRAN release.

**Comment by kevinushey** [comment]
Can you please file that now so I might be able to fix before release?

**Comment by schrnstn** [comment]
@kevinushey Sorry for my late reply. Have been busy on other topics. When preparing my reprex I figured that the mistake was on my side. Sorry for the false alarm.

**Comment by kevinushey** [comment]
No worries; thanks for reporting back!

**Comment by schrnstn** [comment]
Ultimately, there really seems to be a bug related to the `renv.download.headers` option which may be related to this issue.
See #665
