### ISSUE TITLE
document how renv::use_python affects RETICULATE_PYTHON_ENV

### ISSUE THREAD

**Issue by myoung3** [rstudio/renv#642]
Two related issues:
- The help file here (https://rstudio.github.io/renv/reference/use_python.html) states that "On load, set the RETICULATE_PYTHON environment variable, so that the reticulate package can automatically use the requested copy of Python as appropriate," This could be more clear that this effectively *supersedes* any RETICULATE_PYTHON value set in .Renviron (ie while the value in .Renviron is left as-is, it is silently ignored)
- when `renv::use_python(name=)` is specified, presumably renv::use_python does the same for RETICULATE_PYTHON_ENV that the python argument does for RETICULATE_PYTHON. Adding to this information to the help file would be good.

**Comment by hadley** [comment]
* That's what setting an environment variable means — it replaces any existing values.
* I don't see any code in renv that changes `RETICULATE_PYTHON_ENV`, so I think that code must have changed in the interim.
