### ISSUE TITLE
install packages from lockfile to normal .libPaths() library

### ISSUE THREAD

**Issue by myoung3** [rstudio/renv#644]
It would be great if there would be a way to install all packages from a given lockfile into the standard .libPaths() library. This would facilitate faster renv::restore() when renv::restore() is being called repeatedly in complex pipelines (e.g. distributing to a HPC cluster).

**Comment by kevinushey** [comment]
You should be able to use `renv::restore(library = <your desired library path>, lockfile = <path to lockfile>)`.

> This would facilitate faster renv::restore() when renv::restore() is being called repeatedly in complex pipelines (e.g. distributing to a HPC cluster).

If you have the `renv` cache set up and accessible to each cluster, then they'd be able to re-use the global cache here as well.

**Comment by myoung3** [comment]
Thanks. I misunderstood how renv used caching. I was under the impression it was copying from .libPaths(), if available, and downloading and installing to a local ./renv library otherwise. The use of symlinks should make setup super fast. This is perfect, thanks!
