### ISSUE TITLE
Multiple paths in renv.config.hydrate.libpaths

### ISSUE THREAD

**Issue by boshek** [rstudio/renv#646]
Continued from [here](https://community.rstudio.com/t/creating-renv-cache-in-an-offline-environment/95521/5). I think there _may_ be an issue but I am trying to give as much context as possible as it is equally possible that I am diagnosing my problems incorrectly. Thanks for such a great package. 

```
Diagnostics Report -- renv [0.12.5]
===================================

# Session Info =======================
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    
---
# Environment Variables ==============
HOME        = C:/Users/salbers
LANG        = <NA>
R_LIBS      = R:/.libs/RLIBS/3.6
R_LIBS_SITE = R:/.libs/RLIBS
R_LIBS_USER = U:/RLIBS
```
My first issue when I run `renv::init` is renv can't seem to find the libraries. `renv_hydrate_dependencies` seems to struggle with the `R_LIBS_SITE` set this way. That is it doesn't seem to find the directory 3.6 directory that is within and therefore, although all dependencies are detected in the project, none can be found to copy over. So if I set: `options(renv.config.hydrate.libpaths = c("R:/.libs/RLIBS/3.6"))` then at least `renv_hydrate_dependencies` knows where to find dependencies. However at this point I run into copying issues where `renv` complains:

```
Error:could not copy / move file '{project_path}/renv/library/R-3.6/x86_64-w64-ming32/fansi' to '{project_path}/renv/library/R-3.6/x86_64-w64-ming32/.renv-backup-fansi24f0323e704e'
copy: source file '{project_path}/renv/library/R-3.6/x86_64-w64-ming32/fansi'  does not exist.
```

My solution to that is to set `options(renv.config.cache.symlinks = FALSE)`. That works fine, copies files directly to that project and I am able to lock/restore as normal. 

The final wrinkle here is that I have local packages that are installed at `R_LIBS_USER` (`U:/RLIBS`) which I also need. So then I thought to add a second path to `renv.config.hydrate.libpaths`. Unfortunately that seems to result in a misformed ("flipped" as you say) path:

``` r
options(renv.config.hydrate.libpaths = c("R:/.libs/RLIBS/3.6", "U:/RLIBS"))
renv:::renv_hydrate_libpaths()
#> [1] "C:/Users/salbers/AppData/Local/Temp/RtmpUjXIrO/reprex87e0501d33db/R"
#> [2] "C:/.libs/RLIBS/3.6"                                                 
#> [3] "C:/Users/salbers/AppData/Local/Temp/RtmpUjXIrO/reprex87e0501d33db/U"
#> [4] "C:/RLIBS"
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I _think_ this is where things are going wrong:
https://github.com/rstudio/renv/blob/4743bda1d4578784ea8abb8292a692abe686f069/R/hydrate.R#L141

But I am not clear quite what this line is doing:
https://github.com/rstudio/renv/blob/4743bda1d4578784ea8abb8292a692abe686f069/R/hydrate.R#L131

**Comment by kevinushey** [comment]
Can you confirm what the output of `normalizePath("U:/RLIBS")` is? Does that actually get resolved back to `C:/.libs/RLIBS/3.6`? (Is that file path a Windows symlink or something similar?)

**Comment by boshek** [comment]
No that resolves to `U:\\RLIBS`

**Comment by boshek** [comment]
Ahh! It was a symlink - very good guess. It resolves to a personal drive on the same volume. I am still getting that R letter appended to the end of the path and the drive is replaced with C:

``` r
options(renv.config.hydrate.libpaths = c("R:/.libs/RLIBS/3.6", "R:/salbers/RLIBS"))
renv:::renv_hydrate_libpaths()
#> [1] "C:/Users/salbers/AppData/Local/Temp/Rtmpg5br5m/reprex45a081452d2/R"
#> [2] "C:/.libs/RLIBS/3.6"                                                
#> [3] "C:/Users/salbers/AppData/Local/Temp/Rtmpg5br5m/reprex45a081452d2/R"
#> [4] "C:/salbers/RLIBS"
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
