### ISSUE TITLE
Feature request: function to batch-install all packages "used in the project, but not installed"

### ISSUE THREAD

**Issue by MatthieuStigler** [rstudio/renv#647]
Thanks to the commit https://github.com/rstudio/renv/commit/7bd669b40dea4c3bb1ce61731701159d7aef6fb7, now renv correctly detects newly required packages (i.e. after init), and gives message: *The following package(s) are used in the project, but are not installed:*. Is it possible to have a function to install those newly added packages in batch?

The current workflow is either:

1. Install all of them manually with `renv::install()`.
2. Install all of them automatically with `renv::hydrate()`. 

The problem with 1) is that this is quite cumbersome, and against the usual workflow in R (install a package once forever, no need to install again in every new project, just call with `library`). 

The problem with 2) is that this will also update all other installed packages to their latest version! This goes against a conservative approach, that would update packages only when needed, or only after testing. Updating packages and installing newly required are two distinct steps, that could ideally be called separately?

Thanks!

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding, but `renv::hydrate()` should already conform to your expectations. It will look at the packages used in your project, and either:

1. Copy an installed version from the cache, or the user library paths; or,
2. Install the latest-available copy from CRAN.

That is, you shouldn't see any packages being updated. Can you provide any more details -- ideally, a reproducible example?

**Comment by kevinushey** [comment]
The main reason I can think of that `hydrate()` would update an already-installed package would be because the newly-installed package(s) depends on an already-installed package, but actually requires a newer version of that package. Is that plausible?

**Comment by MatthieuStigler** [comment]
Hi Kevin

Thanks for your answer! I actually believe `hydrate` does seek to update packages which are available elsewhere on the system. In the code below, I have say version `1.0.15` of ash on my system, but install `1.0.13` in my project (obviously this is artificial: I would usually have a version installed on my renv project, then update the general library). When I add a new package in a script and use `hydrate` to install it, it seems `hydrate` also updates ash!? This does not happen, however, if I don't have the newer version on my general library: indeed `hydrate` is not looking on CRAN for updates. But it seems to do so for local updates? 

This is where my feature request is: it would be great if those two steps could be separated (install missing packages versus updated versions of recorded packages?)

Here is a (almost) reproducible example:


```
## Create project
tmp_dir <- tempdir()
pkg_dir <- paste0(tmp_dir, "/MyNewProject")
usethis::create_project(path = pkg_dir, open = FALSE, rstudio = TRUE)

## Install expint in your general library
remotes::install_version("ash", version = "1.0.15", repos = "http://cran.us.r-project.org")

## init
renv::init(pkg_dir, restart=FALSE)

## require and add package, older version
cat("library(ash)", file=paste0(tmp_dir, "/MyNewProject/R/first_file.R"))

renv::status(pkg_dir)
remotes::install_version("ash", version = "1.0.13", repos = "http://cran.us.r-project.org")
renv::status(pkg_dir)
renv::snapshot(pkg_dir, prompt = FALSE)

## Now add new requirement
cat("\nlibrary(viridisLite)", file=paste0(tmp_dir, "/MyNewProject/first_file.R"))
renv::status(pkg_dir)

## Using hydrate will not only install newly required, but also seek to update others!?
renv::hydrate()
renv::status(pkg_dir)


## stop
fs::dir_delete(pkg_dir)
```

**Comment by kevinushey** [comment]
Thank you very much for taking the time to create a reproducible example! You are indeed correct -- `hydrate()` is updating packages that already happen to be installed in the project library.

I'll see if we can make this behavior configurable.

**Comment by kevinushey** [comment]
Now implemented in the development version of `renv` -- use `renv::hydrate(update = FALSE)` to only pull in packages that aren't already installed in the project library.

**Comment by MatthieuStigler** [comment]
great, thanks a lot!!
