### ISSUE TITLE
clean() could continue even if answer is no

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#65]
When `clean()` is used, a question is asked if interactive
```r
> renv::clean()
The following non-system packages are installed in the system library:

	translations

These packages will be removed.
Consider re-installing these packages in your site library.

Do you want to proceed? [y/N]:
```
If I say no, the operation is aborted. As other kind of interactive functions, I would expect it to continue to the next cleaning task even if I don't want to go on with the previous one. 

I am not sure there is a real use case behind that. It is just a feeling as a user. I need to say yes to go to see what next step is.

What do you think ?

**Comment by kevinushey** [comment]
This has been implemented now -- rather than stopping after the first 'no', `renv` will keep going with each possible clean action. (The user can use Escape to interrupt R and cancel all future clean requests)
