### ISSUE TITLE
Portable renv?

### ISSUE THREAD

**Issue by liutiming** [rstudio/renv#650]
I wonder if it is possible to port a renv to another computer. I often find myself working in data heaven with no internet access and this will make it very difficult to install packages with many dependencies.

**Comment by kevinushey** [comment]
You can use `renv::isolate()` to copy the packages used by a project to the project library. Once that's done, you can copy the project folder to another computer (of the same OS / architecture), install R, and open the project, and things should "just work".

**Comment by liutiming** [comment]
Brilliant thanks a lot!

________________________________
