### ISSUE TITLE
Auto snapshot should not be triggered by renv::status()

### ISSUE THREAD

**Issue by schrnstn** [rstudio/renv#651]
Suppose that `options(renv.config.auto.snapshot = TRUE)` and I receive
```
* The project may be out of sync -- use `renv::status()` for more details.
```
on startup.

Running `renv::status()` automatically triggers a snapshot. If I want to `renv::restore()` after inspecting the output of `renv::status()` , I have to first reset the changes of the lockfile (with git).

Am I doing something wrong here?
This behaviour does not make sense to me.

# Example

```
❯ r40
* The project may be out of sync -- use `renv::status()` for more details.
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Platform: x86_64-w64-mingw32 (64-bit)

r$> renv::status()
The following package(s) are recorded in the lockfile but not installed:
      _
  zoo   [1.8-8]

Use `renv::restore()` to install these packages.

* Automatic snapshot has updated '~/repos/my-package/renv.lock'.

r$> renv::restore()
* The library is already synchronized with the lockfile.
```

![image](https://user-images.githubusercontent.com/16709990/107975967-29737f00-6fb9-11eb-9be0-4ddfbd97c67c.png)

**Comment by kevinushey** [comment]
The behavior makes sense in that having automatic snapshots enabled implies trying to eagerly synchronize the state of the lockfile with that of the project library -- it's just doing so too eagerly in this case.

What's confusing to me is that the behavior here should be keyed off of whether `renv` detects that the project library has been modified. For some reason, `renv` is seeing the project library state as having changed in your project after calling `renv::status()`.

**Comment by schrnstn** [comment]
Yes, I agree that `renv` seems to be to eager in this case. Is this something you intend to fix? As of now I think this behaviour is not bound to my local environment and applies for all uses.
The current behaviour makes me turn of the `auto.snapshot` option, although we would really like to use it for simplicity in keeping the `renv.lock` up-to-date.

**Comment by schrnstn** [comment]
Hello there, are you planning to work on this in the near feature?
Best wishes.

**Comment by kevinushey** [comment]
It should be fixed in the next version of renv on CRAN.

**Comment by schrnstn** [comment]
Thanks for the fix! I noticed a typo in the NEWS file: You wrote
`renv` no longer performs an automatic snapshot after a call to `renv::snapshot()`. (#651)
but you mean
.... to `renv::status()`

**Comment by kevinushey** [comment]
Yes, that is a typo 😞 I'll fix that up.
