### ISSUE TITLE
Integrate debugme?

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#654]
Would you support adding logging via debugme to this project? I suspect this will simplify debugging and pinpointing bottlenecks, once we add a bit of logging code.

**Comment by kevinushey** [comment]
I'd be open to this (or some other form of logging).

It looks like the CRAN version of `debugme` has some issues, though:

```
> renv::install("r-lib/debugme")
Error: .onLoad failed in loadNamespace() for 'renv', details:
  call: as.function.default(c(value, if (is.null(bd) || is.list(bd)) list(bd) else bd),
  error: use of NULL environment is defunct
>
```

Also: is it possible for `debugme` to use `glue` strings here, so that we could log the value of certain variables?

**Comment by krlmlr** [comment]
It's weird, the error comes from base's `formals<-()` . Does it occur when you try to install, or when it's active? Also with the CRAN version (your code installs the GitHub version)?

debugme uses backticks for this purpose. I'm using a helper function that prints expression and value: https://github.com/r-lib/pillar/blob/master/R/utils.R#L64-L67

**Comment by hadley** [comment]
This is an interesting idea, but not something we're considering at the moment.
