### ISSUE TITLE
system library that is installed doesn't appear in Packages/System Library 

### ISSUE THREAD

**Issue by ras44** [rstudio/renv#656]
I installed a variety of libraries at the system level.  When I run R on the command-line, I can call `library(here)`, for example, and it will reference the system here lib.  Also, when I start a regular R project, the system libs that I installed are all there.  However, when I open a project in RStudio Server with renv they do not appear.  I only see what look like a core set of system libs.

I'm guessing this is probably intentional, so that external (non-core) system libs are not modified on the fly, potentially corrupting the environment.  On the other hand, we create instances that data scientists use and would like them to use the same set of base libraries.

It sounds like the simple solution is just to snapshot what were system libs into renv as well- does that sound right?

Apologies if this is not so much an issue as a comment.

**Comment by kevinushey** [comment]
Just to be sure, by "system" library do you mean the library referenced by the `.Library` variable in an R session? Or do you mean a site library (`.Library.site`) or user library?

By default, `renv` will generate a "sandboxed" version of the system library, to help ensure `renv` projects are properly isolated and don't accidentally depend on external packages. This behavior can indeed be configured though: in an appropriate `.Renviron` (say, `Renviron.site` for your R install) you could set:

```
RENV_CONFIG_SANDBOX_ENABLED = FALSE
```

and that would tell `renv` to use the system library "as-is" in each project.

**Comment by ras44** [comment]
oh, great- thanks, that looks like it would be useful.  I was referencing the library referenced by the `.Library` variable.

**Comment by kevinushey** [comment]
Thanks! I think this issue can be closed; feel free to re-open or file a new issue if you still have any questions.
