### ISSUE TITLE
validate that 'curl' works on load and disable if it doesn't

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#660]
https://stackoverflow.com/questions/66282859/curl-error-is-not-allowing-packages-installation-in-rstudio-under-renv

**Comment by sdcharle** [comment]
I am still seeing this today (6/26/2022)

R Version 4.2.0
renv version 0.15.5

I have tested, and outside of renv things work without the warning, so it does not appear to be a network issue. Perhaps renv is not acknowledging my selections in the global options in R Studio?

Do you know when this issue might be addressed? I'm trying to encourage renv usage but this is a bit of a blocker

**Comment by kevinushey** [comment]
Can you elaborate a bit more? https://rstudio.github.io/renv/articles/renv.html#downloads gives some prescriptions / potential solutions.

**Comment by hadley** [comment]
Given no one else has reported a similar problem and it's > 2 years since the original issue, I'm going to close.

**Comment by grainnemcguire** [comment]
If anyone finds their way to this issue with this problem then maybe this will help:

I have this problem currently - windows 10 22H2, renv v0.17.3, curl v5.0.0, AVG free anti-virus. I get a curl message in RStudio about missing certificates. I thought it was probably AVG causing problems since I've only recently started using it - and this is the first time I've had this problem after a couple of years of extensive `renv` use.

I got round it in 3 ways - the best one I think is following Kevin Ushey's link above (https://rstudio.github.io/renv/articles/renv.html#downloads). I put `options(renv.download.override = utils::download.file)` in my project .Rprofile - and that seems to have fixed things.

Other fixes that I used before I found this issue and the link above:

- **To install a single package**: typing `renv::install('data.table',repos='http://cran.us.r-project.org')` worked whereas `renv::install('data.table')` did not
- **Restoring from a renv lockfile**: I turned off my AVG antivirus while doing the restore and it worked.

**Comment by danielvartan** [comment]
Same here @grainnemcguire.

At first, the issue appeared to go away when I disabled Avast Antivirus, but, I don't know why, it reappeared again later.

Putting `options(renv.download.override = utils::download.file)` in `.Rprofile` seems to do the trick. Thank you! 🎉

**Comment by danielvartan** [comment]
> @danielvartan try `Sys.setenv(R_LIBCURL_SSL_REVOKE_BEST_EFFORT=TRUE)` [Source](https://stackoverflow.com/questions/76266237/install-packages-issues-behind-firewall)

The issue with this fix seems to be with `renv` permissions to overwrite a file. It may work for projects stored outside the Windows `User` space.

---

Comment: both `dplyr` and `lubridate` were already installed in `renv`'s project repository before the tests shown below.

---

`.Rprofile` before project load.

```r
source("renv/activate.R")
Sys.setenv(R_LIBCURL_SSL_REVOKE_BEST_EFFORT=TRUE)
```

Test:

```r
install.packages("dplyr")
#> # Downloading packages -------------------------------------------------------
#> - Downloading dplyr from CRAN ...               OK [file is up to date]
#> Successfully downloaded 1 package in 2.1 seconds.
#> 
#> The following package(s) will be installed:
#> - dplyr [1.1.4]
#> These packages will be installed into "~/GitHub/mastersthesis/renv/library/R-4.3/x86_64-w64-mingw32".
#> 
#> Do you want to proceed? [Y/n]: Y
#> 
#> # Installing packages --------------------------------------------------------
#> - Installing dplyr ...                          OK [installed binary and cached in 0.45s]
#> Error: target file 'C:/Users/Daniel/Documents/GitHub/mastersthesis/renv/library/R-4.3/x86_64-w64-mingw32/dplyr' already exists
#> Traceback (most recent calls last):
#> 11: install.packages("dplyr")
#> 10: install(pkgs)
#>  9: renv_install_impl(records)
#>  8: renv_install_staged(records)
#>  7: enumerate(targets, renv_file_move, overwrite = TRUE)
#>  6: lapply(idx, callback)
#>  5: FUN(X[[i]], ...)
#>  4: f(n[[i]], x[[i]], ...)
#>  3: renv_file_preface(source, target, overwrite)
#>  2: stopf("target file '%s' already exists", target)
#>  1: stop(sprintf(fmt, ...), call. = call.)
```

---

`.Rprofile` before project load.

```r
source("renv/activate.R")
options(renv.download.override = utils::download.file)
```

Test:

```r
install.packages("lubridate")
#> # Downloading packages -------------------------------------------------------
#> trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/lubridate_1.9.3.zip'
#> Content type 'binary/octet-stream' length 986642 bytes (963 KB)
#> downloaded 963 KB
#> 
#> Successfully downloaded 1 package in 1.7 seconds.
#> 
#> The following package(s) will be installed:
#> - lubridate [1.9.3]
#> These packages will be installed into "~/GitHub/mastersthesis/renv/library/R-4.3/x86_64-w64-mingw32".
#> 
#> Do you want to proceed? [Y/n]: Y
#> 
#> # Installing packages --------------------------------------------------------
#> - Installing lubridate ...                      OK [installed binary and cached in 0.47s]
#> Successfully installed 1 package in 17 seconds.
``` 

---

```r
sessionInfo()
#> R version 4.3.2 (2023-10-31 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 11 x64 (build 22621)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8   
#> [3] LC_MONETARY=Portuguese_Brazil.utf8 LC_NUMERIC=C                      
#> [5] LC_TIME=Portuguese_Brazil.utf8    
#> 
#> time zone: America/Sao_Paulo
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.33     fastmap_1.1.1     xfun_0.41         glue_1.6.2       
#>  [5] knitr_1.45        htmltools_0.5.7   rmarkdown_2.25    lifecycle_1.0.4  
#>  [9] cli_3.6.1         reprex_2.0.2      withr_2.5.2       compiler_4.3.2   
#> [13] rstudioapi_0.15.0 tools_4.3.2       evaluate_0.23     yaml_2.3.7       
#> [17] rlang_1.1.2       fs_1.6.3 
```

**Comment by kevinushey** [comment]
Based on this stack trace:

```
#> Error: target file 'C:/Users/Daniel/Documents/GitHub/mastersthesis/renv/library/R-4.3/x86_64-w64-mingw32/dplyr' already exists
#> Traceback (most recent calls last):
#> 11: install.packages("dplyr")
#> 10: install(pkgs)
#>  9: renv_install_impl(records)
#>  8: renv_install_staged(records)
#>  7: enumerate(targets, renv_file_move, overwrite = TRUE)
#>  6: lapply(idx, callback)
#>  5: FUN(X[[i]], ...)
#>  4: f(n[[i]], x[[i]], ...)
#>  3: renv_file_preface(source, target, overwrite)
#>  2: stopf("target file '%s' already exists", target)
#>  1: stop(sprintf(fmt, ...), call. = call.)
```

I wonder if the issue here is that one or more files within the `dplyr` folder are being accessed / held by your antivirus, and so `renv` is unable to move that folder prior to the installation of `dplyr`?

**Comment by danielvartan** [comment]
I think you're right @kevinushey ! I just test it after I disabled the antivirus and everything worked fine. Thank you for the suggestion.

Also, thank you @mabuimo for finding a solution to the problem.

**Comment by danielvartan** [comment]
About issues with `renv` when storing projects in the Windows `User` space.

I found that my privacy settings (`Settings > Documents`) were blocking Rstudio from writing some files. If someone still having issues with this, try checking those Windows settings.
