### ISSUE TITLE
Custom repos overwritten by renv in .profile

### ISSUE THREAD

**Issue by al-obrien** [rstudio/renv#661]
I am running on RStudio Server Pro with renv 0.12.5. When I try to use custom repositories via the *.Rprofile* I am finding the 'renv' script overwrites the provided values.

**(a) Running the repos prior to the 'activate.R' in renv will cause them to be overwritten.**
```
local({
  r <- getOption("repos")
  r["CRAN"] <- "https://cran.rstudio.com/"
  r["rspm_ext"] <- "https://customlocation.com"
  options(repos = r)
})

source("renv/activate.R")
```

Output is just the default CRAN set by renv.
```
getOption('repos')
                         CRAN 
"https://cloud.r-project.org" 
```

**(b) Running the code within `local({...})` after the activate script appears makes sure it is not overwritten.**
```
source("renv/activate.R")

local({
  r <- getOption("repos")
  r["CRAN"] <- "https://cran.rstudio.com/"
  r["rspm_ext"] <- "https://customlocation.com"
  options(repos = r)
})
```

## Session Info
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: RHEL

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    packrat_0.5.0  renv_0.12.5

**Comment by kevinushey** [comment]
This happens because `renv` stores the repositories used by a project in the lockfile, and those repositories get read and applied on startup.

The "fix" here would be something like:

```
options(repos = <...>)
renv::snapshot()
```

to update the repositories. Or, just use `renv::modify()` to change it directly with a text editor.

**Comment by al-obrien** [comment]
Thank you, I thought it might be something simple that I happened to miss.

I will give this a try.
