### ISSUE TITLE
Avoid reading lockfile during startup?

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#663]
This seems to be the single most time-consuming part during startup. Can we postpone reading the lockfile until we actually need it?

**Comment by kevinushey** [comment]
Does the slowness go away if you disable the startup synchronized check? E.g. with:

```
RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE
```

in an appropriate `.Renviron`.

**Comment by kevinushey** [comment]
(maybe that check should only be done in interactive sessions)

**Comment by kevinushey** [comment]
Sorry, that was incorrect. We read and use the lockfile here:

https://github.com/rstudio/renv/blob/dd75414ba7aef430ded8601f7681fd7d80b58078/R/load.R#L70-L74

That's basically done to:

1. Check the version of R being used and check that it matches the lockfile version,
2. Set the R repositories based on what's encoded in the lockfile.

**Comment by krlmlr** [comment]
We could read the first 100 lines or so, and cut after the first `"^  [}],"` (and replace it with `}`).

**Comment by kevinushey** [comment]
I just merged some changes that should substantially speed up the JSON parser:

## Before

```
> microbenchmark::microbenchmark(renv:::renv_lockfile_load(getwd()))
Unit: milliseconds
                               expr      min       lq    mean   median       uq      max neval
 renv:::renv_lockfile_load(getwd()) 51.68507 53.66519 56.3856 54.91054 57.66084 100.2985   100
```

## After

```
> microbenchmark::microbenchmark(renv:::renv_lockfile_load(getwd()))
Unit: milliseconds
                               expr      min       lq    mean  median       uq      max neval
 renv:::renv_lockfile_load(getwd()) 6.320551 7.657821 8.36583 7.93167 8.280665 12.34278   100
```

Hopefully this is now fast enough that the lockfile load speed is no longer a concern?

**Comment by krlmlr** [comment]
Thanks. renv still adds ~150ms to R's start time in `time R -q -e TRUE` (vs. the same with `--vanilla`), but it feels much faster now. I guess there's still room for improvement, there may be other things that can be optimized before these 10 ms (with a larger lock file) become relevant again. Let's keep this open for now.

**Comment by krlmlr** [comment]
`RENV_CONFIG_SYNCHRONIZED_CHECK = FALSE` helped remove another bottleneck, I wonder why `options(renv.config.synchronized.check = FALSE)` did not work in this case?

**Comment by krlmlr** [comment]
I'm mistaken, both options seem to work.
