### ISSUE TITLE
Slow startup due to querying of RSPM

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#664]
In my `renv.lock` I have

```
{
  "R": {
    "Version": "4.0.3",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://packagemanager.rstudio.com/all/1390593"
      }
    ]
  },
  "Packages": {
...
```

This slows down startup of the R session, because `renv_rspm_transform_impl()` actually queries RSPM. When I use `"URL": "https://packagemanager.rstudio.com/__linux__/focal/1390593"`, I can't install packages from CRAN.

Can we set a flag that indicates that the repo is an RSPM repo, so that the necessary transformations must be carried out without contacting RSPM?

**Comment by kevinushey** [comment]
I'd be open to a PR. Where do you think the right place to encode this metadata is? Should it be part of the lockfile? Or should there be an R option or similar that controls the behavior?

**Comment by krlmlr** [comment]
I'd suggest to make it part of the metadata that's written to the lockfile, so when we import legacy lockfiles this is inserted automatically with the next `snapshot()`.

**Comment by hadley** [comment]
Since it's been a couple of weeks and we haven't heard anything more, I'm going to close this issue.

**Comment by krlmlr** [comment]
I've seen this to be a problem recently, to the point that an renv project was inoperable without internet access (or with flaky internet access). Should we avoid network access during startup?

**Comment by kevinushey** [comment]
I think we could probably construct the binary URL without needing to contact RSPM? The code here does so:

https://github.com/rstudio/renv/blob/146afc4a4b9be79eccf0f3e1abd411298dd619e2/R/rspm.R#L68-L88

We could probably just strip that out and assume binaries are available on the current platform.

**Comment by hadley** [comment]
@kevinushey or could it cache the value in the repositories data structure?
