### ISSUE TITLE
Insights Unable to install new packages with install.packages() after running renv::init()

### ISSUE THREAD

**Issue by eduardcmp** [rstudio/renv#668]
Issue
Began using renv today for managing project environments and package dependencies. After creating a new project folder and running renv::init(), I attempted to install packages into the new project however am unable to do so.

Here is code below from my attempt to install the profvis package and related error and warnings:

> install.packages('profvis')
Error: package 'profvis' is not available
In addition: Warning messages:
1: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib"
2: could not retrieve available packages for url "https://cran.rstudio.com/bin/windows/contrib/3.6"

I've confirmed that I'm able to install the package in a new R session separate from the project. This issue is not unique to the profvis package as I have tried it on a few others with the same result

Also, I noticed when I went into RStudio-->Global Options-->Packages that I saw the following warning under the Package Management header that said

CRAN Repositories modified outside package preferences

I'm not sure what this is referring to exactly.

Also I'm working from my work laptop which might have security

System specs
Windows 10
RStudio v1.2.5033
R v3.6.2
renv v0.9.2

renv.lock file
{ "R": { "Version": "3.6.2", "Repositories": [ { "Name": "CRAN", "URL": "https://cran.rstudio.com" } ] }, "Packages": { "renv": { "Package": "renv", "Version": "0.9.2", "Source": "Repository", "Repository": "CRAN", "Hash": "5181d5f316c7a6589219866d640e004c" } } }

**Comment by kevinushey** [comment]
> 1: could not retrieve available packages for url "https://cran.rstudio.com/src/contrib"

It looks like your R session is unable to reach RStudio's CRAN mirror. What is the output of `getOption("repos")` in your `renv` project, versus a separate R project?

`renv` projects store the active repositories in the lockfile `renv.lock` and load those on startup, so you likely need to fix the repositories with something like:

```
options(repos = <your repos here>)
renv::snapshot()
```

**Comment by eduardcmp** [comment]
Thanks for the quick reply.



For the renv project I get "https://cran.rstudio.com" .  And for a normal project "https://cran.rstudio.com/"  attr(,"RStudio")

That doesn't seem to be the problem... It's weird, do you think it could have something to do with proxys or firewalls? But I can install packages as usual if I not use renv.

Thanks in advance

**Comment by kevinushey** [comment]
It could be the downloader then -- what is the output of:

```
options("download.file.method", "download.file.extra")
Sys.getenv(c("http_proxy", "https_proxy"))
```

in each case? Does setting:

```
Sys.setenv(RENV_DOWNLOAD_FILE_METHOD = "wininet")
```

help?

**Comment by ltrainstg** [comment]
I had the same issue and it did help.
