### ISSUE TITLE
renv tries to retrieve R-Forge packages from CRAN

### ISSUE THREAD

**Issue by jonnybaik** [rstudio/renv#671]
I have an `renv` enabled project that I am trying to run on a new machine. When I run `renv::restore()`, it correctly lists the package as being sourced from R-Forge, but then when I confirm the restore action, I see that it tries to retrieve the package from CRAN. However, the package is not listed on CRAN, so I get an error.

```r
> renv::restore()
The following package(s) will be updated:

# CRAN ===============================
- Matrix           [1.3-2 -> 1.2-18]

[...] ### Truncated

# R-Forge ============================
- circtree         [* -> 0.1-0]
- disttree         [* -> 0.2-0]

Do you want to proceed? [y/N]: y
* Querying repositories for available source packages ... Done!
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/boot/boot_1.3-25.tar.gz' ...
        OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/codetools/codetools_0.2-16.tar.gz' ...
        OK [downloaded 12.8 Kb in 0.1 secs]
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/Matrix/Matrix_1.2-18.tar.gz' ...
        OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/nlme/nlme_3.1-149.tar.gz' ...
        OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/Formula_1.2-4.tar.gz' ...
        OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/broom_0.7.5.tar.gz' ...
        OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/tidyr/tidyr_1.1.2.tar.gz' ...
        OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/cpp11_0.2.6.tar.gz' ...
        OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/circtree/circtree_0.1-0.tar.gz' ...       # <--- renv is trying to get the package from CRAN here
Error: failed to retrieve package 'circtree'
In addition: Warning message:
curl: (22) The requested URL returned error: 404
Traceback (most recent calls last):
8: renv::restore()
7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
6: renv_retrieve(packages)
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)

```

I am using renv version 0.13.0.

**Comment by kevinushey** [comment]
The simplest fix here would be to manually add `R-Forge` as a package repository; e.g.

```
repos <- getOption("repos")
repos[["R-Forge"]] <- "https://r-forge.r-project.org"
options(repos = repos)
```

Then use `renv::snapshot()` to ensure that repository is saved in your lockfile.

**Comment by jonnybaik** [comment]
Thanks, I ended up just manually installing the R-forge packages before running `renv::restore()` again. I posted the issue because I thought it was a bug.

**Comment by pdeffebach** [comment]
Yes. Can you try instantiating [this .lock file](https://gist.github.com/pdeffebach/f1e3cf25ddfb48403e3441948da8f045)?

**Comment by kevinushey** [comment]
Thanks -- I made a change in https://github.com/rstudio/renv/commit/5887b9b737cc2d7e74eca10bc70ba67f23d0ee88 that should help with this case. Can you try with the development version of `renv`?

Alternatively, you can modify the lockfile so that the repository fields read:

```
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      },
      {
        "Name": "R-Forge",
        "URL": "https://R-Forge.R-project.org"
      }
    ]

```

**Comment by pdeffebach** [comment]
The change you suggested worked! So likely the commit you linked to is a good fix. 

cc @lrberge since this may be specific to something fixest-related.

**Comment by kevinushey** [comment]
Thanks!

From my understanding, packages are typically installed from R-Forge without explicitly changing the `repos` R options; for example:

```
install.packages("maxLik", repos="http://R-Forge.R-project.org")
```

And because of that, `renv` doesn't "know" the repository URL that was used to download the package. Fortunately though, because packages installed from R-Forge have:

```
Repository: R-Forge
```

in their DESCRIPTION file, we can use that to infer their original source.
