### ISSUE TITLE
Error when project is specified in init()

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#673]
This is the error
``` r
dir.create(tmp_dir <- tempfile())
old <- setwd(tmp_dir)
dir.create("R")
list.files()
#> [1] "R"
getwd()
#> [1] "C:/Users/chris/AppData/Local/Temp/RtmpGEavao/file4cfc3c3556ae"
renv::init("R")
#> Error in normalizePath(path.expand(path), winslash, mustWork): path[1]="R": Le fichier spécifié est introuvable
getwd()
#> [1] "C:/Users/chris/AppData/Local/Temp/RtmpGEavao/file4cfc3c3556ae/R"
setwd(old)
unlink(tmp_dir)
```

<sup>Created on 2021-03-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9002)</sup>

`renv::init()` will change the working directory before calling other function
https://github.com/rstudio/renv/blob/7530431f1f780b9bffaa191149f2e289a92177a8/R/init.R#L96-L99

But `project` is still passed as is to functions that will try to normalize path, based on a new working dir.
https://github.com/rstudio/renv/blob/45cf93edb72f2d82e6b72372f447d2512a8927ef/R/dependencies.R#L1282-L1284

I believe this cause the issue. 

```r
> packageVersion("renv")
[1] ‘0.13.0.15’
```

**Comment by kevinushey** [comment]
Thanks; should be fixed on master now.
