### ISSUE TITLE
Proposal: make renv:::project public or add a public method for getting dependencies defined in renv.lock

### ISSUE THREAD

**Issue by donarus** [rstudio/renv#676]
Hi, would it be possible to make **renv:::project** public or somehow make available any option to get info about packages and their versions recorded in _renv.lock_ file?

Our use case is that we build and deploy internal snapshot  (ie. unstable versions under development) packages with version string as 99.99.99.9000 and what we are doing when we want to build a package is that we check all its (also transient) dependencies with 99.99.99.9000 version string and forcibly reinstalls them. And we don't want to increase the versions every time we make a change to these snapshot packages because we have a pretty wide dependency graph. 

So we are accessing _renv:::project$data()$Packages_ for getting information about packages recorded in renv.lock_, then we detect all snapshot versions and reinstalls them with _renv.install("xxxxxx@99.99.99.9000", rebuild = TRUE)_.

SO what I'd propose is to export _renv:::project_. Or is there any other safe alternative to get the information about dependencies other than using internal API or parsing the JSON lock file directly?

**Comment by hadley** [comment]
This sounds like it's out of scope for renv. You now might want to use the tools provided by pak to introspect the dependency graph of your package.
