### ISSUE TITLE
proposal: extend settings and allow additional libraries to be recorded

### ISSUE THREAD

**Issue by donarus** [rstudio/renv#679]
I would have another proposal for discussion

our example use case:

we have a custom library (custom tool, which helps us to manage our projects - for example, it contains some helper functions used during the build on our build server, or it contains some functions used to deploy to our custom and secured CRAN deployment)

We don't reference this library anywhere in the code, but we use it and we want it to be tracked using RENV.

One option would be to record the package in the "Suggests" section of DESCRIPTION, but we have a single-repo for multiple R packages managed as a single RENV project. For this reason, RENV is not scanning DESCRIPTION in these sub-folders, so this does not work.

What I'd propose for these custom scenarios is to add a configuration option in 
https://rstudio.github.io/renv/reference/settings.html

called additional.packages and every package mentioned here would be tracked by RENV.

What do you think abouyt this improvement?

**Comment by kevinushey** [comment]
Seems reasonable, but why not just add `library(<package>)` to some file explicitly, e.g. in a file `deps.R`?

**Comment by donarus** [comment]
I have another use case which leads to a slightly different (but tightly coupled) proposal

example project structure
```
├── project_A
│   ├── DESCRIPTION
│   ├── NAMESPACE
│   ├── R
│   └── tests
├── project_B
│   ├── DESCRIPTION
│   ├── NAMESPACE
│   ├── R
│   └── tests
├── renv
└── renv.lock
```

We use similar project structure - we have a single repository maintained by RENV but in this repository we have multiple packages. In this case, RENV is not scanning inner package's DESCRIPTION and NAMESPACE files when detecting dependencies, so we have to force RENV to store some dependencies like for example *foreach* (which is used by *plyr* when _parallel_ argument is set to TRUE)

we do this by adding a simple call ```requireNamespace("foreach", quietly = TRUE)``` to *.Rprofile* file in the root directory, but it means that we are somehow duplicating the reference to the dependency


so maybe instead of *additional.packages* it would be maybe better to add some option to enrich the function responsible for dependency resolution (like for example possibility to add custom headers *renv.download.headers*)

**Comment by hadley** [comment]
Closing since renv now has a standard place to put extra dependencies: `_dependencies.R`
