### ISSUE TITLE
snapshot not adding installed and used packages to lock file

### ISSUE THREAD

**Issue by gui-salome** [rstudio/renv#681]
I have been using `renv` for a while now without any issues, but today `renv::snapshot` simply stopped doing its job. I created a new project and used `renv::init(bare = TRUE)`, then restarted R and confirmed the bootstrapping of renv worked. Then, I installed Tidyverse with `renv::install("tidyverse")`. Next, I ran `renv::snapshot()`, but only `renv` itself was added to the lock file. 
I tried loading tidyverse before calling snapshot, but that did not change the outcome. I also checked `renv/library` and all of tidyverse is there. I also tried installing other packages with `renv::install`, but they would still not show up in the lock file after calling snapshot.

Any idea what's going on or how to fix it? Is there any other information I can provide to help with this?

Update: I am using renv version 0.13, but the problem was present in 0.12.2 too. I am using R 4.0.3 and my platform is x86_64-pc-linux-gnu.

**Comment by gui-salome** [comment]
Alright, I just figured out what was happening. It looks like `renv` goes through my .R files to determine what packages are used and then uses that information to take the snapshot. I added a dummy file with `library(tidyverse)` and called `renv::snapshot()` and the package was correctly added to the lock file.

**Comment by kevinushey** [comment]
That is correct -- please see https://rstudio.github.io/renv/articles/faq.html#why-isn-t-my-package-being-snapshotted-into-the-lockfile for more details.

**Comment by gui-salome** [comment]
Cool, thanks for the link @kevinushey!
