### ISSUE TITLE
ERROR 1: Parser error: did not find expected <document start>

### ISSUE THREAD

**Issue by Dee-L** [rstudio/renv#682]
I'm just getting started with `renv`.

I created a directory, created an R project in the folder via R Studio, then used `renv::init()`. At the end of my work session, after I'd installed a couple more packages, I used `renv::snapshot()` to capture the changes to the project libraries.

So far so good, I think.

Today, I opened the project, did some more work that included adding a new child directory in the project directory along with an R Markdown file. The R Markdown file was copied from a public source and is merely a reference for myself, but not code I've actually run.

At the end of my work session I tried to use `renv::snapshot()` to capture the changes to the project libraries again. I received then the following error:

```{r}
WARNING: One or more problems were discovered while enumerating dependencies.

[redacted path]/[my R project directory]/markdown/[myfile].rmd
-------------------------------------------------------------

ERROR 1: Parser error: did not find expected <document start> at line 2, column 1

Please see `?renv::dependencies` for more information.

Do you want to proceed? [y/N]:
```

Running `?renv::dependencies` takes me to the help documentation, but I don't really see how adding an R markdown file into a child directory in the project file should lead to any errors with `renv` identifying dependencies.

If I use `y` to proceed, then it apparently updates the lockfile without issue.

**Three quick questions**

1. What is causing the error message?
2. Should I care?
3. Do you have suggestions to improve my workflow with `renv`?

Thank you!

**Comment by kevinushey** [comment]
This appears to be a bug in `renv`. Any chance you could share the `.Rmd` document where you saw this error?

**Comment by Dee-L** [comment]
I've modified the file so that it is rather minimal, but the error persists.

Github will not allow me to upload a .rmd, so I just changed the extension to .txt prior to uploading.
[m02_demo.txt](https://github.com/rstudio/renv/files/6166353/m02_demo.txt)

**Comment by kevinushey** [comment]
Thanks! I think the problem here is that the first entry in the YAML header is indented. Removing that indent will fix the issue; e.g.

`````
---
title: "Doc title"
description: >
    Description of document.
---
    
```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(error = TRUE)
```

`````

**Comment by Dee-L** [comment]
Great! Thanks for the tip!

I cleaned up these erroneous whitespaces, and now the document renders with ` rmarkdown::render()` and the error message from ` renv::snapshot()` has gone away.

I appreciate your help!
