### ISSUE TITLE
Managing `renv.lock` for Github Actions when installing packages from internal RStudio Package Manager

### ISSUE THREAD

**Issue by dwhdai** [rstudio/renv#683]
In our Github Actions, we use `renv::restore()` to restore and cache the package dependencies. When installing and snapshotting packages installed from an internal RStudio Package Manager (inaccessible on Github), what is the best way to manage the `renv.lock` file so that the same package dependencies can be installed from a secondary source/repository?

As an example, this following script modifies the `renv.lock` to install internal packages from Github instead of RSPM. Are there issues with this approach, or is there a better way to handling this?

```library(rjson)
internals <- c("package1","package2")
lockfile <- rjson::fromJSON(file = "renv.lock")
packages <- lockfile$Packages
lockfile$Packages <- packages[!(names(packages) %in% internals)]
fileConn<-file("renv.scrubbed.lock")
writeLines(rjson::toJSON(lockfile), fileConn)
close(fileConn)
for(package in internals){
    devtools::install_github(paste0("LKS-CHART/",package))
}
renv::restore(lockfile = "renv.scrubbed.lock")
```

Thank you!

**Comment by kevinushey** [comment]
That seems fine to me. Ultimately, the lockfile is just JSON and you're free to mutate it as appropriate.

The other approach would be to use something like:

```
renv::restore(packages = <packages>)
```

and explicitly set which packages you want to restore from the lockfile.
