### ISSUE TITLE
dependencies() should understand use()

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#686]
And consider the implications for deployment (i.e. does rsconnect/packrat need this too)

**Comment by kevinushey** [comment]
FWIW `use()` is normally used for file-specific dependencies, so I don't think we'd want them to enter the lockfile for a general `snapshot()` call in an `renv` project. Whether or not we include `use()` statements would probably depend on the type of deployed application (e.g. if you're deploying an R Markdown document you probably want it)

**Comment by hadley** [comment]
Right, so `dependencies()` might need an option to recognise them? (That would be off by default but on for deployment?)
