### ISSUE TITLE
renv::use() should only temporarily change the libpath

### ISSUE THREAD

**Issue by hadley** [rstudio/renv#688]
So that you won't be confused if you do `install.packages()` after using `renv::use()`.

**Comment by kevinushey** [comment]
One downside: calls to `library()` will fail if the requested package is not on the library paths, even (somewhat frustratingly) if that package's namespace is already loaded. Spitballing some potential solutions:

1. Shim the `library()` and `require()` functions, to also look in the 'use' library path as well. I don't love that idea.
1. Place a temporary 'staging' library path in front of the 'use' library path, and register a callback that moves packages installed into that directory to the "true" library path. This is fiddly, but feels okay.
1. Send a patch to R, allowing `library()` to attach an already-loaded package if possible.
1. Have `renv::install()` and friends be smart enough to install into the "true" library as opposed to the temporary use library path.
1. Just document the current behavior and let users know that installing packages while `use()` is active will install packages into that library path.

**Comment by hadley** [comment]
The other option is to shim `install.packages()` to default to using the actual libpath. Or to just warn that it's going to an unexpected location. Would pair well with option 5.

**Comment by hadley** [comment]
Given that `renv::use()` is supposed to be document oriented, I no longer think that this is useful.
