### ISSUE TITLE
use() should use named arguments for packages

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#689]
Otherwise, it can be challenging to find the packages by name when mixing CRAN packages with development dependencies; e.g.

```
  "tidyselect@1.1.0",
  "tidyverse/dplyr",
  "tinytex@0.30",
```

**Comment by hadley** [comment]
Something like this?

```R
use(
  tidyselect = "tidyselect@1.1.0",
  dplyr = "tidyverse/dplyr",
  tinytex = "tinytex@0.30"
)
```

**Comment by kevinushey** [comment]
@hadley I like that. The downside is that `renv::use()` currently takes both `...` and not-dot-prefixed arguments, so there's theoretically some risk of collisions there.

**Comment by hadley** [comment]
Hmmm, that makes me unclear about what you want to do with the names. I was thinking that they'd just be ignored, making them useful for humans only (i.e. to make it easier to scan the calls generated by `embed()`).

**Comment by kevinushey** [comment]
That's what I was thinking as well. I think my only concern was the fact that we'd (in theory) have calls like:

```
renv::use(
  tidyselect = "tidyselect",
  sandbox = TRUE
)
```

But that's probably fine, except for the poor souls who want to use the [sandbox](https://cran.r-project.org/web/packages/sandbox/index.html) package?

```
renv::use(
  packages = list(
    tidyselect = "tidyselect"
  ),
  sandbox = TRUE
)
```

**Comment by kevinushey** [comment]
We could even support both, and use:

```
renv::use(
  tidyselect = "tidyselect",
  sandbox = TRUE
)
```

by default, but make the `packages` argument available for easier programmatic use if someone needs it. I think `renv::install()` does something similar.

**Comment by r2evans** [comment]
I realize this was marked as resolved some time ago, but would it not make sense for the named arguments after `...` to be prepended by a dot?

```r
renv::use(
  tidyselect = "tidyselect",
  .sandbox = TRUE
)
```

It wouldn't be too difficult within lifecycle management to still find the non-dotted argument names within `...`.
