### ISSUE TITLE
renv to install libraries globally

### ISSUE THREAD

**Issue by michaelhogersosis** [rstudio/renv#69]
Hi there,

Once again, thanks for this wonderful package. I was wondering whether it is possible to use a generated lockfile to install libraries globally? Instead of saving libraries on a project level in the renv folder. This would be great to have, as it would be possible to generate the lockfile periodically in a project and then use this lockfile to update global packages on a base docker image. Example Dockerfile is shown below.

```
FROM image-based-on-lockfile-renv
COPY . .
RUN rm -rf .Rdata || true
EXPOSE 3838
CMD ["R", "-e", "source('run.R')"]
```

Best regards,

Michael

**Comment by kevinushey** [comment]
Something like the following should work:

```
renv::restore(
    lockfile = "<path/to/renv.lock>",
    library = "<path/to/requested/library>",
    actions = c("install", "upgrade")
)
```

**Comment by michaelhogersosis** [comment]
Thanks @kevinushey, that would work fine.

**Comment by combiz** [comment]
Would be useful to include this snippet in the docs!

**Comment by combiz** [comment]
Would be useful to include this snippet in the docs.  Installing packages in the global library seems to make sense for a Docker image used across different projects.  Thanks for the excellent work on renv!

**Comment by kevinushey** [comment]
There's some documentation on using `renv` with Docker here:

https://rstudio.github.io/renv/articles/docker.html

Let me know if you think something there could be extended.

**Comment by GitHunter0** [comment]
> 
> 
> Would be useful to include this snippet in the docs. Installing packages in the global library seems to make sense for a Docker image used across different projects. Thanks for the excellent work on renv!

Yes, that was exactly what I was thinking. This is an important feature that probably should be highlighted.
