### ISSUE TITLE
The .Rprofile generated by renv shadows user .Rprofiles

### ISSUE THREAD

**Issue by Kodiologist** [rstudio/renv#692]
R only looks for one .Rprofile, so if you like to use a single .Rprofile for all your projects, the renv-generated one will prevent it from being loaded.

My workaround has been to delete the generated .Rprofile and add `source("renv/activate.R")` to my code.

**Comment by kevinushey** [comment]
This is documented in `?renv::config`:

>      *'renv.config.user.profile'* Load the user R profile (typically
>           located at ~/.Rprofile) when 'renv' is loaded? Consider
>           disabling this if you require extra encapsulation in your
>           projects; e.g. if your '.Rprofile' attempts to load packages
>           that you might not install in your projects. Defaults to
>           'FALSE'.

So you might want to set `RENV_CONFIG_USER_PROFILE = TRUE` in your `.Renviron` or similar.

**Comment by Kodiologist** [comment]
Thanks for the tip. I had seen the page for `settings` but didn't realize there was a `config` one, too.
