### ISSUE TITLE
Bootstrapping renv downloads binary of 0.12.5 on windows  altough 0.13.1 is required

### ISSUE THREAD

**Issue by schrnstn** [rstudio/renv#695]
There is a buggy behaviour due to the missing windows binaries on CRAN.
We require renv version `0.13.1` in our lockfile in some project. When cloning a fresh version of the project from git, the renv bootstrapping mechanism on first start of R on **windows** however downloads the `0.12.5` windows binary. This one we cannot use, since it has the bugs in it which were solved in prior issues.
Possible solutions could be to make CRAN publish a windows binary and/or fix the download bug.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I'll try to get this fixed up soon. Hopefully, CRAN should be publishing a new binary of renv soon as well.
