### ISSUE TITLE
Unable to find catboost repository

### ISSUE THREAD

**Issue by AdrianAntico** [rstudio/renv#703]
This is likely a broader issue beyond catboost. After running renv::snapshot() all packages were found except catboost. Could it be due to the R version of catboost being nested several layers inside the main github repository?

**Comment by kevinushey** [comment]
Can you please provide extra context / a reproducible example so I can better understand the issue?

**Comment by AdrianAntico** [comment]
When I run renv::snapshot() on my local machine there is no issue. However, when running it on a windows server, I get the following message:

```
"The following package(s) were installed from an unknown source:

  catboost [0.25.1]

renv may be unable to restore these packages in the future.
Consider re-installing these packages from a known source (e.g. CRAN)"
```

However, when I run renv::snapshot() on my local machine, there isn't such a warning. I receive the standard printout for CRAN packages, but for catboost it's printed out as such:

```
# URL =========================
- catboost             [* -> 0.25.1]
``` 

I should note that I install catboost in different ways for each machine. For my local machine, I use:
```
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.25.1/catboost-R-Windows-0.25.1.tgz', INSTALL_opts = c("--no-multiarch"))
```

whereas for the windows server, I have to use:
```
install.packages("https://github.com/catboost/catboost/releases/download/v0.25.1/catboost-R-Windows-0.25.1.tgz", repos = NULL, type = "source", INSTALL_opts = c("--no-multiarch", "--no-test-load"))
```

**Comment by AdrianAntico** [comment]
@kevinushey Just checking in on this issue...

**Comment by kevinushey** [comment]
This is hard, because catboost is "weird" compared to any typical R package. If we want to support catboost, we basically have to implement some custom restore code specifically for this package, which is a bit frustrating.

**Comment by AdrianAntico** [comment]
@kevinushey Would there are also be issues with installing GPU versions of packages such as xgboost and lightgbm?

Also, Renv does work with catboost but only if installed using the devtools::install_url() method but not the method install.packages("https://github.com/catboost/catboost/releases/download/v0.25.1/catboost-R-Windows-0.25.1.tgz", repos = NULL, type = "source", INSTALL_opts = c("--no-multiarch", "--no-test-load"))

With a particular set of windows servers I'm running I have to install catboost with the install.packages("https://...") method. I haven't looked into the source code of how Renv works but there be a way to check if a URL is provided to install.packages first before running the remaining code and in the case of a URL, save that URL path to the Renv object?

**Comment by hadley** [comment]
It looks like catboost uses it's own unique system of making an R package; I think a better path forward would be to encourage the developers to use something more standard. This is pretty easy these days with the advent of https://r-universe.dev/
