### ISSUE TITLE
Would be nice if renv mentioned which file tripped it up

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/renv#71]
The traceback is nice, but won't help me find the file with the wrong YAML in a big directory with many files.

> renv::init()
> * Discovering package dependencies ... Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Parser error: did not find expected <document start> at line 3, column 1
Traceback (most recent calls first):

**Comment by rubenarslan** [comment]
Cheers!

**Comment by kevinushey** [comment]
Thanks!
