### ISSUE TITLE
Set `renv::settings$snapshot.type()` with env var or `options()`

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#710]
Hi Hi!

Is there a way to set `renv::settings$snapshot.type("all")` option globally? I didn't see it  in the configuration help file https://rstudio.github.io/renv/reference/config.html

It would be great to be able to set this once and forget for my team.

Thank you!

**Comment by kevinushey** [comment]
I think you're looking for the documentation at https://rstudio.github.io/renv/reference/settings.html#defaults.

Note that these settings don't override already-set project options for existing projects; they just effect the defaults for new projects. Is that the behavior you're looking for?

**Comment by ddsjoberg** [comment]
That is perfect! Thank you so much, and apologies for not seeing it!
