### ISSUE TITLE
Custom Pkg Management + Remote Servers

### ISSUE THREAD

**Issue by sethneel** [rstudio/renv#711]
I am in the setting where I have a custom R package that is used in dozens of repos, on dozens of remote machines. I am using .Renv because when I upgrade a package or install a new package from CRAN to one of these repos on my local, I want to be able to push a new lock file, and have it be used in all the repos. However, with my own package, I would like to be able to deploy a small change (say I update the NAMESPACE file) without having to go through the following process: 

1. Cut a new release of the package
2. devtools::install_github(package_name, ref = packageversion)
3. renv::snapshot() 
4. commit and push the lockfile to the new repos

Ideally I would push my new package to master branch, and when I renv::restore() on a remote server it would realize that the package hash has changed, and it would re install / build the package from the master branch in the github repo. However, this is not the case. Is it possible to force this behavior?

**Comment by hadley** [comment]
You can do cut a couple of setup by doing just `renv::install("package_name@packagevesrion"); renv::snasphot()`. Let us know if that's not a good fit for your problem and we can re-open.
