### ISSUE TITLE
Restore renv without installing dependencies.

### ISSUE THREAD

**Issue by JacobBas** [rstudio/renv#712]
Hi,

I have a current large project that uses many different packages that I want to be able to restore without installing any dependencies since these will be installed in a more centralized repository.

Is there a way to implement `renv::restore(dependencies=FALSE)` similar to the way that you are able to call `renv::install('package', dependencies=FALSE)`.

Currently I have a separate script which calls `renv::install(package_list, dependencies=FALSE)` on a list of packages, but this prohibits me from being able to restore from the `renv.lock` file.

Thanks.

**Comment by hadley** [comment]
The lockfile doesn't have a notion of dependencies (it records the full tree of all packages), so unfortunately there's no way to implement this.
