### ISSUE TITLE
RStudio Packages tab not updated

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/renv#72]
When installing a package, the Packages tab is not updated to contain the new package and package version until the R session is restarted.

**Comment by slopp** [comment]
Do you see this same behavior installing packages outside of renv?

**Comment by kevinushey** [comment]
I believe this is because RStudio overrides `install.packages()` and attaches a bunch of hooks + behaviors that only get called when the RStudio shim of `install.packages()` is used. We'll have to teach `renv` how to use those notification hooks as well.

**Comment by mac-pfa** [comment]
@slopp no, outside renv the Packages tab refreshes upon completion.

**Comment by kevinushey** [comment]
This should be fixed now.
