### ISSUE TITLE
Custom package loader

### ISSUE THREAD

**Issue by ATpoint** [rstudio/renv#720]
I usually load packages in the following way:

```
pkgs <- c("SingleCellExperiment", "parallel", "DESeq2", "diffanalyseR", "vizzy", "scuttle",
          "CreateGeneSignatures", "scater", "egg", "BiocParallel", "scran", "dplyr", "PCAtools",
          "ComplexHeatmap")

invisible(lapply(pkgs, function(x) suppressPackageStartupMessages(library(x, character.only = TRUE))))

```

which according to the FAQs is not being recognized by renv. Is there something one could do about it? The simplest would be that renv scans for certain (e.g. user-defined) variables in the code that contain the package names.
Say something like `renv::scan_variables(c("pkgs", "my_packages"))`, and then checks for these variables. Would that be possible?

**Comment by kevinushey** [comment]
It would be possible, but it's honestly not a change I want to make in `renv` (one can imagine some users might use those variables for things that aren't R packages, or for R packages that they don't actually intend to load).

Sorry -- I'd recommend just using `library()` in your sources.
