### ISSUE TITLE
Package detection in eval=FALSE Rmd chunks

### ISSUE THREAD

**Issue by ATpoint** [rstudio/renv#722]
I noted that Rmd chunks with `{r, eval=FALSE}` are currently not used for package detection, and I could not find a workaround other than setting eval to TRUE. Any option I can set here to check those chunks regardless of eval?

**Comment by ATpoint** [comment]
@kevinushey 
I think it's this one here, https://github.com/rstudio/renv/blob/master/R/dependencies.R#L622 , could you make this an option for the user to switch on/off?

**Comment by kevinushey** [comment]
In the development version of `renv`, you'll now be able to do something like:

`````
```{r, eval=F, renv.ignore=F}
# this code will be parsed for dependencies
```
`````

Will that be sufficient?

**Comment by ATpoint** [comment]
Yes, for my purpose that will do, many thanks. Is it possible to somehow make this a global option that I can execute once with all Rmds of that project being changed then? For now I will just add it manually to each chunk, but I think in general a global option would be preferrable. At best something within renv::init() or renv::snapshot().
