### ISSUE TITLE
DESCRIPTION of base packages missing

### ISSUE THREAD

**Issue by DavZim** [rstudio/renv#723]
I run `renv` Version 0.13.2 on a Windows machine with R version 4.0.5 and RStudio 1.4.1103.
Usually everything works as expected, but every couple of days, R's core packages go missing, similarly to #361.
The error I get is this

```r
renv::status()
#> The following package(s) are missing their DESCRIPTION files:
#> 
#> 	boot       [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/boot]
#> 	class      [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/class]
#> 	cluster    [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/cluster]
#> 	codetools  [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/codetools]
#> 	foreign    [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/foreign]
#> 	KernSmooth [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/KernSmooth]
#> 	lattice    [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/lattice]
#> 	MASS       [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/MASS]
#> 	Matrix     [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/Matrix]
#> 	mgcv       [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/mgcv]
#> 	nlme       [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/nlme]
#> 	nnet       [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/nnet]
#> 	rpart      [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/rpart]
#> 	spatial    [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/spatial]
#> 	survival   [C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/survival]
#> 
#> These may be left over from a prior, failed installation attempt.
#> Consider removing or re-installing these packages.
```

Following #248, I also got this output:
```r
libpaths <- .libPaths()
boot <- file.path(libpaths, "boot")
desc <- file.path(boot, "DESCRIPTION")

sapply(boot, file.exists)
#> C:/Users/davzim/Documents/projects/the-project/renv/library/R-4.0/x86_64-w64-mingw32/boot 
#> FALSE 
#> C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/boot 
#> TRUE 

sapply(desc, file.exists)
#> C:/Users/davzim/Documents/projects/the-project/renv/library/R-4.0/x86_64-w64-mingw32/boot/DESCRIPTION 
#> FALSE 
#> C:/Users/davzim/AppData/Local/Temp/RtmpCcv5ct/renv-system-library/boot/DESCRIPTION 
#> FALSE 
```

The project renv library contains all installed packages, but the base packages are dropped. Similarly, the Temp folders are all empty.

If I open another R session (for example from the terminal, the R GUI, or another RStudio Session outside of the renv project), I get the error "fatal error, cannot open base package".

I suspect it has something to do with Windows cleaning up the Temp folders (could be also some other tool on the machine, note this happens on a work machine so I do not have full controll of the machine) and `renv` sanboxing the packages to these folders.

The "solution" was to reinstall R, then it would work again. I will use `RENV_CONFIG_SANDBOX_ENABLED = FALSE` for now, but would prefer if sandboxing would be enabled and the base packages be installed to a different folder.

**Comment by kevinushey** [comment]
Do you have some kind of application or software that is trying to periodically delete things in the Windows temporary directory?

**Comment by DavZim** [comment]
I have checked with IT and they said that we don't have any software that does that. I'll investigate further and report back if I found anything.
Just for my understanding, the base-packages are not copied to the Temp folder but are shortcuts/symlinks correct?

Otherwise, because I haven't said it before: Thank you for developing renv, really makes life easier (even with the issue I curently face :) )

**Comment by kevinushey** [comment]
> Otherwise, because I haven't said it before: Thank you for developing renv, really makes life easier (even with the issue I curently face :) )

Thank you for the kind words!

For what it's worth, an escape hatch here is to tell `renv` to disable the sandbox. You can do so with the following R code:

```
cat("RENV_CONFIG_SANDBOX_ENABLED = FALSE", file = "~/.Renviron", sep = "\n", append = TRUE)
```

That will ensure that `renv` avoids trying to sandbox the system library in the temporary directory, which should hopefully help ensure this doesn't happen again.
