### ISSUE TITLE
Handle exit during selection in use_python()

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#725]
Currently, if one exists properly from `select.list` used in `renv::use_python()`, it is not handle nicely and thow an error because the result is still being handled.

````r
> renv::use_python()
Please select a version of Python to use with this project: 

: 

Selection: a
Enter an item from the menu, or 0 to exit
Selection: 0
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="": La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte
Run `rlang::last_error()` to see where the error occurred.
````

I believe this could be improve by stopping early the processing in `use_python()` with a nicer message if `utils::select.list` return `""` (cancelled or 0 entered) in `renv_python_select()`. Currently this empty path is passed in `path_expand()`

https://github.com/rstudio/renv/blob/ffe5790161fed81226577a31231299e2be2c36ba/R/python.R#L331-L346

NOTE: In the example above I get no choice but this is for another issue. 😅

**Comment by kevinushey** [comment]
Thanks! This should be handled a little better on master now.
