### ISSUE TITLE
snapshot() option to **not** remove packages from lockfile

### ISSUE THREAD

**Issue by mmuurr** [rstudio/renv#727]
It's fairly common for me to include a package in a project, then remove some code that uses it (perhaps while experimenting a bit) and install other packages in the meantime. When taking an `snapshot()` to capture those newer packages, renv wants to _remove_ the no-longer-referenced original package. I can't find an option to `snapshot()` while protecting against deletions from the lockfile. (`type = "all"` doesn't exactly cover it, either, as it'll often add much more to the lockfile than is actually needed.)

Perhaps an additional control to snapshot to selectively list the packages to edit (where edit is insert, delete, or update)? The existing `packages=my_pkgs` argument doesn't quite cut it, either, as that'll lead to a removal of any existing lockfile entry that's **not** in `my_pkgs`.

Perhaps there's already a workflow for this (adding or updating packages selectively) of which I'm just ignorant?

**Comment by kevinushey** [comment]
You can selectively add a package via `renv::record()`, using the desired package and version; e.g.

```
renv::record("package@version")
```

However, you do have to explicitly specify the version -- otherwise, the latest version available from your declared R package repositories will be used, which might not match what you currently have in the library.

**Comment by mmuurr** [comment]
Ah, got it. I suppose this works to version-match the currently-installed version?:
```r
renv::record(sprintf("pkg@%s", packageVersion("pkg")))
```

**Comment by kevinushey** [comment]
That won't quite work, because `packageVersion()` converts "delimiters" to `.`s, e.g. compare:

```
> packageVersion("renv")
[1] '0.13.2.19'
> packageDescription("renv", fields = "Version")
[1] "0.13.2-19"
```

So I'd recommend the second form.

**Comment by kevinushey** [comment]
Seems like it would be useful in `renv` to make this easier; e.g. something like:

```
renv::record("package@*installed")
```

That is, some special syntax to say "use the version of the package that is currently installed". Will have to think a bit more about what the right form is...

**Comment by mmuurr** [comment]
Got it (I wasn't aware `packageVersion` munged the `-` separator!) ; thanks!

And yeah, some 'magic' versions, like "installed" and/or "latest" (i.e. the default now) would be neat.
(Does the `*` even need to be there, assuming all valid package versions start with an integer?)
I'd be happy to spin up a small PR to add that if you want (would just pass the package list through a regex replacer).

**Comment by kevinushey** [comment]
I'd like to think about this a little bit more, just to make sure that whatever we choose is consistent / compatible with what [remotes](https://github.com/r-lib/remotes) does (if anything). Or, at least make sure we can agree on a common syntax.

**Comment by mmuurr** [comment]
Polite bump to see if any more thought's been put into this. A colleague of mine just had the same question, effectively: "How do I add a package via `renv::snapshot()` without it trying to remove records from `renv.lock`?"). I gave her the `record()` solution, but I think both the:
* `"<pkgname>@<version>"` `"installed" shorthand for version (with the potential default behavior of just the currently-installed version when the `@<version>` is missing)
* possibility of a "write-only" optional flag added to `snapshot()` would both be welcomed.

As for a use case (on why to include packages in `renv.lock` that are not referenced in the project's code): consider R projects where the existing code does **not** include library {x}, but the expected interactive sessions will likely make use of {x}, and the author of the project would like to enforce (or minimally, hint-at) a version of {x}.

**Comment by kevinushey** [comment]
Thanks for the bump. I've now added `snapshot(update = TRUE)`, to allow records from a previously-existing lockfile to be preserved when calling `renv::snapshot()`. Effectively, only packages whose records have changed, or newly-installed packages, will change in the lockfile.
