### ISSUE TITLE
getting pre-flight validation failure while trying to publish app to rstudio-connect

### ISSUE THREAD

**Issue by ankitsoni16** [rstudio/renv#729]
I am getting following error while publishing the app on server, however I am able to run the app locally:

![image](https://user-images.githubusercontent.com/78069046/115671229-ebebf300-a367-11eb-8db5-631c644d7e41.png)

I am using renv for the first time and would really appreciate help.

Thanks

**Comment by kevinushey** [comment]
If I understand correctly, this appears to be a Packrat / RStudio Connect issue as opposed to an `renv` issue. If you're using RStudio Connect, you should be able to contact RStudio support at support@rstudio.com.

Let me know if I'm misunderstanding anything.

**Comment by ankitsoni16** [comment]
Thanks Kevin.

I was using renv::init from within the app.R code.

Running it outside resolved the issue.
