### ISSUE TITLE
testing installed package

### ISSUE THREAD

**Issue by reikoch** [rstudio/renv#730]
In R 4.0.3 on Macos 11.2.3  and renv 0.13.2 installed with tests
`tools::testInstalledPackage('renv', types = 'tests')`
skips all tests, see 
[testthat.Rout.txt](https://github.com/rstudio/renv/files/6356636/testthat.Rout.txt).

Can the tests be executed on the installed renv package?

**Comment by kevinushey** [comment]
Strange; I'm not able to reproduce. The tests run fine locally on my machine.

`renv` uses the `testthat` package for tests; perhaps the version of `testthat` you're using is too old? I've only ever tested with the latest release of testthat.

**Comment by reikoch** [comment]
Am using testthat 3.0.2. Just upgraded to R 4.0.5 and updated all packages to today's (2021-04-23) state.
Still all renv tests are skipped. Is there a good way to trace testthat's processing?

**Comment by reikoch** [comment]
There is very Mac and user specific code in renv/tests/testthat/helper-aaa.R:
```
test_that <- function(desc, code) {

  iscran <-
    !identical(Sys.getenv("NOT_CRAN"), "true") &&
    !identical(Sys.getenv("USER"), "kevinushey") &&
    !identical(Sys.getenv("USER"), "kevin")

  testthat::skip_if(iscran && renv_platform_macos())
...
```
So setting environment variable NOT_CRAN to "true" let me enter the test suite of renv. 
Now on brand new R 4.1.0 I got
```
[ FAIL 2 | WARN 0 | SKIP 23 | PASS 591 ]
Error: Test failures
```
the two failures are about packrat 0.6.0 where sources are not found.

**Question:**  
Can the Mac and CRAN specific criterium be modified to have testing capabilities also for users not named "kevin" or "kevinushey"?

**Comment by kevinushey** [comment]
Thanks for spotting that. I've removed the user-specific code check there.

That said, the NOT_CRAN environment variable check is unfortunately the best way I know of to check and prevent certain tests from being run on CRAN, that I'd prefer not to run there.

Do you have an alternate way to declare that `renv` should run tests here, in a way that would still allow me to shield these tests from running on CRAN's macOS builder?

**Comment by reikoch** [comment]
True, I know nothing better than the NOT_CRAN env variable. I wonder whether that should get automatically set to TRUE in tools::testInstalledPackage(), but that is another story.
