### ISSUE TITLE
Spaces in path to project folder

### ISSUE THREAD

**Issue by hkaspersen** [rstudio/renv#731]
I am having an issue with `renv::init()` when i use it in my R project folder location. Because of my organizations data setup, the folders where my project is has a path that contains spaces and/or special characters (æ,ø,å) in certain folder names. Therefore, when running `renv::init()`, i get the following error message:
```
Error opening project. 
Project '<path>/test/test.Rproj' does not exist (it has been moved or deleted), or it is not writeable.
```

Is there any way to change the path handling in `renv` to escape such characters? Everything works fine when I run it in a location with no spaces or special characters in the path.

Output from `sessionInfo()`
```
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Norwegian Bokmål_Norway.1252  LC_CTYPE=Norwegian Bokmål_Norway.1252   
[3] LC_MONETARY=Norwegian Bokmål_Norway.1252 LC_NUMERIC=C                            
[5] LC_TIME=Norwegian Bokmål_Norway.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5    renv_0.13.2-21
```

**Comment by kevinushey** [comment]
Hmm, that error is actually printed by RStudio, not `renv`. So the issue you're seeing might be either an RStudio-specific issue, or some kind of strange interaction between RStudio and `renv`.

What version of RStudio are you using?

**Comment by hkaspersen** [comment]
I am currently using RStudio version 1.2.5042

**Comment by hkaspersen** [comment]
I also noticed that some packages, like "ape" fails to install with this error:
```
make: "C:/Users/username/OneDrive - VeterinÃ¦rinstituttet/Dokumenter/.R/Makevars": No such file or directory
make: *** No rule to make target '"C:/Users/username/OneDrive - VeterinÃ¦rinstituttet/Dokumenter/.R/Makevars"'.  Stop
```
Is this also due to the spaces/special characters in the path?

**Comment by kevinushey** [comment]
That would be my first guess. You could confirm by checking whether installation succeeds if run in a project outside of your OneDrive folder (with no spaces).

Alternatively, it might be worth trying to create a Windows junction point (shortcut) to that directory, with the path for that shortcut containing no non-ASCII characters. From R on Windows, you can use the `Sys.junction()` function to create such junction points.
