### ISSUE TITLE
Askpass does not exist in renv cache

### ISSUE THREAD

**Issue by Nitinws** [rstudio/renv#732]
I am getting following error while publishing the app on server, however I am able to run the app locally:

2021/04/22 10:47:20.858373862 Error in value[[3L]](cond) : 
2021/04/22 10:47:20.858396626   source file '/opt/rstudio-connect/mnt/tmp/.local/share/renv/cache/v5/R-3.6/x86_64-pc-linux-gnu/askpass/1.1/e8a22846fff485f0be3770c2da758713/askpass' does not exist
2021/04/22 10:47:20.858431857 Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
2021/04/22 10:47:20.858432998 Execution halted
2021/04/22 10:47:20.866912099 * Copying packages into the private library ... 

Really appreciate help.

Thanks

**Comment by kevinushey** [comment]
This appears to be a Packrat / RStudio Connect issue, not an renv issue? If you're using RStudio Connect, you should contact support at support@rstudio.com.
