### ISSUE TITLE
renv::restore() does not install packages under Windows

### ISSUE THREAD

**Issue by ccamara** [rstudio/renv#735]
Whenever I want to recreate a project on my windows machine using `renv:restore()` it always fails installing packages. I always get the same error (although the packages may change):

```
Retrieving 'https://cloud.r-project.org/src/contrib/Archive/xfun/xfun_0.21.tar.gz' ...
Error: failed to retrieve package 'xfun'
In addition: Warning messages:
1: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate. 
2: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate. 
3: download failed [error code 35] 
4: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate. 
5: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate. 
```

This is my session info:

```R
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5    renv_0.12.0   
```

And this might also be useful: 

```
> getOption("download.file.method")
[1] "wininet"
> renv:::renv_download_file_method()
[1] "curl"
>
```

After running: `Sys.setenv(RENV_DOWNLOAD_METHOD = "curl")` (or` wininet` or `libcurl`) I always get the same error as before.

As a workaround I did the following:

1.  Close the project
2.  Install package as normal (without renv)
3.  Open the project using renv
4.  Restore snapshot

If the packages have previously been installed, they will be symlinked and they would work.

Unfortunately, this is extremely cumbersome, as many packages have dependencies and I have to manually install them all, and that's precisely one of the things I want to avoid and one of the reasons for using renv!

**Comment by kevinushey** [comment]
> loaded via a namespace (and not attached):
> [1] compiler_4.0.5 tools_4.0.5    renv_0.12.0   

You're using an older version of `renv` -- please update.

For older versions of `renv`, the environment variable to set is `RENV_DOWNLOAD_FILE_METHOD`, not `RENV_DOWNLOAD_METHOD`.

**Comment by ccamara** [comment]
Thank you, @kevinushey !

After updating to `renv` v. 0.13.2 I could not install packages, although the error was slightly different:

> renv::restore()
> [...]
> Error: failed to retrieve package 'xfun'
> In addition: Warning messages:
> 1: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate. 
> 2: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate. 
> 3: failed to retrieve 'https://rstudio-buildtools.s3.amazonaws.com/renv/mran/packages.rds' [error code 35] 
> 4: internal error: unexpected status code 'structure(list(message = "failed to retrieve 'https://rstudio-buildtools.s3.amazonaws.com/renv/mran/packages.rds' [error code 35]", call = NULL, traceback = c("Traceback (most recent calls last):", "32: renv::restore()", "31: renv_restore_run_actions(project, diff, current, lockfile, rebuild)", "30: renv_retrieve(packages)", "29: handler(package, renv_retrieve_impl(package))", "28: renv_retrieve_impl(package)", "27: renv_retrieve_successful(record, path)", "26: renv_retrieve(package)", "25: handler(package, renv_retrieve_impl(package))",  "24: renv_retrieve_impl(package)", "23: renv_retrieve_successful(record, path)", "22: renv_retrieve(package)", "21: handler(package, renv_retrieve_impl(package))", "20: renv_retrieve_impl(package)", "19: renv_retrieve_successful(record, path)", "18: renv_retrieve(package)", "17: handler(package, renv_retrieve_impl(package))", "16: renv_retrieve_impl(package)", "15: renv_retrieve_repos(record)", "14: catch(withCa [... truncated] 

however, after running `Sys.setenv(RENV_DOWNLOAD_METHOD = "wininet")` it worked fine.

**Comment by kevinushey** [comment]
Thanks! In that case, I'd recommend setting that environment variable by default; e.g. in your `~/.Renviron` file. Please see `?Startup` for more details.

**Comment by brianmsm** [comment]
Same issue here. Run `Sys.setenv(RENV_DOWNLOAD_METHOD = "libcurl")` fix the problem in my case.
