### ISSUE TITLE
renv::clean() issue? All non-base packages now missing in all non-renv projects

### ISSUE THREAD

**Issue by grasshoppermouse** [rstudio/renv#737]
Outside of my renv projects, all my non-base packages are gone. I'm not 100% sure this is a renv issue, but I think it was caused by a call to renv::clean(). I called this function [with no args] within a renv project because the source of a package installed from GitHub was incorrectly listed in the lock file as unknown, and a quick google suggested that this could be due to stale lock files. I would have assumed that renv::clean would only affect the project-specific libraries, and not my global library.

**Comment by kevinushey** [comment]
What is the output of `.libPaths()` for you in a clean (non-renv) R session?

**Comment by grasshoppermouse** [comment]
"/Library/Frameworks/R.framework/Versions/4.0/Resources/library"

**Comment by kevinushey** [comment]
Thanks -- I think this is indeed a bug (or at least, unintended behavior) in `renv::clean()`.

Normally, on macOS, user-installed packages should be installed into the user library; e.g. in my case I have:

```
> .libPaths()
[1] "/Users/kevinushey/Library/R/4.0/library"                       
[2] "/Library/Frameworks/R.framework/Versions/4.0/Resources/library"
```

The first of those being the "user" library path; the last being the "system" library path.

Under that assumption, `renv::clean()` tries to find and remove user-installed packages from the "system" library path, with the intention that this would help improve sandboxing for cases where the "explicit" renv sandbox cannot be used. For example:

```
> renv::install("digest", library = .Library)
Installing digest [0.6.27] ...
	OK [copied cache]
> renv::clean()
* No stale package locks were found.
* No temporary directories were found in the project library.
The following non-system packages are installed in the system library:

	digest, renv

Normally, only packages distributed with R should be installed in the system library.
These packages will be removed.
If necessary, consider re-installing these packages in your site library.
```

However, if the user does not actually have a user library and all packages are installed into the system library, then this action is too destructive.

I think I'll disable this for the default "clean" implementation as normally users (especially on macOS) shouldn't have any trouble relying on `renv`'s sandboxing mechanism.

**Comment by hadley** [comment]
@kevinushey did you disable this?

**Comment by kevinushey** [comment]
Not yet, it looks like.

**Comment by hadley** [comment]
I think you did? https://github.com/rstudio/renv/blob/main/R/clean.R#L110-L111. At least it now requires explicit opt-in.
