### ISSUE TITLE
Licensing of renv-generated infra files

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/renv#738]
I contributed R as a language to https://pre-commit.com, and we are [improving it currently](https://github.com/pre-commit/pre-commit/pull/1841) so that infrastructure generated with `renv::init()` is distributed as part of pre-commit (which is MIT licenced like renv) in certain cases and used in tests. That raises the question of the license of these files. The same question arises in any project that uses {renv} and contains artefact files such as `renv/activate.R` and friends that is public (at least I think it does). To be on the safe side here, we decided to come here and ask if it's possible to include these files in the distribution of pre-commit and how they should be licensed. I notice that in {vctrs}, certain files [were *unlicensed*](https://github.com/r-lib/vctrs/pull/1314) to make it unambiguously clear that c/p is fine. Maybe that's an approach worth taking into consideration? Thanks.

**Comment by kevinushey** [comment]
These files are (at least currently) also MIT-licensed, and so I think they're fine to use in any project that is licensed in an MIT-compatible way. That is, please feel free to use them with pre-commit.

The intent is definitely to allow users to freely use those files in their projects without needing to worry about copyright / licensing occurs, so we'll evaluate if unlicense might be a good choice.
