### ISSUE TITLE
No way to tell `install()` to also install suggested dependencies

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/renv#739]
The documentation for `renv.install()` says that only *Required package dependencies (Depends, Imports, LinkingTo) will be installed*. It would be nice if the argument `dependencies` would be exposed (like in `install.packages()`) or via `renv::settings` or `renv::config`. For local packages, I otherwise have to use {remotes} for that.

Related: https://github.com/rstudio/renv/issues/66

**Comment by krlmlr** [comment]
There's a `package.dependency.fields` setting, see `?settings`.

**Comment by lorenzwalthert** [comment]
Indeed, thanks. Should this be linked in the help file for `renv::install()`? I don't know if it is a convention in this repo to link `settings`, but I think it could be useful in this situation.
