### ISSUE TITLE
status occasionally not seeing installed packages

### ISSUE THREAD

**Issue by bhogan-mitre** [rstudio/renv#740]
Occasionally a project gets into a weird state where `renv::status()` is not properly seeing packages installed in the project library.

Generally `renv` has been working fine and has been hugely helpful for me.  So this is just an occasional occurrence, and I'm not sure how to reproduce it or how best to document it.  I'm posting here regardless in case someone has suggestions of things to try or can help illustrate a specific bug.

For example in the screenshot below, I have installed several packages in the project library with only two (`renv` and `DBI`) currently in the lock file.  Yet, `status()` is showing that everything is in sync.

![Screen Shot 2021-04-30 at 9 03 18 AM](https://user-images.githubusercontent.com/32336739/116699738-ef006800-a993-11eb-9c95-ae80c461fd9a.png)

![Screen Shot 2021-04-30 at 9 14 36 AM](https://user-images.githubusercontent.com/32336739/116700189-81087080-a994-11eb-9840-b5456e9e7b8d.png)

Stepping through in a debugger, I can see that `status()` eventually calls `renv_lockfile_create()`.  Within that function the call to `renv_snapshot_r_packages()` shows everything, but after it is piped into `renv_snapshot_filter()` only the two packages currently in the lockfile remain.  
https://github.com/rstudio/renv/blob/ffe5790161fed81226577a31231299e2be2c36ba/R/lockfile.R#L161

Is there something about the `type = "implicit"` parameter value there that is causing this issue?

**Comment by kevinushey** [comment]
The most likely answer is that renv believes those packages aren't actually used in your project -- see the first entry in https://rstudio.github.io/renv/articles/faq.html for more details.

What does `renv::dependencies()` report in your project?

**Comment by bhogan-mitre** [comment]
Thanks for pointing that out.  I had preemptively installed a few packages in a new project but hadn't started using them yet.  A while later after several packages were clearly being used in scripts (and after a couple session restarts) `renv::status()` did start picking them up.  So I think that checks out with the FAQ.  

What threw me off however was that `DBI` of all things was being picked up while nothing else was.  I don't have an explanation for why that would have been tracked as a dependency prior to anything else.  I might have installed that via `renv::install()` and maybe the others via `install.packages()`.  Could that have made a difference?

**Comment by kevinushey** [comment]
No, that would not make a difference. You'd need to check the output of `renv::dependencies()` to know for sure.

**Comment by bhogan-mitre** [comment]
Got it, thanks.  I will try that the next time this comes up.
