### ISSUE TITLE
compilation failed for package ‘rhdf5filters’

### ISSUE THREAD

**Issue by yanxianl** [rstudio/renv#741]
Hi,

I have an R project stored in Dropbox which is synced among 3 computers (2 installed with windows10 and 1 installed with ubuntu 20). I had no problems installing project libraries on our Windows computers. When installing a Bioconductor package, biomformat, on ubuntu 20, the package failed to compile. I could install other Bioconductor packages on this ubuntu computer though. 

Error messages:
> cp: target 'Dropbox/projects/yanxian/Li_AqFl1-Microbiota_2020/renv/library/R-4.0/x86_64-pc-linux-gnu/00LOCK-rhdf5filters/00new/rhdf5filters/lib/' is not a directory
> make: *** [Makevars:24: copying] Error 1
> ERROR: compilation failed for package ‘rhdf5filters’
> * removing ‘/media/md0/nutrition_group Dropbox/projects/yanxian/Li_AqFl1-Microbiota_2020/renv/library/R-4.0/x86_64-pc-linux-gnu/rhdf5filters’
> ERROR: dependency ‘rhdf5filters’ is not available for package ‘rhdf5’
> * removing ‘/media/md0/nutrition_group Dropbox/projects/yanxian/Li_AqFl1-Microbiota_2020/renv/library/R-4.0/x86_64-pc-linux-gnu/rhdf5’
> ERROR: dependency ‘rhdf5’ is not available for package ‘biomformat’
> * removing ‘/media/md0/nutrition_group Dropbox/projects/yanxian/Li_AqFl1-Microbiota_2020/renv/library/R-4.0/x86_64-pc-linux-gnu/biomformat’

**Comment by yanxianl** [comment]
Yes, it did! I made a copy of my R project outside the Dropbox folder and I was able to install this bioconductor. Is it possible to also make it work within the Dropbox folder?

**Comment by kevinushey** [comment]
I'd recommend placing your project library folder somewhere separate from your Dropbox folder. You could do so by placing this in your `~/.Renviron` file; e.g. something like:

```
RENV_PATHS_LIBRARY_ROOT = /media/md0/renv
```

Tweak that path as appropriate, you'd just want to make sure you're placing your library paths outside of the Dropbox folder.

**Comment by svillegasv** [comment]
Hello! I`m having the same problem, and im not working on Dropbox. It is ubuntu 22.04.02 LTS

**Comment by hadley** [comment]
@svillegasv can you please file a new issues showing exactly what code you ran and what error you’re seeing?
