### ISSUE TITLE
renv::restore() fails on git repos installed with devtools::install_git

### ISSUE THREAD

**Issue by martinv13** [rstudio/renv#744]
Hi,

First of all thanks for this great package which helps up improving the robustness of our dev process.

I am trying to use renv to restore a package developed internally and hosted on a private git server. I tried the following steps (here with a github version of data.table but I have exactly the same error with our package) :

* Start from a new Rstudio project with renv (0.13.2) enabled
* Install devtools with `renv::install("devtools")` : ok
* Install the package from git server with `devtools::install_git("https://github.com/Rdatatable/data.table.git"` : ok
* Add a dummy file with `library(data.table)` to be sure that renv will pick it up
* Write lock file with `renv::snapshot()` : ok, the lock file has the following record:
```
"data.table": {
      "Package": "data.table",
      "Version": "1.14.1",
      "Source": "Git",
      "RemoteType": "xgit",
      "RemoteUrl": "https://github.com/Rdatatable/data.table.git",
      "RemoteSha": "10463e32613bb9b400e54179d2ac92e655b22701",
      "Hash": "5ff9b341945ced43c2c731da7da2656f"
    }
```
* Deactivate renv with `renv::deactivate()`
* Delete library, local and staging folder to simulate a new copy of the project
* Reactivate renv with `renv::activate()`
* Restore from lock file: here comes the error:
```
> renv::restore()
The following package(s) will be updated:

# Git ================================
- data.table   [* -> 1.14.1]

Do you want to proceed? [y/N]: y
Erreur : file 'C:\Users\MARTIN~1.VER\AppData\Local\Temp\Rtmp8a2VY3\renv-git-395c614c570f' exists but is a directory
Traceback (most recent calls last):
12: renv::restore()
11: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
10: renv_retrieve(packages)
 9: handler(package, renv_retrieve_impl(package))
 8: renv_retrieve_impl(package)
 7: renv_retrieve_git(record)
 6: renv_retrieve_successful(record, path)
 5: renv_description_read(path, subdir = subdir)
 4: renv_filebacked("DESCRIPTION", path, renv_description_read_impl, 
        subdir = subdir, ...)
 3: callback(path, ...)
 2: stopf("file '%s' exists but is a directory", path)
 1: stop(sprintf(fmt, ...), call. = call.)

```

Besides and oddly, it will also download the content of the git repository in the working directory.

I am a bit confused about the support status for git package sources as the lock file seems to pick them up correctly but so far I have had no luck trying to restore them, starting from "clean", cloned project source. I tried to understand where the error comes from with no success as I do not understand well enough the internals of the restore process.

Thank you very much in advance.

Cheers,
Martin

____
if it helps, here is my session info in case you do not manage to reproduce:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 cli_2.5.0      tools_4.0.3    yaml_2.2.1     renv_0.13.2    rlang_0.4.11 
```

**Comment by kevinushey** [comment]
Thank you for the thorough bug report! I was unfortunately not able to reproduce this on my macOS machine, but will try and see if I can reproduce on Windows.

**Comment by kevinushey** [comment]
I also cannot reproduce on my Windows machine, unfortunately.

One potential hypothesis: does your user account name have non-ASCII / accented characters? If so, it's possible `renv` is mishandling the encoding somewhere. To test, you could try setting the environment variable:

```
TMP = "C:\tmp"
```

in your project `.Renviron` file. Restart R, and confirm that `tempdir()` resolves to a directory within `C:\tmp` (you may need to create it if it does not already exist). Does the restore work then?

If that doesn't work, then if you're willing it'd be helpful if you could `debug(renv:::renv_retrieve_git)` and step through to see what is happening / what is going wrong.

**Comment by martinv13** [comment]
Thank you, changing TMP folder location did work! It is not straightforward as we have the same behaviour on different PC with no special characters in the AppData temp folder. Maybe this has something to do with the antivirus but I could not be positive about this.
Thank you, we'll go with this solution then!
Best, Martin
