### ISSUE TITLE
Suggestion to make renv_project_synchronized_check() an exported function

### ISSUE THREAD

**Issue by lhuhmann** [rstudio/renv#745]
My team wants our script to throw an error if the loaded renv library does not match the lockfile. We are currently using the following code:

```
if (!renv:::renv_project_synchronized_check()) {
    stop()
}
```

However, we'd prefer not to rely on a non-exported function in our project code. Would it be possible to provide this as an exported function?

I wasn't able to identify a pre-existing exported function that would work for this, but of course feel free to let me know if I overlooked something. Thank you!

**Comment by hadley** [comment]
As described in #807, you can use the synchronised flag in the output of `renv::status()` for this.
