### ISSUE TITLE
Robust restore()

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#746]
I'm currently struggling with the `restore()` of a massive lock file in two different systems:

- Linux, no control (I can only run a Shiny app), air-gapped, network-local CRAN mirror
- Windows, no (desire to) compile from sources, slow connection to the CRAN mirror

Some packages don't install out of the box. When I call `restore()`:

- all packages are downloaded
- the installation process starts, they are installed one by one
- eventually, it fails
- when I strip the failing package from the lock file, it is still installed in the next step, because of some downstream package that depends on the failing package

This makes the installation attempts unnecessarily long. How can we make `restore()` more robust in such initialization cases?

- Print upfront, which packages are going to be restored due to dependency repair (so that these can be removed from the lock file too)
- Topological sort of the packages in the lock file (so that we can restore the first n lines of the lock file, then add the next n lines, etc.)
- Offer a way to download + install package by package
- Offer a way to restore the first `n` packages (topological sort?)
- Offer a "keep going" option that attempts to restore all packages despite failures, and reports failures in the end
- ...?

**Comment by kevinushey** [comment]
FWIW, you can use `renv::restore(packages = <...>)` to restore a subset of packages from the lockfile. In theory, you could then attempt to restore each package one-by-one.

Perhaps `renv::restore(exclude = <...>)` would be useful as well, to restore all but some subset of packages.

> Offer a "keep going" option that attempts to restore all packages despite failures, and reports failures in the end

This seems reasonable as well; perhaps as an argument to `renv::restore()` to control how failures are handled.

**Comment by krlmlr** [comment]
Thanks for the quick reply. The `packages` argument works for me and removes a lot of frustration already.

How do you feel about splitting `restore()` and also `update()` into two lower-level parts: collect a recipe and then apply it? The recipe should already contain the packages sorted in the correct order. Normal users would rarely if ever need to use those lower-level parts, however, they would be documented and exposed:

```r
restore <- function(...) {
  recipe <- restore_recipe(...)
  print(recipe)
  if (prompt) ask()
  apply_recipe(recipe)
}
```

I suspect that this will also make it easier to implement a "keep going" mode.

I haven't found the string "topo" in the codebase, are you ever doing an explicit topological sort of the dependency graph? Could you please point me to the location? In my script, I'm doing something along the lines of:

```r
dep_graph <- igraph::graph_from_data_frame(dep_df(tools::package_dependencies()))
package_order <- format(names(igraph::topo_sort(dep_graph))
```

This needs igraph which we don't normally have, we should be able to roll a somewhat efficient topological sort with base R data frame functions too. This is somewhat imperfect, as GitHub packages aren't captured, and (in theory) the dependency graph might change over time, it might be good enough in practice.

**Comment by krlmlr** [comment]
(I admit there is some overlap with pak, what are the longer-term plans for integrating it?)

**Comment by kevinushey** [comment]
> How do you feel about splitting restore() and also update() into two lower-level parts: collect a recipe and then apply it? The recipe should already contain the packages sorted in the correct order. Normal users would rarely if ever need to use those lower-level parts, however, they would be documented and exposed:

This is what I would eventually like to do. `renv` already does something like this internally -- a restore basically has two stages.

1. Retrieve all requested packages, and return a list of topologically-sorted packages;
2. Install those packages.

Ideally, step (1) would be separated into two steps -- first, topologically sort the list of packages, then retrieve those packages, then install them.

FWIW, I'm considering calling this 'plan()' rather than 'recipe()' just to avoid conflicts with the recipes packages: https://cran.r-project.org/web/packages/recipes/index.html

> I haven't found the string "topo" in the codebase, are you ever doing an explicit topological sort of the dependency graph? Could you please point me to the location?

It happens somewhat implicitly here:

https://github.com/rstudio/renv/blob/master/R/retrieve.R#L736-L743

That is, `renv_retrieve()` calls itself recursively on the dependencies of each downloaded package, and the ordering of retrieval gets encoded into the returned list of packages.

https://github.com/rstudio/renv/blob/master/R/retrieve.R#L36-L39

That list is then passed on to an internal `install` method; e.g. in

https://github.com/rstudio/renv/blob/master/R/restore.R#L184-L186

> (I admit there is some overlap with pak, what are the longer-term plans for integrating it?)

Eventually, I'd like for any `renv` routine that needs to install packages to delegate to `pak` if installed / requested by the user, but honestly that work hasn't been scoped out yet.

**Comment by krlmlr** [comment]
Thanks, this helps a lot.

As a first step, how about supporting `restore(dry_run = FALSE)`, where `dry_run = TRUE` returns the output of `renv_retrieve()`? Do we already have a high-level method that accepts an input as returned by `renv_retrieve()` ? This could also be `restore(plan_only = FALSE)` with a new `renv::execute(plan)` .

**Comment by krlmlr** [comment]
A few more observations:

- The "keep going" option might want to to strip downstream dependencies with source installs, not necessarily with binary installs; not sure about mixed installs
- A progress callback would be great

**Comment by ddsjoberg** [comment]
> Perhaps renv::restore(exclude = <...>) would be useful as well, to restore all but some subset of packages.

For what it's worth, an exclude argument would be fantastic. It often occurs that I run into an issue with a small number of packages (most often those being installed from my company's internal RSPM), and it would be much easier to exclude a handful of packages, compared to including 100+ packages. Thank you!

**Comment by kevinushey** [comment]
@ddsjoberg thanks! I've implemented that on master now.

**Comment by ddsjoberg** [comment]
@kevinushey wow! Thank you so much!

**Comment by krlmlr** [comment]
Thanks, this is useful! Another way to help difficult `restore()` operations could be the specification of a maximum number of packages to download and install; we abort the download and proceed to installation when that limit is reached. Do downloads happen in topological order too?

**Comment by krlmlr** [comment]
Maybe we can achieve the same with much less effort if we download and attempt to install in an interleaved way?

Today: download all -> install some -> fail -> argh

Desired: download one -> install one -> download two -> fail -> much less argh

With transactional installs this still gives us all-or-nothing, but the packages are copied to the cache early so that there's not too much work duplicated.

**Comment by hadley** [comment]
Closing in favour of #1109.
