### ISSUE TITLE
renv::restore() tries to restore a Bioconductor Package downloading it from CRAN 

### ISSUE THREAD

**Issue by masaver** [rstudio/renv#747]
I'm using `renv::restore()` to install some libraries, when creating a docker image on a Linux/Ubuntu system. Most of the libraries are restored without a problem. However, I encountered a problem with "SomaticSignatures" , which is a package from Bioconductor. After some time, `renv::restore()` stops, and gives this error message:
`Error: failed to retrieve package 'SomaticSignatures'
In addition: Warning messages:
1: could not retrieve available packages for url 'https://bioconductor.org/packages/3.11/books/src/contrib'
2: In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
  cannot open URL 'https://cran.rstudio.com/src/contrib/Archive/pcaMethods/pcaMethods_1.82.0.tar.gz': HTTP status was '404 Not Found'
3: failed to retrieve package 'pcaMethods'
4: internal error: unexpected status code 'structure(list(message = "failed to retrieve package 'pcaMethods'", call = NULL, traceback = c("Traceback (most recent calls last):", "25: renv::restore(lockfile = \"/home/project/renv.lock\")", "24: renv_restore_run_actions(project, diff, current, lockfile, rebuild)", "23: renv_retrieve(packages)", "22: handler(package, renv_retrieve_impl(package))", "21: renv_retrieve_impl(package)", "20: renv_retrieve_bioconductor(record)", "19: renv_retrieve_repos(record)", "18: catch(withCallingHandlers(method(record), renv.retrieve.error = function(error) {",  "        errors$push(error)", "    }))", "17: tryCatch(withCallingHandlers(expr, error = renv_error_capture), ", "        error = renv_error_tag)", "16: tryCatchList(expr, classes, parentenv, handlers)", "15: tryCatchOne(expr, names, parentenv, handlers[[1L]])", "14: doTryCatch(return(expr), name, parentenv, handler)", "13: withCallingHandlers(expr, error = renv_error_capture)", "12: withCallingHandle [... truncated]
5: In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
  cannot open URL 'https://cran.rstudio.com/src/contrib/Archive/SomaticSignatures/SomaticSignatures_2.24.0.tar.gz': HTTP status was '404 Not Found'
Traceback (most recent calls last):
9: renv::restore(lockfile = "/home/project/renv.lock")
8: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
7: renv_retrieve(packages)
6: handler(package, renv_retrieve_impl(package))
5: renv_retrieve_impl(package)
4: renv_retrieve_bioconductor(record)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)
Execution halted`

It seems that renv:restore() is trying to install SomaticSignatures by downloading it from CRAN. This is incorrect since SomaticSignatures is a Bioconductor Package.

The lock file correctly specifies Bioconductor as the source for SomaticSignatures:
`"SomaticSignatures": {
      "Package": "SomaticSignatures",
      "Version": "2.24.0",
      "Source": "Bioconductor",
      "Hash": "0bc200200114e0239f4ea69ae6ac0325"
    }`

Here is a link to the full lock file : https://www.dropbox.com/s/puz50orcbggv0ai/renv.lock?dl=0

Does anyone know what might be happening here ?

Thanks in advance,

-Mathias

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, I was not able to reproduce -- I was able to successfully restore that lockfile locally (at least, on my macOS machine).

Is it possible this was caused by an intermittent connectivity failure to the Bioconductor repositories?

**Comment by masaver** [comment]
I don't think so . I tried restoring the lock file two more times, and I even used a different r-base image, but I still saw the same error.

**Comment by masaver** [comment]
Solved it ! Although I'm not sure why the error was happening on the first place.

I ended up updating all of my biocunductor packages to the latest release, by running `BiocManager::install( version = '3.12')`, then recreated the renv.lock file and was finally able to restore the libraries using `renv:restore()`.

**Comment by kevinushey** [comment]
Glad to hear it! We do want to spend some time further improving the experience when restoring packages from Bioconductor; hopefully when that happens issues of this form will occur less often in the future.
