### ISSUE TITLE
R and Rstudio Dependencies for renv

### ISSUE THREAD

**Issue by aetiologicCanada** [rstudio/renv#748]
I won't describe the 2+ hours that got me to this question, but ...in trying to use renv for the first time on a colleague's system, I finally realized that the IT-maintained R and Rstudio versions are both from 2018.   I should have checked ... renv was not happy with this situation.  Lots of errors, including several that probably arose in my attempt to debug the problem.  Their Rstudio  Server version was 1.1.xxx and was still asking about packrat during new project configuration!  (How did I miss that detail?)

What are the minimum versions of R and Rstudio needed to run renv?   Could these be tested for during the renv package installation?   Of course updating their R and Rstudio version will involve corporate IT and various protracted internal considerations.

**Comment by kevinushey** [comment]
> What are the minimum versions of R and Rstudio needed to run renv?

`renv` itself supports versions of R 3.2 and greater, and RStudio's integration with `renv` was introduced with RStudio 1.4. In theory, you should be able to use `renv` with older versions of RStudio; you just won't get the necessary integration / UI. (That is, you'll still get unwanted prompts and UI for Packrat instead, as you have seen).

> Could these be tested for during the renv package installation?

We could potentially have `renv` warn / notify the user if we detect that the user is running in RStudio, and that version of RStudio is "old". Would that suffice for your case?

**Comment by hadley** [comment]
These are now really old versions, so I think it's probably ok to skip these checks.
