### ISSUE TITLE
Consider chattier message on status / snapshot

### ISSUE THREAD

**Issue by slopp** [rstudio/renv#749]
If you are using a renv mode that only snapshots identified dependencies and not the entire active library, it can be hard to understand why some packages are being excluded. 

While this behavior is often what you want, users have to be proactive in finding this very helpful FAQ: https://rstudio.github.io/renv/articles/faq.html#why-isn-t-my-package-being-snapshotted-into-the-lockfile-

It may help if renv::status and renv::snapshot were a little chattier when the snapshot type is not all. For example, a status message might say: 

8 packages are installed in the library but will not be snapshotted because don't appear to be used. See renv::dependencies to see what packages appear to be in use. Run renv::settings$snapshot.type("all") to tell renv to track all installed packages.

This is a long message and may get annoying overtime... a tradeoff to consider. 

FWIW I really like the renv::dependencies default, I sometimes forget about it though! This ticket was prompted by the parsnip package which has dependencies that are usually not identified by renv::dependencies.

**Comment by kevinushey** [comment]
What about something like the following:

```
> renv::status(verbose = TRUE)
The following package(s) are installed, but do not appear to be used in the project:
         _
  digest   [0.6.27]

These packages will not enter the lockfile when `renv::snapshot()` is called.
If you intend for any of these packages to be snapshotted, you can place
a call to library(<pkg>) in a file called `_deps.R` in your project.
```

**Comment by kevinushey** [comment]
The main downside is -- what if this is the outcome the user actually does want, e.g. for packages like `devtools`? You might want those explicitly installed in the project library but not recorded in the lockfile as it's not a runtime dependency.

**Comment by hadley** [comment]
I still think you want this chattiness when a suggested package is attached, rather than when you run `renv::status()`.

**Comment by hadley** [comment]
Or maybe `status()` could just report the snapshot type being used.

**Comment by hadley** [comment]
See discussion in PR above.
