### ISSUE TITLE
Use lockfile when building a docker image

### ISSUE THREAD

**Issue by vnijs** [rstudio/renv#75]
`renv` looks great. Very interested to see how it develops. One thing I was hoping to use the lockfile for was to install packages R packages for a docker image. I develop on macOS but want a docker image/container for (longer term) reproducibility. 

I had hoped that `renv::restore` could parse the lockfile and install packages as part of the Docker build process. This would be similar to (1) creating a requirements.txt file in python using `freeze` and then (2) using the command below to install specific versions of the required packages.

```
pip3 install -r requirements.txt
```

When I try this, however, the build seems to stall for a while without any output shown and then throws the error below. Is this not something that `restore` can do? Any suggestions?

```
> renv::restore(lockfile = "./renv.lock", actions = "install", library = "/usr/local/lib/R/site-library", confirm = FALSE)
Error: target file '/usr/local/lib/R/site-library/assertthat' already exists
In addition: Warning message:
In file.rename(path, tempfile) :
  cannot rename file '/usr/local/lib/R/site-library/assertthat' to '/usr/local/lib/R/site-library/renv-backup-assertthat6730c1b26', reason 'Invalid cross-device link'
Traceback (most recent calls first):
  10: stop(sprintf(fmt, ...), call. = call.)
   9: stopf("target file '%s' already exists", target)
   8: renv_file_preface(source, target, overwrite)
   7: f(n[[i]], x[[i]], ...)
   6: FUN(X[[i]], ...)
   5: lapply(idx, function(i) f(n[[i]], x[[i]], ...))
   4: enumerate(targets, renv_file_move, overwrite = TRUE)
   3: renv_install(project, records)
   2: renv_restore_run_actions(project, diff, current, lockfile)
   1: renv::restore(lockfile = "./renv.lock", actions = "install",      librar <...>
Execution halted
The command '/bin/sh -c R -e 'renv::restore(lockfile = "./renv.lock", actions = "install", library = "/usr/local/lib/R/site-library", confirm = FALSE)'' returned a non-zero code: 1
```

**Comment by kevinushey** [comment]
Thanks! This is a configuration we absolutely want to support; I'll try to take a look next week.

Can you also try running with options(warn = 2) to try turning that warning into an error?

**Comment by kevinushey** [comment]
A reproducible example (e.g. the Dockerfile you're trying to use) would also be helpful.

**Comment by vnijs** [comment]
Great! Using `options(warn = 2)` doesn't change the output as this was already an error.

I create a minimal repo @ https://github.com/vnijs/renv_docker. I use `build-container.sh` to generate the lockfile and build the docker image from `Dockerfile`. Then I use `launch-container.sh` to startup the container but you can of course just use `docker run`

```
> options(warn = 2); renv::restore(lockfile = "./renv.lock", actions = "install", library = "/usr/local/lib/R/site-library", confirm = FALSE)
Error in file.rename(path, tempfile) : 
  (converted from warning) cannot rename file '/usr/local/lib/R/site-library/assertthat' to '/usr/local/lib/R/site-library/renv-backup-assertthat6151557c4', reason 'Invalid cross-device link'
Calls: <Anonymous> ... renv_file_preface -> renv_file_scoped_backup -> file.rename
Traceback (most recent calls first):
  14: doWithOneRestart(return(expr), restart)
  13: withOneRestart(expr, restarts[[1L]])
  12: withRestarts({     .Internal(.signalCondition(simpleWarning(msg, call),  <...>
  11: .signalSimpleWarning("cannot rename file '/usr/local/lib/R/site-library/ <...>
  10: file.rename(path, tempfile)
   9: renv_file_scoped_backup(target)
   8: renv_file_preface(source, target, overwrite)
   7: f(n[[i]], x[[i]], ...)
   6: FUN(X[[i]], ...)
   5: lapply(idx, function(i) f(n[[i]], x[[i]], ...))
   4: enumerate(targets, renv_file_move, overwrite = TRUE)
   3: renv_install(project, records)
   2: renv_restore_run_actions(project, diff, current, lockfile)
   1: renv::restore(lockfile = "./renv.lock", actions = "install",      librar <...>
Execution halted
The command '/bin/sh -c R -e 'options(warn = 2); renv::restore(lockfile = "./renv.lock", actions = "install", library = "/usr/local/lib/R/site-library", confirm = FALSE)'' returned a non-zero code: 1

```

**Comment by michaelhogersosis** [comment]
We have a Dockerfile that copies a renv.lock file with the steps as below and this seems to work fine, could this issue be related to the library argument used in restore @kevinushey ?
 
```
RUN R -e "install.packages('devtools')"

RUN R -e "devtools::install_github('rstudio/renv@0.3.0-1')"

COPY . .

RUN R -e "library('renv')"

RUN R -e "renv::restore()"
```

**Comment by vnijs** [comment]
Thanks for the suggestion @michaelhogersosis. I tried adding `library('renv')` but that had no effect. 
I did find, however, that changing the library to use from `/usr/local/lib/R/site-library` to `/usr/lib/R/site-library` resolved the issue! Works as expected now so I will close this issue for now.

**Comment by kevinushey** [comment]
@vnijs is it possible `/usr/local/lib` was a mounted directory or something similar in your container?

**Comment by vnijs** [comment]
I am using this while building a docker image so nothing is mount. See the Dockerfile at the example repo linked below.

https://github.com/vnijs/renv_docker

**Comment by cboettig** [comment]
@vnijs why did you originally choose `"/usr/local/lib/R/site-library"`?  Looks like your images install R from apt-get and not from source, so your R_HOME would be `/usr/lib/R`and not `/usr/local/lib/R` ... does `/usr/local/lib/R/site-library` exist on your image?  what does `.libPaths()` show?  

so far it looks like `renv::restore()` is working for me in Docker images, and we may eventually migrate to this approach over MRAN snapshots.  really nice work with `renv`!

**Comment by vnijs** [comment]
@cboettig I do install a few packages with `apt-get`. However, I also use `install.packages` from R. The output from `.libPaths()` is shown below. 

> .libPaths()
[1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"
[3] "/usr/lib/R/library"
