### ISSUE TITLE
Update to R 4.1 triggers many "package x was installed before R 4.0.0: please re-install it"

### ISSUE THREAD

**Issue by MatthieuStigler** [rstudio/renv#750]
Hi

I recently upgraded to R 4.1, which triggered issues in multiple renv projects. I get the warning message *R version change [4.0.5 -> 4.1.0]*, and many packages are now missing. 

I tried `rend::restore()`, but this quickly fails, complaining that some packages have been built with R <4. For example, I got: 

> Error: package or namespace load failed for ‘RcppZiggurat’:
>  package ‘RcppZiggurat’ was installed before R 4.0.0: please re-install it

I am able to solve the issue by running ` renv::install("RcppZiggurat",rebuild=TRUE)`, but I have to do again with the next packages, and to do ten times so far. 

Is there a more elegant way to address this? I tried using `renv::update(rebuild=TRUE)`, but it just says *All packages appear to be up-to-date.* I notice that I have `RcppZiggurat` in the newest cache (`ls ~/.local/share/renv/cache/v5/R-4.1/x86_64-pc-linux-gnu/RcppZiggurat/0.1.6/`), but I guess this is just a link to the version installed on my system, that is built for R < 4? 

So what can I do? Should I hence just update/rebuild all my packages on the standard non-renv folder?

Thanks!
PS: running on Ubuntu 18.04.

**Comment by kevinushey** [comment]
Can you please share the output of `renv::diagnostics()` in your project?

**Comment by kevinushey** [comment]
FWIW, this surprises me a bit since `renv` should use different / unique library paths for different versions of R; e.g.

```
> .libPaths()
[1] "/Users/kevinushey/scratch/abc/renv/library/R-4.1/x86_64-apple-darwin17.0"
[2] "/private/tmp/Rtmpf4HpNb/renv-system-library"
```

Note the `4.1` component in the library path. (Is it possible that you have `RcppZiggurat` + other packages installed into a site library or system library?)

**Comment by MatthieuStigler** [comment]
Thanks for your prompt answer Kevin! Attaching the output of `renv::diagnostics()` as requested. 

And yes, my main library has indeed a version of `RcppZiggurat` (and probably others), which is indeed built under R 3.6. Note that this was installed not through R, but using Ubuntu's bult-in packages (cran2deb), hence in `/usr/lib/R/site-library`, not in `/home/mat_rstudio/R/x86_64-pc-linux-gnu-library/` like other packages. But that means it is even more strange renv was looking  at this one? During the `restore()`, it seemed renv was downloading the packages from the web? My .libPaths() within the renv project are:

```
[1] "/home/mat_rstudio/kenya_cropIns/renv/library/R-4.1/x86_64-pc-linux-gnu"
[2] "/tmp/RtmpHnoi84/renv-system-library" 
```

Thanks!

**Comment by MatthieuStigler** [comment]
Strangely enough, I notice that the problem happens trying to install package `Rfast`, while supposedly `RcppZiggurat` has already been installed? See the output of `renv::restore()`:

```
Installing RcppZiggurat [0.1.6] ...
	OK [linked cache]
Installing Rcsdp [0.1.57.1] ...
	OK [linked cache]
Installing Rfast [2.0.1] ...
...
installing to /home/mat_rstudio/kenya_cropIns/renv/staging/1/00LOCK-Rfast/00new/Rfast/libs
...
Error: package or namespace load failed for ‘RcppZiggurat’:
 package ‘RcppZiggurat’ was installed before R 4.0.0: please re-install it
```

I cannot see however the package in the project library: 

```
a<-as.data.frame(installed.packages())
a[grepl("Rcpp", a$Package, ignore.case=TRUE),1:3]
     Package
Rcpp    Rcpp
                                                                    LibPath
Rcpp /home/mat_rstudio/kenya_cropIns/renv/library/R-4.1/x86_64-pc-linux-gnu
     Version
Rcpp   1.0.6
```

**Comment by kevinushey** [comment]
I think I know what's going on here...

One of the installation shortcuts that `renv` tries to take is that it will look in the default user + site libraries for a requested package, and install a copy of that into the private library if a compatible version is found.

However, your site library contains packages compiled for an older version of R. Those packages won't be compatible with R 4.1.x, but `renv` is still finding and copying those into the private library. :-/

The workaround for now would be something like:

```
options(renv.config.install.shortcuts = FALSE)
options(renv.config.cache.enabled = FALSE)
unlink(renv::paths$library(), recursive = TRUE)
renv::restore(rebuild = TRUE)
```

I'll try to get this fixed this ASAP in the next version of `renv` as well.

**Comment by MatthieuStigler** [comment]
Thanks! And tried and get an error message, not sure what I am missing?

```
Error in renv_description_read(path) : 
  renv_path_absolute(path) is not TRUE
Traceback (most recent calls last):
10: renv::restore(rebuild = TRUE)
 9: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
 8: renv_retrieve(packages)
 7: sprintf("renv (%s)", renv_package_version("renv"))
 6: base::sprintf(fmt, ...)
 5: renv_package_version("renv")
 4: renv_package_description_field(package, "Version")
 3: renv_description_read(path)
 2: stopifnot(renv_path_absolute(path))
 1: stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p)))
```

**Comment by kevinushey** [comment]
Oops. Removing the library also implies removing `renv`, which then implies getting this weird error in the same session. Can you try restarting the R session and calling `renv::restore(build = TRUE)`? (On restart, `renv` should get automagically bootstrapped into the project library)

**Comment by kevinushey** [comment]
And I'm now recalling that `renv::rebuild()` is a more ergonomic way to directly rebuild all packages used within a project, so that may be worth giving a shot. Sorry for the run-around.

**Comment by MatthieuStigler** [comment]
Thanks, it all worked removing the lines as you suggested

```
options(renv.config.install.shortcuts = FALSE)
options(renv.config.cache.enabled = FALSE)
```

Interestingly, I still got other issues, reporting them here just in case, as I was able to solve them

```
Installing pkgload [1.1.0] ...
	FAILED
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘pkgload’:
 .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: namespace ‘rlang’ 0.4.8 is already loaded, but >= 0.4.9 is required
```

That was very weird, even after `renv::install` rlang 0.4.11, it would still show up. I had to update the renv.lock manually for the newer version. 

And I also got:

```
Installing tictoc [1.0] ...
	FAILED
	
	Error: package or namespace load failed for ‘tictoc’:
 .onLoad failed in loadNamespace() for 'tictoc', details:
  call: assign(".ticmsg", Stack(), envir = baseenv())
  error: cannot add binding of '.ticmsg' to the base environment
```
For this one had to remove from the renv, then install once everything ran smoothly. 

Thanks for your help!

**Comment by kevinushey** [comment]
That tictoc error sounds like it's probably due to a change in R 4.1.0. The latest release looks fine on CRAN, though.
