### ISSUE TITLE
Cancelling `renv::restore()` should also cancel python environment restoring 

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#752]
In a project with R and Python, I cancelled a `restore()` but it continued with Python env skipping R restoring. 

Maybe cancelling should act on both restoration process, R and Python ? 

````r
> renv::restore()
The following package(s) will be updated:

# LISTING OF R PACKAGE HERE

Do you want to proceed? [y/N]: N
* Operation canceled.
Collecting anyio==2.2.0
  Downloading anyio-2.2.0-py3-none-any.whl (65 kB)
Collecting appnope==0.1.2
  Downloading appnope-0.1.2-py2.py3-none-any.whl (4.3 kB)

# OTHER R PYTHON PACKAGES HERE 

* Restored Python packages from '~/myproject/requirements.txt'.
````

I guess not some many user answer No to restore but it seems unexpected that operation was cancelled only for R.

**Comment by kevinushey** [comment]
Thanks! Should now be fixed in the development version of `renv`.
