### ISSUE TITLE
renv::init() cannot create symlink

### ISSUE THREAD

**Issue by JoWhi** [rstudio/renv#753]
Hoping to get a handle on my package versions, but I'm not able to get started with renv. I'm working on RStudio on an institutional server, version 1.1.456, R version 3.6.3 (2020-02-29) -- "Holding the Windsock", from a laptop running macOS Big Sur 11.3.1. Updating R or RStudio is not under my control. 

Starting a new blank project and calling `renv::init()` gives this error:

```
Warning message:
In file.symlink(from, to) :
  cannot symlink '/usr/lib/R/library/base' to '/home/XXXXX.LAN/.../MyNewProject/packrat/lib-R/x86_64-pc-linux-gnu/3.6.3/base', reason 'Operation not supported'
```
Is this a permissions issue? Server or local? Any suggestions appreciated!

**Comment by kevinushey** [comment]
I suspect the issue is that your home directory is on a network share or similar that doesn't support symlinks.

The simplest fix would be something like:

```
RENV_CONFIG_SANDBOX_ENABLED = FALSE
```

in your project's `.Renviron`, or your global `~/.Renviron` file. See `?Startup` for more details.

**Comment by kevinushey** [comment]
Also ...

>   cannot symlink '/usr/lib/R/library/base' to '/home/XXXXX.LAN/.../MyNewProject/packrat/lib-R/x86_64-pc-linux-gnu/3.6.3/base', reason 'Operation not supported'

Are you using Packrat, or renv here?

**Comment by JoWhi** [comment]
So on a new R project, I had the option to use packrat, so I checked that box. Trying now without, then calling init() I get: 

```
`* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- renv   [* -> 0.13.2]

* Lockfile written to '~/.../myNextProject/renv.lock'.`
```


`Warning message:
In file.symlink(from, to) :
  cannot symlink '/usr/lib/R/library/base' to '/home/XXXXX.LAN/myNextProject/packrat/lib-R/x86_64-pc-linux-gnu/3.6.3/base', reason 'Operation not supported'`

(still with the packrat designation).

**Comment by aetiologicCanada** [comment]
This is the same environment discussed in this previous issue: https://github.com/rstudio/renv/issues/748
Efforts are underway to improve the R and Rstudio versions, but ...

**Comment by JoWhi** [comment]
I updated the .Rprofile as suggested, but get the same error. If I try to install any packages I get something like this:

`> init()
This project already has a lockfile. What would you like to do? 

1: Restore the project from the lockfile.
2: Discard the lockfile and re-initialize the project.
3: Activate the project without snapshotting or installing any packages.
4: Abort project initialization.

Selection: 2
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
* The lockfile is already up to date.

Restarting R session...

* Project '~/KoborLab/kobor_space/jwhitehead/toescrossed' loaded. [renv 0.13.2]
Warning message:
In file.symlink(from, to) :
  cannot symlink '/usr/lib/R/library/base' to '/home/BCRICWH.LAN/joanne.whitehead/KoborLab/kobor_space/jwhitehead/toescrossed/packrat/lib-R/x86_64-pc-linux-gnu/3.6.3/base', reason 'Operation not supported'
> install.packages("exoplanets")
Retrieving 'https://cloud.r-project.org/src/contrib/cli_2.5.0.tar.gz' ...
	OK [file is up to date]
...
Retrieving 'https://cloud.r-project.org/src/contrib/cpp11_0.2.7.tar.gz' ...
	OK [downloaded 194.9 Kb in 0.2 secs]
Installing glue [1.4.2] ...
cp -pPR '/mnt/xxx-hpc/tools/R/library/3.5/glue/' '/home/XXXXX.LAN/.../MyNewProject/renv/staging/1/.renv-copy-96f32cfddfa'
================================================================================

cp: preserving permissions for ‘/home/XXXXX.LAN/.../MyNewProject/renv/staging/1/.renv-copy-96f32cfddfa/NAMESPACE’: Operation not supported
cp: preserving permissions for ‘/home/XXXXX.LAN/.../MyNewProject/renv/staging/1/.renv-copy-96f32cfddfa/LICENSE’: Operation not supported
...`

**Comment by kevinushey** [comment]
Can you please try the following:

First, place the following in your project's `.Renviron` file:

```
RENV_CONFIG_SANDBOX_ENABLED = FALSE
RENV_CONFIG_INSTALL_TRANSACTIONAL = FALSE
```

Then, remove the project's `.Rprofile`:

```
unlink(".Rprofile")
```

Finally, restart R, and then call `renv::init()` once more and re-initialize the project.

**Comment by JoWhi** [comment]
Still the same error I'm afraid.

**Comment by hadley** [comment]
@JoWhi is this still a problem for you with the latest version of renv?

**Comment by pmhogan** [comment]
@hadley @JoWhi

I just encountered a similar `cp: preserving permissions` error on a Cray system when upgrading from `renv` v0.17.3 to v1.x, and this thread was the only information I could find on this error.

In case anyone else encounters this issue: setting the environment variable`RENV_CONFIG_COPY_METHOD = rsync` resolved it for me 👍
