### ISSUE TITLE
snapshot does not work with explicit type and non-default profiles

### ISSUE THREAD

**Issue by vspinu** [rstudio/renv#754]
I have the following in the DESCRIPTION file

```
Config/renv/profiles/base/dependencies: jsonlite, Rcpp, httpuv, stringi
```

Then I do per documentation

```
renv::activate(profile = "base")
renv::settings$snapshot.type("explicit")
renv::snapshot()
```

Nothing is added to the `renv/profiles/base/renv/renv.lock` file.

**Comment by vspinu** [comment]
Actually, I can reproduce this with local setup, the DESCRIPTION file is not picked up

```
Config/renv/profiles/base/dependencies: jsonlite, Rcpp, httpuv, stringi
```

```
> 
> renv::restore()
* The library is already synchronized with the lockfile.
```

**Comment by vspinu** [comment]
This might be expected, as there are no packages installed with the base profile. I guess, my expectation was that packages from the default profile will be automatically recognized and snapshot into the custom profiles.

**Comment by hadley** [comment]
We should double check that `snapshot()` warns when a package used by the project is not installed.
