### ISSUE TITLE
Managing packages from private repos

### ISSUE THREAD

**Issue by mrkaye97** [rstudio/renv#755]
Is there a best practice for managing packages that live in private Github repos with `renv`? Even with a `GITHUB_PAT = <foobar>` environment variable specified, I still always get an error on `renv::restore()` that `renv` couldn't find `<my-package>`.

I've defaulted to just ignoring the private packages in `settings.dcf`, but this forces me to manually install them after doing an `renv::restore()`.

Thanks in advance for any pointers!

**Comment by kevinushey** [comment]
> Even with a GITHUB_PAT = <foobar> environment variable specified, I still always get an error on renv::restore() that renv couldn't find <my-package>.

That should work. What happens if you explicitly try to install the package, e.g. with:

```
renv::install("repo/package")
```

Does that succeed? What about the equivalent call using `remotes::install_github()`?

**Comment by mrkaye97** [comment]
Sorry in advance for the ignorance here...

This works fine:

```r
Sys.setenv("GITHUB_PAT" = <foo>)

## works
renv::install("repo/package")

## works too
remotes::install_github("repo/package")
```

but then:

```r
> renv::snapshot()
* The lockfile is already up to date.
```

and

```r
> renv::install()
Error: package 'foo' is not available
```

Sorry again if I'm just doing something wrong here, but this wasn't the behavior I'd expect. I was expecting to just do `renv::install('repo/package')` and then `renv::snapshot()`, have the lockfile update, and have no issues.

Thanks for the help!

**Comment by kevinushey** [comment]
What does the lockfile entry in `renv.lock` for your package look like? Is it properly declared as being from GitHub?

**Comment by mrkaye97** [comment]
Looks like this:

```json
    "package": {
      "Package": "package-name",
      "Version": "2.1.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "collegevine",
      "RemoteRepo": "repo",
      "RemoteRef": "main",
      "RemoteSha": "a...xxx",
      "Hash": "f...xxx"
    }
```

which seems okay to me?

**Comment by kevinushey** [comment]
The error message here:

> Error: package 'foo' is not available

would seem to indicate that `renv` is trying to install that package from CRAN, rather than from GitHub, which is surprising to me. Is that package perhaps listed in the Remotes: field of your DESCRIPTION file (in case that's somehow overriding this)?

Either way, the full error output from `renv::restore()` would be helpful (you should normally see a backtrace of what went wrong). For example, using your lockfile record as an example:

```
> renv::restore()
The following package(s) will be updated:

# GitHub =============================
- nosuchpackage   [* -> collegevine/repo@main]

Do you want to proceed? [y/N]: y
Retrieving 'https://api.github.com/repos/collegevine/repo/tarball/a...xxx' ...
Warning: curl: (22) The requested URL returned error: 404
```

**Comment by mrkaye97** [comment]
So it seems like I can't replicate the `restore()` issue now. Maybe doing `renv::install("repo/package")` updated something somehow? 

Now when I `renv::restore()` it works fine (lockfile looks the same), but `renv::install()` still gives `Error: package 'package' is not available`.

I don't have good intuitions for why `restore()` and `install()` would behave differently in this case. Does `install()` assume CRAN by default maybe but `restore()` does something different? It's not in the Remotes field in my DESCRIPTION (it's in Imports)

**Comment by kevinushey** [comment]
What is the exact `install` command you are running, and the exact error output you are seeing?

If you are running `renv::install("package")`, then `renv` will assume you're trying to install that package from CRAN -- you need to explicitly provide the repository name (e.g. `renv::install("repo/package")`) to install from GitHub.

**Comment by mrkaye97** [comment]
It's just `renv::install()` which I was thinking would install all of the packages that are included in the lockfile. Is that not right? The exact error is what I pasted: `Error: package 'package' is not available`, which I agree makes it seem like it's looking for `package` on CRAN instead of `repo/package` on Github

**Comment by kevinushey** [comment]
Thanks; sorry, I misunderstood that part.

`renv::restore()` restores packages from the lockfile, `renv::install()` installs packages as declared in the DESCRIPTION file. I think that explains the difference here -- the DESCRIPTION file doesn't declare anything special about your package, so `renv` assumes it is from CRAN.

I believe the solution would be to declare the remote, e.g. add `Remotes: repo/package`, to the DESCRIPTION file.

**Comment by mrkaye97** [comment]
Aha! Okay, that totally makes sense! Thanks a bunch for the help.

**Comment by kevinushey** [comment]
I'll also update the documentation in `?install` to make this more clear. Thanks for the bug report and sorry for the confusion!

**Comment by mrkaye97** [comment]
Awesome, sounds great!
