### ISSUE TITLE
Error installing rmarkdown or stringi using renv::install("rmarkdown") 

### ISSUE THREAD

**Issue by 10adavis** [rstudio/renv#756]
I am unable to install rmarkdown or stringi after initiating renv in my Rproj. I have replicated this issue on 2 separate PCs running R on Windows 10. 

renv::install("stringi")

Retrieving 'https://cran.rstudio.com/src/contrib/stringi_1.6.2.tar.gz' ...
	OK [file is up to date]
Installing stringi [1.6.2] ...
	FAILED
Error installing package 'stringi':
===================================

* installing to library 'C:/Users/andre/Documents/GitHub_Repos/TensorFlow2.0_Course/renv/staging/1'
* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
** using staged installation
Warning in system("sh ./configure.win") : 'sh' not found
ERROR: configuration failed for package 'stringi'
* removing 'C:/Users/andre/Documents/GitHub_Repos/TensorFlow2.0_Course/renv/staging/1/stringi'
Error: install of package 'stringi' failed [error code 1]

sessionInfo()

R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0    tinytex_0.32   xfun_0.23     
[5] renv_0.13.2

**Comment by kevinushey** [comment]
Can you share the output of:

```
getOption("pkgType")
Sys.getenv("MAKE")
```

as well as:

```
renv::diagnostics()
```

Presumedly, setting `options(pkgType = "binary")` should resolve the problem here.

**Comment by 10adavis** [comment]
> getOption("pkgType")
[1] "both"
> Sys.getenv("MAKE")
[1] ""

**Comment by 10adavis** [comment]
> renv::diagnostics()
Diagnostics Report [renv 0.13.2]
================================

# Session Info =======================
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.4 tools_4.0.4    renv_0.13.2   

# Project ============================
Project path: "C:/Users/andrew.davis/OneDrive - Unilever/Desktop/Computational_Biology/Resources_Tools/Rmarkdown_Template_2021"

# Status =============================
* This project has not yet been snapshotted -- 'renv.lock' does not exist.
The following package(s) are installed but not recorded in the lockfile:
       _
  renv   [0.13.2]

Use `renv::snapshot()` to add these packages to your lockfile.

The following package(s) are used in the project, but are not installed:

	rmarkdown

Consider installing these packages, and then using `renv::snapshot()`
to record these packages in the lockfile.


# Packages ===========================
This project has not yet been snapshotted: 'renv.lock' does not exist.
           Library Source Lockfile Source Path Dependency
KernSmooth 2.23-20   CRAN     <NA>   <NA>  [2]       <NA>
MASS        7.3-54   CRAN     <NA>   <NA>  [2]       <NA>
Matrix       1.3-3   CRAN     <NA>   <NA>  [2]       <NA>
boot        1.3-28   CRAN     <NA>   <NA>  [2]       <NA>
class       7.3-19   CRAN     <NA>   <NA>  [2]       <NA>
cluster      2.1.2   CRAN     <NA>   <NA>  [2]       <NA>
codetools   0.2-18   CRAN     <NA>   <NA>  [2]       <NA>
foreign     0.8-81   CRAN     <NA>   <NA>  [2]       <NA>
here         1.0.1   CRAN     <NA>   <NA>  [1]       <NA>
lattice    0.20-44   CRAN     <NA>   <NA>  [2]       <NA>
mgcv        1.8-35   CRAN     <NA>   <NA>  [2]       <NA>
nlme       3.1-152   CRAN     <NA>   <NA>  [2]       <NA>
nnet        7.3-16   CRAN     <NA>   <NA>  [2]       <NA>
renv        0.13.2   CRAN     <NA>   <NA>  [1]       <NA>
rmarkdown     <NA>   <NA>     <NA>   <NA> <NA>     direct
rpart       4.1-15   CRAN     <NA>   <NA>  [2]       <NA>
rprojroot    2.0.2   CRAN     <NA>   <NA>  [1]       <NA>
spatial     7.3-14   CRAN     <NA>   <NA>  [2]       <NA>
survival    3.2-11   CRAN     <NA>   <NA>  [2]       <NA>

[1]: C:/Users/andrew.davis/OneDrive - Unilever/Desktop/Computational_Biology/Resources_Tools/Rmarkdown_Template_2021/renv/library/R-4.0/x86_64-w64-mingw32
[2]: C:/Users/andrew.davis/AppData/Local/Temp/RtmpgjQC4r/renv-system-library                                                                              

# User Profile =======================
[no user profile detected]

# Settings ===========================
List of 8
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ r.version                : chr(0) 
 $ snapshot.type            : chr "implicit"
 $ use.cache                : logi TRUE
 $ vcs.ignore.library       : logi TRUE
 $ vcs.ignore.local         : logi TRUE

# Options ============================
List of 6
 $ defaultPackages     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method: chr "wininet"
 $ download.file.extra : NULL
 $ repos               : Named chr "https://cloud.r-project.org"
  ..- attr(*, "names")= chr "CRAN"
 $ renv.consent        : logi TRUE
 $ renv.verbose        : logi TRUE

# Environment Variables ==============
HOME                        = C:\Users\andrew.davis\OneDrive - Unilever\Documents
LANG                        = <NA>
R_LIBS                      = <NA>
R_LIBS_SITE                 = <NA>
R_LIBS_USER                 = C:/Users/andrew.davis/OneDrive - Unilever/Desktop/Computational_Biology/Resources_Tools/Rmarkdown_Template_2021/renv/library/R-4.0/x86_64-w64-mingw32;C:/Users/andrew.davis/AppData/Local/Temp/RtmpgjQC4r/renv-system-library
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = <NA>
RENV_DEFAULT_R_LIBS_USER    = C:/Users/andrew.davis/OneDrive - Unilever/Documents/R/win-library/4.0
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = C:/Users/andrew.davis/OneDrive - Unilever/Desktop/Computational_Biology/Resources_Tools/Rmarkdown_Template_2021

# PATH ===============================
- C:\rtools40\usr\bin
- C:\rtools40\usr\bin
- C:\Users\andrew.davis\Program Files\R\R-4.0.4\bin\x64
- C:\Program Files (x86)\Common Files\Oracle\Java\javapath
- C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services
- C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services
- C:\WINDOWS\system32
- C:\WINDOWS
- C:\WINDOWS\System32\Wbem
- C:\WINDOWS\System32\WindowsPowerShell\v1.0\
- C:\WINDOWS\System32\OpenSSH\
- C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\
- C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\
- C:\Users\andrew.davis\AppData\Local\Microsoft\WindowsApps
- C:\Users\andrew.davis\AppData\Local\Programs\Microsoft VS Code\bin
- C:\Users\andrew.davis\AppData\Local\Programs\Git\cmd
- C:\Users\andrew.davis\AppData\Local\Pandoc\

# Cache ==============================
There are a total of 287 package(s) installed in the renv cache.
Cache path: "C:/Users/andrew.davis/AppData/Local/renv/cache/v5/R-4.0/x86_64-w64-mingw32"

Warning messages:
1: The 'rmarkdown' package is required to parse dependencies within R Markdown files.
Consider installing it with `install.packages("rmarkdown")`. 
2: The 'knitr' package is required to parse dependencies within multi-mode files.
Consider installing it with `install.packages("knitr")`.

**Comment by kevinushey** [comment]
Thanks -- one more thing to ask. What is the output of `Sys.which("make")`? And, does the following work?

```
options(pkgType = "binary")
renv::install("stringi")
```

For context, the error here is occurring because binaries for the latest version of `stringi` are not available, and you do not have the requisite command line tools available in order to build packages from sources. See https://cran.r-project.org/bin/windows/Rtools/ for more details.

**Comment by 10adavis** [comment]
> renv::diagnostics()
Diagnostics Report [renv 0.13.2]
================================

# Session Info =======================
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0    renv_0.13.2   

# Project ============================
Project path: "C:/Users/andre/Documents/GitHub_Repos/TensorFlow2.0_Course"

# Status =============================
* This project has not yet been snapshotted -- 'renv.lock' does not exist.
The following package(s) are installed but not recorded in the lockfile:
       _
  renv   [0.13.2]

Use `renv::snapshot()` to add these packages to your lockfile.


# Packages ===========================
This project has not yet been snapshotted: 'renv.lock' does not exist.
           Library Source Lockfile Source Path Dependency
KernSmooth 2.23-20   CRAN     <NA>   <NA>  [2]       <NA>
MASS        7.3-54   CRAN     <NA>   <NA>  [2]       <NA>
Matrix       1.3-3   CRAN     <NA>   <NA>  [2]       <NA>
base64enc    0.1-3   CRAN     <NA>   <NA>  [1]       <NA>
boot        1.3-28   CRAN     <NA>   <NA>  [2]       <NA>
class       7.3-19   CRAN     <NA>   <NA>  [2]       <NA>
cluster      2.1.2   CRAN     <NA>   <NA>  [2]       <NA>
codetools   0.2-18   CRAN     <NA>   <NA>  [2]       <NA>
digest      0.6.27   CRAN     <NA>   <NA>  [1]       <NA>
evaluate      0.14   CRAN     <NA>   <NA>  [1]       <NA>
foreign     0.8-81   CRAN     <NA>   <NA>  [2]       <NA>
glue         1.4.2   CRAN     <NA>   <NA>  [1]       <NA>
highr          0.9   CRAN     <NA>   <NA>  [1]       <NA>
htmltools  0.5.1.1   CRAN     <NA>   <NA>  [1]       <NA>
jsonlite     1.7.2   CRAN     <NA>   <NA>  [1]       <NA>
lattice    0.20-44   CRAN     <NA>   <NA>  [2]       <NA>
magrittr     2.0.1   CRAN     <NA>   <NA>  [1]       <NA>
markdown       1.1   CRAN     <NA>   <NA>  [1]       <NA>
mgcv        1.8-35   CRAN     <NA>   <NA>  [2]       <NA>
mime          0.10   CRAN     <NA>   <NA>  [1]       <NA>
nlme       3.1-152   CRAN     <NA>   <NA>  [2]       <NA>
nnet        7.3-16   CRAN     <NA>   <NA>  [2]       <NA>
renv        0.13.2   CRAN     <NA>   <NA>  [1]       <NA>
rlang       0.4.11   CRAN     <NA>   <NA>  [1]       <NA>
rpart       4.1-15   CRAN     <NA>   <NA>  [2]       <NA>
spatial     7.3-14   CRAN     <NA>   <NA>  [2]       <NA>
survival    3.2-11   CRAN     <NA>   <NA>  [2]       <NA>
xfun          0.23   CRAN     <NA>   <NA>  [1]       <NA>

[1]: C:/Users/andre/Documents/GitHub_Repos/TensorFlow2.0_Course/renv/library/R-4.1/x86_64-w64-mingw32
[2]: C:/Users/andre/AppData/Local/Temp/Rtmp0oYDB4/renv-system-library                                

# User Profile =======================
[no user profile detected]

# Settings ===========================
List of 8
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ r.version                : chr(0) 
 $ snapshot.type            : chr "implicit"
 $ use.cache                : logi TRUE
 $ vcs.ignore.library       : logi TRUE
 $ vcs.ignore.local         : logi TRUE

# Options ============================
List of 6
 $ defaultPackages     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method: chr "wininet"
 $ download.file.extra : NULL
 $ repos               : Named chr "https://cloud.r-project.org"
  ..- attr(*, "names")= chr "CRAN"
 $ renv.consent        : logi TRUE
 $ renv.verbose        : logi TRUE

# Environment Variables ==============
HOME                        = C:\Users\andre\OneDrive\Documents
LANG                        = <NA>
R_LIBS                      = <NA>
R_LIBS_SITE                 = <NA>
R_LIBS_USER                 = C:/Users/andre/Documents/GitHub_Repos/TensorFlow2.0_Course/renv/library/R-4.1/x86_64-w64-mingw32;C:/Users/andre/AppData/Local/Temp/Rtmp0oYDB4/renv-system-library
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = <NA>
RENV_DEFAULT_R_LIBS_USER    = C:/Users/andre/OneDrive/Documents/R/win-library/4.1
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = C:/Users/andre/Documents/GitHub_Repos/TensorFlow2.0_Course

# PATH ===============================
- C:\Program Files\R\R-4.1.0\bin\x64
- C:\Windows\system32
- C:\Windows
- C:\Windows\System32\Wbem
- C:\Windows\System32\WindowsPowerShell\v1.0\
- C:\Windows\System32\OpenSSH\
- C:\Program Files\Git\cmd
- C:\Users\andre\AppData\Local\Microsoft\WindowsApps
- 
- C:\Users\andre\AppData\Local\Programs\Microsoft VS Code\bin

# Cache ==============================
There are a total of 12 package(s) installed in the renv cache.
Cache path: "C:/Users/andre/AppData/Local/renv/cache/v5/R-4.1/x86_64-w64-mingw32"

**Comment by 10adavis** [comment]
Setting `options(pkgType = "binary")` allowed me to install stringi successfully.

**Comment by 10adavis** [comment]
> Sys.which("make")
make 
  ""
