### ISSUE TITLE
`renv` installation / remotes syntax conflict with remotes/devtools for deeper nested packages

### ISSUE THREAD

**Issue by gtm19** [rstudio/renv#759]
I have come across an issue (similar to #497) where I am unable to install a package using `remotes` / `devtools` syntax for GitHub based packages nested more deeply than at the top level / 1 folder down in a repository.

This is an issue for me since we use a monorepo at work, and I am sometimes not able to keep a package high up enough in the repo structure to keep `renv` happy.

I have created a [repo and instructions](https://github.com/gtm19/subsub.renv) which demonstrates that _either_ `remotes`/`devtools` OR `renv` is happy, but in short, installation like follows results in an error using `renv`, despite `remotes::install_*` being happy:

```r
desc::desc_set_remotes("github::gtm19/skeleton/subdir/subsubdir")
renv::install()
# Error: failed to resolve remote 'github::gtm19/skeleton/subdir/subsubdir' -- failed to retrieve 'https://api.github.com/repos/gtm19/skeleton/subdir' [error code 22]
# In addition: Warning message:
# curl: (22) The requested URL returned error: 404
```

Whereas making `renv` happy then makes `remotes` / `devtools` unhappy:

```r
desc::desc_set_remotes("github::gtm19/skeleton:subdir/subsubdir")
devtools::build()
devtools::install_local("../subsub.renv_0.0.0.9000.tar.gz")

# Error: Failed to install 'subsub.renv' from local:
#  HTTP error 404.
#  Not Found

#  Did you spell the repo owner (`gtm19`) and repo name (`skeleton:subdir`) correctly?
#  - If spelling is correct, check that you have the required permissions to access the repo.
# Execution halted
```

I believe I have a fix for this which passes all existing `renv` tests. I will PR shortly.

**Comment by hadley** [comment]
Based on discussion in the linked PR, it looks like this was fixed.
