### ISSUE TITLE
`init()` on onedrive/sharepoint folders does not install packages

### ISSUE THREAD

**Issue by brshallo** [rstudio/renv#76]
`renv::init()`, as well as `hydrate()`, and `dependencies()` (the warning printed below is the same when running each of these functions), does not work for me when run on a Onedrive/Sharepoint synced folder (on work Windows computer). The initial "renv/" folder gets created, though none of the libraries install (`install.packages()` etc. still works after this though).  (`renv::init()` has worked fine on my computer on non onedrive/sharepoint project directories.)

```r
renv::equip()
#> * External software is up to date.

renv::hydrate()
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> Warning message:
#> In system(command, intern = TRUE) :
#> running command 'C:\WINDOWS\system32\cmd.exe /c chcp 65001 && dir /B C:\Users\USERNAME\projectHomeDirectory' had status 1

sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> loaded via a namespace (and not attached):
#> [1] compiler_3.5.1 tools_3.5.1    renv_0.4.0-20 
```

**Comment by brshallo** [comment]
UPDATE: it actually seems the issue was with the folder path name in windows.  

In my example above I should have written "C:\Users\BSHALLOW\projectHomeDirectory" as something more representative of typical synced OneDrive/Sharepoint folder pathways in windows:

E.g synced OneDrive paths take on names like:
"C:\Users\USERNAME\OneDrive - Company Inc\project_home\"

E.g. synced Sharepoint paths take on names like:
"C:\Users\USERNAME\Company Inc\Sharepoint Site Name - Documents\project_home\"

When I created a local project with a similar name to these, I received the same error as I note in the original post.  E.g.
"C:\Users\USERNAME\Documents\Test - WeirdName Inc\project_home\"

**Comment by brshallo** [comment]
Seems like the issue is fixed if you add quotes around the directory in the `system()` call in `renv:::renv_file_list_impl()`.  Perhaps just changing the `command` assignment to:

`command <- paste0(comspec(), " /c chcp 65001 && dir /B ", '"' path, '"')`

in the function below would fix the issue...?

```{r}
renv_file_list_impl <- function(path) {

  # on Windows, list.files mangles encoding; avoid this by making a call to
  # 'dir' with the code page set to request UTF-8 encoded paths
  if (renv_platform_windows()) {
    path <- normalizePath(path)
    command <- paste(comspec(), "/c chcp 65001 && dir /B", path)
    output <- system(command, intern = TRUE)
    Encoding(output) <- "UTF-8"
    return(output)
  }

  # otherwise, a plain old list.files will suffice
  list.files(path)

}
```

**Comment by kevinushey** [comment]
I believe you're right -- should be fixed up now. Thanks!
