### ISSUE TITLE
Enable repository preference to prioritize versions available in first repository on install

### ISSUE THREAD

**Issue by smingerson** [rstudio/renv#763]
By default, it seems that renv gets the latest version of a package `pkg` available from any of the repositories listed in renv.lock. In the case of RSPM, we have set up  development and production sources for RSPM, both of which have our internal packages and are listed in the renv.lock during development.

Since the dev version is always larger than the production version, that version is what is installed by `renv::install("pkg")`. This can easily be worked around by using `renv::install("pkg@0.1.1")`, for example, but relies on the user understanding something about how the RSPM is set up, and how to interpret version numbers. 

Is there some setting which can be added to renv to *not* prefer the latest version, and rather prefer what is in the first repository listed?I am also open to hearing how changes in our workflow can alleviate this.

**Comment by hadley** [comment]
@kevinushey does renv not look for packages in repos in order they're defined in `getOption("repos")`

**Comment by kevinushey** [comment]
renv will install the latest-available package from the declared repositories, similar to what R does. If a particular version of a package is provided by multiple repositories, renv will use the first one in the repository list.

If I understand correctly, this issue is requesting that we install whatever package is provided by the "first" repository even if it's not the latest version?

**Comment by smingerson** [comment]
@kevinushey I would want the latest stable version by default, not the latest version ovwral

**Comment by hadley** [comment]
This feels to me like you need to configure your development packages some other way, so that they're not included in the default repositories. In general, there's no way to tell if a package is a development version, because not everyone uses the `.9000` convention.

**Comment by smingerson** [comment]
That's reasonable. Thank you for the discussion.
