### ISSUE TITLE
Auto-detection of available R versions?

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#765]
**Disclaimer**: Hi Kevin! I am aware this is a huge one but nevertheless I believe it could be a substantial user experience improvement 🙂 

**Scenario**

{renv} informs users if the current R version used differs from the one referenced in `renv.lock`. The process of installing multiple R versions differs on every OS, so do default installation paths.

**Idea**

Nevertheless, I was wondering if {renv} could potentially scan common R interpreter installation paths for major OS such as Windows, macOS and, let's say Ubuntu, for Linux.
If it finds a matching R interpreter, this one is automatically selected and somehow configured on a project basis.

**Thoughts**

While of course this does not work during the initial startup of a "wrong" R interpreter, {renv} could potentially create some softlinks / create some shims to ensure a specific R version is used during following R startups.

I cannot provide a full-fledged idea how this might work in practice but RStudio Workbench is also somehow able to encapsulate certain sessions with a specific R version which is known upfront.

I think such a behaviour is supported by project-env packages in other languages as well (no examples/proofs at hand though).

I am aware that dynamic version handling is feature of RStudio Workbench but I am also often finding myself in a terminal session with {renv} where such an auto-detection of available interpreter would be awesome to have.

**Comment by kevinushey** [comment]
> Nevertheless, I was wondering if {renv} could potentially scan common R interpreter installation paths for major OS such as Windows, macOS and, let's say Ubuntu, for Linux.
> If it finds a matching R interpreter, this one is automatically selected and somehow configured on a project basis.

How would this work, though? `renv` is an R package, so it ultimately requires an R interpreter to be running and available -- but once R has been launched, `renv` cannot help in configuring the version of R to use.

Either the user would need to intervene in some way (to "activate" a particular R interpreter in a project) or they would have to rely on their R front-end to select a version of R. `renv` could potentially "help" here (e.g. by finding and setting R symlinks in a project `bin` directory or something, or providing a command line toolkit for doing that) but I'm not sure how popular that would be in practice.

**Comment by pat-s** [comment]
> How would this work, though? renv is an R package, so it ultimately requires an R interpreter to be running and available -- but once R has been launched, renv cannot help in configuring the version of R to use.

Yes. The idea was to optionally take some action to change the default R interpreter by applying some magic.
Given that this is invasive, it should probably be off by default.

> renv could potentially "help" here (e.g. by finding and setting R symlinks in a project bin directory or something, or providing a command line toolkit for doing that) but I'm not sure how popular that would be in practice.

{renv} could, in addition to printing that the current R version != the on in `renv.lock`, apply some action to change the default interpreter to a matching one, assuming one was discovered.

A potential workflow could look like this

If `renv_setting_XX = TRUE`

1. Auto-discover available R interpreter from one or two common places on every OS (maybe `/opt/R` and in addition checking user supplied paths)
2. Make them the default interpreter
3. Restart the session automatically

On macOS, `rswitch` sets some [symlinks](https://github.com/hrbrmstr/RSwitch/blob/00d8fcce3f405772d5d464740dad0a4274b7cefb/rswitch-cmd/main.swift#L223). 
The same could probably be done on Linux and Ubuntu, but maybe setting an env var would already suffice (did not yet look into details).
Usually the R version is configurable on the user side and if not, {renv} could just return a potential permission issue.

I know that this is quite some sugar which might not be the core of {renv}. However, in the real world I often see people not even being aware that they have multiple versions installed or how to switch between such. I see people getting annoyed about the {renv} printout being on a different R version and while they most often just bump the R version, this becomes annoying when working in a collaborate manner where multiple persons are on different R versions and cannot follow the bump.
The potential solution to simplify the use of (especially older) existing R versions for medium-experienced users would make every day life a lot easier 😃

**Comment by kevinushey** [comment]
> {renv} could, in addition to printing that the current R version != the on in renv.lock, apply some action to change the default interpreter to a matching one, assuming one was discovered.

Perhaps `renv::snapshot()` could write some extra data (or writes a symlink, or something) that front-ends (e.g. RStudio) could then use when deciding which version of R to use on launch.

Or even, RStudio could read `renv.lock` and then choose an interpreter based on the declared version (searching the common locations). That would be pretty nice, but there are probably some questions to answer in terms of making this behavior more apparent to the user.

**Comment by pat-s** [comment]
> Perhaps renv::snapshot() could write some extra data (or writes a symlink, or something) that front-ends (e.g. RStudio) could then use when deciding which version of R to use on launch.

Symlinks might be an IDE-agnostic way to implement this. Direct support for RStudio is ofc always welcome but I would also hope have this working when working solely in a terminal :)

> That would be pretty nice, but there are probably some questions to answer in terms of making this behavior more apparent to the user.

Definitely, not an easy task from an architectural standpoint.
My first idea was a message in the console and an option which the user first needs to switch on.
Maybe a post-action message that {renv} did this change would also be helpful as the action can be seen as quite invasive 😄 

Would be really great to have this, happy to help if I can provide valuable help in some way or another. I think you might want to do the implementation yourself most likely, so I won't come up with an opinionated PR for now :)

**Comment by kevinushey** [comment]
> Symlinks might be an IDE-agnostic way to implement this. Direct support for RStudio is ofc always welcome but I would also hope have this working when working solely in a terminal :)

You'd need to have some helper script to "activate" a particular R session from the terminal, e.g. by modifying your PATH. (This is the Python / virtualenv approach). Or, some suitable alias for R / Rscript that automagically delegates to a different version of R if discovered (but that can be brittle).

**Comment by hadley** [comment]
IMO this is out of scope for renv, but it's now handled by https://github.com/r-lib/rig
