### ISSUE TITLE
Found continuation line starting ' <!DOCTYPE html> ...' at begin of record.

### ISSUE THREAD

**Issue by avraam-inside** [rstudio/renv#766]
Good afternoon!

Tell me what can cause the error to appear:

![image](https://user-images.githubusercontent.com/52919010/121036894-b1bf9f00-c7b7-11eb-987e-9d378f1fa40d.png)

Install code: remotes::install_git(ref = 'v2.1',url = 'https://someurl.com/bms-analytics/custom.utils', credentials = git2r::cred_user_pass(username = '', password = ''))

when installing a package from your own git?

I do not know how to explain to my colleagues how to install the package in the project.

**Comment by hadley** [comment]
Unfortunately we don't have enough information to know what's gone wrong, and it's now been almost 2 years. If this is still a problem, please file a new issue with a bit more context.
