### ISSUE TITLE
Clarify impact of additional args in install.packages()

### ISSUE THREAD

**Issue by rpodcast** [rstudio/renv#77]
My typical workflow for bootstrapping new projects (for example a shiny application) is to take advantage of using multiple CPU cores via `install.packages("shiny", Ncpus = 10)` when I'm running R on a server with lots of cores.  I noticed that after initializing a new `{renv}` project that when I use the additional Ncpus argument, many of the dependencies for Shiny did not get installed.  I discovered that when I ran `renv::snapshot()` and got a message about missing dependencies.  However, when I don't supply the additional argument, everything worked as expected and the dependencies got installed.  I tracked it down to one of the shims below: 

https://github.com/rstudio/renv/blob/e5b9b51cf98625510566613e4a7dee0f7178c2fd/R/shims.R#L10-L19

In addition, I saw that the library paths for the session included my default R installation's library as well as the project-specific library:

```r
> .libPaths()
[1] "/path/to/shiny_projects/golemshiny/renv/library/R-3.5/x86_64-pc-linux-gnu"
[2] "/path/to/R/R-3.5.2/lib64/R/library"  
```

I may have missed it, but it would be good to have a note in the documentation about this possibility.

**Comment by kevinushey** [comment]
>  I noticed that after initializing a new {renv} project that when I use the additional Ncpus argument, many of the dependencies for Shiny did not get installed.

If I'm understanding correctly, you executed `install.packages("shiny", Ncpus = 10)`, and saw that some Shiny dependencies were not installed? That is a bit surprising to me because in that case we would just delegate back to the default `utils::install.packages()` function as provided by base R.

In other words, the `renv` shim currently only activates when using a single argument as e.g. `install.packages("shiny")`.

**Comment by rpodcast** [comment]
I did some more digging and verified that this odd behavior occurs even after removing any `renv` configuration files/packages in my home directory (`~/.local/share/renv`). I believe it is due to the `.libPaths()` containing the system-wide R library path, and not just the `renv` project library path.  Since the system-wide library has shiny already installed, it seems to think that the dependencies are already there (well at least some of them?). 

When I run the same `install.packages("shiny", Ncpus = 10)` with `packrat`, all of the dependencies to shiny get installed as exected.  Checking the `.libPaths()` for the `packrat` version of the project leads to this:

```
> .libPaths()
[1] "/path/to/project/packrat/lib/x86_64-pc-linux-gnu/3.5.2"
[2] "/path/to/project/packrat/lib-ext/x86_64-pc-linux-gnu/3.5.2"
[3] "/path/to/project/packrat/lib-R/x86_64-pc-linux-gnu/3.5.2"
```

FWIW I replicated the same issue with my R installation on Mac OS X.

**Comment by kevinushey** [comment]
I wonder if R sees that `shiny` is installed, and so assumes that all of its transitive dependencies must already be installed as well?

**Comment by rpodcast** [comment]
That's my only guess at this point.  If nothing else, this tells me to try and stick with the `renv` shim for installing packages, or to manually remove the system-wide library path from `.libPaths()` before running the multiple-core install?

**Comment by kevinushey** [comment]
I'm going to leave this issue open for now to consider if we should enable the shim in more contexts. (You can also use `renv::install("<package>")` directly if you want direct access to the `renv` installation machinery)

**Comment by rpodcast** [comment]
I'm not sure if you want to move this to a separate issue, but I am curious why renv retains the system-level R library path in `.libPaths()`?  Perhaps I'm a bit conservative but when I am working in an renv project, I don't want any impact from the system library if it can be prevented.

**Comment by kevinushey** [comment]
The system library path needs to remain for base R packages (e.g. the `tools` and `utils` packages). In theory we could do some extra work to sandbox the library in case someone has installed user packages into the system library (we took that approach in Packrat) but that approach does have a number of failure modes that are difficult to overcome.

We could re-explore that but I think the simpler solution is to request that users maintain a 'clean' system library.

**Comment by kevinushey** [comment]
`renv` now sandboxes the system library by default, so that only base + recommended packages within the system library are exposed to projects.
