### ISSUE TITLE
renv::init is searching for and parsing dependencies with `bare = TRUE`

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#771]
I don't think this needs a reprex because a quick look at the code path here will confirm this is true:
https://github.com/rstudio/renv/blob/master/R/init.R#L94

This seems at odds with the description of `bare` which says:
> bare Boolean; initialize the project without attempting to discover and install R package dependencies?

Discovery is currently being performed which has a couple of unfortunate side effects:
* `renv` initialisation is slow for the case where you want to manually limit the dependency search scope
* `renv` can choke parsing files that don't need to be parsed causing unexpected errors (how I discovered this problem, new issue will be created)

**Comment by kevinushey** [comment]
Thanks! Should be fixed up now.
