### ISSUE TITLE
Warn/message if `snapshot()` called in an uninitialised project

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/renv#777]
I recently forgot to `init()` before `snapshot()`ing and happily had my remote collaborators run `renv::restore()`, which then was surprisingly difficult to diagnose remotely - even though the issue should have been obvious to me due to the missing renv directory in the git repo. The reason, I think, is that the renv directory & renv-generated .Rprofile is mostly "commit once, forget about it", so it's hard to spot that it's missing. 

I was a bit surprise that renv let me do that without complaining, given how (usefully) explicit/talkative it is generally.

Clearly this is a silly user error, but I wonder if it might make sense to check in `snapshot()` whether the current project has in fact been initialised for renv to save others the same trouble? (Unless there is a rationale for `snapshot()` outside renv-managed projects, but then a message might still be useful.)

**Comment by petrbouchal** [comment]
More precisely, when I run `snapshot()` without first running `init()`, the following happens:

- `renv` dir created
- `renv/activate.R` file created
- nothing else in the `renv` directory (no `settings.dcd`, no `library` dir)
- no `.Rprofile` created

which I think explains a bit more why this was difficult to troubleshoot.

**Comment by petrbouchal** [comment]
I also just noticed that in `renv` 0.12, the `renv` directory was in fact created, with only `activate.R` inside it. In 0.13.2, only `renv.lock` is created.

RStudio also seems to be doing some detection, because the renv-related UI elements only turn up after `init()` but not when only a `renv.lock` file is present.

**Comment by kevinushey** [comment]
> (Unless there is a rationale for snapshot() outside renv-managed projects, but then a message might still be useful.)

There is, in that you can use `snapshot()` and `restore()` outside the context of an `renv` project (for example, to snapshot and restore arbitrary library paths), but I think that by default we should definitely do something here to notify the user if it looks like they're trying to call `snapshot()` in a project that hasn't yet been initialized.

**Comment by kevinushey** [comment]
I think we should do something like: if `renv::snapshot()` is invoked, and no project appears to be active, and the user hasn't explicitly provided a library path to be snapshotted, then prompt the user to initialize the project instead.

We should also do something similar in `restore()` -- I am sure some users would be confused if they called `renv::restore()` in what they believed was an active `renv` project but instead ended up installing packages into their user library instead.

**Comment by kevinushey** [comment]
I think this should be handled better now with the development version of `renv`. For example, if you call `renv::snapshot()` in an `renv` project that has not yet been initialized:

```
> renv::snapshot()

This project has not yet been activated.
Activating this project will ensure the project library is used for snapshot().
Please see `?renv::activate` for more details.

Would you like to activate this project before snapshot()? [Y/n]:
```

You can then have `renv` automatically activate the current project before calling snapshot.

**Comment by petrbouchal** [comment]
Many thanks - I tested this and it behaves as expected as far as I can tell. Certainly helpful for my original use case.

**Comment by kevinushey** [comment]
Glad to hear it -- thanks for reporting back!
