### ISSUE TITLE
Document / Check for minimum required system `git` version

### ISSUE THREAD

**Issue by strazto** [rstudio/renv#778]
renv requires some `git` features that are only available/only work beyond a certain release.

On ubuntu 16.04, the default `git` install is `2.7.4` .
On `git <= 2.7.4`, `renv` will fail on `git` operations with an error I can't reproduce right now (I'll try this out on a new VM soon)

On `git >= 2.21`, renv does not fail in `git` operations.

The actual minimum version is within `min > 2.7.4 && min <= 2.21`, though I don't know precisely what.

I *think* that Ubuntu 18.04's default `git --version` of `2.17.1` doesn't have problems.

the `2.7` release of `git` is ~6 years old (`2.7.4` was released march 2016), and considering `git` is a portable & widely available dependency, I don't think the minimum requirement is too onerous, but debugging the failure is tricky. 

(Even in HPC environments, if you're unable to obtain a modern `git` from modules, or build one yourself, you probably have bigger problems on your hands)

This minimum requirement should be ascertained, documented, & added to `renv_git_preflight()` s.t it's clear _why_ renv git operations are failing, & users are prompted to upgrade. 

(we could also investigate accomodating backwards compatibility, but I don't know that its worth it since no-one else seems to be raising this issue)

**Comment by matthewstrasiotto** [comment]
You know what? I can't reproduce this on `git version 2.7.4`.

Maybe this isn't a problem for `git >= 2.7.4`
