### ISSUE TITLE
show more  feedback when restoring python project

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#779]
Using last dev version (0.13.2-83), it seems that now the console output of restoring python requirement are no more shown (or I remember incorrectly they were shown). 

However, I find it that it could be clearer if an additional printed feedback is added to the existing 

````r
> renv::restore()
The following package(s) will be updated:

# CRAN ===============================
- base64enc    [0.1-3 -> 0.1-3]

Do you want to proceed? [y/N]: y
Installing base64enc [0.1-3] ...
	OK [linked cache]
* Restored Python packages from '~/demo/requirements.txt'.
````

We currently don't know when R packages are correctly restored and when python requirements is being installed. We don't have information on what is up to date or not, and when it is starting restoring or not. We only guess when the R console is hanging and we get an answer at the end when the `* Restored Python packages ...` is printed. 

What about adding additional step feedback ? 

````diff
> renv::restore()
The following package(s) will be updated:

# CRAN ===============================
- base64enc    [0.1-3 -> 0.1-3]

Do you want to proceed? [y/N]: y
Installing base64enc [0.1-3] ...
	OK [linked cache]
+ * Restoring Python packages from '~/demo/requirements.txt'
+     OK
- * Restored Python packages from '~/demo/requirements.txt'.
````

Even if I know it is working I am always questionning the R console hanging step. 😅

**Comment by kevinushey** [comment]
Thanks! This should be resolved on master now; the suppression of output during the Python 'restore' was unintended.
