### ISSUE TITLE
Docker builds and renv

### ISSUE THREAD

**Issue by michaelhogersosis** [rstudio/renv#78]
Hi there,

Installing packages via renv on a docker image is a bit finicky, the renv::restore() command takes a long time for larger projects (say > 100 libraries), if there is a failure at some point the entire RUN R -e "renv::restore()" command is nullified and has to be performed again. Is it possible to make renv more robust when restoring libraries on a Docker images? For example, could there be a way to (partially) cache the renv installations, as one would see when using the RUN R -e "install.packages('xxx')" lines repeatedly?

Best regards,

Michael

**Comment by kevinushey** [comment]
You can use the environment variable `RENV_CACHE_PATH` to set a location where the `renv` package cache should be written, and make sure that path is a mounted directory that is shared by `renv`-using containers.

(We should document this in a vignette)

**Comment by kevinushey** [comment]
This is a case where one might _not_ want the restore to be atomic, so we might need to think about when that should be enabled / disabled.

**Comment by kevinushey** [comment]
I've now documented this here: https://rstudio.github.io/renv/articles/docker.html

Please let me know if you have any feedback!

**Comment by michaelhogersosis** [comment]
Thanks @kevinushey! Very helpful, will try to use the documentation over the coming days
