### ISSUE TITLE
Arbitrary changes of the "Repository" field in renv.lock

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#785]
Finally I got around reprexing a weird problem where the "Repository" field in `renv.lock` keeps alternating between `"RSPM"` and `"CRAN"` for no obvious reason. This adds a lot of Git noise if left unchecked.

This field is set in `renv.lock` depending on the installation source. On macOS, it is reset to `"CRAN"` during `restore()`. I'll double-check what happens on Ubuntu.

``` r
packageVersion("renv")
#> [1] '0.13.2.85'

# Two repositories: test1 and test2
# test1 has a "normal" CRAN, test2 is linked to an RSPM snapshot
# During setup, we simulate a clean environment with renv::purge()
# The callr::r() call conveniently returns the result of renv::snapshot(),
#   which is the lock file as an R list. We watch the Repository component
#   for the rlang package.

renv::purge("rlang")
#> The following packages will be purged from the cache:
#> 
#>  rlang 0.4.11 [Hash: 515f341d3affe0de9e4a7f762efb0456]
#> 
#> * Removed 1 package from the cache.
dir.create("test1")
setwd("test1")

callr::r(function() {
  options(repos = "https://cloud.r-project.org")
  renv::init()
  renv::snapshot()
  renv::install("rlang")
  writeLines("library(rlang)", "packages.R")
  renv::snapshot()
})$Packages$rlang$Repository
#> [1] "CRAN"

setwd("..")

renv::purge("rlang")
#> The following packages will be purged from the cache:
#> 
#>  rlang 0.4.11 [Hash: 515f341d3affe0de9e4a7f762efb0456]
#> 
#> * Removed 1 package from the cache.
dir.create("test2")
setwd("test2")

callr::r(function() {
  options(repos = "https://packagemanager.rstudio.com/cran/2021-06-21")
  renv::init()
  renv::snapshot()
  renv::install("rlang")
  writeLines("library(rlang)", "packages.R")
  renv::snapshot()
})$Packages$rlang$Repository
#> [1] "RSPM"

setwd("..")

# The erratic behavior occurs when attempting a restore() + snapshot().
# In both repositories, the package's "Repository" entry is set to CRAN,
#   at least on macOS. This generates unnecessary VCS noise and has been
#   a source of moderate pain in the past months.

setwd("test1")
unlink("renv/library", recursive = TRUE)
callr::r(function() {
  renv::restore()
  renv::snapshot()
})$Packages$rlang$Repository
#> [1] "CRAN"

setwd("..")

setwd("test2")
unlink("renv/library", recursive = TRUE)
callr::r(function() {
  renv::restore()
  renv::snapshot()
})$Packages$rlang$Repository
#> [1] "CRAN"

setwd("..")
```

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by krlmlr** [comment]
Bingo! On Ubuntu (with older renv), the behavior is reversed -- both repositories return `"RSPM"` in this example. Testing with up-to-date renv.

``` r
packageVersion("renv")
#> [1] '0.13.2'

# Two repositories: test1 and test2
# test1 has a "normal" CRAN, test2 is linked to an RSPM snapshot
# During setup, we simulate a clean environment with renv::purge()
# The callr::r() call conveniently returns the result of renv::snapshot(),
#   which is the lock file as an R list. We watch the Repository component
#   for the rlang package.

renv::purge("rlang")
#> The following packages will be purged from the cache:
#> 
#>  rlang 0.4.10 [Hash: 599df23c40a4fce9c7b4764f28c37857]
#>  rlang 0.4.11 [Hash: 515f341d3affe0de9e4a7f762efb0456]
#>  rlang 0.4.8  [Hash: 843a6af51414bce7f8a8e372f11d6cd0]
#> 
#> * Removed 3 packages from the cache.
dir.create("test1")
setwd("test1")

callr::r(function() {
  options(repos = "https://cloud.r-project.org")
  renv::init()
  renv::snapshot()
  renv::install("rlang")
  writeLines("library(rlang)", "packages.R")
  renv::snapshot()
})$Packages$rlang$Repository
#> [1] "CRAN"

setwd("..")

renv::purge("rlang")
#> The following packages will be purged from the cache:
#> 
#>  rlang 0.4.11 [Hash: 515f341d3affe0de9e4a7f762efb0456]
#> 
#> * Removed 1 package from the cache.
dir.create("test2")
setwd("test2")

callr::r(function() {
  options(repos = "https://packagemanager.rstudio.com/cran/2021-06-21")
  renv::init()
  renv::snapshot()
  renv::install("rlang")
  writeLines("library(rlang)", "packages.R")
  renv::snapshot()
})$Packages$rlang$Repository
#> [1] "RSPM"

setwd("..")

# The erratic behavior occurs when attempting a restore() + snapshot().
# In both repositories, the package's "Repository" entry is set to CRAN,
#   at least on macOS. This generates unnecessary VCS noise and has been
#   a source of moderate pain in the past months.

setwd("test1")
unlink("renv/library", recursive = TRUE)
callr::r(function() {
  renv::restore()
  renv::snapshot()
})$Packages$rlang$Repository
#> [1] "RSPM"

setwd("..")

setwd("test2")
unlink("renv/library", recursive = TRUE)
callr::r(function() {
  renv::restore()
  renv::snapshot()
})$Packages$rlang$Repository
#> [1] "RSPM"

setwd("..")
```

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by krlmlr** [comment]
Identical behavior with -85.

``` r
packageVersion("renv")
#> [1] '0.13.2.85'

# ...
```

Moving forward, what are our options here?

**Comment by krlmlr** [comment]
I propose to always use the moniker given to the repo in the `renv.lock` file. This resolves ambiguity and finally stabilizes the `renv.lock` format.

CC @pat-s.

**Comment by kevinushey** [comment]
I wonder if the issue here is that `renv` is finding a compatible version of the associated package in the cache, but the package the entered the cache was installed from CRAN (not RSPM) and so have a differing Repository: field set?

FWIW this is where `renv` tries to determine the Source + Repository for a package:

https://github.com/rstudio/renv/blob/master/R/snapshot.R#L660-L709

and note that this is all driven off of the package's DESCRIPTION file, so I think this implies that the Repository field is indeed flipping between CRAN and RSPM.

**Comment by krlmlr** [comment]
Not sure. The reprex purges the cache between the steps, the `"Repository"` field is different at installation vs. restore time.

In the code you pointed to, where does `dcf` come from? Can we extend the reprex to look at it?

Could we keep the repository field at installation time and not touch it during the snapshot if the version doesn't change?

**Comment by kevinushey** [comment]
Just pushed a change to `renv` that should hopefully help here. Can you give it a shot?

**Comment by krlmlr** [comment]
With -87 there's still the same behavior for the reprex on the M1 Mac.

I reviewed the code, it looks like it solves this particular corner case. We'll see how it works in practice. I'd still favor a solution where the `"Repository"` field is consistent with the `"Repository"` description in `renv.lock`, irrespective of the actual installation source.

**Comment by krlmlr** [comment]
Thanks for your fast responses and fixes!

**Comment by kevinushey** [comment]
> I'd still favor a solution where the "Repository" field is consistent with the "Repository" description in renv.lock, irrespective of the actual installation source.

FWIW, the general intention is that the R package's DESCRIPTION file is the source of truth; it feels a little bit odd to me to have a newly-generated `renv.lock` depend on a prior `renv.lock` (if any). But I think it makes sense in this narrow case to prevent spurious diffs.

However, the fact that `renv` kind of plays it fast-and-loose with package repositories (a package from repository A can be restored from repository B; alongside the MRAN + other shortcuts) means these kinds of spurious diffs can be more common, so it makes sense to catch and prevent some of the more common forms.

**Comment by krlmlr** [comment]
I see how `DESCRIPTION` should be the ground truth, but the `Repository` field is only part of the `DESCRIPTION` for packages installed locally. As you describe, packages can be restored from multiple sources.

I'm proposing to record, for each package, the first repository from which the package in this version can be installed, and to attempt installing from this repository first during a `restore()`. To me, recording the location from where a local package happened to have been installed feels odd. Or perhaps to not record the `"Repository"` field at all, or in a different file.

Maybe if renv had a logging facility that records installation sources during `install()` and `restore()`? These could be new files, one per non-empty install/restore, that accurately track the past installation processes. This permits answering questions like "I can't restore package {foobar}, where did other users get this package from in the past"?

**Comment by krlmlr** [comment]
Things have greatly improved with renv 0.14.0, no need to take immediate action here.
