### ISSUE TITLE
Issue installing pkg with `Additional_repositories:` set

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#786]
Hello!

I have a package that is hosted on GitHub, and it depends on a package from a non-CRAN repository (an R-Universe repo in this case).

I started with `Additional_repositories: https://ddsjoberg.r-universe.dev` in the DESCRIPTION file, but `renv::install()` failed to install.

I reviewed https://github.com/rstudio/renv/issues/221 and tried to mimic the instructions there, but cannot get `renv::install()` to install the package. Below is the log using `renv:::renv_error_handler`. At the moment the DESCRIPTION file has the following entries (after a number of iterations and various attempts).
```
Additional_repositories: https://ddsjoberg.r-universe.dev
RemoteType: standard
RemoteRef: ddsjoberg
RemoteRepos: https://ddsjoberg.r-universe.dev
RemotePkgType: binary
```

Do you have any tips for getting `renv::install("ddsjoberg/hotfun@rstudio_prefs")` to install without error and to properly log the dependencies?

Thank you! 💮 

```r
Restarting R session...

* Project 'C:/Users/sjobergd/Desktop/Delete/runi_test' loaded. [renv 0.13.2]
> options(error = renv:::renv_error_handler)
* Automatic snapshot has updated 'C:/Users/sjobergd/Desktop/Delete/runi_test/renv.lock'.
> renv::install("ddsjoberg/hotfun@rstudio_prefs")
Retrieving 'https://api.github.com/repos/ddsjoberg/hotfun/tarball/4d15c91553c033a08f9dc761ec7f9d371165bb25' ...
	OK [downloaded 137.3 Kb in 0.6 secs]
Error: package 'rstudio.prefs' is not available
Traceback (most recent calls last):
15: renv::install("ddsjoberg/hotfun@rstudio_prefs")
14: renv_retrieve(names(remotes))
13: handler(package, renv_retrieve_impl(package))
12: renv_retrieve_impl(package)
11: renv_retrieve_github(record)
10: renv_retrieve_package(record, url, path)
 9: renv_retrieve_successful(record, path)
 8: renv_retrieve(package)
 7: handler(package, renv_retrieve_impl(package))
 6: renv_retrieve_impl(package)
 5: records[[package]] %||% renv_retrieve_missing_record(package)
 4: renv_retrieve_missing_record(package)
 3: renv_available_packages_latest(package)
 2: stopf("package '%s' is not available", package)
 1: stop(sprintf(fmt, ...), call. = call.)
```

**Comment by kevinushey** [comment]
Thanks! I think this just hasn't yet been implemented in `renv`. The "simple" workaround, at least, is to explicitly add that repository to your R `repos` option, but it'd be nice if `renv` automatically handled this.

**Comment by ddsjoberg** [comment]
Thank you! I'll change from `Additional_repositoires:` to `Remotes:` for now.

**Comment by kevinushey** [comment]
Huh, you're right. It's a documented convention, but the only thing it's used for is `R CMD check` which verifies a package dependency might be available there...

**Comment by kevinushey** [comment]
... so I think `Remotes:` is going to be the right way forward; it's a convention supported more widely across the R ecosystem. @ddsjoberg let us know if that sounds reasonable?

**Comment by ddsjoberg** [comment]
Ahhh, I didn't realize the Additional Repositories wasn't taken into account in the standard install function. Apologies for the original post!
