### ISSUE TITLE
should 'local' package tarballs always be used?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#79]
Related to https://github.com/rstudio/renv/issues/43.

Suppose we have a package installed from CRAN, e.g.

```
[R/Package/Matrix]
Package=Matrix
Version=1.2-17
Source=CRAN
Hash=b10030fd8c964dbecd79719236d4a668
```

Now, suppose a local tarball for that package is available, at e.g.

```
<project>/renv/local/Matrix/Matrix_1.2-17.tar.gz
```

Should we consider installing from that tarball directly, skipping the attempt to download and install from CRAN? Should we consider doing this for all package sources? This would effectively allow 'local' sources to act as an override for packages which aren't otherwise retrievable (ie: it could be an escape hatch)

**Comment by michaelhogersosis** [comment]
Would it make sense to perhaps have a global or library level flag for defaulting to the <project>/renv/local/... tarball?

**Comment by kevinushey** [comment]
I've decided to turn this on by default now (since it's most likely that if someone takes the time to make a local tarball available, they want to use it). We can consider hiding this behind a user preference if this assumption is flawed.
