### ISSUE TITLE
Request: `renv::install()` to work with `Remotes:` tracking of the latest release on GitHub.

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#792]
Hello! Thank you for all the amazing work on renv !

I'm writing to request installation support (and subsequently recording and restore support) for packages in the `Remotes:` field that are tracking the latest release of a package, e.g. `Remotes: ddsjoberg/gtsummary@*release`. The release tracking is described here: https://cran.r-project.org/web/packages/remotes/vignettes/dependencies.html

When I attempt to install the dependencies from within the a package's project folder using the release tracking, this is the error I get.

```
* Project 'C:/Users/sjobergd/Desktop/Delete/gh.install.test' loaded. [renv 0.13.2]
> renv::install()
Error: failed to resolve remote 'ddsjoberg/gtsummary@*release' -- failed to retrieve 'https://api.github.com/repos/ddsjoberg/gtsummary/commits/*release' [error code 22]
In addition: Warning message:
curl: (22) The requested URL returned error: 422 Unprocessable Entity 
```

For reproducibility purposes, here is the DESCRIPTION file contents.

```
Package: gh.install.test
Type: Package
Title: What the Package Does (Title Case)
Version: 0.1.0
Author: Who wrote it
Maintainer: The package maintainer <yourself@somewhere.net>
Description: More about what it does (maybe more than one line)
    Use four spaces when indenting paragraphs within the Description.
License: What license is it under?
Encoding: UTF-8
LazyData: true
Imports: gtsummary
Remotes: ddsjoberg/gtsummary@*release
```

Thank you!

**Comment by kevinushey** [comment]
Thanks! This should now be supported in the development version of `renv` via https://github.com/rstudio/renv/commit/0c23386b907e4f218c1ca8f9133b5a0b76c3be7b. Let me know if it works as you expect.

**Comment by ddsjoberg** [comment]
Thank you @kevinushey 💯 🕺🏼
