### ISSUE TITLE
`renv::restore()` fails for git-based packages

### ISSUE THREAD

**Issue by kdkavanagh** [rstudio/renv#793]
Similar to #744 

Having trouble restoring a totally-empty (no cache) workspace - failing on a git package with a subdir.  Unlike the linked ticket above, my tmp directory is "standard", but even changing it does not solve the issue.  

Looking at the source code, we clone the git repo to the temp file provided as `path` and then later check to ensure `path` is not a directory - I'm not sure how this is compatible - the folder will always be a directory - tho the code seems to have been unchanged for 2 years....

```
Error: file '/tmp/RtmpN57aeD/renv-git-3308f81157f' exists but is a directory
Traceback (most recent calls last):
12: renv::restore()
11: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
10: retrieve(packages)
 9: handler(package, renv_retrieve_impl(package))
 8: renv_retrieve_impl(package)
 7: renv_retrieve_git(record)
 6: renv_retrieve_successful(record, path)
 5: renv_description_read(path, subdir = subdir)
 4: renv_filebacked(scope = "DESCRIPTION", path = path, callback = renv_description_read_impl,
        subdir = subdir, ...)
 3: callback(path, ...)
 2: stopf("file '%s' exists but is a directory", path)
 1: stop(sprintf(fmt, ...), call. = call.)
```

This occurs on 0.12.4, 0.13.2, and 0.13.2-82

**Comment by kevinushey** [comment]
Any chance you can share a reproducible example?

I think the error may be misleading here; I suspect `renv` is looking in the wrong sub-directory when trying to restore the package.

**Comment by kdkavanagh** [comment]
Unfortunately the git repos I'm installing from are private/internal

**Comment by kevinushey** [comment]
Can you share the lockfile field (redacting some pieces if necessary)? Is the package itself located within a sub-directory of the repository?

**Comment by kdkavanagh** [comment]
Yes, a subdirectory:

```
"myPackage": {
      "Package": "myPackage",
      "Version": "1.0.0",
      "Source": "Git",
      "RemoteType": "git2r",
      "RemoteUrl": "...",
      "RemoteSubdir": "r",
      "RemoteSha": "fb9ac8b7230028e7b14f11f9a725783e0aaec2ff",
      "Hash": "d5556772b1e1ccdb42fdbf5e6dff7e32"
    },
```

**Comment by kevinushey** [comment]
Here's a reproducible example:

```
renv::install("git@github.com:kevinushey/subdir.git:subdir", rebuild = TRUE)
```

I see:

> Error: failed to resolve remote 'git@github.com:kevinushey/subdir.git:subdir' -- file '/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T//RtmpqKud6O/renv-git-25b649407a44' exists but is a directory 

I believe we are indeed not handling sub-directories consistently.
