### ISSUE TITLE
Resolve calls of the form `renv::install("gitlab@<host>::<user>/<repo>")` to the default branch of the repo

### ISSUE THREAD

**Issue by jistria** [rstudio/renv#795]
Now that [GitLab have adopted a default branch name of `"main"` instead of `"master"`](https://docs.gitlab.com/ee/user/project/repository/branches/default.html), would it be possible to read the `default_branch` for repositories created on GitLab, and resolve calls of the form `renv::install("gitlab@<host>::<user>/<repo>")` to the declared `default_branch`, rather than always defaulting to `"master"`? Similar to the change made in response to #557; b570aa9.

**Comment by kevinushey** [comment]
Should now be implemented in the development version -- please give it a try and let me know if all looks well. Thanks!

**Comment by jistria** [comment]
Looks to be working as intended. Thanks very much!
