### ISSUE TITLE
Set path of .gitignore

### ISSUE THREAD

**Issue by chasset** [rstudio/renv#796]
Hello,

First, many thanks for this library.

I customize all these paths using the function `Sys.setenv` in a `.Rprofile`:

```bash
RENV_PATHS_ROOT=".local/lib/renv"
RENV_PATHS_LIBRARY=".local/lib/renv/library"
RENV_PATHS_BINARY=".local/bin/renv"
RENV_PATHS_CACHE=".cache/renv/cache"
RENV_PATHS_SOURCE=".cache/renv/source"
RENV_PATHS_LIBRARY_STAGING=".cache/renv/staging"
```

So, in RENV_PATHS_ROOT, one can find for example `.gitignore` and `activate.R` files.

Each time, I load R with renv, all works fine. `renv::restore()` tells us that:

```
* Project '~/' loaded. [renv 0.13.2]
* The library is already synchronized with the lockfile.
```

But, still, every time, a useless file `renv/.gitignore` is created. 

How could I force to use the path RENV_PATHS_ROOT  for this?

Best regards,

Pierre-Olivier

--

R version
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.0                         
year           2021                        
month          05                          
day            18                          
svn rev        80317                       
language       R                           
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen
```

**Comment by kevinushey** [comment]
Those files are always written to the project directory; e.g.

https://github.com/rstudio/renv/blob/fb671f6e2de9f8256632658ea685a72b05aeca26/R/infrastructure.R#L59-L79
https://github.com/rstudio/renv/blob/fb671f6e2de9f8256632658ea685a72b05aeca26/R/infrastructure.R#L89

This is so that the `renv` auto-loader can always find and use a stable path to the activate script on startup.
