### ISSUE TITLE
Using MRAN functionality behind a firewall - how can I prevent from using amazonaws.com downloaded file ?

### ISSUE THREAD

**Issue by arnauddeblic** [rstudio/renv#798]
Hello
Thanks for this very usefull package.
I would like to use the MRAN functionality offered by RENV in my company, on an environment without internet.
MRAN url is configured in the Sonar Nexus proxy, therefore I can install packages from MRAN in my R session.
However, I understand that RENV package needs to connect to amazonaws.com, when using MRAN functionality. In my environment, I've no access to amazonaws.com.
Is there a workaround, allowing to use MRAN functionality offered by RENV in such an environment ? Maybe by having the downloaded file locally ? Is there an evolution planned on the roadmap, allowing to address this use case ? For instance by providing the downloaded file within the RENV package ?
In advance many thanks
Kind regards

**Comment by kevinushey** [comment]
You could set the `RENV_MRAN_DATABASE_URL` to some URL of your own choosing that is accessible in your environment, and do some work externally to copy the `renv`-maintained database to that location.
