### ISSUE TITLE
renv::dependencies() unable to find .Rmd Packages Dependencies 

### ISSUE THREAD

**Issue by blue2609** [rstudio/renv#799]
Hi there, 

I'm very new to R and Renv and I'm having trouble using `renv::init()/renv::dependencies()` to find dependencies in a project R Markdown file. 

First of all, just want to make it clear that I'm running R and RStudio on my **MacBook Pro 16" 2019** with these specs:
- Operating System: macOS Big Sur 11.2.3
- CPU: Intel Core i9 2.3GHz 8-Core 
- Memory: 16GB 2667 MHz DDR4
- GPU: AMD Radeon Pro 5500M 4GB

Now, `renv::dependencies()` does not have any problem finding package dependencies for R files in my project but it's having difficulty in detecting these package requirements in an Rmarkdown file:

![image](https://user-images.githubusercontent.com/26863547/124846732-ce304080-dfdc-11eb-9d58-e7131b3165d3.png)

I already have `rmarkdown` package installed to the private project library and yet when I run `renv::dependencies()` from R console, this is the output that I got:

![image](https://user-images.githubusercontent.com/26863547/124847102-8c53ca00-dfdd-11eb-959e-363d32a764dd.png)

As you can see, it only detects `"rmarkdown"` package from the **Rmd** file. even though it should've detected:
- lubridate
- ggplot2
- data.table
- ggrepel
- dplyr
- tidyverse

Does anyone have the same issue with `renv::dependencies()` not being able to detect their R markdown package dependencies as well? 

Thanks in advance!!

**Comment by kevinushey** [comment]
This is because `renv` detects "used" dependencies, e.g. via `library(<package>)`. Technically speaking, `install.packages("<package>")` will install the requested package, but will not actually _use_ the installed package in the document (ie those packages won't actually be loaded yet).

If you were to explicitly load these packages e.g. via `library(tidyverse)` you should see `renv` pick it up. Is that sufficient?

**Comment by blue2609** [comment]
@kevinushey 

Ahhhhh, no no my bad, yeah I see how it is. 

Again I'm sorry, I'm very new to R and Renv but yeah it will only detect `library(package)` but it won't detect `install.packages(package)`. 

Sorry about that 😅

Thanks so much for the help @kevinushey !!! Feel free to close this issue~
