### ISSUE TITLE
renv::install(, type = "both") not supported => different behavior between utils::install.package and renv::install

### ISSUE THREAD

**Issue by hokkwan** [rstudio/renv#800]
I work on Windows and R without Rtools, because usually do not want to go through the hassle of compilation. Therefore when installing packages, I would like to install the highest version possible without compilation needed. This behavior is implemented by utils::install.package but not by renv::install. This seems to boil down to the support for argument type = "both".

**Could renv implements support for type = "both"?**
Such that in default situation the behavior is same between utils::install.package and renv::install?

**utils::install.package**
Calling utils::install.package will default in utils::install.package(, type = "both"), because getOption("pkgType") defaults in "both". In this case, the function first analyzes which binary and source versions are available **_and_** whether compilation is needed. Based on this analysis, the highest possible version is installed. So for table below, utils::install.package acts as follows:

- Rcpp: Source version 1.0.7 is highest but **_not_** installed because compilation is needed. Therefore binary version 1.0.6 is installed.
- bslib: Source version 0.2.5.1 is highest and installed, because no compilation needed

|       | binary | source  | needs_compilation |
|-------|--------|---------|-------------------|
| Rcpp  | 1.0.6  | 1.0.7   | TRUE              |
| bslib | 0.2.4  | 0.2.5.1 | FALSE             |

**renv::install**
renv::install seems not to support for type = "both" which causes an error and different behavior compared to utils::install.package, i.e. renv::install acts as follows:
- Rcpp: Source version 1.0.7 is highest and installed. Installation fails, because compilation is needed.
- bslib: Source version 0.2.5.1 highest and installed. Installation succeeds, because no compilation needed

**Comment by kevinushey** [comment]
Thanks; I just pushed a change to the development version of `renv` that should fix this.

**Comment by kevinushey** [comment]
```
> Sys.which("make")
make 
  "" 
> renv::install("Rcpp", type = "both", rebuild = TRUE)
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/4.1/Rcpp_1.0.6.zip' ...
	OK [downloaded 3.1 Mb in 0.4 secs]
Installing Rcpp [1.0.6] ...
	OK [installed binary]
Copying Rcpp [1.0.6] into the cache ...
	OK [copied to cache in 1.3 seconds]
```

**Comment by hokkwan** [comment]
Thanks @kevinushey for the quick response. Issue can be closed
