### ISSUE TITLE
renv::dependencies() skips R utility script files without file extension

### ISSUE THREAD

**Issue by klmr** [rstudio/renv#801]
I frequently use R to write command line utilities, especially to do common build tasks inside R projects. By common POSIX convention these scripts don’t have a filename extension, carry the executable flag, and contain a suitable shebang which execs Rscript (`#!/usr/bin/env Rscript`). They’re commonly located in a subdirectory called `scripts` or `build` or similar.

Unfortunately `renv::dependencies` doesn’t scan such files. Thus all dependencies used in these files are missed.

I’d be happy to submit a PR for this. As far as I can see this would entail adding a fallback to `renv_dependencies_callback` — something along these lines:

```diff
diff --git a/R/dependencies.R b/R/dependencies.R
index f883a7bf..48096cde 100644
--- a/R/dependencies.R
+++ b/R/dependencies.R
@@ -242,8 +242,14 @@ renv_dependencies_callback <- function(path) {
     ".rnw"         = function(path) renv_dependencies_discover_multimode(path, "rnw")
   )
 
-  cbname[[basename(path)]] %||% cbext[[tolower(fileext(path))]]
+  cbname[[basename(path)]] %||% cbext[[tolower(fileext(path))]] %||% {
+    if (is_r_executable(path)) renv_dependencies_discover_r(path)
+  }
+
+}
 
+is_r_executable <- function(path) {
+  grepl("^#!.*\\b(R|r|RScript)\\b", readLines(path, n = 1L))
 }
 
 renv_dependencies_find_extra <- function(root) {
```

Untested; of course a PR would include unit tests. Potentially this should also test the executable flag on systems which support this. — Maybe via `(file.info(path)$mode & S_IXUSR) != 0L` (with `S_IXUSR <- 64L`), but that code is probably platform-dependent (at the very least I’d have to check how Windows permissions map to POSIX file modes).

**Comment by kevinushey** [comment]
I'd be open to a PR. My main concern is we should do our best to avoid reading files that we won't need to read; e.g. perhaps we should only do this check for:

- Files that are executable,
- files that don't have an extension (?),
- Files that live in a particular directory (?)

Do we have a strategy for avoiding binary files (since binary executables might be included in an `renv` project)? I wonder if we should first read the file as binary (e.g. the first 512 bytes), discard anything containing a nul byte, and then try to parse the shebang line from that.

The counter-argument, I think, is that a well-constructed `.renvignore` would also be a fix for over-aggressive dependency scanning.

**Comment by klmr** [comment]
> we should only do this check for:
> * Files that are executable,

I’ve had another look, and this might be problematic on Windows: `file.access` hard-codes this check to look for the file extensions `.exe`, `.com` `.bat` and `.cmd` on Windows, since Windows doesn’t have an executable flag. This means that `dependencies()` would return a different result on Windows and on POSIX systems for the same project.

> * files that don't have an extension (?),

Good idea. This will still potentially miss stuff (POSIX users occasionally use “fake” extensions, e.g. `.run`) but they should be rare. And `.R` extensions are handled already.

> * Files that live in a particular directory (?)

I don’t think that will work: there isn’t really any convention around this, and executable scripts can reasonably be expected anywhere in the directory hierarchy in a non-package project.

I do think that we should try avoiding binary files: it’s easy, and in pathological cases we’d otherwise try to read a huge first “line”, and we’d have to handle warnings from NULs.
