### ISSUE TITLE
renv::init(restart = FALSE) does not create RStudio project file

### ISSUE THREAD

**Issue by hokkwan** [rstudio/renv#805]
Initializing a new renv project, but without an automatic restarts, fails to create a RStudio project file.
I would expect a RStudio project file to be created regardless whether restart = TRUE or FALSE.

**Comment by kevinushey** [comment]
`renv` is not responsible for creating or managing the RStudio project file (they are independent applications, even if they have some integrations).

**Comment by hokkwan** [comment]
To my understanding renv::init relies on rstudioapi::openProject to create and immediately open the RStudio project file.

Perhaps the following suggestion.

If renv::init(restart = FALSE) is called, could then rstudioapi::initializeProject be called instead which creates a RStudio project file but not immediately open, see [https://rstudio.github.io/rstudioapi/reference/projects.html](https://rstudio.github.io/rstudioapi/reference/projects.html)

**Comment by kevinushey** [comment]
Sorry, you are indeed correct! I'll take a look.

**Comment by kevinushey** [comment]
Sorry, I think I misunderstood the issue initially.

When calling `renv::init(restart = TRUE)`, if `renv` is running inside of RStudio, then we use RStudio APIs to re-open the project. This also implies creating the project file if it does not exist.

However, when calling `renv::init(restart = FALSE)`, we don't interact with the front-end (or RStudio) in any way, hence why the project file is not created.

If I understand correctly, your suggestion is to call `rstudioapi::initializeProject()` when calling `renv::init(restart = FALSE)` from within RStudio. That seems reasonable.

**Comment by hokkwan** [comment]
Yes exactly, when calling renv::init(restart = FALSE) from within RStudio, then a RStudio project file should be created.

**Comment by hadley** [comment]
Unless I misunderstand this code, it looks like it's already done:

https://github.com/rstudio/renv/blob/40aa593527e828fe392df24f566427ba04d2961d/R/activate.R#L82-L86
