### ISSUE TITLE
`install.packages()` shim doesn't fallback to `utils::install.packages()` correctly

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/renv#808]
The idea of the renv `install.packages()` shim is to handoff to `install()` if just a single argument is passed (`pkgs`), otherwise it falls back to `utils::install.packages()`.

But it doesn't seem like the fallback is passing through optional arguments correctly. For example, this installs the INLA package (which isn't on CRAN but is hosted elsewhere) when you aren't in an renv enabled project.

```r
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
```

However, if you run this from an renv enabled project, then you'll get an error that it can't find INLA:

```r
> install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
Installing package into ‘/Users/davis/Desktop/r/playground/temp/test-renv/renv/library/R-4.1/x86_64-apple-darwin17.0’
(as ‘lib’ is unspecified)
Warning message:
package ‘INLA’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

None of the optional arguments are getting passed through to `utils::install.packages()`, so it doesn't know about the extra repo.

The shim here looks like it passes dots through correctly:
https://github.com/rstudio/renv/blob/e8ccdda601ec208e387d769076aaa16ad4f86bb6/R/shims.R#L4-L11

But the formals of that shim are actually changed to align with `install.packages()` at package load time by `renv_shim()`
https://github.com/rstudio/renv/blob/e8ccdda601ec208e387d769076aaa16ad4f86bb6/R/shims.R#L38-L41
https://github.com/rstudio/renv/blob/e8ccdda601ec208e387d769076aaa16ad4f86bb6/R/shims.R#L51

**Comment by kevinushey** [comment]
Thanks for the bug report! Should hopefully be alleviated in the development version of `renv`.

**Comment by DavisVaughan** [comment]
Yep, I was able to install it now, thanks!
