### ISSUE TITLE
Feature Request: Add `renv.config.ask.snapshot` setting similar to `renv.config.auto.snapshot`

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#810]
hello @kevinushey ! This package has been invaluable to my team, thank you for all your work here!

Our team did some testing with the `renv.config.auto.snapshot` option set to TRUE. Overall, we liked the functionality. There are a growing number of packages that have dependencies listed in suggests that we utilize, and it was great to have these suggested dependencies automatically added to our lock files. 

But there were enough edge cases where we were getting unwanted snapshots. For example, we use packages from CRAN, our own internal RSPM, public GitHub, an internal Enterprise GitHub, and it happens every so often there is a package that cannot be restored. When working around this issue, we were often getting an auto snaps, locking in the more recent version of packages when we are trying to restore the previous versions.

To this end, what are you thoughts on implementing a `renv.config.ask.snapshot` option that will ask us each time the library changes if we'd like to snapshot?

Thank you!
Daniel

**Comment by kevinushey** [comment]
That sounds reasonable to me.

**Comment by hadley** [comment]
This would be a nice feature, giving an additional stage in between fully automatic snapshotting and manual snapshotting. However, it's quite a lot of work to implement (including thinking through how this would be surfaced in the IDE), and it's unlikely to make it to the top of our development TODO list any time soon. So for now, we'll close the issue, but it's still indexed via google and if many other people are interested, we can reconsider in the future.
