### ISSUE TITLE
Option to suppress activate-prompt in `snapshot()` called in an uninitialised project 

### ISSUE THREAD

**Issue by cstepper** [rstudio/renv#814]
Hi, 

we use `renv::snapshot(type = "explicit")` to create an *renv.lock*-file for R packages checking only the DESCRIPTION files (further used in CI/CD).
In the last version of *renv* (0.14.0), the user prompt was integrated to `renv::snapshot()`, if project has not been activated yet (#777).

Would it be possible to add an option to suppress/bypass this user-prompt (e.g. by adding an additional argument `ask_activate = TRUE/FALSE`?

Thanks

**Comment by fdetsch** [comment]
Or alternatively, provide a `y(es)/n(o)` canned response via an argument.

**Comment by kevinushey** [comment]
You should be able to use `options(renv.config.activate.prompt = FALSE)`. Does that help? The other option is to explicitly provide the library paths which you wish to snapshot. See https://github.com/rstudio/renv/blob/9344caf707ab31d7e6e64bc7c42215a052df19ad/R/activate.R#L138-L144 for more details.

**Comment by cstepper** [comment]
Hi @kevinushey ,
thanks for your comment. And yes, this helps.
We changed our code to 
`renv::snapshot(library = .libPaths(), type = "explicit")`
