### ISSUE TITLE
Change cache directory

### ISSUE THREAD

**Issue by liutiming** [rstudio/renv#816]
Thanks for this awesome package!

Current renv cache directory is: `~/.local/share/renv/cache/v5`

I wonder if I could change this away from `~`, because I am working on a cluster and there is not enough storage space under home directory.

Thank you!

**Comment by liutiming** [comment]
I will give `RENV_PATHS_ROOT` a try first

**Comment by kevinushey** [comment]
Yes, you can use `RENV_PATHS_ROOT` or `RENV_PATHS_CACHE` to adjust the cache path. Please see https://rstudio.github.io/renv/reference/paths.html for more details.
