### ISSUE TITLE
renv+GHA cache woes "Error: incompatible virtual environment already exists"

### ISSUE THREAD

**Issue by cboettig** [rstudio/renv#817]
Hi folks,

We're using renv in an R+python project with a renv configuration based on `r-lib/actions`.  After stable use for some time, we now seem  to have hit a problem I can't manage to debug.  It seems to be related to cache, commits that previously passed now fail.  The problem seems to occur immediately on any call to R.  Sorry I'm not sure how to create a `reprex` of this issue.

What does "incompatible virtual environment already exists" mean? Of course the virtualenv already exists (presumably because we just ran `renv::restore()` in the previous GH-Actions step), but why then does renv suddenly think it is incompatible?  This feels like a caching issue, but I don't understand how the cache could become invalid when renv.lock etc haven't changed.  

Here's the trace:

```
Run Rscript -e "rmarkdown::render('appendices/appendix-B-examples.Rmd')"
Error: Error: incompatible virtual environment already exists at path '/home/runner/work/rl-intro/rl-intro/renv/python/virtualenvs/renv-python-3.8.5'
Traceback (most recent calls last):
18: source("renv/activate.R")
17: withVisible(eval(ei, envir))
16: eval(ei, envir)
15: eval(ei, envir)
14: local(...)
13: eval.parent(substitute(eval(quote(expr), envir)))
12: eval(expr, p)
11: eval(expr, p)
10: eval(quote(...), new.env())
 9: eval(quote(...), new.env())
 8: renv_bootstrap_load(project, libpath, version)
 7: renv::load(project)
 6: renv_load_python(project, lockfile$Python)
 5: renv_load_python_env(fields, renv_use_python_virtualenv)
 4: loader(project = project, version = version, name = name)
 3: renv_python_virtualenv_validate(path, python, version)
 2: stopf(fmt, path)
 1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
Error: Process completed with exit code 1.
````

## Links: 

[GH-Actions config](https://github.com/boettiger-lab/rl-intro/blob/main/.github/workflows/render_rmarkdown.yml)
[GH-Actions log](https://github.com/boettiger-lab/rl-intro/pull/41/checks?check_run_id=3304028974)

**Comment by kevinushey** [comment]
To confirm, what version of `renv` are you using? Was the version of Python updated on the image or something like that?

If you have a `requirements.txt` file, you should be able to remove the virtual environment and let `renv` restore the Python environment and let `renv` re-generate it. Does that help?

**Comment by cboettig** [comment]
Hi @kevinushey ! Thanks for the reply -- just to clarify, this issue only appears on GitHub Actions runner I link above, where our action is based on @jimhester 's https://github.com/r-lib/actions/blob/master/examples/render-rmarkdown.yaml, which installs the current version of `renv` from RSPM (0.14.0) now.  

The repository does have a committed [requirements.txt](https://github.com/boettiger-lab/rl-intro/blob/main/requirements.txt), and uses the `renv`'s automatic .gitignore settings; so that the virtual environment itself is not being committed to GitHub and a fresh clone of the repo should already result in a repo with no pre-built virtualenv and just let renv rebuild it.

However, as you know, the GH-Action recipe from `r-lib/actions` for render markdown linked above includes the creation of a `renv` cache, https://github.com/r-lib/actions/blob/master/examples/render-rmarkdown.yaml#L24-L29, which is why I believe this is a GitHub Caching issue.  Unfortunately I don't know how to get GitHub to purge the action cache (https://github.com/actions/cache/issues/2 has been an open issue for years), so I don't know how to remove the virtual environment from GitHub's runner and let `renv` regenerate it as you suggest.  

Sorry if I'm missing something here and let me know if this should be filed as in issue in https://github.com/r-lib/actions if it seems that the issue is due to that configuration and not related to `renv` per se?

**Comment by kevinushey** [comment]
If you look at the build log, it looks like your project is still configured to use `renv 0.13.2` so even though you try to manually install `renv 0.14.0` on restore `renv 0.13.2` gets re-installed over the previously-installed 0.14.0 copy.

Can you update the version of `renv` used here? https://github.com/boettiger-lab/rl-intro/blob/main/renv.lock#L549-L555

A lot of work went into polishing the Python-related workflows with `renv 0.14.0` so I'm hopeful the issue will be resolved after that's fixed up. In particular, in renv 0.14.0, the error you're seeing should now be a much clearer warning:

https://github.com/rstudio/renv/blob/9344caf707ab31d7e6e64bc7c42215a052df19ad/R/python-virtualenv.R#L22-L39

**Comment by cboettig** [comment]
Thanks @kevinushey! Bumping the `renv` version in the lockfile worked -- sorry I should have realized we would have the `renv` version locked and not actually keep the one from `install.packages()`.  One unexpected gotchas was that I did have to upgrade Rcpp as well, (`renv::restore()` was working, but suddenly `library(reticulate)` started complaining about a missing Rcpp function... (see https://github.com/boettiger-lab/rl-intro/pull/42)

Anyway, all is well now.  Thanks again for the amazing work on `renv`+python, and for the rapid replies!

**Comment by kevinushey** [comment]
No worries, glad we were able to get it sorted!
