### ISSUE TITLE
function to add a repository to lockfile

### ISSUE THREAD

**Issue by tjmahr** [rstudio/renv#819]
I can't find anything in the documentation or issues about this but it would be nice to be able to register to a repository. Something like

```
renv::add_repo(stan = "https://mc-stan.org/r-packages/")
```

And then have the Repositories in the lockfile update to include this entry. 

I am aware of using the .Rprofile to update options, but I would favor a programmatic way. The alternative in #786 (using the DESCRIPTION file) would also be cool though.

**Comment by zkamvar** [comment]
What I've found to work is to temporarily set the options for the repositories you want in the lockfile before doing any snapshotting. Eg: https://github.com/carpentries/sandpaper/blob/9b886c0ff2b4ed93ca632cac3a008fa2c5132fda/R/renv.R#L107-L117

**Comment by tjmahr** [comment]
Appears to be fixed in 15.0. Thanks!

> `renv::snapshot() gains the repos argument, to be used to force the lockfile to be generated with the requested set of R repositories encoded within.`
