### ISSUE TITLE
renv should be able to bootstrap itself from the repository specified in renv.lock

### ISSUE THREAD

**Issue by ajirnyi** [rstudio/renv#820]
Currently, renv tries to download & install itself from cloud.r-project.org which caused trouble in environments with limited internet access. Related SO: https://stackoverflow.com/questions/68892428

It would be nice if it could _first_ check if a matching version of `renv` is available in (i) the repository that is specified in renv.lock, or, failing that, (ii) repositories in `.libPaths()`. 

It is a bit counterintuitive that an online repo is used even when `renv.lock` explicitly specifies an internal repository as a source for renv.

It would also be nice to allow offline deployment bundled with package tarballs.

**Comment by kevinushey** [comment]
This has now been implemented in the development version of `renv` -- thanks for the request!
