### ISSUE TITLE
renv captures Suggest-dependencies although package.dependency.fields does not contain "Suggest"

### ISSUE THREAD

**Issue by MarselScheer** [rstudio/renv#823]
Used versions: 

- rocker/verse:4.1.0
- renv 0.14.0

Steps to reproduce:

1. Create a package (for instance with `usethis::create_package("suggestdemo")`)
2. Run `renv::init()` and restart the R session
3. Add the Suggest-field to the DESCRIPTION file (for instance `Suggests: knitr`)
4. Run `renv::status()`

That results in:

```
The  following package(s) are used in the project, but are not installed:

	knitr

Consider installing these packages, and then using `renv::snapshot()`
to record these packages in the lockfile.

```
My expectation would be to NOT see that message. At least that is the way I understand the documentation of `package.dependency.fields` when calling `?renv::settings`

**Comment by bollard** [comment]
+1

I'm expiring the same issue, using renv 0.15.5

**Comment by hadley** [comment]
Closing in favour of #1019.
