### ISSUE TITLE
`renv` CI cache bust best practices

### ISSUE THREAD

**Issue by mrkaye97** [rstudio/renv#826]
Hey @kevinushey

We've been running into an issue in our CI, where we have an internal package that lives in a monorepo (which is about 300mb), that we update very often. This ends up leading to re-installs and re-caches of the new versions of the package often (multiple times a day). The issue is that our CI cache -- we use Circle, but AFAICT it'd be the same on GHA or anything else -- is growing by the size of the entire monorepo on every new install. It seems to me that this is happening because `renv` is downloading a tarball of the entire repo, unpacking it, installing the package, and then caching the entire repo and package instead of just caching the package and getting rid of the cruft. 

Is this mental model right? And if so, what's the best practice advice for not blowing up the size of our CI cache? RIght now it's almost 10gb because of installs over the past couple weeks, and growing fast. I can think of a bunch of ways to manually cache bust, but it'd be nice if there were a way to just clean up after myself on the install instead.

Let me know, and thanks!

**Comment by kevinushey** [comment]
I don't think so, but I'm not positive (you'd have to look at what's in the cache to be certain). `renv` basically just copies whatever would be in the R library path after install into the cache, so it _shouldn't_ be copying anything superfluous that isn't used post-install.

Is there any way for you to poke inside the CI cache and confirm if it is indeed the `renv` cache entries for that package occupying all the space?

**Comment by mrkaye97** [comment]
Yeah, I can do that and report back. I have a hunch that this is probably an R issue and not an `renv` issue, but I'm not 100% sure. Will get back to you on the CI front tomorrow probably. Thanks again

**Comment by mrkaye97** [comment]
Alright @kevinushey, I believe I've found the issue. AFAICT, here's the problem: In our CI, there's a directory at `~/.local/share/renv/` that contains three subdirectories. One of them is `cache`, which holds the package cache and is a normal package cache size. There's another one, though, named `source`, which has two subdirs: `github` and `repository`. The `github` subdir is 7Gb, because it holds all of the tarballs for all of the past installs.

Again, I'm still not sure if this is an `renv` issue, an R issue, or a CI issue, but I'm starting to lean towards `renv` because those `source/*` subdirs are living inside of `~/.local/share/renv`. Any thoughts on that? My mental model for what should happen is that I should be able to easily purge those `source/` tarballs if I want to (or maybe auto-clean up on install?) but again, not totally sure how all the mechanics work. WDYT?

**Comment by kevinushey** [comment]
Those are indeed cached by `renv`; the intention being that users might want to ensure a copy of the package sources are kept locally in case access to CRAN (or whatever internet resource was providing that package) was not available.

However, in practice this is likely burdensome, especially since we don't provide a way of cleaning up older packages.

I think you could safely delete the `source` directory, and set the `RENV_PATHS_SOURCE` environment variable to some place in the R temporary directory so that `renv` doesn't try to store package sources in the cache. See https://rstudio.github.io/renv/reference/paths.html for more details.

**Comment by mrkaye97** [comment]
@kevinushey Circling back -- I think deleting `source/` solves it. I'm not sure if I even need to set the `RENV_PATHS_SOURCE` env var, since I'm just restoring packages once, copying them into a container, and that's it. (Let me know if I'm missing something and that's a terrible idea for some reason). 

Thanks for the pointers! Closing this issue.
