### ISSUE TITLE
in Rstudio, package remains unticked when entering `library(package)` in console

### ISSUE THREAD

**Issue by rinkjames** [rstudio/renv#827]
I'm new to renv so I may be missing something, but I noticed the above and had to check which packages are currently loaded with `(.packages())`.

Bascially, entering `library(dplyr)` in RStudio console seems to attach dplyr but dplyr remains unticked in RStudio's Project Library. This is happening in an RStudio project that has 'Use renv with this project' ticked in project options, but this doesn't appear to happen outside of projects.

Is this renv or Rstudio?

**Comment by kevinushey** [comment]
This would be an RStudio issue. What version of RStudio are you using? Have you already tried updating to the latest release?

**Comment by rinkjames** [comment]
Yeah it's version 1.4.1717 macOS. I'm also noticing that if I manually tick a package and then filter packages using the search bar, the tick is gone when I reset the search bar to dispaly all packages again. Irritating.

Recommendations? I'm using homebrew rstudio
