### ISSUE TITLE
A temporary path on .libPaths() is left after renv fails to install a package

### ISSUE THREAD

**Issue by llrs** [rstudio/renv#830]
Many thanks for providing this package. It has make it easier to be sure which versions I use between machines. 

When a package installation fails renv leaves a temporary directory on `.libPaths()`, which later causes confusion when installing, as the packages go to the temporary directory instead of the project library.

This happened when installing some package dependencies that depend on Bioconductor when those packages are not present. I don't remember the exact packages as I found that I could use `renv::use("package", library = .libPaths()[2])` as a workaround.

Maybe an on.exit call, `withr::with_libpaths` or similar strategies could be used to prevent this?

**Comment by kevinushey** [comment]
Can you please provide a reproducible example, or at least confirm what renv APIs you were calling when you observed this?

**Comment by kevinushey** [comment]
> I don't remember the exact packages as I found that I could use renv::use("package", library = .libPaths()[2]) as a workaround.

`renv::use()` intentionally places a temporary library path on the `.libPaths()` by default, as per its documentation.

**Comment by llrs** [comment]
Apologies! I've have mixed both without fully reading the documentation. May I suggest to describe this more prominently on the description side of renv::use (instead of details)
