### ISSUE TITLE
bug in `renv:::renv_lockfile_from_manifest`

### ISSUE THREAD

**Issue by elong0527** [rstudio/renv#832]
It seems `record` shall be `entry`

https://github.com/rstudio/renv/blob/471b6a395619645cb6acf0cfcc2fac6666c17988/R/manifest-convert.R#L52
https://github.com/rstudio/renv/blob/471b6a395619645cb6acf0cfcc2fac6666c17988/R/manifest-convert.R#L52

**Comment by elong0527** [comment]
The code piece below shall probably be exchanged. 

Current: 
```
source <- entry[["Source"]]
names(source) <- entry[["Repository"]]
```

Suggest:
```
source <- entry[["Repository"]]
names(source) <-  entry[["Source"]]
```

**Comment by kevinushey** [comment]
You are indeed correct, thank you for spotting that!
