### ISSUE TITLE
rcmdcheck fails on 'installing the package to build vignettes' when library not installed in R_HOME

### ISSUE THREAD

**Issue by jabenninghoff** [rstudio/renv#833]
I'm using renv 0.14.0 on macOS with a homebrew installation of R (`brew install --formula r`).

Running rcmdcheck within the project is normally successful:

```
> rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✓  checking for file ‘.../DESCRIPTION’ ...
─  preparing ‘rdev’: (2s)
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✓  creating vignettes (2.9s)
─  checking for LF line-endings in source and make files and shell scripts (749ms)
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘rdev_0.4.0.tar.gz’
   
── R CMD check ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─  using log directory ‘/private/var/folders/4v/k12n8ksn77l4_bcsvc6kfgk00000gn/T/RtmpIVbwHy/file15a41d0c76ca/rdev.Rcheck’
─  using R version 4.1.1 (2021-08-10)
─  using platform: x86_64-apple-darwin18.7.0 (64-bit)
─  using session charset: UTF-8
─  using option ‘--no-manual’
✓  checking for file ‘rdev/DESCRIPTION’ ...
─  this is package ‘rdev’ version ‘0.4.0’
─  package encoding: UTF-8
✓  checking package namespace information
✓  checking package dependencies (830ms)
✓  checking if this is a source package
✓  checking if there is a namespace
✓  checking for executable files ...
✓  checking for hidden files and directories
✓  checking for portable file names ...
✓  checking for sufficient/correct file permissions
✓  checking whether package ‘rdev’ can be installed (2.4s)
✓  checking installed package size ...
✓  checking package directory
✓  checking ‘build’ directory
✓  checking DESCRIPTION meta-information ...
✓  checking top-level files
✓  checking for left-over files
✓  checking index information ...
✓  checking package subdirectories ...
✓  checking R files for non-ASCII characters ...
✓  checking R files for syntax errors ...
✓  checking whether the package can be loaded (667ms)
✓  checking whether the package can be loaded with stated dependencies (604ms)
✓  checking whether the package can be unloaded cleanly (617ms)
✓  checking whether the namespace can be loaded with stated dependencies (624ms)
✓  checking whether the namespace can be unloaded cleanly (661ms)
✓  checking loading without being on the library search path (707ms)
✓  checking dependencies in R code (829ms)
✓  checking S3 generic/method consistency (945ms)
✓  checking replacement functions (606ms)
✓  checking foreign function calls (597ms)
✓  checking R code for possible problems (1.7s)
✓  checking Rd files ...
✓  checking Rd metadata ...
✓  checking Rd cross-references ...
✓  checking for missing documentation entries (595ms)
✓  checking for code/documentation mismatches (1.8s)
✓  checking Rd \usage sections (1s)
✓  checking Rd contents ...
✓  checking for unstated dependencies in examples ...
✓  checking installed files from ‘inst/doc’ ...
✓  checking files in ‘vignettes’ ...
✓  checking examples (904ms)
✓  checking for unstated dependencies in ‘tests’ ...
─  checking tests ...
✓  Running ‘testthat.R’ (1.3s)
✓  checking for unstated dependencies in vignettes ...
✓  checking package vignettes in ‘inst/doc’ ...
─  checking running R code from vignettes
     ‘analysis-package-layout.Rmd’ using ‘UTF-8’... OK
    NONE
✓  checking re-building of vignette outputs (461ms)
   
   
── R CMD check results ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── rdev 0.4.0 ────
Duration: 20s

0 errors ✓ | 0 warnings ✓ | 0 notes ✓
```

However, if I remove devtools from R_HOME/site-library, rcmdcheck fails, even after running `renv::install(devtools)` within the project:

```
> rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✓  checking for file ‘.../DESCRIPTION’ ...
─  preparing ‘rdev’: (4.9s)
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
   Warning message:
   could not load renv from project "/private/var/folders/4v/k12n8ksn77l4_bcsvc6kfgk00000gn/T/Rtmp9xfABd/Rbuild15d5b7fb6915/rdev"; reloading previously-loaded renv 
─  installing *source* package ‘rdev’
─  using staged installation
─  R
─  byte-compile and prepare package for lazy loading
   Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
     there is no package called ‘devtools’
   Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
   Execution halted
   ERROR: lazy loading failed for package ‘rdev’
─  removing ‘/private/var/folders/4v/k12n8ksn77l4_bcsvc6kfgk00000gn/T/Rtmp9xfABd/Rinst15d5baafe5cb/rdev’
         -----------------------------------
   ERROR: package installation failed
Error in proc$get_built_file() : Build process failed
```

After removing the vignette, rcmdcheck is once again successful - this issue **only** occurs when trying to create the vignette. I first noticed this problem on a [CI Check](https://github.com/jabenninghoff/rdev/runs/3750688489) and was able to reproduce it in my local IDE.

Please let me know if any additional information is needed. Thanks!

**Comment by MartinSchobben** [comment]
I can confirm this issue with renv 0.14.0-8 installed from the master branch. Calling R CMD build locally executes without problems, while CI with Travis and the [GitHub R-CMD-check workflow](https://github.com/MartinSchobben/bookkeeper/runs/3777696644?check_suite_focus=true) fails when building the package at the equivalent line.

My work-around for now is building the package without rendering the vignettes (`--no-build-vignettes`) or deleting the `library()` call in the vignette to my development package. 

I have the impression that the issue occurs when `rmarkdown::html_vignette` renders an R script that loads the development package (e.g., the default vignette template when calling: `usethis::use_vignette()`).

**Comment by jabenninghoff** [comment]
> I have the impression that the issue occurs when `rmarkdown::html_vignette` renders an R script that loads the development package (e.g., the default vignette template when calling: `usethis::use_vignette()`).

My [vignette](https://github.com/jabenninghoff/rdev/blob/main/vignettes/analysis-package-layout.Rmd) includes no R code, only Markdown. It's interesting that you can work around the issue by removing the `library()` call.

**Comment by jabenninghoff** [comment]
The problem appears to occur when `ensure_installed()` is called within [`build.R`](https://github.com/wch/r-source/blob/tags/R-4-1-1/src/library/tools/R/build.R).  This code is only called when building a vignette.

**Comment by MartinSchobben** [comment]
II scrapped the part of deleting `library()` call, as it does not solve the error. I thought I explicitly tested this case, but I did not.

**Comment by kevinushey** [comment]
Does a plain `R CMD check` work, without the `rcmdcheck` package in the mix?

**Comment by MartinSchobben** [comment]
I get the same error when performing CI with Travis, where I follow the recommendations of the [vignette](https://rstudio.github.io/renv/articles/ci.html).

**Comment by jabenninghoff** [comment]
> Does a plain `R CMD check` work, without the `rcmdcheck` package in the mix?

I was able to replicate the error after removing devtools from R_HOME/site-library and running R CMD build from the Terminal within RStudio:

```
$ R CMD build rdev
* checking for file ‘rdev/DESCRIPTION’ ... OK
* preparing ‘rdev’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
Warning message:
could not load renv from project "/private/var/folders/4v/k12n8ksn77l4_bcsvc6kfgk00000gn/T/RtmpUNEflk/Rbuild14db74b3467d3/rdev"; reloading previously-loaded renv 
* installing *source* package ‘rdev’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘devtools’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘rdev’
* removing ‘/private/var/folders/4v/k12n8ksn77l4_bcsvc6kfgk00000gn/T/RtmpUNEflk/Rinst14db75d8c7437/rdev’
      -----------------------------------
ERROR: package installation failed
```

What's really interesting is that the same command runs fine within a terminal session outside RStudio:

```
$ R CMD build rdev
* checking for file ‘rdev/DESCRIPTION’ ... OK
* preparing ‘rdev’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Removed empty directory ‘rdev/analysis’
Omitted ‘LazyData’ from DESCRIPTION
* building ‘rdev_0.4.1.9000.tar.gz’
```

I may have some time to compare the environments later today.

**Comment by jabenninghoff** [comment]
Update: it definitely appears contained to the R CMD build process. Running `R CMD build` without renv loaded (in terminal outside RStudio) and then running `R CMD check` with renv loaded (in terminal inside RStudio) works.

**Comment by kevinushey** [comment]
```
* installing the package to build vignettes
      -----------------------------------
Warning message:
could not load renv from project "/private/var/folders/4v/k12n8ksn77l4_bcsvc6kfgk00000gn/T/RtmpUNEflk/Rbuild14db74b3467d3/rdev"; reloading previously-loaded renv 
```

My guess here is that R launches an R sub-process to build vignettes, but the `renv` library isn't inherited or used by that sub-process and so anything in the `renv` library is missed.

If that is the case, I presume this could be reproduced in any R package project using `renv` that also has vignettes to be built and bundled in the package. Does that sound correct?

**Comment by jabenninghoff** [comment]
That sounds right to me, and it looks like that's what's happening in [`build.R`](https://github.com/wch/r-source/blob/tags/R-4-1-1/src/library/tools/R/build.R), within `temp_install_pkg`.

**Comment by jabenninghoff** [comment]
The fix for this is to auto-activate renv in R CMD INSTALL per https://rstudio.github.io/renv/news/index.html#renv-0-14-0-unreleased by setting RENV_ACTIVATE_PROJECT to TRUE. I added the following to my `.Rprofile`:

```r
# auto-activate renv in R CMD INSTALL per
#   https://rstudio.github.io/renv/news/index.html#renv-0-14-0-unreleased
Sys.setenv(RENV_ACTIVATE_PROJECT = "TRUE")
```

**Comment by kevinushey** [comment]
To that effect, I'm curious whether this commit fixes the issue for you, even without `RENV_ACTIVATE_PROJECT` set:

https://github.com/rstudio/renv/commit/35807477008e7a3189274a62eb2695beeef80250

**Comment by niekdt** [comment]
I can't speak for jabenninghoff, but your commit https://github.com/rstudio/renv/commit/35807477008e7a3189274a62eb2695beeef80250 fixed the issue for my package (latrend) on macOS, ubuntu and Windows. Thanks!
