### ISSUE TITLE
[FR] Configuration option to change renv.lock name

### ISSUE THREAD

**Issue by DanChaltiel** [rstudio/renv#836]
Hi,

This is a simple feature request to have an option in renv to change the `renv.lock` file name.

Indeed, the `.lock` file extension is associated with some ransomware and is thus hard blacklisted by some cloud management systems, such as the one I'm using, Nextcloud: https://github.com/nextcloud/ransomware_protection/issues/60#issuecomment-777661232. This unfortunately makes `renv` unusable in my workplace.

In my case, having the sysadmins change the system security parameters is not doable.

If the name and extension of this file were changeable, this would solve the problem.

**Comment by hadley** [comment]
IMO this is a problem with Nextcloud, not renv.

**Comment by DanChaltiel** [comment]
Just for the record, this issue has now a solution.
Just rename `renv.lock` to something else and set the `RENV_PATHS_LOCKFILE` environment variable in your `.Rprofile` before activating `renv`:
```r
Sys.setenv(RENV_PATHS_LOCKFILE="renv.json")
source("renv/activate.R")
```

It works with Nextcloud 😁
