### ISSUE TITLE
Attempting to rebuild a yet-to-be-installed package gives an uninformative error

### ISSUE THREAD

**Issue by kmishra9** [rstudio/renv#838]
Context: I've just upgraded R from V3 to V4 and am restoring my packages for my project. Things error and require a rebuild:
```
* installing *source* package ‘scales’ ...
** package ‘scales’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package ‘munsell’ was installed before R 4.0.0: please re-install it
Execution halted
ERROR: lazy loading failed for package ‘scales’
* removing ‘/tmp/RtmpcYZ26h/renv-staging-710fa0f147a/scales’
```

When I try to `renv::rebuild()` a package that has yet to be installed in the "new" `renv` project library, I get the following cryptic error: 
```
renv::rebuild('munsell')

#> Error in vapply(x, `[[`, ..., FUN.VALUE = character(1)) : 
#> values must be length 1,
#> but FUN(X[[1]]) result is length 0
```

To get rid of this error, the appropriate set of steps is:
```
renv::install('munsell') # Copies the V3 version into the cache
renv::rebuild('munsell') # Reinstalls the package from scratch so it's compatible with V4
```

At minimum, it feels like the appropriate behavior on a `rebuild` call should be a more informative error, but the ideal solution is probably to simply build the package from scratch on any `rebuild` call, regardless of whether it exists in the project library already or not.

Hope that's helpful feedback! :)

**Comment by kevinushey** [comment]
This seems to do the expected thing for me with the development version of `renv`:

```
renv::remove("munsell")
renv::rebuild("munsell")
```

gives

```
> renv::remove("munsell")
* Removing package(s) from library '~/Library/R/x86_64/4.1/library' ...
Removing package 'munsell' ... Done!
> renv::rebuild("munsell")
The following package(s) and their dependencies will be reinstalled:
          _
  munsell   [0.5.0]

Do you want to proceed? [y/N]: 
```

**Comment by kmishra9** [comment]
Thanks, that’s perfect. Appreciate it!
