### ISSUE TITLE
Warn/error when snapshotting the development version of a package

### ISSUE THREAD

**Issue by daattali** [rstudio/renv#841]
I have an existing project that I wanted to run on another machine. I called `renv::init()` on the machine A, committed to git, and pulled from machine B. On machine B I ran `renv::restore()` and kept getting errors. It seems that any package that was installed on machine A that was installed from source locally is being considered as if it was from CRAN. For example the latest {shinycssloaders} on CRAN is version 1.0.0 but locally I'm working on a new version so on my machine I had version 1.0.0.9000, and this is what the renv.lock file had:

```
    "shinycssloaders": {
      "Package": "shinycssloaders",
      "Version": "1.0.0.9000",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "08d8f6984ea3ad3a3eeea9f139e68f79"
    },
```

I understand that local sources can be problematic and I don't expect it to work magically, but I do think it should at least warn me and make it clear that this package is NOT from CRAN. When I ran `init()` it should have clearly warned me that there are packages that are from local source.

**Comment by kevinushey** [comment]
The associated logic comes from here:

https://github.com/rstudio/renv/blob/master/R/snapshot.R#L684-L697

What do you think the right solution here is?

**Comment by daattali** [comment]
I don't know if there is currently a way for locally installed packages to work in renv when restored on a different machine.

If yes: I would expect "Source" or "Repository" to be "local" instead of CRAN, and when trying to restore if I don't have the source available on this machine then I should get an explicit error saying package X was installed from local source but is not available.

If not: when doing a snapshot I should get an error of at least a message letting me know package X has been installed from a local source and therefore may not be restoreable for others.

**Comment by hadley** [comment]
Seems like a warning on snapshot would be a nice feature here.

**Comment by daattali** [comment]
I would say that an error would be even better than a warning in this case, because a warning is easy to miss, and something like this seems urgent enough to warrant a fatal error. Perhaps you can have some flag to allow the snapshot to continue even when this error happens.

**Comment by kevinushey** [comment]
Adding a bit of extra context, I think the confusion in `renv` arises because:

- A package called 'shinycssloaders' is indeed available from CRAN,
- However, that particular version of 'shinycssloaders' is not available on CRAN (since it's the development version of the package)

Normally, `renv` tries to determine a package's source based only on the contents of the DESCRIPTION file, but falls back to assuming packages which are available on CRAN can be assumed to be retrieved from CRAN. That's what this fallback is doing:

https://github.com/rstudio/renv/blob/81fecb07fcc78cabb61b5309875e59484727b090/R/snapshot.R#L784-L800

Perhaps in here:

https://github.com/rstudio/renv/blob/81fecb07fcc78cabb61b5309875e59484727b090/R/snapshot.R#L813-L822

we should check the package version against what happens to be available from CRAN, and only accept it if it seems to be available (or perhaps an older version)?

We could also disallow packages with "development" version components, e.g. where the last version component is 9000 or greater (since CRAN doesn't accept packages with large version components like that anyhow)

**Comment by daattali** [comment]
> disallow packages with "development" version components

That won't solve the issue IMO. Firstly, not everyone follows the dev versioning system. But even for people who do, like myself, it's entirely possible to have a non-dev version available but not have it on CRAN. Sometimes I've had proper versions on GitHub but didn't submit them to CRAN until a few versions later because .... CRAN. I don't know if there's a good solution other than making sure the installed version is on CRAN.

**Comment by hadley** [comment]
In rsconnect, we now compare the package version to the latest on CRAN and declare it "development" if it's higher. That's not a perfect heuristic either, but it's pretty safe.

**Comment by hadley** [comment]
Another idea from @jennybc  if package was installed from local source, try to determine the dev home by inspecting the `Url`/`BugReports` fields (I think we have existing code for this in usethis or devtools).

**Comment by jennybc** [comment]
Yeah I bumped my shins on exactly this today, deploying a Shiny document to Connect (I happened to have a few packages installed locally from source).

`usethis::use_dev_package()` introduces a dependency in `DESCRIPTION` on a dev package, in the `Remotes:` field. If the remote isn't specified, it tries to make an educated guess with this helper, which is the heart of what @hadley's alluding to:

https://github.com/r-lib/usethis/blob/418bc89a5bc4e116315656d9a58b775d34e9cf81/R/package.R#L99-L128

**Comment by kevinushey** [comment]
@hadley do you think this is worth implementing for the 1.0.0 release? If not feel free to punt.

**Comment by hadley** [comment]
@kevinushey yeah, I think so, just because it's the commonest cause of renv annoyance for me and my team (but I doubt it affects many other users)

**Comment by jennybc** [comment]
> Is it okay to infer that a package installed from sources is compatible with whatever the remote inferred from a DESCRIPTION file might be? It seems like this will be wrong if you were working on a feature branch, since the inference would still probably conclude you want to use "main".

This seems reasonable to me (I'm assuming some sort of message alerts me to this inference). I think the vast majority of dev versions I have installed locally are from `main` and I have not installed from a specific commit for specific reasons. I feel like if I'm allowing my dependecies to be inferred (vs. specifying them explicitly), I've signed up for tolerating this amount of wiggle and "best effort" guessing.

**Comment by daattali** [comment]
This might be obvious, but since it's impossible to take care of these edge cases, it should at least be documented in {renv} that local installations are not going to work reliably.

**Comment by kevinushey** [comment]
Maybe we should just update the package's DESCRIPTION profile post-hoc with our guess of the package remote.

**Comment by kevinushey** [comment]
Or alternatively, packages could encode their remote details in the DESCRIPTION file by default, and then strip those out during R CMD build for package submission?

**Comment by jennybc** [comment]
If I have a DESCRIPTION file, I absolutely use it to record this info and take full responsibility for keeping DESCRIPTION up-to-date.

When I bumped into this problem, it was in a different context: I was deploying a single `.Rmd` to Connect. There was no intentional use of renv at all, but obviously it's getting used behind the scenes.

**Comment by kevinushey** [comment]
Here's the behavior now if you call `renv::snapshot()`, and one of the packages in the project library was installed from sources:

```
> renv::snapshot()
The following package(s) were installed from sources, but may be available from the following remotes:

- rlang  [r-lib/rlang]

Would you like to use these remote sources for these packages?
See 'snapshot.inference' in ?renv::config for more details.
Otherwise, these packages will be recorded with an unknown source.


Allow renv to update the remote sources for these packages? [Y/n]:
```

After selecting yes, the installed package's DESCRIPTION file is updated with the requisite remote information, e.g.

```
> utils::packageDescription("rlang")
Package: rlang
Version: 1.1.1.9000
Title: Functions for Base Types and Core R and 'Tidyverse' Features
Description: A toolbox for working with base types, core R features
        like the condition system, and core 'Tidyverse' features like
        tidy evaluation.
Authors@R: c( person("Lionel", "Henry", ,"lionel@posit.co", c("aut",
        "cre")), person("Hadley", "Wickham", ,"hadley@posit.co",
        "aut"), person(given = "mikefc", email =
        "mikefc@coolbutuseless.com", role = "cph", comment = "Hash
        implementation based on Mike's xxhashlite"), person(given =
        "Yann", family = "Collet", role = "cph", comment = "Author of
        the embedded xxHash library"), person(given = "Posit, PBC",
        role = c("cph", "fnd")) )
License: MIT + file LICENSE
ByteCompile: true
Biarch: true
Depends: R (>= 3.5.0)
Imports: utils
Suggests: cli (>= 3.1.0), covr, crayon, fs, glue, knitr, magrittr,
        methods, pillar, rmarkdown, stats, testthat (>= 3.0.0), tibble,
        usethis, vctrs (>= 0.2.3), withr
Enhances: winch
Encoding: UTF-8
RoxygenNote: 7.2.3
Roxygen: list(markdown = TRUE)
URL: https://rlang.r-lib.org, https://github.com/r-lib/rlang
BugReports: https://github.com/r-lib/rlang/issues
Config/testthat/edition: 3
Config/Needs/website: dplyr, tidyverse/tidytemplate
Author: Lionel Henry [aut, cre], Hadley Wickham [aut], mikefc [cph]
        (Hash implementation based on Mike's xxhashlite), Yann Collet
        [cph] (Author of the embedded xxHash library), Posit, PBC [cph,
        fnd]
Maintainer: Lionel Henry <lionel@posit.co>
Built: R 4.3.1; aarch64-apple-darwin20; 2023-07-08 01:09:19 UTC; unix
RemoteType: github
RemoteHost: api.github.com
RemoteUsername: r-lib
RemoteRepo: rlang
RemoteRef: main
GithubHost: api.github.com
GithubRepo: rlang
GithubUsername: r-lib
GithubRef: main
```

**Comment by kevinushey** [comment]
I think this can be closed now. `renv` is warning / notifying sufficiently when a package is installed from local sources, and happens to be newer than whatever is available currently on CRAN.

For example, using a development version of `ggplot2` installed from sources:

```
> renv::init()
- Linking packages into the project library ... Done!
The following package(s) were installed from an unknown source:
- ggplot2 [3.4.4.9000]
renv may be unable to restore these packages in the future.
Consider reinstalling these packages from a known source (e.g. CRAN).

The following package(s) will be updated in the lockfile:

# CRAN -----------------------------------------------------------------------
- cli            [* -> 3.6.1]
- colorspace     [* -> 2.1-0]
- fansi          [* -> 1.0.5]
- farver         [* -> 2.1.1]
- glue           [* -> 1.6.2]
- gtable         [* -> 0.3.4]
- isoband        [* -> 0.2.7]
- labeling       [* -> 0.4.3]
- lattice        [* -> 0.21-8]
- lifecycle      [* -> 1.0.4]
- magrittr       [* -> 2.0.3]
- MASS           [* -> 7.3-60]
- Matrix         [* -> 1.6-4]
- munsell        [* -> 0.5.0]
- nlme           [* -> 3.1-164]
- pillar         [* -> 1.9.0]
- pkgconfig      [* -> 2.0.3]
- R6             [* -> 2.5.1]
- RColorBrewer   [* -> 1.1-3]
- rlang          [* -> 1.1.2]
- scales         [* -> 1.3.0]
- tibble         [* -> 3.2.1]
- utf8           [* -> 1.2.4]
- vctrs          [* -> 0.6.5]
- viridisLite    [* -> 0.4.2]
- withr          [* -> 2.5.2]

# RSPM -----------------------------------------------------------------------
- mgcv           [* -> 1.9-0]

# Repository -----------------------------------------------------------------
- renv           [* -> 1.0.3.9000]

# (Unknown Source) -----------------------------------------------------------
- ggplot2        [* -> 3.4.4.9000]

The version of R recorded in the lockfile will be updated:
- R              [* -> 4.3.1]

- Lockfile written to "/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.HiUszFEeqB/renv.lock".
- renv activated -- please restart the R session.
```
