### ISSUE TITLE
`renv::snapshot()` removes the `"Name"` of an existing Python venv

### ISSUE THREAD

**Issue by rpln** [rstudio/renv#843]
When inheriting an existing `venv` with `renv::use_python(name = "./myvenv")`

The `renv.lock` file is populated correctly at `Python.Name`; e.g. below:

```
  "Python": {
    "Version": "3.8.10",
    "Type": "virtualenv",
    "Name": "./myvenv"
  },
```

But after running `renv::snapshot()`, the name is changed to null, e.g. below

```
  "Python": {
    "Version": "3.8.10",
    "Type": "virtualenv",
    "Name": null
  },
```

And this forces `renv` to create a new blank `venv` within the `renv` directory when the project is opened again. If I manually put it back to `"./myvenv"` then it works fine, but this requires a manual change after each `renv::snapshot()`.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I've reproduced this locally as well, and will take a look.

**Comment by kevinushey** [comment]
I believe this should now be better handled in the development version of `renv`. Would you be willing to upgrade and test? You can use:

```
renv::upgrade(version = "master")
```

to upgrade `renv` to the development version in a particular project.

**Comment by rpln** [comment]
@kevinushey, based on your instructions I've tested this with `renv 0.14.0-144` and it now seems to be fixed, thanks!

**Comment by kevinushey** [comment]
Great news! Thanks for taking the time to test and report back.
