### ISSUE TITLE
renv::install download directory

### ISSUE THREAD

**Issue by johnyaku** [rstudio/renv#844]
When `renv::install()` downloads a package, where is the tarball downloaded and extracted?
Are there environment variables or configuration settings that control this download destination?

Context: I am trying to use `renv` with a Singularity container. I say 'with' rather than 'in' because the container filesystem is read-only, so that only directories from the host filesystem that have been specifically bound to the container are writable.  I have bound a host directory to act as the `renv` cache and pointed `renv` to this directory with `RENV_PATHS_CACHE` in `.Renviron`. 

However, `renv::install()` fails at the decompression step, and I suspect that this is because it is happening in a directory in the container file system that is not writable (perhaps `/var` or `/tmp`, for example). 

Thanks for your help, and for a great tool!

**Comment by kevinushey** [comment]
> but downloading from GitHub still failed

Can you provide a reproducible example? AFAIK `renv` should only ever try downloading or mutating files in:

- One of the `RENV_PATHS_*` directories;
- The R temporary directory (as seen by `tempdir()`),
- The project library.
