### ISSUE TITLE
User Library & Project Library

### ISSUE THREAD

**Issue by James-G-Hill** [rstudio/renv#846]
Hello, not sure if this is an issue, and if it's not, maybe more prominent documentation may help as I haven't been able to find an answer to my question / problem.

Previously, when activating and using renv in my R packages my Packages pane would show a 'System Library' and a 'Project Library'.  The 'System Library' has core R packages; the 'Project Library' has the packages that are installed and recorded in the lockfile.

However, I now have a package that has a 'User Library' in place of the 'System Library'.  I don't understand why and if there's any impact?  The package and renv seem to work as normal but I spent time trying to fix another issue wondering whether this was a problem.

Any ideas?  Is there something in the documentation that I've missed?

**Comment by kevinushey** [comment]
I believe this is only a UI issue in RStudio -- there shouldn't be any functional issue. (RStudio tries to detect whether the "user" library is located within the project directory and call it a "project" library in that case; it sounds like that detection might be failing on your machine but we'd need more information to accurately diagnose)

**Comment by dsolito** [comment]
I have the same behaviour. Some project use a "user library", other "project library".
