### ISSUE TITLE
Ability to copy user's `.Rprofile` contents to project `.Rprofile` on activation/initialization

### ISSUE THREAD

**Issue by arnold-c** [rstudio/renv#847]
I'm currently testing out VSCode-R for a bit of fun and am running into some problems that I believe are related to `{renv}`'s structure, namely due to the use of a project `.Rprofile`. As mentioned in #692 , it's possible to set up `renv.config.user.profile` through setting `RENV_CONFIG_USER_PROFILE = TRUE` in `.Renviron`, but I think it'd be a useful feature to be able to copy the contents of the user's `.Rprofile` to the project's, maybe through an argument like `renv::init/activate(import_rprof = TRUE)`? 

I think this would help in situations that the default `renv.config.user.profile` is trying to avoid, particularly where you may have multiple ongoing projects that aren't consistent in their `.Rprofile` requirements and you don't want to have to keep resetting `renv.config.user.profile` as you switch between projects. It might also aid reproducibility if people do have packages listed in their User's `.Rprofile`, as they wouldn't be tracked otherwise.

Not sure if this would be a simple addition, so feel free to ignore if not feasible. Thanks for the work.

**Comment by kevinushey** [comment]
Thanks for the feature request, but I don't think this is a right fit for `renv` -- I think the existing infrastructure (control whether or not the user `.Rprofile` is run on startup) is more appropriate; if users wanted to clone their user profile for each project, I'd suggest doing that manually.
