### ISSUE TITLE
Issue with renv::restore for local / custom packages in 0.14.0 but not 0.12.0-3

### ISSUE THREAD

**Issue by stevejburr** [rstudio/renv#849]
I have been experiencing difficulties in using renv::restore with a local package file in version 0.14.0, the same approach works fine in a previous version 0.12.0-3. 

I can't see anything in the change log which suggests this is expected behavior due a deliberate/breaking change but maybe I've missed something.

The use case is using a renv.lock file to replicate a set of packages used on a local install in the creation of a docker image.

The problem is that when I run renv::restore renv tries to find the local package on CRAN and fails. With an older renv version, this works fine.

I can't share the actual package but an example renv.lock file would be something like:

```
{
  "R": {
    "Version": "4.1.1",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Packages": {
    "customPackage": {
      "Package": "customPackage",
      "Version": "0.1.7",
      "Source": "/path/to/package/customPackage_0.1.7.tar.gz"
    }
  }
}
```

The error will be something like:

```
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/customPackage/customPackage_0.1.7.tar.gz' ...
Error: failed to retrieve package 'customPackage'
```

It looks like at the start of the renv::restore process it knows this isn't a CRAN package -

```
The following package(s) will be updated:
/path/to/package/customPackage_0.1.7.tar.gz ==
customPackage         [* -> 0.1.7]
```

This is being run within an Ubuntu 20.04 docker image.

**Comment by kevinushey** [comment]
Thanks -- I think this should be resolved in the development version of `renv`. Would you be willing to test and verify?

**Comment by stevejburr** [comment]
Yes, just tried the latest version from GitHub and this is resolved. Thanks a lot.

**Comment by kevinushey** [comment]
Awesome; thanks for taking the time to verify!
