### ISSUE TITLE
Migrating existing packrat project to renv

### ISSUE THREAD

**Issue by rpodcast** [rstudio/renv#85]
I am already seeing much better performance with renv as compared to packrat, and I'm exploring how to perform a migration from an existing project using packrat to renv in an semi-automated way.  Thanks to the local sources [vignette](https://rstudio.github.io/renv/articles/local-sources.html), it looks like I could reference the `packrat/src` directory from the first project as a __local source__ (temporarily) and ensure this directory would be used for the initial "restore" in the renv project.  

However, that alone doesn't suffice because I still need to convert the packrat lockfile to the renv lockfile format.  Are there a set of functions I could utilize to translate the packrat lockfile?  Also is there a better way to go about this type of migration?

**Comment by kevinushey** [comment]
Not yet, but migration is something that I've been thinking about. It seems like it shouldn't be difficult to convert from a Packrat lockfile to an `renv` lockfile.

**Comment by kevinushey** [comment]
I've put together a function (currently unexported) for migrating a project in the development version of `renv`:

```
renv:::renv_migrate_packrat("/path/to/packrat/project")
```

It will take care of migrating the Packrat infrastructure in a project to `renv` as much as possible. Of course, since there isn't a 1-to-1 correspondence between Packrat and `renv` features yet, some bits may get lost.

If you have a sample Packrat project you'd like to test this on, I'd appreciate it. (Consider backing up the project beforehand just to be safe)

**Comment by rpodcast** [comment]
I did a quick test on a packrat project that intentionally had an older version of a particular package.  After creating that test packrat project, I created a separate renv project just to run the migration function (which asked me to install `packrat` and I did).  Running  `renv_migrate_packrat()` seemed to work at least without visible errors.  Throwing in some additional observations:

* `renv.lock` looks to have the same packages and versions as the packrat lock file 
* Running `renv::status()` in the migrated project says the project is syncronized with the lock file
* I checked the cache directory at `~/.local/share/renv/cache` and the only package I saw in the cache directory was `packrat` itself (likely from that separate `renv` project mentioned above).  I didn't see any of the other packages that were in the packrat project.  It looks like the migration installs the packages in the project's `renv/library` and not the cache directory, is that correct?

**Comment by kevinushey** [comment]
Thanks for taking the time to test! I agree we should try to migrate packages in the Packrat library to the renv cache -- let me add that. Good to hear that everything is working as intended otherwise!

**Comment by kevinushey** [comment]
I've just pushed a change that should ensure the packages copied from the Packrat library are now also moved into the Packrat cache.

**Comment by kevinushey** [comment]
I've now documented and exported the `renv::migrate()` function, for migrating functions from Packrat to renv.

**Comment by ckiefer** [comment]
I just tried to migrate my R project from Packrat to Renv with `renv::migrate()` function. However, it didn't copy the packages to the cache directory at `~/.local/share/renv/cache`. Instead, it put everything into the project-specific `renv/library/R-3.5/x86_64-pc-linux-gnu/` directory.

If I instead to a `renv::init()` it downloads and installs them into the cache directory, but for some packages not the version specified in the `packrat.lock` file (I need exactly does versions). Any help would be highly appreciated.

**Comment by kevinushey** [comment]
Any chance you can provide a reproducible example? Is your project public so that I might try testing and seeing what's happening myself?

**Comment by ckiefer** [comment]
Unfortunately the project is not public. I just re-run it with an empty Renv cache and a copy of the same, not-yet-migrated Packrat project (see my screenshots below).

Project before migration:
![1_Project_before_migration](https://user-images.githubusercontent.com/8458235/61688883-71231d80-ad26-11e9-97e0-261576b8ad4f.png)

Empty cache before migration:
![2_Empty_cache_before_migration](https://user-images.githubusercontent.com/8458235/61688884-71231d80-ad26-11e9-8f64-53389f589e0d.png)

Project when I go into R:
![3_Project_load_packrat_stuff](https://user-images.githubusercontent.com/8458235/61688885-71231d80-ad26-11e9-828a-8d06f67154a3.png)

Migration:
![4_Migration](https://user-images.githubusercontent.com/8458235/61688886-71bbb400-ad26-11e9-9324-e414af06f378.png)

Project after migration:
![5_Project_after_migration](https://user-images.githubusercontent.com/8458235/61688887-71bbb400-ad26-11e9-98e9-d2d4c35a4a38.png)

Cache after migration:
![6_Cache_after_migration](https://user-images.githubusercontent.com/8458235/61688888-71bbb400-ad26-11e9-9832-da76232d429f.png)
