### ISSUE TITLE
Should version numbers be used in the remoteSHA field?

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#850]
I noticed that with recent `{renv}` dev versions the `remoteSHA` field gets set to a version number for CRAN packages.

This breaks some logic I have in `capsule` to catch a situation where packages have the same version numbers but different SHAs.

That is I assumed the presence of a SHA in the lockfile, and no sha in the local library indicates a situation where the packages have the same version with different SHAs (common with dev packages) and I throw a warning.

I can fix this, but I would question the use of a field for SHAs for version numbers. These are different concepts, and the version number is already a separate field.

**Comment by kevinushey** [comment]
Are you sure this is being done by renv and not the repository providing your packages? (Can you share a reproducible example?)

**Comment by MilesMcBain** [comment]
Ack you're right. It's getting added by `pak`. Do you think I should raise this over there?

**Comment by kevinushey** [comment]
It's worth bringing up, at least to ask if that's intentional.
