### ISSUE TITLE
rmarkdown identified as dependency for qmd without code chunks

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#852]
The `renv::dependencies` call is identifying `rmarkdown` as a dependency for Quarto content that does not use R and has no executable chunks.

```bash
quarto create-project quarto-simple --type website
#=> Creating project at /FILESYSTEM-PATHS/quarto-simple:
#=>  - Created _quarto.yml
#=>  - Created index.qmd
#=>  - Created about.qmd
#=>  - Created styles.css
R -s -e 'renv::dependencies("quarto-simple")'
#=>Finding R package dependencies ... Done!
#=>                                                      Source   Package Require
#=>1 /FILESYSTEM-PATHS/quarto-simple/about.qmd rmarkdown
#=>2 /FILESYSTEM-PATHS/quarto-simple/index.qmd rmarkdown
#=>  Version   Dev
#=>1         FALSE
#=>2         FALSE
```

Related: https://github.com/rstudio/packrat/pull/634 - avoids adding `rmarkdown` as a dependency to all `*.qmd`.

The packrat change may not be completely correct, as it is not adding `rmarkdown` back to the dependency list upon discovering an executable code chunk.

**Comment by kevinushey** [comment]
This should be resolved now via https://github.com/rstudio/renv/commit/2abff8c60bf4ae11544ef87cc2023f90b05358a3 (+ some other later changes).
