### ISSUE TITLE
renv::restore() attempts to install package that is not on lockfile 

### ISSUE THREAD

**Issue by paupaiz** [rstudio/renv#853]
I am trying to build a Docker container image where i `COPY` in a renv.lock file in the dockerfile. I made sure to `renv::purge("BiocNeighbors")` but during the build process, `renv::restore` still tries to install BiocNeighbors. I am having a similar problem with Biocmanager. Please let me know what information you need so I can be more helpful. 

<img width="439" alt="Screen Shot 2021-11-04 at 10 04 13 PM" src="https://user-images.githubusercontent.com/59720098/140597811-5d24c882-cdb3-4fd2-9a66-6a635ba93be2.png"
![Screen Shot 2021-11-05 at 3 45 45 PM](https://user-images.githubusercontent.com/59720098/140597823-3b6b175f-4b95-46d2-a016-da450b4b41d3.png)
>

**Comment by kevinushey** [comment]
`purge()` only removes a package from the global cache; it does not remove that package from the lockfile. You probably want something like:

```
renv::restore(exclude = c("BiocNeighbors"))
```

**Comment by paupaiz** [comment]
Thank you @kevinushey! that worked. I included this line before: `renv::install("BiocNeighbors")` because I still need BiocNeighbors but I am getting the following error: 
#14 0.832 > renv::install("BiocNeighbors")
#14 1.511 Error: package 'BiocNeighbors' is not available
#14 1.513 Traceback (most recent calls last):
#14 1.513 7: renv::install("BiocNeighbors")
#14 1.513 6: retrieve(names(remotes))
#14 1.513 5: handler(package, renv_retrieve_impl(package))
#14 1.513 4: renv_retrieve_impl(package)
#14 1.513 3: renv_available_packages_latest(record$Package)
#14 1.513 2: stopf("package '%s' is not available", package)
#14 1.513 1: stop(sprintf(fmt, ...), call. = call.)
#14 1.513 Execution halted
------
executor failed running [/bin/sh -c R -e 'renv::install("BiocNeighbors")']: exit code: 1

Looking forward to your response!

**Comment by kevinushey** [comment]
By default, `renv::install()` will attempt to install a package from the package repositories as declared by `getOption("repos")`. Because `BiocNeighbors` is a Bioconductor package, you need:

```
renv::install("bioc::BiocNeighbors")
```

Note that `BiocNeighbors` depends on a large number of other R packages so you may see those required dependencies installed as well.

**Comment by paupaiz** [comment]
alright! Thanks again @kevinushey I really admire all your work with renv! it's a great solution

**Comment by kevinushey** [comment]
Thanks! I'm going to close this issue as resolved; please feel free to re-open or file a new issue if you have any other questions.
