### ISSUE TITLE
`renv::dependencies` doesn't pick up packages specified as `base_format` in `rmarkdown` header

### ISSUE THREAD

**Issue by zandergordan** [rstudio/renv#854]
If I open a new RStudio project and create an `rmarkdown` file with the following content, `renv::dependencies` will list my dependencies as `rmarkdown`, `renv`, and `rticles`.

```
---
title: "renv::dependencies detects packages in output format"
author: Zander

output: rticles::plos_article

---

Text.
```

If I replace that with the following content to [enable cross-referencing](https://bookdown.org/yihui/bookdown/a-single-document.html) from the `bookdown` package, `renv::dependencies` now lists `rmarkdown`, `renv`, and `bookdown`, but fails to list `rticles`. 

```
---
title: "but renv::dependencies doesn't detect packages in nested base_format"
author: Zander

output:
  bookdown::pdf_book:
    base_format: rticles::plos_article

---

Text.
```

I am for now working around this by placing a 1-line R file in my project that calls `library(rticles)`, so that `renv` doesn't try to remove `rticles` from my lock-file every time I call `renv::snapshot`.

**Comment by kevinushey** [comment]
Should now be handled via https://github.com/rstudio/renv/commit/8de42eaddf8fd6636bfb98ac1c018c77072b6c81 -- thanks for the report!
