### ISSUE TITLE
Best Practise: Renv with R Package & Plumber

### ISSUE THREAD

**Issue by RDalziel** [rstudio/renv#855]
//Disclaimer: I'm new to R with a background in C# & Javascript

I'm working on a sample to expose an R Package as an API with renv supporting the dependency management and reproducibility. The API itself is exposed in a docker container.

Below is my folder structure:
![image](https://user-images.githubusercontent.com/3485935/140648072-7914e8bd-2c30-47ac-a17e-10939b89971d.png)

The Plumber script within plumber.R is simple. It just attempts to call into the HelloWorld package.

`
helloworld::sayhello()
`

Locally i can run things like devtools::load_all() or remotes::install_local(dependencies = FALSE) to bring helloworld into scope. This is fine but it does create a bit of an interesting setup on my docker container. 

```
RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv')"

COPY . .

RUN  find . -type f -print0 | xargs -0 dos2unix

RUN R -e "renv::install('remotes')"
RUN R -e "renv::restore()"
RUN R -e "remotes::install_local(dependencies = FALSE)"
```

The install of remotes on the first line to pull in renv is out of scope following renv::restore() moving the package paths.

This is pointing towards me mis-understanding something fundamental here. What's the correct way to proceed here? Ideally i could pull the local package into the context via renv configuration alone or perhaps there's a different method?

**Comment by kevinushey** [comment]
Is https://rstudio.github.io/renv/articles/docker.html helpful here?

I'm a bit confused why you want to use both `renv::restore()` and `remotes::install_local(dependencies = FALSE)`; in theory, you should only need `renv::restore()`, assuming your lockfile contains all the packages your Dockerfile requires.

Regardless, I think what you have is otherwise correct -- can you elaborate on what you're concerned about?

**Comment by RDalziel** [comment]
The issue is with the _local_ package. The helloworld package code contained in /R & described in the DESCRIPTION file is not in scope to the plumber API code in inst/plumber/helloworld/plumber.R and renv:restore() only contains remote packages so does not bring it into context.

It looks like the missing piece i haven't figured out is how to describe the local package to renv such that it'll hook it up as part of the restore process.

**Comment by kevinushey** [comment]
Got it, thanks for clarifying -- that makes sense. If that's the case, I think the steps here would be something like:

```
RUN R -e "renv::restore()"
RUN R CMD build /path/to/helloworld
RUN R CMD INSTALL /path/to/helloworld_1.0.tar.gz  # change version number as appropriate
```

In other words, you'd use `renv::restore()` to restore the packages which `helloworld` depends on, and then explicitly install the `helloworld` package via R's own tooling. Then, I believe your Dockerfile entrypoint would call a function in the `helloworld` package that starts up your Plumber API. Does that sound correct?

**Comment by RDalziel** [comment]
That's pretty much exactly it.  Plumber just runs off Main.R which doesn't have any local package refs directly but each of the endpoints will most likely call out to local lib functions.

remotes::install_local does this in a sense and drops it in the renv/library folder. But it feels like a heavy command for the task.

**Comment by RDalziel** [comment]
So just to make sure i'm following: you feel that:

```
RUN R -e "remotes::install_local(dependencies = FALSE)
```
Is the best way to currently achieve what you described above as:
```
RUN R CMD build /path/to/helloworld
RUN R CMD INSTALL /path/to/helloworld_1.0.tar.gz  # change version number as appropriate
```

**Comment by kevinushey** [comment]
Yes, I think so.

**Comment by RDalziel** [comment]
Brilliant! Cheers for the steer! :)
