### ISSUE TITLE
`Unable to find conda binary` with `use_python()` on M1 mac

### ISSUE THREAD

**Issue by juliasilge** [rstudio/renv#857]
I am having trouble getting renv to see/use the correct Python environment on my M1 mac. I install Python generally [using these instructions](https://gist.github.com/juliasilge/035d54c59436604d6142ebebf29aa224), with [Miniforge](https://github.com/conda-forge/miniforge) that works on ARM. 

Outside of renv, I do not have trouble using this environment with reticulate:

``` r
reticulate::py_discover_config("tensorflow")
#> python:         /Users/juliasilge/miniforge3/envs/tf_env/bin/python
#> libpython:      /Users/juliasilge/miniforge3/envs/tf_env/lib/libpython3.8.dylib
#> pythonhome:     /Users/juliasilge/miniforge3/envs/tf_env:/Users/juliasilge/miniforge3/envs/tf_env
#> version:        3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:27:18)  [Clang 11.1.0 ]
#> numpy:          /Users/juliasilge/miniforge3/envs/tf_env/lib/python3.8/site-packages/numpy
#> numpy_version:  1.19.2
#> tensorflow:     /Users/juliasilge/miniforge3/envs/tf_env/lib/python3.8/site-packages/tensorflow
#> 
#> NOTE: Python version was forced by RETICULATE_PYTHON
```

<sup>Created on 2021-11-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

With renv, though, it says it can't find conda:

``` r
renv::use_python(python = "~/miniforge3/envs/tf_env/bin/python", type = "conda")
#> Error: Unable to find conda binary. Is Anaconda installed?
```

<sup>Created on 2021-11-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kevinushey** [comment]
That is a bit surprising, since `renv` should just be using `reticulate` APIs here for conda environments. Does `reticulate:::find_conda()` succeed for you?

Setting `options(reticulate.conda_binary = path.expand("~/miniforge3/bin/conda"))` beforehand should also work, I think. (assuming conda is indeed available at that location)

**Comment by juliasilge** [comment]
This is outside of an renv project:
``` r
reticulate:::find_conda()
#>                                    conda 
#> "/Users/juliasilge/miniforge3/bin/conda"
```

<sup>Created on 2021-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is inside the renv project:

``` r
reticulate:::find_conda()
#> NULL
```

<sup>Created on 2021-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I am happy to report that `options(reticulate.conda_binary = path.expand("~/miniforge3/bin/conda"))` does work, though. If I run that right after opening the renv project, I can use reticulate.

**Comment by kevinushey** [comment]
Are the same versions of reticulate being used in each case?

It might also depend on where `conda` is on the PATH -- what does `Sys.which("conda")` report in each case?

**Comment by juliasilge** [comment]
Outside of renv:

``` r
Sys.which("conda")
#>                                    conda 
#> "/Users/juliasilge/miniforge3/bin/conda"
reticulate:::find_conda()
#>                                    conda 
#> "/Users/juliasilge/miniforge3/bin/conda"
```

<sup>Created on 2021-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Inside of renv:

``` r
Sys.which("conda")
#> conda 
#>    ""
reticulate:::find_conda()
#> NULL

options(reticulate.conda_binary = path.expand("~/miniforge3/bin/conda"))
Sys.which("conda")
#> conda 
#>    ""
reticulate:::find_conda()
#> [1] "/Users/juliasilge/miniforge3/bin/conda"
```

<sup>Created on 2021-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kevinushey** [comment]
Do you know why the PATH differs in each case?

**Comment by juliasilge** [comment]
Oh gosh, I was definitely hoping you could tell me that, as this seems to be the main source of my problem. When I open the renv project, it just will not recognize the conda binary. If you want to see the project's `renv.lock`, [it is here](https://github.com/EmilHvitfeldt/smltar/blob/master/renv.lock).

**Comment by kevinushey** [comment]
This should be solved in the development version of `reticulate`, as we now support discovery of miniforge installations by default.
