### ISSUE TITLE
renv::dependencies does not include "shiny" as a dependency for parameterized R Markdown

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#859]
Given a directory containing only the following `index.Rmd`:

````markdown
---
params:
  color: "red"
---

```{r}
params$color
```
````

Running `renv::dependencies` against that directory does not report a dependency on `shiny`.

```bash
R -s -e 'options(width=150);renv::dependencies(".",quiet=TRUE)'
#>                                                                           Source   Package Require Version   Dev
#> 1 /Users/aron/dev/rstudio/standalone/renv-dependencies/shiny-param-rmd/index.Rmd rmarkdown                 FALSE
```

Compare to the dependencies reported by `packrat:::dirDependencies` (ignore the warning).

```bash
R -s -e 'options(width=150);packrat:::dirDependencies(".")'
#> [WARNING] This document format requires a nonempty <title> element.
#>   Defaulting to 'index.knit' as the title.
#>   To specify a title, use 'title' in metadata or --metadata title="...".
#> [1] "rmarkdown" "shiny"
```

**Comment by aronatkins** [comment]
Note: The `shiny` dependency is helpful should folks want to call `rmarkdown::knit_params_ask("index.Rmd")` and configure the content parameters ahead of a render.

The `rsconnect` package forces an implicit dependency on `shiny` for parameterized R Markdown documents; this is external to any dependency analysis by packrat or renv. https://github.com/rstudio/rsconnect/blob/312f70e9b24c5a4e85080c0350af288706166785/R/bundle.R#L688-L721

**Comment by aronatkins** [comment]
`packrat` has this logic to add a `shiny` dependency upon non-empty parameters:
https://github.com/rstudio/packrat/blob/f16d36ec1f5dc643fbddc13f5ffc7420f2f6445f/R/dependencies.R#L304-L305

**Comment by kevinushey** [comment]
Should now be handled with https://github.com/rstudio/renv/commit/b90e629b0f5a905ac68468feea37a132006b5a79.
