### ISSUE TITLE
Packages with installation controlled by env vars are hard to lock down e.g. {arrow}

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#860]
Just starting a conversation here. I discovered an interesting failure mode with {arrow}.

If you're installing from source, the build looks for env vars to determine what features to build: https://arrow.apache.org/docs/r/articles/install.html

If this installation is done by `{renv}` the built package is cached.

When it comes time to restore the package into `{renv}` library, the cached version is used, without consideration of environment variables in the session. This can lead to a situation where some project developers use the same lockfile to build a library and get different sets of capabilities enabled for their project library arrow versions, depending on what was baked into the cached version.

The only solution if you've accidentally cached a minimal version of {arrow} is to purge it from the cache and install it again.

Solutions:
* `{arrow}`/other packages that do this stop doing this kind of weird thing, or install full builds by default. I plan to raise a corresponding discussion to this on `{arrow}` JIRA.
* `{arrow}`/other packages that do this somehow declare what environment variables are used in build and these can be incorporated into the cache hash.
  - not suggesting `{renv}` record the env vars, merely recognise the project build environment is different and the cached version cannot be used.

**Comment by kevinushey** [comment]
> {arrow}/other packages that do this stop doing this kind of weird thing, or install full builds by default. I plan to raise a corresponding discussion to this on {arrow} JIRA.

This would be the easiest solution, at least for me. Does arrow have a good reason to _not_ produce full builds by default?

> {arrow}/other packages that do this somehow declare what environment variables are used in build and these can be incorporated into the cache hash.

The big challenge here is that `renv` tries to use the package `DESCRIPTION` file when computing the cache key, and there isn't a great way for the source package to declare which particular variant of that package should be installed.

If we solve this in `renv`, I think it should be done via a file that lives as part of the project. That way, any install or restore of the package in that project context could respect things declared in that file, and anyone working within that project context would see the same file metadata. Does that make sense?

I don't know what it would look like, though. Probably something in `renv/cache.json` like (just an example):

```
{
    "packages": {
        "arrow": {
            "vars": {
                "ENV_VAR_USED_BY_ARROW": <...>
            }
        }
    }
}
```

Then, the contents of the `arrow` field would become part of the hash used for caching, and so one could effectively use different builds of arrow in that way. (If you wanted to turn on or off some `arrow` feature, you'd just modify the field in `renv/cache.json`)

**Comment by MilesMcBain** [comment]
I raised this one over on {arrow} JIRA: https://issues.apache.org/jira/browse/ARROW-14719

**Comment by nealrichardson** [comment]
> > {arrow}/other packages that do this stop doing this kind of weird thing, or install full builds by default. I plan to raise a corresponding discussion to this on {arrow} JIRA.
> 
> This would be the easiest solution, at least for me. Does arrow have a good reason to _not_ produce full builds by default?

The short answer is CRAN. Building with everything enabled increases the risk of spurious rejection, and it increases the build time. We originally tried to have the `configure` script download the prebuilt binaries on Linux that we host, which would solve the build time issue, but CRAN rejected that as a violation of policy (though I know of other packages that do this, and it's how the mac and Windows dependencies are satisfied 🤷 ).

We have been working on enabling at least the most common compression libraries in the default build (https://github.com/apache/arrow/pull/11614), though as it turns out, doing so means we get to confront *their* sanitizer failures on CRAN as well.
