### ISSUE TITLE
Plans for supporting neuroconductor?

### ISSUE THREAD

**Issue by romunov** [rstudio/renv#861]
Are there any plans of supporting https://neuroconductor.org/ ?

**Comment by kevinushey** [comment]
This is my first time hearing about it -- what would it take for `renv` to support it?

**Comment by romunov** [comment]
Are you interested in terms of changes to the code or how a user would see it?

For the latter case, I see `renv` handling packages from CRAN, Git*/Bit* and Bioconductor via i.e. `renv::install("bioc::Biobase)". Perhaps a homologous functionality via `renv::install("neuroc::aws")`. That is, if you deem the Neuroconductor community large and lively enough to make it worth while adapting the code for this repository, too.

For the former, I would have to look into the `renv` source code to even begin to dish out educated guesses. :)

**Comment by adigherman** [comment]
This would be awesome for the neuroimaging community. I am in charge of Neuroconductor, please let me know how I can help.

**Comment by kevinushey** [comment]
It looks like Neuroconductor is relatively similar in structure to Bioconductor?

- CRAN-like repositories are available for different releases, from https://neuroconductor.org/releases/
- Packages are also available from GitHub, at https://github.com/orgs/neuroconductor/repositories. (Are these development versions?)

The simplest way would be to just set the appropriate R repositories, and ensure those are set in the lockfile -- for example:

```
options(repos = c(
    Neuroconductor = "https://neuroconductor.org/releases/2020/05/",
    CRAN = "https://cran.r-project.org"
))

renv::snapshot()
```

That would be compatible with existing `renv` infrastructure, at least. I could imagine it being useful to have a way to declare more directly which "release" of Neuroconductor one would want to use, though.

**Comment by hadley** [comment]
Closing, since it seems that neuroconductor is compatible with the existing CRAN repository spec, so you can already use it with renv by setting the appropriate repositories.
