### ISSUE TITLE
option for ignore rules

### ISSUE THREAD

**Issue by aronatkins** [rstudio/renv#863]
renv should allow callers to indicate project-level ignore rules using an in-memory option. This would let us map the packrat option ignored.directories to an renv setting, for example.

We are considering a function like the following to create renv rules from the packrat setting:

```r
# Return renv ignore patterns based on the packrat ignored.directories option.
# Each directory is returned as a rooted pattern for renv, meaning that it
# should only apply at the root directory of the project.
#
# Note: The "/data/" and "/inst/" directories are ignored by default.
ignoredDirsForRenv <- function(ignoredDirs) {
  if (length(ignoredDirs) > 0) {
    # Make sure all the directories end with a slash.
    ignoredDirs <- ifelse(
        substr(ignoredDirs, nchar(ignoredDirs), nchar(ignoredDirs)) != "/",
        paste0(ignoredDirs, "/"),
        ignoredDirs
    )
    # Make sure all the directories begin with a slash.
    ignoredDirs <- ifelse(
        substr(ignoredDirs, 1, 1) != "/",
        paste0("/", ignoredDirs),
        ignoredDirs
    )
    ignoredDirs
  }
}
```

That code would then be called like:

```r
do_some_thing <- function() {
    old_renv_ignore <- options("renv.settings.ignore.matching" = ignoredDirsForRenv(packrat::opts$ignored.directories())
    on.exit(do.call(options, old_renv_ignore), add = TRUE)
    deps <- renv::dependencies(".")
    # ...
}
```

The `renv.settings.ignore.matching` setting name is an example of what renv could use; it does not need to use this name.

**Comment by kevinushey** [comment]
Some questions:

1. Should these rules override the default `renv` ignore rules, or supplement them?

2. What is the "right" behavior for a person who has opted into using `renv`? (For example, suppose they're deploying a project that already has `renv.lock`, or they're already using an `.renvignore`). This might be a concern for Packrat, not renv, though.

**Comment by aronatkins** [comment]
I don't have great answers to either of those questions.

1. Maybe the best example to follow is the `$HOME/.gitignore` that folks use. These are ignore rules that are applied to all projects. They augment the project-specific ignore rules. I vote supplement.

2. You're right - this is more of a question for packrat / other callers who need to decide how to combine renv with the choices they've already made. I was hoping that the `renv` rules (given `.renvignore` files) combined with the `ignored.directories` constraint from `packrat` would be sufficient.
