### ISSUE TITLE
`renv::snapshot()` wants to update Bioconductor version

### ISSUE THREAD

**Issue by mcanouil** [rstudio/renv#864]
Hi,

Bioconductor 3.14 was released two weeks ago and now each time `renv::snapshot()` is used, renv update the release version of Bioconductor to the latest, this lead to discrepancies which force you to update all Bioconductor packages in order to not break the ability to restore your project while breaking reproducibility in case of major changes in the updated packages.

![image](https://user-images.githubusercontent.com/8896044/141482242-fd108aa2-284f-4a17-95b9-5a93f718342e.png)

I did not found any options in "config", "settings or elsewhere (in renv) to avoid `renv::snapshot()` to update Bioconductor release.

Is there a way to avoid that behaviour and fix the Bioconductor release somehow when using `renv::snapshot()`? i.e., maybe something what is used for MRAN
I did not try, but I am guessing `renv::install("bioc::PKG)` is using the latest bioconductor version as well, thus lead to the use of two separate bioconductor release in the same project (if you don't update everything).

**Comment by kevinushey** [comment]
Does your project have a lockfile? Is the Bioconductor version already recorded in that lockfile?

`renv` just asks the BiocManager package what version of Bioconductor to use, via `BiocManager::version()`. That in turn looks at what version of the `BiocVersion` package is installed, so "in theory" installing the older version of the `BiocVersion` package would resolve this.

It's also possible that `renv` is automatically (and undesiredly) updating the stored Bioconductor version; if that's the case I'd be happy to try and tighten things up.

**Comment by mcanouil** [comment]
3.13 is recorded in the lockfile which is consistent with the installed and recorded bioconductor packages.
The screenshot comes from a call on a perfectly up to date renv project.

**Comment by kevinushey** [comment]
Sorry, I misspoke -- `BiocManager` infers the Bioconductor version from the `BiocVersion` package, but only if that package is installed (which it isn't by default). When `BiocVersion` is not installed, `BiocManager` tries to guess the "best" version of Bioconductor to use, and that is evidently overriding whatever is already recorded in the lockfile.

In addition, installing a particular version of the `BiocVersion` package appears to be somewhat challenging. I had assumed it was standard practice to use that to lock the Bioconductor version, but that may not be the case.

I'll have to see how to better handle this in `renv`.

**Comment by kevinushey** [comment]
I've now made some changes in the development version of `renv` that should allow you to freeze the version of Bioconductor used in a project, via a project setting:

https://github.com/rstudio/renv/commit/2f804942a5ccdcb9ce972b9a34be89c392ca3f32

If you want to give this a spin, you can try:

```
renv::upgrade(version = "main")
# restart R
renv::settings$bioconductor.version("3.13")
```

And then check whether `renv::snapshot()` correctly reports the Bioconductor version.

**Comment by mcanouil** [comment]
Thanks! I will definitely give it a try next week, since bioconductor is used in all our projects.

**Comment by kevinushey** [comment]
Currently, those options only applied to newly-created projects -- they don't override project settings in existing projects. (This has been confusing in the past so I might want to change that behavior.)

**Comment by kevinushey** [comment]
I've now made a few changes on the main branch:

1. When `renv::snapshot()` is called, `renv` will retain fields like `git_tag` and `git_release`, which are normally set in packages installed from Bioconductor. When possible, `renv` will use those fields to ensure associated package is installed from the correct Bioconductor release.

2. `renv`'s project settings can now be overridden via options of the same name, in line with the behavior you expected in https://github.com/rstudio/renv/issues/864#issuecomment-968677965.

If you can, please let me know if you run into any trouble as I'd like to be sure Bioconductor packages are handled appropriately with `renv`!

**Comment by mcanouil** [comment]
The last change worked well in several of my work-related project.
The "overwrite" behaviour is (in my case) mostly to be used when I initialise an empty project or an old one I want to migrate to `renv`.
So far, all good (although I won't be able to do much more testing on this until January)

**Comment by kevinushey** [comment]
Glad to hear it! Thanks for testing.

**Comment by kevinushey** [comment]
I'm going to close this issue as resolved for now; please feel free to file a new issue if anything else comes up.
