### ISSUE TITLE
setting global cache

### ISSUE THREAD

**Issue by paupaiz** [rstudio/renv#869]
In renv documentation, whether I should change `RENV_PATHS_ROOT` and/or `RENV_PATHS_CACHE` to the directory where I want my renv cache to live in is unclear. Issues I have found that tried to use only `RENV_PATHS_CACHE` were instructed to use `RENV_PATHS_ROOT` instead (See below). So which of the two do I use and is it correct to put them on the .Renviron file if I want all my R sessions to use the same one? 

https://community.rstudio.com/t/renv-puts-all-packages-into-projects-renv-library/50173
https://github.com/rstudio/renv/issues/313
https://githubmemory.com/repo/rstudio/renv/issues/816
https://github.com/r-lib/actions/actions/runs/1359802000

**Comment by kevinushey** [comment]
Basically, `renv` collects a variety of metadata, all stored within a directory at `RENV_PATHS_ROOT` by default. The cache is one part of that metadata.

The documentation in https://rstudio.github.io/renv/reference/paths.html may be helpful.
