### ISSUE TITLE
Windows - request to use robocopy for `renv_file_move` by default

### ISSUE THREAD

**Issue by slodge** [rstudio/renv#870]
We had an issue on some Windows machines where `renv::restore()` was taking an extra 8 minutes after the last `install` had completed, while on other PCs the restore completed "instantly".

We eventually tracked this down to the fact that `renv` was using `move` on those PCs while on others it was using `robocopy`.

We've worked around this by now using `options(renv.config.install.transactional = FALSE)` as proposed in https://github.com/rstudio/renv/issues/621

There are several advantages in using `robocopy` - including it's quicker at copying files and (particularly important for renv) by default it seems it copies junction points, rather than deep copying the underlying files - which is what `move` was doing on those PCs.

Based on what I've seen in this testing, I'd like to suggest removing this block https://github.com/rstudio/renv/blob/bf04c2dbcba4fe9cd9535874f04b1fdeb99b52a1/R/files.R#L213-L219 ... or to put it behind an option which defaults to `off`. 

On Windows, the code would then drop through to https://github.com/rstudio/renv/blob/bf04c2dbcba4fe9cd9535874f04b1fdeb99b52a1/R/files.R#L60-L78 followed by `unlink` https://github.com/rstudio/renv/blob/bf04c2dbcba4fe9cd9535874f04b1fdeb99b52a1/R/files.R#L226

Other possible options that could be considered:
- `robocopy` has a `/MOVE` switch which could be added (some refactoring required for this though)
- `mklink` could again be used to make the junction point in the library path instead of moving the junction point out of staging (this feels like a bigger change though)

**Comment by kevinushey** [comment]
Thanks! I agree using `robocopy` rather than `move` here seems like the right choice. I'll try and explore this.

**Comment by kevinushey** [comment]
> There are several advantages in using robocopy - including it's quicker at copying files and (particularly important for renv) by default it seems it copies junction points, rather than deep copying the underlying files - which is what move was doing on those PCs.

I'm not able to replicate this. From what I can see, `robocopy` doesn't generate new junction points on copy; rather, it copies the contents of the junction point as a new directory. Unfortunately, as far as I can see, Windows doesn't provide any tooling in `robocopy` (or other command line tools) for copying junction points in the way we expect here. :-/

For now, I think we can implement a robocopy-based 'move' for this action, and then think about special-casing the migration of the library path in transactional installations to handle junction points more cleanly.

**Comment by slodge** [comment]
Let me get back to you on this tomorrow.

The evidence we had in our late night debugging was that the PCs using move
copied files and ended up without junction points, but the PCs using
robocopy ended up with junction points.

Certainly switching to transactional gave us the 8 minutes boost on the
move PCs.

Apologies if we saw something else happening... Will try again with direct
code in the fresh light of day tomorrow!

**Comment by kevinushey** [comment]
It actually seems like the reverse could be true: calling `move` on a directory will preserve junction points within the moved directory, whereas using `robocopy` will force a full copy.

Is it possible that the project library path, and the configured staging install library path, live in different directories / volumes? If that were the case, then `move` might fail in a context where `robocopy` would succeed.

**Comment by slodge** [comment]
I've been looking into this...

It appears the late night debugging strikes again... 

On the PCs without `move` it seems like it's actually the line that uses `file.rename` that is succeeding:
https://github.com/rstudio/renv/blob/0a4543577d9c27f1a5671b7726160fbae7c91088/R/files.R#L184

On the PCs with `move` I'll have to get back to you (I need to talk with someone who's in a different timezone!)

From the debugging we did, I'm pretty sure all directories were on the same drive - so `file.rename` should have worked for them too... but they were definitely falling back to `move` - and they were still definitely (+) not getting symbolic links in their renv/project library folder.

(+) subject to my late-night debugging eyes completely lying to me (will check again!)

Thanks for looking into this - sorry we got some rather important details wrong here...

--------------

Away from this 8 minute delay.... Aside from the symbolic links, `robocopy` is still much faster and it does have a /MOVE argument... so this is still some benefit I think in using `robocopy` by default...

----------------

More to follow...

**Comment by kevinushey** [comment]
The output of `renv::diagnostics()` in each case may be useful, especially if `renv` has been configured to use a project library + staging library that happen to live on different volumes. See https://rstudio.github.io/renv/reference/paths.html for more details.

**Comment by slodge** [comment]
We used code like below to prove `file.rename` was working fine for us on all involved machines last Friday - it was - `file.rename` is definitely doing what we wanted on all the machines :+1: ... but then timezones (and time of the month/year) worked against me working out what happened in renv. Will follow up some more this week to work out what happened... 

```
library(tidyverse)

packageVersion("renv")

if (dir.exists("C:/rdata/copyExperiments")) {
  unlink("C:/rdata/copyExperiments", force = TRUE, recursive = TRUE)
}
path0 <- "C:/rdata/copyExperiments/Original"
path1 <- "C:/rdata/copyExperiments/From"
path2 <- "C:/rdata/copyExperiments/To"
dir.create(path0, recursive = T)
dir.create(path1, recursive = T)
dir.create(path2, recursive = T)

packagePath <- "C:/rdata/copyExperiments/Original/pkg"
dir.create(packagePath, recursive = T)

sample_data <- tibble::tibble(Id = 1:100000) |> dplyr::mutate(Text = stringr::str_glue("This is row {Id}"))
readr::write_lines(sample_data, file.path(packagePath, "file.txt"))

fromPackagePath <- "C:/rdata/copyExperiments/From/pkg"
renv:::renv_file_link(packagePath, fromPackagePath)

toPackagePath <- "C:/rdata/copyExperiments/To/pkg"
status <- renv:::catchall(file.rename(fromPackagePath, toPackagePath))

if (file.exists(toPackagePath)) {
  message("It worked")
} else {
  message("It failed")
  message(status)
}

# tidy up
unlink("C:/rdata/copyExperiments", force = TRUE, recursive = TRUE)
```

Sorry for delay - thanks again for advice and patience 👍

**Comment by kevinushey** [comment]
No worries! Thanks for taking the time to thoroughly investigate.

**Comment by slodge** [comment]
OK... finally have some closure on this here.

I'm afraid to say we were mixing drives.

This wasn't obvious to us as we were doing some "temporary folder" stuff ourselves when some automation checked out the code and ran renv on the project.

However, if we got `renv::diagnostics()` at the right point, then:

```
# Environment Variables ==============
HOME                              = C:\Users\a.user\Documents
LANG                              = <NA>
MAKE                              = <NA>
R_LIBS                            = <NA>
R_LIBS_SITE                       = <NA>
R_LIBS_USER                       = D:/R/runtime/library/Stuff_Monitoring-46114156/R-4.1/x86_64-w64-mingw32;D:/temp/RtmpoFkzmp/renv-system-library
RENV_CONFIG_AUTO_SNAPSHOT         = TRUE
RENV_CONFIG_INSTALL_TRANSACTIONAL = TRUE
RENV_CONFIG_USER_PROFILE          = TRUE
RENV_DEFAULT_R_ENVIRON            = <NA>
RENV_DEFAULT_R_ENVIRON_USER       = <NA>
RENV_DEFAULT_R_LIBS               = <NA>
RENV_DEFAULT_R_LIBS_SITE          = <NA>
RENV_DEFAULT_R_LIBS_USER          = C:\Users\a.user\Documents/R/win-library/4.1
RENV_DEFAULT_R_PROFILE            = <NA>
RENV_DEFAULT_R_PROFILE_USER       = <NA>
RENV_DOWNLOAD_FILE_METHOD         = wininet
RENV_PATHS_LIBRARY_ROOT           = D:/R/runtime/library
RENV_PATHS_ROOT                   = D:/R/runtime/renv
RENV_PROJECT                      = C:/Users/tofsuatsvc/AppData/Local/Temp/d221b0bd-bb41-4a04-aa09-789dc03f3885/R/Reports/Stuff_Monitoring
```

Thanks hugely for your time and input on this.

Sorry it did turn out to just be us crossing the drives, and sorry about delays while we remote debugged this across some transatlantic timezones. I owe you (another) one 👍

**Comment by kevinushey** [comment]
Thanks for taking the time to verify!

It sounds like we might still want to prefer using robocopy, in the case that an R level file.rename() fails for some reason.

I also wonder if there's something renv could be doing here to signal what's going on to the user.

**Comment by slodge** [comment]
Thanks.

I think robocopy would be much faster - and should be faster again with the /MOVE parameter. It looks like it's been available all on Win versions since Vista too - so should be good to use - https://en.wikipedia.org/wiki/Robocopy (although there is often a gap between "should be" and "is"!)

Could also consider adding some verbose-only logging in the case that the `file.rename` and/or `move` attempts fail. It was great that the code automatically fell through to other methods, but there was no way of getting that execution flow out into a log file.

**Comment by kevinushey** [comment]
I've now switched to using robocopy for file moves in `renv`:

https://github.com/rstudio/renv/commit/482cde9676da8c4eb36208f559fd1e76f6dc3fca

If you have a chance, please give the development version of `renv` a spin and let me know if performance does indeed look better.

**Comment by slodge** [comment]
I've been using the Github version of renv on a couple of projects... no huge sign of perf improvements, but these are smaller, newer projects anyway - so no real perf problems in them to solve... 

Will see if I can test on some bigger projects on the remote boxes on the other side of the atlantic "soon"

For now - all looks 👍

**Comment by kevinushey** [comment]
Glad to hear it -- thanks for reporting back!
