### ISSUE TITLE
Only one version of igraph available in MRAN database for macOS

### ISSUE THREAD

**Issue by zkamvar** [rstudio/renv#871]
This is similar to #784, but I noticed that when I tried to install igraph 1.2.7, my computer was trying to build it from source. I decided to look at the database and it shows that the only igraph version available for 4.1 is 1.2.6, which is strange because the snapshot exists for the release version of R according to https://cran.microsoft.com/snapshot/2021-10-19/web/packages/igraph/index.html

``` r
grep("igraph ", ls(envir = renv:::renv_mran_database_load()$`/bin/macosx/contrib/4.1`), 
    value = TRUE)
#> [1] "igraph 1.2.6"    "migraph 0.6.6"   "multigraph 0.93"
```

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kevinushey** [comment]
It looks like the `renv` MRAN database hasn't been updated in a while. I'll need to take a look and see why.

**Comment by kevinushey** [comment]
Should be fixed now. Thanks for the report!

```
> packages <- ls(envir = renv:::renv_mran_database_load()$`/bin/macosx/contrib/4.1`)
> grep("^igraph ", packages, value = TRUE)
[1] "igraph 1.2.6" "igraph 1.2.7" "igraph 1.2.8"
```

You might need to run `renv:::renv_mran_database_refresh()` to get an up-to-date copy of the MRAN database.

**Comment by zkamvar** [comment]
It worked! Thank you ^_^
