### ISSUE TITLE
Best practice: user-level renv config and ~/.Rprofile

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#876]
Hi Kevin,

In https://rstudio.github.io/renv/reference/config.html it reads

> If you want to set and persist these options across multiple projects, it is recommended that you set them in your user startup files (e.g. in ~/.Rprofile or ~/.Renviron).

I am a bit confused by this: In a normal `renv` project, `~/.RProfile` is not read by default as the project `.Rprofile` takes precedence.
Unless the user adds extra code into the project `.Rprofile` to also source `~/.RProfile`, it won't be read.

Next, if this happens and `~/.RProfile` contains important config for the project, collaborators won't be aware of it.

Is this still recommended and I am maybe overlooking something? :)

**Comment by kevinushey** [comment]
That's a good point. You can opt in to sourcing the user `~/.Rprofile` with `RENV_CONFIG_USER_PROFILE = TRUE`, but we should probably clarify this.

**Comment by kevinushey** [comment]
> Next, if this happens and ~/.RProfile contains important config for the project, collaborators won't be aware of it.

In general, "config" options are supposed to be "personal", in that they affect how you personally use `renv` but might not be relevant to collaborators. (That's not always true; the abstraction is a little leaky.) If you want those options to be visible to all users, though, you probably want to place them in a site-wide profile for your R installation.

**Comment by pat-s** [comment]
Thanks Kevin! This clarifies things for me.
