### ISSUE TITLE
renv to snapshot only specific folders or exclude specific folders

### ISSUE THREAD

**Issue by Athanasiamo** [rstudio/renv#880]
I've tried searching through issues, but could not see anything about this.

I have a project (several really) where I'd love to use renv, but its snapshotting the entire project, when I really only want it to snapshot a single folder, or at least exclude snapshotting a specific folder.

The background being that this is a blogdown project, but I dont want or need any blog content to be snapshotted (i.e. anything in `content/blog/` of the project should not be snapshotted, I dont need to be able to reknit old blog posts). I do have some scripts that I have running on a schedule on github actions, to re-knit certain pages on the website, and its these files I want renv to snapshot, as I want these to knit over and over again in perpetuity.

Is there a way to specify folders to specifically look in or not look in when setting up renv?

**Comment by kevinushey** [comment]
I think `.renvignore` is what you need here: https://rstudio.github.io/renv/reference/dependencies.html#ignoring-files

I could also add `content/blog` to the list of default ignores in `renv`.

**Comment by kevinushey** [comment]
The development version also supports syntax of the form:

```
*
!path
```

if you'd like to tell `renv` to ignore everything except for `path`. I should add that to the documentation...

**Comment by Athanasiamo** [comment]
oh wow, thanks! I was looking in all the wrong places for that information. 
This makes things so much smoother :)
