### ISSUE TITLE
<na> for lockfile, source, and dependency 

### ISSUE THREAD

**Issue by paupaiz** [rstudio/renv#883]
I am not sure why `<na>` shows up for some packages in the lockfile, source, and dependencies columns. I downloaded some of these packages using the `renv::install` function

<img width="724" alt="Screen Shot 2021-12-05 at 3 20 30 PM" src="https://user-images.githubusercontent.com/59720098/144768660-cca5f53e-1e9d-418f-83bf-992db971b983.png">
<img width="691" alt="Screen Shot 2021-12-05 at 3 39 16 PM" src="https://user-images.githubusercontent.com/59720098/144768682-8585540a-ea89-4780-87c6-2b628b3b2e25.png">

**Comment by kevinushey** [comment]
The output implies that those packages are installed in the project library, but not yet snapshotted into the lockfile. Do those packages have entries in `renv.lock`?

**Comment by paupaiz** [comment]
they do not, and when I run `renv::snapshot()` it says the project is already up to date with the lock file...

**Comment by kevinushey** [comment]
You're most likely running into the first entry in the FAQ: https://rstudio.github.io/renv/articles/faq.html

Basically, as far as `renv` can tell, your project doesn't actually depend on those packages directly and so they're not included in the lockfile. You might need to add an explicit dependency on those packages.

**Comment by paupaiz** [comment]
alright thanks for the explanation! Does `renv` have functionality to do explicit dependency on top of its discovery machinery? Or if I use `renv::settings$snapshot.type("explicit")` i will have to list all the packages?

**Comment by kevinushey** [comment]
The simplest solution is to create a file called `_dependencies.R` in your project, and add extra library calls e.g. `library(<pkg>)`.

**Comment by paupaiz** [comment]
Wouldn't creating `_dependencies.R` drop the use of `renv` all together?

**Comment by paupaiz** [comment]
or were you referring to doing something like this:
# alternatively, provide a full record as a list
`digest_record <- list(
  Package = "digest",
  Version = "0.6.22",
  Source  = "Repository",
  Repository = "CRAN"
)

renv::record(list(digest = digest_record))`

**Comment by kevinushey** [comment]
I don't think so? I don't quite understand your comment.
