### ISSUE TITLE
history fails to bind_list parts

### ISSUE THREAD

**Issue by llrs** [rstudio/renv#886]
Many thanks for maintaining this package it is a nice tool to keep track where does each package come from. When attempting to see the history of renv of one of my projects I receive this error:

``` r
renv::history()
#> Error in names(rhs) <- names(rhs) %||% names: 'names' attribute [4] must be the same length as the vector [0]
traceback()
#> No traceback available
```

I'm using R 3.6.3 and on the console not the reprex the traceback pointed to: `: bind_list(parts, names = c("commit", "author_date", "committer_date", "subject"))`.  The file is tracked on my VCS so I'm not sure why I don't see anything.

<sup>Created on 2021-12-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kevinushey** [comment]
Thanks! This should now be fixed in the development version of `renv`; I've added some tests to help ensure this doesn't happen again. Sorry for the trouble!
