### ISSUE TITLE
Init ignores RENV_PATHS_CACHE after restarting

### ISSUE THREAD

**Issue by wiedenhoeft** [rstudio/renv#888]
My ~/.Rprofile contains 

> Sys.setenv(RENV_PATHS_CACHE="/SAN/bioinf_core/programs/renv/")

After starting R-3.6.2, 

> Sys.getenv("RENV_PATHS_CACHE")

correctly shows

> "/SAN/bioinf_core/programs/renv/"

I run renv::init() and restart as required. After restarting, getenv now shows

> ""

and installing packages happens in the directory without symlinking to the global cache. Setting RENV_PATHS_CACHE manually after restarting R works as a workaround, but this is clearly a nuisance.

**Comment by kevinushey** [comment]
This is because `~/.Rprofile` is not sourced by default. From https://rstudio.github.io/renv/reference/config.html:

```
renv.config.user.profile
Load the user R profile (typically located at ~/.Rprofile) when renv is loaded? Consider disabling this if you require extra encapsulation in your projects; e.g. if your .Rprofile attempts to load packages that you might not install in your projects. Defaults to FALSE.
```

The easiest solution is to enable this option in your `~/.Renviron`; or perhaps even easier is to just set `RENV_PATHS_CACHE` in `~/.Renviron`.

**Comment by wiedenhoeft** [comment]
Thanks for the clarification! Since the standard use case for a global cache is to use it in all projects by default, it would be nice to have this approach featured prominently in the documentation. From the introductory documents, the user very easily gets into a situation where they end up with local repos for each project, potentially without even realizing.

**Comment by kevinushey** [comment]
I can do that. Do you have an opinion on what the best place for that documentation would be? (Somewhere in the getting started guide? https://rstudio.github.io/renv/articles/renv.html)
