### ISSUE TITLE
restore - quiet argument

### ISSUE THREAD

**Issue by cstepper** [rstudio/renv#889]
Hi,

thanks for this great package, which we use quite heavily in our CI/CD framework and for creating custom Docker images.

When running `renv::restore()` in a CI/CI job or during `docker build` (e.g. `RUN Rscript -e "renv::restore()"`), the output is quite verbose.

```
Step 10/11 : RUN Rscript -e "renv::restore()"
 ---> Running in b42d1f57a761
[1] "/opt/renv/cache/v5/R-4.1/x86_64-pc-linux-gnu"
The following package(s) will be updated:
# RSPM ===============================
- R6              [* -> 2.5.1]
- Rcpp            [* -> 1.0.7]
- askpass         [* -> 1.1]
...
Installing R6 [2.5.1] ...
        OK [copied cache]
Installing Rcpp [1.0.7] ...
        OK [copied cache]
Installing sys [3.4] ...
        OK [copied cache]
Installing askpass [1.1] ...
        OK [copied cache]
...
```
Would it be possible, to have an additional argument for `renv::restore()`, e.g. `quiet = FALSE` (similar to the `remotes::install_*`-functions). When set to `TRUE`, output would be suppressed. This would be a neat feature for logs.

Thanks, Christoph

**Comment by kevinushey** [comment]
Thanks for the feature request! Are you expecting to see no output at all, or only the initial "these packages will be updated" log, or something else?

**Comment by cstepper** [comment]
Hi,
I thought of something like a summary printed to console, when `renv::restore(quiet = TRUE)` was executed successfully.
Maybe something like
```
sprintf("%s package(s) updated and copied to cache.", length(renv:::renv_lockfile_read("renv.lock")$Packages)
```
But I would be happy with anything compressed output compared to the current solution.
Thanks

**Comment by hadley** [comment]
I'm slightly surprised that you want this, because in my opinion, you want CI/CD logs to be pretty noisy since any debugging otherwise requires an expensive roundtrip where you have to set some debug flag and then restart the whole job.

**Comment by hadley** [comment]
Also, you can suppress all renv output by setting `options(renv.verbose = FALSE)` or `Sys.getenv(RENV_VERBOSE = FALSE)`.
