### ISSUE TITLE
Bootstrapping from cellar

### ISSUE THREAD

**Issue by ray-p144** [rstudio/renv#891]
Somewhat related to issue https://github.com/rstudio/renv/issues/820

But it would also be a nice feature if renv could first attempt to bootstrap from the cellar (https://github.com/rstudio/renv/blob/6dcd471ffb35d0c3e91563ce51fec0c46b86fefb/vignettes/cellar.Rmd) or from a user specified path to a binary copy of renv or the source so they do not have to set up a local repository just to allow bootstrapping in environments with limited internet access.

I propose checking a binary or source for the required renv version in the cellar, or checking for an environment variable and/or an `options()` setting prior to attempting to download renv ([here](https://github.com/rstudio/renv/blob/cc7963be31ce055fb5ea1a74265648d5db76abf3/R/bootstrap.R#L8)).

This would allow the user to either include renv in the cellar or specify a path to a binary or source through an environment variable or through `options()` in the .Rprofile prior to it calling `source("renv/activate.R")`.

**Comment by kevinushey** [comment]
Implemented now in https://github.com/rstudio/renv/commit/aee463dec6e53cbe6c8640a47f21b32349715d0d; you can set `RENV_BOOTSTRAP_TARBALL` to point `renv` at a tarball to be used during bootstrap.
