### ISSUE TITLE
blank line in DESCRIPTION breaks renv_dcf_read

### ISSUE THREAD

**Issue by bellma-lilly** [rstudio/renv#892]
Thanks for this useful package.

I am using renv [0.14.0-130], which I just cloned.
Starting with this error:
> renv::status()
Error in !deps$Dev : invalid argument type
In addition: Warning message:
In FUN(X[[i]], ...) : subscript out of bounds

I traced the problem to a single blank link in my DESCRIPTION file.
Consider the following DESCRIPTION file:
```
Package: mypackage
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person(given = "jane",family = "doe",role = c("aut", "cre")
Description: TFLs
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
Imports: 
    bslib
```
It loads properly:
renv:::renv_dcf_read(".../DESCRIPTION")
```
$Package
[1] "mypackage"
$Title
[1] "What the Package Does (One Line, Title Case)"
$Version
[1] "0.0.0.9000"
$`Authors@R`
[1] "person(given = \"jane\",family = \"doe\",role = c(\"aut\", \"cre\")"
$Description
[1] "TFLs"
$Encoding
[1] "UTF-8"
$LazyData
[1] "true"
$Roxygen
[1] "list(markdown = TRUE)"
$RoxygenNote
[1] "7.1.2"
$Imports
[1] "bslib"
```

If I add a single blank line in the file:
```
Package: mypackage
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person(given = "jane",family = "doe",role = c("aut", "cre")
Description: TFLs

Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
Imports: 
    bslib
```
 It breaks things:
renv:::renv_dcf_read(".../DESCRIPTION")
```
$Package
[1] "mypackage" NA         
$Title
[1] "What the Package Does (One Line, Title Case)"
[2] NA                                            
$Version
[1] "0.0.0.9000" NA          
$`Authors@R`
[1] "person(given = \"jane\",family = \"doe\",role = c(\"aut\", \"cre\")"
[2] NA                                                                   
$Description
[1] "TFLs" NA    
$Encoding
[1] NA      "UTF-8"
$LazyData
[1] NA     "true"
$Roxygen
[1] NA                      "list(markdown = TRUE)"
$RoxygenNote
[1] NA      "7.1.2"
$Imports
[1] NA      "bslib"
```

Please make renv tolerant to blank lines.

**Comment by kevinushey** [comment]
I can do this, but note that this file is not a valid DESCRIPTION file -- R does not tolerate spaces between fields in that context. A package containing such a DESCRIPTION file would have something like:

```
$ R CMD build .
* checking for file ‘./DESCRIPTION’ ...Error : contains a blank line
 EXISTS but not correct format
```

printed by R at build time.

That said, of course `renv`'s dependency discovery machinery should be robust to this sort of thing.

**Comment by kevinushey** [comment]
Should be fixed via https://github.com/rstudio/renv/commit/a1aea821df00b87a8869dd5ff5c88481b27467b5 -- please let me know if you bump into any other issues.

**Comment by bellma-lilly** [comment]
> note that this file is not a valid DESCRIPTION file

@kevinushey Leaving it at this would have been totally understandable. Thanks for going the extra mile!
