### ISSUE TITLE
Initializing new project slow on Windows Mapped Network Drive

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#893]
Hello! I use renv primarily on my C drive. But some colleagues keep everything on a Windows mapped network drive. I took two identical projects (both only including packages that are already in the system cache), and initialized the projects on the C drive and again on the mapped network drive. The project on the C drive took 20 seconds to initialize, and the same project on the network drive took 15 minutes.

Is there anything we can do to make this process faster for those using the network drives on Windows? 

Thank you! (again!)

**Comment by kevinushey** [comment]
Can you try collecting an R profile? E.g. something like:

```
utils::Rprof("~/renv-trace.Rprof")
# work in renv
utils::Rprof(NULL)
```

and then share a copy of the trace?

**Comment by ddsjoberg** [comment]
Thank you so much @kevinushey for taking a look! I put the .Rprof file in a zip so GH would allow me to attach it to this comment.

I've never created a file like this before. If I"ve done it incorrectly I can read up on it and try again.

[renv-trace.zip](https://github.com/rstudio/renv/files/7715366/renv-trace.zip)

**Comment by kevinushey** [comment]
Thanks! It looks like almost all of the time is spent copying packages from the user / system library to the project library:

```
$by.total
                                                       total.time total.pct
"renv::init"                                               800.14     97.93
"tryCatch"                                                 768.18     94.02
"tryCatchList"                                             768.12     94.01
"tryCatchOne"                                              768.10     94.01
"doTryCatch"                                               768.08     94.01
"withCallingHandlers"                                      758.84     92.87
"hydrate"                                                  756.50     92.59
"FUN"                                                      755.86     92.51
"lapply"                                                   751.48     91.97
"renv_file_copy"                                           717.88     87.86
"catchall"                                                 716.44     87.69
"f"                                                        715.34     87.55
"enumerate"                                                715.32     87.55
"renv_file_copy_dir"                                       714.48     87.45
"suppressWarnings"                                         710.28     86.93
"renv_hydrate_link_packages"                               707.92     86.64
"renv_file_link"                                           705.94     86.40
"renv_file_copy_dir_impl"                                  700.82     85.77
"system2"                                                  700.28     85.71
"renv_file_copy_dir_robocopy"                              699.62     85.63
"renv_system_exec"                                         699.58     85.62
```

`renv::init()` tries to "fork" the current state of your user library, hence why it chooses to install packages from there rather than the cache. I'm guessing your project library and your user library live on separate volumes?

I suspect something like:

```
renv::init(bare = TRUE)
renv::install()
```

may be faster, since `renv::install()` will try to use the cache in that case.

**Comment by ddsjoberg** [comment]
Thank you for the suggestion @kevinushey !

Most of the new projects are built from a template, which calls `renv::scaffold(project = path, settings = list(snapshot.type = "all"))`. After they open the newly created project, they call `renv::hydrate()` and `renv::snapshot()`. In this scenario, do you have a suggestion to speed up the process? 🙌🏼

**Comment by kevinushey** [comment]
Not really. `hydrate()` is going to be slow if the project library and the user library live on different drives, especially if they're on different network drives. I don't think think there's much `renv` can do here.

You could use `RENV_PATHS_LIBRARY` to set the project library on the same drive as where the user / site libraries live, to avoid that cost if necessary?

**Comment by ddsjoberg** [comment]
Thank you so much @kevinushey ! I'll add setup instructions for those that use the network drives to change their renv library location.

Appreciate the responses! 🕺🏼
