### ISSUE TITLE
Opt-out of `~/.Renviron` when `.Renviron` is present

### ISSUE THREAD

**Issue by eheinzen** [rstudio/renv#896]
Related to #876 but for `.Renviron`.  There's an option to opt-in (default opted out) for the `~/.Rprofile`, but not the `~/.Renviron`.

I have a renv project with a `.Renviron` to set project-specific environment variables.  I want this project to be as encapsulated as possible, so I don't want to "accidentally" source my `~/.Renviron`.  If I read `?Startup` correctly, R only sources the project-specific one, instead of sourcing both.  I would expect `renv`'s defaults to respect this behavior.

Not a huge deal; I was just surprised when adding `renv` to my project expanded my available environment variables.

**Comment by kevinushey** [comment]
Thanks for the feature request! Now implemented in the development version of `renv`.

**Comment by eheinzen** [comment]
Brilliant, thanks for the quick response!
