### ISSUE TITLE
`Failing to load renv from project [...], reloading previously-loaded` when loading one renv from the working directory of another via RStudio's system terminal

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/renv#900]
The below behavior makes {renv} incompatible with [pre-commit](https://pre-commit.com/) for `language: r`.

[{precommit}](https://github.com/lorenzwalthert/precommit) has recently started to use {renv} as an environment manager for [various reasons](https://lorenzwalthert.github.io/precommit/news/index.html#precommit-v020), and I am quite excited about that. However, there is a problem that this does not work when the repository in which hooks with `language: r` from pre-commit are used is at the same time a {renv} project (https://github.com/lorenzwalthert/precommit/issues/342). After countless hours of digging, I think I was able to narrow the problem down. When 
* you have a global {renv} version installed
* two {renv} projects e.g. `~/proj1`, and `~/proj2`.
* The two {renv} repos don't use the same (and globally installed) renv version.
* and you use the RStudio project in  `~/proj1` -> open the system terminal in RStudio ->  `cd ~/proj2` -> `R --vanilla`.

You can't load the renv from `~/proj2` with `source('renv/activate.R')`.

```
> search() # just to see there are no renv shims or renv is loaded
[1] ".GlobalEnv"        "package:stats"     "package:graphics" 
[4] "package:grDevices" "package:utils"     "package:datasets" 
[7] "package:methods"   "Autoloads"         "package:base"     
> source('renv/activate.R')
Warning message:
could not load renv from project "~/.cache/pre-commit/repoop2cc2mv/renv-default"; reloading previously-loaded renv 
```
The message apparently comes from [here](https://github.com/rstudio/renv/blob/main/R/load.R#L522). It seems like the unload of one renv version and load of another can't be performed cleanly (although there was none loaded or attached to the search path).

What sounds like a very abstractly constructed case, is apparently pretty much what happens when you run `pre-commit install --install-hooks` or `git commit` if `pre-commit install --install-hooks` was not previously called. This means in most user's workflow, pre-commit can't be used in a project where {renv} is present within RStudio (unless you do a tedious workaround outside RStudio, which has to be done repeatedly on every `precommit::autoupdate()`) because the wrong renv is loaded. 

The interesting part is that the correct renv is loaded *unless* you use the System terminal within RStudio. Outside RStudio, the correct renv is loaded. Also within the R prompt RStudio provides, the correct renv is loaded. I was inspecting environment variables that are set in the system terminal within RStudio and wonder if any environment variable that RStudio sets causes the problem:

```
> Sys.getenv()
__CF_USER_TEXT_ENCODING
                        0x1F5:0x0:0x2
_CE_CONDA               
_CE_M                   
BASH_SILENCE_DEPRECATION_WARNING
                        1
CLICOLOR_FORCE          1
COLUMNS                 107
CONDA_EXE               /Users/lorenz/opt/miniconda3/bin/conda
CONDA_PYTHON_EXE        /Users/lorenz/opt/miniconda3/bin/python
CONDA_SHLVL             0
DISPLAY                 /private/tmp/com.apple.launchd.l9E1W2GNNS/org.xquartz:0
DYLD_FALLBACK_LIBRARY_PATH
                        /Library/Frameworks/R.framework/Resources/lib:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/server:/Library/Frameworks/R.framework/Resources/lib:/Users/lorenz/lib:/usr/local/lib:/usr/lib:/lib:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/server:/var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/rstudio-fallback-library-path-XbyCqQ
EDITOR                  vi
GGMAP_GOOGLE_API_KEY    *** 
GIT_ASKPASS             rpostback-askpass
GITHUB_PAT              ***
HISTCONTROL             ignoreboth
HOME                    /Users/lorenz
LANG                    en_US.UTF-8
LC_CTYPE                en_US.UTF-8
LESS                    -R
LINES                   34
LN_S                    ln -s
LOGNAME                 lorenz
LSCOLORS                Gxfxcxdxbxegedabagacad
MAKE                    make
MPLENGINE               tkAgg
PAGER                   /usr/bin/less
PATH                    /Users/lorenz/.poetry/bin:/Users/lorenz/Library/Preferences/netlify/helper/bin:/usr/local/opt/libpq/bin:/Users/lorenz/opt/miniconda3/condabin:/Users/lorenz/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/RStudio.app/Contents/MacOS/postback
PROMPT_COMMAND          echo -ne "\033]0;${PWD/#${HOME}/~}\007"
PWD                     /Users/lorenz/git/precommit
PYTHONIOENCODING        utf-8
R_ARCH                  
R_BROWSER               /usr/bin/open
R_BZIPCMD               /usr/bin/bzip2
R_DOC_DIR               /Library/Frameworks/R.framework/Resources/doc
R_GZIPCMD               /usr/bin/gzip
R_HOME                  /Library/Frameworks/R.framework/Resources
R_INCLUDE_DIR           /Library/Frameworks/R.framework/Resources/include
R_LIBS_SITE             
R_LIBS_USER             ~/Library/R/x86_64/4.1/library
R_PAPERSIZE             a4
R_PAPERSIZE_USER        a4
R_PDFVIEWER             /usr/bin/open
R_PLATFORM              x86_64-apple-darwin17.0
R_PRINTCMD              lpr
R_QPDF                  /Library/Frameworks/R.framework/Resources/bin/qpdf
R_RD4PDF                times,inconsolata,hyper
R_SESSION_TMPDIR        /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T//RtmpQnYU9N
R_SHARE_DIR             /Library/Frameworks/R.framework/Resources/share
R_STRIP_SHARED_LIB      strip -x
R_STRIP_STATIC_LIB      strip -S
R_SYSTEM_ABI            macos,gcc,gxx,gfortran,gfortran
R_TEXI2DVICMD           /usr/local/bin/texi2dvi
R_UNZIPCMD              /usr/bin/unzip
R_ZIPCMD                /usr/bin/zip
RENV_PATHS_RENV         /Users/lorenz/git/precommit.and.proj.renv/renv
RETICULATE_MINICONDA_PYTHON_ENVPATH
                        /Users/lorenz/git/precommit.and.proj.renv/renv/python/r-reticulate
RMARKDOWN_MATHJAX_PATH
                        /Applications/RStudio.app/Contents/Resources/resources/mathjax-27
RS_PPM_FD_READ          17
RS_PPM_FD_WRITE         22
RS_RPOSTBACK_PATH       /Applications/RStudio.app/Contents/MacOS/rpostback
RS_SHARED_SECRET        168072824752491622650073
RSTUDIO_CONSOLE_COLOR   256
RSTUDIO_CONSOLE_WIDTH   100
RSTUDIO_FALLBACK_LIBRARY_PATH
                        /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/rstudio-fallback-library-path-XbyCqQ
RSTUDIO_PANDOC          /Applications/RStudio.app/Contents/MacOS/pandoc
RSTUDIO_PROGRAM_MODE    desktop
RSTUDIO_USER_IDENTITY   lorenz
RSTUDIO_WINUTILS        bin/winutils
SDKROOT                 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
SED                     /usr/bin/sed
SHELL                   /bin/zsh
SHLVL                   1
SSH_AGENT_PID           3781
SSH_ASKPASS             rpostback-askpass
SSH_AUTH_SOCK           /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T//ssh-MlikIsCZS0YT/agent.3780
TAR                     /usr/bin/tar
TERM                    xterm-256color
TMPDIR                  /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/
USER                    lorenz
XPC_FLAGS               0x0
XPC_SERVICE_NAME        0
ZSH                     /Users/lorenz/.oh-my-zsh
```

Which is oviously different from when I use `zsh`:
```
> Sys.getenv()
COLORFGBG               0;15
COLORTERM               truecolor
COLUMNS                 80
CONDA_EXE               /Users/lorenz/opt/miniconda3/bin/conda
CONDA_PYTHON_EXE        /Users/lorenz/opt/miniconda3/bin/python
CONDA_SHLVL             0
DISPLAY                 /private/tmp/com.apple.launchd.l9E1W2GNNS/org.xquartz:0
DYLD_FALLBACK_LIBRARY_PATH
                        /Library/Frameworks/R.framework/Resources/lib:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/server
EDITOR                  vi
HOME                    /Users/lorenz
ITERM_PROFILE           Default
ITERM_SESSION_ID        w0t0p0:D85E344D-F118-4AAC-8857-956C9CDE0FA8
LC_CTYPE                UTF-8
LC_TERMINAL             iTerm2
LC_TERMINAL_VERSION     3.4.10
LESS                    -R
LINES                   25
LN_S                    ln -s
LOGNAME                 lorenz
LSCOLORS                Gxfxcxdxbxegedabagacad
MAKE                    make
PAGER                   less
PATH                    /Users/lorenz/.poetry/bin:/Users/lorenz/Library/Preferences/netlify/helper/bin:/usr/local/opt/libpq/bin:/Users/lorenz/opt/miniconda3/condabin:/Users/lorenz/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD                     /Users/lorenz/.cache/pre-commit/repoop2cc2mv/renv-default
R_ARCH
R_BROWSER               /usr/bin/open
R_BZIPCMD               /usr/bin/bzip2
R_DOC_DIR               /Library/Frameworks/R.framework/Resources/doc
R_ENVIRON
R_ENVIRON_USER
R_GZIPCMD               /usr/bin/gzip
R_HOME                  /Library/Frameworks/R.framework/Resources
R_INCLUDE_DIR           /Library/Frameworks/R.framework/Resources/include
R_LIBS_SITE
R_LIBS_USER             ~/Library/R/x86_64/4.1/library
R_PAPERSIZE             a4
R_PDFVIEWER             /usr/bin/open
R_PLATFORM              x86_64-apple-darwin17.0
R_PRINTCMD              lpr
R_PROFILE
R_PROFILE_USER
R_QPDF                  /Library/Frameworks/R.framework/Resources/bin/qpdf
R_RD4PDF                times,inconsolata,hyper
R_SESSION_TMPDIR        /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T//RtmpZWzE1U
R_SHARE_DIR             /Library/Frameworks/R.framework/Resources/share
R_STRIP_SHARED_LIB      strip -x
R_STRIP_STATIC_LIB      strip -S
R_SYSTEM_ABI            macos,gcc,gxx,gfortran,gfortran
R_TEXI2DVICMD           /usr/local/bin/texi2dvi
R_UNZIPCMD              /usr/bin/unzip
R_ZIPCMD                /usr/bin/zip
SED                     /usr/bin/sed
SHELL                   /bin/zsh
SHLVL                   1
SSH_AGENT_PID           487
SSH_AUTH_SOCK           /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T//ssh-4qglsP4LuJWj/agent.486
TAR                     /usr/bin/tar
TERM                    xterm-256color
TERM_PROGRAM            iTerm.app
TERM_PROGRAM_VERSION    3.4.10
TERM_SESSION_ID         w0t0p0:D85E344D-F118-4AAC-8857-956C9CDE0FA8
TMPDIR                  /var/folders/6g/bg5mcmsj7s51r33snbxhm1400000gn/T/
USER                    lorenz
XPC_FLAGS               0x0
XPC_SERVICE_NAME        0
ZSH                     /Users/lorenz/.oh-my-zsh
_CE_CONDA
_CE_M
__CF_USER_TEXT_ENCODING
                        0x1F5:0x0:0x2
```

I tried to unset some of the `RSTUDIO_*` env variables, but no success.

I hope you can provide me some input in how to resolve the problem. Also, after running `source('renv/activate.R')` a second time, I don't get a warning, but is the correct renv now loaded or not? Calling `source('renv/activate.R')` multiple times sounds like a hack. The code pre-commit runs on setup can be found [here](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/r.py#L99-L127). I don't think it's necessary for this issue to have that context of pre-commit. And the above linked code is *not* run from the directory in which the user's renv exists, but in a pre-commit cache directory (where also the `renv.lock` exists for the hooks).

**Comment by lorenzwalthert** [comment]
Or should I just use `renv::load()`? This seems not to give the same warning.

**Comment by kevinushey** [comment]
> Is source('renv/activate.R') the right call to activate the renv? Or should I just use renv::load()?

`source("renv/activate.R")` is used to run the `renv` autoloader -- its job is basically to call `renv::load()`, after trying to find, install, and load the "right" version of `renv` for the project.

The main downside around using `renv::load()` is that you would still likely be using the version of `renv` in the user / global library, rather than the copy installed in the project library.

> This seems not to give the same warning but also does not work. I am not sure I understand the difference between activate(), load() and source('renv/activate.R').

`renv::activate()` is used to turn the project autoloader on and off (basically, enabling or disabling the `source("renv/activate.R")` part of the `.Rprofile`). The `renv` autoloader's job is to call `renv::load()`, but it does so after trying to ensure the "right" version of `renv` is installed and loaded from the project library.

**Comment by kevinushey** [comment]
I realize this is likely challenging, but do you think it's be possible to share a reproducible example? (e.g. as a bash script that uses different versions of `renv` to initialize different projects)

For what it's worth, if calling `renv::load()` directly works fine for you then I'd recommend just doing that.

**Comment by lorenzwalthert** [comment]
Thanks Kevin. I think I can create a reprex (not now though). Just though maybe you know a quick fix or where the problem lies without me providing a reprex, but if you think it's required going forward, I'll try to provide one soon.

**Comment by lorenzwalthert** [comment]
Here is a reprex

```bash
R -e 'install.packages("renv", repos = c(CRAN = "https://cloud.r-project.org"))'  # CRAN 0.14.0
mkdir /tmp/renv1
mkdir /tmp/renv2
cd /tmp/renv1
R -e 'renv::init(); renv::record("rstudio/renv@0.13.0")'
cd /tmp/renv2
R -e 'renv::init(); renv::record("rstudio/renv@0.12.0")'
R --vanilla -e 'usethis::create_project(".", rstudio = TRUE)'
# -> open RStudio project in /tmp/renv2
# Go to RStudio system terinal
# cd /tmp/renv1
# R (open R interactively) -> .Rprofile in wd -> `source('renv/activate.R')` gets executed
#> Warning messages:
#> 1: renv 0.14.0 was loaded from project library, but this project is configured to use renv 0.13.0.
#> Use `renv::record("renv@0.14.0")` to record renv 0.14.0 in the lockfile.
#> Use `renv::restore(packages = "renv")` to install renv 0.13.0 into the project library.
#> 2: could not load renv from project "/private/tmp/renv1"; reloading previously-loaded renv
```

**Comment by kevinushey** [comment]
Thanks for the bug report. I think I know what's going on now. In the terminal, `RENV_PROJECT` is set, so `renv` believes that the active project is `/private/tmp/renv2`. When R is started in `/private/tmp/renv1`, `renv` detects this as a "switch" from `renv2` to `renv1`.

This basically leads to the following sequence of events:

1. R calls `source("renv/activate.R")` in `renv1`,
2. `renv` tries to load the project,
3. `renv` sees that `RENV_PROJECT` is set, and so believes this is an attempt to "switch" the active project,
4. This leads to `renv_load_switch()`, which basically tries to run `source("renv/activate.R")` again.
5. The activation script has a recursion guard, which basically short-circuits the attempt to re-activate.

I think this is fixed in the development version of `renv`, so you shouldn't see this if you have two projects using the latest versions of `renv`:

https://github.com/rstudio/renv/blob/c5fbd794788d5b91765f6a53aef65ee00a41ce82/R/load.R#L43-L47

However, as a workaround you could unset `RENV_PROJECT` in the terminal, e.g.

```
MBP-P2MQ:renv1 kevin$ unset RENV_PROJECT
MBP-P2MQ:renv1 kevin$ R -s
* The project may be out of sync -- use `renv::status()` for more details.
Warning message:
renv 0.14.0 was loaded from project library, but this project is configured to use renv 0.13.0.
Use `renv::record("renv@0.14.0")` to record renv 0.14.0 in the lockfile.
Use `renv::restore(packages = "renv")` to install renv 0.13.0 into the project library. 
```

**Comment by lorenzwalthert** [comment]
Thanks Kevin for looking into it. A little christmas gift for me 🎅 👍 . This makes sense. Both the workaround and the dev version don't suffer from the problem anymore. Since I also want older versions of {renv} to work with pre-commit, I filed a PR there to unset that env variable.

**Comment by lorenzwalthert** [comment]
Since I am already talking to you about pre-commit, here's [how I activate the renv](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/r.py#L109-L114) in pre-commit:
```r
getwd()
#> ~/path/to/user/git/repo/where/hooks/are/used/on/commit
'old <- setwd('~/.cache/pre-commit/hook-repo-with-renv/')
source("renv/activate.R")
setwd(old)
renv::load('~/.cache/pre-commit/hook-repo-with-renv/')
```

Can't remember why I load it again after activating it, but does it hurt? On install, the repo is initiated and dependencies are `restored()` from the lockfile.

**Comment by kevinushey** [comment]
That seems strange to me -- calling `source("renv/activate.R")` should be sufficient, since the job of the autoloader is to call `renv::load()` anyhow.
