### ISSUE TITLE
renv::config$cache.symlinks() now returns NULL

### ISSUE THREAD

**Issue by zkamvar** [rstudio/renv#906]
I found a minor issue in my wrapper of {renv} where I was using `renv::config$cache.symlinks() && BOOL` to pass on to a {callr} env var so that I can turn off cache symlinks when I'm testing and still allow the user to choose this option when they are running locally (https://github.com/carpentries/sandpaper/issues/223).

The change came from https://github.com/rstudio/renv/commit/1709a19ff7de208642a225963dad8252556ee1fa and now `renv::config$cache.symlinks()` returns `NULL` on UNIX instead of `TRUE` or `FALSE` unless it is manually set beforehand. 

I am now wondering: how should I provision this situation?

**Comment by kevinushey** [comment]
Thanks! I think that was an oversight. For now, I think you can set it to `TRUE` if you see `NULL`. I'll try to fix that up.
