### ISSUE TITLE
`renv::restore()` using pak as backend?

### ISSUE THREAD

**Issue by rpodcast** [rstudio/renv#907]
I'm so excited to see the [initial support](https://rstudio.github.io/renv/news/index.html) for `pak` to install packages with `renv`! I have everything working for installing packages, but I am testing out the experience of cloning a project and restoring the packages, and running `restore()` still installs the packages one-by-one even with `RENV_CONFIG_PAK_ENABLED = TRUE` declared in the project's `.Renviron` file. Is there another way to trick `restore()` to leverage pak?

**Comment by kevinushey** [comment]
Not yet -- that work is being tracked on the `pak` side here. https://github.com/r-lib/pak/issues/343

**Comment by yonicd** [comment]
I saw that `renv::install()` can be ported to pak (NEWS 0.15.0) via an ENV var. is there any way to run the full restore via pak?

> renv gains experimental support for the [pak](https://pak.r-lib.org/) package. Set RENV_CONFIG_PAK_ENABLED = TRUE in an appropriate .Renviron file to enable pak integration. When enabled, calls to renv::install() will use pak to download and install packages.

**Comment by kevinushey** [comment]
I don't think the required infrastructure is available yet on the `pak` side.

**Comment by yonicd** [comment]
Sorry I didn’t explain correctly my question. If i set the env var to true and run renv::restore, should renv use pak to install the deps? Or is it not running renv::install (in a vectorized map) under the hood when it restores?

**Comment by yonicd** [comment]
Found it

restore [runs directly](https://github.com/rstudio/renv/blob/main/R/restore.R#L189) *_impl which is too downstream in the direct install() sequence and the pak [check clause](https://github.com/rstudio/renv/blob/main/R/install.R#L164) is done higher up. It should be possible to let pak drive restore too

**Comment by kevinushey** [comment]
> It should be possible to let pak drive restore too

But AFAIK `pak` doesn't support installation of packages from older versions, e.g.

```
> pak::pkg_install("renv@0.15.3")
Error: Cannot install packages:
* renv@0.15.3: Versioned CRAN packages are not implemented yet
Type .Last.error.trace to see where the error occurred
```

So until that's been implemented (or some other similar supporting infrastructure) we can't use `pak` for restore.

**Comment by yonicd** [comment]
ah. ok. thanks for the clarification

**Comment by hadley** [comment]
Closing in favour of #1210
