### ISSUE TITLE
Docker build error for local package using renv::restore()

### ISSUE THREAD

**Issue by kcawley** [rstudio/renv#909]
Hello, I am making the switch from packrat to renv for a project that we run in docker. For some reason during the docker build process, on the renv::restore() step, I am getting an error for installing our local package. Any ideas on how to get the local package to install during the docker build would be appreciated.

Warning: failed to find source for 'pkgInternal 2.0.0' in package repositories Warning: failed to retrieve 'https://cran.rstudio.com/src/contrib/Archive/pkgInternal/pkgInternal_2.0.0.tar.gz' [cannot open URL 'https://cran.rstudio.com/src/contrib/Archive/pkgInternal/pkgInternal_2.0.0.tar.gz']

Error: failed to retrieve package 'pkgInternal@2.0.0' In addition: Warning messages: 1: In (function (url, destfile, method, quiet = FALSE, mode = "w", :

The package tar is in the renv/local folder and the renv.lock file entry for the package is:

"pkgInternal": {
      "Package": "pkgInternal",
      "Version": "2.0.0",
      "Source": "/app/projectFolder/renv/local/pkgInternal_2.0.0.tar.gz",
      "Requirements": [
        "XML",
        "dataRetrieval",
        "eddy4R.base",
        "eddy4R.qaqc",
        "httr",
        "jsonlite",
        "stageQCurve",
        "uuid"
      ]
    },

**Comment by kcawley** [comment]
This issue can be closed. Turned out it was the two .gitignore files that are automatically generated. I had to delete "local/" from both and now it's working!

**Comment by kevinushey** [comment]
> This issue can be closed. Turned out it was the two .gitignore files that are automatically generated. I had to delete "local/" from both and now it's working!

Glad to hear it! You can also use `renv::settings$vcs.ignore.local(FALSE)` to instruct `renv` to stop trying to update that field in that project.
