### ISSUE TITLE
consider renv::init(bare = TRUE) for initializing project w/out populating private library

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#91]
Sometimes you just want a private library and the `renv` infrastructure without all the packages discovered + installed.

Technically, `renv::activate()` will work too but that seems less obvious.

**Comment by rpodcast** [comment]
I like this idea too.  I have situations where I want to bootstrap the infrastructure in a project that already has some R code implemented, but I want to control how the packages are installed (i.e. order of installation, custom versions, etc).  Most of the time I am disciplined enough to get packrat/renv set up right away before working on the project (hence the auto-discovery doesn't find anything), but sometimes I forget to do it right away.
