### ISSUE TITLE
renv should respect yaml style chunk options (like `eval: false`)

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/renv#912]
Currently, renv doesn't respect yaml style chunk options in Quarto/R Markdown documents so `eval = FALSE` and `eval: false` have different behaviours. For example, I have a document with intentionally broken code in a chunk. When I specify `#| eval: false` in the chunk, and `renv::snapshot()` gave me a warning:

```r
ERROR 1: <text>:441:15: unexpected input
440: #| eval: false
441: ggplot(data = _
                   ^

Please see `?renv::dependencies` for more information.
```

If I change the code chunk to be defined in the original way with `eval = FALSE`, renv doesn't complain.

**Comment by kevinushey** [comment]
Thanks for the bug report. One unfortunate result of this change is that `renv` will now require a YAML parser for static analysis of chunks, but ideally `renv` shouldn't require any external packages for static analysis.

I'll have to think about how to best handle this, but for now I'll probably just use a lazy solution...

**Comment by kevinushey** [comment]
Actually, I'm wrong -- we do depend on `yaml` specifically for parsing YAML items in R Markdown documents:

https://github.com/rstudio/renv/blob/a3b90eb88e25f7f8b86969e9396f6fdd1a2b15f5/R/dependencies.R#L598-L602

so that should be a way forward.

**Comment by kevinushey** [comment]
`renv 0.15.1` is now on CRAN, so hopefully this should work as expected now. Please let me know if you run into any more issues!

**Comment by mine-cetinkaya-rundel** [comment]
Just tested, works great, thank you!
