### ISSUE TITLE
renv 0.15.0 writes extra line breaks to DESCRIPTION files in specific cases

### ISSUE THREAD

**Issue by dfsnow** [rstudio/renv#914]
## Problem

`renv@0.15.0` seems to write extra CR characters to the DESCRIPTION file of installed packages under the following specific conditions:

- Installing a remote package from source to a Windows machine (GitLab, GitHub, etc.)
- While within an activated `renv` **_package_** project
- And the DESCRIPTION file of the installed remote package contains indented multi-line text such as below:

    ```
    Description: An R package to do lots of cool things and make good plots
        with many cool functions and statistics. Cats are cool. Dogs are cool too.
        Big long package description here.
    ```

After the remote package is installed via `renv`, the DESCRIPTION file will contain the info appended by `renv` plus additional line breaks after indented text. The text above becomes:

```
Description: An R package to do lots of cool things and make good plots

    with many cool functions and statistics. Cats are cool. Dogs are cool too.

    Big long package description here.
```

Or, with `cat -e DESCRIPTION`:

```
Description: An R package to do lots of cool things and make good plots^M^M$
    with many cool functions and statistics. Cats are cool. Dogs are cool too.^M^M$
    Big long package description here.^M$
```

The resulting DESCRIPTION file is unreadable (incorrect DCF format) and makes the package unusable.

I suspect this issue due the change in how `renv` handles installs for package projects. `0.15.0` move package project libraries to an external dir at `tools::R_user_dir("renv", "cache")`. Again, this only happens with >= 0.15.0 and only for package projects.

## More Info

NOTE: The line endings of the source package DESCRIPTION file don't seem to matter. My source package line endings are unix but are converted to windows endings on `renv::install()`.

`sessionInfo()`

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     
```

**Comment by kevinushey** [comment]
Can you please provide a reproducible example, just so I can be sure how this issue is reproduced?

**Comment by kevinushey** [comment]
Okay, I think this illustrates what you're seeing:

```
renv::install("r-lib/rlang")
descfile <- system.file("DESCRIPTION", package = "rlang")
system(paste("cat -e", descfile))
```

And:

```
> read.dcf(descfile)
Error in read.dcf(descfile) : 
  Found continuation line starting '  like the condition ...' at begin of record.
```

I'll take a look.

**Comment by kevinushey** [comment]
I believe this has been fixed with https://github.com/rstudio/renv/commit/78b4105e326dd01f9754a7e094fba6c07670d2ff.

Could you please try installing the development version of `renv`, and let me know if the issue appears to be fixed in your case?

**Comment by dfsnow** [comment]
I can confirm that 78b4105 fixes the issue. Thanks for the quick turnaround.

**Comment by kevinushey** [comment]
Thanks for confirming. I'll try to get a fixed version up on CRAN soon.
