### ISSUE TITLE
Confusing about `snapshot.type = "all"` and the R system package library

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#917]
**If this post is better suited for the RStudio Community, let me know and I'll post there.**

Me team and I use `snapshot.type = "all"` to capture all packages in a project library in the renv lock file. We primarily do this because a package may keep some dependencies in `Suggests`. When we install those Suggested packages to have the full features available to us, using `snapshot.type = "all"` ensures that those installed packages are recorded in the lock file (making the project portable and does not depend on any packages not listed in `renv.lock`).

An example of this is the survey package. The survey pkg lists the CompQuadForm pkg in Suggests. If CompQuadForm is installed, it is used in some p-value calculations. If it's not installed, the calculation falls back to another method. In our use case, we want to include CompQuadForm in the lock file, so whomever is running the code will restore the project's libraries and all calculations will be identical on all machines.

In the recent renv release, I am seeing that the system R library is included in `.libPaths()`. This update, coupled with `snapshot.type = "all"`, results in renv trying to snapshot every package installed on a user's system library to the project lock file.

```r
Restarting R session...

* Project 'C:/Users/SjobergD/GitHub/Writing-Function-with-the-tidyverse' loaded. [renv 0.15.1]
> .libPaths()
[1] "C:/Users/SjobergD/GitHub/my_project/renv/library/R-4.1/x86_64-w64-mingw32"
[2] "C:/Program Files/R/R-4.1.1/library"    
```

What workflow should we use to 1. Capture all packages we utilize (even when there is not a direct call to a function within that package (aka the package is being used internally in another package), and 2. not capture every installed package from the system library in each project's lock file.

Thank you! 🕺🏼

**Comment by kevinushey** [comment]
One solution -- you might need to re-enable the renv sandbox, e.g. in your `.Renviron`:

```
RENV_CONFIG_SANDBOX_ENABLED = TRUE
```

See https://github.com/rstudio/renv/issues/614 for motivation.

**Comment by ddsjoberg** [comment]
I am prepping a reproducible research with renv seminar in 2 months, and trying to understand all the use cases. I appreciate your kind and helpful responses so so much!

**Comment by kevinushey** [comment]
My pleasure! And given that there aren't a large number of `renv` experts out there yet, I'm happy to field any questions on the GitHub issue tracker for now. :-)

Let me know if this solution works for you, or if you can imagine something else that might make this easier to manage. It'd be nice if we had a solution that didn't rely on the sandbox being active.

**Comment by ddsjoberg** [comment]
Thank you so much! This solution works perfectly.

Now that the R system library is included by default, I wonder if the original intended use of `snapshot.type = "all"` is being met? When I started using it, I wanted every package I install in a renv project to be added to my lockfile. Are there users who want to snapshot every package in the system library? (I say this know there are an infinite number of setups and surely there are many scenarios I can't imagine!)

Maybe another snapshot type would be useful, e.g.`snapshot.type = "project.all"` that would include all packages installed into `"~/my_project/renv/library/R-4.1/x86_64-w64-mingw32"` library, but not those in the system library? It's my first idea, but would need to think through the repercussions more thoroughly
