### ISSUE TITLE
renv::activate() issue with cached library on travis

### ISSUE THREAD

**Issue by benkeser** [rstudio/renv#919]
With the update to v0.15, I am finding that `renv::activate(project = "path/to/project")` no longer correctly loads the project library when using a cached library on travis CI.

As recommended in the docs, we've been using 

```yaml
cache:
  directories:
  - "$HOME/.local/share/renv"
  - "$TRAVIS_BUILD_DIR/renv/library"
```

in `.travis.yml` and have not previously had any issues. However, our builds break with the update to v0.15.

It would be pretty time consuming to set up a fully reproducible example, but I'll try to summarize what I've seen in debugging.

The project structure is something like this:
````
/project
|_.Rprofile
|_.renv.lock
|_renv/
|_code/
|___script.R
````

As part of the build process, `script.R` is run from the `code` directory. `script.R` contains a call to `renv::activate`:

```r
renv::activate(project = "..")
```

If I check `.libPaths()` after this call I see

```r
"/home/travis/.cache/R/renv/library/repo-name-and-hash/R-4.1/x86_64-pc-linux-gnu"
```

But this directory does not contain project packages. It contains a folder called `renv` (which itself may contain the project packages, I'm not sure; I didn't poke around in it).

Also included in `.libPaths()` is 

```r
"/opt/R/4.1.1/lib/R/library"
```

which contains base R packages.

When I install the archived v0.14 of `renv` and run the same code `.libPaths()` shows

```r
"$TRAVIS_BUILD_DIR/renv/library/R-4.1/x86_64-pc-linux-gnu"
```

(where I've replaced the absolute path to the travis build directory with `$TRAVIS_BUILD_DIR`), which correctly loads the package library. 

In this case, `.libPaths()` also includes 

```r
"/tmp/RtmpZpPlNF/renv-system-library"
```

which contains the base R packages.

The issue seems to be isolated to using the `project` option of the call to `renv::activate` -- under v0.15 I am able to correctly load the package library if I open `R` in the `/project` folder (thereby loading `.Rprofile`, thereby calling `renv::activate()`).

I'm unable to reproduce this behavior locally on my Mac, which makes me believe it's somehow related to cache'ing on travis.

**Comment by kevinushey** [comment]
> "/home/travis/.cache/R/renv/library/repo-name-and-hash/R-4.1/x86_64-pc-linux-gnu"

What kind of project are you using? A recent change in `renv` now ensures that R package projects no longer use a project-local library path. For example:

```
#!/usr/bin/env bash

cd "$(mktemp -d)"

R -e 'usethis::create_package("testing")'
cd testing
R -e 'renv::init()'
R -e '.libPaths()'
```

I see:

```
* Project '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.QqK1aBOU/testing' loaded. [renv 0.15.1]
> .libPaths()
[1] "/Users/kevin/Library/Caches/org.R-project.R/R/renv/library/testing-95186240/R-4.1/aarch64-apple-darwin21.1.0"
[2] "/opt/homebrew/Cellar/r/4.1.2/lib/R/library"
```

And from NEWS:

```
* `renv` now uses an external library by default for R package projects,
  with the library located within `tools::R_user_dir("renv", "cache")`.
  This directory can be configured via the `RENV_PATHS_LIBRARY_ROOT`
  environment variable if desired. See
  `vignette("packages", package = "renv")` for more details. (#384)
```

If you're working within a package project but still want a project-local library, you can set

```
RENV_PATHS_LIBRARY = renv/library
```

in e.g. `.Renviron`.

**Comment by benkeser** [comment]
It’s not an R package project.

**Comment by hadley** [comment]
@benkeser is this still a problem for you?
