### ISSUE TITLE
Allow local folders to act as package sources

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#92]
It would be convenient if `Source` in the renv.lock could point to a location on the file system. I think this could serve a variety of use cases however my specific case is that I have a work project which has a package dependency attached as a git submodule. 

Trust me that there is a sane reason for doing this involving working within some arduous security constraints.

Currently when I install the package with `devtools::install` and follow with `renv::snapshot`, this dependency gets the source set to `unknown`.

It might be work considering something in settings, e.g. `local.packages`, where I could add paths for `renv` to look for things like this.

**Comment by kevinushey** [comment]
Part of this was implemented here:

https://github.com/rstudio/renv/commit/77c8519c160dda819572e187f494f15f9bc85fd8

That is, `renv` does understand when `Source` points to an explicit path. The question, though, is how should `renv::snapshot()` know that this particular path should be used when generating the lockfile?

It looks like `remotes::install_local()` does annotate the DESCRIPTION with the path used, e.g.

```
RemoteType: local
RemoteUrl: /Users/kevin/r/pkg/skeleton
```

I'll see what else needs to be done to wire this through in `renv`.

**Comment by kevinushey** [comment]
This should be handled now:

1. `renv` understands how to restore packages that use `remotes::install_local()`;
2. Otherwise, you can use `renv`'s own "local sources" system: https://rstudio.github.io/renv/articles/local-sources.html

I believe the simplest way forward (if it works for you) is to simply switch to using `remotes::install_local()` when installing packages from local sources.

If this is insufficient please let me know and feel free to re-open!

**Comment by MathieuMarauri** [comment]
Hello, 

I am trying to install a package that is on my computer inside an renv project. I could not make it work with your second point but `remotes::install_local()` works. Nevertheless the path in the `renv.lock` file is not relative to the R project but to my computer (Users/... ). 

How can I tell `remotes::install_local()` to update the DESCRIPTION file according to the project path?
How to use the local sources system to avoid installing `remotes`?

Thanks for your work, it is appreciated.
Cheers, 
Mathieu

**Comment by kevinushey** [comment]
If I understand correctly, you would have to request this directly in `remotes` -- this seems independent from `renv`.

**Comment by jlopezper** [comment]
@MathieuMarauri how did you finally manage to fix this? I have the exact same problem.

Thanks in advance.

**Comment by kevinushey** [comment]
FWIW, the renv "local sources" approach is basically an escape hatch -- you place package tarballs / binary archives into the project folder at `renv/local`, and `renv` uses those in lieu of whatever external source is declared by the package. See https://rstudio.github.io/renv/articles/local-sources.html for more details.

**Comment by dancingfrog** [comment]
> FWIW, the renv "local sources" approach is basically an escape hatch -- you place package tarballs / binary archives into the project folder at `renv/local`, and `renv` uses those in lieu of whatever external source is declared by the package. See https://rstudio.github.io/renv/articles/local-sources.html for more details.

This link is dead.

**Comment by isaactpetersen** [comment]
I'm getting a similar error when trying to test my package:
```
E  checking whether package 'petersenlab' can be installed (8s)
   Installation failed.
   See 'D:/Documents/GitHub/petersenlab.Rcheck/00install.out' for details.
   
   See
     'D:/Documents/GitHub/petersenlab.Rcheck/00check.log'
   for details.
   
   
-- R CMD check results ----------------------------------------------------------------- petersenlab 0.1.1 ----
Duration: 13.1s

> checking whether package 'petersenlab' can be installed ... ERROR
  See below...

-- Install failure --------------------------------------------------------------------------------------------

* installing *source* package 'petersenlab' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'petersenlab' in library.dynam(lib, package, package.lib):
 DLL 'survival' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'D:/Documents/GitHub/petersenlab.Rcheck/petersenlab'

1 error x | 0 warnings v | 0 notes v
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.
```

My package is here:
https://research-git.uiowa.edu/PetersenLab/petersenlab

Using `install.packages("survival", INSTALL_opts = c("--no-multiarch"))` did not fix the error.

**Comment by kevinushey** [comment]
```
*** arch - i386
Error: package or namespace load failed for 'petersenlab' in library.dynam(lib, package, package.lib):
 DLL 'survival' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
```

Just guessing, but you might need to reinstall the `survival` package.

**Comment by isaactpetersen** [comment]
Here's my `reprex()`:

```
renv::install("survival", INSTALL_opts = c("--no-multiarch"))
#> Retrieving 'https://cran.r-project.org/src/contrib/survival_3.3-1.tar.gz' ...
#>  OK [file is up to date]
#> Installing survival [3.3-1] ...
#>  OK [built from source]
#> Moving survival [3.3-1] into the cache ...
#>  OK [moved to cache in 5.8 seconds]

sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.29   withr_2.5.0     magrittr_2.0.2  reprex_2.0.1   
#>  [5] evaluate_0.15   highr_0.9       stringi_1.7.6   rlang_1.0.2    
#>  [9] cli_3.2.0       renv_0.15.4     rstudioapi_0.13 fs_1.5.2       
#> [13] rmarkdown_2.12  tools_4.1.2     stringr_1.4.0   glue_1.6.2     
#> [17] xfun_0.30       yaml_2.3.5      fastmap_1.1.0   compiler_4.1.2 
#> [21] htmltools_0.5.2 knitr_1.37
Created on 2022-03-05 by the reprex package (v2.0.1)

==> devtools::check(document = FALSE)

-- Building ------------------------------------------------------------------------------------ petersenlab --
Setting env vars:
* CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
* CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
* CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
* CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
* CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
* CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
---------------------------------------------------------------------------------------------------------------
v  checking for file 'D:\Documents\GitHub\petersenlab/DESCRIPTION' ...
-  preparing 'petersenlab': (1.4s)
v  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (761ms)
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'petersenlab_0.1.1.tar.gz'
   
-- Checking ------------------------------------------------------------------------------------ petersenlab --
Setting env vars:
* _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
* _R_CHECK_CRAN_INCOMING_       : FALSE
* _R_CHECK_FORCE_SUGGESTS_      : FALSE
* NOT_CRAN                      : true
-- R CMD check ------------------------------------------------------------------------------------------------
-  using log directory 'D:/Documents/GitHub/petersenlab.Rcheck'
-  using R version 4.1.2 (2021-11-01)
-  using platform: x86_64-w64-mingw32 (64-bit)
-  using session charset: ISO8859-1
-  using options '--no-manual --as-cran'
v  checking for file 'petersenlab/DESCRIPTION' ...
-  checking extension type ... Package
-  this is package 'petersenlab' version '0.1.1'
-  package encoding: UTF-8
v  checking package namespace information
v  checking package dependencies (4s)
v  checking if this is a source package ... 
v  checking if there is a namespace
v  checking for executable files (743ms)
v  checking for hidden files and directories ... 
v  checking for portable file names ... 
v  checking serialization versions ...
E  checking whether package 'petersenlab' can be installed (7.8s)
   Installation failed.
   See 'D:/Documents/GitHub/petersenlab.Rcheck/00install.out' for details.
   
   See
     'D:/Documents/GitHub/petersenlab.Rcheck/00check.log'
   for details.
   
   
-- R CMD check results ----------------------------------------------------------------- petersenlab 0.1.1 ----
Duration: 14s

> checking whether package 'petersenlab' can be installed ... ERROR
  See below...

-- Install failure --------------------------------------------------------------------------------------------

* installing *source* package 'petersenlab' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'petersenlab' in library.dynam(lib, package, package.lib):
 DLL 'survival' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'D:/Documents/GitHub/petersenlab.Rcheck/petersenlab'

1 error x | 0 warnings v | 0 notes v
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.
```

Any ideas? Thanks for your help with this!

**Comment by kevinushey** [comment]
The problem here is you're installing a single architecture build of the `survival` package (by virtue of using `--no-multiarch`), but `devtools::check()` is attempting to build and check for both architectures. The check on the i386 architecture fails because `survival` was not built for that architecture.

I'm not sure if there's a way to force `--no-multiarch` to be set in this context. Maybe `devtools::check(args = "--no-multiarch")`?
