### ISSUE TITLE
renv::init() and renv::status() fail with unexpected '!'

### ISSUE THREAD

**Issue by dmonder** [rstudio/renv#921]
Both renv::init() and renv::status() fail with unexpected '!' when encountering the following code snippet:

```
    if (is.na(ay_type)) {
        ay_type <- "FSS"
    } else {
        if !(ay_type %in% ("FSS","SFS")) {
            return( NA )
        }
    }
```

As this is a valid use of '!' as a logical NOT operator, I think there might be an error in the renv. Any thoughts?

**Comment by kevinushey** [comment]
Are you sure? I see a parse error if I try to parse this with R.

``` r
code <- '
  if (is.na(ay_type)) {
    ay_type <- "FSS"
  } else {
    if !(ay_type %in% ("FSS","SFS")) {
      return( NA )
    }
  }
'

script <- tempfile(fileext = ".R")
writeLines(code, con = script)
parse(script)
#> Error in parse(script): /var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//RtmpeAJ0ZF/file201ecd5a952.R:5:8: unexpected '!'
#> 4:   } else {
#> 5:     if !
#>           ^
```

<sup>Created on 2022-01-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
