### ISSUE TITLE
renv::clean returns function object instead of the project directory

### ISSUE THREAD

**Issue by jabenninghoff** [rstudio/renv#922]
`renv::clean` returns the `renv::status` function object instead of 'The project directory, invisibly.' as [documented](https://rstudio.github.io/renv/reference/clean.html).

Reproducible example. This should return `FALSE`.

```
> identical(renv::clean(), renv::status)
* No stale package locks were found.
* No temporary directories were found in the project library.
* No unused packages were found in the project library.
* The project has been cleaned.
[1] TRUE
```

While the documentation states that the return value is the project directory, the code for clean returns (line 99 of clean.R):

```r
invisible(status)
```

It seems like the intent is to return `invisible(status())`. If so, can this be corrected and the documentation updated?

**Comment by kevinushey** [comment]
Thanks! I've instead changed the implementation to match the documentation.
