### ISSUE TITLE
Feature Request: Project-level `snapshot.type = "all"`

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/renv#923]
Hey Hey @kevinushey ! Following up on our previous conversation in #917

> Now that the R system library is included by default, I wonder if the original intended use of `snapshot.type = "all"` is being met? When I started using it, I wanted every package I install in a renv project to be added to my lockfile. Are there users who want to snapshot every package in the system library? (I say this know there are an infinite number of setups and surely there are many scenarios I can't imagine!)
> 
> Maybe another snapshot type would be useful, e.g.`snapshot.type = "all.project"` that would include all packages installed into `"~/my_project/renv/library/R-4.1/x86_64-w64-mingw32"` library, but not those in the system library? 

After thinking about this for a couple of days, my preference would be for `snapshot.type = "all"` to only capture the packages installed to the project library (not capturing all pkgs from the system library).

Are there users who really do want to snapshot the entire system library? I can't image anyone wanting this, and if there are, they surely are a small minority?

Thanks! 👯

**Comment by kevinushey** [comment]
> Are there users who really do want to snapshot the entire system library? I can't image anyone wanting this, and if there are, they surely are a small minority?

I agree with that, but I'm still not positive if I want to make this change since it's technically doing what it's documented to do.

Would it be feasible for you to use a custom snapshot type? You could then do something like:

```
options(renv.snapshot.filter = function(project) {
    # list packages in non-system library paths, get their recursive dependencies,
    # and return the names of those packages
})
renv::settings$snapshot.type("custom")
```

That hook would need to live in the project; e.g. at `renv/settings.R` or directly in the project `.Rprofile` or similar.

**Comment by kevinushey** [comment]
I could also just add a new snapshot type to indicate that only the project library should be snapshotted...

**Comment by ddsjoberg** [comment]
🤔 I think for a few power-users, the custom snapshot type would work well. In my dept, however, we primarily have users for whom a custom option probably wouldn't get used due to the complexity. In the academic setting, it's already difficult to get researchers to utilize reproducibility tools, and I think the custom snapshot type/function may be too much for them.

I think the two most user-friendly options are these:
1. Update `snapshot.type = "all"` to only capture the project library, and update the renv documentation. I like this because I think it's likely how most users would expect it to work. While it technically is a breaking change, it does restore the functionality to be what it was before the v0.15.0 release.
2. A new snapshot type to only capture pkgs in the project library, e.g. `snapshot.type = "all.project"`

I still lean toward the first, but either of them would be great!

**Comment by hadley** [comment]
It seems like including the base packages in `type = "all"` is not often going to be useful (since their versions are mostly bound to the R version), I think `type = "all"` should automatically ignore the "base" library.

**Comment by ddsjoberg** [comment]
This issue may now be out of date. In a previous version of renv, the paths returned by `.libPaths()` included both the renv, project-specific folders and also the system library (e.g. mine is located here `"C:/Program Files/R/R-4.3.0/library"`). When we used the snapshot all option, the packages in both the project-specific renv libraries and the system library (including base packages and any other package we've installed) were snapshotted into the `renv.lock` file.

But, the system library is no longer included in a renv project, so from my POV, this is no longer an issue.

I won't close this as you brought up handling of base packages, and leave it to you two to decide.

Thank you

**Comment by kevinushey** [comment]
> But, the system library is no longer included in a renv project, so from my POV, this is no longer an issue.

I suspect this is solved by the system library sandbox? (Since that "shields" any renv projects from other packages installed into a system library)

**Comment by hadley** [comment]
If I create a new project, then do `renv::init()`, `renv::snapshot(type = "all")` gives me:

```
> renv::snapshot(type = "all")
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- KernSmooth   [* -> 2.23-20]
- MASS         [* -> 7.3-58.2]
- Matrix       [* -> 1.5-3]
- boot         [* -> 1.3-28.1]
- class        [* -> 7.3-21]
- cluster      [* -> 2.1.4]
- codetools    [* -> 0.2-19]
- foreign      [* -> 0.8-84]
- lattice      [* -> 0.20-45]
- mgcv         [* -> 1.8-42]
- nlme         [* -> 3.1-162]
- nnet         [* -> 7.3-18]
- rpart        [* -> 4.1.19]
- spatial      [* -> 7.3-16]
- survival     [* -> 3.5-3]
```

That's not expected, right?

**Comment by kevinushey** [comment]
I believe it is expected -- those are recommended packages, not base packages, and aren't guaranteed to be available in some scenarios (e.g. some builds of R on Linux come without recommended packages) so it's important we record them.
