### ISSUE TITLE
Shiny Project Using Renv Won’t Open in RSSP Session

### ISSUE THREAD

**Issue by kcsimon21** [rstudio/renv#924]
I have a Shiny project using renv that fails to open in a new RStudio Server Pro session (i.e., when I try to start the project in a new session, I get a spinning loading wheel that runs indefinitely). Once I deleted the renv folder and the lock file from the repo, I was then able to start the project in a new session, close the session, and reopen. Something about the presence of renv in the project is bugging out the RSSP session, but I’m having trouble isolating the exact problem.

**Comment by kevinushey** [comment]
Sorry to hear you're having trouble! If you're using RStudio Server Pro, you would be eligible for RStudio's support services -- please get in touch with the support team at support@rstudio.com.

For extra information, what do you see if you try to load the project manually, e.g. by running:

```
renv::load("/path/to/project")
```

Does `renv` load the project successfully? Or does the R session then hang as well?

Is there any opportunity for you to replicate this behavior in an RStudio terminal, e.g. by launching an R process within that project directory from the terminal?

**Comment by kcsimon21** [comment]
Hi Kevin, thanks for the quick response! 

I first tried loading the project manually from a blank session like you suggested, and it looks like the R session is hanging there too. After running renv::load( ), I just see "# Bootstrapping renv 0.14.0 --------------------------------------------------" indefinitely in the console. 

I had the same exact issue when trying to run one of the project's R scripts from within the RSSP terminal.

**Comment by kcsimon21** [comment]
If it's helpful context at all, the original project I created in RSSP does work. I can make edits, commit and push changes to Git, end the session, and restart the session later and keep working. We noticed this behavior when a colleague of mine tried to clone the project into his own RSSP environment; when he checked out the branch that uses renv (the original project branch did not have renv enabled), the project wouldn't restart when he ended the session and tried to get back in. To test if it was just his problem, I tried creating a new project in my RSSP environment by just cloning in that same project from our Git repo. Weirdly enough, I'm having the same problems described above.

**Comment by kcsimon21** [comment]
After looking into the code in activate.R, I think I might have an idea of what's potentially going on -- renv is automatically bootstrapping itself (as it should), which means that renv isn't in the project library (I think?). Since the renv version number is 4 digits (0.14.0), it's trying to bootstrap from Github. I think that's where the problem lies -- I'm working in RSSP on a corporate network, and in the past, I haven't been able to install packages from Github (I think it has something to do with corporate security measures, or firewalls, or something -- I'm definitely no expert when it comes to that sort of thing). 

If that sounds feasible, is there some kind of workaround I might try?

**Comment by kevinushey** [comment]
`renv` should only look at GitHub if the version number has four components; that is, three separate `.`s in the version string.

It seems like `renv` is most likely trying to download itself from CRAN during bootstrap (maybe from the wrong repository?) and that's hanging / failing.

For what it's worth, a change in renv 0.15.0 ensures that renv will use the repositories declared in the project lockfile (if any) during bootstrap if possible; if the issue here is indeed renv trying to reach out to the public CRAN mirror and failing, then I think upgrading to the latest version of renv should resolve your issue.

**Comment by hadley** [comment]
@kcsimon21 please let us know if upgrading to latest renv didn't fix your probelm.
