### ISSUE TITLE
renv keeps system library in .libPaths()

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/renv#93]
On my PC if I set up a new `renv` environment I with `renv::activate()` or `renv::init()` and restart my R session, my library paths look like this:

```
.libPaths()
[1] "c:/repos/demand_forecast_hex_characteristics/renv/library/R-3.6/x86_64-w64-mingw32"
[2] "c:/R/R-3.6.0/library"                                                              
```

Which creates headaches as the presence of system library stops me from being able to test whether the packages installed into my local library are sufficient to run my project.

I just checked `packrat` and the result of running `packrat::init()` and restarting my R session is this:

```
.libPaths()
[1] "c:/repos/demand_forecast_hex_characteristics/packrat/lib/x86_64-w64-mingw32/3.6.0"    
[2] "c:/repos/demand_forecast_hex_characteristics/packrat/lib-ext/x86_64-w64-mingw32/3.6.0"
[3] "c:/repos/demand_forecast_hex_characteristics/packrat/lib-R/x86_64-w64-mingw32/3.6.0"  
```

I am not sure whether `renv`'s behaviour is intended or a bug? The total isolation approach of `packrat` is more useful in my workflow.

**Comment by kevinushey** [comment]
This is mainly because the sandboxing done by Packrat tended to fail in obscure ways, e.g.

https://github.com/rstudio/packrat/issues/542
https://github.com/rstudio/packrat/issues/534
https://github.com/rstudio/packrat/issues/498

There's probably a sensible way to overcome this issue, but I'm not yet sure what the best way to do that is.

**Comment by MilesMcBain** [comment]
Ahhhh okkkkay. I don't fully understand these but I think I see the shape of the problem - Having the system lib in the path ensures you can fall back to it for the base packages which can't be installed from repos?

I think what this means is for me is that to have a smooth `renv` experience I should avoid installing things into my system library and should configure an `R_LIBS_USER` for general use which can be replaced with my project-local library.

**Comment by kevinushey** [comment]
I've tried implemented support for sandboxing of R system libraries in the development version of `renv`, but I haven't turned it on by default. If you want to give it a try, you can set:

```
options(renv.config.sandbox.enabled = TRUE)
```

e.g. in your user profile. If you do this, you should see something like:

```
> .libPaths()
[1] "/Users/kevin/scratch/appy/renv/library/R-3.6/x86_64-apple-darwin15.6.0"
[2] "/private/var/folders/qt/txb728ms5012wp_4yn369wth0000gn/T/RtmpDTEqMb/renv-system-library-29936a31f4e4"
```

when you open your renv projects.
