### ISSUE TITLE
Remedy for R version mismatch warning

### ISSUE THREAD

**Issue by ck37** [rstudio/renv#931]
It would be helpful if the warning message "This project is configured to use R version X, but Y is currently being used." included a command to remedy the warning. E.g. is it possible to provide a command like "Run `renv::snapshot('R')`" to specifically update the R version recorded in the lockfile?

From my googling I have only found renv::snapshot(), which may change other packages that the user doesn't want to change.

It also seems unfortunate that renv::status() does not display the R version mismatch or provide a remedy.

**Comment by kevinushey** [comment]
One option would be to use `renv::modify()` to interactively modify and update the version of R as used in the lockfile -- would that be sufficient?

I've also made a change in the development version of `renv` to make modifying a lockfile a little easier; you should now be able to do something like:

```
renv::modify(changes = list(R = list(Version = "4.1.3")))
```

The interface is a little verbose, but does allow for arbitrary changes in the lockfile.

**Comment by kevinushey** [comment]
That said, it seems like it should be relatively rare for one to want to update the version of R used in a project, but not the R packages as well -- there usually isn't a strong guarantee that older versions of packages will work as expected with new (or different) versions of R.

**Comment by kevinushey** [comment]
@gaborcsardi has a new project [rim](https://github.com/gaborcsardi/rim) that might do what you're hoping here -- it's also possible that `renv` could depend on and use `rim` in the future to help handle R version management.

**Comment by mmuurr** [comment]
Re: {rim}, oh neat, thanks! I'll follow that closely, as I'm generally a fan of anything Gábor produces :-)

**Comment by kevinushey** [comment]
Me too :-)

**Comment by hadley** [comment]
Sounds like rig provides the tooling needed here but we'll continue to think about renv can also do better.
