### ISSUE TITLE
Slow renv::status() and snapshot() with large R files

### ISSUE THREAD

**Issue by psimm** [rstudio/renv#932]
Hi, I'm working with renv and the package [dittodb](https://github.com/ropensci/dittodb), which creates mocks of database queries. These mock files are `.R` files and live in the `tests/` folder. I have many of these mocks and some of them are quite large (megabytes). Running `renv::status()` and `renv::snapshot()` take a very long time (I stopped it after 30 minutes). When I remove the large `.R` files, the functions run normally and quickly.

My current workaround is to move the large files to another location on my computer, run renv, then move the large files back.

Is there a more efficient way to limit the scope of `status()` and `snapshot()`? Perhaps an argument could be added to them?

**Comment by kevinushey** [comment]
I think you could use a `.renvignore` (as documented in `?renv::dependencies`) to tell `renv` to ignore those files.

If you include a file called `.renvignore` in your `tests` folder, with the contents:

```
*.R
```

does that work for you?

**Comment by psimm** [comment]
That works perfectly for me! Thank you so much.
