### ISSUE TITLE
Bioconductor packages on github not installing dependencies

### ISSUE THREAD

**Issue by macroscian** [rstudio/renv#934]
If I attempt to load a github repository of a Bioconductor package, e.g.
```
renv::install("mikelove/DESeq2")
```
I get a series of unavailable (bioconducor) packages - I can install these one-by-one, but is there a way I can force it do recognise that these dependencies do exist? I can do an `install("bioc::DESeq2")` and then install the github on top of that, but my _real_ problem is that I want to install my own bioconductor-dependent package which is only on github and not in the bioconductor repos, and would like a quick way of creating an environment for that - is there an easy way to do that?

```renv::install("mikelove/DESeq2")
Retrieving 'https://api.github.com/repos/mikelove/DESeq2/tarball/f722b14ad9793f88e06be0d56d8adf8f1a6e1b53' ...
        OK [downloaded 641 Kb in 0.7 secs]
Error: package 'BiocGenerics' is not available
In addition: Warning messages:
1: package 'BiocGenerics' is not available 
2: no MRAN records available from repository URL '/bin/windows/contrib/4.0' 
Traceback (most recent calls last):
15: renv::install("mikelove/DESeq2")
14: retrieve(names(remotes))
13: handler(package, renv_retrieve_impl(package))
12: renv_retrieve_impl(package)
11: renv_retrieve_github(record)
10: renv_retrieve_package(record, url, path)
 9: renv_retrieve_successful(record, path)
 8: retrieve(package)
 7: handler(package, renv_retrieve_impl(package))
 6: renv_retrieve_impl(package)
 5: records[[package]] %||% renv_retrieve_missing_record(package)
 4: renv_retrieve_missing_record(package)
 3: renv_available_packages_latest(package)
 2: stopf("package '%s' is not available", package)
 1: stop(sprintf(fmt, ...), call. = call.)
```

**Comment by macroscian** [comment]
Your suggestion has solved this and so many other niggles I was having with renvs - many thanks.

**Comment by kevinushey** [comment]
Great, I'm glad to hear it!

I'm going to keep this issue open to track https://github.com/rstudio/renv/issues/934#issuecomment-1035342573; in particular, `renv` should ideally be able to handle this without requiring you to set the `repos` option.
