### ISSUE TITLE
Error when trying to install additional packages: `Warning messages: ...pkg_name/DESCRIPTION': No such file or directory)`

### ISSUE THREAD

**Issue by GitHunter0** [rstudio/renv#935]
Hey guys, could you give me some help here, please? Maybe it is a trivial issue but it is driving me nuts...

Steps to reproduce the issue:

(1) Create a DESCRIPTION file
(2) `renv::activate()`
(3) `renv::install()` to install packages from the DESCRIPTION (many times it freezes here and I have to restart session and run the command again)
(4) `renv::snapshot(type="explicit")` 

So far things are working, but then when I try to install additional packages (`tictoc` for example) via `renv::install('tictoc')` or `install.packages('tictoc')`, it returns this error message:

´´´
Retrieving 'https://cloud.r-project.org/bin/windows/contrib/4.1/tictoc_1.0.1.zip' ...
	OK [file is up to date]
Installing tictoc [1.0.1] ...
	OK [installed binary]
Moving tictoc [1.0.1] into the cache ...
	OK [moved to cache in 5.5 seconds]
Warning messages:
1: In file(con, "rb") :
  cannot open file 'C:\Users\myname\AppData\Local/R/cache/R/renv/cache/v5/R-4.1/x86_64-w64-mingw32/tictoc/1.0.1/5acb66b0266ad1f0ebf7ffe1aa36ff4c/tictoc/DESCRIPTION': No such file or directory
2: In file(con, "rb") :
  cannot open file 'C:\Users\myname\AppData\Local/R/cache/R/renv/cache/v5/R-4.1/x86_64-w64-mingw32/tictoc/1.0.1/5acb66b0266ad1f0ebf7ffe1aa36ff4c/tictoc/DESCRIPTION': No such file or directory
´´´

Do you know what's happening?

Thank you.

```  .libPaths()
[1] "C:/Users/myname/AppData/Local/R/cache/R/renv/library/Global_Data_App-08ebaf5b/R-4.1/x86_64-w64-mingw32"
[2] "C:/Program Files/R/R-4.1.1/library" 
```

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices datasets 
[5] utils     methods   base     

other attached packages:
[1] renv_0.15.2

loaded via a namespace (and not attached):
[1] compiler_4.1.1 tools_4.1.1  
```

**Comment by GitHunter0** [comment]
I found out that if I delete the folder `C:\Users\myname\AppData\Local/R/cache/R/renv/cache/v5/R-4.1/x86_64-w64-mingw32/[pkg_name]` , then the installation works.

**Comment by kevinushey** [comment]
Glad you were able to get it sorted! If it happens again, please let us know.

> cannot open file 'C:\Users\myname\AppData\Local/R/cache/R/renv/cache/v5/R-4.1/x86_64-w64-mingw32/tictoc/1.0.1/5acb66b0266ad1f0ebf7ffe1aa36ff4c/tictoc/DESCRIPTION': No such file or directory

This makes me think that something went wrong when copying `tictoc` to the package cache when it was last installed, but it's hard to know for sure.

**Comment by GitHunter0** [comment]
> Glad you were able to get it sorted! If it happens again, please let us know.

I will @kevinushey , thank you!

I have just one remaining question if I may:

First my library paths were:
```
[1] "C:/Users/myname/AppData/Local/R/cache/R/renv/library/Global_Data_App-08ebaf5b/R-4.1/x86_64-w64-mingw32"
[2] "C:/Program Files/R/R-4.1.1/library" 
```
Then, after some session restarts it automatically switched to:
```
[1] "My_Project_Directory/renv/library/R-4.1/x86_64-w64-mingw32"
[2] "C:/Program Files/R/R-4.1.1/library"    
```
But then I lost all my packages and had to reinstall them! This issue is happening frequently, so how can I avoid `renv` to suddenly without warning change `renv` default library path from cache to local?

**Comment by kevinushey** [comment]
How are you setting the library paths in your project? By default, the project library resolves to a project-local location, as in your second example.

My guess is that you're setting a custom library path that `renv` isn't seeing after an (RStudio?) session restart.

**Comment by GitHunter0** [comment]
Hey @kevinushey , actually I'm not setting a custom a setting, I'm letting `renv` automatically defines the library path. I just do `renv::activate()` and then `renv::install()` to install what is in my DESCRIPTION. Is there something wrong with this procedure?

**Comment by kevinushey** [comment]
@GitHunter0 Thanks, I think I understand now. Are you using `renv` within an R package project? Do you see this after building and installing the package in RStudio?

If so, the issue may be fixed in the development version of `reticulate`.

**Comment by GitHunter0** [comment]
Thank you for the reply @kevinushey , the crazy thing is that it is a conventional RStudio project, in which I run a Shiny app (and I do not use `golem`, so it is not a package).

Do you have a guideline for properly setting `.libPaths()` and `renv cache path` **manually** in a way `renv` understands? This would help a lot I think.
