### ISSUE TITLE
`.libPaths` is being updated when suspended session is restored

### ISSUE THREAD

**Issue by Mosk915** [rstudio/renv#936]
I'm using RStudio Workbench, and have an renv-enabled project.  When the the project is first opened, `.libPaths` looks like this:

```r
> .libPaths()
[1] "/home/comzm/renv_test/renv/library/R-4.0/x86_64-pc-linux-gnu"
[2] "/opt/R/4.0.5/lib/R/library"   
```

After awhile of inactivity, the R session will enter a suspended state (it can also be forcibly suspended from the home screen to avoid having to wait).  Then when the session is resumed, `.libPaths` looks like this:

```r
> .libPaths()
[1] "/home/comzm/renv_test/renv/library/R-4.0/x86_64-pc-linux-gnu"
[2] "/opt/R/4.0.5/lib/R/library"                                  
[3] "/rlibrary/4.0"    
```

The third path is our site library that we set in `Rprofile.site` for use with non-renv-enabled projects.  It shouldn't be part of `.libPaths` in renv-enabled projects.

Restarting R correctly removes the third path from `.libPaths`.

I can see that when first opening the project or after restarting R, `.Library.site` is correctly set to `NULL`, but when resuming a suspended session, `Library.site` is set to `"/rlibrary/4.0"`.  If there is some code that runs to prevent `.Library.site` from being set, or overriding it once it is, that code doesn't seem to be triggered when resuming a suspended session.

**Comment by kevinushey** [comment]
I've spent a little bit of time investigating, and I think your call to `.libPaths()` may be superfluous -- you should only need to set `.Library.site`, and then the updated library paths will be available once R has finished starting up. Does that work as you expect?

**Comment by Mosk915** [comment]
Without the line `.libPaths(.libPaths())` in `Rprofile.site`, the site library isn't available.  The way we have `Rprofile.site` set up is based on the help page for `.libPaths`.

```
Function .libPaths always uses the values of .Library and .Library.site in the base namespace. .Library.site can be set by the site in ‘Rprofile.site’, which should be followed by a call to .libPaths(.libPaths()) to make use of the updated value.
```

**Comment by kevinushey** [comment]
Interesting; for me, it's not necessary to perform that `.libPaths()` step. I'm testing with a script of the form:

```
#!/usr/bin/env bash

cd "${TMPDIR}"
echo ".Library.site <- tempdir()" > Rprofile.site

R_PROFILE=${PWD}/Rprofile.site
export R_PROFILE

/opt/R/3.6.3/bin/R -s -e 'print(.libPaths())'
/opt/R/4.1.2/bin/R -s -e 'print(.libPaths())'
/opt/R/r81560/bin/R -s -e 'print(.libPaths())'
/opt/R/r81713/bin/R -s -e 'print(.libPaths())'
```

As an aside, the behavior appears to have changed in R-devel; I can't tell if that change is intentional, though.

**Comment by Mosk915** [comment]
That's strange that the behavior is different.  I did something similar to you by going directly from the command line but it confirms what I've already been seeing:

```
$ sudo echo ".Library.site <- tempdir()" > /opt/R/4.0.5/lib/R/etc/Rprofile.site
$ cat /opt/R/4.0.5/lib/R/etc/Rprofile.site
.Library.site <- tempdir()
$ /opt/R/4.0.5/bin/R -s -e 'print(.libPaths())'
[1] "/home/localadmin/R/x86_64-pc-linux-gnu-library/4.0"
[2] "/opt/R/4.0.5/lib/R/library"                        

$ sudo echo ".Library.site <- tempdir(); .libPaths(.libPaths())" > /opt/R/4.0.5/lib/R/etc/Rprofile.site
$ cat /opt/R/4.0.5/lib/R/etc/Rprofile.site
.Library.site <- tempdir(); .libPaths(.libPaths())
$ /opt/R/4.0.5/bin/R -s -e 'print(.libPaths())'
[1] "/home/localadmin/R/x86_64-pc-linux-gnu-library/4.0"
[2] "/opt/R/4.0.5/lib/R/library"                        
[3] "/tmp/RtmpQIlboT" 
```

Regardless of whether the `.libPaths(.libPaths))` line is needed in `Rprofile.site`, it still seems like there's different behavior between first opening an renv-enabled project vs. resuming a suspended session since `.Library.site` is set to `NULL` when the project is first opened and not after resuming from being suspended.

From a quick search of the code, I found this which looks like it's doing the override to `NULL` that I'm seeing.  I'm not sure if it's relevant to this or not.
https://github.com/rstudio/renv/blob/f2f2dafaa49181073d2ff8037a13ff953627cae2/R/sandbox.R#L48:L50

**Comment by kevinushey** [comment]
Thanks, I think I understand what's going on better now.

When the R session is suspended and resumed, the site profile is run, but the project-local profile is not. This implies that `renv` doesn't get a chance to update `.Library.site` after the suspend-resume has been performed.

I think this is ultimately an RStudio bug -- I'm going to file something for that.

**Comment by kevinushey** [comment]
I took a closer look and I think I can fix this on the `renv` side; I have a candidate fix here: https://github.com/rstudio/renv/commit/5808e3fd6225fb76a7ad306da6228ab7f9b5683c

Basically, if `renv` sees that it's part of a resumed RStudio session, and there's an `renv` project already loaded, then it re-activates the sandbox (which should ensure `.Library.site` is unset).

**Comment by Mosk915** [comment]
I confirmed that fixed it.  Thanks for taking care of this.

**Comment by kevinushey** [comment]
Thanks for testing so quickly!
