### ISSUE TITLE
wrong package version loaded from cache if version numbers are equal

### ISSUE THREAD

**Issue by pfuehrlich-pik** [rstudio/renv#938]
reprex (assuming the poorman package is not in the renv cache):
```r
renv::init()
renv::install('nathaneastwood/poorman@4750f4a0567414ee0a6c8edb35d477e8f88b2784')
renv::install('poorman@0.2.5')
```
actual behavior: The first renv::install will install poorman@0.2.5 from GitHub, the second renv::install will load the Version from GitHub from cache.
expected behavior: The second renv::install should instead check the cache for a poorman@0.2.5 installation from CRAN, and if it does not find it, install poorman@0.2.5 from CRAN (just as if the cached GitHub installation was not there, or rebuild = TRUE was passed).

Maybe this is not considered a bug in general, but for our use case it is, so an option for the expected behavior would be great. We have many people developing the same package independently via forks. As a result different versions of the same package have the same version number, but they can be differentiated by installation source (GitHub repos/forks, CRAN, CRAN-like repository, r-universe). Now these people test their changes on a shared HPC with a shared global renv cache. Some people want to install the "official" version of a package, but instead they get a development version from the global renv cache that was installed from a fork.

**Comment by kevinushey** [comment]
Thanks for the bug report + reproducible example! I've confirmed the issue; I think we need to tighten up the logic here.

https://github.com/rstudio/renv/blob/main/R/cache.R#L66-L74

**Comment by pfuehrlich-pik** [comment]
Thanks so much for fixing this so quickly, what a welcome surprise! I noticed two minor things with the new version:
1) There's a confusing knitr/vignette related message that the package build is skipped, but the package is installed just fine:
```
> renv::install('nathaneastwood/poorman@59b725976')
Retrieving 'https://api.github.com/repos/nathaneastwood/poorman/tarball/59b725976ec39074822585b4f9db4768fbfeb501' ...
	OK [downloaded 278.4 Kb in 0.5 secs]
Skipping package build: vignette builder 'knitr' is not installed
Installing poorman [0.2.5] ...
	OK [built from source]
Moving poorman [0.2.5] into the cache ...
	OK [moved to cache in 0.66 milliseconds]
```
2) When I run that exact command again the cached version is correctly found. If I run the same command without the last 2 places of the git commit hash (so just `renv::install('nathaneastwood/poorman@59b7259')`) the cache file is not used, although the git commit hash is expanded to the same long hash in both cases (`Retrieving 'https://api.github.com/repos/nathaneastwood/poorman/tarball/59b725976ec39074822585b4f9db4768fbfeb501'`)

**Comment by kevinushey** [comment]
> There's a confusing knitr/vignette related message that the package build is skipped, but the package is installed just fine:

This is expected; it just implies that the package was installed without building vignettes (because knitr wasn't available). In fact, I'm not sure if we can build vignettes for the package unless we can confirm that knitr and suggested packages are available, but I should confirm.

> When I run that exact command again the cached version is correctly found. If I run the same command without the last 2 places of the git commit hash (so just renv::install('nathaneastwood/poorman@59b7259')) the cache file is not used, although the git commit hash is expanded to the same long hash in both cases (Retrieving 'https://api.github.com/repos/nathaneastwood/poorman/tarball/59b725976ec39074822585b4f9db4768fbfeb501')

Would you mind filing a separate issue for that?
