### ISSUE TITLE
`renv::install()` does not trigger automatic snapshot

### ISSUE THREAD

**Issue by JackCaster** [rstudio/renv#939]
I have set the ENV variable `RENV_CONFIG_AUTO_SNAPSHOT=TRUE` to enable auto snapshot anytime I install a package. I am using `renv::install()` to install packages from the `DESCRIPTION` file. I noticed that if there are packages to install from the `DESCRIPTION` file, `renv` will install those but the snapshot will not be created. After the installation, if I type again `renv::install()`, it will trigger it instead:
```R
> renv::install()
* There are no packages to install.
* Automatic snapshot has updated '/project/renv.lock'.
```
I would expect the snapshot to be created automatically after the installation from the  `DESCRIPTION` file

System:
   R version 4.1.2
   Linux Ubuntu

**Comment by kevinushey** [comment]
Any chance you can share a reproducible example, or a project wherein I could try and reproduce the behavior you're seeing?

**Comment by kevinushey** [comment]
Thanks! I'm seeing something that I think it similar; for example:

```
> renv::install()
* There are no packages to install.
> renv::install()
* There are no packages to install.
* Automatic snapshot has updated '~/scratch/renvie/renv.lock'.
> renv::install()
* There are no packages to install.
> renv::install()
* There are no packages to install.
* Automatic snapshot has updated '~/scratch/renvie/renv.lock'.
```

It's as though the lockfile is updated only on every second call to `install()`. I'll take a closer look.

**Comment by kevinushey** [comment]
I believe this should now be fixed in https://github.com/rstudio/renv/commit/d1de2d40ef6862e4e11ad8adb92f6171f9bc5b64 -- would you be able to download the latest development version of `renv` and test?

**Comment by JackCaster** [comment]
I think it works as expected:
```
> renv::upgrade(version = "d1de2d4")
A new version of the renv package will be installed:

# GitHub =============================
- renv   [ver: 0.14.0-129 -> 0.15.2-12; ref: HEAD -> d1de2d4; sha: cc7963be -> d1de2d40]

This project will use the newly-installed version of renv.
> options(renv.config.auto.snapshot = TRUE)
> renv::install()
* There are no packages to install.
* Automatic snapshot has updated '~/test/renv.lock'.
```

**Comment by kevinushey** [comment]
Great, thanks for taking the time to test and report back!
