### ISSUE TITLE
Can't install packages in a fresh project

### ISSUE THREAD

**Issue by mikkmart** [rstudio/renv#941]
After creating a fresh project, I can't install any packages with `renv`. Here's the steps I've taken:

``` r
usethis::create_project("projects/renv-test")

# In the new project
renv::init()
renv::install("praise")
#> Retrieving 'https://cran.rstudio.org/bin/windows/contrib/4.1/praise_1.0.0.zip' ...
#> 	OK [downloaded 19.4 Kb in 0.4 secs]
#> Installing praise [1.0.0] ...
#> 	FAILED
#> Error installing package 'praise':
#> ==================================
#> 
#> * installing to library 'C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot/R/win-library/4.1'
#> package 'praise' successfully unpacked and MD5 sums checked
#> Error: install of package 'praise' failed ["~/R/projects/renv-test/renv/staging/1/praise" does not exist]
dir.exists("~/R/projects/renv-test/renv/staging")
#> [1] TRUE
```

Maybe `~` is not expanded "correctly"? This has caused me headaches before:

``` r
path.expand("~")
#> [1] "C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot"
```

The "installing to library" location also looks strange -- that's not somewhere I'd want my packages to go. (I normally set `R_LIBS_USER="C:/Users/mikkmart/R/win-library/4.1"`)

**Comment by kevinushey** [comment]
Do you know why the `renv` private library isn't being used in your project? What is the output of `.libPaths()`?

**Comment by Danny-dK** [comment]
Could this be because you are using a network drive (OneDrive). I've had this staging issue on various occasions when working on Windows in a network drive. In the Project Rprofile folder I added:

```
	# Use following only when package installation fails. The symlink one tells renv to not look in 
	# the global renv library install cache located somewhere on the c drive (which may happen when working
	# from a network drive). The transactional indicates whether to install libraries first into a temp 
	# library (staging) before copying it into the actual project library. this again may cause issues if 
	# TRUE when working on network drives.
	
        # options(renv.config.cache.symlinks = FALSE)
	 options(renv.config.install.transactional = FALSE)

 source("renv/activate.R")
```

The transactional option worked. If it still would not work, the symlink option could possibly solve it as well (remove the # in front of that option if the transactional option did not solve it).

**Comment by mikkmart** [comment]
@kevinushey no, I have no idea. `.libPaths()` in the active project seems to indicate the private library should be there:
``` r
.libPaths()
#> [1] "C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot/R/projects/renv-test/renv/library/R-4.1/x86_64-w64-mingw32"
#> [2] "C:/Users/mikkmart/R/R-4.1.2/library" 
```

... Although that said, I thought it would have been created under AppData -- at least that's what happened on my personal Windows PC.

@Danny-dK Thanks for sharing! I tried adding that option, but unfortunately to no effect. I don't think our OneDrive is a network drive, it should be just a local folder that gets synced to the cloud -- so this is probably related to something else.

**Comment by mikkmart** [comment]
Here's the full `renv::diagnostics()` output, in case there's something useful to be found there:

<details>
 <summary> Diagnostics </summary>

``` r
> renv::diagnostics()
Diagnostics Report [renv 0.15.2]
================================

# Session Info =======================
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2    renv_0.15.2   

# Project ============================
Project path: "~/R/projects/renv-test"

# Status =============================
* The project is already synchronized with the lockfile.

# Packages ===========================
           Library Source Lockfile Source Path Dependency
KernSmooth 2.23-20   CRAN     <NA>   <NA>  [2]       <NA>
MASS        7.3-54   CRAN     <NA>   <NA>  [2]       <NA>
Matrix       1.3-4   CRAN     <NA>   <NA>  [2]       <NA>
boot        1.3-28   CRAN     <NA>   <NA>  [2]       <NA>
class       7.3-19   CRAN     <NA>   <NA>  [2]       <NA>
cluster      2.1.2   CRAN     <NA>   <NA>  [2]       <NA>
codetools   0.2-18   CRAN     <NA>   <NA>  [2]       <NA>
foreign     0.8-81   CRAN     <NA>   <NA>  [2]       <NA>
lattice    0.20-45   CRAN     <NA>   <NA>  [2]       <NA>
mgcv        1.8-38   CRAN     <NA>   <NA>  [2]       <NA>
nlme       3.1-153   CRAN     <NA>   <NA>  [2]       <NA>
nnet        7.3-16   CRAN     <NA>   <NA>  [2]       <NA>
renv        0.15.2   CRAN   0.15.2   CRAN  [1]     direct
rpart       4.1-15   CRAN     <NA>   <NA>  [2]       <NA>
spatial     7.3-14   CRAN     <NA>   <NA>  [2]       <NA>
survival    3.2-13   CRAN     <NA>   <NA>  [2]       <NA>
utils         <NA>   <NA>     <NA>   <NA>  [2]   indirect

[1]: C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot/R/projects/renv-test/renv/library/R-4.1/x86_64-w64-mingw32
[2]: C:/Users/mikkmart/R/R-4.1.2/library                                                                                

# ABI ================================
* ABI conflict checks are not yet implemented on Windows.

# User Profile =======================
                                                              Source  Package Require Version   Dev
1 C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot/.Rprofile fortunes                 FALSE

# Settings ===========================
List of 10
 $ bioconductor.version     : chr(0) 
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ r.version                : chr(0) 
 $ snapshot.type            : chr "implicit"
 $ use.cache                : logi TRUE
 $ vcs.ignore.cellar        : logi TRUE
 $ vcs.ignore.library       : logi TRUE
 $ vcs.ignore.local         : logi TRUE

# Options ============================
List of 8
 $ defaultPackages                     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method                : chr "wininet"
 $ download.file.extra                 : NULL
 $ install.packages.compile.from.source: chr "interactive"
 $ pkgType                             : chr "both"
 $ repos                               : Named chr [1:2] "http://orpdev.orion.fi/r-packages/latest" "https://cran.rstudio.org"
  ..- attr(*, "names")= chr [1:2] "orion" "CRAN"
 $ renv.consent                        : logi TRUE
 $ renv.verbose                        : logi TRUE

# Environment Variables ==============
HOME                        = C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot
LANG                        = <NA>
MAKE                        = <NA>
R_LIBS                      = <NA>
R_LIBS_SITE                 = <NA>
R_LIBS_USER                 = C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot/R/projects/renv-test/renv/library/R-4.1/x86_64-w64-mingw32;C:/Users/mikkmart/R/R-4.1.2/library
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = C:\Users\mikkmart\OneDrive - Orion Corporation\Tiedostot\.Renviron
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = <NA>
RENV_DEFAULT_R_LIBS_USER    = C:\Users\mikkmart/R/win-library/4.1
RENV_DEFAULT_R_PROFILE      = //sfisp-sasdatap/biostat/R/setup/config/Rprofile.site
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot/R/projects/renv-test

# PATH ===============================
- C:\Users\mikkmart\R\Rtools-4.0\usr\bin
- C:\Users\mikkmart\R\Rtools-4.0\mingw64\bin
- C:\Users\mikkmart\R\Rtools-4.0\usr\bin
- C:\Users\mikkmart\R\Rtools-4.0\usr\bin
- C:\Users\mikkmart\R\Rtools-4.0\mingw64\bin
- C:\Users\mikkmart\R\Rtools-4.0\usr\bin
- C:\Users\mikkmart\R\R-4.1.2\bin\x64
- C:\Users\mikkmart\R\R-4.1.2\bin\x64
- C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
- C:\Oracle\Ora11g2\bin
- C:\Program Files (x86)\Common Files\Oracle\Java\javapath
- C:\WINDOWS\system32
- C:\WINDOWS
- C:\WINDOWS\System32\Wbem
- C:\WINDOWS\System32\WindowsPowerShell\v1.0\
- C:\WINDOWS\System32\OpenSSH\
- C:\Program Files\Docker\Docker\resources\bin
- C:\ProgramData\DockerDesktop\version-bin
- C:\Users\mikkmart\AppData\Local\Programs\Python\Python39\Scripts\
- C:\Users\mikkmart\AppData\Local\Programs\Python\Python39\
- C:\Users\mikkmart\AppData\Local\Programs\Python\Launcher\
- C:\Users\mikkmart\AppData\Local\Microsoft\WindowsApps
- C:\Users\mikkmart\AppData\Local\Programs\Git\cmd
- C:\Users\mikkmart\AppData\Local\Programs\Microsoft VS Code\bin
- C:\Users\mikkmart\AppData\Local\gitkraken\bin
- C:\Users\mikkmart\R\R-4.1.2\bin
- C:\Users\mikkmart\R\Rtools-4.0\usr\bin
- C:\Users\mikkmart\bin
- C:\Users\mikkmart\opt\node-v14.15.4-win-x64
- C:\Users\mikkmart\opt\highlight-4.1-x64
- C:\Users\mikkmart\opt\sqlite-tools-win32-x86-3360000
- C:\Users\mikkmart\Miniconda3\condabin
- C:\Users\mikkmart\OneDrive - Orion Corporation\scripts
- C:\Users\mikkmart\AppData\Roaming\TinyTeX\bin\win32

# Cache ==============================
There are a total of 0 package(s) installed in the renv cache.
Cache path: "C:/Users/mikkmart/AppData/Local/R/cache/R/renv/cache/v5/R-4.1/x86_64-w64-mingw32"

```

</details>

**Comment by mikkmart** [comment]
Okay so I've narrowed this down a bit: the problem seems to be caused by these lines in my `Rprofile.site`:
``` r
user_libs <- function() {
  libs <- strsplit(Sys.getenv("R_LIBS_USER"), ";")[[1]]
  suppressWarnings(normalizePath(libs))
}

.libPaths(c(user_libs(), .libPaths()))
```

**Comment by mikkmart** [comment]
Thanks @Danny-dK, I appreciate you taking the time to troubleshoot this with me!

You're right, that code is certainly not in a default `Rprofile.site`. It's my own doing from setting this up a few years back. We don't have a packaged R set-up, but I've instructed colleagues to run a set-up script after installation. The script appends to their `.Renviron` the location of this profile file using the `R_PROFILE` variable. The `Rprofile.site` file itself is hosted on a network drive, which is why changing it would affect other users, too.

The purpose of the `Rprofile.site` at the moment is two-fold:

* It appends our internal package repository URL to `getOption("repos")`.
* It sets the default library location to point to `"${USERPROFILE}/R/win-library/%v"` rather than the corresponding under `$HOME`. This is to avoid installing packages in a OneDrive synced location.

The need for the second point indeed caused by `HOME` (managed by IT with most other (non-R) users in mind):

``` r
Sys.getenv("HOME")
#> [1] "C:/Users/mikkmart/OneDrive - Orion Corporation/Tiedostot"
```

However, since I seem to have already baked in the default library configuration into the `.Renviron` template with `R_LIBS_USER`, I'm not sure that `Rprofile.site` needs to worry about that anymore. As I mentioned, removing the setting of `.libPaths()` seems to resolve the issue with renv, and it looks like `R_LIBS_USER` alone handles the library location for non-renv use.

That said, shouldn't activating renv still also override any `.libPaths()` set in `Rprofile.site`? Strangely enough it seems to work on the project level (in the interactive R session `.libPaths()` points to the private library), but not with `renv::install()`.

**Comment by mikkmart** [comment]
And to answer some of your specific questions I managed to side-step earlier: Setting the `library` option in `renv::install()` doesn't help -- I still get the same error. Strangely enough, adding a `.Renviron` in the project directory also doesn't help -- I would have thought it would override my user `.Renviron` and thus solve the problem indirectly.

**Comment by Danny-dK** [comment]
Yeah I did not get that either, apparently the rprofile.site is overruling on everything. Would you be able to write a `.Rprofile` instead of a `Rprofile.site` that contains the same contents? The .Rprofile is normally also located at the $HOME variable which R always checks for its presence at startup. Thus any user running R will run the .Rprofile file present in their $HOME location (whatever that drive actually is) and set the library paths required. I had the same thing where I placed my contents of Rprofile.site in a .Rprofile in my $HOME and R/Rstudio picked up the correct settings. When running renv, this resulted in the correct library present in the renv project for me.

Did you try the renv::install with library specification using the aforementioned option setting in the .Rprofile found in your project root directory? If that does not work. Could you try renv::purge("praise") and try again with library specification and the aforementioned options? 

If all above fails.... then I'm out of options.

**Comment by Danny-dK** [comment]
You don't have to replace the .Rprofile though, you can add lines to .Rprofile. Renv does this as well if you have a project that included a .Rprofile and you later on initialize renv in the already existing project, renv will then only add source(renv/activate.R), it will not delete or overwrite any existing text in that file. That would mean that any other user settings someone has, still remains intact.

**Comment by kevinushey** [comment]
This probably should be addressed in `renv`. We should find a way to ensure the library path requested by `renv` still takes precedence over anything that's happening in `Rprofile.site` when a package is installed.

I was able to reproduce with this script:

```

override <- file.path(tempdir(), "library")
dir.create(override)

# use a custom Rprofile.site
site <- file.path(tempdir(), "Rprofile.site")

fmt <- '
.libPaths(c(%s, .libPaths()))
writeLines("Library paths:")
writeLines(.libPaths())
'

text <- sprintf(fmt, shQuote(normalizePath(override, winslash = "/")))
writeLines(text, con = site)
Sys.setenv(R_PROFILE = site)

# try installing a package
renv::install("praise")
```

Strangely, it seems to only effect renv on Windows, not on other platforms?

**Comment by mikkmart** [comment]
Thank you for the fix! I can confirm that it's worked for me, too.

And thank you @Danny-dK for the helpful discussion!
