### ISSUE TITLE
renv.config.synchronized.check still receiving message at FALSE

### ISSUE THREAD

**Issue by Danny-dK** [rstudio/renv#942]
I have `options(renv.config.synchronized.check = FALSE)` within my .Rprofile at the project root directory but I'm still getting the messages:

```
* Project 'D:/renvtest' loaded. [renv 0.15.0]
* The project library is out of sync with the lockfile.
* Use `renv::restore()` to install packages recorded in the lockfile.
```

I was assuming if it does not check for synched library that you would also not get the messages. What am I doing wrong?

system Windows 10
R version 4.1.2
Rstudio 2021.9.1.372
renv 0.15.0

Full contents of .Rprofile:

```
source("renv/activate.R")

.First <- function() {

	Sys.setlocale("LC_TIME", "English")
	
	if(!dir.exists(paste0(Sys.getenv('HOME'), '/project_libs/project_test'))){
	
		dir.create(paste0(Sys.getenv('HOME'), '/project_libs/project_test'), recursive = TRUE)
	
	}

	# options(renv.config.cache.symlinks = FALSE)
	 options(renv.config.install.transactional = FALSE)
	 options(renv.config.synchronized.check = FALSE)
}

```

.Renviron file contents

```
RENV_PATHS_LIBRARY_ROOT=${HOME}/project_libs
RENV_PATHS_LIBRARY=${HOME}/project_libs/project_test
RENV_PATHS_CACHE=${HOME}/project_libs/global_renv_cache

```

**Comment by kevinushey** [comment]
Does the issue resolve if you set `options(renv.config.synchronized.check = FALSE)` before you call `source("renv/activate.R")`?

**Comment by Danny-dK** [comment]
Oh for *$%^&*'s sake ..... I'm an idiot...Yep that did it. The option specifically needs to be either outside the `.First` function and before the `source()`, or the `source()` should also be in the `.First` and after the options. (placing `source()` after `.First` when `.First` includes the options doesn't work). I thought the `.First` runs first regardless what comes after, but apparently that is not the case. I guess I need to look more into `.First` and its meaning in .Rprofile. Do you have a recommendation, put all options outside `.First` or include `source()` in `.First`? You're welcome to  close the issue.

**Comment by kevinushey** [comment]
Glad to hear it! There are a lot of moving parts in R's startup process (especially when `renv` is involved as well) so it's definitely a valid question. The documentation in `?Startup` may be useful, although it doesn't describe as well how `renv` fits in there.
