### ISSUE TITLE
Update doc to mention r-lib/actions/setup-renv ?

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#944]
Currently, doc about CI does not mention r-lib/actions/setup-renv
https://rstudio.github.io/renv/articles/ci.html#github-actions
and it points also to https://github.com/actions/cache/blob/main/examples.md#r---renv as an example of using cache with renv. 

Maybe https://github.com/r-lib/actions/tree/v2-branch/setup-renv should be mentioned as it is one step to 
* install renv 
* setup the cache 
* restore the package based on the lockfile

this is the recommended way right ?

**Comment by kevinushey** [comment]
Yes, I think so. Would you be willing to file a PR?

**Comment by kevinushey** [comment]
@cderv are you still able to find time to tackle this?

**Comment by cderv** [comment]
Yes I'll do that soon. Are you timed on this ?

**Comment by kevinushey** [comment]
No rush; just wanted to double-check if it was still on your radar. Thanks!
