### ISSUE TITLE
renv::restore(rebuild = T) not correctly rebuilding dependency packages

### ISSUE THREAD

**Issue by kmishra9** [rstudio/renv#947]
Hey there, currently migrating to a new environment/R version. I can confirm my [last issue raised](https://github.com/rstudio/renv/issues/838) has not reared its ugly head 🎉 but it looks like there are times when the most recent version of a dependency package (but installed for a previous R version), exists but is not rebuilt. 

For example, I'm on R 4.1.2 and during an `renv::restore(rebuild = T)` call, there was an error:
```
Installing classInt [0.4-3] ...
	FAILED
Error installing package 'classInt':
====================================

* installing to library ‘/home/airflow_service_account/predictive-analytics/renv/staging/1’
* installing *source* package ‘classInt’ ...
** package ‘classInt’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -fno-optimize-sibling-calls  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-J7pprH/r-base-4.1.2=. -fstack-protector-strong  -c fish1.f -o fish1.o
gcc -std=gnu99 -std=gnu11 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-J7pprH/r-base-4.1.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
gcc -std=gnu99 -std=gnu11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o classInt.so fish1.o init.o -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
installing to /home/airflow_service_account/predictive-analytics/renv/staging/1/00LOCK-classInt/00new/classInt/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error: package ‘KernSmooth’ was installed before R 4.0.0: please re-install it
Execution halted
ERROR: lazy loading failed for package ‘classInt’
* removing ‘/home/airflow_service_account/predictive-analytics/renv/staging/1/classInt’
Error: install of package 'classInt' failed [error code 1]
```

Specifically, `KernSmooth` was not rebuilt properly, causing the installation of `classInt` to fail. A simple `renv::install('KernSmooth')` followed by a `renv::restore()` encounters no issues and allows the `restore` to continue, which seems like something that rebuilding should be able to catch and handle.

Thanks!

**Comment by kmishra9** [comment]
This sorta thing feels challenging to reproduce and I haven't run into any issues like this recently either. Feels like we can close this and I'll follow up in the future w/ more (and an attempt to reproduce) if I bump into it again.

**Comment by hadley** [comment]
Thanks!
