### ISSUE TITLE
delete empty renv/library in tests

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#948]
Re: last CRAN submission:

> This is much better, but did leave empty ~/.cache/R/renv/library behind
> when it had previously created it.  We don't think that is the best
> behaviour, but acceptable for now.

The test suite should delete `renv/library` if it is empty.

**Comment by hadley** [comment]
This should no longer be a problem because we're customising `RENV_PATHS_ROOT` in `renv_tests_setup_envvars()`.
