### ISSUE TITLE
renv only discovers itself or its dependencies

### ISSUE THREAD

**Issue by telegott** [rstudio/renv#949]
I want to manage the dependencies of my R package with `renv`. My `DESCRIPTION` file reads as:
```
Package: debugme
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person(given = "First",
           family = "Last",
           role = c("aut", "cre"),
           email = "first.last@example.com",
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: What the package does (one paragraph).
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Imports:
    purrr
Suggests:
    covr,
    DT,
    htmltools,
    mockery,
    devtools,
    usethis,
    lintr,renv github
    styler,
    testthat
Config/testthat/edition: 3
```

When I do `renv::init(bare=TRUE)` and then `renv::snapshot(type = "explicit")` I only get: 

```
* Project '~/projects/debugme' loaded. [renv 0.15.2]
> renv::snapshot(type="explicit")
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- renv   [* -> 0.15.2]

```
I'm aware I'd need to add `Suggests` to the `settings.dcf`, but I'd at least expect it to find `purrr` as dependency. 
My understanding of the process is this:
- I need an extra package
- I do `usethis::use_package(<pkg>)`
- `<pkg>` is installed by `usethis`
- it's added to `DESCRIPTION` by `usethis`
- I want to snapshot the exact versions of the packages to `renv.lock` to use it e.g. in a Docker container and I try `renv::snapshot(type = "explicit")`

Does `renv`, during snapshot, look at the `DESCRIPTION`, find `purrr`, then checks the local library, find `purrr` is installed, and record that version in `renv.lock`? On the other side if I have `dplyr` in the local library, but not in `DESCRIPTION`, it would not get added to `renv.lock` because it's not in `DESCRIPTION`, no?
I read here that the `renv.lock` is the source of truth, that contradicts the role of the `DESCRIPTION` file though. 
In my understanding, `DESCRIPTION` needs to list packages, possibly lower barriers for versions, and with `renv.lock` I record the exact versions, _but_ only of the ones the `DESCRIPTION` lists, it should be the base-layer of truth.

What approaches are there to separate `Suggests` and `Imports` lockfile wise? For CI, I'd need the `Suggests` packages, but not in e.g. in production.

**Comment by kevinushey** [comment]
Is the `purrr` package installed when you call `renv::snapshot()`?

When creating a lockfile with the "explicit" snapshot type, `renv` looks in your `DESCRIPTION` file for the names of the packages it should use, and your project library for the package versions that should actually be placed into the lockfile.

In other words, if I'm understanding the issue correctly, I believe you need to:

1. Add the packages you want to use to your lockfile,
2. Install those packages (e.g. with `renv::install()`),
3. Call `renv::snapshot()` to create a lockfile.

In general, `renv::snapshot()` treats the project library as the "source of truth"; it just uses your project file(s) to figure out which packages should actually enter the lockfile.

That said, we should probably:

1. Warn, or provide some other feedback, when using `snapshot(type = "explicit")` when a requested package is not installed, or
2. Consider using the latest-available version from the active package repositories when creating the lockfile.

**Comment by telegott** [comment]
@kevinushey no, `purrr` was not installed. I just did `renv::init(bare=TRUE)` in a new folder containing only that `DESCRIPTION`. `renv::install()` and then `renv::snapshot(type="explicit")` did indeed do the trick. I wasn't aware that the local library plays that role.

So in other words, my assumption was correct? e.g. `purrr` in `DESCRIPTION`, local library has `purrr` version xyz and `dplyr`, calling `renv::snapshot(type="explicit")` will realise that although `dplyr` is installed, it should not go into the lockfile because it's not listed in `DESCRIPTION`?

Thanks for the fast answer! Do you have any suggestions for separating lockfiles into `Imports` and `Imports` + `Suggests` for e.g. production and running tests on CI?

**Comment by kevinushey** [comment]
> So in other words, my assumption was correct? e.g. purrr in DESCRIPTION, local library has purrr version xyz and dplyr, calling renv::snapshot(type="explicit") will realise that although dplyr is installed, it should not go into the lockfile because it's not listed in DESCRIPTION?

That's correct. However, I still think it's a bug that `renv` doesn't report if `purrr` is not installed if you've explicitly added it to your DESCRIPTION file.

> Thanks for the fast answer! Do you have any suggestions for separating lockfiles into Imports and Imports + Suggests for e.g. production and running tests on CI?

You might find profiles to be useful: https://rstudio.github.io/renv/articles/profiles.html

**Comment by telegott** [comment]
thanks, I'll look into that! So then it'd be best to have some wrapper scripts that to the snapshot, switch the environment and do the snapshot again, since they seem to be pretty decoupled?

**Comment by kevinushey** [comment]
I wasn't able to reproduce. I suspect something else local on your system affecting things here. I don't see why packages like 'simplermarkdown' would be getting installed here either unless they're being referenced somewhere else in your project.

The output of `renv::dependencies()` might be useful.

**Comment by telegott** [comment]
thanks I will check. I was suspecting the same, that something quite fundamental is wrong and tried to delete all renv related folders, but to no success so far

**Comment by telegott** [comment]
This is the output:
```
                                                           Source   Package
1                    /home/michael/projects/r.example/DESCRIPTION     purrr
2                    /home/michael/projects/r.example/DESCRIPTION      covr
3                    /home/michael/projects/r.example/DESCRIPTION        DT
4                    /home/michael/projects/r.example/DESCRIPTION htmltools
5                    /home/michael/projects/r.example/DESCRIPTION   mockery
6                    /home/michael/projects/r.example/DESCRIPTION  devtools
7                    /home/michael/projects/r.example/DESCRIPTION   usethis
8                    /home/michael/projects/r.example/DESCRIPTION     lintr
9                    /home/michael/projects/r.example/DESCRIPTION    styler
10                   /home/michael/projects/r.example/DESCRIPTION  testthat
11                   /home/michael/projects/r.example/DESCRIPTION      covr
12                   /home/michael/projects/r.example/DESCRIPTION        DT
13                   /home/michael/projects/r.example/DESCRIPTION htmltools
14                   /home/michael/projects/r.example/DESCRIPTION   mockery
15                   /home/michael/projects/r.example/DESCRIPTION  devtools
16                   /home/michael/projects/r.example/DESCRIPTION   usethis
17                   /home/michael/projects/r.example/DESCRIPTION     lintr
18                   /home/michael/projects/r.example/DESCRIPTION    styler
19                   /home/michael/projects/r.example/DESCRIPTION  testthat
20                   /home/michael/projects/r.example/R/process.R     purrr
21                   /home/michael/projects/r.example/R/process.R     stats
22                     /home/michael/projects/r.example/renv.lock      renv
23    /home/michael/projects/r.example/tests/testthat/test-lint.R     lintr
24 /home/michael/projects/r.example/tests/testthat/test-process.R   mockery
25              /home/michael/projects/r.example/tests/testthat.R r.example
26              /home/michael/projects/r.example/tests/testthat.R  testthat
```
Seems ok to me ...

**Comment by telegott** [comment]
It seems this also happens in Docker: 
[scripts/docker-renv](https://github.com/telegott/r.example/pull/10/files#diff-2d4360085d892e2060cb0314b404948ece292a5672d012e4d63f244e351cec50)
Unless I'm doing something wrong. I try to mimick setting it up on a new machine, initialising renv and installing from `DESCRIPTION`. In the docker image, this should create `.Rprofile` which I otherwise don't want in Docker. `renv:snapshot` seems to be confused, in 
```The following unused package(s) are recorded in the lockfile:
               _
```
it lists `purrr`

**Comment by gui-salome** [comment]
I am having a similar problem. I am using the `explicit` setting for snapshotting, and some of the packages listed in `Imports` (in the `DESCRIPTION` file) are not being captured in the snapshot. My current `DESCRIPTION` file literally only lists `data.table`, but `renv::snapshot()` wants to add `renv` to the lock file, but nothing else.

**Comment by gui-salome** [comment]
I created a new project and added a few dependencies in a file, but even those are failing to show up when using the `Implicit` type. What is weird is that `renv::dependencies()` correctly finds the packages, but then `renv::snapshot()` never captures them.

**Comment by kevinushey** [comment]
Are the packages installed? `renv::snapshot()` uses the project's library status to figure out what versions of packages (and their sources) will enter the lockfile.

We should probably at least warn if an explicit dependency is declared, but does not appear to be installed. Or, infer that the user probably wants whatever the latest version on CRAN is.

**Comment by gui-salome** [comment]
Hi @kevinushey, that's a good point that I didn't think about. I was under the impression that if the file was under `Imports`, for example, then it would be captured in the lockfile in some form, but I didn't consider the issue about the versions. Thanks for explaining.

If I install the packages with `renv::install`, and then re-run `renv::snapshot`, then those packages are captured indeed. And so are all other dependencies that were installed with the packages under `Imports`. This is the expected behavior, right?

**Comment by kevinushey** [comment]
Indeed, that's the expected behavior.

**Comment by kevinushey** [comment]
This is now supported in the development version of `renv`:

`````
> renv::settings$snapshot.type("explicit")
> writeLines("Depends: data.table", con = "DESCRIPTION")
> renv::snapshot()
The following packages are required by this project, but are not installed:

        data.table

Packages must first be installed before `renv` can snapshot them.
Consider installing these packages using `renv::install()`.
Alternatively, remove these packages from the project DESCRIPTION file.
`````
