### ISSUE TITLE
renv::restore does not have any effect in Docker

### ISSUE THREAD

**Issue by telegott** [rstudio/renv#950]
I have an `renv.lock` file containing few packages (`purrr` among them), a `Dockerfile`:

```
FROM rocker/r-ver:4.1.2 AS base
RUN set -xe \
    && apt-get update \
    && apt-get install -y \
        make \
        git-core \
        libssl-dev \
        libcurl4-openssl-dev \
        libgit2-dev \
        libicu-dev \
        libxml2-dev \
    && rm -rf /var/lib/apt/lists/* \
    && R -e 'install.packages("renv")'

WORKDIR app
COPY renv.lock renv.lock
RUN set -xe \
	R -e 'renv::restore()'
```
a build script 
```
TAG=test
docker build --tag $TAG --target=base -f Dockerfile .
docker run \
    --rm \
    $TAG \
    R -e "library(purrr)"
```
but after running this script I get 
```
> library(purrr)
Error in library(purrr) : there is no package called ‘purrr’
```
from the container. It seems like `R -e 'renv::restore()'` doesn't really do anything and silently exits. I do not want a local library in docker since it already is isolated, following the articles about `renv` suggest just copying the `renv.lock` and doing `renv::restore()` should suffice. What could go wrong that I don't get any feedback during this apparently failing docker command? Are there any flags I need to set for R to exit with code 1 on failure?

**Comment by telegott** [comment]
missing `&&` on the `restore` line. However, it seems that `renv::install` uses binaries whereas `renv::restore` does not. Does it have to do with environment variables set in the image `rocker/r-ver` ?

**Comment by kevinushey** [comment]
Binary packages normally aren't available on Linux, unless you're using RSPM (in which case you might only see binaries available for the latest-available versions of packages).
