### ISSUE TITLE
How to get consistent behaviour between rocker/r-ver and Github Actions

### ISSUE THREAD

**Issue by telegott** [rstudio/renv#951]
I have an R project set up as a package, and I want to use Github Actions as CI and also be able to reproducibly build a Docker container. 
As a base image I'm using `rocker/r-ver:4.1.2`. In both situations I'm calling `renv::restore`. The Docker container builds and runs the tests without problems (`renv/library` is in the `.dockerignore`, takes longer, but is more reproducible). 

Using the default settings for the action, I get an [error](https://github.com/telegott/r.example/runs/5344033276?check_suite_focus=true) like
```
Retrieving 'https://cloud.r-project.org/src/contrib/Archive/DT/DT_0.20.tar.gz' ...
Warning: Warning: failed to find source for 'jsonlite 1.7.3' in package repositories
Warning: Warning: failed to find source for 'glue 1.6.1' in package repositories
Warning: Warning: failed to find source for 'yaml 2.3.4' in package repositories
Warning: Warning: failed to find source for 'clipr 0.7.1' in package repositories
Warning: Warning: failed to retrieve 'https://cloud.r-project.org/src/contrib/Archive/DT/DT_0.20.tar.gz' [error code 22]
```
It seems that under the hood, both might have different R repositories to pull the libraries from. I tried setting both to MRAN via `RENV_CONFIG_REPOS_OVERRIDE`, but that wasn't successful either.

I am step by step consolidating my learning here, so some things in the readme might be out of date by now:

https://github.com/telegott/r.example/pull/10

How do you go about fixing these sources? While it would be nice to install binaries, I care much more about time-independent builds. And it seems that without extra work, builds tend to break at random points because something in the repositories change.

**Comment by kevinushey** [comment]
This seems like an intermittent internet connectivity issue, since that package can be successfully downloaded now:

```
> renv:::download("https://cloud.r-project.org/src/contrib/Archive/DT/DT_0.20.tar.gz", tempfile())
Retrieving 'https://cloud.r-project.org/src/contrib/Archive/DT/DT_0.20.tar.gz' ...
        OK [downloaded 1.4 Mb in 0.2 secs]
[1] "/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//Rtmp78Ez53/filee393632c7a6e"
```
