### ISSUE TITLE
cannot install highcharter: wrong arguments for subsetting an environment

### ISSUE THREAD

**Issue by pfuehrlich-pik** [rstudio/renv#955]
Trying to install `highcharter` in a fresh `renv` (0.15.4) fails:
```
* Project '/p/tmp/pascalfu/playground/asdf' loaded. [renv 0.15.4]
> renv::install('highcharter')
Retrieving 'https://cran.rstudio.com/src/contrib/highcharter_0.9.4.tar.gz' ...
	OK [downloaded 1 Mb in 0.1 secs]
Error in state$requirements[[record$Package]] : 
  wrong arguments for subsetting an environment
Traceback (most recent calls last):
12: renv::install("highcharter")
11: retrieve(names(remotes))
10: handler(package, renv_retrieve_impl(package))
 9: renv_retrieve_impl(package)
 8: renv_retrieve_repos(record)
 7: renv_retrieve_repos_impl(record)
 6: renv_retrieve_package(record, url, path)
 5: renv_retrieve_successful(record, path)
 4: retrieve(package)
 3: handler(package, renv_retrieve_impl(package))
 2: renv_retrieve_impl(package)
 1: renv_retrieve_incompatible(record)
 ```
On the same system `highcharter@0.9.4` can be installed outside of an `renv` without any problem.
```
$ hostnamectl 
  Operating System: SUSE Linux Enterprise Server 12 SP3
      Architecture: x86-64
```

On another system (Ubuntu 21.10) `renv` can install `highcharter` without any problems, so seems to be a system related issue :unamused: .
Any ideas what I could try or where that might be coming from?

**Comment by kevinushey** [comment]
Thanks for the bug report -- unfortunately, I wasn't able to reproduce either. I tried initializing `renv` in a brand new directory, and then calling `renv::install("highcharter")` after.

Could you try running the following on that system?

```
trace(renv:::renv_retrieve_incompatible, quote((str(record))))
renv::install("highcharter")
```

The issue here might depend on what packages are installed in the project library when `renv::install()` is called.

**Comment by pfuehrlich-pik** [comment]
Thanks for the reply! Unfortunately, the output of your command (see attached file) is not helpful I think. I'm always using a completely fresh `renv`, so there is nothing installed before I run `renv::install("highcharter")`. I'm using `R version 3.6.3 (2020-02-29)`.
[renv_highcharter_bug.log](https://github.com/rstudio/renv/files/8184771/renv_highcharter_bug.log)

**Comment by kevinushey** [comment]
It's a little helpful -- it's telling us that we have a `NULL` record here for some reason. The hard part is figuring out where and why that is happening.

**Comment by pfuehrlich-pik** [comment]
Hi, I managed to find the problem on our system: rjson 0.2.21 could not be installed, because it requires R >= 4.0.0. I simply installed rjson 0.2.20 first and the problem was solved. Here's the log of my debugging session, in case you want to improve the error message to include the problematic package:
```r
> renv::install('highcharter')
Retrieving 'https://cran.rstudio.com/src/contrib/highcharter_0.9.4.tar.gz' ...
	OK [file is up to date]
Error in state$requirements[[record$Package]] : 
  wrong arguments for subsetting an environment

Enter a frame number, or 0 to exit   

 1: renv::install("highcharter")
 2: retrieve(names(remotes))
 3: handler(package, renv_retrieve_impl(package))
 4: renv_retrieve_impl(package)
 5: renv_retrieve_repos(record)
 6: renv_retrieve_repos_impl(record)
 7: renv_retrieve_package(record, url, path)
 8: renv_retrieve_successful(record, path)
 9: retrieve(package)
10: handler(package, renv_retrieve_impl(package))
11: renv_retrieve_impl(package)
12: renv_retrieve_incompatible(record)

Selection: 11
Called from: top level 
Browse[1]> ls()
[1] "ostype"    "package"   "record"    "records"   "skip"      "source"   
[7] "state"     "uselatest"
Browse[1]> ostype
[1] ""
Browse[1]> package
[1] "rjson"
Browse[1]> record
NULL
```
Feel free to close this issue :slightly_smiling_face:

**Comment by alexfhnw** [comment]
I've got the same issue with the `recommenderlab` package on Pop!_OS 20,04. 
Any advice on how to fix the issue?

```
renv::install('recommenderlab')
Retrieving 'https://cloud.r-project.org/src/contrib/recommenderlab_0.2-7.tar.gz' ...
        OK [file is up to date]
Error in state$requirements[[record$Package]] : 
  wrong arguments for subsetting an environment
Traceback (most recent calls last):
12: renv::install("recommenderlab")
11: retrieve(names(remotes))
10: handler(package, renv_retrieve_impl(package))
 9: renv_retrieve_impl(package)
 8: renv_retrieve_repos(record)
 7: renv_retrieve_repos_impl(record)
 6: renv_retrieve_package(record, url, path)
 5: renv_retrieve_successful(record, path)
 4: retrieve(package)
 3: handler(package, renv_retrieve_impl(package))
 2: renv_retrieve_impl(package)
 1: renv_retrieve_incompatible(record)
```

**Comment by kevinushey** [comment]
I believe you should see a more helpful error message with the development version of `renv`, if you want to give that a try. Use:

```
renv::upgrade(version = "main")
```

to upgrade `renv`, and then restart and try once more.

**Comment by alexfhnw** [comment]
> I've got the same issue with the `recommenderlab` package on Pop!_OS 20,04. Any advice on how to fix the issue?
> 
> ```
> renv::install('recommenderlab')
> Retrieving 'https://cloud.r-project.org/src/contrib/recommenderlab_0.2-7.tar.gz' ...
>         OK [file is up to date]
> Error in state$requirements[[record$Package]] : 
>   wrong arguments for subsetting an environment
> Traceback (most recent calls last):
> 12: renv::install("recommenderlab")
> 11: retrieve(names(remotes))
> 10: handler(package, renv_retrieve_impl(package))
>  9: renv_retrieve_impl(package)
>  8: renv_retrieve_repos(record)
>  7: renv_retrieve_repos_impl(record)
>  6: renv_retrieve_package(record, url, path)
>  5: renv_retrieve_successful(record, path)
>  4: retrieve(package)
>  3: handler(package, renv_retrieve_impl(package))
>  2: renv_retrieve_impl(package)
>  1: renv_retrieve_incompatible(record)
> ```

nvm. Just found out that I was running an old version of R. Upgraded to 4.1 and now it works
