### ISSUE TITLE
Enable renv::update to update based on RSPM

### ISSUE THREAD

**Issue by afshinmhCLG** [rstudio/renv#960]
As reported [here](https://community.rstudio.com/t/whats-the-best-way-to-update-renv-lock-based-on-internal-rstudio-package-manager/112679), 

**Here is the use-case**: update package versions in renv.lock using rstudio package-manager as the source.

**Issue**: There is not a convenient way from renv to do that. `renv::update` function only looks at CRAN and GitHub at this point and does not provide ways of explicitly providing a url to internal package repository.

**feature request**  a function like `renv::update_package(pakcage = "pkg", url = "http://rspm-myorg.com", version = "0.0.1")`. 
While this does not universally update all package, it does go a long way in helping renv better work with RSPM. Additionally, it provide fine control over versions.

**Comment by kevinushey** [comment]
> are there some contribution guidelines for renv?

I haven't put one together yet, but the main guidelines are:

- Internal functions should have a prefix of the form `renv_<scope>_<name>`, where `<scope>` _usually_ matches the name of the file where that function is implemented;
- Try to follow the existing code style if you're editing an existing source file.

I've also intentionally tried to keep `renv`'s public API relatively slim (and even with that it's already grown a bit large!) so we might want to discuss what the best "name" for such a function should be (or if the functionality could be rolled into `snapshot()` or something else)

**Comment by kevinushey** [comment]
You might also want to take a look at `renv:::checkout()`; it's an internal function that tried to accomplish a similar goal that I never quite finished up. (Basically, it could be used to create or update a lockfile based on an external repository)

**Comment by hadley** [comment]
Doesn't this already just work assuming that you have RSPM set up correctly in `repos`?

**Comment by hadley** [comment]
The problem of switching repositories (e.g. from CRAN to RSPM) is now tracked in #413.
