### ISSUE TITLE
renv_python_discover should return python earliest in PATH, not latests

### ISSUE THREAD

**Issue by timbalam** [rstudio/renv#961]
Hi devs,

The issue I have encountered occurs when first starting an renv project that uses a python virtualenv, in a system with two installations of the same version of python available in PATH. When running for the first time running, renv attempts to create a virtualenv, but finds an unexpected python executable. I expect that the python executable in a folder found earliest on PATH (left-most) would be used, however the python executable found latest on PATH is found.

I believe the cause of this behaviour is in the code for discovering paths for installed python binaries renv_python_discover. In the function, the folders on PATH are traversed (from latest to earliest/rightmost to leftmost) and any found binaries are pushed to a 'stack'. Finally, the $data() method is called on the stack to get the list of pushed binaries. This method returns a list of pushed elements in the order they were pushed, meaning that the python executables that occur in folders earlier on PATH are at the front of the list. The function then returns the first executable with the appropriate version from the list.
 
 To fix this behaviour, some possible options are:
 - don't reverse the order of the folders on PATH in the loop where the found executables are pushed
 - change the behaviour of the $data() method of the stack to reverse the internal list so that elements pushed last are at the front of the list
 - reverse the output of the $data() method
 
 Sorry for not providing a reproducible example! 
 
 Thanks, 
 Tim

**Comment by kevinushey** [comment]
Thanks for the bug report + in-depth investigation! I agree with this solution:

> don't reverse the order of the folders on PATH in the loop where the found executables are pushed

I'll push a change to that effect. Thanks!

**Comment by kevinushey** [comment]
Should now be fixed via https://github.com/rstudio/renv/commit/2538da36d9dfa88fc6e1cf88005a31067cb5bd82.
