### ISSUE TITLE
Display changes to R version during snapshot confirmation

### ISSUE THREAD

**Issue by ck37** [rstudio/renv#962]
Hello,

When calling snapshot() all package version changes are listed, but changes to the R version are not shown. It would be helpful to see show the R version change in addition to the package version changes.

This is an example of what it could look like:

```
> renv::snapshot()
The following package(s) will be updated in the lockfile:

# R interpreter ======================
- R            [4.0.5 -> 4.1.1]

# CRAN ===============================
- rlang        [1.0.1 -> 1.0.2]
- tidyselect   [1.1.1 -> 1.1.2]

Do you want to proceed? [y/N]:
```

Or it could be a separate section before "the following packages" since R itself is not technically a package, it's really a system requirement.

Thanks,
Chris

**Comment by hadley** [comment]
I see it if there are other packages to update:

```
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- cli     [3.6.1 -> *]
- rlang   [* -> 1.1.1]

The version of R recorded in the lockfile will be updated:
- R       [4.1.3 -> 4.2.3]
```

but not if there aren't. So probably a small logic error.
