### ISSUE TITLE
renv has trouble parsing multiline yaml chunk options

### ISSUE THREAD

**Issue by zkamvar** [rstudio/renv#963]
I was trying out {renv} with an RMarkdown document that uses yaml syntax for multiline figure captions. While it works for {knitr}, {renv} throws an error. If you parse down in the error, it's related to renv not being able to parse the yaml syntax. On the surface, this looks similar to #772, but I think the root cause is related to how the chunks in knitr are partitioned. I'm wondering if the upcoming export of `partition_chunk()` from knitr will help with this: https://github.com/yihui/knitr/pull/2083

Here's an example (text from https://stackoverflow.com/a/70665396/2752888):

```` r
  txt <- r"{But, the new syntax also allows you to use yaml syntax to specify the chunk options, and yaml allows for multiline strings. So you could do the following:

```{r}
#| echo: false
#| warning: false
#| fig.cap: >
#|   Here is my really long caption.  It'd be nice to
#|   split this and other portions across lines

print(plot(x=runif(100),y=runif(100)))
```
}"
  tmp <- tempfile(fileext = ".Rmd")
  writeLines(txt, tmp)
````

This works in knitr

``` r
  writeLines(knitr::knit(text = txt))
#> But, the new syntax also allows you to use yaml syntax to specify the chunk options, and yaml allows for multiline strings. So you could do the following:
#> 
#> ![Here is my really long caption.  It'd be nice to split this and other portions across lines](https://i.imgur.com/3ofKiSk.png)
#> 
#> ```
#> #> NULL
#> ```
```

This does NOT work with `renv::dependencies()`

``` r
  renv::dependencies(dirname(tmp))
#> Finding R package dependencies ... Done!
#> Error in split.default(x = seq_len(nrow(x)), f = f, drop = drop, ...): group length is 0 but data length > 0
```

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kevinushey** [comment]
Thanks for the bug report! This should now be fixed in the development version of `renv`.
