### ISSUE TITLE
Error: all repository entries must be named

### ISSUE THREAD

**Issue by wlandau** [rstudio/renv#964]
My organization has its own internal CRAN-like repository, and it sets the default `"repos"` option for all of us.

```r
> getOption("repos")
  CRAN 
"CENSORED/CENSORED-cran" 
                                                                            
"CENSORED/bioconductor/bioc" 
                                                                            
"CENSORED/data/annotation" 
                                                                            
"CENSORED/data/experiment" 
                                                                            
"CENSORED/workflows"
```

Not all the repos have names.

```r
> names(getOption("repos"))
[1] "CRAN" ""     ""     ""     ""    
```

When I run `renv::init()` on an empty (or small) project, I get an error (with both CRAN `renv` and 7243b4810f58d4fc11025a1eedf8e9ca8e21fe94):

```r
> renv::init()
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
Error: all repository entries must be named
Traceback (most recent calls last):
5: renv::init()
4: snapshot(project = project, library = libpaths, repos = repos, 
       prompt = FALSE)
3: renv_repos_validate(repos)
2: stopf("all repository entries must be named")
1: stop(sprintf(fmt, ...), call. = call.)
```

This error resolves itself when I manually give names to all entries of `getOption("repos")`.

As a workaround, I will ask my devops team to name all the repos. But would it be possible for `renv` to supply its own default names if none already exist? As a user, I almost never think about repos and would prefer them to be handled automatically.

**Comment by kevinushey** [comment]
Thanks for the feature request! This seems reasonable to me.

**Comment by wlandau** [comment]
Thanks for accommodating!
