### ISSUE TITLE
Remove packages not in lock file

### ISSUE THREAD

**Issue by cboettig** [rstudio/renv#968]
Though `renv::restore()` is described as "to restore the state of your project from `renv.lock`", it will happily leave additional packages that have been installed but not yet added to lockfile (e.g. via `renv::snapshot()`) in the local package cache.  

Maybe this is merely a quirk of my own workflows or I'm doing something wrong, but I find this results in projects growing ever larger `renv.lock` files over time, as I switch to a different package to perform a similar function, or as I install a package for some one-off interactive testing while in an active renv project but don't actually use it.  (This balloons even faster with collaborators who may also install packages for one-off use and have no way to restore their local cache to the pristine required-packages-only described in the renv lock file.  Then eventually when they need to add a new or updated package to the lock-file they run `renv::snapshot()` and the lockfile rapidly expands to the kitchen sink).  

Is there a function that could simply remove the packages that have been installed but not added via `renv::snapshot()` (other than `renv::deactivate()`, or manually destroying the local package cache, which do not feel like the ergonomic ways to do this).  If not, would you consider adding one?  (And again apologies if I'm just missing something entirely obvious!)

**Comment by kevinushey** [comment]
Does `renv::restore(clean = TRUE)` do what you need?

>   clean: Boolean; remove packages not recorded in the lockfile from
>           the target library? Use 'clean = TRUE' if you'd like the
>           library state to exactly reflect the lockfile contents after
>           'restore()'.

In addition, what kind of snapshots are you taking (see: https://rstudio.github.io/renv/reference/snapshot.html#snapshot-type). The fact that packages are entering your lockfile would imply that they're being used, or are still referenced, within your project, and so `renv` sees those packages as necessary.

If you wanted to take more explicit control over which packages enter the lockfile, you might want to use an explicit snapshot instead.

**Comment by cboettig** [comment]
thanks, this looks just like what I was looking for!

**Comment by cboettig** [comment]
I didn't know about `explicit` and `renv::settings$snapshot.type("explicit")`, that's great!
