### ISSUE TITLE
packages uploading issues,

### ISSUE THREAD

**Issue by Zango89** [rstudio/renv#970]
I recently updated my R, Regrettably i am having issue with almost all packages. i cannot upload most of the packages 

Error: package or namespace load failed for 'dplyr' in library.dynam(lib, package, package.lib):
 No this DLL 'vctrs': is it not installed for this architecture?
Load the required program package: usethis
Error: package or namespace load failed for 'usethis' in library.dynam(lib, package, package.lib):
 No this DLL 'glue': is it not installed for this architecture?
Error: Unable to load package 'usethis'
Error: package or namespace load failed for 'ggplot2' in library.dynam(lib, package, package.lib):
 No this DLL 'glue': is it not installed for this architecture?

**Comment by kevinushey** [comment]
You could try using `renv::rebuild()` to force reinstallation of your R packages. Does that help?
