### ISSUE TITLE
Add vignette re: customizing of autoloader 

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#972]

**Comment by hadley** [comment]
Is there anything you can brain dump that I could turn into a vignette? (Or maybe just a section in `renv::activate()`?)

**Comment by kevinushey** [comment]
Now I can't recall what I wanted to change 😞

I guess probably the minimum would be pointing at the use of `RENV_CONFIG_AUTOLOADER_ENABLED=FALSE` for users who want to temporarily disable the `renv` autoloader for some reason (without needing to update the project `.Rprofile`).

**Comment by hadley** [comment]
Maybe I can just mention that in `?activate` ?
