### ISSUE TITLE
Feature request: Pin dependencies

### ISSUE THREAD

**Issue by pdeffebach** [rstudio/renv#973]
I have a few dependencies in an `renv` environment which are hard to install on the cluster but easy to install locally, such as `rgdal` and `sf`. 

Whenever we add a new package locally, `renv` is very aggressive at ensuring all dependencies are at their latest possible versions. This often results in "trivial" version bumps for our hard-to-download packages. For instance, right now we have `rgdal@1.5-28` installed on the cluster but our `renv.lock` lists `rgdal@1.5-29`. We get warnings that we should run `renv::restore()`, but this requires manually downloading `rgdal@1.5-29` which sometimes fails due to configurations. 

It would be nice to pin the difficult-to-download versions in the `renv.lock` file so they are never update, and a lower version of a new package is installed if needed.

**Comment by kevinushey** [comment]
> Whenever we add a new package locally

Can you confirm how you are adding (installing) packages?

You should be able to use something like:

```
options(renv.records = list(rgdal = list(Package = "rgdal", Version = "1.5-28", Source = "Repository")))
renv::restore()
```

to override the record used in the lockfile with an older version of `rgdal`.

**Comment by kevinushey** [comment]
(Internal note: should be consider renaming this to `renv.records.override`, and documenting it?)

**Comment by hadley** [comment]
@pdeffebach are you still interested in following up on this issue?

**Comment by hadley** [comment]
Since it's been a couple of weeks and we haven't anything more, I'm going to close this issue.
