### ISSUE TITLE
use_python removing lock.file requirements

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#974]
Hello, new to `renv` but loving it already. Trying to use it with python as well but coming across something and I don't understand why it is happening.

1. Create brand new R project
2. `renv::init()` > commit everything
3. Installing `reticulate` and then `renv::snapshot()` on the new dependency
![image](https://user-images.githubusercontent.com/53956863/161628947-56b9bf11-21bd-45e1-adf3-849fd0c172b7.png)
4. run `renv::use_python(name = "...path to a venv")`
![image](https://user-images.githubusercontent.com/53956863/161629435-b4a18c2b-550a-438b-8cf7-f14d6f229ee1.png)

The question is: why is that step removing those dependencies from the lock.file?

**Comment by kevinushey** [comment]
That's a good question. That seems like a bug to me; I'll need to investigate and see if I can reproduce.

**Comment by hutch3232** [comment]
Thanks for the super rapid response! Let me know if I can help test on my end.

**Comment by hutch3232** [comment]
@kevinushey - I looked into this a little, stepping through `renv::use_python(name = "...path to a venv")` using `debug`.

I think I have found the cause:

https://github.com/rstudio/renv/blob/4e00953f254d40cceeb4cfaebcb13ee139cd0340/R/lockfile-write.R#L55-L72

As soon as I run the above, any package with `"Requirements"` has that attribute erased. 

I don't completely understand what this function is doing, but I found that if I threw "Requirements" into the `keys` vector, it preserves them. There might be a more appropriate solution, but thought I should test some options.

**Comment by kevinushey** [comment]
Thanks! There's probably a code path calling `renv::snapshot()` that's somehow collecting package records without the Depends / Imports / LinkingTo packages included, and so the Requirements field is not being computed correctly. Sorry; I still haven't had a chance to dive in further but it's on my radar.

**Comment by kevinushey** [comment]
Thanks! Should now be fixed up in the development version of `renv`.

**Comment by hutch3232** [comment]
Thank you!!
