### ISSUE TITLE
Error in RENV_PATHS_LIBRARY_ROOT_ASIS=TRUE 

### ISSUE THREAD

**Issue by gacolitti** [rstudio/renv#976]
Based on [this vignette](https://cran.r-project.org/web/packages/renv/vignettes/packages.html) I can set the environmental variable `RENV_PATHS_LIBRARY_ROOT_ASIS=TRUE` to remove the id suffix from project-name-id renv library folder. 

However, I get this error:

```r
Error in if (asis) return(basename(project)) : 
  argument is not interpretable as logical
```

**Comment by kevinushey** [comment]
Thanks! Should now be fixed in the development version.
