### ISSUE TITLE
data.table repository: "could not retrieve available packages for url" at renv startup

### ISSUE THREAD

**Issue by adamaltmejd** [rstudio/renv#979]
Using the repository at `https://Rdatatable.gitlab.io/data.table` for data.table on mac-arm64 makes the following warning message show up at every startup of R in an renv project. Probably because data.table does not supply mac binaries. Is there any way to get rid of it?

```
Warning message:
could not retrieve available packages for url 'https://Rdatatable.gitlab.io/data.table/bin/macosx/big-sur-arm64/contrib/4.1' 
```

**Comment by kevinushey** [comment]
FWIW, you'll see the same warning with base R:

```
> options(repos = c(DT = "https://Rdatatable.gitlab.io/data.table"))
> ap <- as.data.frame(available.packages(type = "binary", ignore_repo_cache = TRUE))
Warning: unable to access index for repository https://Rdatatable.gitlab.io/data.table/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'https://Rdatatable.gitlab.io/data.table/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'
```

Usually, package repositories should create an empty `PACKAGES` file for each relevant binary repository, or users should explicitly set `options(pkgType = "source")` or similar to request only the source arms of a package repository.

**Comment by adamaltmejd** [comment]
I see. But I guess its not possible to set pkgType = "source" only for one repository either. This is not a big deal, but will check over at data.table if they cannot create that file.
