### ISSUE TITLE
renv::snapshot(type="implicit") does not record dependencies listed in renv::dependencies()

### ISSUE THREAD

**Issue by nathaniel-mahieu** [rstudio/renv#986]
I am having the problem that renv::snapshot(type="implicit") does not add all the packages found by renv::dependencies().

Love the package but this makes it impossible to keep my lock file updated.  Could this be due to wsl2 path escaping?

```
> renv::dependencies()
Finding R package dependencies ... Done!
                                                                                                                 Source    Package Require Version   Dev
1 \\\\wsl$/Ubuntu/home/nmahieu/ms-data-pipeline-flow-development/sposemR/ingest-metadata/merge-metadata-with-sequence.R data.table                 FALSE
2 \\\\wsl$/Ubuntu/home/nmahieu/ms-data-pipeline-flow-development/sposemR/ingest-metadata/merge-metadata-with-sequence.R     hablar                 FALSE
3 \\\\wsl$/Ubuntu/home/nmahieu/ms-data-pipeline-flow-development/sposemR/ingest-metadata/merge-metadata-with-sequence.R         R6                 FALSE
4 \\\\wsl$/Ubuntu/home/nmahieu/ms-data-pipeline-flow-development/sposemR/ingest-metadata/merge-metadata-with-sequence.R    stringr                 FALSE
5 \\\\wsl$/Ubuntu/home/nmahieu/ms-data-pipeline-flow-development/sposemR/ingest-metadata/merge-metadata-with-sequence.R      tools                 FALSE
6                      \\\\wsl$/Ubuntu/home/nmahieu/ms-data-pipeline-flow-development/sposemR/ingest-metadata/renv.lock       renv                 FALSE
```

Note that these are called as `library(data.table)`.

```
> renv::snapshot()
* Lockfile written to '//wsl$/Ubuntu/home/nmahieu/ms-data-pipeline-flow-development/sposemR/ingest-metadata/renv.lock'.
```

renv.lock
```
{
  "R": {
    "Version": "4.1.0",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.15.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "206c4ef8b7ad6fb1060d69aa7b9dfe69",
      "Requirements": []
    }
  }
}
```

**Comment by nathaniel-mahieu** [comment]
Similar to #435

**Comment by kevinushey** [comment]
Are those package actually installed in the renv library?

Can you please provide a reproducible example?

**Comment by nathaniel-mahieu** [comment]
Ah I have misunderstood.  The correct order is renv::hydrate(), renv::snapshot(), renv::activate()?

**Comment by kevinushey** [comment]
Why not just call renv::init()?

**Comment by nathaniel-mahieu** [comment]
That seems to work as well! Thank you.

**Comment by nathaniel-mahieu** [comment]
Maybe consider adding here, during the discussion of snapshot: https://rstudio.github.io/renv/articles/faq.html#capturing-all-dependencies that though `renv::settings$snapshot.type("all")` impacts dependency discovery, `renv::snapshot()` does not discover dependencies and point the user towards the optimal call `renv::init()`?

**Comment by kevinushey** [comment]
Maybe I'm missing something, but doesn't https://rstudio.github.io/renv/#workflow describe the intended workflow? I'm confused why you're trying to call snapshot before actually installing the packages you want to use.

**Comment by kevinushey** [comment]
In addition, from https://rstudio.github.io/renv/reference/snapshot.html, the documentation for implicit:

Only capture packages which appear to be used in your project in the lockfile. **The intersection of packages installed in your R libraries, alongside those used in your R code as inferred by [renv::dependencies()](https://rstudio.github.io/renv/reference/dependencies.html), will enter the lockfile.** This helps ensure that only the packages your project requires will enter the lockfile, but may be slower if your project contains a large number of files. If this becomes an issue, you might consider using .renvignore files to limit which files renv uses for dependency discovery, or explicitly declaring your required dependencies in a DESCRIPTION file. You can also force a dependency on a particular package by writing e.g. library(<package>) into a file called dependencies.R.

**Comment by nathaniel-mahieu** [comment]
I was calling snapshot because https://rstudio.github.io/renv/articles/faq.html#why-isnt-my-package-being-snapshotted-into-the-lockfile indicates snapshot on cursory read.  As a novice this was confusing.

My intent was to discover dependencies, write them to renv.lock, then install them.  The general pattern has been to copy code which includes several dependencies into the project, avoid calling renv::install for each, but rather discover and append them to the renv.lock.

init() does the trick though it would be nice if there was a solution that didn't restart the r session, just appended new dependencies.

I do think the above suggestion regarding the faq would guide people to desired info.
