### ISSUE TITLE
renv::update package to specific version

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#987]
I attempted to update an existing package to a newer version that I knew existed using the special `@` syntax and got an unintuitive error message:

```r
renv::update(packages = "data.table@1.14.0")
The following package(s) are not currently installed:

	data.table@1.14.0

The latest available versions of these packages will be installed instead.

Do you want to proceed? [y/N]: y
* Checking for updated packages ... Error in vapply(x, `[[`, ..., FUN.VALUE = character(1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0
Traceback (most recent calls last):
4: renv::update(packages = "data.table@1.14.0")
3: renv_update_find(selected)
2: extract_chr(records, "Source")
1: vapply(x, `[[`, ..., FUN.VALUE = character(1))
```

After reviewing the documentation, I realize I should have used `renv::install(packages = "data.table@1.14.0")` or `renv::update(packages = "data.table")`. Maybe this syntax could be supported? Or perhaps the `@` could be caught and a helpful error message provided?

Thanks!

**Comment by hadley** [comment]
When you run this with the latest version you see:

```
The following package(s) are not currently installed:

	data.table@1.14.0

The latest available versions of these packages will be installed instead.

Do you want to proceed? [Y/n]: 
```

Which while not perfect, is much better than a weird error 😄
