### ISSUE TITLE
feature request: default permissions setting

### ISSUE THREAD

**Issue by hutch3232** [rstudio/renv#988]
I am working in a unix-like environment with many users with varying default permissions that are used when they create files. I am trying to setup `renv` so that all users could share the same cache. For the most part this works very well, however, if someone installs a new package with read-only permissions, new versions can't be added without the original user going in and opening the permissions back up.

Would it be possible to add a `mode` argument to `install` and `update`? Or perhaps some new [configuration setting](https://rstudio.github.io/renv/reference/config.html)? I did see this `renv.config.copy.method` and wondered if somehow a `Sys.chmod` could be added to keep the permissions open but I didn't really understand how to use this setting exactly or where it applies.

Thanks for any advice!

edit:
I tried adding this to my .Rprofile and it did not seem to work:
```r
options(renv.config.copy.method = function(src, dst) {
  Sys.chmod(paths = src, mode = "0777", use_umask = FALSE)
  file.copy(from = src, to = dst, overwrite = TRUE, recursive = TRUE, copy.mode = TRUE, copy.date = TRUE)
})
```

**Comment by hutch3232** [comment]
There actually isn't an error message, it's just that maybe this configuration option isn't being picked up (or I'm doing something wrong)? I just added some `cat`s so that I could see if it is being used:
```r
getOption("renv.config.copy.method")
function (src, dst) 
{
    cat("copying ", src, " to ", dst, "\n")
    Sys.chmod(paths = src, mode = "0777", use_umask = FALSE)
    cat("mode is ", file.mode(src), "\n")
    file.copy(from = src, to = dst, overwrite = TRUE, recursive = TRUE, 
        copy.mode = TRUE, copy.date = TRUE)
}
```

Then I installed the `mlr3` package and the `cat` messages never showed up:
```r
renv::install("mlr3")
```

The resulting files were still in my default mode, not 777 as expected.

**Comment by kevinushey** [comment]
Thanks @hutch3232 -- I've made those changes in https://github.com/rstudio/renv/commit/55d022f0cccfa7809cd13bb06119b71436084698, alongside a way to register a general callback function be run after a package is copied into the cache. Let me know if that seems like a reasonable way forward.

**Comment by hutch3232** [comment]
This is amazing, thanks for adding!! I have an observation from some initial testing I'm doing. (I tried to include a screenshot but GitHub is not letting me).

When you install a package it build out this structure (as you know):

- cache
  ...
  - pkg
    - version
      - hash
        - pkg # here
          - all contents

I'm finding that `RENV_CACHE_MODE` successfully updates the mode for everything at and below "here". I wonder if it'd be possible to get the three directories above as well? That could be tough for the cases where a different user created those. Maybe I can address this with the callback functionality you added.

I'll follow-up after some more testing. Thanks again!

**Comment by hutch3232** [comment]
hey @kevinushey I wanted to follow-up to get your thoughts on my comment above. Essentially - would it make sense for the `RENV_CACHE_MODE` and `RENV_CACHE_USER` to actually make the change three directories "up" and then "force" it?

If my understanding is correct, even if someone uses `RENV_CACHE_MODE` with 777, when they install a package (assume no other versions exist yet) it will still be locked above (without this change), so others can't install additional versions.

**Comment by kevinushey** [comment]
@hutch3232 let me know if the changes in https://github.com/rstudio/renv/commit/0c7455a607fa70d3f1c97494018f36d835f36323 give you what you need.

**Comment by hutch3232** [comment]
Thank you for your help with this! I think it is close, but I'm encountering a problem. When it forces `chmod` it doesn't error out (on `system2`) but it does record a nonzero exit code (1). 

https://github.com/rstudio/renv/blob/f9cc3e0ec2f4eb0c1a729fa41f794c71c92f96e5/R/system.R#L49

Which then causes `renv_system_exec` to throw an error. This seems like a relevant question: https://unix.stackexchange.com/questions/118217/chmod-silent-mode-how-force-exit-code-0-in-spite-of-error

I'm thinking you wouldn't want to change `renv_system_exec`, but maybe `|| true` could be added to `args`?

To summarize - when I tried installing a new package this worked great, permissions were opened as I expected. When I tried to install a new version for a package that someone else initially installed, `renv` threw an error:

```r
renv::install("gbm")
Retrieving '.../gbm_2.1.8.tar.gz' ...
	OK [downloaded 433.9 Kb in 1.3 secs]
Installing gbm [2.1.8] ...
	OK [built from source]
Moving gbm [2.1.8] into the cache ...
Error: error chmoding cached package [error code 1]
Traceback (most recent calls last):
11: renv::install("gbm")
10: renv_install_impl(records)
 9: renv_install_staged(records)
 8: renv_install_default(records)
 7: handler(package, renv_install_package(record))
 6: renv_install_package(record)
 5: renv_cache_synchronize(record, linkable = linkable)
 4: renv_cache_synchronize_impl(cachePath, record, linkable, path)
 3: renv_system_exec(command = "chmod", args = c("-Rf", renv_shell_quote(mode), 
        renv_shell_path(parent)), action = "chmoding cached package", 
        quiet = TRUE)
 2: stopf(fmt, action, status)
 1: stop(sprintf(fmt, ...), call. = call.)
```

**Comment by kevinushey** [comment]
Let me take a look... however, isn't the fact that `chmod` is failing here a concern?

**Comment by hutch3232** [comment]
Good question, I should have clarified that. Basically the `-f` silences the errors (since it's possible that `chmod` is being run on another owner's directories). So it appears to be silent, but still is returning non-zero exit status due to "operation not permitted" (changing someone else' files' modes). In this case, I was hoping with `-f` it would just ignore the fact that I was getting errors from `chmod`ing others' files. 

A possibly better way would be to use `find` to identify files that "I" own, and only `chmod` those?

Does that clear it up?

**Comment by hutch3232** [comment]
Just tested the latest commit [f01698e](https://github.com/rstudio/renv/commit/f01698e541237cbf3f59ad041512de66f67b0e11) and it is working great, thank you! Your solution using `success` is better than my suggestion of `|| true` too. Nice!

**Comment by hutch3232** [comment]
Hi @kevinushey, I have been using the `RENV_CACHE_MODE` feature extensively since you added it and it is working great. Thank you! I had a related question/idea: could we also change the mode of the source files as they're saved into the source/repository directory based on this environmental variable? I've found that in a multiuser/shared cache setup, users with default permissions of 0755 (for instance) can prevent new sources from being downloaded. Please let me know if you need an example or further explanation!

**Comment by kevinushey** [comment]
That's great, I'm glad to hear it!

> I had a related question/idea: could we also change the mode of the source files as they're saved into the source/repository directory based on this environmental variable?

This feels beyond the purview of `renv`, since it's not normally part of saving / loading of source files in a project. Is there an alternate way or place this could be handled? Could you change the default `umask` for users via `Sys.umask("0")`, perhaps set in the project `.Rprofile`?

Or, could you set up a file watcher for these projects that re-writes file permissions on save as required?

**Comment by hutch3232** [comment]
Thank you for the really fast response! I just realized my initial question was confusing. I meant to be referring to the tarballs that `renv` downloads into the source directory. It probably sounded like I was asking about regular development code files.

**Comment by kevinushey** [comment]
Ah! Yes, that's what I thought you meant. Adjusting permissions on the downloaded package tarballs definitely makes sense :-)

**Comment by kevinushey** [comment]
I made a change in https://github.com/rstudio/renv/commit/8d5015741717b6cfb8e4ea88b4e57f497cd78420; let me know if that looks reasonable.

**Comment by hutch3232** [comment]
Awesome, thank you! I will try it tomorrow when I'm on my computer but from reading it I am wondering if it would also open the package directory permission as well? I guess that would only need to occur the first time a package is installed (directory gets created with open permissions) then subsequent versions will be able to be written. Hopefully that makes sense. I think on the cache side you had set it up with a recursive `chmod` to accomplish that.

**Comment by hutch3232** [comment]
I had a chance to test this on my system. I think the solution is close, but it didn't quite work for me.

One thing worth noting is that I think when using `Sys.chmod` we should use the argument `use_mask = FALSE`. Otherwise it actually doesn't respect the value input to `mode` (assuming umask is set somewhere else like `.bashrc`).

Additionally, as I suspected in my prior message, it didn't change the permissions of the tarballs' parent directory. I think that is an important piece to include in the permission change.

On the cache side of things, you approached it like this:
https://github.com/rstudio/renv/blob/dc80ee9419f18bbf90126ae4430d319e1129c970/R/cache.R#L208-L219

I feel doing the same thing here on the source/tarball side would work too. I think the main difference would be that only one `dirname` is needed, since we only need to `chmod` (recursively) one level up from the tarball.

**Comment by kevinushey** [comment]
Thanks for following up! I'll take a look.

**Comment by hutch3232** [comment]
I was able to test this just now and **tl;dr** it's working great!

I did the following two tests:
1. Install a new package that didn't yet exist in `/renv/source/repository` and the result was that it created a new directory with permissions set according to `RENV_CACHE_MODE` and also copied in the new tarball with correct permissions as well
2. Install a new package version where someone else already installed another version, so the directory already existed (but was writeable). In this case it added my new version with `RENV_CACHE_MODE` permissions and did not error when trying to `chmod` the directory.

**Comment by kevinushey** [comment]
renv 0.17.0 is now available on CRAN! Let me know if everything looks good on your end.

**Comment by hutch3232** [comment]
I just redid the same tests from before and everything is working great! Thanks so much for incorporating this feature!

**Comment by kevinushey** [comment]
Great news! Thanks for taking the time to confirm.
