### ISSUE TITLE
Build packages with vignettes on offline systems

### ISSUE THREAD

**Issue by ticarki** [rstudio/renv#989]
We started to use renv for versioning on our offline system, with multiple versioned self-hosted R package repositories (CRAN, gitlab, bioconductor, etc.) on RSPM.

According to #344 it is recommended to set the self-hosted cran repository via `RENV_CONFIG_REPOS_OVERRIDE`. However, that seems to not only overwrite repositories during [bootstrap ](https://github.com/rstudio/renv/blob/main/inst/resources/activate.R#L89)but also during R package [installation ](https://github.com/rstudio/renv/blob/main/R/install.R#L152)and thus does not work with multiple versioned self-hosted repositories. Using the `options('renv.repos.cran'=<cran repos>)` in the .Rprofile project file works perfectly for restoring the project. Renv correctely [bootstraps](https://github.com/rstudio/renv/blob/main/inst/resources/activate.R#L105) and installs packages using the checkpoints encoded in `renv.lock`.

## Problems

When developing R packages with vignettes, I am not able to build the source package with vignettes via the Rstudio IDE. Rstudio keeps trying to renv restore the session during the `- installing the package to build vignettes` step, even though I added all renv files/folders to `.Rbuildignore`. It seems to ignore the `options('renv.repos.cran'=<cran repos>)` but still tries to restore the project (session freezes, as it is a offline system). I tested both, `R CMD build ...` and `devtools::build()` via the IDE, both did not work. However, `devtools::buil()` in a project session works fine.

## Code snippets

**.Rprofile**
```{r}
options(renv.repos.cran ='<self-hosted cran>')
source("renv/activate.R")
```

**.Rbuildignore**
```{r}
^renv$
^renv\.lock$
^\.Rprofile$
```

**Bootstrap works fine**
```{r}
# Bootstrapping renv 0.15.4 --------------------------------------------------
* Downloading renv 0.15.4 ... OK (downloaded source)
* Installing renv 0.15.4 ... Done!
* Successfully installed and loaded renv 0.15.4.
* Project '~/r_package' loaded. [renv 0.15.4]
* The project library is out of sync with the lockfile.
* Use `renv::restore()` to install packages recorded in the lockfile.
```

**Building in the session after `renv::restore()`**
```{r}
> devtools::build()
✓  checking for file ‘/home/foo/r_package/DESCRIPTION’ ...
─  preparing ‘r_package’: (651ms)
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✓  creating vignettes (5m 17s)
─  checking for LF line-endings in source and make files and shell scripts (498ms)
─  checking for empty or unneeded directories
─  building r_package_0.0.1.tar.gz’
   
[1] "/home/foo/r_package_0.0.1.tar.gz"
```

**Rstudio > Build > Build Source Package**
```{r}
==> devtools::build()

✓  checking for file ‘/home/foo/r_package/DESCRIPTION’ ...
─  preparing ‘foo’: (635ms)
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
   # Bootstrapping renv 0.15.4 --------------------------------------------------
   Warning: unable to access index for repository https://cloud.r-project.org/src/contrib:
     cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES
```

Could you please help me with the correct setting for such a system, so that building via RStudio also works?

**Comment by kevinushey** [comment]
> Rstudio keeps trying to renv restore the session during the - installing the package to build vignettes step, even though I added all renv files/folders to .Rbuildignore.

I wonder if including the project `.Rprofile` in your `.Rbuildignore` would help? For example, an entry like:

```
^\.Rprofile$
```

RStudio should already be passing along the requisite library paths, so the active library paths (ie, the renv library) should still be used in each stage.

---

For posterity, RStudio is running the build step with the moral equivalent of:

```
R --vanilla -s -e "devtools::build()"
```

and so relevant R options (e.g. the package repositories) are not passed along to the R CMD build step, and they're also not passed along when building vignettes. (This also implies the project `.Rprofile` is not being sourced in that sub-process either, but I guess it is being picked up when R launches the sub-process to build vignettes.)

You could also try setting the environment variable `R_PROFILE_USER` to an empty or non-existent value; e.g.

```
Sys.setenv(R_PROFILE_USER = "<disabled>")
```

and then running the build. R should see that environment variable and forego sourcing the project profile in that case. That might have other unintended side-effects, though.
