### ISSUE TITLE
Setting the public RSPM as CRAN URL breaks MRAN

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#990]
Installation from MRAN fails if an URL to RStudio Package Manager is used as CRAN URL.

With the following script, openssl is downloaded from MRAN as `.tgz` :

```sh
#!/bin/sh

# run from the renv directory
R CMD INSTALL .
rm -rf test
mkdir test
cd test
R -q -e 'options(repos = "https://cloud.r-project.org/"); renv::init()'
R -q -e 'renv::snapshot()'
R -q -e 'renv::purge("openssl")'
R -q -e 'renv::install("openssl")'
```

Changing the URL to `https://packagemanager.rstudio.com/cran/2022-04-15` or even `https://packagemanager.rstudio.com/cran/latest` now gets the `.tar.gz` and attempts to build the package.

I tried older versions as far back as 0.10.0, with seemingly the same behavior. I remember seeing this working before.

We're using fixed-date snapshots to pin all packages to some consistent state. The snapshot is supposed to define the versions to be installed, but I'd still expect the binaries to be downloaded from MRAN.

This is on macOS M1, R 4.1.3 .

**Comment by kevinushey** [comment]
It looks like the MRAN database hasn't been synchronized in a while, so I probably need to do that to get the latest version of openssl.

**Comment by krlmlr** [comment]
Thanks. Is there a way to check the sanity of the MRAN database? Perhaps renv could print a warning in case of trouble?
