### ISSUE TITLE
partial restore()s

### ISSUE THREAD

**Issue by tjmahr** [rstudio/renv#991]
This is more of a question.

When I try a restore(), a package installation might fail and then all of the progress installing the packages is lost. For example, if I run restore() and 10 packages appear, 9 of them might successfully build and 1 will fail. But when I run restore() again, all 10 appear un-installed. (The successful packages are quick to reinstall because they are cached though.)

Is this the intended behavior of restore()? That it succeeds only when every package reinstalls successfully? (I don't care if it is. Just want to clarify.) If so, there a way to get a vector of package names from the lockfile, so I can bulk install() packages?

**Comment by kevinushey** [comment]
It is; by default, `renv::restore()` tries to be transactional (so that the library is mutated only if all packages can be successfully installed).

You can disable this behavior with:

```
options(renv.config.install.transactional = FALSE)
```

See https://rstudio.github.io/renv/reference/config.html#renv-config-install-transactional for more details.
