### ISSUE TITLE
renv should not infer `quarto` R requirement from the presence of `_quarto.yml`.

### ISSUE THREAD

**Issue by toph-allen** [rstudio/renv#995]
It looks like renv adds infers a dependency for the quarto R package if it finds `_quarto.yml` in the working directory. The presence of Quarto files shouldn't imply a Quarto dependency, since Quarto does its rendering outside of R, and the `quarto` R package is just an interface for scripting interactions with the Quarto binary.

There might be other dependencies to infer from a the `_quarto.yml`, so we probably want to leave the hook in place. Perhaps the only change needed here is to remove line 556.

https://github.com/rstudio/renv/blob/203d222e8d540f0ab29f251986fd47a3363907d7/R/dependencies.R#L235

https://github.com/rstudio/renv/blob/203d222e8d540f0ab29f251986fd47a3363907d7/R/dependencies.R#L554-L557

I don't think any changes is needed to the handling of `.qmd` files, only `_quarto.yml`.

It looks like `renv` does inspect at `.qmd` files like it does `.Rmd` files, but only to discover dependencies in code chunks and the YAML front matter. It doesn't look like it adds a `quarto` dependency if those files are discovered — I'd expect that to occur around here:

https://github.com/rstudio/renv/blob/203d222e8d540f0ab29f251986fd47a3363907d7/R/dependencies.R#L582

**Comment by kevinushey** [comment]
I've made the change re: `_quarto.yml`.

> It doesn't look like it adds a quarto dependency if those files are discovered — I'd expect that to occur around here:

Does this imply the `quarto` R package is required if one needs to render a Quarto document containing R code chunks? Or is the "quarto" package ultimately optional?

**Comment by aronatkins** [comment]
The `quarto` package is useful for folks who are writing some type of scripted automation around Quarto content. It is not needed by Quarto for rendering.

Quarto content may need rmarkdown / knitr when it contains executable R code chunks and shiny when using the Shiny runtime.
