### ISSUE TITLE
`renv::restore()`fails with private repo (hosted on github-organization site)

### ISSUE THREAD

**Issue by cathblatter** [rstudio/renv#996]
I tried to `renv::restore()` a project, but the command fails with this message: 
```
Retrieving 'https://api.github.com/repos/INS-Basel/swissNHQI/tarball/f2690ecfea94b4e35be7dbf8c482b95cb5330bf6' ...
Error: failed to retrieve 'https://api.github.com/repos/INS-Basel/swissNHQI/tarball/f2690ecfea94b4e35be7dbf8c482b95cb5330bf6' [error code 22]
In addition: Warning message:
curl: (22) The requested URL returned error: 404 
Traceback (most recent calls last):
8: renv::restore()
7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
6: retrieve(packages)
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_github(record)
2: renv_retrieve_package(record, url, path)
1: stop(status)
```
The repo in question is a private repo hosted on our github-organization (for which I have full admin access).

I tried to manually install the package:

`remotes::install_github("INS-Basel/swissNHQI")` which gives:

```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`INS-Basel`) and repo name (`swissNHQI`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

 while` pak::pak("INS-Basel/swissNHQI")` works like a charm. 

I also tried to pass the` auth_token `but this gives 
```
remotes::install_github("INS-Basel/swissNHQI", auth_token="<hidden>")

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2022-04-27 12:01:25 UTC
```

I can reproduce this issue with a private package on my personal account, too. Removing the private package from the `renv.lock`-file leads to` renv::restore()` working as expected.
 
I have trouble placing this observation, e.g. a problem of my gh-credentials? Or something with {remotes}? Or am I missing something? 

thanks for {renv} - made my analysis-life smoother many times!

```
R version 4.1.3 (2022-03-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.3 tools_4.1.3    renv_0.15.4    pak_0.2.1   
```

**Comment by kevinushey** [comment]
Is https://rstudio.github.io/renv/articles/renv.html#authentication helpful? If you haven't already, you may need to set `GITHUB_PAT` with an appropriate personal access token that can allow authentication with the private repository.

**Comment by cathblatter** [comment]
thanks @kevinushey for your pointer - following usethis's 2.0 release I removed the `GITHUB_PAT` from my `.Renviron` a while ago... now, following up this resource: https://usethis.r-lib.org/articles/git-credentials.html#what-about-the-remotes-and-pak-packages I realise why it failed with {remotes} but worked with {pak}...  thanks for helping me solve this!
